<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('ADD_STUDENT_REGISTER')); 
	echo $this->headTitle(''); 
	$frm = $this->frm;
?>	
<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
.image-box {
    text-align: center;
}
.image-box img {
    width: 165px;
    height: 185px;
}
.button_browse {
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 38px;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 38px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 165px;
    margin: 0 auto;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<form id="add_student" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit" enctype="multipart/form-data">			
			if(this.validate()) {	
				branch_id = dijit.byId('branch_id').get('value');
				if(branch_id==''){
					dijit.byId('branch_id').focus();
					return false;
				}
	    		loadingBlock();
				return true;
			} else {
				return false;
			}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-user-plus" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_STUDENT_REGISTER');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<!-- Tab Menu -->
	    	<div class="card-box">
	    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
		            <li class="nav-item active">
		                <a class="nav-link " data-toggle="tab" href="#panel21" role="tab"><i class="fa fa-user ml-2"></i> <?php echo $tr->translate("STUDENT_INFO");?></a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
		                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("PARENT_INFO");?>
		                </a>
		            </li>
					<li class="nav-item">
		                <a class="nav-link" data-toggle="tab" href="#panel23" role="tab">
		                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("OTHER_INFOMATION");?>
		                </a>
		            </li>
		        </ul>
		    </div>
		    <!--/. Tab Menu -->
		    <div class="col-md-12">
		        <!-- Tab panels -->
		        <div class="tab-content vertical">
			        <!--Panel 1-->
			        <div class="tab-pane fade in active" id="panel21" role="tabpanel">
			        	 <div class="card-box">
				        	<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDENT_INFO");?> 
				                   </label>
				                </div>
				                <div class="form-group">
					                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span> :</label>
					                <div class="col-md-7 col-sm-7 col-xs-12">
					                	<?php echo $frm->getElement("branch_id");?>
					                </div>
					             </div>
					             <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STUDENT_TYPE");?> <span class="required">*</span> :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("stu_denttype");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STUDENT_NAMEKHMER");?> <span class="required">*</span> :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("name_kh");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("Last Name");?> <span class="required">*</span> :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("last_name");?>
				                   </div>
				                </div>
				                 <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("First Name");?> <span class="required">*</span> :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("name_en");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SEX");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("sex");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NATION");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="nation" />
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NATIONALITY");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="studen_national" />
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DOB");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("date_of_birth");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PHONE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("phone");?>
				                   </div>
				                </div>
				            </div>
				            <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CURRENT_ADDRESS_POB");?> 
				                   	<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="AllRefresh();"/>
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("POB");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("pob");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NUMBER_HOME");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("home_note");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STREET");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("way_note");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CITY_PROVINCE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("student_province");?>
				                   </div>
				                </div>
				                 <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DISTRICT");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php //echo $frm->getElement("distric_note");?>
				                   		<input id="distric_note"  />
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("COMMUNE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php //echo $frm->getElement("commun_note");?>
				                   		<input id="commun_note"  />
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("VILLAGE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php //echo $frm->getElement("village_note");?>
				                   		<input id="village_note"  />
				                   </div>
				                </div>
				            </div>
				            <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("OTHER_INFOMATION");?> 
				                   </label>
				                </div>
				                <div class="form-group">
					                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"  style="line-height: 7.75;"><?php echo $tr->translate("IMAGE");?>
				                   </label>
				                  <div class="col-md-7 col-sm-7 col-xs-12">
				                    	<div class="account-image text-center">
											<div class="image-box">
												<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/no-profile.png';?>" alt=""  />
											</div>
											<div class="button_browse">
											<div id='preview'></div>	
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="photo" name="photo"  />
													<input type="hidden" name="uploaded" id="uploaded" />
											</div>
											<button type="button" style="padding-left: 20px;" onClick="setup()" class="btn btn-success btn-sm">បើក Camera</button>
										</div>
										
				                   </div>
				                </div>
				            </div>
			            </div>
			            <div class="card-box">
							<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDY_INFO");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label bold  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STUDENT_ID");?> <span class="required">*</span> :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("student_id");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GROUP");?> <span class="required">*</span> :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="group" />
				                   		</div>
				                   		<div class="col-md-3 col-sm-3 col-xs-12">
				                   			<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshGroup();"/>
				                   		</div>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CULTURE_LEVEL");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("calture");?>
				                   </div>
				                </div>  
						        <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ACADEMIC_YEAR");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="academic_year" />
				                   </div>
				                </div>  
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SESSION");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("session");?>
				                   </div>
				                </div>  
				            </div>
				            <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDY_INFO");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DEGREE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php //echo $frm->getElement("degree");?>
				                   		<input id="degree" />
				                   </div>
				                </div>  
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GRADE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="grade" />
									    <input class="fullside" dojoType="dijit.form.TextBox"  id="grade_fromgrouop" name="grade_fromgrouop" value="" type="hidden"  >
				                   </div>
				                </div>  
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ROOM_NAME");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php //echo $frm->getElement("room");?>
				                   		<input id="room" />
				                   </div>
				                </div>  
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("status");?>
				                   </div>
				                </div>  
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("REMARK");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   <?php echo $frm->getElement("remark");?>
				                   </div>
				                </div>  
				            </div>
				            <div class="col-md-4 col-sm-4 col-xs-12">
				            	<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-graduation-cap" aria-hidden="true"></i> <?php echo $tr->translate("SCHOLARSHIP");?></label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DISCOUNT_TYPE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   <?php echo $frm->getElement("discount_type");?>
				                   </div>
				                </div> 
				                
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SCHOLASHIP");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   <?php echo $frm->getElement("scholarship_amount");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FROM_DATE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   <?php echo $frm->getElement("scholarship_fromdate");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TO_DATE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   <?php echo $frm->getElement("scholarship_todate");?>
				                   </div>
				                </div> 
				            </div>
						</div>
			        </div>
			        <!--/.Panel 1-->
			        
			        <!--Panel 2-->
			        <div class="tab-pane fade in " id="panel22" role="tabpanel">
			        	 <div class="card-box">
				        	<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("FATHER_INFO");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FATHER_NAME");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("fa_name_en");?>
				                   </div>
				                </div> 
					      	   <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DOB");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("fa_dob");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NATIONALITY");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="fa_national" />
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("OCCUPATION");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="fa_job" />
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PHONE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		 <?php echo $frm->getElement("fa_phone");?>
				                   </div>
				                </div>
								<div class="form-group">
									<label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHOTO");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                    	<div class="account-image" style="margin:0;">
											<div class="image-box">
												<img id="father_wiew" src="<?php echo $this->baseUrl().'/images/no-profile.png';?>" alt=""  />
											</div>
											<div class="button_browse">
											<div id='preview'></div>	
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="father_photo" name="father_photo"  />
													<input type="hidden" name="uploaded" id="uploaded" />
											</div>
										</div>
				                   </div>
				                </div>
				             </div>
				             <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("MOTHER_INFO");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("MOTHER_NAME");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("mom_name_en");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DOB");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("mo_dob");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NATIONALITY");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="mom_nation" />
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("OCCUPATION");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="mo_job" />
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PHONE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("mon_phone");?>
				                   </div>
				                </div>
								<div class="form-group">
									<label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHOTO");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                    	<div class="account-image" style="margin:0;">
											<div class="image-box">
												<img id="mother_wiew" src="<?php echo $this->baseUrl().'/images/no-profile.png';?>" alt=""  />
											</div>
											<div class="button_browse">
											<div id='preview'></div>	
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="mother_photo" name="mother_photo"  />
													<input type="hidden" name="uploaded" id="uploaded" />
											</div>
										</div>
				                   </div>
				                </div>
								
				             </div>
				             <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("GUARDIAN_INFO");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NAME");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("guardian_name_en");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DOB");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("guardian_dob");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NATIONALITY");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="guardian_national" />
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("OCCUPATION");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="gu_job" />
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PHONE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("guardian_phone");?>
				                   </div>
				                </div>
								<div class="form-group">
									<label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHOTO");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                    	<div class="account-image" style="margin:0;">
											<div class="image-box">
												<img id="guardian_wiew" src="<?php echo $this->baseUrl().'/images/no-profile.png';?>" alt=""  />
											</div>
											<div class="button_browse">
											<div id='preview'></div>	
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="guardian_photo" name="guardian_photo"  />
													<input type="hidden" name="uploaded" id="uploaded" />
											</div>
										</div>
				                   </div>
				                </div>
				             </div>
				         </div>
			        </div>
			        <!--/.Panel 2-->
					
					<!--Panel 3-->
			        <div class="tab-pane fade in " id="panel23" role="tabpanel">
			        	 <div class="card-box">
				        	<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("OTHER_INFOMATION");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" >
										<?php echo $tr->translate("ENGLISH_LANGUAGE_LEVEL");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
										<input id="lang_level" />
				                   </div>
				                </div> 
					      	   <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FROM_SCHOOL");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("from_school");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("KNOW_BY");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="know_by" />
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SPONSER");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<?php echo $frm->getElement("sponser");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PHONE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		 <?php echo $frm->getElement("sponser_phone");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("BACCII_INFOMATION");?></label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DATE_BACCEXAM");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		 <?php echo $frm->getElement("date_baccexam");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SCOOL_BACCPROVINCE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		 <?php echo $frm->getElement("school_province");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CENTER_BACCEXAM");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		 <?php echo $frm->getElement("center_baccexam");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ROOM_BACCEXAM");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		 <?php echo $frm->getElement("room_baccexam");?>
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TABLE_BACCEXAM");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		 <?php echo $frm->getElement("table_baccexam");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GRADE_BACCEXAM");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		 <?php echo $frm->getElement("grade_baccexam");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SCORE_BACCEXAM");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		 <?php echo $frm->getElement("score_baccexam");?>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CERTIFICATE_BACCEXAM");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		 <?php echo $frm->getElement("certificate_baccexam");?>
				                   </div>
				                </div>     
				                 
				             </div>
							 <div class="col-md-8 col-sm-8 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("DOCUMENT_INFO");?> 
				                   </label>
				                </div>
								<div class="form-group">
									<div class="col-md-12 col-sm-12 col-xs-12">
										<table border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
											<tr id="head-title" class="head-td"  align="right" style="font-size:12px;"></tr>
										</table>
										<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
												iconClass="dijitIconEditProperty" onclick="addRow();" />
												
										<input type="hidden" id="identity" name="identity" />
										<input type="hidden" id="popup_index" name="popup_index" />
									</div>		
								</div>	
							 </div>
				         </div>
			        </div>
			        <!--/.Panel 3-->
			    </div>
			    <!--/. Tab panels -->
			</div>
			<div class="clearfix"></div>
		    <div class="card-box">
               	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               		<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" onclick="getStudentNo();"/>
               		<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
					<input type="submit" value="save_new" id="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
	    		</div>
	    	</div>
		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ObjectStore");

var language_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->lang_level));?> );
var job_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->occupation));?> );
var job_store1  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->occupation));?> );
var job_store2  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->occupation));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var knowby_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->know_by));?> );
var doctype_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->doc_type));?> );

var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

var room_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var degree_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: degree_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,
		id: "degree",
		name: "degree",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_DEGREE");?>",          
		onChange: function() {  
			getallGrade();
			getStudentNo()
		}
	}, "degree");
	
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete:false,                     
		required: true,                      
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
	    	group_id = dijit.byId('group').get('value');
	    	if(group_id==-1){
	    		dijit.byId('academic_year').set('readOnly',false);
	    		dijit.byId('calture').set('readOnly',false);
				dijit.byId('degree').set('readOnly',false);
				dijit.byId('grade').set('readOnly',false);
				dijit.byId('session').set('readOnly',false);
	    		window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/group/add";?>','_blank');
			  }else{
				  getInfoBygroup();
			  }
	    }
	}, "group");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                     
		id: "academic_year",
		name: "academic_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('academic_year').get('value');
		}
	}, "academic_year");
	
	new dijit.form.FilteringSelect({
	    queryExpr: "*${0}*",
		autoComplete:false,                     
		required: true,                        
	    id: "grade",
	    name: "grade",  
	    tabindex: "16",  
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
	    onChange: function() {  
	    	make_id = dijit.byId('grade').get('value');
	    }
	}, "grade");
	getallGrade();

	new dijit.form.FilteringSelect({
		store: job_store,
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: true,
	    id: "fa_job",
	    name: "fa_job",  
	    queryExpr: "*${0}*",
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_JOB");?>", 
	    onChange: function() {          
	   	fa_job = dijit.byId('fa_job').get('value');
	    if(fa_job==-1){
	     dijit.byId("save").attr("disabled",false);
	   	 dijit.byId("popup_dept2").show();
		   	dijit.byId('value_j').attr('value',1);
	     }
	    else {
	    }  
	   } 
	}, "fa_job");
	dijit.byId('fa_job').attr('value',0);
	
	new dijit.form.FilteringSelect({
		store: job_store,
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: true,              
	    id: "mo_job",
	    name: "mo_job",  
	    tabindex: "17",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_JOB");?>", 
	    onChange: function() {          
	   	mo_job = dijit.byId('mo_job').get('value');
	    if(mo_job==-1){
	     dijit.byId("save").attr("disabled",false);
	   	 dijit.byId("popup_dept2").show();
		   	dijit.byId('value_j').attr('value',2);
	     }
	    else {
	    }  
	   } 
	}, "mo_job");
	dijit.byId('mo_job').attr('value',0);

	new dijit.form.FilteringSelect({
		store: job_store,
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: true,                     
	    id: "gu_job",
	    name: "gu_job",  
	    tabindex: "17",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_JOB");?>", 
	    onChange: function() {          
	   	mo_job = dijit.byId('gu_job').get('value');
	    if(mo_job==-1){
	     dijit.byId("save").attr("disabled",false);
	   	 dijit.byId("popup_dept2").show();
		   	dijit.byId('value_j').attr('value',3);
	     }
	    else {
	    }  
	   } 
	}, "gu_job");
	dijit.byId('gu_job').attr('value',0);

	new dijit.form.FilteringSelect({
		store: nation_store,
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: true,
	    id: "nation",
	    name: "nation",  
	    queryExpr: "*${0}*",
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_NATION");?>", 
	    onChange: function() {          
	    nation = dijit.byId('nation').get('value');
	    if(nation==-1){
	     dijit.byId("save_nation").attr("disabled",false);
	   	 dijit.byId("popup_nation").show();
		   	dijit.byId('value_j').attr('value',1);
	     } else {
	    	nation = dijit.byId('nation').get('value');
			dijit.byId('studen_national').attr('value',nation);
	    }  
	   } 
	}, "nation");
	dijit.byId('nation').attr('value',0);

	new dijit.form.FilteringSelect({
		store: nation_store,
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: true,
	    id: "studen_national",
	    name: "studen_national",  
	    queryExpr: "*${0}*",
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_NATION");?>", 
	    onChange: function() {          
	   	stu_nation = dijit.byId('studen_national').get('value');
	    if(stu_nation==-1){
	     dijit.byId("save_nation").attr("disabled",false);
	   	 dijit.byId("popup_nation").show();
		   	dijit.byId('value_j').attr('value',2);
	     }
	    else {
	    }  
	   } 
	}, "studen_national");
	dijit.byId('studen_national').attr('value',0);

	new dijit.form.FilteringSelect({
		store: nation_store,
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: true,
	    id: "fa_national",
	    name: "fa_national",  
	    queryExpr: "*${0}*",
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_NATION");?>", 
	    onChange: function() {          
	    fa_nation = dijit.byId('fa_national').get('value');
	    if(fa_nation==-1){
	     dijit.byId("save_nation").attr("disabled",false);
	   	 dijit.byId("popup_nation").show();
		   	dijit.byId('value_j').attr('value',3);
	     } else {
	    	nation = dijit.byId('fa_national').get('value');
			dijit.byId('mom_nation').attr('value',nation);
			dijit.byId('guardian_national').attr('value',nation);
		    
	    }  
	   } 
	}, "fa_national");
	dijit.byId('fa_national').attr('value',0);

	new dijit.form.FilteringSelect({
		store: nation_store,
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: true,
	    id: "mom_nation",
	    name: "mom_nation",  
	    queryExpr: "*${0}*",
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_NATION");?>", 
	    onChange: function() {          
	    mom_nation = dijit.byId('mom_nation').get('value');
	    if(mom_nation==-1){
	     dijit.byId("save_nation").attr("disabled",false);
	   	 dijit.byId("popup_nation").show();
		   	dijit.byId('value_j').attr('value',4);
	     }
	    else {
	    }  
	   } 
	}, "mom_nation");
	dijit.byId('mom_nation').attr('value',0);

	new dijit.form.FilteringSelect({
		store: nation_store,
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: true,
	    id: "guardian_national",
	    name: "guardian_national",  
	    queryExpr: "*${0}*",
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_NATION");?>", 
	    onChange: function(){          
	   	gurdian_nation = dijit.byId('guardian_national').get('value');
	    if(gurdian_nation==-1){
	     dijit.byId("save_nation").attr("disabled",false);
	   	 dijit.byId("popup_nation").show();
		   	dijit.byId('value_j').attr('value',5);
	     }
	    else {
	    }  
	   } 
	}, "guardian_national");
	dijit.byId('guardian_national').attr('value',0);
	
	new dijit.form.FilteringSelect({
		store: language_store,
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                        
	    id: "lang_level",
	    name: "lang_level",  
	    tabindex: "17",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("ENGLISH_LANGUAGE_LEVEL");?>", 
	    onChange: function() {          
			lang_level = dijit.byId('lang_level').get('value');
			if(lang_level==-1){
				dijit.byId("popup_lang_level").show();
			}
	    } 
	}, "lang_level");
	
	new dijit.form.FilteringSelect({
		store: knowby_store,
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                        
	    id: "know_by",
	    name: "know_by",  
	    tabindex: "17",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT");?>", 
	    onChange: function() {          
	   	know_by = dijit.byId('know_by').get('value');
	    if(know_by==-1){
			dijit.byId("popup_know_by").show();
	    }
	   } 
	}, "know_by");
	
	new dijit.form.FilteringSelect({
		store: district_store,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "distric_note",
		id: "distric_note",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
			onChange: function() {
				distric_note = dijit.byId('distric_note').get('value');
				if(distric_note==-1){
					window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/district/add?rightclick=true";?>','_blank');
				}
					filterCommune();
			}  
		}, "distric_note");
		 
		new dijit.form.FilteringSelect({
		store: commun_note,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "commun_note",
		id: "commun_note",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់",	
			onChange: function() {
				commun_note = dijit.byId('commun_note').get('value');
				if(commun_note==-1){
					window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/commune/add?rightclick=true";?>','_blank');
				}
				else{
					filterVillage();
				}
	  }
		}, "commun_note");
		 
		new dijit.form.FilteringSelect({
		store: village_store,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "village_note",
		id: "village_note",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះភូមិ!",	
			onChange: function() {
				vill = dijit.byId('village_note').get('value');
				if(vill==-1){
					window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/village/add?rightclick=true";?>','_blank');
				}
			}
		}, "village_note");

		new dijit.form.FilteringSelect({
			store: room_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                     
			id: "room",
			name: "room",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ROOM");?>",          
			onChange: function() {  
				room = dijit.byId('room').get('value');
				if(room==-1){
					window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/room/add?rightclick=true";?>','_blank');
				}
			}
		}, "room");
		
		filterDistrict();
		dijit.byId('student_province').attr('value',12);
		getAllGroupByBranch();
		getStudentNo();
		oldRow();
		dijit.byId('nation').attr("value",1);
		dijit.byId('fa_national').attr("value",1);

		var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getRefreshGroup();
	    });
		 getRefreshGroup();	    
}); 
function AllRefresh(){
	loadingBlock();
	student_province = dijit.byId('student_province').get('value');
	if(student_province!=''){
		filterDistrict();
	}
	distric_note = dijit.byId('distric_note').get('value');
	if(distric_note!='' || distric_note!=-1){
		filterCommune();
	}
	commun_note = dijit.byId('commun_note').get('value');
	if(commun_note!='' || commun_note!=-1){
		filterVillage();
	}
	
}

url_getdistrict = '<?php echo $this->url(array('module'=>'global','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	student_province = dijit.byId('student_province').get('value');
	if(student_province==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': student_province
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('distric_note').set('store', district_store);
		    document.getElementsByClassName("overlay")[0].style.display="none";	
		},
		error: function(err) {
			alert(err);
		}
	});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'global','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('distric_note').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commun_note').set('store', commune_store);
		    document.getElementsByClassName("overlay")[0].style.display="none";	
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getvillage = '<?php echo $this->url(array('module'=>'global','controller'=>'village','action'=>'get-allvillage'));?>';
function filterVillage(){
	commune_id = dijit.byId('commun_note').get('value');
	if(commune_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getvillage,	
		content:{ 
			'commune_id': commune_id
		},
		handleAs:"json",
		load: function(data) {	
			village_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('village_note').set('store', village_store);
		    document.getElementsByClassName("overlay")[0].style.display="none";	
		},
		error: function(err) {
			alert(err);
		}
	});
}

var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store);   
				    dijit.byId('grade').set('value',dijit.byId('grade_fromgrouop').get('value'));
				},
				error: function(err) {
					alert(err);
				}
			});
	}
var url_getgroup = '<?php echo $this->url(array("module"=>"foundation","controller"=>"group","action"=>"getgroup"));?>';										
function getRefreshGroup(){
	loading();
	dijit.byId('group').reset();
	dijit.byId('room').reset();
	dijit.byId('grade').reset();
	dijit.byId('degree').reset();
	getAllGroupByBranch();
	getRefreshRoom();
	getRefreshItems();
	getAllAcademicByBranch();
	document.getElementsByClassName("overlay")[0].style.display="none";
	
	/*
	loading();
	dojo.xhrPost({
		url:url_getgroup,
		handleAs:"json",
		load: function(data) {
			group_store  = getDataStorefromJSON('id','name', data.group);
		    dijit.byId('group').set('store',group_store);  
		    degree_store  = getDataStorefromJSON('id','name', data.degree);
		    dijit.byId('degree').set('store',degree_store);  

		    room_store  = getDataStorefromJSON('id','name', data.room);
		    dijit.byId('room').set('store',room_store);  

		    
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
	*/
}

function getRefreshItems(){
	dijit.byId('degree').reset();   
	var url_getItems = '<?php echo $this->url(array("module"=>"global","controller"=>"degree","action"=>"refreshitems"));?>';										
	dojo.xhrPost({
		url: url_getItems,
		content:{
			'items_type':1
			},
		handleAs:"json",
		load: function(data) {
			degree_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('degree').set('store',degree_store);  
		   document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}

var url_getRoom = '<?php echo $this->url(array("module"=>"foundation","controller"=>"group","action"=>"getroom"));?>';										
function getRefreshRoom(){
	dijit.byId('room').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id == -1){
		return false;
	}
	dojo.xhrPost({
		url: url_getRoom,
		handleAs:"json",
		content:{
				'branch_id':branch_id
				},
		load: function(data) {
			room_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('room').set('store',room_store);  
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}

var url_getstuno = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-stu-no')); ?>';
function getStudentNo(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id=='' || dept_id==-1){return false;}
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){return false;}
	dojo.xhrPost({
		url:url_getstuno,
		content:{
			'dept_id':dept_id,
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			dijit.byId('student_id').attr('value',data);   
		},
		error: function(err) {
			alert(err);
		}
	});
}	

url_getacademic = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
	function getAllAcademicByBranch(){
		dijit.byId('academic_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('academic_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getacademic,
			content:{
				'branch_id':branch_id
				},
			handleAs:"json",
			load: function(data){
				academic_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('academic_year').set('store',academic_store);  
				
				dijit.byId('academic_year').attr("value","<?php echo $this->adv_search['academic_year']?>");
			},
			error: function(err) {
				alert(err);
			}
		});
	}

</script>

<style>
 @media (min-width: 1401px) and (max-width: 1601px){
	#mainTabContainer{
	width: 1400px !important;
   	 display: block;
	}
}
</style>
<script>
var url_add_lang = '<?php echo $this->url(array("module"=>"foundation","controller"=>"register","action"=>"add-langlevel")); ?>';
function addLanguage(){
	if(dijit.byId('frm_lang_level').validate()){	
		dojo.xhrPost({
			url:url_add_lang,
			form: dojo.byId("frm_lang_level"),
			handleAs:"json",
			load: function(data) {
			var Itemmake = { 
					 id: dijit.byId('title').get('value'),
					 name: dijit.byId('title').get('value')
				   };
		   addDataToSelectbox(dijit.byId('lang_level'), language_store, Itemmake, dijit.byId('title').get('value'));
		   dijit.byId('frm_lang_level').reset();
		   dijit.byId("popup_lang_level").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

var nation_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->nation));?> );
var nation_store1  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->nation));?> );
var nation_store2  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->nation));?> );
var nation_store3  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->nation));?> );
var nation_store4  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->nation));?> );
var url_add_nation = '<?php echo $this->url(array("module"=>"foundation","controller"=>"register","action"=>"add-nation")); ?>';
function addNationBy(){
	if(dijit.byId('frm_nation_kh').validate()){
	dijit.byId("save_nation").attr("disabled",true);
	type=dijit.byId('value_j').get('value');
	nation=dijit.byId('nation').get('value');
	studen_national=dijit.byId('studen_national').get('value');
	fa_national=dijit.byId('fa_national').get('value');
	mom_nation=dijit.byId('mom_nation').get('value');
	guardian_national=dijit.byId('guardian_national').get('value');
	dojo.xhrPost({
		url:url_add_nation,
		form: dojo.byId("frm_nation_kh"),
		handleAs:"json",
		load: function(data) {
			var Itemmake = { 
			    		id: data,
				        name: dijit.byId('title_kh').get('value')
				   };
		if(type==1){	   
	 		addDataToSelectbox(dijit.byId('nation'), nation_store, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('studen_national'), nation_store1, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('fa_national'), nation_store2, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('mom_nation'), nation_store3, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('guardian_national'), nation_store4, Itemmake, data);
			//dijit.byId('guardian_national').attr('value',fa_job);
			//dijit.byId('studen_national').attr('value',mo_job);
			//dijit.byId('mom_nation').attr('value',fa_job);
			//dijit.byId('fa_national').attr('value',fa_job);
		}else if(type==2){
			addDataToSelectbox(dijit.byId('nation'), nation_store, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('studen_national'), nation_store1, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('fa_national'), nation_store2, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('mom_nation'), nation_store3, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('guardian_national'), nation_store4, Itemmake, data);
	 		//dijit.byId('nation').attr('value',mo_job);
			//dijit.byId('guardian_national').attr('value',fa_job);
			//dijit.byId('mom_nation').attr('value',fa_job);
			//byId('fa_national').attr('value',fa_job);
		}else if(type==3){
			addDataToSelectbox(dijit.byId('nation'), nation_store, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('studen_national'), nation_store1, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('fa_national'), nation_store2, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('mom_nation'), nation_store3, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('guardian_national'), nation_store4, Itemmake, data);
	 		//dijit.byId('nation').attr('value',mo_job);
			//dijit.byId('guardian_national').attr('value',fa_job);
			//dijit.byId('studen_national').attr('value',mo_job);
			//dijit.byId('mom_nation').attr('value',fa_job);
		}else if(type==4){
			addDataToSelectbox(dijit.byId('nation'), nation_store, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('studen_national'), nation_store1, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('fa_national'), nation_store2, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('mom_nation'), nation_store3, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('guardian_national'), nation_store4, Itemmake, data);
	 		//dijit.byId('nation').attr('value',mo_job);
			//dijit.byId('guardian_national').attr('value',fa_job);
			//dijit.byId('studen_national').attr('value',mo_job);
			//dijit.byId('fa_national').attr('value',fa_job);
		}else if(type==5){
			addDataToSelectbox(dijit.byId('nation'), nation_store, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('studen_national'), nation_store1, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('fa_national'), nation_store2, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('mom_nation'), nation_store3, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('guardian_national'), nation_store4, Itemmake, data);
			//dijit.byId('nation').attr('value',mo_job);
			//dijit.byId('studen_national').attr('value',mo_job);
			//dijit.byId('mom_nation').attr('value',fa_job);
			//dijit.byId('fa_national').attr('value',fa_job);
		}
	    dijit.byId('frm_nation_kh').reset();
	    dijit.byId("popup_nation").hide();
		},
		error: function(err) {
			alert(err);
		}
	});
	}
}
var url_add_know_by = '<?php echo $this->url(array("module"=>"foundation","controller"=>"register","action"=>"add-knowby")); ?>';
function addKnowBy(){
	if(dijit.byId('frm_know_by').validate()){
		dojo.xhrPost({
			url:url_add_know_by,
			form: dojo.byId("frm_know_by"),
			handleAs:"json",
			load: function(data) {
			var Itemmake = { 
					 id: dijit.byId('title_know_by').get('value'),
					 name: dijit.byId('title_know_by').get('value')
				   };
		   addDataToSelectbox(dijit.byId('know_by'), knowby_store, Itemmake, dijit.byId('title_know_by').get('value'));
		   dijit.byId('frm_know_by').reset();
		   dijit.byId("popup_know_by").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}	
}

var url_add_doc_type = '<?php echo $this->url(array("module"=>"foundation","controller"=>"register","action"=>"add-doctype")); ?>';
function addDocType(){
	if(dijit.byId('frm_doc_type').validate()){
		dijit.byId("save_doc_type").attr("disabled",true);
		dojo.xhrPost({
			url:url_add_doc_type,
			form: dojo.byId("frm_doc_type"),
			handleAs:"json",
			load: function(data) {
			var Itemmake = { 
					 id: dijit.byId('title_doc_type').get('value'),
					 name: dijit.byId('title_doc_type').get('value')
				   };
			index = $("#popup_index").val();	   
		   addDataToSelectbox(dijit.byId('document_type_'+index), doctype_store, Itemmake, dijit.byId('title_doc_type').get('value'));
		   dijit.byId('frm_doc_type').reset();
		   dijit.byId("popup_doc_type").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

function hideDialog() {		
	dijit.byId("popup_lang_level").hide();
}
function hideDialog1() {		
	dijit.byId("popup_dept2").hide();
}
function hideDialog2() {		
	dijit.byId("popup_know_by").hide();
}
function hideDialog3() {		
	dijit.byId("popup_doc_type").hide();
}
function hideDialog4() {
	dijit.byId("popup_nation").hide();
}

var url_add_job = '<?php echo $this->url(array("module"=>"foundation","controller"=>"register","action"=>"add-job")); ?>';
function addJob(){
	if(dijit.byId('frm_add_tran1').validate()){
	dijit.byId("save").attr("disabled",true);
	type=dijit.byId('value_j').get('value');
	fa_job=dijit.byId('fa_job').get('value');
	mo_job=dijit.byId('mo_job').get('value');
	gu_job=dijit.byId('gu_job').get('value');
	dojo.xhrPost({
		url:url_add_job,
		form: dojo.byId("frm_add_tran1"),
		handleAs:"json",
		load: function(data) {
			var Itemmake = { 
			    		id: data,
				        name: dijit.byId('occu_name').get('value')
				   };
		if(type==1){	   
	 		addDataToSelectbox(dijit.byId('fa_job'), job_store, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('mo_job'), job_store1, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('gu_job'), job_store2, Itemmake, data);
			dijit.byId('mo_job').attr('value',mo_job);
			dijit.byId('gu_job').attr('value',gu_job);
		}else if(type==2){
			addDataToSelectbox(dijit.byId('fa_job'), job_store, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('mo_job'), job_store1, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('gu_job'), job_store2, Itemmake, data);
			dijit.byId('fa_job').attr('value',fa_job);
			dijit.byId('gu_job').attr('value',gu_job);
		}else if(type==3){
			addDataToSelectbox(dijit.byId('fa_job'), job_store, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('mo_job'), job_store1, Itemmake, data);
	 		addDataToSelectbox(dijit.byId('gu_job'), job_store2, Itemmake, data);
			dijit.byId('mo_job').attr('value',mo_job);
			dijit.byId('fa_job').attr('value',fa_job);
		}
	    dijit.byId('frm_add_tran1').reset();
	    dijit.byId("popup_dept2").hide();
		},
		error: function(err) {
			alert(err);
		}
	});
	}
}
</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:415px;" align="center" data-dojo-props="title:'Camera'" id="showcamera" >
		<div id="my_camera"></div>
		<button type="button" onClick="take_snapshot()" class="btn btn-success btn-sm">ចុចថត</button>
	</div>
</div>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;" id="popup_dept2" >
		<form style="background-color: buttonface;" id='frm_add_tran1' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate('ADD_OCCUPATION');?></legend>
						<table style="margin: 0 auto; width: 100%;  padding:10px; line-height: 35px;" cellspacing="7" >
							<tr>
								<td><?php echo $tr->translate('TITLE');?></td>
								<td><input dojoType="dijit.form.ValidationTextBox" required="true"  class="fullside" id="occu_name" name="occu_name" value="" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate('STATUS');?></td>
								<td><select name="status_j" id="status_j" dojoType="dijit.form.FilteringSelect"   class="fullside">
	    								<option value="1" >Active</option>
	    								<option value="0" >Deactive</option>
									</select>
								</td>
							</tr>
							<input type="hidden" name="" id="value_j" dojoType="dijit.form.TextBox" />
							<tr>
								<td colspan="4" align="center">
									<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button" 
									​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
									<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addJob();"/>
								</td>
							</tr>
						</table>
				</fieldset>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;" id="popup_nation" >
		<form style="background-color: buttonface;" id='frm_nation_kh' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_NATION');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px; line-height:35px;" cellspacing="7" >
								<tr>
								<td><?php echo $tr->translate('KH_NAME');?></td>
								<td><input dojoType="dijit.form.ValidationTextBox" required="true"  class="fullside" id="title_kh" name="title_kh" value="" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate('EN_NAME');?></td>
								<td><input dojoType="dijit.form.ValidationTextBox" required="true"  class="fullside" id="title_en" name="title_en" value="" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate('STATUS');?></td>
								<td><select name="status_na" id="status_na" dojoType="dijit.form.FilteringSelect"   class="fullside">
	    								<option value="1" >Active</option>
	    								<option value="0" >Deactive</option>
									</select>
								</td>
							</tr>
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" id="hide_nation" name="hide_nation" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog4();"/>
										<input type="button" value="save" label="SAVE" id="save_nation" name="save_nation" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNationBy();"/>
									</td>
								</tr>
							</table>
						</fieldset>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;" id="popup_lang_level" >
		<form style="background-color: buttonface;" id='frm_lang_level' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate('ADD_LANGUAGE_LEVEL');?></legend>
						<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
							<tr>
								<td><?php echo $tr->translate('TITLE');?></td>
								<td><input dojoType="dijit.form.ValidationTextBox" required="true"  class="fullside" id="title" name="title" value="" type="text"></td>
							</tr>
							
							<tr>
								<td colspan="4" align="center">
									<input type="button" value="ចាកចេញ" label="Close" id="hide" name="hide" dojoType="dijit.form.Button" 
									​ ​​iconClass="dijitIconUndo" onclick="hideDialog();"/>
									<input type="button" value="save" label="SAVE" id="save_lang" name="save_lang" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addLanguage();"/>
								</td>
							</tr>
						</table>
				</fieldset>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;" id="popup_know_by" >
		<form style="background-color: buttonface;" id='frm_know_by' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate('KNOW_BY');?></legend>
						<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
							<tr>
								<td><?php echo $tr->translate('TITLE');?></td>
								<td><input dojoType="dijit.form.ValidationTextBox" required="true"  class="fullside" id="title_know_by" name="title_know_by" value="" type="text"></td>
							</tr>
							
							<tr>
								<td colspan="4" align="center">
									<input type="button" value="ចាកចេញ" label="Close" id="hide_know_by" name="hide_know_by" dojoType="dijit.form.Button" 
									​ ​​iconClass="dijitIconUndo" onclick="hideDialog2();"/>
									<input type="button" value="save" label="SAVE" id="save_know_by" name="save_know_by" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addKnowBy();"/>
								</td>
							</tr>
						</table>
				</fieldset>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;" id="popup_doc_type" >
		<form style="background-color: buttonface;" id='frm_doc_type' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('DOCUMENT_TYPE');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('TITLE');?></td>
									<td><input dojoType="dijit.form.ValidationTextBox" required="true"  class="fullside" id="title_doc_type" name="title_doc_type" value="" type="text"></td>
								</tr>
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" id="hide_doc_type" name="hide_doc_type" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog3();"/>
										<input type="button" value="save" label="SAVE" id="save_doc_type" name="save_doc_type" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addDocType();"/>
									</td>
								</tr>
							</table>
						</fieldset>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>

<script type="text/javascript">
	
Webcam.set({
	width: 320,
	height: 240,
	image_format: 'jpeg',
	jpeg_quality: 90
});
function setup() {
	dijit.byId("showcamera").show();	
	Webcam.reset();
	Webcam.attach('#my_camera' );
}
var shutter = new Audio();
shutter.autoplay = false;
shutter.src = navigator.userAgent.match(/Firefox/) ? '<?php echo $this->baseUrl();?>/webcam/shutter.ogg' : '<?php echo $this->baseUrl();?>/webcam/shutter.mp3';
function take_snapshot() {
	// play sound effect
	shutter.play();
	// take snapshot and get image data
	Webcam.snap( function(data_uri) {
		  $('#profile_wiew').attr('src',data_uri);
		  SaveSnap();
	} );
}
function SaveSnap(){
    var url_upload = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'webcam')); ?>';	

    var base64image = document.getElementById("profile_wiew").src;
    Webcam.upload( base64image, url_upload, function(code, text) {
    	  console.log('Save successfully');
    	  //console.log(text);
    	  uploadcomplete(event);
    	 });
}
function uploadcomplete(event){
    var image_return=event.target.responseText;
    $("#uploaded").val(image_return);
}
	function getInfoBygroup(){
		url_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getgroupinfo'));?>';
		group = dijit.byId('group').get('value');
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			dijit.byId('group').attr('value','');
			dijit.byId('branch_id').focus();
			return false;
		}
		if(group=='' || group==-1){
			dijit.byId('academic_year').set('readOnly',false);
			dijit.byId('degree').set('readOnly',false);
			dijit.byId('calture').set('readOnly',false);
			dijit.byId('grade').set('readOnly',false);
			dijit.byId('session').set('readOnly',false);
			dijit.byId('group').focus();
			//alert("Please Select Group");
			return false;
		}
		dojo.xhrPost({
			url:url_group,	
			content:{ 
				'group_id': group
			},
			handleAs:"json",
			load: function(data) {
				
				dijit.byId('academic_year').set('value',data.academic_year);
				dijit.byId('academic_year').set('readOnly',true);
				dijit.byId('degree').set('value',data.degree);
				dijit.byId('degree').set('readOnly',true);
				dijit.byId('calture').set('value',data.calture);
				dijit.byId('calture').set('readOnly',true);
				dijit.byId('grade').set('value',data.grade);
				dijit.byId('grade').set('readOnly',true);
				dijit.byId('grade_fromgrouop').set('value',data.grade);
				dijit.byId('session').set('value',data.session);
				dijit.byId('session').set('readOnly',true);
				dijit.byId('room').set('value',data.room_id);
				getStudentNo();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile_wiew').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    var maxSize = 0;
    $("#photo").change(function(){
        readURL(this);
    });
	function loading(){
	    document.getElementsByClassName("overlay")[0].style.display="block";
	}
	
var template = '';
var service = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
date_format = '"dd/MM/yyyy"';
	function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("DOCUMENT_TYPE");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("DATE_GIVE");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("RECEIVED");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("DATE_GIVE_BACK");?></th>';
			temp+='<th><?php echo $tr->translate("NOTE");?></th>';
			temp+='<th><?php echo $tr->translate("ATTACHMENT");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
			}
			template+='<td width="5%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="5%" align="center">'+no+'</td>';
			template+='<td width="25%"><select class="fullside" name="document_type_'+col+'" id="document_type_'+col+'" value="0" onChange="popupDocType('+col+');" dojoType="dijit.form.FilteringSelect" >';	
				<?php if(!empty($this->doc_type)){foreach($this->doc_type as $doc_type){?>
					template+='<option value="'+'<?php echo $doc_type['id']?>'+'"><?php echo $doc_type['name'];?></option>';
				<?php }}?>
			template+='</select></td>';
			template+='<td width="15%"><input type="text" class="fullside" name="date_give_'+col+'" id="date_give_'+col+'" value="now" dojoType="dijit.form.DateTextBox" constraints='+'{datePattern:"dd/MM/yyyy"}'+' /></td>';
			template+='<td width="15%"><select class="fullside" name="is_receive_'+col+'" id="is_receive_'+col+'" dojoType="dijit.form.FilteringSelect" ><option value="1"><?php echo $tr->translate("RECEIVED");?></option><option value="0"><?php echo $tr->translate("NOT_RECEIVED");?></option></select></td>';
			template+='<td width="15%"><input type="text" class="fullside" name="date_end_'+col+'" id="date_end_'+col+'" value="now" dojoType="dijit.form.DateTextBox" constraints='+'{datePattern:"dd/MM/yyyy"}'+' /></td>';
			template+='<td width="25%"><input type="text" class="fullside" name="note_'+col+'" id="note_'+col+'" dojoType="dijit.form.TextBox" placeholder="<?php echo $tr->translate("NOTE");?>" /></td>';
			template+='<td width="15%">';
				template+='<div id="attachment'+col+'" class="form-group" style=" margin-bottom: 5px !important;">';
					template+='<div class="input-group input-file" name="attachment'+col+'">';
						template+='<input type="text" class="form-control" placeholder="<?php echo $tr->translate('CHOOSE_FILE');?>..." value="" />';
					template+='</div>';
				template+='</div> <div class="clearfix"></div>';
			template+='</td>';
		
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});

		bs_input_file();
	}

	function oldRow() {
		<?php if(!empty($this->doc)){ //echo '111111';exit();
			foreach($this->doc as $row){ 
		?>
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("DOCUMENT_TYPE");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("DATE_GIVE");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("RECEIVED");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("DATE_GIVE_BACK");?></th>';
			temp+='<th><?php echo $tr->translate("NOTE");?></th>';
			temp+='<th><?php echo $tr->translate("ATTACHMENT");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
			}
			template+='<td width="5%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="5%" align="center">'+no+'</td>';
			template+='<td width="25%"><label style="padding: 1px 1px;font-weight:normal;"><?php echo $row['name']?></label><input type="hidden" class="fullside" name="document_type_'+col+'" id="document_type_'+col+'" dojoType="dijit.form.TextBox" value="<?php echo $row['id']?>" />';
			template+='</td>';
			template+='<td width="15%"><input type="text" class="fullside" name="date_give_'+col+'" id="date_give_'+col+'" value="now" dojoType="dijit.form.DateTextBox" constraints='+'{datePattern:"dd/MM/yyyy"}'+' /></td>';
			template+='<td width="15%"><select class="fullside" name="is_receive_'+col+'" id="is_receive_'+col+'" dojoType="dijit.form.FilteringSelect" ><option value="1"><?php echo $tr->translate("RECEIVED");?></option><option value="0"><?php echo $tr->translate("NOT_RECEIVED");?></option></select></td>';
			template+='<td width="15%"><input type="text" class="fullside" name="date_end_'+col+'" id="date_end_'+col+'" value="now" dojoType="dijit.form.DateTextBox" constraints='+'{datePattern:"dd/MM/yyyy"}'+' /></td>';
			template+='<td width="25%"><input type="text" class="fullside" name="note_'+col+'" id="note_'+col+'" dojoType="dijit.form.TextBox" placeholder="<?php echo $tr->translate("NOTE");?>" /></td>';
			template+='<td width="10%">';
				template+='<div id="attachment'+col+'" class="form-group" style=" margin-bottom: 5px !important;">';
					template+='<div class="input-group input-file" name="attachment'+col+'">';
						template+='<input type="text" class="form-control" placeholder="<?php echo $tr->translate('CHOOSE_FILE');?>..." value="" />';
					template+='</div>';
				template+='</div> <div class="clearfix"></div>';
			template+='</td>';
			
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});

		bs_input_file();
		<?php }}?>
	}
	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++){
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
	function popupDocType(index){
		id = dijit.byId('document_type_'+index).get('value');
		dijit.byId("save_doc_type").attr("disabled",false);
		if(id==-1){
			$('#popup_index').val(index);
			dijit.byId("popup_doc_type").show();
		}
		
	}
	
	url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
	function getAllGroupByBranch(){
		dijit.byId('student_id').set('value',"");
		dijit.byId('group').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('group').set('store',group_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getgroup,
			content:{
				'branch_id':branch_id
				},
			handleAs:"json",
			load: function(data) {
			    group_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('group').set('store',group_store);   
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	
	function readURLguardian(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#guardian_wiew').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    var maxSize = 0;
    $("#guardian_photo").change(function(){
        readURLguardian(this);
    });
	
	
	function readURLmother(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#mother_wiew').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    var maxSize = 0;
    $("#mother_photo").change(function(){
        readURLmother(this);
    });
	
	function readURLfather(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#father_wiew').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    var maxSize = 0;
    $("#father_photo").change(function(){
        readURLfather(this);
    });

    function bs_input_file() {
    	$(".input-file").before(
    		function() {
    		if ( ! $(this).prev().hasClass('input-ghost') ) {
    			var element = $("<input  type='file' accept='.xlsx,.xls,image/*,.doc, .docx,.txt,.pdf' class='input-ghost' style='visibility:hidden; height:0'>");
    			element.attr("name",$(this).attr("name"));
    			element.change(function(){
    				element.next(element).find('input').val((element.val()).split('\\').pop());
    			});
    			$(this).find("button.btn-choose").click(function(){
    				element.click();
    			});
    			
    			$(this).find('input').css("cursor","pointer");
    			$(this).find('input').mousedown(function() {
    				$(this).parents('.input-file').prev().click();
    				return false;
    			});
    			return element;
    		}
    	}
    	);
    }
</script>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("/psst/trunk/public/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>