<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('ADD_STUDENT_REGISTER')); 
	echo $this->headTitle(''); 
	$photo= $this->frm_techer;
?>	
<style>
.image-box {
    text-align: center;
}
.image-box img {
    width: 120px;
    height: 130px;
}
.button_browse {
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 38px;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 38px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 120px;
    margin: 0 auto;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<form id="add_student" dojoType="dijit.form.Form" method="post" action=" " enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				dijit.byId('save_close').set('disabled',true);	
				return true;
			}else {
				return false;
			}
			</script>
			
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-files-o" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_STUDENT_REGISTER');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<!-- Tab Menu -->
	    	<div class="card-box">
	    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
		            <li class="nav-item active">
		                <a class="nav-link " data-toggle="tab" href="#panel21" role="tab"><i class="fa fa-user ml-2"></i> <?php echo $tr->translate("STUDENT_INFO");?></a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
		                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("PARENT_INFO");?>
		                </a>
		            </li>
		        </ul>
		    </div>
		    <!--/. Tab Menu -->
		    
		     <div class="col-md-12">
		        <!-- Tab panels -->
		        <div class="tab-content vertical">
			        <!--Panel 1-->
			        <div class="tab-pane fade in active" id="panel21" role="tabpanel">
			        	 <div class="card-box">
				        	<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDENT_INFO");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_KH");?> <span class="required">*</span> :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  tabindex="2" dojoType="dijit.form.ValidationTextBox"  id="name_kh" name="name_kh" value="<?php echo $this->rs['stu_khname'];?>" type="text"  >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_EN");?> <span class="required">*</span> :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" tabindex="2" required="1" dojoType="dijit.form.ValidationTextBox"  id="name_en" name="name_en" value="<?php echo $this->rs['stu_enname'];?>" type="text"  >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<select class="fullside"  tabindex="3" name="sex" id="sex" dojoType="dijit.form.FilteringSelect" >
											<option value="1" <?php if($this->rs['sex']==1){{ echo "selected='selected'"; }} ?> ><?php echo $tr->translate("MALE")?></option>
											<option value="2"<?php if($this->rs['sex']==2){{ echo "selected='selected'"; }} ?> ><?php echo $tr->translate("FEMALE")?></option>
										</select>
				                   </div>
				                </div>
				                
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" tabindex="4" dojoType="dijit.form.TextBox"  id="studen_national" name="studen_national" value="<?php echo $this->rs['nationality'];?>" type="text" >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" tabindex="4" dojoType="dijit.form.TextBox"  id="phone" name="phone" value="<?php echo $this->rs['tel'];?>" type="text" >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" tabindex="5"  name="date_of_birth" id="date_of_birth" dojoType="dijit.form.DateTextBox"  value="<?php echo $this->rs['dob'];?>" type="text"/>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("POB");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<textarea class="fullside"  style=" height: 60px !important;" tabindex="20" id="pob" name="pob"  ><?php echo $this->rs['pob'];?></textarea>
				                   </div>
				                </div>
				            </div>
				            <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CURRENT_ADDRESS");?> 
				                   </label>
				                </div>
				                
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("HOME");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input  class="fullside" tabindex="9" dojoType="dijit.form.TextBox"  id="home_note" name="home_note" value="<?php echo $this->rs['home_num'];?>" >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STREET");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input  class="fullside" tabindex="10" dojoType="dijit.form.TextBox"  id="way_note" name="way_note" value="<?php echo $this->rs['street_num'];?>" type="text" >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("VILLAGE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" tabindex="11" dojoType="dijit.form.TextBox"  id="village_note" name="village_note" value="<?php echo $this->rs['village_name'];?>" type="text" >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMMUNE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" tabindex="12" dojoType="dijit.form.TextBox"  id="commun_note" name="commun_note" value="<?php echo $this->rs['commune_name'];?>" type="text" >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" tabindex="13" dojoType="dijit.form.TextBox"  id="distric_note" name="distric_note" value="<?php echo $this->rs['district_name'];?>" type="text" >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<select  class="fullside" tabindex="14" name="student_province" id="student_province" dojoType="dijit.form.FilteringSelect"">
											<?php if(!empty($this->province))foreach ($this->province as $row){?>
											<option value="<?php echo $row['id']?>"<?php if($row['id']==$this->rs['province_id']) echo 'selected="selected"';?>><?php echo $row['name']?></option>
											<?php }?>
										</select>
				                   </div>
				                </div>
				                
				                
				             </div>
				            <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("OTHER_INFOMATION");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <div class="col-md-12 col-sm-12 col-xs-12 text-center">
				                    	<div class="account-image">
											<div class="image-box">
												<?php
													$images = $this->baseUrl().'/images/no-profile.png';
													 if (!empty($this->rs['photo'])){
													$images = $this->baseUrl().'/images/'.$this->rs['photo'];
													 }
												?>
											
												<img id="profile_wiew" src="<?php echo $images;?>" alt=""  />
											</div>
											<div class="button_browse">
											<div id='preview'></div>	
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="photo" name="photo"  />
													<input type="hidden" name="old_photo" value="<?php echo $this->rs['photo'];?>" id="old_photo" dojoType="dijit.form.TextBox" />
											</div>
										</div>
				                   </div>
				                </div>
				            </div>
				         </div>
				         <div class="card-box">
							<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDY_INFO");?> 
				                   </label>
				                </div>
				                
				                <div class="form-group">
				                   <label title="បញ្ជូលលេខសំគាល់និស្សិត" class="control-label bold  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STUDENT_ID");?> <span class="required">*</span> :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  style="color: red;" tabindex="15" dojoType="dijit.form.TextBox" id="student_id" name="student_id" value="<?php echo $this->rs['stu_code']; ?>" type="text" >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("GROUP");?> <span class="required">*</span> :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="group" />
										<!-- <select class="fullside" tabindex="15" name="group" id="group" dojoType="dijit.form.FilteringSelect" onchange="getInfoBygroup();">
											<option value=""><?php //echo $tr->translate("SELECT_GROUP");?></option>
											<?php //if(!empty($this->group))foreach ($this->group as $row){?>
											<option value="<?php //echo $row['id']?>" <?php //if($row['id']==$this->rs['group_id']) echo 'selected="selected"'?>><?php //echo $row['name']?></option>
											<?php //}?>
										</select> -->
										<input class="fullside" dojoType="dijit.form.TextBox"  id="old_group_id" name="old_group_id" value="<?php echo $this->rs['group_id'];?>" type="hidden"  >
				                   		</div>
				                   		<div class="col-md-3 col-sm-3 col-xs-12">
				                   			<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshGroup();"/>
				                   		</div>
				                   </div>
				                </div>
						        <div class="form-group">
				                   <label title="បញ្ជូលលេខសំគាល់និស្សិត" class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ACADEMIC_YEAR");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<select class="fullside" tabindex="14" dojoType="dijit.form.FilteringSelect" readonly="readonly"  id="academic_year" name="academic_year" placeholder="----- Select Year -----" value="" type="text" >
											<?php if(!empty($this->year))foreach ($this->year as $rows){?>
											<option value="<?php echo $rows['id'];?>"<?php if($rows['id']==$this->rs['academic_year']) echo 'selected="selected"'?>><?php echo $rows['years']?></option>
											<?php }?>
										</select>
				                   </div>
				                </div>  
							
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SESSION");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<select class="fullside" tabindex="19" readonly="readonly"  name="session" id="session" dojoType="dijit.form.FilteringSelect" >
											<option value="1" <?php if($this->rs['session']==1){ echo "selected='selected'"; } ?>><?php echo $tr->translate("MORNING")?></option>
											<option value="2" <?php if($this->rs['session']==2){ echo "selected='selected'"; } ?>><?php echo $tr->translate("AFTERNOON")?></option>
											<option value="3" <?php if($this->rs['session']==3){ echo "selected='selected'"; } ?>><?php echo $tr->translate("EVERNING")?></option>
											<option value="4" <?php if($this->rs['session']==4){ echo "selected='selected'"; }?>><?php echo $tr->translate("WEEKEND")?></option>
										</select>
				                   </div>
				                </div>
				             </div>
				             <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDY_INFO");?> 
				                   </label>
				                </div>
				                
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DEGREE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<select class="fullside" tabindex="16" name="degree" id="degree" readonly="readonly"  dojoType="dijit.form.FilteringSelect" onchange="getallGrade(0);">
											<?php if(!empty($this->degree))foreach ($this->degree as $row){?>
											<option value="<?php echo $row['dept_id']?>"<?php if($row['dept_id']==$this->rs['degree']) echo 'selected="selected"'?>><?php echo $row['en_name']?></option>
											<?php }?>
										</select>
				                   </div>
				                </div>  
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("GRADE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" tabindex="17" id="grade" value="<?php echo $this->rs['grade'];?>" />
										<input class="fullside" dojoType="dijit.form.TextBox"  id="grade_fromgrouop" name="grade_fromgrouop" value="" type="hidden"  >
				                   </div>
				                </div>  
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ROOM_NAME");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<select id="room" name="room" class="fullside" type="text"  dojoType="dijit.form.FilteringSelect" >
											<option value="-1"> Select Room</option>
											<?php if(!empty($this->room)){foreach ($this->room as $room){?>
											<option value="<?php echo $room['id'];?>" <?php if($room['id']==$this->rs['room']){echo 'selected="selected"';}?>><?php echo $room['name'];?></option>
											<?php }}?>
									   </select>
				                   </div>
				                </div>  
							
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<select class="fullside" tabindex="20" dojoType="dijit.form.FilteringSelect"   id="status" name="status" type="text">								
											<option value="1" <?php if($this->rs['status']==1){{ echo "selected='selected'"; }}?>><?php echo $this->translate("Active")?></option>
											<option value="0" <?php if($this->rs['status']==0){{ echo "selected='selected'"; }}?>><?php echo $this->translate("Deactive")?></option>
										</select>
				                   </div>
				                </div>  
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("REMARK");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                	  <textarea class="fullside" style=" height: 60px !important;" tabindex="21" dojoType=""  id="remark" name="remark"  ><?php echo $this->rs['remark'];?></textarea>
				                   </div>
				                </div>  
				                
				             </div>
				             
				         </div>
				    </div>
				     <!--/. Panel 1-->
				     
				     <!--Panel 2-->
			        <div class="tab-pane fade in " id="panel22" role="tabpanel">
			        	 <div class="card-box">
				        	<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("FATHER_INFO");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  tabindex="23" dojoType="dijit.form.ValidationTextBox"  id="fa_name_en" name="fa_name_en" value="<?php echo $this->rs['father_enname'];?>" type="text" >
				                   </div>
				                </div> 
					      	   <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" tabindex="24" dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" id="fa_dob" name="fa_dob" value="<?php echo $this->rs['father_dob'];?>" type="text" >
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  tabindex="25" dojoType="dijit.form.TextBox"  id="fa_national" name="fa_national" value="<?php echo $this->rs['father_nation'];?>" type="text"  >
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("OCCUPATION");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="fa_job" />
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                  		<input class="fullside"  tabindex="27" dojoType="dijit.form.ValidationTextBox"  id="fa_phone" name="fa_phone" value="<?php echo $this->rs['father_phone'];?>" type="text"  >
				                   </div>
				                </div> 
				             </div>
				             <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("MOTHER_INFO");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  tabindex="29" dojoType="dijit.form.ValidationTextBox"  id="mom_name_en" name="mom_name_en" value="<?php echo $this->rs['mother_enname'];?>" type="text"  >
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  tabindex="30" dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}"  id="mo_dob" name="mo_dob" value="<?php echo $this->rs['mother_dob'];?>" type="text" >
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" tabindex="31" dojoType="dijit.form.TextBox"  id="mom_nation" name="mom_nation" value="<?php echo $this->rs['mother_nation'];?>" type="text" >
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("OCCUPATION");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="mo_job" />
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  tabindex="33" dojoType="dijit.form.ValidationTextBox"  id="mon_phone" name="mon_phone" value="<?php echo $this->rs['mother_phone'];?>" type="text"   >
				                   </div>
				                </div> 
				             </div>
				             <div class="col-md-4 col-sm-4 col-xs-12">
								<div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("GUARDIAN_INFO");?> 
				                   </label>
				                </div>
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  tabindex="35" dojoType="dijit.form.ValidationTextBox"  id="guardian_name_en" name="guardian_name_en" value="<?php echo $this->rs['guardian_enname'];?>" type="text"  >
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  tabindex="36" dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" id="guardian_dob" name="guardian_dob" value="<?php echo $this->rs['guardian_dob'];?>" type="text" >
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  tabindex="37" dojoType="dijit.form.TextBox"  id="guardian_national" name="guardian_national" value="<?php echo $this->rs['guardian_nation'];?>" type="text"  >
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("OCCUPATION");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input id="gu_job" />
				                   </div>
				                </div> 
				                <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside"  tabindex="40" dojoType="dijit.form.ValidationTextBox"  id="guardian_phone" name="guardian_phone" value="<?php echo $this->rs['guardian_tel'];?>" type="text"  >
				                   </div>
				                </div> 
				             </div>
				         </div>
				    </div>
				     <!--/. Panel 2-->
				</div>
				 <!--/. Tab panels -->
			</div>
			
			<div class="clearfix"></div>
		    <div class="card-box">
               	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               			<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
						<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
							iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'foundation','controller'=>"register",'action'=>'index'),null,true); ?>';" />
						<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate('ADD');?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
	    		</div>
	    	</div>
	    	
		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");

var language_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->language));?> );
var job_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->occupation));?> );
var job_store1  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->occupation));?> );
var job_store2  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->occupation));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->group));?> );

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: group_store,
	    autoComplete: true,                        
	    id: "group",
	    name: "group",  
	    value:'<?php echo $this->rs['group_id'];?>' ,       
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",  
	    onChange: function() {  
	    	group_id = dijit.byId('group').get('value');
	    	if(group_id==-1){
	    		window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/group/add";?>','_blank');
			  }else{
				  getInfoBygroup();
			  }
	    }
	}, "group");
	getInfoBygroup();
	new dijit.form.FilteringSelect({
	    autoComplete: true,                        
	    id: "grade",
	    name: "grade",
	    required : "false",
	    readOnly: true,            
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
	    onChange: function() {  
	    	make_id = dijit.byId('grade').get('value');
	    }
	}, "grade");
	getallGrade(1);

	new dijit.form.FilteringSelect({
		store: job_store,
		autoComplete: true,                        
	    id: "fa_job",
	    name: "fa_job",  
	    tabindex: "17",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_JOB");?>", 
	    onChange: function() {          
	   	fa_job = dijit.byId('fa_job').get('value');
	    if(fa_job==-1){
	   	 	dijit.byId("popup_dept2").show();
		   	dijit.byId('value_j').attr('value',1);
	    }
	    else {
	    }  
	   } 
	}, "fa_job");
	dijit.byId('fa_job').attr('value',"<?php echo $this->rs['father_job']?>");
	fa = dijit.byId('fa_job').get('value');
	if(fa==''){
		dijit.byId('fa_job').attr('value',0);
	}

	new dijit.form.FilteringSelect({
		store: job_store,
		autoComplete: true,                        
	    id: "mo_job",
	    name: "mo_job",  
	    tabindex: "17",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_JOB");?>", 
	    onChange: function() {          
	   	mo_job = dijit.byId('mo_job').get('value');
	    if(mo_job==-1){
	   	 dijit.byId("popup_dept2").show();
		   	dijit.byId('value_j').attr('value',2);
	     }
	    else {
	    }  
	   } 
	}, "mo_job");
	dijit.byId('mo_job').attr('value',"<?php echo $this->rs['mother_job']?>");
	mo = dijit.byId('mo_job').get('value');
	if(mo==''){
		dijit.byId('mo_job').attr('value',0);
	}

	new dijit.form.FilteringSelect({
		store: job_store,
		autoComplete: true,                        
	    id: "gu_job",
	    name: "gu_job",  
	    tabindex: "17",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_JOB");?>", 
	    onChange: function() {          
	   	mo_job = dijit.byId('gu_job').get('value');
	    if(mo_job==-1){
	   	 dijit.byId("popup_dept2").show();
		   	dijit.byId('value_j').attr('value',3);
	     }
	    else {
	    }  
	   } 
	}, "gu_job");
	dijit.byId('gu_job').attr('value',"<?php echo $this->rs['guardian_job']?>");
	fa = dijit.byId('gu_job').get('value');
	if(fa==''){
		dijit.byId('gu_job').attr('value',0);
	}
	dijit.byId('academic_year').attr('value',"<?php echo $this->rs['academic_year']?>");
}); 

var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(condition){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store); 
				    if(condition==1){
				    	dijit.byId('grade').attr('value','<?php echo $this->rs['grade']; ?>');  
				    }else{
				    	dijit.byId('grade').set('value',dijit.byId('grade_fromgrouop').get('value'));
				    }
				},
				error: function(err) {
					alert(err);
				}
			});
	}
</script>

<style>
 @media (min-width: 1401px) and (max-width: 1601px){
	#mainTabContainer{
	width: 1400px !important;
   	 display: block;
	}
}
</style>
<script>
function hideDialog1() {		
	dijit.byId("popup_dept2").hide();
}
var url_add_job = '<?php echo $this->url(array("module"=>"foundation","controller"=>"register","action"=>"add-job")); ?>';
function addJob(){
	fa_job=dijit.byId('fa_job').get('value');
	mo_job=dijit.byId('mo_job').get('value');
	gu_job=dijit.byId('gu_job').get('value');
	type=dijit.byId('value_j').get('value');
	dojo.xhrPost({
		url:url_add_job,
		form: dojo.byId("frm_add_tran1"),
		handleAs:"json",
		load: function(data) {
			var Itemmake = { 
			    		id: data,
				        name: dijit.byId('occu_name').get('value')
				   };
			if(type==1){	   
		 		addDataToSelectbox(dijit.byId('fa_job'), job_store, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('mo_job'), job_store1, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('gu_job'), job_store2, Itemmake, data);
				dijit.byId('mo_job').attr('value',mo_job);
				dijit.byId('gu_job').attr('value',gu_job);
			}else if(type==2){
				addDataToSelectbox(dijit.byId('fa_job'), job_store, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('mo_job'), job_store1, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('gu_job'), job_store2, Itemmake, data);
				dijit.byId('fa_job').attr('value',fa_job);
				dijit.byId('gu_job').attr('value',gu_job);
			}else if(type==3){
				addDataToSelectbox(dijit.byId('fa_job'), job_store, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('mo_job'), job_store1, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('gu_job'), job_store2, Itemmake, data);
				dijit.byId('mo_job').attr('value',mo_job);
				dijit.byId('fa_job').attr('value',fa_job);
			}
	    dijit.byId('frm_add_tran1').reset();
	    dijit.byId("popup_dept2").hide();
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;" id="popup_dept2" >
		<form style="background-color: buttonface;" id='frm_add_tran1' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate('ADD_OCCUPATION');?></legend><br />
						<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
							<tr>
								<td><?php echo $tr->translate('OCCUPATION_KHNAME');?></td>
								<td>
									<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="occu_name" name="occu_name" value="" type="text">
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate('OCCUPATION_ENNAME');?></td>
								<td>
									<input dojoType="dijit.form.TextBox" type="hidden" name="value_j" id="value_j" value=""   />
									<input dojoType="dijit.form.ValidationTextBox"  class="fullside" id="occu_enname" name="occu_enname" value="" type="text">
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate('STATUS');?></td>
								<td><select name="status_j" id="status_j" dojoType="dijit.form.FilteringSelect"  class="fullside">
	    								<option value="1" label="active">Active</option>
	    								<option value="0" label="deactive">Deactive</option>
									</select>
								</td>
							</tr>
							<tr>
								<td colspan="4" align="center">
									<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addJob();"/>
									<input type="button" value="ចាកចេញ" label="ចាកចេញ" id="close" name="close" dojoType="dijit.form.Button" 
									​ ​​iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideDialog1();"/>
								</td>
							</tr>
						</table>
				</fieldset>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	//dojo.require("dojo.NodeList-manipulate");
	//dojo.require("dojo.data.ObjectStore");
	//dojo.require("dojo.store.Memory");
	var url_getgroup = '<?php echo $this->url(array("module"=>"global","controller"=>"group","action"=>"getgroup"));?>';										
	function getRefreshGroup(){
		loading();
		dojo.xhrPost({
			url:url_getgroup,
			handleAs:"json",
			load: function(data) {
				group_store  = getDataStorefromJSON('id','name', data.group);
			    dijit.byId('group').set('store',group_store);  
			    degree_store  = getDataStorefromJSON('id','name', data.degree);
			    dijit.byId('degree').set('store',degree_store);  

			    room_store  = getDataStorefromJSON('id','name', data.room);
			    dijit.byId('room').set('store',room_store);  
			    
			    document.getElementsByClassName("overlay")[0].style.display="none";
			},
			error: function(err) {
				alert("err here ");
				document.getElementsByClassName("overlay")[0].style.display="none";
			}
		});
	}
	function getInfoBygroup(){
		url_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getgroupinfo'));?>';
		group = dijit.byId('group').get('value');
		if(group==''){
			alert("Please Select Group");
			return false;
		}
		dojo.xhrPost({
			url:url_group,	
			content:{ 
				'group_id': group
			},
			handleAs:"json",
			load: function(data) {
				dijit.byId('academic_year').set('value',data.academic_year);
				dijit.byId('academic_year').set('readOnly',true);
				dijit.byId('degree').set('value',data.degree);
				dijit.byId('degree').set('readOnly',true);
				dijit.byId('grade').set('value',data.grade);
				dijit.byId('grade').set('readOnly',true);
				dijit.byId('grade_fromgrouop').set('value',data.grade);
				dijit.byId('session').set('value',data.session);
				dijit.byId('session').set('readOnly',true);
				dijit.byId('room').set('value',data.room_id);
				//dijit.byId('room').set('readOnly',true);
			},
			error: function(err) {
				alert(err);
			}
		});
	}

	function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile_wiew').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    var maxSize = 0;
    $("#photo").change(function(){
    	/*
    	var iSize = ($("#photo")[0].files[0].size / 1024); 
        if (iSize / 1024 > 1) 
        { 
           if (((iSize / 1024) / 1024) > 1) 
           { 
               iSize = (Math.round(((iSize / 1024) / 1024) * 100) / 100);
               maxSize = 0;
               //$("#lblSize").html( iSize + "Gb"); 
           }else{ 
               iSize = (Math.round((iSize / 1024) * 100) / 100);
               if(iSize>5){
                   alert('<?php //echo $tr->translate("Image size more than 5Mb can not upload");?>');
                   maxSize = 1;
                   $('#profile_wiew').attr('src', "<?php //echo $this->baseUrl().'/images/no-profile.png';?>");
                   return false;
               }
               //$("#lblSize").html( iSize + "Mb"); 
           } 
        } 
        else 
        {
           iSize = (Math.round(iSize * 100) / 100);
           maxSize = 0;
           //$("#lblSize").html( iSize  + "kb"); 
        }
    	*/    
        
        readURL(this);
    });
	function loading(){
	    document.getElementsByClassName("overlay")[0].style.display="block";
	}
</script>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("/psst/trunk/public/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>