<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('EDIT_STUDENT_REGISTER')); 
	echo $this->headTitle(''); 
	$photo= $this->frm_techer;
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
//dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
//dojo.require("dijit.form.CheckBox");

var language_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->language));?> );
var job_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->occupation));?> );
var job_store1  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->occupation));?> );
var job_store2  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->occupation));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->group));?> );

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: group_store,
	    autoComplete: true,                        
	    id: "group",
	    name: "group",  
	    value:'<?php echo $this->rs['group_id'];?>' ,       
	    class: 'fullside',  
	    placeHolder:"SELECT_GROUP",  
	    onChange: function() {  
	    	group_id = dijit.byId('group').get('value');
	    	if(group_id==-1){
	    		window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/group/add";?>','_blank');
			  }else{
				  getInfoBygroup();
			  }
	    }
	}, "group");
	 getInfoBygroup();
	
	new dijit.form.FilteringSelect({
	    autoComplete: true,                        
	    id: "grade",
	    name: "grade",
	    required : "false",
	    readOnly: true,            
	    class: 'fullside',  
	    placeHolder:"Selected Grade",          
	    onChange: function() {  
	    	make_id = dijit.byId('grade').get('value');
	    }
	}, "grade");
	getallGrade(1);

	new dijit.form.FilteringSelect({
		store: job_store,
		autoComplete: true,                        
	    id: "fa_job",
	    name: "fa_job",  
	    tabindex: "17",         
	    class: 'fullside',  
	    placeHolder:"Selected job", 
	    onChange: function() {          
	   	fa_job = dijit.byId('fa_job').get('value');
	    if(fa_job==-1){
	   	 	dijit.byId("popup_dept2").show();
		   	dijit.byId('value_j').attr('value',1);
	    }
	    else {
	    }  
	   } 
	}, "fa_job");
	dijit.byId('fa_job').attr('value',"<?php echo $this->rs['father_job']?>");
	fa = dijit.byId('fa_job').get('value');
	if(fa==''){
		dijit.byId('fa_job').attr('value',0);
	}

	new dijit.form.FilteringSelect({
		store: job_store,
		autoComplete: true,                        
	    id: "mo_job",
	    name: "mo_job",  
	    tabindex: "17",         
	    class: 'fullside',  
	    placeHolder:"Selected job", 
	    onChange: function() {          
	   	mo_job = dijit.byId('mo_job').get('value');
	    if(mo_job==-1){
	   	 dijit.byId("popup_dept2").show();
		   	dijit.byId('value_j').attr('value',2);
	     }
	    else {
	    }  
	   } 
	}, "mo_job");
	
	dijit.byId('mo_job').attr('value',"<?php echo $this->rs['mother_job']?>");
	mo = dijit.byId('mo_job').get('value');
	if(mo==''){
		dijit.byId('mo_job').attr('value',0);
	}
	new dijit.form.FilteringSelect({
		store: job_store,
		autoComplete: true,                        
	    id: "gu_job",
	    name: "gu_job",  
	    tabindex: "17",         
	    class: 'fullside',  
	    placeHolder:"Selected job", 
	    onChange: function() {          
	   	mo_job = dijit.byId('gu_job').get('value');
	    if(mo_job==-1){
	   	 dijit.byId("popup_dept2").show();
		   	dijit.byId('value_j').attr('value',3);
	     }
	    else {}  
	   } 
	}, "gu_job");
	dijit.byId('gu_job').attr('value',"<?php echo $this->rs['guardian_job']?>");
	fa = dijit.byId('gu_job').get('value');
	if(fa==''){
		dijit.byId('gu_job').attr('value',0);
	}
	dijit.byId('academic_year').attr('value',"<?php echo $this->rs['academic_year']?>");
}); 
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(condition){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store); 
				    if(condition==1){
				    	dijit.byId('grade').attr('value','<?php echo $this->rs['grade']; ?>');  
				    }else{
				    	dijit.byId('grade').set('value',dijit.byId('grade_fromgrouop').get('value'));
				    }
				},
				error: function(err) {
					alert(err);
				}
			});
	}
</script>
<form id="add_student" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
		<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				dijit.byId('save_close').set('disabled',true);	
				return true;
			}else {
				return false;
			}
		</script>
		<table width="100%" >
			<tr>
				<td>
				 <div id="mainTabContainer" style="width: 1150px;height: 500px;" dojoType="dijit.layout.TabContainer" region="center" width="1000px !importand" >
				  <div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("STUDENT_INFO");?>" selected="true">
					<table  cellspacing="5" style="margin:0 auto;" width="100%">
						<tr>
							<td ><?php echo $tr->translate("NAME_KH");?></td>
							<td><input class="fullside" tabindex="2" dojoType="dijit.form.ValidationTextBox"  id="name_kh" name="name_kh" value="<?php echo $this->rs['stu_khname'];?>" type="text"  ></td>
							<td ><?php echo $tr->translate("NAME_EN");?></td>
							<td><input class="fullside" tabindex="2" required="true" dojoType="dijit.form.ValidationTextBox" id="name_en" name="name_en" value="<?php echo $this->rs['stu_enname'];?>" type="text"  ></td>
							<td ><?php echo $tr->translate("SEX");?></td>
							<td>
								<select class="fullside"  tabindex="3" name="sex" id="sex" dojoType="dijit.form.FilteringSelect" >
									<option value="1" <?php if($this->rs['sex']==1){{ echo "selected='selected'"; }} ?> ><?php echo $tr->translate("MALE")?></option>
									<option value="2"<?php if($this->rs['sex']==2){{ echo "selected='selected'"; }} ?> ><?php echo $tr->translate("FEMALE")?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td title="សញ្ឃាតិ"><?php echo $tr->translate("NATIONALITY");?></td>
							<td><input class="fullside" tabindex="4" dojoType="dijit.form.TextBox"  id="studen_national" name="studen_national" value="<?php echo $this->rs['nationality'];?>" type="text" ></td>
							<td ><?php echo $tr->translate("DOB");?></td>
							<td><input class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" tabindex="5"  name="date_of_birth" id="date_of_birth" dojoType="dijit.form.DateTextBox"  value="<?php echo $this->rs['dob'];?>" type="text"/></td>
							<td><?php echo $tr->translate("PARENT_PHONE");?></td>
							<td><input class="fullside" tabindex="4" dojoType="dijit.form.TextBox"  id="phone" name="phone" value="<?php echo $this->rs['tel'];?>" type="text" ></td>
						</tr>
						<tr>			
							<td><?php echo $tr->translate("POB");?></td>
							<td colspan="3"><textarea class="fullside"  style=" height: 60px !important;" tabindex="20" id="pob" name="pob"  ><?php echo $this->rs['pob'];?></textarea></td>
							<td ><?php echo $tr->translate("PHOTO");?></td>
							<td>
								<?php echo $photo->getElement('photo');?>
								<img  src="<?php echo $this->baseUrl().'/images/'.$this->rs['photo'];?>" width="70px">
							</td>
						</tr>
							<input type="hidden" name="old_photo" value="<?php echo $this->rs['photo'];?>" id="old_photo" dojoType="dijit.form.TextBox" />
						<tr>
							<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("CURRENT_ADDRESS");?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("HOME");?></td>
							<td><input class="fullside" tabindex="9" dojoType="dijit.form.TextBox"  id="home_note" name="home_note" value="<?php echo $this->rs['home_num'];?>" ></td>
							<td><?php echo $tr->translate("STREET");?></td>
							<td><input class="fullside" tabindex="10" dojoType="dijit.form.TextBox"  id="way_note" name="way_note" value="<?php echo $this->rs['street_num'];?>" type="text" ></td>
							<td><?php echo $tr->translate("VILLAGE");?></td>
							<td><input class="fullside" tabindex="11" dojoType="dijit.form.TextBox"  id="village_note" name="village_note" value="<?php echo $this->rs['village_name'];?>" type="text" ></td>
						</tr>
						<tr>								
							<td><?php echo $tr->translate("COMMUNE");?></td>
							<td><input class="fullside" tabindex="12" dojoType="dijit.form.TextBox"  id="commun_note" name="commun_note" value="<?php echo $this->rs['commune_name'];?>" type="text" ></td>
							<td><?php echo $tr->translate("DISTRICT");?></td>
							<td><input class="fullside" tabindex="13" dojoType="dijit.form.TextBox"  id="distric_note" name="distric_note" value="<?php echo $this->rs['district_name'];?>" type="text" ></td>
							<td><?php echo $tr->translate("PROVINCE");?></td>
							<td>
							<select class="fullside" tabindex="14" name="student_province" id="student_province" dojoType="dijit.form.FilteringSelect"">
									<?php if(!empty($this->province))foreach ($this->province as $row){?>
									<option value="<?php echo $row['id']?>"<?php if($row['id']==$this->rs['province_id']) echo 'selected="selected"';?>><?php echo $row['name']?></option>
									<?php }?>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("STUDY_INFO");?></strong></td>
						</tr>
						<tr>
						<td><?php echo $tr->translate("GROUP");?>*</td>
							<td>
								<input id="group" />
								<input class="fullside" dojoType="dijit.form.TextBox"  id="old_group_id" name="old_group_id" value="<?php echo $this->rs['group_id'];?>" type="hidden"  >
							</td>
							<td><input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshGroup();"/></td>
						</tr>
						<tr>
							<td title="បញ្ជូលលេខសំគាល់និស្សិត"><?php echo $tr->translate("ACADEMIC_YEAR");?>*</td>
							<td>
								<select class="fullside" tabindex="14" dojoType="dijit.form.FilteringSelect" readonly="readonly"  id="academic_year" name="academic_year" placeholder="----- Select Year -----" value="" type="text" >
									<?php if(!empty($this->year))foreach ($this->year as $rows){?>
									<option value="<?php echo $rows['id'];?>"<?php if($rows['id']==$this->rs['academic_year']) echo 'selected="selected"'?>><?php echo $rows['years']?></option>
									<?php }?>
								</select>
							</td>
							<td><?php echo $tr->translate("DEGREE");?>*</td>
							<td>
								<select class="fullside" tabindex="16" name="degree" id="degree" readonly="readonly"  dojoType="dijit.form.FilteringSelect" onchange="getallGrade(0);">
									<?php if(!empty($this->degree))foreach ($this->degree as $row){?>
									<option value="<?php echo $row['dept_id']?>"<?php if($row['dept_id']==$this->rs['degree']) echo 'selected="selected"'?>><?php echo $row['en_name']?></option>
									<?php }?>
								</select>
							</td>
							<td><?php echo $tr->translate("GRADE");?>*</td>
							<td>
								<input class="fullside" tabindex="17" id="grade" value="<?php echo $this->rs['grade'];?>" />
								<input class="fullside" dojoType="dijit.form.TextBox"  id="grade_fromgrouop" name="grade_fromgrouop" value="" type="hidden"  >
							</td>
						</tr>
						<tr>
							<td title="បញ្ជូលលេខសំគាល់និស្សិត"><?php echo $tr->translate("STUDENT_ID");?>*</td>
							<td><input class="fullside"  style="color: red;" tabindex="15" dojoType="dijit.form.TextBox"  id="student_id" name="student_id" value="<?php echo $this->rs['stu_code']; ?>" type="text" ></td>
							<td><?php echo $tr->translate("SESSION");?>*</td>
							<td>
								<select class="fullside" tabindex="19" readonly="readonly"  name="session" id="session" dojoType="dijit.form.FilteringSelect" >
									<option value="1" <?php if($this->rs['session']==1){ echo "selected='selected'"; } ?>><?php echo $tr->translate("MORNING")?></option>
									<option value="2" <?php if($this->rs['session']==2){ echo "selected='selected'"; } ?>><?php echo $tr->translate("AFTERNOON")?></option>
									<option value="3" <?php if($this->rs['session']==3){ echo "selected='selected'"; } ?>><?php echo $tr->translate("EVERNING")?></option>
									<option value="4" <?php if($this->rs['session']==4){ echo "selected='selected'"; }?>><?php echo $tr->translate("WEEKEND")?></option>
								</select>
							</td>
							<td title="កំរិតភាសា"><?php echo $tr->translate("ROOM_NAME");?></td>
							<td>
							   <select id="room" name="room" class="fullside" type="text" dojoType="dijit.form.FilteringSelect" >
									<option value="-1"> Select Room</option>
									<?php if(!empty($this->room)){foreach ($this->room as $room){?>
									<option value="<?php echo $room['id'];?>" <?php if($room['id']==$this->rs['room']){echo 'selected="selected"';}?>><?php echo $room['name'];?></option>
									<?php }}?>
							   </select>
							</td>
						</tr>
						<tr>
							<td title="ស្ថានការណ៍"><?php echo $tr->translate("STATUS");?></td>
							<td>
								<select class="fullside" tabindex="20" dojoType="dijit.form.FilteringSelect"   id="status" name="status" type="text">								
									<option value="1" <?php if($this->rs['status']==1){{ echo "selected='selected'"; }}?>><?php echo $this->translate("Active")?></option>
									<option value="0" <?php if($this->rs['status']==0){{ echo "selected='selected'"; }}?>><?php echo $this->translate("Deactive")?></option>
								</select>
							</td>
							<td title="ពណ៌នា"><?php echo $tr->translate("REMARK");?></td>
							<td  colspan="3" >
								<textarea class="fullside" style=" height: 60px !important;"
								tabindex="21" dojoType=""  id="remark" name="remark"  ><?php echo $this->rs['remark'];?></textarea>
							</td>
						</tr>
					</table>
				  </div><!-- end tab 1 -->
				  <div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("PARENT_INFO");?>" selected="false">
					<table width="100%" style="margin:0 auto;" cellspacing="5">
						<tr>
							<td colspan="6" style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("FATHER_INFO");?></strong></td>
						</tr>
						<tr>
							<td ><?php echo $tr->translate("NAME");?>*</td>
							<td><input class="fullside"  tabindex="23" dojoType="dijit.form.ValidationTextBox"  id="fa_name_en" name="fa_name_en" value="<?php echo $this->rs['father_enname'];?>" type="text" ></td>
							<td><?php echo $tr->translate("DOB");?></td>
							<td><input class="fullside" tabindex="24" dojoType="dijit.form.DateTextBox"  id="fa_dob" name="fa_dob" value="<?php echo $this->rs['father_dob'];?>" type="text" ></td>
							<td><?php echo $tr->translate("NATIONALITY");?></td>
							<td><input class="fullside"  tabindex="25" dojoType="dijit.form.TextBox"  id="fa_national" name="fa_national" value="<?php echo $this->rs['father_nation'];?>" type="text"  ></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("OCCUPATION");?></td>
							<td><input id="fa_job" />
							</td>
							<td><?php echo $tr->translate("PHONE");?>*</td>
							<td><input class="fullside"  tabindex="27" dojoType="dijit.form.ValidationTextBox"  id="fa_phone" name="fa_phone" value="<?php echo $this->rs['father_phone'];?>" type="text"  ></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("MOTHER_INFO");?></strong></td>
						</tr>
						<tr>
							<td ><?php echo $tr->translate("NAME");?>*</td>
							<td><input class="fullside"  tabindex="29" dojoType="dijit.form.ValidationTextBox"  id="mom_name_en" name="mom_name_en" value="<?php echo $this->rs['mother_enname'];?>" type="text"  ></td>
							<td><?php echo $tr->translate("DOB");?></td>
							<td><input class="fullside"  tabindex="30" dojoType="dijit.form.DateTextBox"  id="mo_dob" name="mo_dob" value="<?php echo $this->rs['mother_dob'];?>" type="text" ></td>
							<td><?php echo $tr->translate("NATIONALITY");?></td>
							<td><input class="fullside" tabindex="31" dojoType="dijit.form.TextBox"  id="mom_nation" name="mom_nation" value="<?php echo $this->rs['mother_nation'];?>" type="text" ></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("OCCUPATION");?></td>
							<td><input id="mo_job" /></td>
							<td><?php echo $tr->translate("PHONE");?>*</td>
							<td><input class="fullside"  tabindex="33" dojoType="dijit.form.ValidationTextBox"  id="mon_phone" name="mon_phone" value="<?php echo $this->rs['mother_phone'];?>" type="text"   ></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("GUARDIAN_INFO");?></strong></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME");?>*</td>
							<td><input class="fullside"  tabindex="35" dojoType="dijit.form.ValidationTextBox"  id="guardian_name_en" name="guardian_name_en" value="<?php echo $this->rs['guardian_enname'];?>" type="text"  ></td>
							<td><?php echo $tr->translate("DOB");?></td>
							<td><input class="fullside"  tabindex="36" dojoType="dijit.form.DateTextBox"  id="guardian_dob" name="guardian_dob" value="<?php echo $this->rs['guardian_dob'];?>" type="text" ></td>
							<td><?php echo $tr->translate("NATIONALITY");?></td>
							<td><input class="fullside"  tabindex="37" dojoType="dijit.form.TextBox"  id="guardian_national" name="guardian_national" value="<?php echo $this->rs['guardian_nation'];?>" type="text"  ></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("OCCUPATION");?></td>
							<td><input id="gu_job" /></td>
							<td><?php echo $tr->translate("PHONE");?>*</td>
							<td><input class="fullside"  tabindex="40" dojoType="dijit.form.ValidationTextBox"  id="guardian_phone" name="guardian_phone" value="<?php echo $this->rs['guardian_tel'];?>" type="text"  ></td>
						</tr>
					</table>
				  </div>
			   </div>
			   </td>
			</tr>
			<tr>
				<td align="center">
					<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
					<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
						iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'foundation','controller'=>"register",'action'=>'index'),null,true); ?>';" />
					<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
				</td>
			</tr>
		</table>
</form>
<script>
function hideDialog1() {		
	dijit.byId("popup_dept2").hide();
}
var url_add_job = '<?php echo $this->url(array("module"=>"foundation","controller"=>"register","action"=>"add-job")); ?>';
function addJob(){
	fa_job=dijit.byId('fa_job').get('value');
	mo_job=dijit.byId('mo_job').get('value');
	gu_job=dijit.byId('gu_job').get('value');
	type=dijit.byId('value_j').get('value');
	dojo.xhrPost({
		url:url_add_job,
		form: dojo.byId("frm_add_tran1"),
		handleAs:"json",
		load: function(data) {
			var Itemmake = { 
			    		id: data,
				        name: dijit.byId('occu_name').get('value')
				   };
			if(type==1){	   
		 		addDataToSelectbox(dijit.byId('fa_job'), job_store, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('mo_job'), job_store1, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('gu_job'), job_store2, Itemmake, data);
				dijit.byId('mo_job').attr('value',mo_job);
				dijit.byId('gu_job').attr('value',gu_job);
			}else if(type==2){
				addDataToSelectbox(dijit.byId('fa_job'), job_store, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('mo_job'), job_store1, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('gu_job'), job_store2, Itemmake, data);
				dijit.byId('fa_job').attr('value',fa_job);
				dijit.byId('gu_job').attr('value',gu_job);
			}else if(type==3){
				addDataToSelectbox(dijit.byId('fa_job'), job_store, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('mo_job'), job_store1, Itemmake, data);
		 		addDataToSelectbox(dijit.byId('gu_job'), job_store2, Itemmake, data);
				dijit.byId('mo_job').attr('value',mo_job);
				dijit.byId('fa_job').attr('value',fa_job);
			}
	    dijit.byId('frm_add_tran1').reset();
	    dijit.byId("popup_dept2").hide();
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px" id="popup_dept2" >
		<form style="background-color: buttonface; width:15cm;" id='frm_add_tran1' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate('ADD_OCCUPATION');?></legend><br />
						<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
							<tr>
								<td><?php echo $tr->translate('OCCUPATION_KHNAME');?></td>
								<td>
									<input dojoType="dijit.form.ValidationTextBox"  class="fullside" id="occu_name" name="occu_name" value="" type="text">
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate('OCCUPATION_ENNAME');?></td>
								<td>
									<input dojoType="dijit.form.TextBox" type="hidden" name="value_j" id="value_j" value=""   />
									<input dojoType="dijit.form.ValidationTextBox"  class="fullside" id="occu_enname" name="occu_enname" value="" type="text">
								</td>
							</tr>
							<tr>
							<tr>
								<td><?php echo $tr->translate('STATUS');?></td>
								<td>
									<select name="status_j" id="status_j" dojoType="dijit.form.FilteringSelect"  class="fullside">
	    								<option value="1" label="active">Active</option>
	    								<option value="0" label="deactive">Deactive</option>
									</select>
								</td>
							</tr>
							<tr>
								<td colspan="4" align="center">
									<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addJob();"/>
									<input type="button" value="ចាកចេញ" label="ចាកចេញ" id="close" name="close" dojoType="dijit.form.Button" 
									​ ​​iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideDialog1();"/>
								</td>
							</tr>
						</table>
				</fieldset>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<script type="text/javascript">
	function getInfoBygroup(){
		url_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getgroupinfo'));?>';
		group = dijit.byId('group').get('value');
		if(group==''){
			alert("Please Select Group");
			return false;
		}
		dojo.xhrPost({
			url:url_group,	
			content:{ 
				'group_id': group
			},
			handleAs:"json",
			load: function(data) {
				dijit.byId('academic_year').set('value',data.academic_year);
				dijit.byId('academic_year').set('readOnly',true);
				dijit.byId('degree').set('value',data.degree);
				dijit.byId('degree').set('readOnly',true);
				dijit.byId('grade').set('value',data.grade);
				dijit.byId('grade').set('readOnly',true);
				dijit.byId('grade_fromgrouop').set('value',data.grade);
				dijit.byId('session').set('value',data.session);
				dijit.byId('session').set('readOnly',true);
				dijit.byId('room').set('value',data.room_id);
				//dijit.byId('room').set('readOnly',true);
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	var url_getgroup = '<?php echo $this->url(array("module"=>"global","controller"=>"group","action"=>"getgroup"));?>';										
	function getRefreshGroup(){
		loading();
		dojo.xhrPost({
			url:url_getgroup,
			handleAs:"json",
			load: function(data) {
				group_store  = getDataStorefromJSON('id','name', data.group);
			    dijit.byId('group').set('store',group_store);  
			    degree_store  = getDataStorefromJSON('id','name', data.degree);
			    dijit.byId('degree').set('store',degree_store);

			    room_store  = getDataStorefromJSON('id','name', data.room);
			    dijit.byId('room').set('store',room_store);  
			      
			    document.getElementsByClassName("overlay")[0].style.display="none";
			},
			error: function(err) {
				alert("err here ");
				document.getElementsByClassName("overlay")[0].style.display="none";
			}
		});
	}
	function loading(){
	    document.getElementsByClassName("overlay")[0].style.display="block";
	}
</script>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("/psst/trunk/public/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>