
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('STUDENT_INFO'));
	echo $this->headTitle(''); 
	$url_copy =$this->url(array('module'=>'foundation','controller'=>'register','action'=>'copy'));
	$formList = new Application_Form_Frmtable();
	$frm =  $this->form_search;
	
	$urlCopy = $this->baseUrl()."/foundation/register/copy/id/";
	$urlEdit = $this->baseUrl()."/foundation/register/edit/id/";
	$urlView = $this->baseUrl()."/foundation/register/view/id/";
	$urlTrandrop = $this->baseUrl()."/foundation/studenttrandrop/stutrandrop/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_INFO');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
		<div class="card-box">
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("adv_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("study_year");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("degree");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("grade_all");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("session");?>
                   </div>
                </div>
                <div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("user");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("status");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
                   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>	



<script type="text/javascript">
dojo.require("dijit.form.CheckBox"); 
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");

	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 if(id!=''){
			window.location.href = url+'/id/'+id;
		 }else{
			alert('Please select record you want to copy');
			return false;
		 }
	}

	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}

	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
			
				var m = "clicked: " + key;
				if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}else if(key=="copy"){
					url='<?php echo $urlCopy;?>';
				}
				else if(key=="view"){
					url='<?php echo $urlView;?>';
				}else if(key=="stutrandrop"){
					url='<?php echo $urlTrandrop;?>';
				}
				
				gotoAction();
				//window.console && console.log(m) || alert(m); 
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
				"copy": {name: "<?php echo $tr->translate("COPY");?>", icon: "copy"},
				"view": {name: "<?php echo $tr->translate("Profile");?>", icon: "fa-user"},
				"stutrandrop": {name: "<?php echo $tr->translate("TRANDROP");?>", icon: "fa-info-circle"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.open(url+row, '_blank');
		 //window.open(url+row);
	}
</script> 
