
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('STUDENT_INFO'));
	echo $this->headTitle(''); 
	$url_copy =$this->url(array('module'=>'foundation','controller'=>'register','action'=>'copy'));
	$formList = new Application_Form_Frmtable();
	$frm =  $this->form_search;
	
	$urlCopy = $this->baseUrl()."/foundation/register/copy/id/";
	$urlEdit = $this->baseUrl()."/foundation/register/edit/id/";
	$urlView = $this->baseUrl()."/foundation/register/view/id/";
	$urlTrandrop = $this->baseUrl()."/foundation/studenttrandrop/stutrandrop/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_INFO');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
		<div class="card-box">
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("adv_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php //echo $frm->getElement("study_year");?>
                   		<input id="study_year" />
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php //echo $frm->getElement("group");?>
                   		<input id="group" />
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("degree");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("grade_all");?>
                   </div>
                </div>
                <div class="form-group">
                	 <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("session");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("user");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("status");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
                   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>	



<script type="text/javascript">
dojo.require("dijit.form.CheckBox"); 
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");

dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.FilteringSelect"); 

dojo.require("dojo.html");
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
			getAllGroupByAcademic()
		}
	}, "study_year");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
		    
	    }
	}, "group");
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
    });
	 getAllAcademicByBranch();
	 getAllGroupByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->adv_search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->adv_search['study_year']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->adv_search['group']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}
var oldstudy_year = '<?php echo $this->search['study_year'];?>';
url_getgroupbyAca = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbyacademic'));?>';
function getAllGroupByAcademic(){
	dijit.byId('group').reset();
	study_year = dijit.byId('study_year').get('value');
	if(study_year=='' || study_year==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		//dijit.byId('study_year').focus();
		getAllGroupByBranch();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroupbyAca,
		content:{
			'academic_year':study_year,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldstudy_year==study_year){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}
	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 if(id!=''){
			window.location.href = url+'/id/'+id;
		 }else{
			alert('Please select record you want to copy');
			return false;
		 }
	}

	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}

	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
			
				var m = "clicked: " + key;
				if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}else if(key=="copy"){
					url='<?php echo $urlCopy;?>';
				}
				else if(key=="view"){
					url='<?php echo $urlView;?>';
				}else if(key=="stutrandrop"){
					url='<?php echo $urlTrandrop;?>';
				}
				
				gotoAction();
				//window.console && console.log(m) || alert(m); 
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
				"copy": {name: "<?php echo $tr->translate("COPY");?>", icon: "copy"},
				"view": {name: "<?php echo $tr->translate("Profile");?>", icon: "fa-user"},
				"stutrandrop": {name: "<?php echo $tr->translate("STUDENT_DROP");?>", icon: "fa-info-circle"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.open(url+row, '_blank');
		 //window.open(url+row);
	}
</script> 
