<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_STUDENT_CHANGE_GROUP')); 
?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
</script>
<div class="card">
	<div class="card-content collapse show">
		<form id="add_car" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentchangegroup','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
   				if(this.validate()){
					stu_id = dijit.byId('studentid').get('value');
					if(stu_id==0){
						dijit.byId("studentid").focus();
						alert("Select student !!! ");
						return false;
					}
					to_group = dijit.byId("to_group").get('value');		
					if(to_group==0){
						alert("Select group !!! ");
						dijit.byId("to_group").focus();
						return false;
					}
					dijit.byId('save_close').set('disabled',true);	
       				return true;
  				}else {
  					return false;
  				}
			</script>

			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-sitemap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_STUDENT_CHANGE_GROUP');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
    		<div class="card-box">
	        	<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDENT_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STUDENT_ID");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select class="fullside" readonly="readonly" name="studentid" id="studentid" dojoType="dijit.form.FilteringSelect" onchange="getStudentInfo();" >
						    	<?php if(!empty($this->stu_id))foreach ($this->stu_id as $stu_id){?>
									<option value="<?php echo $stu_id['id']?>"<?php if($stu_id['id']==$this->rows['stu_id']) echo 'selected="selected"';?>><?php echo $stu_id['stu_code']?></option>
								<?php }?>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STUDENT_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select class="fullside" readonly="readonly" name="studentname" id="studentname" dojoType="dijit.form.FilteringSelect" onchange="getStudentInfo();" >
						    	<?php if(!empty($this->stu_name))foreach ($this->stu_name as $stu_name){?>
									<option value="<?php echo $stu_name['id']?>"<?php if($stu_name['id']==$this->rows['stu_id']) echo 'selected="selected"';?>><?php echo $stu_name['name']?></option>
								<?php }?>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX")?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select dojoType="dijit.form.FilteringSelect"  readonly="readonly" class="fullside" id="gender" name="gender" type="text">
								<option value="1"><?php echo $tr->translate("MALE")?></option>
								<option value="2"><?php echo $tr->translate("FEMALE")?></option>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FROM_GROUP");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select dojoType="dijit.form.FilteringSelect" required="true" readonly="readonly" class="fullside" id="from_group" name="from_group" type="text" onchange="toStudentGroup(1);">
								<option value="0" placeholder="select group"><?php echo $tr->translate("SELECT_YEAR")?></option>
								<?php if(!empty($this->row))foreach ($this->row as $_row){?>
									<option value="<?php echo $_row['id']?>"<?php if($_row['id']==$this->rows['from_group']) echo 'selected="selected"';?>><?php echo $_row['group_code']?></option>
								<?php }?>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("DETAIL");?> :
	                   </label>
	                </div>
	                <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<label id="lblfromgroup" name="detail_from_group" style="font-size: 12px; background:#fff;width:100%;min-height:70px;display:block; padding: 10px; border: solid 1px #ccc;"></label>
	                   </div>
	                </div>
	           </div>
	           <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("GROUP_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TO_GROUP")?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="to_group" name="to_group" type="text" onchange="toStudentGroup(2);">
								<?php if(!empty($this->row))foreach ($this->row as $_row){?>
									<option value="<?php echo $_row['id']?>" <?php if($_row['id']==$this->rows['to_group']) echo 'selected="selected"';?>><?php echo $_row['group_code']?></option>
								<?php }?>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("MOVING_DATE")?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.DateTextBox"  class="fullside" id="moving_date" name="moving_date" value="<?php echo $this->rows['moving_date'];?>" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE")?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.TextBox" class="fullside"  value="<?php echo $this->rows['note'];?>" id="note" name="note" type="text" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS")?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select dojoType="dijit.form.FilteringSelect" class="fullside" id="status" name="status" type="text">
								<option value="1" <?php if($this->rows['status']==1) echo 'selected="selected"';?>><?php echo $tr->translate("ACTIVE")?></option>
								<option value="0" <?php if($this->rows['status']==0) echo 'selected="selected"';?>><?php echo $tr->translate("DEACTIVE")?></option>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("DETAIL");?> :
	                   </label>
	                </div>
	                <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<label id="lbltogroup"  name="detail_to_group" style="font-size: 12px; background:#fff;width:100%;min-height:70px;display:block; padding: 10px; border: solid 1px #ccc;"></label>
	                   </div>
	                </div>
	           </div>
       	  </div>
       	  <div class="clearfix"></div>
		    <div class="card-box">
               	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               			<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
						<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
						 iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'foundation','controller'=>"studentchangegroup",'action'=>'index'),null,true); ?>';" />
						<input type="submit" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
	    		</div>
	    	</div>
       </form>
	</div>
</div>

<script type="text/javascript">
var url_student = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentchangegroup','action'=>'get-student')); ?>';
dojo.ready(function(){
	getStudentInfo();
	toStudentGroup(1);
	toStudentGroup(2);
});
	function getStudentInfo(){
		studentid = dijit.byId('studentid').get('value');
		dojo.xhrPost({
			url:url_student,
			content:{
				'studentid':studentid
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId("gender").attr("value",data.sex);
			},
			error: function(err) {
				alert(err);
			}
		});
	}
var url_to_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentchangegroup','action'=>'get-to-group')); ?>';
function toStudentGroup(type){
	if(type==1){
		togroup = dijit.byId('from_group').get('value');
	}else{
		togroup = dijit.byId('to_group').get('value');
		}
	dojo.xhrPost({
		url:url_to_group,
		content:{
			'to_group':togroup
			},
		handleAs:"json",
		load: function(data) {
			if(type==1){
				dojo.byId('lblfromgroup').innerHTML='<span style="color:red;"><?php echo $tr->translate("ACADEMIC_YEAR")?> :  </span>'+data.year+"&nbsp;&nbsp;,&nbsp;&nbsp;"+'<span style="color:red;">  <?php echo $tr->translate("DEGREE")?> :  </span>'+data.degree+"&nbsp;&nbsp;,&nbsp;&nbsp;"+'<span style="color:red;">  <?php echo $tr->translate("GRADE")?> :  </span>'+data.grade+"<br />"+'<span style="color:red;">  <?php echo $tr->translate("SESSION")?> :  </span>'+data.session+"&nbsp;&nbsp;,&nbsp;&nbsp;"+'<span style="color:red;">  <?php echo $tr->translate("START_DATE")?> :  </span>'+data.start_date+"&nbsp;&nbsp;,&nbsp;&nbsp;"+'<span style="color:red;">  <?php echo $tr->translate("EXPIRE_DATE")?> :  </span>'+data.expired_date;
			}else{
				dojo.byId('lbltogroup').innerHTML='<span style="color:red;"><?php echo $tr->translate("ACADEMIC_YEAR")?> :  </span>'+data.year+"&nbsp;&nbsp;,&nbsp;&nbsp;"+'<span style="color:red;">  <?php echo $tr->translate("DEGREE")?> :  </span>'+data.degree+"&nbsp;&nbsp;,&nbsp;&nbsp;"+'<span style="color:red;">  <?php echo $tr->translate("GRADE")?> :  </span>'+data.grade+"<br />"+'<span style="color:red;">  <?php echo $tr->translate("SESSION")?> :  </span>'+data.session+"&nbsp;&nbsp;,&nbsp;&nbsp;"+'<span style="color:red;">  <?php echo $tr->translate("START_DATE")?> :  </span>'+data.start_date+"&nbsp;&nbsp;,&nbsp;&nbsp;"+'<span style="color:red;">  <?php echo $tr->translate("EXPIRE_DATE")?> :  </span>'+data.expired_date;
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>