<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_GROUP_STUDENT_CHANGE_GROUP')); 
?>

<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.CheckBox");
</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		   			<h4 class="m-b-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_GROUP_STUDENT_CHANGE_GROUP');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<div class="card-box">
    		<form id="add_car" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<script type="dojo/method" event="onSubmit" >			
					if(this.validate()) {
						branch_id = dijit.byId('branch_id').get('value');
						if(branch_id==''){
							alert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>');
							dijit.byId('branch_id').focus();
							return false;
						}
               			 from_group=dijit.byId('from_group').get('value');
                		 to_group=dijit.byId('to_group').get('value');
               			 if(from_group==0 || from_group==''){
                        	alert('<?php echo $tr->translate("PLEASE_SELECT_FROM_GROUP");?>');
							dijit.byId('from_group').focus();
							return false;	
                		}
						if(to_group==0 || to_group==''){
                        	alert('<?php echo $tr->translate("PLEASE_SELECT_TO_GROUP");?>');
							dijit.byId('to_group').focus();
							return false;	
               		 	}
                		if(from_group==to_group){
                			alert("'<?php echo $tr->translate("From Group and To Group Can not The Same");?> !"); 
							dijit.byId('to_group').focus();
							return false;
						}
						loadingBlock();	
					}else {
						return false;
					}
				</script>
				<div class="card-box">
		        	<div class="col-md-8 col-sm-8 col-xs-12 search-blog">
						<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("FROM_GROUP");?> 
		                   </label>
		                </div>
		                <div class="form-group">
			                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
			                <div class="col-md-7 col-sm-7 col-xs-12">
			                	<?php $counbranhc = count($this->branch);?>
			                	<select class="fullside" <?php if ($counbranhc==1){ echo 'readonly="readonly"';}?> tabindex="15" name="branch_id" queryExpr="*${0}*" autoComplete="false" id="branch_id" dojoType="dijit.form.FilteringSelect" onchange="getAllGroupByBranch();">
									<option value=""><?php echo $tr->translate("PLEASE_SELECT_BRANCH");?></option>
									<?php if(!empty($this->branch))foreach ($this->branch as $row){?>
									<option value="<?php echo $row['id']?>" <?php if ($counbranhc==1){ echo 'selected="selected"';}?>><?php echo $row['name']?></option>
									<?php }?>
								</select>
			                </div>
			             </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FROM_GROUP");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input id="from_group" />
		                   		
		                   </div>
		                </div>
		                 <div class="form-group">
		                   <label class="control-label  col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("DETAIL")?> :
		                   </label>
		                </div>
		                <div class="form-group">
		                   <div class="col-md-12 col-sm-12 col-xs-12">
		                   		<label id="lblfromgroup" name="detail_from_group" style="background:#fff;height:70px;display:block; font-size: 14px; padding: 10px; border: solid 1px #ccc;"></label>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <div id="data_table" style="min-height: 300px !important;overflow-y: auto; padding: 5px; border: solid 1px #ccc;" class="col-md-12 col-sm-12 col-xs-12">
		                   </div>
		                </div>
		            </div>
		            <div class="col-md-4 col-sm-4 col-xs-12 search-blog">
		            	<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("TO_GROUP");?> 
		                   </label>
		                </div>
			            <div class="form-group">
		                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TO_GROUP");?> <span class="required">*</span> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		 <div class="col-md-7 col-sm-7 col-xs-12">
		                   			<select style="width: 100%;" dojoType="dijit.form.FilteringSelect" required="required"  id="to_group" name="to_group" type="text"   queryExpr="*${0}*" autoComplete="false" placeholder="to group" onchange="toStudentGroup(2);popupAddGroup();">
										<option value="0" ><?php echo $tr->translate("SELECT_GROUP")?></option>
										<option value="-1" ><?php echo $tr->translate("ADD_NEW")?></option>
										<?php if(!empty($this->rs))foreach ($this->rs as $_row){?>
											<option value="<?php echo $_row['id']?>"><?php echo $_row['group_code']?></option>
										<?php }?>
									</select>
		                   		</div>
		                   		<div class="col-md-3 col-sm-3 col-xs-12">
		                   			<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshGroup();"/>
		                   		</div>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("DETAIL")?> :
		                   </label>
		                </div>
		                <div class="form-group">
		                   <div class="col-md-12 col-sm-12 col-xs-12">
		                   		<label id="lbltogroup" class="fullside"  name="detail_to_group" style="background:#fff;width:100%;height:100px;display:block; font-size: 14px;  padding: 5px; border: solid 1px #ccc;"></label>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TYPE");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<select  class="fullside" dojoType="dijit.form.FilteringSelect"  class="fullside" id="change_type" name="change_type" type="text">
										<?php if(!empty($this->change_type)){foreach ($this->change_type as $rs){?>
											<option value="<?php echo $rs['id']?>"><?php echo $rs['name']?></option>
										<?php }}?>
									</select>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("MOVING_DATE");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input class="fullside" dojoType="dijit.form.DateTextBox"   id="moving_date" name="moving_date" value="now" type="text">
		                   </div>
		                </div>
		                 <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="note" name="note" type="text" />
		                   </div>
		                </div>
		                 <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<select  class="fullside" dojoType="dijit.form.FilteringSelect"  class="fullside" id="status" name="status" type="text">
									<option value="1"><?php echo $tr->translate("ACTIVE")?></option>
									<option value="0"><?php echo $tr->translate("DEACTIVE")?></option>
								</select>
								<input dojoType="dijit.form.TextBox"  type="hidden" name="identity" id="identity" />
		                   </div>
		                </div>
		                <div class="form-group">
		                   <div class="col-md-12 col-sm-12 col-xs-12 text-center">
		                   		<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" onclick="clear();" dojoType="dijit.form.Button"/>
								<input type="submit" id="save_close" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
								<input type="submit" value="save_new" id="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
		                   </div>
		                </div>
			        </div>
			     </div>
			</form>
    	</div>
   </div>
</div>
<script type="text/javascript">
dojo.ready(function(){
	new dijit.form.FilteringSelect({
	    autoComplete: true,                        
	    id: "grade_group",
	    name: "grade_group",           
	    class: 'fullside',  
	    placeHolder:"Selected Grade",          
	}, "grade_group");
	getallGrade(2);
}); 

var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'get-grade')); ?>';
		function getallGrade(type){
			if(type==1){
				dept_id = dijit.byId('degree').get('value');
			}
			else if(type==2){
				dept_id = dijit.byId('degree_group').get('value');
			}
				dojo.xhrPost({
					url:url_dept,
					content:{
						'dept_id':dept_id,
						},
					handleAs:"json",
					load: function(data) {
						if(type==1){
							grade_store  = getDataStorefromJSON('id','name', data);
						    dijit.byId('grade').set('store',grade_store);   
						    dijit.byId('grade').attr('value','<?php echo $this->value['grade']; ?>');  
						}
						else{
							grade_store  = getDataStorefromJSON('id','name', data);
							dijit.byId('grade_group').set('store',grade_store); 
						}
					},
					error: function(err) {
					}
				});
		}

</script>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:28cm;" id="popup_dept" >
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table width="100%">
				<tr>
					<td>
							<fieldset style="margin-top:-13px;">
								<legend align="center" ><strong>Create New Group</strong></legend>
								<table style="margin: 0 auto; white-space: nowrap;" cellspacing="10">
									<tr>
										<td><?php echo $tr->translate("GROUP_CODE")?></td>
										<td>
											<input dojoType="dijit.form.ValidationTextBox" required="true" id="group_code" name="group_code" value="" type="text">
										</td>
									    <td><?php echo $tr->translate("ACADEMIC_YEAR")?></td>
										<td>
											<select name="academic_year" id="academic_year" type="text" dojoType="dijit.form.FilteringSelect">
												<option value="0">Select AcademicYear</option>
												<?php if(!empty($this->academy)){ foreach ($this->academy as $row){?>
													<option value="<?php echo $row['id'];?>"><?php echo $row['years']; ?></option>
												<?php }}?>
										    </select>
										</td>
										<td ><?php echo $tr->translate("DEGREE")?></td>
										<td>
											<select name="degree_group" id="degree_group" type="text" dojoType="dijit.form.FilteringSelect" onchange="getallGrade(2);">
													<?php if(!empty($this->degree))foreach ($this->degree as $row){?>
														<option value="<?php echo $row['dept_id']?>"<?php if($row['dept_id']==$this->value['degree']) echo "selected='selected'"?>><?php echo $row['en_name']?></option>
													<?php }?>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("GRADE")?></td>
										<td>
											<input id="grade_group" name="grade_group" />
										</td>
										<td><?php echo $tr->translate("SEMESTER")?></td>
										<td><input dojoType="dijit.form.ValidationTextBox" required="true" name="semester" value="" type="text"></td>
										<td><?php echo $tr->translate("SESSION")?></td>
										<td>
											<select name="session_group" id="session_group" dojoType="dijit.form.FilteringSelect">
												<?php if(!empty($this->rs_session)){ foreach ($this->rs_session as $row){?>
													<option value="<?php echo $row['key_code'];?>"><?php echo $row['view_name']; ?></option>
												<?php }}?>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("START_DATE")?></td>
										<td><input dojoType="dijit.form.DateTextBox" name="start_date" id="start_date" onchange="setEndDate();" value="now" type="text"></td>
										<td><?php echo $tr->translate("AMOUNT_MONTH")?></td>
										<td><input dojoType="dijit.form.NumberTextBox"   name="amountmonth" id="amountmonth" value="" onkeyup="setEndDate();" type="text"></td>
										<td><?php echo $tr->translate("END_DATE")?></td>
										<td><input dojoType="dijit.form.DateTextBox" id="end_date" name="end_date" type="text" value="now" ></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("ROOM_NAME")?></td>
										<td>
											<select name="room" id="room" dojoType="dijit.form.FilteringSelect" >
												<?php if(!empty($this->room))foreach ($this->room as $row){?>
														<option value="<?php echo $row['room_id']?>"><?php echo $row['room_name']?></option>
												<?php }?>
											</select>
										</td>
										<td><?php echo $tr->translate("TIME")?></td>
										<td>
											<select name="time" id="time" dojoType="dijit.form.FilteringSelect" >
												<option value="-1"><?php echo $tr->translate("SELECT_TIME")?></option>
												<option value="1">Part Time</option>
												<option value="2">Full Time</option>
											</select>
										</td>
										<td><?php echo $tr->translate("NOTE")?></td>
										<td><input dojoType="dijit.form.TextBox"   name="note" value="" type="text"></td>
										
									</tr>
									<tr>
										<td colspan="6" align="center">
											<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="CLEAR" dojoType="dijit.form.Button"/>
											<input type="button" value="close" name="close" label="Close" dojoType="dijit.form.Button" 
													iconClass="dijitEditorIcon dijitEditorIconClose" onClick="HidePopupGroup()" />
											<input type="button" value="save" name="save_new" label="SAVE" dojoType="dijit.form.Button" 
													iconClass="dijitEditorIcon dijitEditorIconSave" onClick="addGroup()" />
										</td>
									</tr>
								</table>
							</fieldset>
					</td>
				</tr>
			</table>
		</form>
		
	</div>
</div>


<script type="text/javascript">
var url_getservice = '<?php echo $this->url(array("module"=>"global","controller"=>"group","action"=>"refreshservice"));?>';										
function getRefreshGroup(){
	loading();
	dojo.xhrPost({
		url:url_getservice,
		handleAs:"json",
		load: function(data) {
			group_store  = getDataStorefromJSON('id','name', data.group);
		    dijit.byId('to_group').set('store',group_store);  
		    //degree_store  = getDataStorefromJSON('id','name', data.degree);
		    //dijit.byId('degree').set('store',degree_store);  
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
var url_get_all_student_from_group = "<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'get-all-student')); ?>";
	function getStudentFromGroup(){
			from_group = dijit.byId('from_group').get('value');
			if(from_group==0 || from_group==""){
				dojo.byId('data_table').innerHTML = "";
				return false;
			}
	
			//alert(from_group);
			dojo.xhrPost({
				url:url_get_all_student_from_group,
				content:{
					'from_group':from_group
					},
				handleAs:"json",
				load: function(respone) {
					tem='<table border="1" style="border:1px solid #000;border-collapse:collapse; font-size:12px;background-color:white;width: 99.5%;font-family: Khmer OS Battambang, Times New Roman;"  id="table" >'
						+'<thead><tr style="background: #bcd5f0;min-height: 30px;font-size:13px;"><th><?php echo $tr->translate('NUM');?></th>'
							+'<th><?php echo $tr->translate('CODE');?></th>'
							+'<th><?php echo $tr->translate('NAME_KH');?></th>'
							+'<th><?php echo $tr->translate('NAME_EN');?></th>'
							+'<th colspan="2"><?php echo $tr->translate('SEX');?></th>'
							+'<th style="white-space:nowrap; border-right: 0px none;" colspan="1"><input style="height: 13px;" type="checkBox" value="0" checked="checked" name="checkall" onclick="check('+respone.length+');setValue('+respone.length+');" id="checkall"/></th>'
							+'<th style="white-space:nowrap;border-left: 0px none;" > <?php echo $tr->translate('ALL');?></th></tr>'
						+'</thead>';
					if(respone!=""){
						num=0;
						for(var i=0;i<respone.length;i++){
							inx = i+1;

								tem += '<tr style="border:1px solid #000;">';
							
							    tem += '<td align="center">&nbsp;'+inx+'&nbsp;<input type="hidden"  name="stu_id_'+inx+'" id="stu_id_'+inx+'" value="'+respone[i].stu_id+'" /></td>';
								tem += '<td>&nbsp;<label>'+respone[i].stu_code+'</label></td>';
								tem += '<td>&nbsp;<label>'+respone[i].stu_khname+'</label></td>';
								tem += '<td>&nbsp;<label>'+respone[i].stu_enname+'</label></td>';
								tem += '<td colspan="2" align="center">&nbsp;<label>'+respone[i].sex+'</label></td>';
								tem += '<td align="center" colspan="2"><input style="height: 13px;" type="checkBox" checked="checked" value="'+inx+'" onclick="setValue('+respone.length+');" name="checkbox'+inx+'" id="checkbox'+inx+'"/></td>';
							    tem += '</tr>';

							    if($("#identity").val()!="") {
									var identity = $("#identity").val();
									$("#identity").val(identity+','+inx);
								} else {$("#identity").val(inx);}

						}
					}
					tem+='</table>';
					dojo.byId('data_table').innerHTML = tem;
				},
				error: function(err) {
					alert(err);
				}
			});
	}

var url_to_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'get-to-group')); ?>';
function toStudentGroup(type){
	//alert(type);
	if(type==1){
		togroup = dijit.byId('from_group').get('value');

		if(togroup==0){
			//alert("Please Select Group"); 
			dojo.byId('lblfromgroup').innerHTML='';
			return false;
		}
	}else{
			togroup = dijit.byId('to_group').get('value');
			if(togroup==0 ){
				//alert("Please Select Group"); 
				dojo.byId('lbltogroup').innerHTML='';
				return false;
			}
		}
	dojo.xhrPost({
		url:url_to_group,
		content:{
			'to_group':togroup,
			'type'	  :type,
			},
		handleAs:"json",
		load: function(data) {
			//alert(data.year);
			if(type==1){
				dojo.byId('lblfromgroup').innerHTML='<span style="color:red;"><?php echo $tr->translate("ACADEMIC_YEAR")?> :  </span>'+data.year+'<span style="color:red;">  <?php echo $tr->translate("DEGREE")?> :  </span>'+data.degree+'<span style="color:red;">  <?php echo $tr->translate("GRADE")?> :  </span>'+data.grade+'<span style="color:red;">  <?php echo $tr->translate("SESSION")?> :  </span>'+data.session+'<span style="color:red;">  <?php echo $tr->translate("START_DATE")?> :  </span>'+data.start_date+'<span style="color:red;">  <?php echo $tr->translate("EXPIRE_DATE")?> :  </span>'+data.expired_date;
			}else{
				dojo.byId('lbltogroup').innerHTML='<span style="color:red;"><?php echo $tr->translate("ACADEMIC_YEAR")?> :  </span>'+data.year+'<span style="color:red;">  <?php echo $tr->translate("DEGREE")?> :  </span>'+data.degree+'<span style="color:red;">  <?php echo $tr->translate("GRADE")?> :  </span>'+data.grade+'<span style="color:red;">  <?php echo $tr->translate("SESSION")?> :  </span>'+data.session+'<span style="color:red;">  <?php echo $tr->translate("START_DATE")?> :  </span>'+data.start_date+'<span style="color:red;">  <?php echo $tr->translate("EXPIRE_DATE")?> :  </span>'+data.expired_date;
			}
			if(type==1){
				dijit.byId('identity').attr('value','');
			}else{
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}
function setValue(i){
	$('#identity').val('');
	for(var j=1;j<=i;j++){
		if(dojo.byId('checkbox'+j).checked){
			if($("#identity").val()!="") {
				var iden = $("#identity").val();
				$("#identity").val(iden+','+j);
			} else{
				$("#identity").val(j);
			}
		}
	}
}

function check(i){
	if(dojo.byId('checkall').checked){
		for(var j=1;j<=i;j++){
			$("#checkbox"+j).attr('checked', 'checked');
		}
	}else{
		for(var j=1;j<=i;j++){
			$("#checkbox"+j).removeAttr("checked");
		}
	}
}

function clear(){
	dojo.byId('lblfromgroup').innerHTML='';
	dojo.byId('lbltogroup').innerHTML='';
	dijit.byId("studentid").attr("value",'');
	dijit.byId("from_group").attr("value",'');
	dijit.byId("studentname").attr("value",'');
	dijit.byId("to_group").attr("value",'');
	dijit.byId("moving_date").attr("value",'');
	dijit.byId("note").attr("value",'');
	clear1();
}

function popupAddGroup(){
	id = dijit.byId('to_group').get('value');
	if(id==-1){
		window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/group/add";?>','_blank');
	}
}
function HidePopupGroup(){
	dijit.byId("popup_dept").hide();
}

//var url_add_group = '<?php //echo $this->url(array('module'=>'foundation','controller'=>'studentgroup','action'=>'add-group')); ?>';
var group_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->g_new));?> );
var url_add_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'add-group')); ?>';
function addGroup(){
	 if(dijit.byId('frm_add_tran').validate()){
		group_code= dijit.byId('group_code').get('value');
		academic_year=dijit.byId('academic_year').get('value');
		degree_group=dijit.byId('degree_group').get('value');
		room=dijit.byId("room").get("value");
		if(academic_year=='' || academic_year==0){
			alert('Please selecte academic year !');
			return false;
			dijit.byId('academic_year').focus();
		}
		if(degree_group=='' || degree_group==0){
			alert('Please selecte degree!');
			return false;
			dijit.byId('degree_group').focus();
		}
		if(room=='' || room==0){
			alert('Please room degree!');
			return false;
			dijit.byId('room').focus();
		}
		dojo.xhrPost({
				url:url_add_group,
				form: dojo.byId("frm_add_tran"),
				handleAs:"json",
				load: function(data) {
					var Itemmake = {     
						      id: data,
						      name: dijit.byId('group_code').get('value')
						    };
			    addDataToSelectbox(dijit.byId('to_group'), group_store, Itemmake, data);
			    dijit.byId('frm_add_tran').reset();
			    dijit.byId("popup_dept").hide();
				},
				error: function(err) {
					alert(err);
				}
		});
	 }
}

function setEndDate(){
	amount_date = dijit.byId('amountmonth').get('value');
	release_date = dijit.byId("start_date").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		mm = a.getMonth()+amount_date+1;
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('end_date').attr('value',epx_date);	
    }
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "from_group",
	    name: "from_group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
	    	group_id = dijit.byId('from_group').get('value');
	    	toStudentGroup(1);
	    	getStudentFromGroup();
	    }
	}, "from_group");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "to_group",
	    name: "to_group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
	    	group_id = dijit.byId('to_group').get('value');
	    	toStudentGroup(2);
	    	popupAddGroup();
	    }
	}, "to_group");
	
	getAllGroupByBranch();
}); 
url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('from_group').reset();
	dijit.byId('to_group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('from_group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('from_group').set('store',group_store); 
		    dijit.byId('to_group').set('store',group_store);     
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("/psst/trunk/public/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>