<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_GROUP_STUDENT_CHANGE_GROUP')); 
	$frm =  $this->frm;
?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		   			<h4 class="m-b-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_GROUP_STUDENT_CHANGE_GROUP');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
    	<div class="card-box">
    		<form id="add_car" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<script type="dojo/method" event="onSubmit" >			
					if(this.validate()) {
						identity = dijit.byId('identity').get('value');
						if(identity==''){
							alert('<?php echo $tr->translate("No Student");?>');
							return false;
						}
						branch_id = dijit.byId('branch_id').get('value');
						if(branch_id==''){
							alert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>');
							dijit.byId('branch_id').focus();
							return false;
						}
						changeType = dijit.byId('change_type').get('value');
						if(changeType==3){
							academicYear=dijit.byId('academic_year').get('value');
               			 	if(academicYear==0 || academicYear==''){
                        		alert('<?php echo $tr->translate("PLEASE_SELECT_FEE_STUDY");?>');
								dijit.byId('academic_year').focus();
								return false;	
                			}
							degreeId=dijit.byId('degree').get('value');
               			 	if(degreeId==0 || degreeId==''){
                        		alert('<?php echo $tr->translate("PLEASE_SELECT_DEGREE");?>');
								dijit.byId('degree').focus();
								return false;	
                			}
							gradeId=dijit.byId('grade').get('value');
               			 	if(gradeId==0 || gradeId==''){
                        		alert('<?php echo $tr->translate("PLEASE_SELECT_GRADE");?>');
								dijit.byId('grade').focus();
								return false;	
                			}
						}else{
							from_group=dijit.byId('from_group').get('value');
                			 to_group=dijit.byId('to_group').get('value');
               			 	if(from_group==0 || from_group==''){
                        		alert('<?php echo $tr->translate("PLEASE_SELECT_FROM_GROUP");?>');
								dijit.byId('from_group').focus();
								return false;	
                			}
							if(to_group==0 || to_group==''){
                        		alert('<?php echo $tr->translate("PLEASE_SELECT_TO_GROUP");?>');
								dijit.byId('to_group').focus();
								return false;	
               		 		}
                			if(from_group==to_group){
                				alert("<?php echo $tr->translate("From Group and To Group Can not The Same");?> !"); 
								dijit.byId('to_group').focus();
								return false;
							}
						}
               			 
						//loadingBlock();	
					}else {
						return false;
					}
				</script>
				<div class="card-box">
		        	<div class="col-md-8 col-sm-8 col-xs-12 search-blog">
						<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("FROM_GROUP");?> 
		                   </label>
		                </div>
		                <div class="form-group">
			                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
			                <div class="col-md-7 col-sm-7 col-xs-12">
			                	<?php echo $frm->getElement("branch_id");?>
			                </div>
			            </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FROM_GROUP");?> <span class="required">*</span> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input id="from_group" />
		                   		<?php echo $frm->getElement("from_degree");?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <div class="col-md-12 col-sm-12 col-xs-12">
		                   		<div id="lblfromgroup" ></div>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <div class="col-md-12 col-sm-12 col-xs-12">
		                   		<ul style="list-style: none; padding: 0;">
		                   			<li>
		                   				<span>&#x2611;</span> <?php echo $tr->translate("PASS")?> / <?php echo $tr->translate("CHANGE")?>
		                   			</li>
		                   			<li>
		                   				<span>&#x2610;</span> <?php echo $tr->translate("FAIL")?> / <?php echo $tr->translate("NOT_CHANGE")?>
		                   			</li>
		                   			<li>
		                   				<?php echo $tr->translate("TOTAL_STUDENT_SELECTED")?><label id="lblStudentSelected"></label>
		                   			</li>
		                   		</ul>
		                   </div>
		                </div>
						
		                <div class="form-group">
		                   <div id="data_table" style="min-height: 300px !important;overflow-y: auto; padding: 5px; border: solid 1px #ccc;" class="col-md-12 col-sm-12 col-xs-12">
		                   </div>
						   <input type="text" name="all_student" id="all_student" dojoType="dijit.form.TextBox"  />
		                </div>
		            </div>
		            <div class="col-md-4 col-sm-4 col-xs-12 search-blog">
		            	<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("NEW_STUDY_INFORMATION");?> 
		                  <input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshGroup();"/>
		                   </label>
		                </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TYPE");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $frm->getElement("change_type");?>
		                   </div>
		                </div>
		                 <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("MOVING_DATE");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement("moving_date");?>
		                   </div>
		                </div>
		                 <div class="form-group upDegreeStudent">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FEE");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input id="academic_year" />
		                   </div>
		                </div>  
		                <div class="form-group upDegreeStudent">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DEGREE");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input id="degree" />
		                   </div>
		                </div>  
		                <div class="form-group upDegreeStudent">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GRADE");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input id="grade" />
		                   </div>
		                </div>  
		                <div class="form-group otherCondiction">
		                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ACADEMIC_YEAR");?> <span class="required">*</span> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		 <input id="study_year" />
		                   </div>
		                </div>
			            <div class="form-group otherCondiction">
		                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TO_GROUP");?> <span class="required">*</span> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		 	<input id="to_group" />
		                   </div>
		                </div>
		                <div class="form-group">
		                   <div class="col-md-12 col-sm-12 col-xs-12">
		                   		<div id="lbltogroup"   name="detail_to_group" ></div>
		                   </div>
		                </div>
		                
		               
		                 <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement("note");?>
								<input dojoType="dijit.form.TextBox"  type="text" name="identity" id="identity" />
		                   </div>
		                </div>
		                <div class="form-group">
		                   <div class="col-md-12 col-sm-12 col-xs-12 text-center">
		                   		<input type="submit" id="save_close" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
								<input type="submit" value="save_new" id="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
		                   </div>
		                </div>
			        </div>
			    </div>
			</form>
    	</div>
   </div>
</div>
<style>
ul.listFor {
    list-style: none;
    margin: 0;
    padding: 10px;
    border: solid 1px #02014a;
    width: 100%;
    display: block;
    background: #feffca;
    border-radius: 5px;
}
li.row-value {
    display: inline-block;
    width: 50%;
}
li.row-value span.title {
    min-width: 22%;
    display: inline-block;
    font-weight: 600;
    color: #0063a5;
}
li.row-value span.value {
    color: #02014a;
}

table#table {
    border: 1px solid #000;
    border-collapse: collapse;
    font-size: 12px;
    background-color: white;
    width: 99.5%;
    font-family: 'Times New Roman','Khmer OS Battambang';
}
table#table tr.header-row td {
    background: #02014a;
    font-size: 14px;
    font-weight: bold;
    color: #fff;
    padding: 5px 1px;
}
table#table tr td {
    padding: 3px 1px;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");

var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var degree_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
study_yearStore = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                     
		id: "academic_year",
		name: "academic_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('academic_year').get('value');
		}
	}, "academic_year");

	new dijit.form.FilteringSelect({
		store: degree_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,
		id: "degree",
		name: "degree",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_DEGREE");?>",          
		onChange: function() {  
			getallGrade();
		}
	}, "degree");
	
	new dijit.form.FilteringSelect({
	    queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                   
	    id: "grade",
	    name: "grade",  
	    tabindex: "16",  
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
	    onChange: function() {  
	    }
	}, "grade");
	
	
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
	    id: "from_group",
	    name: "from_group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function(){  
	    	group_id = dijit.byId('from_group').get('value');
	    	toStudentGroup(1);
	    	getStudentFromGroup();
	    	getRefreshItems();
	    }
	}, "from_group");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
	    id: "to_group",
	    name: "to_group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
	    	group_id = dijit.byId('to_group').get('value');
	    	toStudentGroup(2);
	    	popupAddGroup();
	    }
	}, "to_group");

	new dijit.form.FilteringSelect({
		store: study_yearStore,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			getAllGroupByBranch();
		}
	}, "study_year");

	getStudyYear();
	getAllGroupByBranch();

	var branch_id = dijit.byId('branch_id');
	branch_id.on('change', function(evt) {
		getAllGroupByBranch();
		getAllAcademicByBranch();
	});
	var change_type = dijit.byId('change_type');
	change_type.on('change', function(evt) {
		changeTypeMove()
	});
	getAllAcademicByBranch();
	getRefreshItems();
	getallGrade();
	changeTypeMove();
}); 


function changeTypeMove(){
	changeType = dijit.byId('change_type').get('value');
	if(changeType==3){
		$(".upDegreeStudent").css("display", "flow-root");
		$(".otherCondiction").css("display", "none");
	}else{
		$(".otherCondiction").css("display", "flow-root");
		$(".upDegreeStudent").css("display", "none");
		getAllGroupByBranch(1);
	}
}
url_getacademic = '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'getfeeid'));?>';
function getAllAcademicByBranch(){
	dijit.byId('academic_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('academic_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id,
			'selectOption':1
			},
		handleAs:"json",
		load: function(data){
			academic_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('academic_year').set('store',academic_store);  
		},
		error: function(err) {
		}
	});
}

url_getstudyYear= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
function getStudyYear(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		dijit.byId('study_year').set('store',study_yearStore);  
		dijit.byId('branch_id').focus();
		return false;
	}
	
		contentData = {
			'branch_id':branch_id
		}
		
		getAllYear(url_getacademic,contentData);
		
}
function getRefreshItems(){
	dijit.byId('degree').reset();   
	var url_getItems = '<?php echo $this->url(array("module"=>"global","controller"=>"degree","action"=>"refreshitems"));?>';										
	dojo.xhrPost({
		url: url_getItems,
		content:{
			'items_type':1
			},
		handleAs:"json",
		load: function(data) {

			var degreeId = dijit.byId('from_degree').get('value');  
			var data = $.grep(data, function(e){ 
			     return e.id != degreeId; 
			});
			
			degree_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('degree').set('store',degree_store);  
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);   
			},
			error: function(err) {
			}
		});
}


var url_getgroup1 = '<?php echo $this->url(array("module"=>"foundation","controller"=>"group","action"=>"getgroup"));?>';										
function getRefreshGroup(){
	branch_id = dijit.byId('branch_id').get('value');
	study_year = dijit.byId('study_year').get('value');
	loadingBlock();	
	dojo.xhrPost({
		url:url_getgroup1,
		content:{
			'branch_id':branch_id,
			'academic_year':study_year
		},
		handleAs:"json",
		load: function(data) {
			group_store  = getDataStorefromJSON('id','name', data.group);
			dijit.byId('to_group').set('store',group_store);  
			HideloadingBlock();
		},
		error: function(err) {
			HideloadingBlock();
		}
	});
}

var url_get_all_student_from_group = "<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'get-all-student')); ?>";
function getStudentFromGroup(){
	from_group = dijit.byId('from_group').get('value');
	if(from_group==0 || from_group==""){
		dojo.byId('data_table').innerHTML = "";
		return false;
	}
	dijit.byId('all_student').attr('value','');
	dojo.xhrPost({
		url:url_get_all_student_from_group,
		content:{
			'from_group':from_group
			},
		handleAs:"json",
		load: function(respone){
			tem='<table border="1"   id="table" >'
				+'<thead><tr align="center" class="header-row"><td><?php echo $tr->translate('NUM');?></td>'
					+'<td><?php echo $tr->translate('STUDENT_CODE');?></td>'
					+'<td><?php echo $tr->translate('STUDENT_NAMEKHMER');?></td>'
					+'<td><?php echo $tr->translate('NAME_EN');?></td>'
					+'<td colspan="2"><?php echo $tr->translate('SEX');?></td>'
					+'<td style="white-space:nowrap; border-right: 0px none;" colspan="1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input style="height: 13px;" type="checkBox" value="0" checked="checked" name="checkall" onclick="check('+respone.length+');setValue('+respone.length+');" id="checkall"/></td>'
					+'<td align="left" style="white-space:nowrap;border-left: 0px none;" > <?php echo $tr->translate('ALL');?></td></tr>'
				+'</thead>';
			if(respone!=""){
				num=0;
				all_student = respone.length;
				dijit.byId('all_student').attr('value',all_student);
				for(var i=0;i<respone.length;i++){
					inx = i+1;
					tem += '<tr style="border:1px solid #000;">';
					tem += '<td align="center">&nbsp;'+inx+'&nbsp;<input type="hidden"  name="stu_id_'+inx+'" id="stu_id_'+inx+'" value="'+respone[i].stu_id+'" /></td>';
					tem += '<td>&nbsp;'+respone[i].stu_code+'</td>';
					tem += '<td>&nbsp;'+respone[i].stu_khname+'</label></td>';
					tem += '<td>&nbsp;'+respone[i].last_name+" "+respone[i].stu_enname+'</td>';
					tem += '<td colspan="2" align="center">&nbsp;'+respone[i].sex+'</td>';
					tem += '<td align="center" colspan="2"><input style="height: 13px;" type="checkBox" checked="checked" value="'+inx+'" onclick="setValue('+respone.length+');" name="checkbox'+inx+'" id="checkbox'+inx+'"/></td>';
					tem += '</tr>';
					if($("#identity").val()!="") {
						var identity = $("#identity").val();
						$("#identity").val(identity+','+inx);
					} else {$("#identity").val(inx);}
				}
			}
			tem+='</table>';
			dojo.byId('data_table').innerHTML = tem;
		},
		error: function(err) {
		}
	});
}
var url_to_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'get-to-group')); ?>';
function toStudentGroup(type){
	if(type==1){
		dijit.byId('from_degree').set('value',"");  
		dijit.byId('identity').attr('value','');
		togroup = dijit.byId('from_group').get('value');
		if(togroup==0){
			dojo.byId('lblfromgroup').innerHTML='';
			return false;
		}
	}else{
		togroup = dijit.byId('to_group').get('value');
		if(togroup==0 ){
			dojo.byId('lbltogroup').innerHTML='';
			return false;
		}
	}
	dojo.xhrPost({
		url:url_to_group,
		content:{
			'to_group':togroup,
			'type'	  :type,
			},
		handleAs:"json",
		load: function(data) {
			if(type==1){
				dijit.byId('from_degree').set('value',data.degree_id);  
				string='';
				string+='<ul class="listFor">';
					string+='<li class="row-value"><span class="title"><?php echo $tr->translate("ACADEMIC_YEAR")?></span> <span class="value">:'+data.year+'</span></li>';
					string+='<li class="row-value"><span class="title"><?php echo $tr->translate("DEGREE")?></span> <span class="value">:'+data.degree+'</span></li>';
					string+='<li class="row-value"><span class="title"><?php echo $tr->translate("GRADE")?></span> <span class="value">:'+data.grade+'</span></li>';
					string+='<li class="row-value"><span class="title"><?php echo $tr->translate("SESSION")?></span> <span class="value">:'+data.session+'</span></li>';
				string+='</ul>';
				dojo.byId('lblfromgroup').innerHTML=string;
				getAllGroupByBranch(1);
			}else{
				string='';
				string+='<ul class="listFor">';
					string+='<li class="row-value"><span class="title"><?php echo $tr->translate("ACADEMIC_YEAR")?></span> <span class="value">:'+data.year+'</span></li>';
					string+='<li class="row-value"><span class="title"><?php echo $tr->translate("DEGREE")?></span> <span class="value">:'+data.degree+'</span></li>';
					string+='<li class="row-value"><span class="title"><?php echo $tr->translate("GRADE")?></span> <span class="value">:'+data.grade+'</span></li>';
					string+='<li class="row-value"><span class="title"><?php echo $tr->translate("SESSION")?></span> <span class="value">:'+data.session+'</span></li>';
				string+='</ul>';
				dojo.byId('lbltogroup').innerHTML=string;
			}
		},
		error: function(err) {
		}
	});
}
function setValue(i){
	$('#identity').val('');
	for(var j=1;j<=i;j++){
		if(dojo.byId('checkbox'+j).checked){
			if($("#identity").val()!="") {
				var iden = $("#identity").val();
				$("#identity").val(iden+','+j);
			} else{
				$("#identity").val(j);
			}
		}
	}
	countStudentSelected();
}
function countStudentSelected(){
	$('#lblStudentSelected').html('');
	identitys = $('#identity').val();
	if(identitys!=''){
		arraysStu = identitys.split(',');
		$('#lblStudentSelected').html(arraysStu.length);
	}
}
function check(i){
	if($('#checkall').is(":checked")){setValue
		for(var j=1;j<=i;j++){
			$('#checkbox'+j).each(function() { //loop through each checkbox
	            this.checked = true;  
			});
		}
	}else{
		for(var j=1;j<=i;j++){
			$("#checkbox"+j).removeAttr("checked");
		}
	}
}
function popupAddGroup(){
	id = dijit.byId('to_group').get('value');
	if(id==-1){
		window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/foundation/group/add";?>','_blank');
	}
}

url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
function getAllGroupByBranch(typeFrom=0){
	dijit.byId('to_group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	study_year = dijit.byId('study_year').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('from_group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	fromGroup="";
	fromDegree="";
	changeType="";
	if(typeFrom!=0){
		fromGroup=dijit.byId('from_group').get('value');
		fromDegree = dijit.byId('from_degree').get('value');
		changeType = dijit.byId('change_type').get('value');
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,
			'academic_year':study_year,
			'degree':fromDegree,
			'group_id':fromGroup,
			'noaddnew':0,
			'change_type':changeType
			},
		handleAs:"json",
		load: function(data) {
		    group_store = getDataStorefromJSON('id','name', data);
		    dijit.byId('to_group').set('store',group_store);   
		    if(typeFrom==0){
		   	 dijit.byId('from_group').set('store',group_store);   
		    }  
		},
		error: function(err) {
		}
	});
}
</script>
