
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('GROUP_STUDENT_CHANGE_GROUP'));
	$frm =  $this->form_search;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		   			<h4 class="m-b-0"><i class="fa fa-server" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('GROUP_STUDENT_CHANGE_GROUP');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
	               <div class="col-md-3 col-sm-3 col-xs-12">
	               		<?php echo $frm->getElement("adv_search");?>
	               </div>
	               <div class="col-md-3 col-sm-3 col-xs-12">
	               		<?php echo $frm->getElement("branch_id");?>
	               </div>
	               <div class="col-md-3 col-sm-3 col-xs-12">
	               		<?php echo $frm->getElement("academic_year");?>
	               </div>
	               <div class="col-md-3 col-sm-3 col-xs-12">
	               		<?php echo $frm->getElement("degree");?>
	               </div>
	            </div>   
	            <div class="form-group">
	            	<div class="col-md-3 col-sm-3 col-xs-12">
	               		<input id="grade" />
	               </div>
	               <div class="col-md-3 col-sm-3 col-xs-12">
	               		 <?php echo $frm->getElement("session");?>
	               </div>
	               <div class="col-md-3 col-sm-3 col-xs-12">
	               		<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
	               </div>
	            </div>
	        </form> 
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.ready(function(){

	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false, 
		required: false,
		id: "grade",
		name: "grade",           
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
		}
	}, "grade");
	var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
  });
	getallGrade();
});
var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id=='' || dept_id==-1){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store); 
			    dijit.byId('grade').attr('value','<?php echo $this->adv_search['grade']?>');    
			},
			error: function(err) {
			}
		});
}
</script>