<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_DOCUMENT')); 
?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-shield " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_DOCUMENT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='add_document' action="" method="post" dojoType="dijit.form.Form" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
  				 if(this.validate()) {
				types=dijit.byId('types').get('value');
					if(types==0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_CATEGORY');?> !');dijit.byId('types').focus();return false;
					return false;
				}
    				dijit.byId("save_close").attr("disabled",true);
					dijit.byId("save_new").attr("disabled",true);
   					 return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DOCUMENT_NAME");?> <span class="required">*</span>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="name" name="name" type="text">
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DOCUMENT_TYPE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select name="types" id="types" dojoType="dijit.form.FilteringSelect" required="true" class="fullside">
	                   				<option value="0" ><?php echo $tr->translate('PLEASE_SELECT_CATEGORY');?></option>
    								<option value="1" label="<?php echo $tr->translate('STUDENT_DOCUMENT');?>"><?php echo $tr->translate('STUDENT_DOCUMENT');?></option>
    								<option value="2" label="<?php echo $tr->translate('TEACHER_DOCUMENT');?>"><?php echo $tr->translate('TEACHER_DOCUMENT');?></option>
							</select>
	                   </div>
	                </div>
	                 <div class="clearfix"></div>
			         <div class="card-box mt-20">
		               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
							<input type="button" onClick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
							<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
		               	</div>
		             </div>
	            </div>
	         </div>
		</form>
	</div>
</div>
<script>
function submitDataClose(){
	if(dijit.byId('add_document').validate()) {
		types=dijit.byId('types').get('value');
		if(types==0){
			alert('<?php echo $tr->translate('PLEASE_SELECT_CATEGORY');?> !');dijit.byId('type').focus();return false;
			return false;
		}
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'global','controller'=>'document','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_document"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/global/document";
			},
			error: function(e) {
			}
		});
	}
}
</script>