<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_DISCOUNTSETTING')); 
	$frm= $this->frm_discount;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require('dijit.form.TextBox');  
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dijit.form.DateTextBox");
</script>
<script>
var disname_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->discount));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: disname_store,
		required: true,   
		autoComplete: false,
		queryExpr: "*${0}*",  
		id: "disname_id",
		name: "disname_id",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_DISCOUNT");?>",          
		onChange: function() {  
			discount_id = dijit.byId('disname_id').get('value');
			if(discount_id==-1){
				dijit.byId("popup_add_discount").show();
				dijit.byId("s_save").set("disabled",false);
			}
		}
	}, "disname_id");

	new dijit.form.FilteringSelect({
		store: service_store,
		required: true,  
		autoComplete: false,
		queryExpr: "*${0}*",                      
	    id: "title",
	    name: "title",  
	    tabindex: "1",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_CATEGORY")?>", 
	    onChange: function() {          
		   	service_id = dijit.byId('title').get('value');
		    if(service_id==-1){
		   		dijit.byId("popup_dept").show();
		   		dijit.byId("s_save").set("disabled",false);
		    }
	   }
	}, "title");
});
</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-shield " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_DISCOUNTSETTING');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='add_discount' action="" method="post" dojoType="dijit.form.Form" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit"> 
				dranch=dijit.byId('branch_id').get('value');
					if(dranch==''){
						alert('Please Select Branch!');
						dijit.byId('branch_id').focus()
						return false;
					}
				dis_max=dijit.byId('dis_max').get('value');
					if(dis_max>100){
					alert('អាចបញ្ចុះតម្លៃពី 1 ដល់ 99!');
					return false;
					}  
				 end_date=dijit.byId('end_date').get('value');
				 start_date=dijit.byId('start_date').get('value');
					if(end_date<start_date){
						alert('ថ្ងៃចាប់ផ្តើម មិនអាចហួសថ្ងៃបញ្ចប់ទេ!');
						return false;
					}
  				 if(this.validate()) {
    				dijit.byId("save_close").attr("disabled",true);
					dijit.byId("save_new").attr("disabled",true);
   					 return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					 <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("branch_id");?>
		                </div>
		             </div>
					<div class="form-group">
	                 	<label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DISCOUNT_TYPE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="disname_id" />
						</div>
		             </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DIS_MAX");?>%
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("dis_max");?>
	                   </div>
	                </div>
	              	 <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("START_DATE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("start_date");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("END_DATE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("end_date");?>
	                   </div>
	                </div>
                 <div class="clearfix"></div>
		         <div class="card-box mt-20">
	               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
		               	<input type="button" onClick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
               </div>
             </div>
           </div>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;" id="popup_add_discount" >
		<form style="" id='frm_adddiscount' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					return true;
				} else {
					return false;
				}
			</script>
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset>
					<legend align="center" ><?php echo $tr->translate('ADD_DISCOUNT');?></legend>
						<table style="margin: 0 auto; width: 100%;  padding:10px; line-height: 35px;" cellspacing="7" >
							<tr>
								<td><?php echo $tr->translate('DISCOUNT_TYPE');?></td>
								<td><input dojoType="dijit.form.ValidationTextBox" required="true"  class="fullside" id="dis_name" name="dis_name" value="" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate('STATUS');?></td>
								<td><select name="status_j" id="status_j" dojoType="dijit.form.FilteringSelect"   class="fullside">
	    								<option value="1" ><?php echo $tr->translate('ACTIVE');?></option>
	    								<option value="0" ><?php echo $tr->translate('DEACTIVE');?></option>
									</select>
								</td>
							</tr>
							<tr>
								<td colspan="2" align="center" >
									<input type="button"  label="<?php echo $tr->translate("CANCEL");?>" id="cancelButton" 
									dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideDialog();"/>
									<input type="button" value="save_new" name="s_save"  id="s_save" label="<?php echo $tr->translate("SAVE");?>" id="submitButton" 
									dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addDiscount();"/>
								</td>
							</tr>
						</table>
				</fieldset>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<script>
function submitDataClose(){
	dranch=dijit.byId('branch_id').get('value');
	if(dranch==''){
		alert('Please Select Branch!');
		dijit.byId('branch_id').focus();
		return false;
	}
	dis_max=dijit.byId('dis_max').get('value');
	if(dis_max>100){
		alert('អាចបញ្ចុះតម្លៃពី 1 ដល់ 99!');
		return false;
	}
	end_date=dijit.byId('end_date').get('value');
	start_date=dijit.byId('start_date').get('value');
	if(end_date<start_date){
		alert('ថ្ងៃចាប់ផ្តើម មិនអាចហួសថ្ងៃបញ្ចប់ទេ!');
		return false;
	} 
	if(dijit.byId('add_discount').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'discountsetting','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_discount"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/accounting/discountsetting";
			},
			error: function(e) {
			}
		});
	}
}
var url_adddiscount = '<?php echo $this->url(array('module'=>'accounting','controller'=>'discountsetting','action'=>'adddiscount')); ?>';
	function addDiscount(){
		if(dijit.byId('frm_adddiscount').validate()){
			dijit.byId("s_save").attr("disabled",true);
			dojo.xhrPost({
					url:url_adddiscount,
					form: dojo.byId("frm_adddiscount"),
					handleAs:"json",
					load: function(data) {
						var Itemmake = { 
							 id: data,
							 name: dijit.byId('dis_name').get('value')
						   };
				   addDataToSelectbox(dijit.byId('disname_id'), disname_store, Itemmake, data);
				   dijit.byId('frm_adddiscount').reset();
				   dijit.byId("popup_add_discount").hide();	
				},
				error:function(err){
				}
		});
	}
}
function branch(){
    dept_id = dijit.byId('branch').get('value');
    if(dept_id==-1){
    	dijit.byId("popup_add_discount").show();
	}
}
function hideDialog(){
	dijit.byId('frm_adddiscount').reset();
	dijit.byId("popup_add_discount").hide();
}
</script>