<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_DISCOUNTSETTING')); 
	$frm= $this->frm_discount;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dijit.form.DateTextBox");
</script>
<script>
	var disname_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->discount));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: disname_store,
			autoComplete: false,
			queryExpr: "*${0}*",                   
			required: true,
			id: "disname_id",
			name: "disname_id",           
			class: "full", 
			placeHolder:"<?php echo $tr->translate("SELECT_DISCOUNT");?>",          
			onChange: function() {  
				discount_id = dijit.byId('disname_id').get('value');
				if(discount_id==-1){
					dijit.byId("popup_add_discount").show();
				}
			}
		}, "disname_id");
	});
</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-shield " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_DISCOUNTSETTING');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='add_discount' action="" method="post" dojoType="dijit.form.Form" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
  				 dranch=dijit.byId('branch_id').get('value');
				if(dranch==''){
					alert('Please Select Branch!');
					return false;
				}
				dis_max=dijit.byId('dis_max').get('value');
				if(dis_max>100){
					alert('អាចបញ្ចុះតម្លៃពី 1 ដល់ 99!');
					return false;
				}  
				 end_date = dijit.byId('end_date').get('value');
				 start_date=dijit.byId('start_date').get('value');
				if(end_date<start_date){
					alert('ថ្ងៃចាប់ផ្តើម មិនអាចហួសថ្ងៃបញ្ចប់ទេ!');
					return false;
				}
  				if(this.validate()){
    				dijit.byId("save_close").attr("disabled",true);
   					return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("branch_id");?>
		                </div>
		             </div>
					<div class="form-group">
	                 	<label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DISCOUNT_TYPE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select name="disname_id" id="disname_id" class="fullside" dojoType="dijit.form.FilteringSelect" >
								<?php if(!empty($this->discount)){foreach ($this->discount as $discount){?>
									<option value="<?php echo $discount['id']?>" <?php if($discount['id']==$this->rs['disname_id']){echo 'selected="selected"';}?>><?php echo $discount['name']?></option>
								<?php }}?>
							</select>
						</div>
		            </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DIS_MAX");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("dis_max");?>
	                   </div>
	                </div>
	              	<div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("START_DATE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("start_date");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("END_DATE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("end_date");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("status");?>
	                   </div>
	                </div>
                 <div class="clearfix"></div>
		         <div class="card-box mt-20">
	               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
	               		<input type="submit" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
	               	</div>
	             </div>
             </div>
           </div>
		</form>
	</div>
</div>