<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('ADD_DISCOUNTSETTING'));
$frm = $this->frm_discount;
$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl();
$result = $this->rs;
$degreeIds = explode(",",$result['degree']);

?>
<style>
	.optListRow li.opt-items input[type=checkbox],
	input[type=radio] {
		margin: -9px 0 0 !important;
	}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
			<div class="col-sm-12 border-botom">
				<div class="col-sm-8 pd-0">
					<h4 class="m-b-0"><i class="fa fa-shield "
							aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_DISCOUNTSETTING'); ?>
					</h4>
				</div>
				<div class="col-sm-4 text-right">
				</div>
			</div>
		</div>
		<form id='add_discount' action="" method="post" dojoType="dijit.form.Form"
			enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">
				branch=dijit.byId('branch_id').get('value');
				if(branch==''){
					alert('Please Select Branch!');
					return false;
				}
				dis_max=dijit.byId('discountValue').get('value');
				if(dis_max>100){
					alert('អាចបញ្ចុះតម្លៃពី 1 ដល់ 99!');
					return false;
				}  
				 end_date = dijit.byId('end_date').get('value');
				 start_date=dijit.byId('start_date').get('value');
				if(end_date<start_date){
					alert('ថ្ងៃចាប់ផ្តើម មិនអាចហួសថ្ងៃបញ្ចប់ទេ!');
					return false;
				}
				 discountforType=dijit.byId('discountforType').get('value');
					var ifCheckedDegree = $('input[name="selector[]"]:checked').length > 0;

					if(discountforType==1 && ifCheckedDegree==false){
						alert('please check degree');
						return false;
					}
				  if(this.validate()){
					dijit.byId("save_close").attr("disabled",true);
					   return true;
				   }else {
					return false;
				   }
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex ">
										<div class="settings-main-icon ">
											<i class="material-icons-outlined">discount</i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("DISCOUNT_INFO"); ?>
											</p>
										</div>
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12">
										&nbsp;
									</div>
									<div class="form-group">
										<label
											class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH"); ?>
											<span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("branch_id"); ?>
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ACEDMIC_YEAR"); ?>
											<span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("academic_year"); ?>
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DISCOUNT_TITLE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("discountTitle"); ?>
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DISCOUNT_OPTION"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("discountFor"); ?>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12 col-sm-12 col-xs-12">
											<div class="d-flex ">
												<div class="settings-main-icon ">
													<i class="material-icons-outlined">discount</i>
												</div>
												<div class="col-md-10 col-sm-10 col-xs-12">
													<p class="tx-20 font-weight-semibold d-flex ">
														<?php echo $tr->translate("DISCOUNT_INFO"); ?>
													</p>
												</div>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DISCOUNT_OPTION"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("discountforType"); ?>
										</div>
									</div>
									<!-- <div class="form-group hidden_student">
										<label
											class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="studentId" />
										</div>
									</div> -->
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("status"); ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex ">
										<div class="settings-main-icon ">
											<i class="material-icons-outlined">discount</i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("DISCOUNT_SETTING"); ?>
											</p>
										</div>
									</div>

									<div class="form-group">
										<label
											class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DISCOUNT_TYPE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="discount_id" />
										</div>
									</div>

									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DisValueType"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("DisValueType"); ?>
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DIS_MAX"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("discountValue"); ?>
										</div>
									</div>
									<div class="d-flex ">
										<div class="settings-main-icon ">
											<i class="fa fa-calendar" aria-hidden="true"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("VALIDATE"); ?>
											</p>
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DISCOUNT_PERIOD"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("discountPeriod"); ?>
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("START_DATE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("start_date"); ?>
										</div>
									</div>
									<div class="form-group">
										<label
											class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("END_DATE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("end_date"); ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex">
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-indent-left" aria-hidden="true"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("DEGREE"); ?>
											</p>
										</div>
									</div>
									<div class="custom-control custom-checkbox ">
										<input type="checkbox" class="checkbox custom-control-input"
											onchange="checkall();" class="checkbox" id="check_all" name="check_all">
										<label class="custom-control-label" for="check_all">
											<?php echo $tr->translate('CHECK_ALL'); ?>
										</label>
									</div>
									<div class="form-group">
										<ul class="optListRow">
											<?php
											if (!empty($this->rsdegree))
												foreach ($this->rsdegree as $rs) {
													?>
													<li class="opt-items">
														<div class="custom-control custom-checkbox">
															<input <?php if (in_array($rs['id'], $degreeIds)) {
																echo "checked";
															} ?>
																type="checkbox" class="checkbox custom-control-input"
																id="depts<?php echo $rs['id']; ?>"
																value="<?php echo $rs['id']; ?>" name="selector[]">
															<label class="custom-control-label"
																for="depts<?php echo $rs['id']; ?>">
																<?php echo $rs['name']; ?>
															</label>
														</div>
													</li>
												<?php } ?>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="card-box">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-education"></i>
										</div> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT_LIST");?></p>
											<div class="card-blogform">
												<div class="form-group" style="background: #d8e0e2; padding: 15px 15px; margin: 0; border: solid 1px #697996; border-radius: 2px;">
													<div class="form-group">
														<label class="control-label  col-md-3 col-sm-3 col-xs-12"><?php echo $tr->translate("SELECT_STUDENT");?></label>
														<div class="col-md-7 col-sm-7 col-xs-12">
															<input id="studentId" />
														</div>
													</div>
												</div>
											</div>
										</div> 
									</div>
									<div class="form-group">
										<div class="card-box">
											<div class="col-md-12 col-sm-12 col-sxs-12">
												<div class="form-group">
													<input type="hidden" name="identity" id="identity" value="">
													<table  class="collape responsiveTable" >
														<thead id="tableHeadInfo">
														</thead>
														<tbody id="table_row">
														</tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
				<div class="card-box mt-20">
					<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
						<input type="submit" value="save_close" name="save_close" id="save_close"
							label="<?php echo $tr->translate('GO_EDIT'); ?>" dojoType="dijit.form.Button"
							class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-open" />
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl(); ?>/admin/js/global.js" type="text/javascript"></script>
<script src="<?php echo $baseurl; ?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require('dijit.form.TextBox');
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dijit.form.Textarea");
	dojo.require("dojo.NodeList-manipulate");

</script>
<script>
	var disname_store = getDataStorefromJSON('id', 'name', <?php print_r(Zend_Json::encode($this->discount)); ?>);
	dojo.ready(function () {
		new dijit.form.FilteringSelect({
			store: disname_store,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: true,
			id: "discount_id",
			name: "discount_id",
			class: "fullside",
			value:'<?php echo $result['discountId']; ?>',
			placeHolder: "<?php echo $tr->translate("SELECT_DISCOUNT"); ?>",
			onChange: function () {
				discount_id = dijit.byId('discount_id').get('value');
				if (discount_id == -1) {
					dijit.byId("popup_add_discount").show();
				}
			}
		}, "discount_id");
		new dijit.form.FilteringSelect({
			required: false,
			autoComplete: false,
			queryExpr: "*${0}*",
			id: "studentId",
			name: "studentId",
			tabindex: "1",
			class: 'fullside',
			placeHolder: "<?php echo $tr->translate("SELECT_STUDENT_NAME") ?>",
			onChange: function () {
				addRowStudent();
			}

		}, "studentId");

		branchId = dijit.byId('branch_id');
		branchId.on('change', function (evt) {
			branchId = dijit.byId('branch_id').get('value');
			if (branchId == '') {
				dijit.byId("branch_id").focus();
				return false;
			}
			getAllstudentBranch();
		});

		discountOption = dijit.byId('discount_id');
		discountOption.on('change', function (evt) {
			getAllstudentBranch();
		});
		getAllstudentBranch();
		discountFor();
		initailizeStudent();
	});

	function getAllstudentBranch() {
		dijit.byId("studentId").reset();
		branchId = dijit.byId('branch_id').get('value');
		if (branchId == '') {
			dijit.byId('branch_id').focus();
		}
		discountOption = dijit.byId('discount_id').get('value');

		if (discountOption == 1) {
			return false;
		}
		var urlGet = '<?php echo $this->url(array('module' => 'registrar', 'controller' => 'register', 'action' => 'getliststudenturl')); ?>';
		selectedId = '<?php echo $result['studentId']; ?>';
		contentData = {
			'branchId': branchId,
			'customerType': 1
		}
		getAllStudentByBranch(urlGet, contentData, selectedId);
	}
	function checkall() {
		if ($('#check_all').is(':checked')) {
			$(".checkbox").prop('checked', true);
		} else {
			$(".checkbox").prop('checked', false);
		}
		checkDiscountForType();
	}
	function checkDiscountPeriod() {
		discountPeriod = dijit.byId('discountPeriod').get('value');
		if (discountPeriod == 2) {
			dijit.byId('start_date').set('readOnly', false);
			dijit.byId('end_date').set('readOnly', false);
			dijit.byId('start_date').set("required", true);
			dijit.byId('end_date').set("required", true);
		} else {
			dijit.byId('start_date').reset();
			dijit.byId('end_date').reset();
			dijit.byId('start_date').set("required", false);
			dijit.byId('end_date').set("required", false);
			dijit.byId('start_date').set('readOnly', true);
			dijit.byId('end_date').set('readOnly', true);
		}
	}
	function checkDiscountForType() {
		var discountforType = dijit.byId('discountforType').get('value');
		if (discountforType == 1) {//school fee
			//$(".hidden_student").css('display','block');
		} else {
			//$(".hidden_student").css('display','none');
			$(".checkbox").prop('checked', false);
		}
	}
	function discountFor() {
		var discountFor = dijit.byId('discountFor').get('value');
		if (discountFor == 1) {
			$(".hidden_student").css('display', 'block');
		} else {
			$(".hidden_student").css('display', 'none');
		}
	}

	var title=0;
	var keyrow=0;
	var strHeadRow="";

	function initailizeStudent(){
		
		<?php if (!empty($this->allstudentByDiscount)) { foreach ($this->allstudentByDiscount as $key=> $row){
		
				if ($row['sex']==1){
					$gender = $tr->translate("MALE");
				}else{
					$gender = $tr->translate("FEMALE");
				}
			?>
					keyrow = keyrow+1;
					if(title!=1){
							strHeadRow = '<tr class="head-td" >';
								strHeadRow+='<th scope="col" ><?php echo $tr->translate("DEL");?></th>';
								strHeadRow+='<th scope="col" ><?php echo $tr->translate("NUM");?></th>';
								strHeadRow+='<th scope="col" ><?php echo $tr->translate("STUDEN_CODE");?></th>';
								strHeadRow+='<th scope="col" ><?php echo $tr->translate("STUDEN_NAME");?></th>';
								strHeadRow+='<th scope="col" ><?php echo $tr->translate("GENDER");?></th>';
							strHeadRow += '</tr>';
							dojo.html.set(dojo.byId("tableHeadInfo"),strHeadRow, {
									parseContent: true,
							});
						title=1;
					}
					var strStudent="";
					strStudent += '<td width="40px" align="center"><img onclick="deleteRecord(' + keyrow + ')" src="<?php echo $this->baseUrl(); ?>/images/Delete_16.png"></td>';
					strStudent+='<td data-label="<?php echo $tr->translate("NUM");?>">'+keyrow+'</td>';
					strStudent+='<td data-label="<?php echo $tr->translate("STUDEN_CODE");?>"><?php echo $row['stu_code'];?></td>';
					strStudent+='<td data-label="<?php echo $tr->translate("STUDEN_NAME");?>"><?php echo $row['stu_name'];?>';
						strStudent+='<input dojoType="dijit.form.TextBox" type="hidden" name="student_id'+keyrow+'" id="student_id'+keyrow+'"  value="<?php echo $row['stu_id'];?>" >';
					strStudent+='</td>';
					strStudent+='<td data-label="<?php echo $tr->translate("GENDER");?>"><?php echo $gender;?></td>';
				
					tmp='<tr id="row'+keyrow+'" class="rowData" >';
					tmp+='</tr>';
					
					dojo.query("#table_row").append(tmp);
					if($("#identity").val()!="") {
						var identity = $("#identity").val();
						$("#identity").val(identity+','+keyrow);
					} else {$("#identity").val(keyrow);}
					dojo.html.set(dojo.byId("row"+keyrow),strStudent , {
						 parseContent: true,
					});
			<?php }
		}else{?>
				$('#identity').val('');
				document.getElementById("table_row").innerHTML = '';
		<?php }?>		
	}

	
	urlGetStudentInfo = '<?php echo $this->url(array('module'=>'issue','controller'=>'discipline','action'=>'get-student-info'));?>';
	function addRowStudent(){
		
		studentId=dijit.byId("studentId").get("value");

		if(studentId==-1 || studentId==""){return false;}
		var iden = $("#identity").val();
		var arrays = iden.split(',');
		if(arrays!=""){
			 for(var i=0;i< arrays.length;i++) {
				readychoose = dijit.byId('student_id'+arrays[i]).get('value');
				if(readychoose==studentId){
					alert("<?php echo $tr->translate("Choosen ready")?>");
					dijit.byId('studentId').reset();
					return false;
				}
			}
		}
		
		dojo.xhrPost({
			url: urlGetStudentInfo,
			content:{
				'studentId':studentId,
				},
			handleAs:"json",
			load: function(data) { 
				if(data!=""){
					keyrow = keyrow+1;
					if(title!=1){
							strHeadRow = '<tr class="head-td" >';
								strHeadRow+='<th scope="col" ><?php echo $tr->translate("DEL");?></th>';
								strHeadRow+='<th scope="col" ><?php echo $tr->translate("NUM");?></th>';
								strHeadRow+='<th scope="col" ><?php echo $tr->translate("STUDEN_CODE");?></th>';
								strHeadRow+='<th scope="col" ><?php echo $tr->translate("STUDEN_NAME");?></th>';
								strHeadRow+='<th scope="col" ><?php echo $tr->translate("GENDER");?></th>';
							strHeadRow += '</tr>';
							dojo.html.set(dojo.byId("tableHeadInfo"),strHeadRow, {
									parseContent: true,
							});
						title=1;
					}
					var strStudent="";
					strStudent += '<td width="40px" align="center"><img onclick="deleteRecord(' + keyrow + ')" src="<?php echo $this->baseUrl(); ?>/images/Delete_16.png"></td>';
					strStudent+='<td data-label="<?php echo $tr->translate("NUM");?>">'+keyrow+'</td>';
					strStudent+='<td data-label="<?php echo $tr->translate("STUDEN_CODE");?>">'+data.stu_code+'</td>';
					strStudent+='<td data-label="<?php echo $tr->translate("STUDEN_NAME");?>">';
						strStudent+=data.stuNameKH+'-';
						strStudent+=data.stuNameLatin;
						strStudent+='<input dojoType="dijit.form.TextBox" type="hidden" name="student_id'+keyrow+'" id="student_id'+keyrow+'"  value="'+data.stu_id+'" >';
					strStudent+='</td>';
					strStudent+='<td data-label="<?php echo $tr->translate("GENDER");?>">'+data.genderTitle+'</td>';
				
					tmp='<tr id="row'+keyrow+'" class="rowData" >';
					tmp+='</tr>';
					
					dojo.query("#table_row").append(tmp);
					if($("#identity").val()!="") {
						var identity = $("#identity").val();
						$("#identity").val(identity+','+keyrow);
					} else {$("#identity").val(keyrow);}
					dojo.html.set(dojo.byId("row"+keyrow),strStudent , {
						 parseContent: true,
					});
					dijit.byId('studentId').reset();
				}
			
			},
			error: function(err) {
				alert(err);
			}
		});	
	}

	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}

</script>