<?php 
     $url_save = $this->url(array('module'=>'stock','controller'=>'productcategory','action'=>'edit'));
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $status_view=$this->status_view;
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $this->tr->translate("EDIT_PRODUCT_CATEGORY")?></title>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_PRODUCT_CATEGORY');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id="add_province" action="<?php echo $url_save;?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	 		<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="name_kh" name="name_kh" value="<?php echo $this->row['name_kh']?>" type="text" >
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside">
						        <option value="1" <?php if($this->row['status']==1){ echo "selected='selected'";}?>><?php echo $tr->translate("ACTIVE");?></option>
						        <option value="0" <?php if($this->row['status']==0){ echo "selected='selected'";}?>><?php echo $tr->translate("DEACTIVE");?></option>
							</select>
	                   </div>
	                </div>
	                <div class="clearfix"></div>
			         <div class="card-box mt-20">
		               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
		               		<input type="reset" value="Clear" label="<?php echo $tr->translate("CLEAR");?>"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
							<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate("SAVE_CLOSE");?>" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
		               	</div>
		             </div>
	             </div>
	         </div>
		</form>
	</div>
</div>
	