<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_GRADUATED_STUDENT')); 
	
	//$hour=explode(',', $this->rs['array_checkbox']);
	//$hour=$this->rs['array_checkbox'];
	//print_r($hour);exit();
	
?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit  " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_GRADUATED_STUDENT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id="add_car" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'graduatedstudent','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit" >			
			if(this.validate()) {
				branch_id=dijit.byId('branch_id').get('value');
                	if(branch_id==0 || branch_id==''){
                        alert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>');
						dijit.byId('branch_id').focus();
						return false;	
                	}
					var identity = [];
	    			 $('.checkbox:checked').each(function(i){
	    				 identity[i] = $(this).val();
	     			});
					if(identity==""){
						alert("<?php echo $tr->translate("PLEASE_SELECT_STUDENT");?>");
						return false;
					}
                from_group=dijit.byId('from_group').get('value');
                if(from_group==0 || from_group==''){
                        alert('Please Select Form Group !');
						dijit.byId('from_group').focus();
						return false;	
                }
				loadingBlock();
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select class="fullside" dojoType="dijit.form.FilteringSelect" required="true" readOnly="readOnly" id="branch_id" name="branch_id" type="text" onchange="getAllGroupByBranch();">
								<option value="-1"><?php echo $tr->translate("SELECT_BRANCH")?></option>
								<?php if(!empty($this->branch_name)){foreach($this->branch_name as $name){?>
									<option value="<?php echo $name['id'];?>" <?php if($name['id']==$this->rs['branch_id']) echo 'selected="selected"';?>><?php echo $name['name'];?></option>
								<?php }}?>
							</select>
							<input dojoType="dijit.form.TextBox" class="fullside" id="id" name="id" type="hidden"  value="<?php echo $this->rs['id'];?>"/>
		                </div>
		             </div>
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="from_group" />
							<input dojoType="dijit.form.TextBox"  type="hidden" name="identity" id="identity" />
							<input dojoType="dijit.form.TextBox"  type="hidden" name="old_array_checkbox" id="old_array_checkbox" value="<?php echo $this->rs['array_checkbox'];?>" />
									
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="type" name="type" type="text">
								<?php if(!empty($this->rstype)){foreach ($this->rstype as $rs){?>
									<option value="<?php echo $rs['id']?>" <?php if($rs['id']==$this->rs['type']) echo 'selected="selected"';?>><?php echo $rs['name']?></option>
								<?php }}?>
							</select>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		               	 	<input dojoType="dijit.form.TextBox" class="fullside" value="<?php echo $this->rs['note'];?>" id="note" name="note" type="text" />
		                	<input dojoType="dijit.form.TextBox" class="fullside" id="identity " name="identity " type="hidden" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select class="fullside" dojoType="dijit.form.FilteringSelect"   class="fullside" id="status" name="status" type="text">
								<option value="1" <?php if($this->rs['status']==1) echo 'selected="selected"';?>><?php echo $tr->translate("ACTIVE");?></option>
								<option value="0" <?php if($this->rs['status']==0) echo 'selected="selected"';?>><?php echo $tr->translate("DEACTIVE");?></option>
							</select>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-12 col-sm-12 col-xs-12"><?php echo $tr->translate("DETAIL");?> </label>
		             </div>
		             <div class="form-group">
		                <div class="col-md-12 col-sm-12 col-xs-12">	
		                	<div id="lblfromgroup">
		                	</div>
		                </div>
		             </div>
		             
		         </div>
		         <div class="col-md-8 col-sm-8 col-xs-12">
		    		<div class="form-group">
		                <label class="control-label text-center bold col-md-12 col-sm-12 col-xs-12"><?php echo $tr->translate("STUDENT_LIST");?> </label>
		             </div>
		             <div class="form-group">
		             	<div id="data_table"> </div>
		             	<?php $old_iden=""; foreach ($this->studentpass as $id => $rs){?>
								<input type="hidden" name="old_student<?php echo $id?>" id="old_student<?php echo $id?>" value="<?php echo $rs['stu_id']?>"/>
							<?php if($id==0){$old_iden.=$id;}else{$old_iden.=','.$id;}?>
							
						<?php }?>	
						<input type="hidden" name="old_iden" id="old_iden" value="<?php echo $old_iden;?>"/>
		             </div>
		         </div>
		     </div>
		     <div class="card-box">
	    		<div class="col-md-12 col-sm-12 col-xs-12">
	    			
	    		</div>
	    	</div>
	    	<div class="clearfix"></div>
	       	<div class="card-box mt-20 ">
	      	 	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
              		 <input type="submit" value="close" name="close" label="<?php echo $tr->translate("GO_EDIT");?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconClose" />
            	 </div>
            </div>
		</form>
	</div>
</div>
<style>
.fixed_header{
    width: 100%;
    table-layout: fixed;
    border-collapse: collapse;
}

.fixed_header tbody{
  display:block;
  width: 100%;
  overflow: auto;
  height: 300px;
}

.fixed_header thead tr {
   display: block;
}
.fixed_header thead tr td{
	text-align: center;
}
.fixed_header thead {
  background: #02014a;
  color:#fff;
}

.fixed_header th, .fixed_header td {
  padding: 5px;
  text-align: left;
  width: 200px;
}
.fixed_header td.center {
    text-align: center;
}
div#lblfromgroup div.info{
	    background: #fdfbbd;
    border: solid 1px #02014a;
    white-space: normal;
    display: block;
    font-size: 14px;
    border-radius: 5px;
    padding: 10px !important;
    color: #02014a;
}
</style>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.DateTextBox");
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                      
			id: "from_group",
			name: "from_group",  
			class: 'fullside', 
			required:false,
			readOnly:true,
			placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
			onChange:function(){
				toStudentGroup(1);
				getStudentFromGroup();			 						 						
			}
		},"from_group");
		getAllGroupByBranch();
		 
		
	}); 
var oldbranch ='<?php echo $this->rs['branch_id']?>';
url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('from_group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('from_group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
		},
		handleAs:"json",
		load: function(data) {
			group_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('from_group').set('store',group_store);   
			if(oldbranch == branch_id){
				dijit.byId('from_group').set('value','<?php echo $this->rs['group_id']?>');  
				toStudentGroup(1);
				getStudentFromGroup();
			}
		},
		error: function(err) {
		}
	});
}
	
var url_get_all_student_from_group_update = "<?php echo $this->url(array('module'=>'foundation','controller'=>'graduatedstudent','action'=>'get-all-student-update')); ?>";
function getStudentFromGroup(){

		from_group = dijit.byId('from_group').get('value');
		if(from_group==0){
			alert("Please Select Group");
			return false;
		}
		dojo.xhrPost({
			url:url_get_all_student_from_group_update,
			content:{
				'from_group':from_group
				},
			handleAs:"json",
			load: function(respone) {
				tem='<table border="1" id="table"  class="fixed_header">'
					+'<thead><tr ><td style="width: 20px;"><?php echo $tr->translate('NUM');?></td>'
					+'<td ><?php echo $tr->translate('STUDENT_ID');?></td>'
					+'<td><?php echo $tr->translate('STUDENT_NAMEKHMER');?></td>'
					+'<td><?php echo $tr->translate('NAME_EN');?></td>'
					+'<td ><?php echo $tr->translate('SEX');?></td>'
					+'<td style="width: 20px;"><input style=" height: initial;"  type="checkBox" value="0"  name="check_all" onclick=" CheckAll(0);;" id="check_all"/> </td> '
					+'</tr>'
					+'</thead>'
					+'<tbody>';
				if(respone!=""){
					num=0;
					for(var i=0;i<respone.length;i++){
						inx = i+1;
							tem += '<tr >';
						    tem += '<td style="width: 20px;" class="center">&nbsp;'+inx+'&nbsp;<input type="hidden"  name="stu_id_'+inx+'" id="stu_id_'+inx+'" value="'+respone[i].stu_id+'" /></td>';
							tem += '<td>'+respone[i].stu_code+'</td>';
							tem += '<td>'+respone[i].stu_khname+'</td>';
							tem += '<td>'+respone[i].stu_enname+' '+respone[i].last_name+'</td>';
							tem += '<td class="center">'+respone[i].sex+'</td>';
							tem += '<td class="center" style="width: 20px;"><input class="checkbox" style="height: initial;" type="checkBox" value="'+respone[i].stu_id+'"  name="selector[]" id="checkbox'+inx+'"/></td>';
						    tem += '</tr>';
						    if($("#identity").val()!="") {
								var identity = $("#identity").val();
								$("#identity").val(identity+','+inx);
							}else {$("#identity").val(inx);}
					}
				}
				tem+='</tbody>';
				tem+='</table>';
				dojo.byId('data_table').innerHTML = tem;
				setpassstudent();
			},
			error: function(err) {
				alert(err);
			}
		});
}
function CheckAll(index){
	if(index==0){
			if($('#check_all').is(":checked")){
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = true;  
				});
			}else{
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = false;  
				});
			}
	}else{
		var a = $("input:checked").val();
		 var identity = [];
	     $('.checkbox:checked').each(function(i){
	    	 identity[i] = $(this).val();
	     });
	}
}


var url_to_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudentchangegroup','action'=>'get-to-group')); ?>';
function toStudentGroup(type){
	togroup = dijit.byId('from_group').get('value');
	dojo.xhrPost({
		url:url_to_group,
		content:{
			'to_group':togroup,
			'type'	  :type,
			},
		handleAs:"json",
		load: function(data) {
			dojo.byId('lblfromgroup').innerHTML='<div class="info"><span class="bold"><?php echo $tr->translate("ACADEMIC_YEAR")?> :  </span>'+data.year+'<br /><span class="bold">  <?php echo $tr->translate("DEGREE")?> :  </span>'+data.degree+'<br /><span class="bold">  <?php echo $tr->translate("GRADE")?> :  </span>'+data.grade+'<br /><span class="bold"><?php echo $tr->translate("SESSION")?> :  </span>'+data.session;
		},
		error: function(err) {
		}
	});
}


function setpassstudent(){
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=1;i<=arrays.length;i++) {
		var stu_id = $("#stu_id_"+i).val();
		var pass_identity = $('#old_iden').val();
		var arr = pass_identity.split(',');
		
		for(var j=0;j<arr.length;j++) {
			var pass_stu_id = $("#old_student"+j).val();
			//alert(stu_id);alert(pass_stu_id);
			if(stu_id==pass_stu_id){
				$('#checkbox'+i).prop('checked', true);
			}
		}
		$("#identity").val("<?php echo $this->rs['array_checkbox'];?>");
	}
}

</script>
