<?php 
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
#table tr td{
	border:1px solid #cccccc;
	text-align: center;
}
#table tr th{
	background: #cccccc;
	border:1px solid #ddd;
}
</style>
<title><?php echo $this->tr->translate("CREATE_TERM_TEST")?></title>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-tasks" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CREATE_TERM_TEST');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id="add_province" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	  			 if(this.validate()) {
					loadingBlock();
					return true;
	  			 }else {
					return false;
	   			}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TITLE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input  type="text" required="required"   dojoType="dijit.form.ValidationTextBox" name="title" id="title" class="fullside" />
		                </div>
		            </div>
					<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("START_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" value="now" class="fullside" id="start_date" name="start_date" type="text" required="required" >
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("END_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" value="<?php echo date("Y-m-d",strtotime("+1 month"))?>" class="fullside" id="end_date" name="end_date" type="text" required="required" >
		                </div>
		             </div>
				</div>
				<div class="col-md-8 col-sm-8 col-xs-12">
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" value="Clear" label="Clear"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
					<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVE_CLOSE");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
    </div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	
	dojo.ready(function(){ 
	
	});

</script>