<?php 
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
#table tr th{
	background: #cccccc;
	border:1px solid #ddd;
	text-align: center;
}
table.collape tbody td {
    text-align: center;
}
</style>
<title><?php echo $tr->translate("EDIT_START_DATE_AND_END_DATE")?></title>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
             <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_START_DATE_AND_END_DATE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id="add_province" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	   			if(this.validate()) {
					dijit.byId('save_new').set('disabled',true);
					dijit.byId('save_close').set('disabled',true);
					return true;
	   			}else {
					return false;
	   			}
			</script>
			<div class="card-box">
				<div class="col-sm-12" >
					<table class="collape tablesorter" id="table_row" style="white-space: nowrap;border:1px solid #ddd;">
					    <tr id="head-title" class="head-td" align="right"></tr>
					</table>
				</div>
				<div class="col-sm-12 text-left" >
					<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
					<input type="button" label="<?php echo $tr->translate('ADD_TERM');?>" dojoType="dijit.form.Button" 
						iconClass="dijitIconEditProperty" onclick="addRow();" />
				</div>
    		</div>
    		<div class="card-box">
    			<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
    				<input type="reset" value="Clear" label="Clear"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
					<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("GO_EDIT");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
    			</div>
    		</div>
		</form>
	</div>
</div>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");

	dojo.ready(function(){ 
		Initialize();
	});


	var col= 0; 
	var no=0;
	var title = 0;
	function addRow() {
		col++;no++;
		template='';
		temp = "";
	
		if(title!=1){
			temp+='<td><?php echo $tr->translate("DEL");?></td>';
			temp+='<td><?php echo $tr->translate("N_O");?></td>';
			temp+='<td><?php echo $tr->translate("START_DATE");?></td>';
			temp+='<td><?php echo $tr->translate("END_DATE");?></td>';
			temp+='<td><?php echo $tr->translate("NOTE");?></td>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			
		template+='<td width="2%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td align="center" width="2%">'+no+'</td>';
		template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox" value="now" class="fullside" id="startdate_'+col+'" name="startdate_'+col+'" value="" type="text" required="required" ></td>';	
		template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox"  value="now" class="fullside" id="enddate_'+col+'" name="enddate_'+col+'" value="" type="text" required="required" ></td>';	
		template+='<td width="10%"><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="remark_'+col+'" name="remark_'+col+'" value="" type="text"  ></td>';	
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
	}


	function Initialize(){
		template='';
		temp = "";
		if(title!=1){
			temp+='<td><?php echo $tr->translate("DEL");?></td>';
			temp+='<td><?php echo $tr->translate("N_O");?></td>';
			temp+='<td><?php echo $tr->translate("START_DATE");?></td>';
			temp+='<td><?php echo $tr->translate("END_DATE");?></td>';
			temp+='<td><?php echo $tr->translate("NOTE");?></td>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
		
		 <?php if(!empty($this->row)) foreach($this->row  As $row_detail){?>
		 
			col++;no++;
			template='';
			template+='<td width="2%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td align="center" width="2%">'+no+'</td>';
			
			template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox" value="now" class="fullside" id="startdate_'+col+'" name="startdate_'+col+'" value="" type="text" required="required" ></td>';	
			template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox"  value="now" class="fullside" id="enddate_'+col+'" name="enddate_'+col+'" value="" type="text" required="required" ></td>';	
			template+='<td width="10%"><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="remark_'+col+'" name="remark_'+col+'" value="" type="text"  ></td>';	

			tmp='<tr id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});


		    dijit.byId('startdate_'+col).set('value','<?php echo $row_detail['start_date']?>');
		    dijit.byId('enddate_'+col).set('value','<?php echo $row_detail['end_date']?>');
		    dijit.byId('remark_'+col).set('value','<?php echo $row_detail['note']?>');
		<?php }?>
	}
	
	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		
		if(arrays[i] == index) arrays.splice(i,1);
			
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
		 calulator(arrays['i']);
	}
</script>