<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_DISPLINCE_NOTE')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$countlang = count($this->lang);
?>
<script>
	dojo.require("dijit/Editor");
	require(["dijit/form/Textarea","dijit/form/NumberTextBox"]);
</script>
	<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<style>
body, #dijitEditorBody {
    height: 100%;
    width: 100%;
    overflow: auto;
    background: #fff !important;
}
.dijitEditor {
    border: solid 1px #ccd9ff;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<form  id='add_room' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
                loadingBlock();
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
	        	<div class="col-sm-12 border-botom">
			    	<div class="col-sm-8 pd-0">
			    		<h4 class="m-b-0"><i class="fa fa-address-book" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_DISPLINCE_NOTE');?></h4>
		    		</div>
		    		<div class="col-sm-4 text-right">
		    		</div>
	    		</div>
	    	</div>
	    	<div class="card-box mb-12">
	    		<div class="col-md-8 col-sm-8 col-xs-12">
	        		<?php if ($countlang>1){?>
			    	<div class="card-box">
			    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
			    		 	<?php $alias=''; foreach($this->lang as $key=> $rs){
		                      	$alias = str_replace(' ','',$rs['title']);?>
				            <li class="nav-item <?php if ($key<1){echo "active";}?>">
				                <a class="nav-link " data-toggle="tab" href="<?php echo "#".$alias;?>" role="tab"><i class="fa fa-flag ml-2"></i> <?php echo $tr->translate(strtoupper($rs['title']));?></a>
				            </li>
				            <?php }?>
				        </ul>
				    </div>
				    <?php }?>
				    <?php if ($countlang>1){?>
				    <div class="col-md-12">
				        <!-- Tab panels -->
				        <div class="tab-content vertical">
				         <?php $alias=''; foreach($this->lang as $key=> $rs){
		                      	$alias = str_replace(' ','',$rs['title']);?>
					        <!--Panel <?php echo $key+1?>-->
					        <div class="tab-pane fade <?php if ($key<1){echo "active in";}?>" id="<?php echo $alias;?>" role="tabpanel">
					        	<div class="col-md-12 col-sm-12 col-xs-12">
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?> <span class="required">*</span>
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<input   type="text" dojoType="dijit.form.ValidationTextBox" required="required" name="title<?php echo str_replace(' ','',$rs['title']);?>"  id="title<?php echo str_replace(' ','',$rs['title']);?>" value="" class="fullside" placeholder="<?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>" />
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-12 col-sm-12 col-xs-12" ><?php echo $tr->translate('CONTENT_'.strtoupper($rs['title']))?><span class="required">*</span>
					                   </label>
					                   <div class="col-md-12 col-sm-12 col-xs-12">
					                 	  <textarea class="ckeditor"   style="min-height:400px; height:400px;" id="description<?php echo str_replace(' ','',$rs['title']);?>" name="description<?php echo str_replace(' ','',$rs['title']);?>"></textarea>
					                   </div>
					                </div>
					          	</div>
					        </div>
					        <?php }?>
					   </div>
					</div>
					<?php }else{?>
					 <div class="col-md-12">
						 <?php $alias=''; foreach($this->lang as $key=> $rs){
		                      	$alias = str_replace(' ','',$rs['title']);?>
				        	<div class="col-md-12 col-sm-12 col-xs-12">
				                <div class="form-group">
				                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?> <span class="required">*</span>
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input   type="text" dojoType="dijit.form.ValidationTextBox" required="required" name="title<?php echo str_replace(' ','',$rs['title']);?>"  id="title<?php echo str_replace(' ','',$rs['title']);?>" value="" class="fullside" placeholder="<?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>" />
				                   </div>
				                </div>
				                <div class="form-group">
				                   <label class="control-label col-md-12 col-sm-12 col-xs-12" ><?php echo $tr->translate('CONTENT_'.strtoupper($rs['title']))?><span class="required">*</span>
				                   </label>
				                   <div class="col-md-12 col-sm-12 col-xs-12">
				                 	  <textarea class="ckeditor"   style="min-height:400px; height:400px;" id="description<?php echo str_replace(' ','',$rs['title']);?>" name="description<?php echo str_replace(' ','',$rs['title']);?>"></textarea>
				                   </div>
				                </div>
				          	</div>
				        <?php }?>
					 </div>
					<?php }?>
		            </div>
	        	<div class="col-md-4 col-sm-4 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-3 col-md-3 col-xs-12" ><?php echo $tr->translate("ORDERING");?> :</label>
	                   <div class="col-md-9 col-sm-9 col-xs-12">
	                   		<input dojoType="dijit.form.NumberTextBox" required="true" class="fullside" id="ordering" name="ordering" value="0" type="text">
	                   </div>
	                </div>
	           </div>
	        </div>
	        <div class="card-box">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input class="button-class button-danger" iconClass="glyphicon glyphicon-repeat" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
					<input class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" type="submit" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" />
					<input class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button"  />
               	</div>
            </div>
		</form>
	</div>
</div>
