<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CUTSTOCK')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->frm_payment;
?>	
 <style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
span.oldsup {
    font-style: normal;
    padding-left: 10px;
    color: #cc0100;
}
span.oldsup input[type=checkbox] {
    margin: 0;
    padding: 0;
    height: initial;
}
label.invoicelabel {
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
    width: 120px;
}
tr.head-td th {
    white-space: nowrap;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-cubes" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_CUTSTOCK');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id=office_receipt action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
 				branch_id = dijit.byId('branch_id').get('value');
				if(branch_id==""){
					alert("<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>");
					dijit.byId("branch_id").focus();
					return false;
				}
				student_id = dijit.byId('student_id').get('value');
				if(student_id==""){
					alert("<?php echo $tr->translate('PLEASE_SELECT_STUDENT');?>");
					dijit.byId("student_id").focus();
					return false;
				}
				if($('#identity').val()==""){
					alert("<?php echo $tr->translate('PLEASE_CHECK_PRODUCT_TO_RETURN');?>");
					return false;
				}
				total_paid = dijit.byId('total_paid').get('value');
				if(total_paid==""){
					alert("<?php echo $tr->translate('PLEASE_ENTER_QTY_TO_RETURN');?>");
					dijit.byId("amount").focus();
					return false;
				}
                loadingBlock();
				return true;
			} else {
				return false;
			}
			</script>
	          <div class="card-box">
	          	<div class="col-md-12 col-sm-12 col-xs-12">
          		 	<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH");?> 
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement("branch_id");?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STUDENT_NAME");?> 
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input id="student_id" />
		                   		<input type="hidden" name="student_name" id="student_name"  value="<?php echo $this->exchange_rate;?>" class="form-control" />
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("REMAIN");?> 
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement("balance");?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ALL_QTY_BALANCE");?> 
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement("all_balance");?>
		                   </div>
		                </div>
		            </div>
		            <div class="col-md-6 col-sm-6 col-xs-12">
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RECEIPT_NO");?> 
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement("serailno");?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RECEIVED_DATE");?> 
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement("date_payment");?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php //echo $tr->translate("PAID_BY");?> 
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php //echo $frm->getElement("paid_by");?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("AMOUNT");?> 
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement("amount");?>
		                   </div>
		                </div>
		            </div>
				</div>
			</div>
			<div class="x_panel">
				<div class="card-box">
					<div class="x_panel searc-blog">
		          		<div class="x_title">
						   	<h2><i class="fa fa-search"></i> <?php echo $tr->translate("FILTER")?></h2>
							<span class="pull-right"></span>
							<div class="clearfix"></div>
						</div>
						<div class="x_content search">
							<div class="form-group" >      
				                 <label style=" margin: 0; line-height: 30px; " class="control-label bold col-md-2 col-sm-2 col-xs-12"><?php echo $tr->translate("FILTER_BY_RECIEPT_NO");?> </label>
				                 <div class="col-md-7 col-sm-7 col-xs-12">
				                		<?php echo $frm->getElement("bypuchase_no");?>
				                </div>
				                <div class="col-md-3 col-sm-3 col-xs-12">
		                   			<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('SEARCH');?>" dojoType="dijit.form.Button" onclick="getStudentProductPaymentDetail();"/>
		                   		</div>
				                <div class="clearfix"></div>
				                <div class="clearfix">
				               		 <input type="checkbox" class="checkbox"  name="check_all" id="check_all" value="all" OnChange="CheckAllTotal(0);" style="display: inline-block;height: initial;"  />&nbsp;
									<span class="bold" style="vertical-align: top;"><?php echo $tr->translate('ALL');?></span>
								</div>
			             	</div>
						</div>            
				       </div>
			       </div>
		       </div>
		       <div class="card-box">
	             	<div class="form-group">
	          			<table  style="margin: 0 auto; width: 100%; border-collapse: collapse; border: 1px #ccc solid;">
							<thead>
								<tr id="head-title" class="head-td" align="right">
									<th>&nbsp;</th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style=" min-width: 105px;"><?php echo $tr->translate("DATE");?></th>
									<th><?php echo $tr->translate("RECEIPT_NO");?></th>
									<th><?php echo $tr->translate("PRODUCT");?></th>
									<th><?php echo $tr->translate("ORIG");?></th>
									<th><?php echo $tr->translate("DUE");?></th>
									<th><?php echo $tr->translate("RECEIVE_QTY");?></th>
									<th><?php echo $tr->translate("REMAIN");?></th>
									<th><?php echo $tr->translate("REMIDE_DATE");?></th>
								</tr>
							</thead>
							<tbody id="table_row">
							<tbody>
						</table>
						<input type="hidden" id="identity" name="identity" />
						<input type="hidden" name="old_identity" id="old_identity"  value="" >
				 </div>
          	</div>	
	          
	          <div class="clearfix"></div>
	          <div class="card-box">
          		 <div class="col-md-8 col-sm-8 col-xs-12">
          		 	<div class="form-group">
	                   <label class="control-label bold col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> 
	                   </label>
	                </div>
          		 	<div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<?php echo $frm->getElement("note");?>
	                   </div>
	                </div>
          		 </div>
          		 <div class="col-md-4 col-sm-4 col-xs-12">
          		 	<div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_RECEIVED");?> 
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("total_paid");?>
	                   </div>
	                </div>
	                <div class="form-group" style="display: none;">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_DISCOUNT");?> 
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("total_discount");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_QTY_DUE");?> 
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("total_due");?>
	                   </div>
	                </div>
          		 </div>
         	 </div>  
	          <div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
					<input type="submit" name="save_close" id="save_close" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>"  dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					<input type="button" id="popup" value="popup" label="<?php echo $tr->translate('SAVE_PRINT');?>" onclick="printSave();" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconTask" />
               	</div>
             </div>  
		</form>
    </div>
</div>
<div class="dijitHidden" style="padding: 0px; margin: 0px;">
	<div id="terms" data-dojo-type="dijit.Dialog" style="width:23.5cm;height: 16cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("បោះពុម្ពទទួលទំនិញ");?>'"  >
	<div id="PrintReceipt" style="width: 22cm !important; padding: 0px; margin-bottom:30px; ">
		<style>
			.print tr td{
					padding:0px 2px 0px 2px; 
				}
				tr.hearder_table td {
				    padding: 5px;
				}
		</style>
		<table width="100%"  class="print" cellspacing="0"  cellpadding="0" style="height:4cm;font-family: 'Times New Roman','Khmer OS Battambang' !important;font-size:15px !important;white-space:nowrap;">
			<tr>
				<td colspan="4"><label id="lbl_header"></label></td>
			</tr>
			<tr>
				<td colspan="4" align="center">
					<strong style="font-family:'Khmer OS Muol';">បង្កាន់ទទួលទំនិញ</strong>
				</td>
			</tr>
			<tr>
				<td>Student's ID : &nbsp;&nbsp;<span id="lb_id"></span> </td>
				<td></td>
				<td colspan="2" align="right"><span style="text-align:left; min-width: 100px; display: inline-block;">Ref Receipt No.</span> : <span id="lb_receipt_no" style="text-align:left; color:red; min-width: 100px; display: inline-block;"></span></td>
			</tr>
			<tr>
				<td>Student's Name : &nbsp;&nbsp;<span id="lb_name"></span></td>
				<td></td>
				<td colspan="2" align="right"><span style="text-align:left; min-width: 100px; display: inline-block;">Received Date</span> : <span id="lb_date" style="text-align:left; min-width: 100px; display: inline-block;"><?php echo date("d/M/Y",strtotime($this->row['received_date']));?></span></td>
			</tr>
			<tr>
				<td  colspan="4">
					<div id="t_amountmoneytype"></div>
				</td>
			</tr>
			<tr>
				<td colspan="2" width="50%" align="center">
					<div style="margin-top:40px;font-size:10px;"></div>
					<?php echo $tr->translate("INFORS_TO");?>
				</td>
				<td colspan="2" width="50%" align="center">
					<div style="margin-top:40px;font-size:10px;"></div>
					<?php echo $tr->translate("INFORS_RECEIVE");?>
				</td>
			</tr>
			<tr>
				<td colspan="2" width="50%" align="center">
					<div style="margin-top:30px;font-size:10px;"></div>
					<?php 
						   $session_user=new Zend_Session_Namespace(SYSTEM_SES);
						   $last_name=$session_user->last_name;
						   $username = $session_user->first_name;
						   echo "".$last_name." ".$username;
						?>
				</td>
				<td colspan="2" width="50%" align="center">
					<div style="margin-top:30px;font-size:10px;"></div>
					<span id="studentpay"></span>
				</td>
			</tr>
			<tr>
				<td colspan="4" align="right">
					<!-- <div style=" font-size: 11px;font-weight: bold;font-family: arail">Date : <label id="lb_date" class=" one bold"><?php //echo date("d/M/Y",strtotime($this->row['received_date']));;?></label></div> -->
					<div style="padding-top:20px; font-size:10px;"><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?></div>
				</td>
			</tr>
		</table>
	</div>
	<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
			<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
			type="button" onclick="hideDialog();">Cancel</button>
			<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				type="button" onclick="printSubmit();"><?php echo $tr->translate("Print");?></button>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
var oldBranch = '<?php echo empty($this->stu['branch_id'])?"":$this->stu['branch_id'];?>';
var oldStudent = '<?php echo empty($this->stu['stu_id'])?'':$this->stu['stu_id'];?>';
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.DateTextBox");
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dojo.number");
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "student_id",
			name: "student_id",   
			required:true,        
			class: 'fullside', 
			placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
			onChange: function(){
					getStudentProductPaymentDetail();
			}
		}, "student_id");
		
		var branch_id = dijit.byId('branch_id');
	 	branch_id.on('change', function(evt) {
	 		getbranchinfo();
			getallstudentname();
	 		getStudentProductPaymentDetail();
	    });
		if(oldBranch!=''){
			dijit.byId('branch_id').attr('value',oldBranch);
		}
	 	
	 	getbranchinfo();
		getallstudentname();
 		getStudentProductPaymentDetail();
});	
var url_getbranch = "<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getbranchinfo')); ?>";
function getbranchinfo(){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id != ""){
			dojo.xhrPost({
				url:url_getbranch,
				content:{
					'branch_id':branch_id,
					},
				handleAs:"json",
				load: function(data){
					dojo.byId('lbl_header').innerHTML=data;
					getReceiptNo();
				},
				error: function(err) {
				}
			});	
		} 
	}
var url_getreceipt_no = '<?php echo $this->url(array('module'=>'stock','controller'=>'cutstock','action'=>'getreceipt')); ?>';
function getReceiptNo(){
	var branch_id = dijit.byId('branch_id').get('value'); 
	if(branch_id==""){
		return false;
	}
	dojo.xhrPost({
		url:url_getreceipt_no,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			dijit.byId('serailno').attr('value',data); 
			dojo.byId("lb_receipt_no").innerHTML = data;
		},
		error: function(err) {
		}
	});
}
function printSave(new_receipt){
	if(dijit.byId('office_receipt').validate()){
		getReceiptNo();
		today = dijit.byId("date_payment").get("value");
		var dd = today.getDate();
		var mon = today.toDateString().substr(4,3); //January is 0!
		var yyyy = today.getFullYear();
		dojo.byId("lb_date").innerHTML = dijit.byId("date_payment").attr('displayedValue');
	template="";
	temp='';
    temp='<table border="1" align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:11px;font-family:Khmer OS Battambang !important; white-space:nowrap; ">'
		  temp+='<tr class="hearder_table" style=" font-size:12px; text-align:center;background:#f2f2f2;font-weight:bold;">';
			  temp+='<td >No</td>';
			  temp+='<td >Receipt</td>';
			  temp+='<td >Item Name</td>';
			  temp+='<td >Qty</td>';
			  temp+='<td >Qty Received</td>';
			  temp+='<td >Qty Balance</td>';
			  temp+='<td >Remain Date</td>';
		  temp+='</tr>';
		  var rowId = $('#identity').val();
			var rowIDArray = rowId.split(',');
			i=0;
			for(var n = 0; n < rowIDArray.length; n++){
				i++;
				remain = $('#remain'+rowIDArray[n]).val();
				dateremide="-";
				if(remain!=0){
					var b = new Date(dijit.byId("remide_date"+rowIDArray[n]).get('value'));
					  mm = b.getMonth()+1;
					  var dd = b.getDate();
					  if(dd<10){
						dd = "0"+dd;
					  }
					  var mon = getMonthByNumber(mm);
					  if(mm<10){
						mm = "0"+mm;
					  }
					  var y = b.getFullYear();
					  var dateremide = dd + '/' + mon + '/' + y ;
				}
		      	temp+='<tr class="rowlist">';
			 	temp+='<td align="center">&nbsp;'+i+'&nbsp;</td>';
			 	temp+='<td align="center">&nbsp;'+$('#receipt_number'+rowIDArray[n]).val()+'&nbsp;</td>';
			  	temp+='<td>&nbsp;'+$('#productname'+rowIDArray[n]).val()+'&nbsp;</td>';
			  	temp+='<td align="center">&nbsp;'+$('#qty_balance'+rowIDArray[n]).val()+'&nbsp;</td>';
			  	temp+='<td align="center">'+$('#qty_receive'+rowIDArray[n]).val()+'</td>';
			  	temp+='<td align="center">&nbsp;'+remain+'&nbsp;</td>';
			  	temp+='<td align="center">&nbsp;'+dateremide+'&nbsp;</td>';
				temp+='</tr>';
			}
			temp+='<tr class="rowlist">';
				temp+='<td colspan="6" align="right" style=" border-bottom: #fff 1px solid; border-left: 1px solid #fff;">Total Received :</td>';
				temp+='<td align="center">&nbsp;&nbsp;'+dijit.byId('total_paid').get('value')+'&nbsp;</td>';
			temp+='</tr>';
			temp+='<tr class="rowlist">';
				temp+='<td colspan="6" align="right" style=" border-bottom: #fff 1px solid; border-left: 1px solid #fff;">Total Remain :</td>';
				temp+='<td align="center">&nbsp;&nbsp;'+dijit.byId('total_due').get('value')+'&nbsp;</td>';
			temp+='</tr>';
		temp+='</table>';
	dojo.byId('t_amountmoneytype').innerHTML = temp;
	dijit.byId("terms").show();	
	}
}
function getMonthByNumber(m){
	var monthName=[
	         "Jan",
      		 "Feb",
      		 "Mar",
      		 "Apr",
      		 "May",
      		 "Jun",
      		 "Jul",
      		 "Aug",
      		 "Sept",
      		 "Oct",
      		 "Nov",
      		 "Dec",
		];
	return (monthName[m-1]);
}
function getallstudentname(){//
		var url_data = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getallstudent')); ?>';
		branch_id = dijit.byId("branch_id").attr("value");
		if(branch_id==''){
			dijit.byId("branch_id").focus();
			return false;
		}
		dojo.xhrPost({
			url:url_data,
			content:{
				'student_name':1,
				'branch_id':branch_id,
			},
			handleAs:"json",
			load: function(data) {
				student_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('student_id').set('store',student_store);  
			    if(oldBranch == branch_id){
			    	dijit.byId('student_id').set('value',oldStudent);  
			    }
			},
			error: function(err) {
			}
		});
	}
	var keyindex=1;
	var url_getSupplier = '<?php echo $this->url(array('module'=>'stock','controller'=>'cutstock','action'=>'getallpaydetailbystudent')); ?>';
	function getStudentProductPaymentDetail(){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id==""){
			dijit.byId("branch_id").focus();
			return false;
		}
		student_id = dijit.byId('student_id').get('value');
		if(student_id==""){
			dijit.byId("student_id").focus();
			return false;
		}
		invoicesearch = dijit.byId('bypuchase_no').get('value');
		loadingBlock();
		dojo.xhrPost({
			url: url_getSupplier,
			content:{
				'branch_id':branch_id,
				'student_id':student_id,
				'keyindex':keyindex,
				'bypuchase_no':invoicesearch,
	 			},
			handleAs:"json",
			load: function(data) {
				keyindex=data.keyindex;
				$("#old_identity").val(data.identity);
				$("#identity").val(data.identity);
				dojo.html.set(dojo.byId("table_row"),data.stringrow,{
				     parseContent: true,
					});
				dijit.byId('all_balance').set('value',data.all_balance);
				dijit.byId('amount').set('value',data.all_balance);	

				dojo.byId("lb_name").innerHTML =  data.stuName;
				dojo.byId("lb_id").innerHTML =  data.stucode;
				dojo.byId("studentpay").innerHTML =  data.stuName;
				
				calculateAmountCheck();
				calBalance();
				HideloadingBlock();
			},
			error: function(err) {
				HideloadingBlock();
			}
		});
	}
	
	function hideDialog(){
		dijit.byId('terms').hide();
	}

	function printSubmit(){
		getReceiptNo();
		window.frames["print_frame"].document.body.innerHTML = dojo.byId('PrintReceipt').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    loadingBlock();
	    HideloadingBlock();
	    dijit.byId('office_receipt').submit();
	}
	function CheckAllTotal(index){
		var total = 0;
		var descriptionr="";
		var old_identity = $("#old_identity").val();
		if(index==0){
				if($('#check_all').is(":checked")){
					$('.checkbox').each(function() { //loop through each checkbox
			            this.checked = true;  
					});
					$("#identity").val(old_identity);
				}else{
					$('.checkbox').each(function() { //loop through each checkbox
			            this.checked = false;  
					});
					ResetPayment();
					$("#identity").val('');
				}
		}else{
			 $('#check_all').attr('checked', false); // Unchecks it
			var a = $("input:checked").val();
			 var identity = [];
		     $(':checkbox:checked').each(function(i){
		    	 identity[i] = $(this).val();
		     });
		     $("#identity").val(identity);
		     var newIdentity = $("#identity").val();
				if(old_identity == newIdentity ){
					$('#check_all').attr('checked', true); // checks it
				}
			if($('#mfdid_'+index).is(":checked")){
			}else{
				dijit.byId('qty_receive'+index).set('value',0);
				calculateAmountCheckByKeyup();
				ResetPayment();
			}
		}
		calculateAmountCheck();
		calBalance();
	}
	function ResetPayment(){
		var old_identity = $("#old_identity").val();
		var rowIDArray = old_identity.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			dijit.byId('qty_receive'+rowIDArray[n]).set('value',0);
			amountrow = parseFloat(dijit.byId('qty_balance'+rowIDArray[n]).get('value'));
			discount = 0;
			amountrowdis = parseFloat((amountrow*parseFloat(discount))/100).toFixed(2);
			amountrowafterdis = amountrow - amountrowdis; //amount after discount
			amountrow = parseFloat(dijit.byId('remain'+rowIDArray[n]).set('value',amountrowafterdis.toFixed(2)));
		}
	}
	function calBalance() {
		var balance=0;
		var rowId = $('#old_identity').val();
		if(rowId==""){
			return false;
		}
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			if($('#mfdid_'+rowIDArray[n]).is(":checked")){
				amountrow = parseFloat(dijit.byId('qty_balance'+rowIDArray[n]).get('value'));
				discount = 0;
				amountrowdis = parseFloat((amountrow*parseFloat(discount))/100).toFixed(2);
				amountrowafterdis = amountrow - amountrowdis; //amount after discount
				balance = balance + parseFloat(amountrowafterdis);
			}
		}
		dijit.byId('balance').attr('value',balance.toFixed(2));
	}
	function checkAmout(){
		amount_paid = parseFloat(dijit.byId('amount').get('value'));
		balance = parseFloat(dijit.byId('balance').get('value'));
		if(amount_paid>=balance){
			dijit.byId('amount').set('value',balance.toFixed(2))
		}
		calculateAmountCheck();
	}
	function calculateAmountCheck(){
		ResetPayment();
		amount_paid = parseFloat(dijit.byId('amount').get('value'));
		var rowId = $('#identity').val();
		if(rowId==""){
			return false;
		}
		var credit=0;
		var payment=0;
		var amount = 0;
		var due = 0;
		var discount = 0;
		var totaldis=0;
		var amountrow = 0;
		var rowIDArray = rowId.split(',');
		var amountrowdis = 0;
		if(amount_paid>0){
			var paid=0;
			for(var n = 0; n < rowIDArray.length; n++) {
				amountrow = parseFloat(dijit.byId('qty_balance'+rowIDArray[n]).get('value'));
				discount =0;
				amountrowdis = parseFloat((amountrow*parseFloat(discount))/100).toFixed(2);
				amountrowafterdis = amountrow - amountrowdis; //amount after discount
				amount_paid = amount_paid - parseFloat(amountrowafterdis);
				totaldis+=  totaldis+parseFloat(amountrowdis);
				if(amount_paid>=0){
					payment+= amountrowafterdis;
					dijit.byId('qty_receive'+rowIDArray[n]).set('value',amountrowafterdis.toFixed(2));
					dijit.byId('remain'+rowIDArray[n]).set('value',0);
					
					due+= 0;
				}else{
					remain = Math.abs(amount_paid);
					paid = parseFloat(dijit.byId('qty_balance'+rowIDArray[n]).get('value')) - parseFloat(remain);
					dijit.byId('qty_receive'+rowIDArray[n]).set('value',paid.toFixed(2));
					dijit.byId('remain'+rowIDArray[n]).set('value',remain.toFixed(2));
					payment+= paid;
					due+= remain;
					break;
				}
			}
		}
		calculateLastTotal();
	}
	function calculateLastTotal(){
		var rowId = $('#identity').val();
		if(rowId==""){
			return false;
		}
		var credit=0;
		var payment=0;
		var amount = 0;
		var due = 0;
		var discount = 0;
		var totaldis=0;
		var amountrow = 0;
		var rowIDArray = rowId.split(',');
		var amountrowdis = 0;
		for(var n = 0; n < rowIDArray.length; n++) {
			payment+= parseFloat(dijit.byId('qty_receive'+rowIDArray[n]).get('value'));
			due+= parseFloat(dijit.byId('remain'+rowIDArray[n]).get('value'));

			amountrow = parseFloat(dijit.byId('qty_balance'+rowIDArray[n]).get('value'));
			discount = 0;
			amountrowafterdis = ((amountrow*parseFloat(discount))/100).toFixed(2);
			totaldis= totaldis+parseFloat(amountrowafterdis);
		}
		dijit.byId('total_discount').attr('value',totaldis);
		dijit.byId('total_paid').attr('value',payment.toFixed(2));
		dijit.byId('total_due').attr('value',due.toFixed(2));
	}
	function calculateamount(index){
		var due = dijit.byId('qty_balance'+index).get('value');
		var discount = 0;
		var payment = dijit.byId('qty_receive'+index).get('value');
		var paid =0;
		var subtotal=0;
		paid = parseFloat(payment);
		subtotal= parseFloat(due) - ((parseFloat(due)*parseFloat(discount))/100).toFixed(2);
		if(paid > subtotal){
			dijit.byId('qty_receive'+index).set('value',subtotal.toFixed(2));
			dijit.byId('remain'+index).set('value',0);
		}else{
			dijit.byId('remain'+index).set('value',(subtotal-paid).toFixed(2));
		}
		calBalance();
		calculateAmountCheckByKeyup();
	}
	function calculateAmountCheckByKeyup(){
		var rowId = $('#identity').val();
		if(rowId==""){
			return false;
		}
		var payment=0;
		var amount = 0;
		var due = 0;
		var discount = 0;
		var totaldis=0;
		var amountrow = 0;
		var rowIDArray = rowId.split(',');
			for(var n = 0; n < rowIDArray.length; n++) {
				payment+= parseFloat(dijit.byId('qty_receive'+rowIDArray[n]).get('value'));
				due+= parseFloat(dijit.byId('remain'+rowIDArray[n]).get('value'));
		
				amountrow = parseFloat(dijit.byId('qty_balance'+rowIDArray[n]).get('value'));
				discount = 0;
				amountrowafterdis = ((amountrow*parseFloat(discount))/100).toFixed(2);
				totaldis= totaldis+parseFloat(amountrowafterdis);
			}
		amount = parseFloat(payment).toFixed(2);
		dijit.byId('total_discount').attr('value',totaldis.toFixed(2));
		dijit.byId('total_paid').attr('value',payment.toFixed(2));
		dijit.byId('total_due').attr('value',due.toFixed(2));
		dijit.byId('amount').attr('value',parseFloat(amount).toFixed(2));
	}
</script>