<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
	$pageTitle = $tr->translate("EDIT_ISSUE_SCORE");
	echo $this->headTitle($pageTitle);
	$base_url = Application_Form_FrmMessage::getUrl("/");
	
	$pageTitle = '<i class="glyphicon glyphicon-pencil"></i> '.$pageTitle;
	$current_month = date("m");
	$row = $this->rs;
?>	
<?php 
	echo $this->render('externalHead.phtml');
?>
<div class="row"> 
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="card mb-1 ">
			<div class="card-header pb-1"> 
				<h3 class="card-title mb-2 "><?php echo $row['branchName'].' "ថ្នាក់ '." ".$row['groupCode'].'"'?></h3> 
				<h3 class="card-title mb-2 "><?php echo $row['branchNameEn'].' "Class'." ".$row['groupCode'].'"'?></h3> 
			</div>
			<div class="card-content collapse show mt-1">
				<form id='scoreForm' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<script type="dojo/method" event="onSubmit">   
					if(this.validate()){
						var identity = $('#identity').val();
						if(identity==''){
							var msgTitle = "បំពេញព័ត៌មានមិនគ្រប់គ្រាន់ / Incompleted Data To save";
							var msgDesc = "មិនមានព័ត៌មានសិស្សដែលត្រូវបញ្ចូល / There is no record to save";
							infoMessageAlert(msgTitle,msgDesc);
							return false;
						}
						var msgTitle = "អ្នកពិតជាចង់រក្សាទុកទីន្នន័យនេះឬ ? / Do you want to Save it ?";
						var msgDesc = "សូមធ្វើការត្រួតពិនិត្យព័ត៌មានមុនពេលរក្សាទុក ! / Please checking information before saving !";
						comfirmingSubmit('scoreForm',msgTitle,msgDesc);
						return false;
						
					}else {
						return false;
					}
					</script>
					<div class="card-box">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex ">ព័ត៌មានពិន្ទុ / Score Info</p>
												</div> 
											</div>
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12">ពិន្ទុសម្រាប់/Score For</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<div class="col-md-4 col-sm-4 col-xs-12">
														<select readOnly id="examType" name="examType" class="fullside" onchange="checkExamType(); getAllSubject();"  dojoType="dijit.form.FilteringSelect" >
															<option value="1" <?php if(1==$this->rs['examType']){echo "selected='selected'";}?>>ប្រចាំខែ/Monthly Exam</option>
															<option value="2" <?php if(2==$this->rs['examType']){echo "selected='selected'";}?>>ប្រចាំឆមាស/Semester Exam</option>
														</select>
														
														<input type="hidden" name="branch_id" id="branch_id" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $row['branchId']?>" />
														<input type="hidden" name="group" id="group" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $row['groupId']?>"/>
														<input type="hidden" name="gradingId" id="gradingId" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $row['gradingId']?>"/>
														<input type="hidden" name="id" id="id" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->rs['id']?>" />
													</div>
													<div class="col-md-4 col-sm-4 col-xs-12">
														<select readOnly dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="forSemester" name="forSemester" queryExpr="*${0}*" autoComplete="false">								
															<option value="1" <?php if(1==$this->rs['forSemester']){echo "selected='selected'";}?>>ឆមាសទី១/Semester I</option>
															<option value="2" <?php if(1==$this->rs['forSemester']){echo "selected='selected'";}?>>ឆមាសទី២/Semester II</option>
														</select>
													</div>
													<div class="col-md-4 col-sm-4 col-xs-12">
														<select readOnly dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="forMonth" name="forMonth" queryExpr="*${0}*" autoComplete="false">								
															<?php if(!empty($this->month)){foreach ($this->month as $month){?>
																<option value="<?php echo $month['id']?>" <?php if($month['id']==$this->rs['forMonth']){echo "selected='selected'";}?>><?php echo $month['name'];?></option>
															<?php }}?>
														</select>
													</div>
												</div>
											</div>
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12">មុខវិជ្ជា/Subject</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													
													<input id="subjectId" />
													<input type="hidden" name="maxSubjectScore" id="maxSubjectScore" class="fullside" dojoType="dijit.form.TextBox" value="0"/>
												</div>
											 </div>
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12">តម្រៀបសិស្ស/Sort Student Lists</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<select id="sortStundent" name="sortStundent" class="fullside" onchange="filterStudent()"  dojoType="dijit.form.FilteringSelect" >
														<option value="0">ទូរទៅ / Default </option>
														<option value="1">លេខសម្គាល់សិស្ស/Student ID (ASC)</option>
														<option value="2">ឈ្មោះសិស្សខ្មែរ/Name In Khmer (ASC)</option>
														<option value="3"> ឈ្មោះសិស្សអង់គ្លេស / Name In English (ASC)</option>
													</select>
												</div>
											 </div>
											 <div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12">សម្គាល់ / Remark</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<input class="fullside" placeholder="<?php echo $tr->translate("NOTE");?>" dojoType="dijit.form.Textarea"  id="note" name="note" value="<?php echo $this->rs['note'];?>" type="text" style=" height: 120px !important;"  >
												</div>
											 </div>
											 <div class="form-group">
													<label class="control-label custom-switch float-end "> 
														<a href="javascript:void(0);" class="switchButton status">ស្ថានការណ៍/Status</a> 
														<input type="checkbox" id="status" name="status" class="custom-switch-input"  <?php if(!empty($this->rs['status'])){ echo "checked";} ?> > 
														<span class="custom-switch-indicator custom-radius switch-status"></span> 
													</label>
												</div>
										 </div>
									 </div>
								 </div>
							 </div>
							
								
								  
						  </div>
						  <div class="col-md-6 col-sm-6 col-xs-12">
								<div class="card-info bg-gradient-directional-notice">
									<div class="card-content">
										<div class="card-body">
											<div class="media d-flex">
												<div class="media-body text-dark text-left align-self-bottom ">
													<span class="d-block mb-1 font-medium-1"></span>
													<ul class="optListRow">
														<li class="opt-items titleEx"><h4 class="text-dark mb-10">ព័ត៌មានថ្នាក់សិក្សា/Class Student Info.</h4></li>
														<li class="opt-items two-column"><span class="lbl-tt">ឆ្នាំសិក្សា/Academic Year</span>: 	<span class="text-value"><?php echo $row['academicYear'];?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt">កម្រិត/Degree</span>: 			<span class="text-value"><?php echo $row['degreeTitle'];?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt">បន្ទប់/Room</span>: 				<span class="text-value"><?php echo $row['roomName'];?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt">ថ្នាក់/Grade</span>: 				<span class="text-value"><?php echo $row['gradeTitle'];?></span></li>
														
													</ul>
												</div>
												<div class="align-self-top">
												<i class="fa fa-info-circle icon-opacity2 text-dark font-large-4 float-end"></i>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div id="gradingInfo">
								</div>
								
							 
								 
						  </div>
					 </div>
					 <div class="card-box">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<div id="studentList">
							</div>
							<input type="hidden" name="identity" id="identity"  value="" >
							<input type="hidden" dojoType="dijit.form.TextBox" name="indexKey" id="indexKey"  value="" >
							<div class="form-group">
								
								<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;width:100%" >
								</table>
							</div>
						</div>
				   </div>
				   <div class="clearfix"></div>
					 <div class="card-box mt-20">
						<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" label="រក្សាទុក/Save" dojoType="dijit.form.Button" />
						</div>
					 </div>
				</form>
			</div>
		</div>
	</div>
</div>
<style>
ul.optListRow.gradingInfo li {
    font-size: 11px;
    padding: 0;
}
th.criterialTitle {
    background: #c4d4eb;
}
tr.head-td th {
    vertical-align: top;
}
.lableEng {
    display: block;
    line-height: 12px;
}
small.small-label {
    font-size: 9px;
    line-height: 11px;
    margin-top: 2px;
    display: block;
}
span.titleSubCriterial {
    font-size: 9px;
    display: block;
    line-height: 12px;
    font-weight: 600;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">

$( document ).ready(function() {
   setPageTitle('<?php echo $pageTitle; ?>');
});
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require('dijit.form.NumberTextBox');
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,             
		id: "subjectId",
		name: "subjectId",           
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_SUBJECT");?>",          
		onChange: function() {
			getSubjectInfo();
		}
	}, "subjectId");
	
	getAllSubject();
});
urlGetSubjectStore = '<?php echo $this->url(array('module'=>'default','controller'=>'external','action'=>'getsubjectlist'));?>';
function getAllSubject(){
	dijit.byId('subjectId').reset();
	var subjectStore  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dijit.byId('subjectId').set('store',subjectStore); 
	
	group = dijit.byId('group').get('value');
	examType = dijit.byId('examType').get('value');
	
	dojo.xhrPost({
		url: urlGetSubjectStore,
		content:{
			'groupId':group,
			'examType':examType,
			},
		handleAs:"json",
		load: function(data) {
		    subjectStore  = getDataStorefromJSON('id','name', data);
		    dijit.byId('subjectId').set('store',subjectStore);   
			dijit.byId('subjectId').set('value','<?php echo $this->rs['subjectId'];?>');   
			dijit.byId('subjectId').set("readOnly",true);
		},
		error: function(err) {
		}
	});
}


var subject = <?php print_r(Zend_Json::encode($this->criterial));?>;
var urlGetSubjectInfo= '<?php echo $this->url(array('module'=>'default','controller'=>'external','action'=>'getsubjectinfo')); ?>';
function getSubjectInfo(){
	group = dijit.byId('group').get('value');
	subjectId = dijit.byId('subjectId').get('value');
	if(subjectId=='' || subjectId==0){
		$('#identity').val('');
		dojo.query("#table_row").append("");
		return false;
	}
	
	examType = dijit.byId('examType').get('value');
	
	dojo.xhrPost({
	    url: urlGetSubjectInfo,
	    content : { 
			'groupId':group,
			'examType':examType,
			'subjectId':subjectId,
		},				    
	   handleAs:"json", 
	   load: function(data) {
		   dijit.byId('maxSubjectScore').attr('value',data.maxSubjectscore);
		   filterStudent();
	   },		
	    error: function(err) {
	    }
	});
}

var inx=0;

var urlGetStudent= '<?php echo $this->url(array('module'=>'default','controller'=>'issuescore','action'=>'get-studentedit')); ?>';
function filterStudent(){
	$('#identity').val('');
	dojo.query("#table_row").append("");
	loadingBlock();
	
	group = dijit.byId('group').get('value');
	sortStundent = dijit.byId('sortStundent').get('value');
	amtsubject = 0;
	currentID = dijit.byId('id').get('value');
	examType = dijit.byId('examType').get('value');
	subjectId = dijit.byId('subjectId').get('value');
	gradingId = dijit.byId('gradingId').get('value');
	maxSubjectScore = dijit.byId('maxSubjectScore').get('value');
	
	if(group==''){
		return false;
	}
	dojo.xhrPost({
	    url: urlGetStudent,
	    content : { 
			'groupId':group
			,'sortStundent':sortStundent
			,'maxSubjectScore':maxSubjectScore
			,'examType':examType
			,'subjectId':subjectId
			,'gradingId':gradingId
			,'keyIndex':inx
			,'currentID':currentID
			
		},				    
	   handleAs:"json", 
	   load: function(data) {
		 
	       if(data!=""){
				
				inx=data.keyIndex;
				$("#identity").val(data.identity);
				
				dojo.html.set(dojo.byId("studentList"),data.contentHtml , {
					parseContent: true,
				});
				
				dojo.html.set(dojo.byId("gradingInfo"),data.htmlGradingInfo , {
					parseContent: true,
				});
				
				calculateAverage();
	       }else{
		    	$('#identity').val('');
	       }
		   HideloadingBlock();	
	   },		
	    error: function(err) {
			HideloadingBlock();
	    }
	});
	
}

function deleteRecord(index){
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
function gender(sex){
	if(sex==1){
		sex='<?php echo $tr->translate('MALE');?>';
	}else sex='<?php echo $tr->translate('FEMALE');?>';
	return sex;
}
function checkExamType(){
	examType = dijit.byId("examType").get("value");
	dijit.byId('forMonth').set("readOnly",false);
	if(examType==2){
		dijit.byId('forMonth').set("readOnly",true);
	}
}


function checkAllCaterial(index){
	
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if($('#checkAll'+index).is(":checked")){
			dijit.byId('score_'+arrays[i]+'_'+index).attr('value',0);
			dijit.byId('score_'+arrays[i]+'_'+index).set("readOnly",true);
		}else{
			dijit.byId('score_'+arrays[i]+'_'+index).attr('value',0);
			dijit.byId('score_'+arrays[i]+'_'+index).set("readOnly",false);
		}
	}
	
}

var urlCalculateEverage= '<?php echo $this->url(array('module'=>'default','controller'=>'issuescore','action'=>'calculate-average')); ?>';
function calculateAverage(indexKey=null){
	dijit.byId('indexKey').attr('value',indexKey);
	//if(dijit.byId('scoreForm').validate()){
		dojo.xhrPost({
			url: urlCalculateEverage,
			form: dojo.byId("scoreForm"),
		   handleAs:"json", 
		   load: function(data) {
			   if(indexKey!=null){
				   dijit.byId('average'+indexKey).attr('value',data);
			   }else{
				   var identity = $('#identity').val();
					var arrays = identity.split(',');
					for(var i=0;i<arrays.length;i++) {
						keyRow = +arrays[i];
						dijit.byId('average'+keyRow).attr('value',data[keyRow]);
					}
			   }
			   
		   },		
			error: function(err) {
			}
		});
	//}	
}
</script>
<?php 
	echo $this->render('externalFoot.phtml');
?>