<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
	$pageTitle = $tr->translate("ISSUE_SCORE");
	echo $this->headTitle($pageTitle);
	$base_url = Application_Form_FrmMessage::getUrl("/");
	
	$pageTitle = '<i class="glyphicon glyphicon-tasks"></i> '.$pageTitle;

	$current_month = date("m");
	$msgTitle = "ទិន្នន័យស្ទួន / Duplicated Record";
	$msgDesc = "ពិន្ទុមុខវិជ្ជានេះបានបញ្ចូលរួចរាល់ហើយ / This subject's score has been entered !";
	$resultRecord = $this->resultRecord;
?>	
<?php 
	echo $this->render('externalHead.phtml');
?>
<div class="row"> 
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="card mb-1 ">
			<div class="card-header pb-1"> 
				<h3 class="card-title mb-2 "><?php echo $this->row['branchNameKh'].'/'.$this->row['branchNameEn'].' "ថ្នាក់ '." ".$this->row['group_code'].'"'.' "Class'." ".$this->row['group_code'].'"';?></h3> 
			</div>
			<div class="card-content collapse show mt-1">
				<form id='scoreForm' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<script type="dojo/method" event="onSubmit">   
					if(this.validate()){
						if(isDuplicate==1){
							var msgTitle = $( '.msgTitle' ).html();
							var msgDesc = $( '.msgDesc' ).html();
							infoMessageAlert(msgTitle,msgDesc);
							return false;
						}
						var identity = $('#identity').val();
						if(identity==''){
							var msgTitle = "បំពេញព័ត៌មានមិនគ្រប់គ្រាន់ / Incompleted Data To save";
							var msgDesc = "មិនមានព័ត៌មានសិស្សដែលត្រូវបញ្ចូល / There is no record to save";
							infoMessageAlert(msgTitle,msgDesc);
							return false;
						}
						var msgTitle = "អ្នកពិតជាចង់រក្សាទុកទីន្នន័យនេះឬ ? / Do you want to Save it ?";
						var msgDesc = "សូមធ្វើការត្រួតពិនិត្យព័ត៌មានមុនពេលរក្សាទុក ! / Please checking information before saving !";
						comfirmingSubmit('scoreForm',msgTitle,msgDesc);
						return false;
					}else {
						return false;
					}
					</script>
					<div class="card-box">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex ">ព័ត៌មានពិន្ទុ / Score Info</p>
													
												</div> 
											</div>
											<div class="form-group">
												<div class="card-blogform">		  
												    <div class="card-body"> 
														<div class="row">
															<label class="control-label bold col-md-5 col-sm-5 col-xs-12">
																ប្រភេទ / Criteria
															</label>
															<div class="col-md-7 col-sm-7 col-xs-12">
																<select onchange="getSubjectInfo();"  dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="criteriaId" name="criteriaId" queryExpr="*${0}*" autoComplete="false">								
																	<?php if(!empty($this->criteria)){foreach ($this->criteria as $rscriteria){?>
																		<option <?php echo ($rscriteria['criteriaId']==$resultRecord['criteriaId'])?"selected":"";?> value="<?php echo $rscriteria['criteriaId']?>" ><?php echo $rscriteria['criterialTitle'].'/'.$rscriteria['criterialTitleEng'];?></option>
																	<?php }}?>
																</select>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="form-group">
												<div class="card-blogform">		  
												    <div class="card-body"> 
														<div class="row">
															<label class="control-label bold col-md-5 col-sm-5 col-xs-12">
																ប្រភេទពិន្ទុ / Score Type
															</label>
															<div class="col-md-7 col-sm-7 col-xs-12">
																<select id="examType" name="examType" class="fullside" onchange="checkExamType(); getAllSubject();"  dojoType="dijit.form.FilteringSelect" >
																	<option <?php echo ($resultRecord['examType']==1)?"selected":"";?> value="1">ប្រចាំខែ/Monthly Exam</option>
																	<option <?php echo ($resultRecord['examType']==2)?"selected":"";?> value="2">ប្រចាំឆមាស/Semester Exam</option>
																</select>
															</div>
														</div>
													</div>
												</div>
											</div>
	
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12">ពិន្ទុសម្រាប់/Score For</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<div class="col-md-7 col-sm-7 col-xs-12">
														<input type="hidden" name="branch_id" id="branch_id" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->row['branch_id']?>" />
														<input type="hidden" name="group" id="group" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->row['id']?>"/>
														<input type="hidden" name="gradingId" id="gradingId" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->row['gradingId']?>"/>
													</div>
													<div class="col-md-6 col-sm-6 col-xs-12">
														<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="forSemester" name="forSemester" queryExpr="*${0}*" autoComplete="false">								
															<option <?php echo ($resultRecord['forSemester']==1)?"selected":"";?> value="1">ឆមាសទី១/Semester I</option>
															<option <?php echo ($resultRecord['forSemester']==2)?"selected":"";?> value="2">ឆមាសទី២/Semester II</option>
														</select>
													</div>
													<div class="col-md-6 col-sm-6 col-xs-12">
														<select readonly onChange="duplicationRecord();" dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="forMonth" name="forMonth" queryExpr="*${0}*" autoComplete="false">								
															<?php if(!empty($this->month)){foreach ($this->month as $month){?>
																<option <?php echo ($month['id']==$resultRecord['forMonth'])?"selected":"";?> value="<?php echo $month['id'];?>" <?php if($month['id']==$current_month){echo "selected='selected'";}?>><?php echo $month['name'];?></option>
															<?php }}?>
														</select>
													</div>
												</div>
											</div>
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12">មុខវិជ្ជា/Subject</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<input id="subjectId" />
													<input type="hidden" name="maxSubjectScore" id="maxSubjectScore" class="fullside" dojoType="dijit.form.TextBox" value="0"/>
												</div>
											 </div>
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12">តម្រៀបសិស្ស/Sort Student Lists</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<select id="sortStundent" name="sortStundent" class="fullside" onchange="filterStudent()"  dojoType="dijit.form.FilteringSelect" >
														<option value="0">ទូរទៅ / Default </option>
														<option value="1">លេខសម្គាល់សិស្ស/Student ID (ASC)</option>
														<option value="2">ឈ្មោះសិស្សខ្មែរ/Name In Khmer (ASC)</option>
														<option value="3"> ឈ្មោះសិស្សអង់គ្លេស / Name In English (ASC)</option>
													</select>
												</div>
											 </div>
											 <div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12">សម្គាល់ / Remark</label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<input class="fullside" placeholder="<?php echo $tr->translate("NOTE");?>" dojoType="dijit.form.Textarea"  id="note" name="note" value="<?php echo $resultRecord['note'];?>" type="text" style=" height: 120px !important;"  >
												</div>
											 </div>
										 </div>
									 </div>
								 </div>
							 </div>
						  </div>
						  <div class="col-md-6 col-sm-6 col-xs-12">
								<div id="duplicateMessage" class="hidden alert round alert-secondary alert-icon-left alert-dismissible mb-3 " role="alert">
									<span class="alert-icon">
										<i class="glyphicon glyphicon-time text-dark"></i>
									</span>
									<h4 class="msgTitle"><?php echo $msgTitle;?></h4>
									<small class="msgDesc">
										<?php echo $msgDesc;?>
									</small>
								</div>
								<div class="card-info bg-gradient-directional-notice">
									<div class="card-content">
										<div class="card-body">
											<div class="media d-flex">
												<div class="media-body text-dark text-left align-self-bottom ">
													<span class="d-block mb-1 font-medium-1"></span>
													<ul class="optListRow">
														<li class="opt-items titleEx"><h4 class="text-dark mb-10">ព័ត៌មានថ្នាក់សិក្សា/Class Student Info.</h4></li>
														<li class="opt-items two-column"><span class="lbl-tt">ឆ្នាំសិក្សា/Academic Year</span>: 	<span class="text-value"><?php echo $this->row['academic']?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt">កម្រិត/Degree</span>: 			<span class="text-value"><?php echo $this->row['degree']?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt">បន្ទប់/Room</span>: 				<span class="text-value"><?php echo $this->row['room_name']?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt">ថ្នាក់/Grade</span>: 				<span class="text-value"><?php echo $this->row['grade']?></span></li>
													</ul>
												</div>
												<div class="align-self-top">
												<i class="fa fa-info-circle icon-opacity2 text-dark font-large-4 float-end"></i>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div id="gradingInfo">
								</div>
						  </div>
					 </div>
					 <div class="card-box">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<div id="studentList">
							</div>
							<input type="hidden" name="identity" id="identity"  value="" >
							<input type="hidden" dojoType="dijit.form.TextBox" name="indexKey" id="indexKey"  value="" >
							<div class="form-group">
								<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;width:100%" >
								</table>
							</div>
						</div>
				   </div>
				   <div class="clearfix"></div>
					 <div class="card-box mt-20">
						<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" label="រក្សាទុក/Save" dojoType="dijit.form.Button" />
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" id="save_new" name="save_new" label="រក្សាទុក&បន្ថែមថ្មី/Save New" dojoType="dijit.form.Button"  />
						</div>
					 </div>
				</form>
			</div>
		</div>
	</div>
</div>
<style>
ul.optListRow.gradingInfo li {
    font-size: 11px;
    padding: 0;
}
th.criterialTitle {
    background: #c4d4eb;
}
tr.head-td th {
    vertical-align: top;
}
.lableEng {
    display: block;
    line-height: 12px;
}
small.small-label {
    font-size: 9px;
    line-height: 11px;
    margin-top: 2px;
    display: block;
}
span.titleSubCriterial {
    font-size: 9px;
    display: block;
    line-height: 12px;
    font-weight: 600;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
var isDuplicate=0;
$( document ).ready(function() {
   setPageTitle('<?php echo $pageTitle; ?>');
});
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require('dijit.form.NumberTextBox');
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,             
		id: "subjectId",
		name: "subjectId",           
		class: 'fullside', 
		placeHolder:"ជ្រើសមុខវិជ្ជា/Select Subject",          
		onChange: function() {
			getSubjectInfo();
		}
	}, "subjectId");
	
	getAllSubject();
});
urlGetSubjectStore = '<?php echo $this->url(array('module'=>'default','controller'=>'external','action'=>'getsubjectlist'));?>';
function getAllSubject(){
	dijit.byId('subjectId').reset();
	var subjectStore  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dijit.byId('subjectId').set('store',subjectStore); 
	
	group = dijit.byId('group').get('value');
	examType = dijit.byId('examType').get('value');
	
	dojo.xhrPost({
		url: urlGetSubjectStore,
		content:{
			'groupId':group,
			'examType':examType,
			},
		handleAs:"json",
		load: function(data) {
		    subjectStore  = getDataStorefromJSON('id','name', data);
		    dijit.byId('subjectId').set('store',subjectStore);
		    subjectId ='<?php echo $resultRecord['subjectId'];?>';
		    if(subjectId>0){
		    	dijit.byId('subjectId').attr('value',subjectId);
			}   
		},
		error: function(err) {
		}
	});
}


var subject = <?php print_r(Zend_Json::encode($this->criterial));?>;
var urlGetSubjectInfo= '<?php echo $this->url(array('module'=>'default','controller'=>'external','action'=>'getsubjectinfo')); ?>';
function getSubjectInfo(){
	group = dijit.byId('group').get('value');
	subjectId = dijit.byId('subjectId').get('value');
	if(subjectId=='' || subjectId==0){
		$('#identity').val('');
		dojo.query("#table_row").append("");
		return false;
	}
	examType = dijit.byId('examType').get('value');
	dojo.xhrPost({
	    url: urlGetSubjectInfo,
	    content : { 
			'groupId':group,
			'examType':examType,
			'subjectId':subjectId,
		},				    
	   handleAs:"json", 
	   load: function(data) {
		   dijit.byId('maxSubjectScore').attr('value',data.maxSubjectscore);
		   filterStudent();
		   duplicationRecord();
	   },		
	    error: function(err) {
	    }
	});
}

var inx=0;

var urlGetStudent= '<?php echo $this->url(array('module'=>'default','controller'=>'grading','action'=>'get-studentsingleengry')); ?>';
function filterStudent(){
	$('#identity').val('');
	dojo.query("#table_row").append("");
	loadingBlock();
	
	group = dijit.byId('group').get('value');
	sortStundent = dijit.byId('sortStundent').get('value');
	amtsubject = 0;
	examType = dijit.byId('examType').get('value');
	subjectId = dijit.byId('subjectId').get('value');
	gradingId = dijit.byId('gradingId').get('value');
	maxSubjectScore = dijit.byId('maxSubjectScore').get('value');

	forSemester = dijit.byId('forSemester').get('value');
	forMonth = dijit.byId('forMonth').get('value');

	criteriaId = dijit.byId('criteriaId').get('value');
	
	if(group==''){
		return false;
	}
	dojo.xhrPost({
	    url: urlGetStudent,
	    content : { 
			'groupId':group
			,'sortStundent':sortStundent
			,'criteriaId':criteriaId
			,'maxSubjectScore':maxSubjectScore
			,'examType':examType
			,'subjectId':subjectId
			,'gradingId':gradingId
			,'forSemester':forSemester
			,'forMonth':forMonth
			,'keyIndex':inx
			,'gradingRowId':'<?php echo $this->gradingRowId;?>'
			
		},				    
	   handleAs:"json", 
	   load: function(data) {
	       if(data!=""){
				inx=data.keyIndex;
				$("#identity").val(data.identity);
				dojo.html.set(dojo.byId("studentList"),data.contentHtml , {
					parseContent: true,
				});
				
				dojo.html.set(dojo.byId("gradingInfo"),data.htmlGradingInfo , {
					parseContent: true,
				});
	       }else{
		    	$('#identity').val('');
	       }
		   HideloadingBlock();	
	   },		
	    error: function(err) {
			HideloadingBlock();
	    }
	});
	
}

function deleteRecord(index){
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
function gender(sex){
	if(sex==1){
		sex='<?php echo $tr->translate('MALE');?>';
	}else sex='<?php echo $tr->translate('FEMALE');?>';
	return sex;
}
function checkExamType(){
	examType = dijit.byId("examType").get("value");
	dijit.byId('forMonth').set("readOnly",false);
	if(examType==2){
		dijit.byId('forMonth').set("readOnly",true);
	}
	duplicationRecord();
}

function checkAllCaterial(index){
	
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if($('#checkAll'+index).is(":checked")){
			dijit.byId('score_'+arrays[i]+'_'+index).attr('value',0);
			dijit.byId('score_'+arrays[i]+'_'+index).set("readOnly",true);
		}else{
			dijit.byId('score_'+arrays[i]+'_'+index).attr('value',0);
			dijit.byId('score_'+arrays[i]+'_'+index).set("readOnly",false);
		}
	}
}
var urlCalculateEverage= '<?php echo $this->url(array('module'=>'default','controller'=>'issuescore','action'=>'calculate-average')); ?>';
function calculateAverage(indexKey=null){
	dijit.byId('indexKey').attr('value',indexKey);
	dojo.xhrPost({
		url: urlCalculateEverage,
		form: dojo.byId("scoreForm"),
	   handleAs:"json", 
	   load: function(data) {
		   if(indexKey!=null){
			   dijit.byId('average'+indexKey).attr('value',data);
		   }else{
			   var identity = $('#identity').val();
				var arrays = identity.split(',');
				for(var i=0;i<arrays.length;i++) {
					keyRow = +arrays[i];
					dijit.byId('average'+keyRow).attr('value',data[keyRow]);
				}
		   }
	   },		
		error: function(err) {
		}
	});
}



var urlDuplicationRecord= '<?php echo $this->url(array('module'=>'default','controller'=>'issuescore','action'=>'checking-duplicate')); ?>';
function duplicationRecord(){
	criteriaId = dijit.byId('criteriaId').get('value');
	if(criteriaId!=9){
		return false;
	}
	group = dijit.byId('group').get('value');
	examType = dijit.byId('examType').get('value');
	subjectId = dijit.byId('subjectId').get('value');
	forSemester = dijit.byId('forSemester').get('value');
	forMonth = dijit.byId('forMonth').get('value');
	
	if(group==''){
		return false;
	}
	dojo.xhrPost({
	    url: urlDuplicationRecord,
	    content : { 
			'groupId':group
			,'subjectId':subjectId
			,'examType':examType
			,'forSemester':forSemester
			,'forMonth':forMonth
			
		},				    
	   handleAs:"json", 
	   load: function(data) {
	       if(data==1){
	    	   $('#identity').val('');
				dojo.query("#table_row").append("");
				loadingBlock();
				
				isDuplicate=1;
				var msgTitle = $( '.msgTitle' ).html();
				var msgDesc = $( '.msgDesc' ).html();
				infoMessageAlert(msgTitle,msgDesc);
				$( "#duplicateMessage" ).removeClass( "hidden" );
				
	       }else{
		    	isDuplicate=0;
				$( "#duplicateMessage" ).addClass( "hidden" );
	       }
		  
		   HideloadingBlock();	
	   },		
	    error: function(err) {
			HideloadingBlock();
	    }
	});
	
}
</script>
<?php 
	echo $this->render('externalFoot.phtml');
?>