<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
	$pageTitle = $tr->translate("EDIT_STUDENT_ASSESSMENT");
	echo $this->headTitle($pageTitle);
	$base_url = Application_Form_FrmMessage::getUrl("/");
	
	$pageTitle = '<i class="fa fa-edit"></i> '.$pageTitle;

	
	$current_month = date("m");
	$msgTitle = "ស្ទួនទិន្នន័យ / Duplicated Record";
	$msgDesc = "ការវាយតម្លៃសម្រាប់ខែនេះបានបញ្ចូលរួចរាល់ហើយ / This students's assessment for this month has been entered !"
?>	
<?php 
	echo $this->render('externalHead.phtml');
?>
<div class="row"> 
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="card mb-1 ">
			<div class="card-header pb-1"> 
				<h3 class="card-title mb-2 "><?php echo $this->row['branchName'].' "'.$tr->translate("GROUP")." ".$this->row['groupCode'].'"'?></h3> 
			</div>
			<div class="card-content collapse show mt-1">
				<form id='frmAssessment' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<script type="dojo/method" event="onSubmit">   
					if(this.validate()){
						if(isDuplicate==1){
							var msgTitle = $( '.msgTitle' ).html();
							var msgDesc = $( '.msgDesc' ).html();
							infoMessageAlert(msgTitle,msgDesc);
							return false;
						}
						var identity = $('#identity').val();
						if(identity==''){
							var msgTitle = "បំពេញព័ត៌មានមិនគ្រប់គ្រាន់ / Incompleted Data To save";
							var msgDesc = "មិនមានព័ត៌មានសិស្សដែលត្រូវបញ្ចូល / There is no record to save";
							infoMessageAlert(msgTitle,msgDesc);
							return false;
						}
						var msgTitle = "អ្នកពិតជាចង់រក្សាទុកទីន្នន័យនេះឬ ? / Do you want to Save it ?";
						var msgDesc = "សូមធ្វើការត្រួតពិនិត្យព័ត៌មានមុនពេលរក្សាទុក ! / Please checking information before saving !";
						comfirmingSubmit('frmAssessment',msgTitle,msgDesc);
						return false;
					}else {
						return false;
					}
					</script>
					<div class="card-box">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('ASSESSMENT_INFO')?> </p>
													
												</div> 
											</div>
											 
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ASSESSMENT_FOR");?></label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<div class="col-md-4 col-sm-4 col-xs-12">
														<select id="examType" name="examType" class="fullside" onchange="checkExamType(); getAllSubject();"  dojoType="dijit.form.FilteringSelect" >
															<option value="1" <?php if(1==$this->row['forType']){echo "selected='selected'";}?> ><?php echo $tr->translate("MONTHLY");?></option>
															<option value="2" <?php if(2==$this->row['forType']){echo "selected='selected'";}?> ><?php echo $tr->translate("SEMESTER");?></option>
														</select>
														<input type="hidden" name="branchId" id="branchId" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->row['branchId']?>" />
														<input type="hidden" name="groupId" id="groupId" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->row['groupId']?>"/>
														<input type="hidden" name="degree" id="degree" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->row['degreeId']?>"/>
														<input type="hidden" name="id" id="id" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->row['id']?>"/>
													</div>
													<div class="col-md-4 col-sm-4 col-xs-12">
														<select onchange="duplicationRecord();" dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="forSemester" name="forSemester" queryExpr="*${0}*" autoComplete="false">								
															<option value="1" <?php if(1==$this->row['forSemester']){echo "selected='selected'";}?> ><?php echo $tr->translate("SEMESTER1");?></option>
															<option value="2" <?php if(2==$this->row['forSemester']){echo "selected='selected'";}?> ><?php echo $tr->translate("SEMESTER2");?></option>
														</select>
													</div>
													<div class="col-md-4 col-sm-4 col-xs-12">
														<select onchange="duplicationRecord();" dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="forMonth" name="forMonth" queryExpr="*${0}*" autoComplete="false">								
															<?php if(!empty($this->month)){foreach ($this->month as $month){?>
																<option value="<?php echo $month['id']?>" <?php if($month['id']==$this->row['forMonth']){echo "selected='selected'";}?>><?php echo $month['month_kh']?></option>
															<?php }}?>
														</select>
													</div>
												</div>
											</div>
											<div class="form-group">
												<label class="control-label col-md-5 col-sm-5 col-xs-12">
													<?php echo $tr->translate("ISSUE_DATE");?></label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<input dojoType="dijit.form.DateTextBox"  class="fullside" id="issueDate" name="issueDate" value="<?php echo $this->row['issueDate']?>" constraints="{datePattern:'dd/MM/yyyy'}" >
												</div>
											</div>
											 
											<div class="form-group">
												<label class="control-label col-md-5 col-sm-5 col-xs-12">
													<?php echo $tr->translate("RETURN_DATE");?></label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<input dojoType="dijit.form.DateTextBox"  class="fullside" id="returnDate" name="returnDate" value="<?php echo $this->row['returnDate']?>" constraints="{datePattern:'dd/MM/yyyy'}" >
												</div>
											</div>
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SORT_STUDENT");?></label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<select id="sortStundent" name="sortStundent" class="fullside" onchange="filterStudent()"  dojoType="dijit.form.FilteringSelect" >
														<option value="0"><?php echo $tr->translate("DEFAULT");?></option>
														<option value="1"><?php echo $tr->translate("BY_STU_CODE_ASC");?></option>
														<option value="2"><?php echo $tr->translate("BY_STU_KHNAME_ASC");?></option>
														<option value="3"><?php echo $tr->translate("BY_STU_ENNAME_ASC");?></option>
													</select>
												</div>
											 </div>
											 <div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?></label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<input class="fullside" placeholder="<?php echo $tr->translate("NOTE");?>" dojoType="dijit.form.Textarea"  id="note" name="note" value="<?php echo $this->row['note']?>" type="text" style=" height: 120px !important;"  >
												</div>
											 </div>
											 
											<div class="form-group">
													<label class="control-label custom-switch float-end "> 
														<a href="javascript:void(0);" class="switchButton status"><?php echo $tr->translate("STATUS");?></a> 
														<input type="checkbox" id="status" name="status" class="custom-switch-input"  <?php if(!empty($this->row['status'])){ echo "checked";} ?> > 
														<span class="custom-switch-indicator custom-radius switch-status"></span> 
													</label>
												</div>
								
										 </div>
									 </div>
								 </div>
							 </div>
							
								
								  
						  </div>
						  <div class="col-md-6 col-sm-6 col-xs-12">
								<div id="duplicateMessage" class="hidden alert round alert-secondary alert-icon-left alert-dismissible mb-3 " role="alert">
									<span class="alert-icon">
										<i class="glyphicon glyphicon-time text-dark"></i>
									</span>
									<h4 class="msgTitle"><?php echo $msgTitle;?></h4>
									<small class="msgDesc">
										<?php echo $msgDesc;?>
									</small>
								</div>
								 <div class="card-info bg-gradient-directional-notice">
									<div class="card-content">
										<div class="card-body">
											<div class="media d-flex">
												<div class="media-body text-dark text-left align-self-bottom ">
													<span class="d-block mb-1 font-medium-1"></span>
													<h4 class="text-dark mb-10"><?php echo $tr->translate("GROUP_STUDENT_INFO");?></h4>
													<ul class="optListRow">
														<li class="opt-items two-column"><span class="lbl-tt"><?php echo $tr->translate("ACADEMIC_YEAR");?></span>: <span class="text-value"><?php echo $this->row['academicYear']?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt"><?php echo $tr->translate("DEGREE");?></span>: <span class="text-value"><?php echo $this->row['degreeTitle']?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt"><?php echo $tr->translate("ROOM");?></span>: <span class="text-value"><?php echo $this->row['roomName']?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt"><?php echo $tr->translate("GRADE");?></span>: <span class="text-value"><?php echo $this->row['gradeTitle']?></span></li>
														
													</ul>
												</div>
												<div class="align-self-top">
												<i class="fa fa-info-circle icon-opacity2 text-dark font-large-4 float-end"></i>
												</div>
											</div>
										</div>
									</div>
								</div>
											
								<div id="assessmentInfo">
								</div>
								
							 
								 
						  </div>
					 </div>
					 <div class="card-box">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<div id="studentList">
							</div>
							<input type="hidden" name="identity" id="identity"  value="" >
							<div class="form-group">
								
								<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;width:100%" >
								</table>
							</div>
						</div>
				   </div>
				   <div class="clearfix"></div>
					 <div class="card-box mt-20">
						<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE');?>" dojoType="dijit.form.Button" />
						</div>
					 </div>
				</form>
			</div>
		</div>
	</div>
</div>
<style>
ul.optListRow.gradingInfo li {
    font-size: 11px;
    padding: 0;
}
th.criterialTitle {
    background: #c4d4eb;
}
tr.head-td th {
    vertical-align: top;
}
.lableEng {
    display: block;
    line-height: 12px;
}
small.small-label {
    font-size: 9px;
    line-height: 11px;
    margin-top: 2px;
    display: block;
}
span.titleSubCriterial {
    font-size: 9px;
    display: block;
    line-height: 12px;
    font-weight: 600;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
var isDuplicate=0;
$( document ).ready(function() {
   setPageTitle('<?php echo $pageTitle; ?>');
});
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require('dijit.form.NumberTextBox');
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.ready(function(){
	duplicationRecord();
	
filterStudent();
});



var inx=0;

var urlGetStudent= '<?php echo $this->url(array('module'=>'default','controller'=>'assessment','action'=>'get-studentassessmentedit')); ?>';
function filterStudent(){
	$('#identity').val('');
	dojo.query("#table_row").append("");
	loadingBlock();
	
	currentID = dijit.byId('id').get('value');
	groupId = dijit.byId('groupId').get('value');
	sortStundent = dijit.byId('sortStundent').get('value');
	degree = dijit.byId('degree').get('value');
	
	if(groupId==''){
		return false;
	}
	dojo.xhrPost({
	    url: urlGetStudent,
	    content : { 
			'groupId':groupId
			,'sortStundent':sortStundent
			,'degree':degree
			,'keyIndex':inx
			,'currentID':currentID
			
		},				    
	   handleAs:"json", 
	   load: function(data) {
		 
	       if(data!=""){
				
				inx=data.keyIndex;
				$("#identity").val(data.identity);
				
				dojo.html.set(dojo.byId("studentList"),data.contentHtml , {
					parseContent: true,
				});
				
				dojo.html.set(dojo.byId("assessmentInfo"),data.commentContentInfo , {
					parseContent: true,
				});
				
				
				
	       }else{
		    	$('#identity').val('');
	       }
		   HideloadingBlock();	
	   },		
	    error: function(err) {
			HideloadingBlock();
	    }
	});
	
}


function checkExamType(){
	examType = dijit.byId("examType").get("value");
	dijit.byId('forMonth').set("readOnly",false);
	if(examType==2){
		dijit.byId('forMonth').set("readOnly",true);
	}
}

var urlDuplicationRecord= '<?php echo $this->url(array('module'=>'default','controller'=>'assessment','action'=>'checking-duplicate')); ?>';
function duplicationRecord(){
	
	currentId = dijit.byId('id').get('value');
	groupId = dijit.byId('groupId').get('value');
	examType = dijit.byId('examType').get('value');
	forSemester = dijit.byId('forSemester').get('value');
	forMonth = dijit.byId('forMonth').get('value');
	
	if(groupId==''){
		return false;
	}
	dojo.xhrPost({
	    url: urlDuplicationRecord,
	    content : { 
			'currentId':currentId
			,'groupId':groupId
			,'examType':examType
			,'forSemester':forSemester
			,'forMonth':forMonth
			
		},				    
	   handleAs:"json", 
	   load: function(data) {
		 
	       if(data==1){
				isDuplicate=1;
				var msgTitle = $( '.msgTitle' ).html();
				var msgDesc = $( '.msgDesc' ).html();
				infoMessageAlert(msgTitle,msgDesc);
				$( "#duplicateMessage" ).removeClass( "hidden" );
	       }else{
		    	isDuplicate=0;
				$( "#duplicateMessage" ).addClass( "hidden" );

	       }
		  
		   HideloadingBlock();	
	   },		
	    error: function(err) {
			HideloadingBlock();
	    }
	});
	
}


</script>
<?php 
	echo $this->render('externalFoot.phtml');
?>