<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('EDIT_NOTIFICATION'));
$row = $this->row;
?>
<script>
dojo.require("dijit/Editor");
</script>

<style>
body, #dijitEditorBody {
    height: 100%;
    width: 102%;
    overflow: auto;
    background: #fff !important;
    border: 1px solid #bcf;
}
.dijitEditor {
    border: solid 1px #ccd9ff;
}
</style>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<div class="card">
	<div class="card-content collapse show">
		<form  id='add_room' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
                dijit.byId("save_close").attr("disabled",true);
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
	        	<div class="col-sm-12 border-botom">
			    	<div class="col-sm-8 pd-0">
			    		<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_NOTIFICATION');?></h4>
		    		</div>
		    		<div class="col-sm-4 text-right">
		    		</div>
	    		</div>
	    	</div>
	    	<div class="card-box mb-10">
	        	<div class="col-md-8 col-sm-8 col-xs-12">
	        		<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE");?> :
	                   </label>
	                </div>
	                <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<input type="hidden" name="id" value="<?php echo $row['id'] ?>">
	                   		<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="title" name="title" value="<?php echo $row['title'] ?>" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("DESCRIPTION");?> :
	                   </label>
	                </div>
	                <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<textarea class="ckeditor"   style="min-height:400px; height:400px;" id="description" name="description"><?php echo $row['description'] ?></textarea>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
	            	<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("NORTIFICATION_OPT");?> :
	                   </label>
	                </div>
	            	<div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<select name="opt_notification" id="opt_notification" class="fullside" onChange="Checkchange();" dojoType="dijit.form.FilteringSelect" >
								<option value="1" <?php if ($row['opt_notification']==1){ echo 'selected="selected"';} ?>><?php echo $tr->translate("FOR_ALL");?></option>
								<option value="2" <?php if ($row['opt_notification']==2){ echo 'selected="selected"';} ?>><?php echo $tr->translate("GROUP");?></option>
								<option value="3" <?php if ($row['opt_notification']==3){ echo 'selected="selected"';} ?>><?php echo $tr->translate("STUDENT");?></option>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("GROUP");?> :
	                   </label>
	                </div>
	            	<div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<select name="group" id="group" class="fullside" placeholder="<?php echo $tr->translate("GROUP");?>"  dojoType="dijit.form.FilteringSelect" >
	                   			<option value=""></option>
	                   			<?php if (!empty($this->group)) foreach ($this->group as $rs){?>
								<option value="<?php echo $rs['id']?>" <?php if ($row['group']==$rs['id']){ echo 'selected="selected"';} ?>><?php echo $rs['name']?></option>
								<?php }?>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate("STUDENT");?> :
	                   </label>
	                </div>
	            	<div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<select  name="student" id="student" placeholder="<?php echo $tr->translate("STUDENT");?>" class="fullside"  dojoType="dijit.form.FilteringSelect" >
	                   			<option value=""></option>
	                   			<?php if (!empty($this->all_student)) foreach ($this->all_student as $rs){?>
								<option value="<?php echo $rs['stu_id']; ?>" <?php if ($row['student']==$rs['stu_id']){ echo 'selected="selected"';} ?>><?php echo $rs['stu_code']." ".$rs['stu_name']; ?></option>
								<?php }?>
							</select>
	                   </div>
	                </div>
	            </div>
	         </div>
	         <div class="card-box">
               	<div class="col-md-8 col-sm-8 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
					<input type="submit" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
	</div>
</div>
<script>
dojo.ready(function(){
	try{
		Checkchange();
	}catch(e){
		alert(e);
	}
});

function Checkchange(){
	  if (dijit.byId("opt_notification").get('value')==1){
		  dijit.byId('group').reset();
		  dijit.byId('student').reset();
		  dijit.byId('group').set('required',false); 
		  dijit.byId('group').set('readonly',true); 
		  dijit.byId('group').set('disabled', true);
		  dijit.byId('student').set('required',false); 
		  dijit.byId('student').set('readonly',true); 
		  dijit.byId('student').set('disabled', true);
	  }else if (dijit.byId("opt_notification").get('value')==2){
		  dijit.byId('student').reset();
		  dijit.byId('group').set('required',true); 
		  dijit.byId('group').set('readonly',false);
		  dijit.byId('group').set('disabled', false); 
		  
		  dijit.byId('student').set('required',false); 
		  dijit.byId('student').set('readonly',true); 
		  dijit.byId('student').set('disabled', true); 	 
	  }else if (dijit.byId("opt_notification").get('value')==3){
		  dijit.byId('group').reset();
		  dijit.byId('group').set('required',false); 
		  dijit.byId('group').set('readonly',true); 
		  dijit.byId('group').set('disabled', true);
		  
		  dijit.byId('student').set('required',true); 
		  dijit.byId('student').set('readonly',false); 
		  dijit.byId('student').set('disabled', false);
	  }
}
</script>