<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_ADD_PROVINCE')); 
?>
<?php  $province= $this->frm_province;?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
             <div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_PROVINE_NAME');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<div class="card-box">
    		<form id="add_province" action="<?php echo $this->url(array('module'=>'global','controller'=>'province','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<script type="dojo/method" event="onSubmit" enctype="multipart/form-data">			
					if(this.validate()) {
						loadingBlock();
						return true;
					}else {
						return false;
					}
				</script>
				<div class="col-md-6 col-sm-6 col-xs-12">
				<div class="form-group">
                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EN_PROVINCE");?> 
                   </label>
                   <div class="col-md-7 col-sm-7 col-xs-12">
                    	<?php echo $province->getElement("en_province");?>
                   </div>
                </div>
                <div class="form-group">
                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("KH_PROVINCE");?>
                   </label>
                   <div class="col-md-7 col-sm-7 col-xs-12">
                    	<?php echo $province->getElement("kh_province");?>
                   </div>
                </div>
                <div class="clearfix"></div>
				    <div class="card-box">
	               		<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
							<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
		    			</div>
		    		</div>
             </div>
		</form>
    	</div>
	</div>
</div>
