<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("PROVINCE_LIST"));
?>	
<?php $frm =  $this->frm_search;?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="col-sm-12 border-botom m-0">
	    	<div class="col-sm-8 pd-0">
    			<h4 class="m-b-0"><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('PROVINCE_LIST');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">	
						<?php echo $frm->getElement("title");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('status_search');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button  class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
