<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_callteral;
	echo $this->headTitle($tr->translate("ADD_STUDY_GROUP"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$frm = $this->frm;
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
    dojo.require("dojo.data.ObjectStore");
	dojo.require("dijit.form.FilteringSelect");
    dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require('dijit.form.NumberTextBox');
	dojo.require('dijit.form.TextBox');
	dojo.require('dijit.form.Textarea');
	dojo.require("dojo.html");
	
</script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
                branch_id=dijit.byId("branch_id").get("value");
                if(branch_id==-1 || branch_id==''){
					alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>");
					dijit.byId('branch_id').focus();
                    return false;
				}
 				year=dijit.byId("academic_year").get("value");
                if(year==-1 || year==''){
					alert("<?php echo $tr->translate("PLEASE_SELECT_YEAR");?>");
					dijit.byId('academic_year').focus();
                    return false;
				}
				cal=dijit.byId("calture").get("value");
                if(cal==-1 || cal==''){
					alert("<?php echo $tr->translate("PLEASE_SELECT_CALTURE");?>");
					dijit.byId('calture').focus();
                    return false;
				}
    			var rowId = $('#identity1').val();
				if(rowId!=''){ 
				var rowIDArray = rowId.split(',');
				for(var n = 0; n < rowIDArray.length; n++){
				var row_id = dijit.byId('group_subject_study_'+rowIDArray[n]).get('value');
				if(row_id==''){
						alert("Please select subject title!");
						return false;
						}
					}
				}
				loadingBlock();
				return true;
			}else {
				return false;
			}
		</script>
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-user-plus" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_STUDY_GROUP');?></h4>
    				</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<div class="col-md-4 col-sm-4 col-xs-12">
    		<div class="form-group">
                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span> :</label>
                <div class="col-md-7 col-sm-7 col-xs-12">
                	<?php echo $frm->getElement("branch_id");?>
                </div>
             </div>
    		<div class="form-group">
                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP_CODE");?> <span class="required">*</span> :</label>
                <div class="col-md-7 col-sm-7 col-xs-12">
                	<?php echo $frm->getElement("group_code");?>
                </div>
             </div>
             <div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ACADEMIC_YEAR");?> <span class="required">*</span> :</label>
                <div class="col-md-7 col-sm-7 col-xs-12">
					<input id="academic_year" name="academic_year" />
                </div>
             </div>
             <div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("CULTURE_LEVEL");?></label>
                <div class="col-md-7 col-sm-7 col-xs-12">
					<?php echo $frm->getElement("calture");?>
                </div>
             </div>
             <div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DEGREE");?></label>
                <div class="col-md-7 col-sm-7 col-xs-12">
                 <input id="degree" name="degree" />
                </div>
             </div>
             <div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GRADE");?></label>
                <div class="col-md-7 col-sm-7 col-xs-12">
                  <input id="grade" name="grade" />
                </div>
             </div>
              <div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SEMESTER");?></label>
                <div class="col-md-7 col-sm-7 col-xs-12">
                 	<input dojoType="dijit.form.ValidationTextBox" class="fullside" required="true" name="semester" value="" type="text">
                </div>
             </div>
    	</div>
    	<div class="col-md-4 col-sm-4 col-xs-12">
    		<div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SESSION");?></label>
                <div class="col-md-7 col-sm-7 col-xs-12">
					<?php echo $frm->getElement("session");?>
                </div>
             </div>
             <div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TIME");?></label>
                <div class="col-md-7 col-sm-7 col-xs-12">
					<?php echo $frm->getElement("time");?>
                </div>
             </div>
             <div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ROOM_NAME");?></label>
                <div class="col-md-7 col-sm-7 col-xs-12">
                	<input id="room" />
                </div>
             </div>
             <div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TEACHER_ROOM");?></label>
                <div class="col-md-7 col-sm-7 col-xs-12">
                	<input id="teacher_id" />
                </div>
             </div>
             <div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TEACHER_ASSISTANCE");?></label>
                <div class="col-md-4 col-sm-4 col-xs-12">
                	<input id="teacher_ass" />
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                   	<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="AllRefresh();"/>
                 </div>
             </div>
    	</div>
    	<div class="col-md-4 col-sm-4 col-xs-12">
    		<div class="form-group">
                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?></label>
                <div class="col-md-7 col-sm-7 col-xs-12" >
                	<?php echo $frm->getElement("notes");?>
                </div>
             </div>
    	</div>
    	<div class="card-box">
               	<div class="col-sm-12">
               		<table  style="border-collapse: collapse; border:1px solid #ccc;width:100%" >
               			<thead  id="head-title">
               				<tr class="head-td">
               					<th><?php echo $tr->translate("DEL");?></th>
								<th><?php echo $tr->translate("N_O");?></th>
								<th style="white-space:nowrap"><?php echo $tr->translate("SUBJECT_STUDY");?></th>
								<th style="white-space:nowrap"><?php echo $tr->translate("AMOUNT_SUBJECT");?></th>
								<th style="white-space:nowrap"><?php echo $tr->translate("AMOUNT_SUBJECT_FORSEMESTER");?></th>
								<th><?php echo $tr->translate("NOTE");?></th>
								<th><?php echo $tr->translate("TEACHER");?></th>
               				</tr>
               			</thead>
						<tbody id="table_row"></tbody>
					</table>
    			</div>
    			<div class="clearfix"></div>
    			<div class="col-sm-12">
    				<input type="button" label="<?php echo $tr->translate('ADD_SUBJECT_STUDY');?>" dojoType="dijit.form.Button" 
						iconClass="dijitIconEditProperty" onclick="addRow();" />
					<input type="hidden" name="identity1" id="identity1"  />
    			</div>
    	</div>
    	<div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
					<input type="button" onclick="submitDataClose();"  value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
	</div>
</div>
<script type="text/javascript">

var grade_store  = getDataStorefromJSON('id','name',);
var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var room_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?>  );
var subject_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->subjectlist));?> );
var teacher_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var teacher_storeass= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: teacher_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,
		id: "teacher_id",
		name: "teacher_id",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_TEACHER");?>",          
		onChange: function() {  
			teacher_id = dijit.byId('teacher_id').get('value');
			if(teacher_id==-1){
				$("#tow_value").val(-2)
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/lecturer/add?rightclick=true";?>','_blank');
			}
		}
	}, "teacher_id");

	new dijit.form.FilteringSelect({
		store: teacher_storeass,
		queryExpr: "*${0}*",
		autoComplete: false,                  
		required: false,
		id: "teacher_ass",
		name: "teacher_ass",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_TEACHER");?>",          
		onChange: function() {  
			teacher_id = dijit.byId('teacher_ass').get('value');
			if(teacher_id==-1){
				$("#tow_value").val(-2)
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/lecturer/add?rightclick=true";?>','_blank');
			}
		}
	}, "teacher_ass");
	
	new dijit.form.FilteringSelect({
		store: subject_store,
		queryExpr: "*${0}*",
		autoComplete: false,                  
		required: false,
		id: "subject_id",
		name: "subject_id",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_SUBJECT");?>",          
		onChange: function() {  
			subject_id = dijit.byId('subject_id').get('value');
			if(subject_id==-1){
				dijit.byId('save_subject').set('disabled',false);	
				dijit.byId("popupsubject").show();
			}else{
				addRowDegree();
			}
		}
	}, "subject_id");
	
	new dijit.form.FilteringSelect({
		store: dept_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,
		id: "degree",
		name: "degree",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_DEGREE");?>",          
		onChange: function() {  
			dept_id = dijit.byId('degree').get('value');
			if(dept_id==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/degree/add?rightclick=true";?>','_blank');
			}else{
				getSubjectByDegree();
				getallGrade();
			}
		}
	}, "degree");	
	
	new dijit.form.FilteringSelect({
		store: grade_store,
		queryExpr: "*${0}*",
		autoComplete: false,                                           
		id: "grade",
		name: "grade",           
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
			make_id = dijit.byId('grade').get('value');
			grade = dijit.byId('grade').get('value');
			if(grade==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/grade/add?rightclick=true";?>','_blank');
			}
		}
	}, "grade");

	new dijit.form.FilteringSelect({
		store: room_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                     
		id: "room",
		name: "room",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ROOM");?>",          
		onChange: function() {  
			room = dijit.byId('room').get('value');
			if(room==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/room/add?rightclick=true";?>','_blank');
			}
		}
	}, "room");

	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                     
		id: "academic_year",
		name: "academic_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('academic_year').get('value');
			getAllDegreeByAcademicSchoolOption();
			getSubject();
		}
	}, "academic_year");
	addRow();
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
		 getRefreshRoom();
    });
});
url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getacademic'));?>';
function getAllAcademicByBranch(){
	dijit.byId('academic_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('academic_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('academic_year').set('store',academic_store);   
		},
		error: function(err) {
		}
	});
}
url_getdegree= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getdegree'));?>';
function getAllDegreeByAcademicSchoolOption(){
	dijit.byId('degree').reset();
	academic_year = dijit.byId('academic_year').get('value');
	if(branch_id=='' || branch_id==-1){
		var dept_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('degree').set('store',dept_store);  
		dijit.byId('academic_year').focus();
		return false;
	}
	if(academic_year=='' || academic_year == -1){
		return false;
	}
	dojo.xhrPost({
		url: url_getdegree,
		content:{
			'academic_year':academic_year
			},
		handleAs:"json",
		load: function(data) {
			dept_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('degree').set('store',dept_store);   
		},
		error: function(err) {
		}
	});
}
function AllRefresh(){
	loadingBlock();
	getRefreshItems();
	getRefreshTeacher();
	getAllAcademicByBranch();
	dept_id = dijit.byId('degree').get('value');
	if(dept_id!='' || dept_id!=-1){getallGrade();}
	getRefreshRoom();
}
function getRefreshItems(){
	var url_getItems = '<?php echo $this->url(array("module"=>"global","controller"=>"degree","action"=>"refreshitems"));?>';										
	dojo.xhrPost({
		url: url_getItems,
		content:{
			'items_type':1
			},
		handleAs:"json",
		load: function(data) {
			dept_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('degree').set('store',dept_store);  
		   document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
var teacher_option = '';
var url_gettecher = '<?php echo $this->url(array("module"=>"foundation","controller"=>"group","action"=>"getteacher"));?>';										
function getRefreshTeacher(){
	dijit.byId('teacher_id').reset();
	dijit.byId('teacher_ass').reset();
	teacher_option = '';
	academic_year = dijit.byId('academic_year').get('value');
	branch_id = dijit.byId('branch_id').get('value');
	if(academic_year=='' || academic_year==-1){
		var teacher_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('teacher_ass').set('store',teacher_store);  
		dijit.byId('teacher_id').set('store',teacher_store);  
		dijit.byId('academic_year').focus();
		teacher_option="";
		return false;
	}
	if(academic_year=='' || academic_year == -1){
		return false;
	}
	dojo.xhrPost({
		url:url_gettecher,
		content:{
			'academic_year':academic_year,'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			teacher_storeass  = getDataStorefromJSON('id','name', data);
		    dijit.byId('teacher_ass').set('store',teacher_storeass);
		    teacher_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('teacher_id').set('store',teacher_store);  
		    for(var i = 0; i < data.length; i++) {
			    if(data[i].id==-1){
			    }else{
		    		teacher_option+='<option value='+data[i].id+'>'+data[i].name+'</option>';
			    }
		    }
		    dojo.query("#table_row").append("");
		    $("#identity1").val("");
		    addRow();
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err){
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}

var url_getRoom = '<?php echo $this->url(array("module"=>"foundation","controller"=>"group","action"=>"getroom"));?>';										
function getRefreshRoom(){
	dijit.byId('room').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id == -1){
		return false;
	}
	dojo.xhrPost({
		url: url_getRoom,
		handleAs:"json",
		content:{
				'branch_id':branch_id
				},
		load: function(data) {
			room_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('room').set('store',room_store);  
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
var subject = '';
var url_getsubject = '<?php echo $this->url(array("module"=>"foundation","controller"=>"group","action"=>"getsubject"));?>';										
function getSubject(){
	subject = '';
	academic_year = dijit.byId('academic_year').get('value');
	if(academic_year=='' || academic_year==-1){
		subject="";
		return false;
	}
	if(academic_year=='' || academic_year == -1){
		return false;
	}
	dojo.xhrPost({
		url:url_getsubject,
		content:{
			'academic_year':academic_year
			},
		handleAs:"json",
		load: function(data) {
		    for(var i = 0; i < data.length; i++) {
			    if(data[i].id==-1){
			    }else{
			    	subject+='<option value='+data[i].id+'>'+data[i].name+'</option>';
			    }
		    }
		    getRefreshTeacher();
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
var col = 0;
var no = 0;
var title = 1;
tmp = '';
temp='';
function addRow() {
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th style="white-space:nowrap"><?php echo $tr->translate("SUBJECT_STUDY");?></th>';
		temp+='<th style="white-space:nowrap"><?php echo $tr->translate("AMOUNT_SUBJECT");?></th>';
		temp+='<th style="white-space:nowrap"><?php echo $tr->translate("AMOUNT_SUBJECT_FORSEMESTER");?></th>';
		temp+='<th><?php echo $tr->translate("NOTE");?></th>';
		temp+='<th><?php echo $tr->translate("TEACHER");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="4%" align="center">'+no+'</td>';
		template+='<td width="40%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="checkSubject('+col+');" class="fullside" id="group_subject_study_'+col+'" name="group_subject_study_'+col+'">'+subject+'</select></td>';
		template+='<td width="50px"><input required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="amount_subject'+col+'" id="amount_subject'+col+'" value="1" type="text"></td>';
		template+='<td width="60px"><input required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="amount_subject_semester'+col+'" id="amount_subject_semester'+col+'" value="1" type="text"></td>';	
		template+='<td width="23%"><input dojoType="dijit.form.TextBox" class="fullside" name="group_note_'+col+'" id="group_note_'+col+'" value="" type="text"></td>';		
		template+='<td width="24%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="popupTeacher('+col+');" class="fullside" id="teacher_'+col+'" name="teacher_'+col+'" >';
		template+=teacher_option;  
		template+='</select></td>';
		
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity1").val()!="") {
		var identity = $("#identity1").val();
		$("#identity1").val(identity+','+col);
	} else {$("#identity1").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
}
function deleteRecord(index) {
	var identity = $('#identity1').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity1').val(strings);
	dojo.query("#row"+index).remove();
}
function checkSubject(index){
	var identity = $('#identity1').val();
	var arrays = identity.split(',');
	current_subject = dijit.byId('group_subject_study_'+index).get('value');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index){
		}else{
			old_subject = dijit.byId('group_subject_study_'+arrays[i]).get('value');
			if(current_subject == old_subject){
				alert("Can not add the same subject !!! ");
				deleteRecord(index);
			}
		}
	}
}
var url_dept_subject = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getsubjectbydegree')); ?>';
function getSubjectByDegree(){
		dept_id = dijit.byId('degree').get('value');
		dojo.xhrPost({
			url:url_dept_subject,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				var identity = $('#identity1').val();
				if(identity !=''){
					var arrays = identity.split(',');
					for(var i=0;i<arrays.length;i++) {
						deleteRecord(arrays[i]);
					}
					$("#identity1").val("");
				}
				tem="";
			    if(data!=""){
					template='';
					for(i=0;i<data.length;i++){
						col++;no++;
						template='';
						if(title!=1){
							temp+='<th><?php echo $tr->translate("DEL");?></th>';
							temp+='<th><?php echo $tr->translate("N_O");?></th>';
							temp+='<th><?php echo $tr->translate("SUBJECT_STUDY");?></th>';
							temp+='<th><?php echo $tr->translate("NOTE");?></th>';
							temp+='<th><?php echo $tr->translate("STATUS");?></th>';
							dojo.query("#head-title").append(temp);
							title=1;
						}
							template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
							template+='<td width="4%" align="center">'+no+'</td>';
							template+='<td width="40%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="checkSubject('+col+')" class="fullside" id="group_subject_study_'+col+'" name="group_subject_study_'+col+'">'+subject+'</select></td>';
							template+='<td width="50px"><input required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="amount_subject'+col+'" id="amount_subject'+col+'" value="1" type="text"></td>';
							template+='<td width="60px"><input required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="amount_subject_semester'+col+'" id="amount_subject_semester'+col+'" value="1" type="text"></td>';	
							template+='<td width="35%"><input dojoType="dijit.form.TextBox" class="fullside" name="group_note_'+col+'" id="group_note_'+col+'" value="" type="text"></td>';		
							template+='<td width="24%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="popupTeacher('+col+');" class="fullside" id="teacher_'+col+'" name="teacher_'+col+'" >';
							template+=teacher_option;  
							template+='</select></td>';
						tmp='<tr id="row'+col+'">';
						tmp+="</tr>";
						dojo.query("#table_row").append(tmp);
						if($("#identity1").val()!="") {
							var identity = $("#identity1").val();
							$("#identity1").val(identity+','+col);
						} else {$("#identity1").val(col);}
						dojo.html.set(dojo.byId("row"+col),template , {
							 parseContent: true,
						});
						dijit.byId('group_subject_study_'+col).attr('value',data[i].subject_id);
						dijit.byId('group_note_'+col).attr('value',data[i].note);
					}
			    }
			},
			error: function(err) {
			}
		});
}
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id=='' || dept_id==-1){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);   

			},
			error: function(err) {
			}
		});
}
function submitDataClose(){
    branch_id=dijit.byId("branch_id").get("value");
    if(branch_id==-1 || branch_id==''){
		alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>");
		dijit.byId('branch_id').focus();
        return false;
	}
	year=dijit.byId("academic_year").get("value");
    if(year==-1 || year==''){
		alert("<?php echo $tr->translate("PLEASE_SELECT_YEAR");?>");
		dijit.byId('academic_year').focus();
        return false;
	}
    cal=dijit.byId("calture").get("value");
    if(cal==-1 || cal==''){
		alert("<?php echo $tr->translate("PLEASE_SELECT_CALTURE");?>");
		dijit.byId('calture').focus();
        return false;
	}
    var rowId = $('#identity1').val();
	if(rowId!=''){ 
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++){
		var row_id = dijit.byId('group_subject_study_'+rowIDArray[n]).get('value');
		if(row_id==''){
				alert("Please select subject title!");
				return false;
			}
		}
	}
	if(dijit.byId('frm_add_tran').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/foundation/group";
			},
			error: function(e) {
			}
		});
	}
}
</script>