<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('GROUP'));
	$formList = new Application_Form_Frmtable();	
    $frm =  $this->form_search;
    $urlCopy = $this->baseUrl()."/foundation/group/copy/id/";
    $urlEdit = $this->baseUrl()."/foundation/group/edit/id/";
    
    $urlStudentGroup = $this->baseUrl()."/allreport/allstudent/rpt-student-group/id/";
    $urlAttList = $this->baseUrl()."/allreport/allstudent/rpt-att-list/id/";
    $urlTotalAtt = $this->baseUrl()."/allreport/score/rpt-totalattendance/id/";
    $urlStudentList = $this->baseUrl()."/allreport/allstudent/rpt-student-list/id/";
    $urlAssesment = $this->baseUrl()."/allreport/score/rpt-assessmentterm/id/";
    $urlscoresemester = $this->baseUrl()."/allreport/score/rpt-resultbysemester/id/";
    $urloutstanding1 = $this->baseUrl()."/allreport/score/semester-outstanding-student/id/";
    $urlscoreyear = $this->baseUrl()."/allreport/score/rpt-resultbyyear/id/";
    $urloutstandingyear = $this->baseUrl()."/allreport/score/yearly-outstanding-student/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('GROUP_INFO');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
                   <div class="col-md-2 col-sm-3 col-xs-12">
                   		<?php echo $frm->getElement("adv_search");?>
                   </div>
                   <div class="col-md-2 col-sm-3 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                  		<?php echo $frm->getElement("academic_year");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("degree");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input id="grade" />
                   </div>
				   <div class="col-md-2 col-sm-3 col-xs-12">
                		<?php echo $frm->getElement("session");?>
                	</div>
                </div>
                <div class="form-group">
                	<div class="col-md-2 col-sm-3 col-xs-12">
                		<?php echo $frm->getElement("teacher");?>
                	</div>
                	<div class="col-md-2 col-sm-3 col-xs-12">
                		<?php echo $frm->getElement("is_pass");?>
                	</div>
                	<div class="col-md-2 col-sm-2 col-xs-12">
                		<?php echo $frm->getElement("status");?>
                	</div>
                	<div class="col-md-2 col-sm-2 col-xs-12">
                		<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />	
	                   	<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                	</div>
                </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.ready(function(){

	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false, 
		required: false,
		id: "grade",
		name: "grade",           
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
		}
	}, "grade");
	var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
  });
	getallGrade();
});

var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id=='' || dept_id==-1){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store); 
			    dijit.byId('grade').attr('value','<?php echo $this->adv_search['grade']?>');    
			},
			error: function(err) {
			}
		});
}

	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 if(id!=''){
			window.location.href = url+'/id/'+id;
		 }else{
			alert('Please select record you want to copy');
			return false;
		 }
	}
	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}
	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}else if(key=="copy"){
					url='<?php echo $urlCopy;?>';
				}else if(key=="rpt-student-group"){
					url='<?php echo $urlStudentGroup;?>';
				}else if(key=="rpt-att-list"){
					url='<?php echo $urlAttList;?>';
				}else if(key=="rpt-totalattendance"){
					url='<?php echo $urlTotalAtt;?>';
				}else if(key=="rpt-student-list"){
					url='<?php echo $urlStudentList;?>';
				}else if(key=="rpt-resultbysemester"){
					url='<?php echo $urlscoresemester;?>';
					window.open(url+''+row+'/type/1','_blank');
					return true;
				}else if(key=="outstandingsem1"){
					url='<?php echo $urloutstanding1;?>';
					window.open(url+''+row+'/type/1','_blank');
					return true;
				}
				else if(key=="rpt-semester2"){
					url='<?php echo $urlscoresemester;?>';
					window.open(url+''+row+'/type/2','_blank');
					return true;
				}else if(key=="outstandingsem2"){
					url='<?php echo $urloutstanding1;?>';
					window.open(url+''+row+'/type/2','_blank');
					return true;
				}
				else if(key=="scoreyear"){
					url='<?php echo $urlscoreyear;?>';
					window.open(url+''+row+'/type/3','_blank');
					return true;
				}
				else if(key=="outstandingyear"){
					url='<?php echo $urloutstandingyear;?>';
					window.open(url+''+row+'/type/3','_blank');
					return true;
				}
				gotoAction();
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
				"copy": {name: "<?php echo $tr->translate("COPY");?>", icon: "copy"},
				"rpt-student-group": {name: "<?php echo $tr->translate("STUDENT_LIST_REPORT");?>", icon: "fa-file-text-o",},
				"rpt-student-list": {name: "<?php echo $tr->translate("STUDENT_LIST");?>", icon: "fa-file-text-o"},
				"rpt-att-list": {name: "<?php echo $tr->translate("STUDENT_ATTENDANT_LIST");?>", icon: "fa-file-text-o"},
				"rpt-totalattendance": {name: "<?php echo $tr->translate("TOTAL_ATTENDANT_LIST");?>", icon: "fa-file-text-o"},
				"rpt-resultbysemester": {name: "<?php echo $tr->translate("RESULT_SEMESTER1");?>", icon: "fa-file-text-o"},
				"rpt-semester2": {name: "<?php echo $tr->translate("RESULT_SEMESTER2");?>", icon: "fa-file-text-o"},
				"scoreyear": {name: "<?php echo $tr->translate("YEARLY_EXAM");?>", icon: "fa-file-text-o"},
				"outstandingsem1": {name: "<?php echo $tr->translate("HONOR_SEMESTER1");?>", icon: "fa-file-text-o"},
				"outstandingsem2": {name: "<?php echo $tr->translate("HONOR_SEMESTER2");?>", icon: "fa-file-text-o"},
				"outstandingyear": {name: "<?php echo $tr->translate("HONOR_YEARLY");?>", icon: "fa-file-text-o"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.open(url+row,'_blank');
	}
</script> 