<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_STUDENT_GROUP')); 
	$frm =  $this->form_search;
?>	
<head>
 	<link href="<?php echo $this->baseUrl()."/jsmultiselect"?>/multi-select.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<style>
.ms-container .ms-selectable {
    margin: 0 10px;
}
.search-blog {
    background: #bcd5f0;
    border-radius: 5px;
}

.ms-container .ms-selectable, .ms-container .ms-selection{
	width:48%;
}
.ms-container .ms-selectable li.ms-elem-selectable, .ms-container .ms-selection li.ms-elem-selection {
    font-size: 13px;
    white-space: nowrap;
    color: #000;
    margin-top:10px;
}
a.btnstyle{background:#337ab7;padding:6px;border-radius:5px;color:#fff;border:1px solid #265074;}
a.btnstyle:hover{color:#eee;}
.introduction label{font-size: 12px !important;}
.bgintro{background:#b1badf !important;}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		   			<h4 class="m-b-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_STUDENT_GROUP');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	
	    	<div class="card-box">
	        	<div class="col-md-4 col-sm-4 col-xs-12">
	        		<form id="studentgroup" dojoType="dijit.form.Form" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'addstudenttogroup','action'=>'add')); ?>" method="post" enctype="application/x-www-form-urlencoded">
						<script type="dojo/method" event="onSubmit">			
							if(this.validate()) {
								branch_id = dijit.byId('branch_id').get('value');
								if(branch_id==''){
									alert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>');
									dijit.byId('branch_id').focus();
									return false;
								}
								grade = dijit.byId('grade').get('value');
								if(grade==''){
									alert('<?php echo $tr->translate("SELECT_GRADE");?>');
									dijit.byId('grade').focus();
									return false;
								}
								return true;
	   						}else {
								return false;
	   						}
						</script>
						<div class="card-blogform">
							<div class="card-body">
			               	  <div class="form-group">
								<div class="d-flex"> 
									<div class="settings-main-icon ">
										<i class="fa fa-search" aria-hidden="true"></i>
									</div> 
									<div class="col-md-10 col-sm-10 col-xs-12"> 
										<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("SEARCH_GROUP");?></p>
									</div> 
								</div>
							  </div>
				                <div class="form-group">
					                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
					                <div class="col-md-7 col-sm-7 col-xs-12">
					                	<?php echo $frm->getElement("branch_id");?>
					                </div>
					             </div>
								<div class="form-group">
									<div class="form-group">
					                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ACADEMIC_YEAR");?>  :
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $frm->getElement("academic_year");?>
					                   </div>
					                 </div>
				                </div>
								<div class="form-group">
									 <div class="form-group">
					                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TYPE");?>  :
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<input id="study_year" />
					                   </div>
					                </div>
								</div>
								<div class="form-group">
				                	<div class="form-group">
					                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DEGREE");?>  :
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $frm->getElement("degree");?>
					                   </div>
					                </div>
				                </div>
								<div class="form-group">
									 <div class="form-group">
					                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GRADE");?>  :
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		<input id="grade" />
					                   </div>
					                </div>
								</div>
								<div class="form-group" style="display:none;">
									<div class="form-group">
					                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SESSION");?>  :
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
					                   		 <?php echo $frm->getElement("session");?>
					                   </div>
					                </div>
								</div>
								<div class="form-group">
									<div class="form-group">
					                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SESSION");?>  :
					                   </label>
					                   <div class="col-md-7 col-sm-7 col-xs-12">
										<input id="partTime" />
					                   </div>
					                </div>
								</div>
								<div class="form-group">
					                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SORT_STUDENT");?></label>
					                <div class="col-md-7 col-sm-7 col-xs-12">
					                	<select id="sortStundent" name="sortStundent" class="fullside"  dojoType="dijit.form.FilteringSelect" >
										   	<option value="0"><?php echo $tr->translate("DEFAULT");?></option>
										   	<option value="1"><?php echo $tr->translate("BY_STU_CODE_ASC");?></option>
										   	<option value="2"><?php echo $tr->translate("BY_STU_KHNAME_ASC");?></option>
										   	<option value="3"><?php echo $tr->translate("BY_STU_ENNAME_ASC");?></option>
										</select>
					                </div>
					             </div>
				                <div class="form-group">
			                   		 <label class="control-label  col-md-5 col-sm-5 col-xs-12" >
					                 </label>
					                 <div class="col-md-7 col-sm-7 col-xs-12">
			                   		 		<input type="submit" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("SEARCH")?>" id="search"
											class="button-class button-primary" iconClass="glyphicon glyphicon-search"/>
									 </div>
				                 </div>
				                 <div class="form-group">
				                 	<div class="card-blogform bgintro">
											<div class="card-body introduction">
							               	  <div class="form-group">
												<div class="d-flex"> 
													<div class="settings-main-icon ">
														<i class="fa fa-info-circle" aria-hidden="true"></i>
													</div> 
													<div class="col-md-10 col-sm-10 col-xs-12"> 
														<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("INTRODUCTION");?></p>
													</div> 
												</div>
											</div>
											<div class="form-group">
								                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" >1 ស្វែងរកសិស្សតាម ឆ្នាំសិក្សា,កម្រិត/វគ្គ ,ថ្នាក់/កម្រិត ណាមួយ រួចចុចស្វែងរក</label>
							                </div>
							                <div class="form-group">
								                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" >2 ចុចលើប៊ូតុង ជ្រើសរើសទាំងអស់ ឬ យកសិស្សណាដែលចង់ដាក់ចូលក្រុម</label>
							                </div>
							                <div class="form-group">
								                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" >3 ជ្រើសរើសថ្នាក់ ក្នុង ព័ត៌មានថ្នាក់ </label>
							                </div>
							                <div class="form-group">
								                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" >4 រក្សាទុក </label>
							                </div>
										   </div>
										</div>
				                 </div>
				              </div>
		                </div>
					</form>
	            </div>
	            <div class="col-md-8 col-sm-8 col-xs-12">
		            		<form id='submitgroup' dojoType="dijit.form.Form" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'addstudenttogroup','action'=>'submit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
								<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
						branch_id = dijit.byId('branch_id').get('value');
						if(branch_id=='' || branch_id==-1){
							alert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>');
							dijit.byId('branch_id').focus();
							return false;
						}
							groupId = dijit.byId('group').get('value');
								if(groupId<=0){
									alert('<?php echo $tr->translate("SELECT_GROUP");?>');
									dijit.byId('group').focus();
									return false;
								}
								identity = dijit.byId('identity').get('value');
								if(identity<=0){
									alert('<?php echo $tr->translate("SELECT_STUDENT");?>');
									return false;
								}

						loadingBlock();	
						return true;
	   				}else {
						return false;
	   				}
				</script>
			            	<div class="card-blogform">
								<div class="card-body">
				               	  <div class="form-group">
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa fa-users" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT_INFO");?></p>
										</div> 
									</div>
								  </div>
					            	<div class="form-group">
						         		<div class="col-md-12 col-sm-12 col-xs-12 text-center">
											<a id="select-all" href="#" class='btnstyle'><span style="font-size: 15px;"><?php echo $tr->translate("SELECT_ALL");?></span></a> <span style="font-size: 16px;"> | </span>
											<a id="deselect-all" href="#" class='btnstyle'><span style="font-size: 15px;"><?php echo $tr->translate("DESELECT_ALL");?></span></a> <span style="font-size: 16px;"> </span>
											<div style="height: 10px;"></div>
										</div>
										 <div class="clearfix" style="margin-top:10px;"></div>
										<div class="col-md-12 col-sm-12 col-xs-12">
											<select multiple id="public-methods" name="public-methods[]" >
												<?php $no=0;
												$strStuId='';
												if(!empty($this->rs)) foreach($this->rs as $key=> $row){ $no++;
												$strStuId = ($key==0)?$row['gd_id']:$strStuId.=','.$row['gd_id'];
												?>
													<option value="<?php echo $row['gd_id'];?>">
														<?php echo $no, ". " , $row['stu_code'],"-",$row['last_name'].' '.$row['stu_enname'],"-",$row['stu_khname']." (".$row['grade_title'].")"; ?>
													</option>
												<?php }?>
											</select>
										</div>
										 <div class="clearfix"></div>
						         	</div>
					               </div>
					             </div>
					             <div class="card-box">
						            <div class="col-md-6 col-sm-6 col-xs-12">
						            	<div class="card-blogform">
											<div class="card-body">
												<div class="form-group">
								                   <div class="d-flex"> 
														<div class="settings-main-icon ">
															<i class="fa fa-server " aria-hidden="true"></i>
														</div> 
														<div class="col-md-10 col-sm-10 col-xs-12"> 
															<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("DETAIL");?></p>
														</div> 
													</div>
								                </div>
								            	<div class="form-group">
								                   <div class="col-md-12 col-sm-12 col-xs-12">
								                   		<label id="lbldetail" name=lbldetail style="background:#fff; font-size: 12px; min-height:37px;display:block;"></label>
														<input type="hidden" name="allStudent" id="allStudent" dojoType="dijit.form.TextBox" value="<?php echo $strStuId;?>"/> 
								                   		<input type="hidden" id="identity"  name="identity" id="allStudent" dojoType="dijit.form.TextBox" /> 
								                   </div>
								                </div>
						               		 </div>
						                </div>
						            	
						            	
						            </div>
						            <div class="col-md-6 col-sm-6 col-xs-12">
										<div class="card-blogform">
											<div class="card-body">
							               	  <div class="form-group">
												<div class="d-flex"> 
													<div class="settings-main-icon ">
														<i class="fa fa-sitemap" aria-hidden="true"></i>
													</div> 
													<div class="col-md-5 col-sm-5 col-xs-12"> 
														<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("GROUP_INFO");?></p>
													</div> 
													<div class="col-md-5 col-sm-5 col-xs-12">
								                   		<input class="button-class button-primary" iconClass="glyphicon glyphicon-refresh" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getAllGroup();"/>
								                   </div>
												</div>
											  </div>
								                
								                <div class="form-group">
								                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GROUP_CODE");?> <span class="required">*</span> :
								                   </label>
								                   <div class="col-md-7 col-sm-7 col-xs-12">
								                   		<input id="group" />
								                   		 <input type="hidden" name="branch" id="branch" dojoType="dijit.form.TextBox" /> 
								                   </div>
								                </div>
								              </div>
								          </div>
						            </div>
						        </div>
						         <div class="card-box">
							         <div class="form-group">
					                   <div class="col-md-12 col-sm-12 col-xs-12 text-center">
					                   		<input type="submit" id="save_close" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("SAVE_CLOSE");?>"
											   class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-saved"/>
											<input type="submit" id="save_new" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("SAVE_NEW");?>" 
												class="button-class button-primary" iconClass="	glyphicon glyphicon-floppy-open"/>
					                   </div>
					                </div>
						         </div>
			         	 </form>
		            </div>
	            <div class="clearfix"></div>
	        </div>
	        <div class="card-box" style="margin-top: 10px;">
		    <div class="clearfix"></div>
       	 </div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/jquery.multi-select.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/rainbow.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/application.js" type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.NodeList-manipulate");
dojo.require('dijit.form.Textarea');
dojo.require("dojo.data.ItemFileWriteStore"); 

var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){

	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false, 
		required: false,
		id: "grade",
		name: "grade",           
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
		}
	}, "grade");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false, 
		required: false,
		id: "partTime",
		name: "partTime",           
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_PARTTIME_SHIFT");?>",          
		onChange: function() {  
		}
	}, "partTime");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false, 
		required: false,
		id: "study_year",
		name: "study_year",           
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_TYPE");?>",          
		onChange: function() {  
		}
	}, "study_year");
	
	var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllGroup();
  	});

	 var degree = dijit.byId('degree');
	 degree.on('change', function(evt) {
		 getAllGroup();
		 getAllPartTimeList();
  	});

	 var grade = dijit.byId('grade');
	 grade.on('change', function(evt) {
		 getAllGroup();
  	});
	
	 var academicYearControl = dijit.byId('academic_year');
	 academicYearControl.on('change', function(evt) {
		 getAllAcademicBy();
  	});
	
	new dijit.form.FilteringSelect({
	    store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,    
	    id: "group",
	    name: "group",           
	    class: 'fullside',
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",    
	    onChange: function() { 
	    	group_id = dijit.byId('group').get('value');
		    if(group_id==-1){
		    	dojo.byId('lbldetail').innerHTML='';
		    	window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/foundation/group/add";?>','_blank');
			}else{
				getGroupDetail();
			}        
	    } 
	}, "group");
	getallGrade();
	getAllGroup();
	getAllAcademicBy();
	getAllPartTimeList();
	<?php if(!empty($this->search['study_year'])){ ?>
		setTimeout(function() {
			dijit.byId('study_year').attr('value','<?php echo $this->search['study_year']?>');
		}, 1000);
	<?php } ?>	
	
});


$('#deselect-all').click(function(){
  $('#public-methods').multiSelect('deselect_all');
  dijit.byId('identity').attr('value','');
});

$('#public-methods').multiSelect({
	afterSelect: function(values){
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+values);
		} else {$("#identity").val(values);}
	},
	afterDeselect: function(values){
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == values) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
	}
});

var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id=='' || dept_id==-1){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store); 
			    dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');    
			},
			error: function(err) {
			}
		});
}
</script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
var url_to_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentchangegroup','action'=>'get-to-group')); ?>';
function getGroupDetail(){
		group = dijit.byId('group').get('value');
		if(group==-1 || group==''){
			return false;
		}
	dojo.xhrPost({
		url:url_to_group,
		content:{
			'to_group':group
			},
		handleAs:"json",
		load: function(data) {
			dojo.byId('lbldetail').innerHTML='<span style="color:red;">Academic :  </span>'+data.year+'<span style="color:red;"> , Degree :  </span>'+data.degree+'<br /><span style="color:red;">  Grade :  </span>'+data.grade+'<span style="color:red;"> , Session :  </span>'+data.session+'<span style="color:red;"> , Room :  </span>'+data.room;   
		},
		error: function(err) {
		}
	});
}

url_getallgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
function getAllGroup(){
	dijit.byId('group').reset();
	grade = dijit.byId('grade').get('value');
	if(grade=='' || grade==-1){
		return false;
	}
	
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	degree = dijit.byId('degree').get('value');
	if(degree=='' || degree==-1){
		degree ="";
	}
	
	
	academic_year = dijit.byId('academic_year').get('value');
	if(academic_year=='' || academic_year==-1){
		academic_year ="";
	}
	dojo.xhrPost({
		url: url_getallgroup,
		content:{
			'branch_id':branch_id,
			'academic_year':academic_year,
			'degree':degree,
			'grade':grade,
			'noaddnew':0
		},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		},
		error: function(err) {
		}
	});
}

urlGetPartTimeShift = '<?php echo $this->url(array('module'=>'global','controller'=>'parttimelist','action'=>'get-parttime'));?>';
function getAllPartTimeList(){
	dijit.byId('partTime').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var partTimeStore  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',partTimeStore);  
		dijit.byId('partTime').focus();
		return false;
	}
	degree = dijit.byId('degree').get('value');
	if(degree=='' || degree==-1){
		degree ="";
	}
	dojo.xhrPost({
		url: urlGetPartTimeShift,
		content:{
			'branchId':branch_id,
			'degree':degree,
		},
		handleAs:"json",
		load: function(data) {
		    partTimeStore  = getDataStorefromJSON('id','name', data);
		    dijit.byId('partTime').set('store',partTimeStore);  
			<?php if(!empty($this->search['partTime'])){ ?>
				dijit.byId('partTime').attr('value','<?php echo $this->search['partTime']?>');
			<?php } ?>	 
		},
		error: function(err) {
		}
	});
}

function getAllAcademicBy(){
	
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		dijit.byId('branch_id').focus();
		return false;
	}
	academicYear = dijit.byId('academic_year').get('value');
	let url_getacademic = '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'getfeeid'));?>';
	contentData = {
		'branch_id':branch_id,
		'academicYear':academicYear,
		'shortTitle':1,
		'isFinished':0
	}
	getAllAcademicByBranch(url_getacademic,contentData);
	
	
}
</script>
