<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_STUDENT_GROUP')); 
?>	
<head>
 <link href="<?php echo $this->baseUrl()."/jsmultiselect"?>/multi-select.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require('dijit.form.Textarea');
    dojo.require("dojo.parser");
    dojo.require("dojo.data.ItemFileWriteStore"); 
</script>
<style>
select{ width:100%;}
fieldset{  background:#DFF7FD;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}

table .set-style tr td a {
    font-size: 14px;
}

.ms-container .ms-selectable {
    margin: 0 3.2%;
}

.search-blog {
    background: #bcd5f0;
    border-radius: 5px;
}

</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		   			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_STUDENT_GROUP');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	
	    	<div class="card-box">
	        	<div class="col-md-8 col-sm-8 col-xs-12 search-blog">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-search" aria-hidden="true"></i> <?php echo $tr->translate("SEARCH_GROUP");?> 
	                   </label>
	                </div>
	                <form id="addstudenttogroup" dojoType="dijit.form.Form" action="" method="post" enctype="application/x-www-form-urlencoded">
						<div class="form-group">
							<div class="col-md-6 col-sm-6 col-xs-12">
								<div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GROUP_CODE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<select class="fullside" dojoType="dijit.form.FilteringSelect" required="true"  id="academy" name="academy" type="text">
											<option value=""><?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?></option>
											<?php if(!empty($this->academy)) foreach($this->academy as $row){?>
												<option value="<?php echo $row['id'];?>"><?php echo $row['years']; ?></option>
											<?php }?>
										</select>
				                   </div>
				                 </div>
			                </div>
			                <div class="col-md-6 col-sm-6 col-xs-12">
			                	<div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DEGREE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<select class="fullside"  name="degree" id="degree" dojoType="dijit.form.FilteringSelect" onchange="getallGrade();">
											<option value=""><?php echo $tr->translate("SELECT_DEGREE");?></option>		
											<?php if(!empty($this->degree))foreach ($this->degree as $row){?>
												<option value="<?php echo $row['id']?>"<?php if($row['id']==$this->value['degree']) echo "selected='selected'"?>><?php echo $row['name']?></option>
											<?php }?>
										</select>
				                   </div>
				                </div>
			                </div>
		                </div>
						<div class="form-group">
							<div class="col-md-6 col-sm-6 col-xs-12">
								 <div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GRADE");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		 <input id="grade" value="<?php echo $this->value['grade'];?>" />
				                   </div>
				                </div>
							</div>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<div class="form-group">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SESSION");?>  :
				                   </label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		 <select class="fullside"  tabindex="24" name="session" id="session" dojoType="dijit.form.FilteringSelect" >
										      <option value=""><?php echo $tr->translate("SELECT_SESSION");?></option>
										       <?php if(!empty($this->rs_session)) foreach ($this->rs_session As $rs_sesion){?>
												    <option value="<?php echo $rs_sesion['key_code'];?>" <?php if($rs_sesion['key_code']==$this->value['session']) echo "selected='selected'"?> ><?php echo $rs_sesion['view_name'];?></option>
										       <?php }?>			
										 </select>
				                   </div>
				                </div>
							</div>
						</div>
		                <div class="form-group">
		                   <div class="col-md-12 col-sm-12 col-xs-12">
		                   		 <input type="submit" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("SEARCH")?>" id="search"
								 	iconClass="dijitEditorIcon dijitEditorIconSearch"/>
		                   </div>
		                </div>
				</form>
			
	            </div>
	            <form id='submitgroup' dojoType="dijit.form.Form" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'addstudenttogroup','action'=>'submit1')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
						group = dijit.byId('group').get('value');
						if(group == -1){
							alert('Please select group !!! ');
							return false;
						}
					dijit.byId('save_close').set('disabled',true);	
					dijit.byId('save_new').set('disabled',true);	

						return true;
	   				}else {
						return false;
	   				}
			</script>
	        <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("GROUP_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GROUP_CODE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   			<input id="group" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-12 col-sm-12 col-xs-12" ><?php echo $tr->translate("DETAIL")?> :
	                   </label>
	                </div>
	                <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<label id="lbldetail" name=lbldetail style="border: 1px solid #ccc; background:#fff; font-size: 13px; min-height:70px;display:block;"></label>
							<input type="hidden" name="academic_year_group" id="academic_year_group" dojoType="dijit.form.TextBox" /> 
							<input type="hidden" name="degree_group" id="degree_group" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="grade_group" id="grade_group" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="session_group" id="session_group" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="room_group" id="room_group" dojoType="dijit.form.TextBox" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select class="fullside" dojoType="dijit.form.FilteringSelect" required="true"  id="status" name="status" type="text">		
								<option value="1"<?php if($this->id['status']==1) echo "selected='selected'"?>><?php echo $tr->translate("ACTIVE");?></option>						
								<option value="0"<?php if($this->id['status']==0) echo "selected='selected'"?>><?php echo $tr->translate("DEACTIVE");?></option>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12 text-center">
	                   		<input type="submit" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("SAVE");?>" id="save"
										iconClass="dijitEditorIcon dijitEditorIconSave"/>
	                   </div>
	                </div>
	            </div>
	            <div class="clearfix"></div>
			         <div class="card-box">
			         	<div class="form-group">
			         		<div class="col-md-12 col-sm-12 col-xs-12 text-center">
								<a id="select-all" href="#"><span style="font-size: 15px;"><?php echo $tr->translate("SELECT_ALL");?></span></a> <span style="font-size: 16px;"> | </span>
								<a id="deselect-all" href="#"><span style="font-size: 15px;"><?php echo $tr->translate("DESELECT_ALL");?></span></a> <span style="font-size: 16px;"> </span>
							</div>
							 <div class="clearfix"></div>
							<div class="col-md-12 col-sm-12 col-xs-12">
								<select multiple id="public-methods" name="public-methods[]">
									<?php $no=0; if(!empty($this->rs)) foreach($this->rs as $row ){$no++;?>
										<option value="<?php echo $row['stu_id'];?>" >
											<?php echo $no," . ",$row['stu_code']," - ",$row['stu_enname']," - ",$row['stu_khname']; ?>
										</option>
									<?php }?>
									<?php $no=0; if(!empty($this->rr)) foreach($this->rr as $row ){$no++;?>
										<option value="<?php echo $row['stu_id'];?>" <?php echo "selected='Selected'";?>>
											<?php echo $no," . ", $row['code']," - ",$row['kh_name']," - ",$row['en_name']; ?>
										</option>
									<?php }?>
								</select>
							</div>
							 <div class="clearfix"></div>
			         	</div>
			         </div>
	             </form>
	        </div>
	        
       
	</div>
</div>	
<script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/jquery.multi-select.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/rainbow.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/application.js" type="text/javascript"></script>
<script type="text/javascript">
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->group));?> );
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.ready(function(){
	new dijit.form.FilteringSelect({
	    queryExpr: "*${0}*",
		autoComplete: false,                        
	    id: "grade",
	    name: "grade",           
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
	    onChange: function() {  
	    	make_id = dijit.byId('grade').get('value');
	    	paymentTerm();
	    }
		
	}, "grade");

	new dijit.form.FilteringSelect({
	    store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                       
	    required: true,
	    id: "group",
	    name: "group",
	    readOnly: "true",           
	    class: 'fullside',            
	    onChange: function() { 
		    
	    } 
	}, "group");

	dijit.byId('group').attr('value','<?php echo $this->id['id']?>');	
	toaddstudenttogroup();
}); 
   
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'addstudenttogroup','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id != ''){
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id,
					},
				handleAs:"json",
				load: function(data) {
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store);   
				    dijit.byId('grade').attr('value','<?php echo $this->value['grade']; ?>');  
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
	
</script>
<?php
$frm_set_price = $this->frm_set_charge;?>





<script type="text/javascript">


	var url_to_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentchangegroup','action'=>'get-to-group')); ?>';
	function toaddstudenttogroup(){
		group = dijit.byId('group').get('value');
		dojo.xhrPost({
			url:url_to_group,
			content:{
				'to_group':group
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				dojo.byId('lbldetail').innerHTML='<span style="color:red;">Academic :  </span>'+data.year+'<span style="color:red;"> , Degree :  </span>'+data.degree+'<br /><span style="color:red;">  Grade :  </span>'+data.grade+'<span style="color:red;"> , Session :  </span>'+data.session+'<span style="color:red;"> , Room :  </span>'+data.room;

				dijit.byId('academic_year_group').attr('value',data.academic_year_id);
				dijit.byId('degree_group').attr('value',data.degree_id);
				dijit.byId('grade_group').attr('value',data.grade_id);
				dijit.byId('session_group').attr('value',data.session_id);
				dijit.byId('room_group').attr('value',data.room_id);
			},
			error: function(err) {
				alert(err);
			}
		});
	}

</script>


