<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_STUDENT_GROUP')); 
?>	
<head>
 <link href="<?php echo $this->baseUrl()."/jsmultiselect"?>/multi-select.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require('dijit.form.Textarea');
    dojo.require("dojo.parser");
    dojo.require("dojo.data.ItemFileWriteStore"); 
</script>
<style>
select{ width:100%;}
fieldset{  background:#DFF7FD;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}

table .set-style tr td a {
    font-size: 14px;
}

.ms-container .ms-selectable {
    margin: 0 3.2%;
}



</style>

<script type="text/javascript">
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->group));?> );
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.ready(function(){
	new dijit.form.FilteringSelect({
	    autoComplete: true,                        
	    id: "grade",
	    name: "grade",           
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
	    onChange: function() {  
	    	make_id = dijit.byId('grade').get('value');
	    	paymentTerm();
	    }
		
	}, "grade");

	new dijit.form.FilteringSelect({
	    store: group_store,
	    autoComplete: true,                        
	    required: true,
	    id: "group",
	    name: "group",
	    readOnly: "true",           
	    class: 'fullside',            
	    onChange: function() { 
		    
	    } 
	}, "group");

	dijit.byId('group').attr('value','<?php echo $this->id['id']?>');	
	toaddstudenttogroup();
}); 
   
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'addstudenttogroup','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id != ''){
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id,
					},
				handleAs:"json",
				load: function(data) {
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store);   
				    dijit.byId('grade').attr('value','<?php echo $this->value['grade']; ?>');  
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
	
</script>
<?php
$frm_set_price = $this->frm_set_charge;?>

<table cellspacing="10" style="margin: 0 auto;width:100%;" >
	<tr>
		<td valign="top">
		<form id='addstudenttogroup' dojoType="dijit.form.Form"  dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<fieldset style="width: 50%;float: left;">
					<legend align="center"><strong><?php echo $tr->translate("SEARCH_GROUP");?></strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD;white-space: nowrap;" cellspacing="10" broder 1>
						<tr>
							<td><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
							<td>
								<select class="fullside" dojoType="dijit.form.FilteringSelect" required="true"  id="academy" name="academy" type="text">
									<option value=""><?php echo $tr->translate("SELECT_YEAR");?></option>
									<?php if(!empty($this->academy)) foreach($this->academy as $row){?>
										<option value="<?php echo $row['id'];?>"><?php echo $row['years']; ?></option>
									<?php }?>
								</select>
							</td>
							<td><?php echo $tr->translate("DEGREE");?></td>
							<td >
								<select class="fullside"  name="degree" id="degree" dojoType="dijit.form.FilteringSelect" onchange="getallGrade();">
									<option value=""><?php echo $tr->translate("SELECT_DEGREE");?></option>		
									<?php if(!empty($this->degree))foreach ($this->degree as $row){?>
										<option value="<?php echo $row['dept_id']?>"<?php if($row['dept_id']==$this->value['degree']) echo "selected='selected'"?>><?php echo $row['en_name']?></option>
									<?php }?>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("GRADE");?></td>
							<td>
							    <input id="grade" value="<?php echo $this->value['grade'];?>" />
							</td>
							<td><?php echo $tr->translate("SESSION");?></td>
							<td>
								 <select class="fullside"  tabindex="24" name="session" id="session" dojoType="dijit.form.FilteringSelect" >
								      <option value=""><?php echo $tr->translate("SELECT_SESSION");?></option>
								       <?php if(!empty($this->rs_session)) foreach ($this->rs_session As $rs_sesion){?>
										    <option value="<?php echo $rs_sesion['key_code'];?>" <?php if($rs_sesion['key_code']==$this->value['session']) echo "selected='selected'"?> ><?php echo $rs_sesion['view_name'];?></option>
								       <?php }?>			
								 </select>
							</td>
						</tr>
						<tr>
							
							<td align="center" colspan="6">
								 	<input type="submit" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("SEARCH");?>" id="search"
								 		iconClass="dijitIconSearch"/>
							</td>
						</tr>
					
					</table>
			</fieldset>	
		</form>
		
		<form id='submitgroup' dojoType="dijit.form.Form" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'addstudenttogroup','action'=>'submit1')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<fieldset style="width: 49%;">
				<legend align="center"><strong><?php echo $tr->translate("TO_GROUP")?></strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD;" cellspacing="10" broder 1>
						<tr>
							<td><?php echo $tr->translate("GROUP");?></td>
							<td>
								<input id="group" />
							</td>
									
						</tr> 
						<tr>
							<td><?php echo $tr->translate("DETAIL")?></td>
							<td  colspan="3" rowspan="1"><label id="lbldetail"  name=lbldetail style="background:#fff;width:100%;height:100px;display:block;border: 1px solid #ccc;"></label></td>
							<input type="hidden" name="academic_year_group" id="academic_year_group" dojoType="dijit.form.TextBox" /> 
							<input type="hidden" name="degree_group" id="degree_group" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="grade_group" id="grade_group" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="session_group" id="session_group" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="room_group" id="room_group" dojoType="dijit.form.TextBox" />
						</tr> 
						<tr>
							<td><?php echo $tr->translate("STATUS");?></td>
							<td>
								<select class="fullside" dojoType="dijit.form.FilteringSelect" required="true"  id="status" name="status" type="text">		
									<option value="1"<?php if($this->id['status']==1) echo "selected='selected'"?>><?php echo $tr->translate("ACTIVE");?></option>						
									<option value="0"<?php if($this->id['status']==0) echo "selected='selected'"?>><?php echo $tr->translate("DEACTIVE");?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td align="center" colspan="8">
								<input type="submit" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("SAVE");?>" id="save"
										iconClass="dijitEditorIcon dijitEditorIconSave"/>
							</td>
						</tr>
					</table>
				</fieldset>		
					<div  align="center">
						<a id="select-all" href="#">Select all</a> <span style="font-size: 16px;"> | </span>
						<a id="deselect-all" href="#">Deselect all</a> <span style="font-size: 16px;"> </span>
					</div>
					<select multiple id="public-methods" name="public-methods[]">
						<?php $no=0; if(!empty($this->rs)) foreach($this->rs as $row ){$no++;?>
							<option value="<?php echo $row['stu_id'];?>" >
								<?php echo $no," . ",$row['stu_code']," - ",$row['stu_enname']," - ",$row['stu_khname']; ?>
							</option>
						<?php }?>
						<?php $no=0; if(!empty($this->rr)) foreach($this->rr as $row ){$no++;?>
							<option value="<?php echo $row['stu_id'];?>" <?php echo "selected='Selected'";?>>
								<?php echo $no," . ", $row['code']," - ",$row['kh_name']," - ",$row['en_name']; ?>
							</option>
						<?php }?>
					</select>
						
						
						 
						 <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/jquery.multi-select.js" type="text/javascript"></script>
		   				 <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/rainbow.js" type="text/javascript"></script>
		   				 <script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/application.js" type="text/javascript"></script>
		</form>
		
		</td>
	</tr>		
</table>	



<script type="text/javascript">


	var url_to_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentchangegroup','action'=>'get-to-group')); ?>';
	function toaddstudenttogroup(){
		group = dijit.byId('group').get('value');
		dojo.xhrPost({
			url:url_to_group,
			content:{
				'to_group':group
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				dojo.byId('lbldetail').innerHTML='<span style="color:red;">Academic :  </span>'+data.year+'<span style="color:red;"> , Degree :  </span>'+data.degree+'<br /><span style="color:red;">  Grade :  </span>'+data.grade+'<span style="color:red;"> , Session :  </span>'+data.session+'<span style="color:red;"> , Room :  </span>'+data.room+'<br /><span style="color:red;">  Start Date :  </span>'+data.start_date+'<span style="color:red;"> , Expired Date :  </span>'+data.expired_date;

				dijit.byId('academic_year_group').attr('value',data.academic_year_id);
				dijit.byId('degree_group').attr('value',data.degree_id);
				dijit.byId('grade_group').attr('value',data.grade_id);
				dijit.byId('session_group').attr('value',data.session_id);
				dijit.byId('room_group').attr('value',data.room_id);
			},
			error: function(err) {
				alert(err);
			}
		});
	}

</script>


