<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('STUDENT_TO_GROUP')); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		   			<h4 class="m-b-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_TO_GROUP');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'addstudenttogroup','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<input dojoType="dijit.form.TextBox"   id="adv_search" name="adv_search" placeholder="<?php echo $tr->translate("SEARCH");?>....." value="<?php echo $this->adv_search['adv_search']; ?>"  class="fullside" type="text">
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("branch_id");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("study_year");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("degree");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("grade_all");?>
					 </div>
				</div>
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("session");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("room");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					 </div>
				</div>
            </form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>	
