<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('RPT_ADJUST_STOCK')); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
	$rows=$this->rows;
	//print_r($rows);
?>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_ADJUST_STOCK');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form action="" dojoType="dijit.form.Form" method="post">
		 <div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('title');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('branch_id');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('start_date');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('end_date');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('user_id');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
        </div>
	</form>
	<style>
	#footer{display: none;}
	</style>	
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<style>
				a{text-decoration: none;color: 000;}
			</style>
			<table width="100%">
				<tr>
					<td width="15%" align="center">
						<img style="width:60%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"> 
					</td>
					<td align="center" width="70%">
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('CUSTOMER_BRANCH');?></strong><br />
						<strong style="padding-left: 0px;font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('RPT_ADJUST_STOCK');?></strong><br>
						<span style="font-weight: bold;font-size: 12px; "><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search['start_date']));?> &nbsp;<?php echo $tr->translate('TO');?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));}?></span>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<style>
					table tr th{
						border: 1px solid #000;	
					}
					table {page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					}		
					thead tr td {
						font-weight: bold;
						padding: 6px 2px;
					}					
				</style>
				<tr>
					<td colspan="3" id="exportExcel">
						<table cellpadding="4"​ style="font-family:'Khmer OS Battambang' ; margin:0 auto;width:100%;border:1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<thead>
								<tr style="font-size:12px; height: 20px;background: #ccd9ff;" align="center" >
									<td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
									<td colspan="2">&nbsp;<?php echo $tr->translate("PRODUCT_INFO");?>&nbsp;</td>
									<td colspan="7">&nbsp;<?php echo $tr->translate("ADJUST_INFO");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("USER");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("STATUS");?>&nbsp;</td>
								</tr>
								
								<tr style="font-size:12px; height: 20px;background: #ccd9ff;" align="center" >
									<td><?php echo $tr->translate("CATEGORY");?></td>
									<td><?php echo $tr->translate("PRODUCT_NAME");?></td>
									
									<td><?php echo $tr->translate("ADJUST_NO");?></td>
									<td><?php echo $tr->translate("TITLE");?></td>
									<td><?php echo $tr->translate("QTY_BEFOR");?></td>
									<td><?php echo $tr->translate("QUANTITY_NEW");?></td>
									<td><?php echo $tr->translate("STOCK_SPACING");?></td>
									<td><?php echo $tr->translate("NOTE");?></td>
									<td><?php echo $tr->translate("ADJUST_DATE");?></td>
								</tr>
							</thead>
							<?php 
							$gender=array(1=>"Male",2=>"Female");
							if(!empty($rows))foreach($rows As $key=> $rs_row){
							?>
							<tr style="font-size:12px; height: 23px;" class="hover" >
								<td >&nbsp;<?php echo $key+1; ?>&nbsp;</td>
								<td >&nbsp;<?php echo $rs_row['branch_name']; ?>&nbsp;</td>
								<td >&nbsp;<?php echo $rs_row['category']; ?>&nbsp;</td>
								<td >&nbsp;<?php echo $rs_row['pro_name']; ?>&nbsp;</td>
								
								<td align="center">&nbsp;<strong><?php echo $rs_row['adjust_no']; ?></strong>&nbsp;</td>
								<td >&nbsp;<?php echo $rs_row['request_name']; ?>&nbsp;</td>
								
								<td align="center">&nbsp;<?php if($rs_row['qty_befor']!=0) echo $rs_row['qty_befor']; ?>&nbsp;</td>
								<td align="center">&nbsp;<?php if($rs_row['qty_after']!=0) echo $rs_row['qty_after']; ?>&nbsp;</td>
								<td align="center">&nbsp;<?php if($rs_row['difference']!=0) echo $rs_row['difference']; ?>&nbsp;</td>
								<td >&nbsp;<?php echo $rs_row['note']; ?></td>
								<td align="center">&nbsp;<?php echo date("d/m/Y",strtotime($rs_row['request_date'])); ?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo $rs_row['user_name']; ?>&nbsp;</td>
								<td align="center">&nbsp;<?php if ($rs_row['status']==1){ echo $tr->translate("ACTIVE"); }else{ echo $tr->translate("DEACTIVE");} ?>&nbsp;</td>
							</tr>
							<?php
							}
							?>
						</table>
						<table width="100%" style="font-family:'Khmer OS Battambang';">
							<tr>
								<td colspan="3">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="3">&nbsp;</td>
							</tr>
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>	
	</div>
</div>