<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_PURCHASE_ALL')); 
	$frm =  $this->form_search;
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->form_search;
?>	
<meta charset="utf-8">
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_PURCHASE_ALL');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form action="" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("title");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("location");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("supplier_id");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("category_id");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("product");?>
        	</div>
        	
        </div>
        <div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("start_date");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("end_date");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("status_search");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"
						showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
        </div>
	</form>
	 <div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="15%" align="center">
					</td>
					<td align="center" width="70%">
						<strong style="padding-left: 1px;font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('RPT_PURCHASE_ALL');?></strong><br>
						<span style="font-weight: bold;font-size: 12px; "><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search['start_date']));?> &nbsp;<?php echo $tr->translate('TO');?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));}?></span>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
						<style>
							table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
							tr{ page-break-inside:avoid; page-break-after:auto }
							.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap; font-size: 14px;}
							#header {
							  display: table-header-group;
							  page-break-inside:avoid; page-break-after:auto;
							}
							.hover:hover{background:#eee;}
							tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }										
						</style>
						<table cellpadding="5"​ style="font-family:'Khmer OS Battambang';margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<thead>
								<tr style="font-size:12px; height: 16px; background-color: #CCD9FF;line-height: 24px;font-weight: bold;" align="center">
									<td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
									<td colspan="2">&nbsp;<?php echo $tr->translate("SUPPLIER_INFO");?>&nbsp;</td>
									<td colspan="8">&nbsp;<?php echo $tr->translate("PURCHASE_INFO");?>&nbsp;</td>
								</tr>
								<tr style="font-size:12px; height: 16px;background-color: #CCD9FF;line-height: 24px;font-weight: bold;" align="center">
									
									<td>&nbsp;<?php echo $tr->translate('SUPPLIER_NAME');?></td>
									<td>&nbsp;<?php echo $tr->translate('TEL');?></td>
									<td>&nbsp;<?php echo $tr->translate('PURCHASE_NO');?></td>
									<td>&nbsp;<?php echo $tr->translate('PRODUCT_CATEGORY');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('PRODUCT_NAME');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('QTY');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('COST');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('TOTAL');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('DATE');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('STATUS');?>&nbsp;</td>
							   </tr>
						   </thead>
						<?php $i=0;
						$totalpaid=0;
						$totalQTY=0;
						$totalbalance=0; if(!empty($this->pur_all))foreach ($this->pur_all AS $rs) { $i++; ?>
							<tr class="hover" style="font-size:11px; height: 18px;"​ align="center">
								    <td>&nbsp;<?php echo $i; ?>&nbsp;</td>
								    <td>&nbsp;<?php echo $rs['brand_name'];?>&nbsp;</td>
								    <td>&nbsp;<?php echo $rs['sup_name'];?>&nbsp;</td>
								    <td>&nbsp;<?php echo $rs['tel'];?>&nbsp;</td>
								    <td>&nbsp;<strong><?php echo $rs['supplier_no'];?></strong>&nbsp;</td>
								    <td>&nbsp;<?php echo $rs['cate_name'];?>&nbsp;</td>
								    <td>&nbsp;<?php echo $rs['pro_id'];?>&nbsp;</td>
								    <td><?php echo number_format($rs['qty'],0);?>&nbsp;</td>
								    <td>&nbsp;$&nbsp;<?php echo $rs['cost'];?>&nbsp;</td>
								    <td>&nbsp;$&nbsp;<?php echo $rs['amount'];?>&nbsp;</td>
								    <td><?php echo date("d/m/Y",strtotime($rs['date']));?>&nbsp;</td>
								    <td>&nbsp;<?php echo $rs['status']; ?>&nbsp;</td>
							 </tr>
							<?php $totalbalance=$totalbalance+$rs['amount'];
							$totalQTY = $totalQTY +$rs['qty'];
							}?>	  
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<?php if(!empty($this->pur_all)){?>
				<tr>
					<td colspan="3" align="right">
					     <table width="25%"  style="font-family:'Times New Roman','Khmer OS Battambang'; border: 1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1"  >
					           <tr align="center" style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center">
					               <td><?php echo $tr->translate('TOTAL_QTY');?> :</td>
					               <td align="right"><strong>&nbsp;<?php echo number_format($totalQTY,2)." ".$tr->translate('Items');?>&nbsp;</strong></td>
					           </tr>
					           <tr align="center" style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center">
					               <td><?php echo $tr->translate('TOTAL_AMOUNT');?> :</td>
					               <td align="right"><strong>&nbsp;$&nbsp;<?php echo number_format($totalbalance,2);?>&nbsp;</strong></td>
					           </tr>
					     </table>
					</td>
				</tr>
				<?php }?>
				
				<tr>
					<td colspan="3" width="100%">
						<table width="100%" style="font-family:'Khmer OS Battambang';">
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>		
	</div>
</div>