<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_PRODUCT_SELLOUT')); 
	$frm = $this->form_search;
	$classHideHeight=classHideHeight;
?>	
<meta charset="utf-8">
<style>
	.hover:hover{ background:#ccc;}
	table.content-data tr.style-head,
	
</style>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_PRODUCT_SELLOUT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form dojoType="dijit.form.Form" method="post">
		<div class="form-group">
        	<div class="col-md-3 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("title");?>
        	</div>
        	<div class="col-md-3 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("branch_id");?>
        	</div>
        	<div class="col-md-3 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("category_id");?>
        	</div>
        	<div class="col-md-3 col-sm-2 col-xs-12">
        		<input id="product" />
        	</div>
        </div>
        <div class="form-group">
        	<div class="col-md-3 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("start_date");?>
        	</div>
        	<div class="col-md-3 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("end_date");?>
        	</div>
			<div class="col-md-3 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("user");?>
        	</div>
        	<div class="col-md-3 col-sm-2 col-xs-12">
        		<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button"
					showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
        </div>
	</form>
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;font-family:'Times New Roman','Khmer OS Battambang';" >
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr>
					<td width="15%" align="center">
					</td>
					<td align="center"  width="70%">
						<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate('RPT_PRODUCT_SELLOUT');?></span><br />
						<span style="color:#000; font-size: 12px;"><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> <?php echo $tr->translate('TO');?> <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></span> 
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
					<style>
					.style{
						line-height: 22px;font-size: 11px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.style1:hover{ background: #ccc; }
					table.content-data { page-break-inside:auto }
					table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:8px;
						width:100%;
					}
					table.content-data thead tr.style {
					   line-height: 22px; font-size:10px !important; padding:1px 0px; white-space: nowrap; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.content-data tr.style {
					   white-space: nowrap;
					}
					table tr td{
						padding:0 2px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					.redBold {
						font-weight: 600;
						color: #f80000;
					}
					table.content-data tr td{
						padding: 1px;
					}	
					@media print{
						@page{
							margin:0.3cm 0.7cm 0cm 0.7cm;
							page-break-before: avoid;
							-webkit-transform: scale(0.5);  /* Chrome, Safari 3.1+  */
							-moz-transform: scale(0.5);  /* Firefox 3.5-15 */
							-ms-transform: scale(0.5);   /* IE 9 */
							-o-transform: scale(0.5);    /* Opera 10.50-12.00 */
							transform: scale(0.5);
							size:A4 landscape;
						}
					}						
						</style>
						<table class="content-data" cellpadding="5"​  border="1" >
							<thead>
								<tr class="style"  align="center">
									<td scope="col" rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td scope="col" rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH");?>&nbsp;</td>
									<td scope="col" colspan="2">&nbsp;<?php echo $tr->translate("STUDENT_INFO");?>&nbsp;</td>
									<td scope="col" colspan="2">&nbsp;<?php echo $tr->translate("PRODUCT_INFO");?>&nbsp;</td>
									<td scope="col" colspan="10">&nbsp;<?php echo $tr->translate("PRODUCT_INFO");?>&nbsp;</td>
								</tr>
								<tr class="style" align="center">
									<td scope="col">&nbsp;<?php echo $tr->translate('STUDENT_ID');?></td>
									<td scope="col">&nbsp;<?php echo $tr->translate('STUDENT_NAME');?></td>
									<td scope="col">&nbsp;<?php echo $tr->translate('PRODUCT_CATEGORY');?></td>
									<td scope="col">&nbsp;<?php echo $tr->translate('PRODUCT_NAME');?></td>
									<td scope="col">&nbsp;<?php echo $tr->translate('QTY');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('UNIT_COST');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('TOTAL_COST');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('SELL_PRICE');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('TOTAL');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('PROFIT');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('RECEIPT_NO');?></td>
									<td scope="col"> &nbsp;<?php echo $tr->translate('CREATE_DATE');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('USER');?>&nbsp;</td>
							   </tr>
						   </thead>
						<?php $i=0;
							$totalCost=0;
							$totalSell=0;
						if(!empty($this->product_sold)){ foreach ($this->product_sold AS $rs) { $i++;
						?>
							<tr class="style hover" align="left">
							    <td align="center" data-label="<?php echo $tr->translate("NUM");?>"><?php echo $i; ?></td>
							    <td data-label="<?php echo $tr->translate("BRANCH");?>"> <?php echo $rs['branch_name'];?></td>
							    <td data-label="<?php echo $tr->translate("STUDENT_ID");?>"><?php echo $rs['stu_code'];?></td>
							    <td data-label="<?php echo $tr->translate("STUDENT_NAME");?>" style="text-align: left;"><?php echo $rs['student_name'];?></td>
							    <td data-label="<?php echo $tr->translate("PRODUCT_CATEGORY");?>"><?php echo $rs['category'];?></td>
							    <td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" style="text-align: left;">&nbsp;<?php echo $rs['items_name'];?></td>
							    <td data-label="<?php echo $tr->translate("QTY");?>"><?php echo $rs['qty'];?></td>
							    <td data-label="<?php echo $tr->translate("UNIT_COST");?>"><?php echo $rs['cost'];?></td>
							    <td data-label="<?php echo $tr->translate("TOTAL_COST");?>"><strong>
							    <?php 
								    	$subTotalcost = $rs['qty']*$rs['cost'];
								    	echo number_format($subTotalcost,2);
								    	$subTotalSell=$rs['qty']*$rs['price'];
								    	$totalCost = $totalCost+$subTotalcost;
								    	$totalSell = $totalSell+$subTotalSell;
							    ?>
							    </strong></td>
							    <td data-label="<?php echo $tr->translate("SELL_PRICE");?>"><?php echo $rs['price'];?></td>
							    <td data-label="<?php echo $tr->translate("TOTAL");?>"><strong><?php echo number_format($subTotalSell,2);?></strong>&nbsp;</td>
							    <td align="center" data-label="<?php echo $tr->translate("PROFIT");?>"><strong><?php echo number_format($subTotalSell-$subTotalcost,2);?></strong>&nbsp;</td>
							    <td align="center" data-label="<?php echo $tr->translate("RECEIPT_NO");?>"><strong><?php echo $rs['receipt_number'];?></strong></td>
							    <td align="center" data-label="<?php echo $tr->translate("CREATE_DATE");?>"><?php echo date('d/m/Y',strtotime($rs['create_date']));?></td>
							    <td align="center" data-label="<?php echo $tr->translate("USER");?>"><?php echo $rs['user']; ?></td>
							 </tr>
						  		<?php 
								}}
								?>	  
						</table>
						<table width="40%" border="1" style="font-family:'Times New Roman','Khmer OS Battambang'; margin-top:15px;border: 1px solid #000;border-collapse: collapse;float:right"  >
						   <tr align="center" style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height:25px; " align="center">
							   <td width="33%"><?php echo $tr->translate('TOTAL_UNIT_PRICE')?></td>
							    <td width="33%"><?php echo $tr->translate('TOTAL_SALE')?></td>
							   <td width="33%"><?php echo $tr->translate('TOTAL_PROFIT')?></td>
						   </tr>
						    <tr align="center" style="font-size:12px;line-height:25px;font-weight:bold;" align="center">
							   <td>$ <?php echo number_format($totalCost,2);?></td>
							   <td>$ <?php echo number_format($totalSell,2);?></td>
							   <td>$ <?php echo number_format($totalSell-$totalCost,2);?></td>
						   </tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
			</table>
		</div>		
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  

	var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		getProductByCate();
		new dijit.form.FilteringSelect({
			store: academic_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "study_year",
			name: "study_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				academic_year = dijit.byId('study_year').get('value');
			}
		}, "study_year");
		
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",
			placeholder:'<?php echo $tr->translate("SELECT_PRODUCT");?>',
			required:false,        
			class: 'fullside', 
		}, "product");
		
		var branch_id = dijit.byId('branch_id');
		branch_id.on('change', function(evt) {
		});
	});
	url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
	var oldBranch = "<?php echo $this->search['branch_id']?>";
	function getAllAcademicByBranch(){
		dijit.byId('study_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('study_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		
		contentData = {
			'branch_id':branch_id
		}
		selectedId = '';
		if(oldBranch==branch_id){
			//selectedId = '<?php //echo $this->search['study_year']?>';
		}
		getAllYear(url_getacademic,contentData,selectedId);
		
	}
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value','<?php echo $this->search['product']?>');
				},
				error: function(err) {
				}
			});
	}
</script>