<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('RPT_REQUEST_PRODUCT')); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
	$rows=$this->rows;
?>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_REQUEST_PRODUCT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form action="" dojoType="dijit.form.Form" method="post">
		 <div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('title');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('branch_id');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<select name="request_for" id="request_for" dojoType="dijit.form.FilteringSelect" class="fullside" >
						<option value="-1"><?php echo $tr->translate('SELECT_REQUEST_FOR')?></option>
						<?php if(!empty($this->rq_for)){foreach($this->rq_for as $req_for){?>
							<option value="<?php echo $req_for['id']?>" <?php if($req_for['id']==$this->search['request_for']){echo "selected='selected'";}?> ><?php echo $req_for['name']?></option>
						<?php }}?>
					</select>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<select name="for_section" id="for_section" dojoType="dijit.form.FilteringSelect" class="fullside" >
					<option value="-1"><?php echo $tr->translate('SELECT_REQUEST_FOR_DEPT')?></option>
					<?php if(!empty($this->for_section)){foreach($this->for_section as $for_sec){?>
						<option value="<?php echo $for_sec['id']?>" <?php if($for_sec['id']==$this->search['for_section']){echo "selected='selected'";}?> ><?php echo $for_sec['name']?></option>
					<?php }}?>
				</select>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        	</div>
        </div>
         <div class="form-group">
         	<div class="col-md-2 col-sm-2 col-xs-12">
         		<?php echo $frm->getElement('start_date');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('end_date');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('status');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
         </div>
	</form>
	<style>
	#footer{display: none;}
	</style>	
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<style>
				a{text-decoration: none;color: 000;}
				.hover:hover{background: #ddd;}
			</style>
			<table width="100%">
				<tr>
					<td width="15%" align="center">
						<img style="width:60%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"> 
					</td>
					<td align="center" width="70%">
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('CUSTOMER_BRANCH');?></strong><br />
						<strong style="padding-left: 10px;font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('RPT_REQUEST_PRODUCT');?></strong> 
						<div><?php if(!empty($this->search['start_date'])){echo date("d/m/Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';} echo date("d/m/Y",strtotime($this->search['end_date']));?></div>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<table class="table" style="width:100%; border:1px solid #ddd; border-collapse: collapse;font-family:'Khmer OS Battambang';" >
							<tr style="background: #CCD9FF;font-size: 12px; line-height: 30px;font-weight: bold;" align="center">
								<td style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("N_O");?></td>
								<td style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("BRANCH");?></td>
								<td style="border:1px solid #000;text-align: center;" nowrap><?php echo $tr->translate("REQUEST_NO");?></td>
								<td style="border:1px solid #000;text-align: center;" nowrap><?php echo $tr->translate("REQUEST_FOR");?></td>
								<td style="border:1px solid #000;text-align: center;" nowrap><?php echo $tr->translate("FOR_SECTION");?></td>
								<td style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("PURPOSE");?></td>
								<td style="border:1px solid #000;text-align: center;" ><?php echo $tr->translate("REQUEST_DATE");?></td>
								<td style="border:1px solid #000;text-align: center;" nowrap><?php echo $tr->translate("USER");?></td>
								<td style="border:1px solid #000;text-align: center;" nowrap><?php echo $tr->translate("STATUS");?></td>
							</tr>
							<?php 
							$gender=array(1=>"Male",2=>"Female");
							$i=0;
							if(!empty($rows)) foreach($rows As $key=> $rs_row){	$i++;
							?>
								<tr style="font-size: 12px;" class="hover">
									<td style="border:1px solid #000;text-align: center;"><?php echo $i; ?></td>
									<td style="border:1px solid #000;text-align: center;"><?php echo $rs_row['branch_name'];; ?></td>
									<td style="border:1px solid #000;text-align: center;"><a style="color: #000;" target="_blank" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'reprint-request-product','id'=>$rs_row['id']))?>"><?php echo $rs_row['request_no']; ?></a></td>
									<td style="border:1px solid #000;text-align: center;"><a style="color: #000;" target="_blank" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'reprint-request-product','id'=>$rs_row['id']))?>"><?php echo $rs_row['request_for']; ?></a></td>
									<td style="border:1px solid #000;text-align: center;"><a style="color: #000;" target="_blank" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'reprint-request-product','id'=>$rs_row['id']))?>"><?php echo $rs_row['for_section']; ?></a></td>   
									<td style="border:1px solid #000;text-align: center;"><?php echo $rs_row['purpose']; ?></td>
									<td style="border:1px solid #000;text-align: center;"><?php echo date("d-M-Y",strtotime($rs_row['request_date'])); ?></td>
									<td style="border:1px solid #000;text-align: center;"><?php echo $rs_row['user']; ?> </td>
									<td style="border:1px solid #000;text-align: center;"><?php echo $rs_row['status']; ?> </td>
								</tr>
							<?php
							}
							?>
						</table>
						<table width="100%" style="font-family:'Khmer OS Battambang';">
							<tr>
								<td colspan="3">&nbsp;</td>
							</tr>
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>	
	</div>
</div>
