<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('TRANSFER'));
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
	$formList = new Application_Form_Frmtable();
?>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('TRANSFER');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form action="" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
			<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement("title");?>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement("start_date");?>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement("end_date");?>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
			</div>
		</div>
	</form>
	<style>
		#footer{display: none;}
	</style>	
	<div style="min-height:22cm; margin:0 auto;">
			<div id="divPrint">
			<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr >
					<td width="15%" align="center">
					</td>
					<td width="70%" align="center">
					    <strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('TRANSFER')?></strong><br />					
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search["start_date"]))?><?php echo $tr->translate('TO');?><?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></strong> 
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>		
					<style>
						table tr th{
						border: 1px solid #000;	
						}
						table {page-break-inside:auto }
						tr{ page-break-inside:avoid; page-break-after:auto; }
						#header {
						  display: table-header-group;
						  page-break-inside:avoid; page-break-after:auto;
						}
						.hover:hover{background:#eee;}
						tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }					
					</style>
					<tr colspan="3">
					<td colspan="3" id="exportExcel" >
						<table class="table" style="width:100%; border:1px solid #ddd; border-collapse: collapse;font-family:'Khmer OS Battambang';" >
							<thead>
							<tr style="background: #ccd9ff; white-space: bold; font-size: 13px;font-weight: bold;">
								<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("N_O");?></th>
								<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("TRANSFER_NUMBER");?></th>
								<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("TRANSFER_DATE");?></th>
								<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("FROM_LOCATION");?></th>
								<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("TO_LOCATION");?></th>
								<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("NOTE");?></th>
								<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("BY_USER");?></th>
								<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("STATUS");?></th>
							</tr>
							</thead>
							<?php if(!empty($this->all_transfer)){ foreach($this->all_transfer as $key=>$rs){ $key=$key+1; ?>
							<tr style="font-size: 12px;">
								<td style="border:1px solid #000;text-align: center;"><?php echo $key; ?></td>
								<td style="border:1px solid #000;text-align: center;"><a target="_blank" style="color:#000;" href="<?php echo $this->baseurl();?>/allreport/stock/rpt-transferdetail/id/<?php echo $rs['id'];?>"><?php echo $rs['transfer_no']; ?></a></td>
								<td style="border:1px solid #000;text-align: center;"><a target="_blank" style="color:#000;" href="<?php echo $this->baseurl();?>/allreport/stock/rpt-transferdetail/id/<?php echo $rs['id'];?>"><?php echo $rs['transfer_date']; ?></a></td>
								<td style="border:1px solid #000;text-align: center;"><?php echo $rs['fromlocation']; ?></td>
								<td style="border:1px solid #000;text-align: center;"><?php echo $rs['tolocation']; ?></td>
								<td style="border:1px solid #000;text-align: center;"><?php echo $rs['note']; ?></td>
								<td style="border:1px solid #000;text-align: center;"><?php echo $rs['user_name']; ?></td>
								<td style="border:1px solid #000;text-align: center;"><?php echo $rs['status']; ?></td>
							</tr>
							<?php
							}}
							?>
						</table>
						</tr>
					</tr>
				</td>
			</table>
			<table width="100%" style="font-family:'Khmer OS Battambang';">
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td  width="25%" align="center">
						<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
					</td>
					<td  width="50%">
						&nbsp;
					</td>
					<td align="center"  width="25%">
						<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
					</td>
				</tr>
			</table>
		</div>	
	</div>
</div>