<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Payment Late'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->form_search;
?>	
<meta charset="utf-8">
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<form action="" dojoType="dijit.form.Form" method="post">
		<table style="width: 100%">
			<tr>
				<td><?php echo $frm->getElement("title");?></td>
				<td><?php echo $frm->getElement("location");?></td>
				<td> <?php echo $frm->getElement("supplier_id");?></td>
				<td> <?php echo $frm->getElement("start_date");?></td>
				<td> <?php echo $frm->getElement("end_date");?></td>
				<td>
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"
						showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</td>
			</tr>
		</table>
	</form>
 
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
				<tr>
					<td width="15%" align="center">
						<img style="width:60%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"> 
					</td>
					<td align="center" width="70%">
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('CUSTOMER_BRANCH');?></strong><br />
						<strong style="padding-left: 10px;font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('RPT_PURCHASE');?></strong><br>
						<span style="font-weight: bold;font-size: 12px; "><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search['start_date']));?> &nbsp;<?php echo $tr->translate('TO');?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));}?></span>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
					<style>
						table tr th{
							border: 1px solid #000;	
						}
						table {page-break-inside:auto }
						tr{ page-break-inside:avoid; page-break-after:auto; }
						#header {
						  display: table-header-group;
						  page-break-inside:avoid; page-break-after:auto;
						}							
					</style>
					<tr>
					<td colspan="3" id="exportExcel">
						<table cellpadding="5"​ style="font-family:'Khmer OS Battambang';margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<thead>
							<tr style="font-size:12px; height: 20px;background-color: #CCD9FF;line-height: 30px;font-weight: bold;" align="center">
									<th>&nbsp;<?php echo $tr->translate('N_O');?>&nbsp;</th>
									<th>&nbsp;<?php echo $tr->translate('PURCHASE_NO');?>&nbsp;</th>
									<th>&nbsp;<?php echo $tr->translate('BRANCH_NAME');?>&nbsp;</th>
									<th>&nbsp;<?php echo $tr->translate('SUPPLIER_NAME');?>&nbsp;</th>
									<th>&nbsp;<?php echo $tr->translate('TEL');?>&nbsp;</th>
									<th>&nbsp;<?php echo $tr->translate('TOTAL_AMOUNT');?>&nbsp;</th>
									<th>&nbsp;<?php echo $tr->translate('DATE');?>&nbsp;</th>
									<th>&nbsp;<?php echo $tr->translate('STATUS');?>&nbsp;</th>
									<th>&nbsp;<?php echo $tr->translate('PRINT');?>&nbsp;</th>
						   </tr>
							</thead>
						<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->pur_code))foreach ($this->pur_code AS $rs) { $i++;
						       
						  ?>
							<tr class="hover" style="font-size:11px; height: 18px;"​ align="center">
								    <td> <?php echo $i; ?></td>
								    <td ><a target="_blank" style="text-decoration: none;color:#000;" href="<?php echo $this->baseUrl();?>/allreport/stock/rpt-purchase-supplier/id/<?php echo $rs['id'];?>"><?php echo $rs['supplier_no'];?></a></td>
								    <td><?php echo $rs['branch_name'];?></td>
								    <td><?php echo $rs['sup_name'];?></td>
								    <td><?php echo $rs['tel'];?></td>
								    <td>&nbsp;$&nbsp;<?php echo $rs['amount_due'];?></td>
								    <td><?php echo date("d/m/Y",strtotime($rs['date']));?></td>
								    <td><?php echo $rs['status']; ?></td>
								    <td><a target="_blank" style="text-decoration: none;color:#000;" href="<?php echo $this->baseUrl();?>/allreport/stock/rpt-purchase-supplier/id/<?php echo $rs['id'];?>"><?php echo $tr->translate('PRINT');?></a></td>
							 </tr>
						  
										<?php $totalbalance=$totalbalance+$rs['amount_due'];}?>	 
							
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3" align="right">
					     <table width="20%"  style="border: 0px solid #000;border-collapse: collapse;"  >
					           <tr align="center" style="font-size:12px; height: 20px;background-color: #ccc;line-height: 30px;font-weight: bold;" align="center">
					               <td>Total Amount :</td><td>&nbsp;$&nbsp;<?php echo number_format($totalbalance,2);?>&nbsp;</td>
					           </tr>
					     </table>
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" width="100%">
						<table width="100%" style="font-family:'Khmer OS Battambang';">
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>		
	</div>
</div>





