<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_PRODUCT_LOCATION')); 
	$frm =  $this->form_search;
	$base_url = Application_Form_FrmMessage::getUrl("/");
	?>	
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_PRODUCT_LOCATION');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
		<form dojoType="dijit.form.Form" method="post">
			<div class="form-group">
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("title");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("location");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("category_id");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("product");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("status_search");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"
							showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
			</div>
		</form>
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="15%" align="center">
					</td>
					<td align="center" width="70%">
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('RPT_PRODUCT_LOCATION');?></strong><br />
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
						<style>
							table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
							tr{ page-break-inside:avoid; page-break-after:auto }
							.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap; font-size: 14px;}
							#header {
							  display: table-header-group;
							  page-break-inside:avoid; page-break-after:auto;
							}
						.hover:hover{background:#eee;}	
							tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }									
						</style>
						<table cellpadding="5"​ style="font-family:'Times New Roman','Khmer OS Battambang';margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<thead>
								<tr style="font-size:12px; height: 16px; background-color: #CCD9FF;line-height: 24px;font-weight: bold;" align="center">
									<td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td colspan="3">&nbsp;<?php echo $tr->translate("PRODUCT_INFO");?>&nbsp;</td>
									<td colspan="5">&nbsp;<?php echo $tr->translate("STOCK_INFO");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("DATE");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("NOTE");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("STATUS");?>&nbsp;</td>
								</tr>
								<tr style="font-size:12px; height: 16px; background-color: #CCD9FF;line-height: 24px;font-weight: bold;" align="center">
									<td>&nbsp;<?php echo $tr->translate('PRODUCT_CATEGORY');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('PRODUCT_CODE');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('PRODUCT_NAME');?>&nbsp;</td>
									
									<td>&nbsp;<?php echo $tr->translate('QTY');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('UNIT_PRICE');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('TOTAL');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('SELL_PRICE');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('TOTAL');?>&nbsp;</td>
									
							   </tr>
						   </thead>
						<?php 
							$branch_name =''; 
						
							$i=0;
							$total_sell=0;
							$total_cost=0;
							if(!empty($this->pro_loc)) foreach ($this->pro_loc AS $rs) { $i++;
						   if($branch_name!=$rs['brand_name']){
						  ?>
							<tr class="hover" style="font-size:15px; height: 18px;"​ align="center">
							    <td colspan="12" ><strong><?php echo $rs['brand_name']; ?></strong></td>
							</tr>
							<?php } $branch_name=$rs['brand_name'];?>
							<tr class="hover" style="font-size:12px; height: 18px;"​ align="center">
							    <td> <?php echo $i; ?></td>
							    <td style="text-align: left;">&nbsp;<?php echo $rs['category_name'];?></td>
							    <td><?php echo $rs['pro_code'];?></td>
							    <?php $url_barcode = $this->url(array("module"=>"allreport","controller"=>"accounting","action"=>"generate-barcode","pro_code"=>$rs['pro_code']),null,true); ?>
							    <!-- <td><img src="<?php //echo $url_barcode;?>" /></td> -->
							    <td align="left">&nbsp;<?php echo $rs['pro_name'];?></td>
							    <td><?php echo number_format($rs['pro_qty'],0); ?></td>
							    <td>&nbsp;&nbsp;<?php echo number_format($rs['cost'],2);?></td>
							    <td><span style="float: right;"><?php echo number_format($rs['pro_qty']*$rs['cost'],2);?>&nbsp;</span></td>
								<td><span style="float: right;"><?php echo number_format($rs['pro_price'],2);?>&nbsp;</span></td>
								<td><span style="float: right;"><?php echo number_format($rs['pro_qty']*$rs['pro_price'],2);?>&nbsp;</span></td>
								    <?php 
								    $total_cost = $total_cost+($rs['pro_qty']*$rs['cost']);
								    $total_sell = $total_sell+($rs['pro_qty']*$rs['pro_price']);
								    ?>
							    <td><?php echo date("d/m/Y",strtotime($rs['date']));?></td>
							    <td><?php echo $rs['note']; ?></td>
							    <td><?php echo $rs['status']; ?></td>
							</tr>
								<?php
									} 
								?>
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<?php if(!empty($this->pro_loc)){?>
				<tr>
					<td colspan="3" align="right">
					     <table width="25%"  style="font-family:'Times New Roman','Khmer OS Battambang'; border: 1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1"  >
					           <tr align="center" style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center">
					               <td><?php echo $tr->translate('TOTAL_UNIT_PRICE');?> :</td>
					               <td align="right"><strong>&nbsp;$&nbsp;<?php echo number_format($total_cost,2);?>&nbsp;</strong></td>
					           </tr>
					           <tr align="center" style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center">
					               <td><?php echo $tr->translate('TOTAL_SELL_PRICE');?> :</td>
					               <td align="right"><strong>&nbsp;$&nbsp;<?php echo number_format($total_sell,2);?>&nbsp;</strong></td>
					           </tr>
					     </table>
					</td>
				</tr>
				<?php }?>
				<tr>
					<td colspan="3" width="100%">
						<table width="100%" style="font-family:'Khmer OS Battambang';">
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>		
	</div>
</div>