<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_PURCHASE_ALL')); 
	$frm = $this->form_search;
	$classHideHeight=classHideHeight;
?>	
<meta charset="utf-8">
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_PURCHASE_ALL');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form action="" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("title");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("location");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("supplier_id");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("category_id");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<input id="product" />
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("product_type");?>
        	</div>
        </div>
        <div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("start_date");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("end_date");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("status_search");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button"
						showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
        </div>
	</form>
	 <div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<style>

				.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table { page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:8px;
						width:100%;
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:10px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.content-data  tr.style {
					 
					   white-space: nowrap;
						
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:11px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:0 2px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					.redBold {
						font-weight: 600;
						color: #f80000;
					}
					table.content-data tr td{
						padding: 2px;
					}	
												
			</style>
			<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="15%" align="center">
					</td>
					<td align="center" width="70%">
						<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate('RPT_PURCHASE_ALL');?></span><br>
						<span style="font-size: 12px; "><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search['start_date']));?> &nbsp;<?php echo $tr->translate('TO');?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));}?></span>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
						<table class="content-data" cellpadding="5"​ border="1" >
							<thead>
								<tr class="style"  align="center">
									<td scope="col" rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td scope="col"  rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH");?>&nbsp;</td>
									<td scope="col"  colspan="2">&nbsp;<?php echo $tr->translate("SUPPLIER_INFO");?>&nbsp;</td>
									<td scope="col"  colspan="9">&nbsp;<?php echo $tr->translate("PURCHASE_INFO");?>&nbsp;</td>
								</tr>
								<tr class="style" align="center">
									<td scope="col" >&nbsp;<?php echo $tr->translate('SUPPLIER_NAME');?></td>
									<td scope="col" >&nbsp;<?php echo $tr->translate('PHONE');?></td>
									<td scope="col" >&nbsp;<?php echo $tr->translate('PURCHASE_NO');?></td>
									<td scope="col" >&nbsp;<?php echo $tr->translate('INVOICE_NO');?></td>
									<td scope="col" >&nbsp;<?php echo $tr->translate('PRODUCT_CATEGORY');?>&nbsp;</td>
									<td scope="col" >&nbsp;<?php echo $tr->translate('PRODUCT_NAME');?>&nbsp;</td>
									<td scope="col" >&nbsp;<?php echo $tr->translate('QTY');?>&nbsp;</td>
									<td scope="col" >&nbsp;<?php echo $tr->translate('COST');?>&nbsp;</td>
									<td scope="col" >&nbsp;<?php echo $tr->translate('TOTAL');?>&nbsp;</td>
									<td scope="col" >&nbsp;<?php echo $tr->translate('PURCHASE_DATE');?>&nbsp;</td>
									<td scope="col" >&nbsp;<?php echo $tr->translate('STATUS');?>&nbsp;</td>
							   </tr>
						   </thead>
						<?php $i=0;
						$totalpaid=0;
						$totalQTY=0;
						$totalbalance=0; if(!empty($this->pur_all))foreach ($this->pur_all AS $rs) { $i++; ?>
							<tr class="style hover" align="left" style="<?php if($rs['status']==0){echo'background:#fceeee;';}?>">
							    <td data-label="<?php echo $tr->translate("NUM");?>">&nbsp;<?php echo $i; ?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("BRANCH");?>">&nbsp;<?php echo $rs['brand_name'];?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("SUPPLIER_NAME");?>">&nbsp;<?php echo $rs['sup_name'];?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("PHONE");?>"> &nbsp;<?php echo $rs['tel'];?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("PURCHASE_NO");?>">&nbsp;<strong><?php echo $rs['supplier_no'];?></strong>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("INVOICE_NO");?>">&nbsp;<?php echo $rs['invoice_no'];?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("PRODUCT_CATEGORY");?>">&nbsp;<?php echo $rs['cate_name'];?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>">&nbsp;<?php echo $rs['pro_id'];?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("QTY");?>"><?php echo number_format($rs['qty'],0);?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("COST");?>">&nbsp;$&nbsp;<?php echo $rs['cost'];?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("TOTAL");?>">&nbsp;$&nbsp;<?php echo $rs['amount'];?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("PURCHASE_DATE");?>"><?php echo date("d/m/Y",strtotime($rs['date']));?>&nbsp;</td>
							    <td data-label="<?php echo $tr->translate("STATUS");?>">&nbsp;<?php echo $rs['status_po']; ?>&nbsp;</td>
							 </tr>
							<?php 
								if($rs['status']==1){
									$totalbalance=$totalbalance+$rs['amount'];
									$totalQTY = $totalQTY +$rs['qty'];
								}
							}?>	  
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<?php if(!empty($this->pur_all)){?>
				<tr>
					<td colspan="3" align="right">
					     <table width="25%"  style="font-family:'Times New Roman','Khmer OS Battambang'; border: 1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1"  >
					           <tr align="center" style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;" align="center">
					               <td><?php echo $tr->translate('TOTAL_QTY');?> :</td>
					               <td align="right"><strong>&nbsp;<?php echo number_format($totalQTY,2);?>&nbsp;</strong><?php echo " ".$tr->translate('Items'); ?>&nbsp;</td>
					           </tr>
					           <tr align="center" style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;" align="center">
					               <td><?php echo $tr->translate('TOTAL_AMOUNT');?> :</td>
					               <td align="right"><strong>&nbsp;$&nbsp;<?php echo number_format($totalbalance,2);?>&nbsp;</strong></td>
					           </tr>
					     </table>
					</td>
				</tr>
				<?php }?>
				
				<tr>
					<td colspan="3" width="100%">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
			</table>
		</div>		
	</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	
	require(["dojo/ready"], function(ready){
		ready(function(){
			getProductByCate();
		});
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",   
			required:false,        
			class: 'fullside', 
		}, "product");
	});
	
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
		//if(cate_id>0){
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value',"<?php echo $this->search['product']?>");
				},
				error: function(err) {
				}
			});
		//}
	}
</script>