<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('RPT_PURCHASE')); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->form_search;
?>	
<meta charset="utf-8">
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_PURCHASE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form action="" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("title");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("location");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("supplier_id");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("start_date");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("end_date");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
             	<div class="col-md-7 col-sm-7 col-xs-12">
			    	<select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside" >
						<option value=""><?php echo $tr->translate('STATUS')?></option>
						<option value="1" <?php if ($this->search['status']==1){ echo 'selected=selected';}?>><?php echo $tr->translate('VOID')?></option>
						<option value="2" <?php if ($this->search['status']==2){ echo 'selected=selected';}?>><?php echo $tr->translate('SOME_PAID')?></option>
						<option value="3" <?php if ($this->search['status']==2){ echo 'selected=selected';}?>><?php echo $tr->translate('FULL_PAID')?></option>
					</select>
				</div>
				<div class="col-md-5 col-sm-5 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"
						showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
        	</div>
        </div>
	</form>
 
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
				<tr>
					<td width="15%" align="center">
						<img style="width:60%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"> 
					</td>
					<td align="center" width="70%">
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('CUSTOMER_BRANCH');?></strong><br />
						<strong style="padding-left: 10px;font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('RPT_PURCHASE');?></strong><br>
						<span style="font-weight: bold;font-size: 12px; "><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search['start_date']));?> &nbsp;<?php echo $tr->translate('TO');?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));}?></span>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
					<style>
						table tr th{
							border: 1px solid #000;	
						}
						table {page-break-inside:auto }
						tr{ page-break-inside:avoid; page-break-after:auto; }
						#header {
						  display: table-header-group;
						  page-break-inside:avoid; page-break-after:auto;
						}			
						thead tr rd {
							font-weight: bold;				
						}
					</style>
					<tr>
					<td colspan="3" id="exportExcel">
						<table cellpadding="5"​ style="font-family:'Times New Roman','Khmer OS Battambang';margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<thead>
								<tr style="font-size:12px; height: 16px; background-color: #CCD9FF;line-height: 24px;font-weight: bold;" align="center">
									<td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
									<td colspan="2">&nbsp;<?php echo $tr->translate("SUPPLIER_INFO");?>&nbsp;</td>
									<td colspan="5">&nbsp;<?php echo $tr->translate("PURCHASE_INFO");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("USER");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("PRINT");?>&nbsp;</td>
								</tr>
								<tr style="font-size:12px; height: 16px; background-color: #CCD9FF;line-height: 24px;font-weight: bold;" align="center">
										<td>&nbsp;<?php echo $tr->translate('SUPPLIER_NAME');?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate('PHONE');?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate('PURCHASE_NO');?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate('TOTAL_AMOUNT');?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate('DATE');?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate('STATUS');?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate('REMAIN');?>&nbsp;</td>
							   </tr>
							</thead>
						<?php $i=0;$totalpaid=0;
						$totalremain =0;
						$totalbalance=0; if(!empty($this->pur_code))foreach ($this->pur_code AS $rs) { $i++;
						       
						  ?>
							<tr class="hover" style="font-size:11px; line-height:16px; "​ align="center">
								<td>&nbsp;<?php echo $i; ?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs['branch_name'];?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs['sup_name'];?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs['tel'];?>&nbsp;</td>
								<td >&nbsp;
								   	<a target="_blank" style="text-decoration: none;color:#000;" href="<?php echo $this->baseUrl();?>/allreport/stock/rpt-purchase-supplier/id/<?php echo $rs['id'];?>">
								     		<strong><?php echo $rs['supplier_no'];?></strong>
								   	</a>&nbsp;
								</td>
								   
								<td align="right">&nbsp;$&nbsp;<?php echo number_format($rs['amount_due'],2);?>&nbsp;</td>
								<td>&nbsp;<?php echo date("d/m/Y",strtotime($rs['date']));?>&nbsp;</td>
								<td>&nbsp;<?php if($rs['status']==0){ echo $tr->translate('VOID');}else if($rs['amount_due']>$rs['amount_due_after'] AND $rs['amount_due_after']>0){ echo $tr->translate('SOME_PAID'); }else if($rs['is_paid']==1){ echo $tr->translate('FULL_PAID');}else{ echo "-";} ?>&nbsp;</td>
								<td align="right">&nbsp;$&nbsp;<?php echo number_format($rs['amount_due_after'],2); ?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs['user_name']; ?>&nbsp;</td>
								<td>&nbsp;
									<a target="_blank" style="text-decoration: none;color:#000;" href="<?php echo $this->baseUrl();?>/allreport/stock/rpt-purchase-supplier/id/<?php echo $rs['id'];?>"><?php echo $tr->translate('PRINT');?></a>
									&nbsp;
								</td>
							 </tr>
						  
							<?php 
								$totalbalance=$totalbalance+$rs['amount_due'];
								$totalremain = $totalremain+$rs['amount_due_after'];
							}?>	 
							
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<?php if(!empty($this->pur_code)){?>
				<tr>
					<td colspan="3" align="right">
					     <table width="25%"  style="font-family:'Times New Roman','Khmer OS Battambang'; border: 1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1"  >
					           <tr align="center" style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center">
					               <td><?php echo $tr->translate('TOTAL_AMOUNT');?> :</td>
					               <td align="right"><strong>&nbsp;$&nbsp;<?php echo number_format($totalbalance,2);?>&nbsp;</strong></td>
					           </tr>
					           <tr align="center" style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center">
					               <td><?php echo $tr->translate('Total Remain');?> :</td>
					               <td align="right"><strong>&nbsp;$&nbsp;<?php echo number_format($totalremain,2);?>&nbsp;</strong></td>
					           </tr>
					     </table>
					</td>
				</tr>
				<?php }?>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" width="100%">
						<table width="100%" style="font-family:'Khmer OS Battambang';">
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>		
	</div>
</div>





