<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RPT_BYPRODUCT_SOLD")); 
	$frm =  $this->form_search;
	$classHideHeight=classHideHeight;
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,

</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>	
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_BYPRODUCT_SOLD');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
			<div class="col-md-3 col-sm-3 col-xs-12">
          		<?php echo $frm->getElement("title");?>
    	    </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
           		<?php echo $frm->getElement("branch_id");?>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
           		<?php echo $frm->getElement("category_id");?>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
           		<input id="product" />
            </div>
         </div>
         <div class="form-group">
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php echo $frm->getElement("start_date");?>
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php echo $frm->getElement("end_date");?>
			</div>
			<div class="col-md-3 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("user");?>
        	</div>
			 <div class="col-md-3 col-sm-3 col-xs-12">
            		<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			    	<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
             </div>
		</div>
	</form>
	<style>
		.hover:hover{background: #ddd;}
	</style>
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<style>
					.style{
						line-height: 20px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					
					tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; 
					  page-break-after:auto;
					}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:10px;
						width:100%;
					}
					table.content-data thead tr.style {
					   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.content-data  tr.style {
					   white-space: nowrap;
					}
					table.content-data tr td{
						padding: 1px;
					}
					
					.small{white-space:normal;width:200px;}
					.wrapcontent{width:350px;white-space: normal;}	
					td.hideborder{border-left: 1px solid #fff;border-bottom: 1px solid #fff;}
					@media print{
						@page{
							margin:0.5cm;
							page-break-before: avoid;
							-webkit-transform: scale(0.5);  /* Chrome, Safari 3.1+  */
							-moz-transform: scale(0.5);  /* Firefox 3.5-15 */
							-ms-transform: scale(0.5);   /* IE 9 */
							-o-transform: scale(0.5);    /* Opera 10.50-12.00 */
							transform: scale(0.5);
							size:A4 Portrait;
						}
					}
			</style>
			<table style="background:#fff;margin: 0 auto;white-space: nowrap;width: 100%;font-family:'Times New Roman','Khmer OS Battambang'">
				
				<tr>
					<td colspan="3" id="exportExcel">
						<table width="100%">
						<tr>
							<td colspan="3"><?php echo $this->rsheader;?></td>
						</tr>
						<tr>
							<td width="15%" align="right">&nbsp;</td>
							<td align="center"  width="70%">
								<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate("RPT_BYPRODUCT_SOLD"); ?></span><br />
								<span style="font-size: 12px;"><?php if(!empty($this->search['start_date'])){?>&nbsp;<?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> <?php echo $tr->translate("TO"); ?> <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></span>
							</td>
							<td width="15%" align="right">&nbsp;</td>
						</tr>
						</table>
						<table class="content-data" cellpadding="0"​  border="1" >
							<thead>
							<tr class="style" align="center">
									<td scope="col" rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td scope="col" rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH");?>&nbsp;</td>
									<td scope="col" colspan="3">&nbsp;<?php echo $tr->translate("PRODUCT_INFO");?>&nbsp;</td>
									<td scope="col" colspan="5">&nbsp;<?php echo $tr->translate("SALE_INFO");?>&nbsp;</td>
								</tr>
							<tr class="style" align="center">
								<td scope="col">&nbsp;<?php echo $tr->translate("CATEGORY");?>&nbsp;</td>
								<td scope="col">&nbsp;<?php echo $tr->translate("PRODUCT_CODE");?>&nbsp;</td>
							    <td scope="col">&nbsp;<?php echo $tr->translate("PRODUCT_NAME");?>&nbsp;</td>
							    <td scope="col">&nbsp;<?php echo $tr->translate("QTY");?>&nbsp;</td>
							    <td scope="col">&nbsp;<?php echo $tr->translate("TOTAL_SALE");?>&nbsp;</td>
								<td scope="col">&nbsp;<?php echo $tr->translate("TOTAL_COST");?>&nbsp;</td>
								<td scope="col">&nbsp;<?php echo $tr->translate("TOTAL_PROFIT");?>&nbsp;</td>
							</tr>
							</thead>
						<?php 
						$total_qty=0;
						$grand_totalsale=0;
						$grand_totalcost=0;
						 if (!empty($this->rspro)) foreach ($this->rspro as $key=> $rs){?>
							<tr class="style hover" align="center">
								<td data-label="<?php echo $tr->translate("NUM");?>">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("BRANCH");?>" align="left">&nbsp;<?php echo $rs['branch_name'];?>&nbsp;</td>
								<td class="small" data-label="<?php echo $tr->translate("CATEGORY");?>" align="left">&nbsp;<?php echo $rs['category'];?>&nbsp;</td>
								<td class="small" align="left" data-label="<?php echo $tr->translate("PRODUCT_CODE");?>">&nbsp;<?php echo $rs['code'];?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" align="left" class="wrapcontent">&nbsp;<?php echo $rs['items_name'];?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("QTY");?>">&nbsp;<?php echo number_format($rs['qty'],2);?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("TOTAL_SALE");?>">&nbsp;<?php echo number_format($rs['subtotalsale'],2);?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("TOTAL_COST");?>"> &nbsp;<?php echo number_format($rs['subtotalcost'],2);?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("TOTAL_PROFIT");?>"> &nbsp;<?php echo number_format($rs['subtotalsale']-$rs['subtotalcost'],2);?>&nbsp;</td>
							</tr>
						<?php
						$total_qty = $total_qty + $rs['qty'];
						$grand_totalsale = $grand_totalsale + $rs['subtotalsale'];
						$grand_totalcost = $grand_totalcost + $rs['subtotalcost'];
						}?>
	 						<tr style="font-size:12px; height: 20px;border: 1px solid #000;" align="center" class="hover" >
								<td colspan="5" align="right" class="hideborder"><?php echo $tr->translate("TOTLE_AMOUNT");?></td>
								<td><strong><?php echo number_format($total_qty,2);?></strong></td>
								<td><strong><?php echo "$ ".number_format($grand_totalsale,2);?></strong></td>
								<td><strong><?php echo "$ ".number_format($grand_totalcost,2);?></strong></td>
								<td align="center" style="border: 1px solid #000;"><strong><?php echo "$ ".number_format($grand_totalsale-$grand_totalcost,2);?></strong></td>
	 						</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
			</table>
		</div>		
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	
	require(["dojo/ready"], function(ready){
		ready(function(){
			getProductByCate();
		});
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",  
			placeholder:'<?php echo $tr->translate("SELECT_PRODUCT");?>', 
			required:false,        
			class: 'fullside', 
		}, "product");
	});
	
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value',"<?php echo $this->search['product']?>");
				},
				error: function(err) {
				}
			});
	}
</script>