<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('RPT_STATISTIC_PRODUCT_SOLD')); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_STATISTIC_PRODUCT_SOLD');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
			<div class="col-md-2 col-sm-2 col-xs-12">
          		<?php echo $frm->getElement("advance_search");?>
    	    </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
           		<?php echo $frm->getElement("branch_search");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
           		<?php echo $frm->getElement("items_search");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
           		<input id="pro_id" />
            </div>
         </div>
         <div class="form-group">
			<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement("start_date");?>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement("end_date");?>
			</div>
			 <div class="col-md-2 col-sm-2 col-xs-12">
            		<button IconClass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			    	<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
             </div>
		</div>
	</form>
	<style>
		.hover:hover{background: #ddd;}
	</style>
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
				<tr>
					<td width="15%" align="center"><img style="width:60%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /></td>
					<td align="center"  width="70%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2'; "><?php echo $tr->translate("CUSTOMER_BRANCH"); ?></strong><br />
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2'; "><?php echo $tr->translate("RPT_STATISTIC_PRODUCT_SOLD"); ?></strong><br />
						<strong style="font-weight:bold;font-family: 'Times New Roman','Khmer MEF2';color:#000; font-size: 13px;"><?php if(!empty($this->search['start_date'])){?>&nbsp;<?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> ដល់ <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></strong>
					</td>
					<td width="15%" align="right">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
						<table cellpadding="5"​ style="font-family:'Times New Roman','Khmer OS Battambang'; border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<tr style="font-size:12px; height: 16px; background-color: #CCD9FF;line-height: 24px;font-weight: bold;" align="center">
									<td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
									<td colspan="2">&nbsp;<?php echo $tr->translate("PRODUCT_INFO");?>&nbsp;</td>
									<td colspan="4">&nbsp;<?php echo $tr->translate("SALE_INFO");?>&nbsp;</td>
								</tr>
							<tr style="font-size:12px; height: 16px; background-color: #CCD9FF;line-height: 24px;font-weight: bold;" align="center">
								<td>&nbsp;<?php echo $tr->translate("PRODUCT_CODE");?>&nbsp;</td>
							    <td>&nbsp;<?php echo $tr->translate("PRODUCT_NAME");?>&nbsp;</td>
							    <td>&nbsp;<?php echo $tr->translate("RECEIPT");?>&nbsp;</td>
							    <td>&nbsp;<?php echo $tr->translate("PRICE");?>&nbsp;</td>
							    <td>&nbsp;<?php echo $tr->translate("QTY");?>&nbsp;</td>
							    <td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
							</tr>
						<?php $grand_total=0; if (!empty($this->rspro)) foreach ($this->rspro as $key=> $rs){?>
							<tr class="hover" style="font-size:11px; line-height:16px; "​ align="center">
								<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
								<td align="left">&nbsp;<?php echo $rs['branch_name'];?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs['code'];?>&nbsp;</td>
								<td align="left">&nbsp;<?php echo $rs['items_name'];?>&nbsp;</td>
								<td>&nbsp;<strong><?php echo $rs['receipt_number'];?></strong>&nbsp;</td>
								<td>&nbsp;<?php echo $rs['fee'];?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs['qty'];?>&nbsp;</td>
								<td>&nbsp;<?php echo number_format($rs['subtotal'],2);?>&nbsp;</td>
							</tr>
						<?php 
						$grand_total = $grand_total + $rs['subtotal'];
						}?>
	 						<tr style="font-size:13px; height: 20px;border: 1px solid #000;font-weight: bold;" align="center" class="hover" >
								<td colspan="7" ><?php echo $tr->translate("TOTLE_AMOUNT");?></td>
								<td align="center" style="border: 1px solid #000;font-weight: bolder;">&nbsp;<?php echo "$ ".number_format($grand_total,2);?></td>
	 						</tr>
						</table>
					</td>
				</tr>
			</table>
			<table style="background:#fff;width:90%;margin:0 auto;white-space: nowrap;width:100%;font-family:Khmer OS Battambang,Times New Roman;">
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td align="center" width="25%">
						<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
					</td>
					<td  width="50%">&nbsp;</td>
					<td align="center"  width="25%">
						<span style=" font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
					</td>
				</tr>
			</table>
		</div>		
	</div>
</div>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	var pro_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->product));?> );
	dojo.ready(function(){ 
		new dijit.form.FilteringSelect({
			store: pro_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                        
			id: "pro_id",
			name: "pro_id",  
			class: 'fullside',  
			required:false,
			placeHolder:"<?php echo $tr->translate("SELECT_PRODUCT");?>",          
			onChange: function() {  
			}
		}, "pro_id");
		 var items_search = dijit.byId('items_search');
		 items_search.on('change', function(evt) {
			 getAllProductByBranch();
	    });
		 getAllProductByBranch();
	});	
	url_getacademic= '<?php echo $this->url(array('module'=>'stock','controller'=>'product','action'=>'getproductbyacate'));?>';
	var oldcate = '<?php echo $this->search['items_search']?>';
	function getAllProductByBranch(){
		dijit.byId('pro_id').reset();
		items_search = dijit.byId('items_search').get('value');
		if(items_search=='' || items_search==-1){
			var pro_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->product));?> );
			dijit.byId('pro_id').set('store',pro_store);  
			dijit.byId('items_search').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getacademic,
			content:{
				'category':items_search
				},
			handleAs:"json",
			load: function(data) {
				pro_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('pro_id').set('store',pro_store); 
			    if(oldcate==items_search) {
			    	dijit.byId('pro_id').set('value','<?php echo $this->search['pro_id']?>'); 
			    }
			},
			error: function(err) {
				alert(err);
			}
		});
	}
</script>