<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RPT_BYPRODUCT_SOLD")); 
	$frm =  $this->form_search;
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>	
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_BYPRODUCT_SOLD');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
			<div class="col-md-3 col-sm-3 col-xs-12">
          		<?php echo $frm->getElement("title");?>
    	    </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
           		<?php echo $frm->getElement("branch_id");?>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
           		<?php echo $frm->getElement("category_id");?>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
           		<input id="product" />
            </div>
         </div>
         <div class="form-group">
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php echo $frm->getElement("start_date");?>
			</div>
			<div class="col-md-3 col-sm-3 col-xs-12">
				<?php echo $frm->getElement("end_date");?>
			</div>
			<div class="col-md-3 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("user");?>
        	</div>
			 <div class="col-md-3 col-sm-3 col-xs-12">
            		<button IconClass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			    	<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
             </div>
		</div>
	</form>
	<style>
		.hover:hover{background: #ddd;}
	</style>
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<style>
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table { page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:8px;
						width:100%;
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:10px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.content-data  tr.style {
					 
					   white-space: nowrap;
						
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:11px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:0 2px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					.redBold {
						font-weight: 600;
						color: #f80000;
					}
					table.content-data tr td{
						padding: 2px;
					}	
			</style>
			<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;font-family:'Times New Roman','Khmer OS Battambang'">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="15%" align="right">&nbsp;</td>
					<td align="center"  width="70%">
						<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate("RPT_BYPRODUCT_SOLD"); ?></span><br />
						<span style="font-size: 12px;"><?php if(!empty($this->search['start_date'])){?>&nbsp;<?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> <?php echo $tr->translate("TO"); ?> <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></span>
					</td>
					<td width="15%" align="right">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
						<table class="content-data" cellpadding="5"​  border="1" >
							<thead>
							<tr class="style" align="center">
									<td scope="col" rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td scope="col" rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH");?>&nbsp;</td>
									<td scope="col" colspan="3">&nbsp;<?php echo $tr->translate("PRODUCT_INFO");?>&nbsp;</td>
									<td scope="col" colspan="3">&nbsp;<?php echo $tr->translate("SALE_INFO");?>&nbsp;</td>
								</tr>
							<tr class="style" align="center">
								<td scope="col">&nbsp;<?php echo $tr->translate("CATEGORY");?>&nbsp;</td>
								<td scope="col">&nbsp;<?php echo $tr->translate("PRODUCT_CODE");?>&nbsp;</td>
							    <td scope="col">&nbsp;<?php echo $tr->translate("PRODUCT_NAME");?>&nbsp;</td>
							    <!-- <td>&nbsp;<?php //echo $tr->translate("RECEIPT");?>&nbsp;</td> -->
							    <td scope="col">&nbsp;<?php echo $tr->translate("PRICE");?>&nbsp;</td>
							    <td scope="col">&nbsp;<?php echo $tr->translate("QTY");?>&nbsp;</td>
							    <td scope="col">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
							</tr>
							</thead>
						<?php $grand_total=0; if (!empty($this->rspro)) foreach ($this->rspro as $key=> $rs){?>
							<tr class="style hover" align="center">
								<td data-label="<?php echo $tr->translate("NUM");?>">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("BRANCH");?>" align="left">&nbsp;<?php echo $rs['branch_name'];?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("CATEGORY");?>" align="center">&nbsp;<?php echo $rs['category'];?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("PRODUCT_CODE");?>">&nbsp;<?php echo $rs['code'];?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" align="left">&nbsp;<?php echo $rs['items_name'];?>&nbsp;</td>
								<!-- <td>&nbsp;<strong><?php //echo $rs['receipt_number'];?></strong>&nbsp;</td> -->
								<td data-label="<?php echo $tr->translate("PRICE");?>">&nbsp;<?php echo $rs['fee'];?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("QTY");?>">&nbsp;<?php echo $rs['qty'];?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("TOTAL");?>"> &nbsp;<?php echo number_format($rs['subtotal'],2);?>&nbsp;</td>
							</tr>
						<?php 
						$grand_total = $grand_total + $rs['subtotal'];
						}?>
	 						<tr style="font-size:13px; height: 20px;border: 1px solid #000;" align="center" class="hover" >
								<td colspan="7" ><?php echo $tr->translate("TOTLE_AMOUNT");?></td>
								<td align="center" style="border: 1px solid #000;"><strong><?php echo "$ ".number_format($grand_total,2);?></strong></td>
	 						</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
			</table>
		</div>		
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	
	require(["dojo/ready"], function(ready){
		ready(function(){
			getProductByCate();
		});
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",   
			required:false,        
			class: 'fullside', 
		}, "product");
	});
	
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
		//if(cate_id>0){
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value',"<?php echo $this->search['product']?>");
				},
				error: function(err) {
				}
			});
		//}
	}
</script>