<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("PLACEMENT_TEST"));
$_dbgb= new Application_Model_DbTable_DbGlobal();
$_dbpl= new Application_Model_DbTable_DbPlacementTest();
$startTime  = date("Y-m-d H:i:s",strtotime($this->exam['start'])); //"2019-10-01 15:52:12";
$duration = empty($this->exam['duration'])?1:number_format($this->exam['duration'],0);
$endTiem = date("Y-m-d H:i:s",strtotime("+$duration min $startTime"));

$placemnet_id = $this->exam_id; 
$truefalseList=$_dbgb->getOptionTrueFalse(1,1);
?>

        	<div class="col-md-3 left_col ">
          		<div class="left_col scroll-view">
		            <div class="navbar nav_title">
		            </div>
            		<div class="clearfix"></div>
            		
            		<div class="left-content">
            			<div class="blog-duration">
            				<div class="title-label">
		            			<h2><i class="fa fa-clock-o" aria-hidden="true"></i> <?php echo $tr->translate("រយៈពេលប្រឡង");?></h2>
		            		</div>
		            		<div class="test-min">
		            			<span id="hours" class="min">60</span>
		            			<span id="minutes" class="min">60</span>
		            			<span id="seconds" class="min">00</span>
		            		</div>
            			</div>
            			<div class="blog-score">
            				<div class="title-label">
		            			<h2><i class="fa fa-trophy" aria-hidden="true"></i> <?php echo $tr->translate("លទ្ធផល");?></h2>
		            		</div>
		            		<div class="test-score">
		            			<ul>
		            				<li><span class="lb-title"><?php echo $tr->translate("ពិន្ទុ");?></span> : <span class="lb-value">10/10</span></li>
		            				<li><span class="lb-title"><?php echo $tr->translate("សំនួរសរុប");?></span> : <span class="lb-value">20</span></li>
		            				<li><span class="lb-title"><?php echo $tr->translate("ត្រឹមត្រូវ");?></span> : <span class="lb-value">15</span></li>
		            				<li><span class="lb-title"><?php echo $tr->translate("មិនត្រឹមត្រូវ");?></span> : <span class="lb-value">2</span></li>
		            				<li><span class="lb-title"><?php echo $tr->translate("មិនបានឆ្លើយ");?></span> : <span class="lb-value">3</span></li>
		            			</ul>
		            		</div>
            			</div>
	            	</div>
            	</div>
            	
            </div>
           
            <!-- page content -->
       		<div class="right_col" role="main" >
       		 	<div class="right-conten" style="min-height: 570px;">
       		 		<div style="clear:both;"></div>
       		 		<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
       		 			<section class="inputmask">
							<div class="row">
						    	<div class="col-sm-12">
						    		<div class="reportblog">
						    			<div class="header-row">
						    				<?php echo $this->rsheader;?>
						    			</div>
						    			<div class="content exam-test-data">
						    				<div class="title-examination text-center">
						    					<?php if (!empty($this->setting)){?>
						    					<h2><?php echo $this->setting['test_type_title'];?></h2>
						    					<?php }?>
						    				</div>
						    				<?php 
						    				$parent=0;
						    				$section=0;
						    				$number=0;
						    				if (!empty($this->question)) foreach ($this->question as $key => $rs){ ?>
						    					<?php if ($parent!=$rs['parent']){ if (!empty($rs['parent_title'])){?>
							    					<div class="section-exam">
							    						<div class="section-exam-title">
								    						<h2><?php echo $rs['parent_title'];?></h2>
								    						<?php if (!empty($rs['parent_instruction'])){?>
								    						<small>Instruction: <?php echo $rs['parent_instruction'];?></small>
								    						<?php }?>
								    					</div>
							    					</div>
							    					<?php }
						    						}?>
						    						<?php if ($section!=$rs['section_id']){ $number=0; ?>
						    						<div class="section-exam">
							    						<div class="section-exam-title <?php if (!empty($rs['parent'])){ echo "sub-section";}?>">
								    						<h2><?php echo $rs['section_title'];?></h2>
								    						<?php if (!empty($rs['instruction'])){?>
								    						<small>Instruction: <?php echo $rs['instruction'];?></small>
								    						<?php }?>
								    					</div>
							    					</div>
						    						<?php }?>
						    						<?php 
						    						$number++;
						    						?>
						    						
						    						
						    						<?php 
						    						$question_type = $rs['question_type'];
						    						//Question Block
						    						if ($question_type==1){ 
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							$question_id = $rs['id'];
						    							if (!empty($rowQ)){
						    							?>
						    							<div class="section-exam-question">
								    						<ul>
								    							<li>
								    								<div class="answer-blog">
								    									<ul>
											    							<?php foreach ($rowQ as $index => $question){ $keyIndex = $index+1;?>
											    							<li class="answer-opt col5">
												    							<?php if (!empty($question['answer_label'])){?>
												    								<span class="question-num"><?php echo $keyIndex?>.</span> <?php echo $question['answer_label'];?>
												    							<?php }else{
												    								$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
												    							?>
												    							
												    							<div class="row-data">
													    							<span class="question-num"><?php echo $keyIndex?>.</span>
													    							<div class="fill-in">
														    							<input class="full-width" type="text" onChange="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id."_".$question['id'];?>" name="answere_<?php echo $question_id."_".$question['id'];?>" dojoType="dijit.form.TextBox" placeholder="<?php echo $tr->translate("Enter Answer");?>" value="<?php if (!empty($result)){ echo $result['answer_key']; }?>" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"  >
													    							</div>
												    							</div>
												    							<?php }?>
											    							</li>
											    							<?php }?>
										    								
						    											</ul>
						    										</div>
						    									</li>
						    								</ul>
						    							</div>
						    							<?php }?>
						    						<?php }else if ($question_type==2){ 
						    							$image = $this->baseUrl().'/images/no-photo.png';
						    							if (!empty($rs['images'])){
						    								if (file_exists(PUBLIC_PATH."/images/placement/".$rs['images'])){
						    									$image = $this->baseUrl()."/images/placement/".$rs['images'];
						    								}
						    							}
						    							?>
						    							<?php 
						    							$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    									<div class="image-question answer-opt col4">
								    								<span class="question-num"><?php echo $number?>.</span>
								    								<img class="img-question" src="<?php echo $image;?>" />
								    								<ul>
								    									<?php foreach ($rowQ as $index => $question){ $keyIndex = $index+1;
								    									$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
								    									?>
							    										<li>
							    											<input type="radio" <?php if (!empty($result)){ echo 'checked="checked"';}?> onClick="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id;?>" name="answere_<?php echo $question_id; ?>" value="<?php echo $question['answer_label'];?>"> <span class="question-num"><?php echo $index+1?>.</span> <?php echo $question['answer_label'];?>
							    										</li>
							    										<?php }?>
								    								</ul>
								    							</div>
						    							<?php }?>
						    							
						    						<?php }else if ($question_type==3){
						    							$image = $this->baseUrl().'/images/no-photo.png';
						    							if (!empty($rs['images'])){
						    								if (file_exists(PUBLIC_PATH."/images/placement/".$rs['images'])){
						    									$image = $this->baseUrl()."/images/placement/".$rs['images'];
						    								}
						    							}
						    							?>	
						    							<?php 
						    							$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    								<div class="image-question answer-opt col2">
								    								<div class="two-blog ans-left">
								    									<span class="question-num"><?php echo $number?>.</span>
									    								<img class="img-question" src="<?php echo $image;?>" />
									    								<span><?php echo $rs['question_title'];?></span>
								    								</div>
								    								<div class="two-blog ans-right">
								    									<ul>
									    									<?php foreach ($rowQ as $index => $question){ $keyIndex = $index+1;
									    									$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
									    									?>
								    										<li>
								    											<input type="radio" <?php if (!empty($result)){ echo 'checked="checked"';}?> onClick="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id; ?>" name="answere_<?php echo $question_id; ?>" value="<?php echo $question['answer_label'];?>"> <span class="question-num"><?php echo $keyIndex;?>.</span> <?php echo $question['answer_label'];?>
								    										</li>
								    										<?php }?>
									    								</ul>
								    								</div>
								    								
								    							</div>
						    							<?php }?>
						    						<?php }else if ($question_type==4){?>
						    							
						    							<?php 
						    							$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question ">
								    						<ul>
								    							<li>
								    								<div class="answer-blog">
								    									<ul>
											    							<?php foreach ($rowQ as $index => $question){ $keyIndex = $index+1;
											    								$image = $this->baseUrl().'/images/no-photo.png';
											    								if (!empty($question['image'])){
											    									if (file_exists(PUBLIC_PATH."/images/placement/".$question['image'])){
											    										$image = $this->baseUrl()."/images/placement/".$question['image'];
											    									}
											    								}
											    								$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
											    							?>
											    							<li class="answer-opt col4">
											    								
											    								<div class="image-class">
											    									<img class="img-question" src="<?php echo $image;?>" />
											    								</div>
											    								<div class="row-data">
													    							<span class="question-num"><?php echo $keyIndex;?>.</span>
													    							<div class="fill-in">
														    							<input class="full-width" type="text" onChange="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id."_".$question['id']; ?>" name="answere_<?php echo $question_id."_".$question['id']; ?>" dojoType="dijit.form.TextBox" placeholder="<?php echo $tr->translate("Enter Answer");?>" value="<?php if (!empty($result)){ echo $result['answer_key']; }?>" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"  >
													    							</div>
												    							</div>
											    							</li>
											    							<?php }?>
										    								
						    											</ul>
						    										</div>
						    									</li>
						    								</ul>
						    							</div>
						    							<?php }?>
						    							
						    						<?php }else if ($question_type==5){?>
						    							<?php 
						    							$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question two-blog">
								    						<ul>
								    							<li>
								    								<div class="text-center">
								    									<?php echo $rs['question_title'];?>
								    								</div>
								    								<div class="answer-blog">
								    									<ul>
											    							<?php foreach ($rowQ as $index => $question){ $keyIndex = $index+1;?>
											    							<li class="answer-opt col1">
												    							<?php if (!empty($question['answer_label'])){?>
												    								<span class="question-num"><?php echo $keyIndex;?>.</span> <?php echo $question['answer_label'];?>
												    							<?php }else{
												    								$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
												    							?>
												    							
												    							<div class="row-data">
													    							<span class="question-num"><?php echo $keyIndex;?>.</span>
													    							<div class="fill-in">
														    							<input class="full-width" type="text" onChange="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id."_".$question['id']; ?>" name="answere_<?php echo $question_id."_".$question['id'];?>" dojoType="dijit.form.TextBox" placeholder="<?php echo $tr->translate("Enter Answer");?>" value="<?php if (!empty($result)){ echo $result['answer_key']; }?>" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" >
													    							</div>
												    							</div>
												    							<?php }?>
											    							</li>
											    							<?php }?>
										    								
						    											</ul>
						    										</div>
						    									</li>
						    								</ul>
						    							</div>
						    							<?php }?>
						    								
						    						<?php }else if ($question_type==6){?>
						    						
						    							<?php 
						    							$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question ">
								    						<ul>
								    							<li>
								    								<div class="answer-blog">
								    									<div class="two-blog">
									    									<div class="text-center">
										    									A
										    								</div>
									    									<ul>
												    							<?php $tdHead=""; 
												    							$options= '<option value="" >'.htmlspecialchars($tr->translate("SELECT_ANSWER"), ENT_QUOTES).'</option>';
												    							foreach ($rowQ as $index => $question){ 
												    								$colB = $question['column_b'];
												    								$options .= '<option value="'.$colB.'" >'.htmlspecialchars($colB, ENT_QUOTES).'</option>';
												    								$tdHead.='<td align="center">'.($index+1).'</td>';
												    								?>
												    							<li class="answer-opt col1">
												    								<span class="question-num"><?php echo $index+1;?>.</span> <?php echo $question['answer_label'];?>
												    							</li>
												    							<?php }?>
											    								
							    											</ul>
								    									</div>
								    									<div class="two-blog">
									    									<div class="text-center">
										    									B
										    								</div>
									    									<ul>
												    							<?php 
												    							$script='';
												    							$tdAnswer="";
												    							foreach ($rowQ as $index => $question){ $keyIndex = $index+1;
												    							
												    								$tdAnswer.='<td><select onChange="enterAnswer('."'".$question_type."'".','."'".$question_id."'".','."'".$question['id']."'".');" id="answere_'.$question_id."_".$question['id'].'" name="answere_'.$question_id."_".$question['id'].'" class="option-answer full-width" dojoType="dijit.form.FilteringSelect">';
												    								
												    								$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
												    								if (!empty($result)){
												    									$opti= '<option value="" >'.htmlspecialchars($tr->translate("SELECT_ANSWER"), ENT_QUOTES).'</option>';
													    								foreach ($rowQ as $index => $quest){
												    										$selected = '';
												    										if ($quest['column_b']==$result['answer_key']){
												    											$selected = 'selected="selected"';
												    										}
												    										$colB = $quest['column_b'];
												    										$opti.= '<option '.$selected.' value="'.$colB.'" >'.htmlspecialchars($colB, ENT_QUOTES).'</option>';
												    									}
												    									$tdAnswer.=$opti;
												    								}else{
												    									$tdAnswer.=$options;
												    								}
												    								
												    								
												    								$tdAnswer.='</select></td>';
												    								
												    								
												    							?>
												    							<li class="answer-opt col1">
												    								<?php echo $question['column_b'];?>
												    							</li>
												    							<?php }?>
							    											</ul>
								    									</div>
								    									<table class="table_answer" border="1">
								    										<tr>
								    											<?php echo $tdHead;?>
								    										</tr>
								    										<tr>
								    											<?php echo $tdAnswer;?>
								    										</tr>
								    									</table>
						    										</div>
						    									</li>
						    								</ul>
						    							</div>
						    							<?php }?>
						    							
						    						<?php }else if ($question_type==7){?>
						    						
						    						<?php 
						    						
							    						$image = $this->baseUrl().'/images/no-photo.png';
							    						if (!empty($rs['images'])){
							    							if (file_exists(PUBLIC_PATH."/images/placement/".$rs['images'])){
							    								$image = $this->baseUrl()."/images/placement/".$rs['images'];
							    							}
							    						}
							    						$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							$optAnswer = $_dbgb->getGetAnswerKeyById($rs['section_id'],$rs['question_type'],1);
						    							$answerList = $_dbgb->getGetAnswerKeyById($rs['section_id'],$rs['question_type']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question ">
								    						<ul>
								    							<li>
								    								<div class="answer-blog">
								    									<ul>
								    										<li class="answer-opt col1">
												    							<div class="row-data">
												    								<span class="question-num"><?php echo $number?>.</span>
												    								<img class="img-question" src="<?php echo $image;?>" />
											    									<?php foreach ($rowQ as $index => $question){ $keyIndex = $index+1;?>
													    								
													    								<span class="inline-value">
													    								<?php 
													    									echo $question['answer_label'];
													    								?>
													    								</span>
													    								<span class="inline-value ">
													    									<select class="option-answer full-width" onChange="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id."_".$question['id']; ?>" name="answere_<?php echo $question_id."_".$question['id']; ?>" dojoType="dijit.form.FilteringSelect" >
													    									<?php 
													    									
													    									$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
													    									if (!empty($result)){
													    										$opti= '<option value="" >'.htmlspecialchars($tr->translate("SELECT_ANSWER"), ENT_QUOTES).'</option>';
													    										foreach ($answerList as $quest){
													    											$selected = '';
													    											if ($quest['answer_key']==$result['answer_key']){
													    												$selected = 'selected="selected"';
													    											}
													    											$colB = $quest['answer_key'];
													    											$opti.= '<option '.$selected.' value="'.$quest['answer_key'].'" >'.htmlspecialchars($colB, ENT_QUOTES).'</option>';
													    										}
													    										echo $opti;
													    									}else{
													    										echo $optAnswer;
													    									}
													    									
													    									?>
													    									</select>
													    								</span>
											    								<?php }?>
										    									</div>
											    							</li>
						    											</ul>
						    										</div>
								    							</li>
								    						</ul>
								    					</div>
								    					<?php }?>
								    					
						    						<?php }else if ($question_type==8){?>
						    						
						    						<?php 
						    							$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							$optAnswer = $_dbgb->getGetAnswerKeyById($rs['section_id'],$rs['question_type'],1);
						    							$answerList = $_dbgb->getGetAnswerKeyById($rs['section_id'],$rs['question_type']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question ">
								    						<ul>
								    							<li>
								    								<div class="answer-blog">
								    									<?php if ($number==1){?>
								    									<div style="text-align: center;margin: 20px 0;">
									    									<table class="table_answer" border="1" style="width: 60%;margin: 0 auto;">
									    										<tr>
									    											<td align="center">
									    											<?php if (!empty($answerList)) foreach ($answerList as $rr){ echo "<span class='value-list'>".$rr['answer_key']."<span>"; }?>
									    											</td>
									    										</tr>
									    									</table>
								    									</div>
								    									<?php }?>
								    									<ul>
								    										<li class="answer-opt col1">
								    											<span class="inline-value ">
								    											<span class="question-num"><?php echo $number?>.</span>
								    											</span>
											    									<?php foreach ($rowQ as $index => $question){ $keyIndex = $index+1; ?>
													    								<?php if (empty($question['answer_label'])){?>
													    								<span class="inline-value ">
														    								<select class="option-answer full-width" onChange="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id."_".$question['id']; ?>" name="answere_<?php echo $question_id."_".$question['id']?>" dojoType="dijit.form.FilteringSelect" >
														    								<?php $result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
													    									if (!empty($result)){
													    										$opti= '<option value="" >'.htmlspecialchars($tr->translate("SELECT_ANSWER"), ENT_QUOTES).'</option>';
													    										foreach ($answerList as $quest){
													    											$selected = '';
													    											if ($quest['answer_key']==$result['answer_key']){
													    												$selected = 'selected="selected"';
													    											}
													    											$colB = $quest['answer_key'];
													    											$opti.= '<option '.$selected.' value="'.$quest['answer_key'].'" >'.htmlspecialchars($colB, ENT_QUOTES).'</option>';
													    										}
													    										echo $opti;
						    																}else{
						    																	echo $optAnswer;
						    																}?>
														    								</select>
													    								</span>
													    								<?php }else{?>
													    								<span class="inline-value ">
													    									<?php echo $question['answer_label'];?>
													    								</span>
													    								<?php }?>
											    								<?php }?>
											    							</li>
						    											</ul>
						    										</div>
								    							</li>
								    						</ul>
								    					</div>
								    					<?php }?>
								    					
						    						<?php }else if ($question_type==9){?>
						    						
						    						<?php 
						    							$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question ">
								    						<ul>
								    							<li>
								    								<input type="hidden" value="<?php echo $rs['id'];?>" id="question_id_<?php echo $key+1?>" name="question_id_<?php echo $key+1?>">
								    								<div class="answer-blog">
								    									<ul>
								    										<li class="answer-opt col1">
								    											<span class="inline-value ">
								    											<span class="question-num"><?php echo $number?>.</span>
								    											</span>
											    									<?php $keyIndex=0; foreach ($rowQ as $index => $question){ 
											    										$keyIndex = $index+1;
											    										$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
											    									?>
													    								<?php if (empty($question['answer_label'])){?>
													    								<span class="inline-value ">
														    								<input class="full-width" type="text" onChange="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id."_".$question['id']?>" name="answere_<?php echo $question_id."_".$question['id']; ?>" value="<?php if (!empty($result)){ echo $result['answer_key']; }?>" dojoType="dijit.form.TextBox"  placeholder="<?php echo $tr->translate("Enter Answer");?>" autocomplete="off" dojoType="dijit.form.TextBox" autocorrect="off" autocapitalize="off" spellcheck="false" >
													    								</span>
													    								<?php }else{?>
													    								<span class="inline-value ">
													    									<?php echo $question['answer_label'];?>
													    								</span>
													    								<?php }?>
													    								
												    							
											    								<?php }?>
											    							</li>
						    											</ul>
						    										</div>
								    							</li>
								    						</ul>
								    					</div>
								    					<?php }?>
								    					
						    						<?php }else if ($question_type==10){?>
						    						<?php }else if ($question_type==11){?>
						    						<?php 
						    							$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question ">
								    						<ul>
								    							<li>
								    								<input type="hidden" value="<?php echo $rs['id'];?>" id="question_id_<?php echo $key+1?>" name="question_id_<?php echo $key+1?>">
								    								<div class="answer-blog">
								    									<ul>
											    							<?php foreach ($rowQ as $index => $question){ 
											    								$keyIndex = $index+1; 
											    								$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
											    							?>
											    							<li class="answer-opt col1">
												    							<div class="row-data">
												    								<div class="two-blog">
												    									<span class="question-num"><?php echo $keyIndex; ?>.</span> <?php echo $question['answer_label'];?>
												    								</div>
												    								<div class="two-blog">
														    							<input class="full-width" type="text" onChange="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id."_".$question['id']; ?>" name="answere_<?php echo $question_id."_".$question['id'];?>" dojoType="dijit.form.TextBox" value="<?php if (!empty($result)){ echo $result['answer_key']; }?>"  autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" placeholder="<?php echo $tr->translate("Enter Answer");?>"  >
												    								</div>
												    							</div>
											    							</li>
											    							<?php }?>
										    								
						    											</ul>
						    										</div>
						    									</li>
						    								</ul>
						    							</div>
						    							<?php }?>
						    						<?php }else if ($question_type==12){?>
							    						<?php if ($number==1){?>
							    							<?php echo $rs['article']; ?>
							    						<?php }?>
							    						
							    						<?php 
							    						$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question ">
								    						<ul>
								    							<li>
								    								<div class="answer-blog">
								    									<span class="question-num"><?php echo $number?>.</span> <?php echo $rs['question_title'];?>
								    									<ul>
								    										<?php foreach ($rowQ as $index => $question){ 
								    											$keyIndex = $index+1; 
								    											$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
								    										?>
								    										<li class="answer-opt col4">
								    											<input type="radio" <?php if (!empty($result)){ echo 'checked="checked"';}?> onClick="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id; ?>" name="answere_<?php echo $question_id; ?>" value="<?php echo $question['answer_label'];?>">  <?php echo $question['answer_label'];?>
								    										</li>
								    										<?php }?>
						    											</ul>
						    										</div>
						    									</li>
						    								</ul>
						    							</div>
						    							<?php }?>
						    							
						    						<?php }else if ($question_type==13){?>
						    							<?php if ($number==1){?>
							    							<?php echo empty($rs['article'])?"":$rs['article']; ?>
							    						<?php }?>
						    							<?php 
							    						$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question ">
								    						<ul>
								    							<li>
								    								<div class="answer-blog">
								    									<span class="question-num"><?php echo $number?>.</span> <?php echo $rs['question_title'];?>
								    									<ul>
								    										<?php foreach ($rowQ as $index => $question){ 
								    											$keyIndex = $index+1; 
								    											$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
								    										?>
								    										<li class="answer-opt col2">
								    											<input type="radio" <?php if (!empty($result)){ echo 'checked="checked"';}?> onClick="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id; ?>" name="answere_<?php echo $question_id; ?>" value="<?php echo $question['answer_label'];?>">  <?php echo $question['answer_label'];?>
								    										</li>
								    										<?php }?>
						    											</ul>
						    										</div>
						    									</li>
						    								</ul>
						    							</div>
						    							<?php }?>
						    						<?php }else if ($question_type==14){?>	
						    							<?php if ($number==1){?>
							    							<?php echo $rs['article']; ?>
							    						<?php }?>
							    						<?php 
							    						$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question ">
								    						<ul>
								    							<li>
								    								<div class="answer-blog">
								    									<table class="table_answer">
								    										<?php foreach ($rowQ as $index => $question){ 
								    											$keyIndex = $index+1;
								    											$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
								    										?>
								    											
								    												<tr>
								    													<td width="80%"> <?php echo $question['answer_label'];?> </td>
								    													<td valign="top">
											    											<select class="option-answer full-width" onChange="enterAnswer('<?php echo $question_type;?>','<?php echo $question_id;?>','<?php echo $question['id'];?>');" id="answere_<?php echo $question_id."_".$question['id']; ?>" name="answere_<?php echo $question_id."_".$question['id'];?>" dojoType="dijit.form.FilteringSelect" >
														    								<?php 
														    								if (!empty($result)){
														    									$opti= '<option value="" >'.htmlspecialchars($tr->translate("SELECT_TRUE_FALSE"), ENT_QUOTES).'</option>';
														    									foreach ($truefalseList as $quest){
														    										$selected = '';
														    										if ($quest['id']==$result['answer_key']){
														    											$selected = 'selected="selected"';
														    										}
														    										$colB = $quest['name'];
														    										$opti.= '<option '.$selected.' value="'.$quest['id'].'" >'.htmlspecialchars($colB, ENT_QUOTES).'</option>';
														    									}
														    									echo $opti;
														    								}else{
														    									echo $this->truefalse_opt;
														    								}?>
														    								</select>
								    													</td>
								    												</tr>
								    											
								    											
								    										<?php }?>
						    											</table>
						    										</div>
						    									</li>
						    								</ul>
						    							</div>
						    							<?php }?>
						    							
							    					<?php }else if ($question_type==15){?>
							    					
							    						<?php 
							    						$question_id = $rs['id'];
						    							$rowQ = $_dbgb->getQuestionDetailById($rs['id']);
						    							if (!empty($rowQ)){
						    								?>
						    							<div class="section-exam-question ">
								    						<input type="hidden" value="<?php echo $rs['id'];?>" id="question_id_<?php echo $key+1?>" name="question_id_<?php echo $key+1?>">
						    								<div class="answer-blog">
						    									<ul>
						    										<li class="answer-opt col1">
									    									<?php 
									    									$tdHead="";
									    									$options= '<option value="" >'.htmlspecialchars($tr->translate("SELECT_ANSWER"), ENT_QUOTES).'</option>';
									    									foreach ($rowQ as $index => $question){ $keyIndex = $index+1;
									    										$colB = $question['column_b'];
									    										$options .= '<option value="'.$colB.'" >'.htmlspecialchars($colB, ENT_QUOTES).'</option>';
									    										$tdHead.='<td align="center">'.$keyIndex.'</td>';
									    										?>
									    										<span class="inline-value ">
											    									<?php echo $question['answer_label'];?>
											    								</span>
											    								<span class="inline-value ">
											    									<?php echo $keyIndex;?>.) &#9634;
											    								</span>
											    								
									    								<?php }?>
									    								<span class="inline-value ">
									    								<?php echo $rs['note'];?>
									    								</span>
									    							</li>
				    											</ul>
				    											
				    											<ul>
									    							<?php 
									    							$tdAnswer="";
									    							foreach ($rowQ as $index => $question){ $keyIndex = $index+1;
									    							
									    								$result = $_dbpl->getPlacementTestAnswerRow($placemnet_id, $question_id, $question['id']);
									    							
									    								$tdAnswer.='<td><select onChange="enterAnswer('."'".$question_type."'".','."'".$question_id."'".','."'".$question['id']."'".');" id="answere_'.$question_id."_".$question['id'].'" name="answere_'.$question_id."_".$question['id'].'" dojoType="dijit.form.FilteringSelect" class="option-answer full-width" >';
									    								if (!empty($result)){
									    									$opti= '<option value="" >'.htmlspecialchars($tr->translate("SELECT_ANSWER"), ENT_QUOTES).'</option>';
									    									foreach ($rowQ as $index => $quest){
									    										$selected = '';
									    										if ($quest['column_b']==$result['answer_key']){
									    											$selected = 'selected="selected"';
									    										}
									    										$colB = $quest['column_b'];
									    										$opti.= '<option '.$selected.' value="'.$colB.'" >'.htmlspecialchars($colB, ENT_QUOTES).'</option>';
									    									}
									    									$tdAnswer.=$opti;
									    								}else{
									    									$tdAnswer.=$options;
									    								}
									    								$tdAnswer.='</select></td>';
									    							?>
									    							<li class="answer-opt col1">
									    								<?php echo $question['column_b'];?>
									    							</li>
									    							<?php }?>
				    											</ul>
							    								<table class="table_answer" border="1">
								    										<tr>
								    											<?php echo $tdHead;?>
								    										</tr>
								    										<tr>
								    											<?php echo $tdAnswer;?>
								    										</tr>
								    									</table>			
				    										</div>
								    					</div>
								    					<?php }?>
						    						<?php }else {?>
						    						<?php } //End Question Block?>
						    						
						    						<?php 
						    						$parent = $rs['parent'];
						    						$section = $rs['section_id'];
						    						?>
						    						
						    				<?php }?>
						    				
						    			</div>
						    		</div>
						    		<div class="foot-bt text-center">
						    			<a class="bt-complete" href="<?php echo $this->baseUrl()."/index/complete"?>"><?php echo $tr->translate("COMPLETE")?> </a>
						    		</div>
						    	</div>
						    	<div style="clear:both;"></div>
						    </div>
						</section>
       		 		</form>
             		
       		 	</div>
       		</div>
     <style>
			.foot-bt {
			    display: block;
			    margin: 45px 0;
			}
			a.bt-complete {
			    background: #0d8e75;
			    padding: 10px;
			    color: #fff;
			    border-radius: 5px;
			}
			a.bt-complete:hover {
			    background: #046754;
			}
			.test-min {
				    padding: 10px;
				    border-radius: 8px;
				    font-weight: 600;
				    font-size: 21px;
				    color: #fff;
				}
			span.min {
			    background: #333d98;
			    padding: 10px;
			    border: solid 1px #ccc;
			    display:inline-block;
				border-radius: 10px;
			}
		span.min span { display:block; width:100%;}
     </style>
     <script type="text/javascript">
	     url_enter_answer= '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'enteranswer'));?>';
	     function enterAnswer(question_type,question_id,answer_id){
		     if(question_type==2 || question_type==3 || question_type==12 || question_type==13){
		    	 var answer = $("input[name='answere_"+question_id+"']:checked").val();
		     }else{
		    	 var answer = dijit.byId('answere_'+question_id+'_'+answer_id).get('value');
		     }
	     	dojo.xhrPost({
	     		url: url_enter_answer,
	     		content:{
	     			'question_type':question_type,'question_id':question_id,'answer_id':answer_id,'answer_key':answer
	     			},
	     		handleAs:"json",
	     		load: function(data) {
	     		},
	     		error: function(err) {
	     		}
	     	});
	     }

	     function makeTimer() {

    		//	var endTime = new Date("29 April 2018 9:56:00 GMT+01:00");	
    			var endTime = new Date("<?php echo date("d M Y H:i:s",strtotime($endTiem));?>");			
    				endTime = (Date.parse(endTime) / 1000);

    				var now = new Date();
    				now = (Date.parse(now) / 1000);

    				var timeLeft = endTime - now;

    				var days = Math.floor(timeLeft / 86400); 
    				var hours = Math.floor((timeLeft - (days * 86400)) / 3600);
    				var minutes = Math.floor((timeLeft - (days * 86400) - (hours * 3600 )) / 60);
    				var seconds = Math.floor((timeLeft - (days * 86400) - (hours * 3600) - (minutes * 60)));
    	  
    				if (hours < "10") { hours = "0" + hours; }
    				if (minutes < "10") { minutes = "0" + minutes; }
    				if (seconds < "10") { seconds = "0" + seconds; }

    				//$("#days").html(days + "<span>Days</span>");
    				$("#hours").html(hours + "<span> Hrs </span>");
    				$("#minutes").html(minutes+ "<span> Min </span>");
    				$("#seconds").html(seconds+ "<span> Sec </span>");	
    				if(hours==00 && minutes==00 && seconds==05 ){
	    				//redirect
    					window.location.href = "<?php echo $this->baseUrl()."/index/complete"?>";
    				}	

    		}

    		setInterval(function() { makeTimer(); }, 1000);
     </script>
	