<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("EDIT_STUDENT_ATTENDENCE"));
?>	
<head>
  <meta charset="utf-8">
</head>
<style>
select{ width:100%;}
fieldset{  background:none;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 0px; border:1px solid #ccc;font-size: 12px;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
div.panel {
    padding: 0 18px;
    display: none;
    background-color: white;
}
div.panel.show {
    display: block;
}
table#table_row tr th,
table#table_row tr td {
    border: solid 1px #ccc;
    text-align: center;
}

ul.blogscoresubject li{list-style: none;width:10%;float: left; }
ol.blogscoresubject li{list-style: none;width:10%;float: left; }
ol{margin: 10px;}

table#table_row {
    width: 100%;
}
.label-info {
    background: #466979;
    color: #fff;
    margin-top: 10px;
    border: solid 1px #d8e1e0;
    padding: 3px 0;
}
.form-group ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
}
.form-group ul li {
    line-height: 28px;
}
.form-group ul li span.lbl-tt {
    min-width: 100px;
    display: inline-block;
	font-weight: bold;
}
div#score-info .form-group {
    display: block;
    font-size: 12px;
    background: #fdfbbd;
    border: solid 2px #dc0303;
    border-radius: 5px;
}
div#score-info .form-group ul li span.lbl-tt {
    color: #02014a;
}
span.red {
    color: #f00;
    font-weight: bold;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-gavel " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_STUDENT_ATTENDENCE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	 <form id='office_receipt' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
  				 if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
   					if(branch_id=="" || branch_id==-1){
						alert("<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>");
         				dijit.byId("branch_id").focus();
        				return false;
    				}
					group = dijit.byId('group').get('value');
   					if(group=="" || group==-1){
						alert("<?php echo $tr->translate('PLEASE_SELECT_GROUP');?>");
         				dijit.byId("group").focus();
        				return false;
    				}
					loadingBlock();
    				return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="material-icons-outlined">class</i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("GROUP_STUDENT_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select class="fullside" tabindex="15" name="branch_id" queryExpr="*${0}*" autoComplete="false" id="branch_id" dojoType="dijit.form.FilteringSelect"  >
												<option value="-1"><?php echo $tr->translate("SELECT_BRANCH");?></option>
												<?php if(!empty($this->branch_id))foreach ($this->branch_id as $row){?>
												<option value="<?php echo $row['id']?>" <?php if($row['id']==$this->row['branchId']){echo "selected";}?>><?php echo $row['name']?></option>
												<?php }?>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="group" />
										</div>
									</div>
									<div>&nbsp;</div>
									<div id="gr-info"></div>
								</div>
							</div>
						</div>
					</div>
		         </div>
		         <div class="col-md-4 col-sm-4 col-xs-12">
					 <div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-sound-dolby"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT_ATTENDENCE");?></p>
										</div> 
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="stu_name">
										</div>
									</div>
								
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ATTENDANCE_DATE");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input dojoType="dijit.form.DateTextBox" required="true" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" id="attendence_date" name="attendence_date" type="text" value="<?php echo $this->row['attendanceDate'];?>">
										</div>
									</div>
									
									<div class="form-group">
										<label class="control-label bold  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("FOR_SEMESTER");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="for_semester" name="for_semester" type="text">								
												<option value="1" <?php if($this->row['forSemester']==1){echo "selected";}?>><?php echo $tr->translate("SEMESTER1");?></option>
												<option value="2" <?php if($this->row['forSemester']==2){echo "selected";}?>><?php echo $tr->translate("SEMESTER2");?></option>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SESSION_TYPE");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="session_type" name="session_type" type="text">								
												<option value="1" <?php if($this->row['forSession']==1){echo "selected";}?>><?php echo $tr->translate("MORNING");?></option>
												<option value="2" <?php if($this->row['forSession']==2){echo "selected";}?>><?php echo $tr->translate("EVENING");?></option>
												<option value="3" <?php if($this->row['forSession']==3){echo "selected";}?>><?php echo $tr->translate("FULL_DAY");?></option>
											</select>
										</div>
									</div>
									<div class="form-group hidden">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SUBJECT");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="subject">
										</div>
									</div>
									
									<div class="form-group">
										<label class="control-label bold  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ATTENDANCE");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="attedence" name="attedence" type="text">								
												<option value="2" <?php if($this->row['attendence_status']==2){echo "selected";}?>><?php echo $tr->translate("ABSENT");?></option>
												<option value="3" <?php if($this->row['attendence_status']==3){echo "selected";}?>><?php echo $tr->translate("PERMISSION");?></option>
												<option value="4" <?php if($this->row['attendence_status']==4){echo "selected";}?>><?php echo $tr->translate("LATE");?></option>
												<option value="5" <?php if($this->row['attendence_status']==5){echo "selected";}?>><?php echo $tr->translate("EARLY_LEAVE");?></option>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("COMMENT");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input class="fullside" dojoType="dijit.form.TextBox"  id="comment" name="comment" value="<?php echo $this->row['description']?>" />
											<input type="hidden" class="fullside" dojoType="dijit.form.TextBox"  id="id" name="id" value="<?php echo $this->row['id']?>" />
										</div>
									</div>
									
									
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="status" name="status" type="text">								
												<option value="1" <?php if($this->row['status']==1){echo "selected";}?>><?php echo $tr->translate("ACTIVE");?></option>
												<option value="0" <?php if($this->row['status']==0){echo "selected";}?>><?php echo $tr->translate("DEACTIVE");?></option>
											</select>
										</div>
									</div>
								</div>
							</div>
						</div>
					 </div>
		         </div>
		         <div class="col-md-4 col-sm-4 col-xs-12">
		         </div>
		     </div>
	    	<div class="clearfix"></div>
	       	<div class="card-box mt-20 ">
	      	 	<div class="col-md-8 col-sm-8 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
					class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" />
            	 </div>
            </div>
		</form>
    </div>
 </div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.Textarea");
	
	var subject_store  = getDataStorefromJSON('id','name',  <?php print_r(array())?>  );
	var group_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->group));?> );
	var stu_name_store  = getDataStorefromJSON('id','name',  <?php print_r(array())?>  );
	
	dojo.ready(function(){
		
		new dijit.form.FilteringSelect({
			store:stu_name_store,
			queryExpr: "*${0}*",
			autoComplete: false,                   
			required: true,               
			id: "stu_name",
			name: "stu_name",   
			class: 'fullside', 
			placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",
			onChange: function() {  
				//setID(2);    
			}
		}, "stu_name");
		new dijit.form.FilteringSelect({
		    store:subject_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                
		    required: false,
		    id: "subject",
		    name: "subject",   
		    class: 'fullside',  
		    placeHolder:"<?php echo $tr->translate("SELECT_SUBJECT");?>",          
		    onChange: function() {  
		    }
		}, "subject");
		
		new dijit.form.FilteringSelect({
			store:group_store,
			queryExpr: "*${0}*",
			autoComplete: false,                   
			required: false,               
			id: "group",
			name: "group",   
			class: 'fullside', 
			placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",
			onChange: function() {  
			 getInfoBygroup();   
			 getStudentByGroup(<?php echo $this->row['stu_id']?>);
			}
		}, "group");
		getallgroupby(<?php echo $this->row['groupId']?>);
		
		var branch_id = dijit.byId('branch_id');
	 	branch_id.on('change', function(evt) {
	 		getallgroupby();
	    });
	});
	
	// function setID(type){
	// 	if(type==1){
	// 		stu_id = dijit.byId('stu_code').get('value');
	// 		dijit.byId('stu_name').attr('value',stu_id);
	// 	}else{
	// 		stu_id = dijit.byId('stu_name').get('value');
	// 		dijit.byId('stu_code').attr('value',stu_id);
	// 	}
	// }
	
	url_getstudent = '<?php echo $this->url(array('module'=>'issue','controller'=>'studentevaluation','action'=>'get-studentbygroup'));?>';
	function getStudentByGroup(stu_id=''){
		dijit.byId('stu_name').reset();
		group = dijit.byId('group').get('value');
		if(group=='' || group==-1){
			var stu_name_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('stu_name').set('store',stu_name_store); 
				
			dijit.byId('group').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getstudent,
			content:{
				'group':group
				},
			handleAs:"json",
			load: function(data) {
				stu_name_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('stu_name').set('store',stu_name_store);   
				if(stu_id!=''){
					dijit.byId('stu_name').attr('value',stu_id);
				}
			},
			error: function(err) {
			}
		});
	}
	
	function getallgroupby(group_id=''){// 
		var url_data = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup')); ?>';
		branch_id = dijit.byId("branch_id").attr("value");
		if(branch_id==''){  
			dijit.byId("branch_id").focus();
			return false;}
		loadingBlock();
		dojo.xhrPost({
			url:url_data,
			content:{
				'branch_id':branch_id,
			},
			handleAs:"json",
			load: function(data) {
				group_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('group').set('store',group_store);
				if(group_id!=''){
					dijit.byId('group').attr('value',group_id);
				}
			    document.getElementsByClassName("overlay")[0].style.display="none";	
			},
			error: function(err) {
			}
		});
	}

	function gender(sex){
		if(sex==1){
			sex='Male';
		}else sex='Female';
		return sex;
	}

	function getInfoBygroup(){
		url_group = '<?php echo $this->url(array('module'=>'issue','controller'=>'scoreeng','action'=>'getgroupinfo'));?>';
		group = dijit.byId('group').get('value');
		if(group==''){
			alert("<?php echo $tr->translate("PLEASE_SELECT_GROUP");?>");
			dojo.byId("gr-info").innerHTML = "";
			return false;
		}
		dojo.xhrPost({
			url:url_group,	
			content:{ 
				'group_id': group,'string':1
			},
			handleAs:"json",
			load: function(data) {
				string='';
				string+='<div class="card-info bg-gradient-directional-warning">';
					string+='<div class="card-content">';
						string+='<div class="card-body">';
							string+='<div class="media d-flex">';
								string+='<div class="media-body text-white text-left align-self-bottom mt-3">';
									string+='<span class="d-block mb-1 font-medium-1"></span>';
									string+='<h3 class="text-white mb-10"><?php echo $tr->translate("GROUP_STUDENT_INFO");?></h3>';
										string+=data;
								string+='</div>';
								string+='<div class="align-self-top">';
									string+='<i class="glyphicon glyphicon-briefcase icon-opacity text-white font-large-4 float-end"></i>';
								string+='</div>';
							string+='</div>';
						string+='</div>';
					string+='</div>';
				string+='</div>';
				dojo.byId("gr-info").innerHTML = string;
			},
			error: function(err) {
			}
		});
	}
	var url_getSubject= '<?php echo $this->url(array('module'=>'issue','controller'=>'studentattendance','action'=>'getsubjectbygroup')); ?>';
	function getSubjectByGroup(){
		group = dijit.byId('group').get('value');
		dojo.xhrPost({
			url: url_getSubject,
			content : { 
				'group':group,
			},				    
		   handleAs:"json", 
		   load: function(data){
			   subject_store  = getDataStorefromJSON('id','name', data);
			   dijit.byId('subject').set('store',subject_store);  
		   },		
		   error: function(err) {
		   }
		});
	}
</script> 