
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('STUDENT_INFO')." ".$this->rs['stu_khname']);
	echo $this->headTitle(''); 
	$url_copy =$this->url(array('module'=>'foundation','controller'=>'register','action'=>'copy'));
	$formList = new Application_Form_Frmtable();
	$frm =  $this->form_search;
	$photo= $this->frm_techer;
?>
<style>
 .bold{
		font-weight:bold;
  }
.image-box {
    text-align: center;
}
.image-box img {
    width: 120px;
    height: 130px;
}
.account-image {
    border: solid 1px #eee;
    width: 120px;
    margin: 0 auto;
} 
</style>	
	<span style="padding-left: 3px;padding-right: 40px;float: right;font-weight:600;position: absolute;right: 0px;z-index: 9999999;"><a class="add-link addsign" href="<?php echo $this->baseUrl()?>/home/searchstudentinfo"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i>ត្រលប់ក្រោយ</a></span>

<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-user-circle-o" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_INFO');?> <strong><?php echo $this->rs['stu_khname']." (".$this->rs['stu_code'].")";?></strong></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
		<div class="card-box">
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'home','controller'=>'searchstudentinfo','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<script type="dojo/method" event="onSubmit" enctype="multipart/form-data">			
		 		  if(this.validate()) {	

					return true;
				} else {
					return false;
				}
			</script>
			<!-- 
			<table style="width:100%">
			  <tr> 
					<td><input dojoType="dijit.form.TextBox"   id="adv_search" name="adv_search" placeholder="Search....." value="<?php echo $this->adv_search['adv_search']; ?>" class="fullside" type="text"></td>
					<td><?php //echo $frm->getElement("branch_id");?></td>
					<td> <?php //echo $frm->getElement("study_year");?></td>
					<td> <?php //echo $frm->getElement("degree");?></td>
					<td> <?php //echo $frm->getElement("grade_all");?></td>
					<td> <?php //echo $frm->getElement("session");?></td>
			  </tr>
			  <tr>
			        <td><?php //echo $frm->getElement("stu_name");?></td> 
			        <td><?php //echo $frm->getElement("payment_by");?></td>
			  		<td><?php //echo $frm->getElement("start_date");?></td>
			 		<td><?php //echo $frm->getElement("end_date");?></td>
					<td> <?php //echo $frm->getElement("user");?></td>
					<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			  </tr>
			  <input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
			 </table>
			  -->
			</form>
		</div>
		<div class="card-box">
			<form id="add_student" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {
						dijit.byId('save_close').set('disabled',true);	
						return true;
					}else {
						return false;
					}
				</script>
				<!-- Tab Menu -->
		    	<div class="card-box">
		    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
			            <li class="nav-item active">
			                <a class="nav-link " data-toggle="tab" href="#panel21" role="tab"><i class="fa fa-user ml-2"></i> <?php echo $tr->translate("STUDENT_INFO");?></a>
			            </li>
			            <li class="nav-item">
			                <a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
			                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("PARENT_INFO");?>
			                </a>
			            </li>
			            <li class="nav-item">
			                <a class="nav-link" data-toggle="tab" href="#panel23" role="tab">
			                <i class="fa fa-money ml-2"></i> <?php echo $tr->translate("HISTORY_PAYMENT");?>
			                </a>
			            </li>
			            <li class="nav-item">
			                <a class="nav-link" data-toggle="tab" href="#panel24" role="tab">
			                <i class="fa fa-star ml-2"></i> <?php echo $tr->translate("SERVICE_TYPE");?>
			                </a>
			            </li>
			            <li class="nav-item">
			                <a class="nav-link" data-toggle="tab" href="#panel25" role="tab">
			                <i class="fa fa-calendar ml-2"></i> <?php echo $tr->translate("RPT_RESCHEDULE_BYGROUP");?>
			                </a>
			            </li>
						<li class="nav-item">
			                <a class="nav-link" data-toggle="tab" href="#panel26" role="tab">
			                <i class="fa fa-calendar-times-o ml-2"></i> <?php echo $tr->translate("STUDENT_ATTENDANCE");?>
			                </a>
			            </li>
						<li class="nav-item">
			                <a class="nav-link" data-toggle="tab" href="#panel27" role="tab">
			                <i class="fa fa-exclamation-triangle ml-2"></i> <?php echo $tr->translate("STUDENT_MISTAKE");?>
			                </a>
			            </li>
			        </ul>
			    </div>
			    <!--/. Tab Menu -->
			    <div class="col-md-12">
			        <!-- Tab panels -->
			        <div class="tab-content vertical">
				        <!--Panel 1-->
				        <div class="tab-pane fade in active" id="panel21" role="tabpanel">
				        	<div class="card-box">
					        	<div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDENT_INFO");?> 
					                   </label>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STUDENT_ID");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['stu_code'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_KH");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['stu_khname'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME_EN");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['stu_enname'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php if($this->rs['sex']==1){
											  	echo $tr->translate("MALE");
											  }else{
											  	echo $tr->translate("FEMALE");
											  }
										  	?>
					                   </div>
					                </div>
					               	<div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['nationality'];?>
					                   </div>
					                </div>
									<div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATION");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['nation'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo empty($this->rs['dob'])?"":date("d/m/Y",strtotime($this->rs['dob']));?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("POB");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['pob'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['tel'];?>
					                   </div>
					                </div>
					             </div>
					             <div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDY_INFO");?> 
					                   </label>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("GROUP");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['group_name'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ACADEMIC_YEAR");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['year_name'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DEGREE");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['degree_name'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("GRADE");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['grade_name'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SESSION");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php if($this->rs['session']==1){
							    					echo $tr->translate("MORNING");
										   		  }elseif ($this->rs['session']==2){
										   		  		echo $tr->translate("AFTERNOON");
										   		  } elseif ($this->rs['session']==3){
										   		  		echo $tr->translate("EVERNING");
										   		  } else{
										   		  		echo $tr->translate("WEEKEND");
										   		  }
										   	 ?>  
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ROOM_NAME");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['room_name'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("REMARK");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['remark'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php if($this->rs['status']==1){ 
											 	echo $tr->translate("ACTIVE");
											  }else{
											  	echo $tr->translate("DEACTIVE");
											  }
											 ?>
					                   </div>
					                </div>
					             </div>
					             <div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("OTHER_INFOMATION");?> 
					                   </label>
					                </div>
					                <div class="form-group">
					                	<div class="account-image">
					                		<?php 
					                		$photo = $this->baseUrl().'/images/no-profile.png';
					                		if (!empty($this->rs['photo'])){
					                			$photo = $this->baseUrl().'/images/'.$this->rs['photo'];
					                		}?>
											<div class="image-box">
												<img id="profile_wiew" src="<?php echo $photo;?>" alt=""  />
											</div>
										</div>
					                </div>
					                 
					             </div>
					         </div>
					         <div class="card-box">
					        	<div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CURRENT_ADDRESS");?> 
					                   </label>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NUMBER_HOME");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['home_num'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STREET");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['street_num'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("VILLAGE");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['village_name'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMMUNE");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['commune_name'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISTRICT");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['district_name'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROVINCE");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['province_name'];?>
					                   </div>
					                </div>
					            </div>
								
								<div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("OTHER_INFOMATION");?> 
					                   </label>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ENGLISH_LANGUAGE_LEVEL");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['lang_level'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FROM_SCHOOL");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['from_school'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("KNOW_BY");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['know_by'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SPONSER");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['sponser'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['sponser_phone'];?>
					                   </div>
					                </div>
					            </div>
								
								<div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("DOCUMENT_INFO");?> 
					                   </label>
					                </div>
					                <div class="form-group">
					                   <div class="control-label col-md-12 col-sm-12 col-xs-12" >
											<table width="100%" border="1" style="border:1px solid #000;border-collapse:collapse;line-height: 24px;white-space:nowrap;">
												<tr align="center" style="font-size:14px;height:27px;font-weight:bold;background-color: #e8e6e6;">
													<td><?php echo $tr->translate("N_O");?></td>
													<td><?php echo $tr->translate("DOCUMENT_TYPE");?></td>
													<?php /*?><td><?php echo $tr->translate("DATE_GIVE");?></td><?php */?>
													<td><?php echo $tr->translate("RECEIVED");?></td>
													<td><?php echo $tr->translate("NOTE");?></td>
												</tr>
												<?php $i=0;if(!empty($this->document)){foreach($this->document as $rs){$i++;?>
												<tr style="font-size:13px;height:23px;">
													<td align="center"><?php echo $i;?></td>
													<td><?php echo $rs['document_type'];?></td>
													<?php /*?><td align="center"><?php echo date("d/m/Y",strtotime($rs['date_give']));?></td><?php */?>
													<td><?php if($rs['is_receive']==1){echo $tr->translate("RECEIVED");}else{echo $tr->translate("NOT_RECEIVED");}?></td>
													<td><?php echo $rs['note'];?></td>
												</tr>
												<?php }}?>
											</table>
					                   </div>
					                </div>
					            </div>
								
					        </div>
				        </div>
				        <!--/. Panel 1-->
				       
				        <!--Panel 2-->
				        <div class="tab-pane fade in " id="panel22" role="tabpanel">
				        	<div class="card-box">
					        	<div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("FATHER_INFO");?> 
					                   </label>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['father_enname'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo date("d",strtotime($this->rs['father_dob'])>0)?date("d/m/Y",strtotime($this->rs['father_dob'])):"";?>
											
											<?php //echo date("d",strtotime($this->rs['father_dob']));?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['father_nation'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("OCCUPATION");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['fath_job'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['father_phone'];?>
					                   </div>
					                </div>
					            </div>
					            <div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("MOTHER_INFO");?> 
					                   </label>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['mother_enname'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo date("d",strtotime($this->rs['mother_dob'])>0)?date("d/m/Y",strtotime($this->rs['mother_dob'])):"";?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['mother_nation'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("OCCUPATION");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['moth_job'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['mother_phone'];?>
					                   </div>
					                </div>
					                
					            </div>
					            <div class="col-md-4 col-sm-4 col-xs-12">
									<div class="form-group">
					                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("GUARDIAN_INFO");?> 
					                   </label>
					                </div>
					                 <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NAME");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['guardian_enname'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo date("d",strtotime($this->rs['guardian_dob'])>0)?date("d/m/Y",strtotime($this->rs['guardian_dob'])):"";?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['guardian_nation'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("OCCUPATION");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['guard_job'];?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?> 
					                   </label>
					                   <div class=" bold col-md-7 col-sm-7 col-xs-12">
					                   		<?php echo $this->rs['guardian_tel'];?>
					                   </div>
					                </div>
					            </div>
					        </div>
				        </div>
				        <!--/. Panel 2-->
				        
				         <!--Panel 3-->
				        <div class="tab-pane fade in " id="panel23" role="tabpanel">
				        	<div class="card-box">
					        	<div class="col-md-12 col-sm-12 col-xs-12">
					        		<?php 
										$total=0;
										$total_balance = 0;
										$total_receive = 0;
									?>	
									<table class="padd" width="100%" border="1" align="center" style="border:1px solid #000;border-collapse:collapse;white-space:nowrap;font-family: 'Khmer OS Battambang';">
										  <thead>
											  <tr style="text-align:center;background-color: #ccd9ff;line-height: 30px;font-weight: bold;font-size:12px; height: 20px; align="center" >
											    <td><?php echo $tr->translate('N_O');?></td>
												<td><?php echo $tr->translate('SERVICE_CATE');?></td>
												<td><?php echo $tr->translate('SERVICE_NAME');?></td>
												<td><?php echo $tr->translate('PAID_DATE');?></td>
												<td><?php echo $tr->translate('RECEIPT_NO');?></td>
												<td><?php echo $tr->translate('SCHOLARSHIP');?></td>
												<td><?php echo $tr->translate('SCHOLARSHIP_AMOUNT');?></td>
												<td><?php echo $tr->translate('PAYMENT_TERM');?></td>
												<td><?php echo $tr->translate('QTY');?></td>
												<td><?php echo $tr->translate('PRICE');?></td>
												<td><?php echo $tr->translate('LATE_FEE');?></td>
												<td><?php echo $tr->translate('EXTRA_FEE');?></td>
												<td><?php echo $tr->translate('DISCOUND');?></td>
												<td><?php echo $tr->translate('DISCOUNT');?></td>
												<td><?php echo $tr->translate('PAID_AMOUNT');?></td>
												<td><?php echo $tr->translate('START_DATE');?></td>
												<td><?php echo $tr->translate('END_DATE');?></td>
												<td><?php echo $tr->translate('REMARK');?></td>
												<td><?php echo $tr->translate('STATUS');?></td>
												<td><?php echo $tr->translate('USER');?></td>
											  </tr>
										 </thead>
										<style> 
											td{padding:0 2px; }
											.hover:hover{background: #ccc;}
										</style>
										  <?php $i=0;if(!empty($this->row)){ foreach($this->row as $rs){ $i++;?>
										  <tr class="hover" style="font-size:12px; color:#000; height: 18px;"​ align="center">
										  	<td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $i;?></td>
										    <td style="text-align:left"><?php echo $rs['category']; ?></td>
										    <td style="text-align:left"><?php echo $rs['title']; ?></td>
										    <td><?php echo date('d/m/Y', strtotime($rs['create_date']));?></td>
										    <td align="center" <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $rs['receipt_number']; ?></td>
										    <td align="center"><?php echo $rs['scholarship_percent']; ?>%</td>
										    <td align="center"><?php echo $rs['scholarship_amount']; ?></td>
										    <td align="center"><?php echo $rs['payment_term']; ?></td>
										    <td><?php echo $rs['qty'];?></td>
										    <td>$ <?php echo number_format($rs['fee'],2); ?></td>
										    <td><?php if($rs['late_fee']>0){echo '$ '.$rs['late_fee'];}?></td>
										    <td><?php if($rs['extra_fee']>0){echo '$ '.$rs['extra_fee'];}?></td>
										    <td><?php if($rs['discount_percent']>0){echo $rs['discount_percent'].' %';} ?> </td>
										    <td><?php echo $rs['discount_fix']; ?> </td>
										    <td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>>$ <?php echo $rs['paidamount']; ?></td>
										    <td><?php echo empty($rs['start_date'])?"":date('d/m/Y', strtotime($rs['start_date'])); ?></td>
										    <td><?php echo empty($rs['validate'])?"":date('d/m/Y', strtotime($rs['validate'])); ?></td>
										    <td style="font-size: 9px;"><?php echo $rs['note']; ?></td>
										   	<td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $rs['void_status']; ?></td>
										  	 <td><?php echo $rs['user']; ?></td>
										  </tr>
										  <?php 
										 	if($rs['is_void']==0){
										 		$total = $rs['paidamount'] + $total;
										 	}
										  ?> 
										  <?php } }?>
										</table>
					        	</div>
					       	</div>
				        </div>
				        <!--/. Panel 3-->
				        
				         <!--Panel 4-->
				        <div class="tab-pane fade in " id="panel24" role="tabpanel">
				        	<div class="card-box">
					        	<div class="col-md-12 col-sm-12 col-xs-12">
					        		<?php 
										$total=0;
										$total_balance = 0;
										$total_receive = 0;
									?>	
									<table class="padd" width="100%" border="1" align="center" style="border:1px solid #000;border-collapse:collapse;white-space:nowrap;font-family: 'Khmer OS Battambang';">
										  <thead>
											  <tr style="text-align:center;background-color: #ccd9ff;line-height: 30px;font-weight: bold;font-size:12px; height: 20px; align="center" >
											    <td><?php echo $tr->translate('N_O');?></td>
												<td><?php echo $tr->translate('SERVICE_CATE');?></td>
												<td><?php echo $tr->translate('SERVICE_NAME');?></td>
												<td><?php echo $tr->translate('PAID_DATE');?></td>
												<td><?php echo $tr->translate('RECEIPT_NO');?></td>
												<td><?php echo $tr->translate('SCHOLARSHIP');?></td>
												<td><?php echo $tr->translate('SCHOLARSHIP_AMOUNT');?></td>
												<td><?php echo $tr->translate('PAYMENT_TERM');?></td>
												<td><?php echo $tr->translate('QTY');?></td>
												<td><?php echo $tr->translate('PRICE');?></td>
												<td><?php echo $tr->translate('LATE_FEE');?></td>
												<td><?php echo $tr->translate('EXTRA_FEE');?></td>
												<td><?php echo $tr->translate('DISCOUND');?></td>
												<td><?php echo $tr->translate('DISCOUNT');?></td>
												<td><?php echo $tr->translate('PAID_AMOUNT');?></td>
												<td><?php echo $tr->translate('START_DATE');?></td>
												<td><?php echo $tr->translate('END_DATE');?></td>
												<td><?php echo $tr->translate('REMARK');?></td>
												<td><?php echo $tr->translate('STATUS');?></td>
												<td><?php echo $tr->translate('USER');?></td>
											  </tr>
										 </thead>
										<style> 
											td{padding:0 2px; }
											.hover:hover{background: #ccc;}
										</style>
										  <?php $i=0;if(!empty($this->service)){foreach($this->service as $rs){ $i++;?>
										  <tr class="hover" style="font-size:12px; color:#000; height: 18px;"​ align="center">
										  	<td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $i;?></td>
										    <td style="text-align:left"><?php echo $rs['category']; ?></td>
										    <td style="text-align:left"><?php echo $rs['title']; ?></td>
										    <td><?php echo date('d/m/Y', strtotime($rs['create_date']));?></td>
										    <td align="center" <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $rs['receipt_number']; ?></td>
										    <td align="center"><?php echo $rs['scholarship_percent']; ?>%</td>
										    <td align="center"><?php echo $rs['scholarship_amount']; ?></td>
										    <td align="center"><?php echo $rs['payment_term']; ?></td>
										    <td><?php echo $rs['qty'];?></td>
										    <td>$ <?php echo number_format($rs['fee'],2); ?></td>
										    <td><?php if($rs['late_fee']>0){echo '$ '.$rs['late_fee'];}?></td>
										    <td><?php if($rs['extra_fee']>0){echo '$ '.$rs['extra_fee'];}?></td>
										    <td><?php if($rs['discount_percent']>0){echo $rs['discount_percent'].' %';} ?> </td>
										    <td><?php echo $rs['discount_fix']; ?> </td>
										    <td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>>$ <?php echo $rs['paidamount']; ?></td>
										    <td><?php echo empty($rs['start_date'])?"":date('d/m/Y', strtotime($rs['start_date'])); ?></td>
										    <td><?php echo empty($rs['validate'])?"":date('d/m/Y', strtotime($rs['validate'])); ?></td>
										    <td style="font-size: 9px;"><?php echo $rs['note']; ?></td>
										   	<td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $rs['void_status']; ?></td>
										  	 <td><?php echo $rs['user']; ?></td>
										  </tr>
										  <?php 
										 	if($rs['is_void']==0){
										 		$total = $rs['paidamount'] + $total;
										 	}
										  ?> 
										  <?php } }?>
										</table>
					        	</div>
					       	</div>
				        </div>
				        <!--/. Panel 4-->
				        
				        <!--Panel 5-->
				        <div class="tab-pane fade in " id="panel25" role="tabpanel">
				        	<div class="card-box">
					        	<div class="col-md-12 col-sm-12 col-xs-12">
					        		<?php
										$tr = Application_Form_FrmLanguages::getCurrentlanguage();
										$this->headTitle('Report Student Drop'); 
										echo $this->headTitle(''); 
										$frm =  $this->form_search;
										//print_r($this->rs);
										$db_sub=new Allreport_Model_DbTable_DbRptStudentDrop();
										
										$day = array(
												1=>'Monday',
												2 =>'Tuesday',
												3 =>'Wednesday',
												4=>'Thursday',
												5=>'Friday',
										);
										
									?>	
									<div style=" background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">	
										<div id="divPrint">
											<table style="background:#fff; margin: 0 auto;width: 100%; font-family: 'Times New Roman','Kh Battambang','Khmer Battambang';">
												<tr>
													<td width="25%" align="left">
														<img style="width: 40%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
													</td>
													<td align="center">
														<strong​​ style="font-weight:bold;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_BRANCH");?></strong><br />
														<strong​​ style="font-weight:bold;color:#000; font-size: 16px;font-family:initial;"><?php echo $tr->translate("CUSTOMER_BRANCH");?>-Sen Sok Campus</strong><br />
														<strong style="font-weight:bold;color:#000; font-size: 13px;font-family:'Arial Black','Khmer MEF2';"><?php echo $tr->translate("RPT_RESCHEDULE_BYGROUP");?></strong><br />
													</td>
													<td width="25%" align="right">
													</td>
												</tr>
											<style>
												table tr th{
													border: 1px solid #000;	
												}
												.hover:hover{background: #ccc;}
												table { page-break-inside:auto }
												  tr{ page-break-inside:avoid; page-break-after:auto; }
												#header {
												  display: table-header-group;
												  page-break-inside:avoid; page-break-after:auto;
												}
												tr.head_schedule th {
												    padding: 5px 0;
												    text-align: center;
												}
											</style>
												<tr>
													<td colspan="3">
													<?php $title=0; $titles=0; $year='';$group='';$hour=''; if(!empty($this->re_row)) 
														foreach ($this->re_row As $rs){
														$timestudy = $db_sub->getTimeSchelduleByYGS($rs['year_id'],$rs['group_id']);
														?>
														<table border="1" cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;" >
															<thead>
																<tr><th align="left" colspan="7" style="border:1px solid #fff;">Room:&nbsp;<?php echo $rs['room_name']?></th></tr>
																<tr><th align="left" colspan="7" style="border-right:1px solid #fff;border-left:1px solid #fff;">Grade:&nbsp;<?php echo $rs['grade_name']?></th></tr>
																<tr class="head_schedule" style="font-size:12px;" align="center" >
																	<th rowspan="2" width="15%"><?php echo $tr->translate("TIME");?></th>
																	<th colspan="5"><?php echo $tr->translate("DAYS");?></th>
																</tr>
																
																<tr class="head_schedule" style="font-size:12px;" align="center" >
																<?php foreach ($day as $key => $days){?>
																	<th ><?php echo $tr->translate($days);?></th>
																<?php }?>
																</tr>
															</thead>
														<?php $session='';foreach($timestudy As $time){
															if($time['from_hour']<=12){
																if($title==0){?>
																<tr  align="center" >
																	<th colspan="6" style="font-size:12px; padding: 5px 2px; text-decoration: underline;"><?php echo  $tr->translate("Morning");?></th>
																</tr>
														        <?php $title=1;}
															}else{
																if($titles==0){
													        ?>
													        	<tr  align="center" >
																	<th colspan="6" style="font-size:12px; padding: 5px 2px; text-decoration: underline;"><?php echo  $tr->translate("Afternoon");?></th>
																</tr>
													        <?php $titles=1;}
																}
													        ?>
																<tr class="hover" style="font-size:11px; height: 20px;" align="center" >
																	<td align="center"><?php echo $time['times'];?></td>
																	<?php foreach ($day as $key => $days){
																		$subjecNteacher = $db_sub->getSubjectTeacherByScheduleAndGroup($rs['year_id'],$rs['group_id'],$time['times'], $key)
																	?>
																	<td>
																		<?php 
																	 	if (!empty($subjecNteacher)){
																			 if (!empty($subjecNteacher['teacher_name'])){echo $subjecNteacher['teacher_name'];}
																			 if (!empty($subjecNteacher['teacher_phone'])){echo "<br/>".$subjecNteacher['teacher_phone'];}
																			 if (!empty($subjecNteacher['subject_name'])){echo "<br/>(".$subjecNteacher['subject_name'].")";}
																		}?>
																	</td>
																	<?php }?>
																</tr>
														 <?php }?>
														 
														 <?php  foreach($db_sub->getSubjectListByYG($rs['year_id'],$rs['group_id'] ) As $key=>$rs_list){
														 	if($rs_list['total_hour']>1){
														        $h_label='hrs';
														 	}else{
														 		$h_label='hr';
														 	}
														 	$totalTime = $db_sub->getSubjectForCalculateTime($rs['year_id'], $rs['group_id'], $rs_list['subject_id']);
														 	?>
														 <tr>
														    <td style="border-left: 1px solid #fff;border-right: 1px solid #fff;border-bottom: 1px solid #fff;padding:0px;line-height: 25px;"><?php echo $key+1?>.&nbsp;<?php echo $rs_list['subject_name']?>:&nbsp;<?php echo $totalTime;//$rs_list['total_hour'].''.$h_label?></td>
														 </tr>
														 <?php }?>
														  <tr >
														 	<td colspan="7" align="right" style="border: 1px solid #fff;">
														 	Phnom Penh,&nbsp;<?php echo date('d F Y');?>
														 	</td>
														 </tr>
														</table>	
														
														<br/>
													<?php  }?>
													</td>
												</tr>
												<tr>
													<td colspan="3">&nbsp;</td>
												</tr>
												 
												<tr >
													<td align="center" width="25%">
														<span style="font-weight: bold;font-size: 14px;">Verified by</span>
													</td>
													<td  width="50%">&nbsp;
														
													</td>
													<td align="center"  width="25%">
														<span style="font-weight: bold;font-size: 14px;text-align: right;">Prepared by</span>
													</td>
												</tr>
											</table>
										</div>		
									</div>
					        	</div>
					        </div>
				        </div>
				        <!--/. Panel 5-->
						
						
						<!--Panel 6-->
				        <div class="tab-pane fade in " id="panel26" role="tabpanel">
				        	<div class="card-box">
					        	<div class="col-md-12 col-sm-12 col-xs-12">
					        		<?php if (!empty($this->student_attendance)){?>
									<table cellpadding="5"​ style="font-family:'Khmer OS Battambang' ; margin:0 auto;width:100%;border:1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
										<thead>
										<?php 
											$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
											$i=0; 
											$old_groupid=0; 
											$old_student_id=0; 
										 foreach ($this->student_attendance as $key => $rs){
											if ($rs['sex']==1){$sex = $tr->translate("MALE");}else{$sex = $tr->translate("FEMALE");}
										?>
										<?php if ($old_groupid!=$rs['group_id']){ ?>
										<?php if ($key>0){ 
										?>
									
										<tr>
											<td align="right" style="  border-left: 1px solid #fff; border-right: 1px solid #fff;">
												&nbsp;
											</td>
										</tr>
										<?php }$i=0; ?>
										<tr>
											<td align="center" style=" border-top: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
												<!-- <img style="width: 90px;float: left; " alt="<?php ?>" src="<?php //echo $this->baseUrl().'/images/logo.png'?>"> -->
												<strong​​ style="font-weight:bold;color:#000; font-size: 16px;font-family: 'Times New Roman','Khmer OS Muol light';"><?php echo $tr->translate("STUDENT_ATTENDENCE");?></strong><br />
												<strong​​ style="color:#000; font-size: 13px;font-family:'Times New Roman','Khmer OS Muol light';">
													<?php echo $tr->translate("ACADEMIC_YEAR");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['academic_year'];?></span> ,
													<?php echo $tr->translate("DEGREE");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['degree'];?></span> 
													<?php echo $tr->translate("MONTHLY");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $month[date("m")]." ".date("Y");?></span>
													<br />
													<?php echo $tr->translate("GROUP");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['group_code'];?></span> , 
													<?php echo $tr->translate("GRADE");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['grade'];?></span> , 
													<?php echo $tr->translate("SEMESTER");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['semester'];?></span> , 
													<?php echo $tr->translate("ROOM_NAME");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['room_name'];?></span> 
													, <?php echo $tr->translate("SESSION");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['session'];?></span>
												</strong>
											</td>
										</tr>
										</thead>
										<?php } $i++;?>
										<tr style="border: solid 1px #fff;">
											<td style="font-weight: 600;">
												<?php echo $i.". ".$tr->translate("STUDENT_ID");?> : <?php echo $rs['stu_code'];?>
												<?php echo $tr->translate("STUDENT");?> : <?php echo $rs['stu_khname'];?>
												<?php echo $tr->translate("SEX");?> : <?php echo $sex;?>
											</td>
										</tr>
										<?php 
										$A=0; 
										$P=0; 
										$L=0; 
										$EL=0; 
										$db = new Home_Model_DbTable_DbStudent();
										$attentence_status = $db->getStatusAttendence($rs['stu_id'], $rs['group_id']);
										?>
										
										<?php if (!empty($attentence_status)){?>
										<tr style="border: solid 1px #fff;">
											<td>
												<table cellpadding="5"​ border="1" style="font-family:'Khmer OS Battambang' ; border:1px solid #000; border-collapse: collapse; margin:0 auto; width:100%; white-space: nowrap;" >
													<tr style="font-size:13px; font-weight:bold; background: #ccd9ff;">
														<td rowspan="2" align="center">
															<?php echo $tr->translate("DATE");?>	
														</td>
														<td colspan="4" align="center">
															<?php echo $tr->translate("ATTENDANCE");?>
														</td>
														<td rowspan="2" align="center">
															<?php echo $tr->translate("DESCRIPTION");?>
														</td>
													</tr>
													<tr style="font-size:12px; font-weight:bold; background: #ccd9ff;">
														<td align="center"><?php echo $tr->translate("ABSENT");?></td>
														<td align="center"><?php echo $tr->translate("PERMISSION");?></td>
														<td align="center"><?php echo $tr->translate("LATE");?></td>
														<td align="center"><?php echo $tr->translate("EARLY_LEAVE");?></td>
													</tr>
													<?php foreach ($attentence_status as $rs){
														$absent="";
														$permission="";
														$late="";
														$early_leave="";
														
														if ($rs['attendence_status']==2){
															$absent = 1;
															$A=$A+1;
															//Absent
														}
														else if ($rs['attendence_status']==3){
															$permission=1;
															 $P = $P+1;
															//Permission
														}
														else if ($rs['attendence_status']==4){
															$late=1;
															$L = $L+1;
															//Late
														}
														else if ($rs['attendence_status']==5){
															$early_leave=1;
															$EL = $EL+1;
															//Early Leave
														}else{
															echo " ";
														}
													?>
													<tr style="font-size:13px;">
														<td width="20%" align="center"><?php echo date("d-m-Y",strtotime($rs['date_attendence']));?></td>
														<td width="10%" align="center"><?php echo $absent;?></td>
														<td width="10%" align="center"><?php echo $permission;?></td>
														<td width="10%" align="center"><?php echo $late;?></td>
														<td width="10%" align="center"><?php echo $early_leave;?></td>
														<td width="40%" align="left"> &nbsp;<?php echo $rs['description'];?></td>
													</tr>
													<?php }?>
													<tr align="center" style="font-size:13px;">
														<td style="background: #ccd9ff;">
															<?php echo $tr->translate("TOTAL");?>
														</td>
														<td>
															<?php echo $A;?>
														</td>
														<td>
															<?php echo $P;?>
														</td>
														<td>
															<?php echo $L;?>
														</td>
														<td>
															<?php echo $EL;?>
														</td>
													</tr>
												</table>
											</td>
										</tr>
										<?php }?>
										<?php $old_groupid = $rs['group_id'];
										}?>
										<tr>
											<td align="right" style=" border-bottom: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
												&nbsp;
											</td>
										</tr>
									</table>
									<?php }?>
					        	</div>
					        </div>
				        </div>
				        <!--/. Panel 6-->
						
						
						<!--Panel 7-->
				        <div class="tab-pane fade in " id="panel27" role="tabpanel">
				        	<div class="card-box">
					        	<div class="col-md-12 col-sm-12 col-xs-12">
					        		<?php if (!empty($this->student_mistake)) {?>
									<table cellpadding="5"​ style="font-family:'Khmer OS Battambang' ; margin:0 auto;width:100%;border:1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
										<thead>
										<?php 
											$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
											$i=0; 
											$old_groupid=0; 
											$old_student_id=0; 
										 foreach ($this->student_mistake as $key => $rs){
											if ($rs['sex']==1){$sex = $tr->translate("MALE");}else{$sex = $tr->translate("FEMALE");}
										?>
										<?php if ($old_groupid!=$rs['group_id']){ ?>
										<?php if ($key>0){ 
										?>
									
										<tr>
											<td align="right" style="  border-left: 1px solid #fff; border-right: 1px solid #fff;">
												&nbsp;
											</td>
										</tr>
										<?php }$i=0; ?>
										<tr>
											<td align="center" style=" border-top: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
												<!-- <img style="width: 90px;float: left; " alt="<?php ?>" src="<?php //echo $this->baseUrl().'/images/logo.png'?>"> -->
												<strong​​ style="font-weight:bold;color:#000; font-size: 16px;font-family: 'Times New Roman','Khmer OS Muol light';"><?php echo $tr->translate("STUDENT_MISTAKE");?></strong><br />
												<strong​​ style="color:#000; font-size: 13px;font-family:'Times New Roman','Khmer OS Muol light';">
													<?php echo $tr->translate("ACADEMIC_YEAR");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['academic_year'];?></span> ,
													<?php echo $tr->translate("DEGREE");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['degree'];?></span> 
													<?php echo $tr->translate("MONTHLY");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $month[date("m")]." ".date("Y");?></span>
													<br />
													<?php echo $tr->translate("GROUP");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['group_code'];?></span> , 
													<?php echo $tr->translate("GRADE");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['grade'];?></span> , 
													<?php echo $tr->translate("SEMESTER");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['semester'];?></span> , 
													<?php echo $tr->translate("ROOM_NAME");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['room_name'];?></span> 
													, <?php echo $tr->translate("SESSION");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['session'];?></span>
												</strong>
											</td>
										</tr>
										</thead>
										<?php } $i++;?>
										<tr style="border: solid 1px #fff;">
											<td style="font-weight: 600;">
												<?php echo $i.". ".$tr->translate("STUDENT_ID");?> : <?php echo $rs['stu_code'];?>
												<?php echo $tr->translate("STUDENT");?> : <?php echo $rs['stu_khname'];?>
												<?php echo $tr->translate("SEX");?> : <?php echo $sex;?>
											</td>
										</tr>
										<?php 
										$s=0; 
										$m=0; 
										$b=0; 
										$db = new Home_Model_DbTable_DbStudent();
										$mistake_status = $db->getStatusMistakeByStudent($rs['stu_id'],$rs['group_id']);?>
										<?php if (!empty($mistake_status)){?>
										<tr style="border: solid 1px #fff;">
											<td>
												<table cellpadding="5"​ border="1" style="font-family:'Khmer OS Battambang' ; border:1px solid #000; border-collapse: collapse; margin:0 auto; width:100%; white-space: nowrap;" >
													<tr style="font-size:13px; font-weight:bold; background: #ccd9ff;">
														<td rowspan="2" align="center">
															<?php echo $tr->translate("DATE");?>	
														</td>
														<td colspan="3" align="center">
															<?php echo $tr->translate("MISTAKE");?>
														</td>
														<td rowspan="2" align="center">
															<?php echo $tr->translate("DESCRIPTION");?>
														</td>
													</tr>
													<tr style="font-size:12px; font-weight:bold; background: #ccd9ff;">
														<td align="center"><?php echo $tr->translate("SMALL_MISTACK");?></td>
														<td align="center"><?php echo $tr->translate("MEDIUM_MISTACK");?></td>
														<td align="center"><?php echo $tr->translate("BIG_MISTACK");?></td>
													</tr>
													<?php foreach ($mistake_status as $rs){
														$small="";
														$medium="";
														$big="";
														$description="";
														if ($rs['type']==2){
															$description = $rs['description'];
															if ($rs['mistake_type']==1){
																$small = 1;
																$s=$s+1;
																//small
															}
															else if ($rs['mistake_type']==2){
																$medium=1;
																 $m = $m+1;
																//medium
															}
															else if ($rs['mistake_type']==3){
																$big=1;
																$b = $b+1;
																//big
															}else{
																echo " ";
															}
														}else{
															if ($rs['mistake_type']==4){
																$small = 1;
																if ($rs['for_session']==1){
																	$descri_added = "(មកយឺត ពេលព្រឹក)";
																}else if ($rs['for_session']==2){
																	$descri_added = "(មកយឺត ពេលល្ងាច)";
																}
																$description = $rs['description']." ".$descri_added;
																 $s=$s+1;
															}elseif ($rs['mistake_type']==5){
																$small = 1;
																if ($rs['for_session']==1){
																	$descri_added = "(ចេញមុន ពេលព្រឹក)";
																}else if ($rs['for_session']==2){
																	$descri_added = "(ចេញមុន ពេលល្ងាច)";
																}
																$description = $rs['description']." ".$descri_added;
			// 													$description = "( 'ចេញមុន' ".$rs['description'].")";
																$s=$s+1;
															}
														}
													?>
													<tr style="font-size:13px;">
														<td width="20%" align="center"><?php echo date("d-m-Y",strtotime($rs['mistake_date']));?></td>
														<td width="10%" align="center"><?php echo $small;?></td>
														<td width="10%" align="center"><?php echo $medium;?></td>
														<td width="10%" align="center"><?php echo $big;?></td>
														<td width="50%" align="left"> &nbsp;<?php echo $description;?></td>
													</tr>
													<?php }?>
													<tr align="center" style="font-size:13px;">
														<td style="background: #ccd9ff;">
															<?php echo $tr->translate("TOTAL");?>
														</td>
														<td>
															<?php echo $s;?>
														</td>
														<td>
															<?php echo $m;?>
														</td>
														<td>
															<?php echo $b;?>
														</td>
													</tr>
												</table>
											</td>
										</tr>
										<?php }?>
										<?php $old_groupid = $rs['group_id'];
										}?>
										<tr>
											<td align="right" style=" border-bottom: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
												&nbsp;
											</td>
										</tr>
									</table>
									<?php }?>
					        	</div>
					        </div>
				        </div>
				        <!--/. Panel 7-->
						
						
			   		 </div>
			   		   <!--/. Tab panels -->
			   	</div>
			    
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
dojo.require("dijit.form.CheckBox"); 
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");

	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 if(id!=''){
			window.location.href = url+'/id/'+id;
		 }else{
			alert('Please select record you want to copy');
			return false;
		 }
	}

	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}

	function setStuValue(type){ //type=1 set value vy studet code. type =2 by stu name
	  if(type==1){
		  stu_code=dijit.byId("stu_code").get("value");
		  dijit.byId("stu_name").attr("value",stu_code);
	  }else{
		  stu_name=dijit.byId("stu_name").get("value");
		  dijit.byId("stu_code").attr("value",stu_name);
	  }
	}
		
</script> 
