<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_ACADEMIC_YEAR')); 
	$frm= $this->frm;

	$dept = '';
	if (!empty($this->rs['degreeList'])) {
		$dept =  explode(",", $this->rs['degreeList']);
	}
	$array = array();
	if (!empty($dept)) {
		foreach ($dept as $ss) {
			$array[$ss] = $ss;
		}
	}
?>
<style>
	.optListRow li.opt-items input[type=checkbox],
	input[type=radio] {
		margin: -9px 0 0 !important;
	}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
              <div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_ACADEMIC_YEAR');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='add_discount' action="" method="post" dojoType="dijit.form.Form" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
  				 if(this.validate()) {
					loadingBlock();
					dijit.byId("save_new").attr("disabled",true);
   					 return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-calendar" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("ACADEMIC_YEAR");?></p>
										</div> 
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FROM_YEAR");?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
												<?php echo $frm->getElement("fromYear");?>
												<?php echo $frm->getElement("id");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TO_YEAR");?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
												<?php echo $frm->getElement("toYear");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label custom-switch float-end "> 
											<a href="javascript:void(0);" class="switchButton status"><?php echo $tr->translate("Is Default");?></a> 
											<input type="checkbox" id="isCurrent" name="isCurrent" class="custom-switch-input"  <?php if(!empty($this->rs["isCurrent"])){ echo "checked";} ?> > 
											<span class="custom-switch-indicator custom-radius switch-status"></span> 
										</label>
									</div>
									<div class="form-group">
										<label class="control-label custom-switch float-end "> 
											<a href="javascript:void(0);" class="switchButton status"><?php echo $tr->translate("STATUS");?></a> 
											<input type="checkbox" id="status" name="status" class="custom-switch-input"  <?php if(!empty($this->rs["status"])){ echo "checked";} ?> > 
											<span class="custom-switch-indicator custom-radius switch-status"></span> 
										</label>
									</div>
								</div>
							</div>
						</div>
					</div>			
	            </div>
				<div id="degreee" class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex">
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-indent-left" aria-hidden="true"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("DEGREE"); ?></p>
										</div>
									</div>
									<br />
									<div class="custom-control custom-checkbox ">
										<input type="checkbox" class="checkbox custom-control-input" onchange="checkall();" class="checkbox" id="check_all" name="check_all">
										<label class="custom-control-label" for="check_all">
											<?php echo $tr->translate('CHECK_ALL'); ?>
										</label>
									</div>
									<div class="form-group">
										<ul class="optListRow">
											<?php
											if (!empty($this->faculty)) foreach ($this->faculty as $rs) {
											?>
												<li class="opt-items">
													<div class="custom-control custom-checkbox">
														<input <?php if (in_array($rs['id'], $array)) {
																	echo "checked";
																} ?> type="checkbox" class="checkbox custom-control-input" id="depts<?php echo $rs['id']; ?>" value="<?php echo $rs['id']; ?>" name="selector[]">
														<label class="custom-control-label" for="depts<?php echo $rs['id']; ?>">
															<?php echo $rs['name']; ?>
														</label>
													</div>
												</li>

											<?php } ?>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="clearfix"></div>
			    <div class="card-box mt-20">
		        	<div class="col-md-8 col-sm-8 col-xs-12 border-top mt-20 ptb-10 text-center">
		               	<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE');?>" dojoType="dijit.form.Button" 
							class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-saved" />
		        	</div>
		        </div>
	         </div>
		</form>
	</div>
</div>
<script type="text/javascript">

	dojo.require('dijit.form.NumberTextBox');
	function checkall(){
		if ($('#check_all').is(':checked')) {
			$(".checkbox").prop('checked', true);
		}else{
			$(".checkbox").prop('checked', false);
		}
	}
</script>