<?php
require_once PUBLIC_PATH. '\mpdf\vendor\autoload.php';
require_once PUBLIC_PATH. '\mpdf\vendor\mpdf\mpdf\mpdf.php';

$studentInfo = $this->resultData['studentInfo'];
$scoreSubjectList = $this->resultData['scoreSubjectInfo'];
$evalueationList = $this->resultData['EvalueationList'];
$scoreInfo = $this->resultData['scoreInfo'];
$groupId = $scoreInfo['group_id'];
$forMonthId = $scoreInfo['for_month'];
$academicId = $scoreInfo['academicYearId'];
$forSemester= $scoreInfo['for_semester'];
$degreeId= $scoreInfo['degreeId'];
$examType = $scoreInfo['exam_type'];

$dbgb = new Application_Model_DbTable_DbGlobal();
$db = new Allreport_Model_DbTable_DbScoreTranscript();

$scoreTitle=($scoreInfo['exam_type']==1)?$scoreInfo['forMonthKhLabel'].'-'.$scoreInfo['forMonthEnLabel']:"SEMESTER ".$scoreInfo['for_semester'];
$stringSubjectType = array(
		'1'=>'កម្មវិធីខ្មែរ Khmer Program',
		'2'=>'កម្មវិធីអង់គ្លេស English Program'
		);
		
		

$branchId = $scoreInfo['branch_id'];
$branchId = empty($branchId)?1:$branchId;
$headerScore = getHeaderReportPDF($branchId);	
	
$subjectProgram= array(
					1=>'កម្មវិធីសិក្សាជាភាសាខ្មែរ Khmer Program',
					2=>'កម្មវិធីសិក្សាជាភាសាអង់គ្លេស English Program',
					3=>'កម្មវិធីភាសាចិន Chinese Program',
				);
$bgProgramColor= array(
					1=>'bg-blue',
					2=>'bg-yellow',
					3=>'bg-red',
				);
			
$sexkh="ប្រុស";
$sexen="Male";
if ($studentInfo['sex']==2){
	$sexkh="ស្រី";
	$sexen="Female";
}
$logo=$this->baseUrl()."/images/logo.png";
$imageBackground=$this->baseUrl()."/images/logo.png";
$shortCutIco=$this->baseUrl()."/images/icon.ico";
$signCambo=$this->baseUrl()."/images/agreementsign.jpg";

if($scoreInfo['exam_type']==1){
$html='<html>
		<head>
			<meta charset="UTF-8">
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
			<link rel="shortcut icon" href="'.$shortCutIco.'" type="image/x-icon" />
			<style type="text/css">
			
			body{
			    min-height: 100vh;
			    display: flex;
			    flex-direction: column;
			}
			footer{
			    margin-top: auto;
			}
			table,
			table.khmerFont,
			table.studentInfo {
				page-break-inside:avoid;
				autosize : true;
				font-family: khmeros !important;
				font-size: 12px !important;
			}

			.cheader {
				line-height: 20px;
				white-space: nowrap;
				color:#000;
				font-weight: normal;
				font-family: '."'Times New Roman'".', khmermoullight;
			}
			.cheader td {
				line-height: 20px;
				white-space: nowrap;
				color:#000;
				font-weight: normal;
				text-align:center;
				font-family: '."'Times New Roman'".', khmermoullight;
			}
			.hover:hover {
				background: #ccc;
			}
			
			.blue {
				color: #4839bd;
			}

			.border-right-none {
				border-right: #fff solid 1px;
			}

			.borderBottom {
				border-bottom: 1px dashed #000 !important;
				border-right: 1px solid #fff;
				border-left: 1px solid #fff;
			}

			.borderSolidBottom {
				border-bottom: 2px solid #000 !important;
			}

			.teacherComment {
				min-height: 80px;
				border:1px solid #000;
			}
			.SingleBorder{
				border:1px solid #000;
			}

			.border-none {
				border: 1px solid #fff;
			}

			.fontBold {
				font-weight: bold;
			}

			.colorRed {
				color: #ff0000 !important;
				font-weight: bold;
				font-size: 14px;
			}

			.khmerBoldFont {
				font-family: '."'Times New Roman'".', khmermoullight;
			}

			.doubleBorder {
				border: 2px solid #000;
			}

			.circleHeader {
				padding: 5px;
				display: block;
			}
			.circleHeader-eng{
				text-transform: uppercase;
			}

			table tr {
				line-height: 22px;
			}
			.separateColumn{
				font-weight: bold;
				white-space: nowrap;
				color:red;
				font-size:14px;
				text-align: center;
				
			}
			#footer {
			   position:absolute;
			   bottom:0;
			   width:100%;
			   height:60px;   /* Height of the footer */
			   background:#6cf;
			}

			@media print {
				@page {
					page: A4;
					size: portrait;
					;
					margin: 0.8cm 0.8cm 0.2cm 0.8cm;
				}
			}
			.bg-grey{
				background: #b1c1ff !important;
			}
			.bg-blue{
				background: #2facff !important;
			}
			.bg-yellow{
				background: #fffb3b;
			}
			.bg-red{
				background: #ff4646!important;
			}
			.bg-grey-light{
				background: #d7d9db !important;
			}
			</style>
		</head>';

		$scoreTitle = ($scoreInfo['exam_type'] == 1) ? $scoreInfo['forMonthKhLabel'] : "SEMESTER " . $scoreInfo['for_semester']; 
		$resultTitleKh=(!empty($scoreInfo['title_score']))?$scoreInfo['title_score'] :$scoreTitle;
									
		$scoreTitle = ($scoreInfo['exam_type'] == 1) ? ucfirst($scoreInfo['forMonthEnLabel']) : "SEMESTER " . $scoreInfo['for_semester']; 
		$resultTitleEn=(!empty($scoreInfo['title_score_en']))? strtoupper($scoreInfo['title_score_en']) :$scoreTitle;
		$html.='<body>';
		
		$html.='
			<table class="pages-break" style="width:100%;background:#fff; margin: 0 auto;font-size:14px;break-after: page;">
					<tr >
						<td align="center" colspan="3">'.$headerScore.'</td>
					</tr>
					<tr style="height: 5px;">
						<td align="center" colspan="3"></td>
					</tr>
					<tr>
						<td colspan="3" align="center">
							<div class="khmerBoldFont" style="color:#000;line-height:20px; margin: 0;font-size:16px;margin-bottom:10px;">
								<span class="circleHeader">របាយការណ៍ប្រចាំខែ '.$resultTitleKh.'</span><br />
								<strong class="circleHeader-eng">REPORT FOR '.$resultTitleEn.'</strong>
							</div>
							<table class="studentInfo" cellpadding="0" style="width:100%;line-height:15px;">
								<tr>
									<td width="20%">អត្តលេខ / ID : </td>
									<td class="bold" align="left" width="23%"> '.$studentInfo['stu_code'].'</td>
									<td width="4%"></td>
									<td  width="25%">ថ្ងៃខែឆ្នាំកំណើត : </td>
									<td class="bold" align="left" width="23%"> '.$studentInfo['dob'].'</td>
								</tr>
								<tr>
									<td>ឈ្មោះសិស្ស : </td>
									<td  align="left" width="23%" class="khmerBoldFont"> '.$studentInfo['stu_khname'].'</td>
									<td></td>
									<td  width="25%">ថ្នាក់ទី : </td>
									<td class="bold" align="left" width="23%"> '.$scoreInfo['groupCode'].'</td>
								</tr>
								<tr>
									<td>'."Student's name in Latin".' : </td>
									<td class="bold" align="left" width="23%"> '.$studentInfo['last_name'] . ' ' . $studentInfo['stu_enname'].'</td>
									<td></td>
									<td>ឆ្នាំសិក្សា / Academic Year : </td>
									<td class="bold" align="left" width="23%">'.$scoreInfo['academicYearLabel'].'</td>
								</tr>
								<tr>
									<td>ភេទ / Gender : </td>
									<td class="bold" align="left" width="23%"> '.$sexkh . '-' . $sexen.'</td>
									<td></td>
									<td></td>
									<td class="bold" align="left" width="23%"></td>
								</tr>
							</table>
						</td>
					</tr>
		';
		$html.='<tr>
					<td colspan="3" id="exportExcel" valign="top">
						<table class="header" border="1" style="margin:0 auto;width:100%;border-collapse:collapse;border: solid 2px #000;">
				';
				$totalAveragescore = 0;
				$totalMaxScore = 0;
				$totalSubMaxScore = 0;
				$totalmultiAllSubject = 0;
				$totalmultiSubSubject = 0;
				$i = 0;
				$currentLang = 0;
				if (!empty($scoreSubjectList)) {
					foreach ($scoreSubjectList as $keyLang => $resultScore) {
						$i++;
						$maxScore = $resultScore['maxScore'] * $resultScore['multiSubject'];

						$totalMaxScore = $totalMaxScore + $maxScore;

						$grade = $dbgb->getMentionScore($resultScore['totalAverage'], $academicId, $scoreInfo['degreeId'], 1, null, $maxScore);
						if ($currentLang != $resultScore['subjectLang']) {
							if ($keyLang > 0) {
								$totalKhmerAverage = $totalAveragescore / $totalmultiSubSubject;
								$mentionGrade = $dbgb->getMentionScore($totalAveragescore, $academicId, $scoreInfo['degreeId'], 1, null, $totalSubMaxScore);
								$currentRanking = getRankingBySubjectLangId($scoreInfo,$currentLang);
								$currentRanking = empty($currentRanking) ? 0 : $currentRanking;
								$html.='
									<tr class="style hover">
										<td colspan="3" align="center">
											<strong>ការវាយតម្លៃរួម / Overall Assessment</strong>
										</td>
										<td align="center"><strong>'.$totalSubMaxScore.'</strong></td>
										
										<td colspan="2" align="center"><strong>'.number_format($totalAveragescore, 2).'</strong></td>
										<td colspan="2" align="center" class="bg-grey-light">
											<span class="separateColumn">'.number_format($totalKhmerAverage, 2).'</span>
											<span class="separateColumn">'.$currentRanking.'</span>
											<span class="separateColumn">'.$mentionGrade.'</span>
										</td>
									</tr>
								';
								
								
								
								$totalAveragescore = 0;
								$totalSubMaxScore = 0;
								$totalmultiSubSubject = 0;
								$i = 1;
							}
							if($scoreInfo['degreeId']==1){
								$html.=' 
									<tr class="cheader '.@$bgProgramColor[$resultScore['subjectLang']].' " align="center">
										<td>ល.រ<br />No.</td>
										<td colspan="2">'.@$subjectProgram[$resultScore['subjectLang']].'</td>
										<td>ពិន្ទុអតិបរមា <br />Maximum Score </td>
										<td colspan="2">ពិន្ទុ<br />Score</td>
										<td>និទ្ទេស<br />Grade</td>
										<td>ចំណាត់ថ្នាក់<br />Rank</td>
									</tr>
								';
							}else{
								$html.='
									<tr class="cheader '.@$bgProgramColor[$resultScore['subjectLang']].' " align="center">
										<td >ល.រ<br />No.</td>
										<td colspan="2">'.@$subjectProgram[$resultScore['subjectLang']].'</td>
										<td>ពិន្ទុអតិបរមា <br />Maximum Score </td>
										<td colspan="2">ពិន្ទុ<br />Total Score</td>
										<td>និទ្ទេស<br />Grade</td>
										<td>ចំណាត់ថ្នាក់<br />Rank</td>
									</tr>
								';
							}
						}
						
						$currentLang = $resultScore['subjectLang'];

						$totalmultiSubSubject = $totalmultiSubSubject + $resultScore['multiSubject']; //មេគុណសរុប
						$totalSubMaxScore = $totalSubMaxScore + $maxScore;

						$totalmultiAllSubject = $totalmultiAllSubject + $resultScore['multiSubject'];
						$totalAveragescore = $totalAveragescore + $resultScore['totalAverage'];
						
						if ($resultScore['innerSubject'] == 0) {
							$html.='
								<tr class="hover blackColor">
									<td align="center">'.$i.'</td>
									<td align="left">'.$resultScore['sub_name'].'</td>
									<td align="left">'.$resultScore['sub_name_en'].'</td>
									<td class="" align="center" style="white-space:nowrap;">'.$maxScore.'</td>
									<td colspan="2"  align="center">'.$resultScore['totalAverage'].'</td>
									<td align="center" class="colorRed">'.$grade.'</td>
									<td align="center">'.$resultScore['rankingSubject'].'</td>
								</tr>
							';
						} else {
							$issetMerge = 0;
							$rowspan = $resultScore['innerSubject'];
							foreach ($resultScore['innerSubjectList'] as $resultSubList) {
								$i++;
								$html.='<tr class="hover blackColor">
											<td align="center">'.$i.'</td>
											<td align="left">'.$resultSubList['subCriterialTitleKh'].'</td>
											<td align="left">'.$resultSubList['subCriterialTitleEng'].'</td>
											<td class="" align="center" style="white-space:nowrap;">'.$maxScore.'</td>
											<td align="center">'.$resultSubList['totalGrading'].'</td>
											';
									if ($issetMerge == 0) {
										$html.='
											<td rowspan="'.$rowspan.'" align="center">'.$resultScore['totalAverage'].'</td>
											<td class="colorRed" rowspan="'.$rowspan.'" align="center">'.$grade.'</td>
											<td align="center" rowspan="'.$rowspan.'">'.$resultScore['rankingSubject'].'</td>
										';
									}
								$html.='</tr>';
								$issetMerge = 1;
							}
						}
					}
				}
				$totalKhmerAverage = $totalAveragescore / $totalmultiSubSubject;
				$mentionGrade = $dbgb->getMentionScore($totalAveragescore, $academicId, $scoreInfo['degreeId'], 1, null, $totalSubMaxScore);
				$currentRanking = getRankingBySubjectLangId($scoreInfo,$currentLang);
				$currentRanking = empty($currentRanking) ? 0 : $currentRanking;
				$html.='
					<tr class="style hover">
						<td colspan="3" align="center">
							<strong>ការវាយតម្លៃរួម / Overall Assessment</strong>
						</td>
						<td align="center"><strong>'.$totalSubMaxScore.'</strong></td>
						
						<td  colspan="2" align="center"><strong>'.number_format($totalAveragescore, 2).'</strong></td>
						<td colspan="2" align="center">
							<span class="separateColumn">'.number_format($totalKhmerAverage, 2).'</span>
							<span class="separateColumn">'.$currentRanking.'</span>
							<span class="separateColumn">'.$mentionGrade.'</span>
						</td>
					</tr>
					<tr class="style hover bg-blue" style=" height: 40px;">
						<td rowspan="2" colspan="4" align="center" class="cheader">
							ពិន្ទុសរុប មធ្យមភាគ និងចំណាត់ថ្នាក់ Total Score Average  Rank
						</td>
						<td rowspan="2"  align="center" class="colorRed">'.$scoreInfo['totalScoreAvg'].'</td>
						<td rowspan="2" align="center" class="colorRed">'.$scoreInfo['totalAvg'].'</td>
						<td rowspan="2" align="center" class="colorRed">'.$dbgb->getMentionScore($scoreInfo['totalScoreAvg'], $academicId, $scoreInfo['degreeId'], 1, null, $totalMaxScore).'</td>
						<td rowspan="2"  align="center" class="colorRed">'.$scoreInfo['rank'] . '/' . $scoreInfo['amountStudent'].'</td>
					</tr>
				';
		$html.='</table>';
		$html.='<br />';
		
		$data = array(
			'groupId' => $groupId,
			'degree' => $degreeId,
			'semesterId' => $forSemester,
			'studentId' => $studentInfo['student_id'],
			'forMonth' => $forMonthId,
			'attStatus' => 3,
		);
		$dbAttendance = new Allreport_Model_DbTable_DbScoreTranscript();
		$permission = count($dbAttendance->countAttendenceTranscript($data));
		$data['attStatus'] = 2;
		$absent = count($dbAttendance->countAttendenceTranscript($data));
		$data['attStatus'] = 4;
		$late = count($dbAttendance->countAttendenceTranscript($data));
		
		$data['attStatus'] = 1;
		$minor = $dbAttendance->countDisplineTranscript($data);
		$data['attStatus'] = 2;
		$moderate = $dbAttendance->countDisplineTranscript($data);
		$data['attStatus'] = 3;
		$major = $dbAttendance->countDisplineTranscript($data);
									
		$html.='<table class="header" width="100%" border="1" style="width:100%; border-collapse:collapse;border: solid 2px #000;">
					<tr class="cheader bg-blue">
						<td colspan="2" class="khmerBoldFont" style=" text-align:center; border: solid 2px #000;">
							អវត្តមាន ABSENCE RECORD
						</td>
						<td colspan="2" class="khmerBoldFont" style=" text-align:center; border: solid 2px #000;">
							កិច្ចការវិន័យ DISCIPLINE RECORD
						</td>
					</tr>
					<tr class="style hover">
						<td align="left" style="white-space:nowrap;">ថ្ងៃឈប់មានច្បាប់ Days of Excused Absence</td>
						<td  align="center">'.$permission.'</td>
						<td align="left" style="white-space:nowrap;">ស្រាល Minor</td>
						<td  align="center">'.$minor.'</td>
					</tr>
					<tr class="style hover">
						<td align="left" style="white-space:nowrap;">ថ្ងៃឈប់ឥតច្បាប់ Days of Unexcused Absence</td>
						<td align="center" class="">'.$absent.'</td>
						<td align="left" style="white-space:nowrap;">មធ្យម Moderate</td>
						<td  align="center">'.$moderate.'</td>
					</tr>
					<tr class="style hover">
						<td align="left" style="white-space:nowrap;">ចំនួនពេលមកយឺត Times of Tardiness</td>
						<td align="center" class="">'.$late.'</td>
						<td align="left" style="white-space:nowrap;">ធ្ងន់ Major</td>
						<td  align="center">'.$major.'</td>
					</tr>
				</table>
			';
		$html.='<br />';
		$html.='
			<table class="khmerFont" width="100%" border="1" style="width:100%; border-collapse:collapse;border: solid 2px #000;">
				<tr>
					<td align="center" colspan="5" class="khmerBoldFont  bg-blue">ប្រព័ន្ធពិន្ទុ GRADING SYSTEM</td>
				</tr>
				<tr class="khmerBoldFont " align="center">
					<td align="center" colspan="2">របបពិន្ទុ<br />GRADING CRITERIA</td>
					<td align="center">ភាគរយ<br />PERCENTAGE</td>
					<td align="center" colspan="2">កម្រិតនិទ្ទេស <br />LETTER GRADE</td>
				</tr>
		';
				$ismergRow=0;
					$reGradingResult  = $dbgb->getGradingSystem($degreeId);
					if (!empty($reGradingResult)) foreach ($reGradingResult as $keygd => $rsgd) { 
						$html.='<tr align="center">';
						if(empty($rsgd['criteria']) AND $ismergRow==0){
							$ismergRow=1;
							$html.='<td align="left" colspan="2" rowspan="2" ></td>';
							
						}else if($ismergRow==0){
							$html.='
								<td align="left">'.$rsgd['criteria'].'</td>
								<td align="center" width="100px">'.$rsgd['percent'].'</td>
								';
						}
						$html.='<td align="center" width="100px">'.$rsgd['percentage'].'</td>
								<td align="center" width="100px">'.$rsgd['grade'].'</td>
								<td>'.$rsgd['interpretation'].'</td>
							';
						$html.='</tr>';
					}
			$html.='<tr class="" align="center">
						<td align="center" colspan="2">TOTAL SCORE</td>
						<td align="center">100%</td>
						<td colspan="2"></td>
					</tr>';
					
					
				$teacherComment = '';
				$commentType = '';
				if (!empty($evalueationList)) foreach ($evalueationList as $keycom => $rsComment) {
					if ($teacherComment == '') {
						$teacherComment = $rsComment['teacherComment'];
					}
					if ($commentType != $rsComment['commentType']) {
						$html.='
							<tr align="center">
								<td colspan="5" class=" doubleBorder khmerBoldFont">'.$rsComment['commentType'].'</td>
							</tr>';
						
					}
					$commentType = $rsComment['commentType'];
					$html.='
						<tr>
							<td align="left" colspan="4" class="">'.$rsComment['commentLabel'].'</td>
							<td align="center">'.$rsComment['ratingLabel'].'</td>
						</tr>';
				}
		$html.='</table>';
		$teacherComment = empty($teacherComment) ? "<br />" : $teacherComment;
		$html.='<table class="header" width="100%" style="width:100%; border-collapse:collapse;">
				<tr class="SingleBorder cheader  bg-blue">
					<td colspan="6" align="center"><span >'."មតិយោបល់របស់គ្រូ និងសំណូមពរ / TEACHER'S COMMENTS AND SUGESTION".'</span>
					</td>
				</tr>
				<tr >
					<td colspan="6" align="left" class="teacherComment">
						'.$teacherComment.'
					</td>
				</tr>
				<tr align="left">
					<td colspan="6" class=" khmerBoldFont">'."មតិយោបល់របស់មាតាបិតា និងសំណូមពរ /PARENT'S COMMENT AND SUGGESTION:".'</td>
				</tr>';
				for ($i = 0; $i <= 2; $i++) {
				$html.='
					<tr class="borderBottom">
						<td colspan="6" class="borderBottom">&nbsp;</td>
					</tr>
				';
				}	
			$html.='<tr>
					<td class="" width="30%"></td>
					<td colspan="4"></td>
					<td class="" width="30%"></td>
				</tr>
				<tr>
					<td>កាលបរិច្ឆេទ / Date:......./......./.......</td>
					<td colspan="4" class=""></td>
					<td>កាលបរិច្ឆេទ / Date:......./......./.......</td>
				</tr>
				<tr height="100px;">
					<td class="borderSolidBottom "></td>
					<td colspan="4"></td>
					<td class="borderSolidBottom "></td>
				</tr>
				<tr height="40px;">
					<td valign="top"> '."ហត្ថលេខាមាតាបិតា Parent's Signature".'</td>
					<td colspan="4"></td>
					<td valign="top">គ្រូបន្ទុកថ្នាក់ Homeroom Teacher</td>
				</tr>
				<tr height="130px;">
					<td valign="top" class="borderSolidBottom khmerBoldFont">បានឃើញ និងឯកភាព <br />SEEN AND APPROVED</td>
					<td colspan="4"></td>
					<td valign="top" class="borderSolidBottom "><strong>បានពិនិត្យត្រឹមត្រូវ / Checked</strong></td>
				</tr>
				<tr >
					<td>នាយករង / VICE PRINCIPLE</td>
					<td colspan="4"></td>
					<td>ការិយាល័យសិក្សា / Academic Office</td>
				</tr>
				<tfoot>
					<tr>
						<td>
							
						</td>
					</tr>
				</tfoot>
			</table>';
		
		
		
		$html.='
				</td>
			</tr>
		</table>';
		$html.='
			</body>
		</html>';
}else if($scoreInfo['exam_type']==2){
	
	$semesterScale = (empty($scoreInfo['semesterTotalAverage'])) ? 50 : $scoreInfo['semesterTotalAverage'];
	$SemesterKhAvg = $scoreInfo['totalKhAvg'];
	$SemesterEnAvg = $scoreInfo['totalEnAvg'];
	$SemesterChAvg = $scoreInfo['totalChAvg'];
				
	$html='<html>
		<head>
			<meta charset="UTF-8">
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
			<link rel="shortcut icon" href="'.$shortCutIco.'" type="image/x-icon" />
			<style type="text/css">
			
			body{
			    min-height: 100vh;
			    display: flex;
			    flex-direction: column;
			}
			footer{
			    margin-top: auto;
			}
			table,
			table.khmerFont,
			table.studentInfo {
				page-break-inside:avoid;
				autosize : true;
				font-family: khmeros !important;
				font-size: 12px !important;
			}

			.cheader {
				line-height: 20px;
				white-space: nowrap;
				color:#000;
				font-weight: normal;
				font-family: '."'Times New Roman'".', khmermoullight;
			}
			.cheader td {
				line-height: 20px;
				white-space: nowrap;
				color:#000;
				font-weight: normal;
				text-align:center;
				font-family: '."'Times New Roman'".', khmermoullight;
			}
			.hover:hover {
				background: #ccc;
			}
			
			.blue {
				color: #4839bd;
			}

			.border-right-none {
				border-right: #fff solid 1px;
			}

			.borderBottom {
				border-bottom: 1px dashed #000 !important;
				border-right: 1px solid #fff;
				border-left: 1px solid #fff;
			}

			.borderSolidBottom {
				border-bottom: 2px solid #000 !important;
			}

			.teacherComment {
				min-height: 80px;
				border:1px solid #000;
			}
			.SingleBorder{
				border:1px solid #000;
			}

			.border-none {
				border: 1px solid #fff;
			}

			.fontBold {
				font-weight: bold;
			}

			.colorRed {
				color: #ff0000 !important;
				font-weight: bold;
				font-size: 14px;
			}

			.khmerBoldFont {
				font-family: '."'Times New Roman'".', khmermoullight;
			}

			.doubleBorder {
				border: 2px solid #000;
			}

			.circleHeader {
				padding: 5px;
				display: block;
			}
			.circleHeader-eng{
				text-transform: uppercase;
			}

			table tr {
				line-height: 22px;
			}
			.separateColumn{
				font-weight: bold;
				white-space: nowrap;
				color:red;
				font-size:14px;
				text-align: center;
				
			}
			#footer {
			   position:absolute;
			   bottom:0;
			   width:100%;
			   height:60px;   /* Height of the footer */
			   background:#6cf;
			}

			@media print {
				@page {
					page: A4;
					size: portrait;
					;
					margin: 0.8cm 0.8cm 0.2cm 0.8cm;
				}
			}
			.bg-grey{
				background: #b1c1ff !important;
			}
			.bg-blue{
				background: #2facff !important;
			}
			.bg-yellow{
				background: #fffb3b;
			}
			.bg-red{
				background: #ff4646!important;
			}
			.bg-grey-light{
				background: #d7d9db !important;
			}
			</style>
		</head>';
		
		$arrRomanNum = array(1 => "I", 2 => "II");
		$romanNumber = empty($arrRomanNum[$scoreInfo['for_semester']]) ? "I" : $arrRomanNum[$scoreInfo['for_semester']];
		$resultTitleKh =  "ឆមាសទី " . $dbgb->getNumberInkhmer($scoreInfo['for_semester']); 
		$resultTitleEn= "SEMESTER ". $romanNumber;
		
		$html.='<body>';
		$html.='
			<table style="width:100%;background:#fff; margin: 0 auto;font-size:14px;break-after: page;">
					<tr >
						<td align="center" colspan="3">'.$headerScore.'</td>
					</tr>
					<tr style="height: 5px;">
						<td align="center" colspan="3"></td>
					</tr>
					<tr>
						<td colspan="3" align="center">
							<div class="khmerBoldFont" style="color:#000;line-height:20px; margin: 0;font-size:16px;margin-bottom:10px;">
								<span class="circleHeader">របាយការណ៍ប្រចាំ '.$resultTitleKh.'</span><br />
								<strong class="circleHeader-eng">REPORT FOR '.$resultTitleEn.'</strong>
							</div>
							<table class="studentInfo" cellpadding="0" style="width:100%;line-height:15px;">
								<tr>
									<td width="20%">អត្តលេខ / ID : </td>
									<td class="bold" align="left" width="23%"> '.$studentInfo['stu_code'].'</td>
									<td width="4%"></td>
									<td  width="25%">ថ្ងៃខែឆ្នាំកំណើត : </td>
									<td class="bold" align="left" width="23%"> '.$studentInfo['dob'].'</td>
								</tr>
								<tr>
									<td>ឈ្មោះសិស្ស : </td>
									<td  align="left" width="23%" class="khmerBoldFont"> '.$studentInfo['stu_khname'].'</td>
									<td></td>
									<td  width="25%">ថ្នាក់ទី : </td>
									<td class="bold" align="left" width="23%"> '.$scoreInfo['groupCode'].'</td>
								</tr>
								<tr>
									<td>'."Student's name in Latin".' : </td>
									<td class="bold" align="left" width="23%"> '.$studentInfo['last_name'] . ' ' . $studentInfo['stu_enname'].'</td>
									<td></td>
									<td>ឆ្នាំសិក្សា / Academic Year : </td>
									<td class="bold" align="left" width="23%">'.$scoreInfo['academicYearLabel'].'</td>
								</tr>
								<tr>
									<td>ភេទ / Gender : </td>
									<td class="bold" align="left" width="23%"> '.$sexkh . '-' . $sexen.'</td>
									<td></td>
									<td></td>
									<td class="bold" align="left" width="23%"></td>
								</tr>
							</table>
						</td>
					</tr>
		';
		$html.='<tr>
					<td colspan="3" valign="top">
						<table class="khmerFont" border="1" style="margin:0 auto;width:100%;border-collapse:collapse;border: solid 2px #000;">
				';
				$totalAveragescore = 0;
				$totalMaxScore = 0;
				$totalSubMaxScore = 0;
				$totalmultiAllSubject = 0;
				$totalmultiSubSubject = 0;
				$i = 0;
				$currentLang = 0;
				if (!empty($scoreSubjectList)) {
					foreach ($scoreSubjectList as $keyLang => $resultScore) {
						$i++;
						$maxScore = $resultScore['maxScore'] * $resultScore['multiSubject'];

						$totalMaxScore = $totalMaxScore + $maxScore;

						$grade = $dbgb->getMentionScore($resultScore['totalAverage'], $academicId, $scoreInfo['degreeId'], 1, null, $maxScore);
						if ($currentLang != $resultScore['subjectLang']) {
							if ($keyLang > 0) {
								$totalmultiSubSubject = $totalSubMaxScore / $semesterScale;
								$totalKhmerAverage = $totalAveragescore / $totalmultiSubSubject;
								$mentionGrade = $dbgb->getMentionScore($totalAveragescore, $academicId, $scoreInfo['degreeId'], 1, null, $totalSubMaxScore);
								$currentRanking = getRankingBySubjectLangId($scoreInfo,$currentLang);
								$currentRanking = empty($currentRanking) ? 0 : $currentRanking;
								
								$semesterMonthlyAvgLang = 0;
								if ($currentLang == 1) {
									$semesterMonthlyAvgLang = $SemesterKhAvg;
								} elseif ($currentLang == 2) {
									$semesterMonthlyAvgLang = $SemesterEnAvg;
								} else {
									$semesterMonthlyAvgLang = $SemesterChAvg;
								}
								
								$rankLangOverlal=0;
								if ($currentLang == 1) {
									$rankLangOverlal = $scoreInfo['rankOverallKh'];
								} elseif ($currentLang == 2) {
									$rankLangOverlal = $scoreInfo['rankOverallEng'];
								} else {
									$rankLangOverlal = $scoreInfo['rankOverallCh'];
								}
								$overalSemesterLangAvg = ($semesterMonthlyAvgLang + $totalKhmerAverage) / 2;
								$html.='
									<tr class="style hover">
										<td colspan="3" align="center">
											<strong>ការវាយតម្លៃជារួមលើការប្រឡង / Overall Assessment of the Examination</strong>
										</td>
										<td align="center"><strong>'.number_format($totalKhmerAverage, 2).'</strong>
										</td>
										<td align="center"><strong>'.$totalSubMaxScore.'</strong></td>
										
										<td colspan="2" align="center"><strong>'.number_format($totalAveragescore, 2).'</strong></td>
										<td align="center" class="colorRed"><strong>'.$mentionGrade.'</strong></td>
										<td align="center"><strong>'.$currentRanking.'</strong></td>
									
									</tr>
									<tr class="style hover">
										<td colspan="3" align="center">
											<strong>មធ្យមភាគពិន្ទុខែប្រចាំឆមាស / Semester Monthly Average Score</strong>
										</td>
										<td align="center">
											<strong>'.$semesterMonthlyAvgLang.'</strong>
										</td>
										<td align="center" colspan="5" ></td>
									</tr>
									<tr class="style hover">
										<td colspan="3" align="center">
											<strong>ការវាយតម្លៃជារួមប្រចាំឆមាស / Overall Assessment of the Semester</strong>
										</td>
										<td align="center">
											<strong>'.number_format($overalSemesterLangAvg, 2).'</strong>
										</td>
										<td colspan="3" align="center"></td>
										<td align="center"><strong class="colorRed">'.$dbgb->getMentionScore($overalSemesterLangAvg, $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).'</strong></td>
										<td align="center"> 
											<strong>'.$rankLangOverlal.'</strong>
										</td>
									</tr>
								';
								$totalAveragescore = 0;
								$totalSubMaxScore = 0;
								$totalmultiSubSubject = 0;
								$i = 1;
							}
							
							if($scoreInfo['degreeId']==1){
								$html.='
									<tr class="cheader '.@$bgProgramColor[$resultScore['subjectLang']].' " align="center">
										<td>ល.រ<br />No.</td>
										<td colspan="2">'.@$subjectProgram[$resultScore['subjectLang']].'</td>
										<td>ពិន្ទុមធ្យមភាគ <br />Average Score </td>
										<td>ពិន្ទុអតិបរមា <br />Maximum Score </td>
										<td colspan="2">ពិន្ទុ<br />Score</td>
										<td>និទ្ទេស<br />Grade</td>
										<td>ចំណាត់ថ្នាក់<br />Rank</td>
									</tr>
								';
							}else{
								$html.='
									<tr class="cheader '.@$bgProgramColor[$resultScore['subjectLang']].' " align="center">
										<td>ល.រ<br />No.</td>
										<td colspan="2">'.@$subjectProgram[$resultScore['subjectLang']].'</td>
										<td>ពិន្ទុមធ្យមភាគ <br />Average Score </td>
										<td>ពិន្ទុអតិបរមា <br />Maximum Score </td>
										<td colspan="2">ពិន្ទុ<br />Total Score</td>
										<td>និទ្ទេស<br />Grade</td>
										<td>ចំណាត់ថ្នាក់<br />Rank</td>
									</tr>
								';
							}
						}
						
						
						$currentLang = $resultScore['subjectLang'];

						$totalmultiSubSubject = $totalmultiSubSubject + $resultScore['multiSubject']; //មេគុណសរុប
						$totalSubMaxScore = $totalSubMaxScore + $maxScore;

						$totalmultiAllSubject = $totalmultiAllSubject + $resultScore['multiSubject'];
						$totalAveragescore = $totalAveragescore + $resultScore['totalAverage'];
						
						$html.='
							<tr class="hover blackColor">
								<td align="center">'.$i.'</td>
								<td align="left">'.$resultScore['sub_name'].'</td>
								<td align="left">'.$resultScore['sub_name_en'].'</td>
							';
							if($i==1){
								$coountingSubject = getCountSubjectLang($scoreSubjectList,$currentLang);
								$html.='<td rowspan="'.$coountingSubject.'"></td>';
							}
						$html.='<td class="" align="center" style="white-space:nowrap;">'.$maxScore.'</td>
								<td colspan="2"  align="center">'.$resultScore['totalAverage'].'</td>
								<td align="center" class="colorRed">'.$grade.'</td>
								<td align="center">'.$resultScore['rankingSubject'].'</td>
							</tr>
						
						';
					}
				}
				
				$totalmultiSubSubject = $totalSubMaxScore / $semesterScale;
				$totalKhmerAverage = $totalAveragescore / $totalmultiSubSubject;
				
				$semesterMonthlyAvgLang = 0;
				if ($currentLang == 1) {
					$semesterMonthlyAvgLang = $SemesterKhAvg;
				} elseif ($currentLang == 2) {
					$semesterMonthlyAvgLang = $SemesterEnAvg;
				} else {
					$semesterMonthlyAvgLang = $SemesterChAvg;
				}
				$overalSemesterLangAvg = ($semesterMonthlyAvgLang + $totalKhmerAverage) / 2;
				
				$rankLangOverlal=0;
				if ($currentLang == 1) {
					$rankLangOverlal = $scoreInfo['rankOverallKh'];
				} elseif ($currentLang == 2) {
					$rankLangOverlal = $scoreInfo['rankOverallEng'];
				} else {
					$rankLangOverlal = $scoreInfo['rankOverallCh'];
				}
				$html.='
					<tr class="style hover">
						<td colspan="3" align="center">
							<strong>ការវាយតម្លៃជារួមលើការប្រឡង / Overall Assessment of the Examination</strong>
						</td>
						<td align="center"><strong>'.number_format($totalKhmerAverage, 2).'</strong></td>
						<td align="center"><strong>'.$totalSubMaxScore.'</strong></td>
										
						<td colspan="2" align="center"><strong>'.number_format($totalAveragescore, 2).'</strong></td>
						<td align="center" class="colorRed"><strong>'.$dbgb->getMentionScore($totalAveragescore, $academicId, $scoreInfo['degreeId'], 1, null, $totalSubMaxScore).'</strong></td>
						<td align="center"><strong>'.getRankingBySubjectLangId($scoreInfo,$currentLang).'</strong></td>		
					</tr>
					<tr class="style hover">
						<td colspan="3" align="center">
							<strong>មធ្យមភាគពិន្ទុខែប្រចាំឆមាស / Semester Monthly Average Score</strong>
						</td>
						<td align="center">
							<strong>'.$semesterMonthlyAvgLang.'</strong>
						</td>
						<td align="center" colspan="5" ></td>
					</tr>
					<tr class="style hover">
						<td colspan="3" align="center">
							<strong>ការវាយតម្លៃជារួមប្រចាំឆមាស / Overall Assessment of the Semester</strong>
						</td>
						<td align="center">
							<strong>'.number_format($overalSemesterLangAvg, 2).'</strong>
						</td>
						<td colspan="3" align="center"></td>
						<td align="center"><strong class="colorRed">'.$dbgb->getMentionScore($overalSemesterLangAvg, $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).'</strong></td>
						<td align="center"> 
							<strong>'.$rankLangOverlal.'</strong>
						</td>
					</tr>';
					
				$html.='<tr class="style hover bg-grey-light" style=" height: 40px;">
						<td  colspan="3" align="center" class="cheader">
							ការវាយតម្លៃជារួមលើការប្រឡង Overall Assessment of the Examination
						</td>
						<td  align="center" class="colorRed">'.$scoreInfo['totalAvg'].'</td>
						<td  align="center" class="colorRed">'.$totalMaxScore.'</td>
						<td  colspan="2"  align="center" class="colorRed">'.$scoreInfo['totalScoreAvg'].'</td>
						<td  align="center" class="colorRed">'.$dbgb->getMentionScore($scoreInfo['totalScoreAvg'], $academicId, $scoreInfo['degreeId'], 1, null, $totalMaxScore).'</td>
						<td   align="center" class="colorRed">'.$scoreInfo['rank'] . '/' . $scoreInfo['amountStudent'].'</td>
					</tr>
					<tr></tr>
					<tr class="style hover bg-grey-light" style=" height: 40px;">
						<td colspan="3" align="center" class="cheader bg-grey-light">
							មធ្យមភាគពិន្ទុខែប្រចាំឆមាស Semester Monthly Average Score
						</td>
						<td align="center" class="colorRed bg-grey-light">'.$scoreInfo['monthlySemesterAvg'].'</td>
						<td colspan="5"  align="center" ></td>
					</tr>
					<tr></tr>
					<tr class="style hover bg-blue" style=" height: 40px;">
						<td rowspan="2" colspan="3" align="center" class="cheader">
							ការវាយតម្លៃជារួមប្រចាំឆមាស Overall Assessment of the Semester
						</td>
						<td align="center" class="colorRed">'.$scoreInfo['overallAssessmentSemester'].'</td>
						<td colspan="3"  align="center" ></td>
						<td align="center" class="colorRed">'.$dbgb->getMentionScore($scoreInfo['overallAssessmentSemester'], $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).'</td>
						<td  align="center" class="colorRed">'.$scoreInfo['rankOverall'] . '/' . $scoreInfo['amountStudent'].'</td>
					</tr> 
					<tr></tr>
				';
				$html.='</table>';
				
				$html.='<br />';
		
		$data = array(
			'groupId' => $groupId,
			'semesterId' => $forSemester,
			'studentId' => $studentInfo['student_id'],
			'forMonth' => $forMonthId,
			'examType' => $examType,
			'attStatus' => 3,
		);
		$dbAttendance = new Allreport_Model_DbTable_DbScoreTranscript();
		$permission = count($dbAttendance->countAttendenceTranscript($data));
		$data['attStatus'] = 2;
		$absent = count($dbAttendance->countAttendenceTranscript($data));
		$data['attStatus'] = 4;
		$late = count($dbAttendance->countAttendenceTranscript($data));
		
		$data['attStatus'] = 1;
		$minor = $dbAttendance->countDisplineTranscript($data);
		$data['attStatus'] = 2;
		$moderate = $dbAttendance->countDisplineTranscript($data);
		$data['attStatus'] = 3;
		$major = $dbAttendance->countDisplineTranscript($data);
									
		$html.='<table class="header" width="100%" border="1" style="width:100%; border-collapse:collapse;border: solid 2px #000;">
					<tr class="cheader bg-blue">
						<td colspan="2" class="khmerBoldFont" style=" text-align:center; border: solid 2px #000;">
							អវត្តមាន ABSENCE RECORD
						</td>
						<td colspan="2" class="khmerBoldFont" style=" text-align:center; border: solid 2px #000;">
							កិច្ចការវិន័យ DISCIPLINE RECORD
						</td>
					</tr>
					<tr class="style hover">
						<td align="left" style="white-space:nowrap;">ថ្ងៃឈប់មានច្បាប់ Days of Excused Absence</td>
						<td  align="center">'.$permission.'</td>
						<td align="left" style="white-space:nowrap;">ស្រាល Minor</td>
						<td  align="center">'.$minor.'</td>
					</tr>
					<tr class="style hover">
						<td align="left" style="white-space:nowrap;">ថ្ងៃឈប់ឥតច្បាប់ Days of Unexcused Absence</td>
						<td align="center" class="">'.$absent.'</td>
						<td align="left" style="white-space:nowrap;">មធ្យម Moderate</td>
						<td  align="center">'.$moderate.'</td>
					</tr>
					<tr class="style hover">
						<td align="left" style="white-space:nowrap;">ចំនួនពេលមកយឺត Times of Tardiness</td>
						<td align="center" class="">'.$late.'</td>
						<td align="left" style="white-space:nowrap;">ធ្ងន់ Major</td>
						<td  align="center">'.$major.'</td>
					</tr>
				</table>
			';
		$html.='<br />';
		$html.='
			<table class="khmerFont" width="100%" border="1" style="width:100%; border-collapse:collapse;border: solid 2px #000;">
				<tr class="khmerBoldFont bg-blue " align="center">
					<td class="khmerBoldFont " align="center" width="20%" colspan="2">របាយការណ៍សម្រាប់<br />REPORT FOR</td>
					<td class="khmerBoldFont " align="center" width="20%">ឆមាសទី១<br />FIRST SEMESTER</td>
					<td class="khmerBoldFont " align="center" width="20%">ឆមាសទី២ <br />SECOND SEMESTER</td>
					<td class="khmerBoldFont " align="center" width="20%">ប្រចាំឆ្នាំ<br />ANNUAL</td>
					<td class="khmerBoldFont " align="center" width="20%">លទ្ធផល <br />RESULT</td>
				</tr>';
				if($forSemester==1){
					$html.='<tr class="khmerBoldFont " align="center">
						<td class="khmerBoldFont " colspan="2">ពិន្ទុសរុប<br />Total Score</td>
						<td align="center"><strong>'.$scoreInfo['totalScoreAvg'].'</strong></td>
						<td align="center"></td>
						<td></td>
						<td></td>

					</tr>
					<tr class="khmerBoldFont " align="center">
						<td class="khmerBoldFont "colspan="2">មធ្យមភាគពិន្ទុ<br />Average Score</td>
						<td align="center"><strong>'.$scoreInfo['overallAssessmentSemester'].'</strong></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr  align="center">
						<td class="khmerBoldFont " colspan="2">និទ្ទេស និងចំណាត់ថ្នាក់<br />Letter Grade And Rank</td>
						<td class="" align="center"><strong class="colorRed">'.$dbgb->getMentionScore($scoreInfo['overallAssessmentSemester'], $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).'  '.$scoreInfo['rankOverall'] . '/' . $scoreInfo['amountStudent'].'</strong></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>';
				}else{
					$html.='<tr class="khmerBoldFont " align="center">
						<td class="khmerBoldFont " colspan="2">ពិន្ទុសរុប<br />Total Score</td>
						<td align="center"></td>
						<td align="center"><strong>'.$scoreInfo['totalScoreAvg'].'</strong></td>
						
						<td></td>
						<td></td>

					</tr>
					<tr class="khmerBoldFont " align="center">
						<td class="khmerBoldFont "colspan="2">មធ្យមភាគពិន្ទុ<br />Average Score</td>
						<td></td>
						<td align="center"><strong>'.$scoreInfo['overallAssessmentSemester'].'</strong></td>
						
						<td></td>
						<td></td>
					</tr>
					<tr  align="center">
						<td class="khmerBoldFont " colspan="2">និទ្ទេស និងចំណាត់ថ្នាក់<br />Letter Grade And Rank</td>
						<td></td>
						<td class="" align="center"><strong class="colorRed">'.$dbgb->getMentionScore($scoreInfo['overallAssessmentSemester'], $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).'  '.$scoreInfo['rankOverall'] . '/' . $scoreInfo['amountStudent'].'</strong></td>
						
						<td></td>
						<td></td>
					</tr>';
				}

			$html.='</table>';
		$html.='
			<table class="khmerFont" width="100%" border="1" style="width:100%; border-collapse:collapse;border: solid 2px #000;">
				<tr align="center">
					<td align="center" colspan="6" class=" khmerBoldFont bg-blue">ប្រព័ន្ធពិន្ទុ GRADING SYSTEM</td>
				</tr>
				<tr class="khmerBoldFont " align="center">
					<td align="center" colspan="2">របបពិន្ទុ<br />GRADING CRITERIA</td>
					<td align="center">ភាគរយ<br />PERCENTAGE</td>
					<td align="center">កម្រិត <br />GRADE</td>
					<td align="center">និទ្ទេស<br />INTERPRETATION</td>
					<td align="center"><label style="white-space: nowrap;">ការសម្រេចផល និងការខិតខំប្រឹងប្រែង</label><br />ACHIEVMENT AND EFFORT</td>
				</tr>
		';
				$ismergRow=0;
					$reGradingResult  = $dbgb->getGradingSystem($degreeId);
					if (!empty($reGradingResult)) foreach ($reGradingResult as $keygd => $rsgd) { 
						$html.='<tr align="center">';
						
						if ($keygd == 0) {
							$html.='
								<td align="center" colspan="2" rowspan="'.count($reGradingResult).'" class="khmerBoldFont">
									<span>Semester <sub>Avg</sub> = </span>
									<div class="frac">
										<span>Monthly <sub>Avg</sub> + Exam <sub>Avg</sub></span>
										<span class="symbol">/</span>
										<span class="bottom">2</span>
									</div>
								</td>
							';
						}
						
						$html.='<td align="center">'.$rsgd['percentage'].'</td>
								<td align="center">'.$rsgd['grade'].'</td>
								<td align="center">'.$rsgd['interpretation'].'</td>
								<td>'.$rsgd['achievment'].'</td>
							';
						$html.='</tr>';
					}
			$html.='<tr class="" align="center">
						<td align="center" colspan="2">TOTAL SCORE</td>
						<td align="center">100%</td>
						<td colspan="2"></td>
					</tr>';
					
					
				$teacherComment = '';
				$commentType = '';
				if (!empty($evalueationList)) foreach ($evalueationList as $keycom => $rsComment) {
					if ($teacherComment == '') {
						$teacherComment = $rsComment['teacherComment'];
					}
					if ($commentType != $rsComment['commentType']) {
						$html.='
							<tr align="center">
								<td colspan="5" class=" doubleBorder khmerBoldFont">'.$rsComment['commentType'].'</td>
							</tr>';
						
					}
					$commentType = $rsComment['commentType'];
					$html.='
						<tr>
							<td align="left" colspan="4" class="">'.$rsComment['commentLabel'].'</td>
							<td align="center">'.$rsComment['ratingLabel'].'</td>
						</tr>';
				}
		$html.='</table>';
		$teacherComment = empty($teacherComment) ? "<br />" : $teacherComment;
		$html.='<table class="header" width="100%" style="width:100%; border-collapse:collapse;">
				<tr class="SingleBorder cheader  bg-blue">
					<td colspan="6" align="center"><span >'."មតិយោបល់របស់គ្រូ និងសំណូមពរ / TEACHER'S COMMENTS AND SUGESTION".'</span>
					</td>
				</tr>
				<tr >
					<td colspan="6" align="left" class="teacherComment">
						'.$teacherComment.'
					</td>
				</tr>
				<tr align="left">
					<td colspan="6" class=" khmerBoldFont">'."មតិយោបល់របស់មាតាបិតា និងសំណូមពរ /PARENT'S COMMENT AND SUGGESTION:".'</td>
				</tr>';
				for ($i = 0; $i <= 2; $i++) {
				$html.='
					<tr class="borderBottom">
						<td colspan="6" class="borderBottom">&nbsp;</td>
					</tr>
				';
				}	
			$html.='<tr>
					<td class="" width="30%"></td>
					<td colspan="4"></td>
					<td class="" width="30%"></td>
				</tr>
				<tr>
					<td>កាលបរិច្ឆេទ / Date:......./......./.......</td>
					<td colspan="4" class=""></td>
					<td>កាលបរិច្ឆេទ / Date:......./......./.......</td>
				</tr>
				<tr height="100px;">
					<td class="borderSolidBottom "></td>
					<td colspan="4"></td>
					<td class="borderSolidBottom "></td>
				</tr>
				<tr height="40px;">
					<td valign="top"> '."ហត្ថលេខាមាតាបិតា Parent's Signature".'</td>
					<td colspan="4"></td>
					<td valign="top">គ្រូបន្ទុកថ្នាក់ Homeroom Teacher</td>
				</tr>
				<tr height="130px;">
					<td valign="top" class="borderSolidBottom khmerBoldFont">បានឃើញ និងឯកភាព <br />SEEN AND APPROVED</td>
					<td colspan="4"></td>
					<td valign="top" class="borderSolidBottom "><strong>បានពិនិត្យត្រឹមត្រូវ / Checked</strong></td>
				</tr>
				<tr >
					<td>នាយករង / VICE PRINCIPLE</td>
					<td colspan="4"></td>
					<td>ការិយាល័យសិក្សា / Academic Office</td>
				</tr>
				<tfoot>
					<tr>
						<td>
							
						</td>
					</tr>
				</tfoot>
			</table>';
			
		$html.='
				</td>
			</tr>
		</table>';				
	$html.="
		</body>
	</html>";
	
}else {
	
	$semesterScale = (empty($scoreInfo['semesterTotalAverage'])) ? 50 : $scoreInfo['semesterTotalAverage'];
	$SemesterKhAvg = $scoreInfo['totalKhAvg'];
	$SemesterEnAvg = $scoreInfo['totalEnAvg'];
	$SemesterChAvg = $scoreInfo['totalChAvg'];
				
	$html='<html>
		<head>
			<meta charset="UTF-8">
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
			<link rel="shortcut icon" href="'.$shortCutIco.'" type="image/x-icon" />
			<style type="text/css">
			
			body{
			    min-height: 100vh;
			    display: flex;
			    flex-direction: column;
			}
			footer{
			    margin-top: auto;
			}
			table,
			table.khmerFont,
			table.studentInfo {
				page-break-inside:avoid;
				autosize : true;
				font-family: khmeros !important;
				font-size: 12px !important;
			}

			.cheader {
				line-height: 20px;
				white-space: nowrap;
				color:#000;
				font-weight: normal;
				font-family: '."'Times New Roman'".', khmermoullight;
			}
			.cheader td {
				line-height: 20px;
				white-space: nowrap;
				color:#000;
				font-weight: normal;
				text-align:center;
				font-family: '."'Times New Roman'".', khmermoullight;
			}
			.hover:hover {
				background: #ccc;
			}
			
			.blue {
				color: #4839bd;
			}

			.border-right-none {
				border-right: #fff solid 1px;
			}

			.borderBottom {
				border-bottom: 1px dashed #000 !important;
				border-right: 1px solid #fff;
				border-left: 1px solid #fff;
			}

			.borderSolidBottom {
				border-bottom: 2px solid #000 !important;
			}

			.teacherComment {
				min-height: 80px;
				border:1px solid #000;
			}
			.SingleBorder{
				border:1px solid #000;
			}

			.border-none {
				border: 1px solid #fff;
			}

			.fontBold {
				font-weight: bold;
			}

			.colorRed {
				color: #ff0000 !important;
				font-weight: bold;
				font-size: 14px;
			}

			.khmerBoldFont {
				font-family: '."'Times New Roman'".', khmermoullight;
			}

			.doubleBorder {
				border: 2px solid #000;
			}

			.circleHeader {
				padding: 5px;
				display: block;
			}
			.circleHeader-eng{
				text-transform: uppercase;
			}

			table tr {
				line-height: 22px;
			}
			.separateColumn{
				font-weight: bold;
				white-space: nowrap;
				color:red;
				font-size:14px;
				text-align: center;
				
			}
			#footer {
			   position:absolute;
			   bottom:0;
			   width:100%;
			   height:60px;   /* Height of the footer */
			   background:#6cf;
			}

			@media print {
				@page {
					page: A4;
					size: portrait;
					;
					margin: 0.8cm 0.8cm 0.2cm 0.8cm;
				}
			}
			.bg-grey{
				background: #b1c1ff !important;
			}
			.bg-blue{
				background: #2facff !important;
			}
			.bg-yellow{
				background: #fffb3b;
			}
			.bg-red{
				background: #ff4646!important;
			}
			.bg-grey-light{
				background: #d7d9db !important;
			}
			</style>
		</head>';
		
		
		
		$scoreTitle = ($scoreInfo['exam_type'] == 1) ? $scoreInfo['forMonthKhLabel'] : "SEMESTER " . $scoreInfo['for_semester']; 
		$resultTitleKh=(!empty($scoreInfo['title_score']))?$scoreInfo['title_score'] :$scoreTitle;
									
		$scoreTitle = ($scoreInfo['exam_type'] == 1) ? ucfirst($scoreInfo['forMonthEnLabel']) : "SEMESTER " . $scoreInfo['for_semester']; 
		$resultTitleEn=(!empty($scoreInfo['title_score_en']))? strtoupper($scoreInfo['title_score_en']) :$scoreTitle;
		
		if($scoreInfo['exam_type'] == 3){
			$resultTitleKh =  "ឆ្នាំ "; 
			$resultTitleEn= "ANNUAL";
		}
		$html.='<body>';
		$html.='
			<table style="width:100%;background:#fff; margin: 0 auto;font-size:14px;break-after: page;">
					<tr >
						<td align="center" colspan="3">'.$headerScore.'</td>
					</tr>
					<tr style="height: 5px;">
						<td align="center" colspan="3"></td>
					</tr>
					<tr>
						<td colspan="3" align="center">
							<div class="khmerBoldFont" style="color:#000;line-height:20px; margin: 0;font-size:16px;margin-bottom:10px;">
								<span class="circleHeader">របាយការណ៍ប្រចាំ'.$resultTitleKh.'</span><br />
								<strong class="circleHeader-eng">REPORT FOR '.$resultTitleEn.'</strong>
							</div>
							<table class="studentInfo" cellpadding="0" style="width:100%;line-height:15px;">
								<tr>
									<td width="20%">អត្តលេខ / ID : </td>
									<td class="bold" align="left" width="23%"> '.$studentInfo['stu_code'].'</td>
									<td width="4%"></td>
									<td  width="25%">ថ្ងៃខែឆ្នាំកំណើត : </td>
									<td class="bold" align="left" width="23%"> '.$studentInfo['dob'].'</td>
								</tr>
								<tr>
									<td>ឈ្មោះសិស្ស : </td>
									<td  align="left" width="23%" class="khmerBoldFont"> '.$studentInfo['stu_khname'].'</td>
									<td></td>
									<td  width="25%">ថ្នាក់ទី : </td>
									<td class="bold" align="left" width="23%"> '.$scoreInfo['groupCode'].'</td>
								</tr>
								<tr>
									<td>'."Student's name in Latin".' : </td>
									<td class="bold" align="left" width="23%"> '.$studentInfo['last_name'] . ' ' . $studentInfo['stu_enname'].'</td>
									<td></td>
									<td>ឆ្នាំសិក្សា / Academic Year : </td>
									<td class="bold" align="left" width="23%">'.$scoreInfo['academicYearLabel'].'</td>
								</tr>
								<tr>
									<td>ភេទ / Gender : </td>
									<td class="bold" align="left" width="23%"> '.$sexkh . '-' . $sexen.'</td>
									<td></td>
									<td></td>
									<td class="bold" align="left" width="23%"></td>
								</tr>
							</table>
						</td>
					</tr>
		';
		$html.='<tr>
					<td colspan="3" valign="top">
						<table class="khmerFont" border="1" style="margin:0 auto;width:100%;border-collapse:collapse;border: solid 2px #000;">
				';
				$totalAveragescore = 0;
				$totalMaxScore = 0;
				$totalSubMaxScore = 0;
				$totalmultiAllSubject = 0;
				$totalmultiSubSubject = 0;
				$i = 0;
				$currentLang = 0;
				if (!empty($scoreSubjectList)) {
					foreach ($scoreSubjectList as $keyLang => $resultScore) {
						$i++;
						$maxScore = $resultScore['maxScore'] * $resultScore['multiSubject'];
						$totalMaxScore = $totalMaxScore + $maxScore;
						$grade = $dbgb->getMentionScore($resultScore['totalAverage'], $academicId, $scoreInfo['degreeId'], 1, null, $maxScore);
						if ($currentLang != $resultScore['subjectLang']) {
							if ($keyLang > 0) {
								if ($currentLang == 1) {
									$overalSemesterLangAvg = $scoreInfo['OveralAvgKh'];
									$rankLangOverlal = $scoreInfo['rankOverallKh'];
								} elseif ($currentLang == 2) {
									$overalSemesterLangAvg = $scoreInfo['OveralAvgEng'];
									$rankLangOverlal = $scoreInfo['rankOverallEng'];
								} else {
									$overalSemesterLangAvg = $scoreInfo['OveralAvgCh'];
									$rankLangOverlal = $scoreInfo['rankOverallCh'];
								}
								$html.='
								<tr class="style hover">
									<td colspan="3" align="center" >
									<strong>រង្វាយតម្លៃជារួមប្រចាំឆ្នាំ Overall Annual Assessment</strong>
										 
									</td>
									<td align="center"><strong>'.number_format($overalSemesterLangAvg,2).'</strong></td>
									<td align="center" colspan="3"></td>
									<td class="" align="center"><strong class="colorRed">'.$dbgb->getMentionScore($overalSemesterLangAvg, $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).'</strong></td>
									<td align="center"><strong>'.$rankLangOverlal.'</strong></td>
								</tr>';
								$totalAveragescore = 0;
								$totalSubMaxScore = 0;
								$totalmultiSubSubject = 0;
								$i = 1;
							}
							
							if($scoreInfo['degreeId']==1){
								$html.='
									<tr class="cheader '.@$bgProgramColor[$resultScore['subjectLang']].' " align="center">
										<td>ល.រ<br />No.</td>
										<td colspan="2">'.@$subjectProgram[$resultScore['subjectLang']].'</td>
										<td>ពិន្ទុមធ្យមភាគ <br />Average Score </td>
										<td>ពិន្ទុអតិបរមា <br />Maximum Score </td>
										<td colspan="2">ពិន្ទុ<br />Score</td>
										<td>និទ្ទេស<br />Grade</td>
										<td>ចំណាត់ថ្នាក់<br />Rank</td>
									</tr>
								';
							}else{
								$html.='
									<tr class="cheader '.@$bgProgramColor[$resultScore['subjectLang']].' " align="center">
										<td>ល.រ<br />No.</td>
										<td colspan="2">'.@$subjectProgram[$resultScore['subjectLang']].'</td>
										<td>ពិន្ទុមធ្យមភាគ <br />Average Score </td>
										<td>ពិន្ទុអតិបរមា <br />Maximum Score </td>
										<td colspan="2">ពិន្ទុ<br />Total Score</td>
										<td>និទ្ទេស<br />Grade</td>
										<td>ចំណាត់ថ្នាក់<br />Rank</td>
									</tr>
								';
							}
						}
						
						
						$currentLang = $resultScore['subjectLang'];

						$totalmultiSubSubject = $totalmultiSubSubject + $resultScore['multiSubject']; //មេគុណសរុប
						$totalSubMaxScore = $totalSubMaxScore + $maxScore;

						$totalmultiAllSubject = $totalmultiAllSubject + $resultScore['multiSubject'];
						$totalAveragescore = $totalAveragescore + $resultScore['totalAverage'];
						
						$html.='
							<tr class="hover blackColor">
								<td align="center">'.$i.'</td>
								<td align="left">'.$resultScore['sub_name'].'</td>
								<td align="left">'.$resultScore['sub_name_en'].'</td>
							';
							if($i==1){
								$coountingSubject = getCountSubjectLang($scoreSubjectList,$currentLang);
								$html.='<td rowspan="'.$coountingSubject.'"></td>';
							}
						$html.='<td class="" align="center" style="white-space:nowrap;">'.$maxScore.'</td>
								<td colspan="2"  align="center">'.$resultScore['totalAverage'].'</td>
								<td align="center" class="colorRed">'.$grade.'</td>
								<td align="center">'.$resultScore['rankingSubject'].'</td>
							</tr>
						
						';
					}
				}
				$rankOverall = 0;
				$overalSemesterLangAvg = 0;
				if ($currentLang == 1) {
					$overalSemesterLangAvg = $scoreInfo['OveralAvgKh'];
					$rankOverall = $scoreInfo['rankOverallKh'];
				} elseif ($currentLang == 2) {
					$overalSemesterLangAvg = $scoreInfo['OveralAvgEng'];
					$rankOverall = $scoreInfo['rankOverallEng'];
				} else {
					$overalSemesterLangAvg = $scoreInfo['OveralAvgCh'];
					$rankOverall = $scoreInfo['rankOverallCh'];
				}
				$html.='
					<tr class="style hover">
							<td colspan="3" align="center" >
							  <strong>រង្វាយតម្លៃជារួមប្រចាំឆ្នាំ Overall Annual Assessment</strong>
							</td>
							<td align="center"><strong>'.number_format($overalSemesterLangAvg,2).'</strong></td>
							<td align="center" colspan="3"></td>
							<td class="" align="center"><strong class="colorRed">'.$dbgb->getMentionScore($overalSemesterLangAvg, $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).'</strong></td>
							<td align="center">'.$rankOverall.'</td>
					</tr>
				';
					
				$html.='
					
					<tr class="style hover bg-blue" style=" height: 40px;">
						<td colspan="3" align="center" >
							<strong>រង្វាយតម្លៃជារួមប្រចាំឆ្នាំ Overall Annual Assessment</strong>
						</td>
						<td class="" align="center"><strong>'.$scoreInfo['overallAssessmentSemester'].'</strong></td>
						<td colspan="3" align="center"></td>
						<td align="center"><strong class="colorRed">'.$dbgb->getMentionScore($scoreInfo['overallAssessmentSemester'], $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).'</strong></td>
						<td class="" align="center"><strong class="colorRed">'.$scoreInfo['rankOverall'] . '/' . $scoreInfo['amountStudent'].'</strong></td>
					</tr>
									
					
				';
				$html.='</table>';
				
				$html.='<br />';
		
		$data = array(
			'groupId' => $groupId,
			'semesterId' => $forSemester,
			'studentId' => $studentInfo['student_id'],
			'forMonth' => $forMonthId,
			'examType' => $examType,
			'attStatus' => 3,
		);
		$dbAttendance = new Allreport_Model_DbTable_DbScoreTranscript();
		$permission = count($dbAttendance->countAttendenceTranscript($data));
		$data['attStatus'] = 2;
		$absent = count($dbAttendance->countAttendenceTranscript($data));
		$data['attStatus'] = 4;
		$late = count($dbAttendance->countAttendenceTranscript($data));
		
		$data['attStatus'] = 1;
		$minor = $dbAttendance->countDisplineTranscript($data);
		$data['attStatus'] = 2;
		$moderate = $dbAttendance->countDisplineTranscript($data);
		$data['attStatus'] = 3;
		$major = $dbAttendance->countDisplineTranscript($data);
									
		$html.='<table class="header" width="100%" border="1" style="width:100%; border-collapse:collapse;border: solid 2px #000;">
					<tr class="cheader bg-blue">
						<td colspan="2" class="khmerBoldFont" style=" text-align:center; border: solid 2px #000;">
							អវត្តមាន ABSENCE RECORD
						</td>
						<td colspan="2" class="khmerBoldFont" style=" text-align:center; border: solid 2px #000;">
							កិច្ចការវិន័យ DISCIPLINE RECORD
						</td>
					</tr>
					<tr class="style hover">
						<td align="left" style="white-space:nowrap;">ថ្ងៃឈប់មានច្បាប់ Days of Excused Absence</td>
						<td  align="center">'.$permission.'</td>
						<td align="left" style="white-space:nowrap;">ស្រាល Minor</td>
						<td  align="center">'.$minor.'</td>
					</tr>
					<tr class="style hover">
						<td align="left" style="white-space:nowrap;">ថ្ងៃឈប់ឥតច្បាប់ Days of Unexcused Absence</td>
						<td align="center" class="">'.$absent.'</td>
						<td align="left" style="white-space:nowrap;">មធ្យម Moderate</td>
						<td  align="center">'.$moderate.'</td>
					</tr>
					<tr class="style hover">
						<td align="left" style="white-space:nowrap;">ចំនួនពេលមកយឺត Times of Tardiness</td>
						<td align="center" class="">'.$late.'</td>
						<td align="left" style="white-space:nowrap;">ធ្ងន់ Major</td>
						<td  align="center">'.$major.'</td>
					</tr>
				</table>
			';
		$html.='<br />';
		$statusRestult = 'Failed';
		$statusRestultKh = 'ធ្លាក់';
		if ($scoreInfo['overallAssessmentSemester'] >= ($semesterScale / 2)) {
			$statusRestult = 'Passed - Promoted ';
			$statusRestultKh = 'ជាប់ - ត្រូវបានឡើងថ្នាក់ ';
		}
		$html.='
			<table class="khmerFont" width="100%" border="1" style="width:100%; border-collapse:collapse;border: solid 2px #000;">
				<tr class="khmerBoldFont bg-blue " align="center">
					<td class="khmerBoldFont " align="center" width="20%" colspan="2">របាយការណ៍សម្រាប់<br />REPORT FOR</td>
					<td class="khmerBoldFont " align="center" width="20%">ឆមាសទី១<br />FIRST SEMESTER</td>
					<td class="khmerBoldFont " align="center" width="20%">ឆមាសទី២ <br />SECOND SEMESTER</td>
					<td class="khmerBoldFont " align="center" width="20%">ប្រចាំឆ្នាំ<br />ANNUAL</td>
					<td class="khmerBoldFont " align="center" width="20%">លទ្ធផល <br />RESULT</td>
				</tr>
				<tr class="khmerBoldFont " align="center">
					<td class="khmerBoldFont " colspan="2">ពិន្ទុសរុប<br />Total Score</td>
					<td align="center"><strong>'.$scoreInfo['totalScoreSemester1'].'</strong></td>
					<td align="center"><strong>'.$scoreInfo['totalScoreSemester2'].'</strong></td>
					<td align="center"><strong>'.$scoreInfo['totalScoreAvg'].'</strong></td>
					<td>'.$statusRestultKh.'</td>

				</tr>
				<tr class="khmerBoldFont " align="center">
					<td class="khmerBoldFont "colspan="2">មធ្យមភាគពិន្ទុ<br />Average Score</td>
					<td align="center"><strong>'.$scoreInfo['overalSemester1'].'</strong></td>
					<td align="center"><strong>'.$scoreInfo['overalSemester2'].'</strong></td>
					<td align="center"><strong>'.$scoreInfo['overallAssessmentSemester'].'</strong></td>
					<td>'.$statusRestult.'</td>
				</tr>
				<tr  align="center">
					<td class="khmerBoldFont " colspan="2">និទ្ទេស និងចំណាត់ថ្នាក់<br />Letter Grade And Rank</td>
					<td class="" align="center"><strong class="colorRed">'.$dbgb->getMentionScore($scoreInfo['overalSemester1'], $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).' '.$scoreInfo['rankSemester1'] . '/' . $scoreInfo['amountStudent'].'</strong></td>
					<td class="" align="center"><strong class="colorRed">'.$dbgb->getMentionScore($scoreInfo['overalSemester2'], $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).' '.$scoreInfo['rankSemester2'] . '/' . $scoreInfo['amountStudent'].'</strong></td>
					<td class="" align="center"><strong class="colorRed">'.$dbgb->getMentionScore($scoreInfo['overallAssessmentSemester'], $academicId, $scoreInfo['degreeId'], 1, null, $semesterScale).' '.$scoreInfo['rankOverall'] . '/' . $scoreInfo['amountStudent'].'</strong></td>
					<td></td>
				</tr>

			</table>
			';
		$html.='
			<table class="khmerFont" width="100%" border="1" style="width:100%; border-collapse:collapse;border: solid 2px #000;">
				<tr align="center">
					<td align="center" colspan="6" class=" khmerBoldFont bg-blue">ប្រព័ន្ធពិន្ទុ GRADING SYSTEM</td>
				</tr>
				<tr class="khmerBoldFont " align="center">
					<td align="center" colspan="2">របបពិន្ទុ<br />GRADING CRITERIA</td>
					<td align="center">ភាគរយ<br />PERCENTAGE</td>
					<td align="center">កម្រិត <br />GRADE</td>
					<td align="center">និទ្ទេស<br />INTERPRETATION</td>
					<td align="center"><label style="white-space: nowrap;">ការសម្រេចផល និងការខិតខំប្រឹងប្រែង</label><br />ACHIEVMENT AND EFFORT</td>
				</tr>
		';
				$ismergRow=0;
					$reGradingResult  = $dbgb->getGradingSystem($degreeId);
					if (!empty($reGradingResult)) foreach ($reGradingResult as $keygd => $rsgd) { 
						$html.='<tr align="center">';
						
						if ($keygd == 0) {
							$html.='
								<td align="center" colspan="2" rowspan="'.count($reGradingResult).'" class="khmerBoldFont">
									<span>Semester <sub>Avg</sub> = </span>
									<div class="frac">
										<span>Monthly <sub>Avg</sub> + Exam <sub>Avg</sub></span>
										<span class="symbol">/</span>
										<span class="bottom">2</span>
									</div>
								</td>
							';
						}
						
						$html.='<td align="center">'.$rsgd['percentage'].'</td>
								<td align="center">'.$rsgd['grade'].'</td>
								<td align="center">'.$rsgd['interpretation'].'</td>
								<td>'.$rsgd['achievment'].'</td>
							';
						$html.='</tr>';
					}
			$html.='<tr class="" align="center">
						<td align="center" colspan="2">TOTAL SCORE</td>
						<td align="center">100%</td>
						<td colspan="2"></td>
					</tr>';
					
					
				$teacherComment = '';
				$commentType = '';
				if (!empty($evalueationList)) foreach ($evalueationList as $keycom => $rsComment) {
					if ($teacherComment == '') {
						$teacherComment = $rsComment['teacherComment'];
					}
					if ($commentType != $rsComment['commentType']) {
						$html.='
							<tr align="center">
								<td colspan="5" class=" doubleBorder khmerBoldFont">'.$rsComment['commentType'].'</td>
							</tr>';
						
					}
					$commentType = $rsComment['commentType'];
					$html.='
						<tr>
							<td align="left" colspan="4" class="">'.$rsComment['commentLabel'].'</td>
							<td align="center">'.$rsComment['ratingLabel'].'</td>
						</tr>';
				}
		$html.='</table>';
		$teacherComment = empty($teacherComment) ? "<br />" : $teacherComment;
		$html.='<table class="header" width="100%" style="width:100%; border-collapse:collapse;">
				<tr class="SingleBorder cheader  bg-blue">
					<td colspan="6" align="center"><span >'."មតិយោបល់របស់គ្រូ និងសំណូមពរ / TEACHER'S COMMENTS AND SUGESTION".'</span>
					</td>
				</tr>
				<tr >
					<td colspan="6" align="left" class="teacherComment">
						'.$teacherComment.'
					</td>
				</tr>
				<tr align="left">
					<td colspan="6" class=" khmerBoldFont">'."មតិយោបល់របស់មាតាបិតា និងសំណូមពរ /PARENT'S COMMENT AND SUGGESTION:".'</td>
				</tr>';
				for ($i = 0; $i <= 2; $i++) {
				$html.='
					<tr class="borderBottom">
						<td colspan="6" class="borderBottom">&nbsp;</td>
					</tr>
				';
				}	
			$html.='<tr>
					<td class="" width="30%"></td>
					<td colspan="4"></td>
					<td class="" width="30%"></td>
				</tr>
				<tr>
					<td>កាលបរិច្ឆេទ / Date:......./......./.......</td>
					<td colspan="4" class=""></td>
					<td>កាលបរិច្ឆេទ / Date:......./......./.......</td>
				</tr>
				<tr height="100px;">
					<td class="borderSolidBottom "></td>
					<td colspan="4"></td>
					<td class="borderSolidBottom "></td>
				</tr>
				<tr height="40px;">
					<td valign="top"> '."ហត្ថលេខាមាតាបិតា Parent's Signature".'</td>
					<td colspan="4"></td>
					<td valign="top">គ្រូបន្ទុកថ្នាក់ Homeroom Teacher</td>
				</tr>
				<tr height="130px;">
					<td valign="top" class="borderSolidBottom khmerBoldFont">បានឃើញ និងឯកភាព <br />SEEN AND APPROVED</td>
					<td colspan="4"></td>
					<td valign="top" class="borderSolidBottom "><strong>បានពិនិត្យត្រឹមត្រូវ / Checked</strong></td>
				</tr>
				<tr >
					<td>នាយករង / VICE PRINCIPLE</td>
					<td colspan="4"></td>
					<td>ការិយាល័យសិក្សា / Academic Office</td>
				</tr>
				<tfoot>
					<tr>
						<td>
							
						</td>
					</tr>
				</tfoot>
			</table>';
			
		$html.='
				</td>
			</tr>
		</table>';				
	$html.="
		</body>
	</html>";
}

	$mpdf = new Mpdf();
	$mpdf->SetWatermarkImage($imageBackground);
	$mpdf->showWatermarkImage = true;
	
	$mpdf->SetMargins(1.0, 1, 1,1); // Set by default to TRUE
	$mpdf->SetDisplayMode('fullpage');
	$mpdf->WriteHTML($html);
	$mpdf->SetTitle('PROGRESS REPORT '.$scoreTitle);
	//$mpdf->addPage('P'); 
	$mpdf->output();
	
	
	function getCountSubjectLang($subjectArray,$subjectLang){
		if($subjectLang==1){
			$arrFilter = array_filter($subjectArray, function($subjectArray) {
				return $subjectArray['subjectLang'] == 1;
			});
			return count($arrFilter);
		}else if($subjectLang==2){
			$arrFilter = array_filter($subjectArray, function($subjectArray) {
				return $subjectArray['subjectLang'] == 2;
			});
			return count($arrFilter);
		}else{
			return 0;
		}
	}
	
	
	function getRankingBySubjectLangId($ResultData,$subjectLangId){
		$indexResult = array(
				1=>'rankingInKhmer',
				2=>'rankingInEnglish',
				3=>'rankingInChinese',
				);
		$resultValue = $indexResult[$subjectLangId];
		return $ResultData[$resultValue];
	}
	
	 function getHeaderReportPDF($branch_id = null, $forGenerate = 0)
	{
		$key = new Application_Model_DbTable_DbKeycode();
		$setting = $key->getKeyCodeMiniInv(TRUE);
		$tr = Application_Form_FrmLanguages::getCurrentlanguage();
		$str = "";

		if ($forGenerate == 1) {
			$baseUrl = PUBLIC_PATH;
			$styleLogo = "width:120px;";
		} else {
			$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
			$styleLogo = "max-width: 98%;max-height:90px;min-height:50px;";
		}

		$logo = $baseUrl . '/images/Logo/Logo.png';
		if (!empty($setting['logo'])) {
			if (file_exists(PUBLIC_PATH . "/images/logo/" . $setting['logo'])) {
				$logo = $baseUrl . '/images/logo/' . $setting['logo'];
			}
		}

		$school_khname = $tr->translate('SCHOOL_NAME');
		$school_name = $tr->translate('CUSTOMER_BRANCH_EN');
		$address = $tr->translate('CUSTOMER_ADDRESS');
		$tel = $tr->translate('CUSTOMER_TEL');
		$email =  $tr->translate('CUSTOMER_EMAIL');
		$website = $tr->translate('CUSTOMER_WEBSITE');
		if ($branch_id == null) {

			$school_khname = $tr->translate('SCHOOL_NAME');
			$school_name = $tr->translate('CUSTOMER_BRANCH_EN');
			$address = $tr->translate('CUSTOMER_ADDRESS');
			$tel = $tr->translate('CUSTOMER_TEL');
			$email =  $tr->translate('CUSTOMER_EMAIL');
			$website = $tr->translate('CUSTOMER_WEBSITE');
		} else {
			$db = new Application_Model_DbTable_DbGlobal();
			$rs = $db->getBranchInfo($branch_id);
			if (!empty($rs)) {

				if (!empty($rs['photo'])) {
					if (file_exists(PUBLIC_PATH . "/images/logo/" . $rs['photo'])) {
						$logo = $baseUrl . '/images/logo/' . $rs['photo'];
					}
				}

				$school_khname = $rs['school_namekh'];
				$school_name = $rs['school_nameen'];

				$address = $rs['br_address'];
				$tel = $rs['branch_tel'];
				$email = $rs['email'];
				$website = $rs['website'];
			}
		}

		$imgSing = "agreementsign.jpg";
		$str = '
		<table width="100%" style="white-space:nowrap;">
			<tbody>
				<tr>
					<td width="35%" valign="top"  style="text-align: left; font-family: ' . "'Times New Roman'" . ',' . "'Khmer OS Muol Light'" . ';">
						<img style="' . $styleLogo . ' margin-top:30px;" src="' . $logo . '">
					</td>
					<td width="30%" valign="top" style="font-size:11px;line-height: 18px;font-family: Khmer OS Battambang;">
					</td>
					<td width="35%" valign="top" style="font-family: ' . "'Times New Roman'" . ',' . "khmermoullight,'Khmer OS Muol Light'" . ';">
						<span style="font-size: 14px; color: #002c7b;">ព្រះរាជាណាចក្រកម្ពុជា</span><br />
						<span><span style="margin:0;padding:0;font-weight: 600; color: #002c7b; font-size: 12px;">KINGDOM OF CAMBODIA</span></span><br />
						<span style="font-size: 12px; color: #002c7b;">ជាតិ សាសនា ព្រះមហាក្សត្រ</span><br />
						<span><span style=" margin:0; padding:0; font-weight: 600; color: #002c7b;font-size: 10px; ">NATION RELIGION KING</span></span><br />
						<span><img style=" height: 12px; " src="' . $baseUrl . '/images/' . $imgSing . '"></span>
						
					</td>
				</tr>
			</tbody>
		</table>
		';
		return $str;
	}
?>