<?php 
    $request=Zend_Controller_Front::getInstance()->getRequest();
    $tr = Application_Form_FrmLanguages::getCurrentlanguage();
    $frm =  $this->form_search;
	
	$parameterserch =  basename($_SERVER['REQUEST_URI']);
	$urlsting = str_replace("&pages=".$this->currentPage,"",$parameterserch);
	$sign="?";
	if (!empty($urlsting)){
		$sign="&";
	}
?>
<title><?php echo $tr->translate("PAYMENT")?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<div class="col-sm-12 border-botom">
				<div class="col-sm-8 pd-0">
					<h4 class="m-b-0"><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('PAYMENT');?></h4>
				</div>
				<div class="col-sm-4 text-right">
				</div>
			</div>
	    </div>
		<div class="card-box">
			<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="get" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input dojoType="dijit.form.TextBox"   id="adv_search" name="adv_search" placeholder="<?php echo $tr->translate('SEARCH');?>....." value="<?php echo $this->adv_search['adv_search']; ?>" class="fullside" type="text">
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("study_year");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input id="group" />
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("degree");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input id="grade_all" />
                   </div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
                   		<select class="fullside" required="false" dojoType="dijit.form.FilteringSelect" id="customer_type" name="customer_type" >
							<option value="-1"><?php echo $tr->translate("ALL");?></option>
							<option value="1" <?php if($this->adv_search['customer_type']==1){ echo "selected";}?> ><?php echo $tr->translate("Existing Student");?></option>
							<option value="2" <?php if($this->adv_search['customer_type']==2){ echo "selected";}?> ><?php echo $tr->translate("Cutomer");?></option>
							<option value="3" <?php if($this->adv_search['customer_type']==3){ echo "selected";}?> ><?php echo $tr->translate("CRM");?></option>
							<option value="4" <?php if($this->adv_search['customer_type']==4){ echo "selected";}?> ><?php echo $tr->translate("Tested Student");?></option>
						</select>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   		<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box search-list">
			<?php if(!empty($this->row)) foreach($this->row AS $key=>$rs){?>
			<div class="col-md-3">
                <div class="text-center card-box-border">
					<div class="member-card">
						<span class="user-badge bg-warning" ><?php echo ($key+1).".) "; echo $rs['typeStudent'];?></span>
						<ul class="nav navbar-right panel_toolbox stusearch">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a target="_blank" href="<?php echo $this->baseUrl()."/registrar/payment/add/id/".$rs['stu_id'];?>"><?php echo $tr->translate('CREATE_PAYMENT');?></a>
									</li>
									<li>
										<a target="_blank" href="<?php echo $this->baseUrl()."/allreport/accounting/paymenthistory/id/".$rs['stu_id'];?>"><?php echo $tr->translate('PAYMENT_HISTORY');?></a>
									</li>
								</ul>
							</li>
						</ul>
							
						<div class="thumb-xl member-thumb m-b-10 center-block">
                       		<?php $photo = $this->baseUrl()."/images/no-profile.png";
                       			if (!empty($rs['photo'])){
                       				if (file_exists(PUBLIC_PATH."/images/photo/".$rs['photo'])){
                       					$photo = $this->baseUrl().'/images/photo/'.$rs['photo'];
                       				}
                       			}
                       		?>
                           	<img src="<?php echo $photo;?>" class=" img-thumbnail" alt="profile-image">
							<?php if ($rs['sex']==1){?>
                            <i class="fa fa-male member-star text-active" title="verified user"></i>
                            <?php }else{?>
                            <i class="fa fa-female member-star text-deactive" title="verified user"></i>
                            <?php }?>
							
                        </div>
						
						<div class="">
                       		<h4 class="blue m-b-5"><?php echo $rs['stu_code'];?></h4>
                       		<h4 class="m-b-5"><?php echo $rs['stu_khname'];?></h4>
                       		<h4 class="m-b-5"><?php echo $rs['stu_name'];?></h4>
                            <p class="text-muted"><span><?php echo $rs['academic_year'];?></span></p>
                       </div>
					   
					   <p class="text-muted info-list font-13">
                       		<span class="title-info"><?php echo $tr->translate('GROUP');?></span> : <span class="inf-value" ><?php echo $rs['group_name'];?></span><br />
                            <span class="title-info"><?php echo $tr->translate('DEGREE');?></span> : <span class="inf-value" ><?php echo $rs['degree'];?></span> <br />
                            <span class="title-info"><?php echo $tr->translate('GRADE');?></span> : <span class="inf-value" ><?php echo $rs['grade'];?></span><br />
                        </p>
					   
				   </div>
				</div>
			</div>
			<?php }?>
			
			 <?php 
             	if($this->countPages>1){ 
					$statpage = $this->currentPage - 5;
					$endpage = $this->currentPage + 5;
				 	if ($this->currentPage<=5){
				 		$statpage = 1;
				 		$endpage =10;
				 	}
                 if (!empty($this->countPages)){
						 ?>
			<div class="clearfix"></div>
            <div class="pagin text-center">
            	<nav aria-label="Page navigation example">
				  <ul class="pagination">
				  	<?php if($this->currentPage!=1){ ?>
				    <li class="page-item"><a class="page-link" href="<?php echo $urlsting.$sign."pages=".$this->previousPage;?>"><?php echo $tr->translate('Previous');?></a></li>
				    <?php }?>
				     <?php  $i=0; for( $i=1; $i<=$this->countPages; $i++){?>
           			 	<?php if ($statpage<=$i && $endpage>=$i){?>
				    <li class="page-item <?php if($i==$this->currentPage){ echo "active";}?>">
				    	<a class="page-link" href="<?php echo $urlsting.$sign."pages=".$i;?>"><?php echo $i;?></a>
				    </li>
				    	<?php }
					}?>
					<?php if($this->countPages!= $this->currentPage){ ?>
				    <li class="page-item"><a class="page-link" href="<?php echo $urlsting.$sign."pages=".$this->nextPage;?>"><?php echo $tr->translate('Next');?></a></li>
				    <?php }?>
				  </ul>
				</nav>
				<span><?php echo $tr->translate('Total Pages')." : ".$this->countPages." ".$tr->translate('Pages');?></span>
            </div>
             <?php }}?>
		</div>
		
	</div>
</div>

<style>
.card-box-border {
    background-color: #ffffff;
    border: 1px solid rgba(98, 103, 115, 0.2);
    padding: 10px;
    margin-bottom: 20px;
        color: #000;
        box-shadow: 1px 1px 2px #ccc;
}
span.user-badge.bg-warning {
    position: absolute;
    top: 5px;
    left: 0;
    padding: 5px 15px;
    border-radius: 20px;
    color: #ffffff;
    font-size: 11px;
    text-transform: uppercase;
    font-weight: bold;
    z-index: 1 !important;
}
.bg-warning {
    background: #009bcc !important;
}
.thumb-xl.member-thumb {
    position: relative;
    height: 100px;
    width: 85px;
}
.member-card p.text-muted.info-list {
    text-align: left;
    color: #0f2a5b;
    font-size: 12px;
    margin: 0;
}
.member-card img.img-thumbnail {
    width: 100%;
    height: 100%;
}
.member-card h4 {
    margin: 0;
    padding: 2px 0;
    font-size: 12px;
    line-height: 11px;
}
span.title-info {
    min-width: 30%;
    display: inline-block;
    font-weight: 600;
    color: #0f2a5b;
}
span.inf-value {
    white-space: nowrap;
    text-overflow: ellipsis;
    display: inline-block;
    width: 63%;
    overflow: hidden;
    vertical-align: bottom;
}

.member-card .member-star {
    position: absolute;
    bottom: 10px;
    right: 5px;
    background-color: #ffffff;
    height: 30px;
    width: 30px;
    border-radius: 50%;
    line-height: 26px;
    text-align: center;
    font-size: 18px;
    border: solid 2px;
}
.text-active {
    color: #009688;
}
.text-deactive {
    color: #ff1203;
}
.card-box.search-list {
    min-height: 400px;
}
a.btn.btn-default.btn-detail {
    background: #009688;
    padding: 10px;
    color: #fff;
}
a.btn.btn-default.btn-detail:hover {
    opacity: 0.8;
}
.blue{
	color: #08086b;
}

ul.nav.navbar-right.panel_toolbox.stusearch {
    min-width: 0;
}
ul.nav.navbar-right.panel_toolbox.stusearch li.dropdown a.dropdown-toggle {
    padding: 10px;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");

	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var oldBranch = "<?php echo empty($this->adv_search['branch_id'])?0:$this->adv_search['branch_id'];?>";
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade_all",
			name: "grade_all",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  

			}
		}, "grade_all");

		new dijit.form.FilteringSelect({
			store: group_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                      
			id: "group",
			name: "group",  
			class: 'fullside', 
			readonly:false,
			placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
			onChange: function() {  
				
			}
		}, "group");

		
		getallGrade();
		getAllGroupByAcademic();

		var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getAllGroupByAcademic();
	    });
	});

	url_getgroupbyAca = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getgroupbyacademic'));?>';
	function getAllGroupByAcademic(){
		dijit.byId('group').reset();
		study_year = dijit.byId('study_year').get('value');
		if(study_year=='' || study_year==-1){
			var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('group').set('store',group_store);  
			getAllGroupByBranch();
			return false;
		}
		dojo.xhrPost({
			url: url_getgroupbyAca,
			content:{
				'academic_year':study_year,'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				group_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('group').set('store',group_store);   
				if(oldstudy_year==study_year){
					dijit.byId('group').set('value','<?php echo $this->adv_search['group']?>');  
				}
			},
			error: function(err) {
			}
		});
	}

	url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getgroupbybranch'));?>';
	function getAllGroupByBranch(){
		dijit.byId('group').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('group').set('store',group_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getgroup,
			content:{
				'branch_id':branch_id,'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				group_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('group').set('store',group_store);   
				if(oldBranch==branch_id){
					dijit.byId('group').set('value','<?php echo $this->adv_search['group']?>');  
				}
			},
			error: function(err) {
			}
		});
	}
	
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade_all').set('store',grade_store);   
				dijit.byId('grade_all').attr('value','<?php echo $this->adv_search['grade_all']?>');  
			},
			error: function(err) {
			}
		});
	}
</script> 