<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_SERVICE')); 
//print_r($this->service); exit();
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox"); 
	
var service_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->service));?> );
dojo.ready(function(){	

	new dijit.form.FilteringSelect({
		store: service_store,
		autoComplete: true,                        
		required: true,                      
	    id: "title",
	    name: "title",  
	    tabindex: "1",         
	    class: 'fullside',  
	    placeHolder:"Selecte Category", 
	    onChange: function() {          
		   	service_id = dijit.byId('title').get('value');
		    if(service_id==-1){
		   		dijit.byId("popup_dept").show();
		    }
	   }
	}, "title");
}); 
</script>
<?php  $item= $this->frm;?>
<form  id='acc_item' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'service','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table cellspacing="10" width="50%" style="margin: 0 auto;">
		<tr>
			<td>
				<fieldset >
					<legend align="center" style="font-size: 18px;"><strong><?php echo $tr->translate("ADD_SERVICE");?></strong></legend><br />
					<table style="margin: 0 auto; width: 95%;" cellspacing="5">
						<tr>
							<td style="width:100px"><?php echo $tr->translate("SERVICE_TYPE")?></td>
							<td>
								<input id="title" />
							</td>
						</tr>
						<tr>
							<td style="width:100px"><?php echo $tr->translate("PROGRAM_TITLE")?></td>
							<td><?php  echo $item->getElement('add_title');?></td>
						</tr>
						<tr>
							<td style="width: 5px"><?php echo $tr->translate("DISCRIPTION")?></td>
							<td><?php  echo $item->getElement('description');?></td>
						</tr>
						<tr>
							<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
							<td><?php  echo $item->getElement('status');?></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
								<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
								<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>	
				</fieldset>		
			</td>
		</tr>
	</table>	
</form>

<script>
	var url_add_service = '<?php echo $this->url(array("module"=>"accounting","controller"=>"service","action"=>"submit")); ?>';
	function addService(){
		language = dijit.byId('p_title').get('value');
		dojo.xhrPost({
				url:url_add_service,
				form: dojo.byId("frm_add_service"),
				handleAs:"json",
				load: function(data) {
					//alert(data); 
					var Itemmake = { 
					     id: data,
						         name: dijit.byId('p_title').get('value')
						   };
			 	addDataToSelectbox(dijit.byId('title'), service_store, Itemmake, data);
			   dijit.byId('frm_add_service').reset();
			   hideDialog();
					
				},
				error: function(err) {
					alert(err);
				}
		});
	}
	function hideDialog() {		
		dijit.byId("popup_dept").hide();
	}

</script>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:40%;" id="popup_dept" >
		<form style="background-color: buttonface;" id='frm_add_service' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate("បន្ថែមប្រភេទសេវាកម្ម");?></legend><br />
					<table style="margin: 0 auto; width: 95%;" cellspacing="5">
						<tr>
							<td style="width:100px"><?php echo $tr->translate("Title")?></td>
							<td><input class="fullside" tabindex="1" value="" dojoType="dijit.form.ValidationTextBox" name="p_title" id="p_title" type="text" required="required" /></td>
						</tr>
						<tr>
							<td>ពណ៌នា</td>
							<td>
								<textarea class="fullside"   style=" height: 40px !important;"
										tabindex="2" dojoType=""  id="note" name=note ></textarea>
							</td>
						</tr>
						<tr>
							<td style="width:100px"><?php echo $tr->translate("Type")?></td>
							<td>
								<select class="fullside"  tabindex="3" name="type" id="type" dojoType="dijit.form.FilteringSelect" >
									    <option value="1"><?php echo $tr->translate("SERVICE")?></option>
									    <option value="2"><?php echo $tr->translate("PROGRAM")?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td style="width:100px"><?php echo $tr->translate("Status")?></td>
							<td>
								<select class="fullside"  tabindex="3" name="status_p" id="status_p" dojoType="dijit.form.FilteringSelect" >
									    <option value="1"><?php echo $tr->translate("Active")?></option>
									    <option value="0"><?php echo $tr->translate("Deactive")?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input iconClass="dijitIconUndo" type="button" value="close" label="Close" dojoType="dijit.form.Button" onclick="hideDialog();"/>
								<input type="button" value="save" name="save" label="Save" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addService();"/>
							</td>
						</tr>
					</table>
				</fieldset>
				</td>
			</tr>
		</table>

		</form>
	</div>
</div>

