<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("EDIT_SERVICE"));
	$frm_items= $this->frm_items;
?>	
<style>
.dijitTextArea[cols].dijitTextArea[cols]{
	width: 99%;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-edit " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_SERVICE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form  id='edit-major' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">	
				items_id = dijit.byId('items_id').get('value');
        			if(items_id==0){
						alert("សូមជ្រើសរើសសេវាកម្ម");dijit.byId('items_id').focus();return false;
					}		
				if(this.validate()) {
					loadingBlock();					
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SERVICE_TYPE");?> </label>
		                <div class="col-md-5 col-sm-5 col-xs-12">
		                	<?php echo $frm_items->getElement("items_id");?>
		                </div>
		                <div class="col-md-2 col-sm-2 col-xs-12">
		                <input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshItems();"/>
		            	</div>
		             </div>
		    		<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("PROGRAM_TITLE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("title");?>
		                	<input type="hidden" id="items_type" name="items_type" value="2" />
		                	<?php echo $frm_items->getElement("id");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SHORTCUT");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("shortcut");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ORDERING");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("ordering");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ONE_PAYMENT");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("is_onepayment");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DISCRIPTION");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("note");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("status");?>
		                </div>
		             </div>
		             <div class="clearfix"></div>
			         <div class="card-box mt-20">
		               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
		               		<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
							<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
								iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'global','controller'=>"grade",'action'=>'index'),null,true); ?>';" />
							<input type="submit"  label="<?php echo $tr->translate("GO_EDIT");?>" id="submitButton" dojoType="dijit.form.Button" 
						 		iconClass="dijitEditorIcon dijitEditorIconSave" />
		               	</div>
		             </div>
		         </div>
			</div>
		</form>
    </div>
 </div>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
    dojo.require("dijit.form.Textarea");
    dojo.require("dojo.data.ItemFileWriteStore");  
    dojo.ready(function(){
    });
    var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->degree));?> );
    require(["dojo/ready"], function(ready){
    	
    	new dijit.form.FilteringSelect({
    		name: "items_id",
    		id: "items_id",
    		searchAttr: "name",
    		class: 'fullside',
    		onChange: function() {
    			checkaddItems();
    	    }
    		}, "items_id");
    	
    });
    function checkaddItems(){
    	dept_id = dijit.byId('items_id').get('value');
    	if(dept_id==-1){
    		window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/accounting/servicecate/add?rightclick=true";?>','_blank');
	    }
    }
	function getRefreshItems(){
		var url_getItems = '<?php echo $this->url(array("module"=>"global","controller"=>"degree","action"=>"refreshitems"));?>';										
			loadingBlock();
			dojo.xhrPost({
				url: url_getItems,
				content:{
					'items_type':2
					},
				handleAs:"json",
				load: function(data) {
					dept_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('items_id').set('store',dept_store);  
				   document.getElementsByClassName("overlay")[0].style.display="none";
				},
				error: function(err) {
					document.getElementsByClassName("overlay")[0].style.display="none";
				}
			});
	}
</script>
<script>
function submitDataClose(){
	items_id = dijit.byId('items_id').get('value');
	if(items_id==0){
		alert("សូមជ្រើសរើសសេវាកម្ម");dijit.byId('items_id').focus();return false;
	}
	if(dijit.byId('office_receipt').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'service','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/accounting/service";
			},
			error: function(e) {
			}
		});
	}
}
</script>
