<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_callteral;
	echo $this->headTitle($tr->translate("ADD_TECHER_NAME"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$techer= $this->frm_techer;
?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");

var position_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->position));?> );

	dojo.ready(function(){
		getTeacherID();
		new dijit.form.FilteringSelect({
			store: position_store,
			autoComplete: true,                        
		    id: "staff_position",
		    name: "staff_position",  
		    class: 'fullside',  
		    placeHolder:" select position ", 
		    onChange: function() {
			   	staff_pos = dijit.byId('staff_position').get('value');
			    if(staff_pos==-1){
			   	 	dijit.byId("popup_position").show();
		     	}
		   } 
		}, "staff_position");
	});
</script>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'global','controller'=>'lecturer','action'=>'add')); ?>" 
dojoType="dijit.form.Form" method="post"  enctype="multipart/form-data">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dojo.byId('password').value != dojo.byId('confirm_password').value ){
					alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
					dojo.byId('password').value = '';
					dojo.byId('confirm_password').value = '';
					dijit.byId('password').focus();
					return false;
				}	
                dijit.byId("save_new").attr("disabled",true);	
				dijit.byId("save_close").attr("disabled",true);		
				return true;
			}else {
				return false;
			}
</script>
<fieldset style="margin-top:-13px; background: #fff;   border: solid 1px #008;">
	<legend align="center" ><strong style="font-size: 18px;"><?php echo $tr->translate("ADD_TEACHER");?></strong></legend>
		<table width="100%">
			<tr>
				<td width="33.33%" valign="top">
					<table width="100%">
						<tr>
							<td><?php echo $tr->translate("ID_NUMBER")?></td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="1" style="color:red;" class="fullside" id="code" name="code" value="" type="text"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("TEACHER_NAME")?></td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="kh_name" name="kh_name" value="" type="text"></td>
						</tr>
						<tr>
							 <td><?php echo $tr->translate("SEX")?></td>
							 <td>
								<select dojoType="dijit.form.FilteringSelect" value="1" class="fullside" id="sex" name="sex" value="" type="text">
									<option value="1">Male</option>
									<option value="2">Female</option>
								</select>
							 </td>
							 </tr>
						<tr>
							<td><?php echo $tr->translate("DOB")?></td>
							<td><input dojoType="dijit.form.DateTextBox" value="now" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" id="dob" name="dob" value="" type="text" /></td>
						</tr>
					</table>
				</td>
				<td width="33.33%" valign="top">
					<table width="100%">
						<tr>
							<td><?php echo $tr->translate("NATIONALITY")?></td>
							<td><input dojoType="dijit.form.TextBox"  class="fullside" id="nationality" name="nationality" value="" type="text"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td><input dojoType="dijit.form.TextBox"  class="fullside" id="phone" name="phone" value="" type="text"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ADDRESS")?></td>
							<td><input dojoType="dijit.form.TextBox"  class="fullside" id="address" name="address" value="" type="text"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><input dojoType="dijit.form.TextBox"  class="fullside" id="note" name="note" value="" type="text"></td>
						</tr>
					</table>
				</td>
				<td width="33.33%" valign="top">
					<table style="margin: 0 auto; width: 100%;white-space: nowrap;background:#ffcece">
							<tr>
								<td><?php echo $tr->translate("ACCOUNT_NAME")?></td>
								<td><input dojoType="dijit.form.TextBox"  class="fullside" id="user_name" name="user_name" value="" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("PASSWORD")?></td>
								<td><input dojoType="dijit.form.ValidationTextBox" regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
								 class="fullside" id="password" name="password" value="" type="password"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("CONFIRM_PASSWORD")?></td>
								<td><input dojoType="dijit.form.ValidationTextBox" regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
								 class="fullside" id="confirm_password" name="confirm_password" value="" type="password"></td>
							</tr>
						</table>
					
				</td>
			</tr>
			<tr>
				<td colspan="3" align="center">
					<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="សម្អាត" dojoType="dijit.form.Button"/>
					<input type="button" onclick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
				</td>
			</tr>
		</table>
</fieldset>
</form>

<script type="text/javascript">
	var url_get_teacher_id = '<?php echo $this->url(array("module"=>"global","controller"=>"lecturer","action"=>"get-teacher-id")); ?>';
	function getTeacherID(){
		dojo.xhrPost({
			url:url_get_teacher_id,
			handleAs:"json",
			load: function(data) {
				dijit.byId('code').attr('value',data);
			},
			error: function(err) {
				alert(err);
			}
		});
	}

	function submitDataClose(){
		if(dojo.byId('password').value != dojo.byId('confirm_password').value ){
			alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
			dojo.byId('password').value = '';
			dojo.byId('confirm_password').value = '';
			dijit.byId('password').focus();
			return false;
		}	
        
		if(dijit.byId('frm_add_tran').validate()) {
			dijit.byId("save_new").attr("disabled",true);	
			dijit.byId("save_close").attr("disabled",true);		
			var url_submit = '<?php echo $this->url(array('module'=>'global','controller'=>'lecturer','action'=>'add')); ?>';
			dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("frm_add_tran"),		    
				load: function(data) {
					alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
					window.location.href ="<?php echo $this->baseUrl();?>/global/lecturer";
				},
				error: function(e) {
				}
			});
		}
	}
</script>