<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_callteral;
	echo $this->headTitle($tr->translate("EDIT_TECHER_NAME"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$techer= $this->frm_techer;
?>
<script type="text/javascript">
var position_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->position));?> );
	dojo.ready(function(){
	
	});

</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_TECHER_NAME');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'global','controller'=>'lecturer','action'=>'edit')); ?>" 
		dojoType="dijit.form.Form" method="post"  enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
			</script>
		</form>
		<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("LECTURER_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ID_NUMBER");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->rs['teacher_code']?>" required="1" style="color:red;" class="fullside" id="code" name="code" value="" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TEACHER_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->rs['teacher_name_kh']?>"required="1" class="fullside" id="kh_name" name="kh_name" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select dojoType="dijit.form.FilteringSelect" value="1" class="fullside" id="sex" name="sex" value="" type="text">
									<option value="1" <?php if($this->rs['sex']==1){echo 'selected="selected"';}?> ><?php echo $tr->translate("MALE");?></option>
									<option value="2" <?php if($this->rs['sex']==2){echo 'selected="selected"';}?> ><?php echo $tr->translate("FEMALE");?></option>
								</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.DateTextBox" value="<?php echo $this->rs['dob']?>" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" id="dob" name="dob" type="text" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.TextBox" value="<?php echo $this->rs['nationality']?>" class="fullside" id="nationality" name="nationality" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.TextBox" value="<?php echo $this->rs['tel']?>" class="fullside" id="phone" name="phone" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ADDRESS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.TextBox" value="<?php echo $this->rs['address']?>" class="fullside" id="address" name="address"  type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.TextBox" value="<?php echo $this->rs['note']?>" class="fullside" id="note" name="note" type="text">
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("LECTURER_ACCOUNT");?> 
	                   </label>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ACCOUNT_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.TextBox" value="<?php echo $this->rs['user_name']?>"  class="fullside" id="user_name" name="user_name" value="" type="text">
	                   </div>
	                </div>
	                
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PASSWORD");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
								 class="fullside" id="password" name="password" value="" type="password">
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CONFIRM_PASSWORD");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
								 class="fullside" id="confirm_password" name="confirm_password" value="" type="password">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select dojoType="dijit.form.FilteringSelect" value="1" class="fullside" id="status" name="status" value="" type="text">
								<option value="1" <?php if($this->rs['status']==1){echo 'selected="selected"';}?>><?php echo $tr->translate("ACTIVE");?></option>
								<option value="0" <?php if($this->rs['status']==0){echo 'selected="selected"';}?>><?php echo $tr->translate("DEACTIVE");?></option>
							</select>
	                   </div>
	                </div>
	            </div>
			</div>
			<div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="សម្អាត" dojoType="dijit.form.Button"/>
					<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
	</div>
</div>

<script type="text/javascript">
</script>