<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_callteral;
	echo $this->headTitle($tr->translate("EDIT_TECHER_NAME"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$techer= $this->frm_techer;
?>

<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");

var position_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->position));?> );
	dojo.ready(function(){
		
		new dijit.form.FilteringSelect({
			store: position_store,
			autoComplete: true,                        
		    id: "staff_position",
		    name: "staff_position",  
		    class: 'fullside',  
		    placeHolder:" select position ", 
		    onChange: function() {
			   	staff_pos = dijit.byId('staff_position').get('value');
			    if(staff_pos==-1){
			   	 	dijit.byId("popup_position").show();
		     	}
		   } 
		}, "staff_position");
		//dijit.byId('staff_position').attr('value','<?php echo $this->rs['position']?>');
	});

</script>


<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'global','controller'=>'lecturer','action'=>'edit')); ?>" 
dojoType="dijit.form.Form" method="post"  enctype="multipart/form-data">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table width="100%">
	<tr>
		<td>
			<fieldset style="margin-top:-13px;">
				<legend align="center" ><strong style="font-size: 18px;"><?php echo $tr->translate("ADD_STAFF");?></strong></legend>
				<table style="margin: 0 auto; width: 100%;white-space: nowrap;" cellspacing="10">
					<tr>
						<td><?php echo $tr->translate("ID_NUMBER")?></td>
						<td><input dojoType="dijit.form.TextBox" style="color:red;" class="fullside" id="code" name="code" value="<?php echo $this->rs['teacher_code']?>" type="text"></td>
						
						<td><?php echo $tr->translate("KH_NAME")?></td>
						<td><input dojoType="dijit.form.TextBox"  class="fullside" id="kh_name" name="kh_name" value="<?php echo $this->rs['teacher_name_kh']?>" type="text"></td>
						
						<td><?php echo $tr->translate("EN_NAME")?></td>
						<td><input dojoType="dijit.form.TextBox"  class="fullside" id="en_name" name="en_name" value="<?php echo $this->rs['teacher_name_en']?>" type="text"></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("SEX")?></td>
						<td>
							<select dojoType="dijit.form.FilteringSelect" class="fullside" id="sex" name="sex" type="text">
								<option value="1" <?php if($this->rs['sex']==1){echo 'selected="selected"';}?> >Male</option>
								<option value="2" <?php if($this->rs['sex']==2){echo 'selected="selected"';}?> >Female</option>
							</select>
						</td>
						
						<td><?php echo $tr->translate("DOB")?></td>
						<td>
							<input dojoType="dijit.form.DateTextBox" value="<?php echo $this->rs['dob']?>" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" id="dob" name="dob" value="" type="text" />
						</td>
						
						<td><?php echo $tr->translate("NATIONALITY")?></td>
						<td><input dojoType="dijit.form.TextBox"  class="fullside" id="nationality" name="nationality" value="<?php echo $this->rs['nationality']?>" type="text"></td>
					</tr>
					
					<tr>
						<td><?php echo $tr->translate("PHONE")?></td>
						<td><input dojoType="dijit.form.TextBox"  class="fullside" id="phone" name="phone" value="<?php echo $this->rs['tel']?>" type="text"></td>
						
						<td><?php echo $tr->translate("ADDRESS")?></td>
						<td><input dojoType="dijit.form.TextBox"  class="fullside" id="address" name="address" value="<?php echo $this->rs['address']?>" type="text"></td>
					
						<td><?php echo $tr->translate("NOTE")?></td>
						<td><input dojoType="dijit.form.TextBox"  class="fullside" id="note" name="note" value="<?php echo $this->rs['note']?>" type="text"></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("STATUS")?></td>
						<td>
							<select dojoType="dijit.form.FilteringSelect" value="1" class="fullside" id="status" name="status" value="" type="text">
								<option value="1" <?php if($this->rs['status']==1){echo 'selected="selected"';}?>>Active</option>
								<option value="0" <?php if($this->rs['status']==0){echo 'selected="selected"';}?>>Deactive</option>
							</select>
						</td>
					</tr>
					<tr>
						<td colspan="6" align="center">
								<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="សម្អាត" dojoType="dijit.form.Button"/>
								
								<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
								<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
						</td>
					</tr>
				</table>
			</fieldset>
		</td>
	</tr>
</table>
</form>

<script type="text/javascript">

	var url_add_position = '<?php echo $this->url(array("module"=>"global","controller"=>"lecturer","action"=>"add-position")); ?>';
	function addPosition(){
		dojo.xhrPost({
				url:url_add_position,
				form: dojo.byId("frm_add_position"),
				handleAs:"json",
				load: function(data) {
					alert(data); 
					var Itemmake = { 
					    	 id: data,
						     name: dijit.byId('title').get('value')
						   };
				   addDataToSelectbox(dijit.byId('staff_position'), position_store, Itemmake, data);
	
				   dijit.byId('frm_add_position').reset();
				   dijit.byId("popup_position").hide();
					
				},
				error: function(err) {
					alert(err);
				}
		});
	}
	
	function hidePopup() {		
		dijit.byId("popup_position").hide();
	}

</script>


<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:25%;" id="popup_position" >
		<form style="background-color: buttonface; " id='frm_add_position' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="0" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate('ADD_POSITION');?></legend>
						<table style="margin: 0 auto; width: 100%; " cellspacing="3" >
							<tr>
								<td><?php echo $tr->translate('TITLE');?></td>
								<td>
									<input dojoType="dijit.form.ValidationTextBox"   class="fullside" id="title" name="title" value="" type="text">
								</td>
							</tr>
							
							<tr>
								<td colspan="4" align="center">
									<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button" 
									​ ​​iconClass="dijitIconUndo" onclick="hidePopup();"/>
									<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addPosition();"/>
								</td>
							</tr>
							
						</table>
				</fieldset>
				</td>
			</tr>
		</table>

		</form>
	</div>
</div>
