<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_callteral;
	echo $this->headTitle($tr->translate("ADD_TECHER_NAME"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$frm= $this->frm_update;
	//print_r($frm); exit();
?>
<script type="text/javascript">
var position_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->position));?> );
	dojo.ready(function(){
	});
</script>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<style>
.image-box {
    text-align: center;
    width: 220px;
    height: 110px;
}
.image-box img {
    width: 220px;
    height: 130px;
}

.button_browse {
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 101%;
    height: 38px;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 38px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 220px;
    margin: 0 auto;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-user-plus" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_TECHER_NAME');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'global','controller'=>'lecturer','action'=>'add')); ?>" 
			dojoType="dijit.form.Form" method="post"  enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dojo.byId('password').value != dojo.byId('confirm_password').value ){
					alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
					dojo.byId('password').value = '';
					dojo.byId('confirm_password').value = '';
					dijit.byId('password').focus();
					return false;
				}
                dijit.byId("save_new").attr("disabled",true);	
				dijit.byId("save_close").attr("disabled",true);		
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
	    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
		            <li class="nav-item active">
		                <a class="nav-link " data-toggle="tab" href="#panel21" role="tab">
		                <i class="fa fa-user ml-2"></i> <?php echo $tr->translate("INFORMATION_TEACHER");?>
		                </a>
		            </li>
					<li class="nav-item">
		                <a class="nav-link" data-toggle="tab" href="#panel23" role="tab">
		                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("STUDY_MATERIAL");?>
		                </a>
		            </li>
		        </ul>
		    </div>
	        <!-- Tab panels -->
        <div class="tab-content vertical">
		    <div class="tab-pane fade in active" id="panel21" role="tabpanel">
			<div class="card-box">
				<!--/.Panel 1-->
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("LECTURER_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ID_NUMBER");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("code");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TEACHER_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("kh_name");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SEX");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
							<?php echo $frm->getElement("sex");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TEACHER");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
							<?php echo $frm->getElement("teacher_type");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DOB");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("dob");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NATIONALITY");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("nationality");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("phone");?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EMAIL");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                  		<?php echo $frm->getElement("email");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ADDRESS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                  		<?php echo $frm->getElement("address");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("note");?>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("CONTACT_INFO_EXPER");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                 	<label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DEGREE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
		                		<?php echo $frm->getElement("degree");?>
						</div>
		             </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("POSITION");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("position_add");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PASSPORT_NO");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("passport_no");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CARD_NO");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("card_no");?>
	                   </div>
	                </div>
	                <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("START_DATE");?></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("start_date");?>
		                </div>
		             </div>
	                <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("END_DATE");?></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		               		<?php echo $frm->getElement("end_date");?>
		                </div>
		             </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("AGREEMENT");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("agreement");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EXPERIENCES");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("experiences");?>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("LECTURER_ACCOUNT");?> 
	                   </label>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ACCOUNT_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("user_name");?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PASSWORD");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
								 class="fullside" id="password" name="password" value="" type="password">
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CONFIRM_PASSWORD");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
								 class="fullside" id="confirm_password" name="confirm_password" value="" type="password">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name" style="line-height: 8.75;"><?php echo $tr->translate("SELECT_PICTURE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<div class="account-image">
								<div class="image-box">
									<?php
										$images = $this->baseUrl().'/images/no-profile.png';
										 if (!empty($this->rs['photo'])){
										$images = $this->baseUrl().'/images/'.$this->rs['photo'];
										}										 
									?>		
									<img id="profile_wiew" src="<?php echo $images;?>" alt=""  />
								</div>
								<div class="button_browse">
								<div id='preview'></div>	
										<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
										<input class="btn_borwse_image" type="file" id="photo" name="photo"  />
								</div>
							</div>		
	                   </div>
	                </div>
	            </div>
	           <!--/.Panel 1-->
			</div>
			</div>
			<!--/.Panel 2-->
	   <div class="tab-pane fade in " id="panel23" role="tabpanel">
          <div class="card-box">
	        <div class="col-md-13 col-sm-13 col-xs-12">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<table border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
							<tr id="head-title" class="head-td"  align="right" style="background:#ececec;font-size:12px;"></tr>
						</table>
						<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconEditProperty" onclick="addRow();" />
								
						<input type="hidden" id="identity" name="identity" />
						<input type="hidden" id="popup_index" name="popup_index" />
					</div>		
				</div>		
	         </div>
          </div>
       </div>
	</div>
			<div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="សម្អាត" dojoType="dijit.form.Button"/>
					<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
						iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'global','controller'=>"lecturer",'action'=>'index'),null,true); ?>';" />
					<input type="submit" onclick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					 
               	</div>
             </div>
		</form>
    </div>
 </div>

<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.NodeList-manipulate");

var position_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->position));?> );
var doctype_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->doc_type));?> );
	dojo.ready(function(){
		getTeacherID();
		new dijit.form.FilteringSelect({
			store: position_store,
			autoComplete: true,                        
		    id: "staff_position",
		    name: "staff_position",  
		    class: 'fullside',  
		    placeHolder:" select position ", 
		    onChange: function() {
			   	staff_pos = dijit.byId('staff_position').get('value');
			    if(staff_pos==-1){
			   	 	dijit.byId("popup_position").show();
		     	}
		   } 
		}, "staff_position");
		 initialize();
	});
</script>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;" id="popup_doc_type" >
		<form style="background-color: buttonface;" id='frm_doc_type' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('DOCUMENT_TYPE');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('TITLE');?></td>
									<td><input dojoType="dijit.form.ValidationTextBox" required="true"  class="fullside" id="title_doc_type" name="title_doc_type" value="" type="text"></td>
								</tr>
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="Close" id="hide_doc_type" name="hide_doc_type" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog3();"/>
										<input type="button" value="save" label="SAVE" id="save_doc_type" name="save_doc_type" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addDocType();"/>
									</td>
								</tr>
							</table>
						</fieldset>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>

<script type="text/javascript">
	var url_get_teacher_id = '<?php echo $this->url(array("module"=>"global","controller"=>"lecturer","action"=>"get-teacher-id")); ?>';
	function getTeacherID(){
		dojo.xhrPost({
			url:url_get_teacher_id,
			handleAs:"json",
			load: function(data) {
				dijit.byId('code').attr('value',data);
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	function submitDataClose(){
		degree=dijit.byId('degree').get('value');
		if(degree==0){
			alert('សូមជ្រើសរើសកម្រិតសិក្សា!');dijit.byId('degree').focus();return false;
			return false;
		}
		if(dojo.byId('password').value != dojo.byId('confirm_password').value ){
			alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
			dojo.byId('password').value = '';
			dojo.byId('confirm_password').value = '';
			dijit.byId('password').focus();
			return false;
		}	
		if(dijit.byId('frm_add_tran').validate()) {
			dijit.byId("save_new").attr("disabled",true);	
			dijit.byId("save_close").attr("disabled",true);		
			var url_submit = '<?php echo $this->url(array('module'=>'global','controller'=>'lecturer','action'=>'add')); ?>';
			dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("frm_add_tran"),		    
				load: function(data) {
					alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
					window.location.href ="<?php echo $this->baseUrl();?>/global/lecturer";
				},
				error: function(e) {
				}
			});
		}
	}
	function readURL(input) {
	    if (input.files && input.files[0]) {
	        var reader = new FileReader();
	        
	        reader.onload = function (e) {
	            $('#profile_wiew').attr('src', e.target.result);
	        }
	        reader.readAsDataURL(input.files[0]);
	    }
	}
	var maxSize = 0;
	$("#photo").change(function(){
	    readURL(this);
	});

	var url_add_doc_type = '<?php echo $this->url(array("module"=>"foundation","controller"=>"register","action"=>"add-doctype")); ?>';
	function addDocType(){
		if(dijit.byId('frm_doc_type').validate()){
			dijit.byId("save_doc_type").attr("disabled",true);
			dojo.xhrPost({
				url:url_add_doc_type,
				form: dojo.byId("frm_doc_type"),
				handleAs:"json",
				load: function(data) {
				var Itemmake = { 
						 id: dijit.byId('title_doc_type').get('value'),
						 name: dijit.byId('title_doc_type').get('value')
					   };
				index = $("#popup_index").val();	   
			   addDataToSelectbox(dijit.byId('document_type_'+index), doctype_store, Itemmake, dijit.byId('title_doc_type').get('value'));
			   dijit.byId('frm_doc_type').reset();
			   dijit.byId("popup_doc_type").hide();
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
	function hideDialog3() {		
		dijit.byId("popup_doc_type").hide();
	}
	function initialize(){
		<?php if(!empty($this->row)){ //echo '111111';exit();
			foreach($this->row as $row){ 
		?>
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("DOCUMENT_TYPE");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("DATE_GIVE");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("RECEIVED");?></th>';
			temp+='<th width="100px"><?php echo $tr->translate("DATE_GIVE_TO");?></th>';
			temp+='<th><?php echo $tr->translate("NOTE");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="5%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="5%" align="center">'+no+'</td>';
			template+='<td width="20%"><select class="fullside" name="document_type_'+col+'" id="document_type_'+col+'" value="0" onChange="popupDocType('+col+');" dojoType="dijit.form.FilteringSelect" >';	
				<?php if(!empty($this->doc_type)){foreach($this->doc_type as $doc_type){?>
					template+='<option value="'+'<?php echo $doc_type['id']?>'+'"><?php echo $doc_type['name'];?></option>';
				<?php }}?>
			template+='</select></td>';
			template+='<td width="15%"><input type="text" class="fullside" name="date_give_'+col+'" id="date_give_'+col+'" value="now" dojoType="dijit.form.DateTextBox" constraints='+'{datePattern:"dd/MM/yyyy"}'+' /></td>';
			template+='<td width="15%"><select class="fullside" name="is_receive_'+col+'" id="is_receive_'+col+'" dojoType="dijit.form.FilteringSelect" ><option value="1"><?php echo $tr->translate("RECEIVED");?></option><option value="0"><?php echo $tr->translate("NOT_RECEIVED");?></option></select></td>';
			template+='<td width="15%"><input type="text" class="fullside" name="date_end_'+col+'" id="date_end_'+col+'" value="now" dojoType="dijit.form.DateTextBox" constraints='+'{datePattern:"dd/MM/yyyy"}'+' /></td>';
			template+='<td width="20%"><input type="text" class="fullside" name="note_'+col+'" id="note_'+col+'" dojoType="dijit.form.TextBox" placeholder="<?php echo $tr->translate("NOTE");?>" /></td>';
		
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});

		dijit.byId('document_type_'+col).attr('value',"<?php echo $row['document_type'];?>");
		dijit.byId('date_give_'+col).attr('value',"<?php echo $row['date_give'];?>");
		dijit.byId('date_end_'+col).attr('value',"<?php echo $row['date_end'];?>");
		dijit.byId('is_receive_'+col).attr('value',"<?php echo $row['is_receive'];?>");
		dijit.byId('note_'+col).attr('value',"<?php echo $row['note'];?>");
		
		<?php }}?>
	}
	
var template = '';
var service = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
date_format = '"dd/MM/yyyy"';
function addRow(){
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th width="100px"><?php echo $tr->translate("DOCUMENT_TYPE");?></th>';
		temp+='<th width="100px"><?php echo $tr->translate("DATE_GIVE");?></th>';
		temp+='<th width="100px"><?php echo $tr->translate("RECEIVED");?></th>';
		temp+='<th width="100px"><?php echo $tr->translate("DATE_GIVE_TO");?></th>';
		temp+='<th><?php echo $tr->translate("NOTE");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="5%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="5%" align="center">'+no+'</td>';
		template+='<td width="20%"><select class="fullside" name="document_type_'+col+'" id="document_type_'+col+'" value="0" onChange="popupDocType('+col+');" dojoType="dijit.form.FilteringSelect" >';	
			<?php if(!empty($this->doc_type)){foreach($this->doc_type as $doc_type){?>
				template+='<option value="'+'<?php echo $doc_type['id']?>'+'"><?php echo $doc_type['name'];?></option>';
			<?php }}?>
		template+='</select></td>';
		template+='<td width="15%"><input type="text" class="fullside" name="date_give_'+col+'" id="date_give_'+col+'" value="now" dojoType="dijit.form.DateTextBox" constraints='+'{datePattern:"dd/MM/yyyy"}'+' /></td>';
		template+='<td width="15%"><select class="fullside" name="is_receive_'+col+'" id="is_receive_'+col+'" dojoType="dijit.form.FilteringSelect" ><option value="1"><?php echo $tr->translate("RECEIVED");?></option><option value="0"><?php echo $tr->translate("NOT_RECEIVED");?></option></select></td>';
		template+='<td width="15%"><input type="text" class="fullside" name="date_end_'+col+'" id="date_end_'+col+'" value="now" dojoType="dijit.form.DateTextBox" constraints='+'{datePattern:"dd/MM/yyyy"}'+' /></td>';
		template+='<td width="20%"><input type="text" class="fullside" name="note_'+col+'" id="note_'+col+'" dojoType="dijit.form.TextBox" placeholder="<?php echo $tr->translate("NOTE");?>" /></td>';
	
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);
	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}

function popupDocType(index){
	id = dijit.byId('document_type_'+index).get('value');
	if(id==-1){
		$('#popup_index').val(index);
		dijit.byId("popup_doc_type").show();
	}
	
}
</script>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("/psst/trunk/public/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>
