<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('EDIT_STUDENT_REGISTER')); 
	echo $this->headTitle(''); 
	$sex='';
	if($this->rs['sex']==1){
		$sex=$tr->translate("MALE");
	}else{
		$sex=$tr->translate("FEMALE");
	}
	$image = $this->baseUrl().'/images/no-profile.png';
			if(!empty($this->rs['photo'])){
				if (file_exists(PUBLIC_PATH."/images/photo/".$this->rs['photo'])){
				$image = $this->baseUrl().'/images/photo/'.$this->rs['photo'];
				}
	}
	//print_r($image); exit();
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<style>
tr.head td h2 {
    font-size: 16px !important;
    line-height: 27px !important;
}
.b{ font-weight: bold; }

p.padding-left {
    line-height: 24px !important;
}

table#exportExcel tr td {
    font-size: 14px !important;
}
label.title {
    font-size: 14px !important;
    min-width: 100px !important;
}
label.value {
    font-size: 14px !important;
    min-width: 100px !important;
}
</style>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.ready(function(){
	 
}); 
 
</script>
<table width="100%">
<div class="ptss-frame  js-ptss-frame "><!-- is-opened -->
		<div class="ptss__toggle-btn  js-ptss-toggle-btn ">
			<i class="fa fa-print"></i>
		</div>
      <div class="ptss__header"><?php echo $tr->translate("PRINT");?></div>
		<div class="ptss__settings">
			<div class="ptss__single-setting" id="ptss__layout">
				<div class="ptss__setting-control">
					<div class="ptss__layout-wrapper">
						<a class="qButton" title="<?php echo $tr->translate("Preview");?>" href="#" onclick="preview();"><i class="fa fa-search" aria-hidden="true"></i></a>
						<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrint();" ><i class="fa fa-print" aria-hidden="true"></i></a>
						<a class="qButton excel" href="#"  title="<?php echo $tr->translate("Export");?>"  onclick="exportExcel();"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a>
					</div>
					
				</div>
			</div>
		</div>
</div>
</table>
<div style="background: #fff;width: 27cm;margin: 0 auto;min-height: 25cm; padding: 0.5cm;">
<div id="divPrint">
			<style>
	   			label.value{
	   				font-weight: initial;
	   				min-width: 90px;
	   				font-size: 14px;
	   				display: inline-block;
				}
				p.padding-left {
				    padding-left: 10px;
					    line-height: 20px;
				}
				label.title {
				    font-size: 14px;
				    min-width: 80px;
				    display: inline-block;
				}
				.border {
				    
				    display: block;
				    width: 100%;
				    height: 1px;
				    margin-bottom: 10px;
				}
	  		 </style>
				<table width="100%" style="font-size:12px; font-family:Tahoma,'Khmer OS Battambang';"> 
					<tr class="head">
						<td width="40%" valign="middle">
							<img alt="" src="<?php echo $this->baseUrl()."/images/logo.png"?>" style="width: 60px;display: inline-block;margin-right: 10px;">
							<div style=" display: inline-block;    vertical-align: top;">
							<h2 style="font-size:14px;     line-height: 14px; font-weight: initial; font-family:'Khmer OS Muol Light';" >សាលាបញ្ញាសាស្ត្រអន្តរជាតិ</h2>
					   		<h2 style="font-size:14px;     line-height: 14px; font-weight: initial; font-family:'Times New Roman';">Paññāsāstra International School</h2>
							</div>
					   </td>
					   <td width="30%" align="center">
					   		
					   </td>
					   <td width="30%" align="center">
					   		<h2 style="font-size:16px;     line-height: 14px; font-weight: initial; font-family:'Khmer OS Muol Light';" >ព្រះរាជាណាចក្រកម្ពុជា</h2>
					   		<h2 style="font-size:14px;     line-height: 14px; font-weight: initial; font-family:'Khmer OS Battambang';">ជាតិ សាសនា ព្រះមហាក្សត្រ</h2>
					   		<img alt="" src="<?php echo $this->baseUrl()."/images/sign.PNG"?>" style=" width: 120px;">
					   </td>
					</tr>
					<tr class="head">
					   <td colspan="3" align="center">
					   		<h1 style="font-size:18px;font-weight: initial;font-family:'Khmer OS Muol Light';text-decoration: underline;" >ប្រវត្តិរូបសង្ខេប</h1>
					   </td>
					</tr>
					<tr>
					   <td colspan="3">
					   		<table id="exportExcel" style="font-family:'Khmer OS Battambang'; border-collapse:collapse;  font-size:14px; white-space: nowrap;" width="100%" cellspacing="0">
						    	<tr>
						    		<td align="center" style="font-size:14px; font-weight: initial; font-family:'Khmer OS Muol Light';">
						    			<img id="profile_wiew" src="<?php echo $image;?>" alt="" style="width:100px;max-height: 120px;border: solid 1px #a29f9f;"/>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight: initial; font-family:'Khmer OS Battambang';">
						    			I. <?php echo $tr->translate("LECTURER_INFO");?>
						    			<div class="border"></div>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight:600;  font-family:'Khmer OS Battambang';">
						    			<p class="padding-left">
						    			<label class="title">ឈ្មោះគ្រូ</label> : <label class="value"><?php echo $this->rs['teacher_name_kh'];?></label> <label class="title">ភេទ</label> : <label class="value"><?php echo $this->rs['sex'];?></label> <label class="title">អត្តលេខ</label> : <label class="value"><?php echo $this->rs['teacher_code'];?></label>
						    			</p>
						    			<p class="padding-left">
						    			 <label class="title">ថ្ងៃ-ខែ-ឆ្នាំកំណើត</label> : <label class="value"><?php echo empty($this->rs['dob'])?"":date("d/m/Y",strtotime($this->rs['dob']));?></label><label class="title">សញ្ជាតិ</label> : <label class="value"><?php echo $this->rs['nationality'];?></label> <label class="title">ជនជាតិ</label> : <label class="value"><?php echo $this->rs['nation'];?></label>
						    			</p>
						    			<p class="padding-left">
						    			<label class="title">ប្រភេទគ្រូ</label> : <label class="value"><?php echo $this->rs['teacher_type'];?></label> 
						    			</p>
						    		</td>
						    	</tr>
						    	<tr><td>&nbsp;</td></tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight: initial; font-family:'Khmer OS Battambang';">
						    			II. <?php echo $tr->translate("CURRENT_ADDRESS");?>
						    			<div class="border"></div>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight:600;  font-family:'Khmer OS Battambang';">
						    			<p class="padding-left">
						    			<label class="title">លេខផ្ទះ</label> : <label class="value"><?php echo $this->rs['home_num'];?></label><label class="title">ផ្លូវលេខ</label> : <label class="value"><?php echo $this->rs['street_num'];?></label><label class="title">ភូមិ</label> : <label class="value"><?php echo $this->rs['Village_name'];?></label>​ 
						    			</p>
						    			<p class="padding-left">
						    			 <label class="title">ឃុំ/សង្កាត់ </label> : <label class="value"><?php echo $this->rs['com_name'];?></label><label class="title">ស្រុក /ខណ្ឌ</label> : <label class="value"><?php echo $this->rs['dis_name'];?></label> <label class="title">រាជធានី/ខេត្ត </label> : <label class="value"><?php echo $this->rs['province_name'];?></label>  
						    			</p>
						    		</td>
						    	</tr>
						    	<tr><td>&nbsp;</td></tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight: initial; font-family:'Khmer OS Battambang';">
						    			III. <?php echo $tr->translate("CONTACT_INFO");?>
						    			<div class="border"></div>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight:600;  font-family:'Khmer OS Battambang';">
						    			<p class="padding-left">
						    			<label class="title">លេខទូរស័ព្ទ </label> : <label class="value"><?php echo $this->rs['tel'];?></label><label class="title">អ៊ីម៉ែល </label> : <label class="value"><?php echo $this->rs['email'];?></label> 
						    			</p>
						    			<p class="padding-left">
						    			<label class="title">លេខអត្តសញ្ញាណប័ណ្ណ</label> : <label class="value"><?php echo $this->rs['card_no'];?></label>  <label class="title">លិខិតឆ្លងដែនលេខ</label> : <label class="value"><?php echo $this->rs['passport_no'];?></label>
						    			</p>
						    			<p class="padding-left">
						    			 
						    			</p>
						    			<p class="padding-left">
						    			 <label class="title">សម្គាល់  </label> : <label class="value"><?php echo $this->rs['note'];?></label> 
						    			</p>
						    		</td>
						    	</tr>
						    	<tr><td>&nbsp;</td></tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight: initial; font-family:'Khmer OS Battambang';">
						    			VI. <?php echo $tr->translate("CONTACT_INFO_EXPER");?>
						    			<div class="border"></div>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight:600;  font-family:'Khmer OS Battambang';">
						    			<p class="padding-left">
						    			<label class="title">កម្រិតសិក្សា</label> : <label class="value"><?php echo $this->rs['degree'];?></label>  <label class="title">ថ្ងៃចាប់ផ្តើម</label> : <label class="value"><?php echo $this->rs['start_date'];?></label><label class="title">ថ្ងៃបញ្ចប់ </label> : <label class="value"><?php echo $this->rs['end_date'];?></label> 
						    			</p>
						    			<p class="padding-left">
						    			<label class="title">តួនាទី </label> : <label class="value"><?php echo $this->rs['position_add'];?></label>
						    			</p>
						    			<p class="padding-left">
						    			<label class="title">បទពិសោធន៍ការងារ  </label> : <label class="value"><?php echo $this->rs['experiences'];?></label> 
						    			</p>
						    			<p class="padding-left">
						    			<label class="title">កិច្ចព្រមព្រៀង </label> : <label class="value"><?php echo $this->rs['agreement'];?></label> 
						    			</p>
						    		</td>
						    	</tr>
						    </table>
					   </td>
					</tr>
	  		 	</table>
	   		</div>
		 </div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>

