<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("EDIT_STUDENT_MISTAKE"));
	$row_sub=$this->rows_sub;
	$_model = new Issue_Model_DbTable_DbStudentAttendance();
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$payment_term = $this->payment_term;
	$rs_sub=$this->rows_sub;
?>	
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-gavel " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_STUDENT_MISTAKE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
    	 <form id='office_receipt' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
  			 if(this.validate()) {
				loadingBlock();
   				 return true;
   			}else {
    			return false;
   			}
			</script>
	    	<div class="card-box">
	    		<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="material-icons-outlined">class</i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("GROUP_STUDENT_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php $counbranhc = count($this->branch);?>
											<select class="fullside" readonly="readonly" tabindex="15" name="branch_id" queryExpr="*${0}*" autoComplete="false" id="branch_id" dojoType="dijit.form.FilteringSelect" onchange="getAllGroupByBranch();">
												<option value=""><?php echo $tr->translate("PLEASE_SELECT_BRANCH");?></option>
												<?php if(!empty($this->branch))foreach ($this->branch as $row){?>
												<option value="<?php echo $row['id']?>" <?php if ($this->row['branch_id']==$row['id']){ echo "selected='selected'";}?>><?php echo $row['name']?></option>
												<?php }?>
											</select>
										</div>
									 </div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="group" />
										</div>
									 </div>
									 <div class="form-group">
										<div id="gr-info"></div>
									</div>
									 
								 </div>
							 </div>
						 </div>
					 </div>
		         </div>
		         <div class="col-md-6 col-sm-6 col-xs-12">
		         	<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("NOTE");?></p>
										</div> 
									</div>
									<div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("MISTAKE_DATE");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="discipline_date" constraints="{datePattern:'dd/MM/yyyy'}" name="discipline_date" type="text" value="<?php echo $this->row['date_attendence'];?>">
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("FOR_SEMESTER");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="for_semester" name="for_semester" type="text">								
													<option value="1" <?php if($this->row['for_semester']==1){echo"selected";};?>><?php echo $tr->translate("SEMESTER1");?></option>
													<option value="2" <?php if($this->row['for_semester']==2){echo"selected";};?>><?php echo $tr->translate("SEMESTER2");?></option>
											</select>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="status" name="status" type="text">								
												<option value="1" <?php if($this->row['status']==1){echo"selected";};?>><?php echo $tr->translate("ACTIVE")?></option>
												<option value="0" <?php if($this->row['status']==0){echo"selected";};?>><?php echo $tr->translate("DEACTIVE")?></option>
											</select>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input class="fullside" dojoType="dijit.form.Textarea"  id="note" name="note" value="" type="text" style=" height: 60px !important;"  >
										</div>
									 </div>
									
								 </div>
							 </div>
						 </div>
					 </div>
					 
					 
		         </div>
	    	</div>
	    	<div class="card-box">
				<div class="card-blogform">
					<div class="card-body"> 
						<div class="row"> 
							<div class="col-md-12 col-sm-12 col-xs-12"> 
								<div class="d-flex"> 
									<div class="settings-main-icon ">
										<i class="glyphicon glyphicon-education"></i>
									</div> 
									<div class="col-md-10 col-sm-10 col-xs-12"> 
										<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT_LIST");?></p>
									</div> 
								</div>
								<br />
								<div class="form-group">
									<div class="col-md-12 col-sm-12 col-xs-12">
										<div class="custom-control custom-checkbox ">
											<input type="checkbox" class="checkboxMistake custom-control-input" onchange="CheckAll();"  name="check_all" id="check_all" value="1"  >
											<label class="custom-control-label" for="check_all">
												<?php echo $tr->translate('CHECK_ALL_BY');?>
											</label>
										</div>
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12">
										<input type="radio" onchange="CheckAll();" checked="checked"  name="attendence_opt" id="attendence_opt" value="1" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("SMALL_MISTACK");?></label>
										<input type="radio" onchange="CheckAll();" name="attendence_opt" id="attendence_opt" value="2" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("MEDIUM_MISTACK");?></label>
										<input type="radio" onchange="CheckAll();" name="attendence_opt" id="attendence_opt" value="3" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("BIG_MISTACK");?></label>
									</div>
								</div>
								<div class="col-md-12 col-sm-12 col-xs-12">
									<table id="table_row" class="collape responsiveTable">
									</table>
									<label id="liststudent"></label>
								 </div>
				 
							</div>
						</div>
					</div>
				</div>
	    		
	    		  
	    	</div>
	    	<div class="clearfix"></div>
	       	<div class="card-box mt-20 ">
	      	 	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
              		 <input type="hidden" name="identity" id="identity"  value="" >
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_new" name="save_new" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" />
            	 </div>
            </div>
    	</form>
    </div>
 </div>
 <script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.html");
	dojo.require("dijit.form.Textarea");
var subject_store  = getDataStorefromJSON('id','name',  <?php print_r(array())?>  );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
		
		new dijit.form.FilteringSelect({
		    store:subject_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                          
		    required: false,
		    id: "subject",
		    name: "subject",   
		    class: 'fullside',  
		    value:'<?php echo $this->row['subject_id'];?>',
		    searchAttr: "name",
		    placeHolder:"<?php echo $tr->translate("SELECT_SUBJECT")?>",          
		    onChange:function(){  
		    }
		}, "subject");
		new dijit.form.FilteringSelect({
			store: group_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                      
		    id: "group",
		    name: "group",  
		    class: 'fullside', 
		    readOnly: true, 
		    required:false,
		    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
		    onChange: function() {  
		    	group_id = dijit.byId('group').get('value');
		    }
		}, "group");
		getAllGroupByBranch();
		initailize();
});

function gender(sex){
	if(sex==1){
		sex='<?php echo $tr->translate('MALE');?>';
	}else sex='<?php echo $tr->translate('FEMALE');?>';
	return sex;
}
</script>
<script> //validate controll form 
function AllowOnlyNumbers(e) {
    e = (e) ? e : window.event;
    var key = null;
    var charsKeys = [
        97, // a  Ctrl + a Select All
        65, // A Ctrl + A Select All
        99, // c Ctrl + c Copy
        67, // C Ctrl + C Copy
        118, // v Ctrl + v paste
        86, // V Ctrl + V paste
        115, // s Ctrl + s save
        83, // S Ctrl + S save
        112, // p Ctrl + p print
        80 // P Ctrl + P print
    ];
    var specialKeys = [
	    8, // backspace
	    9, // tab
	    27, // escape
	    13, // enter
	    35, // Home & shiftKey +  #
	    36, // End & shiftKey + $
	    37, // left arrow &  shiftKey + %
	    39, //right arrow & '
	    46, // delete & .
	    109,//.
	    45 //Ins &  -
    ];
    key = e.keyCode ? e.keyCode : e.which ? e.which : e.charCode;
    if (key && key < 48 || key > 57) {
        if ((e.ctrlKey && charsKeys.indexOf(key) != -1) ||
            (navigator.userAgent.indexOf("Firefox") != -1 && ((e.ctrlKey && e.keyCode && e.keyCode > 0 && key >= 112 && key <= 123) || (e.keyCode && e.keyCode > 0 && key && key >= 112 && key <= 123)))) {
            return true
        }
        else if (specialKeys.indexOf(key) != -1) {
            if ((key == 39 || key == 45 || key == 46 || key == 109)) {
                return true
            }
            else if (e.shiftKey && (key == 35 || key == 36 || key == 37)) {
                return false;
            }
            else {
                return true;
            }
        }
        else {
            return false;
        }
    }
    else {
        return true;
       }
  }
var olbranch = '<?php echo $this->row['branch_id'];?>';
var inx=0;
var url_getStudentbygroup= '<?php echo $this->url(array('module'=>'issue','controller'=>'studentattendance','action'=>'get-student-bygroup')); ?>';
function filterStudentBygroup(type = null){
	var textareastyle=" font-family: 'Khmer OS Battambang'";
	if(group==''){
		return false;
	}
	if(type!=null){
		return false;
	}
	dojo.xhrPost({
	    url: url_getStudentbygroup,
	    content : { 
		    'group':group,
			'item_type':1,
		},				    
	   handleAs:"json", 
	   load: function(data) {
		   tem="";
	       if(data!=""){
				num =0;
				title=0;
				temp='';
				str='';
				column = 0;
				str='';
				for(i=0;i<data.length;i++){ 
					inx = i+1;
					var classRow="OddRow";
					if((i%2)==0){
						classRow="EvenRow";
					}
					
					num++;
					var gender='';
					if(data[i].sex==1){
						gender="<?php echo $tr->translate("MALE");?>";
					}else{
						gender="<?php echo $tr->translate("FEMALE");?>";
					}
					if(i<1){
						str+='<thead><tr class="head-td" align="center">';
						str+='<th scope="col" ><?php echo $tr->translate("NUM");?></th>';
						str+='<th scope="col" ><?php echo $tr->translate("STUDEN_CODE");?></th>';
						str+='<th scope="col" ><?php echo $tr->translate("STUDEN_NAME");?></th>';
						str+='<th scope="col" ><?php echo $tr->translate("GENDER");?></th>';
						str+='<th scope="col" ><?php echo $tr->translate("HAVE_MISTACK");?></th>';
						str+='<th scope="col" ><?php echo $tr->translate("DISCIPLINE_TYPE");?></th>';
						str+='<th scope="col" ><?php echo $tr->translate("DESCRIPTION");?></th>';
						str+='</tr></thead>';
					}
					str+='<tr class="rowData '+classRow+'">';
						str+='<td data-label="<?php echo $tr->translate("NUM");?>">'+inx+'</td>';
						str+='<td data-label="<?php echo $tr->translate("STUDEN_CODE");?>">'+data[i].stu_code+'</td>';
						str+='<td data-label="<?php echo $tr->translate("STUDEN_NAME");?>">&nbsp;'+data[i].stu_name+'</td>';
						str+='<td data-label="<?php echo $tr->translate("GENDER");?>">'+gender+'<input type="hidden" name="student_id'+inx+'" id="student_id'+inx+'"  value="'+data[i].stu_id+'" ></td>';
						str+='<td data-label="<?php echo $tr->translate("HAVE_MISTACK");?>">';
							str+='<div class="custom-control custom-checkbox ">';
								str+='<input type="checkbox" class="checkboxMistake custom-control-input" name="have_mistake'+inx+'" onclick="checkmistake('+inx+');" id="have_mistake'+inx+'"  >';
								str+='<label class="custom-control-label" for="have_mistake'+inx+'"><?php echo $tr->translate("HAVE_MISTACK");?>';
								str+='</label>';
							str+='</div>';
						str+='</td>';
						str+='<td data-label="<?php echo $tr->translate("DISCIPLINE_TYPE");?>">';
							str+='<input type="radio" onclick="checkmistake('+inx+');"  name="mistake_type'+inx+'" id="mistake_types'+inx+'" value="1" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("SMALL_MISTACK");?></label>';
							str+='<input type="radio" onclick="checkmistake('+inx+');"  name="mistake_type'+inx+'" id="mistake_typem'+inx+'" value="2" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("MEDIUM_MISTACK");?></label>';
							str+='<input type="radio" onclick="checkmistake('+inx+');"  name="mistake_type'+inx+'" id="mistake_typeb'+inx+'" value="3" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("BIG_MISTACK");?></label>';
							str+='<input type="radio" onclick="checkmistake('+inx+');"  name="mistake_type'+inx+'" id="mistake_typeb'+inx+'" value="4" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("OTHER");?></label>';
						str+='</td>';
						str+='<td data-label="<?php echo $tr->translate("DESCRIPTION");?>"><input dojoType="dijit.form.Textarea"  class="fullside"  name="comment'+inx+'" type="text" value="" style="'+textareastyle+'"></td>';
					str+='</tr>';
				    if(inx!=1) {
						var identity = $('#identity').val();
						$('#identity').val(identity+','+inx);
					} else {
						$('#identity').val(inx);
					}
				}
				dojo.html.set(dojo.byId("table_row"),str, {
					 parseContent: true,
				});
	       }else{
	    	   $('#identity').val('');
	    	   document.getElementById("table_row").innerHTML = '';
	       }
	   },		
	    error: function(err){
	    }
	});
}
function CheckAll(){
	var identity = $('#identity').val();
	check_type = $('input[name="attendence_opt"]:checked').val();
	if(identity==""){
		return false;
	}else{
		 var arrays = identity.split(',');
		 if(arrays!=""){
	    	 for(var i=1;i<= arrays.length;i++){
	    		 if($("#check_all").is(':checked')){
	    			 $('input[value="'+check_type+'"]').attr("checked",true);
	    		 }else{
	    			 $('input[value="'+check_type+'"]').attr("checked",false);
	    		 }
	    	}
		}
	}
}
function initailize(){
	str=""; 
	var textareastyle=" font-family: 'Khmer OS Battambang'";
	<?php if (!empty($this->allstudentBygroup)) { foreach ($this->allstudentBygroup as $key=> $row){
			$discipline_type = $_model->getDisciplineStatus($this->row['id'],$row['stu_id']);
		?>
			inx = inx+1;
			<?php if ($row['sex']==1){
				$gender = $tr->translate("MALE");
				}else{
					$gender = $tr->translate("FEMALE");
				}?>
			<?php if ($key<1){?>
				str+='<thead><tr class="head-td" align="center">';
					str+='<th scope="col" ><?php echo $tr->translate("NUM");?></th>';
					str+='<th scope="col" ><?php echo $tr->translate("STUDEN_CODE");?></th>';
					str+='<th scope="col" ><?php echo $tr->translate("STUDEN_NAME");?></th>';
					str+='<th scope="col" ><?php echo $tr->translate("GENDER");?></th>';
					str+='<th scope="col" ><?php echo $tr->translate("HAVE_MISTACK");?></th>';
					str+='<th scope="col" ><?php echo $tr->translate("DISCIPLINE_TYPE");?></th>';
					str+='<th scope="col" ><?php echo $tr->translate("DESCRIPTION");?></th>';
				str+='</tr></thead>';
			<?php }?>
				var classRow="OddRow";
				if((inx%2)==0){
					classRow="EvenRow";
				}
				str+='<tr class="rowData '+classRow+'">';
				str+='<td data-label="<?php echo $tr->translate("NUM");?>">'+inx+'</td>';
				str+='<td data-label="<?php echo $tr->translate("STUDEN_CODE");?>"><?php echo $row['stu_code'];?></td>';
				str+='<td data-label="<?php echo $tr->translate("STUDEN_NAME");?>" style="text-align: left;">&nbsp;<?php echo $row['stu_name'];?></td>';
				str+='<td data-label="<?php echo $tr->translate("GENDER");?>"><?php echo $gender;?><input type="hidden" name="student_id'+inx+'" id="student_id'+inx+'"  value="<?php echo $row['stu_id'];?>" ></td>';
				str+='<td data-label="<?php echo $tr->translate("HAVE_MISTACK");?>">';
					str+='<div class="custom-control custom-checkbox ">';
							str+='<input type="checkbox" class="checkboxMistake custom-control-input" <?php if (!empty($discipline_type['attendence_status'])){echo 'checked="checked"';}?> onclick="checkmistake('+inx+');" name="have_mistake'+inx+'" id="have_mistake'+inx+'"  >';
							str+='<label class="custom-control-label" for="have_mistake'+inx+'"><?php echo $tr->translate("HAVE_MISTACK");?>';
							str+='</label>';
						str+='</div>';
				str+='</td>';
				str+='<td data-label="<?php echo $tr->translate("DISCIPLINE_TYPE");?>">';
					str+='<input type="radio" onclick="checkmistake('+inx+');" <?php if ($discipline_type['attendence_status']==1){echo 'checked="checked"';}?>  name="mistake_type'+inx+'" id="mistake_types'+inx+'" value="1" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("SMALL_MISTACK");?></label>';
					str+='<input type="radio" onclick="checkmistake('+inx+');" <?php if ($discipline_type['attendence_status']==2){echo 'checked="checked"';}?> name="mistake_type'+inx+'" id="mistake_typem'+inx+'" value="2" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("MEDIUM_MISTACK");?></label>';
					str+='<input type="radio" onclick="checkmistake('+inx+');" <?php if ($discipline_type['attendence_status']==3){echo 'checked="checked"';}?> name="mistake_type'+inx+'" id="mistake_typeb'+inx+'" value="3" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("BIG_MISTACK");?></label>';
					str+='<input type="radio" onclick="checkmistake('+inx+');" <?php if ($discipline_type['attendence_status']==4){echo 'checked="checked"';}?> name="mistake_type'+inx+'" id="mistake_typeb'+inx+'" value="4" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("OTHER");?></label>';
				str+='</td>';
				str+='<td data-label="<?php echo $tr->translate("DESCRIPTION");?>"><input dojoType="dijit.form.Textarea" name="comment'+inx+'" type="text" value="<?php echo addslashes($discipline_type['description']);?>" style="'+textareastyle+'"></td>';
			str+='</tr>';
		    if(inx!=1) {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+inx);
			} else {
				$('#identity').val(inx);
			}
			dojo.html.set(dojo.byId("table_row"),str, {
				 parseContent: true,
			});
	<?php }
	}else{?>
    	   $('#identity').val('');
    	   document.getElementById("table_row").innerHTML = '';
	<?php }?>
}
function checkmistake(index){
	if($('#have_mistake'+index).is(':checked')){
	}else{
		$('#mistake_types'+index).attr('checked', false); 
		$('#mistake_typem'+index).attr('checked', false); 
		$('#mistake_typeb'+index).attr('checked', false); 
	}
}
function CheckAll(){
	var identity = $('#identity').val();
	check_type = $('input[name="attendence_opt"]:checked').val();
	if(identity==""){
		return false;
	}else{
		 var arrays = identity.split(',');
		 if(arrays!=""){
	    	 for(var i=1;i<= arrays.length;i++) {
	    		 if($("#check_all").is(':checked')){
	    			 if($('#have_mistake'+i).is(':checked')){
	    				 if(check_type==1){
	    					 $('#mistake_types'+i).attr('checked', true); 
	    				 }else if(check_type==2){
	    					 $('#mistake_typem'+i).attr('checked', true); 
	    				 }else{
	    					 $('#mistake_typeb'+i).attr('checked', true); 
	    				 }
	    			 }
	    		 }else{
	    			 $('input[value="'+check_type+'"]').attr("checked",false);
	    		 }
	    	}
		}
	}
}

url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,
			'noaddnew':0
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(olbranch==branch_id){
		    	 dijit.byId('group').set('value','<?php echo $this->row['group_id'];?>');   
		    }
		},
		error: function(err) {
		}
	});
}
</script>