<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("MISTAKE"));
	$frm =  $this->form_search;
?>	
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
			    	<div class="col-sm-8 pd-0">
			    		<h4 class="m-b-0"><i class="fa fa-gavel " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('MISTAKE');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right"></div>
    			</div>
    	</div>
		<div class="card-box">
			<form  action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("branch_id");?>
					 </div>
					  <div class="col-md-2 col-sm-2 col-xs-12">
					 	<input id="study_year" />
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<input id="group_name" />
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("grade");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("session");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("room");?>
					 </div>
				</div>
				<div class="form-group">
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("start_date");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">	
					 	<?php echo $frm->getElement("end_date");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					 </div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php  echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	//dojo.require("dojo.data.ObjectStore");
	dojo.require("dijit.form.DateTextBox");
dojo.ready(function(){
		var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		var group_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
		new dijit.form.FilteringSelect({
			store: academic_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "study_year",
			name: "study_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				academic_year = dijit.byId('study_year').get('value');
			}
		}, "study_year");
		new dijit.form.FilteringSelect({
		    store:group_store,
		    store: academic_store,
			queryExpr: "*${0}*",                      
		    required:false,
		    id: "group_name",
		    name: "group_name",
		    class:'fullside',  
		    value:'<?php echo $this->g_name['group_name'];?>',         
		    placeHolder:"<?php echo $tr->translate('SELECT_GROUP');?>",          
		    onChange: function() {  
		    }
		}, "group_name");

		var branch_id = dijit.byId('branch_id');
	 	branch_id.on('change', function(evt) {
	 		getAllGroupByBranch();
	 		getAllAcademicByBranch();
	    });
	 	getAllAcademicByBranch();
	 	getAllGroupByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	
		contentData = {
			'branch_id':branch_id
		}
		selectedId = '';
		if(oldBranch==branch_id){
			selectedId = '<?php echo $this->search['study_year']?>';
		}
		
		getAllYear(url_getacademic,contentData,selectedId);
}
url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group_name').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group_name').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group_name').set('store',group_store);   
		    <?php if (!empty($this->search['group_name'])){?>
		    dijit.byId('group_name').set('value','<?php echo $this->search['group_name'];?>');   
		    <?php }?>
		},
		error: function(err) {
		}
	});
}
</script>