<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Add Student Register')); 
?>
<style>
	select{ width:100%;}
	fieldset{  background:none;}
	.red{ color: red; padding-left:5px;}
	.tab-content.vertical div.tab-pane {
	    overflow-y: auto;
	    max-height: 300px;
	}
	.tab-content.vertical div.tab-pane {
	    overflow-y: auto;
	    max-height: 300px;
	   
	}
.tab-content.vertical div.tab-pane {
    min-height: 71px !important;
}
.tablesorter tr td{
		border: 1px solid #000;	
	}
</style>
<div class="card">
	<div class="card-content collapse show">
		<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
   				if(this.validate()) {
    				year = dijit.byId('study_year').get('value');
   					if(year==-1){
         				dijit.byId("study_year").focus();
        				return false;
    				}
					dijit.byId('save_new').set('disabled',true);	
					dijit.byId('save_close').set('disabled',true);
    				return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-user-plus" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Add Student Register');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	        	<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDENT_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CUSTOMER_TYPE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select class="fullside" name="customer_type" id="customer_type" dojoType="dijit.form.FilteringSelect" onchange="clearControll();">
				    			<option value="1">Student Payment</option>
				    			<option value="2">Customer Payment</option>
				    		</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STUDENT_TYPE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select type="text" name="student_type" id="student_type" class="fullside" dojoType="dijit.form.FilteringSelect" onchange="getallstudentname();" >
								<option value="1"><?php echo $tr->translate("Old Student");?></option>
								<option value="2"><?php echo $tr->translate("Tested Student");?></option>
								<option value="3"><?php echo $tr->translate("CRM");?></option>
								<option value="4"><?php echo $tr->translate("Placement Test");?></option>
								<option value="5"><?php echo $tr->translate("New Student");?></option>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STUDENT_NAME");?> <span class="required">*</span>:</label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
							<input id="old_stu" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NAME_KH");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="kh_name" id="kh_name" class="fullside" dojoType="dijit.form.TextBox"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NAME_EN");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<div class="col-md-6 col-sm-6 col-xs-6">
	                   			<input type="text" name="en_name" id="en_name" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox"/>
	                   		</div>
	                   		<div class="col-md-6 col-sm-6 col-xs-6">
	                   			<input type="text" name="last_name" id="last_name" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox"/>
	                   		</div>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SEX");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select type="text" name="sex" id="sex" class="fullside" required="false" dojoType="dijit.form.FilteringSelect" >
								<option value="1"><?php echo $tr->translate("MALE");?></option>
								<option value="2"><?php echo $tr->translate("FEMALE");?></option>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DOB");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input name="dob" id="dob" constraints="{datePattern:'dd/MM/yyyy'}"  dojoType="dijit.form.DateTextBox" value="now" class="fullside" type="text" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PARENT_PHONE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="parent_phone" id="parent_phone" class="fullside" dojoType="dijit.form.TextBox"/>
	                   </div>
	                </div>
	           </div>
	           <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("STUDY_INFO");?> 
	                   </label>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GROUP");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select required="false" name="group" id="group" type="text"  onchange="getInfoBygroup();"  class="fullside" dojoType="dijit.form.FilteringSelect" autoComplete="false" queryExpr="*${0}*"  >
				    			<option value="-1"> -----<?php echo $tr->translate("SELECT_GROUP");?>----- </option>
				    			<?php if(!empty($this->group)){foreach ($this->group as $group){?>
				    			<option value="<?php echo $group['id']?>"><?php echo $group['name']?></option>
				    			<?php }}?>
				    		</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ACADEMIC_YEAR");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select type="text" dojoType="dijit.form.FilteringSelect" class="fullside" name="study_year" id="study_year" autoComplete="false" queryExpr="*${0}*"  >
								<option value=""><?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?></option>
								<?php if(!empty($this->all_year)){foreach ($this->all_year as $year){?>
								<option value="<?php echo $year['id']?>"><?php echo $year['years']?></option>
								<?php }}?>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CULTURE_LEVEL");?> :</label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select type="text" dojoType="dijit.form.FilteringSelect" class="fullside" name="degree_culture" id="degree_culture" autoComplete="false" queryExpr="*${0}*"  >
								<?php if(!empty($this->degreeculture)){foreach ($this->degreeculture as $index => $rs){?>
								<option value="<?php echo $index?>"><?php echo $rs;?></option>
								<?php }}?>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DEGREE");?> <span class="required red">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input id="dept" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CLASS");?> <span class="required red">*</span>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input id="grade" /> 
							 <input class="fullside" dojoType="dijit.form.TextBox"  id="grade_fromgrouop" name="grade_fromgrouop" value="" type="hidden"  >
							 <input type="hidden" name="group_name" id="group_name" class="fullside" dojoType="dijit.form.TextBox"/>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SESSION");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select type="text" name="session" id="session" class="fullside" dojoType="dijit.form.FilteringSelect" autoComplete="false" queryExpr="*${0}*" >
								<?php if(!empty($this->all_session)){foreach ($this->all_session as $session){?>
								<option value="<?php echo $session['id']?>"><?php echo $session['name']?></option>		
								<?php }}?>						
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TIME");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input dojoType="dijit.form.TextBox"  class="fullside" id="study_hour" name="study_hour"  type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ROOM_NAME");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select required="false" type="text" name="room" id="room"  class="fullside" dojoType="dijit.form.FilteringSelect"  autoComplete="false" queryExpr="*${0}*" >
								<option value="0"><?php echo $tr->translate("SELECT_ROOM");?></option>
								<?php if(!empty($this->all_room)){foreach ($this->all_room as $room){?>
								<option value="<?php echo $room['id']?>"><?php echo $room['name']?></option>
								<?php }}?>
							</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PAID_DATE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" dojoType="dijit.form.DateTextBox" required="true" constraints="{datePattern:'dd/MM/yyyy'}" required="1" value="<?php echo date("Y-m-d");?>" name="paid_date" id="paid_date" class="fullside"/>
	                   </div>
	                </div>
	           </div>
	           <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PHOTO");?> 
	                   </label>
	                </div>
					<div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" >
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<div class="account-image" style="padding-right: 821px;">
								<div class="image-box">
									<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/no-profile.png';?>" alt=""  />
								</div>
							</div>
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("OFFICIAL_RECEIPT");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("RECEIPT_NO");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input readonly type="text" style="color: red;" required="1" dojoType="dijit.form.ValidationTextBox" name="receipt_no" id="receipt_no" class="fullside" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BALANCE");?> <span class="required red">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
							<input type="text"  name="balance" id="balance" class="fullside" dojoType="dijit.form.NumberTextBox"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ចុចសងប្រាក់");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="start_date" id="start_date" value="now" class="fullside" dojoType="dijit.form.DateTextBox"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="note" id="note" class="fullside"  style="min-height:40px;" dojoType="dijit.form.Textarea"/>
	                   </div>
	                </div>
	           </div>
	           <div class="card-box" >
		           <div class="form-group" style="background: #d8e0e2; padding: 5px 15px; margin: 0; border: solid 1px #697996; border-radius: 2px;">
			           <div class="col-md-3 col-sm-3 col-xs-12">
			           		 <div class="form-group">
			                   <label class="control-label  col-md-3 col-sm-3 col-xs-12" style="font-size: 16px;" ><?php echo $tr->translate("CATEGORY");?></label>
			                   <div class="col-md-9 col-sm-9 col-xs-12">
			                   		<select style="height: 40px;" required="false" type="text" name="category" id="category"  class="fullside" dojoType="dijit.form.FilteringSelect"  autoComplete="false" queryExpr="*${0}*" onchange="getgradebyDegree(1,1,2);" >
											<option value="-1"></option>
											<?php if(!empty($this->rs_type)){foreach ($this->rs_type as $rs){?>
											<option value="<?php echo $rs['id']?>"><?php echo $rs['name']?></option>
											<?php }}?>
			                   		</select>
			                   </div>
			                </div>
			           </div>
			           <div class="col-md-5 col-sm-5 col-xs-12">
			           		 <div class="form-group">
			                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" style="font-size: 16px;" >វគ្គសិក្សា/សេវាកម្ម<br />ផលិតផល</label>
			                   <div class="col-md-7 col-sm-7 col-xs-12">
			                   		<input id="item" name="item" />
			                   </div>
			                </div>
			           </div>
			           <div class="col-md-4 col-sm-4 col-xs-12">
			           </div>
			           <div class="col-md-4 col-sm-4 col-xs-12">
			           </div>
			           <div style="clear: both;"></div>
		           </div>
		        </div>
	       </div>
	       <!-- Tab Menu -->
	    	<div class="card-box">
	    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
		            <li class="nav-item active">
		                <a class="nav-link " data-toggle="tab" href="#panel21" role="tab"><i class="fa fa-user ml-2"></i> <?php echo $tr->translate("SERVICE_AND_PRODUCT");?></a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
		                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("PAYMENT_HISTORY");?>
		                </a>
		            </li>
		        </ul>
		    </div>
		        <div class="tab-content vertical">
			        <!--Panel 1-->
			        <div class="tab-pane fade in active" id="panel21" role="tabpanel">
			        	 <div class="card-box">
			        	 	<div class="col-md-12 col-sm-12 col-xs-12">
			        	 		<table border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
								 	<tr id="head-title" class="head-td"  align="right" style="background:#ececec;font-size:12px;color:#000"></tr>
								</table>
			        	 	</div>
			        	 </div>
			       	</div>
			       	<!--/.Panel 1-->
			       	<!--Panel 2-->
			        <div class="tab-pane fade in " id="panel22" role="tabpanel">
			        	 <div class="card-box">
			        	 	<div class="col-md-12 col-sm-12 col-xs-12">
			        	 		<table border="1" id="table_paymenthistory" style="width:100%;border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
									 <tr id="head-paymenttitle" class="head-td" align="right" style="background:#dff7fd;font-size:12px;"></tr>
									</table>
			        	 	</div>
			        	 </div>
			       	</div>
			    </div>
			<div class="card-box">
	        	<div class="col-md-4 col-sm-4 col-xs-12">
	        	</div>
	        	<div class="col-md-4 col-sm-4 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PAYMENT_METHOD");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select required="false" type="text" name="payment_method" id="payment_method" class="fullside" dojoType="dijit.form.FilteringSelect"  autoComplete="false" queryExpr="*${0}*" onchange="getgradebyDegree(1,1,2);" >
								<?php if(!empty($this->rs_paymenttype)){foreach ($this->rs_paymenttype as $rs){?>
								<option value="<?php echo $rs['key_code']?>"><?php echo $rs['view_name']?></option>
								<?php }}?>
	                   		</select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NUMBER");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="number" id="number" dojoType="dijit.form.TextBox" class="fullside" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("READ_IN_KHMER");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<Textarea type="text" name="money_in_khmer" id="money_in_khmer" readonly="readonly" dojoType="dijit.form.TextBox" class="fullside" ></Textarea>
	                   </div>
	                </div>
	        	</div>
	        	<div class="col-md-4 col-sm-4 col-xs-12">
	        		
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FINE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text"  onkeyup="onKeyUpDeduct();"  name="penalty" id="penalty"  value="0" dojoType="dijit.form.NumberTextBox" />
	                   </div>
	                </div>
	        		<div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TOTAL_PAYMENT");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" readonly="readonly" name="grand_total" id="grand_total" value="0" dojoType="dijit.form.NumberTextBox" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CREDIT_MEMO");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text"  onkeyup="" readOnly="1"  name="credit_memo" id="credit_memo"  value="0" dojoType="dijit.form.NumberTextBox" />
							<input type="hidden" name="credit_memo_after" id="credit_memo_after" dojoType="dijit.form.TextBox" value="0" />
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PAID_AMOUNT");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="paid_amount" id="paid_amount" value="0" onkeyup="onPaidAmount();" dojoType="dijit.form.NumberTextBox" />
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BALANCE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="balance_due" readonly="readonly" id="balance_due" value="0" style="color:red;" dojoType="dijit.form.NumberTextBox" />
	                   </div>
	                </div>
	        	</div>
	        </div>
	        <div class="clearfix">
	        	<input type="hidden" id="identity" name="identity" />
				<input type="hidden" id="identitystock" name="identitystock" />
				<input type="hidden" dojoType="dijit.form.TextBox" name="br_address" value="<?php echo $this->branch_info['br_address'];?>" id="br_address" />
				<input type="hidden" dojoType="dijit.form.TextBox" name="br_tel" value="<?php echo $this->branch_info['branch_tel'];?>" id="br_tel" />
				<input type="hidden" dojoType="dijit.form.TextBox" value="<?php echo $this->branch_info['branch_nameen']?>" name="br_code" id="br_code" />
				<input type="hidden" dojoType="dijit.form.TextBox" value="<?php echo $this->exchange_rate;?>" name="ex_rate" id="ex_rate" />
				<input type="hidden" dojoType="dijit.form.TextBox" name="credit_memo_id" id="credit_memo_id" />
				<input type="hidden" name="test_fee" id="test_fee" value="<?php echo $this->deduct?>" dojoType="dijit.form.TextBox" />
	        </div>
		    <div class="card-box">
               	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               		<input type="submit"  name="save_close" id="save_close" value="1" label="<?php echo $tr->translate('SAVE_CLOSE');?>"   dojoType="dijit.form.Button" 
					 	iconClass="dijitEditorIcon dijitEditorIconSave"  />
					<input type="button" onclick="submitDataAddNew();" name="save_new" id="save_new" value="1" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
					 	iconClass="dijitEditorIcon dijitEditorIconSave"  />
					 <input type="button" value="1" label="<?php echo $tr->translate('PRINT');?>" id="busyButton" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave('','','');displayNone();"/> 
	    		</div>
	    	</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.number");
	dojo.require("dojo.data.ObjectStore");
	dojo.require('dijit.form.TextBox');
	dojo.require("dijit.form.Textarea");
	var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_dept));?> );
	item_store = getDataStorefromJSON('id','name');
	dojo.ready(function(){
		getStudentNo(1,'');
		getReceiptNo('','');

		new dijit.form.FilteringSelect({
			store: dept_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			required: false,
			id: "dept",
			name: "dept",           
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_DEGREE");?>",          
			onChange: function() {  
				dept_id = dijit.byId('dept').get('value');
				dijit.byId('grade').attr('value','');
				getgradebyDegree(dept_id,a='',1); 
				getStudentNo(dept_id,'');
			}
		}, "dept");
		
		new dijit.form.FilteringSelect({
			autoComplete: false,
			required: false,
			queryExpr: "*${0}*",                      
			id:"grade",
			name:"grade",           
			class:'fullside', 
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {
				//dijit.byId('discount_percent').attr('value','0');
				//dijit.byId('discount_fix').attr('value','0');
			}
		}, "grade");

		new dijit.form.FilteringSelect({
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "old_stu",
			name: "old_stu",   
			required:false,        
			class: 'fullside', 
			placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
			onChange: function() {  
				stu_id = dijit.byId('old_stu').get('value');
				//getPaymentHistory(stu_id);
				getOldStudentInfo();
			}
		}, "old_stu");

		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "item",
			name: "item",   
			required:false,        
			class: 'fullside', 
			onChange: function() {  
				addRow();
			}
		}, "item");
		
		/*new dijit.form.FilteringSelect({
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "old_studens",
			name: "old_studens",  
			required:false,         
			class: 'fullside', 
			placeHolder:"<?php //echo $tr->translate("SELECT_STUDENT_NAME");?>",          
			onChange: function() {  
				getStudentBalance();
				getOldStudentInfo();
				getCreditMemo();
				getOldVildateToStartDateRegister();
			}
		}, "old_studens");*/

		dijit.byId('dept').attr('value','<?php echo $this->degree_row['degree'];?>');
		getallstudentname();
		getgradebyDegree(-1,1,2);
});		
	
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-grade')); ?>';
function getgradebyDegree(dept_id,a,type=1){
	if(type==1){
		if(dept_id==''){return false;}
	}else if(type==2){
		dept_id = dijit.byId("category").get("value");
	}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				if(type==1){
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store);  
				    if(a!=""){
				    	dijit.byId('grade').attr('value',a);
			        }
				}else{
					item_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('item').set('store',item_store);  	
				}
			},
			error: function(err) {
			}
		});
}

	var url_getstuno = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-stu-no')); ?>';
	function getStudentNo(dept_id,condition){
		/*if(dept_id==''){
			return false;
		}
		type = dijit.byId('student_type').get('value'); // old student or new student
		if(type == 3){
		}else{
			dojo.xhrPost({
				url:url_getstuno,
				content:{
					'dept_id':dept_id   // student id ??????? degree ???  prefix ?? ? ????????????????
					},
				handleAs:"json",
				load: function(data) {
					  dijit.byId('stu_id').attr('value',data); 
					  if(condition==1){ 
						getReceiptNo(data,'');
					  }
				},
				error: function(err) {
					alert(err+"1");
				}
			});
		}*/
	}
	var url_getreceipt_no = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-receipt-no')); ?>';
	function getReceiptNo(stu_id,submit){
		dojo.xhrPost({
			url:url_getreceipt_no,
			content:{
				//'dept_id':dept_id   // student id ??????? degree ???  prefix ?? ? ????????????????
				'dept_id':1			  // ?????????? degree ?????????????????????????
				},
			handleAs:"json",
			load: function(data) {
				  dijit.byId('receipt_no').attr('value',data); 
				  if(stu_id!=''){
					  dojo.byId("lb_receipt_no").innerHTML = data;
					  printSave(stu_id,data,submit);
				  }
			},
			error: function(err) {
				alert(err+"2");
			}
		});
	}
	// set regisetr info to readonly when pay for service
// Remove field readonly when balance <= 0 for get all old information of student
function removeReadOnly(){
	/*var customer_type = dijit.byId("customer_type").get("value");
	if(customer_type!=3 || customer_type!=4){
		dijit.byId("start_date").set('readOnly',false);
		dijit.byId("end_date").set('readOnly',false);
		dijit.byId("study_year").set('readOnly',false);
		dijit.byId("dept").set('readOnly',false);
		dijit.byId("grade").set('readOnly',false);
		dijit.byId("session").set('readOnly',false);
		dijit.byId("study_hour").set('readOnly',false);
		dijit.byId("payment_term").set('readOnly',false);
	}*/
}
//calculator date by select term_payment
	/*function getDateTerm() {
		start_end=dijit.byId('start_end').get('value');
		if(start_end==-1){
			payment_term=dijit.byId('payment_term').get('value');
			start_date=dijit.byId('start_date').get('value');
			var a = new Date(start_date);
			if(payment_term==1){
				var mm = a.getMonth() +1+ 1;
			}
			if(payment_term==2){
				var mm = a.getMonth() +3+ 1;
			}else if(payment_term==3){
				mm = a.getMonth()+6+1;
			}else if(payment_term==4){
				mm = a.getMonth()+12+1;
			}
			var dd = a.getDate();
			 if(dd<10){
				 dd = "0"+dd;
			}
			 if(mm<10){
				 mm = "0"+mm;
			}
			var y = a.getFullYear();
			var epx_date = y + '-'+ mm + '-'+dd ;
			
			dijit.byId('end_date').attr('value',epx_date);
		}			
	}*/
	function getTestFee(){
		student_type = dijit.byId('student_type').get('value');
		if(student_type==1){
			dijit.byId('deduct').attr('value','<?php echo $this->deduct ?>');
		}else{
			dijit.byId('deduct').attr('value',0);
		}
	}
</script>
<script type="text/javascript">
function getInfoBygroup(){
	url_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getgroupinfo'));?>';
	group = dijit.byId('group').get('value');
	if(group==''){return false;}
	if(group==-1){
		dijit.byId('study_year').set('readOnly',false);
		dijit.byId('dept').set('readOnly',false);
		dijit.byId('grade').set('readOnly',false);
		dijit.byId('session').set('readOnly',false);
		//dijit.byId('room').set('readOnly',false);
		return false;
	}
	dojo.xhrPost({
		url:url_group,	
		content:{ 
			'group_id': group
		},
		handleAs:"json",
		load: function(data) {
			dijit.byId('study_year').set('value',data.academic_year);
			dijit.byId('study_year').set('readOnly',true);
			dijit.byId('dept').set('value',data.degree);
			dijit.byId('dept').set('readOnly',true);
			dijit.byId('grade').set('readOnly',true);
			dijit.byId('grade_fromgrouop').set('value',data.grade);
			getgradebyDegree(data.degree,data.grade,1);
			dijit.byId('session').set('value',data.session);
			dijit.byId('session').set('readOnly',true);
			dijit.byId('room').set('value',data.room_id);
			dijit.byId('group_name').attr('value',data.group_code);
		},
		error: function(err) {
			alert(err+"5");
		}
	});
}
function test1(){
}
function submitDataClose(){
	if(dijit.byId('office_receipt').validate()) {
		dijit.byId('save_close').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";	
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/registrar/register";
			},
			error: function(e) {
			}
		});
	}
}
function submitDataAddNew(){
	if(dijit.byId('office_receipt').validate()) {
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";		
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/registrar/register/add";
			},
			error: function(e) {
			}
		});
	}
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
function getMonthByNumber(m){
	var monthName=[
		 "01",
		 "02",
		 "03",
		 "04",
		 "05",
		 "06",
		 "07",
		 "08",
		 "09",
		 "10",
		 "11",
		 "12",
		];
		return (monthName[m-1]);
}

</script>
<div class="dijitHidden" style="padding: 0px; margin: 0px;">
	<div id="terms" data-dojo-type="dijit.Dialog" style="width:23.5cm;height: 15.7cm ; overflow-y: scroll" align="center" data-dojo-props="title:'<?php echo $tr->translate("OFFICIAL_RECEIPT");?>'"  >
		<style>
			.hearder_table{height:25px !important;}
			.defaulheight{line-height: 22px !important;}
		</style>
		<div id="PrintReceipt" style="width: 22cm !important; padding: 0px;">
			<table width="100%"  class="print" cellspacing="0"  cellpadding="0" style="height:13cm; font-family: 'Khmer OS Battambang' !important; font-size:11px !important; margin-top: -5px;white-space:nowrap;">
				<tr height="90px;">
					<td colspan="10"  style="" align="center" valign="top">
						<?php echo $this->header?>
					</td>
				</tr>
				<tr height="40px;">
					<td colspan="10"  style="" align="center" valign="top">
						<table width="100%" style="font-size: 10px;margin-bottom: 0px;" >
							<tr>
								<td width="25%">&nbsp;
								</td>
								<td width="50%" valign="top" align="center" style="font-family:Khmer OS Muol, Times New Roman;font-size: 16px;line-height: 20px">
									<div>បង្កាន់ដៃបង់ប្រាក់</div>
									<div>Official Receipt</div>
								</td>
								<td width="25%" valign="top" align="left">
									<div style="font-size: 15px;font-family:Battambang,Arial,Helvetica,sans-serif;"><u>Receipt N<sup>o</sup></u> <label id="lb_receipt_no"></label></div> 
									<div style="font-size: 14px;font-weight: bold;font-family: arail">Pmt Date : <label id="lb_date" class=" one bold"></label></div>
									<div style="font-size:10px;"><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<style>
					.bold{
						font-weight:bold;
						}
						 .noted{
						    white-space: pre-wrap;     
							word-wrap: break-word;      
							word-break: break-all;
							white-space: normal;
							font:12px 'Khmer OS Battambang';
							border: 1px solid #000;
		                    line-height:20px;font-weight: normal !important;
							padding:2px;
						}
				</style>
				<tr>
					<td colspan="10" valign="top">
						<table class='defaulheight' width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:12px;white-space:nowrap;margin-top:-5px;line-height: 11px;">
							<tr>
								<td>Student's ID </td>
								<td> : &nbsp;&nbsp;<label id="lb_stu_id" class="one bold"></label></td>
								<td>Dob</td>
								<td> : &nbsp;&nbsp;<label id="lb_dob" class="one bold"></label> </td>
								<td >Grade</td>
								<td> : &nbsp;<label id="lb_grade" class="one bold"></label> </td>
							</tr>
							<tr>
								<td>Student's Name</td>
								<td colspan="1"> : &nbsp;&nbsp;<label id="lb_name" class="one bold"></label> </td>
								<td>Phone</td>
								<td> : &nbsp;&nbsp;<label id="lb_phone" class="one bold"></label> </td>
								<td>Academic Year</td>
								<td>  : &nbsp;<label id="lb_study_year" class="one bold"> </label> </td>
							</tr>
							<tr>
								<td>Gender </td>
								<td> : &nbsp;&nbsp;<label id="lb_sex" class=" one bold"></label></td>
								<td>Degree</td>
								<td> : &nbsp;&nbsp;<label id="lb_dept" class="one bold"></label> </td>
								<td>Session</td>
								<td> : &nbsp;<label id="lb_session" class="one bold"></label> </td>
							</tr>
							<tr>
								<td colspan="6">
									<div id="t_amountmoneytype"></div>
								</td>
							</tr>
							<tr>
								<td colspan="5">
									<table width="100%" style="marin-top:5px;font-size:12px; white-space:nowrap;line-height:15px;border-collapse:collapse;">
										<tr>
											<td align="left" colspan="3">
												 <div class="col-md-6 col-sm-6 col-xs-12" style="width:49%;float: left;margin-right:1%">Note
												 	<div style="font-size:10px;min-height: 70px;border:1px solid #000;" id="lbl_note" class="noted" ></div>
												 </div>
												 <div class="col-md-6 col-sm-6 col-xs-12" style="width:50%;float: left;">In Khmer
												 	<div style="font-size:10px;min-height: 70px;border:1px solid #000;" id="lb_read_khmer" class="noted" ></div>
												 </div>
											</td>
										</tr>
										<tr>
											<td  align="center">Cashier</td>
											<td align="center">Customer</td>
											<td align="center">Verified By</td>
										</tr>
										<tr>
											<td  align="center">
												<div style="margin-top:60px;font-size:10px;"></div>
												<?php 
												   $session_user=new Zend_Session_Namespace('authstu');
												   $last_name=$session_user->last_name;
												   $username = $session_user->first_name;
												   echo "".$last_name." ".$username;
												?>
											</td>
											<td align="center"></td>
											<td align="center"></td>
										</tr>
									</table>
								</td>
								<td valign="top" >
									<table width="100%" style="marin-top:5px;font-size:12px; white-space:nowrap;line-height:15px;border-collapse:collapse;">
										<tr>
											<td>Penalty</td>
											<td>: $</td>
											<td align="right">&nbsp;&nbsp; <label id="lb_fine" ></label></td>
										</tr>
										<tr>
											<td>Total Payment</td>
											<td>: $</td>
											<td align="right">&nbsp;&nbsp; <label id="lb_total_payment" ></label></td>
										</tr>
										<tr>
											<td><div>Credit Memo</div></td>
											<td>: $</td>
											<td align="right">&nbsp;&nbsp; <label id="lb_credit_memo" ></label></td>
										</tr>
										<tr>
											<td><div>Paid Amount</div></td>
											<td>: $</td>
											<td align="right">&nbsp;&nbsp; <label id="lb_paid_amount" ></label></td>
										</tr>
										<tr>
											<td><div>Balance</div></td>
											<td>: $</td>
											<td align="right">&nbsp;&nbsp;<label id="lb_balance_due" ></label></td>
										</tr>
										<tr>
											<td><div>Payment Method</div></td>
											<td></td>
											<td align="right">&nbsp;&nbsp;<label id="lb_paymentmethod" ></label></td>
										</tr>
										<tr>
											<td><div>Number/Bank</div></td>
											<td></td>
											<td align="right">&nbsp;&nbsp;<label id="lb_paymentnumber" ></label></td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
		<div id="PrintReceipt1">
			<div style="border: 1px dotted #000;width:100%;margin-bottom: 20px;"></div>
			<div id="innerPrintReceipt"></div>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
			<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
					type="button" onclick="hideDialog();">Cancel</button>
			<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconUndo"
					type="button" onclick="printSave('','','');"><?php echo $tr->translate("REFRESH");?></button>		
			<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
					 type="button" onclick="confirmBeforePrint();"><?php echo $tr->translate("SAVE_PRINT");?></button>
	</div>
</div>
<div class="dijitHidden" style="padding: 0px; margin: 0px;">
	<div id="alertBeforePrint" data-dojo-type="dijit.Dialog" style="width:10cm;height: 5cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("បោះពុម្ពបង្កាន់ដៃ");?>'"  >
		<table width="100%"  class="print" cellspacing="0"  cellpadding="0" style="height:4cm;color:red; font-family: 'Khmer OS Battambang' !important;font-size:15px !important;white-space:nowrap;">
			<tr>
				<td align="center" >
					តើលោកអ្នកពិតជាចង់បោះពុម្ពបង្កាន់ដៃនេះ មែនទេ? <br />
					Do you really want to print ?
				</td>
			</tr>
			<tr>
				<td align="center">
					<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
						type="button" onclick="hideDialog1();">No</button>
					<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
						type="button" onclick="printSave('','',1)"><?php echo $tr->translate("Yes");?></button>
				</td>
			</tr>
		</table>
	</div>
</div>
<script>
function confirmBeforePrint(){
	dijit.byId('alertBeforePrint').show();
}
function displayNone(){
	document.getElementById('PrintReceipt1').style.display="none";
}
function printSubmit(){	
	dojo.byId('innerPrintReceipt').innerHTML = dojo.byId('PrintReceipt').innerHTML;
	window.frames["print_frame"].document.body.innerHTML = dojo.byId('PrintReceipt').innerHTML<?php if($this->data['receipt_print']==2){ ?>+dojo.byId('PrintReceipt1').innerHTML<?php }?>;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
	hideDialog1();
    dijit.byId('office_receipt').submit();
}
function hideDialog(){
	dijit.byId('terms').hide();
}
function hideDialog1(){
	dijit.byId('alertBeforePrint').hide();
}
function getallstudentname(){//
	student_type = dijit.byId("student_type").attr("value");
	if(student_type==1){//old
		var url_data = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getallstudent')); ?>';
	}else if(student_type==2){//tested student
		var url_data = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getallstudenttest')); ?>';
	}else if(student_type==3){//crm
		url_data='';
	}
	else if(student_type==4){//new test
		SetReadonly();
		return false;
	}
	dojo.xhrPost({
		url:url_data,
		content:{
			'student_name':1,
		},
		handleAs:"json",
		load: function(data) {
			student_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('old_stu').set('store',student_store);  
		},
		error: function(err) {
		}
	});
}
function SetReadonly(){
	dijit.byId("kh_name").attr('value','');
	dijit.byId("en_name").attr('value','');
	dijit.byId("last_name").attr('value','');
	dijit.byId("dob").set('value','');
	dijit.byId("parent_phone").attr('value','');
	
	dijit.byId("kh_name").set('readOnly',false);
	dijit.byId("en_name").set('readOnly',false);
	dijit.byId("last_name").set('readOnly',false);
	dijit.byId("sex").set('readOnly',false);
	dijit.byId("dob").set('readOnly',false);
	dijit.byId("parent_phone").set('readOnly',false);
	
	dijit.byId("degree_culture").set('readOnly',false);
	dijit.byId("dept").set('readOnly',false);
	dijit.byId("grade").set('readOnly',false);
	
	dijit.byId("group").set('readOnly',true);
	dijit.byId("study_year").set('readOnly',true);
	dijit.byId("session").set('readOnly',true);
	dijit.byId("study_hour").set('readOnly',true);
	dijit.byId("room").set('readOnly',true);
}

function setID(){
	stu_id = dijit.byId('old_stu').get('value');
	getPaymentHistory(stu_id);
}
var url_studentpayment = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-studentpaymenthistory')); ?>';
function getPaymentHistory(student_id){
	tem='';
	dojo.xhrPost({
		url:url_studentpayment,
		content:{
			'student_id':student_id,
		},
		handleAs:"json",
		load: function(respone) {
			tem='<table class="collape tablesorter" style="font-size:12px;" id="table" width="100%">'
				+'<thead><tr><th class="tdheader"><?php echo $tr->translate('NO');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('SERVICE_CATE');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('SERVICE_NAME');?></th>'
				+'<th class="tdheader" ><?php echo $tr->translate('PAID_DATE');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('RECEIPT_NO');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('SCHOLARSHIP');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('SCHOLARSHIP_AMOUNT');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('PAYMENT_TERM');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('QTY');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('PRICE');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('LATE_FEE');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('EXTRA_FEE');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('DISCOUND');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('DISCOUNT');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('PAID_AMOUNT');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('START_DATE');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('END_DATE');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('REMARK');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('STATUS');?></th>'
				+'<th class="tdheader"><?php echo $tr->translate('USER');?></th>'
			+'</thead>';
			no=0;
			for(i=0;i<respone.length;i++){
				no++;
				scholarship_percent='-';
				scholarship_amount='-';
				if(respone[i].type==1){//tution fee
					respone[i].service_cate="Tuition Fee";
					respone[i].service_name=respone[i].major_name;
				}else if(respone[i].type==4){//product
					respone[i].service_cate=respone[i].product_category;
					respone[i].payment_term='';
				}
				tem+= '<tr id=tr_'+i+' style="background-color:none;font-size:12px;text-align:center;">';
				tem += '<td>'+no+'</td>';
				tem += '<td style="text-align:left;">'+respone[i].service_cate+'</td>';
				tem += '<td>'+respone[i].service_name+'</td>';
				tem += '<td>'+respone[i].create_date+'</td>';
				tem += '<td>'+respone[i].receipt_number+'</td>';
				tem += '<td>'+respone[i].scholarship_percent+'</td>';
				tem += '<td>'+respone[i].scholarship_amount+'</td>';
				tem += '<td>'+respone[i].payment_term+'</td>';
				tem += '<td>'+respone[i].qty+'</td>';
				tem += '<td>'+respone[i].fee+'</td>';
				tem += '<td>'+respone[i].late_fee+'</td>';
				tem += '<td>'+respone[i].extra_fee+'</td>';
				tem += '<td>'+respone[i].discount_percent+'</td>';
				tem += '<td>'+respone[i].discount_fix+'</td>';
				tem += '<td>'+respone[i].paidamount+'</td>';
				tem += '<td>'+respone[i].start_date+'</td>';
				tem += '<td>'+respone[i].validate+'</td>';
				tem += '<td>'+respone[i].note+'</td>';
				tem += '<td>'+respone[i].void_status+'</td>';
				tem += '<td>'+respone[i].user+'</td>';
				tem+="</tr>";
			}
			tem+='</table>';
			dojo.byId('table_paymenthistory').innerHTML = tem;
		},
		error: function(err) {
		}
	});
}
function clearControll(){
	dijit.byId('kh_name').attr('value','');
	dijit.byId('en_name').attr('value','');
	dijit.byId('last_name').attr('value','');
	dijit.byId('parent_phone').attr('value','');
	customer_type = dijit.byId('customer_type').get('value');
	if(customer_type==2){//for customer
		
		dijit.byId("group_name").attr('value','');
		dijit.byId("old_stu").attr('value','');
		dijit.byId("group").set('readOnly',true);
		dijit.byId("study_year").set('readOnly',false);
		dijit.byId("degree_culture").set('readOnly',true);
		dijit.byId("dept").set('readOnly',true);
		dijit.byId("grade").set('readOnly',true);

		dijit.byId("session").set('readOnly',true);
		dijit.byId("study_hour").set('readOnly',true);
		dijit.byId("room").set('readOnly',true);
		dijit.byId("student_type").set('readOnly',true);
		dijit.byId("old_stu").set('readOnly',true);
		
	}else{
		dijit.byId("student_type").set('readOnly',false);
		dijit.byId("old_stu").set('readOnly',false);
	}
}
///get Gerneral old student
function getOldStudentInfo(){
	student_type = dijit.byId("student_type").attr("value");
	if(student_type==1){//old
		var url_getdata = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getstudentinfo')); ?>';
	}else if(student_type==2){//tested student
		var url_getdata = "<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-studenttestinfo')); ?>";
	}else if(student_type==3){//crm
		url_getdata='';
	}
	
	student_id=dijit.byId('old_stu').get('value');
	if(student_id==''){return false;}
	dijit.byId('kh_name').attr('value','');
	dijit.byId('en_name').attr('value','');
	dijit.byId('sex').attr('value','');
	dijit.byId('dept').attr('value','');
	dijit.byId('grade').attr('value','');	
	dijit.byId('old_stu').attr('value',student_id);
	
	dojo.xhrPost({
		url:url_getdata,
		content:{
			'student_id':student_id,
			},
		handleAs:"json",
		load: function(data) {
			   if(data){
				   if(student_type==1){//student info
					   if(data.group_id!= null && data.group_id>0){
							dijit.byId('group').attr('value',data.group_id);
							getInfoBygroup();
						}else{
							dijit.byId('group').attr('value','-1');
							dijit.byId('study_year').attr('value',data.academic_year);
							dijit.byId('dept').attr('value',data.degree);
							dijit.byId('session').attr('value',data.session);
							dijit.byId('room').attr('value',data.room);
							getgradebyDegree(data.degree,data.grade,1);
						}
					 
					   dijit.byId('degree_culture').attr('value',data.calture);
						dijit.byId('kh_name').attr('value',data.stu_khname);
						dijit.byId('en_name').attr('value',data.stu_enname);
						dijit.byId('last_name').attr('value',data.last_name);
						
						dijit.byId('sex').attr('value',data.sex);
						dijit.byId('parent_phone').attr('value',data.tel);
						dijit.byId('dob').attr('value',data.dob);
						if(data.photo!=''){
							$('#profile_wiew').attr('src', "<?php echo $this->baseUrl().'/images/';?>"+data.photo);
						}else{
							$('#profile_wiew').attr('src', "<?php echo $this->baseUrl().'/images/no-profile.png';?>");
						}
				 	}else if(student_type==2){//testing info
						dijit.byId("kh_name").attr("value",data.kh_name);
						dijit.byId("en_name").attr("value",data.en_name);
						dijit.byId("sex").attr("value",data.sex);
						dijit.byId("dob").attr("value",data.dob);
						dijit.byId("parent_phone").attr("value",data.phone);
						dijit.byId("dept").attr("value",data.degree_result);
						dijit.byId("session").attr("value",data.session_result);
						//getgradebyDegree(data.degree_result,data.grade_result,1);
			     }
			 }
		},
		error: function(err) {
			alert("get student"+err);
		}
	});
}
var template = '';
var service = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
date_format = '"dd/MM/yyyy"';
function addRow() {
		customer_type = dijit.byId('customer_type').get('value');
		if(customer_type==1){//for customer
			studentid = dijit.byId('old_stu').get('value');
			if(studentid==''){
				alert("Please select student !!!");
				dijit.byId('old_stu').focus();
				return false;
			}
		}else{

		}
		label = dijit.byId("item").attr('displayedValue');
		service_id = dijit.byId("item").get("value");
		if(service_id ==''){return false;}
		
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th><?php echo $tr->translate("SERVICES");?></th>';
			temp+='<th><?php echo $tr->translate("PAYMENT_TERM");?></th>';
			temp+='<th><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th><?php echo $tr->translate("SUBTOTAL");?></th>';
			temp+='<th><?php echo $tr->translate("EXTRA_FEE").'/'.$tr->translate("DEDUCT");?></th>';
			temp+='<th><?php echo $tr->translate("DISCOUNT_TYPE");?></th>';
			temp+='<th><?php echo $tr->translate("DISCOUNT");?> %</th>';
			temp+='<th><?php echo $tr->translate("DISCOUNT");?>$</th>';
			temp+='<th><?php echo $tr->translate("TOTAL_PAYMENT");?></th>';
			temp+='<th><?php echo $tr->translate("DATE_START");?></th>';
			temp+='<th><?php echo $tr->translate("END_DATE");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="30px" align="center"><img onclick="deleteRecord('+col+');calculateTotal('+col+');calculatePaidAmount('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="30px" align="center">'+no+'</td>';
			template+='<td style="width:150px;font-size:12px;"><label id="item_label_'+col+'">'+label+'<label><input type="hidden" value="'+service_id+'" dojoType="dijit.form.TextBox" name="item_id'+col+'" id="item_id'+col+'"/>';
			template+='<td style="width:180px"><select class="fullside" onchange="getservicefee('+col+');getValidate('+col+');" required="false" dojoType="dijit.form.FilteringSelect" id="term_'+col+'" name="term_'+col+'" >';
				<?php if(!empty($this->all_paymentterm))foreach($this->all_paymentterm as $term){?>
					template+='<option value="'+<?php echo $term['id']?>+'"><?php echo $term['name'];?></option>';
				<?php }?>
			template+='</select><input type="hidden" dojoType="dijit.form.TextBox" name="service_type_'+col+'" id="service_type_'+col+'"/></td>';
			column = 0;
			
			template+='<td style="width:70px"><input type="text" class="fullside" onkeyup="calculateTotal('+col+');" name="price_'+col+'" id="price_'+col+'"  value="0" dojoType="dijit.form.NumberTextBox"  /></td>';	
			template+='<td style="width:70px"><input type="text" class="fullside" onkeyup="calculateTotal('+col+');getValidate('+col+');" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox"  /></td>';	
			template+='<td style="width:70px"><input type="text" class="fullside" readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'"  value="0" dojoType="dijit.form.NumberTextBox"  /></td>';
			template+='<td style="width:70px"><input type="text" class="fullside" onkeyup="calculateTotal('+col+');" name="extra_fee'+col+'" id="extra_fee'+col+'" value="0" dojoType="dijit.form.NumberTextBox"  /></td>';
			template+='<td style="width:100px"><select class="fullside" required="false" dojoType="dijit.form.FilteringSelect" id="discount_type'+col+'" name="discount_type'+col+'" >';
			<?php if(!empty($this->rsdiscount))foreach($this->rsdiscount as $rsdis){?>
				template+='<option value="'+<?php echo $rsdis['id']?>+'"><?php echo $rsdis['dis_name'];?></option>';
			<?php }?>
			template+='</select></td>';
			
			template+='<td><input type="text" class="fullside" onkeyup="calculateTotal('+col+');" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox"  /></td>';
			template+='<td><input type="text" class="fullside" onkeyup="calculateTotal('+col+');"  name="discount_amount'+col+'" value="0" id="discount_amount'+col+'" dojoType="dijit.form.NumberTextBox"  /></td>';
			template+='<td><input type="text" class="fullside" readonly="readonly" onkeyup="calculateTotal('+col+');netTotal('+col+');"  name="total_amount'+col+'" value="0" id="total_amount'+col+'" dojoType="dijit.form.NumberTextBox"  /></td>';
			template+="<td style='width:170px;font-size:12px;'><input type='text' class='fullside' constraints="+"{datePattern:'dd/MM/yyyy'}"+" value='now' name='date_start_"+col+"' onchange='getValidate("+col+");' id='date_start_"+col+"' dojoType='dijit.form.DateTextBox' /></td>";
			template+='<td style="width:170px;font-size:12px;"><input type="text" class="fullside" constraints='+'{datePattern:"dd/MM/yyyy"}'+'  name="validate_'+col+'" id="validate_'+col+'" dojoType="dijit.form.DateTextBox" /></td>';
			template+='<input type="hidden" name="onepayment_'+col+'" id="onepayment_'+col+'" dojoType="dijit.form.TextBox" />';
			template+='<td><input type="text" class="fullside" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="<?php echo $tr->translate("NOTE");?>" style="width:140px;" /></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
		getservicefee(col);
		getValidate(col);
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
 function getValidate(key){
	 service_type = dijit.byId('service_type_'+key).get('value');
	 onepayment = dijit.byId('onepayment_'+key).get('value');
	 if(onepayment == 0){
		 amount= dijit.byId('qty_'+key).get('value');
		 term = dijit.byId('term_'+key).get('value');
		 start_date = dijit.byId('date_start_'+key).get('value');
		 if(term==1){
			 var a = new Date(start_date);
			  mm = a.getMonth()+amount+1;
		 }
		 else if(term==2){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(amount*3)+1;
		 }
		 else if(term==3){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(amount*6)+1;
		 }
		 else if(term==4){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(amount*12)+1;
		 }else{
			 var a = new Date(start_date);
			  mm = a.getMonth()+1;
		 }
		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		  }
		  if(mm<10){
		   mm = "0"+mm;
		  }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;
		 dijit.byId('validate_'+key).attr('value',epx_date);
		 
		 if(term==5){
			dijit.byId("validate_"+key).attr("value",null);
		 }		 
	 }
 }
function calculateTotal(index){
		price = dijit.byId('price_'+index).get('value');
		qty = dijit.byId('qty_'+index).get('value');
		qty=isNaN(qty)?1:qty;
		if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
		subtotal = price * qty;
		
		additional_fee = dijit.byId('extra_fee'+index).get('value');
		additional_fee = isNaN(additional_fee)?0:additional_fee;
		discount = dijit.byId('discount_amount'+index).get('value');
		discount = isNaN(discount)?0:discount;
		total = subtotal + additional_fee ;
		total_pay = total -discount ;
		dijit.byId('total_amount'+index).attr('value',subtotal);
		netTotal();
}
	function netTotal() {
		var netTotal=0;
		var netPaidAmount=0;
		var grandTotal=0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		total_payment = 0; //dijit.byId('grand_total').get('value');
	/////////////////////////////////////////////////////////////////////	
		var customer_type = dijit.byId("customer_type").get("value");
		if(customer_type!=2 || customer_type!=4){
			for(var n = 0; n < rowIDArray.length; n++) {
				netPaidAmount += dijit.byId('total_amount'+rowIDArray[n]).get('value');
			}
		}		
		if(customer_type==1){
			grandTotal = parseFloat(netPaidAmount) + parseFloat(total_payment);
		}else if(customer_type==2){
			grandTotal = parseFloat(total_payment);
		}else if(customer_type==3){
			grandTotal = netPaidAmount;
		}		
		ex_rate = dijit.byId('ex_rate').get('value');
		credit_memo = dijit.byId('credit_memo').get('value');
		credit_memo = isNaN(credit_memo)?0:credit_memo;
		
		penalty = dijit.byId('penalty').get('value');
		penalty = isNaN(penalty)?0:penalty;
		
		netAmount = grandTotal + penalty - credit_memo;
		
		dijit.byId('grand_total').attr('value',grandTotal);
		
		if(netAmount<0){
			dijit.byId('paid_amount').attr('value',0);
			dijit.byId('credit_memo_after').attr('value',abs(netAmount));
		}else{
			dijit.byId('paid_amount').attr('value',netAmount.toFixed(2));
			dijit.byId('credit_memo_after').attr('value',0);
		}
		readMoneyInKhmer(netAmount.toFixed(2));
	}
	
	function onPaidAmount(){
		net_amount = dijit.byId('net_amount').get('value');
		net_amount = isNaN(net_amount)?0:net_amount;
		
		paid_amount = dijit.byId('paid_amount').get('value');
		paid_amount = isNaN(paid_amount)?0:paid_amount;
		
		if(net_amount>=paid_amount){
			dijit.byId('balance_due').attr('value',(net_amount-paid_amount).toFixed(2));
		}else{
			alert("Can not paid more than total amount !!! ");
			dijit.byId('paid_amount').attr('value',(net_amount).toFixed(2));
			dijit.byId('balance_due').attr('value',0);
			dijit.byId('paid_amount').focus();
		}
	}
function onKeyUpDeduct(){
		/*grandTotal = dijit.byId('grand_total').get('value');
		grandTotal = isNaN(grandTotal)?0:grandTotal;
		
		credit_memo = dijit.byId('credit_memo').get('value');
		credit_memo = isNaN(credit_memo)?0:credit_memo;
		
		netAmount = grandTotal  - credit_memo - deduct;
		if(netAmount<0){
			dijit.byId('net_amount').attr('value',0);
			dijit.byId('credit_memo_after').attr('value',abs(netAmount));
		}else{
			dijit.byId('net_amount').attr('value',netAmount.toFixed(2));
			dijit.byId('credit_memo_after').attr('value',0);
		}
		
		readMoneyInKhmer(netAmount.toFixed(2));*/
		netTotal();
}
function readMoneyInKhmer(netTotal){
		var str = netTotal.toString();
        str_cent = 'សេន';
		first_decimal = str.substr(-2);
		last_decimal = str.substr(-1);
        if(first_decimal>0){string=' ចុច ';}else{string="";str_cent=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
	    first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
	    last_money_decimal = read_in_khmer_from_0_to_9(last_decimal)
	    money_khmer=read_money_in_khmer(netTotal);

	    if(first_decimal>0){string_en=' dot ';}else{string_en="";str_cent_en=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
	    first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
	    last_money_decimal_en = read_in_english_from_0_to_9(last_decimal)
	    money_english=read_money_in_english(netTotal);
	    read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លារគត់'

	    read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )'
	    
	    dijit.byId('money_in_khmer').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លារគត់'+read_eng);
}
 //get service fee or balance fee that student not yet pay
var url_service_fee = "<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getservicefee')); ?>";
function getservicefee(key){
		service_type = dijit.byId('service_type_'+key).get('value');
	 	stu_type = dijit.byId('student_type').get('value');
 			studentid = dijit.byId('old_stu').get('value');
			
 			service_id = dijit.byId('item_id'+key).get('value');
 			term = dijit.byId('term_'+key).get('value');
 			if(term==''){
 	 			return false;
 	 		}
			if(term==5){
				dijit.byId("price_"+key).set('readOnly',false);
				dijit.byId("price_"+key).attr("value",0);
				calculateTotal(key);
				return 0;
			}else{
				dijit.byId("price_"+key).set('readOnly',true);
			}
			study_year = dijit.byId('study_year').get('value');
 			dojo.xhrPost({
 				url:url_service_fee,
 				content:{
 					'term':term,
 					'service':service_id,
 					'year':study_year,
 					//'studentid':studentid,
 					},
 				handleAs:"json",
 				load: function(data) {
	 					dijit.byId("remark"+key).attr("value",'');
	 					//if(data.sms!=''){
	 						//dijit.byId("remark"+key).attr("value",data.sms);
	 						//dijit.byId("old_service_"+key).attr("value",data.id);
	 						//dijit.byId("validate_"+key).attr("value",data.validate);
	 					//}
	 					dijit.byId("price_"+key).attr("value",data.price);
	 					dijit.byId("onepayment_"+key).attr("value",data.onepayment);
	 					calculateTotal(key);
 				},
 				error: function(err) {
 				}
 			});
	 	
	 
 }
function printSave(new_stu_id,new_receipt,submit){		
		if(dijit.byId('office_receipt').validate()) {
			var identity = $('#identity').val();
			if(identity==''){
				alert("There is no record to save");
				dijit.byId("item").focus();
				return false;
			}
			receipt=dijit.byId("receipt_no").get("value");
			degree = dijit.byId('dept').get('value');
			stu_type = dijit.byId('student_type').get('value');

			if(stu_type==1){
				stu_id = dijit.byId("old_stu").attr('displayedValue');
			}else{
				stu_id = dijit.byId("stu_id").attr('displayedValue');
			}
			if(stu_type==5){
				if(new_stu_id==''){
					getStudentNo(degree,1);
				}else{
					stu_id = new_stu_id;
					receipt = new_receipt;
				}
			}else{
				stu_id = dijit.byId("old_stu").attr('displayedValue');
				if(new_receipt==''){
					getReceiptNo(stu_id);
					
				}else{
					receipt = new_receipt;
				}
			}	
			if(new_receipt==""){
				getReceiptNo(1,submit);
				submit=0;
			}
			
			//var today = new Date();
			today = dijit.byId("paid_date").get("value");
			var dd = today.getDate();
			var mon = today.toDateString().substr(4,3); //January is 0!
			var yyyy = today.getFullYear();
			dojo.byId("lb_stu_id").innerHTML = stu_id;		
			dojo.byId("lb_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
			dojo.byId("lbl_note").innerHTML = dijit.byId("note").attr('displayedValue');
			
			dojo.byId("lb_date").innerHTML  = dd+'-'+mon+'-'+yyyy;
			dojo.byId("lb_dob").innerHTML = dijit.byId("dob").attr('displayedValue');
			dojo.byId("lb_name").innerHTML = dijit.byId("kh_name").get('value')+" - "+dijit.byId("en_name").get('value');
			dojo.byId("lb_study_year").innerHTML = dijit.byId("study_year").attr('displayedValue');
			dojo.byId("lb_dept").innerHTML = dijit.byId('dept').attr('displayedValue');
			dojo.byId("lb_grade").innerHTML = dijit.byId("grade").attr('displayedValue')+"("+dijit.byId("group_name").attr('displayedValue')+")";
			dojo.byId("lb_phone").innerHTML = dijit.byId("parent_phone").attr('displayedValue');
			dojo.byId("lb_session").innerHTML = dijit.byId("session").attr('displayedValue');
			dojo.byId("lb_read_khmer").innerHTML = dijit.byId("money_in_khmer").attr('displayedValue');
			
			dojo.byId("lb_total_payment").innerHTML = dojo.number.format(dijit.byId("grand_total").get('value'),{places:2});
			dojo.byId("lb_fine").innerHTML = dojo.number.format(dijit.byId("penalty").get('value'),{places:2});			
			dojo.byId("lb_credit_memo").innerHTML = dojo.number.format(dijit.byId("credit_memo").get('value'),{places:2});
			dojo.byId("lb_paid_amount").innerHTML = dojo.number.format(dijit.byId("paid_amount").get('value'),{places:2});
			dojo.byId("lb_balance_due").innerHTML = dojo.number.format(dijit.byId("balance_due").get('value'),{places:2});

			dojo.byId("lb_paymentmethod").innerHTML = dijit.byId("payment_method").attr('displayedValue');
			dojo.byId("lb_paymentnumber").innerHTML = dijit.byId("number").get('value');
			
			
			var customer_type = dijit.byId("customer_type").get("value");
			var student_type = dijit.byId("student_type").get("value");

			var rowId = $('#identity').val();
			var rowIDArray = rowId.split(',');
			template="";
				 temp='<table class="collape tablesorter"  align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:11px;font-family:Khmer OS Battambang !important; white-space:nowrap; " id="table">'
					  temp+='<tr class="hearder_table" style=" font-size:12px; text-align:center;background:#f2f2f2;font-weight:bold;">';
						  temp+='<td style="border:1px solid #000;">No</td>';
						  temp+='<td style="border:1px solid #000;><strong style="color:#000;">Item Name</strong></td>';
						  temp+='<td style="border:1px solid #000;><strong style="color:#000;">Term</strong></td>';
						  temp+='<td style="border:1px solid #000;><strong style="color:#000;">Qty</strong></td>';
						  temp+='<td style="border:1px solid #000;><strong style="color:#000;">Unit Price</strong></td>';
						  temp+='<td style="border:1px solid #000;><strong style="color:#000;">Deduct/Extra</strong></td>';
						  temp+='<td style="border:1px solid #000;><strong style="color:#000;">Disc Type</strong></td>';
						  temp+='<td style="border:1px solid #000;><strong style="color:#000;">Disc Amt</strong></td>';
						  temp+='<td style="border:1px solid #000;><strong style="color:#000;">Amount</strong></td>';
						  temp+='<td style="border:1px solid #000;><strong style="color:#000;">Period</strong></td>';
						  temp+='<td style="border:1px solid #000;><strong style="color:#000;">Note</strong></td>';
					  temp+='</tr>';
					i=1;  
					for(var n = 0; n < rowIDArray.length; n++) {
					  temp+='<tr style=" font-size:12px;height: 15px;"​ align="center"><td align="center" style="border:1px solid #000;">'+i+'</td>';
					  temp+='<td align="left" style="border:1px solid #000;">&nbsp;'+dojo.byId('item_label_'+rowIDArray[n]).innerHTML+'</td>'; 
					  temp+='<td align="center" style="border:1px solid #000;">'+dijit.byId("term_"+rowIDArray[n]).attr('displayedValue')+'</td>';
					  temp+='<td style="border:1px solid #000;">'+dijit.byId("qty_"+rowIDArray[n]).get('value')+'</td>';
					  temp+='<td align="center" style="border:1px solid #000;">'+dojo.number.format(dijit.byId('price_'+rowIDArray[n]).get('value'),{places:2})+'</td>';
					  temp+='<td align="center" style="border:1px solid #000;">'+dojo.number.format(dijit.byId('extra_fee'+rowIDArray[n]).get('value'),{places:2})+'</td>';
					  temp+='<td style="border:1px solid #000;">'+dijit.byId("discount_type"+rowIDArray[n]).attr('displayedValue')+' </td>';
					  temp+='<td style="border:1px solid #000;">'+dijit.byId("discount_amount"+rowIDArray[n]).get('value')+' </td>';
					  temp+='<td style="border:1px solid #000;">$ '+dojo.number.format(dijit.byId("total_amount"+rowIDArray[n]).get('value'),{places:2})+'</td>';				  				  

					  service_type = dijit.byId("onepayment_"+rowIDArray[n]).get('value');
					  if(service_type==1){//one payment only
						  start_date = '';
						  epx_date='';
					  }else{//period
						  var b = new Date(dijit.byId("date_start_"+rowIDArray[n]).get('value'));
						  mm = b.getMonth()+1;
						  var dd = b.getDate();
						  if(dd<10){
							dd = "0"+dd;
						  }
						  var mon = getMonthByNumber(mm);
						  if(mm<10){
							mm = "0"+mm;
						  }
						  var y = b.getFullYear();
						  var start_date = dd + '/' + mon + '/' + y ;

						  var a = new Date(dijit.byId("validate_"+rowIDArray[n]).get('value'));
						  mm = a.getMonth()+1;
						  var dd = a.getDate();
						  if(dd<10){
							dd = "0"+dd;
						  }
						  var months = getMonthByNumber(mm);
						  if(mm<10){
							mm = "0"+mm;
						  }
						  var y = a.getFullYear();
						  var epx_date = dd + '/' +months+ '/' + y ;
					  }
					  temp+='<td align="center" style="border:1px solid #000;"> ' + start_date + ' - ' + epx_date + ' </td>';
					  temp+='<td style="border:1px solid #000;">'+dijit.byId("remark"+rowIDArray[n]).get('value')+'</td>';
					  i++;
					  temp+='</tr>';
					}
			temp+='</table>';
			dojo.byId('t_amountmoneytype').innerHTML = temp;
			dijit.byId("terms").show();	
			if(submit==1){
				printSubmit();
			}
		}
}	
/////////////// get student test info ////////////////////////////////////////////////////////

var url_creditmemo = "<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-credit-memo')); ?>";
function getCreditMemo(){
	stu_type = dijit.byId('student_type').get('value');
	if(stu_type==3){
		stu_id = dijit.byId('old_stu').get('value');
		if(stu_id != ""){
			dojo.xhrPost({
				url:url_creditmemo,
				content:{
					'stu_id':stu_id,
					},
				handleAs:"json",
				load: function(data){
					if(data){
						dijit.byId("credit_memo").attr("value",data.total_amountafter);
						dijit.byId("credit_memo_id").attr("value",data.id);
					}else{
						dijit.byId("credit_memo").attr("value",0);
						dijit.byId("credit_memo_id").attr("value",'');
					}
				},
				error: function(err) {
					alert(err+"33");
				}
			});	
		} 
	}
}
var url_get_start_date = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-start-date')); ?>';	
function getOldVildateToStartDateRegister(){
	stu_type = dijit.byId('student_type').get('value');
	if(stu_type==3){
		stu_id = dijit.byId('old_stu').get('value');
		if(stu_id==''){
			return 0;
		}
		service_id = 4; // 4 => get validate only student register
		dojo.xhrPost({
			url:url_get_start_date,
			content:{
				'service_id':service_id,
				'stu_id':stu_id
				},
			handleAs:"json",
			load: function(data) {
				if(data){
					dijit.byId('start_date').attr('value',data);
				}else{
					dijit.byId('start_date').attr('value','<?php echo date('Y-m-d');?>');
				}	
			},
			error: function(err) {
				alert(err+"ttt");
			}
		});
	}
}	
var url_get_start_date = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-start-date')); ?>';	
function getOldVildateToStartDateService(index){
		stu_type = dijit.byId('student_type').get('value');
		if(stu_type==3){
			stu_id = dijit.byId('old_stu').get('value');
			if(stu_id==''){
				return 0;
			}
			service_id = dijit.byId('item_id'+index).get('value');
			if(service_id != ''){
				dojo.xhrPost({
					url:url_get_start_date,
					content:{
						'service_id':service_id,
						'stu_id':stu_id
						},
					handleAs:"json",
					load: function(data) {
						if(data){
							dijit.byId('date_start_'+index).attr('value',data);
						}else{
						}	
					},
					error: function(err) {
						//alert(err);
					}
				});
			}
		}
	}

/*var url_set_date = '<?php //echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-start-date-end-date')); ?>';	
function setStartAndEndDate(){
	dijit.byId('term_lable').attr('value','');
	id = dijit.byId('start_end').get('value');
	dojo.xhrPost({
		url:url_set_date,
		content:{
			'id':id
			},
		handleAs:"json",
		load: function(data) {
			if(data){
				dijit.byId('term_lable').attr('value',data.note);
				dijit.byId('start_date').attr('value',data.start_date);
				dijit.byId('end_date').attr('value',data.end_date);
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}*/
var url_student_balance = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-studentbalance')); ?>';	
function getStudentBalance(){
	stu_id = dijit.byId('old_stu').get('value');
	if(stu_id>0){
		dojo.xhrPost({
			url:url_student_balance,
			content:{
				'stu_id':stu_id
				},
			handleAs:"json",
			load: function(data) {
				if(data){
					alert("This student have balance !!! You have to clear balance first !!!");
					url='<?php echo $this->baseUrl()."/registrar/register/clearbalance/id/";?>';
					window.open(url+data,"_self");
				}
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
</script>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>