<?php 
    $request=Zend_Controller_Front::getInstance()->getRequest();
    $tr = Application_Form_FrmLanguages::getCurrentlanguage();
    $frm =  $this->form_search;
?>
<title><?php echo $tr->translate("REGISTER")?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
            <div class="col-sm-12 border-botom" style="padding-bottom:5px;" >
		    	<div class="d-flex"> 
					<div class="settings-main-icon ">
						<i class="material-icons-outlined">
						paid
						</i>
					</div> 
					<div class="col-md-10 col-sm-10 col-xs-12"> 
						<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('PAYMENT_LIST');?></p>
					</div> 
				</div>
	    	</div>
	    </div>
		<div class="card-box">
			<form  action="<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			   <div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                    	<input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->adv_search['adv_search']?>" placeholder="<?php echo $tr->translate("SEARCH");?>" type="text" >
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input id="study_year" />
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("degree");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input id="grade_all" />
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("session");?>
                   </div>
               </div>
               <div class="form-group">
               		<div class="col-md-2 col-sm-2 col-xs-12">
               			<Input id="userId" />
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<button class="button-class button-primary" iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
               </div>
			 </form>
		</div>
		<div class="card-box">
			<?php //echo $this->list; ?>
		</div>
		<div class="card-box">
			<div class="dataTables_scrollBody" style="position: relative;  width: 100%; background:#fff;   ">
    			<table border="1" id="datatable-responsive" style="  border-collapse: collapse;   border-color: #ddd;"  class="display nowrap dataTable dtr-inline collapsed" cellspacing="0" width="100%" >
    				<thead>
    					<tr>
    						<th class="tdheader text-center"><?php echo $tr->translate("NUM");?></th>
    						<th class="tdheader text-center"><?php echo $tr->translate("BRANCH");?></th>
    						<th class="tdheader text-center"><?php echo $tr->translate("RECEIPT_NO");?></th>
    						<th class="tdheader text-center"><?php echo $tr->translate("STUDENT_ID");?></th>
    						<th class="tdheader text-center"><?php echo $tr->translate("STUDENT_NAME");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("SEX");?></th>
    						<th class="tdheader text-center"><?php echo $tr->translate("ACADEMIC_YEAR");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("FINE");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("TOTAL_PAYMENT");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("CREDIT_MEMO");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("PAID");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("BALANCE");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("PAYMENT_METHOD");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("CHEQUE_NO");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("DATE_PAY");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("USER");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("STATUS");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("VOID_BY");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("VOID");?></th>
    					</tr>
    				</thead>
    				<tbody>
    					<?php $r=0; if (!empty($this->row)) foreach ($this->row as $rs){ 
    						if($r%2==0)$attb='normal';
    						else $attb='alternate';
    						$r++?>
    					<tr class="context-menu-one"  oncontextmenu="setrowdata('<?php echo $rs['id']; ?>');return false;">
    						<td style="text-align:center;" ><?php echo $r;?></td>
							<td class="itesms text-center" id="branchValue"><?php echo $rs['branch_name']?></td>
    						<td class="itesms text-center" id="receiptValue"><?php echo $rs['receipt_number']?></td>
							<td class="itesms text-center" id="stuCodeValue"><?php echo $rs['stu_code']?></td>
							<td class="itesms text-center" id="stuNameValue"><?php echo $rs['stu_khname']?></td>
							<td class="itesms text-center" ><?php echo $rs['sex']?></td>
							<td class="itesms text-center" ><?php echo $rs['YEAR']?></td>
							<td class="itesms text-center" ><?php echo $rs['penalty']?></td>
							<td class="itesms text-center" ><?php echo $rs['grand_total']?></td>
							<td class="itesms text-center" ><?php echo $rs['credit_memo']?></td>
							<td class="itesms text-center" ><?php echo $rs['paid_amount']?></td>
							<td class="itesms text-center" ><?php echo $rs['balance_due']?></td>
							<td class="itesms text-center" ><?php echo $rs['payment_method']?></td>
							<td class="itesms text-center" ><?php echo $rs['number']?></td>
							<td class="itesms text-center" id="dateValue" ><?php echo $rs['create_date']?></td>
							<td class="itesms text-center" ><?php echo $rs['user']?></td>
							<td class="itesms text-center" ><?php echo $rs['void']?></td>
							<td class="itesms text-center" ><?php echo $rs['void_by']?></td>
							<td class="itesms" >
								<?php if($rs['is_void']==0){ ?>
									<a href="#" onclick="VoidForm('<?php echo $rs['id']; ?>');" class="btn btn-primary btn-xs"><i class="fa fa-times"></i> <?php echo $tr->translate("VOID_NOW")?> </a>
								<?php }else{ ?>
									<span class="text-danger"><i class="fa fa-times"></i></span>
								<?php } ?>
								
							</td>
    					</tr>
    					<?php }?>
    				</tbody>
    			</table>
    		</div>		
		</div>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate('VOID_RECORD_TITLE');?>'"  id="updateForm" style="width:350px;" >
		<div class="card pb-10 pt-10 pl-10 pr-10">
			<form id="voidFormInfo"  name="data" action="" dojoType="dijit.form.Form" method="post">
				<div class="card-box">
					<div class="form-group">
						<div class="col-md-12 col-sm-12 col-xs-12" id="contentInfoPop">
						</div>
					</div>
					<div class="form-group border-top mt-20 ptb-10 ">
					   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate('REASON');?> :
					   </label>
					   <div class="col-md-7 col-sm-7 col-xs-12">
							<input style="min-height:70px;" class="fullside" type="text" dojoType="dijit.form.Textarea" name="reason" id="reason" placeholder="<?php echo $tr->translate("REASON");?>" />
							<input type="hidden" dojoType="dijit.form.TextBox" name="id" id="id"  />
					   </div>
					</div>
					<div class="form-group">
						<div class="col-sm-12 text-center">
							<input onclick="voidReceipt();" type="button" value="1" label="<?php echo $tr->translate('VOID_NOW');?>" id="busyButton" dojoType="dijit.form.Button" 
								class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" /> 
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dijit.form.Textarea");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	
	dojo.ready(function(){
		var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		new dijit.form.FilteringSelect({
			store: academic_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "study_year",
			name: "study_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				academic_year = dijit.byId('study_year').get('value');
			}
		}, "study_year");

		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade_all",
			name: "grade_all",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
			}
		}, "grade_all");

		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "userId",
			name: "userId",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_USER");?>",          
			onChange: function() {  
			}
		}, "userId");
		
		var branch_id = dijit.byId('branch_id');
		branch_id.on('change', function(evt) {
			getAllAcademicByBranch();
			getAllUser();
		});
		getAllAcademicByBranch();
		getallGrade();
		getAllUser();
	});
	url_getacademic= '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'getfeeid'));?>';
	var oldBranch = "<?php echo $this->adv_search['branch_id']?>";
	function getAllAcademicByBranch(){
		dijit.byId('study_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('study_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getacademic,
			content:{
				'branch_id':branch_id,
				'selectOption':1
				},
			handleAs:"json",
			load: function(data) {
				academic_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('study_year').set('store',academic_store);  
			    if(oldBranch==branch_id){
			    	dijit.byId('study_year').set('value','<?php echo $this->adv_search['study_year']?>');  
			    }
			},
			error: function(err) {
			}
		});
	}
	function getallGrade(){
		let url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade_all').set('store',grade_store);   
				dijit.byId('grade_all').attr('value','<?php echo $this->adv_search['grade_all']?>');  
			},
			error: function(err) {
			}
		});
	}
	function getAllUser(){
		
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			dijit.byId('branch_id').focus();
			return false;
		}
		let url_user = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'get-user')); ?>';
		contentData = {
				'branchId':branch_id
			}
			selectedId = '';
			if('<?php echo $this->adv_search['branch_id']?>'==branch_id){
				selectedId = '<?php echo $this->adv_search['userId']?>';
			}
			
			getAllUserByBranch(url_user,contentData,selectedId);
	}
	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 if(id!=''){
			window.location.href = url+'/id/'+id;
		 }else{
			alert('Please select record you want to copy');
			return false;
		 }
	}
	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}
	var row=0;
	var url="";
	var currentArr=[];
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="issue"){
					url='<?php echo $this->baseUrl()."/allreport/accounting/rptreceiptdetail/id/";?>';
					addTab("<?php echo $tr->translate("RECEIPT");?>",url+row+'?inFrame=true');
				}else if(key=="void"){
					dijit.byId('id').set('value',row);
					dijit.byId('updateForm').show();
				}
			},
			items: {
				"issue": {name: "<?php echo $tr->translate("RECEIPT");?>", icon: "fa-print", accesskey: "e"},
				<?php 
						$dbacc = new Application_Model_DbTable_DbUsers();
				 		$rs = $dbacc->getAccessUrl('registrar','register','edit');
		 		if(!empty($rs)){
				?>
					"void": {name: "<?php echo $tr->translate("VOID");?>", icon: "fa-file-text"},
			<?php }?>
			}
		});
	});
	function setrowdata(index){
		row = index;
		var strinfo="";
		
		strinfo+='<small >'+$("#branchValue").text()+'</small>';
		strinfo+='<h3 class="text-danger red"><small class="text-primary " ><?php echo $tr->translate("RECEIPT_NO");?>:</small > '+$("#receiptValue").text()+'</h3>';
		strinfo+='<p><?php echo $tr->translate("STUDENT_NAME");?>: <strong class="text-primary ">'+$("#stuCodeValue").text()+' '+$("#stuNameValue").text()+' </strong> </p>';
		strinfo+='<p><?php echo $tr->translate("DATE_PAY");?>: <strong class="text-primary ">'+$("#dateValue").text()+'</strong></p>';
		
		$( "#contentInfoPop" ).html( strinfo );
	}
	var recordid ='';
	function gotoAction(){
		 window.open(url+row, '_self');
	}
	var voidReciept = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'edit')); ?>';
	function voidReceipt(){
		if(dijit.byId('voidFormInfo').validate()){
			if(confirm("<?php echo $tr->translate("Do you want to void this reciept");?>")){
		}else{
			dijit.byId('voidFormInfo').reset();
			dijit.byId('updateForm').hide();
			return false;
		}
			loadingBlock();
			dojo.xhrPost({
				url: voidReciept,
				form: dojo.byId("voidFormInfo"),
				handleAs:"json",
				load: function(data){
					dijit.byId('voidFormInfo').reset();
					dijit.byId('updateForm').hide();
					if(data==1){
						alert("<?php echo $tr->translate("VOID_SUCCESS");?>");
					}else if(data==2){//not permission
						alert("<?php echo $tr->translate("RECORD_NOTFUND");?>");
					}else if(data==3){
						alert("<?php echo $tr->translate("READY_VOID");?>");
					}else{
						alert("<?php echo $tr->translate("VOID_FAIL");?>");
					}
					dijit.byId('reason').set('value','');
					location.reload();
					HideloadingBlock();
				},
				error: function(err){
					dijit.byId('voidFormInfo').reset();
					dijit.byId('updateForm').hide();
					HideloadingBlock();
				}
			});
		}
	}
	function VoidForm(index){
		dijit.byId('id').set('value',index);
		dijit.byId('updateForm').show();
	}
</script>