<title>Register</title>
<?php 
    $request=Zend_Controller_Front::getInstance()->getRequest();
    $tr = Application_Form_FrmLanguages::getCurrentlanguage();
    $frm =  $this->form_search;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form  action="<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			   <div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                    	<input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->adv_search['adv_search']?>" placeholder="<?php echo $tr->translate("SEARCH");?>" type="text" >
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("study_year");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("degree");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("grade_all");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("session");?>
                   </div>
               </div>
               <div class="form-group">
               		<div class="col-md-2 col-sm-2 col-xs-12">
               			<?php echo $frm->getElement("user");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
               </div>
			 </form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>

<?php if(!empty($this->customer_payment)){?>
<table width="100%"  border="1" style="border: 1px solid #CCCCCC;border-collapse: collapse;margin-top: 50px;">
	
	<style>
		tr.tdheader {
		    background: url(../images/tbheader-bg1.jpg) repeat-x scroll center top #F1F1F1;
		    border: 1px solid #CCCCCC;
		    color: #333333;
		    font-family: 'Kh Battambang','Khmer Battambang',Times New Roman;
		    font-size: 12px;
		    font-weight: bold;
		    line-height: 30px;
		    padding: 2px 2px 2px 2px;
		    text-align: center;
		    cursor: pointer;
		}
		.hover:hover{background: red;}
 	</style>

	<tr class="tdheader" align="center">
		<td><?php echo $tr->translate("N_O");?></td>
		<td><?php echo $tr->translate("RECEIPT");?></td>
		<td><?php echo $tr->translate("NAME_KH");?></td>
		<td><?php echo $tr->translate("NAME_EN");?></td>
		<td><?php echo $tr->translate("SEX");?></td>
		<td><?php echo $tr->translate("DOB");?></td>
		<td><?php echo $tr->translate("PHONE");?></td>
		<td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
		<td><?php echo $tr->translate("FINE");?></td>
		<td><?php echo $tr->translate("DEDUCT");?></td>
		<td><?php echo $tr->translate("NET_AMOUNT");?></td>
		<td><?php echo $tr->translate("CREATE_DATE");?></td>
		<td><?php echo $tr->translate("USER");?></td>
		<td><?php echo $tr->translate("STATUS");?></td>
	</tr>
	
	<?php $i=0;foreach ($this->customer_payment as $rs){$i++;?>
		<tr class="hover" align="center" style="background: none repeat scroll 0 0 #FFFFFF;line-height: 25px;">
			<td><?php echo $i;?></td>
			<td><?php echo $rs['receipt_no'];?></td>
			<td><a href="<?php echo $this->baseUrl()."/registrar/register/editcustomerpayment/id/".$rs['id']?>" target="_blank" ><?php echo $rs['name_kh'];?></a></td>
			<td><a href="<?php echo $this->baseUrl()."/registrar/register/editcustomerpayment/id/".$rs['id']?>" target="_blank" ><?php echo $rs['name_en'];?></a></td>
			<td><?php echo $rs['sex'];?></td>
			<td><?php echo date("d-M-Y",strtotime($rs['dob']));?></td>
			<td><?php echo $rs['phone'];?></td>
			<td><?php echo $rs['grand_total'];?></td>
			<td><?php echo $rs['fine'];?></td>
			<td><?php echo $rs['deduct'];?></td>
			<td><?php echo $rs['net_amount'];?></td>
			<td><?php echo date("d-M-Y",strtotime($rs['create_date']));?></td>
			<td><?php echo $rs['user'];?></td>
			<td><?php echo $rs['status'];?></td>
		</tr>
	<?php }?>
</table>

<?php }?>





