<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_STUDENT_SERVICE_PAYMENT')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	
dojo.ready(function(){
    	 dijit.byId('study_year').attr('value','<?php echo $this->row['year']?>');
    	 dijitValue();
    	 getStudentInfo();
    	 initailize();
});

function dijitValue(){
	 dijit.byId('reciept_no').attr('value','<?php echo $this->row['receipt_number']?>');
	 dijit.byId('not').attr('value','<?php echo $this->row['note']?>');
	 dijit.byId('grand_total').attr('value','<?php echo $this->row['total_payment']?>');
}
</script>

<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;
//print_r($register);
?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    return true;
   }else {
    return false;
   }
</script>
<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong style="font-size: 18px;"><?php echo $tr->translate("EDIT_STUDENT_SERVICE_PAYMENT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" >
						<tr>
							<td style="width: 12%"><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
							<td style="width: 37%"><?php echo $register->getElement('study_year');?></td>
							<td align="right" style="width: 12%"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td style="width: 37%"><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td>
								<select type="text" class="fullside" dojoType="dijit.form.FilteringSelect" name="studentid" id="studentid" onChange="getStudentInfo();setID(1);" >
									<option value="-1">Select Student ID</option>
									<?php if(!empty($this->rs)){foreach ($this->rs as $rs){?>
									<option value="<?php echo $rs['id']?>" <?php if($rs['id']==$this->row['student_id']) echo 'selected="selected"' ?>><?php echo $rs['code']?></option>
									<?php }}?>
								</select>
							</td>
							<td align="right"><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td align="center">
								<select type="text" style="" class="fullside" dojoType="dijit.form.FilteringSelect" name="stu_name" id="stu_name" onChange="setID(2);" >
									<option value="-1">Select Student Name</option>
									<?php if(!empty($this->row_name)){foreach ($this->row_name as $row){?>
									<option value="<?php echo $row['id']?>" <?php if($row['id']==$this->row['student_id']) echo 'selected="selected"' ?> ><?php echo $row['name']?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
							<td align="right"><?php echo $tr->translate("NAME_EN");?></td>
							<td ><?php echo $register->getElement('en_name');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?></td>
						    <td align="right"><?php echo $tr->translate("NOT");?></td>
							<td title='Ex: 20 or 10%' ><?php echo $register->getElement('not');?></td>	
						</tr>
						<tr>
							<td colspan="4" align="left">
								<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
							 		iconClass="dijitIconEditProperty" onclick="addRow();" />
							</td>
						</tr>
						<tr>
							<td colspan="4">
								<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="2"><input type="hidden" id="identity" name="identity" /></td>
							<td colspan="2" align="right">
								<table style="width:400px;border-collapse: collapse;" cellpadding="10" cellspacing="10" >
									<tr>
										<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
										<td align="right"><input class="fullside" type="text"  value="<?php //echo $this->row['total_payment'];?>" readonly="readonly" name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
								<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'registrar','controller'=>"uniformandbook",'action'=>'index'),null,true); ?>';" />
								<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="<?php echo $tr->translate('GO_EDIT');?>"  dojoType="dijit.form.Button" 
								 	iconClass="dijitEditorIcon dijitEditorIconSave" />
								<input type="button" value="រក្សាទុក & បោះពុម្ព" label="<?php echo $tr->translate('PRINT');?>" id="busyButton" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
							</td>
						</tr>
					</table>
				<style>
					.h{ margin-top: -8px;/*margin-left:4px;*/}
				</style>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
function printSave(){		
		if(dijit.byId('office_receipt').validate()) {
	
	dojo.byId("lbl_khname").innerHTML = dijit.byId("kh_name").get('value');
	dojo.byId("lbl_enname").innerHTML = dijit.byId("en_name").get('value');
	dojo.byId("lbl_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
	dojo.byId("lbl_stuid").innerHTML = dijit.byId("studentid").attr('displayedValue');
	dojo.byId("lbl_recieptno").innerHTML = dijit.byId("reciept_no").get('value');
	var total = dijit.byId("grand_total").get('value');
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	template="";
		 temp='<table class="collape tablesorter" border="1" align="center" style=" width: 100%; padding: 0px; margin: 0px; border-collapse: collapse; white-space:nowrap; border: 1px solid #000; font-size:12px;  " id="table">'
			  temp+='<tr style="background:#ccc;"><th><strong style="font-family: Khmer OS Battambang;color:#000; ">លេខ<div class="h">No.</div></strong></th>';
	    	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;">ពណ៍នា<div class="h">Description</div></strong></th>';
	    	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000; ">ចំនួន<div class="h">Amount</div></strong></th>';
	     	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000; ">តំលៃ<div class="h">Price</div></strong></th>';
	       	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000; ">បញ្ចុះតំលៃ<div class="h">Discount</div></strong></th>';
	     	  temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000; ">តំលៃសរុប<div class="h">Sub Total</div></strong></th>';
		     //temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000; ">ផ្សេងៗ<div class="h">Others</div></strong></th></tr>';
			    i=1;  for(var n = 0; n < rowIDArray.length; n++) {
			    	var discount = dijit.byId("discount_"+rowIDArray[n]).get('value');
			    	discount = isNaN(discount)?0:discount;
					if(discount==0 || discount==null){
						discount = '';
					}else{
						discount = discount+" %";
					} 
		      temp+='<tr style=" font-size:12px;height: 23px;"​ align="center"><td align="center" style="border:1px solid #000;">'+i+'</td>';
		      temp+='<td align="left" style="border:1px solid #000;">&nbsp;&nbsp;'+dijit.byId("service_"+rowIDArray[n]).attr('displayedValue')+' - '+dijit.byId("remark"+rowIDArray[n]).get('value')+'</td>'; 
		      temp+='<td style="border:1px solid #000;">'+dijit.byId("qty_"+rowIDArray[n]).get('value')+'</td>';	
			  temp+='<td style="border:1px solid #000;">$ '+dijit.byId("price_"+rowIDArray[n]).get('value')+'</td>';
		      temp+='<td style="border:1px solid #000;"> '+discount+'</td>';
		      temp+='<td style="border:1px solid #000;">$ '+dijit.byId("subtotal_"+rowIDArray[n]).get('value')+'</td>';
		      //temp+='<td style="border:1px solid #000;"> '+dijit.byId("remark"+rowIDArray[n]).get('value')+'</td>';
		      i++;
		      temp+='</tr>';
		     }
			  temp+='<tr style="height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="4"></td><td align="center" style="border:1px solid #000; padding-left: 10px;"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">សរុប / Total </strong></td><td align="center" style="border:1px solid #000; padding-left: 10px;">$ '+total+'</td></tr>';
		    temp+='</table>';
		    dojo.byId('t_amountmoneytype').innerHTML = temp;

		dijit.byId("popup_invoice").show();	
	}
}
</script>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" id="popup_invoice" >
		<div id="divPrint" style=" width: 22cm; height: 12cm ; padding: 0px; margin: 0px;">
			<table style=" background:#fff; margin: 0 auto; width: 21cm; height: 12cm; padding: 1cm; ">
							<tr>
								<td width="25%" align="left">
								</td>
								<td align="center">
									<strong style=" font: bold 15px 'Khmer MEF2',Arial Black; color:#000;"><u>បង្កាន់ដៃបង់ប្រាក់របស់សិស្ស</u></strong><br >
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 15px;padding-right: 10px;">OFFICAIL RECEIPT</strong><br >
								</td>
								<td align="right" width="20%">
								</td>
							</tr>
							<tr>
								<td width="35%" style="line-height: 32px;">
									<table style="white-space: nowrap;" >
										<tr>
											<td style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">អត្តលេខសិស្ស  </strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">Student ID &nbsp;&nbsp;&nbsp;</strong>
											</td>
											<td >
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"> : &nbsp;<label id="lbl_stuid"></label></strong>
											</td>
										</tr>
										<tr>
											<td style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">ឈ្មោះសិស្ស </strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">Student Name </strong>
											</td>
											<td >
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"> : &nbsp;<label id="lbl_khname"></label></strong> - <label id="lbl_enname"></label>
											</td>
										</tr>
										
									</table>
								</td>
								<td width="30%">
									&nbsp;
								</td>
								<td width="35%" style="line-height: 32px;">
									<table style="white-space: nowrap;">
										<tr>
											<td width="20%" style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">វិក័យប័ត្រលេខ</strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">Reciept No. </strong>
											</td>
											
											<td width="20%" >
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"> : &nbsp;</strong><b><label id="lbl_recieptno"></label></b>
											</td>
										</tr>
										<tr valign="top" style="line-height: 13px;">
											<td><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">ភេទ / Sex</strong></td>
											<td>
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"> : &nbsp;<label id="lbl_sex"></label></strong>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="3">
                                    	 <label id="t_amountmoneytype"></label>
								</td>
							</tr>
							<tr>
								<td align="left">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';padding-left: 50px;"></strong><br />
								</td>
								<td>&nbsp;</td>
								<td align="right">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';padding-right: 0px;">បេឡា / Cashier : <?php $session_user=new Zend_Session_Namespace('auth'); $last = $session_user->last_name;$first=$session_user->first_name;echo $last.' '.$first; ?></strong><br /><span style="font-size: 13px;"><?php echo Zend_Date::now();?></span>
								</td>
							</tr>
						</table>
	</div>
	<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="printSubmit();doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
</div>
</div>
<script>
//save daata when sub button print 
function printSubmit(){
	$('#office_receipt').submit();
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}
</script>
<script type="text/javascript">
function hideDialog() {		
	dijit.byId("popup_invoice").hide();
}
var template = '';
var metion = '<?php echo $this->all_metion; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';
var service = '<?php echo $this->all_service; ?>';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DISCOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBTOTAL");?></th>';
			
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="50px" align="center"><img onclick="deleteRecord('+col+');calculateDiscount('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="50px" align="center">'+no+'</td>';
			template+='<td width="300px"><select class="fullside" onchange="getprice('+col+');"  dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			
			template+='<td width="600px"> <input type="text" class="fullside" name="remark'+col+'" value="" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"  /><label id="subsub"></label></td>';
			column = 0;
			template+='<td width="250px"> <input class="fullside" type="text" onkeyup="calculateDiscount('+col+');getValidate('+col+');" name="qty_'+col+'" value="1" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';
			template+='<td width="250px"> <input class="fullside" type="text" required="true" onkeyup="calculateDiscount('+col+');" name="price_'+col+'" value="" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td width="250px"> <input class="fullside" type="text"  onkeyup="calculateDiscount('+col+');" value="<?php echo 0;?>"  name="discount_'+col+'" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td width="250px"> <input class="fullside" type="text" readonly="readonly" name="subtotal_'+col+'" value="" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';
			
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
function calculateDiscount(index){
		price = dijit.byId('price_'+index).get('value');
		qty = dijit.byId('qty_'+index).get('value');
		qty=isNaN(qty)?1:qty;
		if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
		total = price*qty;
		
		discount = dijit.byId('discount_'+index).get('value');
		discount=isNaN(discount)?0:discount;
		dijit.byId('subtotal_'+index).attr('value',total-(total*discount/100));
		//dijit.byId('paidamount_'+index).attr('value',total-(total*discount/100));
		netTotal();
}
function netTotal(index) {
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
	}
	dijit.byId('grand_total').attr('value',netTotal);
}

var url_price = "<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'get-price'));?>";
function getprice(index){
	service_price = dijit.byId('service_'+index).get('value');
	//alert(service_price);
	dojo.xhrPost({
		url:url_price,
		content:{
			'service_price':service_price,
			},
		handleAs:"json",
		load: function(data) {
			//alert(data);
			dijit.byId("price_"+index).attr("value",data);
			calculateDiscount(index);
		},
		error: function(err) {
			alert(err);
		}
	});
}

var url_student_info = "<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'get-student')); ?>";
function getStudentInfo(){
			studentid = dijit.byId('studentid').get('value');
			dojo.xhrPost({
				url:url_student_info,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//alert(data.sex);
					dijit.byId("kh_name").attr("value",data.stu_khname);
					dijit.byId("en_name").attr("value",data.stu_enname);
					dijit.byId("sex").attr("value",data.sex);
					//alert(data);
					//dijit.byId("price_"+key).attr("value",data.price_fee);
				},
				error: function(err) {
					alert(err);
				}
			});
}
function setID(type){
	if(type==1){
		dijit.byId('stu_name').attr('value',dijit.byId('studentid').get('value')); 
	}else{
		dijit.byId('studentid').attr('value',dijit.byId('stu_name').get('value')); 
	}
}
function initailize(){
	<?php if(!empty($this->rows)){
		foreach($this->rows as $row){
	?>
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
		temp+='<th><?php echo $tr->translate("REMARK");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMOUNT");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DISCOUNT");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBTOTAL");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="50px" align="center"><img onclick="deleteRecord('+col+');calculateDiscount('+col+');calculatePaidAmount('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="50px" align="center">'+no+'</td>';
		template+='<td width="300px"><select onchange="setValue('+col+');" class="fullside" dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';	
		template+='<td width="600px"> <input type="text" class="fullside" name="remark'+col+'" value="" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';		
		column = 0;
		template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside" onkeyup="calculateDiscount('+col+',1);getValidate('+col+');" name="qty_'+col+'" value="" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';
		template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside" required="true" onkeyup="calculateDiscount('+col+',1);" name="price_'+col+'" value="" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
		template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside" onkeyup="calculateDiscount('+col+',1);" value=""  name="discount_'+col+'" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
		template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside" readonly="readonly" name="subtotal_'+col+'" value="" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);
	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	
	dijit.byId('service_'+col).attr('value','<?php echo $row['service_id']?>');
	dijit.byId('price_'+col).attr('value','<?php echo $row['fee']?>');
	dijit.byId('qty_'+col).attr('value','<?php echo $row['qty']?>');
	dijit.byId('discount_'+col).attr('value','<?php echo $row['discount_percent']?>');
	dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
	dijit.byId('subtotal_'+col).attr('value','<?php echo $row['subtotal']?>');
	<?php } }?>
}

function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>
	
	