<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_ADD_ROOM')); 
?>	
<?php  $classname= $this->frm_classname;?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="glyphicon glyphicon-blackboard" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_CLASSNAME_NAME');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form  id='add_room' action="<?php echo $this->url(array('module'=>'global','controller'=>'room','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id=dijit.byId("branch_id").get('value');
				if(branch_id=='' || branch_id==null){
					dijit.byId("branch_id").focus();
					return false;
				}
				loadingBlock();	
                dijit.byId("save_close").attr("disabled",true);
				dijit.byId("save_new").attr("disabled",true);
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">			 
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-blackboard"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("ROOM");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH");?> <span class="required">*</span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $classname->getElement('branch_id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ROOM_NAME");?> <span class="required">*</span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $classname->getElement('classname');?>
									   </div>
									</div>	
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FLOOR");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $classname->getElement('floor');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("MAX_STUDENT");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $classname->getElement('max_student');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="clearfix"></div>
				 <div class="card-box mt-20">
					<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
						<input type="button" class="button-class button-danger"  iconClass="glyphicon glyphicon-repeat" onClick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button"  />
						<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" />
					</div>
				 </div>
           </div>
         </div>
		</form>
	</div>
</div>

<script>
function submitDataClose(){
	if(dijit.byId('add_room').validate()) {
		brnach=dijit.byId('branch_id').get('value');
		if(brnach==''){
			alert('Please Select Branch !');
			return false;
		}
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'global','controller'=>'room','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("add_room"),		    
			load: function(data){
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/global/room";
			},			
			error: function(e) {
			}
		});
	}
}
</script>