<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
	$formList = new Application_Form_Frmtable();
	echo $this->headTitle($tr->translate("REQUEST_FOR"));
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-exchange " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REQUEST_FOR');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
		        	<div class="col-md-2 col-sm-2 col-xs-12">
		        		<input name="title" id="title" class="fullside" value="<?php echo $this->search['title']?>" dojoType="dijit.form.TextBox" />
		        	</div>
		        	<div class="col-md-2 col-sm-2 col-xs-12">
		        		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
		        	</div>
		        	<div class="col-md-2 col-sm-2 col-xs-12">
		        	</div>
		        </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list; ?>
		</div>
	</div>
</div>

