<?php 
		$tr = Application_Form_FrmLanguages::getCurrentlanguage();
		$image = $this->baseUrl().'/images/no-profile.png';
if(!empty($this->rs['photo'])){
	if (file_exists(PUBLIC_PATH."/images/photo/".$this->rs['photo'])){
		$image = $this->baseUrl().'/images/photo/'.$this->rs['photo'];
	}
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" type="text/css" href="style.css">
	<link href="https://fonts.googleapis.com/css?family=Moul|Roboto|Sumana|Leckerli One" rel="stylesheet">
    <meta charset="utf-8">
     <title>STUDENT RECOMMENDATION</title>
</head>
<body>
	<div class="wrapper" style="background: #fff;width:26cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
		<div id="divPrint">
			 <style>
		    	.wrapper{
		    		width: 100%;
		    		margin: 0px;
		    		padding: 0px;
		    	}
		    	.contain{
		    		width: 1024px;
		    		margin: 0 auto;
		    	}
				table {
		    		border-collapse: collapse;
		    		width: 100%;
				}
				th, td {
		    		padding: 4px;
				}
				.image-box {
				    text-align: center;
				}
				.image-box img {
				    width: 120px;
				    height: 130px;
				border:solid 1px #ddd;
				}
				.account-image {
				    width: 120px;
				    margin: 0 auto;
				}
				.center-no-next{text-align: center;}
				.back-color,.back-footer{background-color: #eee;}
				.back-color td{padding: 20px;}
				.text-left td{text-align: right;}
				.img-size img{height: 15px;}
				tr.line td{ border-bottom: 2px solid #000; }
		    </style>
			<table cellpadding="0" cellspacing="0" width="100%">
				<tr class="no-boder">
					<td>
						<table width="100%" >
							<tr>
								<td width="20%" align="center">
									<?php $logo = $this->baseUrl().'/images/logo.png';
									if (!empty($this->rs['branch_logo'])){
										$logo = $this->baseUrl().'/images/'.$this->rs['branch_logo'];
									}
									?>
									<img style="max-height:100px;" src="<?php echo $logo;?>"><br>
								</td>
								<td width="80%" valign="top">
									<div class="schoo-headkh" style="text-align: center;">
										<h2 style="padding: 0;margin: 0; font-family: Times New Roman , Khmer OS Muol;font-size:24px;background: #2e3192;color: #fff;padding: 8px 0px;"><?php echo $this->rs['school_namekh'];?></h2>
									</div>
									<table width="100%" >
										<tr>
											<td width="60%" align="center" valign="top">
												<h2 style="white-space:nowrap; font-weight:bold; font-size:16px; padding: 0;margin: 0; font-family: Times New Roman , Khmer OS Muol; color: #000;"><?php echo $this->rs['school_nameen'];?></h2>
											</td>
											<td width="40%" align="left" valign="top" style="white-space:nowrap;font-size: 12px;line-height: 14px;">
												Contacts: <?php echo $this->rs['branch_tel'];?><br />
												<span style="visibility: hidden;">Contacts: </span><?php echo $this->rs['branch_tel'];?>
											</td>
										</tr>
									</table>
									<div class="schoo-add" style="text-align: center; font-size: 13px;">
										<?php echo $this->rs['br_address'];?>, E-mail: <?php echo $this->rs['email'];?>, Website: <?php echo $this->rs['website'];?>
									</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr class="line"><td></td></tr>
			  	<tr>
			  		<td>
			  			<table style="font-family: Khmer OS Battambang, Times New Roman;">
			  				<tr>
			  					<td>&nbsp;</td>
			  				</tr>
			  				<tr>
			  					<td><div style="margin-left: 25px;">N<sup>o</sup> <span style="display:inline-block;min-width: 100px;border-bottom: dotted 1px #000;line-height: 11px;">&nbsp;</span>ELT</div></td>
			  				</tr>
			  				<tr>
			  					<td valign="top">
			  						<table width="100%" style="line-height: 15px;white-space: nowrap;">
			  							<tr class="account-image">
			  								<td width="20%" >&nbsp;</td>
											<td width="60%" valign="top" align="center" style="font-family: Times New Roman , Khmer OS Muol;font-size:18px;font-weight: bold; padding-rgiht: 34px; line-height: 24px; text-align: center;">
												STUDENT RECOMMENDATION
											</td>
											<td valign="top" width="20%" align="left" class="image-box" style="padding-left: 0px;">
												<!-- <img style="margin-top: -30px;" id="profile_wiew" src="<?php //echo $image;?>" alt=""  /> -->
											</td>
										</tr>
										<tr class="account-image">
			  								<td colspan="2" valign="bottom">
											</td>
											<td valign="top" width="20%" align="left" class="image-box" style="padding-left: 0px;">
												<img style="margin-top: -75px" id="profile_wiew" src="<?php echo $image;?>" alt=""  />
											</td>
										</tr>
			  						</table>
			  					</td>
			  				</tr>
			  			</table>
			  			<div style="text-align: center; font-family: 'Times New Roman', Khmer OS Muol Light; font-size:16px; ">
			  			This is to certify that
			  			<br />
			  			<span style=" font-size:18px;  font-weight: bold; text-transform: uppercase;"><?php echo $this->rs['name_englsih'];?></span>
			  			</div>
			  		</td>
			  	</tr>
			  	<tr>
			  		<td>
			  			<table border="0" style="margin:0 auto;line-height: 20px;font-family:  Times New Roman , Khmer OS Battambang;width: 70%;">
  							<tr>
  								<td >
  									&nbsp;
  								</td>
  							</tr>
  							<tr>
  								<td valign="top">
  									<strong>Date Of Brith</strong> 
								</td>
								<td valign="top">:&nbsp;<?php echo date("d",strtotime($this->rs['dob']))." ".date("F",strtotime($this->rs['dob']))." ".date("Y",strtotime($this->rs['dob']));?></td>
  							</tr>
  							<tr>
  								<td valign="top" >
  									<strong>Gender</strong> 
  								</td>
  								<td valign="top">:&nbsp;<?php echo $this->rs['sex'];?></td>
  							</tr>
  							<tr>
  								<td valign="top">
  									<strong>Place Of Brith</strong>
  								</td>
  								<td valign="top">:&nbsp;<?php echo $this->rs['pob'];?></td>
  							</tr>
  							<tr>
								<td valign="top">
									<strong>Father Name:</strong> 
								</td>
								<td valign="top">:&nbsp;<?php echo $this->rs['father_enname'];?></td>
							</tr>
							<tr>
								<td valign="top">
									<strong>Mother Name</strong> 
								</td>
								<td valign="top">:&nbsp;<?php echo $this->rs['mother_enname'];?></td>
							</tr>
	  						<tr>
	  							<td valign="top" style="line-height: 32px; white-space: nowrap;">
	  								<strong>Permanent Address</strong> 
	  							</td>
	  							<td valign="top">:&nbsp;N<sup>o</sup> <span style="display: inline-block; white-space:nowrap; min-width: 20px;"><?php echo $this->rs['home_num'];?></span> &nbsp;Street &nbsp;<span style="display: inline-block; min-width: 40px;"><?php echo $this->rs['street_num'];?>,</span>
	  								<?php echo $this->rs['commune_nameeg'];?>,&nbsp;<?php echo $this->rs['district_en'];?>&nbsp;,&nbsp;<?php echo $this->rs['province_enname'];?> 
	  							</td>
	  						</tr>
  						</table>
			  		</td>
			  	</tr>
			  	<tr>
			  		<td style="font-family:  'Times New Roman' , 'Khmer OS Battambang';">Is currently a Student  of <?php echo $this->rs['grade'];?> in the academic school year <?php echo $this->rs['academic_year'];?>  at <?php echo $this->rs['school_nameen'];?> </td>
			  	</tr>
			  	<tr><td>&nbsp;</td></tr>
			  	<tr>
			  		<td style="line-height: 32px; font-family:  Times New Roman , Khmer OS Battambang;">
			  		This letter is issued to the bearer for official purposes is may thereto serve.
			  		</td>
			  	</tr>
			  	<tr>
			  		<td>
			  			<table style="font-family: 'Times New Roman' , 'Khmer OS Battambang';">
			  				<tr>
			  					<td>
			  						<table width="100%" style="line-height: 15px;white-space: nowrap;">
			  							<tr>
			  								<td width="28%">&nbsp;</td>
			  								<td width="40%" align="center"> </td>
			  								<td width="28%" align="center"></td>
			  							</tr>
			  							<tr>
			  								<td>&nbsp;</td>
			  								<td >&nbsp;</td>
			  								<td align="center"><div>Date:&nbsp;<?php echo date('F d, Y');?></div></td>
			  							</tr>
			  							<tr>
			  								<td>&nbsp;</td>
			  								<td align="center"><div>&nbsp;</div></td>
			  							</tr>
			  							<tr>
			  								<td>&nbsp;</td>
			  								<td align="center"><div>&nbsp;</div></td>
			  							</tr>
			  							<tr>
			  								<td>&nbsp;</td>
			  								<td >&nbsp;</td>
			  								<td width="40%" align="center">
			  								<span style="line-height:32px; font-family: 'Times New Roman', Khmer OS Muol Light; display:block;font-size: 16px; margin-buttom: 78px;">
			  								<strong>SCHOOL PRINCIPAL</strong>
			  								</span>
			  								</td>
			  							</tr>
			  						</table>
			  					</td>
			  				</tr>
			  			</table>
			  		</td>
			  	</tr>
			</table>
		</div>
	</div>
</body>
</html>

