<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$_dbgb = new Application_Model_DbTable_DbGlobal();
?>	
<title><?php echo $tr->translate("Pickup Card Selected")?></title>
<script type="text/javascript">
function getKHMonthByNumber(m){
	var monthName=[
		"មករា",
		"កុម្ភៈ",
		"មីនា",
		"មេសា",
		"ឧសភា",
		"មិថុនា",
		"កក្កដា",
		"សីហា",
		"កញ្ញា",
		"តុលា",
		"វិច្ឆិកា",
		"ធ្នូ",
		];
		return (monthName[m-1]);
}	
</script>
<div class="dijitHidden" style="width: 120mm !important; height: 40mm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:22cm;margin: 0 auto;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="print_pickup_card" >
		<div id="PickupCard" style="margin: 0 auto;width:100%;" >
		<style>
			.card-content-student-printpickup{
				background-image: url('<?php echo $this->baseUrl().'/images/card/pickup-student-card.png';?>');
				background-size: 100%;background-repeat: no-repeat;	
				position: relative;			
				display:inline-block;	
				float:left;					
				border:solid 1px #eee;
				width: 14.5cm; 
				height:10.3cm; 	
			}
			<?php if(!empty($this->groupByBranchAndSchool)) foreach($this->groupByBranchAndSchool as $bck){
				$imagepick = $this->baseUrl().'/images/card/default_card_bg.jpg';
				$bgpick = $_dbgb->getPickupCardBackground($bck['branch_id'],$bck['schoolOption']);
				if(!empty($bgpick['background'])){
					if (file_exists(PUBLIC_PATH."/images/card/".$bgpick['background'])){
					$imagepick = $this->baseUrl().'/images/card/'.$bgpick['background'];
					}
				}
				?>
			.card-content-student-printpickup<?php echo ".card".$bck['branch_id']."card".$bck['schoolOption'];?>{	
				background-image: url('<?php echo $imagepick;?>');
				background-size: 100%;background-repeat: no-repeat;					
			}
			<?php }?>
			.guardian-name {
				font-family: 'Khmer OS Muol Light';
				position: absolute;
				top: 33%;
				left: 60px;
				color: #000;
			}
			.profile-card-block {
				position: relative;
			}
			.profile-card-block .photo {
				 width: initial;
				position: absolute;
				top: 120px;
				left: 80.2% !important;
				border: solid 1px #4a4a4a;
			}
			.photo img {
				width: 70.7px;
				height: 92px;
			}
			.profile-card-block .stu_code {
				text-align:center;
				min-width: 70.7px;
				position: absolute;
				top: 213px;
				left: 80.2% !important;
				font-weight:bold;
				font-size:12px;
				color:#000;
			}
			.guardian-card-block .photo {
				width: initial;
				position: absolute;
				top: 150px;
				left: 35.2% !important;
				border: solid 1px #4a4a4a;
			}
			.guardian-card-block .photo.pho1 {
				left: 50.2% !important;
			}
		</style>
		<?php 			
			$i=0;$margin_work = 2;
			if(!empty($this->rs)){foreach ($this->rs as $key => $row){?>
			<div class="card-content-student-printpickup <?php echo "card".$row['branch_id']."card".$row['schoolOption'];?>" style=" <?php if($key==0 || $key==1){ echo "margin-top:-5px;";}else{ echo "margin-top:4px;";} ?> line-height: 16.285px;    color: #3f3f95; font-family: 'Times New Roman', sans-serif,'Kh Battambang','Khmer Battambang'; ">
				<?php 
					$image = $this->baseUrl().'/images/no-profile.png';
					if(!empty($row['photo'])){
						if (file_exists(PUBLIC_PATH."/images/photo/".$row['photo'])){
						$image = $this->baseUrl().'/images/photo/'.$row['photo'];
						}
						
					}
					$stuname = $row['stu_enname']." ".$row['last_name'];
					$bgge = $_dbgb->getPickupCardBackground($row['branch_id'],$row['schoolOption']);
					if (!empty($bgge)){
						if ($bgge['display_by']==2){
							$stuname = $row['stu_khname'];
						}
					}
					?>
				<div class="guardian-name">
					<?php echo $stuname;?>
				</div>
				<div class="profile-card-block">
					<div class="photo">
						<img  src="<?php echo $image;?>" alt="profile-image" >
					</div>
					<div class="stu_code" style="text-align:center;">
						<?php echo $row['stu_code']; ?>
					</div>
				</div>
				<div class="guardian-card-block">
					<?php 
						$guardian_photo = $this->baseUrl().'/images/no-profile.png';
						 if (!empty($row['guardian_photo'])){
							if (file_exists(PUBLIC_PATH."/images/photo/".$row['guardian_photo'])){
								$guardian_photo = $this->baseUrl().'/images/photo/'.$row['guardian_photo'];
							}
						 }
						 $father_photo = $this->baseUrl().'/images/no-profile.png';
						 if (!empty($row['father_photo'])){
							if (file_exists(PUBLIC_PATH."/images/photo/".$row['father_photo'])){
								$father_photo = $this->baseUrl().'/images/photo/'.$row['father_photo'];
							}
						 }
						 $mother_photo = $this->baseUrl().'/images/no-profile.png';
						 if (!empty($row['mother_photo'])){
							if (file_exists(PUBLIC_PATH."/images/photo/".$row['mother_photo'])){
								$mother_photo = $this->baseUrl().'/images/photo/'.$row['mother_photo'];
							}
						 }
					?>
					<?php if(!empty($row['guardian_photo'])){ ?>
					<div class="photo">
						<img  src="<?php echo $guardian_photo;?>" alt="profile-image" >
					</div>
					<?php }else{?>
					<div class="photo">
						<img  src="<?php echo $father_photo;?>" alt="profile-image" >
					</div>
					<?php }?>
					<div class="photo pho1">
						<img  src="<?php echo $mother_photo;?>" alt="profile-image" >
					</div>
				</div>
			</div>
		<?php }}?>
		</div>
		<table width="100%">
			<tr>
				<td align="center">
					<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
					<button dojoType="dijit.form.Button" id="print_pickup" iconClass="dijitEditorIcon dijitEditorIconPrint"
						type="button" onclick="printPickupCard();">Print Pickup Card</button>
				</td>
			</tr>
		</table>
	</div>
</div>
<script type="text/javascript">
	dojo.ready(function(){
		print();
	});
	function print(){

		loadingBlock();
	  	 var contents = document.getElementById("PickupCard").innerHTML;
	 	  var frame1 = document.createElement('iframe');
	    frame1.name = "frame1";
	    frame1.style.position = "absolute";
	    frame1.style.top = "-1000000px";
	    document.body.appendChild(frame1);
	    var frameDoc = (frame1.contentWindow) ? frame1.contentWindow : (frame1.contentDocument.document) ? frame1.contentDocument.document : frame1.contentDocument; frameDoc.document.open();
	    frameDoc.document.write('<html><head><title>Employee ID</title>');
	    frameDoc.document.write('</head><body>');
	    frameDoc.document.write(contents);
	    frameDoc.document.write('</body></html>');
	    frameDoc.document.close();
	    setTimeout(function () {
	        window.frames["frame1"].focus();
	        window.frames["frame1"].print();
	        document.body.removeChild(frame1);
	        HideloadingBlock();
			<?php 
				defined('BASE_URL')	|| define('BASE_URL', Zend_Controller_Front::getInstance()->getBaseUrl());
				$tr = Application_Form_FrmLanguages::getCurrentlanguage();
				$url_copy =$this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-all-student'),null,true);
			?>
			window.location.href = '<?php echo $url_copy;?>';
	    }, 10000);
	   return false;
	}
</script>