<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("CRM_REPORT")); 
	echo $this->headTitle(''); 
	$frm_items= $this->frm_crm;
?>	
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="reportblog">
	<div class="card-box">
    	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file-text " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CRM_REPORT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				 <div class="form-group">
                   	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("advance_search");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("branch_search");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("ask_for_search");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("know_by_search");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement('status_search');?>
				 	</div>
				 </div>
				 <div class="form-group">
	                <div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("crm_process");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("followup_status");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
	                	<input value="<?php echo $this->search['prev_concern'];?>" type="text" id="e15" name="prev_concern" style="width: 100%">
	                </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("degree");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<input id="grade" />
				 	</div>
				 </div>
				 <div class="form-group">
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("start_date");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("end_date");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<button IconClass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				 	</div>
				 </div>
			</form>
		</div>
		<div id="divPrint">
			<table  style="background:#fff; margin: 0 auto; width: 100%; ">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="20%" align="right">
					</td>
					<td width="60%" align="center">
						<span style="color:#000; font-size: 14px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate("CRM_REPORT");?></span><br/>
						<span style="color:#000; font-size: 12px;font-family:Times New Roman,'Khmer OS Battambang';"><?php if(!empty($this->search['start_date'])){?><?php echo date('d-M-Y',strtotime($this->search['start_date']));?> <?php echo $tr->translate("TO");?> <?php echo date('d-M-Y',strtotime($this->search['end_date']));}?> </span>
					</td>
					<td width="20%" align="right"><label id='lbl_branch'></label></td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
			<style>
				.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table.content-data { page-break-inside:auto }
					table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:8px;
						width:100%;
				
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:10px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.content-data  tr.style {
					  
					   white-space: nowrap;
						
					}
					
					
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:11px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:0 2px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					.redBold {
						font-weight: 600;
						color: #f80000;
					}
					table.content-data tr td{
						padding: 1px;
					}

					.know_byitem{display: inline-table;width:33%;}
					.know_by,label{font-family:'Times New Roman','Khmer OS Battambang';font-size:12px;}
					.know_by li{line-height: 15px;}
						@page {
					page:A4;
					size: landscape;
					}
					.oddRecord{background:#ecf1ff;}
				/*
				table tr th{
					border: 1px solid #000;	
				}
				table {page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				table thead tr td{
					text-align: center;
					padding: 5px;
				}
				tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
				
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:12px;
					white-space: nowrap;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
				}
				table.content-data tr.style-rowdata {
					font-size:10px; 
					height: 23px;
				}
				.know_byitem{display: inline-table;width:33%;}
				.know_by,label{font-family:'Times New Roman','Khmer OS Battambang';font-size:12px;}
				.know_by li{line-height: 15px;}
				@page {
					page:A4;
					size: landscape;
				}
				.oddRecord{background:#ecf1ff;}
				*/
			</style>
				<tr>
					<td colspan="3">
						<div id="exportExcel">
							<table class="content-data" cellpadding="4"​   border="1" >
								<thead>
									<tr  class="style" align="center">
										<td scope="col" rowspan="2"><?php echo $tr->translate("NUM");?></td>
										<td scope="col" colspan="4"><?php echo $tr->translate("CUSTOMER_INFO");?></td>
										<td scope="col" rowspan="2"><?php echo $tr->translate("ASK_FOR");?></td>
										<td scope="col" rowspan="2"><?php echo $tr->translate("Previous Concern");?></td>
										<td scope="col" rowspan="2"><?php echo $tr->translate("REASON");?></td>
										<td scope="col" rowspan="2">&nbsp;<?php echo $tr->translate("KNOW_BY");?>&nbsp;</td>
										<td	scope="col" rowspan="2"><?php echo $tr->translate("Amount Contacted");?></td>
										<td scope="col" colspan="3"><?php echo $tr->translate("STUDENT_INFO");?></td>
										<td scope="col" rowspan="2"><?php echo $tr->translate("TYPE");?></td>
										<td scope="col" rowspan="2"><?php echo $tr->translate("CREATE_DATE");?></td>
										<td scope="col" rowspan="2"><?php echo $tr->translate("BY_USER");?></td>
										<td scope="col" rowspan="2"><?php echo $tr->translate("STATUS");?></td>
										<td scope="col" rowspan="2"><?php echo $tr->translate("FOLLOWU_STATUS");?></td>
									</tr>
									<tr  class="style" align="center">
										<td scope="col"><?php echo $tr->translate("NAME");?></td>
										<td scope="col"><?php echo $tr->translate("GENDER");?></td>
										<td scope="col"><?php echo $tr->translate("PHONE");?></td>
										<td scope="col"><?php echo $tr->translate("CURRENT_ADDRESS");?></td>
										<td scope="col">&nbsp;<?php echo $tr->translate("STUDENT_NAME"); ?>&nbsp;</td>
										<td scope="col">&nbsp;<?php echo $tr->translate("DEGREE"); ?>&nbsp;</td>
										<td scope="col">&nbsp;<?php echo $tr->translate("GRADE"); ?>&nbsp;</td>
									</tr>
								</thead>
								<?php $i=0;
								$total_student=0; 
								$know_by = array();
								$db = new Home_Model_DbTable_DbCRM();
								if(!empty($this->row)){ foreach ($this->row AS $key=> $row) { $i++;?>
								<tr class="style hover context-menu-one <?php if($key%2==0){echo'oddRecord';}?>" align="center" oncontextmenu="setrowdata(<?php echo $row['id'];?>);return false;" >
									<td data-label="<?php echo $tr->translate("NUM");?>" ><?php echo $i;?></td>
									<td data-label="<?php echo $tr->translate("NAME");?>"  align="center" style="padding: 1px"><?php echo $row['kh_name'];?><div><?php echo $row['last_name']." ".$row['first_name'];?></div></td>
									<td data-label="<?php echo $tr->translate("GENDER");?>"  align="center">&nbsp;<?php echo $row['sexTitle']; ?>&nbsp;</td>
									<td data-label="<?php echo $tr->translate("PHONE");?>"  align="center" ><?php echo $row['tel'];?></td>
									<td class="small" data-label="<?php echo $tr->translate("CURRENT_ADDRESS");?>"  align="center" ><small><?php echo $row['current_address'];?></small></td>
									<td data-label="<?php echo $tr->translate("ASK_FOR");?>"  align="left">&nbsp;<?php echo $row['ask_for_title'];?>&nbsp;</td>
									<?php 
										$total_student = $total_student+1;
										$know_by[$row['know_by']]=@$know_by[$row['know_by']]+1;
									
										$pre = explode(",", $row['prev_concern']);
										$prevCon="";
										if (!empty($pre)) foreach ($pre as $a){
											if(empty($a)){
												continue;
											}
											$title = $db->getPrevTilteByKeyCode($a);
											if (empty($prevCon)){
												$prevCon = $title;
											}else {
												if (!empty($title)){
													$prevCon = $prevCon." , ".$title;
												}
											}
										}
									
									?>
									
									<td data-label="<?php echo $tr->translate("Previous Concern");?>"  align="left" ><?php echo $prevCon;?></td>
									<td data-label="<?php echo $tr->translate("REASON");?>"  align="left" ><small><?php echo $row['reason'];?></small></td>
									<td data-label="<?php echo $tr->translate("KNOW_BY");?>" ><?php echo $row['know_by_title'];?></td>
									<td data-label="<?php echo $tr->translate("Amount Contacted");?>"  align="center">&nbsp;<?php echo $row['amountContact'];?> <?php echo $tr->translate("Times");?></td>
									<td data-label="<?php echo $tr->translate("STUDENT_NAME");?>"  align="center" style="padding: 2px 5px;"><?php echo $row['stuNameKh'];?><div><?php echo $row['stuNameEn'];?></div></td>	
									<td data-label="<?php echo $tr->translate("DEGREE");?>"  align="left">&nbsp;<?php echo $row['degree'];?>&nbsp;</td>	
									<td data-label="<?php echo $tr->translate("GRADE");?>"  align="left">&nbsp;<?php echo $row['grade'];?>&nbsp;</td>	
									<td data-label="<?php echo $tr->translate("TYPE");?>" >&nbsp;<?php echo $row['customer_type'];?>&nbsp;</td>	
									<td data-label="<?php echo $tr->translate("CREATE_DATE");?>" >&nbsp;<?php echo $row['create_date'];?>&nbsp;</td>	
									<td data-label="<?php echo $tr->translate("BY_USER");?>" >&nbsp;<?php echo $row['userby'];?>&nbsp;</td>	
									<td data-label="<?php echo $tr->translate("STATUS");?>" >&nbsp;<?php echo $row['crm_status_title'];?>&nbsp;</td>	
									<td data-label="<?php echo $tr->translate("FOLLOWU_STATUS");?>" >&nbsp;<?php echo $row['followup_status'];?>&nbsp;</td>	
								</tr>
							<?php }}?>	
							</table>	
						</div>	
					</td>
				</tr>
				<tr>
					<td colspan="3" align="left">
						<div class='know_by'><strong><?php echo $tr->translate("KNOW_BY");?></strong></div>
						<ul class='know_by'>
						<?php if(!empty($this->rsknowBy)){ foreach($this->rsknowBy as $rsknow){?>
							<li class='know_byitem'><?php echo $rsknow['name']."&nbsp;";echo empty($know_by[$rsknow['id']])?'0':$know_by[$rsknow['id']];echo " ".$tr->translate('STUDENT_UNIT');?></li>
						<?php }}?>
							<li style="border-top:1.5px #000 dashed;;list-style-type: none;padding-top:5px;"><strong><?php echo $tr->translate("TOTAL_STUDENT").'&nbsp;'.$total_student." ".$tr->translate('STUDENT_UNIT');?></strong></li>
						</ul>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<?php echo $this->rsfooterFoundation;?>
					</td>
				</tr>
			</table>
		</div>
	</div>
	
 <link href="<?php echo $this->baseUrl()."/admin/"?>/3.5.0/select2.min.css" /> 
 <script src="<?php echo $this->baseUrl()."/admin/"?>/3.5.0/select2.min.js"></script>
 <script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<?php $crmDetail = $this->baseUrl()."/allreport/allstudent/rpt-crm-detail/id/";?>
  <?php 
 $tags="";
 if (!empty($this->prev_concern)) foreach ($this->prev_concern as $rs){
 	if (empty($tags)){
 		$tags = '"'.$rs['name'].'"';
 	}else{
 		if (!empty($rs['name'])){
 		$tags=$tags.',"'.$rs['name'].'"';
 		}
 	}
 }
?>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	
require(["dojo/ready"], function(ready){
	ready(function(){
		 $("#e15").select2({tags:[<?php echo $tags;?>],placeholder: "<?php echo $tr->translate("Previous Concern");?>",allowClear: true});
	
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade",
			name: "grade",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  

			}
		}, "grade");
		<?php if(!empty($this->search['degree'])){?>
		dijit.byId('degree').attr('value','<?php echo $this->search['degree']?>'); 
		<?php }?>
		getAllGrade();
		branch_id = dijit.byId("branch_search").attr('value');
		if(branch_id!=''){
			branch_label = dijit.byId("branch_search").attr('displayedValue');
			$( "#lbl_branch" ).html(branch_label);
		}
	});
});

var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getAllGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id==''){return false;}
	dojo.xhrPost({
		url:url_dept,
		content:{
			'dept_id':dept_id,
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('grade').set('store',grade_store);   
			dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');  
		},
		error: function(err) {
			alert(err);
		}
	});
}
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="detail"){
				url='<?php echo $crmDetail;?>';
			}
			gotoAction();
		},
		items: {
			"detail": {name: "<?php echo $tr->translate("DETAIL");?>", icon: "fa-file-text", accesskey: "c"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}


</script>