<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RPT_STUDENT_TEST"));
	$frm =  $this->form_search;
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data thead tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="reportblog">
	<div class="card-content collapse show">
		<div class="card-box">
			<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("advance_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_search");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input id="study_year" />
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("degree_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
    	               	<?php echo $frm->getElement("nation_search");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
    	               	<?php echo $frm->getElement("student_option_search");?>
                   </div>
                </div>
                <div class="form-group">
               		<div class="col-md-2 col-sm-2 col-xs-12">
                   		<input dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="start_date" name="start_date" value="<?php  echo $this->search['start_date']; ?>"  type="text">
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" id="end_date" name="end_date" value="<?php echo $this->search['end_date'];?>" type="text">
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("type_exam");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
    	               	<?php echo $frm->getElement("province_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<select name="result_status" id="result_status" class="fullside" dojoType="dijit.form.FilteringSelect" >
			   				<option value="" <?php if($this->search['result_status']==""){echo "selected='selected'";}?>><?php echo $tr->translate("RESULT_TEST_TYPE"); ?></option>
			   				<option value="0" <?php if($this->search['result_status']==0){echo "selected='selected'";}?>><?php echo $tr->translate("NO_RESULT"); ?></option>
			   				<option value="1" <?php if($this->search['result_status']==1){echo "selected='selected'";}?>><?php echo $tr->translate("GET_RESULT"); ?></option>
			   			</select>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box">
			<style>
			.hover:hover{ background: #ddd;}
			</style>
					<div id="divPrint"  >
						<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm;" >
							<tr>
								<td colspan="3"><?php echo $this->rsheader;?></td>
							</tr>
							<tr class="line"><td colspan="3"></td></tr>
							<tr>
								<td>&nbsp;</td>
							</tr>
							<tr style="font-size: 13px;">
								<td width="15%" align="center">
								</td>
								<td align="center"  width="70%">
									<span style="color:#4839bd; font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("RPT_STUDENT_TEST"); ?></span><br />
									<span style="color:#4839bd; font-size: 14px;font-family:'Times New Roman','Khmer OS Battambang';"><?php if(!empty($this->search["start_date"])){echo date("d-M-Y",strtotime($this->search["start_date"]))." ".$tr->translate("TO")." ";}?><?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></span>
								</td>
								<td width="15%">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel">
										<style> 
											th,td{ padding:0 1px;}
											body{font-family: "Times New Roman",Arial,'Kh Battambang','Khmer Battambang'; }
											table{ border-collapse:collapse; margin:0 auto; color:#4839bd;
											border-color:#000; }
											tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
											
											table { page-break-inside:auto }
											tr{ page-break-inside:avoid; page-break-after:auto }
											table.content-data{
												border-collapse:collapse;
												width:100%;
												border:1px solid #4839bd; 
												font-family:'Times New Roman','Khmer OS Battambang';
												font-size:13px;
												white-space: nowrap;
												margin:0 auto;
												color: #4839bd;
											}
											table.content-data  tr.style-head {
											   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
												background: #ccd9ff;
												font-weight: bold;
											}
											table.content-data tr.style-rowdata {
												font-size:11px; 
												height: 23px;
											}
										</style>
									<table class="content-data" width="100%" border="1" align="center" >
										 <?php 
										 	$i=0; 
										 	$updated_result=0;
										 	if (!empty($this->row)){  
										 ?>
										  <tr class="style-head" style="height: 20px;background:#ccd9ff;" align="center">
										    <td rowspan="2">&nbsp;<?php echo $tr->translate("N_O"); ?>&nbsp;</td>
										    <td style="line-height: 18px; white-space: normal !important;max-width: 50px;width: 100px;padding: 2px;overflow-wrap: break-word;" rowspan="2">&nbsp;<?php echo $tr->translate("SERIAL"); ?>&nbsp;</td>
										    <td rowspan="2">&nbsp;<?php echo $tr->translate("STUDENT_ID"); ?>&nbsp;</td>
											<td rowspan="2">&nbsp;<?php echo $tr->translate("STUDENT_NAMEKHMER"); ?>&nbsp;</td>
											<td rowspan="2">&nbsp;<?php echo $tr->translate("NAME_ENGLISH"); ?>&nbsp;</td>
											<td rowspan="2">&nbsp;<?php echo $tr->translate("SEX"); ?>&nbsp;</td>
											<td rowspan="2">&nbsp;<?php echo $tr->translate("PHONE"); ?>&nbsp;</td>
											<td rowspan="2">&nbsp;<?php echo $tr->translate("ACADEMIC_YEAR"); ?>&nbsp;</td>
											<td rowspan="2">&nbsp;<?php echo $tr->translate("TEST_DATE"); ?>&nbsp;</td>
											<td colspan="3">&nbsp;<?php echo $tr->translate("RESULT"); ?>&nbsp;</td>
											<td rowspan="2">&nbsp;<?php echo $tr->translate("NOTE"); ?>&nbsp;</td>
											<td rowspan="2">&nbsp;<?php echo $tr->translate("USER"); ?>&nbsp;</td>
											<td rowspan="2">&nbsp;<?php echo $tr->translate("RESULT"); ?>&nbsp;</td>
											<td rowspan="2">&nbsp;<?php echo $tr->translate("STATUS"); ?>&nbsp;</td>
											<td style="line-height: 18px; white-space: normal !important;max-width: 80px;width: 100px;padding: 2px;overflow-wrap: break-word;" rowspan="2">&nbsp;<?php echo $tr->translate("RESULT_BY"); ?>&nbsp;</td>
										  </tr>
										 <tr class="style-head" style="height: 20px;background:#ccd9ff;" align="center">
										 	<td>&nbsp;<?php echo $tr->translate("DEGREE"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("GRADE"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("RESULT_DATE"); ?>&nbsp;</td>
										 </tr>
										 <?php foreach($this->row as $rs){ $i++;?>
											  <tr class="style-rowdata hover context-menu-one" oncontextmenu="setrowdata(<?php echo $rs['stu_id'];?>);return false;" align="center" style="height: 20px;"​ >
												    <td><?php echo $i;?></td>
												    <td style="line-height: 18px; white-space: normal !important;max-width: 50px;width: 100px;padding: 2px;overflow-wrap: break-word;"><?php echo $rs['serial']; ?></td>
												    <td><?php echo $rs['stu_code']; ?></td>
												    <td align="left">&nbsp;<?php echo $rs['stu_khname']; ?></td>
												    <td align="left">&nbsp;<?php echo $rs['last_name']." ".$rs['stu_enname']; ?></td>
												    <td><?php echo $rs['sex']; ?></td>
												    <td><?php echo $rs['tel']; ?></td>
												    <td style="line-height: 18px; white-space: normal !important;max-width: 80px;width: 100px;padding: 2px;overflow-wrap: break-word;"><?php echo $rs['academic']; ?></td>
												    <td><?php echo date('d-M-Y', strtotime($rs['create_date_exam'])); ?></td>
												    <td><?php if ($rs['updated_result_de']==1){ echo $rs['degree_result_title']; }?></td>
												    <td><?php if ($rs['updated_result_de']==1){ echo $rs['grade_result_title']; }?></td>
												    <td><?php if ($rs['updated_result_de']==1){ echo date('d-M-Y', strtotime($rs['result_date'])); }?></td>
												    <td><?php echo $rs['note_result']; ?></td>
													<td><?php echo $rs['user_id'];?></td>								    
												    <td style="line-height: 18px; white-space: normal !important;max-width: 80px;width: 100px;padding: 2px;overflow-wrap: break-word; <?php if($rs['updated_result_de']==0){echo " color:red;";}?>" ><?php echo $rs['result_status']; ?></td>
												    <td style="line-height: 18px; white-space: normal !important;max-width: 80px;width: 100px;padding: 2px;overflow-wrap: break-word; <?php if($rs['is_registered']==0){echo " color:red;";}?>">&nbsp;<?php if ($rs['is_registered']==1){ echo $tr->translate("REGISTERED");}else{ echo $tr->translate("Not Yet Register");}?>&nbsp;</td>							    
											  		<td>&nbsp;<?php echo $rs['result_by'];?>&nbsp;</td>	
											  </tr>
											  <?php 
											  	if($rs['updated_result_de']==1){
													$updated_result = $updated_result + 1;
											  	}
											  ?>
										  <?php }}?>
									</table>
									<?php if (!empty($this->row)){?>
									<table width="40%"  align="right" style=" color:#4839bd; white-space: nowrap;font-family: 'Times New Roman','Khmer OS Battambang'; font-size: 14px; margin-top: 10px;">
										<tr align="right">
											<td>
												<ul style=" list-style: none; padding: 0;">
													<li>
														<?php echo $tr->translate("STUDENT_TOTAL");?> : <?php echo $i;?> <?php echo $tr->translate("STUDENT_UNIT");?>
													</li>
													<li>
														<?php echo $tr->translate("TOTAL_GET_RESULT");?> : <?php echo $updated_result;?> <?php echo $tr->translate("STUDENT_UNIT");?>
													</li>
													<li>
														<?php echo $tr->translate("TOTAL_NO_RESULT");?> : <?php echo ($i-$updated_result);?> <?php echo $tr->translate("STUDENT_UNIT");?>
													</li>
												</ul>
											</td>
										</tr>
									</table>
									<?php }?>
								</td>
							</tr>
							<tr>
								<td colspan="3" style="border:1px solid #fff;">
									<table cellpadding="0" cellspacing="0" width="100%" style="font-size: 14px">
										<tr>
											<td width="35%" align="center">
												<span style="color:#4839bd; font-size: 14px;font-family:Times New Roman , khmer os battambang;"><?php echo $tr->translate("CHECKANDAPPROVED");?></span><br />
												<span style="color:#4839bd; font-size: 14px;font-family:Times New Roman , Khmer OS Muol Light;"><?php echo $tr->translate("PRINCIPAL");?></span>
											</td>
											<td width="30%">&nbsp;</td>
											<td width="35%" align="center">
												<span style="color:#4839bd; font-size: 14px;font-family:Times New Roman , khmer os battambang;"><?php echo $tr->translate("CREATE_WORK_DATE");?></span><br />
												<span style="color:#4839bd; font-size: 14px;font-family:Times New Roman , Khmer OS Muol Light;"><?php echo $tr->translate("PREPARE_BY");?></span>
											</td>
										</tr>
									</table>
							</td>
					</tr>
				</table>
			</div>	
		</div>
	</div>
</div>
<div class="ptss-frame  js-ptss-frame "><!-- is-opened -->
	<div class="ptss__toggle-btn  js-ptss-toggle-btn ">
		<i class="fa fa-print"></i>
	</div>
	<div class="ptss__header"><?php echo $tr->translate("PRINT");?></div>
	<div class="ptss__settings">
		<div class="ptss__single-setting" id="ptss__layout">
			<div class="ptss__setting-control">
				<div class="ptss__layout-wrapper">
					<a class="qButton" title="<?php echo $tr->translate("Preview");?>" href="#" onclick="preview();"><i class="fa fa-search" aria-hidden="true"></i></a>
					<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrint();" ><i class="fa fa-print" aria-hidden="true"></i></a>
					<a class="qButton excel" href="#"  title="<?php echo $tr->translate("Export");?>"  onclick="exportExcel();"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a>
				</div>
			</div>
		</div>
	</div>
</div>
<?php 
	$urlStudentProfile = $this->baseUrl()."/test/index/profile/id/";
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	
	 var branch_id = dijit.byId('branch_search');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
    });
	 getAllAcademicByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->search['branch_search']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_search').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
		    }
		},
		error: function(err) {
		}
	});
}
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="profile"){
				url='<?php echo $urlStudentProfile;?>';
			}
			gotoAction();
		},
		items: {
			"profile": {name: "<?php echo $tr->translate("STUDENT_INFO");?>", icon: "fa-file-text-o",},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	window.open(url+row);
}
</script>