<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('របាយការណ៏ សិស្ស'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
// 	print_r($this->rs);
?>	
<style>
.hover:hover{ background:#ccc;}</style>
<div style="width: 30cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-all-student')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table width="100%">
	       <tr>
	           <td><?php echo $frm->getElement("title");?></td>
	           <td><?php echo $frm->getElement("branch_id");?></td>
	           <td><?php echo $frm->getElement("study_year");?></td>
	           <td><?php echo $frm->getElement("degree");?></td>
	           <td><?php echo $frm->getElement("grade_all");?></td>
			</tr>
			<tr>
				<td><?php echo $frm->getElement("session");?></td>
				<td><?php echo $frm->getElement("start_date");?></td>
				<td><?php echo $frm->getElement("end_date");?></td>
				<td>
					<select name="stu_type" id="stu_type" type="text" class="fullside" dojoType="dijit.form.FilteringSelect" >
						<option value="-1" <?php if($this->search['stu_type']==-1){echo 'selected="selected"';}?>> All Students </option>
						<option value="0" <?php if($this->search['stu_type']==0){echo 'selected="selected"';}?>> Old Students </option>
						<option value="1" <?php if($this->search['stu_type']==1){echo 'selected="selected"';}?>> New Students </option>
					</select>
				</td>
				
				<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		 	</tr>
		</table>		
</form>
</div>
<script type="text/javascript">
function getKHMonthByNumber(m){
	var monthName=[
		"មករា",
		"កុម្ភៈ",
		"មីនា",
		"មេសា",
		"ឧសភា",
		"មិថុនា",
		"កក្កដា",
		"សីហា",
		"កញ្ញា",
		"តុលា",
		"វិច្ឆិកា",
		"ធ្នូ",
		];
		return (monthName[m-1]);
}	
</script>
<div style="border: 1px dotted #000;background: #fff;width:29cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
	<div id="divPrint">
		<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
			<tr>
				<td width="15%" align="center">
					<img style="width: 60%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"> 
				</td>
				<td width="70%"  align="center">
				    <strong​​ style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_BRANCH");?></strong><br />
					<strong​​ style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("ALL_STUDENT_REPORT");?></strong><br />
					<strong​​ style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">From  <?php echo date('d-M-Y',strtotime($this->search['start_date']));?>  To   <?php echo date('d-M-Y',strtotime($this->search['end_date']));?> </strong>
				</td>
				<td width="15%" align="center">
				</td>
			</tr>
		<style>
			table tr th{
				border: 1px solid #000;	
			}
		</style>
		
			<tr>
				<td colspan="3">
				<div id="exportExcel">
					<table cellpadding="4"​ style="font-family:'Khmer OS Battambang' ; margin:0 auto;width:100%;border:1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
						<tr style="font-size:11px; height: 20px;" align="center" >
							<td rowspan="2"><input type="checkBox" onclick="checkAllStudent('<?php echo count($this->rs);?>');" name="checkall" id="checkall" /></td>
							<td rowspan="2">No.</td>
							<td rowspan="2">Branch Name</td>
							<td rowspan="2">Student Code</td>
							<td rowspan="2">Name</td>
							<td rowspan="2">Sex</td>
							<td rowspan="2">Nationality</td>
							<td rowspan="2">Tel</td>
							<td rowspan="2">Email</td>
							<td colspan="5">Study Info</td>
						</tr>
						<input type="hidden" name="id_selected" id="id_selected" dojoType="dijit.form.TextBox" />
						<tr style="font-size:11px; height: 20px;" align="center" >
							<td >AcademicYear</td>
							<td >Degree</td>
							<td >Grade</td>
							<td >Session</td>
							<td >Status</td>
						</tr>
					<?php $i=0;$degree=0; foreach ($this->rs AS $row) { $i++;$degree=$row['degree'];?>
						<tr style="font-size:11px; height: 23px;" align="center" class="hover" >
							<td>
								<input style="height: 15px;margin-top: 5px;" type="checkBox" onClick="checked_id(<?php echo $i?>)" name="check_box<?php echo $i?>" id="check_box<?php echo $i?>" />
								<input type="hidden" name="stu_id<?php echo $i;?>" id="stu_id<?php echo $i;?>" value="<?php echo $row['stu_id'];?>" dojoType="dijit.form.TextBox" />
							</td>
							<td ><?php echo $i;?></td>
							<td ><?php echo $row['branch_name'];?></td>
							<td ><?php echo $row['stu_code'];?></td>
							<td align="left">&nbsp;&nbsp;&nbsp;<?php echo $row['name'];?>&nbsp;</td>
							<td ><?php echo $row['sex'];?></td>	
							<td ><?php echo $row['nationality'];?></td>
							<td ><?php echo $row['tel'];?></td>
							<td align="left">&nbsp;<?php echo $row['email'];?></td>
							<td ><?php echo $row['academic_year'];?></td>
							<td ><?php echo $row['degree'];?></td>
							<td align="left">&nbsp;<?php echo $row['grade'];?></td>
							<td ><?php echo $row['session'];?></td>	
							<td <?php if($row['is_subspend']!=0){echo 'style="color: red;"';}?>><?php echo $row['status'];?></td>	
						</tr>
					<?php }?>	
					</table>	
				</div>	
				</td>
			</tr>
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			<tr >
				<td colspan="3" width="100%">
					<table width="100%" style="font-family:'Khmer OS Battambang';">
						<tr>
							<td  width="25%" align="center">
								<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
							</td>
							<td  width="50%">
								&nbsp;
							</td>
							<td align="center"  width="25%">
								<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>
	<table width="100%">
		<tr>
			<td align="center">
				<button dojoType="dijit.form.Button" id="printselected" iconClass="dijitEditorIcon dijitEditorIconPrint"
					type="button" onclick="printSelected();">Print Selected</button>
				<input type="button" dojoType="dijit.form.Button" label="Print ID Card" iconClass="dijitEditorIcon dijitEditorIconPrint"  onclick="printIDCard();" />
			</td>
		</tr>
	</table>
</div>
<div class="dijitHidden" style="width: 22cm !important; height: 11cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:22cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="print_income" >
		<div id="divPrint1" style="width: 21cm !important; height: 13cm ; padding: 0px; margin: 0px;">
		<?php $con=4;$margin=5;$i=0;if(!empty($this->rs)){foreach ($this->rs AS $row){$i++;?>	
			<table  width="100%" style="white-space: nowrap;font-size:10px;font-family: 'Khmer OS Battambang';<?php if($i==1){echo 'margin-top:50px;';}?> <?php if($i==$margin){echo 'margin-top:50px;';$margin = $margin +4;}?>" class="print" cellspacing="1"  cellpadding="0">
				<tr>
					<td width="50%" align="right">
						<table style="border: 3px solid #FFC107;<?php if($row['dept']<=2){echo 'height: 5.9cm;';}else{echo 'height: 5.95cm;';}?> width: 8.5cm;font-size:11px;font-family: 'Khmer OS Battambang';color:#00007b;">
							<tr>
								<td width="25%" align="left" valign="top">
									<img style="width:100%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
								</td>
								<td valign="top" align="center" width="65%" style="line-height: 20px;white-space: nowrap;">
									<div style="margin-right: 20px;margin-top: 3px;">
										<span style="font-family: 'Khmer OS Muol Light';"><?php echo $tr->translate("CUSTOMER_BRANCH");?></span><br />
										<?php echo $tr->translate("SCHOOL_NAME");?><br />
										<?php echo $tr->translate("SLOGAN_SCHOOL");?> <br />
										<img style="width:40%;" src="<?php echo $this->baseUrl().'/images/style.png'?>">
									</div>
								</td>
								<td width="10%">&nbsp;</td>
							</tr>
							<?php 
								$address_kh='អាសយដ្ឋាន: អាគារលេខ ២D ផ្លូវលេខ៣៧១(សឡា) ភូមិ ទ្រា <br /> 
											សង្កាត់ ស្ទឹងមានជ័យ ខណ្ឌ មានជ័យ រាជធានីភ្នំពេញ<br />
											ទូរស័ព្ទលេខ: ០២៣ ៦៣១ ៦៨៥៧ ឫ ០១៧ ៦៨៣ ៤៧៥ <br />
											បណ្ណនេះប្រើប្រាស់សម្រាប់កិច្ចការសាលាតែប៉ុណ្ណោះ។';
								$address_en='Building # 2 D,Street 371(Sola), Trea Village, Meanchey<br />
										Commune, Stung Meanchey District, Phnom Penh.<br />
										Telephone: (023) 631 6857; (017) 683 475 <br />
										This ID Card is to be used within C.A.S only.';
							?>
							<tr>
								<td align="center" valign="top" colspan="3" style="line-height: 20px;"> 
									<div style="margin-top: -20px;"><?php if($row['dept']<=2){echo 'ឆ្នាំសិក្សា';}else{echo 'Academic Year';}?> &nbsp;<label id="academic_year<?php echo$i;?>"></label><br />
										<script type="text/javascript">
											<?php //echo $row['academic_year'];?>
											<?php if($row['dept']<=2){?>
												year = convertEnglishToKhmerNumber('<?php echo $row['start_year']?>')+'-'+convertEnglishToKhmerNumber('<?php echo $row['end_year']?>');
												
											<?php }else{?>
												year = '<?php echo $row['academic_year'];?>';
											<?php } ?>
											
											dojo.byId('academic_year<?php echo $i;?>').innerHTML=year;
											
										</script>
									
										<?php if($row['dept']<=2){echo $address_kh;}else{echo $address_en;}?>
										
									</div>
								</td>
							</tr>
						</table>
					</td>
					<?php 
						if($row['sex']=='M' ){
							$sex_en = "Male";
							$sex_kh = "ប្រុស";
						}else{
							$sex_en = "Female";
							$sex_kh = "ស្រី";
						}
					?>
					
					<td width="50%">
						<table style="border: 3px solid #FFC107;height: 5.9cm;width: 8.5cm;font-size:11px;font-family: 'Khmer OS Battambang',Arial,sans-serif;color:#00007b;" cellspacing="0" cellpadding="0">
							<tr style="height: 0;">
								<td colspan="4" align="center" valign="top">
									<div style="font-family: 'Khmer OS Muol Light';margin-top: 5px;">អត្តសញ្ញាណបណ្ណសិស្ស</div>
									<div style="margin-top: -4px;"><?php if($row['dept']<=2){echo 'អត្តលេខ';}else{echo 'ID N<sup>o</sup>';}?>: <label id="stu_code<?php echo $i;?>"></label></div>
									
									<script type="text/javascript">
										<?php if($row['dept']<=2){?>
												test1 = convertEnglishToKhmerNumber('<?php echo $row['stu_code']?>');
										<?php }else{?>
												test1 = '<?php echo $row['stu_code'];?>';
										<?php }?>
										dojo.byId('stu_code<?php echo $i;?>').innerHTML=test1;
										//alert(test1);
									</script>
								</td>
							</tr>
							<tr style="height: 0;line-height: 18px" >
								<td width="25%">
									&nbsp;&nbsp;ឈ្មោះ
								</td>
								<td width="50%">
									: <span style="font-family: 'Khmer OS Muol Light';"><?php echo $row['stu_khname'];?></span>
								</td>
								<td width="15%">
									ភេទ : 
								</td>
								<td width="12%">
									<?php echo $sex_kh;?>
								</td>
							</tr>
							
							<tr style="height: 0;line-height: 18px">
								<td >
									&nbsp;&nbsp;Name
								</td>
								<td >
									: <span style="font-family: 'Khmer OS Muol Light';"><?php echo $row['stu_enname'];?></span>
								</td>
								<td >
									Sex : 
								</td>
								
								<td >
									<?php echo $sex_en;?>&nbsp;&nbsp;&nbsp;
								</td>
							</tr>
							
							<tr style="height: 0;line-height: 18px">
								<td >
									&nbsp;&nbsp;<?php if($row['dept']<=2){echo 'កាលកំណើត';}else{echo 'D.O.B';}?>
								</td>
								<td colspan="3">
									: <label id="dob<?php echo $i;?>"></label>
									<script type="text/javascript">
									<?php if($row['dob']==null || $row['dob']==''){ ?>
											dob = '';
									<?php }else{ if($row['dept']<=2){ ?>
												dob = 'ថ្ងៃទី ' + convertEnglishToKhmerNumber('<?php echo date('d',strtotime($row['dob']));?>')+' ខែ '+getKHMonthByNumber('<?php echo date('m',strtotime($row['dob']));?>')+' ឆ្នាំ '+ convertEnglishToKhmerNumber('<?php echo date('Y',strtotime($row['dob']));?>');
											<?php }else{?>
												dob = "<?php echo date('d F Y',strtotime($row['dob']));?>";
											<?php }?>
											dojo.byId('dob<?php echo $i;?>').innerHTML=dob;
									<?php }?>
									</script>
									
								</td>
							</tr>
							
							<tr style="height: 0;line-height: 18px">
								<td >
									&nbsp;&nbsp;<?php if($row['dept']<=2){echo 'សិស្សថ្នាក់';}else{echo 'Level';}?>
								</td>
								<td colspan="3">
									: <?php  echo $row['grade'];?>
								</td>
							</tr>
							
							<tr style="height: 0;line-height: 18px">
								<td >
									&nbsp;&nbsp;<?php if($row['dept']<=2){echo 'ផុតកំណត់';}else{echo 'Expired Date';}?>
								</td>
								<td colspan="3">
								: <label id="year<?php echo $i;?>"></label>
									<script type="text/javascript">
										<?php if($row['dept']<=2){?>
											kh_date = 'ថ្ងៃទី ' + convertEnglishToKhmerNumber('<?php echo date('d',strtotime($row['end_date']));?>')+' ខែ '+getKHMonthByNumber('<?php echo date('m',strtotime($row['end_date']));?>')+' ឆ្នាំ '+ convertEnglishToKhmerNumber('<?php echo date('Y',strtotime($row['end_date']));?>');
										<?php }else{?>
											kh_date = '<?php echo date('F d , Y',strtotime($row['end_date']));?>';
										<?php }?>
										dojo.byId('year<?php echo $i;?>').innerHTML=kh_date;
									</script>
								</td>
							</tr>
							
							<tr>
								<td colspan="4">
									<table width="100%" style="font-size:11px;font-family: 'Khmer OS Battambang';color:#00007b;">
										<tr>
											<td width="20%">
												&nbsp;
											</td>
											<td width="22%" >
												<img style="width:100%;height: 73px;border: 1px solid rgba(0, 0, 0, 0.1);" src="<?php echo $this->baseUrl().'/images/'.$row['photo'];?>">
											</td>
											<td width="58%" align="center" valign="top" colspan="2">
												<div style="margin-top: -3px;">
													<?php if($row['dept']<=2){echo 'ធ្វើនៅថ្ងៃទី ';}else{echo 'Date : ';}?><label id="create_date<?php echo $i;?>"></label>
													<script type="text/javascript">
														<?php if($row['dept']<=2){?>
															create_date = convertEnglishToKhmerNumber('<?php echo date('d');?>')+' ខែ '+getKHMonthByNumber('<?php echo date('m');?>')+' ឆ្នាំ '+ convertEnglishToKhmerNumber('<?php echo date('Y');?>');
														<?php }else{?>
															create_date = '<?php echo date('F d , Y');?>';
														<?php }?>
														dojo.byId('create_date<?php echo $i;?>').innerHTML=create_date;
													</script>
												
												</div>
												<div style="margin-top: -2px;<?php if($row['dept']<=2){echo 'font-family: Khmer OS Muol Light;';}?>"><?php if($row['dept']<=2){echo 'នាយក';}else{echo 'Director';}?></div><br />
												<div style="margin-top: 10px;<?php if($row['dept']<=2){echo 'font-family: Khmer OS Muol Light;';}?>"><?php if($row['dept']<=2){}?></div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<?php if($i==$con){$con = $con + 4;?>
				<table width="100%" height="100px" border="0">
					<tr>
						<td>&nbsp;</td>
					</tr>
				</table>
			
			<?php }?>
		<?php }}?>
		</div>
		<table width="100%">
			<tr>
				<td align="center">
					<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
					
					<button dojoType="dijit.form.Button" id="printall" iconClass="dijitEditorIcon dijitEditorIconPrint"
						type="button" onclick="print();">Print ID Card</button>
						
					
				</td>
				
			</tr>
		</table>
		
	</div>
</div>


<script type="text/javascript">

	function printIDCard(){

		//dijit.byId('print_income').show();
		
		//window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint1').innerHTML;
	   // window.frames["print_frame"].window.focus();
	    //window.frames["print_frame"].window.print();

	    //dijit.byId("terms").hide();
	    print();
	}
	function printSelected(){
		<?php 
			defined('BASE_URL')	|| define('BASE_URL', Zend_Controller_Front::getInstance()->getBaseUrl());
    		$tr = Application_Form_FrmLanguages::getCurrentlanguage();
    		$url_copy =$this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'idselected'));
    	?>

    	 id_selected = dijit.byId('id_selected').get('value');
    	 //alert(id_selected);
		 if(id_selected!=''){
			window.location.href = '<?php echo $url_copy;?>'+'/id/'+id_selected;
		 }else{
			alert('Please select record you want to print');
			return false;
		 }
    	
	}
	function print(){
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint1').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();

	    //dijit.byId("terms").hide();
	}

	function checkAllStudent(array_length){
		//alert(array_length);
		dijit.byId('id_selected').attr('value','');
		
		if(dojo.byId('checkall').checked){
			for(var j=1;j<=array_length;j++){
				$("#check_box"+j).attr('checked', 'checked');
				checked_id(j);
			}
		}else{
			for(var j=1;j<=array_length;j++){
				$("#check_box"+j).removeAttr("checked");
				checked_id(j);
			}
		}
	}
	
	function checked_id(index){
		stu_id = dijit.byId('stu_id'+index).get('value');
		
		if(dojo.byId('check_box'+index).checked){
			
			if($("#id_selected").val()!="") {
				var identity = $("#id_selected").val();
				$("#id_selected").val(identity+','+stu_id);
			}else{
				$("#id_selected").val(stu_id);
			}
			
		}else{
			
			var identity = $('#id_selected').val();
			var arrays = identity.split(',');
			for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == stu_id) arrays.splice(i,1);
			}
			var strings = arrays.join(',');
			$('#id_selected').val(strings);
			//dojo.query("#row"+index).remove();
			
		}
	}


	
</script>
	
	
	
	