<?php
	$_dbgb = new Application_Model_DbTable_DbGlobal();
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('REPORT_STUDENT_DOCUMENT_NOT_ENOUGH')); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<style>
.hover:hover{ background:#ccc;}
.hidden{visibility: visible !important;
display: table-cell !important;
}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="reportblog">	
	<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_STUDENT_DOCUMENT_NOT_ENOUGH');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("adv_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                    	<?php echo $frm->getElement("branch_id");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                    	<?php echo $frm->getElement("academic_year");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input id="group" />
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                    	<?php echo $frm->getElement("degree");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                    	<input id="grade" />
                   </div>
             </div>
             <div class="form-group">
                    <div class="col-md-2 col-sm-2 col-xs-12">
                    	<?php echo $frm->getElement("end_date");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                    	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12"></div>
             </div>
	</form>
	<div id="divPrint">
			<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td width="15%" align="center"></td>
					<td width="70%"  align="center">
						<span style="color:#4839bd; font-size: 14px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate("REPORT_STUDENT_DOCUMENT_NOT_ENOUGH");?></span><br />
						<span style="color:#4839bd; font-size: 13px;font-family:Times New Roman,'Khmer OS Battambang';"><?php if(!empty($this->search['end_date'])){?><?php echo $tr->translate("BY_DAY")." ".date('d-M-Y',strtotime($this->search['end_date']));}?></span>
					</td>
					<td width="15%" align="center"></td>
				</tr>
				<style>
					th,td{ padding:0 1px; color:#4839bd; }
							table{ border-collapse:collapse; margin:0 auto;border-color:#4839bd; }
							.padding{ padding: 0 1px !important;}
							table.content-data{ page-break-inside:auto;font-family:'Times New Roman','Khmer OS Battambang'; }
							tr.content-data{ page-break-inside:avoid; page-break-after:auto }
							#header {display: table-header-group;page-break-inside:avoid; page-break-after:auto;}
							.hover:hover{background: #ccc;}
							.hidden{display: none;}
							tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
							
							table.content-data{
								border-collapse:collapse;
								width:100%;
								border:1px solid #4839bd; 
								font-family:'Times New Roman','Khmer OS Battambang';
								font-size:13px;
								white-space: nowrap;
								margin:0 auto;
								color:#4839bd;
							}
							table.content-data thead tr.style-head {
							   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
								background: #fdbdbd;
								text-align: center;
							}
							table.content-data tr.style-rowdata {
								font-size:12px; 
								height: 23px;
							}
					
				</style>
				<tr>
					<td colspan="3" id="exportExcel">
						<table class="content-data" cellpadding="0"​ border="1" >
							<thead>
								<tr class="style-head" align="center" >
									<td scope="col" rowspan="2"><?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td scope="col" colspan="8"><?php echo $tr->translate("STUDENT_INFO");?>&nbsp;</td>
									<td scope="col" colspan="3"><?php echo $tr->translate("DOCUMENT_INFO");?>&nbsp;</td>
								</tr>
								<tr class="style-head" align="center" >
									<td scope="col"><?php echo $tr->translate("STUDENT_CODE");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("STUDENT_NAMEKHMER");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("NAME_ENGLISH");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("SEX");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("PHONE");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("ACADEMIC_YEAR");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("DEGREE");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("GRADE");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("DOCUMENT");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("LATE");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("DATE_GIVE");?>&nbsp;</td>
								</tr>
							</thead>
						<?php $i=0;$degree=0;foreach ($this->rs AS $row) { $i++;
							$end_dat=date("Y-m-d");
							$total_day=strtotime($end_dat)-strtotime($row['date_end']);
							$total_late_day=$total_day/(60*60*24);
						?>
							<tr align="center" style="font-size:12px; line-height: 25px;"​ align="center" class='hover padding context-menu-one' >
								<td data-label="<?php echo $tr->translate("NUM");?>"> <?php echo $i;?></td>
								<td data-label="<?php echo $tr->translate("STUDENT_CODE");?>"><?php echo $row['stu_code'];?></td>
								<td data-label="<?php echo $tr->translate("STUDENT_NAMEKHMER");?>" align="left"><?php echo $row['stu_khname'];?></td>
								<td data-label="<?php echo $tr->translate("NAME_ENGLISH");?>" align="left">&nbsp;<?php echo $row['last_name'].' '.$row['stu_enname'];?></td>
								<td data-label="<?php echo $tr->translate("SEX");?>">
									<?php if ($row['sex']==1){ echo $tr->translate("MALE");}else{ echo $tr->translate("FEMALE");}?>
								</td>	
								<td data-label="<?php echo $tr->translate("PHONE");?>"><?php echo $row['tel'];?></td>
								<td data-label="<?php echo $tr->translate("ACADEMIC_YEAR");?>"> <?php echo $row['academic_year'];?></td>
								<td data-label="<?php echo $tr->translate("DEGREE");?>"><?php echo $row['degree'];?></td>
								<td data-label="<?php echo $tr->translate("GRADE");?>" align="left"><?php echo $row['grade'];?></td>
								<td data-label="<?php echo $tr->translate("DOCUMENT");?>" align="left"><?php echo $row['document_type'];?></td>	
								<td data-label="<?php echo $tr->translate("LATE");?>"><?php if ($total_late_day>0){echo $total_late_day." ".$tr->translate("DAY");}else{ echo "-";}?></td>	
								<td data-label="<?php echo $tr->translate("DATE_GIVE");?>"><?php echo date("d/M/Y",strtotime($row['date_end']));?></td>	
							</tr>
						<?php }?>	
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3" style="border:1px solid #fff;">
						<?php echo $this->rsfooter; ?>

					</td>
				</tr>
			</table>
		</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 

var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
	    }
	}, "group");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                        
		id: "grade",
		name: "grade",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
			 getAllGroupByBranch();
		}
	}, "grade");
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllGroupByBranch();
    });
	 var academic_year = dijit.byId('academic_year');
	 academic_year.on('change', function(evt) {
		 getAllGroupByBranch();
    });
	 getAllGroupByBranch();
	 getallGrade();
	 
	 dijit.byId('end_date').set('value','<?php echo date("Y-m-d",strtotime($this->search['end_date']))?>');  
});
var oldBranch = '<?php echo $this->search['branch_id']?>'
url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	degree = dijit.byId('degree').get('value');
	if(degree=='' || degree==-1){degree ="";}
	grade = dijit.byId('grade').get('value');
	if(grade=='' || grade==-1){grade ="";}
	academic_year = dijit.byId('academic_year').get('value');
	if(academic_year=='' || academic_year==-1){academic_year ="";}
	
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,
			'degree':degree,
			'grade':grade,
			'academic_year':academic_year,
			'noaddnew':1,
			'forfilter':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
		}
	});
}

var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(){
	getAllGroupByBranch();  
	dept_id = dijit.byId('degree').get('value');
	if(dept_id=='' || dept_id==-1){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store); 
			    dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');  
			},
			error: function(err) {
			}
		});
}
function getKHMonthByNumber(m){
	var monthName=[
			"មករា",
			"កុម្ភៈ",
			"មីនា",
			"មេសា",
			"ឧសភា",
			"មិថុនា",
			"កក្កដា",
			"សីហា",
			"កញ្ញា",
			"តុលា",
			"វិច្ឆិកា",
			"ធ្នូ",
			];
		return (monthName[m-1]);
	}	
</script>