<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('RPT_STUDENT_DROPS')); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_STUDENT_DROP');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
            <div class="col-md-3 col-sm-3 col-xs-12">
            	<?php echo $frm->getElement("title");?>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
            	<?php echo $frm->getElement("branch_id");?>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
            	<?php //echo $frm->getElement("study_year");?>
            	<input id="study_year">
            </div>
            <!-- 
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php //echo $frm->getElement("grade_bac");?>
            </div>
             -->
            <div class="col-md-3 col-sm-3 col-xs-12">
            	<?php echo $frm->getElement("session");?>
            </div>
        </div>	
        <div class="form-group">
        	 <div class="col-md-3 col-sm-3 col-xs-12">
        	 	<?php echo $frm->getElement("start_date");?>
            </div>
             <div class="col-md-3 col-sm-3 col-xs-12">
             	<?php echo $frm->getElement("end_date");?>
            </div>
             <div class="col-md-2 col-sm-2 col-xs-12">
             	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
            </div>
        </div>
	</form>		
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto;width: 100%">
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr class="line"><td colspan="3"></td></tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td width="25%" align="left">
				</td>
				<td align="center">
					<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate("RPT_STUDENT_DROP");?></strong><br />
					<strong​​ style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><?php if(!empty($this->search['start_date'])){?><?php echo date('d-M-Y',strtotime($this->search['start_date']));?><?php echo $tr->translate("TO");?><?php echo date('d-M-Y',strtotime($this->search['end_date']));}?> </strong>
				</td>
				<td width="25%" align="right">
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
		<style>
			table tr th{
				border: 1px solid #000;	
				text-align: center;
				padding:5px;
			}
			.hover:hover{background: #ccc;}
			table {page-break-inside:auto }
			tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}	
			tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
		</style>
			<tr>
				<td colspan="3">
					<table border="1" cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;font-family: Khmer OS Battambang,Times New Roman;" >
						<thead>
						<tr style="font-size:12px;  background: #ccd9ff;" align="center" >
							<th ><?php echo $tr->translate("NUM")?></th>
							<th ><?php echo $tr->translate("BRANCH_NAME")?></th>
							<th ><?php echo $tr->translate("STUDENT_ID")?></th>
							<th ><?php echo $tr->translate("STUDENT_NAME")?></th>
							<th ><?php echo $tr->translate("GENDER")?></th>
							<th ><?php echo $tr->translate("ACADEMIC_YEAR")?></th>
							<th ><?php echo $tr->translate("GROUP")?></th>
							<th ><?php echo $tr->translate("GRADE")?></th>
							<th ><?php echo $tr->translate("SESSION")?></th>
							<th ><?php echo $tr->translate("TYPE")?></th>
							<th ><?php echo $tr->translate("STOP_DATE")?></th>
							<th ><?php echo $tr->translate("REASON")?></th>										
						</tr>
						</thead>
					<?php $i=0;foreach ($this->rs AS $row) { $i++;?>
						<tr class="hover" style="font-size:12px; height: 20px;" align="center" >
							<td ><?php echo $i;?></td>
							<td ><?php echo $row['branch_name'];?></td>
							<td ><?php echo $row['stu_id'];?></td>
							<td align="left">&nbsp;&nbsp;<?php echo $row['name'];?></td>
							<td ><?php echo $row['sex'];?></td>
							<td ><?php echo $row['academic_year'];?></td>
							<td ><?php echo $row['group_name'];?></td>
							<td ><?php echo $row['grade'];?></td>
							<td ><?php echo $row['session'];?></td>
							<td ><?php echo $row['type'];?></td>
							<td ><?php echo $row['date_stop'];?></td>
							<td ><?php echo $row['reason'];?></td>
						</tr>
					<?php }?>	
					</table>	
				</td>
			</tr>
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			<tr >
				<td align="center" width="25%">
					<span style="font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
				</td>
				<td  width="50%">&nbsp;
					
				</td>
				<td align="center"  width="25%">
					<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
				</td>
			</tr>
		</table>
	</div>		
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.FilteringSelect"); 

dojo.require("dojo.html");
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
    });
	 getAllAcademicByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}

</script>