<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('របាយការណ៏ សិស្ស'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<style>
.hover:hover{ background:#ccc;}</style>
<div style="min-height:10cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-all-amount-student')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table width="100%">
	       <tr>
	           <td><?php echo $frm->getElement("title");?></td>
	           <td><?php echo $frm->getElement("branch_id");?></td>
	           <td><?php echo $frm->getElement("study_year");?></td>
	           <td><?php echo $frm->getElement("degree");?></td>
	           <td><?php echo $frm->getElement("grade_all");?></td>
			</tr>
			<tr>
				<td><?php echo $frm->getElement("session");?></td>
				<td><select class="fullside" dojoType="dijit.form.FilteringSelect" id="study_type" name="study_type">
						<option value="" <?php if($this->search['study_type']==''){echo "selected";}?>>ជ្រើសរើសប្រភេទសិស្ស</option>
						<option value="0" <?php if($this->search['study_type']==0){echo "selected";}?>>សិស្សនៅរៀន</option>
						<option value="1" <?php if($this->search['study_type']!=0){echo "selected";}?>>សិស្សឈប់</option>
					</select>
				</td>
				<td><?php echo $frm->getElement("start_date");?></td>
				<td><?php echo $frm->getElement("end_date");?></td>
				<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		 	</tr>
		</table>		
	</form>
	<div id="divPrint">
		<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
			<tr>
				<td width="15%" align="center">
					<img style="width: 60%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
				</td>
				<td width="70%"  align="center">
					<ul>
						<li><strong​​ style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_BRANCH");?></strong></li>
						<li><strong​​ style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate("ALL_STUDENT_REPORT");?></strong></li>
						<strong​​ style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><?php if(!empty($this->search['start_date'])){?><?php echo date('d-M-Y',strtotime($this->search['start_date']));?><?php echo $tr->translate("TO");?><?php echo date('d-M-Y',strtotime($this->search['end_date']));}?> </strong>
					</ul>
				</td>
				<td width="15%" align="center">
				</td>
			</tr>
		<style>
			table tr th{
				border: 1px solid #000;	
			}
			ul li{list-style: none;}
			table {page-break-inside:auto }
			tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
		</style>
			<tr>
				<td colspan="3">
				<div id="exportExcel">
					<table cellpadding="4"​ style="font-family:'Khmer OS Battambang' ; margin:0 auto;width:100%;border:1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
						<thead>
						<tr style="font-size:14px; height: 20px;background: #ccd9ff;" align="center" >
							<th rowspan="2"><?php echo $tr->translate("NUM");?></th>
							<th rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></th>
							<th rowspan="2"><?php echo $tr->translate("STUDENT_CODE");?></th>
							<th rowspan="2"><?php echo $tr->translate("NAME_KH");?></th>
							<th rowspan="2"><?php echo $tr->translate("NAME_EN");?></th>
							<th rowspan="2"><?php echo $tr->translate("SEX");?></th>
							<th rowspan="2"><?php echo $tr->translate("NATIONALITY");?></th>
							<th rowspan="2"><?php echo $tr->translate("PHONE");?></th>
							<th rowspan="2"><?php echo $tr->translate("EMAIL");?></th>
							<th colspan="5"><?php echo $tr->translate("STUDY_INFO");?></th>
						</tr>
						<input type="hidden" name="id_selected" id="id_selected" dojoType="dijit.form.TextBox" />
						<tr style="font-size:12px; height: 20px;background: #ccd9ff;" align="center" >
							<th><?php echo $tr->translate("ACADEMIC_YEAR");?></th>
							<th><?php echo $tr->translate("DEGREE");?></th>
							<th><?php echo $tr->translate("GRADE");?></th>
							<th><?php echo $tr->translate("SESSION");?></th>
							<th><?php echo $tr->translate("STATUS");?></th>
						</tr>
						</thead>
					<?php $i=0;$degree=0;$count=0; 
						$all_total = 0;$all_drop = 0;
						if(!empty($this->rs))foreach ($this->rs AS $key=>$row) { 
						if($row['is_subspend']!=0){
							$all_drop = $all_drop+1;
						}else{
							$all_total = $all_total+1;
						}
					?>
						<?php if($degree!=$row['degree'] && $key>0){?>
							<tr>
								<td colspan="11"></td>
								<td align="center" style="font-size: 15px"><?php echo $tr->translate("TOTAL");?></td>
								<td align="center" style="font-size: 15px"><?php echo $count;$count=0;$i=0;?></td>
							</tr>
						<?php }?>
						<?php $i++;$count++; ?>
						<tr style="font-size:14px; height: 23px;" align="center" class="hover" >
							<td ><?php echo $i;?></td>
							<td ><?php echo $row['branch_name'];?></td>
							<td ><?php echo $row['stu_code'];?></td>
							<td align="left">&nbsp;&nbsp;&nbsp;<?php echo $row['stu_khname'];?>&nbsp;</td>
							<td align="left">&nbsp;&nbsp;&nbsp;<?php echo $row['name'];?>&nbsp;</td>
							<td ><?php echo $row['sex'];?></td>	
							<td ><?php echo $row['nationality'];?></td>
							<td ><?php echo $row['tel'];?></td>
							<td align="left">&nbsp;<?php echo $row['email'];?></td>
							<td ><?php echo $row['academic_year'];?></td>
							<td ><?php echo $row['degree'];?></td>
							<td align="left">&nbsp;<?php echo $row['grade'];?></td>
							<td ><?php echo $row['session'];?></td>	
							<td <?php if($row['is_subspend']!=0){echo 'style="color: red;"';}?>><?php echo $row['status'];?></td>	
						</tr>
						<?php $degree=$row['degree'];?>
					<?php }?>	
						<tr>
							<td colspan="12"></td>
							<td align="center" style="font-size: 15px;">Total</td>
							<td align="center" style="font-size: 15px;"><?php echo $count;$count=0;?></td>
						</tr>
					</table>	
					<table style="float: right;font-weight: bolder;">
						<tr>
							<td>សិស្សកំពុងសិក្សាសរុប : </td>
							<td><?php echo number_format($all_total);?>&nbsp;នាក់</td>
						</tr>
						<tr>
							<td>សិស្សឈប់សរុប : </td>
							<td><?php echo number_format($all_drop);?>&nbsp;នាក់</td>
						</tr>
					</table>
				</div>	
				</td>
			</tr>
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			<tr >
				<td colspan="3" width="100%">
					<table width="100%" style="font-family:'Khmer OS Battambang';">
						<tr>
							<td  width="25%" align="center">
								<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
							</td>
							<td  width="50%">
								&nbsp;
							</td>
							<td align="center"  width="25%">
								<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>
</div>	