<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("CRM_REPORT")); 
	echo $this->headTitle(''); 
	$frm_items= $this->frm_crm;
?>	
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="reportblog">
	<div class="card-box">
    	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CRM_REPORT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				 <div class="form-group">
                   	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("advance_search");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("branch_search");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("ask_for_search");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("know_by_search");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement('status_search');?>
				 	</div>
				 </div>
				 <div class="form-group">
				 	<div class="col-md-4 col-sm-4 col-xs-12">
	                	<input value="<?php echo $this->search['prev_concern'];?>" type="text" id="e15" name="prev_concern" style="width: 100%">
	                </div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("start_date");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("end_date");?>
				 	</div>
				 	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<button IconClass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				 	</div>
				 </div>
			</form>
		</div>
		<div id="divPrint">
			<table  style="background:#fff; margin: 0 auto; width: 100%; ">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="20%" align="right">
					</td>
					<td width="60%" align="center">
						<span style="color:#000; font-size: 17px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate("CRM_REPORT");?></span><br/>
						<span style="color:#000; font-size: 14px;font-family:Times New Roman,'Khmer OS Battambang';"><?php if(!empty($this->search['start_date'])){?><?php echo date('d-M-Y',strtotime($this->search['start_date']));?> <?php echo $tr->translate("TO");?> <?php echo date('d-M-Y',strtotime($this->search['end_date']));}?> </span>
					</td>
					<td width="20%" align="right"></td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
			<style>
				table tr th{
					border: 1px solid #000;	
				}
				table {page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				table thead tr td{
					text-align: center;
					padding: 5px;
				}
				tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
				
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #000; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:13px;
					white-space: nowrap;
				}
				table.content-data thead tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #ccd9ff;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
			</style>
				<tr>
					<td colspan="3">
						<div id="exportExcel">
							<table class="content-data" cellpadding="4"​   border="1" >
								<thead>
									<tr  class="style-head">
										<td><?php echo $tr->translate("NUM");?></td>
										<td><?php echo $tr->translate("BRANCH");?></td>
										<td><?php echo $tr->translate("STUDENT_NAMEKHMER");?></td>
										<td><?php echo $tr->translate("NAME_ENGLISH");?></td>
										<td><?php echo $tr->translate("GENDER");?></td>
										<td><?php echo $tr->translate("PHONE");?></td>
										<td><?php echo $tr->translate("ASK_FOR");?></td>
										<td>&nbsp;<?php echo $tr->translate("KNOW_BY");?>&nbsp;</td>
										<td><?php echo $tr->translate("Amount Contacted");?></td>
										<td><?php echo $tr->translate("STATUS");?></td>
										<td>&nbsp;</td>
									</tr>
								</thead>
								<?php $i=0;$degree=0; if(!empty($this->row)){ foreach ($this->row AS $row) { $i++;?>
								<tr class="style-rowdata hover" align="center" >
									<td ><?php echo $i;?></td>
									<td align="left">&nbsp;<?php echo $row['branch_name'];?></td>
									<td align="left" >&nbsp;<?php echo $row['kh_name'];?>&nbsp;</td>
									<td align="left">&nbsp;<?php echo $row['last_name']." ".$row['first_name'];?>&nbsp;</td>
									<td align="center">&nbsp;<?php echo $row['sexTitle']; ?>&nbsp;</td>
									<td ><?php echo $row['tel'];?></td>
									<td ><?php echo $row['ask_for_title'];?></td>
									<td ><?php echo $row['know_by_title'];?></td>
									<td align="center">&nbsp;<?php echo $row['amountContact'];?> <?php echo $tr->translate("Times");?></td>
									<td><?php echo $row['crm_status_title'];?></td>	
									<td>
										<a target="_blank" style="text-decoration: none;color:#000;" href="<?php echo $this->baseUrl();?>/allreport/allstudent/rpt-crm-detail/id/<?php echo $row['id'];?>">
										<?php echo $tr->translate("DETAIL");?>
										</a>
									</td>	
								</tr>
							<?php }}?>	
							</table>	
						</div>	
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
			</table>
		</div>
	</div>
 <link href="<?php echo $this->baseUrl()."/admin/"?>/3.5.0/select2.min.css" /> 
 <script src="<?php echo $this->baseUrl()."/admin/"?>/3.5.0/select2.min.js"></script>
 <style>
</style>
  <?php 
 $tags="";
 if (!empty($this->prev_concern)) foreach ($this->prev_concern as $rs){
 	if (empty($tags)){
 		$tags = '"'.$rs['name'].'"';
 	}else{
 		if (!empty($rs['name'])){
 		$tags=$tags.',"'.$rs['name'].'"';
 		}
 	}
 }
?>
<script type="text/javascript">
require(["dojo/ready"], function(ready){
	ready(function(){
		 $("#e15").select2({tags:[<?php echo $tags;?>],placeholder: "<?php echo $tr->translate("Previous Concern");?>",allowClear: true});
	});
});
</script>