<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('ALL_STUDENT_REPORT')); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<style>
.hover:hover{ background:#ccc;}
.line-height{line-height:20px !important;}
.table-width{width:40% !important}
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.content-data-main tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="reportblog">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ALL_STUDENT_REPORT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("adv_search");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("branch_id");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("academic_year");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<input id="group" />
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("degree");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<input id="grade" />
        	</div>
        </div>
        <div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("session");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("study_type");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("start_date");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("end_date");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        	</div>
        </div>
	</form>
	<div id="divPrint">
	
		<style>
			ul.title-report {
				list-style: none;
				margin: 0;
				padding: 0;
			}
			th,td{ padding:0 1px; color:#4839bd;}
			table{ border-collapse:collapse; margin:0 auto;border-color:#4839bd; }
			.padding{ padding: 0 1px !important;}
			
			table.content-data{ page-break-inside:auto;font-family:'Times New Roman','Khmer OS Battambang'; }
			table.content-data tr{ page-break-inside:avoid; page-break-after:auto }
			
			#header {display: table-header-group;page-break-inside:avoid; page-break-after:auto;}
			.hover:hover{background: #ccc;}
			.hidden{display: none;}
			tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
			
			table.content-data-main{
				border-collapse:collapse;
				width:100%;
				
				font-family:'Times New Roman','Khmer OS Battambang';
				
				white-space: nowrap;
				margin:0 auto;
				color:#4839bd;
			}
			table.content-data{
				border-collapse:collapse;
				width:100%;
				border:1px solid #4839bd; 
				font-family:'Times New Roman','Khmer OS Battambang';
				font-size:13px;
				white-space: nowrap;
				margin:0 auto;
				color:#4839bd;
			}
			table.content-data-main tr.style-head,
			table.content-data thead tr.style-head {
			   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #ccd9ff;
				text-align: center;
			}
			table.content-data-main tr.style-rowdata td,
			table.content-data-main tr.style-head td {
				border: solid 1px;
			}

			table.content-data tr.style-rowdata {
				font-size:12px; 
				height: 23px;
			}
			#BrowserPrintDefaults{display:none}
		</style>
		
		<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr class="line"><td colspan="3"></td></tr>
			<tr>
				<td width="15%" align="center">
				</td>
				<td width="70%"  align="center">
					<ul class="title-report">
						<li>
							<span style=" font-weight:200; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("ALL_STUDENT_REPORT");?></span>
						</li>
						<?php if(!empty($this->search['start_date'])){?>
							<li><span style=" font-weight:200; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo date('d-M-Y',strtotime($this->search['start_date']));?> <?php echo $tr->translate("TO");?> <?php echo date('d-M-Y',strtotime($this->search['end_date']));?></span></li>
						<?php }?>
					</ul>
				</td>
				<td width="15%" align="center"></td>
			</tr>
		
			<tr>
				<td colspan="3" valign="top">
					<div id="exportExcel">
							<div id="exportExcel">
								<table class="content-data-main" cellpadding="2"​ border="0" >
								<?php $i=0;$degree="";$count=0; $grade="";
									$all_total = 0;$all_drop = 0; $all_female=0; $all_femaledrop=0;
									$female=0;$male=0;
									if(!empty($this->rs))foreach ($this->rs AS $key=>$row) { 
									if($row['is_subspend']!=0){
										$all_drop = $all_drop+1;
										if ($row['sex_key']==2){
											$all_femaledrop++;
										}
									}else{
										$all_total = $all_total+1;
										if ($row['sex_key']==2){ $all_female++;}
									}
								?>
									<?php if($grade!=$row['grade']){?>
										<?php if ($key>0){?>
										<tr>
											<td colspan="14" style="border-left: 1px solid #fff; border-right: 1px solid #fff;">
												<table cellpadding="0" cellspacing="0" width="50%" style="color:#4839bd; font-family:'Times New Roman','Khmer OS Battambang';font-size: 12px;white-space:nowrap;">
													<tr>
														<td valign="top" style="width:33%;">
															<span>
																<?php echo $tr->translate("STUDENT_TOTAL");?> : <?php echo str_pad($count, 2, '0', STR_PAD_LEFT); $male=$count-$female; $count=0;$i=0;?> <?php echo $tr->translate("STUDENT_UNIT");?>
															</span> 
														</td>
														<td  valign="top" style="width:33%; text-align: center;">
															<span>
																<?php echo $tr->translate("FEMALE");?> : <?php echo str_pad($female, 2, '0', STR_PAD_LEFT)." ".$tr->translate("STUDENT_UNIT"); $female=0;?>
															</span> 
														</td>
														<td  style="width:33%;white-space: nowrap;" valign="top">
															<span style=" text-align: center;">
																<?php echo $tr->translate("MALE");?> : <?php echo str_pad($male, 2, '0', STR_PAD_LEFT);?> <?php echo $tr->translate("STUDENT_UNIT");?>
															</span> 
														</td>
													</tr>
												</table>
											</td>
										</tr>
										<tr><td colspan="14" style="">&nbsp;</td></tr>
										<?php }?>
											<tr style="border:0px solid #fff;">
												<td colspan="14" valign="top">
													<table width="100%" class="line-height" style="color:#4839bd; white-space: nowrap;line-height: 19px;font-size: 12px;">
														<tr>
															<td width="10%" ><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
															<td width="15%" ><?php echo $row['academic_year'];?></td>
															<td width="75%"></td>
														</tr>
														<tr>
															<td ><?php echo $tr->translate("DEGREE");?></td>
															<td ><?php echo $row['degree'];?></td>
															<td width="75%"></td>
														</tr>
														<tr>
															<td ><?php echo $tr->translate("GRADE");?></td>
															<td ><?php echo $row['grade'];?></td>
															<td width="75%"></td>
														</tr>
														<tr>
															<td ><?php echo $tr->translate("SESSION");?></td>
															<td ><?php echo $row['session'];?></td>
															<td width="75%"></td>
														</tr>
													</table>
												</td>
											</tr>
											<tr class="style-head" align="center" >
												<td scope="col">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
												<td scope="col">&nbsp;<?php echo $tr->translate("STUDENT_CODE");?>&nbsp;</td>
												<td scope="col">&nbsp;<?php echo $tr->translate("STUDENT_NAMEKHMER");?>&nbsp;</td>
												<td scope="col">&nbsp;<?php echo $tr->translate("NAME_ENGLISH");?>&nbsp;</td>
												<td scope="col">&nbsp;<?php echo $tr->translate("SEX");?>&nbsp;</td>
												<td scope="col">&nbsp;<?php echo $tr->translate("DOB");?>&nbsp;</td>
												<td scope="col">&nbsp;<?php echo $tr->translate("STATUS");?>&nbsp;</td>
											</tr>
									<?php }?>
									<?php $i++;$count++; if ($row['sex_key']==2){ $female++;}?>
									<tr class="style-rowdata hover" align="center" >
										<td  data-label="<?php echo $tr->translate("NUM");?>" >&nbsp;<?php echo $i;?>&nbsp;</td>
										<td  data-label="<?php echo $tr->translate("STUDENT_CODE");?>" >&nbsp;<?php echo $row['stu_code'];?></td>
										<td  data-label="<?php echo $tr->translate("STUDENT_NAMEKHMER");?>" align="left">&nbsp;&nbsp;&nbsp;<?php echo $row['stu_khname'];?>&nbsp;</td>
										<td  data-label="<?php echo $tr->translate("NAME_ENGLISH");?>" align="left">&nbsp;&nbsp;&nbsp;<?php echo $row['name'];?>&nbsp;</td>
										<td  data-label="<?php echo $tr->translate("SEX");?>" >&nbsp;<?php echo $row['sex'];?>&nbsp;</td>	
										<td  data-label="<?php echo $tr->translate("DOB");?>" >&nbsp;<?php echo date("d-m-Y",strtotime($row['dob']));?>&nbsp;</td>
										<td  data-label="<?php echo $tr->translate("STATUS");?>" <?php if($row['is_subspend']!=0){echo 'style="color: red;"';}?>>&nbsp;<?php echo $row['status'];?>&nbsp;</td>	
									</tr>
									<?php $grade=$row['grade'];?>
								<?php }?>	
									<tr>
										<td colspan="14" style="border-left: 1px solid #fff; border-right: 1px solid #fff;">
										</td>
									</tr>
									<tr>
											<td colspan="14" style="border-left: 1px solid #fff; border-right: 1px solid #fff;">
												<table cellpadding="0" cellspacing="0" width="50%" style="color:#4839bd; font-family:'Times New Roman','Khmer OS Battambang';font-size: 12px;white-space:nowrap;">
													<tr>
														<td valign="top" style="width:33%;">
															<span>
																<?php echo $tr->translate("STUDENT_TOTAL");?> : <?php echo str_pad($count, 2, '0', STR_PAD_LEFT); ?> <?php echo $tr->translate("STUDENT_UNIT");?>
															</span> 
														</td>
														<td  valign="top" style="width:33%; text-align: center;">
															<span>
																<?php echo $tr->translate("FEMALE");?> : <?php echo str_pad($female, 2, '0', STR_PAD_LEFT)." ".$tr->translate("STUDENT_UNIT"); ?>
															</span> 
														</td>
														<td  style="width:33%;white-space: nowrap;" valign="top">
															<span style=" text-align: center;">
																<?php echo $tr->translate("MALE");?> : <?php echo str_pad($male, 2, '0', STR_PAD_LEFT);?> <?php echo $tr->translate("STUDENT_UNIT");?>
															</span> 
														</td>
													</tr>
												</table>
											</td>
										</tr>
								</table>	
								<table border="0" align="right" width="60%" style="color:#4839bd; font-size:12px;font-family:'Times New Roman','Khmer OS Battambang'; margin:0 auto; white-space:nowrap;">
									<tr>
										<td width="15%" >
											<?php echo $tr->translate("TOTAL_STUDYING_STUDENT");?>
										</td>
										<td width="15%" >
											: <?php echo $all_total;?> <?php echo $tr->translate("STUDENT_UNIT");?>
										</td>
										<td width="15%" align="right">
											<?php echo $tr->translate("FEMALE");?>
										</td>
										<td width="15%" >
											: <?php echo $all_female;?> <?php echo $tr->translate("STUDENT_UNIT"); ?>
										</td>
										<td width="15%" align="right">
											<?php echo $tr->translate("MALE");?>
										</td>
										<td width="15%" >
											: <?php echo $all_total-$all_female;?> <?php echo $tr->translate("STUDENT_UNIT");?>
										</td>
									</tr>
									<tr>
										<td>
											<?php echo $tr->translate("TOTAL_STOP_STUDENT");?>
										</td>
										<td>
											: <?php echo $all_drop?> <?php echo $tr->translate("STUDENT_UNIT");?>
										</td>
										<td align="right">
											<?php echo $tr->translate("FEMALE");?>
										</td>
										<td>
											: <?php echo $all_femaledrop;?> <?php echo $tr->translate("STUDENT_UNIT"); ?>
										</td>
										<td align="right">
											<?php echo $tr->translate("MALE");?>
										</td>
										<td>
											: <?php echo $all_drop-$all_femaledrop;?> <?php echo $tr->translate("STUDENT_UNIT");?>
										</td>
									</tr>
								</table>
							</div>	
							</td>
						</tr>
						<tr>
							<td colspan="3">&nbsp;</td>
						</tr>
						<tr>
							<td colspan="3">&nbsp;</td>
						</tr>
						<tr>
							<td colspan="3" style="border:1px solid #fff;">
							  <?php  echo $this->rsfooter; ?>
				
							</td>
						</tr>
					</table>
					
				</div>	
				</td>
			</tr>
			
		</table>
	</div>
</div>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 

dojo.require("dojo.html");
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
		    
	    }
	}, "group");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                        
		id: "grade",
		name: "grade",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  

		}
	}, "grade");
	var branch_id = dijit.byId('branch_id');
	branch_id.on('change', function(evt) {
		 getAllGroupByBranch();
  	});
	var academic_year = dijit.byId('academic_year');
	academic_year.on('change', function(evt) {
		getAllGroupByBranch();
  	});
	 getAllGroupByBranch();
	 getallGrade();
});
var oldBranch = '<?php echo $this->search['branch_id']?>'
url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	degree = dijit.byId('degree').get('value');
	if(degree=='' || degree==-1){degree ="";}
	grade = dijit.byId('grade').get('value');
	if(grade=='' || grade==-1){grade ="";}
	academic_year = dijit.byId('academic_year').get('value');
	if(academic_year=='' || academic_year==-1){academic_year ="";}
	
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,
			'degree':degree,
			'grade':grade,
			'academic_year':academic_year,
			'noaddnew':1,
			'forfilter':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
		}
	});
}

var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(){
	getAllGroupByBranch();  
	dept_id = dijit.byId('degree').get('value');
	if(dept_id=='' || dept_id==-1){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store); 
			    dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');  
			},
			error: function(err) {
			}
		});
}
</script>