<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('STUDENT_ATTENDENCE')); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
	$db = new Allreport_Model_DbTable_DbRptAllStudent();
	$start_date = $this->search['start_date'];
	$end_date = $this->search['end_date'];
	$date1 = date("d-m-Y",strtotime($start_date));
	$date2 = date('d-m-Y',strtotime($end_date));
	$diff = abs(strtotime($date2) - strtotime($date1));
	$years = floor($diff / (365*60*60*24));
	$months = floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
	$days = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
	$amount_day =$diff/ (60*60*24);
	$amount_day = $amount_day + 1;
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
?>	
<style>
.hover:hover{ background:#ccc;}</style>
<div style="margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_ATTENDENCE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-attendence')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<script type="dojo/method" event="onSubmit">
			if(this.validate()) {
                start_date=dijit.byId("start_date").get("value");
                if(start_date=='' || start_date==null){
					alert("Please select start date");
					dijit.byId("start_date").focus();
                    return false;
				}
				return true;
			}else {
				return false;
			}
		</script>
		<div class="card-box">
			<div class="form-group">
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<?php echo $frm->getElement("title");?>
            	</div>
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<?php echo $frm->getElement("branch_id");?>
            	</div>
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<input id="study_year" />
            	</div>
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<input id="group" />
            	</div>
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<?php echo $frm->getElement("degree");?>
            	</div>
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<input id="grade_all" />
            	</div>
            </div>
            <div class="form-group">
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<?php echo $frm->getElement("start_date");?>
            	</div>
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<?php echo $frm->getElement("end_date");?>
            	</div>
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
            	</div>
            	<div class="col-md-2 col-sm-2 col-xs-12"></div>
            	<div class="col-md-2 col-sm-2 col-xs-12"></div>
            	<div class="col-md-2 col-sm-2 col-xs-12"></div>
            </div>
         </div>
	</form>
	
	<div id="divPrint">
		<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
			<style>
				table tr th{
					border: 1px solid #000;	
				}	
				.style{
					line-height: 20px; font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				 td.rotate {
				  height: 120px;
    				vertical-align: bottom;
				}				
				td.rotate > div {
				  transform: rotate(270deg);
					width: 15px;
				}
				 td.rotate span{
				    white-space: nowrap;
				    overflow: hidden;
				    text-overflow: ellipsis;
				    display: inline-block;
				    /* max-width: 130px; */
				}
				table {page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}				
				tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
			</style>			
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td colspan="3">
					<div id="exportExcel">
						<table cellpadding="5"​ style="font-family:'Khmer OS Battambang' ; margin:0 auto;width:100%;border:1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<thead>
							<?php $i=0; $old_groupid=0;if (!empty($this->student))foreach ($this->student as $key => $rs){
								if ($rs['sex']==1){$sex = $tr->translate("MALE");}else{$sex = $tr->translate("FEMALE");}
							?>
							<?php if ($old_groupid!=$rs['group_id']){ ?>
							<?php if ($key>0){ 
							?>					
							<tr>
								<td align="right" colspan="<?php echo $amount_day+7;?>" style=" border: 1px solid #fff; border-top: 1px solid #000;">
									<span​​ style="color:#000; font-size: 12px;font-family: 'Times New Roman','Khmer OS Battambang';">
									<?php echo $tr->translate("TOTAL_STUDENT");?> : <span>&nbsp;<strong><?php echo $i;?></strong> <?php echo $tr->translate("STUDENT_UNIT");?>&nbsp;</span> 
									</span>
								</td>
							</tr>
							<?php }$i=0; ?>
							<tr>
								<td align="center" colspan="<?php echo $amount_day+9;?>" style=" border-top: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
									<strong style="font-weight:200;color:#000; font-size: 12px;font-family: 'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("STUDENT_ATTENDENCE");?></strong><br />
								</td>
							</tr>
							<tr>
								<td align="left" colspan="<?php echo $amount_day+9;?>" style=" border-top: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
									<table width="50%" style="white-space:nowrap;line-height:20px;font-size:12px;font-family: 'Times New Roman','Khmer OS Battambang';">
										<tr>
											<td width="30%"><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
											<td width="70%">: <?php echo $rs['academic_year'];?></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("GROUP");?></td>
											<td>: <?php echo $rs['group_code'];?></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("ROOM_NAME");?></td>
											<td>: <?php echo $rs['room_name'];?></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("SESSION");?></td>
											<td>: <?php echo $rs['session'];?></td>
										</tr>
									</table>
								</td>
							</tr>
							</thead>
							<tr style="font-size:12px; line-height: 18px; background: #ccd9ff; " align="center" >
								<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
								<td rowspan="2"><?php echo $tr->translate("STUDENT_CODE");?></td>
								<td rowspan="2"><?php echo $tr->translate("STUDENT_NAMEKHMERWORD");?></td>
								<td rowspan="2"><?php echo $tr->translate("NAME_ENGLISH");?></td>
								<td rowspan="2" ><?php echo $tr->translate("SEX");?></td>
								<?php for($k=0;$k<$amount_day;$k++){?>
									<?php if(date('D',strtotime(" $start_date+$k day"))=="Sun"){}else{ $date = date('d-m-Y',strtotime("$start_date +$k day")); // $tr->translate(date("D",strtotime($date)));?>
										<td rowspan="2" style="font-family: 'Times New Roman','Khmer OS Battambang';" class="rotate"><div><span><?php  echo date("D d-M-Y",strtotime($date));?></span></div></td>
									<?php }?>
								<?php }?>
								<td colspan="4" style="font-family: 'Times New Roman','Khmer OS Muol Light';">&nbsp;<?php echo $tr->translate("TOTAL_ATTENDENCE");?>&nbsp;</td>
							</tr>
							<tr style="font-size:12px; line-height: 18px; font-family: 'Times New Roman','Khmer OS Muol Light'; " align="center">
								<td style="width: 30px;">&nbsp;<?php echo $tr->translate("ABSENT");?>&nbsp;</td>
								<td style="width: 30px;">&nbsp;<?php echo $tr->translate("PERMISSION");?>&nbsp;</td>
								<td style="width: 30px;">&nbsp;<?php echo $tr->translate("LATE");?>&nbsp;</td>
								<td style="width: 30px;">&nbsp;<?php echo $tr->translate("EARLY_LEAVE");?>&nbsp;</td>
							</tr>
							
							<?php } $i++;?>
							<tr class="style">
								<td align="center">&nbsp;<?php echo $i;?>&nbsp;</td>
								<td align="center" style="white-space:nowrap;">&nbsp;<?php echo $rs['stu_code'];?>&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $rs['stu_khname'];?>&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $rs['last_name']." ".$rs['stu_enname'];?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo $sex;?>&nbsp;</td>
								<?php $p=0; $a=0;$l=0;$el=0; for($k=0;$k<$amount_day;$k++){?>
									<?php if(date('D',strtotime(" $start_date+$k day"))=="Sun"){}else{ //$date = date('d-m-Y',strtotime("$start_date +$k day"));?>
										<td align="center" >
										<?php  $check_date = $db->checkDateAttendence(date('Y-m-d',strtotime("$start_date +$k day")), $rs['group_id']);
											if (!empty($check_date)){
												$attentence_status = $db->getStatusAttendence($rs['stu_id'], date('Y-m-d',strtotime("$start_date +$k day")), $rs['group_id']);
												if ($attentence_status['attendence_status']==2){ 
													echo "A"; $a=$a+1;
												}
												else if ($attentence_status['attendence_status']==3){
													echo "P"; $p = $p+1;
												}
												else if ($attentence_status['attendence_status']==4){
													echo "L"; $l = $l+1;
												}
												else if ($attentence_status['attendence_status']==5){
													echo "EL"; $el = $el+1;
												}
												else{ echo "&#10004;";}
											}
										?>
										</td>
									<?php }?>
								<?php }?>
								<td align="center"><?php echo $a;?></td>
								<td align="center"><?php echo $p;?></td>
								<td align="center"><?php echo $l;?></td>
								<td align="center"><?php echo $el;?></td>
							</tr>
							<?php $old_groupid = $rs['group_id'];
							}?>
							<tr>
								<td align="right" colspan="<?php echo $amount_day+7;?>" style=" border-bottom: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
									<span style="font-family: 'Times New Roman','Khmer OS Muol Light';font-weight:200;color:#000; font-size: 12px;">
									<?php echo $tr->translate("TOTAL_STUDENT");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';">&nbsp;<strong><?php echo $i ?></strong> <?php echo $tr->translate("STUDENT_UNIT");?>&nbsp;</span> 
									</span><br />
								</td>
							</tr>
						</table>	
					</div>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr style="font-size: 12px;">
					<td colspan="3">
						<span style="color: red;">Note:</span>
						A = Absent , P = Permission , L = Late , EL = Early Leave
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3" style="border:1px solid #fff;">
						<table cellpadding="0" cellspacing="0" width="100%" style="color:#4839bd; font-size: 12px;font-family:'Times New Roman','Khmer OS Battambang';">
							<tr>
								<td width="35%" align="center">
									<span><?php echo $tr->translate("CHECKANDAPPROVED");?></span><br />
									<span style="font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("PRINCIPAL");?></span>
								</td>
								<td width="30%">&nbsp;</td>
								<td width="35%" align="center">
									<span><?php echo $tr->translate("CREATE_WORK_DATE");?></span><br />
									<span style="font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("PREPARE_BY");?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
//dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.FilteringSelect"); 

dojo.require("dojo.html");
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
		    
	    }
	}, "group");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                        
		id: "grade_all",
		name: "grade_all",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  

		}
	}, "grade_all");
	getallGrade();
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
    });
	 getAllAcademicByBranch();
	 getAllGroupByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id==''){return false;}
	dojo.xhrPost({
		url:url_dept,
		content:{
			'dept_id':dept_id
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('grade_all').set('store',grade_store);   
			dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>