<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RPT_STUDENT_STATISTIC")); 
	$frm =  $this->form_search;
	$dbst = new Allreport_Model_DbTable_DbRptAllStudent();
?>	
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_STUDENT_STATISTIC');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
		<form id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-student-statistic')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					<div class="col-md-3 col-sm-3 col-xs-12">
	            		<?php echo $frm->getElement("allacademicyear");?>
	            	</div>
	            	<div class="col-md-3 col-sm-3 col-xs-12">
	            		<?php echo $frm->getElement("branch_id");?>
	            	</div>
	            	<div class="col-md-3 col-sm-3 col-xs-12">
	            		<input id="study_year" />
	            	</div>
	            	<div class="col-md-3 col-sm-3 col-xs-12">
	            		<?php echo $frm->getElement("degree");?>
	            	</div>
	            </div>
	            <div class="form-group">
	            	<div class="col-md-3 col-sm-3 col-xs-12">
	            		<input id="grade_all" />
	            	</div>
	            	<div class="col-md-3 col-sm-3 col-xs-12">
	            		<?php echo $frm->getElement("session");?>
	            	</div>
	            	<div class="col-md-3 col-sm-3 col-xs-12">
	            			<?php echo $frm->getElement("study_status");?>
	            	</div>
	            	<div class="col-md-3 col-sm-3 col-xs-12">
		            		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
		            </div>
            	</div>
		</form>
	<div id="divPrint">
		<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr class="line"><td colspan="3"></td></tr>
			<tr>
				<td width="15%" align="center">
				</td>
				<td width="70%"  align="center">
					<span style=" color:#4839bd; font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("RPT_STUDENT_STATISTIC");?></span><br />
					<span style=" color:#4839bd; font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php if (!empty($this->search['allacademicyear'])){ echo $tr->translate("STUDY_YEAR")." ".$this->search['allacademicyear'];}?></span>
				</td>
				<td width="15%" align="center">
				</td>
			</tr>
		<style>
			table tr th{
				border: 1px solid #000;	
				text-align: center;
				padding: 3px 2px;
			}
			table {page-break-inside:auto }
			tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
			
			table.content-data{
				border-collapse:collapse;
				width:100%;
				border:1px solid #4839bd; 
				font-family:'Times New Roman','Khmer OS Battambang';
				font-size:13px;
				white-space: nowrap;
				margin:0 auto;
				color:#4839bd;
				margin:0 auto;
			}
			table.content-data thead tr.style-head {
			   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 20px; 
				background: #ccd9ff;
				text-align: center;
			}
			table.content-data tr.style-rowdata {
				font-size:12px; 
				height: 23px;
			}
		</style>
			<tr>
				<td colspan="3" valign="top">
				<div id="exportExcel">
				<?php if (!empty($this->rs)){?>
					<table class="content-data" cellpadding="1"​  border="1" >
						<thead>
							<tr class="style-head">
								<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
								<td colspan="9"><?php echo $tr->translate("STUDY_INFO");?>
									<input type="hidden" name="id_selected" id="id_selected" dojoType="dijit.form.TextBox" />
								</td>
							</tr>
							<tr class="style-head">
								<td><?php echo $tr->translate("BRANCH");?></td>
								<td><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
								<td><?php echo $tr->translate("DEGREE");?></td>
								<td><?php echo $tr->translate("GRADE");?></td>
								<td><?php echo $tr->translate("SESSION");?></td>
								<td><?php echo $tr->translate("AMOUNT_STUDENT");?></td>
								<td><?php echo $tr->translate("NEW_STUDENT");?></td>
								<td><?php echo $tr->translate("STUDENT_DROP");?></td>
								<td><?php echo $tr->translate("STUDENT_STUDY");?></td>
							</tr>
						</thead>
					<?php $i=0;
					$total_amount_student = 0;
					$total_amount_student_new = 0;
					$total_amount_student_drop=0;
					$total_studying=0;
						foreach($this->rs AS $key=>$row){  
							
							$studyng = $dbst->getCountStuBYtype($row['branch_id'], $row['academic_year'], $row['degree'], $row['grade'], $row['session']);
							$stop = $dbst->getCountStuBYtype($row['branch_id'], $row['academic_year'], $row['degree'], $row['grade'], $row['session'],1);
							$newstu = $dbst->getCountStuBYtype($row['branch_id'], $row['academic_year'], $row['degree'], $row['grade'], $row['session'],1,1);
							$totalstu = $row['total_stu'];
							
							$total_amount_student=$total_amount_student+$totalstu;
							$total_amount_student_new=$total_amount_student_new+$newstu;
							$total_amount_student_drop=$total_amount_student_drop+$stop;
							$total_studying = $total_studying+$studyng;
					?>
						<tr class="style-rowdata hover" align="center"  >
							<td><?php echo ++$i;?></td>
							<td align="left">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
							<td align="left">&nbsp;<?php echo $row['academic_year_name'];?>&nbsp;</td>
							<td align="left">&nbsp;<?php echo $row['degree_name'];?></td>
							<td align="left">&nbsp;<?php echo $row['grade_name'];?></td>
							<td><?php echo $row['session_name'];?></td>
							<td><?php echo $totalstu." ".$tr->translate("STUDENT_UNIT");?></td>	
							<td><?php echo $newstu." ".$tr->translate("STUDENT_UNIT");?></td>	
							<td><?php echo $stop." ".$tr->translate("STUDENT_UNIT");?></td>	
							<td><?php echo $studyng." ".$tr->translate("STUDENT_UNIT");?></td>	
						</tr>
						<?php } ?>	
						<tr align="center" class="hover" style="bold;height:30px;font-size:15px;">
							<td colspan="6"><?php echo $tr->translate("TOTAL");?></td>
							<td><?php echo $total_amount_student." ".$tr->translate("STUDENT_UNIT");;?></td>	
							<td><?php echo $total_amount_student_new." ".$tr->translate("STUDENT_UNIT");?></td>	
							<td><?php echo $total_amount_student_drop." ".$tr->translate("STUDENT_UNIT");?></td>
							<td><?php echo $total_studying." ".$tr->translate("STUDENT_UNIT");?></td>
						</tr>
					</table> 
					<?php }?>
				</div>	
				</td>
			</tr>
			<tr >
				<td colspan="3" width="100%">
					<table width="100%" style="color:#4839bd; font-size: 12px;font-family:'Times New Roman','Khmer OS Battambang';">
						<tr>
							<td  width="25%" align="center">
								<span style="font-size: 14px;font-family:'Times New Roman','Khmer OS Battambang';"><?php echo $tr->translate("CHECKANDAPPROVED");?></span><br />
								<span style="font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("PRINCIPAL");?></span>
							</td>
							<td  width="50%">&nbsp;</td>
							<td align="center"  width="25%">
								<span ><?php echo $tr->translate("CREATE_WORK_DATE");?></span><br />
								<span style="font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate('PREPARED_BY')?></span>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 

dojo.require("dojo.html");
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                        
		id: "grade_all",
		name: "grade_all",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
		
		}
	}, "grade_all");
	getallGrade();
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
    });
	 getAllAcademicByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id,'showall':1
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
		    }
		},
		error: function(err) {
		}
	});
}
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id==''){return false;}
	dojo.xhrPost({
		url:url_dept,
		content:{
			'dept_id':dept_id,
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('grade_all').set('store',grade_store);   
			dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
		},
		error: function(err) {
		}
	});
}
</script>