<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('RPT_STUDENT_LIST'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<style>
.hide{visibility:visible !important;
}
</style>
<div style="width: 28cm;margin: 0 auto;">
</div>
<div style="border: 1px dotted #000;background: #fff;min-width: 28cm;margin: 0 auto;min-height: 27cm;">
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-student-list')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table>
			<tr>
				<td><input dojoType="dijit.form.TextBox" id="txtsearch" name="txtsearch" placeholder="Search by student name....." value="" type="text"></td>
				<td>
					<select dojoType="dijit.form.FilteringSelect" id="study_type" name="study_type">
						<option value="">ជ្រើសរើសប្រភេទសិស្ស</option>
						<option value="1" <?php if($this->search['study_type']==1){echo "selected";}?>>សិស្សនៅរៀន</option>
						<option value="2" <?php if($this->search['study_type']==2){echo "selected";}?>>សិស្សឈប់</option>
					</select>
				</td>
				<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			</tr>
		</table>
	</form>
	<div id="divPrint">
		<form action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'submitlist')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table style="background:#fff; margin: 0 auto; width: 100%;" >
				<tr>
					<td></td>
					<td align="center">
						<strong style="font-weight:bold;color:#000; font-size: 16px;font-family:Arial,'Khmer MEF2';"><?php echo $tr->translate("NATIONALITY_OFKINGDOM");?></strong><br />
						<strong style="font-weight:bold;color:#000; font-size: 16px;font-family:Arial,'Khmer MEF2';"><?php echo $tr->translate("NATION_RELIGION_KING");?></strong>
					</td>
					<td></td>
				</tr>
				<tr>
					<td style="width:200px;">
						<img style="max-height:100px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
					</td>
					<td align="center" >
						<strong style="font-weight:bold;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("STUDENT_LIST_REPORT");?></strong><br />
						<strong style="font-weight:bold;color:#000; font-size: 12px;font-family:'Khmer MEF2';white-space: nowrap;"><?php echo $tr->translate("ACADEMIC_YEAR");?> : <?php echo $this->rr['academic'];?><?php echo ", ".$tr->translate("DEGREE");?> : <?php echo $this->rr['degree'];?> <?php echo ','.$tr->translate("GRADE");?> : <?php echo $this->rr['grade'];?> </strong><br />
						<strong style="font-weight:bold;color:#000; font-size: 12px;font-family:'Khmer MEF2';"><?php echo $tr->translate("SESSION");?> : <?php echo $this->rr['session'];?> <?php echo ','.$tr->translate("CLASSES");?> : <?php echo $this->rr['room_name'];?><?php echo ", ".$tr->translate("STUDY_GROUP");?> : <?php echo $this->rr['group_code'];?> </strong><br />
					</td>
					<td style="width:200px;"></td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
						<table  cellpadding="5"​ style="font-size:14px; margin:0 auto;width:100%; border-collapse: collapse;border:1px solid #000; white-space: nowrap;"  border="1" >
							<style> td{padding:0 3px; }
							.cheader{font-weight: bold; background: #ccc; white-space: nowrap;}
							table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
							tr{ page-break-inside:avoid; page-break-after:auto }
							#header {
							  display: table-header-group;
							  page-break-inside:avoid; page-break-after:auto;
							}
							
							</style>
							<thead>
								<tr class="cheader" align="center" >
									<td><?php echo $tr->translate("NUM");?></td>
									<td><?php echo $tr->translate("STUDENT_ID");?></td>
									<td><?php echo $tr->translate("STUDENT_NAMEKHMER");?></td>
									<td><?php echo $tr->translate("NAME_ENGLISH");?></td>
									<td><?php echo $tr->translate("SEX");?></td>
									<td><?php echo $tr->translate("NATIONALITY");?></td>
									<td><?php echo $tr->translate("DATE_OF_BIRTH");?></td>	
									<td><?php echo $tr->translate("POB");?></td>
									<td><?php echo $tr->translate("CONTACT_NO");?></td>	
									<td><?php echo $tr->translate("FATHER_NAME");?></td>	
									<td><?php echo $tr->translate("OCCUPATION");?></td>	
									<td><?php echo $tr->translate("MOTHER_NAME");?></td>	
									<td><?php echo $tr->translate("OCCUPATION");?></td>	
								</tr>
							</thead>
							<?php  $i=0;
							    $str='';
								$male=0;$femle=0;
							foreach ($this->rs as $key=> $row){ $i++;
							if($key==0){
								$str=$key+1;
							}else{
								$str.=",".($key+1);
							}
							?>
							<tr style="font-size:14px;height: 23px;"​ align="center">
								<td><?php echo $i;?></td>
								<td><?php echo $row['stu_code'];?></td>
								<td align="left"><?php echo $row['kh_name'];?></td>
								<td align="left"><?php echo $row['en_name'];?></td>
								<td><?php echo $row['sex'];
									if($row['gender']==1){
										$male=$male+1;
									}else{
										$femle=$femle+1;
									}
								?></td>
								<td><?php echo $row['nation'];?></td>
								<td><?php echo date("Y",strtotime($row['dob']))!=1970?date("d-m-Y",strtotime($row['dob'])):"";?></td>
								<td style="text-align: left;"><?php echo $row['pob'];?></td>
								<td><?php echo $row['tel'];?></td>
								<td align="left">&nbsp;<?php echo $row['father_name'];?></td>
								<td align="left">&nbsp;<?php echo $row['father_job'];?></td>
								<td align="left">&nbsp;<?php echo $row['mother_name'];?></td>
								<td align="left">&nbsp;<?php echo $row['mother_job'];?></td>
							</tr>
							<?php }?>	
							<tr>
								<td colspan="2" style="border:1px solid #fff;border-top:1px solid #000;"><strong style="font-weight:bold;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("STUDENT_TOTAL")." : ".$i." ".$tr->translate("STUDENT_UNIT");?></strong></td>
								<td colspan="8" style="border:1px solid #fff;border-top:1px solid #000;"><strong style="font-weight:bold;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("FEMALE")." ".$femle;?> <?php echo $tr->translate("STUDENT_UNIT")."  <br />";?><?php echo $tr->translate("MALE")." ".$male;?><?php echo $tr->translate("STUDENT_UNIT");?></strong></td>
							</tr>
							<tr>
								<td colspan="3" style="text-align:center;border:1px solid #fff;border-top:1px solid #000;"><strong style="color:#000; font-size: 14px;font-family:'khmer os battambang';"><?php echo $tr->translate("CHECKANDAPPROVED");?></strong><br />
									<strong style="font-weight:bold;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("PRINCIPAL");?></strong>
								</td><td colspan="5" style="border:1px solid #fff;"></td>
								<td colspan="2" style="text-align:right;border:1px solid #fff;text-align: center;"><strong style="color:#000; font-size: 14px;font-family:'khmer os battambang';">ភ្នំពេញ.ថ្ងៃទី.........ខែ..........ឆ្នាំ.....</strong><br />
								<strong style="font-weight:bold;color:#000; font-size: 14px;font-family:'Khmer MEF2';">គ្រូប្រចាំថ្នាក់</strong>
								</td>
							</tr>
						</table>	
					</td>
				</tr>
		</table>
		</form>
	</div>
</div>