<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('របាយការណ៏ សិស្ស'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
	$db = new Allreport_Model_DbTable_DbRptAllStudent();
	$start_date = $this->datasearch['start_date'];
	$end_date = $this->datasearch['end_date'];
	$date1 = date("d-m-Y",strtotime($start_date));
	$date2 = date('d-m-Y',strtotime($end_date));
	$diff = abs(strtotime($date2) - strtotime($date1));
	$years = floor($diff / (365*60*60*24));
	$months = floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
	$days = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
	$amount_day =$diff/ (60*60*24);
	$amount_day = $amount_day + 1;
	
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
	
?>	
<style>
.hover:hover{ background:#ccc;}</style>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-attendence')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<script type="dojo/method" event="onSubmit">
			if(this.validate()) {
                start_date=dijit.byId("start_date").get("value");
                if(start_date=='' || start_date==null){
					alert("Please select start date");
					dijit.byId("start_date").focus();
                    return false;
				}
				return true;
			}else {
				return false;
			}
		</script>
			<table width="100%">
		       <tr>
		           <td><?php echo $frm->getElement("title");?></td>
		           <td><?php echo $frm->getElement("branch_id");?></td>
		           <td><?php echo $frm->getElement("study_year");?></td>
		           <td><?php echo $frm->getElement("group");?></td>
		           <td><?php echo $frm->getElement("degree");?></td>
		           <td><?php echo $frm->getElement("grade_all");?></td>
				</tr>
				<tr>
					<td><?php echo $frm->getElement("start_date");?></td>
					<td><?php echo $frm->getElement("end_date");?></td>
					<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	
			 	</tr>
			</table>		
	</form>
</div>
<div id="divPrint">
		<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
			<style>
				table tr th{
					border: 1px solid #000;	
				}	
				.style{
					line-height: 20px; font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				 td.rotate {
				  height: 120px;
    				vertical-align: bottom;
				}				
				td.rotate > div {
				  transform: rotate(270deg);
					width: 20px;
				}
				 td.rotate span{
				    white-space: nowrap;
				    overflow: hidden;
				    text-overflow: ellipsis;
				    display: inline-block;
				    /* max-width: 130px; */
				}
				table {page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}				
			</style>			
				<tr>
					<td colspan="3">
					<div id="exportExcel">
						<table cellpadding="5"​ style="font-family:'Khmer OS Battambang' ; margin:0 auto;width:100%;border:1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<thead>
							<?php $i=0; $old_groupid=0;if (!empty($this->student))foreach ($this->student as $key => $rs){
								if ($rs['sex']==1){$sex = $tr->translate("MALE");}else{$sex = $tr->translate("FEMALE");}
							?>
							<?php if ($old_groupid!=$rs['group_id']){ ?>
							<?php if ($key>0){ 
							?>					
							<tr>
								<td align="right" colspan="<?php echo $amount_day+7;?>" style=" border: 1px solid #fff; border-top: 1px solid #000;">
									<strong​​ style="font-weight:bold;color:#000; font-size: 13px;font-family: 'Times New Roman','Khmer OS Battambang';">
									<?php echo $tr->translate("TOTAL_STUDENT");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';">&nbsp;<?php echo $i." ".$tr->translate("STUDENT_UNIT");?>&nbsp;</span> 
								</td>
							</tr>
							<?php }$i=0; ?>
							<tr>
								<td align="center" colspan="<?php echo $amount_day+9;?>" style=" border-top: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
									<!-- <img style="width: 90px;float: left; " alt="<?php ?>" src="<?php //echo $this->baseUrl().'/images/logo.png'?>"> -->
									<strong​​ style="font-weight:bold;color:#000; font-size: 16px;font-family: 'Times New Roman','Khmer MEF2';"><?php echo $tr->translate("STUDENT_ATTENDENCE");?></strong><br />
									<strong​​ style="font-weight:bold;color:#000; font-size: 13px;font-family:'Times New Roman','Khmer MEF2';">
										<?php echo $tr->translate("ACADEMIC_YEAR");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['academic_year'];?></span> ,
										<?php echo $tr->translate("DEGREE");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['degree'];?></span> 
										<?php echo $tr->translate("MONTHLY");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $month[date("m",strtotime($end_date))]." ".date("Y",strtotime($end_date));?></span>
										<br />
										<?php echo $tr->translate("GROUP");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['group_code'];?></span> , 
										<?php echo $tr->translate("GRADE");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['grade'];?></span> , 
									 	<?php //echo $tr->translate("SEMESTER");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php //echo $rs['semester'].",";?></span>  
									 	<?php echo $tr->translate("ROOM_NAME");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['room_name'];?></span> 
									 	, <?php echo $tr->translate("SESSION");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['session'];?></span>
									</strong>
								</td>
							</tr>
							</thead>
							<tr style="font-size:14px; line-height: 18px; background: #ccd9ff; " align="center" >
								<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
								<td rowspan="2"><?php echo $tr->translate("STUDENT_CODE");?></td>
								<td rowspan="2"><?php echo $tr->translate("STUDENT_NAMEKHMERWORD");?></td>
								<td rowspan="2"><?php echo $tr->translate("NAME_ENGLISH");?></td>
								<td rowspan="2"><?php echo $tr->translate("SEX");?></td>
								<?php for($k=0;$k<$amount_day;$k++){?>
									<?php if(date('D',strtotime(" $start_date+$k day"))=="Sun"){}else{ $date = date('d-m-Y',strtotime("$start_date +$k day")); // $tr->translate(date("D",strtotime($date)));?>
										<td rowspan="2"  class="rotate"><div><span><?php  echo date("D d-M-Y",strtotime($date));?></span></div></td>
									<?php }?>
								<?php }?>
								<td colspan="4" style="font-family: 'Times New Roman','Khmer MEF2';">&nbsp;<?php echo $tr->translate("TOTAL_ATTENDENCE");?>&nbsp;</td>
							</tr>
							<tr style="font-size:14px; line-height: 18px; " align="center">
								<td style="width: 30px;font-family: 'Times New Roman','Khmer MEF2';">&nbsp;<?php echo $tr->translate("ABSENT");?>&nbsp;</td>
								<td style="width: 30px;font-family: 'Times New Roman','Khmer MEF2';">&nbsp;<?php echo $tr->translate("PERMISSION");?>&nbsp;</td>
								<td style="width: 30px;font-family: 'Times New Roman','Khmer MEF2';">&nbsp;<?php echo $tr->translate("LATE");?>&nbsp;</td>
								<td style="width: 30px;font-family: 'Times New Roman','Khmer MEF2';">&nbsp;<?php echo $tr->translate("EARLY_LEAVE");?>&nbsp;</td>
							</tr>
							
							<?php } $i++;?>
							<tr class="style">
								<td align="center">&nbsp;<?php echo $i;?>&nbsp;</td>
								<td align="center" style="white-space:nowrap;">&nbsp;<?php echo $rs['stu_code'];?>&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $rs['stu_khname'];?>&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $rs['stu_enname'];?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo $sex;?>&nbsp;</td>
								<?php $p=0; $a=0;$l=0;$el=0; for($k=0;$k<$amount_day;$k++){?>
									<?php if(date('D',strtotime(" $start_date+$k day"))=="Sun"){}else{ //$date = date('d-m-Y',strtotime("$start_date +$k day"));?>
										<td align="center" >
										<?php  $check_date = $db->checkDateAttendence(date('Y-m-d',strtotime("$start_date +$k day")), $rs['group_id']);
											if (!empty($check_date)){
												$attentence_status = $db->getStatusAttendence($rs['stu_id'], date('Y-m-d',strtotime("$start_date +$k day")), $rs['group_id']);
												if ($attentence_status['attendence_status']==2){ 
													echo "A"; $a=$a+1;
												}
												else if ($attentence_status['attendence_status']==3){
													echo "P"; $p = $p+1;
												}
												else if ($attentence_status['attendence_status']==4){
													echo "L"; $l = $l+1;
												}
												else if ($attentence_status['attendence_status']==5){
													echo "EL"; $el = $el+1;
												}
												else{ echo "&#10004;";}
											}
										?>
										</td>
									<?php }?>
								<?php }?>
								<td align="center"><?php echo $a;?></td>
								<td align="center"><?php echo $p;?></td>
								<td align="center"><?php echo $l;?></td>
								<td align="center"><?php echo $el;?></td>
							</tr>
							<?php $old_groupid = $rs['group_id'];
							}?>
							<tr>
								<td align="right" colspan="<?php echo $amount_day+4;?>" style=" border-bottom: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
									<strong​​ style="font-family: 'Times New Roman','Khmer MEF2';font-weight:bold;color:#000; font-size: 13px;">
									<?php echo $tr->translate("TOTAL_STUDENT");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';">&nbsp;<?php echo $i." ".$tr->translate("STUDENT_UNIT");?>&nbsp;</span> 
									</strong><br />
								</td>
							</tr>
						</table>	
					</div>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr style="font-size: 12px;">
					<td colspan="3">
						<span style="color: red;">Note:</span>
						A = Absent , P = Permission , L = Late , EL = Early Leave
					</td>
				</tr>
				<tr >
					<td colspan="3" width="100%">
						<table width="100%" style="font-family:'Khmer OS Battambang';">
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 14px;font-family: 'Times New Roman','Khmer MEF2'"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;font-family: 'Times New Roman','Khmer MEF2'"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
</div>