<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("CRM Daily Contact")); 
	echo $this->headTitle(''); 
// 	$frm =  $this->form_search;
	$frm_items= $this->frm_crm;
?>	
<style>
.hover:hover{ background:#ccc;}</style>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				 <div class="form-group">
                   	<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("advance_search");?>
				 	</div>
				 		<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("branch_search");?>
				 	</div>
				 		<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("crm_list");?>
				 	</div>
				 		<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("ask_for_search");?>
				 	</div>
				 		<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement('status_search');?>
				 	</div>
				 </div>
				 
				 <div class="form-group">
				 		<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("start_date");?>
				 	</div>
				 		<div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm_items->getElement("end_date");?>
				 	</div>
				 		<div class="col-md-2 col-sm-2 col-xs-12">
				 		<button IconClass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				 	</div>
				 </div>
			</form>
		</div>
		<div id="divPrint">
				<table  style="background:#fff; margin: 0 auto; width: 100%; ">
					<tr>
						<td width="20%" align="right">
							<img style="height: 90px" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
						</td>
						<td width="60%" align="center">
						    <strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_BRANCH");?></strong><br />
							<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CRM Daily Contact");?></strong><br/>
							<strong​​ style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php if(!empty($this->search['start_date'])){?><?php echo date('d-M-Y',strtotime($this->search['start_date']));?><?php echo $tr->translate("TO");?><?php echo date('d-M-Y',strtotime($this->search['end_date']));}?> </strong>
						</td>
						<td width="20%" align="right">
						</td>
					</tr>
				<style>
					table tr th{
						border: 1px solid #000;	
					}
					table {page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					}
					table thead tr td{
						text-align: center;
						padding: 5px;
					}
					
				</style>
					<tr>
						<td colspan="3">
							<div id="exportExcel">
								<table cellpadding="4"​ style=";font-family:'Khmer OS Battambang' ; margin:0 auto;width:100%;border:1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
									<thead>
										<tr style="font-size:12px; height: 25px;background:#ccd9ff;font-weight: bold;" align="center" >
											<td><?php echo $tr->translate("NUM");?></td>
											<td><?php echo $tr->translate("BRANCH_NAME");?></td>
											<td><?php echo $tr->translate("CONTACT_DATE");?></td>
											<td><?php echo $tr->translate("STUDENT_NAMEKHMER");?></td>
											<td><?php echo $tr->translate("First Name");?></td>
											<td><?php echo $tr->translate("Last Name");?></td>
											<td><?php echo $tr->translate("GENDER");?></td>
											<td><?php echo $tr->translate("PHONE");?></td>
											<td><?php echo $tr->translate("FEEDBACK");?></td>
											<td><?php echo $tr->translate("STATUS");?></td>
											<td><?php echo $tr->translate("CONTACT_BY");?></td>
											<td>&nbsp;</td>
										</tr>
									</thead>
									<?php $i=0;$degree=0; if(!empty($this->row)){ foreach ($this->row AS $row) { $i++;?>
									<tr style="font-size:12px; height: 23px;" align="center" class="hover" >
										<td ><?php echo $i;?></td>
										<td ><?php echo $row['branch_name'];?></td>
										<td align="center" >&nbsp;<?php echo date("d/M/Y",strtotime($row['contact_date']));?>&nbsp;</td>
										<td align="left" >&nbsp;<?php echo $row['kh_name'];?>&nbsp;</td>
										<td align="left">&nbsp;&nbsp;&nbsp;<?php echo $row['first_name'];?>&nbsp;</td>
										<td align="left">&nbsp;&nbsp;&nbsp;<?php echo $row['last_name'];?>&nbsp;</td>
										<td align="center">&nbsp;<?php echo $row['sexTitle']; ?>&nbsp;</td>
										<td ><?php echo $row['tel'];?></td>
										<td ><?php echo $row['feedback'];?></td>
										<td><?php echo $row['crm_status_title'];?></td>	
										<td>&nbsp;<?php echo $row['user_contact_name'];?>&nbsp;</td>
										<td>
											<a target="_blank" style="text-decoration: none;color:#000;" href="<?php echo $this->baseUrl();?>/allreport/allstudent/rpt-crm-detail/id/<?php echo $row['crm_id'];?>">
											<?php echo $tr->translate("DETAIL");?>
											</a>
										</td>	
										
										
									</tr>
								<?php }}?>	
								</table>	
							</div>	
						</td>
					</tr>
					<tr>
						<td colspan="3">&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3">&nbsp;</td>
					</tr>
					<tr >
						<td colspan="3" width="100%">
							<table width="100%" style="font-family:'Khmer OS Battambang';">
								<tr>
									<td  width="25%" align="center">
										<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
		</div>
	</div>
<script type="text/javascript">
	function setID(type){
		if(type==1){
			id = dijit.byId('stu_id').get('value');
			dijit.byId('stu_name').attr('value',id);
		}else{
			id = dijit.byId('stu_name').get('value');
			dijit.byId('stu_id').attr('value',id);
		}
	}
</script>