<?php
	$session_lang=new Zend_Session_Namespace('lang');
	$lang_id=$session_lang->lang_id;//1 kh,2 en
	$gender = array(
			1=>'Male',
			2=>'Female');
	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("STUDENT_ATTENDANT_LIST")); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	
	$db = new Allreport_Model_DbTable_DbRptAllStudent();
	$start_date = $this->datasearch['start_date'];
	$end_date = $this->datasearch['end_date'];
	 	
	$date1 = date("d-m-Y",strtotime($start_date));
	$date2 = date('d-m-Y',strtotime($end_date));
	$diff = abs(strtotime($date2) - strtotime($date1));
	$years = floor($diff / (365*60*60*24));
	$months = floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
	$days = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
	$amount_day =$diff/ (60*60*24);
	
	$amount_day = $amount_day + 1;
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
?>	
<div style="min-height:10cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
    	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_ATTENDANT_LIST');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-att-list')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="start_date" name="start_date" placeholder="<?php echo $tr->translate('SEARCH');?>....." value="<?php echo $this->datasearch['start_date'];?>" type="text">
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="end_date" name="end_date"  value="<?php echo $this->datasearch['end_date'];?>" type="text">
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<select name="teacher" id="teacher" dojoType="dijit.form.FilteringSelect" class="fullside" onchange="setTeacherName();">
						<option value="0"><?php echo $tr->translate("SELECT_TEACHER");?></option>
						<?php if($this->all_teacher_by_group){foreach ($this->all_teacher_by_group as $teacher){?>
							<option value="<?php echo $teacher['id']?>"><?php echo $teacher['name']?></option>
						<?php }}?>
					</select>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<select name="subject" id="subject" dojoType="dijit.form.FilteringSelect" class="fullside" onchange="setSubjectName();">
						<option value="0"><?php echo $tr->translate("SELECT_SUBJECT");?></option>
						<?php if($this->all_subject_by_group){foreach ($this->all_subject_by_group as $subject){?>
							<option value="<?php echo $subject['id']?>"><?php echo $subject['name']?></option>
						<?php }}?>
					</select>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<select name="showsign" id="showsign" dojoType="dijit.form.FilteringSelect" class="fullside">
						<option value="1" <?php if($this->datasearch['showsign']==1){echo"selected";}?>>Print Show Signature</option>
						<option value="0" <?php if($this->datasearch['showsign']==0){echo"selected";}?>>Print Hide Signature</option>
					</select>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
            </div>
        </div>
	</form>
<div id="divPrint">
	<table style="background:#fff; margin: 0 auto; width: 100%;"  border="0">
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr class="line"><td colspan="3"></td></tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td colspan="3" align="center">
					<span style="color:#000; font-size: 18px;font-family:Times New Roman,'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("STUDENT_ATTENDANT_LIST");?></span>
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
			<?php $total_day=0;for($k=0;$k<$amount_day;$k++){?>
				<?php if(date('D',strtotime(" $start_date+$k day"))=="Sun"){}else{ $date = date('d-m-Y',strtotime("$start_date +$k day"));
					$total_day++;
				}?>
			<?php }?>					
			<tr>
				<td colspan="3" id="exportExcel">
					<table cellpadding="5"​ style="font-size:12px; margin:0 auto;width:100%; border-collapse: collapse;border:1px solid #000; white-space: nowrap;font-family: 'Times New Roman','Khmer OS Battambang';"  border="1" >
						<style> 
							td{padding:0 3px; }
							.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap;}
							table{ page-break-inside:auto;font-family:'Times New Roman','Khmer OS Battambang'; }
							tr{ page-break-inside:avoid; page-break-after:auto }
							#header {
							  display: table-header-group;
							  page-break-inside:avoid; page-break-after:auto;
							}
							td.rotate > div {
							  transform: rotate(270deg);
								width: 20px;
							}
							tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
						</style>
						<thead>									
							<tr>
								<td colspan="<?php echo 4+$total_day;?>">
									<table width="100%" border="0" style="border-collapse: collapse;font-family: 'Times New Roman','Khmer OS Battambang';font-size: 14px;line-height: 25px;">
										<tr>
											<td width="20%" style="border-right: 1px solid #000;">
												Attendance sheet for : <?php echo $this->rr['grade']?>
											</td>
											<td width="40%" style="border-right: 1px solid #000;">
												Class report for Academic Year : <?php echo $this->rr['academic']?>
											</td>
											<td width="20%" align="center" style="border-right: 1px solid #000;">
												From <?php echo date("d-m-Y",strtotime($this->datasearch['start_date']));?> to <?php echo date("d-m-Y",strtotime($this->datasearch['end_date']));?>
											</td>
											<td width="20%" >
												Room : <?php echo $this->rr['room_name']?>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="<?php echo 4+$total_day;?>">
									<table width="100%" border="0" style="border-collapse: collapse;font-family: 'Times New Roman','Khmer OS Battambang';font-size: 14px;font-weight: bold;line-height: 25px;">
										<tr>
											<td width="50%" style="border-right: 1px solid #000;">
												Instructor : <label id="teacher_name"> </label>
											</td>
											<td width="50%">
												Subject : <label id="subject_name"> </label>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<?php if($this->datasearch['showsign']==1){?>
							<tr align="center" style="height: 65px; background: #ccd9ff;" class="signnature">
								<td colspan="4" style="font-weight: bold;"><?php echo $tr->translate("Instructor's Signature");?></td>
								<?php for($k=0;$k<$amount_day;$k++){?>
									<?php if(date('D',strtotime(" $start_date+$k day"))=="Sun"){}else{ $date = date('d-m-Y',strtotime("$start_date +$k day"));?>
										<td class="rotate"></td>
									<?php }?>
								<?php }?>
							</tr>
							<?php }?>
							<tr class="cheader" align="center" style="background: #ccd9ff;">
								<td colspan="4"><?php echo $tr->translate("Month");?></td>
								<td style="background: none;" align="center" colspan="<?php echo $total_day;?>">
									From &nbsp;&nbsp; <?php echo date("d-m-Y",strtotime($this->datasearch['start_date']));?> &nbsp;&nbsp;to&nbsp;&nbsp; <?php echo date("d-m-Y",strtotime($this->datasearch['end_date']));?>
								</td>
							</tr>
							
							<tr class="cheader" align="center" style="background: #ccd9ff;" >
								<td colspan="4"><?php echo $tr->translate("Weekday");?></td>
								
								<?php for($k=0;$k<$amount_day;$k++){?>
								<?php if(date('D',strtotime(" $start_date+$k day"))=="Sun"){}else{ $date = date('d-m-Y',strtotime("$start_date +$k day"));?>
									<td class=""><div><span><?php  echo date("D",strtotime($date));?></span></div></td>
								<?php }?>
							<?php }?>
							</tr>
							<tr class="cheader" align="center" style="background: #ccd9ff;" >
								<td colspan="4"><?php echo $tr->translate("Today's Date");?></td>
								<?php for($k=0;$k<$amount_day;$k++){?>
									<?php if(date('D',strtotime(" $start_date+$k day"))=="Sun"){}else{ $date = date('d-m-Y',strtotime("$start_date +$k day"));?>
										<td class=""><div><span><?php  echo date("d",strtotime($date));?></span></div></td>
									<?php }?>
								<?php }?>
							</tr>
						</thead>
						<?php  
							$i=0;
							$male=0;$femle=0;
							foreach ($this->rs as $row){ $i++;
						?>
						<tr style="font-size:12px;height: 23px;"​ align="center">
							<td><?php echo $i;?></td>
							<td><?php echo $row['stu_code'];?></td>
							<td align="left"><?php echo ($lang_id==1)?$row['kh_name']:$row['en_name'];?></td>
							<td><?php 
								if($lang_id==2){
									echo $gender[$row['gender']];
								}
								else{
									echo $row['sex'];
								}
								if($row['gender']==1){
									$male=$male+1;
								}else{
									$femle=$femle+1;
								}?>
							</td>
							
							<?php $p=0; $a=0;$l=0;$el=0; for($k=0;$k<$amount_day;$k++){?>
							<?php if(date('D',strtotime(" $start_date+$k day"))=="Sun"){}else{ //$date = date('d-m-Y',strtotime("$start_date +$k day"));?>
								<td align="center" >
								</td>
								<?php }?>
							<?php }?>
						</tr>
						<?php }?>	
						<tr>
							<td colspan="2" style="border:1px solid #fff;border-top:1px solid #000;"><span style="color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("STUDENT_TOTAL")." : ".$i." ".$tr->translate("STUDENT_UNIT");?></span></td>
							<td colspan="3" align="center" style="border:1px solid #fff;border-top:1px solid #000;"><span style="color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("FEMALE")." ".$femle;?> <?php echo $tr->translate("STUDENT_UNIT")."  <br />";?><?php echo $tr->translate("MALE")." ".$male;?><?php echo $tr->translate("STUDENT_UNIT");?></span></td>
						</tr>
					</table>	
				</td>
			</tr>
		</table>
	</div>
</div>
<script>
	function setTeacherName(){
		teacher = dijit.byId('teacher').attr('displayedValue');
		dojo.byId("teacher_name").innerHTML = teacher ;	
	}
	function setSubjectName(){
		subject = dijit.byId('subject').attr('displayedValue');
		dojo.byId("subject_name").innerHTML = subject;	
	}
</script>