<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDNET_TRANDSFORMATION')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$ac = null;
	$ad = null;
	$i=null;
	$session='';
	$grade='';
	
	$to_ad = null;
	$to_session='';
	$to_grade='';
	$frm =  $this->form_search;
?>	
<div style="min-height:10cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDNET_TRANDSFORMATION');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rptgroupstudentchangegroup')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<div class="form-group">
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<?php echo $frm->getElement("title");?>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php echo $frm->getElement("branch_id");?>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php //echo $frm->getElement("study_year");?>
		           		<input id="study_year" />
                </div>
               <!-- 
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<?php //echo $frm->getElement("grade_bac");?>
                </div>
                -->
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<?php echo $frm->getElement("session");?>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<select  class="fullside" dojoType="dijit.form.FilteringSelect"  class="fullside" id="change_type" name="change_type" type="text">
							<option value=""><?php echo $tr->translate("SELECT_TYPE");?></option>
							<?php if(!empty($this->change_type)){foreach ($this->change_type as $rs){?>
								<option value="<?php echo $rs['id']?>" <?php if($rs['id']==$this->search['change_type']){echo 'selected="selected"';}?>><?php echo $rs['name']?></option>
							<?php }}?>
						</select>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
                </div>
            </div>
		</form>
	<div id="divPrint">
		<style> 
		th{border-top:1px solid #000;border-collapse: collapse;}
		</style>
		<table style="width:100%;background:#fff; margin: 0 auto;border-collapse: collapse;">
			<tr style="font-size: 18px;">
				<td colspan="2"></td>
				<td align="center">
				</td>
			</tr>
			<tr>
				<td width="28%" >
					<img style="width: 110px;padding-left: 45px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
				</td>
				<td width="44%" align="center">
					<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_BRANCH");?></strong><br />
					<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';;"><?php echo $tr->translate("STUDNET_TRANDSFORMATION");?></strong><br />
					<strong></strong>
				</td>
				<td width="28%" align="right">
				</td>
			</tr>
			<tr>
				<td colspan="4" id="exportExcel">								
					<table cellpadding="5"​ style="margin:0 auto;width:90%; border-collapse: collapse;padding-buttom: 10px;"  border="1" >																			
					<?php $total_stu=0; if(!empty($this->rs))foreach ($this->rs as $key =>$stu){										
					?>
						<?php if((($ad!=$stu["academic_year"] OR $session!=$stu["session"] OR $grade!=$stu["grade"]) OR ($to_ad!=$stu["to_academic_year"] OR $to_session!=$stu["to_session"] OR $to_grade!=$stu["to_grade"])) AND  $key>0 ){?>											
						<tr> 
							<td align="right" colspan="3" style="font-size: 12px;font-weight: bold;">Total Students &nbsp;</td>
							<td align="center"><?php echo number_format($i,0);?></td>
 						</tr> 
						</table>
					   <br/>
					<table cellpadding="5"​ style="margin:0 auto;width:90%; border-collapse: collapse;padding-buttom: 10px;"  border="1" >
							
						<?php }$i++;?>
						<?php 
							if(($ad!=$stu["academic_year"] OR $session!=$stu["session"] OR $grade!=$stu["grade"]) OR ($to_ad!=$stu["to_academic_year"] OR $to_session!=$stu["to_session"] OR $to_grade!=$stu["to_grade"])){
								$ac=0;$i=1;
						?>
						<tr style="font-size:14px; height: 20px;" align="center" border: "0" >
							<td colspan="4" style="border: 1px solid white;border-bottom: 1px solid black;">
								<span style="font-size: 15px;font-weight: bold;">
									<span style="background-color: rgba(249,249,249,1);white-space: nowrap;color: red;padding: 0px 5px;border: 1px solid #efefef;border-radius: 5px;">&nbsp;<?php echo $stu["academic_year"]?> &nbsp; <?php echo $stu["grade"];?> &nbsp; <?php echo $stu["session"];?>&nbsp;</span> &nbsp; To &nbsp; <span style="color: red;background-color: rgba(249,249,249,1);padding: 0px 5px;border: 1px solid #efefef;border-radius: 5px;">&nbsp;<?php echo $stu["to_academic_year"]?> &nbsp; <?php echo $stu["to_grade"];?> &nbsp; <?php echo $stu["to_session"];?>&nbsp; </span> &nbsp; <?php echo $tr->translate("TYPE")?> : <span style="background-color: rgba(249,249,249,1);white-space: nowrap;color: red;padding: 0px 5px;border: 1px solid #efefef;border-radius: 5px;"><?php echo $stu["change_type"];?> </span>         
								</span>
							</td>
						</tr>
						<tr style="font-size:12px; height: 15px;border-collapse: collapse;" align="center" >
							<th style="width: 10%;">N.o</th>
							<th style="width: 30%;">Studen Code</th>
							<th style="width: 30%;">Student Name</th>
							<th style="width: 30%;">Sex</th>
						</tr>
						<?php }?>
						<?php 
							  $ad=$stu["academic_year"];
						 	  $session=$stu["session"];
						 	  $grade=$stu["grade"];
						 	  $to_ad=$stu["to_academic_year"];
						 	  $to_session=$stu["to_session"];
						 	  $to_grade=$stu["to_grade"];
						?>
						
						<tr style="font-size:12px;height: 15px;border: 1px solid #000;border-collapse: collapse;"​ align="center">
							<td style="width: 10%;"><?php echo $i;?></td>
							<td style="width: 30%;"><?php echo $stu['stu_code'];?></td>
							<td style="width: 30%;"><?php echo $stu['stu_name'];?></td>
							<td style="width: 30%;"><?php echo $stu['sex'];?></td>
						</tr>
					<?php }?>
					<?php if(!empty($this->rs)){?>
					<tr>
						<td align="right" colspan="3" style="font-size: 12px;font-weight: bold;">Total Students &nbsp;</td>
						<td align="center"><?php echo number_format($i,0);?></td>
					</tr>
					<?php }?>
					</table>	
				</td>
			</tr>
			<tr><td></td></tr>
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			<tr>
				<td align="center" width="25%">
					<span style="font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY");?></span>
				</td>
				<td  width="50%">
					&nbsp;
				</td>
				<td align="center"  width="25%">
					<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY");?></span>
				</td>
			</tr>
		</table>			
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.FilteringSelect"); 

dojo.require("dojo.html");
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
    });
	 getAllAcademicByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}

</script>