<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('GROUP_LISTINGS')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
	$urlStudentGroup = $this->baseUrl()."/allreport/allstudent/rpt-student-group/id/";
	$urlAttList = $this->baseUrl()."/allreport/allstudent/rpt-att-list/id/";
	$urlTotalAtt = $this->baseUrl()."/allreport/allstudent/rpt-totalattendance/id/";
	$urlStudentList = $this->baseUrl()."/allreport/allstudent/rpt-student-list/id/";
?>
<div style="min-height:10cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
    	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('GROUP_LISTINGS');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'student-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("title");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("branch_id");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="study_year" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="group" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("teacher");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("study_status");?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("degree");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("grade");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("session");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("room");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            </div>
        </div>
	</form>	
<style>
.hidden{
	display: table-cell !important;
}
</style>
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto; width: 100%;">
			<tr>
				<td width="28%" align="left">
					<img style="max-height:100px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
				</td>
				<td width="44%" align="center">
					<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_BRANCH");?></strong><br />
					<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><p><?php echo $tr->translate("GROUP_LISTINGS");?></p></strong>
				</td>
				<td align="right" width="28%"></td>
			</tr>
			<tr>
				<td colspan="3" valign="top" id="exportExcel">
						<style type="text/css">
							th,td{ padding:0 1px;}
							table{ border-collapse:collapse; margin:0 auto;border-color:#000; }
							.padding{ padding: 0 1px !important;}
							table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
							tr{ page-break-inside:avoid; page-break-after:auto }
							#header {display: table-header-group;page-break-inside:avoid; page-break-after:auto;}
							.hover:hover{background: #ccc;}
							.hidden{display: none;}
						</style>
						<?php 
						$all_student = 0;
						$active_student = 0;
						$drop_student = 0;?>
					<div id="exportExcel">
						<table cellpadding="3" class="padd" width="99%" border="1" align="center" style="white-space:nowrap;font-family:Time New Roman , Khmer OS Battambang;">
						  <thead>
						  <tr style="font-size:13px; line-height: 27px; font-weight: bold; background: #ccd9ff;" align="center">
						    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
						    <td>&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
						    <td>&nbsp;<?php echo $tr->translate("STUDY_GROUP");?>&nbsp;</td>
						    <td>&nbsp;<?php echo $tr->translate("ACADEMIC_YEAR");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("SEMESTER");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("DEGREE");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("GRADE");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("SESSION");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("CLASSES");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("STATUS");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("TOTAL_STUDENT");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("STUDENT_DROP");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("STUDENT_STUDY");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("NOTE");?>&nbsp;</td>
						  </tr>
						  </thead>
						  <?php $i=0; 
						  //print_r($this->rs);exit();
						  if (!empty($this->rs)){foreach($this->rs as $rs){ $i++;?>
						  <tr oncontextmenu="setrowdata(<?php echo $rs['id'];?>);return false;" style="font-size:12px; line-height: 25px;"​ align="center" class='hover padding context-menu-one'>
						   	<td><?php echo $i;?></td>
						   	<td align="left">&nbsp;<?php echo $rs['branch_name']; ?></a></td>
						    <td align="left">&nbsp;<?php echo $rs['group_code']; ?></a></td>
						    <td align="left">&nbsp;<?php echo $rs['academic']; ?></a></td>
						    <td><?php echo $rs['semester']; ?></a></td>
						    <td align="left">&nbsp;&nbsp;<?php echo $rs['degree']; ?>&nbsp;</td>
						    <td>&nbsp;<?php echo $rs['grade']; ?>&nbsp;</td>
						    <td>&nbsp;<?php echo $rs['session']; ?>&nbsp;</td>
						    <td align="left">&nbsp;&nbsp;<?php echo $rs['room_name']; ?>&nbsp;</td>
						    <td>&nbsp;<?php echo $rs['status']; ?>&nbsp;</td>
						    <td>&nbsp;<?php echo $rs['Num_Student']; ?>&nbsp;<?php echo $tr->translate("STUDENT_UNIT");?></td>
						    <td>&nbsp;<?php echo $rs['student_drop']; ?>&nbsp;<?php echo $tr->translate("STUDENT_UNIT");?></td>
						    <td>&nbsp;<?php echo $rs['Num_Student']-$rs['student_drop']; ?>&nbsp;<?php echo $tr->translate("STUDENT_UNIT");?></td>
						    <td align="left">&nbsp;&nbsp;<?php echo $rs['note']; ?>&nbsp;</td>
						  </tr>
						  <?php 
						  	$all_student = $all_student+$rs['Num_Student'];
						  	$drop_student = $drop_student+$rs['student_drop'];
						  }} ?>
						</table>
						<br>
						<table cellpadding="3" class="padd" width="20%" align="right" style="line-height:27px;white-space:nowrap;font-family:Time New Roman , Khmer OS Battambang;">
							<tr>
								<td width="60%" style="border-bottom:1px solid #1d76e5;"><?php echo $tr->translate("TOTAL_STUDENT");?></td>
								<td width="40%" align="center" style="border-bottom:1px solid #1d76e5;"><strong><?php echo $all_student;?> <?php echo $tr->translate("STUDENT_UNIT");?></strong></td>
							</tr>
							<tr>
								<td style="border-bottom:1px solid #1d76e5;"><?php echo $tr->translate("STUDENT_DROP");?></td>
								<td align="center" style="border-bottom:1px solid #1d76e5;"><strong><?php echo $drop_student;?> <?php echo $tr->translate("STUDENT_UNIT");?></strong></td>
							</tr>
							<tr>
								<td style="border-bottom:1px solid #1d76e5;"><?php echo $tr->translate("STUDENT_STUDY");?></td>
								<td align="center" style="border-bottom:1px solid #1d76e5;"><strong><?php echo $all_student - $drop_student;?> <?php echo $tr->translate("STUDENT_UNIT");?></strong></td>
							</tr>
						</table>
					</div>
				</td>
			</tr>
			<tr>
				<td colspan="3" width="100%">
					<table width="100%" style="font-family:'Khmer OS Battambang';">
						<tr>
							<td colspan="3">&nbsp;</td>
						</tr>
						<tr>
							<td colspan="3">&nbsp;</td>
						</tr>
						<tr>
							<td  width="25%" align="center">
								<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
							</td>
							<td  width="50%">
								&nbsp;
							</td>
							<td align="center"  width="25%">
								<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>	
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.FilteringSelect"); 

dojo.require("dojo.html");
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
		    
	    }
	}, "group");
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
    });
	 getAllAcademicByBranch();
	 getAllGroupByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="rpt-student-group"){
				url='<?php echo $urlStudentGroup;?>';
			}else if(key=="rpt-att-list"){
				url='<?php echo $urlAttList;?>';
			}else if(key=="rpt-totalattendance"){
				url='<?php echo $urlTotalAtt;?>';
			}else if(key=="rpt-student-list"){
				url='<?php echo $urlStudentList;?>';
			}  
			
			gotoAction();
		},
		items: {
			"rpt-student-group": {name: "<?php echo $tr->translate("STUDENT_LIST_REPORT");?>", icon: "fa-file-text-o",},
			"rpt-att-list": {name: "<?php echo $tr->translate("STUDENT_ATTENDANT_LIST");?>", icon: "fa-file-text-o"},
			"rpt-totalattendance": {name: "<?php echo $tr->translate("TOTAL_ATTENDANT_LIST");?>", icon: "fa-file-text-o"},
			"rpt-student-list": {name: "<?php echo $tr->translate("STUDENT_LIST");?>", icon: "fa-file-text-o"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	window.open(url+row);
}


</script>