<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('GROUP_LISTINGS')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
?>
<div style="min-height:10cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
    	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('GROUP_LISTINGS');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'student-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("title");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("branch_id");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="study_year" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="group" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("teacher");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("study_status");?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("degree");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("grade");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("session");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("room");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12 col-sm-12 col-xs-12">
            	<button onclick="getstudentlist();" iconclass="dijitEditorIcon dijitEditorIconPrint" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("STUDENT_LIST");?></button>
            	<button onclick="gettotalatt();" iconclass="dijitEditorIcon dijitEditorIconPrint" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("Total Attendance List");?></button>
            	<button onclick="getTranscript();" iconclass="dijitEditorIcon dijitEditorIconPrint" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("TRANSCRIPT");?></button>
            	<button onclick="getAttendancelist();" iconclass="dijitEditorIcon dijitEditorIconPrint" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("STUDENT_ATTENDANT_LIST");?></button>
	       		<input type="hidden" name="group_id" id="group_id" dojoType="dijit.form.TextBox" />
            </div>
        </div>
	</form>	
<style>
.hidden{
	display: table-cell !important;
}
</style>
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto; width: 100%;">
			<tr>
				<td width="28%" align="left">
					<img style="max-height:100px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
				</td>
				<td width="44%" align="center">
					<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_BRANCH");?></strong><br />
					<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><p><?php echo $tr->translate("GROUP_LISTINGS");?></p></strong>
				</td>
				<td align="right" width="28%"></td>
			</tr>
			<tr>
				<td colspan="3" valign="top" id="exportExcel">
						<style type="text/css">
							th,td{ padding:0 1px;}
							table{ border-collapse:collapse; margin:0 auto;border-color:#000; }
							.padding{ padding: 0 1px !important;}
							table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
							tr{ page-break-inside:avoid; page-break-after:auto }
							#header {display: table-header-group;page-break-inside:avoid; page-break-after:auto;}
							.hover:hover{background: #ccc;}
							.hidden{display: none;}
						</style>
						<?php 
						$all_student = 0;
						$active_student = 0;
						$drop_student = 0;?>
					<div id="exportExcel">
					<table cellpadding="3" class="padd" width="99%" border="1" align="center" style="white-space:nowrap;">
						  <thead>
						  <tr style="font-size:12px; height: 25px; font-weight: bold; background: #ccd9ff;" align="center">
						    <td class="hidden"></td>
						    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
						    <td>&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
						    <td>&nbsp;<?php echo $tr->translate("STUDY_GROUP");?>&nbsp;</td>
						    <td>&nbsp;<?php echo $tr->translate("ACADEMIC_YEAR");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("SEMESTER");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("DEGREE");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("GRADE");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("SESSION");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("CLASSES");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("AMOUNT_MONTH");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("STATUS");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("TOTAL_STUDENT");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("STUDENT_DROP");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("STUDENT_STUDY");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("NOTE");?>&nbsp;</td>
						  </tr>
						  </thead>
						  <?php $i=0; 
						  foreach($this->rs as $rs)if (!empty($this->rs)){ $i++;?>
						  <tr style="font-size:12px; height: 18px;"​ align="center" class='hover padding'>
						   	<td class="hidden">
								<input style="height: 15px;margin-top: 5px;" type="radio" onClick="setValue(<?php echo $i?>)" name="check_box" id="check_box<?php echo $i?>" />
								<input type="hidden" name="group_id<?php echo $i;?>" id="group_id<?php echo $i;?>" value="<?php echo $rs['id'];?>" dojoType="dijit.form.TextBox" />
							</td>
						   	<td><?php echo $i;?></td>
						   	<td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'allstudent','action'=>'rpt-student-group','id'=>$rs['id']));?>" target="_blank"><?php echo $rs['branch_name']; ?></a></td>
						    <td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'allstudent','action'=>'rpt-student-group','id'=>$rs['id']));?>" target="_blank"><?php echo $rs['group_code']; ?></a></td>
						    <td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'allstudent','action'=>'rpt-student-group','id'=>$rs['id']));?>" target="_blank"><?php echo $rs['academic']; ?></a></td>
						    <td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'allstudent','action'=>'rpt-student-group','id'=>$rs['id']));?>" target="_blank"><?php echo $rs['semester']; ?></a></td>
						    <td align="left">&nbsp;&nbsp;<?php echo $rs['degree']; ?>&nbsp;</td>
						    <td>&nbsp;<?php echo $rs['grade']; ?>&nbsp;</td>
						    <td>&nbsp;<?php echo $rs['session']; ?>&nbsp;</td>
						    <td align="left">&nbsp;&nbsp;<?php echo $rs['room_name']; ?>&nbsp;</td>
						    <td align="center">&nbsp;<?php echo $rs['amount_month']; ?>&nbsp;</td>
						    <td>&nbsp;<?php echo $rs['status']; ?>&nbsp;</td>
						    <td>&nbsp;<?php echo $rs['Num_Student']; ?>&nbsp;</td>
						    <td>&nbsp;<?php echo $rs['student_drop']; ?>&nbsp;</td>
						    <td>&nbsp;<?php echo $rs['Num_Student']-$rs['student_drop']; ?>&nbsp;</td>
						    <td align="left">&nbsp;&nbsp;<?php echo $rs['note']; ?>&nbsp;</td>
						  </tr>
						  <?php 
						  	$all_student = $all_student+$rs['Num_Student'];
						  	$drop_student = $drop_student+$rs['student_drop'];
							} ?>
						  <tr>
						  	  <td colspan="11" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						  	  <td align="center"><strong><?php echo $all_student;?></strong></td>
						  	  <td align="center"><strong><?php echo $drop_student;?></strong></td>
						  	  <td align="center"><strong><?php echo $all_student -$drop_student;?></strong></td>
						  </tr>
						</table>
						</div>
					</td>
				</tr>
				<tr >
				<td colspan="3" width="100%">
					<table width="100%" style="font-family:'Khmer OS Battambang';">
						<tr>
							<td colspan="3">&nbsp;</td>
						</tr>
						<tr>
							<td colspan="3">&nbsp;</td>
						</tr>
						<tr>
							<td  width="25%" align="center">
								<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
							</td>
							<td  width="50%">
								&nbsp;
							</td>
							<td align="center"  width="25%">
								<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>	
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.FilteringSelect"); 

dojo.require("dojo.html");
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
		    
	    }
	}, "group");
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
    });
	 getAllAcademicByBranch();
	 getAllGroupByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}
url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}

function setValue(index){
	if(dojo.byId('check_box'+index).checked){
		group_id = dijit.byId('group_id'+index).get('value');
		dijit.byId('group_id').attr('value',group_id);
	}
}
function getstudentlist(){
	id = dijit.byId('group_id').get('value');
	if(id==''){alert("Please select record first!");return false;}
	window.open('<?php echo $this->url(array("module"=>'allreport','controller'=>'allstudent','action'=>'rpt-student-list'));?>'+'/id/'+id,'_blank');
}
function gettotalatt(){
	id = dijit.byId('group_id').get('value');
	if(id==''){alert("Please select record first!");return false;}
	window.open('<?php echo $this->url(array("module"=>'allreport','controller'=>'allstudent','action'=>'rpt-totalattendance'));?>'+'/id/'+id,'_blank');
}
function getTranscript(){
	id = dijit.byId('group_id').get('value');
	if(id==''){alert("Please select record first!");return false;}
	window.open('<?php echo $this->url(array("module"=>'allreport','controller'=>'allstudent','action'=>'rpt-student-group'));?>'+'/id/'+id,'_blank');
}
function getAttendancelist(){
	id = dijit.byId('group_id').get('value');
	if(id==''){alert("Please select record first!");return false;}
	window.open('<?php echo $this->url(array("module"=>'allreport','controller'=>'allstudent','action'=>'rpt-att-list'));?>'+'/id/'+id,'_blank');
}
function getResultyearly(){
	id = dijit.byId('group_id').get('value');
	if(id==''){alert("Please select record first!");return false;}
	window.open('<?php echo $this->url(array("module"=>'allreport','controller'=>'score','action'=>'rpt-resultbyyear'));?>'+'/id/'+id+'/type/3','_blank');
}
function getHonoryearly(){
	id = dijit.byId('group_id').get('value');
	if(id==''){alert("Please select record first!");return false;}
	window.open('<?php echo $this->url(array("module"=>'allreport','controller'=>'score','action'=>'yearly-outstanding-student'));?>'+'/id/'+id+'/type/3','_blank');
}
function getCertificate(){
	id = dijit.byId('group_id').get('value');
	if(id==''){alert("Please select record first!");return false;}
	window.open('<?php echo $this->url(array("module"=>'allreport','controller'=>'score','action'=>'rpt-certificate'));?>'+'/id/'+id+'/type/3','_blank');
}
</script>