 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("Dashboard Student Registration Management System"));
	echo $this->headTitle();
	
	$parameterserch =  basename($_SERVER['REQUEST_URI']);
	$urlsting = str_replace("&pages=".$this->currentPage,"",$parameterserch);
	// echo $urlsting;exit();
	$sign="?";
	if (!empty($urlsting)){
		$sign="&";
	}
?>
<link rel="stylesheet" href="<?php echo $this->baseUrl()."/"?>dashboard/plugins/morris/morris.css">
<!-- Icons CSS -->
<link href="<?php echo $this->baseUrl()."/"?>dashboard/css/icons.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="<?php echo $this->baseUrl()."/"?>dashboard/css/style.css" rel="stylesheet">
<style>
.col-lg-6.capital-box {
    min-height: 115px;
}
 </style>
<div id="page-wrapper">
	<!-- Page content start -->
	<div class="page-contentbar">
		<!-- START PAGE CONTENT -->
		<div id="page-right-content">
			<div class="container">
				 <div class="row">
					<div class="col-lg-6">
						<div class="card-box">
							<div class="col-lg-12">
								<div class="accounting-management text-center">
									<div class="col-lg-6 capital-box" style="background:#17418e;; color: #fff">
										<a title="<?php echo $tr->translate("FINDING_ALL_STUDENT_INFORMATION")?>" href="<?php echo $this->url(array('module'=>'home','controller'=>'searchstudentinfo','action'=>'index'), null, true);?>">
											<span data-bind="text: txnRecorded"><h3><?php echo $tr->translate("FINDING_ALL_STUDENT_INFORMATION")?></h3></span>
											<p class="month" style="text-align: center; margin: 0 auto;" data-bind="text: lang.lang.transactions_recorded">&nbsp;<?php echo $tr->translate("STUDENT_TOTAL")." : ".$this->rsamountstudent." ".$tr->translate("STUDENT_UNIT");?> &nbsp;<?php echo $tr->translate("NEW_STUDENT")." : ".$this->rsnewstudent." ".$tr->translate("STUDENT_UNIT");?></p>
										</a>
									</div>
									<div class="col-lg-6 capital-box" style="background:#0077c5;; color: #fff">
									<a title="<?php echo $tr->translate("RPT_STUDENT_DROPS");?>" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-student-drop'), null, true);?>">
										<span data-bind="text: txnRecorded"><h3><?php echo $tr->translate("STUDENT_DROP")." : ".$this->alltypedrop." ".$tr->translate("STUDENT_UNIT");?></h3></span>
										<p class="month" style="text-align: center; margin: 0 auto;" data-bind="text: lang.lang.transactions_recorded">&nbsp;<?php echo $tr->translate("SUSPEND")." : ".$this->stu_suppend." ".$tr->translate("STUDENT_UNIT");?> &nbsp;<?php echo $tr->translate("DROPPED")." : ".$this->stu_stopped." ".$tr->translate("STUDENT_UNIT");?></p>
									</a>
									<br />
								</div>
								<div class="clearfix"></div>
								</div>
							</div>
						</div>
						<div class="card-box">
							<form id="list" name="list" action="" dojoType="dijit.form.Form" method="GET">
				          		<div class="x_panel searc-blog">
				          			<div class="x_title">
								    	<h2><i class="fa fa-search"></i> <?php echo $tr->translate("Spescial Discount")?></h2>
										<span class="pull-right">
										</span>
										<div class="clearfix"></div>
									</div>
									<div class="x_content search">
										<?php $frm = $this->frm_degree;?>
										<div class="form-control">
											<div class="search-list col-lg-4 col-md-4 col-sm-12 col-xs-12">
											<?php echo $frm->getElement("advance_search");?>
											</div>
											<div class="search-list col-lg-3 col-md-3 col-sm-12 col-xs-12">
											<?php echo $frm->getElement("dis_type");?>
											</div>
											<div class="search-list col-lg-3 col-md-3 col-sm-12 col-xs-12">
											<?php echo $frm->getElement("status_type");?>
											</div>
											<div class="search-list col-lg-2 col-md-2 col-sm-12 col-xs-12">
											<button iconclass="dijitIconSearch" name="search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
											</div>
											<div class="clearfix"></div>
										</div>
									</div>
									<div class="x_content result">
										<?php if (!empty($this->sepcialdiscount)) foreach ($this->sepcialdiscount as $key => $spdis){?>
										<div class="col-md-12 col-sm-12 col-xs-12 profile_details">
					                        <div class="well profile_view">
					                          <div class="col-sm-12">
					                            <h4 class="brief"><i><?php echo $spdis['status_type'];?></i></h4>
					                            <div class="left col-xs-7">
					                              <h2><?php echo $spdis['stu_name'];?></h2>
					                              <p><strong><?php echo $tr->translate("REQUEST_NAME")?>: </strong> <?php echo $spdis['request_name'];?> </p>
					                              <ul class="list-unstyled">
					                                <li><i class="fa fa-phone"></i> <?php echo $tr->translate("PHONE")?> : <?php echo $spdis['phone'];?></li>
					                                <li><i class="fa fa-pencil-square"></i> <?php echo $tr->translate("DISCOUNT_TYPE")?> : <?php echo $spdis['discount_type_title'];?></li>
					                                <li><i class="fa fa-clock-o "></i> <?php echo $tr->translate("PERIOD")?>: <?php echo $spdis['duration']." ".$spdis['duration_type_title'];?></li>
					                                <li><i class="fa fa-calendar"></i> <?php echo $tr->translate("EXPIRE_DATE")?>: <?php echo date("d/M/Y",strtotime($spdis['expired_date']));?></li>
					                              </ul>
					                            </div>
					                            <div class="right col-xs-5 text-center">
					                              <img src="<?php echo $this->baseUrl();?>/images/user.png" alt="" class="img-circle img-responsive">
					                            </div>
					                          </div>
					                          <div class="col-xs-12 bottom text-center">
					                            <div class="col-xs-12 col-sm-6 emphasis">
					                            	<i class="fa fa-calendar"></i> <?php echo $tr->translate("ISSUE_DATE")?>: <?php echo date("d/M/Y",strtotime($spdis['create_date']));?>
					                            </div>
					                            <div class="col-xs-12 col-sm-6 emphasis">
					                            &nbsp;
					                            </div>
					                          </div>
					                        </div>
					                      </div>
					                     <?php }?>
					                     <div class="clearfix"></div>
          			
          			 <?php 
		             	if($this->countPages>1){ 
							$statpage = $this->currentPage - 5;
							$endpage = $this->currentPage + 5;
						 	if ($this->currentPage<=5){
						 		$statpage = 1;
						 		$endpage =10;
						 	}
		                 if (!empty($this->countPages)){
								 ?>
								<div class="clearfix"></div>
					            <div class="pagin text-center">
					            	<nav aria-label="Page navigation example">
									  <ul class="pagination">
									  	<?php if($this->currentPage!=1){ ?>
									  	<li class="page-item"><a class="page-link" href="<?php echo $urlsting.$sign."pages=1";?>"><?php echo $tr->translate('First');?></a></li>
									    <li class="page-item"><a class="page-link" href="<?php echo $urlsting.$sign."pages=".$this->previousPage;?>"><?php echo $tr->translate('Previous');?></a></li>
									    <?php }?>
									     <?php  $i=0; for( $i=1; $i<=$this->countPages; $i++){?>
					           			 	<?php if ($statpage<=$i && $endpage>=$i){?>
									    <li class="page-item <?php if($i==$this->currentPage){ echo "active";}?>">
									    	<a class="page-link" href="<?php echo $urlsting.$sign."pages=".$i;?>"><?php echo $i;?></a>
									    </li>
									    	<?php }
										}?>
										<?php if($this->countPages!= $this->currentPage){ ?>
									    <li class="page-item"><a class="page-link" href="<?php echo $urlsting.$sign."pages=".$this->nextPage;?>"><?php echo $tr->translate('Next');?></a></li>
									    <li class="page-item"><a class="page-link" href="<?php echo $urlsting.$sign."pages=".$this->countPages;?>"><?php echo $tr->translate('Last');?></a></li>
									    <?php }?>
									  </ul>
									</nav>
									<span><?php echo $tr->translate('Total Pages')." : ".$this->countPages." ".$tr->translate('Pages');?></span>
					            </div>
					       <?php }}?>
									</div>
				          		</div>
			          		</form>
						</div>
					</div> <!-- end col -->	  
					<div class="col-lg-6">
					</div> <!-- end col -->	  
				</div> <!-- end row -->
                 <div class="row-fluid">
					<div style="margin-top: 10px; margin-left: 0;" align="center">
						<p>© 2018<span data-bind="text: lang.lang.all_rights_reserved"><a href="http://www.cam-app.com" target="_blank" > Cam App Teachnology</a>. All rights reserved.</span></p>
					</div>	
				</div>       
			</div>
		</div>
		<!-- END PAGE CONTENT -->
	</div>

</div>

