<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_credit;
	$row = $this->row;
?>
<title><?php echo $tr->translate("TRANSFER_CREDIT");?></title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
 </script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Credit Memo Transfer');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'transfercredit','action'=>'transfer')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				stu_idto = dijit.byId('stu_idto').get('value');
       			 if(stu_idto==0){
					alert("សូមជ្រើសរើសអត្តលេខសិស្ស");dijit.byId('stu_idto').focus();return false;}
        			dijit.byId("saveclose").set("disabled",true);
					return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
				<div class="col-md-5 col-sm-5 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("INFORMATION_TO");?> 
	                   </label>
	                </div>
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                <?php echo $frm->getElement('branch_id');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_CODE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement('student_id');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                <?php echo $frm->getElement('student_name');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("CREATED_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement('Date');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EXPIRE_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		               	 <?php echo $frm->getElement('end_date');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TOTAL_SPACE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement('total_amount');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("REASON");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement('prob');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE")?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input type="hidden" id="identity" name="identity" />
		                	<?php echo $frm->getElement('Description');?>
		                </div>
		             </div>
		         </div>
		         <div class="col-md-5 col-sm-5 col-xs-12">
		         	<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("INFORMATION_RECEIVE");?> 
	                   </label>
	                </div>
	                 <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_CODE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement('stu_idto');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                <?php echo $frm->getElement('stu_name');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("CREATED_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	 <input type="text" name="start_date" readOnly="readOnly" id="start_date" constraints="{datePattern:'dd/MM/yyyy'}" value="<?php echo $row['date']?>" class="fullside" dojoType="dijit.form.DateTextBox"/>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EXPIRE_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		               	 <input type="text" name="end_dates" readOnly="readOnly" id="end_dates" constraints="{datePattern:'dd/MM/yyyy'}" value="<?php echo $row['end_date']?>" class="fullside" dojoType="dijit.form.DateTextBox"/>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("REASON");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement('problem');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE")?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input type="hidden" id="identity" name="identity" />
		                	<?php echo $frm->getElement('Descriptions');?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement('status');?>
		                </div>
		             </div>
		         </div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
				 	<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
						iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'accounting','controller'=>"transfercredit",'action'=>'index'),null,true); ?>';" />
					<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' value='saveclose' dojoType="dijit.form.Button"
					 iconClass="dijitIconDelete"/>
               	</div>
             </div>
		</form>
    </div>
</div>

<script type="text/javascript">
	dojo.require("dijit.form.Textarea");
	dojo.ready(function(){
		setSelected(1);
	});
function setSelected(type){
	if(type==1){
		student_id = dijit.byId("student_id").get('value');
		dijit.byId("student_name").attr('value',student_id);
	}else{
		student_id = dijit.byId("student_name").get('value');
		dijit.byId("student_id").attr('value',student_id);
	}
	if(type==1){
		stu_idto = dijit.byId("stu_idto").get('value');
		dijit.byId("stu_name").attr('value',stu_idto);
	}else{
		stu_idto = dijit.byId("stu_name").get('value');
		dijit.byId("stu_idto").attr('value',stu_idto);
	}
}
</script>