<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_credit;
	$row = $this->row;
?>
<title><?php echo $tr->translate("TRANSFER_CREDIT");?></title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Credit Memo Transfer');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'transfercredit','action'=>'transfer')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				stu_name = dijit.byId('stu_name').get('value');
				stu_idfrom = dijit.byId('student_name').get('value');
				if(stu_idfrom == stu_name){
					alert ("<?php echo $tr->translate("MESSAGE_DON_INOUT");?>");
					return false; 
				}else{ 
					return true;}

				stu_idto = dijit.byId('stu_idto').get('value');s	
       			 if(stu_idto==0){
					alert("សូមជ្រើសរើសអត្តលេខសិស្ស");dijit.byId('stu_idto').focus();
					return false;
				}
				dijit.byId("saveclose").set("disabled",true);
					return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
				<div class="col-md-5 col-sm-5 col-xs-12">
					<div class="card-blogform">
							<div class="card-body"> 
								<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12">

												<div class="d-flex "> 
														<div class="settings-main-icon ">
															<i class="material-icons-outlined">person</i>
															
														</div> 
														<div class="col-md-10 col-sm-10 col-xs-12"> 
															<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("INFORMATION_TO");?></p>
														</div> 
												</div>
												<div class="col-md-12 col-sm-12 col-xs-12">
														&nbsp; 
												</div>

							

												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement('branch_id');?>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_CODE");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement('student_id');?>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement('student_name');?>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("CREATED_DATE");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement('Date');?>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EXPIRE_DATE");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement('end_date');?>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TOTAL_SPACE");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement('total_amount');?>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("REASON");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement('prob');?>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE")?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<input type="hidden" id="identity" name="identity" />
														<?php echo $frm->getElement('Description');?>
													</div>
												</div>
										</div>
									</div>
							</div>
						</div>
	

		         </div>

		         <div class="col-md-5 col-sm-5 col-xs-12">
					 <div class="card-blogform">
							<div class="card-body"> 
								<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12">

												<div class="d-flex "> 
														<div class="settings-main-icon ">
														
															<i class="material-icons-outlined">transfer_within_a_station</i>
															
														</div> 
														<div class="col-md-10 col-sm-10 col-xs-12"> 
															<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("INFORMATION_RECEIVE");?></p>
														</div> 
												</div>
												<div class="col-md-12 col-sm-12 col-xs-12">
														&nbsp; 
												</div>

								
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<input id="stu_name" />
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("CREATED_DATE");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<input type="text" name="start_date" readOnly="readOnly" id="start_date" constraints="{datePattern:'dd/MM/yyyy'}" value="<?php echo $row['date']?>" class="fullside" dojoType="dijit.form.DateTextBox"/>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EXPIRE_DATE");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
													<input type="text" name="end_dates" readOnly="readOnly" id="end_dates" constraints="{datePattern:'dd/MM/yyyy'}" value="<?php echo $row['end_date']?>" class="fullside" dojoType="dijit.form.DateTextBox"/>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("REASON");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement('problem');?>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE")?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<input type="hidden" id="identity" name="identity" />
														<?php echo $frm->getElement('Descriptions');?>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
													<div class="col-md-7 col-sm-7 col-xs-12">
														<?php echo $frm->getElement('status');?>
													</div>
												</div>
											</div>
										</div>
									</div>
							</div>

		         </div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
				 	<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
					 class="button-class button-primary" iconClass="glyphicon glyphicon-refresh" onclick="window.location = '<?php echo $this->url(array('module'=>'accounting','controller'=>"transfercredit",'action'=>'index'),null,true); ?>';" />
					<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id="saveclose" value='saveclose' dojoType="dijit.form.Button"
						class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-open"/>
               	</div>
             </div>
		</form>
    </div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
 </script>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.store.Memory");
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		autoComplete: false,
		queryExpr: "*${0}*",                     
		id: "stu_name",
		name: "stu_name",   
		required:true,        
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
		onChange: function() {  
		}
	}, "stu_name");
	getallstudentname();
	 var branch_id = dijit.byId('branch_id');
	 	branch_id.on('change', function(evt) {
	 		getallstudentname();
	    });
});
var url_data = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getliststudenturl')); ?>';
function getallstudentname(){//
	branch_id = dijit.byId("branch_id").attr("value");
	if(branch_id==''){  
		dijit.byId("branch_id").focus();
		return false;}
	dojo.xhrPost({
		url:url_data,
		content:{
			'branch_id':branch_id
		},
		handleAs:"json",
		load: function(data) {
			student_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('stu_name').set('store',student_store);  
		},
		error: function(err) {
			alert(err);
		}
	});
}
	dojo.ready(function(){
		setSelected(1);
	});
function setSelected(type){
	if(type==1){
		student_id = dijit.byId("student_id").get('value');
		dijit.byId("student_name").attr('value',student_id);
	}else{
		student_id = dijit.byId("student_name").get('value');
		dijit.byId("student_id").attr('value',student_id);
	}
	
}
</script>