<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
	$pageTitle = $tr->translate("ISSUE_SCORE");
	echo $this->headTitle($pageTitle);
	$base_url = Application_Form_FrmMessage::getUrl("/");
	
	$pageTitle = '<i class="glyphicon glyphicon-pencil"></i> '.$pageTitle;

	
	$current_month = date("m");
	$duplicateMessage = "ពិន្ទុមុខវិជ្ជានេះបានបញ្ចូលរួចរាល់ហើយ / This subject's score has been entered !"
?>	
<?php 
	echo $this->render('externalHead.phtml');
?>
<div class="row"> 
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="card mb-1 ">
			<div class="card-header pb-1"> 
				<h3 class="card-title mb-2 "><?php echo $this->row['branch_name'].' "'.$tr->translate("GROUP")." ".$this->row['group_code'].'"'?></h3> 
				
			</div>
			<div class="card-content collapse show mt-1">
				<form id='scoreForm' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<script type="dojo/method" event="onSubmit">   
					if(this.validate()){
						if(isDuplicate==1){
							var htmlString = $( '.alert-text' ).html();
							alert(htmlString);
							return false;
						}
						var identity = $('#identity').val();
						if(identity==''){
							alert("There is no record to save");
							return false;
						}
						var rowId = $('#identity').val();
						if(rowId==''){ 
							alert("<?php echo $tr->translate('NO_RECORD_TO_SUBMIT');?>");
							return false;
						}
						var txt;
						var r = confirm("Are you sure to submit ?");
						if(r == true){
							 dijit.byId('save_new').set('disabled',true);
							 loadingBlock();
							 return true;
						}else{
							  return false;
						}
					}else {
						return false;
					}
					</script>
					<div class="card-box">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('SCORE_INFO')?> </p>
													
												</div> 
											</div>
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EXAM_TITLE");?></label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<input type="text" name="title" id="title" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" placeholder="<?php echo $tr->translate("SCORE_FOR_JANUARY");?>..." />
													<input type="hidden" name="branch_id" id="branch_id" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->row['branch_id']?>" />
													<input type="hidden" name="group" id="group" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->row['id']?>"/>
													<input type="hidden" name="gradingId" id="gradingId" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->row['gradingId']?>"/>
												</div>
											</div>
											 
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SCORE_FOR");?></label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<div class="col-md-4 col-sm-4 col-xs-12">
														<select id="examType" name="examType" class="fullside" onchange="checkExamType(); getAllSubject();"  dojoType="dijit.form.FilteringSelect" >
															<option value="1"><?php echo $tr->translate("MONTHLY");?></option>
															<option value="2"><?php echo $tr->translate("SEMESTER");?></option>
														</select>
													</div>
													<div class="col-md-4 col-sm-4 col-xs-12">
														<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="forSemester" name="forSemester" queryExpr="*${0}*" autoComplete="false">								
															<option value="1"><?php echo $tr->translate("SEMESTER1");?></option>
															<option value="2"><?php echo $tr->translate("SEMESTER2");?></option>
														</select>
													</div>
													<div class="col-md-4 col-sm-4 col-xs-12">
														<select onChange="duplicationRecord();" dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="forMonth" name="forMonth" queryExpr="*${0}*" autoComplete="false">								
															<?php if(!empty($this->month)){foreach ($this->month as $month){?>
																<option value="<?php echo $month['id']?>" <?php if($month['id']==$current_month){echo "selected='selected'";}?>><?php echo $month['month_kh']?></option>
															<?php }}?>
														</select>
													</div>
												</div>
											</div>
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SUBJECT");?></label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													
													<input id="subjectId" />
													<input type="hidden" name="maxSubjectScore" id="maxSubjectScore" class="fullside" dojoType="dijit.form.TextBox" value="0"/>
												</div>
											 </div>
											<div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SORT_STUDENT");?></label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<select id="sortStundent" name="sortStundent" class="fullside" onchange="filterStudent()"  dojoType="dijit.form.FilteringSelect" >
														<option value="0"><?php echo $tr->translate("DEFAULT");?></option>
														<option value="1"><?php echo $tr->translate("BY_STU_CODE_ASC");?></option>
														<option value="2"><?php echo $tr->translate("BY_STU_KHNAME_ASC");?></option>
														<option value="3"><?php echo $tr->translate("BY_STU_ENNAME_ASC");?></option>
													</select>
												</div>
											 </div>
											 <div class="form-group">
												<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?></label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<input class="fullside" placeholder="<?php echo $tr->translate("NOTE");?>" dojoType="dijit.form.Textarea"  id="note" name="note" value="" type="text" style=" height: 120px !important;"  >
												</div>
											 </div>
											 
										 </div>
									 </div>
								 </div>
							 </div>
							
								
								  
						  </div>
						  <div class="col-md-6 col-sm-6 col-xs-12">
								<div id="duplicateMessage" class="hidden alert round alert-secondary alert-icon-left alert-dismissible mb-3 " role="alert">
									<span class="alert-icon">
										<i class="glyphicon glyphicon-time text-dark"></i>
									</span>
									<span class="alert-text">
										<?php echo $duplicateMessage;?>
									</span>
									
								</div>
								<div class="card-info bg-gradient-directional-primary">
									<div class="card-content">
										<div class="card-body">
											<div class="media d-flex">
												<div class="media-body text-white text-left align-self-bottom ">
													<span class="d-block mb-1 font-medium-1"></span>
													<h3 class="text-white mb-10"><?php echo $tr->translate("GROUP_STUDENT_INFO");?></h3>
													<ul class="optListRow">
														<li class="opt-items two-column"><span class="lbl-tt"><?php echo $tr->translate("ACADEMIC_YEAR");?></span>: <span class="text-value"><?php echo $this->row['academic']?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt"><?php echo $tr->translate("DEGREE");?></span>: <span class="text-value"><?php echo $this->row['degree']?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt"><?php echo $tr->translate("ROOM");?></span>: <span class="text-value"><?php echo $this->row['room_name']?></span></li>
														<li class="opt-items two-column"><span class="lbl-tt"><?php echo $tr->translate("GRADE");?></span>: <span class="text-value"><?php echo $this->row['grade']?></span></li>
														
													</ul>
												</div>
												<div class="align-self-top">
												<i class="glyphicon glyphicon-briefcase icon-opacity text-white font-large-4 float-end"></i>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div id="gradingInfo">
								</div>
								
							 
								 
						  </div>
					 </div>
					 <div class="card-box">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<div id="studentList">
							</div>
							<input type="hidden" name="identity" id="identity"  value="" >
							<input type="hidden" dojoType="dijit.form.TextBox" name="indexKey" id="indexKey"  value="" >
							<div class="form-group">
								
								<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;width:100%" >
								</table>
							</div>
						</div>
				   </div>
				   <div class="clearfix"></div>
					 <div class="card-box mt-20">
						<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" />
							<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" id="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button"  />
						</div>
					 </div>
				</form>
			</div>
		</div>
	</div>
</div>
<style>
ul.optListRow.gradingInfo li {
    font-size: 11px;
    padding: 0;
}
th.criterialTitle {
    background: #c4d4eb;
}
tr.head-td th {
    vertical-align: top;
}
.lableEng {
    display: block;
    line-height: 12px;
}
small.small-label {
    font-size: 9px;
    line-height: 11px;
    margin-top: 2px;
    display: block;
}
span.titleSubCriterial {
    font-size: 9px;
    display: block;
    line-height: 12px;
    font-weight: 600;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
var isDuplicate=0;
$( document ).ready(function() {
   setPageTitle('<?php echo $pageTitle; ?>');
});
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require('dijit.form.NumberTextBox');
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,             
		id: "subjectId",
		name: "subjectId",           
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_SUBJECT");?>",          
		onChange: function() {
			getSubjectInfo();
		}
	}, "subjectId");
	
	getAllSubject();
});
urlGetSubjectStore = '<?php echo $this->url(array('module'=>'default','controller'=>'external','action'=>'getsubjectlist'));?>';
function getAllSubject(){
	dijit.byId('subjectId').reset();
	var subjectStore  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dijit.byId('subjectId').set('store',subjectStore); 
	
	group = dijit.byId('group').get('value');
	examType = dijit.byId('examType').get('value');
	
	dojo.xhrPost({
		url: urlGetSubjectStore,
		content:{
			'groupId':group,
			'examType':examType,
			},
		handleAs:"json",
		load: function(data) {
		    subjectStore  = getDataStorefromJSON('id','name', data);
		    dijit.byId('subjectId').set('store',subjectStore);   
		},
		error: function(err) {
		}
	});
}


var subject = <?php print_r(Zend_Json::encode($this->criterial));?>;
var urlGetSubjectInfo= '<?php echo $this->url(array('module'=>'default','controller'=>'external','action'=>'getsubjectinfo')); ?>';
function getSubjectInfo(){
	group = dijit.byId('group').get('value');
	subjectId = dijit.byId('subjectId').get('value');
	if(subjectId=='' || subjectId==0){
		$('#identity').val('');
		dojo.query("#table_row").append("");
		return false;
	}
	dojo.xhrPost({
	    url: urlGetSubjectInfo,
	    content : { 
			'groupId':group,
			'subjectId':subjectId,
		},				    
	   handleAs:"json", 
	   load: function(data) {
		   dijit.byId('maxSubjectScore').attr('value',data.maxSubjectscore);
		  
		   filterStudent();
		    duplicationRecord();
	   },		
	    error: function(err) {
	    }
	});
}

var inx=0;

var url_getStudent= '<?php echo $this->url(array('module'=>'issue','controller'=>'score','action'=>'get-student')); ?>';
var urlGetStudent= '<?php echo $this->url(array('module'=>'default','controller'=>'issuescore','action'=>'get-student')); ?>';
function filterStudent(){
	$('#identity').val('');
	dojo.query("#table_row").append("");
	loadingBlock();
	
	group = dijit.byId('group').get('value');
	sortStundent = dijit.byId('sortStundent').get('value');
	amtsubject = 0;
	examType = dijit.byId('examType').get('value');
	subjectId = dijit.byId('subjectId').get('value');
	gradingId = dijit.byId('gradingId').get('value');
	maxSubjectScore = dijit.byId('maxSubjectScore').get('value');
	
	if(group==''){
		return false;
	}
	dojo.xhrPost({
	    url: urlGetStudent,
	    content : { 
			'groupId':group
			,'sortStundent':sortStundent
			,'maxSubjectScore':maxSubjectScore
			,'subjectId':subjectId
			,'gradingId':gradingId
			,'keyIndex':inx
			
		},				    
	   handleAs:"json", 
	   load: function(data) {
		 
	       if(data!=""){
				
				inx=data.keyIndex;
				$("#identity").val(data.identity);
				
				dojo.html.set(dojo.byId("studentList"),data.contentHtml , {
					parseContent: true,
				});
				
				dojo.html.set(dojo.byId("gradingInfo"),data.htmlGradingInfo , {
					parseContent: true,
				});
				
				
	       }else{
		    	$('#identity').val('');
	       }
		   HideloadingBlock();	
	   },		
	    error: function(err) {
			HideloadingBlock();
	    }
	});
	
}

function deleteRecord(index){
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
function gender(sex){
	if(sex==1){
		sex='<?php echo $tr->translate('MALE');?>';
	}else sex='<?php echo $tr->translate('FEMALE');?>';
	return sex;
}
function checkExamType(){
	examType = dijit.byId("examType").get("value");
	dijit.byId('forMonth').set("readOnly",false);
	if(examType==2){
		dijit.byId('forMonth').set("readOnly",true);
	}
	duplicationRecord();
}


function checkAllCaterial(index){
	
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if($('#checkAll'+index).is(":checked")){
			dijit.byId('score_'+arrays[i]+'_'+index).attr('value',0);
			dijit.byId('score_'+arrays[i]+'_'+index).set("readOnly",true);
		}else{
			dijit.byId('score_'+arrays[i]+'_'+index).attr('value',0);
			dijit.byId('score_'+arrays[i]+'_'+index).set("readOnly",false);
		}
	}
}
var urlCalculateEverage= '<?php echo $this->url(array('module'=>'default','controller'=>'issuescore','action'=>'calculate-average')); ?>';
function calculateAverage(indexKey=null){
	dijit.byId('indexKey').attr('value',indexKey);
	if(dijit.byId('scoreForm').validate()){
		dojo.xhrPost({
			url: urlCalculateEverage,
			form: dojo.byId("scoreForm"),
		   handleAs:"json", 
		   load: function(data) {
			   if(indexKey!=null){
				   dijit.byId('average'+indexKey).attr('value',data);
			   }else{
				   var identity = $('#identity').val();
					var arrays = identity.split(',');
					for(var i=0;i<arrays.length;i++) {
						keyRow = +arrays[i];
						dijit.byId('average'+keyRow).attr('value',data[keyRow]);
					}
			   }
			   
		   },		
			error: function(err) {
			}
		});
	}	
}



var urlDuplicationRecord= '<?php echo $this->url(array('module'=>'default','controller'=>'issuescore','action'=>'checking-duplicate')); ?>';
function duplicationRecord(){
	
	
	group = dijit.byId('group').get('value');
	examType = dijit.byId('examType').get('value');
	subjectId = dijit.byId('subjectId').get('value');
	forSemester = dijit.byId('forSemester').get('value');
	forMonth = dijit.byId('forMonth').get('value');
	
	if(group==''){
		return false;
	}
	dojo.xhrPost({
	    url: urlDuplicationRecord,
	    content : { 
			'groupId':group
			,'subjectId':subjectId
			,'examType':examType
			,'forSemester':forSemester
			,'forMonth':forMonth
			
		},				    
	   handleAs:"json", 
	   load: function(data) {
		 
	       if(data==1){
				isDuplicate=1;
				var htmlString = $( '.alert-text' ).html();
				alert(htmlString);
				$( "#duplicateMessage" ).removeClass( "hidden" );
	       }else{
		    	isDuplicate=0;
				$( "#duplicateMessage" ).addClass( "hidden" );

	       }
		  
		   HideloadingBlock();	
	   },		
	    error: function(err) {
			HideloadingBlock();
	    }
	});
	
}
</script>
<?php 
	echo $this->render('externalFoot.phtml');
?>