<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_NEW_STUDENT_SCOREENG"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>	

<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		   			<h4 class="m-b-0"><i class="fa fa-file-text-o " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_NEW_STUDENT_SCOREENG');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='office_receipt' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
   			if(this.validate()) {
				var rowId = $('#identity').val();
				if(rowId==''){ 
					alert("<?php echo $tr->translate('NO_RECORD_TO_SUBMIT');?>");
					return false;
				}
				var txt;
				var r = confirm("Are you sure to submit ?");
				if (r == true) {
    				 dijit.byId('save_new').set('disabled',true);
					 loadingBlock();
    				 return true;
				} else {
  					  return false;
				}
   			}else {
    			return false;
   			}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-file-text-o" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT_SCORE_ENG");?></p>
										</div> 
									</div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select class="fullside" tabindex="15" name="branch_id" queryExpr="*${0}*" autoComplete="false" id="branch_id" dojoType="dijit.form.FilteringSelect" onchange="getAllAcademicByBranch(); getAllGroupByBranch(); getScoreSetting();">
												<?php if(!empty($this->row_branch))foreach ($this->row_branch as $row){?>
												<option value="<?php echo $row['id']?>"><?php echo $row['name']?></option>
												<?php }?>
											</select>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ITEMS_SCORE_ENG");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="scoreSetting" />
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDY_YEAR");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="study_year" />
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="group">
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TITLE");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" name="title" id="title" class="fullside" required="1" dojoType="dijit.form.ValidationTextBox" />
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("FOR_DATE");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" constraints="{datePattern:'dd/MM/yyyy'}" name="for_date" id="for_date" class="fullside" value="now" required="1" dojoType="dijit.form.DateTextBox" />
										</div>
									 </div>
									 <div class="form-group">
											<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<textarea dojoType="dijit.form.Textarea" class="fullside"  style=" height: 60px !important;" tabindex="20" dojoType=""  id="note" name="note"  ></textarea>
											</div>
									 </div>
								 </div>
							 </div>
						 </div>
					 </div>
		          </div>
		          <div class="col-md-6 col-sm-6 col-xs-12">
						<div id="gr-info"></div>
						<div id="score-info"></div>
		          </div>
		     </div>
		     <div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12">
		    		<div class="form-group">
		    			<input type="hidden" name="identity" id="identity"  value="" >
		    			<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;width:100%" >
						</table>
		    		</div>
		    	</div>
		   </div>
	       <div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" id="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button"  />
               	</div>
             </div>
		</form>
	</div>
</div>
<style>
	select{ width:100%;}
	tr.hover td.verites-col,
	td.verites-col {
	    text-align: center;
	    white-space: nowrap;
	    g-origin: 50% 50%;
	    -webkit-transform: rotate(270deg);
	    -moz-transform: rotate(270deg);
	    -ms-transform: rotate(270deg);
	    -o-transform: rotate(270deg);
	    transform: rotate(270deg);
	}
	tr.hover td.verites-col span.verites,
	td.verites-col span.verites {
	     margin: 0 -85%;
	    display: inline-block;
	}
	tr.hover td.verites-col span.verites:before,
	td.verites-col span.verites:before {
	    content: '';
	    width: 0;
	    padding-top: 110%;
	    display: inline-block;
	    vertical-align: middle;
	}
</style>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require('dijit.form.Textarea');
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.DateTextBox");
	dojo.require('dijit.form.NumberTextBox');

var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var scoreSetting_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	var subject = [];
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
			getAllGroupByAcademic();
		}
	}, "study_year");
	
	new dijit.form.FilteringSelect({
	    store:scoreSetting_store,		                    
	    required: true,
	    queryExpr: "*${0}*",
		autoComplete: false,     			
	    id: "scoreSetting",
	    name: "scoreSetting",           
	    class: 'fullside',  
	    required:'true',
	    onChange: function() {  
		    getDetailScoreSetting();
	    }
	}, "scoreSetting");
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,             
			id: "group",
			name: "group",           
			class: 'fullside', 
			placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
			onChange: function() {
				getInfoBygroup();
				filterStudent();
			}
		}, "group");
		getAllGroupByBranch();
		getAllAcademicByBranch();
		getScoreSetting();
});

url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	
		contentData = {
			'branch_id':branch_id
		}
		getAllYear(url_getacademic,contentData,null,'study_year');
}

var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_scoresetting = '<?php echo $this->url(array('module'=>'issue','controller'=>'scoreeng','action'=>'get-scoresetting')); ?>';
function getScoreSetting(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('scoreSetting').reset();
	dojo.xhrPost({
		url: url_scoresetting,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			scoreSetting_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('scoreSetting').set('store',scoreSetting_store);  
		},
		error: function(err) {
		}
	});
}
var url_scoresettingdetail = '<?php echo $this->url(array('module'=>'issue','controller'=>'scoreeng','action'=>'get-scoresettingdetail')); ?>';
function getDetailScoreSetting(){
	scoreSetting = dijit.byId('scoreSetting').get('value');
	if(scoreSetting==''){
		dojo.byId("score-info").innerHTML = '';
		subject ='';
		filterStudent();
		return false;
	}
	dojo.xhrPost({
		url: url_scoresettingdetail,
		content:{
			'scoreSetting':scoreSetting
			},
		handleAs:"json",
		load: function(data) {
			subject = data;
			var string='';
			if(data!=''){
				
				string+='<div class="card-info bg-gradient-directional-warning">';
					string+='<div class="card-content">';
						string+='<div class="card-body">';
							string+='<div class="media d-flex">';
								string+='<div class="media-body text-white text-left align-self-bottom mt-3">';
									string+='<span class="d-block mb-1 font-medium-1"></span>';
									string+='<h3 class="text-white mb-10"><?php echo $tr->translate("SCORE_POLICY");?></h3>';
											string+='<ul class="optListRow">';
											for(j=0;j<subject.length;j++){
												stringsname = subject[j].name;
												string+='<li class="opt-items two-column"><span class="lbl-tt">'+stringsname+'</span>: <span class="text-value">'+subject[j].pecentage_score+'%</span></li>';
											}
											string+='</ul>';
								string+='</div>';
								string+='<div class="align-self-top">';
									string+='<i class="glyphicon glyphicon-folder-open icon-opacity text-white font-large-4 float-end"></i>';
								string+='</div>';
							string+='</div>';
						string+='</div>';
					string+='</div>';
				string+='</div>';

			}
			dojo.byId("score-info").innerHTML = string;
			filterStudent();
		},
		error: function(err) {
		}
	});
}

var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'issue','controller'=>'score','action'=>'get-grade')); ?>';
function filterGrade(){
	degree = dijit.byId('degree').get('value');
		dojo.xhrPost({
			url:url_dept,
			content:{
				'degree':degree
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);  
			    dijit.byId('grade').set('value',dijit.byId('grade_fromgrouop').get('value'));
			},
			error: function(err) {
			}
		});
}
var inx=0;
var url_getStudent= '<?php echo $this->url(array('module'=>'issue','controller'=>'score','action'=>'get-student')); ?>';
function filterStudent(){
	$('#identity').val('');
	dojo.query("#table_row").append("");
	loadingBlock();
	group = dijit.byId('group').get('value');
	if(group==''){
		HideloadingBlock();
		return false;
	}
	//if(subject==''){
		//HideloadingBlock();
		//return false;
	//}
	dojo.xhrPost({
	    url: url_getStudent,
	    content : { 
			'group':group,
		},				    
	   handleAs:"json", 
	   load: function(data) {
		   if(data==''){
			   alert('<?php echo $tr->translate('NO_RECORD');?>');
			   return false;
		   }
		   tem="";
		   temp='';
	       if(data!=""){
				num =0;
				title=0;
				temp='';
				str='';
				column = 0;
				temp='<table class="collape responsiveTable" style="table-layout: fixed;" id="table" >'
					+'<thead><tr class="head-td" align="center">'
					+'<td scope="col" width="4%" class="tdheader" ><?php echo $tr->translate('DEL');?></td>'
					+'<td scope="col" class="tdheader" ><?php echo $tr->translate('NO');?></td>'
					+'<td scope="col" class="tdheader header" style="width:100px;"><?php echo $tr->translate('STUDENT_ID');?></td>'
					+'<td scope="col" class="tdheader header" style="width:100px;"><?php echo $tr->translate('STUDENT_NAME');?></td>'
					+'<td scope="col" class="tdheader header"><?php echo $tr->translate('SEX');?></td>'
					no=0;
				  for(j=0;j<subject.length;j++){
	      			  no++;
	      			  stringsname = subject[j].name.replace(' ','');
		      	      temp+='<td scope="col" class="verites-col" title="'+stringsname+'"><span class="verites">&nbsp;'+no+'-'+stringsname+'&nbsp;</span></td>';
	              }
				  temp+='<td  scope="col" class="text-center">&nbsp;<?php echo $tr->translate('NOTE');?></td>'+'</tr>';
				  temp+='<tr style="border: 1px #4839bd solid;background: #fdbdbd;display:none;">';
					  temp+='<td>&nbsp;</td>';
					  temp+='<td>&nbsp;</td>';
					  temp+='<td>&nbsp;</td>';
					  temp+='<td>&nbsp;</td>';
					  temp+='<td>&nbsp;</td>';
					  no=0;
					  for(j=0;j<subject.length;j++){
		      			  no++;
		      			  stringsname = subject[j].name.replace(' ','');
			      	      temp+='<td title="'+stringsname+'"><input  checked="checked" style=" display: inline-block; height: 15px; margin-right: 10px;" type="checkbox" onClick="CheckSubjectExam('+subject[j].id+');"  class="checkbox" id="subject'+subject[j].id+'" value="'+subject[j].id+'"  name="selector[]"/></td>';
		              }
				  	  temp+='<td>&nbsp;</td>';
				  temp+='</tr>';
				  temp+='</thead>';
				  
				for(i=0;i<data.length;i++){
					num++;
					inx = inx+1;
					temp +='<tr class="rowData" id="row'+inx+'">';
					temp +='<td data-label="<?php echo $tr->translate("REMOVE_RECORD");?>" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD");?>" class="removeRow" onclick="deleteRecord('+inx+')"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span></td>';
					temp +='<td data-label="<?php echo $tr->translate("NO");?>" align="center">'+inx+'</td>';
					temp +='<td data-label="<?php echo $tr->translate("STUDENT_ID");?>">'+data[i].stu_code+'<input dojoType="dijit.form.TextBox" name="student_id'+inx+'"   value="'+data[i].stu_id+'" type="hidden" ></td>';
					temp +='<td data-label="<?php echo $tr->translate("STUDENT_NAME");?>" style="min-width:100px;">&nbsp;'+data[i].stu_name+'&nbsp;</td>';
					temp +='<td data-label="<?php echo $tr->translate("SEX");?>">&nbsp;'+gender(data[i].sex)+'&nbsp;</td>';
					for(j=0;j<subject.length;j++){
						stringsname = subject[j].name.replace(' ','');
						temp += '<td data-label="'+stringsname+'" id="score_'+j+'"><input required="1" class="fullside" onKeyUp="checkScore('+inx+','+subject[j].id+');" dojoType="dijit.form.NumberTextBox" type="text" id="score_'+inx+'_'+subject[j].id+'"  name="score_'+inx+'_'+subject[j].id+'" /><input dojoType="dijit.form.TextBox" value="'+subject[j].pecentage_score+'" name="max_score_'+inx+'_'+subject[j].id+'" id="max_score_'+inx+'_'+subject[j].id+'" type="hidden" ></td>';
					}
					temp += '<td data-label="<?php echo $tr->translate("NOTE");?>"><input dojoType="dijit.form.TextBox" class="fullside" name="note_'+inx+'"  value="" type="text" ></td>';
					temp+= '</tr>';
					
					var no=0;
				    if($("#identity").val()!="") {
						var identity = $("#identity").val();
						$("#identity").val(identity+','+inx);
					} else {$("#identity").val(inx);}
					
				}
				temp+='</table>';
				tmp='<tr id="row'+inx+'">';
				tmp+="</tr>";
				dojo.query("#table_row").append(tmp);
				dojo.html.set(dojo.byId("row"+inx),temp , {
				     parseContent: true,
				});
	       }else{
		    	$('#identity').val('');
	       }
	   },		
	    error: function(err) {
	    }
	});
	HideloadingBlock();
}

function checkScore(index,subject_id){
	score_input = dijit.byId('score_'+index+'_'+subject_id).get('value');
	max_score = dijit.byId('max_score_'+index+'_'+subject_id).get('value');
	if(score_input>max_score){
		alert("Can not input bigger than max score = "+max_score);
		dijit.byId('score_'+index+'_'+subject_id).attr('value',max_score);
	}
}
function CheckSubjectExam(subject_id){
	var rowId = $('#identity').val();
	var amountsub = $(".checkbox:checked").length;
	if ($('#subject'+subject_id).is(':checked')) {
		if(rowId!=''){ 
			var rowIDArray = rowId.split(',');
			for(var b = 0; b < rowIDArray.length; b++){
				dijit.byId('score_'+rowIDArray[b]+'_'+subject_id).set('disabled',false);
				dijit.byId('score_'+rowIDArray[b]+'_'+subject_id).attr('value',0);
				dijit.byId('score_'+rowIDArray[b]+'_'+subject_id).set('required',true); 
			}
		}
	}else{
		if(rowId!=''){ 
			var rowIDArray = rowId.split(',');
			for(var b = 0; b < rowIDArray.length; b++){
				dijit.byId('score_'+rowIDArray[b]+'_'+subject_id).set('disabled',true);
				dijit.byId('score_'+rowIDArray[b]+'_'+subject_id).attr('value',0);
				dijit.byId('score_'+rowIDArray[b]+'_'+subject_id).set('required',false); 
			}
		}
	}
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
function gender(sex){
	if(sex==1){
		sex='Male';
	}else sex='Female';
	return sex;
}
</script>
<script> //validate controll form 
function getInfoBygroup(){
		url_group = '<?php echo $this->url(array('module'=>'issue','controller'=>'scoreeng','action'=>'getgroupinfo'));?>';
		group = dijit.byId('group').get('value');
		if(group==''){
			alert("<?php echo $tr->translate("PLEASE_SELECT_GROUP");?>");
			return false;
		}
		dojo.xhrPost({
			url:url_group,	
			content:{ 
				'group_id': group,'string':1
			},
			handleAs:"json",
			load: function(data) {
				string='';
				string+='<div class="card-info bg-gradient-directional-warning">';
					string+='<div class="card-content">';
						string+='<div class="card-body">';
							string+='<div class="media d-flex">';
								string+='<div class="media-body text-white text-left align-self-bottom mt-3">';
									string+='<span class="d-block mb-1 font-medium-1"></span>';
									string+='<h3 class="text-white mb-10"><?php echo $tr->translate("GROUP_STUDENT_INFO");?></h3>';
										string+=data;
								string+='</div>';
								string+='<div class="align-self-top">';
									string+='<i class="glyphicon glyphicon-briefcase icon-opacity text-white font-large-4 float-end"></i>';
								string+='</div>';
							string+='</div>';
						string+='</div>';
					string+='</div>';
				string+='</div>';
				dojo.byId("gr-info").innerHTML = string;
			},
			error: function(err) {
			}
		});
}
//url_getgroup = '<?php //echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	study_year = dijit.byId('study_year').get('value');
	if(study_year=='' || study_year==-1){
		study_year = null;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,
			'academic_year':study_year,
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		},
		error: function(err) {
		}
	});
}
url_getgroupbyAca = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
function getAllGroupByAcademic(){
	getAllGroupByBranch();
}
</script>