<?php
	$request = Zend_Controller_Front::getInstance ()->getRequest ();
	$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
	$frm =  $this->frm_items;
	$urlCopy = $this->baseUrl()."/stock/productset/copy/id/";
	$urlEdit = $this->baseUrl()."/stock/productset/edit/id/";
?>
<title><?php echo $tr->translate("PRODUCTSET");?></title>
<meta charset="utf-8">
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-cubes " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('PRODUCTSET');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<div class="card-box">
			<form action="<?php echo $this->url(array('module'=>'stock','controller'=>'productset','action'=>'index')); ?>"
				dojoType="dijit.form.Form" method="post">
				<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("advance_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("items_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("status_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"
							showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 if(id!=''){
			window.location.href = url+'/id/'+id;
		 }else{
			alert('Please select record you want to copy');
			return false;
		 }
	}
	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}

	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}else if(key=="copy"){
					url='<?php echo $urlCopy;?>';
				}
				gotoAction();
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
				"copy": {name: "<?php echo $tr->translate("COPY");?>", icon: "copy"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.location.href =url+row;
	}
</script> 