
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('USERACCOUNT'));
	echo $this->headTitle(''); 
	$url_copy =$this->url(array('module'=>'foundation','controller'=>'register','action'=>'copy'));
	$formList = new Application_Form_Frmtable();
	$frm =  $this->form_search;
?>	
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<input dojoType="dijit.form.TextBox"   id="adv_search" name="adv_search" placeholder="<?php echo $tr->translate('SEARCH');?>....." value="<?php echo $this->adv_search['adv_search']; ?>" class="fullside" type="text">
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		 <?php echo $frm->getElement("study_year");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("degree");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		 <?php echo $frm->getElement("grade_all");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("session");?>
	            	</div>
	            </div>
	            <div class="form-group">
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("start_date");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("end_date");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("user");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<select name="status" id="status" class="fullside" dojoType="dijit.form.FilteringSelect"  >
							<option value=""><?php echo $tr->translate('STATUS')?></option>
							<option value="1"><?php echo $tr->translate('ACTIVE')?></option>
							<option value="0"><?php echo $tr->translate('DEACTIVE')?></option>
						</select>	
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
	           			 <input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
	           		</div>
	            </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");

	
</script> 
