
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('REGISTER'));
	echo $this->headTitle(''); 
	$url_copy =$this->url(array('module'=>'foundation','controller'=>'register','action'=>'copy'));
	$formList = new Application_Form_Frmtable();
	$frm =  $this->form_search;
?>	
<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table style="width:100%">
	  <tr> 
			<td><input dojoType="dijit.form.TextBox"   id="adv_search" name="adv_search" placeholder="Search....." value="<?php echo $this->adv_search['adv_search']; ?>" class="fullside" type="text"></td>
			<td> <?php echo $frm->getElement("study_year");?></td>
			<td> <?php echo $frm->getElement("degree");?></td>
			<td> <?php echo $frm->getElement("grade_all");?></td>
			<td> <?php echo $frm->getElement("session");?></td>
	  </tr>
	  <tr>
	  		<td><?php echo $frm->getElement("start_date");?></td>
	 		<td><?php echo $frm->getElement("end_date");?></td>
			<td> <?php echo $frm->getElement("user");?></td>
			<td>
				<select name="status" id="status" class="fullside" dojoType="dijit.form.FilteringSelect"  >
					<option value=""><?php echo $tr->translate('STATUS')?></option>
					<option value="1"><?php echo $tr->translate('ACTIVE')?></option>
					<option value="0"><?php echo $tr->translate('DEACTIVE')?></option>
				</select>			
			</td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	  </tr>
	  <input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
	 </table>
	 
</form>
<?php echo $this->list;?>

<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");

	
</script> 
