<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('EDIT_STUDENT_REGISTER')); 
	echo $this->headTitle(''); 
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<style>
.b{ font-weight: bold; }
</style>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.ready(function(){
	 
}); 
 
</script>
 
		<table width="100%">
		      <tr>
		           <td></td>
			       <td>
						<div class="menureport">
							<ul>
								<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
								<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
								<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
							</ul>
						</div>
			      </td>
			</tr>
		   </table>
		<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
			
			<div id="divPrint">
				<table width="100%" style="font-size:12px;font-family:Tahoma,'Khmer OS Battambang';"> 
					<tr>
						<td>
						   <table width="100%" >
						   			<tr>
										<td width="28%" align="left">
											<img style="height:100px;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
										</td>
										<td align="center" width="44%"  >
											<strong style="font-weight:bold;color:#000; font-size: 14px;font-family:'Khmer OS Muol';"><?php echo $tr->translate("STUDENT_BACKGROUND"); ?></strong><br />
											<span style="font-weight: bold;font-size: 12px; font-family:'Khmer OS Battambang';">&nbsp; For Date &nbsp; <?php echo date("d-M-Y");?></span><br /><br />
										</td>
										<td width="28%" align="right">
										</td>
									</tr>
						   </table>
						   <?php $sex='';
									      if($this->rs['sex']==1){
									      	$sex=$tr->translate("MALE");
										  }else{
										  	$sex=$tr->translate("FEMALE");
										  }
									?>
					      	<table  cellspacing="5"  style="background:#fff;margin: 0 auto;width: 100%;font-size:12px;font-family:Tahoma,'Khmer OS Battambang';" >
					      		<tr>
					     	         <td colspan="6" style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("STUDENT_INFO");?></strong></td>
					     	    </tr>
					      		<tr  >
					      		    <td rowspan="3"   >
					      		       <?php 
					      		            $photo='user.jpg';
					      		            if(!empty($this->rs['photo'])){
					      		            	$photo=$this->rs['photo'];
					      		            }
					      		            
					      		       ?>
										 <div style="width:100px;padding:3px;"><img src="<?php echo $this->baseUrl();?>/images/<?php echo $photo;?>" style="width:100px;max-height: 120px;"/></div>
					      		    </td>
					      		      <td style="width:60%;" colspan="4">
					      		       <br/> <br/><br/> 
					      		         <table width="120%" style="font-size:12px;font-family: 'Khmer OS Battambang';">
					      		               <tr>
					      		                   <td><?php echo $tr->translate("NAME_KH");?>:&nbsp;<label><?php echo $this->rs['stu_khname'];?></label> </td>
					      		                   <td><?php echo $tr->translate("NAME_EN");?>:&nbsp; <label><?php echo $this->rs['stu_enname'];?></label> </td>
					      		                   <td><?php echo $tr->translate("NATIONALITY");?>:&nbsp; <label><?php echo $this->rs['nationality'];?></label></td>
					      		               </tr>
					      		               <tr>
					      		                   <td> <?php echo $tr->translate("SEX");?>:&nbsp; <label><?php echo $sex?></label></td>
					      		                   <td> <?php echo $tr->translate("DOB");?>:&nbsp; <label><?php echo empty($this->rs['dob'])?"":date("d/m/Y",strtotime($this->rs['dob']));?></label> </td>
					      		                   <td><?php echo $tr->translate("PHONE");?>:&nbsp; <label><?php echo $this->rs['tel'];?></label> </td>
					      		               </tr>
					      		                 <tr>
					      		                   <td><?php echo $tr->translate("EMAIL_ADDRESS");?>:&nbsp;<label><?php echo $this->rs['email'];?></label> </td>
					      		                   <td colspan="2"><?php echo $tr->translate("POB");?>:&nbsp;<label><?php echo $this->rs['pob'];?></label><?php echo $tr->translate("SYMBOL");?></td>
					      		               </tr>
					      		         </table>
									</td>
					      		</tr>
					      		<tr >  </tr>
					      		<tr> </tr>
					      		<tr>
					      			<td colspan="6"​ style="border-bottom:1px solid #ddd;" class="b"><strong><?php echo $tr->translate("CURRENT_ADDRESS");?></strong></td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("HOME");?>:</td>
									<td><label><?php echo $this->rs['home_num'];?></label>  </td>
									<td><?php echo $tr->translate("STREET");?>:</td>
									<td><label><?php echo $this->rs['street_num'];?></label> </td>
									<td><?php echo $tr->translate("VILLAGE");?>:</td>
									<td><label><?php echo $this->rs['village_name'];?></label></td>
								</tr>
								<tr>								
									<td><?php echo $tr->translate("COMMUNE");?>:</td>
									<td><label><?php echo $this->rs['commune_name'];?> </td>
									<td><?php echo $tr->translate("DISTRICT");?>:</td>
									<td><label><?php echo $this->rs['district_name'];?></label> </td>
									<td><?php echo $tr->translate("PROVINCE");?>:</td>
									<td><label><?php if(!empty($this->rs['province_name'])) echo $this->rs['province_name'];?></label>
									</td>
								</tr>
					      		<tr>
					      			<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("STUDY_INFO");?></strong></td>
					      		</tr>
					      		<tr>
					      			<td title="បញ្ជូលលេខសំគាល់និស្សិត"><?php echo $tr->translate("ACADEMIC_YEAR");?>:</td>
									<td><label><?php //echo $this->rs['year_name'];?></label> </td>
									<td><?php echo $tr->translate("DEGREE");?>:</td>
									<td><label><?php echo $this->rs['degree_name'];?></label> </td>
									<td><?php echo $tr->translate("GRADE");?>:</td>
									<td><label><?php echo $this->rs['grade_name'];?></label> </td>
								</tr>
								<tr>
									<td title="បញ្ជូលលេខសំគាល់និស្សិត"><?php echo $tr->translate("STUDENT_ID");?>:</td>
									<td><label><?php echo $this->rs['stu_code']; ?></label></td>
									<td><?php echo $tr->translate("STUDY_TIME");?>:</td>
									<td><label><?php //echo $this->rs['day_name'].'('.$this->rs['time_study'].')';?></label> </td>
									<td title="កំរិតភាសា"><?php echo $tr->translate("TIME");?>:</td>
									<td nowrap><label><?php //echo $this->rs['time_study'];?></label></td>
								</tr>
					      		<tr>
								    <td title="កំរិតភាសា"><?php echo $tr->translate("LANGUAGE_LEVEL");?>:</td>
									<td><label><?php //echo $this->rs['lang_name'];?></label></td>
					      			<td title="ស្ថានការណ៍"><?php echo $tr->translate("STATUS");?>:</td>
					      			<?php $status='';
					      			      if($this->rs['status']==1){
					      			      	$status=$tr->translate("ACTIVE");
					      			      }else {
					      			      	$status=$tr->translate("DEACTIVE");
					      			      }
					      			?>
									<td> <label><?php echo $status;?></label> </td>
									<td title="ពណ៌នា"><?php echo $tr->translate("REMARK");?>:</td>
									<td>
									    <label><?php echo $this->rs['remark'];?></label>
									</td>
					      		</tr>
					      	</table>
					     	<table width="100%" style="margin:0 auto;font-size:12px;font-family: 'Khmer OS Battambang';" cellspacing="5">
					      		<tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;" class="b"><strong><?php echo $tr->translate("FATHER_INFO");?></strong></td>
								</tr>
					      		<tr>
					      			<td ><?php echo $tr->translate("NAME_KH");?>:</td>
									<td><label><?php echo $this->rs['father_khname'];?></label> </td>
									<td ><?php echo $tr->translate("NAME_EN");?>:</td>
									<td><label><?php echo $this->rs['father_enname'];?></label> </td>
									<td><?php echo $tr->translate("AGE");?>:</td>
									<td><label><?php //echo $this->rs['father_old'];?></label> </td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("NATIONALITY");?>:</td>
					      			<td><label><?php echo $this->rs['father_nation'];?></label> </td>
					      			<td><?php echo $tr->translate("OCCUPATION");?>:</td>
									<td><label><?php echo $this->rs['fa_job'];?></label> </td>
									<td><?php echo $tr->translate("PHONE");?>:</td>
									<td><label><?php echo $this->rs['father_phone'];?></label> </td>
								</tr>
								<tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;" class="b"><strong><?php echo $tr->translate("MOTHER_INFO");?></strong></td>
								</tr>
					      		<tr>
					      			<td ><?php echo $tr->translate("NAME_KH");?>:</td>
									<td><label><?php echo $this->rs['mother_khname'];?></label> </td>
									<td ><?php echo $tr->translate("NAME_EN");?>:</td>
									<td><label><?php echo $this->rs['mother_enname'];?></label> </td>
									<td><?php echo $tr->translate("AGE");?>:</td>
									<td><label><?php //echo $this->rs['mother_old'];?></label> </td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("NATIONALITY");?>:</td>
								    <td><label><?php echo $this->rs['mother_nation'];?></label> </td>
					      			<td><?php echo $tr->translate("OCCUPATION");?>:</td>
									<td><label><?php echo $this->rs['mo_job'];?></label></td>
									<td><?php echo $tr->translate("PHONE");?>:</td>
									<td><label><?php echo $this->rs['mother_phone'];?></label> </td>
								</tr>
								<tr>
									<td colspan="6" style="border-bottom:1px solid #ccc;" class="b"><strong><?php echo $tr->translate("GUARDIAN_INFO");?></strong></td>
								</tr>
					      		<tr>
					      			<td ><?php echo $tr->translate("NAME_KH");?>:</td>
									<td><label><?php echo $this->rs['guardian_khname'];?></label> </td>
									<td ><?php echo $tr->translate("NAME_EN");?>:</td>
									<td><label><?php echo $this->rs['guardian_enname'];?></label> </td>
									<td><?php echo $tr->translate("AGE");?>:</td>
									<td><label><?php //echo $this->rs['guardian_old'];?></label> </td>
					      		</tr>
					      		<tr>
					      			<td><?php echo $tr->translate("NATIONALITY");?>:</td>
								    <td><label><?php echo $this->rs['guardian_nation'];?></label> </td>
					      			<td    nowrap><?php echo $tr->translate("IDENTITTY_PASSPORT_NO");?>:</td>
									<td><label><?php echo $this->rs['guardian_document'];?></label> </td>
					      			<td><?php echo $tr->translate("OCCUPATION");?>:</td>
									<td><label><?php echo $this->rs['gu_job'];?></label> </td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("PHONE");?>:</td>
									<td><label><?php echo $this->rs['guardian_tel'];?></label> </td>
									<td><?php echo $tr->translate("EMAIL_ADDRESS");?>:</td>
									<td><label><?php echo $this->rs['guardian_email'];?></label> </td>
								</tr>
							</table>
					   </td>
					</tr>
					<tr>
						<td align="center">
							<table width="100%">
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr >
									<td align="center" width="25%">
										<span style="font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY"); ?></span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY"); ?></span>
									</td>
								</tr>
							</table>
					   	</td>
					  </tr>
	   </table>
	   </div>
	 </div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>

