<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_SUSPEND_SERVICE')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	
	dojo.ready(function(){ 
		new dijit.form.FilteringSelect({
		    store: student_id_store,
		    autoComplete: true,                        
		    required: true,
		    id: "studentid",
		    name: "studentid",           
		    class: 'fullside',  
		    placeHolder:"Selected Student id",          
		    onChange: function() {  
		    	setID(1);
		    	getStudentService();
		    }
		}, "studentid");
		
		new dijit.form.FilteringSelect({
		    store: student_name_store,
		    autoComplete: true,                        
		    required: true,
		    id: "student_name",
		    name: "student_name",           
		    class: 'fullside',  
		    placeHolder:"Selected Student Name",          
		    onChange: function() {  
		    	setID(2); 
		    }
		}, "student_name");
	});	

</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_servicesuspend;
//print_r($register);
?>
<form id='suspend_service' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'suspendservice','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit" enctype="multipart/form-data">			
	if(this.validate()) {
                study_year=dijit.byId('study_year').get('value');
                  if(study_year==0 || study_year==''){
                        alert('Please Select Study Year');
                        dijit.byId('study_year').focus();
                        return false;
					}
				dijit.byId('save_new').set('disabled',true);
			    dijit.byId('save_close').set('disabled',true);
				return true;
			} else {
				return false;
			}
</script>
<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_SUSPEND_SERVICE");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" >
						<tr>
							<td style="width: 160px"><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
							<td><?php echo $register->getElement('study_year');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td>
								<input id="studentid" />
							</td>	
							<td><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td>
								<input id="student_name" />
							</td>
						</tr>
						
						<tr>
							<td colspan="4">
							 	<div  id="showrecord"></div>
							 	<table id="table_row" border="1" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="2"><input type="hidden" id="identity" name="identity" /></td>
						</tr>
						<tr>
							<td colspan="4" align="left">
								<!--  	<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
								 -->
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
								<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
								<input type="submit" name="save_close" id="save_close" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								 <input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>


<script type="text/javascript">

var template = '';
var metion = '<?php echo $this->all_metion; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';
var service = '<?php echo $this->all_service; ?>';

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("TYPE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("REASON");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DATE_BACK");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("NOTE");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="30px" align="center">'+no+'</td>';
			template+='<td><select style="width:100%;"  dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			
			template+='<td><select dojoType="dijit.form.FilteringSelect" id="type_'+col+'" onchange="dateReadonly('+col+');" name="type_'+col+'" style="width:100%;"><option value="1">Suspend</option><option value="2">Stop</option></select></td>';
			template+='<td> <input type="text"   name="reason_'+col+'" id="reason_'+col+'" dojoType="dijit.form.TextBox" style="width:100%;" /><label id="subsub"></label></td>';
			template+='<td><input style="width:100%;" value="now" dojoType="dijit.form.DateTextBox" id="date_'+col+'" name="date_'+col+'" /></td>';
			template+='<td> <input type="text"   name="note_'+col+'" id="note_'+col+'" dojoType="dijit.form.TextBox" style="width:100%;" /></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }

function dateReadonly(key) {
	condition = dijit.byId('type_'+key).get('value');
	if(condition==2){
		dijit.byId("date_"+key).set('readOnly',true);
		$('#date_'+key).val('');
	}else{
		dijit.byId("date_"+key).set('readOnly',false);
		dijit.byId('date_'+col).attr('value','<?php echo date('Y-m-d')?>');
	}
}

var url_servict_info = "<?php echo $this->url(array('module'=>'accounting','controller'=>'suspendservice','action'=>'get-student-service')); ?>";
fund_title=0;
function getStudentService(){
	temp='';
	stu_id  = dijit.byId('studentid').get('value');
	fund_title=0;
	dojo.query("#showrecord").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style=" margin-top: 20px; border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; font-size: 14px; height: 40px;font-weight: bold; margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	dojo.xhrPost({
		url: url_servict_info,
		content:{
			'studentid':stu_id
		},
		handleAs:"json",
		load: function(data) {
			$('#identity').val('');
			if(data==''){
				alert('Student can not item !');
				thead='<th style="margin-bottom: 20px;"><?php echo $tr->translate("DEL");?></th>';
				thead+='<th style="width:10px;"><?php echo $tr->translate("N_O");?></th>';
				thead+='<th ><?php echo $tr->translate("SERVICES");?></th>';
				thead+='<th ><?php echo $tr->translate("TYPE");?></th>';
				thead+='<th ><?php echo $tr->translate("REASON");?></th>';
				thead+='<th ><?php echo $tr->translate("DATE_BACK");?></th>';
				thead+='<th ><?php echo $tr->translate("NOTE");?></th>';
				fund_title=1;
				dojo.query("#head_title").append(thead);
			}
		
			for(i=0;i<data.length;i++){
				col++;no++;
				if(fund_title!=1){
					thead='<th style="margin-bottom: 20px;"><?php echo $tr->translate("DEL");?></th>';
					thead+='<th style="width:10px;"><?php echo $tr->translate("N_O");?></th>';
					thead+='<th ><?php echo $tr->translate("SERVICES");?></th>';
					thead+='<th ><?php echo $tr->translate("TYPE");?></th>';
					thead+='<th ><?php echo $tr->translate("REASON");?></th>';
					thead+='<th ><?php echo $tr->translate("DATE_BACK");?></th>';
					thead+='<th ><?php echo $tr->translate("NOTE");?></th>';
					fund_title=1;
					dojo.query("#head_title").append(thead);
				}
				 
				temp='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				temp+='<td width="15px" align="center">'+no+'</td>';
				temp+='<td><select style="width:100%;"  dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';
				temp+='<td><select dojoType="dijit.form.FilteringSelect" id="type_'+col+'" onchange="dateReadonly('+col+');" name="type_'+col+'" style="width:100%;"><option value="1">Suspend</option><option value="2">Stop</option></select></td>';
				temp+='<td> <input type="text"   name="reason_'+col+'" id="reason_'+col+'" dojoType="dijit.form.TextBox" style="width:100%;" /><label id="subsub"></label></td>';
				temp+='<td><input style="width:100%;" value="now" dojoType="dijit.form.DateTextBox" id="date_'+col+'" name="date_'+col+'" /></td>';
				temp+='<td> <input type="text"   name="note_'+col+'" id="note_'+col+'" dojoType="dijit.form.TextBox" style="width:100%;" /></td>';
				
				 
				tmp='<tr style="border:1px solid #deafaf; font-size:14px;height:37px; !important;text-align:center;" id="row'+col+'" >'
				tmp+="</tr>";
				dojo.query("#t_amountmoneytype").append(tmp);
				dojo.html.set(dojo.byId("row"+col),temp, {
					parseContent: true,
				});

				if($("#identity").val()!="") {
					var identity = $("#identity").val();
					$("#identity").val(identity+','+col);
				} else {$("#identity").val(col);}
				dijit.byId("service_"+col).attr('value',data[i].service_id);
			}
		},error: function(err) {
		}
	});
}

var url_student_info = "<?php echo $this->url(array('module'=>'accounting','controller'=>'suspendservice','action'=>'get-student')); ?>";
function getStudentInfo(){
			studentid = dijit.byId('studentid').get('value');
			//alert(studentid);
			dojo.xhrPost({
				url:url_student_info,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//alert(data.sex);
					//dijit.byId("kh_name").attr("value",data.stu_khname);
					//dijit.byId("en_name").attr("value",data.stu_enname);
					//dijit.byId("sex").attr("value",data.sex);
					//alert(data);
					//dijit.byId("price_"+key).attr("value",data.price_fee);
				},
				error: function(err) {
					alert(err);
				}
			});
}
function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
}

var student_id_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var get_id = "<?php echo $this->url(array('module'=>'accounting','controller'=>'suspendservice','action'=>'get-student-id')); ?>";
function getStudentID(){
	dojo.query("#table_row").append('');
	study_year= dijit.byId('study_year').get('value');
	dojo.xhrPost({
		url:get_id,
		content:{
			'study_year':study_year
			},
		handleAs:"json",
		load: function(data) {
			if(data !=''){
			student_id_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('studentid').set('store',student_id_store);  
			//dijit.byId("studentid").attr("value",data);
			}else{
			    
				setClear();
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}


var student_name_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var get_name = "<?php echo $this->url(array('module'=>'accounting','controller'=>'suspendservice','action'=>'get-student-name')); ?>";
function getStudentName(){
	study_year= dijit.byId('study_year').get('value');
	dojo.xhrPost({
		url:get_name,
		content:{
			'study_year':study_year
			},
		handleAs:"json",
		load: function(data) {
			if(data !=''){
				student_name_store  = getDataStorefromJSON('id','name', data);
		    	dijit.byId('student_name').set('store',student_name_store);  
			//dijit.byId("studentid").attr("value",data);
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}
function setID(type){
	//alert(1);
	if(type==1){
		//alert(1);
		id = dijit.byId('studentid').get('value');
		dijit.byId('student_name').attr('value',id);
	}else{
		//alert(2);
		id = dijit.byId('student_name').get('value');
		dijit.byId('studentid').attr('value',id);
	}
}
function setClear(){
	dijit.byId('studentid').attr('value','');
	dijit.byId('student_name').attr('value','');
	dijit.byId('studentid').set('store','');
	dijit.byId('student_name').set('store','');
}

</script>
