<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_SUSPEND_SERVICE')); 
?>	
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
              <div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-warning" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_SUSPEND_SERVICE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='suspend_service' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
				if(this.validate()){
					var iden = $("#identity").val();
					if(iden==""){
						alert("No Service");
						dijit.byId('service').focus();
						return false;	
					}
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex "> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-queen" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("BRANCH_INFO");?></p>
										</div> 
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12">
										&nbsp; 
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select name="branch_id" id="branch_id" class="fullside" onChange="getStudentByBranch();" dojoType="dijit.form.FilteringSelect" >
												<option value="-1"><?php echo $tr->translate("SELECT_BRANCH");?></option>
												<?php if(!empty($this->branch)){foreach($this->branch as $branch){?>
													<option value="<?php echo $branch['id']?>"><?php echo $branch['name']?></option>
												<?php }}?>
											</select>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="studentId" />
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<textarea class="fullside" style="min-height:80px"  name="note" id="note" dojoType="dijit.form.Textarea"> </textarea>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
	             </div>
	             <div class="col-md-8 col-sm-8 col-xs-12">
					 <div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex "> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-tasks" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("SERVICE_INFO");?></p>
										</div> 
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12">
										&nbsp; 
									</div>
									<div class="form-group" style=" background: #d8e0e2; padding: 5px 15px; margin: 0; border: solid 1px #697996; border-radius: 2px;">
										<label class="control-label bold col-md-2 col-sm-2 col-xs-12">
											<?php echo $tr->translate("SERVICE");?>
										</label>
										<div class="col-md-5 col-sm-5 col-xs-12">
											<input id="service" name="service" />
										</div>
										<div class="clearfix"></div>
									</div>
									<div class="form-group">
										<table  border="1px" style="border-collapse: collapse; width:100%; border:1px solid #ccc;">
											<thead>
												<tr id="head-title" class="head-td" align="right" style="width: 100%;">
													<th width="10%"><?php echo $tr->translate("DEL");?></th>
													<th width="5%"><?php echo $tr->translate("N_O");?></th>
													<th width="30%"><?php echo $tr->translate("SERVICE");?></th>
													<th width="25%"><?php echo $tr->translate("STOP_DATE");?></th>
													<th width="35%"><?php echo $tr->translate("REASON");?></th>
												</tr>
											</thead>
											<tbody id="table_row">
											</tbody>
										</table>
										<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
									</div>
								</div>
							</div>
						</div>
					</div>
	             </div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="submit" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
					   class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-open" />
					<input type="submit"  value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
					class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-open" />
               	</div>
             </div>
		</form>
    </div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.DateTextBox");
    dojo.require("dijit.form.Textarea");
	
	student_store = getDataStorefromJSON('id','name');
	service_store = getDataStorefromJSON('id','name');
	
	dojo.ready(function(){ 
		new dijit.form.FilteringSelect({
		    queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,
		    id: "studentId",
		    name: "studentId",           
		    class: 'fullside',  
		    placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_ID")?>",          
		    onChange: function() {  
		    	getServiceByStudent();
		    }
		}, "studentId");
		
		new dijit.form.FilteringSelect({
		    queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
		    id: "service",
		    name: "service",           
		    class: 'fullside',  
		    placeHolder:"<?php echo $tr->translate("SELECT_SERVICE")?>",          
		    onChange: function() {  
		    	addRow();
		    }
		}, "service");
	});	

	var col = 0;
	var no = 0;
	tmp = '';
	function addRow() {
		spd_id = dijit.byId("service").get("value");
		label_service = dijit.byId("service").attr('displayedValue');
		
		dijit.byId("service").reset();
		
		if(spd_id==''){return false;}
		
		var iden = $("#identity").val();
		var arrays = iden.split(',');
		 if(arrays!=""){
			 for(var i=0;i< arrays.length;i++) {
				 readychoose = dijit.byId('spd_id_'+arrays[i]).get('value');
				 if(readychoose==spd_id){
						alert("<?php echo $tr->translate("Choosen ready")?>");
						return false;
				 }
			}
		}
		
		col++;no++;
		
		template='';
		template+='<td align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td align="center">'+no+'</td>';
		template+='<td>&nbsp;'+label_service+'<input type="hidden" dojoType="dijit.form.TextBox" required="true" id="spd_id_'+col+'" name="spd_id_'+col+'" value="'+spd_id+'" /></td>';			
		template+='<td><input class="fullside" type="text" value="<?php echo date("Y-m-d");?>" placeHolder="<?php echo $tr->translate('STOP_DATE'); ?>" constraints=' + '{datePattern:"dd/MM/yyyy"}' + '  name="stopDate' + col + '" id="stopDate' + col + '" dojoType="dijit.form.DateTextBox" /></td>';			
		template+='<td><input type="text" name="reason_'+col+'" id="reason_'+col+'" class="fullside" dojoType="dijit.form.TextBox" /></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
			 parseContent: true,
		});
	}

	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
	
	function getStudentByBranch(){
		dojo.query("#table_row").append("");
		dijit.byId("studentId").reset();
		
		branchId = dijit.byId('branch_id').get('value');
		if(branchId==''){
			 dijit.byId('branch_id').focus();
			 return false;
		}
		let urlGet = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getliststudenturl')); ?>';
		
		contentData = {
				'branchId':branchId,
				'joinGroup':1,
				'activeStudent':1,
				'customerType':1,
				
			}
		getAllStudentByBranch(urlGet,contentData);
	}
	
	var url_service = '<?php echo $this->url(array('module'=>'accounting','controller'=>'suspendservice','action'=>'getservice')); ?>';
	function getServiceByStudent(){
		dojo.query("#table_row").append("");
		student = dijit.byId("studentId").get("value");
		if(student>0){
			dojo.xhrPost({
				url:url_service,
				content:{
					'student':student
				},
				handleAs:"json",
				load: function(data) {
					service_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('service').set('store',service_store);  
				},
				error: function(err) {
				}
			});
		}
	}

</script>