<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("STUDENT_SUSPEND_SERVICE"));
	$frm = $this->form_search;
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
             <div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_SUSPEND_SERVICE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'accounting','controller'=>'suspendservice','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<select name="branch_id" id="branch_id" class="fullside" onChange="getStudentByBranch();" dojoType="dijit.form.FilteringSelect" >
							<option value="-1"><?php echo $tr->translate("SELECT_BRANCH");?></option>
							<?php if(!empty($this->branch)){foreach($this->branch as $branch){?>
								<option value="<?php echo $branch['id']?>" <?php if($branch['id']==$this->rs['branch_id']){echo "selected";}?>><?php echo $branch['name']?></option>
							<?php }}?>
						</select>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<input id="studentid" />
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button  class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
		<div class="card-box">
		<?php  echo $this->list;?>
		</div>
	</div>
</div>

<script src="<?php echo $base_url;?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
    dojo.require("dijit.form.Textarea");
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require("dijit.form.DateTextBox");
	
	student_store = getDataStorefromJSON('id','name');
	dojo.ready(function(){ 
		new dijit.form.FilteringSelect({
		    queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,
		    id: "studentid",
		    name: "studentid",           
		    class: 'fullside',  
		    placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_ID")?>",          
		    onChange: function() {  
		    	//getServiceByStudent();
		    }
		}, "studentid");
		getStudentByBranch("<?php echo $this->rs['studentid']?>");
	});	
	
	var url_data = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getliststudenturl')); ?>';
	function getStudentByBranch(stu_id=''){//
		dijit.byId("studentid").attr("value","");
		branch_id = dijit.byId("branch_id").get("value");
		if(branch_id>0){
			dojo.xhrPost({
				url:url_data,
				content:{
					'branch_id':branch_id
				},
				handleAs:"json",
				load: function(data) {
					student_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('studentid').set('store',student_store);  
					if(stu_id!=''){
						dijit.byId("studentid").attr("value",stu_id);
					}
				},
				error: function(err) {
				}
			});
		}
	}

</script>
