<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('REPORT_PRODUCT_NEAR_OUT_STOCK')); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$session_user=new Zend_Session_Namespace('authstu');
	$user_id=$session_user->user_id;
	$frm =  $this->form_search;
?>
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'reportproductnearoutstock','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table width="90%" style="margin: 0px;">
		   <tr>
		       <td colspan="4">
					<div class="menureport">
						<ul>
							<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
							<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
							<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
						</ul>
					</div>
		      </td>
			</tr>
			<tr>
				<td><?php echo $frm->getElement("title");?></td>
				<td><?php echo $frm->getElement("location");?></td>
				<td><?php echo $frm->getElement("category_id");?></td>
				<td> <?php echo $frm->getElement("status_search");?></td>
				<td>
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"
						showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</td>
			</tr>
		</table>
	</form>
	
	<style>
		.hover:hover{ background: #ddd;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto }
	</style>
	
	<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
		<div id="divPrint">
			<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
				<tr>
					<td width="15%" align="center">
						<img style="width:60%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
					</td>
					<td align="center" width="70%">
						<strong style=" padding-left: 25px;font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('REPORT_PRODUCT_NEAR_OUT_STOCK');?></strong>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
						<table cellpadding="5"​ style="font-family:'Khmer OS Battambang';margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<tr style="font-size:12px; height: 20px;background-color: #ccc;line-height: 30px;font-weight: bold;" align="center">
									<td>&nbsp;<?php echo $tr->translate('N_O');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('PRODUCT_CATEGORY');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('PRODUCT_CODE');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('PRODUCT_NAME');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('QTY');?>&nbsp;</td>
									
									<td>&nbsp;<?php echo $tr->translate('COST');?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate('STATUS');?>&nbsp;</td>
						   </tr>
							
						<?php 
							$branch_name =''; $i=0;$totalpaid=0;$totalbalance=0; 
							if(!empty($this->pro_loc)) foreach ($this->pro_loc AS $rs) { 
								if($rs['pro_qty']<=5){
								
								$i++;
						    		if($branch_name!=$rs['brand_name']){
						  ?>
									<tr class="hover" style="font-size:15px; height: 18px;"​ align="center">
									      <td colspan="9" ><?php echo $rs['brand_name']; ?></td>
									</tr>
								<?php } $branch_name=$rs['brand_name'];?>
							
								
							
									<tr class="hover" style="font-size:11px; height: 18px;"​ align="center">
									    <td style="color:red;"> <?php echo $i; ?></td>
									    <td><?php echo $rs['category_name'];?></td>
									    <td style="color:red;"><?php echo $rs['pro_code'];?></td>
									    <td style="color:red;" align="center">&nbsp;<?php echo $rs['pro_name'];?></td>
									    <td style="color:red;"><?php echo number_format($rs['pro_qty'],0); ?></td>
									    
									     <td>&nbsp;$&nbsp;<?php echo $rs['pro_price'];?></td>
									    <td><?php echo $rs['status']; ?></td>
									</tr>
							<?php }?>
						<?php
							}
						?>
						</table>	
					</td>
				</tr>
				
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" width="100%">
						<table width="100%" style="font-family:'Khmer OS Battambang';">
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>		
	</div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>
