<?php
	$request = Zend_Controller_Front::getInstance ()->getRequest ();
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("DISCOUNT_TYPE"));
?>	
<?php $frm =  $this->form_search;?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'accounting','controller'=>'discount','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			<div class="form-group">
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("title");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('status_search');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					
				</div>
			</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
 
   
   
