<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = $this->baseUrl()."/";
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
	
	$dbExternal=new Application_Model_DbTable_DbExternal();
	$teacherInfo = $dbExternal->getCurrentTeacherInfo();
	$userName = $teacherInfo["user_name"];
	$userId = $teacherInfo["id"];
		            
?>
				</div>
			</div>
		</div>
	 </div>
	</div>
<footer>
  <div class="pull-right">
   All rights reserved
   & Developed By <a target="_blank" href="http://cam-app.com/">Cam App Technology</a>
  </div>
  <div class="clearfix"></div>
</footer>
<?php if($controller=='extreport' AND $action!='index'){?>
<script type="text/javascript" src="<?php echo $this->baseUrl() . ""; ?>/admin/tableExport-master/tableExport.js"></script>
<?php } ?>
<script type="text/javascript">
var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
function changeLange(lang){
	jQuery.ajax({
		url: url_changelang,
		type: "post",
		data:{'lange':lang},
		success: function(data){
			location.reload();
		},
		error:function(err){
			
		}
	});
}

function loadingBlock(){
  document.getElementsByClassName("overlay")[0].style.display="block";
}
function HideloadingBlock(){
  document.getElementsByClassName("overlay")[0].style.display="none";
}
function setPageTitle(pagetTitle){
   $("#breadcrumbTitle").html(pagetTitle);
   $("#breadcrumbSubTitle").html(pagetTitle);
}
jQuery(function () {
	'use strict';
	
	loadingBlock();
    $(".overlay").fadeOut(1000, function() {
    	$("div.container.body").fadeIn(500);  
           
    });
	jQuery(".ptss__toggle-btn").click(function () {	
		jQuery('.js-ptss-frame').toggleClass('is-opened');
	});
	jQuery('.ptss__layout-wrapper > div').click(function(){
		
		jQuery(this).closest('.ptss__setting-control').find('.ptss__layout-wrapper').removeClass('is-selected');
		
		jQuery(this).parent().addClass('is-selected');
		
		if( jQuery(this).hasClass('ptss__layout-box--wide') ) {
			
			jQuery('body').removeClass('boxed');
			jQuery('#ptss__boxed-bg').hide();
			
			jQuery('body').removeClass('bg1').removeClass('bg2').removeClass('bg3').removeClass('bg4');
			
			jQuery('#ptss__boxed-backgrounds span').removeClass('is-selected');
			
		} else {
			
			jQuery('body').addClass('boxed');
			jQuery('#ptss__boxed-bg').show();
			
		}
	});
})
<?php if($controller=='extreport' AND $action!='index'){?>

function doPrint() {
	getPrintBy();
	setTimeout(function () {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
		window.frames["print_frame"].window.focus();
		window.frames["print_frame"].window.print();
	}, 500);

    //hideDialog();
}

function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,fullscreen=yes, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}

var urlPrintBy = '<?php echo $this->url(array('module'=>'default','controller'=>'external','action'=>'printby'));?> ';
function getPrintBy(){
	jQuery.ajax({
		url: urlPrintBy,
		type: "post",
		data:{'data':1 },
		success: function(data){
			
			$(".footPrintDate").html(data);
		},
		error:function(err){
			
		}
	});
}
<?php }?>

function infoMessageAlert(msgTitle,msgDesc=''){
	
	classMessage="info";
	Swal.fire({
		  icon: classMessage,
		  title: msgTitle,
		  reverseButtons:true,
		  text: msgDesc,
		  showConfirmButton: false,
		  timer: 1000,
		  timerProgressBar: true,
		  didOpen: (toast) => {
			toast.addEventListener('mouseenter', Swal.stopTimer)
			toast.addEventListener('mouseleave', Swal.resumeTimer)
		  }
	})
}

function comfirmingSubmit(frmID,msgTitle,msgDesc=''){
	 Swal.fire({
	  title: msgTitle,
	  text: msgDesc,
	  icon: 'warning',
	  reverseButtons:true,
	  showCancelButton: true,
	  confirmButtonColor: '#3085d6',
	  cancelButtonColor: '#d33',
	  confirmButtonText: 'Yes'
	}).then((result) => {
	  if (result.isConfirmed==true) {
		  loadingBlock();
		  $('#'+frmID).submit();
	  }else{
		  return false;
	  }
	})
}


</script>

<script src="<?php echo $this->baseUrl()?>/admin/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl()?>/admin/build/js/custom.min.js"></script>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
</body>
</html>