<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_PICKUP_CARD')); 
?>
<?php  $frm = $this->frm_branch;?>
<style>
.button_browse {
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 38px;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 38px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 12.8cm;
    margin: 0 auto;
}
.image-box {
    text-align: center;
    width: 11.8cm;
    height: 7.5cm;
}
.image-box img {
    width: 11.8cm;
    height: 7.5cm;
}
ul.opt-school {
    list-style-type: none;
}
 input[type=checkbox],  input[type=radio]{
	height: 15px;
    display: initial;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_PICKUP_CARD');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
				</div>
    		</div>
    	</div>
		<form id="frm_branch" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					
					branch_id=dijit.byId("branch_id").get('value');
					if(branch_id=='' || branch_id==null){
						dijit.byId("branch_id").focus();
						return false;
					}
					schoolOption=dijit.byId("schoolOption").get('value');
					if(schoolOption=='' || schoolOption==null){
						dijit.byId("schoolOption").focus();
						return false;
					}
					loadingBlock();
               	 	
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("BRANCH_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">	
	                   		<?php echo $frm->getElement("branch_id");?>
							<?php echo $frm->getElement("id");?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("title");?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("School Option");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php //echo $frm->getElement("schoolOption");?>
	                   		<input id="schoolOption" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("note");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DISPLAY_BY");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("display_by");?>
	                   </div>
	                </div>
	            </div>
	           <div class="col-md-4 col-sm-4 col-xs-12">
				<div class="form-group">
                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PHOTO");?> 
                   
				   &nbsp;<span><input type="checkbox" class="" <?php if($this->rs['default']==1){ echo 'checked="checked"';} ?>  name="setdefault" id="setdefault" OnChange="CheckAllTotal(0);" style=" height: initial;"  />&nbsp;<span class="bold" style="vertical-align: top;"><?php echo $tr->translate('Is Default');?></span></span>
    			
				   </label>
                </div>
                <div class="form-group">
                   <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                    	<div class="account-image">
                    		<div class="image-box">
								<?php 
								$image = $this->baseUrl().'/images/card/pickup-student-card.png';
								if(!empty($this->rs['background'])){
									if (file_exists(PUBLIC_PATH."/images/card/".$this->rs['background'])){
									$image = $this->baseUrl().'/images/card/'.$this->rs['background'];
									}
									
								}?>
								<img id="profile_wiew" src="<?php echo $image;?>" alt=""  />
							</div>
							<div class="button_browse">
							<div id='preview'></div>	
								<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
								<input class="btn_borwse_image" type="file" id="photo" name="photo" >
							</div>
						</div>
                   </div>
                </div>
            </div>	
            <div class="card-box">
	         	<div class="col-md-8 col-sm-8 col-xs-12">
	         		<table id="table_row" border="1" style="border-collapse: collapse; border:1px solid #ccc;">
							<tr id="head-title" class="head-td" align="right"></tr>
					</table>
					<input type="hidden" id="identity" name="identity" />
	         	</div>
	         </div>          
            <div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear" />
					<input type="submit"  value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					
               	</div>
             </div>
		</form>
	</div>
</div>
<script>
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore"); 
var schooloptionstore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: schooloptionstore,
		autoComplete: true,                        
		id: "schoolOption",
		name: "schoolOption",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("PLEASE_SELECT");?>",          
	}, "schoolOption");

	var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getSchoolOption();
  });
	 getSchoolOption();
});
var oldBranch = '<?php echo $this->rs['branch_id'];?>';
function getSchoolOption(){
	var url_getoptionSchool = '<?php echo $this->url(array("module"=>"rsvacl","controller"=>"user","action"=>"getschooloption")); ?>';
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=="" || branch_id==-1){
			schooloptionstore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
			return false;
		}
		dojo.xhrPost({
			url: url_getoptionSchool,
			content:{
				'branch_id':branch_id,
			},
			handleAs:"json",
			load: function(data) {
				schooloptionstore  = getDataStorefromJSON('id','name', data );
			    dijit.byId('schoolOption').set('store', schooloptionstore);
			    if(oldBranch==branch_id){
			    	dijit.byId('schoolOption').set('value', '<?php echo $this->rs['schoolOption'];?>');
			    }
			},
			error: function(err) {
				alert(err);
			}
		});
}

function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#profile_wiew').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#photo").change(function(){
    readURL(this);
});

</script>