<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("Issue Letter Of Praise"));
	$frm = $this->frm;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<style>
tr.OddRow {
    background: #fff;
}
tr.EvenRow {
    background: #e6ecf5;
}
td.stuNameCol {
    font-size: 12px;
    white-space: nowrap;
    width: 30%;
    line-height: 22px;
}

</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="material-icons-outlined">badge</i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('Issue Letter Of Praise');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id='frm_submit' action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
					if(branch_id==-1 || branch_id==""){
						alert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>');
						dijit.byId('branch_id').focus();
						return false;
					}
					group = dijit.byId('group').get('value');
					if(group=='' || group==-1){
						alert('<?php echo $tr->translate("PLEASE_SELECT_GROUP");?>');
						dijit.byId('group').focus();
						return false;
					}
					identity =dijit.byId("identity").get('value');
					if(identity=='' || identity==null){
						alert("<?php echo $tr->translate("PLEASE_SET_STUDENT_ROW");?>");
						return false;
					}
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
    		<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="material-icons-outlined">class</i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("GROUP_STUDENT_INFO");?></p>
										</div> 
									</div>
									<br />
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("branch_id");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="group" />
										</div>
									 </div>
									  <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ACADEMIC_YEAR");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("academic_year");?>
										</div>
									 </div>
									  <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("CLASS");?></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("grade");?>
										</div>
									 </div>
									  <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ISSUE_DATE");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("issue_date");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE");?></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("for_type");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TEACHER");?></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("teacherName");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("POSITION");?></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("positionTeacher");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("PRINCIPAL");?></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("principleName");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("POSITION");?></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("positionPrinciple");?>
										</div>
									 </div>
									 
									 <div class="form-group">
										<label class="control-label bold col-md-12 col-sm-12 col-xs-12"><?php echo $tr->translate("NOTE");?></label>
									 </div>
									 <div class="form-group">
										<div class="col-md-12 col-sm-12 col-xs-12">
											<?php echo $frm->getElement("note");?>
										</div>
									 </div>
								 </div>
							 </div>
						 </div>
					 </div>
		         </div>
		         <div class="col-md-8 col-sm-8 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-list-alt"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT_LIST");?></p>
										</div> 
									</div>
									<br />
									<div class="form-group" >
									   <div class="custom-control custom-checkbox ">
											<input type="checkbox" class="checkbox custom-control-input" id="check_all" name="check_all" value="all" OnChange="CheckAll(0);" >
											<label class="custom-control-label" for="check_all">
												<?php echo $tr->translate("ALL");?>
											</label>
										</div>
									</div>
									<div class="form-group">
										<table  class="collape responsiveTable">
											<thead>
												<tr id="head-title" class="head-td" align="center">
													<th scope="col">
													</th>
													<th scope="col"><?php echo $tr->translate("N_O");?></th>
													<th scope="col" class="stuNameCol" ><?php echo $tr->translate("STUDENT");?></th>
													<th scope="col"><?php echo $tr->translate("RANK");?></th>
													<th scope="col"><?php echo $tr->translate("CODE_NUMBER");?></th>
													<th scope="col"><?php echo $tr->translate("NOTE");?></th>
												</tr>
											</thead>
											<tbody id="table_row">
											
											</tbody>
										</table>
										<input type="hidden"​​ dojoType='dijit.form.TextBox' name="identity" id="identity"  />
										 <div class="clearfix"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
		         </div>
    		</div>
    		<div class="clearfix"></div>
	        <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		 <input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" label="<?php echo $tr->translate("SAVE_CLOSE");?>" id="save_close" name="save_close" value="save_close" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" id="save_new" value="save_new" name="save_new" label="<?php echo $tr->translate("SAVE_NEW");?>" dojoType="dijit.form.Button" />
               	</div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dojo.NodeList-manipulate");

var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
	    	getStudetnOptionByGroup();
	    	getGroupInfo();
	    }
	}, "group");
	getCompleteGroup();
	getStudetnOptionByGroup();
}); 

var url_getgroup = '<?php echo $this->url(array("module"=>"issue","controller"=>"index","action"=>"getgroupcomplete"));?>';										
function getCompleteGroup(){
	 dijit.byId('group').reset();  
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		 dijit.byId('group').set('store',group_store);  
		return false;
	}
	
	dojo.xhrPost({
		url:url_getgroup,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);  
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
var url_getgroupinfo = '<?php echo $this->url(array("module"=>"issue","controller"=>"index","action"=>"getgroupinfo"));?>';										
function getGroupInfo(){
	group = dijit.byId('group').get('value');
	if(group=='' || group==-1){
		 dijit.byId('academic_year').set('value',""); 
	     dijit.byId('grade').set('value',"");  
		return false;
	}
	dojo.xhrPost({
		url: url_getgroupinfo,
		content:{
			'group':group
			},
		handleAs:"json",
		load: function(data) {
		    dijit.byId('academic_year').set('value',data.year_only); 
		    dijit.byId('grade').set('value',data.group_code);  
		    dijit.byId('teacherName').set('value',data.teacherNameKh);  
		    dijit.byId('positionTeacher').set('value','គ្រូបន្ទុកថ្នាក់');  
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
var col = 0;
var url_studentgroup = "<?php echo $this->url(array('module'=>'issue','controller'=>'index','action'=>'get-all-student')); ?>";
function getStudetnOptionByGroup(){
	group = dijit.byId('group').get('value');
	if(group==0 || group==""){
		dojo.query("#table_row").append("");
		return false;
	}
	loadingBlock();
	dojo.xhrPost({
		url: url_studentgroup,
		content:{
			'group':group
			},
		handleAs:"json",
		load: function(data) {
			template='';
			i = 0, size = data.length;
			var l=0;
			for(i; i < size; i++){ l++; col++;
			
				var classRow="OddRow";
				if((l%2)==0){
					classRow="EvenRow";
				}
				
				template+='<tr class="rowData '+classRow+'" style="vertical-align: top;">';
					template+='<td data-label="<?php echo $tr->translate("CHECKING");?>" align="center">';
							template+='<div class="custom-control custom-checkbox ">';
								template+='<input type="checkbox" class="checkbox checkedrow custom-control-input" OnChange="CheckAll('+col+')"  id="mfdid_'+col+'" value="'+col+'"  name="selector[]" >';
								template+='<label class="custom-control-label" for="mfdid_'+col+'">';
								template+='</label>';
							template+='</div>';
					template+='</td>';
					template+='<td data-label="<?php echo $tr->translate("N_O");?>" align="center">'+l+'<input dojoType="dijit.form.TextBox" class="fullside" name="stu_id'+col+'" id="stu_id'+col+'" value="'+data[i].stu_id+'" type="hidden"></td>';
					template+='<td data-label="<?php echo $tr->translate("STUDENT");?>" align="left">'+data[i].stu_name+' '+data[i].stu_code+' <?php echo $tr->translate("SEX");?> '+data[i].sex+'</td>';
					template+='<td data-label="<?php echo $tr->translate("RANK");?>" align="center"><input style="text-align:center;" dojoType="dijit.form.NumberTextBox" class="fullside" name="rank_'+col+'" id="rank_'+col+'"  value="" type="text"></td>';	
					template+='<td data-label="<?php echo $tr->translate("CODE_NUMBER");?>"><input dojoType="dijit.form.TextBox" class="fullside" name="letterpraiseCode_'+col+'" id="letterpraiseCode_'+col+'" value="" type="text"></td>';
					template+='<td data-label="<?php echo $tr->translate("NOTE");?>"><input dojoType="dijit.form.TextBox" class="fullside" name="note_'+col+'" id="note_'+col+'" value="" type="text"></td>';
				template+='</tr>';

				if($("#identity").val()!="") {
					var identity = $("#identity").val();
					$("#identity").val(identity+','+col);
				} else {$("#identity").val(col);}
			}
			dojo.html.set(dojo.byId("table_row"),template , {
			     parseContent: true,
			});
		   
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
function CheckAll(index){
	var identitys = $("#identity").val();
	var b = identitys.split(',').length;
	if(index==0){
			if($('#check_all').is(":checked")){
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = true;  
				});
			}else{
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = false;  
				});
			}
	}else{
		var a = $('.checkedrow:checked').length;
		if(a == b ){
			$('#check_all').attr('checked', true); // checks it
		}else{
			$('#check_all').attr('checked', false);
		}
	}
}
</script>