<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_MONTHLY_NEWSLATTER"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	
	$frm = $this->frm_items;
?>	
<style>
	select{ width:100%;}
		tr.hover td.verites-col,
		td.verites-col {
		    text-align: center;
		    white-space: nowrap;
		    g-origin: 50% 50%;
		    -webkit-transform: rotate(270deg);
		    -moz-transform: rotate(270deg);
		    -ms-transform: rotate(270deg);
		    -o-transform: rotate(270deg);
		    transform: rotate(270deg);
		}
		tr.hover td.verites-col span.verites,
		td.verites-col span.verites {
		     margin: 0 -85%;
		    display: inline-block;
		}
		tr.hover td.verites-col span.verites:before,
		td.verites-col span.verites:before {
		    content: '';
		    width: 0;
		    padding-top: 110%;
		    display: inline-block;
		    vertical-align: middle;
		}
		.form-group ul {
		    list-style-type: none;
		    padding: 0;
		    margin: 0;
		}
		.form-group ul li {
		    line-height: 28px;
		}
		.form-group ul li span.lbl-tt {
		    min-width: 100px;
		    display: inline-block;
			font-weight: bold;
		}
		div#score-info .form-group {
		    display: block;
		    font-size: 12px;
		    background: #fdfbbd;
		    border: solid 2px #dc0303;
		    border-radius: 5px;
		}
		div#score-info .form-group ul li span.lbl-tt {
		    color: #02014a;
		}
		span.red {
		    color: #f00;
		    font-weight: bold;
		}
		div#score-info .form-group ul li {
		    display: inline-block;
		    width: 50%;
		}
span.note_score {
    color: #ff0000;
    font-weight: bold;
    text-decoration: underline;
}
thead tr td {
    padding: 10px;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		   			<h4 class="m-b-0"><i class="fa fa-file-text-o " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_MONTHLY_NEWSLATTER');?></h4>
    				<span id="message"></span>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='office_receipt' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
   			if(this.validate()) {
				student_id = dijit.byId('student_id').get('value');
				if(student_id=='' || student_id=='-1'){
					dijit.byId('student_id').focus();
					return false;
				}
				if(isDuplicate==1){
					alert("<?php echo $tr->translate("ALREADY_EXISTING_RECORD");?>");
					dijit.byId("student_id").focus();
					return false;
				}
				var txt;
				var r = confirm("Are you sure to submit ?");
				if (r == true) {
    				 dijit.byId('save_new').set('disabled',true);
					 loadingBlock();
    				 return true;
				} else {
  					  return false;
				}
   			}else {
    			return false;
   			}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
		    		 <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("branch_id");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NEWSLATTER_SETTING");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="newsLatterSetting" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDY_YEAR");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="study_year" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<input id="group">
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<input id="student_id">
		                </div>
		             </div>
		             
		             
		             
		          </div>
		          <div class="col-md-6 col-sm-6 col-xs-12">
		          	<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("exam_type");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("FOR_SEMESTER");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("for_semester");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("FOR_MONTH");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("for_month");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("FOR_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		               	 <?php echo $frm->getElement("for_date");?>
		                </div>
		             </div>
		             <div class="form-group">
			                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
			                <div class="col-md-7 col-sm-7 col-xs-12">
			                	<?php echo $frm->getElement("note");?>
			                </div>
			         </div>
		          		<div id="gr-info"></div>
		          </div>
		     </div>
		     <div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12">
		    		<div class="form-group">
		    			<input type="hidden" name="identity" id="identity"  value="" >
		    			<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;width:100%" >
						</table>
		    		</div>
		    	</div>
		   </div>
	       <div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="submit" value="save_new" id="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
					iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
	</div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require('dijit.form.Textarea');
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.DateTextBox");
	dojo.require('dijit.form.NumberTextBox');

var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var scoreSetting_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

dojo.ready(function(){
	var subject = [];
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
			getAllGroupByAcademic();
		}
	}, "study_year");
	
	new dijit.form.FilteringSelect({
	    store:scoreSetting_store,		                    
	    required: true,
	    queryExpr: "*${0}*",
		autoComplete: false,     			
	    id: "newsLatterSetting",
	    name: "newsLatterSetting",           
	    class: 'fullside',  
	    required:'true',
	    onChange: function() {  
	    	filterStudent();
	    }
	}, "newsLatterSetting");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,             
		id: "group",
		name: "group",           
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
		onChange: function() {
			getInfoBygroup();
			getAllStudentByGroup();
			filterStudent();
			checkDuplicateRecord();
		}
	}, "group");

	new dijit.form.FilteringSelect({
		store:scoreSetting_store,	
		queryExpr: "*${0}*",
		autoComplete: false,             
		id: "student_id",
		name: "student_id",           
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_STUDENT");?>",          
		onChange: function() {
			checkDuplicateRecord();
		}
	}, "student_id");

	var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch(); 
		 getAllGroupByBranch(); 
		 getSubjectAreaSetting();
	});
	getAllGroupByBranch();
	getAllAcademicByBranch();
	checkExamType();
});

function checkExamType(){
	exam_type = dijit.byId("exam_type").get("value");
	dijit.byId('for_month').set("readOnly",false);
	if(exam_type==2){
		dijit.byId('for_month').set("readOnly",true);
	}
}
var isDuplicate = 0;
var url_duplicate = '<?php echo $this->url(array("module"=>"issue","controller"=>"monthlynewslatter","action"=>"checkduplicate"));?>';										
function checkDuplicateRecord(){
	group = dijit.byId('group').get('value');
	if(group=='' || group==-1){
		dijit.byId('group').focus();
		return false;
	}
	student_id = dijit.byId('student_id').get('value');
	if(student_id=='' || student_id==-1){
		return false;
	}
	exam_type = dijit.byId('exam_type').get('value');
	if(exam_type=='' || exam_type==-1){
		return false;
	}
	for_semester = dijit.byId('for_semester').get('value');
	if(for_semester=='' || for_semester==-1){
		return false;
	}
	for_month = dijit.byId('for_month').get('value');
	if(student_id=='' || student_id==-1){
		return false;
	}
	dojo.xhrPost({
		url: url_duplicate,
		content:{
			'student_id':student_id,'group':group,'exam_type':exam_type,'for_semester':for_semester,'for_month':for_month
			},
		handleAs:"json",
		load: function(data) {
			if(data==1){
				isDuplicate = 1;
				alert("<?php echo $tr->translate("ALREADY_EXISTING_RECORD");?>");
				$("#message").html('<?php echo '<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> '.$tr->translate("ALREADY_EXISTING_RECORD");?> !');
			}else{
				isDuplicate=0;
				$("#message").html('');
			}
			HideloadingBlock();
		},
		error: function(err) {
			alert(err);
			HideloadingBlock();
		}
	});
}

url_getacademic= "<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
		contentData = {
			'branch_id':branch_id
		}
		getAllYear(url_getacademic,contentData,null,'study_year');
}

var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_subjectareasetting = '<?php echo $this->url(array('module'=>'issue','controller'=>'monthlynewslatter','action'=>'getnewslattersetting')); ?>';
function getSubjectAreaSetting(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('newsLatterSetting').reset();
	dojo.xhrPost({
		url: url_subjectareasetting,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			scoreSetting_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('newsLatterSetting').set('store',scoreSetting_store);  
		},
		error: function(err) {
		}
	});
}
var performance = '<?php echo $this->performance;?>';
var inx=0;
var url_getStudent= '<?php echo $this->url(array('module'=>'issue','controller'=>'monthlynewslatter','action'=>'newslatterdetail')); ?>';
function filterStudent(){
	$('#identity').val('');
	dojo.query("#table_row").append("");
	loadingBlock();
	group = dijit.byId('group').get('value');
	if(group=='' || group=='-1'){
		HideloadingBlock();
		return false;
	}
	newsLatterSetting = dijit.byId('newsLatterSetting').get('value');
	if(newsLatterSetting=='' || newsLatterSetting=='-1'){
		HideloadingBlock();
		return false;
	}
	dojo.xhrPost({
	    url: url_getStudent,
	    content : { 
			'subject_area':newsLatterSetting,
		},				    
	   handleAs:"json", 
	   load: function(data) {
		   if(data==''){
			   alert('<?php echo $tr->translate('NO_RECORD');?>');
			   return false;
		   }
		   tem="";
		   temp='';
	       if(data!=""){
				num =0;
				title=0;
				temp='';
				str='';
				column = 0;
				temp='<table class="collape tablesorter" style="font-size:12px;border:1px solid #ccc;text-align: center; table-layout: fixed;" id="table" width="100%">'
					+'<thead><tr style="border: 1px #4839bd solid;background: #fdbdbd;color: #4839bd;font-family: Time New Roman, Khmer OS Battambang;font-weight: bold;font-size: 12px;">'
					+'<td  style="width: 10%;" class="tdheader" ><?php echo $tr->translate('NO');?></td>'
					+'<td class="tdheader header" style="width:40%;"><?php echo $tr->translate('TITLE');?></td>'
					+'<td class="tdheader header" style="width:20%;"><?php echo $tr->translate('PERFORMANCE');?></td>'
				  temp+='<td  class="text-center">&nbsp;<?php echo $tr->translate('NOTE');?></td>'+'</tr>';
				  temp+='</thead>';
				  
				for(i=0;i<data.length;i++){
					num++;
					inx = inx+1;
					temp += '<tr class="hover normal" id="row'+inx+'">';
					temp += '<td align="center">&nbsp;'+inx+'</td>';
					temp += '<td style="text-align: left;">&nbsp;'+data[i].name+'&nbsp; <input dojoType="dijit.form.TextBox" value="'+data[i].subject_area_id+'" name="subject_area_id'+inx+'" id="subject_area_id'+inx+'" type="hidden" ></td>';
					temp +='<td><select dojoType="dijit.form.FilteringSelect" queryExpr="*${0}*" autoComplete="false" class="fullside" id="performance_'+inx+'" name="performance_'+inx+'" >'+performance+'</select></td>';
					temp += '<td><input dojoType="dijit.form.TextBox" class="fullside" name="note_'+inx+'"  value="" type="text" ></td>';
					temp+= '</tr>';
					
					var no=0;
				    if($("#identity").val()!="") {
						var identity = $("#identity").val();
						$("#identity").val(identity+','+inx);
					} else {$("#identity").val(inx);}
					
				}
				temp+='</table>';
				tmp='<tr id="row'+inx+'">';
				tmp+="</tr>";
				dojo.query("#table_row").append(tmp);
				dojo.html.set(dojo.byId("row"+inx),temp , {
				     parseContent: true,
				});
	       }else{
		    	$('#identity').val('');
	       }
	   },		
	    error: function(err) {
	    }
	});
	HideloadingBlock();
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
function getInfoBygroup(){
		url_group = '<?php echo $this->url(array('module'=>'issue','controller'=>'monthlynewslatter','action'=>'getgroupinfo'));?>';
		group = dijit.byId('group').get('value');
		if(group==''){
			alert("Please Select Group");
			return false;
		}
		dojo.xhrPost({
			url:url_group,	
			content:{ 
				'group_id': group,'string':1
			},
			handleAs:"json",
			load: function(data) {
				dojo.byId("gr-info").innerHTML = data;
			},
			error: function(err) {
			}
		});
}
url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		},
		error: function(err) {
		}
	});
}
url_getgroupbyAca = '<?php echo $this->url(array('module'=>'global','controller'=>'foundation','action'=>'getallgroup'));?>';
function getAllGroupByAcademic(){
	dijit.byId('group').reset();
	study_year = dijit.byId('study_year').get('value');
	if(study_year=='' || study_year==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('study_year').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroupbyAca,
		content:{
			'academic_year':study_year,
			'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		},
		error: function(err) {
		}
	});
}

url_getStudentByGroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-student-bygroup'));?>';
function getAllStudentByGroup(){
	dijit.byId('student_id').reset();
	group = dijit.byId('group').get('value');
	if(group=='' || group==-1){
		var student_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('student_id').set('store',student_store);  
		dijit.byId('group').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getStudentByGroup,
		content:{
			'group':group
			},
		handleAs:"json",
		load: function(data) {
		    student_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('student_id').set('store',student_store);   
		},
		error: function(err) {
		}
	});
}
</script>