<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Dialy Payment Report'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$session_user=new Zend_Session_Namespace('auth');
	$user_id=$session_user->user_id;
	$frm =  $this->form_search;
?>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'allreports','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table width="90%" style="margin: 0px;">
   <tr>
       <td colspan="4">
			<div class="menureport">
				<ul>
					<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
					<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
					<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
				</ul>
			</div>
      </td>
	</tr>
	<tr> 
		 <td><input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->search['adv_search']?>" placeholder="Search" type="text" ></td>
		 <td> <?php echo $frm->getElement("branch_id");?></td>
		 <td> <?php echo $frm->getElement("study_year");?></td>
		 <td> <?php echo $frm->getElement("service");?></td>
		 
	</tr>
	<tr>
		<td> <input dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="start_date" name="start_date" value="<?php  echo $this->search['start_date']; ?>"  type="text"></td>
	 	<td><input dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" id="end_date" name="end_date" value="<?php echo $this->search['end_date'];?>" type="text"></td>
		<td> <?php echo $frm->getElement("user");?></td>
		<td>
			<select name="type" id="type" dojoType="dijit.form.FilteringSelect" class="fullside"  >
				<option value="1" <?php if($this->search['type']==1){echo 'selected="selected"';}?>>All Payment</option>
				<option value="2" <?php if($this->search['type']==2){echo 'selected="selected"';}?>>Student's Payment</option>
				<option value="3" <?php if($this->search['type']==3){echo 'selected="selected"';}?>>Income and Expense</option>
			</select>
		</td>
		<td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	</tr>
</table>
</form>
<style>
.hover:hover{ background: #ddd;}
</style>
<div style="border: 1px dotted #000;background: #fff;width:31cm; margin: 0 auto;">
		<div id="divPrint" style="overflow: scroll;" >
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm;" >
							<tr style="font-size: 13px;">
								<td width="15%" align="center">
									<img style="width:45%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
								</td>
								<td align="center"  width="70%">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_BRANCH"); ?></strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("STUDENT_PAYMENT_RECEIPT"); ?></strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';">For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong><br /><br />
								</td>
								<td width="15%">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel">
										<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #e4e4e4; }
										</style>

									<table class="padd" width="100%" border="1" align="center" style="font-family: 'Hanuman';">
										 
										 <?php 
										 	$i=0; $total=0;$total_paid=0;$total_balance=0;
										 	$comple_b=0; $isset =0; $total_other_income=0;
										 	$total_other_expense=0;
										 	$total_income_dollar=0;
										 	$total_income_kh = 0;
										 	$total_expense_dollar = 0;
										 	$total_expense_kh =0;
										 	if (!empty($this->row)){  
										 ?>
										 
										  <tr style="font-size:12px; height: 20px; white-space:nowrap;background: #ccc !important; line-height: 30px; font-weight: bold;" align="center">
										    <td>&nbsp;<?php echo $tr->translate("N_O"); ?>&nbsp;</td>
										    <td>&nbsp;<?php echo $tr->translate("RECEIPT_NO"); ?>&nbsp;</td>
										    <td>&nbsp;<?php echo $tr->translate("STUDENT_ID"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("STUDENT_NAME"); ?>&nbsp;</td>
											<!-- <td>&nbsp;<?php //echo $tr->translate("RECEIPT"); ?>&nbsp;</td> -->
											<td>&nbsp;<?php echo $tr->translate("SERVICE_NAME"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("PAYMENT_TERM"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("FEE"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("Qty"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("Total"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("Late Fee"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("Extra Fee"); ?>&nbsp;</td>
											
											<td>&nbsp;<?php echo $tr->translate("Dis.");?>(%)&nbsp;</td>
											
											<td>&nbsp;<?php echo $tr->translate("Total Payment"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("Paid Date"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("Start"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("Validate"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("Note"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("User"); ?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate("Status"); ?>&nbsp;</td>
										  </tr>
										 
										 <style> 
											td{padding:0 3px; }
										 </style>
										 
										 <?php foreach($this->row as $rs){ $i++;?>
										 
										  <tr style="font-size:11px; height: 18px;white-space:nowrap;"​ class="hover">
										    <td <?php if($rs['is_void']==1){echo "style='color:red;'";}?>><?php echo $i;?></td>
										    <td><?php echo $rs['receipt_number']; ?></td>
										    <td><?php echo $rs['stu_code']; ?></td>
										    <td style=" white-space:nowrap; text-align:left"> <?php echo $rs['stu_enname']; ?> </td>

										    
										    <td style="text-align:left"><?php echo $rs["service_id"]; ?></td>
										    <td style="text-align:center"><?php echo $rs["payment_term"]; ?></td>
										    
										    <td>$ <?php echo number_format($rs['fee'],2); ?></td>
										    <td> <?php echo $rs['qty'];?></td>
										    <td <?php if($rs['is_void']==1){echo "style='color:red;'";}?>>$ <?php echo number_format($rs['subtotal'],2); ?></td>
										    
										    <td> <?php if($rs['late_fee']>0){echo '$ '.$rs['late_fee'];}?></td>
										    <td> <?php if($rs['extra_fee']>0){echo '$ '.$rs['extra_fee'];}?></td>
										    
										    <?php if($rs['discount_percent'] > 0 ){ ?>
										    <td> <?php echo $rs['discount_percent']; ?>%</td>
										    <?php }else{?>
										    <td> <?php echo ''; ?></td>
										    <?php }?>
										    
										    
										    <td <?php if($rs['is_void']==1){echo "style='color:red;'";}?>>$ <?php echo number_format($rs['paidamount'],2); ?></td>
										    
										    
										    <td><?php echo date('d-M-Y', strtotime($rs['create_date'])); ?></td>
										    <td><?php if(!empty($rs['start_date'])){echo date('d-M-Y', strtotime($rs['start_date']));} ?></td>
										    <td><?php if(!empty($rs['validate'])){echo date('d-M-Y', strtotime($rs['validate']));} ?></td>
										   	<td><?php echo $rs['note']; ?></td>
										    <td><?php echo $rs['user_id'];?></td>
										    <td <?php if($rs['is_void']==1){echo "style='color:red;'";}?>><?php echo $rs['void_status'];?></td>
										  </tr>
										  <?php 
										  		if($rs['is_void']==1){
										  		
										  		}else{
											        $total_paid = $rs['paidamount'] + $total_paid;
											        //$total_balance = $rs['balance'] + $total_balance;
											        //$total_balance = $total - $total_paid;
											        if($rs["is_complete"] == 0){
											        	$total_balance = $rs['balance'] + $total_balance;
											        }
											        $total = $total_paid + $total_balance;
										  		}
										   ?> 
										  <?php } }?>
										</table>
										<table width="100%" style="margin-top: 10px;">
										<?php if(!empty($total)){?>
												<tr>
													<td colspan="3">
															<table width="29.2%" border="1" align="right" style="white-space:nowrap;">
																<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
														 				<td style="background-color: #ccc; width: 38%; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("GRAND_TOTAL"); ?>&nbsp;</td>
																		<td colspan="2" style=" color:#F00; font-weight:bold;font-family: Arial Black; font-size: 12px;">$ <?php echo number_format($total,2);?></td>
														  		</tr>
														  		<?php /*?>
															  		<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
															 				<td style="background-color: #ccc; width: 38%; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("PAID_AMOUNT"); ?>&nbsp;</td>
																			<td colspan="2" style=" color:#F00; font-weight:bold;font-family: Arial Black; font-size: 12px;">$ <?php echo number_format($total_paid,2);?></td>
															  		</tr>
														  		
															  		<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
															 				<td style="background-color: #ccc; width: 38%; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("BALANCE"); ?>&nbsp;</td>
																			<td colspan="2" style=" color:#F00; font-weight:bold;font-family: Arial Black; font-size: 12px;">$ <?php echo number_format($total_balance,2);?></td>
															  		</tr>
														  		<?php */?>
														  </table>
													</td>
												</tr>
												
												
										<?php }?>
								
										</table>
											<?php if(!empty($this->expense) || !empty($this->income)){ ?>
												<br /><br />
											<?php }?>
									</td>
									
								</tr>
								
								
							<?php if(!empty($this->income)){?>
								<tr>
								<td colspan="3" id="exportExcel">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #e4e4e4; }
										</style>

									<table class="padd" width="100%" border="1" align="center" style="font-family: 'Hanuman';">
										<tr style="border-left:none;">
											<td align="center" colspan="8" ><strong> Other Income </strong> </td>
										</tr>
													
										<tr style="font-size:12px; height: 20px;border: 1px solid #000;background-color: #ccc;line-height: 30px;font-weight: bold;" align="center" >
											<td style="border: 1px solid #000;"><?php echo $tr->translate('N_O')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('TITLE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('INVOICE_NO')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('CURRENCY_TYPE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('TOTAL')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('FOR_DATE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('USER')?></td>
										</tr>
										 
										 <style> td{padding:0 3px; }</style>
									<?php $i=0;$total_income_kh=0;foreach($this->income as $row){ $i++;?>
										<tr class="hover" style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
											<td style="border: 1px solid #000;"><?php echo $i;?></td>
											<td style="border: 1px solid #000;"><?php echo $row['title'];?></td>
											<td style="border: 1px solid #000;"><?php echo $row['invoice'];?></td>
											<td align="canter" style="border: 1px solid #000;"><?php echo $row['curr_name'];?></td>	
											<td style="border: 1px solid #000;"><?php echo $row['total_amount'];?></td>
											<td style="border: 1px solid #000;"><?php echo date('d-M-Y',strtotime($row['date']));?></td>
											<td style="border: 1px solid #000;"><?php echo $row['name'];?></td>
										</tr>
											<?php 
												$total_income_dollar = $total_income_dollar + $row['total_amount'];
											?> 
										 <?php } ?>
										</table>
										<table width="100%" style="margin-top: 10px;">
											<?php if(!empty($this->income)){?>
												<tr>
													<td colspan="3">
															<table width="29.2%" border="1" align="right" style="white-space:nowrap;">
														  		<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
													 				<td style="background-color: #ccc; width: 38%; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("GRAND_TOTAL"); ?>&nbsp;</td>
																	<td colspan="2" style=" color:#F00; font-weight:bold;font-family: Arial Black; font-size: 12px;">$ <?php echo number_format($total_income_dollar,2);?></td>
														  		</tr>
														  </table>
													</td>
												</tr>
											<?php }?>
										</table>
										
											<?php if(!empty($this->expense) && !empty($this->income)){ ?>
												<br /><br />
											<?php }?>
											
									</td>
								</tr>
							<?php }?>
								
								
							<?php if(!empty($this->expense)){?>
								<tr>
								<td colspan="3" id="exportExcel">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #e4e4e4; }
										</style>

									<table class="padd" width="100%" border="1" align="center" style="font-family: 'Hanuman';">
										<tr style="border-left:none;">
											<td align="center" colspan="8" ><strong> Other Expense </strong> </td>
										</tr>
													
										<tr style="font-size:12px; height: 20px;border: 1px solid #000;background-color: #ccc;line-height: 30px;font-weight: bold;" align="center" >
											<td style="border: 1px solid #000;"><?php echo $tr->translate('N_O')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('TITLE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('INVOICE_NO')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('CURRENCY_TYPE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('TOTAL')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('FOR_DATE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('USER')?></td>
										</tr>
										 
										 <style> td{padding:0 3px; }</style>
									<?php $i=0;$total_expense_kh=0;$total_expense_dollar=0;foreach($this->expense as $row){ $i++;?>
										<tr class="hover" style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
											<td style="border: 1px solid #000;"><?php echo $i;?></td>
											<td style="border: 1px solid #000;"><?php echo $row['title'];?></td>
											<td style="border: 1px solid #000;"><?php echo $row['invoice'];?></td>
											<td align="canter" style="border: 1px solid #000;"><?php echo $row['curr_name'];?></td>	
											<td style="border: 1px solid #000;"><?php echo $row['total_amount'];?></td>
											<td style="border: 1px solid #000;"><?php echo date('d-M-Y',strtotime($row['date']));?></td>
											<td style="border: 1px solid #000;"><?php echo $row['name'];?></td>
										</tr>
											<?php 
												$total_expense_dollar = $total_expense_dollar + $row['total_amount'];
											?> 
										 <?php } ?>
										</table>
										<table width="100%" style="margin-top: 10px;">
											<?php if(!empty($this->expense)){?>
												<tr>
													<td colspan="3">
															<table width="29.2%" border="1" align="right" style="white-space:nowrap;">
														  		<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
														 				<td style="background-color: #ccc; width: 38%; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("GRAND_TOTAL"); ?>&nbsp;</td>
																		<td colspan="2" style=" color:#F00; font-weight:bold;font-family: Arial Black; font-size: 12px;">$ <?php echo number_format($total_expense_dollar,2);?></td>
														  		</tr>
														  </table>
													</td>
												</tr>
											<?php }?>
										</table>
									</td>
								</tr>
							<?php }?>	
							
							<?php 
								$total_income=0;
								$total_expense=$total_other_expense;
								
								$total_income = $total+$total_income_dollar;
								
							
							
							?>
							
								
								<tr>
									<td colspan="3">
										<table width="100%" style="margin-top: 10px;">
											<?php if(!empty($this->row) || !empty($this->income) || !empty($this->expense)){?>
												<tr>
													<td colspan="3"><br /><br />
													<?php 
														$final_total_dollar=0;
														$final_total_dollar=$total_paid+$total_income_dollar-$total_expense_dollar;
													?>
															<table width="100%" border="1"  style="white-space:nowrap;">
																<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
																		<td style="background-color: #ccc; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("CURRENCY_TYPE"); ?>&nbsp;</td>
														 				<td style="background-color: #ccc; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("STUDENT_PAYMENT_INCOME"); ?>&nbsp;</td>
														 				<td style="background-color: #ccc; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("OTHER_INCOME"); ?>&nbsp;</td>
														 				<td style="background-color: #ccc; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("OTHER_EXPENSE"); ?>&nbsp;</td>
														 				<?php /*?>
														 					<td style="background-color: #ccc; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("BALANCE"); ?>&nbsp;</td>
														 				<?php */?>
														 				<td style="background-color: #ccc; font-weight:bold;font-family: 'Hanuman',Arial Black; font-size: 12px;">&nbsp;<?php echo $tr->translate("សមតុល្យ"); ?>&nbsp;</td>
														  		</tr>
														  		<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
														  				<td style="font-weight:bold;font-family: Arial Black; font-size: 12px;"> Dollar ($)</td>
																		<td style=" color:#F00; font-weight:bold;font-family: Arial Black; font-size: 12px;"> <?php echo $total_paid;?> $ </td>
																		<td style=" color:#F00; font-weight:bold;font-family: Arial Black; font-size: 12px;"> <?php echo $total_income_dollar;?> $​ </td>
																		<td style=" color:#F00; font-weight:bold;font-family: Arial Black; font-size: 12px;"> <?php echo $total_expense_dollar;?> $ </td>
																		<?php /*?>
																			<td style=" color:#F00; font-weight:bold;font-family: Arial Black; font-size: 12px;"> <?php echo $total_balance;?> $ </td>
																		<?php */?>
																		<td style=" color:#F00; font-weight:bold;font-family: Arial Black; font-size: 12px;"><?php echo $final_total_dollar;?> $ </td>
																		
														  		</tr>
														  </table>
													</td>
												</tr>
											<?php }?>
										</table>
									</td>
								</tr>
								
								
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								
								<tr >
									<td colspan="3" width="100%">
										<table width="100%" style="font-family: 'Khmer OS Battambang';">
											<tr>
												<td  width="25%" align="center">
													<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
												</td>
												<td  width="50%">
													&nbsp;
												</td>
												<td align="center"  width="25%">
													<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
												</td>
											</tr>
										</table>
									</td>
								</tr>
								
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
							</table>
	</div>	
</div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>
