<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_BRANCH​​')); 
?>
<?php  $frm = $this->frm_branch;?>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-university " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_BRANCH​​');?></h4>
    				<span id="message"></span>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id="frm_branch" action="<?php echo $this->url(array('module'=>'rsvacl','controller'=>'branch','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					 var identity = [];
	    			 $('.checkbox:checked').each(function(i){
	    				 identity[i] = $(this).val();
	     			});
					if(identity==""){
						alert("<?php echo $tr->translate("PLEASE_SELECT_SCHOOL_OPTION");?>");
						return false;
					}
					if(isDuplicate==1){
						alert("<?php echo $tr->translate("ALREADY_EXISTING_PREFIX");?>");
						dijit.byId("title").focus();
						return false;
					}
					main_branch_id = dijit.byId("main_branch_id").get('value');
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
	    		 <ul class="nav  nav-pills nav-fill gap-2 p-1 small bg-white border rounded-5 shadow-sm pills-primary nav-tab" role="tablist">
		            <li class="nav-item active">
		                <a class="nav-link  rounded-5" data-toggle="tab" href="#panel1" role="tab"><i class="fa fa-university ml-2"></i><?php echo $tr->translate("BRANCH_INFO");?></a>
		            </li>
					<li class="nav-item">
		                <a class="nav-link  rounded-5" data-toggle="tab" href="#panel2" role="tab">
		                <i class="fa fa-file-text ml-2"></i> <?php echo $tr->translate("SIGNATURE_INFO");?>
		                </a>
		            </li>
		        </ul>
	    	</div>
			<div class="card-box">
				<div class="tab-content ">
					<!--Panel 1-->
				   <div class="tab-pane fade in active" id="panel1" role="tabpanel">
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-picture" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("LOGO");?></p>
												</div> 
											</div>
											 <div class="form-group">
												<div class="col-md-12 col-sm-12 col-xs-12">
													<div class="account-image">
														<div class="image-box">
															<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/noimage.jpg';?>" alt=""  />
														</div>
														<div class="button_browse">
														<div id='preview'></div>	
															<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
															<input class="btn_borwse_image" type="file" id="photo" name="photo" >
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="fa fa-info" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("BRANCH_INFO");?></p>
												</div> 
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SCHOOL_NAMEKH");?> <span class="required">*</span></label>
											   <div class="col-md-7 col-sm-7 col-xs-12">	
													<?php echo $frm->getElement("school_namekh");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SCHOOL_NAMEEN");?> <span class="required">*</span></label>
											   <div class="col-md-7 col-sm-7 col-xs-12">	
													<?php echo $frm->getElement("school_nameen");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAMEKH");?> <span class="required">*</span>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("branch_namekh");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAMEEN");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("branch_nameen");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ABBREVIATION");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("abbreviations");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PREFIX_CODE");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("prefix_code");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CODE");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">	
													<?php echo $frm->getElement("branch_code");?>
											   </div>
											</div>
											 <div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("MAIN_BRANCH");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("main_branch_id");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("branch_note");?>
											   </div>
											</div> 
										</div>
									</div>
								</div>
							</div>
							
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-modal-window" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("CARD_INFO");?></p>
												</div> 
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("COLOR");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("color");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CARD_TYPE");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("card_type");?>
											   </div>
											</div>
										</div>
									</div>
								</div>
							</div>
							
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-phone-alt" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("CONTACT_INFO");?></p>
												</div> 
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ADDRESS");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("br_address");?>
											   </div>
											</div>
											 <div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PHONE");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("branch_tel");?>
											   </div>
											 </div>
											 <div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PHONE");?>1
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("branch_tel1");?>
											   </div>
											 </div>
											 <div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_FAX");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("fax");?>
											   </div>
											</div>
											 <div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("EMAIL");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("email");?>
											   </div>
											</div>
											 <div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("WEBSITE");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("website");?>
											   </div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="card-blogform">
							
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("School Option");?></p>
												</div> 
											</div>
											<br />
											<div class="custom-control custom-checkbox ">
												<input type="checkbox" class="checkbox custom-control-input" name="check_all" id="check_all" value="all" OnChange="CheckAllTotal(0);"  >
												<label class="custom-control-label" for="check_all">
													<?php echo $tr->translate('ALL');?>
												</label>
											</div>
											<div class="form-group">
												<ul class="optListRow">
													<?php $identityCheck = ""; if (!empty($this->schoolOption)) foreach ($this->schoolOption as $key => $rs){?>
													<li class="opt-items"> 
														<div class="custom-control custom-checkbox">
															<input type="checkbox" id="schoolOptionKey<?php echo $key;?>"  class="checkbox custom-control-input" value="<?php echo $rs['id'];?>" name="selector[]" onClick="CheckAllTotal(1);"  >
															<label class="custom-control-label" for="schoolOptionKey<?php echo $key;?>">
																<?php echo $rs['name'];?>
															</label>
														</div>
													</li>
														<?php if (empty($identityCheck)){ $identityCheck = $rs['id'];}else{$identityCheck = $identityCheck.",".$rs['id'];}?>
													<?php }?>
												</ul>
												<input type="hidden" id="identityCheck" name="identityCheck" value="<?php echo $identityCheck;?>" />
											</div>
					
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!--END Panel 1-->
					<!--Panel 2-->
					<div class="tab-pane fade in " id="panel2" role="tabpanel">
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("OTHER_INFOMATION");?></p>
												</div> 
											</div>
											 <div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("EYSCENTER");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("centereys");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("EYSOFFICE");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("officeeys");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("WORK_AT");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("workat");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PRINCIPAL");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("principal");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DEPUTY_PRINCIPAL");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("deputy_principal");?>
											   </div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="card-blogform">
								<div class="card-body bg-info"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-file" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("NOTE");?></p>
												</div> 
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-12 col-sm-12 col-xs-12" >
													1, <?php echo $tr->translate("IMAGE_SIZE_OF_SIGNATURE");?> 
											   </label>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-12 col-sm-12 col-xs-12" >
													2, <?php echo $tr->translate("IMAGE_SIZE_OF_STAM");?>
											   </label>
											</div>
											
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-picture" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("PRINCIPAL_SINATURE");?></p>
												</div> 
											</div>
											<div class="form-group">
											   <div class="col-md-12 col-sm-12 col-xs-12">
													<div class="account-image">
														<div class="image-box">
															<img id="view_signature" src="<?php echo $this->baseUrl().'/images/noimage.jpg';?>" alt=""  />
														</div>
														<div class="button_browse">
														<div id='preview'></div>	
															<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
															<input class="btn_borwse_image" type="file" id="principalsign" name="principalsign" >
														</div>
													</div>
											   </div>
											  
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-picture" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("PRINCIPAL_STAMP");?></p>
													
												</div> 
											</div>
											
											<div class="form-group">
											   <div class="col-md-12 col-sm-12 col-xs-12">
													<div class="account-image">
														<div class="image-box">
															<img id="view_stamp" src="<?php echo $this->baseUrl().'/images/noimage.jpg';?>" alt=""  />
														</div>
														<div class="button_browse">
														<div id='preview'></div>	
															<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
															<input class="btn_borwse_image" type="file" id="stamp" name="stamp" >
														</div>
													</div>
											   </div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						
					</div>
					<!--END Panel 2-->
				</div>
			</div>
			
            <div class="card-box">
	         	<div class="col-md-8 col-sm-8 col-xs-12">
	         		<table id="table_row" border="1" style="border-collapse: collapse; border:1px solid #ccc;">
							<tr id="head-title" class="head-td" align="right"></tr>
					</table>
					<input type="hidden" id="identity" name="identity" />
	         	</div>
	         </div>          
            <div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" class="button-class button-danger"  iconClass="glyphicon glyphicon-repeat" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button"  />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new"  id="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button"  />
               	</div>
             </div>
		</form>
	</div>
</div>
<style>
.image-box {
    text-align: center;
    height: 160px;
}
.image-box img {
    height: 160px;
}

.button_browse {
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 38px;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 38px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 100%;
    margin: 0 auto;
}
ul.optListRow {
    list-style-type: none;
    margin: 0;
    padding: 0;
    padding-left: 35px;
}
 input[type=checkbox],  input[type=radio]{
	height: 15px;
    display: initial;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.ready(function(){

	var prefix_code = dijit.byId('prefix_code');
	prefix_code.on('keyUp', function(evt) {
		checkDuplicateRecord();
    });
    
});
var isDuplicate = 0;
var url_duplicate = '<?php echo $this->url(array("module"=>"rsvacl","controller"=>"branch","action"=>"checkduplicate"));?>';										
function checkDuplicateRecord(){
	prefix_code = dijit.byId('prefix_code').get('value');
	if(prefix_code=='' || prefix_code==-1){
		dijit.byId('prefix_code').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_duplicate,
		content:{
			'prefix_code':prefix_code,
			},
		handleAs:"json",
		load: function(data) {
			if(data==1){
				isDuplicate = 1;
				alert("<?php echo $tr->translate("ALREADY_EXISTING_PREFIX");?>");
				$("#message").html('<?php echo '<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> '.$tr->translate("ALREADY_EXISTING_PREFIX");?> !');
			}else{
				isDuplicate=0;
				$("#message").html('');
			}
			HideloadingBlock();
			
		},
		error: function(err) {
			alert(err);
			HideloadingBlock();
		}
	});
}
function CheckAllTotal(index){
	if(index==0){
			if($('#check_all').is(":checked")){
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = true;  
				});
			}else{
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = false;  
				});
			}
	}else{
		var a = $("input:checked").val();
		 var identity = [];
	     $('.checkbox:checked').each(function(i){
	    	 identity[i] = $(this).val();
	     });
	     var allidentity = $("#identityCheck").val();
		if(identity == allidentity ){
			$('#check_all').prop('checked', true); // checks it
		}else{
			$('#check_all').prop('checked', false); // Unchecks it
		}
	}
}
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#profile_wiew').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#photo").change(function(){
    readURL(this);
});

function readURLStamp(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#view_stamp').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#stamp").change(function(){
	readURLStamp(this);
});

function readURLSignature(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#view_signature').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#principalsign").change(function(){
	readURLSignature(this);
});


function submitDataClose(){
	if(dijit.byId('frm_branch').validate()) {
		main_branch_id=dijit.byId('main_branch_id').get('value');
		//if(main_branch_id=='' || main_branch_id==null){
			//alert('Please Select Name Branch!');
			//dijit.byId("main_branch_id").focus();
			//return false;
	//	}
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>'branch','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_branch"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/rsvacl/branch";
			},
			error: function(e) {
			}
		});
	}
}
</script>