<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("EDIT_STUDENT_ATTENDENCE"));
	$row_sub=$this->rows_sub;
	$_model = new Foundation_Model_DbTable_DbStudentAttendance();
?>	
<head>
  <meta charset="utf-8">
</head>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$payment_term = $this->payment_term;
	$rs_sub=$this->rows_sub;
?>	
<style>
select{ width:100%;}
fieldset{  background:none;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 0px; border:1px solid #ccc;font-size: 12px;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}

div.panel {
    padding: 0 18px;
    display: none;
    background-color: white;
}
div.panel.show {
    display: block;
}
table#table_row tr th,
table#table_row tr td {
    border: solid 1px #ccc;
    text-align: center;
}

</style>
<style>
ul.blogscoresubject li{list-style: none;width:10%;float: left; }
ol.blogscoresubject li{list-style: none;width:10%;float: left; }
ol{margin: 10px;}
table#table_row {
    width: 100%;
}
.label-info {
    background: #466979;
    color: #fff;
    margin-top: 10px;
    border: solid 1px #d8e1e0;
    padding: 3px 0;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_STUDENT_ATTENDENCE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	 <form id='office_receipt' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
   				if(this.validate()) {
					loadingBlock();
   					 return true;
   				}else {
    				return false;
   				}
			</script>
			
			<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select class="fullside" tabindex="15" name="branch_id" readonly="readonly" queryExpr="*${0}*" autoComplete="false" id="branch_id" dojoType="dijit.form.FilteringSelect" onchange="getInfoBybranch();">
								<option value=""><?php echo $tr->translate("SELECT_BRANCH");?></option>
								<?php if(!empty($this->branch_id))foreach ($this->branch_id as $row){?>
								<option value="<?php echo $row['id']?>" <?php if ($this->row['branch_id']==$row['id']){ echo "selected='selected'";}?>><?php echo $row['name']?></option>
								<?php }?>
							</select>
		                </div>
		             </div>
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="group" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDY_YEAR");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="year_study" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DEGREE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select id="degree" name="degree" onchange="" readonly="readonly" class="fullside" dojoType="dijit.form.FilteringSelect" queryExpr="*${0}*" autoComplete="false" >
								<option value="-1"><?php echo $tr->translate("SELECT_DEGREE");?></option>
							<?php if(!empty($this->degree)){foreach ($this->degree as $degree){?>
								<option value="<?php echo $degree['id'];?>"><?php echo $degree['name'];?></option>
							<?php }}?>
							</select>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GRADE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select id="grade" name="grade" onchange="" readonly="readonly" class="fullside" dojoType="dijit.form.FilteringSelect" queryExpr="*${0}*" autoComplete="false">
								<option value="-1"><?php echo $tr->translate("SELECT_GRADE");?></option>
								<?php if(!empty($this->grade)){foreach ($this->grade as $grade){?>
									<option value="<?php echo $grade['id'];?>"><?php echo $grade['name'];?></option>
								<?php }}?>
							</select>
		                </div>
		             </div>
		             <div class="form-group">
		             	 <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SESSION");?> </label>
		                 <div class="col-md-7 col-sm-7 col-xs-12">
							<select id="session" name="session"  class="fullside" dojoType="dijit.form.FilteringSelect" readonly="readonly" >
								<option value="-1"><?php echo $tr->translate("CHOOSE_SESSION");?></option>
							<?php if(!empty($this->session)){foreach ($this->session as $session){?>
								<option value="<?php echo $session['key_code'];?>"><?php echo $session['view_name'];?></option>
							<?php }}?>
							</select>
						</div>
		             </div>
		         </div>
		         <div class="col-md-4 col-sm-4 col-xs-12">
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ATTENDANCE_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="attendence_date" constraints="{datePattern:'dd/MM/yyyy'}" name="attendence_date" type="text" value="<?php echo $this->row['date_attendence'];?>">
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ROOM_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select id="room" name="room" class="fullside" type="text" value="-1" dojoType="dijit.form.FilteringSelect" queryExpr="*${0}*" autoComplete="false">
						   		<option value="-1"><?php echo $tr->translate("SELECT_ROOM");?></option>
						   		<?php if(!empty($this->room)){foreach ($this->room as $room){?>
						   		<option value="<?php echo $room['id'];?>"><?php echo $room['name'];?></option>
						   		<?php }}?>
						    </select>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("FOR_SEMESTER");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="for_semester" name="for_semester" type="text">								
								<option value="1" <?php if($this->row['for_semester']==1){echo"selected";};?>>ទី 1</option>
								<option value="2" <?php if($this->row['for_semester']==2){echo"selected";};?>>ទី 2</option>
							</select>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SESSION_TYPE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="session_type" name="session_type" type="text">								
								<option value="1" <?php if($this->row['for_session']==1){echo"selected";};?>><?php echo $tr->translate("MORNING");?></option>
								<option value="2" <?php if($this->row['for_session']==2){echo"selected";};?>><?php echo $tr->translate("EVENING");?></option>
							</select>
		                </div>
		             </div>
		             <div class="form-group hidden">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SUBJECT");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="subject">
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="status" name="status" type="text">								
								<option value="1"><?php echo $tr->translate("ACTIVE");?></option>
								<option value="0"><?php echo $tr->translate("DEACTIVE");?></option>
							</select>
		                </div>
		             </div>
		         </div>
		         <div class="col-md-4 col-sm-4 col-xs-12">
		    		<div class="form-group">
		                <label class="control-label  col-md-12 col-sm-12 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
		             </div>
		             <div class="form-group">
		                <div class="col-md-12 col-sm-12 col-xs-12">
		                	<textarea class="fullside"  style=" height: 60px !important;font-family:'Khmer Os Battambang';" tabindex="20" dojoType=""  id="note" name="note"  ><?php echo $this->row['note'];?></textarea>
		                </div>
		             </div>
		         </div>
		     </div>
		     <div class="card-box">
	    		 <div class="col-md-12 col-sm-12 col-xs-12">
	    		 	<div class="label-info">
	    		 		<input type="checkbox" onchange="CheckAll();"  name="check_all" id="check_all" value="1" style=" margin: 0 10px; vertical-align: middle;"/>
						<label><?php echo $tr->translate("CHECK_ALL_BY");?></label>
						<input type="radio" onchange="CheckAll();" checked="checked"  name="attendence_opt" id="attendence_opt" value="1" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("PRESENT");?></label>
						<input type="radio" onchange="CheckAll();" name="attendence_opt" id="attendence_opt" value="2" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("ABSENT");?></label>
						<input type="radio" onchange="CheckAll();" name="attendence_opt" id="attendence_opt" value="3" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("PERMISSION");?></label>
						<input type="radio" onchange="CheckAll();" name="attendence_opt" id="attendence_opt" value="4" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("LATE");?></label>
						<input type="radio" onchange="CheckAll();" name="attendence_opt" id="attendence_opt" value="5" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("EARLY_LEAVE");?></label>
	    		 	</div>
	    		 </div>
	    		  <div class="col-md-12 col-sm-12 col-xs-12">
	    		  	<labal id="liststudent"></labal>
					<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
					</table>
	    		 </div>
	    	</div>
	    	<div class="clearfix"></div>
	       	<div class="card-box mt-20 ">
	      	 	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
              		 <input type="hidden" name="identity" id="identity"  value="" >
					 <input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
            	 </div>
            </div>
		</form>
    </div>
 </div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore"); 
	dojo.require("dijit.form.DateTextBox");
var subject_store  = getDataStorefromJSON('id','name',  <?php print_r(array())?>);
var group_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->group));?> );
dojo.ready(function(){
		var years_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->row_year));?> );
		new dijit.form.FilteringSelect({
		    store:years_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                        
		    required: true,
		    id: "year_study",
		    name: "year_study",   
		    readOnly:true,           
		    class: 'fullside',  
		    required:'true',
		    placeHolder:"Selected Study Years",          
		    onChange: function(){  
		    }
		}, "year_study");

		
		new dijit.form.FilteringSelect({
		    store:subject_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                      
		    required: false,
		    id: "subject",
		    name: "subject",   
		    class: 'fullside',  
		    value:'<?php echo $this->row['subject_id'];?>',
		    searchAttr: "name",
		    placeHolder:"Selected Subject",          
		    onChange: function() {  
		    }
		}, "subject");
		
		new dijit.form.FilteringSelect({
			store:group_store,
			queryExpr: "*${0}*",
			autoComplete: false,                       
			required: false,               
			id: "group",
			name: "group",
			readOnly:true,    
			class: 'fullside', 
			value:"<?php echo $this->row['group_id'];?>",   
			placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",
			 onChange: function() {  
				 getInfoBygroup();    
			    }
		}, "group");
		getallgroupby();
		 var branch_id = dijit.byId('branch_id');
		 	branch_id.on('change', function(evt) {
		 		getallgroupby();
		    });
		    
		getInfoBygroup(1);
		initailize();
});
	function getallgroupby(){// 
		var url_data = '<?php echo $this->url(array('module'=>'issue','controller'=>'studentattendance','action'=>'get-allstubygroup')); ?>';
		branch_id = dijit.byId("branch_id").attr("value");
		if(branch_id==''){  
			dijit.byId("branch_id").focus();
			return false;}
		dojo.xhrPost({
			url:url_data,
			content:{
				'branch_id':branch_id,
			},
			handleAs:"json",
			load: function(data) {
				group_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('group').set('store',group_store);
			    document.getElementsByClassName("overlay")[0].style.display="none";	
			},
			error: function(err) {
			}
		});
	}

var url_getStudent= '<?php echo $this->url(array('module'=>'issue','controller'=>'studentattendance','action'=>'get-student')); ?>';
function filterStudent(){
	year = dijit.byId('year_study').get('value');
	grade = dijit.byId('grade').get('value');
	session = dijit.byId('session').get('value');

	if(year==''){
		return false;
	}
	if(grade==''){
		return false;
	}
	if(session==''){
		return false;
	}
	dojo.xhrPost({
	    url: url_getStudent,
	    content : { 
		    'year':year,
			'grade':grade,
			'session':session,
		},				    
	   handleAs:"json", 
	   load: function(data) {
		   tem="";
	       if(data!=""){
				num =0;
				title=0;
				temp='';
				str='';
				column = 0;
				str='';
				for(i=0;i<data.length;i++){ //alert(data[i].stu_id);
					inx = i+1;
					num++;
					var gender='';
					if(data[i].sex==1){
						gender="<?php echo $tr->translate("MALE");?>";
					}else{
						gender="<?php echo $tr->translate("FEMALE");?>";
					}
					if(i<1){
					str+='<tr class="head-td">';
						str+='<th><?php echo $tr->translate("NUM");?></th>';
						str+='<th><?php echo $tr->translate("STUDEN_CODE");?></th>';
						str+='<th><?php echo $tr->translate("STUDEN_NAME");?></th>';
						str+='<th><?php echo $tr->translate("GENDER");?></th>';
						str+='<th><?php echo $tr->translate("STUDENT_MARK");?></th>';
						str+='<th><?php echo $tr->translate("DESCRIPTION");?></th>';
					str+='</tr>';
					}
					str+='<tr style=" background: #fff;">';
						str+='<td>'+inx+'</td>';
						str+='<td>'+data[i].stu_code+'</td>';
						str+='<td style="text-align: left;">&nbsp;'+data[i].stu_name+'</td>';
						str+='<td>'+gender+'<input type="hidden" name="student_id'+inx+'" id="student_id'+inx+'"  value="'+data[i].stu_id+'" ></td>';
						str+='<td>';
							str+='<input type="radio"  name="attedence'+inx+'" id="attedence'+inx+'" value="1" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("PRESENT");?></label>';
							str+='<input type="radio"  name="attedence'+inx+'" id="attedence'+inx+'" value="2" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("ABSENT");?></label>';
							str+='<input type="radio"  name="attedence'+inx+'" id="attedence'+inx+'" value="3" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("PERMISSION");?></label>';
						str+='</td>';
						str+='<td><input dojoType="dijit.form.Textarea"  class="fullside" id="comment'+inx+'" name="comment'+inx+'" type="text" value=""></td>';
					str+='</tr>';
				    if(inx!=1) {//identity set value 1,2,3,4,5
						var identity = $('#identity').val();
						$('#identity').val(identity+','+inx);
					} else {
						$('#identity').val(inx);
					}
				}
				document.getElementById("table_row").innerHTML = str;
				
	       }else{
	    	   $('#identity').val('');
	    	   document.getElementById("table_row").innerHTML = '';
	       }
	   },		
	    error: function(err) {
	    }
	});
	
}
function gender(sex){
	if(sex==1){
		sex='Male';
	}else sex='Female';
	return sex;
}
</script>
<script> //validate controll form 
function AllowOnlyNumbers(e) {
    e = (e) ? e : window.event;
    var key = null;
    var charsKeys = [
        97, // a  Ctrl + a Select All
        65, // A Ctrl + A Select All
        99, // c Ctrl + c Copy
        67, // C Ctrl + C Copy
        118, // v Ctrl + v paste
        86, // V Ctrl + V paste
        115, // s Ctrl + s save
        83, // S Ctrl + S save
        112, // p Ctrl + p print
        80 // P Ctrl + P print
    ];

    var specialKeys = [
	    8, // backspace
	    9, // tab
	    27, // escape
	    13, // enter
	    35, // Home & shiftKey +  #
	    36, // End & shiftKey + $
	    37, // left arrow &  shiftKey + %
	    39, //right arrow & '
	    46, // delete & .
	    109,//.
	    45 //Ins &  -
    ];

    key = e.keyCode ? e.keyCode : e.which ? e.which : e.charCode;

    // check if pressed key is not number 
    if (key && key < 48 || key > 57) {
        //Allow: Ctrl + char for action save, print, copy, ...etc
        if ((e.ctrlKey && charsKeys.indexOf(key) != -1) ||
            //Fix Issue: f1 : f12 Or Ctrl + f1 : f12, in Firefox browser
            (navigator.userAgent.indexOf("Firefox") != -1 && ((e.ctrlKey && e.keyCode && e.keyCode > 0 && key >= 112 && key <= 123) || (e.keyCode && e.keyCode > 0 && key && key >= 112 && key <= 123)))) {
            return true
        }
            // Allow: Special Keys
        else if (specialKeys.indexOf(key) != -1) {
            //Fix Issue: right arrow & Delete & ins in FireFox
            if ((key == 39 || key == 45 || key == 46 || key == 109)) {
                //return (navigator.userAgent.indexOf("Firefox") != -1 && e.keyCode != undefined && e.keyCode > 0);
                return true
            }
                //DisAllow : "#" & "$" & "%"
            else if (e.shiftKey && (key == 35 || key == 36 || key == 37)) {
                return false;
            }
            else {
                return true;
            }
        }
        else {
            return false;
        }
    }
    else {
        return true;
       }
    }
//////////////////////////////////////////////////
function getInfoBygroup(type=null){
	url_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getgroupinfo'));?>';
	group = dijit.byId('group').get('value');
	if(group==''){
		alert("Please Select Group");
		return false;
	}
	dojo.xhrPost({
		url:url_group,	
		content:{ 
			'group_id': group
		},
		handleAs:"json",
		load: function(data) {
			dijit.byId('year_study').set('value',data.academic_year);
			dijit.byId('year_study').set('readOnly',true);
			
			dijit.byId('degree').set('value',data.degree);
			dijit.byId('degree').set('readOnly',true);
			
			dijit.byId('grade').set('value',data.grade);
			dijit.byId('grade').set('readOnly',true);
			
			dijit.byId('session').set('value',data.session);
			dijit.byId('session').set('readOnly',true);
			
			dijit.byId('room').set('value',data.room_id);
			//dijit.byId('room').set('readOnly',true);
			filterStudentBygroup(type);

			if(data.degree==2){
				getSubjectByGroup(type);
			}
			 dijit.byId('subject').reset();
		},
		error: function(err) {
		}
	});
}
var url_getSubject= '<?php echo $this->url(array('module'=>'issue','controller'=>'studentattendance','action'=>'getsubjectbygroup')); ?>';
function getSubjectByGroup(type=null){
	dojo.xhrPost({
	    url: url_getSubject,
	    content : { 
		    'group':group,
		},				    
	   handleAs:"json", 
	   load: function(data){
		   subject_store  = getDataStorefromJSON('id','name', data);
		   dijit.byId('subject').set('store',subject_store);  
		   if(type!=null){
		  	 dijit.byId('subject').set('value','<?php echo $this->row['subject_id'];?>');
		   }
	   },		
	    error: function(err) {
		}
	});
}
var url_getStudentbygroup= '<?php echo $this->url(array('module'=>'issue','controller'=>'studentattendance','action'=>'get-student-bygroup')); ?>';
function filterStudentBygroup(type=null){
	group = dijit.byId('group').get('value');
	var textareastyle=" font-family: 'Khmer OS Battambang'";
	if(group==''){
		return false;
	}
	if(type!= null){
		return false;
	}
	dojo.xhrPost({
	    url: url_getStudentbygroup,
	    content : { 
		    'group':group,
		},				    
	   handleAs:"json", 
	   load: function(data) {
		   tem="";
	       if(data!=""){
				num =0;
				title=0;
				temp='';
				str='';
				column = 0;
				str='';
				for(i=0;i<data.length;i++){ //alert(data[i].stu_id);
					inx = i+1;
					num++;
					var gender='';
					if(data[i].sex==1){
						gender="<?php echo $tr->translate("MALE");?>";
					}else{
						gender="<?php echo $tr->translate("FEMALE");?>";
					}
					if(i<1){
					str+='<tr class="head-td">';
						str+='<th><?php echo $tr->translate("NUM");?></th>';
						str+='<th><?php echo $tr->translate("STUDEN_CODE");?></th>';
						str+='<th><?php echo $tr->translate("STUDEN_NAME");?></th>';
						str+='<th><?php echo $tr->translate("GENDER");?></th>';
						str+='<th><?php echo $tr->translate("ATTENDANCE");?></th>';
						str+='<th><?php echo $tr->translate("DESCRIPTION");?></th>';
					str+='</tr>';
					}
					str+='<tr style=" background: #fff;">';
						str+='<td>'+inx+'</td>';
						str+='<td>'+data[i].stu_code+'</td>';
						str+='<td style="text-align: left;">&nbsp;'+data[i].stu_name+'</td>';
						str+='<td>'+gender+'<input type="hidden" name="student_id'+inx+'" id="student_id'+inx+'"  value="'+data[i].stu_id+'" ></td>';
						str+='<td>';
							str+='<input type="radio" checked="checked" name="attedence'+inx+'" id="attedence'+inx+'" value="1" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("PRESENT");?></label>';
							str+='<input type="radio"  name="attedence'+inx+'" id="attedence'+inx+'" value="2" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("ABSENT");?></label>';
							str+='<input type="radio"  name="attedence'+inx+'" id="attedence'+inx+'" value="3" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("PERMISSION");?></label>';
							str+='<input type="radio"  name="attedence'+inx+'" id="attedence'+inx+'" value="4" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("LATE");?></label>';
							str+='<input type="radio"  name="attedence'+inx+'" id="attedence'+inx+'" value="5" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("EARLY_LEAVE");?></label>';
						str+='</td>';
						str+='<td><input dojoType="dijit.form.Textarea"  class="fullside" id="comment'+inx+'" name="comment'+inx+'" type="text" value="" style="'+textareastyle+'"></td>';
					str+='</tr>';
				    if(inx!=1) {//identity set value 1,2,3,4,5
						var identity = $('#identity').val();
						$('#identity').val(identity+','+inx);
					} else {
						$('#identity').val(inx);
					}
				}
				document.getElementById("table_row").innerHTML = str;
				 
				
	       }else{
	    	   $('#identity').val('');
	    	   document.getElementById("table_row").innerHTML = '';
	       }
	   },		
	    error: function(err) {
	    }
	});
	
}
function CheckAll(){
	var identity = $('#identity').val();
	check_type = $('input[name="attendence_opt"]:checked').val();
	if(identity==""){
		return false;
	}else{
		 var arrays = identity.split(',');
		 if(arrays!=""){
	    	 for(var i=1;i<= arrays.length;i++) {
	    		 if($("#check_all").is(':checked')){
	    			 $('input[value="'+check_type+'"]').attr("checked",true);
	    		 }else{
	    			 $('input[value="'+check_type+'"]').attr("checked",false);
	    		 }
	    	}
		}
	}
}

function initailize(){
	str=""; 
	var textareastyle=" font-family: 'Khmer OS Battambang'";
	<?php if (!empty($this->allstudentBygroup)) { foreach ($this->allstudentBygroup as $key=> $row){
			$student_att = $_model->getAttendeceStatus($this->row['id'],$row['stu_id']);
		?>
			inx = parseFloat(<?php echo $key?>)+1;

			<?php if ($row['sex']==1){
				$gender = $tr->translate("MALE");
				}else{
					$gender = $tr->translate("FEMALE");
				}?>
			<?php if ($key<1){?>
			str+='<tr class="head-td">';
				str+='<th><?php echo $tr->translate("NUM");?></th>';
				str+='<th><?php echo $tr->translate("STUDEN_CODE");?></th>';
				str+='<th><?php echo $tr->translate("STUDEN_NAME");?></th>';
				str+='<th><?php echo $tr->translate("GENDER");?></th>';
				str+='<th><?php echo $tr->translate("ATTENDANCE");?></th>';
				str+='<th><?php echo $tr->translate("DESCRIPTION");?></th>';
			str+='</tr>';
			<?php }?>
				str+='<tr style=" background: #fff;">';
				str+='<td>'+inx+'</td>';
				str+='<td><?php echo $row['stu_code'];?></td>';
				str+='<td style="text-align: left;">&nbsp;<?php echo $row['stu_name'];?></td>';
				str+='<td><?php echo $gender;?><input type="hidden" name="student_id'+inx+'" id="student_id'+inx+'"  value="<?php echo $row['stu_id'];?>" ></td>';
				str+='<td>';
					str+='<input type="radio" <?php if (empty($student_att['attendence_status'])){echo 'checked="checked"';}?> name="attedence'+inx+'" id="attedence'+inx+'" value="1" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("PRESENT");?></label>';
					str+='<input type="radio" <?php if ($student_att['attendence_status']==2){echo 'checked="checked"';}?>  name="attedence'+inx+'" id="attedence'+inx+'" value="2" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("ABSENT");?></label>';
					str+='<input type="radio" <?php if ($student_att['attendence_status']==3){echo 'checked="checked"';}?> name="attedence'+inx+'" id="attedence'+inx+'" value="3" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("PERMISSION");?></label>';
					str+='<input type="radio" <?php if ($student_att['attendence_status']==4){echo 'checked="checked"';}?> name="attedence'+inx+'" id="attedence'+inx+'" value="4" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("LATE");?></label>';
					str+='<input type="radio" <?php if ($student_att['attendence_status']==5){echo 'checked="checked"';}?> name="attedence'+inx+'" id="attedence'+inx+'" value="5" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("EARLY_LEAVE");?></label>';
				str+='</td>';
				str+='<td><input dojoType="dijit.form.Textarea"  class="fullside" id="comment'+inx+'" name="comment'+inx+'" type="text" value="<?php echo str_replace("'", '', $student_att['description']); ?>" style="'+textareastyle+'"></td>';
			str+='</tr>';
		    if(inx!=1) {//identity set value 1,2,3,4,5
				var identity = $('#identity').val();
				$('#identity').val(identity+','+inx);
			} else {
				$('#identity').val(inx);
			}

		    document.getElementById("table_row").innerHTML = str;
	<?php }
	}else{?>
    	   $('#identity').val('');
    	   document.getElementById("table_row").innerHTML = '';
	<?php }?>
}
</script>