<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_HOLIDAY'));
$dept='';
if(!empty($this->row['dept'])){
$dept =  explode(",",$this->row['dept']);
}
$array = array();
if (!empty($dept)) {
    foreach ($dept as $ss) {
        $array[$ss] = $ss;
    }
}
?>	
<?php  $holiday= $this->frm_holiday;?>
<script>
       dojo.require("dijit.form.DateTextBox");
       dojo.require("dijit/form/NumberTextBox");
</script>

<form  id='add_techer' action="" dojoType="dijit.form.Form" method="post"
 enctype="application/x-www-form-urlencoded">
 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
                dijit.byId("save_new").set("disabled",true);
				dijit.byId("save_close").set("disabled",true);
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="100%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("EDIT_HOLIDAY");?></strong></legend>
				<table style="margin: 0 auto; width: 100%;" cellspacing="10">
					<tr>
						<td  width="70%" style=" vertical-align: top;">
							<table style="margin: 0 auto; width: 100%;" cellspacing="10">
								<tr>
									<td><?php echo $tr->translate("HOLIDAY_NAME")?></td>
									<td><?php  echo $holiday->getElement('holiday_name');?><?php  echo $holiday->getElement('id');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("START_DATE")?></td>
									<td><?php  echo $holiday->getElement('start_date');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("AMOUNT_DAY")?></td>
									<td><?php  echo $holiday->getElement('amount_day');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("END_DATE")?></td>
									<td><?php  echo $holiday->getElement('end_date');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("NOTE")?></td>
									<td><?php  echo $holiday->getElement('note');?></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("STATUS")?></td>
									<td><?php  echo $holiday->getElement('status');?></td>
								</tr>
								
							</table>
						</td>
						<td  width="30%" style=" vertical-align: top;">
							<table style="margin: 0 auto; width: 100%;" cellspacing="1">
								<tr>
									<td>
										<?php echo $tr->translate("DEGREE")?>
									</td>
								</tr>
								<tr>
									<td><input style="  height: 15px; margin-right: 10px;" onchange="checkall();" type="checkbox"  class="checkbox" id="check_all"  name="check_all"/><?php echo $tr->translate("CHECK_ALL")?></td>
								<tr>
								<?php 
								if (!empty($this->faculty)) foreach ($this->faculty as $rs){
								?>
								<tr>
									<td><input style="  height: 15px; margin-right: 10px;" <?php if (in_array($rs['dept_id'], $array)) { echo 'checked="checked"';}?> type="checkbox"  class="checkbox" id="depts<?php echo $rs['dept_id'];?>" value="<?php echo $rs['dept_id'];?>"  name="selector[]"/><?php echo $rs['en_name'];?></span></td>
								</tr>
								<?php } ?>
							</table>
						</td>
						<tr>
							<td colspan="2" align="center">
									<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
									<input type="submit" value="" label="<?php echo $tr->translate('SAVECLOSE');?>" id="submitButton" dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave"/>
							</td>
						</tr>
					</tr>
				</table>
				
									
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<?php $base_url = Application_Form_FrmMessage::getUrl("/"); ?>
​
<script>
function checkall(){
	if ($('#check_all').is(':checked')) {
		$(".checkbox").prop('checked', true);
	}else{
		$(".checkbox").prop('checked', false);
	}
}
function checkall(){
	if ($('#check_all').is(':checked')) {
		$(".checkbox").prop('checked', true);
	}else{
		$(".checkbox").prop('checked', false);
	}
}
function CalculateDate(){
	pay_type = dijit.byId('start_date').value;
	amount_day = dijit.byId('amount_day').get('value');
	
	if(isNaN(amount_day)){
		//alert('សូមបញ្ចលចំនួនរយៈពេល​ !');
		dijit.byId('amount_day').focus();
	}else{
		start_date = dijit.byId("start_date").value;
		var a = new Date(start_date);
		
		var mm = a.getMonth() + 1;
		var dd = a.getDate()+parseInt(amount_day)-1;
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('end_date').attr('value',epx_date);
}
}

</script>