<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_DUTY_SETTING')); 
?>
<?php  $frm = $this->frm_branch;?>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-user " aria-hidden="true"></i>&nbsp;<i class="fa fa-cogs" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate('ADD_DUTY_SETTING');?></h4>
    				<span id="message"></span>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id="frm_branch" action="<?php echo $this->url(array('module'=>'setting','controller'=>'dutysetting','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
				
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="tab-content">
					<!--Panel 2-->
					<div >
						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("DUTY_INFOMATION");?></p>
												</div> 
											</div>
											 <div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NAME_KH");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("duty_namekh");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NAME_EN");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("duty_nameen");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("POSITION_KH");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("positionkh");?>
											   </div>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("POSITION_EN");?>
											   </label>
											   <div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("positionen");?>
											   </div>
											</div>
											
										</div>
									</div>
								</div>
							</div>
							
							<div class="card-blogform">
								<div class="card-body bg-info"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-file" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("NOTE");?></p>
												</div> 
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-12 col-sm-12 col-xs-12" >
													1, <?php echo $tr->translate("IMAGE_SIZE_OF_SIGNATURE");?> 
											   </label>
											</div>
											<div class="form-group">
											   <label class="control-label bold col-md-12 col-sm-12 col-xs-12" >
													2, <?php echo $tr->translate("IMAGE_SIZE_OF_STAM");?>
											   </label>
											</div>
											
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="card-blogform">
									<div class="card-body"> 
										<div class="row"> 
											<div class="col-md-12 col-sm-12 col-xs-12"> 
												<div class="d-flex"> 
													<div class="settings-main-icon ">
														<i class="glyphicon glyphicon-picture" aria-hidden="true"></i>
													</div> 
													<div class="col-md-10 col-sm-10 col-xs-12"> 
														<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STAMP");?></p>
													</div> 
												</div>
												<div class="form-group">
													<div class="col-md-12 col-sm-12 col-xs-12">
														<div class="account-image">
															<div class="image-box">
																<img id="view_admin_stamp" src="<?php echo $this->baseUrl().'/images/noimage.jpg';?>" alt=""  />
															</div>
															<div class="button_browse">
															<div id='preview'></div>	
																<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
																<input class="btn_borwse_image" type="file" id="stamp" name="stamp" >
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">
								<div class="card-blogform">
									<div class="card-body"> 
										<div class="row"> 
											<div class="col-md-12 col-sm-12 col-xs-12"> 
												<div class="d-flex"> 
													<div class="settings-main-icon ">
														<i class="glyphicon glyphicon-picture" aria-hidden="true"></i>
													</div> 
													<div class="col-md-10 col-sm-10 col-xs-12"> 
														<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("SINATURE");?></p>
													</div> 
												</div>
												<div class="form-group">
													<div class="col-md-12 col-sm-12 col-xs-12">
														<div class="account-image">
															<div class="image-box">
																<img id="view_admin_signature" src="<?php echo $this->baseUrl().'/images/noimage.jpg';?>" alt=""  />
															</div>
															<div class="button_browse">
															<div id='preview'></div>	
																<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
																<input class="btn_borwse_image" type="file" id="signature" name="signature" >
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
						</div>
					</div>
					<!--END Panel 2-->
				</div>
			</div>

            <div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" class="button-class button-danger"  iconClass="glyphicon glyphicon-repeat" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button"  />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new"  id="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button"  />
               	</div>
             </div>
		</form>
	</div>
</div>
<style>
.image-box {
    text-align: center;
    height: 160px;
}
.image-box img {
    height: 160px;
}

.button_browse {
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 38px;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 38px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 100%;
    margin: 0 auto;
}
ul.optListRow {
    list-style-type: none;
    margin: 0;
    padding: 0;
    padding-left: 35px;
}
 input[type=checkbox],  input[type=radio]{
	height: 15px;
    display: initial;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.ready(function(){

	
    
});


function readURLAdminStamp(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#view_admin_stamp').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#stamp").change(function(){
	readURLAdminStamp(this);
});

function readURLAminSignature(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#view_admin_signature').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#signature").change(function(){
	readURLAminSignature(this);
});


function submitDataClose(){
	if(dijit.byId('frm_branch').validate()) {
	
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'setting','controller'=>'dutysetting','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_branch"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/setting/dutysetting";
			},
			error: function(e) {
			}
		});
	}
}
</script>