<?php 
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
#table tr td{
	border:1px solid #cccccc;
	text-align: center;
}
#table tr th{
	background: #cccccc;
	border:1px solid #ddd;
}
</style>
<title><?php echo $this->tr->translate("ADD_START_DATE_AND_END_DATE")?></title>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-tasks" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_START_DATE_AND_END_DATE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id="add_province" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	  			 if(this.validate()) {
					academic_year = dijit.byId("academic_year").get('value');
					if(academic_year=='' || academic_year==-1){
						alert("<?php echo $tr->translate("PLEASE_SELECT_ACADEMIC_YEAR");?>");
						dijit.byId("academic_year").focus();
						return false;
					}
					var rowId = $('#identity').val();
					if(rowId==''){ 
						alert("<?php echo $tr->translate("PLEASE_ADD_TERM_DURATION");?>");
						return false;
					}
					if(rowId!=''){ 
						var rowIDArray = rowId.split(',');
						for(var n = 0; n < rowIDArray.length; n++){
							var row_id = dijit.byId('title_'+rowIDArray[n]).get('value');
							if(row_id==''){
								alert("<?php echo $tr->translate("PLEASE_ENTER_TERM_TITLE");?>");
								return false;
							}
						}
						
					}
					loadingBlock();
					return true;
	  			 }else {
					return false;
	   			}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select dojoType="dijit.form.FilteringSelect" class="fullside" id="branch_id" name="branch_id" type="text">
								<?php if(!empty($this->rsbranch)){ foreach ($this->rsbranch as $rs){?>	
									<option value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
								<?php }}?>
							</select>	
		                </div>
		            </div>
					<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ACADEMIC_YEAR");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select dojoType="dijit.form.FilteringSelect" class="fullside" id="academic_year" name="academic_year" type="text">
								<option value=""><?php echo $tr->translate("SELECT_YEAR");?></option>
								<?php if(!empty($this->year)){ foreach ($this->year as $year){?>	
									<option value="<?php echo $year['id'];?>"><?php echo $year['name'];?></option>
								<?php }}?>
							</select>	
		                </div>
		             </div>
				</div>
				<div class="col-md-8 col-sm-8 col-xs-12">
					<table class="collape tablesorter" id="table_row" style="width:100%; white-space: nowrap;border:1px solid #ddd;">
				    	<tr id="head-title" class="head-td" align="right"></tr>
					</table>
					<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
					<input type="button" label="<?php echo $tr->translate('ADD_TERM');?>" dojoType="dijit.form.Button" 
						iconClass="dijitIconEditProperty" onclick="addRow();" />
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" value="Clear" label="Clear"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
					<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVE_CLOSE");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
    </div>
</div>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
    dojo.require("dijit.form.FilteringSelect");
	dojo.ready(function(){ 
		addRow();
	});

	var col= 0; var no=0;
	var title = 0;
	function addRow() {
		col++;no++;
		template='';
		temp = "";
	
		if(title!=1){
			temp+='<td><?php echo $tr->translate("DEL");?></td>';
			temp+='<td><?php echo $tr->translate("N_O");?></td>';
			temp+='<td><?php echo $tr->translate("TITLE");?></td>';
			temp+='<td><?php echo $tr->translate("START_DATE");?></td>';
			temp+='<td><?php echo $tr->translate("END_DATE");?></td>';
			temp+='<td><?php echo $tr->translate("NOTE");?></td>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			
		template+='<td width="2%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td align="center" width="2%">'+no+'</td>';
		template+='<td width="10%"><input required="1" dojoType="dijit.form.ValidationTextBox" class="fullside" id="title_'+col+'" name="title_'+col+'" placeholder="'+'<?php echo $tr->translate("TERM")." ";?>'+col+'" value="" type="text"  ></td>';	
		template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox" value="now" class="fullside" id="startdate_'+col+'" name="startdate_'+col+'" value="" type="text" required="required" ></td>';	
		template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox"  value="now" class="fullside" id="enddate_'+col+'" name="enddate_'+col+'" value="" type="text" required="required" ></td>';	
		template+='<td width="10%"><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="remark_'+col+'" name="remark_'+col+'" value="" type="text"  ></td>';	
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
	}
	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		
		if(arrays[i] == index) arrays.splice(i,1);
			
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>