<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("about"));
$frm = $this->frm;

$urlDelete = $this->baseUrl()."/mobileapp/about/delete/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('about');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("adv_search");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("start_date");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("end_date");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement('search_status');?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	            	</div>
	            </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script>
dojo.require("dijit.form.DateTextBox");
var row=0;
var url="";
var indexkey="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="delete"){
				url='<?php echo $urlDelete;?>';
			}
			
			gotoAction();
			//window.console && console.log(m) || alert(m); 
		},
		items: {
			"delete": {name: "<?php echo $tr->translate("DELETE");?>", icon: "delete", accesskey: "e"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	if(indexkey=='delete'){
	    if (confirm("<?php echo $tr->translate("Do you want to delete this record ?");?>")) {
	    	window.location.href = url+row;
	    } else {
	    	 return false;
	    }
	}else{
	 	window.open(url+row, '_blank');
	}
}
</script>