<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SERVICE_FEE"));
	$url_copy =$this->url(array('module'=>'accounting','controller'=>'servicecharge','action'=>'copy'));
	$urlCopy = $this->baseUrl()."/accounting/servicecharge/copy/id/";
	$urlEdit = $this->baseUrl()."/accounting/servicecharge/edit/id/";
	$formList = new Application_Form_Frmtable();
	$frm =  $this->form_search;
	$frm_fee = $this->frm_fee;
?>	
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	
var aca_year= getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rows_year));?> );

	dojo.ready(function(){
	new dijit.form.FilteringSelect({
	    store: aca_year,
	    autoComplete: true,                        
	    required: false,
	    id: "year",
	    name: "year",
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_YEAR");?>",          
	    onChange: function() {  
	    	 
	    }
	}, "year");
	dijit.byId('year').attr('value','<?php echo $this->adv_search['year']?>');
});
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					 <div class="col-md-3 col-sm-3 col-xs-12">
					 	<?php echo $frm->getElement("title");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					  	<?php echo $frm->getElement("branch_id");?>
					 </div>
					  <div class="col-md-2 col-sm-2 col-xs-12">
					  <?php echo $frm_fee->getElement("year");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					  	<?php echo $frm_fee->getElement("is_finished_search");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					  	<?php echo $frm->getElement("status");?>
					 </div>
					 <div class="col-md-1 col-sm-1 col-xs-12">
					 	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					 </div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
	



 
<script type="text/javascript">
dojo.require("dijit.form.CheckBox"); 
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");

	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 if(id!=''){
			window.location.href = url+'/id/'+id;
		 }else{
			alert('Please select record you want to copy');
			return false;
		 }
	}

	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}
	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
			
				var m = "clicked: " + key;
				if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}else if(key=="copy"){
					url='<?php echo $urlCopy;?>';
				}
				
				gotoAction();
				//window.console && console.log(m) || alert(m); 
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
				"copy": {name: "<?php echo $tr->translate("COPY");?>", icon: "copy"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}

	var recordid ='';
	function gotoAction(){
		window.location.href =url+row;
		 //window.open(url+row);
	}	
</script> 

 