<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SERVICE_FEE"));
	$urlCopy = $this->baseUrl()."/accounting/servicecharge/copy/id/";
	$urlEdit = $this->baseUrl()."/accounting/servicecharge/edit/id/";
	$frm =  $this->form_search;
	$frm_fee = $this->frm_fee;
?>	
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
             <div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SERVICE_CHARGE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>

		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					 <div class="col-md-3 col-sm-3 col-xs-12">
					 	<?php echo $frm->getElement("title");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					  	<select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" class="fullside" onChange="getAllAcademicByBranch();" id="branch_id" name="branch_id" type="text">
							<option value=""><?php echo $tr->translate("SELECT_BRANCH");?></option>
							<?php if(!empty($this->branch)){ foreach ($this->branch as $year){?>	
								<option value="<?php echo $year['id'];?>" <?php if ($this->adv_search['branch_id']==$year['id']){ echo 'selected="selected"';}?>><?php echo $year['name'];?></option>
							<?php }}?>
						</select>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					  	<input id="year" />
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					  	<?php echo $frm_fee->getElement("is_finished_search");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					  	<?php echo $frm->getElement("status");?>
					 </div>
					 <div class="col-md-1 col-sm-1 col-xs-12">
					 	<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					 </div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                          
			required: false,
			id: "year",
			name: "year",
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_YEAR");?>",          
			onChange: function(){  
				
			}
		},"year");
		getAllAcademicByBranch();
	});
	
	url_getacademic = '<?php echo $this->url(array('module'=>'accounting','controller'=>'servicecharge','action'=>'get-yearbybranch'));?>';
	function getAllAcademicByBranch(){
		dijit.byId('year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getacademic,
			content:{
				'branch_id':branch_id
				},
			handleAs:"json",
			load: function(data){
				academic_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('year').set('store',academic_store);  
				dijit.byId('year').attr("value","<?php echo $this->adv_search['year']?>");
			},
			error: function(err) {
			}
		});
	}
	
	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 if(id!=''){
			window.location.href = url+'/id/'+id;
		 }else{
			alert('Please select record you want to copy');
			return false;
		 }
	}

	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}
	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
			
				var m = "clicked: " + key;
				if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}else if(key=="copy"){
					url='<?php echo $urlCopy;?>';
				}
				gotoAction();
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
				"copy": {name: "<?php echo $tr->translate("COPY");?>", icon: "copy"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.location.href =url+row;
	}	
</script> 