<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('ADD_STUDENT_TEST'));
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/Textarea"]);
 </script>
<form id='frm_teststudent' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttest','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
	</script>
	<table cellspacing="10" class='fullside' >
		<tr>
			<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate('ព័ត៏មានសិស្សធ្វើតេស')?></strong></legend>
						<table cellspacing="10"  width="100%">
							<tr>
								<td width="33%">
									<table cellspacing="5"  width="100%">
										<tr>
											<td><?php echo $tr->translate("NAME_KH")?></td>
											<td><input type="text" name="kh_name" id="kh_name" required="true" class="fullside" dojoType="dijit.form.ValidationTextBox"   /></td>
										</tr>
										<tr>
											<td style="white-space: nowrap;"><?php echo $tr->translate("NAME_EN")?></td>
											<td><input type="text" name="en_name" id="en_name" required="true"  class="fullside" dojoType="dijit.form.ValidationTextBox" /></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("SEX")?></td>
											<td>
												<select name="sex" id="sex" class="fullside" dojoType="dijit.form.FilteringSelect"  >
													<option value="1"><?php echo $tr->translate('MALE')?></option>
													<option value="2"><?php echo $tr->translate('FEMALE')?></option>
												</select>
											</td>						
										</tr>
										<tr>
											<td><?php echo $tr->translate("DOB")?></td>
											<td><input type="text" name="dob" id="dob" class="fullside"  value="now" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox"   /></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("PHONE")?></td>
											<td><input type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox"   /></td>
										</tr>
										<tr>
										    <td><?php echo $tr->translate("ADDRESS")?></td>
											<td><textarea style="height:50px;font-family:'Khmer OS Battambang';font-size: 15px;" class="fullside" name="address" id="address" dojoType="dijit.form.Textarea" ></textarea></td>
										</tr>
									</table>
								</td>
								<td valign="top" width="33%">
									<table cellspacing="5"  width="100%">
										<tr>
										    <td><?php echo $tr->translate("RECEIPT")?></td>
											<td><input readonly="readonly" style="color:red;" type="text" name="receipt" id="receipt" class="fullside" dojoType="dijit.form.TextBox"   /></td>
										</tr>
										<tr>
										    <td><?php echo $tr->translate("SERIAL")?></td>
											<td><input type="text" name="serial" id="serial" class="fullside" dojoType="dijit.form.TextBox"   /></td>
										</tr>
										<tr>
										    <td><?php echo $tr->translate("DEGREE")?></td>
											<td>
												<select name="degree" id="degree" class="fullside" dojoType="dijit.form.FilteringSelect"  >
													<?php if(!empty($this->degree)){foreach($this->degree as $rs){?>
														<option value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
													<?php }}?>
												</select>
											</td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("OLD_SCHOOL")?></td>
											<td><input type="text" name="old_school" id="old_school" class="fullside" dojoType="dijit.form.TextBox"   /></td>
										</tr>
										<tr>
											 <td><?php echo $tr->translate("OLD_GRADE")?></td>
											 <td><input type="text" name="old_grade" id="old_grade" class="fullside" dojoType="dijit.form.TextBox" /></td>
										</tr>
										<tr>
											 <td><?php echo $tr->translate("PRICE")?></td>
											 <td><input type="text" name="test_cost" required="true"  id="test_cost" class="fullside" dojoType="dijit.form.NumberTextBox"   /></td>
										</tr>
									</table>
								</td>
								<td valign="top" width="33%">
									<table cellspacing="0"  width="100%">
										<tr>
											<td valign="top"><?php echo $tr->translate("NOTE")?></td>
											<td><textarea style="height:200px;font-family:'Khmer OS Battambang';font-size: 15px;" rows="9" class="fullside" name="note" id="note" dojoType="dijit.form.Textarea" ></textarea></td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
				</fieldset>
			</td>
		</tr>		
		<tr>
			<td align="center">
				<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
					 iconClass="dijitIconClear"/>
				<input label="<?php echo $tr->translate("SAVE_CLOSE")?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button" type="button" onclick="submitDataClose();" iconClass="dijitEditorIcon dijitEditorIconSave"/>
				<input label="<?php echo $tr->translate("SAVE_NEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button" type="button" onclick="submitDataAddNew();" iconClass="dijitEditorIcon dijitEditorIconSave"/>
				<input label="<?php echo $tr->translate("PRINT")?>" name='print' id='print' value='print' dojoType="dijit.form.Button" onclick="printReceipt('');" type="button" iconClass="dijitIconNewTask"/>
			</td>
		</tr>	
	</table>
</form>
<style>
.headerreceipt{height: 0px !important;}
</style>
<div class="dijitHidden" style="padding: 0px; margin: 0px;">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:24cm;height: 16cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("OFFICIAL_RECEIPT");?>'" id="terms" >
		
		<div id="PrintReceipt" style="width: 20cm !important; height: 10cm ; padding: 0px; ">
			<style>
				.headerreceipt{height: 50px;}
			</style>
			<table width="100%" class="print" cellspacing="0"  cellpadding="0" style="white-space:nowrap;">
				<tr>
					<td colspan="10" valign="top">
						<table width="100%" border="0" cellspacing="5" style="font-family: Khmer OS Battambang;font-size:16px;white-space:nowrap;line-height: 18px;">
							<tr >
								<td width="15%"></td>
								<td width="35%"></td>
								<td width="15%"></td>
								<td width="35%"></td>
							</tr>
							<tr>
								<td colspan="4" class="headerreceipt"></td>
							</tr>
							<tr style="line-height:24px;">
								<td colspan="4" style="text-align:center;font-weight:bold;font-family:'Khmer MEF2';">
									<div style="font-size:18px;">បង្កាន់ដៃបង់ប្រាក់</div>
									<div style="font-size:15px;">OFFICIAL RECEIPT</div>
								</td>	
							</tr>
							<style>
								.h{ margin-top: -3px;margin-bottom: 3px;}
								.tab_row{ margin-top: -8px;}
								.h1{ margin-top: -6px;}
								.values{  height: 18px; padding: 0 5px;display: block;
										 font-family: Khmer OS battambang ,Times New Roman;}
								.fonteng{font-size:13px;}
								.one{white-space:nowrap;font-size:16px;}
								.border{border:1px solid #000;}
							</style>
							<tr style="height: 30px;">
								<td colspan="4" align="center">
									<div style="margin-top:-15px;font-size:17px;">
										N<sup>o</sup> : <label id="lb_receipt" style="color:red;" ></label>
									</div>
								</td>
							</tr>
							<tr style="height: 30px;">
								<td class="one ">&nbsp;ឈ្មោះជាខ្មែរ&nbsp;</td>
								<td class="border"><label id="lb_studentkh" class=" values one "></label> </td>
								<td class="one ">&nbsp;SERIAL&nbsp;</td>
								<td class="border"><label id="lb_serial" class=" values one"></label> </td>
							</tr>
							<tr  style="height: 30px;">
								<td class="one ">&nbsp;ឈ្មោះជាអង់គ្លេស&nbsp;</td>
								<td class="border"><label id="lb_studenten" class="values one"></label> </td>
								<td class="one ">&nbsp;កម្រិតសិក្សា&nbsp;</td>
								<td class="border"><label id="lb_degree" class="values one"></label> </td>
							</tr>
							<tr  style="height: 30px;">
								<td class="one " align="left">&nbsp;ភេទ&nbsp;</td>
								<td class="border"><label id="lb_gender" class="values one"> </label></td>
								<td class="one " align="left">&nbsp;តម្លៃ&nbsp;</td>
								<td class="border"><label id="lb_price" class="values one"> </label></td>
							
								</tr>
							<tr  style="height: 30px;">
								<td class="one " align="left">&nbsp;ថ្ងៃ ខែ ឆ្នំាកំណើត&nbsp;</td>
								<td class="border"><label id="lb_dob" class="values one"> </label></td>
								<td class="one " align="left">&nbsp;ឤសយដ្ឋាន&nbsp;</td>
								<td class="border"><label id="lb_address" class="values one"> </label></td>
							</tr>
							<tr  style="height: 30px;">
								<td class="one " align="left">&nbsp;លេខទូរសព្ទ&nbsp;</td>
								<td class="border"><label id="lb_phone" class="values one"> </label></td>
								<td class="one " align="left">&nbsp;សម្គាល់&nbsp;</td>
								<td class="border"><label id="lb_note" class="values one"> </label></td>
							</tr>
							<tr style="font-size: 15px;">
								<td colspan="2" align="center">&nbsp;</td>
							</tr>
							<tr style="font-size: 15px;">
								<td colspan="2" align="center">អ្នកប្រគល់</td>
								<td colspan="2" align="center">អ្នកទទួល</td>
							</tr>
							<tr style="font-size: 15px;">
								<td colspan="2" align="center">&nbsp;</td>
							</tr>
							<tr style="font-size: 15px;">
								<td colspan="2" align="center"></td>
								<td colspan="2" align="center" valign="">
									<h4 style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer OS Battambang';margin-top: -7px;"> 
								        <?php 
										   $session_user=new Zend_Session_Namespace('authstu');
								           $last_name=$session_user->last_name;
								           $username = $session_user->first_name;
										   echo "".$last_name." ".$username;
										?>
										<p style="margin-top:-2px;font-size:11px;"><?php $today = date("F j, Y, g:i a");echo $today; ?></p>
					        		</h4>
					        	</td>
							</tr>
						</table>
					</td>
				</tr>
				
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<div>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				 type="button" onclick="printSubmit();"><?php echo $tr->translate("SAVE_PRINT");?></button>
		
	</div>
</div>
<script>


function submitDataClose(){
	
	if(dijit.byId('frm_teststudent').validate()) {
	
		dijit.byId('saveclose').set('disabled',true);
		
		var url_submit = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttest','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_teststudent"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";	
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/registrar/studenttest";
			},
			error: function(e) {
			}
		});
	}
}
function submitDataAddNew(){
	if(dijit.byId('frm_teststudent').validate()) {
		dijit.byId('savenew').set('disabled',true);
		
		var url_submit = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttest','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_teststudent"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";		
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/registrar/studenttest/add";
			},
			error: function(e) {
			}
		});
	}
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}



dojo.ready(function(){
	getReceiptNumber('');
});
var url_get_recceipt_number = "<?php echo $this->url(array('module'=>'registrar','controller'=>'income','action'=>'get-receipt-number')); ?>";
function getReceiptNumber(condition){
	dojo.xhrPost({
		url:url_get_recceipt_number,
		content:{
			//'branch_id':dijit.byId('branch_id').get('value')
			},
		handleAs:"json",
		load: function(data) {
			 dijit.byId('receipt').attr('value',data);
			 if(condition!=''){
				 printReceipt(data);
			 }
		},
		error: function(err) {
			alert(err);
		}
	});
}
function printReceipt(new_receipt){
	if(dijit.byId('frm_teststudent').validate()) {
		if(new_receipt==''){
			dojo.byId("lb_receipt").innerHTML = '';
			getReceiptNumber(1);
		}else{
			dojo.byId("lb_receipt").innerHTML = new_receipt;
		}
		dojo.byId("lb_studentkh").innerHTML = dijit.byId("kh_name").get('value');
		dojo.byId("lb_studenten").innerHTML = dijit.byId("en_name").get('value');
		dojo.byId("lb_serial").innerHTML = dijit.byId("serial").get('value');
		dojo.byId("lb_degree").innerHTML = dijit.byId("degree").attr('displayedValue');
		dojo.byId("lb_gender").innerHTML = dijit.byId("sex").attr('displayedValue');
		dojo.byId("lb_price").innerHTML = dijit.byId("test_cost").get('value');
		dojo.byId("lb_dob").innerHTML = dijit.byId("dob").get('value');
		dojo.byId("lb_address").innerHTML = dijit.byId("address").get('value');
		dojo.byId("lb_phone").innerHTML = dijit.byId("phone").get('value');
		dojo.byId("lb_note").innerHTML = dijit.byId("note").get('value');
		var d = dijit.byId("dob").get('value');
		 if(d!=null){
			 var day = d.getDate();
			 var mon = d.toDateString().substr(4,3);
			 var year = d.getFullYear();
			 dojo.byId("lb_dob").innerHTML  = day+'/'+mon+'/'+year;
		 }else{
			 dojo.byId("lb_dob").innerHTML  = '';
		}
		dijit.byId("terms").show();	
	}
}
function submitData(){
	if(dijit.byId('frm_teststudent').validate()) {
		dijit.byId('savenew').set('disabled',true);
		dijit.byId('frm_teststudent').submit();
	}
}
function printSubmit(){
	window.frames["print_frame"].document.body.innerHTML = dojo.byId('PrintReceipt').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //submitData();
}
function hideDialog(){
	dijit.byId('terms').hide();
}
 </script>
 
 
 <div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>
 
 
 
 
 
 
 