<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_TEST'));
	$frm =  $this->form_search;
?>
<script>
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttest','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
  				<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input type="text" name="txtsearch" id="txtsearch" dojoType="dijit.form.TextBox" value="<?php echo $this->adv_search['txtsearch']; ?>" placeholder="<?php echo $tr->translate('SEARCH');?>" class="fullside" />
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("degree");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("term_test");?>
                   </div>
                </div>
                <div class="form-group">
                	<div class="col-md-2 col-sm-2 col-xs-12">
                		<select name="result_status" id="result_status" class="fullside" dojoType="dijit.form.FilteringSelect" >
			   				<option value="" <?php if($this->adv_search['result_status']==""){echo "selected='selected'";}?>> Select result status </option>
			   				<option value="0" <?php if($this->adv_search['result_status']==0){echo "selected='selected'";}?>> Result not updated </option>
			   				<option value="1" <?php if($this->adv_search['result_status']==1){echo "selected='selected'";}?>> Result updated </option>
			   			</select>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                </div>
  			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
 
