<?php 
     $url_save = $this->url(array('module'=>'accounting','controller'=>'transfer','action'=>'edit'));
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $status_view=$this->status_view;
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
     $result = $this->rs;
?>
<style>
#table tr td{
	border:1px solid #cccccc;
	text-align: center;
}
#table tr th{
	background: #cccccc;
	border:1px solid #ddd;
}
.center{border:1px solid #000;}
</style>
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ItemFileWriteStore");  
</script>
<title><?php echo $this->tr->translate("PRODUCT_TRANSFER")?></title>
<form id="add_province" action="<?php echo $url_save;?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				ids = dijit.byId('identity').get('value');
                if(ids==''){
				alert("សូមជ្រើសរើសផលិតផលដើម្បី ផ្ទេរ");
				dijit.byId('pro_id').focus();
                return false;
				}
				from_location = dijit.byId('from_location').get('value');
				to_location = dijit.byId('to_location').get('value');
             if(to_location==from_location){
				alert("ទីតាំងដែលត្រូវផ្ទេរទៅមិនអាចដូចគ្នាបានទេ !");
				dijit.byId('to_location').focus();
                return false;
			}
				dijit.byId('save_new').set('disabled',true);
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="20" width="100%" style="margin: 0 auto;">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("PRODUCT_TRANSFER");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table style="margin: 0 auto; width:100%;" cellspacing="10">
									<tr>
										<td><?php echo $tr->translate("TRANSFER_NUMBER");?></td>
										<td><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="transfer_no" name="transfer_no" type="text" required="required" value="<?php echo $result['transfer_no'];?>" >
										<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="id" name="id" type="hidden" value="<?php echo $result['id'];?>" >
											<input dojoType="dijit.form.TextBox" class="fullside" id="old_flocation" name="old_flocation" type="hidden" value="<?php echo $result['from_location'];?>" >
											<input dojoType="dijit.form.TextBox" class="fullside" id="old_tlocation" name="old_tlocation" type="hidden" value="<?php echo $result['to_location'];?>" >
										</td>
										<td><?php echo $tr->translate("DATE");?></td>
										<td><input dojoType="dijit.form.DateTextBox" value="<?php echo date("Y-m-d");?>" constraints="{datePattern:'dd/MM/yyyy'}"  class="fullside" id="date" name="date" value="<?php echo date("Y-m-d",strtotime($result['transfer_date']));?>" type="text" required="required" ></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("FORM_LOCATION");?></td>
										<td>
											<select name="from_location" id="from_location" dojoType="dijit.form.FilteringSelect" required="true" missingMessage="Invalid Module!" class="fullside">
											   <?php 
											    print_r($this->rsbranch);
											    if(!empty($this->rsbranch)){
											    foreach($this->rsbranch as $rs){?>
											    	<option <?php if($result['from_location']==$rs['id']){echo "selected";}?> value="<?php echo $rs['id']?>"><?php echo $rs['name']?></option>
											    <?php }}?>
											</select>
										</td>
										<td><?php echo $tr->translate("TO_LOCATION");?></td>
										<td><select name="to_location" id="to_location" dojoType="dijit.form.FilteringSelect" required="true" missingMessage="Invalid Module!" class="fullside">
											    <?php 
											    if(!empty($this->rsbranch)){
											   	 foreach($this->rsbranch as $rs){?>
											    	<option <?php if($result['to_location']==$rs['id']){echo "selected";}?> value="<?php echo $rs['id']?>"><?php echo $rs['name']?></option>
											    <?php }}?>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("REMARK");?></td>
										<td><input dojoType="dijit.form.TextBox" class="fullside" id="remark" name="remark" value="<?php echo $result['note'];?>" type="text"  ></td>
										<td><?php echo $tr->translate("STATUS");?></td>
										<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true" missingMessage="Invalid Module!" class="fullside">
										       <option value="1" <?php if($result['status']==1){echo "selected";}?> ><?php echo $tr->translate("ACTIVE");?></option>
										       <option value="0" <?php if($result['status']==0){echo "selected";}?> ><?php echo $tr->translate("DEACTIVE");?></option>
											</select>
										</td>
									</tr>
									<tr>
									    <td><?php echo $tr->translate("CHOOSE_PRODUCT");?></td>
									    <td colspan="3">
										    <div style="background: #04a2e0;padding: 1px;">
												<select onchange="getProductName();" style="height:35px;" name="pro_id" id="pro_id" dojoType="dijit.form.FilteringSelect" required="true" missingMessage="Invalid Module!" class="fullside">
													<option></option>
													<?php 
												    if(!empty($this->rsproduct)){
												   	 foreach($this->rsproduct as $rs){?>
												    	<option value="<?php echo $rs['id']?>"><?php echo $rs['name']?></option>
												    <?php }}
												  ?>
											</select>
											</div>	
										</td>
									</tr>
									<tr>
									    <td colspan="4">
											<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
												<tr id="head-title" class="head-td" align="right"></tr>
											</table>
											<input type="hidden" dojoType="dijit.form.TextBox" id="identity" name="identity" />
										</td>
									</tr>
									<tr>
										<td colspan="4" align="center">
											<input type="reset" value="Clear" label="<?php echo $tr->translate("CLEAR");?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
											<input type="submit" value="save_new" id="save_new" name="save_close" label="<?php echo $tr->translate("SAVE_NEW");?>" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
	</table>	
</form> 
<script>
dojo.ready(function(){
	initailize();
});
function initailize(){
	<?php if(!empty($this->rsdetail)){
		foreach($this->rsdetail as $row){
	?>
	index++;
	template='';
	if(index==1){
		temp='';
		temp+='<td>NO</td>';
		temp+='<td>ឈ្មោះផលិតផល</td>';
		temp+='<td>QTY_TRANSFER</td>';
		temp+='<td>ផ្សេងៗ</td>';
		temp+='<td>លុប</td>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
	pro_name='';
	template='<td width="2%" align="center">'+index+'</td>';
	template+='<td ><?php echo $row['pro_name'];?><input dojoType="dijit.form.TextBox" type="hidden"  id="pro_id_'+index+'" name="pro_id_'+index+'" ></td>';
	template+='<td ><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" required="1" id="qty_'+index+'" name="qty_'+index+'" ></td>';
	template+='<td ><input dojoType="dijit.form.TextBox" class="fullside" type="text" id="remark_'+index+'" name="remark_'+index+'" ></td>';
	template+='<td align="center"><img onClick="deleteRecord('+index+');" src="<?php echo BASE_URL; ?>/images/Delete_16.png" /></td>';
	
	tmp='<tr id="row'+index+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+index);
	} else {$("#identity").val(index);}
	dojo.html.set(dojo.byId("row"+index),template , {
	     parseContent: true,
	});
	dijit.byId('qty_'+index).attr('value',<?php echo $row['qty']?>);
	dijit.byId('remark_'+index).attr('value','<?php echo $row['note']?>');
	dijit.byId('pro_id_'+index).attr('value',<?php echo $row['pro_id']?>);
	
	<?php } }?>
}
<?php $url_product =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'get-product-name')); ?>
index=0;
function getProductName() {
	index++;
			if(index==1){
				temp='';
				temp+='<td >NO</td>';
				temp+='<td >ឈ្មោះផលិតផល</td>';
				temp+='<td >QTY_TRANSFER</td>';
				temp+='<td >ផ្សេងៗ</td>';
				temp+='<td >លុប</td>';
				dojo.query("#head-title").append(temp);
			}
            pro_id=dijit.byId("pro_id").get("value");
            pro_name = dijit.byId("pro_id").attr('displayedValue')
			var inp = '';
			template='<td width="2%" align="center">'+index+'</td>';
			template+='<td >'+pro_name+'<input dojoType="dijit.form.TextBox" type="hidden"  id="pro_id_'+index+'" name="pro_id_'+index+'" ></td>';
			template+='<td ><input dojoType="dijit.form.NumberTextBox" class="fullside" type="text" required="1" id="qty_'+index+'" name="qty_'+index+'" ></td>';
			template+='<td ><input dojoType="dijit.form.TextBox" class="fullside" type="text" id="remark_'+index+'" name="remark_'+index+'" ></td>';
			template+='<td align="center"><img onClick="deleteRecord('+index+');" src="<?php echo BASE_URL; ?>/images/Delete_16.png" /></td>';
		tmp='<tr id="row'+index+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		dojo.html.set(dojo.byId("row"+index),template , {
		     parseContent: true,
		});
		dijit.byId("pro_id_"+index).attr("value",pro_id);
		if($('#identity').val()!="") {
			var identity = $('#identity').val();
			$('#identity').val(identity+','+index);
		} else {$('#identity').val(index);}
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
</script>