<?php
$this->headTitle('SRMS | User add page'); 
echo $this->headTitle();
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>

<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.FilteringSelect');
</script>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
             <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-user-plus " aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('ព៌ត័មាន ទំនាក់ទំនង របស់​ អ្នក​ប្រើប្រាស់');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form action="<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">				
				if(this.validate()) {
					if(dojo.byId('password').value != dojo.byId('con_password').value ){
						alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
						dojo.byId('password').value = '';
						dojo.byId('con_password').value = '';
						dijit.byId('password').focus();
						return false;
					}				
					dojo.byId('agent').value = dijit.byId('agent_id').item.id;
					return true;
				}
				return false;
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
	        		<div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FIRST_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" required="true" name="first_name" id="first_name" placeholder="<?php echo $tr->translate("FIRST_NAME");?>" 
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ នាមខ្លួន!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LAST_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" required="true" name="last_name" id="last_name" placeholder="<?php echo $tr->translate("LAST_NAME");?>" 
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ នាម​ត្រកូល!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("USER_NAME");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" required="true" name="user_name" id="user_name" placeholder="<?php echo $tr->translate("USER_NAME");?>" 
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ប្រើ​ប្រាស់!" class='fullside'/>
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PASSWORD");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="password" required="true" name="password" id="password" placeholder="<?php echo $tr->translate("PASSWORD");?>" 
											regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពាក្យ​​សំងាត់!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CONFIRM_PASSWORD");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="password" required="true" name="con_password" id="con_password" placeholder="<?php echo $tr->translate("CONFIRM_PASSWORD");?>" 
											regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox"  missingMessage="អ្នក​ភ្លេច​បំពេញ​ បញ្ជាក់ ពាក្យ​​សំងាត់!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select name="branch_id" class='fullside' required="true" id="branch_id" 
								 missingMessage="អ្នក​ភ្លេច​បំពេញ​  សាខា" dojoType="dijit.form.FilteringSelect"> 
									<?php foreach ($this->rs_branch as $key => $rs) : ?>
										<option value="<?php echo $rs["br_id"];?>"><?php echo $rs['branch_namekh'];?></option>
									<?php endforeach;?>																					
								</select> 
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("USER_TYPE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input id="user_type" />
	                   </div>
	                </div>
	                <div class="clearfix"></div>
				    <div class="card-box">
		               	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
	               		<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
						iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>"user",'action'=>'index'),null,true); ?>';" />
						<input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
			    		</div>
			    	</div>
	             </div>
	         </div>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;overflow-y:scroll;" id="popup_usertype" >
		<form  id='frm_usertype' name='frm_usertype' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="15">
				<tr>
					<td><?php echo $tr->translate("USER_TYPE");?></td>
					<td width="300px">
						<input type="text" required="true" name="user_typename" id="user_typename" placeholder="User Type" 
						dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->usertype['user_type'];?>"
						missingMessage="Invalid User type!" class='fullside'/>
					</td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("PARENT");?></td>
					<td>
						<select class='fullside' id="parent_id"  name="parent_id" required="true" 
						 missingMessage="Invalid Parent Name!" dojoType="dijit.form.FilteringSelect"> 
						 	<?php foreach ($this->user_typelist as $key => $ust) : ?>
								<option value="<?php echo $ust['id'];?>"><?php echo $ust['name'];?></option>
							<?php endforeach;?>																															
						</select> 
					</td>
				</tr>	
				<tr>
					<td colspan="2" align="center">
						<input type="button" onclick="addUsrType();" value="រក្សាទុក" label="រក្សាទុក" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
					</td>
				</tr>								
			</table>
		</form>
	</div>
</div>	
<script>
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  

var usertype_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->user_type));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: usertype_store,
		autoComplete: true,                        
		id: "user_type",
		name: "user_type",
		class: "fullside", 		
		placeHolder:"Select User Type",          
		onChange: function() {  
			user_type = dijit.byId('user_type').get('value');
			if(user_type==-1){
				dijit.byId("popup_usertype").show();
			}
		}
	}, "user_type");
});

function getpopupUsertype(){
	user_type = dijit.byId("user_type").get("value");
	if(user_type==-1){
		dijit.byId("popup_usertype").show();
	}
}
var url_addusertype = '<?php echo $this->url(array("module"=>"rsvacl","controller"=>"usertype","action"=>"addusertype")); ?>';
function addUsrType(){
	if(dijit.byId('frm_usertype').validate()){
		dojo.xhrPost({
			url:url_addusertype,
			form: dojo.byId("frm_usertype"),
			handleAs:"json",
			load: function(data) {
				var myNewItem = {					
						id: data,
						name: dijit.byId('user_typename').get('value')
				};			
				addDataToSelectbox(dijit.byId('user_type'), usertype_store, myNewItem, data);
				dijit.byId("frm_usertype").reset();
				dijit.byId("popup_usertype").hide();
				
			},
			error: function(err) {
				alert(err);
			}
		});
   }
}
</script>