<?php
$this->headTitle('SRMS | User edit page'); 
echo $this->headTitle();
$tr = Application_Form_FrmLanguages::getCurrentlanguage();

$session_user=new Zend_Session_Namespace(SYSTEM_SES);
$user_id = $session_user->user_id;
$branch_id = $session_user->branch_id;

$category='';
if(!empty($this->user_edit['branch_list'])){
	$category =  explode(",",$this->user_edit['branch_list']);
}
$array = array();
if (!empty($category)) {
	foreach ($category as $ss) {
		$array[$ss] = $ss;
	}
}
?>
<style>
ul.optListRow {
    list-style-type: none;
    margin: 0;
    padding: 0;
    padding-left: 35px;
}
 input[type=checkbox],  input[type=radio]{
	height: 15px;
    display: initial;
}
</style>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
             <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;<?php echo $tr->translate('EDIT_INFORMATION_RELETIONSHIP_USER');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id="frmUser" action="<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">										
				if(this.validate()) {
					var identity = [];
	    			 $('.checkbox:checked').each(function(i){
	    				 identity[i] = $(this).val();
	     			});
					if(identity==""){
						alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>");
						return false;
					}

					var schoptcheckIde = [];
	    			 $('.schoptcheck:checked').each(function(i){
	    				 schoptcheckIde[i] = $(this).val();
	     			});
					if(schoptcheckIde==""){
						alert("<?php echo $tr->translate("PLEASE_CHECK_SCHOOLOPTION");?>");
						return false;
					}

					if(dojo.byId('password').value != dojo.byId('con_password').value ){
						alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
						dojo.byId('password').value = '';
						dojo.byId('con_password').value = '';
						dijit.byId('password').focus();
						return false;
					}		
					loadingBlock();		
					return true;
				}
				return false;
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
	        		<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-log-in" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("ACCOUNT_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("USER_NAME");?> <span class="required">*</span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" required="true" name="user_name" id="user_name" placeholder="<?php echo $tr->translate("USER_NAME");?>" 
															dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->user_edit['user_name'];?>" 
														 class='fullside'/>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" >
											<div class="custom-control custom-checkbox ">
												<input type="checkbox" class=" custom-control-input"  id="check_change" name="check_change" onChange="Checkchange();"  >
												<label class="custom-control-label custom-right-side" for="check_change">
													<?php echo $tr->translate('PASSWORD');?>
												</label>
											</div>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input type="password" required="true" name="password" id="password" placeholder="<?php echo $tr->translate("PASSWORD");?>" 
															regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
															dojoType="dijit.form.ValidationTextBox" class='fullside'/>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CONFIRM_PASSWORD");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input type="password" required="true" name="con_password" id="con_password" placeholder="<?php echo $tr->translate("CONFIRM_PASSWORD");?>" 
															regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
															dojoType="dijit.form.ValidationTextBox"  class='fullside'/>
									   </div>
									</div>
									<div class="form-group">
										<label class="control-label custom-switch float-end "> 
											<a href="javascript:void(0);" class="switchButton status"><?php echo $tr->translate("STATUS");?></a> 
											<input type="checkbox" id="active" name="active" class="custom-switch-input"  <?php if(!empty($this->user_edit['active'])){ echo "checked";} ?> > 
											<span class="custom-switch-indicator custom-radius switch-status"></span> 
										</label>
									</div>
								</div>
							</div>
						</div>
					</div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
	             	<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-user" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("USER_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("LAST_NAME");?> <span class="required">*</span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" required="true" name="last_name" id="last_name" placeholder="<?php echo $tr->translate("LAST_NAME");?>" 
															dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->user_edit['last_name'];?>"
															class='fullside'/>
									   </div>
									</div>
									
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FIRST_NAME");?> <span class="required">*</span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" required="true" name="first_name" id="first_name" placeholder="<?php echo $tr->translate("FIRST_NAME");?>" 
															dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->user_edit['first_name'];?>"
															 class='fullside'/>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("USER_TYPE");?> <span class="required">*</span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="user_type" />
									   </div>
									</div>
									<!-- 
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php //echo $tr->translate("BRANCH");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<select name="branch_id" <?php //if ($branch_id!=1){ echo 'readonly="readonly"';}?> class='fullside' required="true" id="branch_id" 
											 missingMessage="អ្នក​ភ្លេច​បំពេញ​  សាខា" dojoType="dijit.form.FilteringSelect"> 
												<?php //foreach ($this->rs_branch as $key => $rs) : ?>
													<option value="<?php //echo $rs["id"];?>" <?php //if($this->user_edit['branch_id']==$rs["id"]) echo 'selected'?> ><?php //echo $rs['name'];?></option>
												<?php //endforeach;?>																					
											</select> 
									   </div>
									</div>
									 -->
					 
								</div>
							</div>
						</div>
					</div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-indent-left" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("School Option");?></p>
										</div> 
									</div>
									<br />
									<div class="form-group">
										<ul class="optListRow" id="lbl_checkoption">
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-indent-left" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("Assign Branch Access");?></p>
										</div> 
									</div>
									<br />
									<div class="custom-control custom-checkbox ">
										<input type="checkbox" class="checkbox custom-control-input" checked="checked"  name="check_all" id="check_all" value="all" OnChange="CheckAllTotal(0);"  >
										<label class="custom-control-label" for="check_all">
											<?php echo $tr->translate('CHECK_ALL');?>
										</label>
									</div>
									<div class="form-group">
										<ul class="optListRow">
											<?php $identityCheck = ""; if (!empty($this->rs_branch)) foreach ($this->rs_branch as $rs){?>
											<li class="opt-items"> 
												<div class="custom-control custom-checkbox">
													<input type="checkbox" class="checkbox custom-control-input" <?php if (in_array($rs['id'], $array)) { echo 'checked="checked"';}?> id="branch<?php echo $rs['id'];?>" value="<?php echo $rs['id'];?>" name="selector[]" onClick="CheckAllTotal(1);" >
													<label class="custom-control-label" for="branch<?php echo $rs['id'];?>">
														<?php echo $rs['name'];?>
													</label>
												</div>
											</li>
												<?php if (empty($identityCheck)){ $identityCheck = $rs['id'];}else{$identityCheck = $identityCheck.",".$rs['id'];}?>
											<?php }?>
										</ul>
										<input type="hidden" id="identityCheck" name="identityCheck" value="<?php echo $identityCheck;?>" />
									</div>
								</div>
							</div>
						</div>
					</div>
	            
	             </div>
	         </div>
	         <div class="clearfix"></div>
			    <div class="card-box">
	               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
	               		<input type="hidden" name="id" value="<?php echo $this->user_edit['id'];?>" />
						<input type="button" class="button-class button-danger"  iconClass="glyphicon glyphicon-repeat" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button"  onclick="window.location = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>"user",'action'=>'index'),null,true); ?>';" />
						<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="Save" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button"  /> 
			    		
		    		</div>
		    	</div>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:500px;overflow-y:scroll;" id="popup_usertype" >
		<form  id='frm_usertype' name='frm_usertype' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="15">
				<tr>
					<td><?php echo $tr->translate("USER_TYPE");?></td>
					<td width="300px">
						<input type="text" required="true" name="user_typename" id="user_typename" placeholder="User Type" 
						dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->usertype['user_type'];?>"
						missingMessage="Invalid User type!" class='fullside'/>
					</td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("PARENT");?></td>
					<td>
						<select class='fullside' id="parent_id"  name="parent_id" required="true" 
						 missingMessage="Invalid Parent Name!" dojoType="dijit.form.FilteringSelect"> 
						 	<?php foreach ($this->user_typelist as $key => $ust) : ?>
								<option value="<?php echo $ust['id'];?>"><?php echo $ust['name'];?></option>
							<?php endforeach;?>																															
						</select> 
					</td>
				</tr>	
				<tr>
					<td colspan="2" align="center">
						<input type="button" onclick="addUsrType();" value="រក្សាទុក" label="រក្សាទុក" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
					</td>
				</tr>								
			</table>
		</form>
	</div>
</div>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">	
	dojo.require("dijit.form.CheckBox");

	dojo.require("dijit.form.ValidationTextBox");
	//dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");

var usertype_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->user_type));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: usertype_store,
		queryExpr: "*${0}*",
		autoComplete: false,                       
		id: "user_type",
		name: "user_type",
		class: "fullside", 	
		value:'<?php echo $this->user_edit['user_type'];?>',
		placeHolder:"Select User Type",          
		onChange: function() {  
			user_type = dijit.byId('user_type').get('value');
			if(user_type==-1){
				dijit.byId("popup_usertype").show();
			}
		}
	}, "user_type");

	getSchoolOption();
});

function getpopupUsertype(){
	user_type = dijit.byId("user_type").get("value");
	if(user_type==-1){
		dijit.byId("popup_usertype").show();
	}
}
var url_addusertype = '<?php echo $this->url(array("module"=>"rsvacl","controller"=>"usertype","action"=>"addusertype")); ?>';
function addUsrType(){
	if(dijit.byId('frm_usertype').validate()){
		dojo.xhrPost({
			url:url_addusertype,
			form: dojo.byId("frm_usertype"),
			handleAs:"json",
			load: function(data) {
				var myNewItem = {					
						id: data,
						name: dijit.byId('user_typename').get('value')
				};			
				addDataToSelectbox(dijit.byId('user_type'), usertype_store, myNewItem, data);
				dijit.byId("frm_usertype").reset();
				dijit.byId("popup_usertype").hide();
				
			},
			error: function(err) {
				alert(err);
			}
		});
   }
}
dojo.ready(function(){
	try{
		Checkchange();
	}catch(e){
		alert(e);
	}
	$(window).keydown(function(event){
		if(event.keyCode == 13) {
		  event.preventDefault();
		  return false;
		}
	  });
});

function Checkchange(){
	  if (dojo.byId("check_change").checked){
		  dijit.byId('password').set('required',true); 
		  dijit.byId('password').set('readOnly',false); 
		  dijit.byId('con_password').set('required',true); 
		  dijit.byId('con_password').set('readOnly',false); 
		 
	  }else{
		  $('#password').val('');
		  dijit.byId('password').set('required',false); 
		  dijit.byId('password').set('readOnly',true); 
		  dijit.byId('con_password').set('required',false); 
		  dijit.byId('con_password').set('readOnly',true); 
	  }
}
var oldschoolOption = '<?php echo $this->user_edit['schoolOption'];?>';
var url_getoptionSchool = '<?php echo $this->url(array("module"=>"rsvacl","controller"=>"user","action"=>"getschooloptionbybranchlist")); ?>';
function getSchoolOption(){
	dojo.query("#lbl_checkoption").append('');
	dojo.xhrPost({
		url:url_getoptionSchool,
		form: dojo.byId("frmUser"),
		handleAs:"json",
		load: function(data) {
			temp='';
			for(var i=0;i<data.length;i++) {
				
				var checkedlabel="";	
					if(oldschoolOption!=''){ 
						var rowIDArray = oldschoolOption.split(',');
						for(var n = 0; n < rowIDArray.length; n++){
							if(data[i].id==rowIDArray[n]){
								checkedlabel="checked";	
								break;
							}
						}
					}
					temp+='<li class="opt-items">';
					
								temp+='<div class="custom-control custom-checkbox">';
										temp+='<input type="checkbox" '+checkedlabel+' class="schoptcheck custom-control-input" id="schoolOption'+data[i].id+'" checked type="checkbox" value="'+data[i].id+'" name="schooloptoncheck[]" id="schooloptoncheck[]" >';
										temp+='<label class="custom-control-label" for="schoolOption'+data[i].id+'">';
											temp+=data[i].name;
										temp+='</label>';
									temp+='</div>';
						
						temp+='</li>';
						
			}
				dojo.query("#lbl_checkoption").append(temp);
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
function CheckAllTotal(index){
	if(index==0){
			if($('#check_all').is(":checked")){
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = true;  
				});
			}else{
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = false;  
				});
			}
	}else{
		var a = $("input:checked").val();
		 var identity = [];
	     $('.checkbox:checked').each(function(i){
	    	 identity[i] = $(this).val();
	     });
	     var allidentity = $("#identityCheck").val();
		if(identity == allidentity ){
			$('#check_all').prop('checked', true); // checks it
		}else{
			$('#check_all').prop('checked', false); // Unchecks it
		}
	}
	getSchoolOption();
}
</script>