<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
	echo $this->headTitle($tr->translate('REQUEST_STOCK'));
	$frm = $this->form_search;
?>
<meta charset="utf-8">
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-cubes " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REQUEST_STOCK');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form action="<?php echo $this->url(array('module'=>'stock','controller'=>'requestproduct','action'=>'index')); ?>"
				dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("title");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_id");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<select name="request_for" id="request_for" dojoType="dijit.form.FilteringSelect" class="fullside" >
							<option value="-1"><?php echo $tr->translate('SELECT_REQUEST_FOR')?></option>
							<?php if(!empty($this->rq_for)){foreach($this->rq_for as $req_for){?>
								<option value="<?php echo $req_for['id']?>" <?php if($req_for['id']==$this->search['request_for']){echo "selected='selected'";}?> ><?php echo $req_for['name']?></option>
							<?php }}?>
						</select>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<select name="for_section" id="for_section" dojoType="dijit.form.FilteringSelect" class="fullside" >
							<option value="-1"><?php echo $tr->translate('SELECT_REQUEST_FOR_DEPT')?></option>
							<?php if(!empty($this->for_section)){foreach($this->for_section as $for_sec){?>
								<option value="<?php echo $for_sec['id']?>" <?php if($for_sec['id']==$this->search['for_section']){echo "selected='selected'";}?> ><?php echo $for_sec['name']?></option>
							<?php }}?>
						</select>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("status_search");?>
                   </div>
                </div>
                <div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"
							showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box">
			<?php  echo $this->list;?>
		</div>
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>