<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_expense;
?>
<title>Add Other Expense</title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
 </script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'expense','action'=>'add')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
				<fieldset>
					<legend><strong>ចំណាយ</strong></legend>
					<table cellspacing="10"  width="100%">
						<tr>
						    <td><?php echo $tr->translate("BRANCH_NAME")?></td>
							<td><?php echo $frm->getElement('branch_id');?></td>
							<td><?php echo $tr->translate("EXPENSE_TITLE")?></td>
							<td><?php echo $frm->getElement('title');?></td>
							<td><?php echo $tr->translate("CURRENCY")?></td>
							<td><?php echo $frm->getElement('currency_type');//echo $frm->getElement('for_date');?></td>
						</tr>
						<tr>
						   <td><?php echo $tr->translate("RECEIPT_NO")?></td>
							<td><?php echo $frm->getElement('invoice');?></td>
							<td><?php echo $tr->translate("TOTAL_EXPENSE")?></td>
							<td><?php echo $frm->getElement('total_amount');?></td>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $frm->getElement('Description');?></td>
						</tr>
						<tr>
							
						    <td><?php echo $tr->translate("CREATED_DATE")?></td>
							<td><?php echo $frm->getElement('Date');?></td>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><?php echo $frm->getElement('Stutas');?></td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>		
	<tr>
		<td align="center">
		<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
				 iconClass="dijitIconClear"/>
			<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' value='saveclose' dojoType="dijit.form.Button"
				 iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button"
				 iconClass="dijitIconNewTask"/>
		</td>
	</tr>	
</table>
</form>

<script type="text/javascript">

dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.store.Memory");
dojo.require("dijit.form.Textarea");

dojo.ready(function(){
	getReceiptNumber();
});

var url_get_recceipt_number = "<?php echo $this->url(array('module'=>'registrar','controller'=>'expense','action'=>'get-receipt-number')); ?>";
	function getReceiptNumber(){
		dojo.xhrPost({
			url:url_get_recceipt_number,
			content:{
				'branch_id':dijit.byId('branch_id').get('value')
				},
			handleAs:"json",
			load: function(data) {
				 dijit.byId('invoice').attr('value',data);
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	
</script>




