<?php 
$this->headTitle('SRMS | Cash Out');
echo $this->headTitle();
?>
<?php 
	$frm_cal = $this->frm_cal;
	define("CENTER","center");
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<script type="text/javascript">
	dojo.require("dijit.Dialog");
</script>
<form id="cash_count" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded" >
<table cellspacing="20" width="100%" >
	<tr>
		<td width="48%">
			<fieldset>
				<legend align="center"><?php echo $tr->translate("USD");?></legend>
				<table style="margin: 0 auto; width: 90%;" cellspacing="10">
					<tr height="30px">
						<td>$ 100</td>
						<td>x</td>
						<td align="<?php echo CENTER;?>" width="40%"><?php echo $frm_cal->getElement("d_hundred");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>" width="40%"><?php echo $frm_cal->getElement("rs_hundred");?></td>
					</tr>
					<tr>
						<td>$ 50</td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("d_fifty");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_fifty");?></td>
					</tr>
					<tr>
						<td>$ 20</td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("d_tweenty");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_tweenty");?></td>
					</tr>
					<tr>
						<td>$ 10 </td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("d_ten");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_ten");?></td>
					</tr>
					<tr>
						<td>$ 5</td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("d_five");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_five");?></td>
					</tr>
					<tr>
						<td>$ 1</td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("d_one");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_one");?></td>
					</tr>
					<tr>
						<td colspan="3" align="<?php echo CENTER;?>"><?php echo $tr->translate("ALL_TOTAL_DOLLAR");?></td>
						<td>$</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_dollar_total");?></td>
					</tr>
					<tr>
						<td colspan="3" align="<?php echo CENTER;?>"><?php echo $tr->translate("ALL_TOTAL_REIL");?></td>
						<td>$</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("total_reil_dollar");?></td>
					</tr>
					<tr>
						<td colspan="3" align="<?php echo CENTER;?>"><?php echo $tr->translate("ALL_TOTAL_REIL");?></td>
						<td>$</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("total_amount");?></td>
				</table>
			</fieldset>
			</td>
			<td width="48%">
			<fieldset>
				<legend align="center"><?php echo $tr->translate("RIEL");?></legend>
				<table style="margin: 0 auto; width: 90%;" cellspacing="10">
					<tr>
						<td>R 50,000 </td>
						<td>x</td>
						<td align="<?php echo CENTER;?>" width="40%"><?php echo $frm_cal->getElement("r_fiftyhousend");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>" width="40%"><?php echo $frm_cal->getElement("rs_fiftyhousend");?></td>
					</tr>
					<tr>
						<td>R 10,000</td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("r_tenthousend");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_tenthousend");?></td>
					</tr>
					<tr>
						<td>R 5,000 </td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("r_fivehousend");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_fivehousend");?></td>
					</tr>
					<tr>
						<td>R 2,000</td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("r_tweentyhousend");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_tweentyhousend");?></td>
					</tr>
					<tr>
						<td>R 1,000 </td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("thousend");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_thousend");?></td>
					</tr>
					<tr>
						<td>R 500 </td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("r_fivehundred");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_fivehundred");?></td>
					</tr>
					<tr>
						<td>R 100 </td>
						<td>x</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("r_onehundred");?></td>
						<td>=</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_onehundred");?></td>
					</tr>
					<tr>
						<td colspan="3" align="<?php echo CENTER;?>"><?php echo $tr->translate("ALL_TOTAL_REIL");?></td>
						<td>R</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rs_kh_total");?></td>
					</tr>
					<tr>
						<td colspan="3" align="<?php echo CENTER;?>"><?php echo $tr->translate("Convert to dollars");?></td>
						<td>R</td>
						<td align="<?php echo CENTER;?>"><?php echo $frm_cal->getElement("rate");?></td>
					</tr>
				</table>
			</fieldset>
		</td>
	</tr>
</table>
</form>
<table width="100%">
	<tr align="center">
		<td>
			<input type="button" value="Save & Print" label="Save & Print" id="busyButton" dojoType="dijit.form.Button" 
			iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printCashCount();"/>
		</td>
	</tr>
</table>
<script>
function Calcuhundred(){
	d_hundred=dijit.byId('d_hundred').get('value');
	//alert(d_hundred);
	rs_hundred=d_hundred*100;
	dojo.byId("rs_hundred").value = dojo.number.format(rs_hundred);
	//subTotalDollar();
	dojo.connect("onkeyup", function(evt){
		subTotalDollar();
    });	
}
function Calfifty(){
	d_fifty=dijit.byId('d_fifty').get('value')
	rs_fifty=d_fifty*50;
	dojo.byId("rs_fifty").value = dojo.number.format(rs_fifty);
	subTotalDollar();	
}
function Caltweenty(){
	d_tweenty=dijit.byId('d_tweenty').get('value')
	rs_tweenty=d_tweenty*20;
	dojo.byId("rs_tweenty").value = dojo.number.format(rs_tweenty);	
	subTotalDollar();
}
function Calten(){
	d_ten=dijit.byId('d_ten').get('value')
	rs_ten=d_ten*10;
	dojo.byId("rs_ten").value = dojo.number.format(rs_ten);	
	subTotalDollar();
}
function Calfive(){
	d_five=dijit.byId('d_five').get('value')
	rs_five=d_five*5;
	dojo.byId("rs_five").value = dojo.number.format(rs_five);
	subTotalDollar();
}
function Calone(){
	d_one=dijit.byId('d_one').get('value')
	rs_one=d_one*1;
	dojo.byId("rs_one").value = dojo.number.format(rs_one);
	subTotalDollar();
}
function subTotalDollar(){
	rs_hundred=parseFloat(dijit.byId('rs_hundred').get('value'));
	rs_fifty=parseFloat(dijit.byId('rs_fifty').get('value'));
	rs_tweenty=parseFloat(dijit.byId('rs_tweenty').get('value'));
	rs_ten=parseFloat(dijit.byId('rs_ten').get('value'));
	rs_five=parseFloat(dijit.byId('rs_five').get('value'));
	rs_one=parseFloat(dijit.byId('rs_one').get('value'));
	if(isNaN(rs_hundred)){
		rs_hundred=0;
	}
	if(isNaN(rs_fifty)){
		rs_fifty=0;
	}
	if(isNaN(rs_tweenty)){
		rs_tweenty=0;
	}
	if(isNaN(rs_ten)){
		rs_ten=0;
	}
	if(isNaN(rs_five)){
		rs_five=0;
	}
	if(isNaN(rs_one)){
		rs_one=0;
	}
	sub_totaldollar=rs_hundred+rs_fifty+rs_tweenty+rs_ten+rs_five+rs_one;
	dojo.byId("rs_dollar_total").value = dojo.number.format(sub_totaldollar);
	AllAmountTotal();
}
///calculator kh
function Calfiftyhousend(){
	r_fiftyhousend=dijit.byId('r_fiftyhousend').get('value')
	r_fiftyhousend=r_fiftyhousend*50000;
	dojo.byId("rs_fiftyhousend").value = dojo.number.format(r_fiftyhousend);
	subTotalkh();
}
function Caltenthousend(){
	r_tenthousend=dijit.byId('r_tenthousend').get('value')
	r_tenthousend=r_tenthousend*10000;
	dojo.byId("rs_tenthousend").value = dojo.number.format(r_tenthousend);
	subTotalkh();	
}
function Calfivehousend(){
	r_fivehousend=dijit.byId('r_fivehousend').get('value')
	rs_tweenty=r_fivehousend*5000;
	dojo.byId("rs_fivehousend").value = dojo.number.format(rs_tweenty);	
	subTotalkh();
}
function Caltweentyhousend(){
	r_tweentyhousend=dijit.byId('r_tweentyhousend').get('value')
	r_tweentyhousend=r_tweentyhousend*2000;
	dojo.byId("rs_tweentyhousend").value = dojo.number.format(r_tweentyhousend);	
	subTotalkh();
}
function Calthousend(){
	thousend=dijit.byId('thousend').get('value')
	thousend=thousend*1000;
	dojo.byId("rs_thousend").value = dojo.number.format(thousend);	
	subTotalkh();
}
function Calfivehundred(){
	r_fivehundred=dijit.byId('r_fivehundred').get('value')
	r_fivehundred=r_fivehundred*500;
	dojo.byId("rs_fivehundred").value = dojo.number.format(r_fivehundred);	
	subTotalkh();
}
function Calonehundred(){
	r_onehundred=dijit.byId('r_onehundred').get('value')
	r_onehundred=r_onehundred*100;
	dojo.byId("rs_onehundred").value = dojo.number.format(r_onehundred);	
	subTotalkh();
}
function subTotalkh(){
	rs_fiftyhousend=parseFloat(dijit.byId('rs_fiftyhousend').get('value'));
	rs_tenthousend=parseFloat(dijit.byId('rs_tenthousend').get('value'));
	rs_fivehousend=parseFloat(dijit.byId('rs_fivehousend').get('value'));
	rs_tweentyhousend=parseFloat(dijit.byId('rs_tweentyhousend').get('value'));
	rs_thousend=parseFloat(dijit.byId('rs_thousend').get('value'));
	rs_fivehundred=parseFloat(dijit.byId('rs_fivehundred').get('value'));
	rs_onehundred=parseFloat(dijit.byId('rs_onehundred').get('value'));
	if(isNaN(rs_fiftyhousend)){
		rs_fiftyhousend=0;
	}
	if(isNaN(rs_tenthousend)){
		rs_tenthousend=0;
	}
	if(isNaN(rs_fivehousend)){
		rs_fivehousend=0;
	}
	if(isNaN(rs_tweentyhousend)){
		rs_tweentyhousend=0;
	}
	if(isNaN(rs_thousend)){
		rs_thousend=0;
	}
	if(isNaN(rs_fivehundred)){
		rs_fivehundred=0;
	}
	if(isNaN(rs_onehundred)){
		rs_onehundred=0;
	}
	sub_totalkh=rs_fiftyhousend+rs_tenthousend+rs_fivehousend+rs_tweentyhousend+rs_thousend+rs_fivehundred+rs_onehundred;
	dojo.byId("rs_kh_total").value = dojo.number.format(sub_totalkh);	
	//rs_kh_total=parseFloat(dijit.byId('rs_kh_total').get('value'));
	rate=parseFloat(dijit.byId('rate').get('value'));
	covertfromreil = sub_totalkh/rate;
	dojo.byId("total_reil_dollar").value = dojo.number.format(covertfromreil);
	AllAmountTotal();
	
}
function AllAmountTotal(){
	rs_total_dollar=parseFloat(dijit.byId('rs_dollar_total').get('value'));
	rs_total_reil=parseFloat(dijit.byId('total_reil_dollar').get('value'));
	if(isNaN(rs_total_dollar)){
		rs_total_dollar=0;
	}
	if(isNaN(rs_total_reil)){
		rs_total_reil=0;
	}
	total_amount = rs_total_dollar+rs_total_reil;
	//total_amount = total_amount.
	dojo.byId("total_amount").value = dojo.number.format(total_amount);
}
function printCashCount(){		
	if(dijit.byId('cash_count').validate()) {
		//100$
		d_hundred=dijit.byId('d_hundred').get('value').toFixed(2);
		rs_hundred=dijit.byId('rs_hundred').get('value').toFixed(2);
	    dojo.byId("lb_hundred").innerHTML =isNaN(d_hundred)?0:d_hundred;
		dojo.byId("rd_hundred").innerHTML =isNaN(rs_hundred)?0:rs_hundred;
        //50$
		d_fifty=dijit.byId('d_fifty').get('value').toFixed(2);
		rs_fifty=dijit.byId('rs_fifty').get('value').toFixed(2);
		dojo.byId("lb_fifty").innerHTML =isNaN(d_fifty)?0:d_fifty;
		dojo.byId("rd_fifty").innerHTML =isNaN(rs_fifty)?0:rs_fifty;
        //20$
		d_tweenty=dijit.byId('d_tweenty').get('value').toFixed(2);
		rs_tweenty=dijit.byId('rs_tweenty').get('value').toFixed(2);
		dojo.byId("lb_tweenty").innerHTML =isNaN(d_tweenty)?0:d_tweenty;
		dojo.byId("rd_tweenty").innerHTML =isNaN(rs_tweenty)?0:rs_tweenty;
		 //10$
		d_ten=dijit.byId('d_ten').get('value').toFixed(2);
		rs_ten=dijit.byId('rs_ten').get('value').toFixed(2);
		dojo.byId("lb_ten").innerHTML =isNaN(d_ten)?0:d_ten;
		dojo.byId("rd_ten").innerHTML =isNaN(rs_ten)?0:rs_ten;
		 //5$
		d_five=dijit.byId('d_five').get('value').toFixed(2);
		rs_five=dijit.byId('rs_five').get('value').toFixed(2);
		dojo.byId("lb_five").innerHTML =isNaN(d_five)?0:d_five;
		dojo.byId("rd_five").innerHTML =isNaN(rs_five)?0:rs_five;            
		 //5$
		d_one=dijit.byId('d_one').get('value').toFixed(2);
		rs_one=dijit.byId('rs_one').get('value').toFixed(2);
		dojo.byId("lb_one").innerHTML =isNaN(d_one)?0:d_one;
		dojo.byId("rd_one").innerHTML =isNaN(rs_one)?0:rs_one;  
		//total dollar
		rs_dollar_total=dijit.byId('rs_dollar_total').get('value').toFixed(2);
		dojo.byId("lb_total").innerHTML =isNaN(rs_dollar_total)?0:rs_dollar_total; 
		///////////////////riel//////////////////////////

		//R50000
		r_fiftyhousend=dijit.byId('r_fiftyhousend').get('value');
		rs_fiftyhousend=dijit.byId('rs_fiftyhousend').get('value');
		dojo.byId("lb_fiftythousend").innerHTML =isNaN(r_fiftyhousend)?0:r_fiftyhousend;
		dojo.byId("rr_fiftythousend").innerHTML =isNaN(rs_fiftyhousend)?'0':rs_fiftyhousend; 
		//R10000
		r_tenthousend=dijit.byId('r_tenthousend').get('value');
		rs_tenthousend=dijit.byId('rs_tenthousend').get('value');
		dojo.byId("lb_tenthousend").innerHTML =isNaN(r_tenthousend)?0:r_tenthousend;
		dojo.byId("rr_tenhousend").innerHTML =isNaN(rs_tenthousend)?'0':rs_tenthousend; 
		//R5000
		r_fivehousend=dijit.byId('r_fivehousend').get('value');
		rs_fivehousend=dijit.byId('rs_fivehousend').get('value');
		dojo.byId("lb_fivethousend").innerHTML =isNaN(r_fivehousend)?0:r_fivehousend;
		dojo.byId("rr_fivethousend").innerHTML =isNaN(rs_fivehousend)?'0':rs_fivehousend; 
		//R2000
		r_tweentyhousend=dijit.byId('r_tweentyhousend').get('value');
		rs_tweentyhousend=dijit.byId('rs_tweentyhousend').get('value');
		dojo.byId("lb_twothousend").innerHTML =isNaN(r_tweentyhousend)?0:r_tweentyhousend;
		dojo.byId("rr_twothousend").innerHTML =isNaN(rs_tweentyhousend)?'0':rs_tweentyhousend; 
		//R1000
		thousend=dijit.byId('thousend').get('value');
		rs_thousend=dijit.byId('rs_thousend').get('value');
		dojo.byId("lb_thousend").innerHTML =isNaN(thousend)?0:thousend;
		dojo.byId("rr_thousend").innerHTML =isNaN(rs_thousend)?'0':rs_thousend;  
		//R500
		r_fivehundred=dijit.byId('r_fivehundred').get('value');
		rs_fivehundred=dijit.byId('rs_fivehundred').get('value');
		dojo.byId("lb_fivehundred").innerHTML =isNaN(r_fivehundred)?0:r_fivehundred;
		dojo.byId("rr_fivehundred").innerHTML =isNaN(rs_fivehundred)?'0':rs_fivehundred;  
		//R100
		r_onehundred=dijit.byId('r_onehundred').get('value');
		rs_onehundred=dijit.byId('rs_onehundred').get('value');
		dojo.byId("lbr_hundred").innerHTML =isNaN(r_onehundred)?0:r_onehundred;
		dojo.byId("rr_hundred").innerHTML =isNaN(rs_onehundred)?'0':rs_onehundred;
		//all total in khmer
		rs_kh_total=dijit.byId('rs_kh_total').get('value');
		dojo.byId("lbr_total_").innerHTML =isNaN(rs_kh_total)?0:rs_kh_total;
		//all dolla and riel
		total_amount=dijit.byId('total_amount').get('value');
		dojo.byId("lbdr_totals_amount").innerHTML =isNaN(total_amount)?0:total_amount;
		dijit.byId("inv_cash").show();	
	}
	
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("inv_cash").hide();	//hideDialog();
}
function hideDialog(){
	dijit.byId("inv_cash").hide();
}
</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:23cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("STUDENT_PAYMENT_RECEIPT");?>'" id="inv_cash" >
		<div id="divPrint" style="width: 21cm; height: 14cm ; padding: 0px; margin: 0px;">
		<table   cellspacing="20" width="100%" >
		<tr>
			<td colspan="2" width="100%">
				<table style="width: 100%;">
					<tr>
						<td width="25%">
							<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
						</td>
						<td width="50%" align="center">
							<strong>Cash Count Ticket</strong>
						</td>
						<td width="25%">
							&nbsp;
						</td>
					</tr>
				</table>
			</td>
		</tr>
		
		<tr> 
			<td width="48%" valign="top">
			<fieldset style="background:none; border-bottom: none;border-left: none;border-right: none;line-height: 10px;  ">
				<legend align="center"><?php echo $tr->translate("USD");?></legend>
					<table  cellspacing="5" style="width:100%;line-height:21px; height:220px; font-size:12pt; color:rgba(14, 0, 107, 1); padding: 0px; margin: 0px; ">
							<tr>
								<td>$ 100</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_hundred"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rd_hundred"></label></td>
						   	</tr>
						   	<tr>
								<td>$ 50</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_fifty"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rd_fifty"></label></td>
						   	</tr>
						   	<tr>
								<td>$ 20</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_tweenty"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rd_tweenty"></label></td>
						   	</tr>
						   	<tr>
								<td>$ 10</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_ten"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rd_ten"></label></td>
						   	</tr>
						   	<tr>
								<td>$ 5</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_five"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rd_five"></label></td>
						   	</tr>
						   	<tr>
								<td>$ 1</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_one"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rd_one"></label></td>
						   	</tr>
						   	<tr>
						   		<td>&nbsp;</td>
						   	</tr>
						   	<tr>
						   		<td>&nbsp;</td>
						   	</tr>
						   	<tr>
					            <td colspan="2" style="text-align: right;font-size: 14px;"><strong>All Total Dollars</strong></td>
					            <td style=""><strong style="font-size: 14px;">&nbsp;=&nbsp;$&nbsp;<label id="lb_total"></strong></label></td>
						   	</tr>
				  </table>
				</fieldset>
		</td>
		<td width="48%" valign="top">
		<fieldset style="background:none;border-bottom: none; border-left: none;border-right: none;line-height: 10px;">
			<legend align="center"><?php echo $tr->translate("RIEL");?></legend>
				<table   cellspacing="5" style="width:100% ;line-height:21px; height:220px; font-size:14px; color:rgba(14, 0, 107, 1); padding: 0px; margin: 0px;">
							<tr>
								<td>R 50,000</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_fiftythousend"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rr_fiftythousend"></label></td>
						   	</tr>
						   	<tr>
								<td>R 10,000</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_tenthousend"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rr_tenhousend"></label></td>
						   	</tr>
						   	<tr>
								<td>R 5,000</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_fivethousend"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rr_fivethousend"></label></td>
						   	</tr>
						   	<tr>
								<td>R 2,000</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_twothousend"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rr_twothousend"></label></td>
						   	</tr>
						   	<tr>
								<td>R 1,000</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_thousend"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rr_thousend"></label></td>
						   	</tr>
						   	<tr>
								<td>R 500</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lb_fivehundred"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rr_fivehundred"></label></td>
						   	</tr>
						   	<tr>
								<td>R 100</td>
					            <td>&nbsp;x&nbsp;&nbsp;<label id="lbr_hundred"></label></td>
					            <td>&nbsp;=&nbsp;&nbsp;<label id="rr_hundred"></label></td>
						   	</tr>
						   	<tr>
						   		<td>&nbsp;</td>
						   	</tr>
						   	<tr>
								<td align="right" colspan="2"><strong style="font-size: 14px;">Total in Khmer</strong></td>
					            <td "><strong style="font-size: 14px;">&nbsp;=&nbsp;&nbsp;R&nbsp;<label id="lbr_total_"></strong></label></td>
						   	</tr>
						   	<tr>
								<td align="right" colspan="2"><strong style="font-size: 14px;">Exchange Rate</strong></td>
					            <td ><strong style="font-size: 14px;">&nbsp;= &nbsp;R <label id="lbr_exchange_rate">4100</strong></label></td>
						   	</tr>
				  </table>
		</fieldset>
	 	 </td>
	</tr>
	<tr>
		<td colspan="2" align="center" style="border-top: 1px solid #000;" ><strong style="height:220px; font-size:14px;">All Totals :&nbsp;&nbsp;&nbsp;$&nbsp;&nbsp;&nbsp; <label id="lbdr_totals_amount"></strong></td>
	</tr>
	<tr>
		<td align="left"><strong style="height: 30px; border-top:1px solid #000; padding:2px 10px;">Remitted by</strong></td>
		<td align="right"><strong style="height: 30px; border-top:1px solid #000; padding:2px 10px;">Received by</strong></td>
	</tr>
	</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
	</div>
</div>	

