<title>Register</title>
<?php 
    $request=Zend_Controller_Front::getInstance()->getRequest();
    $tr = Application_Form_FrmLanguages::getCurrentlanguage();
    $frm =  $this->form_search;
?>
<meta charset="utf-8">
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form  action="<?php echo $this->url(array('module'=>'registrar','controller'=>'calculator','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
		            <div class="col-md-2 col-sm-2 col-xs-12">
		            	<input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->adv_search['adv_search']?>" placeholder="<?php echo $tr->translate("SEARCH");?>" type="text" >
		            </div>
		             <div class="col-md-2 col-sm-2 col-xs-12">
		             	<?php echo $frm->getElement("branch_id");?>
		            </div>
		             <div class="col-md-2 col-sm-2 col-xs-12">
		             	<?php echo $frm->getElement("user");?>
		            </div>
		             <div class="col-md-2 col-sm-2 col-xs-12">
		             	<?php echo $frm->getElement("start_date");?>
		            </div>
		             <div class="col-md-2 col-sm-2 col-xs-12">
		             	<?php echo $frm->getElement("end_date");?>
		            </div>
		            <div class="col-md-2 col-sm-2 col-xs-12">
		            	<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
		            </div>
		        </div>
	        </form>
		</div>
		<div class="card-box">
			<?php 
			   echo $this->list;
			?>
		</div>
	</div>
</div>
<script>
		dojo.require("dijit.form.DateTextBox");
</script>

