<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('លិខិតចាត់តាំង')); 
	echo $this->headTitle(''); 


	$session_lang=new Zend_Session_Namespace('lang');
	$lang_id=$session_lang->lang_id;	
	$dbgb = new Application_Model_DbTable_DbGlobal();

	$teacherId = $this->teacherId;

	$branchInfo = $this->branchInfo;

	if($lang_id==1){
       $schoolName = $branchInfo['school_namekh'];
	}elseif($lang_id==2){
		$schoolName = $branchInfo['school_nameen'];
	}
	
	$signature="";
	$stamp="";
	if (!empty($branchInfo['signature'])){
		if (file_exists(PUBLIC_PATH."/images/logo/".$branchInfo['signature'])){
			$signature = $this->baseUrl().'/images/logo/'.$branchInfo['signature'];
		}
	}
	if (!empty($branchInfo['stamp'])){
		if (file_exists(PUBLIC_PATH."/images/logo/".$branchInfo['stamp'])){
			$stamp = $this->baseUrl().'/images/logo/'.$branchInfo['stamp'];
		}
	}
	
	
	$dbExternal = new Application_Model_DbTable_DbExternal();
	
	$mainTeacherSigature="";
	if (!empty($rs['mainTeacherSigature'])){
		if (file_exists(PUBLIC_PATH."/images/photo/".$rs['mainTeacherSigature'])){
			$mainTeacherSigature = $this->baseUrl().'/images/photo/'.$rs['mainTeacherSigature'];
		}
	}
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>

<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<style>
tr.head td h2 {
    
    line-height: 27px !important;
}
.b{ font-weight: bold; }

p.padding-left {
    line-height: 24px !important;
}

table#exportExcel tr td {
    font-size: 14px !important;
}
label.title {
    font-size: 12px !important;
    min-width: 100px !important;
}
label.value {
    font-size: 14px !important;
    min-width: 100px !important;
}
</style>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.ready(function(){
	 
}); 
</script>
<div class="ptss-frame  js-ptss-frame "><!-- is-opened -->
		<div class="ptss__toggle-btn  js-ptss-toggle-btn ">
			<i class="fa fa-print"></i>
		</div>
      <div class="ptss__header"><?php echo $tr->translate("PRINT");?></div>
		<div class="ptss__settings">
			<div class="ptss__single-setting" id="ptss__layout">
				<div class="ptss__setting-control">
					<div class="ptss__layout-wrapper">
						<a class="qButton" title="<?php echo $tr->translate("Preview");?>" href="#" onclick="preview();"><i class="fa fa-search" aria-hidden="true"></i></a>
						<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrint();" ><i class="fa fa-print" aria-hidden="true"></i></a>
						<a class="qButton excel" href="#"  title="<?php echo $tr->translate("Export");?>"  onclick="exportExcel();"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a>
					</div>
					
				</div>
			</div>
		</div>
</div>
<div style="background: #fff;width: 21cm;margin: 0 auto;min-height: 25cm; padding: 0.5cm;">
<div id="divPrint">
			<style>
	   				.headReportRespone{
							display:none;
						}
						table ,
						table tr td,
						table tr td span{
							
							font-family: 'Times New Roman','Khmer OS Battambang';
							    font-size: 10px;
							line-height: 16px;
						}
						table tr td small {
							font-size: 9px;
							white-space: normal;
						}
						table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:10px;
							width: 100%;
						}
						table.content-data thead tr.style {
							line-height: 16px; 
							padding:1px 0px; 
							white-space: nowrap;height: 22px; 
							background: #ffe5dd;
							font-weight:600;
						}
						table.content-data thead tr.style td,
						table.content-data thead tr.style td span{
							line-height: 16px; 
							font-weight:600;
							color: #000000;
						}
						table.content-data thead tr.style td {
							padding:2px 0;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:10px;
							font-family: 'Times New Roman','Khmer OS Battambang';
						}
						table.tb-footer tr{
						 line-height: 14px; font-size:10px; padding:2px 0px; height: 25px;
						}
						table tr td{
							padding:0 2px;
						}
						span.khmerLabel,
						span.englishLabel{
							display:block;
						}
						span.khmerName, span.englishName {
							line-height: 24px;
							margin: 0;
							padding: 0;
							white-space: nowrap;
							padding: 0 3px;
						}
						tr.style span.khmerName {
							font-size:12px;
						}
						tr.style span.englishName {
							font-size:11px;
						}
						span.valueAmount {
							font-weight: 600;
							color: #002c7b;
						}
						ul.scoreTitle {
							padding: 0;
							margin: 0;
							list-style: none;
							font-size: inherit;
							margin-top: -15px;
						}
						ul.scoreTitle li {
							line-height: 18px;
							color:#002c7b;
							list-style-type:none !important;
						}
						@media print {
							ul.printInfo {
								position: absolute;
								left: 0;
								bottom: 5px;
								list-style: none;
								margin: 0;
								padding: 0;
								visibility: visible;
							}
							ul.printInfo li {
								font-family:'Times New Roman','Khmer OS Battambang';
								font-size: 8px;
								text-align: left;
								line-height:12px;
								color: #002c7b;
							}
						}
						
						td.titleComment {
							min-width:80px;
							white-space:normal;
							
						}
						tr.rowValue td {
							padding:2px;
						}
						tr.rowValue td, tr.rowValue td span {
							line-height: 12px;
						}
						tr.rowValue td {
							padding: 5px 0;
						}
						span.valueLabel {
							display: block;
							line-height: inherit;
						}
					
						span.valueLabel.timeLabel {
							font-size: 12px;
							font-weight: 600;
						}
						span.valueLabel.khmerLabel {
							font-size: 10px;
							font-weight: normal !important;
							line-height: 18px;
							font-family: 'Times New Roman','Khmer OS Muol Light';
						}

						span.className {
							font-size: 12px;
							line-height: 16px;
							margin: 5px 0;
							font-family:Tahoma,'Khmer OS Battambang';
						}
						span.ValueLabelTeacher{
							display: inline-block;
							font-size:12px;
							font-weight: bold;
							font-family:'Khmer OS Battambang';
							color:#f00;
						}
						span.empty {
							color: #8e834e;
						}
						span.red {
							color: #f00;
						}
						span.blue {
							color: #0053ff;
						}
						@media print{
							@page {
								page:A4;
								margin: 0.8cm;
							}
						}
	  		 </style>
				<table width="100%" style="font-size:12px; font-family:Tahoma,'Khmer OS Battambang';"> 
					<tr class="head">
						<td width="35%" valign="middle"></td>
						<td width="30%" align="center"></td>
						<td width="35%" align="center"></td>
					</tr>
					<tr class="head">
						<td colspan="2" valign="bottom" >
							<h2 style="font-size:12px;line-height: 13px; font-weight: initial; font-family:'Khmer OS Muol Light';" >  &nbsp;</h2>
					   		<h2 style="font-size:12px;line-height: 13px; font-weight: initial; font-family:'Khmer OS Muol Light';">មន្ទីរអបរំ យុវជន និងកីឡា</h2>
							<h2 style="font-size:12px;line-height: 13px; font-weight: initial; font-family:'Khmer OS Muol Light';"><?php echo $schoolName; ?></h2>
							<h2 style="font-size:12px;line-height: 13px; font-weight: initial; font-family:'Khmer OS Battambang';">លេខ................. <?php echo $branchInfo['branch_code']; ?></h2>
					   </td>
					   <td align="center" valign="top">
					   		<h2 style="font-size:12px;line-height: 13px; font-weight: initial; font-family:'Khmer OS Muol Light';" >ព្រះរាជាណាចក្រកម្ពុជា</h2>
					   		<h2 style="font-size:12px;line-height: 13px; font-weight: initial; font-family:'Khmer OS Muol Light';">ជាតិ សាសនា ព្រះមហាក្សត្រ</h2>
					   		<img alt="" src="<?php echo $this->baseUrl()."/images/sign.PNG"?>" style=" width: 120px;">
					   </td>
					</tr>
					<tr class="head">
					   <td align="center" colspan="3" valign="top">
						   &nbsp;
					   </td>
					</tr>
					<tr class="head">
					   <td colspan="3" align="center">
					   		<h1 style="font-size:12px;font-weight: initial;font-family:'Khmer OS Muol Light';" >លិខិតចាត់តាំង</h1>
					   </td>
					</tr>

					<tr class="head">
					   <td colspan="3" align="left">
					 	  <label style="font-size:12px;font-weight: initial;font-family:'Khmer OS Muol Light';" >យោង ៖ </label> &nbsp;<label style="font-size:12px;font-weight: initial;font-family:'Khmer OS Battambang';" >លិខិតបើកសាលា និងកិច្ចសន្យាការងារ </label>
					   </td>
					</tr>
					<tr class="head">
					   <td align="center" colspan="3" valign="top">
						   &nbsp;
					   </td>
					</tr>
					<tr class="head"></tr>
					   <td colspan="3" align="left">
					  	 <label style="font-size:12px; line-height: 25px; font-weight: initial;font-family:'Khmer OS Battambang';" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  លោក <span class="ValueLabelTeacher red"><?php echo $this->rs['teacher_name_kh'];?></span> ភេទ <span class="ValueLabelTeacher red"><?php echo $this->rs['sex'];?></span> ឯកទេស <span class="ValueLabelTeacher red">គណិតវិទ្យា</span> ជាបុគ្គលិកនៃសាលាបញ្ញាសាស្រ្តអន្តរជាតិហ្គ្រេនភ្នំពេញ ត្រូវបានចាត់តាំងអោយបង្រៀនថ្នាក់ទី <span class="ValueLabelTeacher red"> <?php echo $this->rs['teachingGroup'];?> </span> ដូចមានភ្ជាប់ជូនក្នុងកាលវិភាគខាងក្រោម ចាប់ពី<span class="ValueLabelTeacher red"> ថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d"));?> ខែ<?php echo $dbgb->getMonthInkhmer(date("m"));?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y"));?> </span>នេះតទៅ ។</label>
						 
					   </td>
					</tr>
				
					<tr class="head">
					   <td colspan="3" align="center">
					   		<h1 style="font-size:12px;font-weight: initial;font-family:'Khmer OS Muol Light';" >កាលវិភាគបង្រៀនវគ្គសិក្សាពេលវិស្សមកាលឆ្ឆ្នាំសិក្សា​ ២០២៣​-២០២៤</h1>
					   </td>
					</tr>
					<tr class="head">
					   <td align="center" colspan="3" valign="top">
						   &nbsp;
					   </td>
					</tr>
					<tr class="head">
					   <td align="left">
					   		<label style="font-size:12px;font-weight: initial;font-family:'Khmer OS Muol Light';" >ឈ្មោះ </label> &nbsp;<label style="font-size:12px;font-weight: initial;font-family:'Khmer OS Battambang';" ><?php echo $this->rs['teacher_name_kh'];?> </label>
					   </td>
					   <td  align="center">
					   		<label style="font-size:12px;font-weight: initial;font-family:'Khmer OS Muol Light';" >ថ្នាក់ទី</label> &nbsp;<label style="font-size:12px;font-weight: initial;font-family:'Khmer OS Battambang';" ><?php echo $this->rs['teachingGroup'];?></label>
					   </td>
					   <td align="right">
					   		<label style="font-size:12px;font-weight: initial;font-family:'Khmer OS Muol Light';" >លេខទូរស័ព្ទ</label> &nbsp;<label style="font-size:12px;font-weight: initial;font-family:'Khmer OS Battambang';" > <?php echo $this->rs['tel'];?> </label>
					   </td>
					</tr>
					<tr class="head">
					   <td align="center" colspan="3" valign="top">
						   &nbsp;
					   </td>
					</tr>
					<tr class="head">
					   <td align="center" colspan="3" valign="top">
					 	  <table class="content-data"  cellpadding="2"​  border="1" >
								<thead>
									<tr class="style" align="center" >
										<td	scope="col" >
											<span class="valueLabel khmerLabel">ម៉ោងបង្រៀន</span>
											<span class="valueLabel englishLabel">Teaching Time</span>
										</td>
										<?php 
										$day = count($this->days);
										if(!empty($this->days)) foreach($this->days AS $key => $days){ 
											
										?>
										<td scope="col" class="titleComment"  >
											<span class="valueLabel khmerLabel"><?php echo $days['daysKh'];?></span>
											<span class="valueLabel englishLabel"><?php echo $days['daysEng'];?></span>
										</td>
										<?php } ?>
									</tr>
								</thead>
										
									<?php 
										$i=0; 
										$m=0;$f=0;
										$moment=1;
										$momentev=1;
										if(!empty($this->timeTeaching)) foreach($this->timeTeaching as $time){ 
										$i++;
										?>
										<?php if($time['from_hour']< 12 ){ if( $moment==1){ 
											?>
											<tr class="rowValue" >
												<td colspan="<?php echo $day+1; ?>" align="center">
													<strong><span class="className khmerLabel  blue"><?php echo $tr->translate("ពេលព្រឹក") ;?></span></strong>
												</td>
											</tr>
										<?php
											$moment++;
											}
										?>
										<tr  class="rowValue">
											<td data-label="ម៉ោងបង្រៀន/Teaching Time" align="center" style="white-space:nowrap;">
												<?php 
													
													$fromHour = $time['from_hour'];
													$toHour = $time['to_hour'];
												?>
												<span class="valueLabel timeLabel"><?php echo $time['fromHourTitle'];?> - <?php echo $time['toHourTitle'];?></span>
											</td>
											
											<?php 
												if(!empty($this->days)) foreach($this->days AS $key => $days){ 
													$dayID = $days['id'];
													$arrCondiction = array(
														'fromHour'	=>$fromHour
														,'toHour'	=>$toHour
														,'dayID'	=>$dayID
														,'teacherId'	=>$teacherId 
													);
													$row = $dbExternal->getScheduleInfoDetail($arrCondiction);
												?>
											<td data-label="<?php echo $days['daysKh']."/".$days['daysEng'];?>" align="center" >
												<?php if(empty($row)){ ?>
													<span class="valueLabel khmerLabel "></span>
													<!-- <span class="valueLabel khmerLabel empty">មិនមាន</span>
													<span class="valueLabel englishLabel empty">(Empty)</span> -->
												<?php }else{
													$gradeTitle = $row['gradeTitle'];
													if(empty($gradeTitle)){ $gradeTitle = $row['gradeTitleEng']; }else{ if(!empty($row['gradeTitleEng'])){$gradeTitle = $gradeTitle."/".$row['gradeTitleEng'];}}
													?>
													<span class="valueLabel khmerLabel red"><?php echo $row['subjectTitleKh']?> (<?php if(!empty($row['subjecLang'])){ if($row['subjecLang']==1){ echo "ខ្មែរ"; }else{  echo "English"; }}?>) </span>
													<span class="className valueLabel blue"><?php echo ' <strong>'.$row['groupCode'].'</strong>';?></span>
												
												<?php }?>
											</td>
											<?php } ?>
										</tr>
									<?php  }else{ ?>
										<?php if( $momentev==1){ 
											?>
											<tr class="rowValue" >
												<td colspan="<?php echo $day+1; ?>" align="center">
													<strong><span class="className khmerLabel  blue"><?php echo $tr->translate("ពេលរសៀល") ;?></span></strong>
												</td>
											</tr>
										<?php
											$momentev++;
											}
										?>
										<tr  class="rowValue">
											<td data-label="ម៉ោងបង្រៀន/Teaching Time" align="center" style="white-space:nowrap;">
												<?php 
													
													$fromHour = $time['from_hour'];
													$toHour = $time['to_hour'];
												?>
												<span class="valueLabel timeLabel"><?php echo $time['fromHourTitle'];?> - <?php echo $time['toHourTitle'];?></span>
											</td>
											
											<?php 
												if(!empty($this->days)) foreach($this->days AS $key => $days){ 
													$dayID = $days['id'];
													$arrCondiction = array(
														'fromHour'	=>$fromHour
														,'toHour'	=>$toHour
														,'dayID'	=>$dayID
														,'teacherId'	=>$teacherId 
													);
													$row = $dbExternal->getScheduleInfoDetail($arrCondiction);
												?>
											<td data-label="<?php echo $days['daysKh']."/".$days['daysEng'];?>" align="center" >
												<?php if(empty($row)){ ?>
													<span class="valueLabel khmerLabel "></span>
													<!-- <span class="valueLabel khmerLabel empty">មិនមាន</span>
													<span class="valueLabel englishLabel empty">(Empty)</span> -->
												<?php }else{
													$gradeTitle = $row['gradeTitle'];
													if(empty($gradeTitle)){ $gradeTitle = $row['gradeTitleEng']; }else{ if(!empty($row['gradeTitleEng'])){$gradeTitle = $gradeTitle."/".$row['gradeTitleEng'];}}
													?>
													<span class="valueLabel khmerLabel red"><?php echo $row['subjectTitleKh']?> (<?php if(!empty($row['subjecLang'])){ if($row['subjecLang']==1){ echo "ខ្មែរ"; }else{  echo "English"; }}?>) </span>
													<span class="className valueLabel blue"><?php echo ' <strong>'.$row['groupCode'].'</strong>';?></span>
												
												<?php }?>
											</td>
											<?php } ?>
										</tr>

									<?php	} ?>
								<?php } ?>
							</table>				  
					   </td>
					</tr>
					<tr class="head">
					   <td align="center" colspan="3" valign="top">
						   &nbsp;
					   </td>
					</tr>
					<tr class="head">
					   <td colspan="3" valign="top">
						  <table width="100%">
						  		<tr class="head">
									<td align="left" colspan="2" >
									</td>
									<td colspan="2" align="center" >
										<h1 style="font-size:12px;font-weight: initial;font-family:'Khmer OS Battambang';"><?php echo $branchInfo['workat'];?> ថ្ងៃទី<?php echo $dbgb->getNumberInkhmer(date("d"));?> ខែ<?php echo $dbgb->getMonthInkhmer(date("m"));?> ឆ្នាំ<?php echo $dbgb->getNumberInkhmer(date("Y"));?></h1>
										<h1 style="font-size:12px;font-weight: initial;font-family:'Khmer OS Muol Light';">នាយកស្តីទី</h1>
									</td>
								</tr>
								<tr class="head">
									<td  align="left" colspan="2" >
											<h1 style="font-size:12px;font-weight: initial;font-family:'Khmer OS Battambang';">ចម្លងជូន ៖</h1>
											<h1 style="font-size:12px;font-weight: initial;font-family:'Khmer OS Battambang';"> - គ្រប់ផ្នែកនៃសាលាបញ្ញាសាស្ត្រ "ដើម្បីជ្រាបជាពត៍មា​ន​​"</h1>
											<h1 style="font-size:12px;font-weight: initial;font-family:'Khmer OS Battambang';"> - សាម៉ីជន " ដើម្បីអនុវត្ត​​ "</h1>
											<h1 style="font-size:12px;font-weight: initial;font-family:'Khmer OS Battambang';"> - ឯកសា - កាលប្បវត្តិ សបអហ</h1>
										
										</td>
										<td colspan="2" align="center">
											<div>
												<?php if(!empty($stamp)){?>
													<img src="<?php echo $stamp;?>" style="max-height:100px;position:relative;" />
												<?php } ?>
											</div>
											<?php if(!empty($signature)){?>
												<img src="<?php echo $signature;?>" style="left:50px;width:200px;position:relative;" />
											<?php } ?>
									</td>
								</tr>
						  </table>
					   </td>
					</tr>
	  		 	</table>
	   		</div>
		 </div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>