<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('TEACHER_ATTENDANCE_SHEET')); 
	echo $this->headTitle(''); 
	$classHideHeight=classHideHeight;
	
	$start_date = $this->search['start_date'];
	$end_date = $this->search['end_date'];
	
	$date1 = date("d-m-Y",strtotime($start_date));
	$date2 = date('d-m-Y',strtotime($end_date));
	$diff = abs(strtotime($date2) - strtotime($date1));
	$years = floor($diff / (365*60*60*24));
	$months = floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
	$days = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
	$amount_day =$diff/ (60*60*24);
	
	$amount_day = $amount_day + 1;
	
	$arrayMonthAmtDay=array();
	$loopMonth="";
	$amtDay=0;
	for($l=0;$l<$amount_day;$l++){
		if(date('D',strtotime(" $start_date+$l day"))=="Sun"){
		}else{
			if($loopMonth!=date('F',strtotime("$start_date +$l day")) ){
				if($l>0){
					$arrayMonthAmtDay[$loopMonth] = $amtDay;
					$amtDay=1;
				}
			}
			$amtDay=$amtDay+1;
			$loopMonth=date('F',strtotime("$start_date +$l day"));
		}
	}
	$arrayMonthAmtDay[$loopMonth] = $amtDay;
	
	$dbStaff = new Allreport_Model_DbTable_DbRptAllStaff();
	
	$arrDaySort = array(
		1=>"M",
		2=>"T",
		3=>"W",
		4=>"TH",
		5=>"F",
		6=>"S",
		7=>"SU",
	);
	$frm =  $this->form_search;
?>	
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<div style="min-height:10cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-file-text " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('TEACHER_ATTENDANCE_SHEET');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id=dijit.byId('branch_id').get('value');
				if(branch_id=='' || branch_id==0){
					alert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>!');
					dijit.byId('branch_id').focus(); 
					return false;
				}
				academic_year=dijit.byId('academic_year').get('value');
				if(academic_year=='' || academic_year==0){
					alert('<?php echo $tr->translate('PLEASE_SELECT_YEAR');?>!');
					dijit.byId('academic_year').focus(); 
					return false;
				}
				teacherId=dijit.byId('teacherId').get('value');
				if(teacherId=='' || teacherId==0){
					department=dijit.byId('department').get('value');
					if(department=='' || department==0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_DEPARTMENT');?>!');
						dijit.byId('department').focus(); 
						return false;
					}
				}
                loadingBlock();
				return true;
			}else {
				return false;
			}
		</script>
		<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="card-blogform">
					<div class="card-body"> 
						<div class="row"> 
							<div class="col-md-12 col-sm-12 col-xs-12">
								
								<div class="form-group">

									<div class="col-md-2 col-sm-2 col-xs-12">
										<?php echo $frm->getElement("branch_id");?>
									</div>
									<div class="col-md-2 col-sm-2 col-xs-12">
										<?php echo $frm->getElement("academic_year");?>
									</div>
									<div class="col-md-2 col-sm-2 col-xs-12">
											<?php echo $frm->getElement("degree");?>
									</div>
									<div class="col-md-2 col-sm-2 col-xs-12">
										<input id="group" />
									</div>
									<div class="col-md-2 col-sm-2 col-xs-12">
										<?php echo $frm->getElement("department");?>
									</div>
									<div class="col-md-2 col-sm-2 col-xs-12">
										<input id="teacherId" />
									</div>
									
								</div>
								<div class="form-group">
									
									<div class="col-md-2 col-sm-2 col-xs-12">
										<input dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="start_date" name="start_date" placeholder="<?php echo $tr->translate('SEARCH');?>....." value="<?php echo $this->search['start_date'];?>" type="text">
									</div>
									<div class="col-md-2 col-sm-2 col-xs-12">
										<input dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="end_date" name="end_date"  value="<?php echo $this->search['end_date'];?>" type="text">
									</div>
									<div class="col-md-2 col-sm-2 col-xs-12">
										<?php $stuOrderBy = empty($this->search['stuOrderBy'])?0:$this->search['stuOrderBy'];?>
										<select class="fullside" dojoType="dijit.form.FilteringSelect" id="stuOrderBy" name=stuOrderBy>
											<option value="0" <?php if($stuOrderBy==0){echo "selected";}?> ><?php echo $tr->translate("DEFAULT");?></option>
											<option value="1" <?php if($stuOrderBy==1){echo "selected";}?>><?php echo $tr->translate("BY_STU_CODE_ASC");?></option>
											<option value="2" <?php if($stuOrderBy==2){echo "selected";}?>><?php echo $tr->translate("BY_STU_KHNAME_ASC");?></option>
											<option value="3" <?php if($stuOrderBy==3){echo "selected";}?>><?php echo $tr->translate("BY_STU_ENNAME_ASC");?></option>
											
										</select>
									</div>
									<div class="col-md-2 col-sm-2 col-xs-12">
										<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
									</div>
									
								</div>
							</div>
						</div>
					</div>
				</div>
		</div>
		
	</form>
	<div id="divPrint">
		<style>
				.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table.content-data { page-break-inside:auto }
					tr.content-data{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:8px;
						width:100%;
				
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:12px !important; padding:2px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.content-data  tr.style {
					 white-space: nowrap;
					
					}
					
					
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:11px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:12px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:0 2px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					.redBold {
						font-weight: 600;
						color: #f80000;
					}
					table.content-data tr td{
						padding: 2px;
						
					}
					table.content-data tr th{
						padding: 2px;
						text-align:center;
						
					}
					
					
					tr.cheader td,
					tr.cheader th
					{
						font-weight: 600;
					}
					

					td.dayWith {
						width: 35px;
					}
					.centerClass{
						text-align:center;
						
					}
					
					table.subHeadTable {
						border-collapse: collapse;
						font-family: 'Times New Roman','Khmer OS Battambang';
						font-size: 14px;
						font-weight: bold;
						line-height: 25px;
						border-color: #000;
					}

					table.subHeadTable tr td {
						padding: 0;
						margin: 0;
					}
					.teacherMoulName {
						font-family: 'Times New Roman','Khmer OS Muol Light';
						font-weight: normal;
					}
					span.teacherName {
						display: block;
						line-height: 18px;
						font-size: 16px;
					}
					.uppercase {
						text-transform: uppercase;
					}
					.hide{visibility: hidden;}
					@media print{
								@page{
									margin:0.3cm 0.7cm 0cm 0.7cm;
									page-break-before: avoid;
									-webkit-transform: scale(0.5);  /* Chrome, Safari 3.1+  */
									-moz-transform: scale(0.5);  /* Firefox 3.5-15 */
									-ms-transform: scale(0.5);   /* IE 9 */
									-o-transform: scale(0.5);    /* Opera 10.50-12.00 */
									transform: scale(0.5);
									page: A4;
									size: landscape;
								}
								.hide{visibility: visible; height: 20px;}
					}
					
					table.content-data{
						page-break-inside:always; page-break-after:always; 
					}
					span.noteBottom {
						font-size: 11px;
						line-height: 14px;
					}
					span.teachingPeriods {
						white-space: normal;
						line-height: 14px;
					}
					
					tr.rowHead{
						background: #b2afaf;
					}
					td.notStudy {
						background: #b2afaf;
					}
					.holiday-label {
						line-height: 1;
						padding-top: .5rem;
						position: relative;
						transform: rotate(180deg);
						white-space: nowrap;
						writing-mode: vertical-rl;
						color: red;
					}
		</style>
		<?php if(!empty($this->rs)) {?>
				<?php  
					$i=0;
					$male=0;$femle=0;
					
					$groupId="";
					$subjectId="";
					$arrStudyDay=array();
					foreach ($this->rs as $key => $row){ 
				?>
						<?php if($subjectId!=$row['subject_id'] || $groupId!=$row['group_id']) { 
	
						
						?>
						<?php if($key>0){?> 
							<?php for($j=1;$j<=5;$j++){ 
								$extra_num = $i+$j;
								if ($extra_num > 30) {
									break;
								}
							?>
							<tr style="font-size:11px;height: 14px;" align="left">
								<td class="centerClass" style="width:30px"><?php echo $extra_num;?></td>
								<td style="width:170px"></td>
								<td class="centerClass" style="width:120px"></td>
								<td class="centerClass" style="width:50px">
								</td>
								<?php if($amount_day>0 ){
										for($k=0;$k<$amount_day;$k++){
											if(date('D',strtotime(" $start_date+$k day"))=="Sun"){
												
											}else{ 
												$dOfWeek = date('w',strtotime("$start_date +$k day"));
												$className="";
												if(empty($arrStudyDay[$dOfWeek])){
													$className="notStudy";
												}
											?>
											<td align="center" class="<?php echo $className;?>" >
											</td>
									<?php 
											} 
										} 
									}
								?>
							</tr>
							<?php } ?>
						<?php } 
						
						$i = 0;
						$arrTime = array(
							"teacherId"=>$row['techer_id'],
							"groupId"=>$row['group_id'],
							"subjectId"=>$row['subject_id'],
						);
						$resultTime = $dbStaff->getTeachingTimeByGroupAndSubject($arrTime);

						if($key>0){
								$arrStudyDay=array();
							?> 
							
							<tr>
								<td colspan="<?php echo 4+$amount_day;?>" style="border:1px solid #fff;border-top:1px solid #000;">
								<span class="noteBottom"><i>Note</i>: Please do not add any student's name without the consent from the enrollment office.</span>
								</td>
							</tr>
						</table>	
						<?php } 
						
						$stringTimeList="";
						if(!empty($resultTime)) {
							
							foreach($resultTime as $eIndex => $teachingList){
								$daySort = empty($arrDaySort[$teachingList["day_id"]]) ? "" : "(".$arrDaySort[$teachingList["day_id"]].")";
								if(!empty($stringTimeList)) {
									$stringTimeList = $stringTimeList." ".$daySort." ".$teachingList["timeTitle"].";";
								}else{
									$stringTimeList = $daySort." ".$teachingList["timeTitle"].";";
								}
								$arrStudyDay[$teachingList["day_id"]]=$teachingList["day_id"];
							}
						}
						?>
						<table class="content-data" cellpadding="5" style="<?php if($key>0){ echo "margin-top:30px !important;"; } ?>  font-size:12px; margin:0 auto;width:100%; border-collapse: collapse;border:1px solid #000; white-space: nowrap;font-family: 'Times New Roman','Khmer OS Battambang';"  border="1" >
							<?php if($key>0){ ?> 
				    		<tr class="hide"  style="border:1px solid #000;">
								<td colspan="<?php echo 4+$amount_day;?>" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
							</tr>
							<?php } ?>
							<tr>
									<td colspan="<?php echo 4+$amount_day;?>" style="padding: 0;">
										<table class="subHeadTable" width="100%" border="1"  >
											<tr class="centerClass">
												<td class="centerClass" style="background: #0c1c4a;width:250px;color: #ffffff;">
													ATTENDANCE SHEET
												</td>
												<td >
													<?PHP echo $row['academicYearTitle'];?>
												</td>
												<td>
													Grade: <?PHP echo str_replace("Grade","",$row['group_code']);?>
												</td>
												<td>
													Room: <?PHP echo str_replace("Room","",$row['roomName']);?>
												</td>
												<td>
													<?PHP 
													$rangMonth="";
													if(!empty($arrayMonthAmtDay)){ 
														foreach($arrayMonthAmtDay as $key=> $currentMonth){
															if(!empty($rangMonth)) {
																$rangMonth = $rangMonth."-".$key;
															}else{
																$rangMonth = $key;
															}
														}
													} 
													echo $rangMonth;
													?>
												</td>
											</tr>
											<tr>
												<td colspan="5">
													<table width="100%" border="0" style="font-size:12px; margin:0 auto;width:100%; border-collapse: collapse; white-space: nowrap;font-family: 'Times New Roman','Khmer OS Battambang';">
														<tr class="centerClass">
															<td height="30px" width="30%">
																<span class="teacherName uppercase"><?PHP echo $row['teacherNameEng'];?></span>
															</td>
															<td class="centerClass" style="border-left:1px solid #000;">
																<?PHP echo $row['subjectNameEng'];?>
															</td>
															<td width="55%" style="border-left:1px solid #000;">
																<span class="teachingPeriods">
																	Teaching Periods: <?PHP echo $stringTimeList;?>
																</span>
															</td>
														</tr>
													</table>
												</td>
											</tr>
											
										</table>
									</td>
								</tr>
								<tr class="cheader">
									<td colspan="4" class="centerClass" height="90px">Instructor's Signature</td>
									<?php if($amount_day>0 ){
										for($k=0;$k<$amount_day;$k++){
											if(date('D',strtotime(" $start_date+$k day"))=="Sun"){
												
											}else{ ?>
											<td align="center" class="holiday-label">
											  
											</td>
									<?php 
											} 
										} 
									}
									?>
								</tr>
								<tr class="cheader rowHead" align="center" >
									<td colspan="4">Mth</td>
									<?php if($amount_day>0 ){
										
										$loopMonth="";
										for($k=0;$k<$amount_day;$k++){
											
											if(date('D',strtotime(" $start_date+$k day"))=="Sun"){
												
											}else{ ?>
											<?php 
											if($loopMonth!=date('M',strtotime("$start_date +$k day"))){
												$colSpan = empty($arrayMonthAmtDay[date('F',strtotime("$start_date +$k day"))]) ? 1 : $arrayMonthAmtDay[date('F',strtotime("$start_date +$k day"))];
											?>
											<td align="center" colspan="<?php echo $colSpan; ?>"  >
												<?php echo date('F',strtotime("$start_date +$k day"));?>
											</td>
											<?php 
												}
											
											$loopMonth=date('M',strtotime("$start_date +$k day"));
											?>
											
									<?php 
											} 
										} 
									}
									?>
								</tr>
								<tr class="cheader rowHead" align="center">
									<td colspan="4">Day</td>
									<?php if($amount_day>0 ){
										for($k=0;$k<$amount_day;$k++){
											if(date('D',strtotime(" $start_date+$k day"))=="Sun"){
												
											}else{
												$dayId = date('w',strtotime("$start_date +$k day"));
												if($dayId==0){$dayId=7;}
												$dayShort = empty($arrDaySort[$dayId]) ? "" : $arrDaySort[$dayId];
									

												?>
											<td align="center" class="uppercase dayWith" >
											<?php echo $dayShort;?>
											</td>
									<?php 
											} 
										} 
									}
									?>
								</tr>
								<tr class="cheader rowHead" align="center">
									<td colspan="4">Date</td>
									<?php if($amount_day>0 ){
										for($k=0;$k<$amount_day;$k++){
											if(date('D',strtotime(" $start_date+$k day"))=="Sun"){
												
											}else{ ?>
											<td align="center" >
											<?php echo date('d',strtotime("$start_date +$k day"));?>
											</td>
									<?php 
											} 
										} 
									}
									?>
								
								</tr>
						<?php } $subjectId=$row['subject_id']; $groupId=$row['group_id']; $i=$i+1;?>
								
							<tr style="font-size:11px;height: 14px;" align="left">
								<td class="centerClass" style="width:30px"><?php echo $i;?></td>
								<td style="width:170px"><?php echo $row['fullName'];?></td>
								<td class="centerClass" style="width:120px"><?php echo $row['stu_code'];?></td>
								<td class="centerClass" style="width:50px">
									<?php 
									$stringGender = "M";
									if($row['sex']==1){
										$male=$male+1;
									}else{
										$femle=$femle+1;
										$stringGender = "F";
									}
									echo $stringGender;
									?>
								</td>
								<?php if($amount_day>0 ){
										for($k=0;$k<$amount_day;$k++){
											if(date('D',strtotime(" $start_date+$k day"))=="Sun"){
												
											}else{ 
												$dOfWeek = date('w',strtotime("$start_date +$k day"));
												$className="";
												if(empty($arrStudyDay[$dOfWeek])){
													$className="notStudy";
												}
											?>
											<td align="center" class="<?php echo $className;?>" >
											</td>
									<?php 
											} 
										} 
									}
								?>
							</tr>
					<?php }?>
						<?php for($j=1;$j<=5;$j++){
							  $extra_num = $i+$j;
								if ($extra_num > 30) {
									break;
								}
							 ?>
							<tr style="font-size:11px;height: 14px;" align="left">
								<td class="centerClass" style="width:30px"><?php echo  $extra_num;?></td>
								<td style="width:170px"></td>
								<td class="centerClass" style="width:120px"></td>
								<td class="centerClass" style="width:50px">
								</td>
								<?php if($amount_day>0 ){
										for($k=0;$k<$amount_day;$k++){
											if(date('D',strtotime(" $start_date+$k day"))=="Sun"){
												
											}else{ 
												$dOfWeek = date('w',strtotime("$start_date +$k day"));
												$className="";
												if(empty($arrStudyDay[$dOfWeek])){
													$className="notStudy";
												}
											?>
											<td align="center" class="<?php echo $className;?>" >
											</td>
									<?php 
											} 
										} 
									}
								?>
							</tr>
							<?php } ?>
							<tr>
								<td colspan="<?php echo 4+$amount_day;?>" style="border:1px solid #fff;border-top:1px solid #000;">
								<span class="noteBottom"><i>Note</i>: Please do not add any student's name without the consent from the enrollment office.</span>
								</td>
							</tr>				
					</table>
					
					<?php }?>	
	</div>
</div>


<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore"); 

	dojo.require("dojo.html");
	var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var teacher_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->all_teacher_by_group));?> );
	var subject_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->all_subject_by_group));?> );
	dojo.ready(function(){
		
		new dijit.form.FilteringSelect({
			store: group_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			id: "group",
			name: "group",  
			class: 'fullside', 
			readonly:false,
			required:false,
			placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
			onChange: function() {  
				getAllTeacherByGroup();
			}
		}, "group");
		
		new dijit.form.FilteringSelect({
			store: teacher_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			id: "teacherId",
			name: "teacherId",  
			class: 'fullside', 
			readonly:false,
			required:false,
			placeHolder:"<?php echo $tr->translate("SELECT_TEACHER");?>",          
			onChange: function() {  
				
			}
		}, "teacherId");

		var branch_id = dijit.byId('branch_id');
		branch_id.on('change', function(evt) {
			getAllGroupByBranch();
			getAllTeacherByGroup();
		});
		var academic_year = dijit.byId('academic_year');
		academic_year.on('change', function(evt) {
			getAllGroupByBranch();
		});

		var department = dijit.byId('department');
		department.on('change', function(evt) {
			getAllTeacherByGroup();
		});

		getAllGroupByBranch();
		getAllTeacherByGroup();
		
		<?php if(!empty($this->search['branch_id'])){ ?>
		dijit.byId('branch_id').set('value','<?php echo $this->search['branch_id']?>');
		<?php } ?>
		<?php if(!empty($this->search['academic_year'])){ ?>
		dijit.byId('academic_year').set('value','<?php echo $this->search['academic_year']?>');
		<?php } ?>
		
	});

	var oldBranch = "<?php echo $this->search['branch_id']?>";
	url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
	function getAllGroupByBranch(){
		dijit.byId('group').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('group').set('store',group_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		academic_year = dijit.byId('academic_year').get('value');
		if(academic_year=='' || academic_year==-1){academic_year ="";}
		
		dojo.xhrPost({
			url: url_getgroup,
			content:{
				'branch_id':branch_id,
				'academic_year':academic_year,
				'noaddnew':1,
				'forfilter':1
				},
			handleAs:"json",
			load: function(data) {
				group_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('group').set('store',group_store);   
				if(oldBranch==branch_id){
		    		dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		  	 	}
			},
			error: function(err) {
			}
		});
	}
	
	url_getteacher = '<?php echo $this->url(array('module'=>'foundation','controller'=>'lecturer','action'=>'getteacher'));?>';
	function getAllTeacherByGroup(){
		dijit.byId('teacherId').reset();
		
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var teacher_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('teacherId').set('store',teacher_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		
		group = dijit.byId('group').get('value');
		department = dijit.byId('department').get('value');

		if(group=='' || group==-1){
			group=0;
		}
		dojo.xhrPost({
			url: url_getteacher,
			content:{
				'branch_id':branch_id,
				'groupId':group,
				'department':department,
				'hideAddnew':1,
				},
			handleAs:"json",
			load: function(data) {
				teacher_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('teacherId').set('store',teacher_store);   
				<?PHP if(!empty($this->search['teacherId'])){?>
				dijit.byId('teacherId').set('value','<?php echo $this->search['teacherId'];?>');  
				<?PHP } ?>
			},
			error: function(err) {
			}
		});
	}

	

</script>
