<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("EDIT_STUDENT_ATTENDENCE"));
	$row_sub=$this->rows_sub;
	$_model = new Foundation_Model_DbTable_DbStudentAttendance();
?>	
<head>
  <meta charset="utf-8">
</head>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$payment_term = $this->payment_term;
	$rs_sub=$this->rows_sub;
?>	
<style>
select{ width:100%;}
fieldset{  background:none;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 0px; border:1px solid #ccc;font-size: 12px;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}

div.panel {
    padding: 0 18px;
    display: none;
    background-color: white;
}
div.panel.show {
    display: block;
}
table#table_row tr th,
table#table_row tr td {
    border: solid 1px #ccc;
    text-align: center;
}

</style>
<style>
ul.blogscoresubject li{list-style: none;width:10%;float: left; }
ol.blogscoresubject li{list-style: none;width:10%;float: left; }
ol{margin: 10px;}
table#table_row {
    width: 100%;
}
.label-info {
    background: #466979;
    color: #fff;
    margin-top: 10px;
    border: solid 1px #d8e1e0;
    padding: 3px 0;
}

.form-group ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
}
.form-group ul li {
    line-height: 28px;
}
.form-group ul li span.lbl-tt {
    min-width: 100px;
    display: inline-block;
	font-weight: bold;
}
div#score-info .form-group {
    display: block;
    font-size: 12px;
    background: #fdfbbd;
    border: solid 2px #dc0303;
    border-radius: 5px;
}
div#score-info .form-group ul li span.lbl-tt {
    color: #02014a;
}
span.red {
    color: #f00;
    font-weight: bold;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_STUDENT_ATTENDENCE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	 <form action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
   				if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
   					if(branch_id=="" || branch_id==-1){
						alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>");
         				dijit.byId("branch_id").focus();
        				return false;
    				}
					group = dijit.byId('group').get('value');
   					if(group=="" || group==-1){
						alert("<?php echo $tr->translate("PLEASE_SELECT_GROUP");?>");
         				dijit.byId("group").focus();
        				return false;
    				}
					var rowId = $('#identity').val();
					if(rowId==''){ 
						alert("<?php echo $tr->translate('NO_RECORD_TO_SUBMIT');?>");
						return false;
					}
					loadingBlock();
   					 return true;
   				}else {
    				return false;
   				}
			</script>
			
			<div class="card-box">
	    		<div class="col-md-6 col-sm-6 col-xs-12">
	    			<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select class="fullside" readonly tabindex="15" name="branch_id"  queryExpr="*${0}*" autoComplete="false" id="branch_id" dojoType="dijit.form.FilteringSelect" onchange="getInfoBybranch();">
								<option value=""><?php echo $tr->translate("SELECT_BRANCH");?></option>
								<?php if(!empty($this->branch_id))foreach ($this->branch_id as $row){?>
								<option value="<?php echo $row['id']?>" <?php if ($this->row['branch_id']==$row['id']){ echo "selected='selected'";}?>><?php echo $row['name']?></option>
								<?php }?>
							</select>
		                </div>
		             </div>
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="group" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ATTENDANCE_DATE");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="attendence_date" constraints="{datePattern:'dd/MM/yyyy'}" name="attendence_date" type="text" value="<?php echo date('d/m/Y',strtotime($this->row['date_attendence']));?>">
		                </div>
		             </div>
		            
		             <div class="form-group">
		                <label class="control-label bold  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("FOR_SEMESTER");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="for_semester" name="for_semester" type="text">								
								<option value="1"><?php echo $tr->translate("SEMESTER1");?></option>
								<option value="2"><?php echo $tr->translate("SEMESTER2");?></option>
							</select>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SESSION_TYPE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="session_type" name="session_type" type="text">								
								<option value="1" ><?php echo $tr->translate("MORNING");?></option>
								<option value="2" ><?php echo $tr->translate("EVENING");?></option>
							</select>
		                </div>
		             </div>
		             <div class="form-group hidden">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SUBJECT");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="subject">
		                </div>
		             </div>
		         </div>
		         <div class="col-md-6 col-sm-6 col-xs-12">
		         	<div id="gr-info"></div>
		    		<div class="form-group">
		                <label class="control-label  col-md-12 col-sm-12 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
		             </div>
		             <div class="form-group">
		                <div class="col-md-12 col-sm-12 col-xs-12">
		                	<input class="fullside" dojoType="dijit.form.Textarea"  id="note" name="note"  type="text" style=" height: 70px !important;"  >
		                </div>
		             </div>
		         </div>
		     </div>
		     <div class="card-box">
	    		 <div class="col-md-12 col-sm-12 col-xs-12">
	    		 	<div class="label-info">&nbsp;</div>
	    		 </div>
	    		  <div class="col-md-12 col-sm-12 col-xs-12">
	    		  	<labal id="liststudent"></labal>
					<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
					</table>
	    		 </div>
	    	</div>
	    	<div class="clearfix"></div>
	       	<div class="card-box mt-20 ">
	      	 	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
              		 <input type="hidden" name="identity" id="identity"  value="" >
					 <input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
            	 </div>
            </div>
		</form>
    </div>
 </div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore"); 
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.Textarea");
	
	var subject_store  = getDataStorefromJSON('id','name',  <?php print_r(array())?>);
	var group_store  = getDataStorefromJSON('id','name', <?php print_r(array());?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
		    store:subject_store,
			autoComplete: false,                      
		    required: false,
		    id: "subject",
		    name: "subject",   
		    class: 'fullside',  
		    searchAttr: "name",
		    placeHolder:"Selected Subject",          
		    onChange: function() {  
		    }
		}, "subject");
		
		new dijit.form.FilteringSelect({
			store:group_store,
			autoComplete: false,                       
			required: false,               
			id: "group",
			name: "group",
			readOnly:true,    
			class: 'fullside', 
			placeHolder:"<?php echo $tr->translate("PLEASE_SELECT_GROUP");?>",
			 onChange: function() {  
				 getInfoBygroup();    
			}
		}, "group");
		getallgroupby();
		getallgroupby();
		initailize();
});
	function getallgroupby(){// 
		var url_data = '<?php echo $this->url(array('module'=>'issue','controller'=>'studentattendance','action'=>'get-allstubygroup')); ?>';
		branch_id = dijit.byId("branch_id").attr("value");
		if(branch_id==''){  
			dijit.byId("branch_id").focus();
			return false;}
		dojo.xhrPost({
			url:url_data,
			content:{
				'branch_id':branch_id,
			},
			handleAs:"json",
			load: function(data) {
				group_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('group').set('store',group_store);
			    dijit.byId('group').set('value','<?php echo $this->row['group_id'];?>');
			    document.getElementsByClassName("overlay")[0].style.display="none";	
			},
			error: function(err) {
			}
		});
	}

</script>
<script> //validate controll form 
function AllowOnlyNumbers(e) {
    e = (e) ? e : window.event;
    var key = null;
    var charsKeys = [
        97, // a  Ctrl + a Select All
        65, // A Ctrl + A Select All
        99, // c Ctrl + c Copy
        67, // C Ctrl + C Copy
        118, // v Ctrl + v paste
        86, // V Ctrl + V paste
        115, // s Ctrl + s save
        83, // S Ctrl + S save
        112, // p Ctrl + p print
        80 // P Ctrl + P print
    ];

    var specialKeys = [
	    8, // backspace
	    9, // tab
	    27, // escape
	    13, // enter
	    35, // Home & shiftKey +  #
	    36, // End & shiftKey + $
	    37, // left arrow &  shiftKey + %
	    39, //right arrow & '
	    46, // delete & .
	    109,//.
	    45 //Ins &  -
    ];

    key = e.keyCode ? e.keyCode : e.which ? e.which : e.charCode;

    // check if pressed key is not number 
    if (key && key < 48 || key > 57) {
        //Allow: Ctrl + char for action save, print, copy, ...etc
        if ((e.ctrlKey && charsKeys.indexOf(key) != -1) ||
            //Fix Issue: f1 : f12 Or Ctrl + f1 : f12, in Firefox browser
            (navigator.userAgent.indexOf("Firefox") != -1 && ((e.ctrlKey && e.keyCode && e.keyCode > 0 && key >= 112 && key <= 123) || (e.keyCode && e.keyCode > 0 && key && key >= 112 && key <= 123)))) {
            return true
        }
            // Allow: Special Keys
        else if (specialKeys.indexOf(key) != -1) {
            //Fix Issue: right arrow & Delete & ins in FireFox
            if ((key == 39 || key == 45 || key == 46 || key == 109)) {
                //return (navigator.userAgent.indexOf("Firefox") != -1 && e.keyCode != undefined && e.keyCode > 0);
                return true
            }
                //DisAllow : "#" & "$" & "%"
            else if (e.shiftKey && (key == 35 || key == 36 || key == 37)) {
                return false;
            }
            else {
                return true;
            }
        }
        else {
            return false;
        }
    }
    else {
        return true;
       }
    }
//////////////////////////////////////////////////
function getInfoBygroup(type=null){
	url_group = '<?php echo $this->url(array('module'=>'issue','controller'=>'scoreeng','action'=>'getgroupinfo'));?>';
	group = dijit.byId('group').get('value');
	if(group==''){
		alert("<?php echo $tr->translate("PLEASE_SELECT_GROUP");?>");
		dojo.byId("gr-info").innerHTML = "";
		return false;
	}
	dojo.xhrPost({
		url:url_group,	
		content:{ 
			'group_id': group,'string':1
		},
		handleAs:"json",
		load: function(data) {
			dojo.byId("gr-info").innerHTML = data;
		},
		error: function(err) {
		}
	});
	
}
var url_getSubject= '<?php echo $this->url(array('module'=>'issue','controller'=>'studentattendance','action'=>'getsubjectbygroup')); ?>';
function getSubjectByGroup(type=null){
	group_id='<?php echo $this->row['group_id'];?>';
	dojo.xhrPost({
	    url: url_getSubject,
	    content : { 
		    'group':group_id,
		},				    
	   handleAs:"json", 
	   load: function(data){
		  subject_store  = getDataStorefromJSON('id','name', data);
		  dijit.byId('subject').set('store',subject_store);  
	   },		
	    error: function(err) {
		}
	});
}

function initailize(){
	str=""; 
	var textareastyle=" font-family: 'Khmer OS Battambang'";
	<?php if (!empty($this->allstudentBygroup)) { foreach ($this->allstudentBygroup as $key=> $row){
		if($row['sex']==1){
			$gender=$tr->translate("MALE");
		}else{
			$gender=$tr->translate("FEMALE");
		}
			
		?>
			inx = parseFloat(<?php echo $key?>)+1;
			<?php if ($key<1){?>
			str+='<tr class="head-td">';
				str+='<th><?php echo $tr->translate("NUM");?></th>';
				str+='<th><?php echo $tr->translate("STUDENT_ID");?></th>';
				str+='<th><?php echo $tr->translate("STUDEN_NAME");?></th>';
				str+='<th><?php echo $tr->translate("GENDER");?></th>';
				str+='<th><?php echo $tr->translate("ATTENDANCE");?></th>';
				str+='<th><?php echo $tr->translate("SCAN_TIME");?></th>';
				str+='<th><?php echo $tr->translate("DESCRIPTION");?></th>';
			str+='</tr>';
			<?php }?>
				str+='<tr style=" background: #fff;">';
				str+='<td>'+inx+'</td>';
				str+='<td><?php echo $row['stu_code'];?></td>';
				str+='<td style="text-align: left;">&nbsp;<?php echo $row['stu_name'];?></td>';
				str+='<td><?php echo $gender;?><input type="hidden" name="student_id'+inx+'" id="student_id'+inx+'"  value="<?php echo $row['stu_id'];?>" ></td>';
				str+='<td>';
					str+='<input type="radio" <?php if (!empty($row['isCome'])){echo 'checked="checked"';}?> name="attedence'+inx+'" id="attedence'+inx+'" value="1" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("PRESENT");?></label>';
					str+='<input type="radio" <?php if (empty($row['isCome'])){echo 'checked="checked"';}?>  name="attedence'+inx+'" id="attedence'+inx+'" value="2" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("ABSENT");?></label>';
					str+='<input type="radio" <?php //if ($student_att['attendence_status']==3){echo 'checked="checked"';}?> name="attedence'+inx+'" id="attedence'+inx+'" value="3" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("PERMISSION");?></label>';
					str+='<input type="radio" <?php //if ($student_att['attendence_status']==4){echo 'checked="checked"';}?> name="attedence'+inx+'" id="attedence'+inx+'" value="4" style=" margin: 0 10px; vertical-align: middle;"/><label><?php echo $tr->translate("LATE");?></label>';
				str+='</td>';
				str+='<td><?php if (!empty($row['isCome'])){echo date("d-m-Y h:i:s",strtotime($row['scanDate']));}?><input type="hidden" name="transacan_id'+inx+'" id="transacan_id'+inx+'"  value="<?php echo $row['transcan_id'];?>" ></td>';
				str+='<td><input dojoType="dijit.form.Textarea"  class="fullside" id="comment'+inx+'" name="comment'+inx+'" type="text" value="<?php //echo str_replace("'", '', $student_att['description']); ?>" style="'+textareastyle+'"></td>';
			str+='</tr>';
		    if(inx!=1) {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+inx);
			} else {
				$('#identity').val(inx);
			}
		    document.getElementById("table_row").innerHTML = str;
	<?php }
	}else{?>
    	   $('#identity').val('');
    	   document.getElementById("table_row").innerHTML = '';
	<?php }?>
}
</script>