<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('EDIT_CATE_INCOME')); 
$frm = $this->frm_expense;
?>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
 </script>
 <div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'cateincome','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				loadingBlock();
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
	             <div class="col-sm-12 border-botom">
			    	<div class="col-sm-8 pd-0">
			    		<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_CATE_INCOME');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	        	<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-sitemap"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("CATE_INCOME");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TITLE");?> <span class="required">*</span>:
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" name="title" id="title" required="1" value="<?php echo $this->rs['category_name'];?>" dojoType="dijit.form.ValidationTextBox" class="fullside" />
									   </div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PARENT");?> :
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select name="parent" id="parent"  dojoType="dijit.form.FilteringSelect" class="fullside" >
												<option value=""></option>
												<?php if(!empty($this->parent)){foreach($this->parent as $parent){?>
												<option value="<?php echo $parent['id']?>" <?php if($parent['id']==$this->rs['parent']){echo "selected";}?>><?php echo $parent['name']?></option>
												<?php }}?>
											</select>
										</div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ACCOUNT_CODE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input type="text" name="acc_code" id="acc_code" value="<?php echo $this->rs['account_code'];?>" dojoType="dijit.form.TextBox" class="fullside" />
									   </div>
									</div>
									<div class="form-group">
										<label class="control-label custom-switch float-end "> 
											<a href="javascript:void(0);" class="switchButton status"><?php echo $tr->translate("STATUS");?></a> 
											<input type="checkbox" id="status" name="status" class="custom-switch-input"  <?php if(!empty($this->rs['status'])){ echo "checked";} ?> > 
											<span class="custom-switch-indicator custom-radius switch-status"></span> 
										</label>
									</div>
									
									<div class="clearfix"></div>
									<div class="card-box mt-20">
										<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
											<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" />
										</div>
									 </div>
								 </div>
							 </div>
						 </div>
					</div>
	             </div>
	          </div>
		</form>
	</div>
</div>
