<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_expense;
?>
<title><?php echo $tr->translate('ADD_CATE_EXPENSE');?></title>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'cateexpense','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
	             <div class="col-sm-12 border-botom">
			    	<div class="col-sm-8 pd-0">
			    		<h4 class="m-b-0"><i class="fa fa-cubes" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_CATE_EXPENSE');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	
	    	<div class="card-box">
	        	<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                  	 	<input type="text" name="title" id="title" required="1" value="" dojoType="dijit.form.ValidationTextBox" class="fullside" />
	                   </div>
	                </div>
					<div class="form-group">
					    <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PARENT");?> :
					    </label>
					    <div class="col-md-7 col-sm-7 col-xs-12">
							<select name="parent" id="parent"  dojoType="dijit.form.FilteringSelect" class="fullside" >
								<option value=""></option>
								<?php if(!empty($this->parent)){foreach($this->parent as $parent){?>
								<option value="<?php echo $parent['id']?>"><?php echo $parent['name']?></option>
								<?php }}?>
							</select>
					    </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("ACCOUNT_CODE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                  		<input type="text" name="acc_code" id="acc_code" value="" dojoType="dijit.form.TextBox" class="fullside" />
	                   </div>
	                </div>
	               
	             </div>
	          </div>
	          <div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-6 col-sm-6 col-xs-12 border-top mt-20 ptb-10 text-center">
               			<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
						<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
						<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
	</div>
</div>