<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_GRADE"));
	$baseurl = $this->baseUrl();
	$frm_items= $this->frm_items;
	$show = SHOW_IN_GRADE;
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<style>
.dijitTextArea[cols].dijitTextArea[cols]{
	width: 99%;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_GRADE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form  id='edit-major' action="<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					items_id = dijit.byId("items_id").get('value');
					if(items_id=='' || items_id==-1){
						alert("<?php echo $tr->translate("PLEASE_SELECT_DEGREE");?>");
						dijit.byId("items_id").focus();
						return false;
					}
					
					var identity = $('#identity').val();
					var arrays = identity.split(',');
					for(var i=0;i<arrays.length;i++) {
						subject_id = dijit.byId('subject_study_'+arrays[i]).get('value');
						if(subject_id == 0 || subject_id == -1){
							alert("<?php echo $tr->translate("SELECT_SUBJECT");?>");
							return false;
						}
					}
					
					loadingBlock();
               		dijit.byId("save_new").attr("disabled",true);
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
		    		<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("MAJOR_KHNAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("title");?>
		                	<input type="hidden" id="items_type" name="items_type" value="1" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("MAJOR_ENNAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("title_en");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SHORTCUT");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("shortcut");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ORDERING");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("ordering");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ONE_PAYMENT");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("is_onepayment");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DEGREE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="items_id" />
		                	<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshItems();"/>
		                </div>
		             </div>
					 <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TOTAL_SCORE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("total_score");?>
		                </div>
		             </div>
					 <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("AMOUNT_SUBJECT");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("amount_subject");?>
		                </div>
		             </div>
					 <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("MAX_AVERAGE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("max_average");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_items->getElement("note");?>
		                </div>
		             </div>
		             <div class="clearfix"></div>
			         <div class="card-box mt-20">
		               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
							<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
		               	</div>
		             </div>
		         </div>
		         <div class="col-md-6 col-sm-6 col-xs-12">
			         <div class="card-box">
							<ul class="nav  md-pills pills-primary nav-tab" role="tablist">
								<li class="nav-item active">
									<a class="nav-link " data-toggle="tab" href="#panel21" role="tab">
										<i class="fa fa-user ml-2"></i> <?php echo $tr->translate("SUBJECT_STUDY");?>
									</a>
								</li>
							</ul>
						</div>
						<div class="tab-content vertical">
						<!--Panel 1-->
							<div class="tab-pane fade in active" id="panel21" role="tabpanel">
								 <div class="card-box">
									<div class="col-md-12 col-sm-12 col-xs-12">
										<table  style="border-collapse: collapse; width:100%; border:1px solid #ccc;">
											<thead id="head-title" style="font-size: 12px;">
												<tr  class="head-td" align="right">
													<th><?php echo $tr->translate("DEL");?></th>
													<th><?php echo $tr->translate("N_O");?></th>
													<th id="lbl_titlemetion"><?php echo $tr->translate("SUBJECT_STUDY");?></th>
													<th id="lbl_titlemetion"><?php echo $tr->translate("MAXSCORE_SUBJECT");?></th>
													<th id="lbl_titlemetion"><?php echo $tr->translate("SCORE_SHORT");?></th>
													<?php if($show==1){?>
													<th id="lbl_titlemetion"><?php echo $tr->translate("MULTI_SUBJECT_MONTH");?></th>
													<th id="lbl_titlemetion"><?php echo $tr->translate("MULTI_SUBJECT_SEMESTER");?></th>
													<?php }?>
												</tr>
											</thead>
											<tbody id="table_row">
											</tbody>
										</table>
										<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
														iconClass="dijitIconEditProperty" onclick="addRow();" />
										<input type="hidden" name="identity" id="identity"  />
									</div>
								 </div>
							</div>
						</div>
				</div>
			</div>
		</form>
    </div>
</div>
<script type="text/javascript">
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.Textarea");
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require('dijit.form.NumberTextBox');
	
	var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->degree));?> );
	var subject_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->subjectlist));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
	    store: dept_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,
	    id: "items_id",
	    name: "items_id",           
	    class: "full height-text", 
	    placeHolder:"<?php echo $tr->translate("SELECT_DEGREE")?>",          
	    onChange: function() {  
	    	dept_id = dijit.byId('items_id').get('value');
	    	if(dept_id==-1){
	    		window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/degree/add?rightclick=true";?>','_blank');
		    }else{
		    	getSubjectByDegree();
			   }
	    }
		}, "items_id");		
	});

var url_dept_subject = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getsubjectbydegree')); ?>';
col = 0;no=0;
subject_opt = '<?php echo $this->subject_opt;?>';
function getSubjectByDegree(){
	dept_id = dijit.byId('items_id').get('value');
	dojo.xhrPost({
		url:url_dept_subject,
		content:{
			'dept_id':dept_id
			},
		handleAs:"json",
		load: function(data) {
			dojo.query("#table_row").append("");
			$("#identity").val("");
			no=0;
			template='';
			if(data!=""){
				//col = 0;
				for(i=0;i<data.length;i++){
					col++;no++;
					template='';
					template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
					template+='<td width="4%" align="center">'+no+'</td>';
					template+='<td width="30%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="checkSubject('+col+')" class="fullside" id="subject_study_'+col+'" name="subject_study_'+col+'">'+subject_opt+'</select></td>';
					template+='<td width="10%"><input required="true" dojoType="dijit.form.NumberTextBox" onKeyUp="calculateTotalScore();" class="fullside" name="max_score'+col+'" id="max_score'+col+'"  type="text"></td>';
					template+='<td width="10%"><input required="true" dojoType="dijit.form.NumberTextBox" onKeyUp="calculateTotalScore();" class="fullside" name="score_cut_'+col+'" id="score_cut_'+col+'"  type="text"></td>';
					<?php if($show==1){?>
					template+='<td width="15%"><input required="true" dojoType="dijit.form.NumberTextBox" value="1" class="fullside" name="amount_subject'+col+'" id="amount_subject'+col+'" value="" type="text"></td>';		
					template+='<td width="15%"><input required="true" dojoType="dijit.form.NumberTextBox" value="1" class="fullside" name="amount_subject_semester'+col+'" id="amount_subject_semester'+col+'" value="" type="text"></td>';		
					<?php }?>	
					tmp='<tr id="row'+col+'">';
					tmp+="</tr>";
					dojo.query("#table_row").append(tmp);
					if($("#identity").val()!="") {
						var identity = $("#identity").val();
						$("#identity").val(identity+','+col);
					} else {$("#identity").val(col);}
					dojo.html.set(dojo.byId("row"+col),template , {
						 parseContent: true,
					});
					dijit.byId('score_cut_'+col).attr('value',data[i].score_short);
					dijit.byId('subject_study_'+col).attr('value',data[i].subject_id);
					calculateTotalScore();
				}
			}
		},
		error: function(err) {
		}
	});
}
function addRow() {
		col++;no++;
	    template='';
		template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="4%" align="center">'+no+'</td>';
		template+='<td width="30%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="checkSubject('+col+')" class="fullside" id="subject_study_'+col+'" name="subject_study_'+col+'">'+subject_opt+'</select></td>';
		template+='<td width="10%"><input required="true" dojoType="dijit.form.NumberTextBox" class="fullside" onKeyUp="calculateTotalScore();" name="max_score'+col+'" id="max_score'+col+'"  type="text"></td>';
		template+='<td width="10%"><input required="true" dojoType="dijit.form.NumberTextBox" class="fullside" onKeyUp="calculateTotalScore();" value="0" name="score_cut_'+col+'" id="score_cut_'+col+'"  type="text"></td>';
		<?php if($show==1){?>
		template+='<td width="15%"><input required="true" dojoType="dijit.form.NumberTextBox" class="fullside" value="1" name="amount_subject'+col+'" id="amount_subject'+col+'" value="" type="text"></td>';		
		template+='<td width="15%"><input required="true" dojoType="dijit.form.NumberTextBox" class="fullside" value="1" name="amount_subject_semester'+col+'" id="amount_subject_semester'+col+'" value="" type="text"></td>';		
		<?php }?>
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	calculateTotalScore();
}
function checkSubject(index){
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	current_subject = dijit.byId('subject_study_'+index).get('value');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index){
		}else{
			old_subject = dijit.byId('subject_study_'+arrays[i]).get('value');
			if(current_subject == old_subject){
				alert("Can not add the same subject !!! ");
				deleteRecord(index);
			}
		}
	}
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
	calculateTotalScore();
	//calculateMaxAverage();
}

function calculateTotalScore(){
	var total_score=0;
	var max_score=0;
	var cut_score=0;
	var total_subject=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	if($("#identity").val()!="") {
		for(var n = 0; n < rowIDArray.length; n++) {
			score = dijit.byId('max_score'+rowIDArray[n]).get('value');
			score = isNaN(score)?0:score;
			max_score += score;
			
			score_cut = dijit.byId('score_cut_'+rowIDArray[n]).get('value');
			score_cut = isNaN(score_cut)?0:score_cut;
			cut_score += score_cut;
		}
	}
	
	total_score = max_score - cut_score;
	
	dijit.byId('amount_subject').attr('value',rowIDArray.length);
	dijit.byId('total_score').attr('value',total_score.toFixed(2));
	calculateMaxAverage();
}

function calculateMaxAverage(){
	total_score = dijit.byId('total_score').get('value');
	amount_subject = dijit.byId('amount_subject').get('value');
	max_average = total_score/amount_subject;
	dijit.byId('max_average').attr('value',max_average.toFixed(2));
}

</script>
<script type="text/javascript">
function getRefreshItems(){
	var url_getItems = '<?php echo $this->url(array("module"=>"global","controller"=>"degree","action"=>"refreshitems"));?>';										
	loadingBlock();
	dojo.xhrPost({
		url: url_getItems,
		content:{
			'items_type':1
			},
		handleAs:"json",
		load: function(data) {
			dept_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('items_id').set('store',dept_store);  
			document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
</script>