<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('GENERAL_SETTING')); 
echo $this->headTitle();
$frm = $this->frm_general;
?>
<style>
div.cke_contents.cke_reset {
    height: 200px !important;
}
</style>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

<style>

img.image_view {
    width: 100%;
	height: 100px;
}
img#image_viewbg {
    height: 50px;
}
.button_browse{
	margin-top:0 !important;
}
.button_browse span {
    padding: 0 5px;
}
tr.header {
    background: #008;
    color: #fff;
}
tr.header td {
    padding: 5px;
}
</style>
<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" >
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				loadingBlock();
				return true;
			}
			return false;
	</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
	               	<div class="col-sm-12 border-botom">
			    		<div class="col-sm-8 pd-0">
			    			<h4 class="m-b-0"><i class="fa fa-user" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('GENERAL_SETTING');?></h4>
		    			</div>
		    			<div class="col-sm-4 text-right">
		    			</div>
		    		</div>
		    	</div>
		    	<div class="card-box">
		    		<div class="col-md-6 col-sm-6 col-xs-12">
		    			<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-user" aria-hidden="true"></i>Company Info 
		                   </label>
		                </div>
		    			<div class="form-group">
		    				<div class="col-sm-4"><?php echo $tr->translate('Company Tel')?></div>
		    				<div class="col-sm-8"><?php echo $frm->getElement('branch_tel')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"><?php echo $tr->translate('Email')?></div>
		    				<div class="col-sm-8"><?php echo $frm->getElement('branch_email')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"><?php echo $tr->translate('Address')?></div>
		    				<div class="col-sm-8"><?php echo $frm->getElement('branch_add')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"><?php echo $tr->translate('Label Animation')?></div>
		    				<div class="col-sm-8"><?php echo $frm->getElement('label_animation')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"><?php echo $tr->translate('RECEIPT_PRINT')?></div>
		    				<div class="col-sm-8"><?php echo $frm->getElement('receipt_print')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"><?php echo $tr->translate('SHOW_HEADER_RECEIPT')?></div>
		    				<div class="col-sm-8"><?php echo $frm->getElement('show_header_receipt')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"><?php echo $tr->translate('Payment Amount Day Alert')?></div>
		    				<div class="col-sm-8"><?php echo $frm->getElement('payment_day_alert');?></div>
		    			</div>
		    			<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-cubes" aria-hidden="true"></i> <?php echo $tr->translate('Stock Option')?> 
		                   </label>
		                </div>
		    			<div class="form-group">
		    				<div class="col-sm-4"><?php echo $tr->translate('Transfer Stock')?></div>
		    				<div class="col-sm-8"><?php echo $frm->getElement('trasfer_st_cut');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"></div>
		    				<div class="col-sm-8"></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"></div>
		    				<div class="col-sm-8"></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"></div>
		    				<div class="col-sm-8"></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"></div>
		    				<div class="col-sm-8"></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-sm-4"></div>
		    				<div class="col-sm-8"></div>
		    			</div>
		    		</div>
		    		<div class="col-md-6 col-sm-6 col-xs-12">
		    			<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-user" aria-hidden="true"></i>Other Info 
		                   </label>
		                </div>
		    			<?php if (!empty($this->allSchoolOption)) foreach ($this->allSchoolOption as $rs){?>
		    			<div class="form-group">
		    				<div class="col-sm-4"><?php echo $rs['title']?></div>
		    				<div class="col-sm-8">
		    					<div class="col-md-6 col-sm-6 col-xs-12">
		    						<input type="radio" name="school_<?php echo $rs['id']?>" <?php if ($rs['status']==1){?> checked="checked" <?php }?> value="1"> <?php echo $tr->translate('ACTIVE')?><br>
								</div>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input type="radio" name="school_<?php echo $rs['id']?>" <?php if ($rs['status']==0){?> checked="checked" <?php }?> value="2"> <?php echo $tr->translate('DEACTIVE')?><br>
		    					</div>
		    				</div>
		    			</div>
		    			<?php }?>
		    		</div>
	    		</div>
	    		<div class="card-box">
	    			<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
						<input class="button_success" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" id="save_close" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 	
	    			</div>
	    		</div>
	  	 </div>
	</div>
</form>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.form.Textarea");
function loadImage(){
	 var output = document.getElementById('image_view');
  output.src = URL.createObjectURL(event.target.files[0]);
}

function CheckPenalty(){
	penalty_type = dijit.byId("penalty_type").get('value');
	if(penalty_type==1){
		penalty_value = dijit.byId("penalty_value").get('value');
		if(penalty_value>100){
			alert("<?php echo $tr->translate('ប្រាក់ពិន័យជាភាគរយមិនអាចលើសពី ១០០%ឡើយ');?>");
			dijit.byId('penalty_value').attr('value',100);
			return false;
		}
	}
}
</script>