<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("TRANSFER_STOCK"));
	$frm =  $this->form_search;
?>	
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-exchange " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('TRANSFER_STOCK');?></h4>
    				</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'stock','controller'=>'transfer','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("title");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                    	<?php echo $frm->getElement("start_date");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                    	<?php echo $frm->getElement("end_date");?>
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                    	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list; ?>
		</div>
	</div>
</div>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
</script> 