<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_COMMENT')); 
?>

<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="glyphicon glyphicon-comment" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_COMMENT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<form id='add_occupation' action="" method="post" dojoType="dijit.form.Form" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
  				 if(this.validate()) {
    				loadingBlock();
   					return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("COMENT_TYPE");?></p>
										</div> 
									</div>
									<div class="form-group">
										<div class="col-md-12 col-sm-12 col-xs-12"> 
											&nbsp;
										</div> 
									</div>
						
									<div class="form-group">
										<div class="col-md-4 col-sm-4 col-xs-12 text-center"> 
											<input class="form-check-input " type="radio" name="commentType" id="commentType" value="1" checked>
											<label class="form-check-label" for="exampleRadios1">
											<?php echo $tr->translate("STUDY_HABITS");?>
											</label>
										</div> 
										<div class="col-md-8 col-sm-8 col-xs-12 text-left"> 
											<input class="form-check-input" type="radio" name="commentType" id="commentType" value="2">
											<label class="form-check-label" for="exampleRadios2">
												<?php echo $tr->translate("CITIZENSHIP_AND_SOCIAL_GROWTH");?>
											</label>
										</div> 
										
									</div>
									
								</div>
							</div>
						</div>
					</div>
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-comment" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("COMMENT");?></p>
										</div> 
									</div>
									<div class="form-group">
										<label class="control-label  col-md-4 col-sm-4 col-xs-12 text-center" >
											<?php echo $tr->translate("COMMENT");?> <span class="required">*</span>
										</label>
										<div class="col-md-8 col-sm-8 col-xs-12">
											<input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="comment" name="comment" type="text">
										</div>
									</div>
									<div class="clearfix"></div>
									<div class="card-box mt-20">
										<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
											<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" />
											<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button"  />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
	            </div>
	         </div>
		</form>
	</div>
</div>
<script>
	$("input:custom-switch-input").on('click', function() {
  // in the handler, 'this' refers to the box clicked on
  var $box = $(this);
  if ($box.is(":checked")) {
  
    var group = "input:custom-switch-input[name='" + $box.attr("name") + "']";
    
    $(group).prop("checked", false);
    $box.prop("checked", true);
  } else {
    $box.prop("checked", false);
  }
});

</script>
