<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("EDIT_STUDENT_SCORE"));
	$score = $this->rows_detail;
	$student = $this->student;
	$db_score = new Foundation_Model_DbTable_DbScore();	 
?>	
<head>
  <meta charset="utf-8">
</head>
<style>
	.tdheader{font-family:'khmer os battambang' !important;}
</style>
<script type="text/javascript">
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	//dojo.require('dojox.form.BusyButton');
dojo.ready(function(){
	 getInfoBygroup();
	 getSubjectByGroup();
	var subject = [];
		var years_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->row_year));?> );
		new dijit.form.FilteringSelect({
		    store:years_store,
		    autoComplete: true,                        
		    required: true,
		    id: "year_study",
		    name: "year_study",           
		    class: 'fullside',  
		    required:'true',
		    placeHolder:"Selected Study Years",          
		    onChange: function() {  
		    	filterStudentByCondition();
		    }
		}, "year_study");
		new dijit.form.FilteringSelect({
			//store: dept_store,
			autoComplete: true,                        
			id: "grade",
			name: "grade",           
			class: 'fullside', 
			placeHolder:"Selected Grade",          
			onChange: function() {
				filterStudentByCondition();
			}
		}, "grade");
		checkExamType();
		
});
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'score','action'=>'get-grade')); ?>';
function filterGrade(){
	degree = dijit.byId('degree').get('value');
		dojo.xhrPost({
			url:url_dept,
			content:{
				'degree':degree
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);  
			    dijit.byId('grade').set('value',dijit.byId('grade_fromgrouop').get('value'));
			},
			error: function(err) {
			}
		});
}
var url_getStudent= '<?php echo $this->url(array('module'=>'foundation','controller'=>'score','action'=>'get-student')); ?>';
function filterStudent(){
	return false;
}
function gender(sex){
	if(sex==1){
		sex='<?php echo $tr->translate("MALE")?>';
	}else sex='<?php echo $tr->translate("FEMALE")?>';
	return sex;
}
var old_group = '<?php echo $this->row_g['group_id'];?>';
function filterStudentByCondition(){
	var new_group = dijit.byId('group').get('value');
	if(old_group == new_group){
		filterStudentOld();
	}else{
		filterStudent();
	}
}
function filterStudentOld(){
	num =0;
	title=0;
	temp='';
	str='';
	column = 0;
	temp+='<table class="collape tablesorter" id="table" width="100%">';
	temp+='<thead><tr><th class="tdheader" ><?php echo $tr->translate('NO');?></th>'
		+'<th class="tdheader header"><?php echo $tr->translate('STUDENT_ID');?></th>'
		+'<th class="tdheader header"><?php echo $tr->translate('STUDENT_NAME');?></th>'
		+'<th class="tdheader header"><?php echo $tr->translate('SEX');?></th>'
		 no=0;
	for(j=0;j<subject.length;j++){//loop subject
	    no++;
	 	stringsname = subject[j].subject_titleen.replace(' ','');
		temp+='<th th class="tdheader header">'+stringsname+no+'</th>';
	}
	temp+='<th class="tdheader header"><?php echo $tr->translate('NOTE');?></th>';
	temp+='</tr></thead>';	    
		<?php $old_stu = null;$i=0;
	foreach ($student as $key=>$rs){
				$i = $i+1;
		?>
		inx = '<?php echo $i; ?>';
		num++;
		temp+='<tr class="hover normal">';
		temp+='<td align="center">&nbsp;'+inx+'</td>';
		temp+='<td>&nbsp;<?php echo $rs["stu_code"] ?><input dojoType="dijit.form.TextBox" name="student_id'+inx+'" id="student_id'+inx+'"  value="'+7+'" type="hidden" ></td>';
		temp+= '<td style="min-width:170px">'+'&nbsp;<?php echo $rs["student_name"]; ?>&nbsp;<input type="hidden" name="student_id'+inx+'" id="student_id'+inx+'" value="<?php echo $rs["student_id"] ?>"/></td>';
		temp+='<td>&nbsp;'+gender(<?php echo $rs["sex"]?>)+'&nbsp;</td>';
			var no=0;
	        	<?php $j =0;
	        	if(!empty($score))foreach ($score as $rss){
	        		if($rs["student_id"]==$rss["student_id"]){
	        	?>
	        	<?php if($rss["is_parent"]== 1){ $j=$j+1;?>
	        	no = '<?php echo $j;?>';
	            stringsname = '<?php echo str_replace(' ','',$rss['subject_titleen'])?>';
	            temp+='<td><input dojoType="dijit.form.validateNumberTextBox"  name="<?php echo $rs["student_id"].'subjectid_'.$rss['subject_id'];?>'+<?php echo $i; ?>+'" id="<?php echo $rs["student_id"].'subjectid_'.$rss['subject_id'];?>'+<?php echo $i; ?>+'"   value="<?php echo $rss["score"] ?>" type="text" onkeypress="return AllowOnlyNumbers(event);"></td>';
	       	 	<?php }?>
		<?php }}?>
		temp += '<td><input dojoType="dijit.form.validateNumberTextBox" class="fullside" name="note_'+inx+'" id="note_'+inx+'"  value="<?php echo $rs["note"];?>" type="text" ></td>';
		temp+='</tr>';
			    if(inx!=1) {//identity set value 1,2,3,4,5
					var identity = $('#identity').val();
					$('#identity').val(identity+','+inx);
					} else {
						$('#identity').val(inx);
					}
			<?php } ?>
		temp+='</table>';
		dojo.byId('liststudent').innerHTML = temp;
}
</script>
<form id='office_receipt' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    return true;
   }else {
    return false;
   }
</script>
<table cellspacing="10" style="margin: 0 auto;width:100%;" >
	<tr>
		<td>
		<fieldset style="background: #fff;border: solid 1px #008;">
					<legend align="center" style="font-size: 14px;"><strong><?php echo $tr->translate("EDIT_STUDENT_SCORE");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<tr>
							<td><strong><?php echo $tr->translate("SUBJECT_TITLE");?></strong>
								<input type="hidden" name="score_id" id="score_id" value="<?php echo $this->score_id;?>"/>
							</td>
							<td>
								<input type="text" name="title" id="title" class="fullside" value="<?php echo $this->score['title_score'];?>" required="1" dojoType="dijit.form.ValidationTextBox" />
							</td>
							<td><?php echo $tr->translate("GROUP");?>*</td>
							<td>
								<select class="fullside" tabindex="15" name="group" id="group" readOnly="readOnly" dojoType="dijit.form.FilteringSelect" onchange="getSubjectByGroup(); getInfoBygroup();">
									<?php if(!empty($this->group))foreach ($this->group as $row){?>
									<option value="<?php echo $row['id']?>" <?php if ($row['id']==$this->score['group_id']){ echo "selected='selected'";}?>><?php echo $row['name']?></option>
									<?php }?>
								</select>
							</td>
							<td ><?php echo $tr->translate("STUDY_YEAR");?></td>
							<td>
								<input id="year_study" />
							</td>
						</tr>
						<tr>
							<td ><?php echo $tr->translate("DEGREE");?></td>
							<td>
								<select id="degree" name="degree" onchange="filterGrade();" class="fullside" dojoType="dijit.form.FilteringSelect" type="text"  >
									<option value="-1"> ------ select degree---------</option>
								<?php if(!empty($this->degree)){foreach ($this->degree as $degree){?>
									<option value="<?php echo $degree['id'];?>"><?php echo $degree['name'];?></option>
								<?php }}?>
								</select>
							</td>
							<td ><?php echo $tr->translate("GRADE");?></td>
							<td>
								<input id="grade" />
								 <input class="fullside" dojoType="dijit.form.TextBox"  id="grade_fromgrouop" name="grade_fromgrouop" value="" type="hidden"  >
							</td>
							<td><?php echo $tr->translate("SESSION");?></td>
							<td>
								<select id="session" name="session" onchange="filterStudentByCondition();" class="fullside" dojoType="dijit.form.FilteringSelect" type="text"  >
									<option value="-1"> ------ select session---------</option>
								<?php if(!empty($this->session)){foreach ($this->session as $session){?>
									<option value="<?php echo $session['key_code'];?>"><?php echo $session['view_name'];?></option>
								<?php }}?>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("EXAM_TYPE");?></td>
							<td>
							   <select id="exam_type" name="exam_type" class="fullside" onchange="checkExamType();"  dojoType="dijit.form.FilteringSelect" >
							   		<option value="1" <?php if($this->score['exam_type']==1){echo "selected";} ?>>ប្រចាំខែ</option>
							   		<option value="2" <?php if($this->score['exam_type']==2){echo "selected";} ?>>ប្រលងឆមាស</option>
							   </select>
							</td>
							<td style="white-space: nowrap;"><?php echo $tr->translate("FOR_MONTH");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="for_month" name="for_month" type="text">								
									<?php if(!empty($this->month)){foreach ($this->month as $month){?>
										<option value="<?php echo $month['id']?>" <?php if($month['id']==$this->score['for_month']){echo "selected='selected'";}?>><?php echo $month['month_kh']?></option>
									<?php }}?>
								</select>
							</td>
							<td><?php echo $tr->translate("FOR_SEMESTER");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="for_semester" name="for_semester" type="text">								
									<option value="1" <?php if ($this->score['for_semester']==1){ echo "Selected='selected'";}?>>ទី 1</option>
									<option value="2" <?php if ($this->score['for_semester']==2){ echo "Selected='selected'";}?>>ទី 2</option>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE");?></td>
							<td colspan="3"><textarea class="fullside"  style=" height: 60px !important;" tabindex="20" dojoType=""  id="note" name="note"  ></textarea></td>
							<td style="white-space: nowrap;"><?php echo $tr->translate("STATUS");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="status" name="status" type="text">								
										<option value="1" <?php if ($this->score['status']==1){ echo "Selected='selected'";}?>>ប្រើប្រាស់</option>
										<option value="0" <?php if ($this->score['status']==0){ echo "Selected='selected'";}?>>មិនប្រើប្រាស់</option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="8">
								<label id="liststudent"></label>
							</td>
						</tr>
					</table>
					<table class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="hidden" name="identity" id="identity"  value="" >
								 </td>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<td colspan="8" align="center">
								 	<input iconClass="dijitIconClear" type="reset" value="" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
								</td>
							</tr>
						</tfoot>
				 </table>
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script> //validate controll form 
function AllowOnlyNumbers(e) {
    e = (e) ? e : window.event;
    var key = null;
    var charsKeys = [
        97, // a  Ctrl + a Select All
        65, // A Ctrl + A Select All
        99, // c Ctrl + c Copy
        67, // C Ctrl + C Copy
        118, // v Ctrl + v paste
        86, // V Ctrl + V paste
        115, // s Ctrl + s save
        83, // S Ctrl + S save
        112, // p Ctrl + p print
        80 // P Ctrl + P print
    ];

    var specialKeys = [
	    8, // backspace
	    9, // tab
	    27, // escape
	    13, // enter
	    35, // Home & shiftKey +  #
	    36, // End & shiftKey + $
	    37, // left arrow &  shiftKey + %
	    39, //right arrow & '
	    46, // delete & .
	    109,//.
	    45 //Ins &  -
    ];

    key = e.keyCode ? e.keyCode : e.which ? e.which : e.charCode;

    // check if pressed key is not number 
    if (key && key < 48 || key > 57) {
        //Allow: Ctrl + char for action save, print, copy, ...etc
        if ((e.ctrlKey && charsKeys.indexOf(key) != -1) ||
            //Fix Issue: f1 : f12 Or Ctrl + f1 : f12, in Firefox browser
            (navigator.userAgent.indexOf("Firefox") != -1 && ((e.ctrlKey && e.keyCode && e.keyCode > 0 && key >= 112 && key <= 123) || (e.keyCode && e.keyCode > 0 && key && key >= 112 && key <= 123)))) {
            return true
        }
            // Allow: Special Keys
        else if (specialKeys.indexOf(key) != -1) {
            //Fix Issue: right arrow & Delete & ins in FireFox
            if ((key == 39 || key == 45 || key == 46 || key == 109)) {
                //return (navigator.userAgent.indexOf("Firefox") != -1 && e.keyCode != undefined && e.keyCode > 0);
                return true
            }
                //DisAllow : "#" & "$" & "%"
            else if (e.shiftKey && (key == 35 || key == 36 || key == 37)) {
                return false;
            }
            else {
                return true;
            }
        }
        else {
            return false;
        }
    }
    else {
        return true;
       }
    }
function getInfoBygroup(){
	url_group = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getgroupinfo'));?>';
	group = dijit.byId('group').get('value');
	if(group==''){
		alert("Please Select Group");
		return false;
	}
	dojo.xhrPost({
		url:url_group,	
		content:{ 
			'group_id': group
		},
		handleAs:"json",
		load: function(data) {
			dijit.byId('year_study').set('value',data.academic_year);
			dijit.byId('year_study').set('readOnly',true);
			
			dijit.byId('degree').set('value',data.degree);
			dijit.byId('degree').set('readOnly',true);
			
			dijit.byId('grade').set('value',data.grade);
			dijit.byId('grade').set('readOnly',true);
			dijit.byId('grade_fromgrouop').set('value',data.grade);
			
			dijit.byId('session').set('value',data.session);
			dijit.byId('session').set('readOnly',true);
		},
		error: function(err) {
			alert(err);
		}
	});
}
var url_getSubject= '<?php echo $this->url(array('module'=>'foundation','controller'=>'score','action'=>'get-subjectbygroup')); ?>';
function getSubjectByGroup(){
	group = dijit.byId('group').get('value');
	if(group==''){
		return false;
	}
	dojo.xhrPost({
	    url: url_getSubject,
	    content : { 
			'group':group,
		},				    
	   handleAs:"json", 
	   load: function(data) {
		   subject = data;
	   },		
	    error: function(err) {	
	    }
	});
}
function checkExamType(){
	exam_type = dijit.byId("exam_type").get("value");
	dijit.byId('for_month').set("readOnly",false);
	if(exam_type==2){
		dijit.byId('for_month').set("readOnly",true);
	}
}
</script> 