<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
	$pageTitle = $tr->translate("STUDENT_SCORE_REPORT");
	echo $this->headTitle($pageTitle);
	
	$session_lang=new Zend_Session_Namespace('lang');
	$lang_id=$session_lang->lang_id;
	
	

	$dbgb = new Application_Model_DbTable_DbGlobal();
	$month = array(
		"01"=>"មករា",
		"02"=>"កុម្ភៈ",
		"03"=>"មីនា",
		"04"=>"មេសា",
		"05"=>"ឧសភា",
		"06"=>"មិថុនា",
		"07"=>"កក្កដា",
		"08"=>"សីហា",
		"09"=>"កញ្ញា",
		"10"=>"តុលា",
		"11"=>"វិច្ឆិកា",
		"12"=>"ធ្នូ"
	);
	$monthKH = array(
		"1"=>"មករា",
		"2"=>"កុម្ភៈ",
		"3"=>"មីនា",
		"4"=>"មេសា",
		"5"=>"ឧសភា",
		"6"=>"មិថុនា",
		"7"=>"កក្កដា",
		"8"=>"សីហា",
		"9"=>"កញ្ញា",
		"10"=>"តុលា",
		"11"=>"វិច្ឆិកា",
		"12"=>"ធ្នូ"
	);
	$monthENG = array("1"=>"January","2"=>"February","3"=>"March","4"=>"April","5"=>"May","6"=>"June","7"=>"July","8"=>"August","9"=>"September","10"=>"October","11"=>"November","12"=>"December"
	);
	$template = SCORE_RESULT_TEMPLATE;
	$branchInfo = $this->branchInfo;
	
	$signature="";
	$stamp="";
	if (!empty($branchInfo['signature'])){
		if (file_exists(PUBLIC_PATH."/images/logo/".$branchInfo['signature'])){
			$signature = $this->baseUrl().'/images/logo/'.$branchInfo['signature'];
		}
	}
	if (!empty($branchInfo['stamp'])){
		if (file_exists(PUBLIC_PATH."/images/logo/".$branchInfo['stamp'])){
			$stamp = $this->baseUrl().'/images/logo/'.$branchInfo['stamp'];
		}
	}
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<?php 
	echo $this->render('externalHead.phtml');
?>
<div class="row"> 
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="card mb-1 ">
			<div class="reportblog">
				<div id="divPrint">
					<style type="text/css">
								table tr td,table tr td span{
									color:#4839bd;
								}
								.style{
									line-height: 20px; font-size: 12px;
									color:#4839bd;
									font-family: 'Times New Roman','Khmer OS Battambang';
								}
								table .header{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
								.header tr{ page-break-inside:avoid; page-break-after:auto }
								#header {
								  display: table-header-group;
								  page-break-inside:avoid; page-break-after:auto;
								}
								
								tr.cheader td {
									 white-space: nowrap;
									color: #002c7b;
									font-size: 12px;
									font-family: 'Times New Roman','Khmer OS Muol Light';
									padding: 5px 1px;
									text-align: center;
								}
								tr.cheader td span.khmerLabel,
								tr.cheader td span.englishLabel{
										color: inherit;
										 line-height: 16px;
										 padding:0;
										 margin:0;
								}
								
								.hover:hover{background: #ccc;}
								.red {
									color: #ff1a02;
								}
								.border-right-none{
									border-right: #fff solid 1px;
								}
								.border-bottom-none{
									border-bottom: #fff solid 1px;
								}
								table.content-data tr.style-rowdata {
									font-size:12px; 
									height: 23px;
								}	
								span.khmerName, span.englishName {
									line-height: 24px;
									margin: 0;
									padding: 0;
									white-space: nowrap;
									padding: 0 3px;
								}
								tr.style span.khmerName {
									font-size:12px;
								}
								tr.style span.englishName {
									font-size:11px;
								}
								span.valueAmount {
									font-weight: 600;
									color: #002c7b;
								}
								ul.scoreTitle {
									padding: 0;
									margin: 0;
									list-style: none;
									font-size: 14px;
								
								}
								ul.scoreTitle li {
									line-height: 26px;
									color:#002c7b;
									list-style-type:none !important;
									list-type:none !important;
								}
							</style>
						<table style="width:100%;background:#fff; margin: 0 auto; font-family: 'Times New Roman','Khmer OS Battambang'; ">
							<tr style="border-bottom: 1px solid #000;">
								<td colspan="3" align="center" >
									<?php echo $this->headerScore;?>
									
								</td>
							</tr>
							
							<?php 
							$i=0; 
							$count_fail=0; 
							//$count = count($subj); 
							$rs = $this->rs;
							if($rs['examType']==1){
								$monthChar = empty($monthKH[$rs['forMonth']])?"":$monthKH[$rs['forMonth']];
								$titleKh='លទ្ធផលប្រឡងប្រចាំខែ'.$monthChar;
								$monthCharEn = empty($monthENG[$rs['forMonth']])?"":$monthENG[$rs['forMonth']];
								$titleENG=$monthCharEn." TEST RESULT";
							}else{
								$arrRomanNum = array(1=>"I",2=>"II");
								$romanNumber = empty($arrRomanNum[$rs['forSemester']])?"":$arrRomanNum[$rs['forSemester']];
								$titleKh='លទ្ធផលប្រឡងប្រចាំឆមាសទី'.$dbgb->getNumberInkhmer($rs['forSemester']);
								$titleENG="SEMESTER ".$romanNumber." TEST RESULT";
							}
							?>
							<tr>
								<td align="center" style=" border-top: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
									<ul class="scoreTitle">
										<li style="font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light';">
										<?php echo $titleKh;?>
										</li>
										<li style="font-size:14px; font-family:'Times New Roman'; text-transform: uppercase;font-weight: 600;">
											<?php echo $titleENG;?>
										</li>
										<li style="font-family:'Times New Roman','Khmer OS Muol Light';">
											ថ្នាក់ទី / GRADE: <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['groupCode'];?></span>
										</li>
										<li style="font-family:'Times New Roman','Khmer OS Muol Light';">
											ឆ្នាំសិក្សា / ACADEMIC YEAR: <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['academicYear'];?></span>
										</li>
									</ul>
								</td>
								<td align="center" valign="top"></td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel" valign="top">
									<table class="header"  cellpadding="2"​ style="margin:0 auto;width:100%;border-collapse:collapse;border:4px double #5a71b5;" border="1" >
										<tr class="cheader" align="center" >
											<td>
												<span class="khmerLabel"><?php echo $tr->translate("NUM");?></span>
												<br />
												<span class="englishLabel">No</span>
											</td>
											<td >
												<span class="khmerLabel"><?php echo $tr->translate("ID_NUMBER");?></span>
												<br />
												<span class="englishLabel">ID</span>
											</td>
											<td colspan="2">
												<span class="khmerLabel"><?php echo $tr->translate("STUDENT_NAMEKHMERWORD");?>
												<br />
												<span class="englishLabel">Family and Given Name</span>
											</td>
											<td>
												<span class="khmerLabel"><?php echo $tr->translate("SEX");?>
												<br />
												<span class="englishLabel">Sex</span>
											</td>
											<?php 
												if(!empty($this->criterial)) foreach($this->criterial as $criterial){ 
											?>
											<td>
												<span class="khmerLabel"><?php echo $criterial['criterialTitle'];?>
												<br />
												<span class="englishLabel"><?php echo $criterial['criterialTitleEng'];?></span>
											</td>
											<?php } ?>
											<td>
												<span class="khmerLabel"><?php echo $tr->translate("TOTAL_SCORE");?>
												<br />
												<span class="englishLabel">Total Score</span>
											</td>
											<td>
												<span class="khmerLabel"><?php echo $tr->translate("AVERAGE");?>
												<br />
												<span class="englishLabel">Average</span>
											</td>
											<td >
												<span class="khmerLabel"><?php echo $tr->translate("RANK");?>
												<br />
												<span class="englishLabel">Rank</span>
											</td>
											<td colspan="3" >
												<span class="khmerLabel">និទ្ទេស និង​ មូលវិចារ</span>
												<br />
												<span class="englishLabel">Letter Grade & Comment</span>
											</td>
										</tr>
										<?php 
										$i=0; 
										$m=0;$f=0;
										if(!empty($this->students)) foreach($this->students as $student){ 
										$i++;
										if($student['sex']==1){ 
											$sex = $tr->translate("MALE_SHORT");$m = $m+1;
										}else{
											$sex = $tr->translate("FEMALE_SHORT");$f=$f+1;
										}
										?>
										<tr class="style style-rowdata hover context-menu-one" style="line-height: 20px;">
											<td align="center"><?php echo $i;?></td>
											<td align="center" style="white-space:nowrap;">
												<?php echo $student['stuCode'];?>
											</td>
											<td style="min-width:100px;">
												<span class="khmerName"><?php echo trim($student['stuKhName']);?></span>
											</td>
											<td style="min-width:100px;">
												<span class="englishName"><?php echo empty(trim($student['stuEnName']))?"":trim($student['stuEnName']);?></span>
											</td>
											<td align="center" class="bg_<?php echo $student['sex'];?>">&nbsp;<?php echo $sex;?>&nbsp;</td>
											
											<?php 
												if(!empty($this->criterial)) foreach($this->criterial as $criterial){ 
											?>
											<td>
												
											</td>
											<?php } ?>
											
										</tr>
										<?php } ?>
									</table>
								</td>
							</tr>
							
						</table>
						
					
				</div>
			</div>
		</div>
	</div>
</div>

<?php 
	$urlOutStanding = $this->baseUrl()."/allreport/score/certificate-letterofpraisenew/id/";
	$urlOutStandingNoPhoto = $this->baseUrl()."/allreport/score/rpt-monthly-score-student/";
?>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">

	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="letterofprais"){
					url='<?php echo $urlOutStanding;?>';
					gotoAction();
				}else if(key=="transcript"){
					url='<?php echo $urlOutStandingNoPhoto;?>';
					gotoAction1();
				}
				
			},
			items: {
				"letterofprais": {name: "<?php echo $tr->translate("HORNOR_CERTIFICATE");?>", icon: "fa-file",},
				"transcript": {name: "<?php echo $tr->translate("TRANSCRIPT");?>", icon: "fa-file",},
			}
		});
	});
	function setrowdata(id,stu_id,index,group,exam_type,for_semester,for_month){
		rank = dijit.byId('rank'+index).get("value");
		row = id;
		student_id = stu_id;
		group_id = group;
		type_exam = exam_type;
		semester = for_semester;
		month = for_month;
	}

	var recordid ='';
	function gotoAction(){
		window.open(url+row+'/stu_id/'+student_id+'/rank/'+rank);
	}
	function gotoAction1(){
		window.open(url+'stu_id/'+student_id+'/group_id/'+group_id+'/exam_type/'+type_exam+'/for_semester/'+semester+'/for_month/'+month);
	}
	
	
	

	dojo.require("dojo.data.ItemFileWriteStore");  
	var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: academic_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "study_year",
			name: "study_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				academic_year = dijit.byId('study_year').get('value');
			}
		}, "study_year");
		new dijit.form.FilteringSelect({
			store: group_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                      
		    id: "group",
		    name: "group",  
		    class: 'fullside', 
		    readonly:false,
		    required:false,
		    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
		    onChange: function() {  
		    }
		}, "group");
		
		 var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getAllAcademicByBranch();
			 getAllGroupByBranch();
	    });
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
		 <?php if (!empty($this->search['branch_id'])){?>
		 dijit.byId('branch_id').set('value','<?php echo $this->search['branch_id']?>'); 
		 <?php }?>
		 displaymonth();
	});
	url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
	var oldBranch = "<?php echo $this->search['branch_id']?>";
	function getAllAcademicByBranch(){
		dijit.byId('study_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('study_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		
		contentData = {
			'branch_id':branch_id
		}
		selectedId = '';
		if(oldBranch==branch_id){
			selectedId = '<?php echo $this->search['study_year']?>';
		}
		getAllYear(url_getacademic,contentData,selectedId);
	}
	url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getgroupbybranch'));?>';
	function getAllGroupByBranch(){
		dijit.byId('group').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('group').set('store',group_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getgroup,
			content:{
				'branch_id':branch_id,'forfilter':1
				},
			handleAs:"json",
			load: function(data) {
			    group_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('group').set('store',group_store);   
			    if(oldBranch==branch_id){
			    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
			    }
			},
			error: function(err) {
			}
		});
	}
	function displaymonth(){
		exam_type = dijit.byId('exam_type').get('value');
		if(exam_type==1){
			$("#semester").css("display", "none");
			$("#month").css("display", "block");
		}else{
			$("#semester").css("display", "block");
			$("#month").css("display", "none");
		}
	}
	
	
	
</script>

<?php 
	echo $this->render('externalFoot.phtml');
?>