<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
	$pageTitle = $tr->translate("STUDENT_SCORE_REPORT");
	echo $this->headTitle($pageTitle);
	
	$session_lang=new Zend_Session_Namespace('lang');
	$lang_id=$session_lang->lang_id;	

	$dbgb = new Application_Model_DbTable_DbGlobal();
	$month = array(
		"01"=>"មករា",
		"02"=>"កុម្ភៈ",
		"03"=>"មីនា",
		"04"=>"មេសា",
		"05"=>"ឧសភា",
		"06"=>"មិថុនា",
		"07"=>"កក្កដា",
		"08"=>"សីហា",
		"09"=>"កញ្ញា",
		"10"=>"តុលា",
		"11"=>"វិច្ឆិកា",
		"12"=>"ធ្នូ"
	);
	$monthKH = array(
		"1"=>"មករា",
		"2"=>"កុម្ភៈ",
		"3"=>"មីនា",
		"4"=>"មេសា",
		"5"=>"ឧសភា",
		"6"=>"មិថុនា",
		"7"=>"កក្កដា",
		"8"=>"សីហា",
		"9"=>"កញ្ញា",
		"10"=>"តុលា",
		"11"=>"វិច្ឆិកា",
		"12"=>"ធ្នូ"
	);
	$monthENG = array("1"=>"January","2"=>"February","3"=>"March","4"=>"April","5"=>"May","6"=>"June","7"=>"July","8"=>"August","9"=>"September","10"=>"October","11"=>"November","12"=>"December"
	);
	$template = SCORE_RESULT_TEMPLATE;
	$branchInfo = $this->branchInfo;
	
	$signature="";
	$stamp="";
	if (!empty($branchInfo['signature'])){
		if (file_exists(PUBLIC_PATH."/images/logo/".$branchInfo['signature'])){
			$signature = $this->baseUrl().'/images/logo/'.$branchInfo['signature'];
		}
	}
	if (!empty($branchInfo['stamp'])){
		if (file_exists(PUBLIC_PATH."/images/logo/".$branchInfo['stamp'])){
			$stamp = $this->baseUrl().'/images/logo/'.$branchInfo['stamp'];
		}
	}
	
	
	$dbExternal = new Application_Model_DbTable_DbExternal();
	$rs = $this->rs;
	$gradingId = $rs['id'];
	
	$mainTeacherSigature="";
	if (!empty($rs['mainTeacherSigature'])){
		if (file_exists(PUBLIC_PATH."/images/photo/".$rs['mainTeacherSigature'])){
			$mainTeacherSigature = $this->baseUrl().'/images/photo/'.$rs['mainTeacherSigature'];
		}
	}
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<?php 
	echo $this->render('externalHead.phtml');
?>
<div class="row"> 
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="card mb-1 ">
			<div class="reportblog">
				<div id="divPrint">
					<style type="text/css">
								table ,
								table tr td,
								table tr td span{
									color: #4839bd;
									font-family: 'Times New Roman','Khmer OS Battambang';
									font-size: 12px;
									line-height: 16px;
								}
								.style{
									line-height: 20px; font-size: 12px;
									color:#4839bd;
									font-family: 'Times New Roman','Khmer OS Battambang';
								}
								table .header{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
								.header tr{ page-break-inside:avoid; page-break-after:auto }
								#header {
								  display: table-header-group;
								  page-break-inside:avoid; page-break-after:auto;
								}
								
								tr.cheader td {
									white-space: nowrap;
									color: #002c7b;
									font-size: 12px;
									padding: 5px 1px;
									text-align: center;
									font-weight: 600;
								}
								tr.cheader td span.khmerLabel,
								tr.cheader td span.englishLabel{
										color: inherit;
										 line-height: 16px;
										 padding:0;
										 margin:0;
								}
								td.textLeft {
									text-align: left !important;
								}
								.red {
									color: #ff1a02;
								}
								.border-right-none{
									border-right: #fff solid 1px;
								}
								.border-bottom-none{
									border-bottom: #fff solid 1px;
								}
								table.content-data tr.style-rowdata {
									font-size:12px; 
									height: 23px;
								}	
								span.khmerName, span.englishName {
									line-height: 24px;
									margin: 0;
									padding: 0;
									white-space: nowrap;
									padding: 0 3px;
								}
								tr.style span.khmerName {
									font-size:12px;
								}
								tr.style span.englishName {
									font-size:11px;
								}
								span.valueAmount {
									font-weight: 600;
									color: #002c7b;
								}
								ul.scoreTitle {
									padding: 0;
									margin: 0;
									list-style: none;
									font-size: 14px;
								
								}
								ul.scoreTitle li {
									line-height: 26px;
									color:#002c7b;
									list-style-type:none !important;
									list-type:none !important;
								}
							</style>
						<table style="width:100%;background:#fff; margin: 0 auto; font-family: 'Times New Roman','Khmer OS Battambang'; ">
							<tr style="border-bottom: 1px solid #000;">
								<td colspan="3" align="center" >
									<?php echo $this->headerScore;?>
									
								</td>
							</tr>
							
							<?php 
							$i=0; 
							
							$countPass=0;
							$countFail=0; 
							$passFemale=0;
							$failFemale=0;
							
							
							if($rs['examType']==1){
								$monthChar = empty($monthKH[$rs['forMonth']])?"":$monthKH[$rs['forMonth']];
								$titleKh='លទ្ធផលប្រឡងប្រចាំខែ'.$monthChar;
								$monthCharEn = empty($monthENG[$rs['forMonth']])?"":$monthENG[$rs['forMonth']];
								$titleENG=$monthCharEn." TEST RESULT";
							}else{
								$arrRomanNum = array(1=>"I",2=>"II");
								$romanNumber = empty($arrRomanNum[$rs['forSemester']])?"":$arrRomanNum[$rs['forSemester']];
								$titleKh='លទ្ធផលប្រឡងប្រចាំឆមាសទី'.$dbgb->getNumberInkhmer($rs['forSemester']);
								$titleENG="SEMESTER ".$romanNumber." TEST RESULT";
							}
							?>
							<tr>
								<td align="center" style=" border-top: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
									<ul class="scoreTitle">
										<li style="font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light';">
										<?php echo $titleKh;?>
										</li>
										<li style="font-size:14px; font-family:'Times New Roman'; text-transform: uppercase;font-weight: 600;">
											<?php echo $titleENG;?>
										</li>
										<li style="font-family:'Times New Roman','Khmer OS Muol Light';">
											ថ្នាក់ទី / GRADE: <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['groupCode'];?></span>
										</li>
										<li style="font-family:'Times New Roman','Khmer OS Muol Light';">
											ឆ្នាំសិក្សា / ACADEMIC YEAR: <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['academicYear'];?></span>
										</li>
									</ul>
								</td>
								<td align="center" valign="top"></td>
							</tr>
							<tr>
								<td colspan="3" id="exportExcel" valign="top">
									<table class="header"  cellpadding="2"​ style="margin:0 auto;width:100%;border-collapse:collapse;border:4px double #5a71b5;" border="1" >
										<tr class="cheader" align="center" >
											<td>
											</td>	
											<td colspan="4">
												<?php echo $rs['subjectTitleKh']." / ".$rs['subjectTitleEng']; ?>
											</td>	
											<td class="textLeft" colspan="8">
												គ្រូបង្រៀន / Lecturer : <?php echo $rs['teaccherNameKh']." / ".$rs['teaccherNameEng']; ?>
											</td>	
										</tr>
										
										<tr class="cheader" align="center" >
											<td>
												<span class="khmerLabel">ល.រ</span>
												<br />
												<span class="englishLabel">N<sup>o</sup></span>
											</td>
											<td >
												<span class="khmerLabel">អត្តលេខ</span>
												<br />
												<span class="englishLabel">ID</span>
											</td>
											<td colspan="2">
												<span class="khmerLabel">គោត្តនាម-នាម
												<br />
												<span class="englishLabel">Student Name</span>
											</td>
											<td>
												<span class="khmerLabel"><?php echo $tr->translate("SEX");?>
												<br />
												<span class="englishLabel">Sex</span>
											</td>
											<?php 
												if(!empty($this->criterial)) foreach($this->criterial as $criterial){ 
											?>
											<td>
												<span class="khmerLabel"><?php echo $criterial['criterialTitle'];?>
												<br />
												<span class="englishLabel"><?php echo $criterial['criterialTitleEng'];?></span>
											</td>
											<?php } ?>
											
											<td>
												<span class="khmerLabel">មធ្យមភាគ	
												<br />
												<span class="englishLabel">Average</span>
											</td>
											<td >
												<span class="khmerLabel">និទ្ទេស
												<br />
												<span class="englishLabel">Grade</span>
											</td>
											<td >
												<span class="khmerLabel">ចំណាត់ថ្នាក់
												<br />
												<span class="englishLabel">Rank</span>
											</td>
											<td width="120px">
												<span class="khmerLabel">ផ្សេងៗ
												<br />
												<span class="englishLabel">Remark</span>
											</td>
											
										</tr>
										<?php 
										$i=0; 
										$m=0;$f=0;
										if(!empty($this->students)) foreach($this->students as $student){ 
										$i++;
										if($student['sex']==1){ 
											$sex = $tr->translate("MALE_SHORT");$m = $m+1;
										}else{
											$sex = $tr->translate("FEMALE_SHORT");$f=$f+1;
										}
										?>
										<tr class=" context-menu-one" style="line-height: 20px;">
											<td align="center"><?php echo $i;?></td>
											<td align="center" style="white-space:nowrap;">
												<?php echo $student['stuCode'];?>
											</td>
											<td style="min-width:100px;">
												<span class="khmerName"><?php echo trim($student['stuKhName']);?></span>
											</td>
											<td style="min-width:100px;">
												<span class="englishName"><?php echo empty(trim($student['stuEnName']))?"":trim($student['stuEnName']);?></span>
											</td>
											<td align="center" class="bg_<?php echo $student['sex'];?>"><?php echo $sex;?></td>
											<?php 
												$total_score=0;
												$remark="";
												if(!empty($this->criterial)) foreach($this->criterial as $criterial){ 
											?>
											<td align="center">
												<?php 
													
													$score = $dbExternal->getScoreByCriterial($gradingId,$student['studentId'],$criterial['exam_typeid']); 
													$point = empty($score['totalGrading'])?0:$score['totalGrading'];
													
													
													echo (float) $point;
													$total_score = $total_score + $point;
												?>
											</td>
											<?php } ?>
											
											<?php 
											$averageRow = $dbExternal->getAverageAndRankBySubjectOfCriterial($gradingId,$student['studentId']); 
											
											$remark = empty($averageRow['remark'])?"":$averageRow['remark'];
											$totalAverage = empty($averageRow['totalAverage'])?0:$averageRow['totalAverage'];
											$rank = empty($averageRow['rank'])?0:$averageRow['rank'];
											
											$passAvrage =0 ;
											if(!empty($rs['maxSubjectscore'])){
												$passAvrage = $rs['maxSubjectscore']/2;
											}
											
											if($totalAverage>=$passAvrage){
												$countPass++;
												if($student['sex']==2){
													$passFemale=$passFemale+1;
												}//Female
											}else{
												$countFail++;
												if($student['sex']==2){
													$failFemale = $failFemale+1;
												}
											}
											
											?>
											<td align="center" ><?php echo $totalAverage;?></td>
											
											<td align="center" >
												<strong>
												<?php  echo $dbgb->getMentionScore($totalAverage, $rs['academicYearId'],$rs['degreeId'],1,$rs['gradeId']);?>
												</strong>
											</td>
											<td align="center" class="red"><strong><?php echo $rank;?></strong></td>
											<td ><?php echo $remark;?></td>
											
										</tr>
										<?php } ?>
									</table>
									
									<?php 
									$totalStudent = count($this->students);
									if (!empty($this->students)){?>
									<table cellpadding="0" cellspacing="0" width="100%" style="margin-top: 10px; line-height:20px; color:#4839bd;">
										<tr>
											<td valign="top" width="33%" style="text-align: left; padding-left: 3%;">
												<span style="display: inline-block; width: 70%;"><?php echo $tr->translate("TOTAL_STUDENT");?> : </span>
												<span class="valueAmount" style=" display: inline-block; text-align: right; width: 28%;"><?php if ($i>0) {echo $dbgb->getNumberInkhmer(sprintf("%02d",$totalStudent));}else{ echo $dbgb->getNumberInkhmer(sprintf("%02d",$totalStudent));} echo " ".$tr->translate("STUDENT_UNIT");?></span>
											</td>
											<td width="33%" valign="top" ></td>
											<td width="33%" style="white-space: nowrap; " valign="top">
												<span style="display: inline-block; width: 15%;"><?php echo $tr->translate("MALE");?> :</span> 
												<span class="valueAmount" style=" display: inline-block; width: 10%; text-align: right;"><?php if ($i-$f>0) {echo $dbgb->getNumberInkhmer(sprintf("%02d",$i-$f));}else{ echo $dbgb->getNumberInkhmer(sprintf("%02d",$i-$f));} echo " ".$tr->translate("STUDENT_UNIT");?></span>
												<span style="display: inline-block; width: 15%;"></span>
												<span style="display: inline-block; width: 15%;"><?php echo $tr->translate("FEMALE");?> :</span> 
												<span class="valueAmount" style=" display: inline-block; width: 10%; text-align: right;"><?php if ($f>0) {echo $dbgb->getNumberInkhmer(sprintf("%02d",$f));}else{ echo $dbgb->getNumberInkhmer(sprintf("%02d",$f));} echo " ".$tr->translate("STUDENT_UNIT");?></span> &nbsp;
											</td>
										</tr>
										<tr>
											<td valign="top" width="33%" style="text-align: left; padding-left: 3%;">
												<span style="display: inline-block; width: 70%;">សិស្សជាប់មធ្យមភាគ  : </span>
												<span class="valueAmount" style=" display: inline-block; text-align: right; width: 28%;"><?php if ($countPass>0) {echo $dbgb->getNumberInkhmer(sprintf("%02d",$countPass));}else{ echo $dbgb->getNumberInkhmer(sprintf("%02d",$countPass));} echo " ".$tr->translate("STUDENT_UNIT");?></span>
											</td>
											<td width="33%" valign="top" ></td>
											<td width="33%" style="white-space: nowrap; " valign="top">
												<span style="display: inline-block; width: 15%;"><?php echo $tr->translate("MALE");?> :</span> 
												<span class="valueAmount" style=" display: inline-block; width: 10%; text-align: right;"><?php if ($countPass-$passFemale>0) {echo $dbgb->getNumberInkhmer(sprintf("%02d",$countPass-$passFemale));}else{ echo $dbgb->getNumberInkhmer(sprintf("%02d",$countPass-$passFemale));} echo " ".$tr->translate("STUDENT_UNIT");?></span>
												<span style="display: inline-block; width: 15%;"></span>
												<span style="display: inline-block; width: 15%;"><?php echo $tr->translate("FEMALE");?> :</span> 
												<span class="valueAmount" style=" display: inline-block; width: 10%; text-align: right;"><?php if ($passFemale>0) {echo $dbgb->getNumberInkhmer(sprintf("%02d",$passFemale));}else{ echo $dbgb->getNumberInkhmer(sprintf("%02d",$passFemale));} echo " ".$tr->translate("STUDENT_UNIT");?></span>&nbsp;
											</td>
										</tr>
										<tr>
											<td valign="top" width="33%" style="text-align: left; padding-left: 3%;">
												<span style="display: inline-block; width: 70%;">សិស្សក្រោមមធ្យមភាគ  : </span>
												<span class="valueAmount" style=" display: inline-block; text-align: right; width: 28%;"><?php if ($countFail>0) {echo $dbgb->getNumberInkhmer(sprintf("%02d",$countFail));}else{ echo $dbgb->getNumberInkhmer(sprintf("%02d",$countFail));} echo " ".$tr->translate("STUDENT_UNIT");?></span>
											</td>
											<td width="33%" valign="top" ></td>
											<td width="33%" style="white-space: nowrap;" valign="top">
												<span style="display: inline-block; width: 15%;"><?php echo $tr->translate("MALE");?> :</span> 
												<span class="valueAmount" style=" display: inline-block; width: 10%; text-align: right;"> <?php if ($countFail-$failFemale>0) {echo $dbgb->getNumberInkhmer(sprintf("%02d",$countFail-$failFemale));}else{ echo $dbgb->getNumberInkhmer(sprintf("%02d",$countFail-$failFemale));} echo " ".$tr->translate("STUDENT_UNIT");?></span>&nbsp;
												<span style="display: inline-block; width: 15%;"></span><span style="display: inline-block; width: 15%;"><?php echo $tr->translate("FEMALE");?> :</span> 
												<span class="valueAmount" style="display: inline-block; width: 10%; text-align: right;"><?php if ($failFemale>0) {echo $dbgb->getNumberInkhmer(sprintf("%02d",$failFemale));}else{ echo $dbgb->getNumberInkhmer(sprintf("%02d",$failFemale));} echo " ".$tr->translate("STUDENT_UNIT");?></span>&nbsp;
											</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr>
											<td valign="top" width="33%" style="font-family:'Khmer OS Muol Light'; text-align: center;">
												បានឃើញ និងឯកភាព<br />
											</td>
											<td width="33%" valign="top" style="font-family:'Khmer OS Battambang'; text-align: center;">បានពិនិត្យត្រឹមត្រូវ</td>
											<td width="33%" style="white-space: nowrap; font-family:'Khmer OS Battambang';" valign="top"><?php echo $branchInfo['workat'].$tr->translate("CREATE_WORK_DATE");?></td>
										</tr>
										<tr>
											<td valign="top" style="font-family:'Khmer OS Muol Light'; text-align: center;"><?php echo $branchInfo['principal'];?></td>
											<td valign="top" style="font-family:'Khmer OS Battambang'; text-align: center;">ការិយាល័យសិក្សាធិការ</td>
											<td valign="top" style=" text-align: center; font-family:'Khmer OS Battambang'; "><?php echo $tr->translate("TEACHER_ROOM");?></td>
										</tr>
										<tr>
											<td valign="top"  style="font-family:'Khmer OS Muol Light';font-size:14px;text-align: center;">
												<div>
													<?php if(!empty($stamp)){?>
													<img src="<?php echo $stamp;?>" style="max-height:100px;position:relative;" />
													<?php } ?>
												</div>
												<?php if(!empty($signature)){?>
													<img src="<?php echo $signature;?>" style="left:100px;bottom:50px;width:200px;position:relative;" />
												<?php } ?>
											</td>
											<td></td>
											<td valign="top" style="font-family:'Khmer OS Muol Light';font-size:14px;text-align: center;">
												<?php if(!empty($mainTeacherSigature)){?>
												<div><img src="<?php echo $mainTeacherSigature;?>" style="height:70px;position:relative;margin-bottom:20px;" /></div>
												<?php }else{?>
													<div style="height: 100px;"></div>
												<?php } ?>
												<span style="font-family:'Khmer OS Muol Light';font-size:14px;text-align: center;padding-left:20px;"><?php echo $rs['mainTeaccherNameKh']?></span>
											</td>
										</tr>
										<tr>
											<td valign="top" width="33%" style="font-family:'Khmer OS Muol Light';font-size:14px;text-align: center;">
											</td>
											<td width="33%" valign="top" style="font-family:'Khmer OS Battambang';font-size:14px;text-align: center;">
											</td>
											<td width="33%" style="white-space: nowrap;font-family:'Khmer os battambang'" valign="top"></td>
										</tr>
									</table>
								<?php }?>
								</td>
							</tr>
							
						</table>
						
					
				</div>
			</div>
		</div>
	</div>
</div>

<?php 
	$urlOutStanding = $this->baseUrl()."/allreport/score/certificate-letterofpraisenew/id/";
	$urlOutStandingNoPhoto = $this->baseUrl()."/allreport/score/rpt-monthly-score-student/";
?>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">

	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="letterofprais"){
					url='<?php echo $urlOutStanding;?>';
					gotoAction();
				}else if(key=="transcript"){
					url='<?php echo $urlOutStandingNoPhoto;?>';
					gotoAction1();
				}
				
			},
			items: {
				"letterofprais": {name: "<?php echo $tr->translate("HORNOR_CERTIFICATE");?>", icon: "fa-file",},
				"transcript": {name: "<?php echo $tr->translate("TRANSCRIPT");?>", icon: "fa-file",},
			}
		});
	});
	function setrowdata(id,stu_id,index,group,exam_type,for_semester,for_month){
		rank = dijit.byId('rank'+index).get("value");
		row = id;
		student_id = stu_id;
		group_id = group;
		type_exam = exam_type;
		semester = for_semester;
		month = for_month;
	}

	var recordid ='';
	function gotoAction(){
		window.open(url+row+'/stu_id/'+student_id+'/rank/'+rank);
	}
	function gotoAction1(){
		window.open(url+'stu_id/'+student_id+'/group_id/'+group_id+'/exam_type/'+type_exam+'/for_semester/'+semester+'/for_month/'+month);
	}
	
	
	
	function displaymonth(){
		exam_type = dijit.byId('exam_type').get('value');
		if(exam_type==1){
			$("#semester").css("display", "none");
			$("#month").css("display", "block");
		}else{
			$("#semester").css("display", "block");
			$("#month").css("display", "none");
		}
	}
	
	
	
</script>

<?php 
	echo $this->render('externalFoot.phtml');
?>