<title>Course Study</title>
<?php 
    $tr = Application_Form_FrmLanguages::getCurrentlanguage();
    $frm =  $this->form_search;
?>
<meta charset="utf-8">
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.ready(function(){ 
 	var dept_store= getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rows_deg));?> );
 	new dijit.form.FilteringSelect({
	     store: dept_store,
	    autoComplete: true,                        
	    id: "degree",
	    name: "degree",           
	    class: 'fullside', 
	    placeHolder:"Selected degree",          
	    onChange: function() {  
	    	 
	    }
	}, "degree");
	 dijit.byId('degree').attr('value','<?php echo $this->adv_search['degree'];?>');
	});	
</script>
 <form  action="<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
					   <table style="width:100%">
						  <tr> 
							   <td><input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->adv_search['adv_search']?>" placeholder="Search" type="text" ></td>
							   <td> <?php echo $frm->getElement("study_year");?></td>
<!-- 							   <td ><input id="degree" /></td> -->
							   <td> <?php echo $frm->getElement("degree_gep");?></td> 
							   <td> <?php echo $frm->getElement("grade_gep");?></td> 
							   <td> <?php echo $frm->getElement("sess_gep");?></td>
							   <td> <?php echo $frm->getElement("user");?></td>
					   	  </tr>
					   	  <tr>
					   	      <td> <input dojoType="dijit.form.DateTextBox" class="fullside" onchange="CalculateDate();" id="start_date" name="start_date" value="<?php echo $this->adv_search['start_date'];?>"  type="text"></td>
					           <td><input dojoType="dijit.form.DateTextBox"  class="fullside" id="end_date" name="end_date" value="<?php echo $this->adv_search['end_date'];?>" type="text"></td>
							   <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
					   	  </tr>
					   </table>
 </form>
<?php 
    echo $this->list;
?>