<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("STUDENT_IS_UNPAY")); 
	$frm =  $this->form_search;
?>	
<?php
?>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-student-not-paid')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" id="txtsearch" name="txtsearch" placeholder="<?php echo $tr->translate('SEARCH')?>" value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td> <?php echo $frm->getElement("group");?></td>
			<td> <?php echo $frm->getElement("grade_all");?></td>
			<td> <?php echo $frm->getElement("session");?></td>
		</tr>
		<tr>	
			<td> <?php echo $frm->getElement("stu_code");?></td>
			<td> <?php echo $frm->getElement("stu_name");?></td>
			<td>
				<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<div id="divPrint">
			<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;">
				
				<tr>
					<td width="15%" align="center">
						<img style="width:60%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
					</td>
					<td align="center" width="70%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_BRANCH");?></strong><br />
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("STUDENT_IS_UNPAY");?></strong>
					</td>
					<td width="15%" align="center">
						&nbsp;
					</td>
					
				</tr>
				<style>
					.hover:hover{background: #ccc;}
					table { page-break-inside:auto }
					  tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					}
				</style>
				<tr>
					<td colspan="3" id="exportExcel">
						<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<thead>
							<tr style="font-family:'Khmer MEF2';font-size:12px; height: 20px;border: 1px solid #000;background: #ccd9ff;" align="center"  >
								<th style="border: 1px solid #000;"><?php echo $tr->translate("NUM");?></th>
								<th style="border: 1px solid #000;"><?php echo $tr->translate("STUDENT_CODE");?></th>
								<th style="border: 1px solid #000;"><?php echo $tr->translate("STUDENT_NAMEKHMER");?></th>
								<th style="border: 1px solid #000;"><?php echo $tr->translate("TEL");?></th>
								<th style="border: 1px solid #000;"><?php echo $tr->translate("GROUP_CODE");?></th>
								<th style="border: 1px solid #000;"><?php echo $tr->translate("DEGREE");?></th>
								<th style="border: 1px solid #000;"><?php echo $tr->translate("GRADE");?></th>
								<th style="border: 1px solid #000;"><?php echo $tr->translate("SESSION");?></th>
							</tr>
							</thead>
						<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
						?>
							<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo $row['stu_code'];?>&nbsp;</td>
								<td style="border: 1px solid #000;text-align: left;">&nbsp;<?php echo $row['name'];?>&nbsp;</td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['tel'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['group_name'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['degree'];?></td>	
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['grade'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['session'];?></td>
 							</tr>
						<?php }}?>	 
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3">
						<table width="100%" style="font-family: 'Khmer OS Battambang';">
							<tr>
								<td align="center" width="25%">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY');?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY');?></span>
								</td>
							</tr>
						</table>
					</td>
						
				</tr>
		</table>		
	</div>		
</div>





