<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("PAYMENTHISTORY"));
?>
<style>
	.hover:hover{ background:#ccc;}
	table.content-data tr.style-head,
	table.tb-footer tr.style-head {
	   font-weight: bold !important;
	}
	.hideprintdate{display:none !important;}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
			<div class="col-sm-12 border-botom">
				<div class="col-sm-8 pd-0">
					<h4 class="m-b-0"><i class="fa fa-file"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("PAYMENTHISTORY");?></h4>
				</div>
				<div class="col-sm-4 text-right">
				</div>
			</div>
		</div>
	</div>
</div>
<div style="min-height:10cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">
	
<style>
.hover:hover{ background: #ddd;}
</style>
	<div id="divPrint" >
			<style>
				table{
					font-family:'Times New Roman','Khmer OS Battambang';
				}
				.hideprintdate{display:block;}
				tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
				table.content-data{
					border-collapse:collapse;
					width:100%;
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:12px;
					white-space: nowrap;
					margin:0 auto;
					color:#000;
					margin:0 auto;
				}
				table.content-data  tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #CCD9FF;
					text-align: center;
				}
				table.content-data tr td{
					padding: 2px;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
				.bold {
					font-weight: 600;				
				}
				span.rsNote {
				    white-space: break-spaces;
				    width: 150px;
				    line-height: 14px;
				    display: block;
				}
				@media print 
				{
				    @page {
				      margin:0.5cm;
				    }
				}
			</style>
			<table style="background:#fff; margin: 0 auto; width:100%;white-space: nowrap;" >
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr style="font-size: 12px;">
					<td width="15%" align="center">
					</td>
					<td align="center"  width="70%">
						<div style="color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("PAYMENTHISTORY"); ?></div>
					</td>
					<td width="15%">&nbsp;
					</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel" valign="top">
						<table  style="width:100%; white-space: nowrap; !important;">
							
							<tr>
								<td colspan="2" valign="top">
									<table class="content-data" align="center" border="1">
										 <?php 
										 	$total_cash = 0;$total_bank = 0;$total_cheque = 0;
										 	$total_cashexp = 0;$total_bankexp = 0;$total_chequeexp = 0;
										 	$i=0;
										 	$total_income_dollar=0;
										 	$total_expense_dollar = 0;
										 	$total_payment=0;
										 	$fine = 0;
										 	$credit_memo = 0;
										 	$net_amount = 0;
											$paid_amount = 0;
											$balance = 0;
										 if (!empty($this->row)){  
										 ?>
										  <thead>
											  <tr class="style-head" style="font-size:10px;" align="center">
											    <td><?php echo $tr->translate("N_O");?></td>
											    <td><?php echo $tr->translate("RECEIPT_NO");?></td>
											    <td><?php echo $tr->translate("STUDENT");?></td>
												<td><?php echo $tr->translate("STUDY_INFO");?></td>
												<td><?php echo $tr->translate("FINE");?></td>
												<td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
												<td><?php echo $tr->translate("Credit Memo");?></td>
												<td><?php echo $tr->translate("PAID_AMOUNT");?></td>
												<td><?php echo $tr->translate("BALANCE");?></td>
												<td><?php echo $tr->translate("PAYMENT_METHOD");?></td>
												<td><?php echo $tr->translate("PAID_DATE");?></td>
												<td><?php echo $tr->translate("NOTE");?></td>
												<td><?php echo $tr->translate("USER");?></td>
												<td><?php echo $tr->translate("STATUS");?></td>
												<td><?php echo $tr->translate("VOID_BY");?></td>
											  </tr>
										  </thead>
										 <?php foreach($this->row as $rs){ $i++;?>
										  <tr class="context-menu-one style-rowdata hover" oncontextmenu="setrowdata(<?php echo $rs['id'];?>,1);return false;" style="<?php if ($rs['is_void']==1){echo "background: #ffd9d9;"; }?> font-size:10px; height: 20px;border-bottom: 1px solid #000;"​ >
										    <td align="center"><?php echo $i;?></td>
										    <td class="bold" align="center"><?php echo $rs['receipt_number']; ?></td>
										    <td style=" white-space:nowrap; text-align:left">
										    &nbsp;
										   	 <?php 
										   	 	echo $rs['stu_code'];
										   	 	echo !empty($rs['stu_khname'])?"/".$rs['stu_khname']:"/".$rs['last_name'].$rs['stu_enname']; 
										   	 ?>
										   	 &nbsp;
										    </td>
											<td><?php 
													echo $rs['year'];
													echo empty($rs['degree'])?"":", ".$rs['degree'];
													echo empty($rs['grade'])?"":", ".$rs['grade'];
													echo empty($rs['session'])?"":", ".$rs['session'];
												?>
											</td>
											<td><?php if($rs['penalty']!=0){echo number_format($rs['penalty'],2);} ?></td>
											<td><?php echo number_format($rs['grand_total'],2); ?></td>
										    <td><?php if($rs['credit_memo']>0){echo number_format($rs['credit_memo'],2);} ?></td>
											<td><?php echo number_format($rs['paid_amount'],2); ?></td>
											<td <?php if($rs['balance_due']>0){echo"style='background:#efb6b6;'";}?>><?php echo number_format($rs['balance_due'],2); ?></td>
											<td><?php echo $rs['paymentMethod']; ?></td>
										    <td><?php echo date('d-m-Y (H:i)', strtotime($rs['create_date'])); ?></td>
										   	<td><span class="rsNote"><?php echo $rs['note']; ?></span></td>
										    <td align="center"><?php echo $rs['user_id'];?></td>
										    <td align="center" <?php if($rs['is_void']==1){echo "style='color:red;'";}?>><?php echo $rs['void_status'];?></td>
										    <td align="center"><?php echo $rs['void_by'];?></td>
										  </tr>
										  	 <?php 
										  	 	if($rs['is_void']==0){
										  	 		$total_payment = $total_payment + $rs['total_payment'];
										  	 		$fine = $fine + $rs['penalty'];
										  	 		$credit_memo = $credit_memo + $rs['credit_memo'];
									  	 			$net_amount = $net_amount + $rs['grand_total'];
													$paid_amount = $paid_amount + $rs['paid_amount'];
													$balance = $balance + $rs['balance_due'];
													
													if($rs['payment_method']==1){
														$total_cash = $total_cash+$rs['paid_amount'];
													}elseif($rs['payment_method']==2){
														$total_bank = $total_bank+$rs['paid_amount'];
													}
													else{
														$total_cheque = $total_cheque+$rs['paid_amount'];
													}
									  	 		} 
										  	 ?>
										  <?php } ?>
										  <?php } ?>
									</table>
								</td>
							</tr>
							
							
							<?php if(!empty($this->row)){?>
							<tr>
								<td colspan="2">
								<?php 
									$final_total_income = $net_amount + $fine + $total_income_dollar  - $credit_memo - $total_expense_dollar ;
								?>								
									<table width="50%" style="margin-top:5px;white-space:nowrap;font-size:13px;">
								  		<tr>
								  			<td><?php echo $tr->translate("FINE");?></td>
								  			<td><?php echo '$ '.number_format($fine,2);?></td>
								  			<td><?php echo $tr->translate("BALANCE");?></td>
								  			<td><?php echo '$ '.number_format($balance,2);?></td>
								  		</tr>
								  		<tr>
								  			<td><?php echo $tr->translate("NET_AMOUNT");?></td>
								  			<td><?php echo '$ '.number_format($total_payment,2);?></td>	
								  			<td>&nbsp;</td>
								  			<td style=" color:#F00; font-weight:bold;"></td>
								  		</tr>
								  		<tr>
								  			<td><?php echo $tr->translate("CREDIT_MEMO");?>(-)</td>
								  			<td><?php echo '$ '.number_format($credit_memo,2);?></td>
								  			<td></td>
								  			<td style=" color:#F00; font-weight:bold;"></td>
								  		</tr>
								  		<tr>
								  			<td style="font-weight:bold;"><?php echo $tr->translate("PAID_AMOUNT");?></td>
								  			<td style="color:blue; font-weight:bold;font-size: 14px;"><?php echo '$ '.number_format($paid_amount,2);?></td>
								  			<td style="font-weight:bold;"><?php echo $tr->translate("GRAND_TOTAL");?></td>
											<td colspan="7" style="border-bottom:5px double #000;color:blue; font-weight:bold;font-size: 14px;"><?php echo '$ '.number_format($final_total_income,2);?></td>
								  		</tr>
								  		<tr><td colspan="10"><br /></td></tr>
								  		<tr>
								  			<td colspan="10" style="border-bottom:1px solid #000;margin-top: 10px;"></td>
								  		</tr>
								  		<tr>
								  			<td colspan="10">
									  			<div style="width:33%;float: left;text-align: center; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';">
									  				<?php echo $tr->translate("CASH");?>&nbsp;$&nbsp; <?php echo number_format($total_cash-$total_cashexp,2);?>
									  			</div>
									  			<div style="width:33%;float: left;text-align: center;font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';">
									  				<?php echo $tr->translate("BANK");?> &nbsp;$&nbsp;<?php echo number_format($total_bank-$total_bankexp,2);?>
									  			</div>
									  			<div style="width:33%;float: left;text-align: center;font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';">
									  				<?php echo $tr->translate("CHEQUE");?>&nbsp;$&nbsp;<?php echo number_format($total_cheque-$total_chequeexp,2);?>
									  			</div>
									  		</td>
								  		</tr>
								    </table>
									<?php }?>
								</td>
							</tr>
						</table>
						<table style="width:100%;font-family: 'Times New Roman','Khmer OS Battambang'; white-space: nowrap; !important;">
							<tr>
								<td colspan="3" >
									<style type="text/css">
										body{font-family: 'Times New Roman','Khmer OS Battambang'; }
										table{ border-collapse:collapse; margin:0 auto;
										border-color:#000; }
										.padd tr td{  text-align:center}
										.padd tr th{  background-color: #e4e4e4; }
										table { page-break-inside:auto }
										tr{ page-break-inside:avoid; page-break-after:auto }
										th,td{ padding:0 1px;}
										table { page-break-inside:auto }
										tr{ page-break-inside:avoid; page-break-after:auto; }
										#header {
										  display: table-header-group;
										  page-break-inside:avoid; page-break-after:auto;
										}
									</style>
								</td>
							</tr>
							<tr>
								<td colspan="3" width="100%">
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>	
</div>

<script type="text/javascript">
	var row=0;
	var typereceipt=1;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="receipt"){
					if(typereceipt==1){//Student Payment
						url='<?php echo $this->baseUrl()."/allreport/accounting/rptreceiptdetail/id/";?>';
					}
				}
				gotoAction();
			},
			items:{
				"receipt": {name: "<?php echo $tr->translate("RECEIPT");?>", icon: "fa-money", accesskey: "c"},
			}
		});
	});
	function setrowdata(index,type){
		row = index;
		typereceipt = type;
	}
	var recordid ='';
	function gotoAction(){
		 window.open(url+row, '_blank');
	}
</script>