<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('បង្កាន់ដៃបង់ប្រាក់'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<style>
#footer{display: none;}
table tr td strong{
	padding-left: 0px;
}
.defaulheight{line-height: 22px !important;}
</style>
<div class="ptss-frame  js-ptss-frame "><!-- is-opened -->
	<div class="ptss__toggle-btn  js-ptss-toggle-btn ">
		<i class="fa fa-print"></i>
	</div>
	<div class="ptss__header"><?php echo $tr->translate("PRINT");?></div>
	<div class="ptss__settings">
		<div class="ptss__single-setting" id="ptss__layout">
			<div class="ptss__setting-control">
				<div class="ptss__layout-wrapper">
					<a class="qButton" title="<?php echo $tr->translate("Preview");?>" href="#" onclick="preview();"><i class="fa fa-search" aria-hidden="true"></i></a>
					<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrint();" ><i class="fa fa-print" aria-hidden="true"></i></a>
					<a class="qButton excel" href="#"  title="<?php echo $tr->translate("Export");?>"  onclick="exportExcel();"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a>
				</div>
			</div>
		</div>
	</div>
</div>
<div style="min-height:10cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
   		<div class="col-sm-12 border-botom">
	    	<div class="col-sm-8 pd-0">
    			<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('បង្កាន់ដៃបង់ប្រាក់');?></h4>
   			</div>
   			<div class="col-sm-4 text-right">
   			</div>
   		</div>
   	</div>
   	<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
   		<div id="divPrint">
   			<div id="divPrint1" style="width: 100%; height: 13cm ; padding: 0px; margin: 0px;">
   			<?php 
			echo $this->officailreceipt;
			?>
			</div>
			<?php if($this->data['receipt_print']>1){?>
			<div id="divPrint2" style="width: 100%;height: 13cm ; padding: 0px; margin: 0px;">
				<div style="border:2px dashed #000; vertical-align: middle;margin:0 0px 40px 0px"></div>
				<div id="printblog2"></div>
			</div>
			<?php }?>
		
			
			
		</div>	
   	</div>
</div>
    	
<script type="text/javascript">
require(["dojo/ready"], function(ready){
	 ready(function(){
		 loadingBlock();
		 printSave();
		 setTimeout(function () {
			 <?php if($this->data['receipt_print']>1){?>
			 dojo.byId('printblog2').innerHTML = dojo.byId('divPrint1').innerHTML;
			 <?php }?>
	        HideloadingBlock();
	    }, 500);
		 
	 });
});	 
function printSave(){
	symbal="$ ";
	<?php if (!empty($this->header)){?>
	$( "#header_receipt" ).append( "<?php echo preg_replace( "/\r|\n/", "",$this->header);?>" );
	<?php }?>
	var statusvoid="";
	<?php if ($this->row['status']==0){?>
		statusvoid="<?php echo preg_replace( "/\r|\n/", "", strip_tags("(Void)"));?>";
	<?php }?>
	dojo.byId("receipt_no").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['invoice'])));?>'+" "+statusvoid;
	dojo.byId("lbl_for_date").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars(date("d/M/Y",strtotime($this->row['date'])))));?>';
	dojo.byId("lbl_title_income").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['title'])));?>';
	dojo.byId("lbl_cate_income").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['cate_income'])));?>';
	dojo.byId("lbl_payment_method").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['payment_method'])));?>';
	dojo.byId("lbl_total_amount").innerHTML = symbal+'<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars(number_format($this->row['total_amount'],2))));?>';
	dojo.byId("lbl_cheqe_no").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['cheqe_no'])));?>';
	dojo.byId("lbl_description").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['description'])));?>';
	dojo.byId("user_sign").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($this->row['last_name']." ".$this->row['first_name'])));?>';
	dojo.byId("time_footer").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars(date("F j, Y, g:i a",strtotime($this->row['create_date'])))));?>';
}
										

function readMoneyInKhmer(netTotal){
	var str = netTotal.toString();
    str_cent = 'សេន';
	first_decimal = str.substr(-2);
	last_decimal = str.substr(-1);
    if(first_decimal>0){string='និង';}else{string="";str_cent=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
    first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
    last_money_decimal = read_in_khmer_from_0_to_9(last_decimal)
    money_khmer=read_money_in_khmer(netTotal);

    if(first_decimal>0){string_en='និង';}else{string_en="";str_cent_en=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
    first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
    last_money_decimal_en = read_in_english_from_0_to_9(last_decimal)
    money_english=read_money_in_english(netTotal);
    read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លារគត់'

    read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )'
    dojo.byId("lbl_moneykhmer").innerHTML = money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លារគត់'+read_eng
}

function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
function hideleft(){
	(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,fullscreen=yes, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>