<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Payment Detail'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->form_search;
?>
<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm; font-family:'Khmer OS Battambang';">
	<div id="divPrint">
		<table cellspacing="20" width="100%" style="margin: 0 auto; font-family:'Khmer OS Battambang';">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_INVICE");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table style="margin: 0 auto; width:100%;" cellspacing="10">
									<tr>
										<td width="25%"><?php echo $tr->translate("STUDENT_ID");?>/ Student ID : </td>
										<td width="25%"><?php echo $this->invoice['stu_code']; ?></td>
										<td width="25%"><?php echo $tr->translate("STUDENT_NAME");?>/ Student Name : </td>
										<td width="25%"><?php echo $this->invoice['stu_khname']; ?></td>
										
									</tr>
									<tr>
										<td width="25%"><?php echo $tr->translate("INVOICE_DATE");?> / Invoice Date : </td>
										<td width="25%"><?php echo $this->invoice['invoice_date']; ?></td>
										<td width="25%"><?php echo $tr->translate("INVOICE_NUMBER");?> /Invoice Number : </td>
										<td width="25%"><?php echo $this->invoice['invoice_num']; ?></td>
									</tr>
									<tr>
										<td width="25%"><?php echo $tr->translate("REMARK");?> : </td>
										<td width="25%"><?php echo $this->invoice['remark']; ?></td>
						
									</tr>
									
									<tr>
									    <td colspan="4">
										    <table width="100%" style="border-collapse: collapse; white-space: nowrap;border:1px solid #000;">
											    <tr style="background:#ccc;">
												    <th  style="border:1px solid #000;"><?php echo $tr->translate("N_O");?></th>
													<th  style="border:1px solid #000;"><?php echo $tr->translate("SERVICES");?></th>
													<th  style="border:1px solid #000;"><?php echo $tr->translate("AMOUNT");?></th>
													<th  style="border:1px solid #000;"><?php echo $tr->translate("START_DATE");?></th>
													<th  style="border:1px solid #000;"><?php echo $tr->translate("END_DATE");?></th>
													<th  style="border:1px solid #000;"><?php echo $tr->translate("REMARK");?></th>
												</tr>
												<?php if(!empty($this->invoice_service)){
													foreach($this->invoice_service as $key=> $row){ $key=$key+1;
												?>	
													<tr>
													    <td align="center" style="border:1px solid #000;"><?php echo $key; ?></td>
														<td style="border:1px solid #000;">&nbsp;&nbsp;<?php echo $row['title']; ?></td>
													    <td align="center" style="border:1px solid #000;">$&nbsp;<?php echo $row['amount']; ?></td>
														<td align="center" style="border:1px solid #000;"><?php echo $row['start_date']; ?></td>
														<td align="center" style="border:1px solid #000;"><?php echo $row['end_date']; ?></td>
														<td style="border:1px solid #000;"><?php echo $row['remark']; ?></td>
													</tr>
												<?php }} ?>	
												<tr>
												    <td colspan="4" style="border:1px solid #fff; border-right: 1px solid #000;"></td>
													<td align="center" style="background:#ccc; border:1px solid #000;"><?php echo $tr->translate("TOTLE_AMOUNT");?></td>
													<td align="center" style="background:#ccc; border:1px solid #000;">$&nbsp;<?php echo $this->invoice['totale_amount']; ?></td>
												</tr>
											</table>
										    </div>
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
	</table>
	</div>	
</div>

