<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Other Expense'); 
	echo $this->headTitle(''); 
	$frm=$this->form_search;
?>	
<div style="background: #fff;width: 100%;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table style="width: 100%">	
		<tr>
			<td>	
				<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td> <?php echo $frm->getElement("branch_id");?></td>
			<td> <?php echo $frm->getElement("user");?></td>
			<td><input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" class="fullside"  id="start_date" name="start_date" placeholder="Search....." value="<?php echo $this->search['start_date'];?>" type="text"></td>
			<td><input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" class="fullside"  id="end_date" name="end_date"  value="<?php echo $this->search['end_date'];?>" type="text"></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>	
</form>	
	<div id="divPrint">
	<style>
		table {page-break-inside:auto }
		      tr{ page-break-inside:avoid; page-break-after:auto; }
		      #header {
		        display: table-header-group;
		        page-break-inside:avoid; page-break-after:auto;
		      }
	</style>
		<div id="exportExcel">
			<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
				<tr>
					<td width="15%" align="center">
						<img style="width: 60%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
					</td>
					<td width="70%" align="center">
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('CUSTOMER_BRANCH');?></strong><br />
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('RPT_CATE_EXPENSE')?></strong><br />
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><?php if(!empty($this->search["start_date"])){?>For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></strong>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<style>
					table tr th{background-color: #ccc;}										
				</style>
				<tr>
					<td colspan="3" id="exportExcel">
						<table cellpadding="5"​ style="font-family:'Khmer OS Battambang';margin:0 auto;width:100%; " >
							<thead>
								<tr style="font-size:14px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center" >
									<td style="text-align: right;" colspan="2"><?php echo $tr->translate('CATE_EXPENSE')?></td>
									<td style=""></td>
									<td style=""><?php echo $tr->translate('TOTAL_EXPENSE')?></td>
								</tr>
							</thead>
						<?php $i=0;
							$total_expense = 0;
						if(!empty($this->row)){foreach ($this->row AS $row) { $i++;?>
							<tr class="hover" style="font-size:15px; height: 20px;" align="center" >
								<td style=""></td>
								<td style="text-align: right;"><?php echo $row['account_name'];?></td>
								<td style="white-space: nowrap;width:200px;">...................................................................................</td>
								<td style=""><?php echo number_format($row['total_expense'],2);?></td>
							</tr>
						<?php }}?>
							<tr>
								<td colspan="3"></td>
								<td style="border-bottom: 5px double #000;text-align: center;">$&nbsp;<strong><?php echo number_format($total_expense,2);?></strong></td>
							</tr>	
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" width="100%">
						<table width="100%" style="font-family:'Khmer OS Battambang';">
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 15px;font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 15px;text-align: right;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			</div>
	</div>		
</div>