<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	 
	$frm =  $this->form_search;
	$session = array(
			"<=12" =>'Morning',
			">12" =>'Afternoon',
	);
	 
	$arr = array();
?>	
<title>
<?php echo $tr->translate("RPT_START_DATE_ENE_DATE");?>
</title>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		
		<table width="100%" cellspacing="5">
	       <tr>
	           <td><?php echo $frm->getElement("title");?></td>
	           <td> <?php echo $frm->getElement("stuname_con");?></td>
	           <td> <?php echo $frm->getElement("term");?></td>
			   <td> <?php echo $frm->getElement("start_date");?></td>
			   <td> <?php echo $frm->getElement("end_date");?></td>
			    <td>
			   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
	       	   </td>
	       </tr>
		</table>
</form>		
</div>
	<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">	
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto;width: 100%">
								<tr>
									<td width="25%" align="left">
										<img style="width: 40%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
									</td>
									<td align="center">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><?php echo $tr->translate("RPT_START_DATE_ENE_DATE");?></strong><br />
									</td>
									<td width="25%" align="right">
									</td>
								</tr>
							<style>
								table tr th{
									border: 1px solid #000;	
								}
								.hover:hover{background: #ccc;}
								table { page-break-inside:auto }
								  tr{ page-break-inside:avoid; page-break-after:auto; }
								#header {
								  display: table-header-group;
								  page-break-inside:avoid; page-break-after:auto;
								}
								
							</style>
								<tr>
									<td colspan="3">
										<table border="1" cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;font-family: Khmer OS Battambang,Times New Roman;" >
											<thead>
											<tr style="font-size:13px; height: 20px;background: #ccc;" align="center" >
												<th >No.</th>
												<th ><?php echo $tr->translate("STUDENT_ID");?></th>
												<th ><?php echo $tr->translate("STUDENT_NAME");?></th>
												<th ><?php echo $tr->translate("PAYMENT_TERM");?></th>
												<th ><?php echo $tr->translate("START_DATE");?></th>
												<th ><?php echo $tr->translate("END_DATE");?></th>
												<th ><?php echo $tr->translate("NOTE");?></th>
												<th ><?php echo $tr->translate("USER");?></th>
												<th ><?php echo $tr->translate("STATUS");?></th>
											</tr>
											</thead>
										 <?php if(!empty($this->rs)) foreach ($this->rs As $key=>$rs){?>
											<tr class="hover" style="font-size:12px; height: 20px;" align="center" >
												<td ><?php echo $key+1;?></td>
												<td ><?php echo $rs['stu_code'];?></td>
												<td ><?php echo $rs['stu_name'];?></td>
												<td align="left">&nbsp;<?php echo $rs['term'];?></td>
												<td ><?php echo date('d-M-Y',strtotime($rs['start_date']));?></td>
												<td ><?php echo date('d-M-Y',strtotime($rs['end_date']));?></td>
												<td ><?php echo $rs['note'];?></td>
												<td ><?php echo $rs['user_name'];?></td>
												<td ><?php echo $rs['STATUS'];?></td>
											</tr>
										 <?php }?>
										</table>	
									</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr >
									<td align="center" width="25%">
										<span style="font-weight: bold;font-size: 14px;">Verified by</span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-weight: bold;font-size: 14px;text-align: right;">Prepared by</span>
									</td>
								</tr>
							</table>
		</div>		
	</div>
	
<script>
$( document ).ready(function() {
	if('<?php echo $this->search['session']?>'){
	 dijit.byId("session").set("value","<?php echo $this->search['session']?>");
	}
});

</script>