<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SERVICE_CHARGE_RPT')); 
	$frm = $this->form_search;
	$classHideHeight=classHideHeight;
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SERVICE_CHARGE_RPT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="<?php echo $tr->translate("SEARCH");?>" value="<?php echo $this->search['txtsearch'];?>" type="text">
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('branch_id')?>
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<input id="academic_year" />
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('degree_bac')?>
       		</div>
       	</div>
       	<div class="form-group">
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('grade_all')?>
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('finished_status')?>
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       	</div>
	</form>	
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto; white-space: nowrap;width: 100%">
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr>
				<td width="15%" align="center">
				</td>
				<td width="70%" align="center">
					<strong style="font-weight:normal;color:#000; font-size: 14px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate('SERVICE_CHARGE_RPT');?></strong><br />
				</td>
				<td width="15%" align="center">
				</td>
			</tr>
			<style>
				.style{
									line-height: 20px;font-size: 11px !important;
									font-family: 'Times New Roman','Khmer OS Battambang';
								}
								.hideblog{display: none;}
								.hiddenblog{display: block !important;}
								.style1:hover{ background: #ccc; }
								table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
								table.content-data { page-break-inside:auto }
								tr.content-data{ page-break-inside:avoid; page-break-after:auto; }
								#header {
								display: table-header-group;
								page-break-inside:avoid; page-break-after:auto;
								margin-top: 100px;
								}
								.hide{visibility: hidden;}
								@media print {
								div.divFooter {
									position: fixed;
									top: 0;
									width: 100%;
									height: 100px;
									bottom:0px;
									margin:0;
								}
									.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
									
								}
								.center{text-align: center !important;}
								table.content-data{
									border-collapse:collapse;
									border:1px solid #000; 
									font-size:8px;
								}
								table.content-data thead tr.style {
								line-height: 26px; font-size:10px !important; padding:1px 0px; white-space: nowrap;height: 25px; 
									background: #c1d0f3;
									font-weight:600;
								}
								table.content-data tr.style {
								 white-space: nowrap;
								
								}
								table.tb-footer{
									border-collapse:collapse;
									border:1px solid #000; 
									font-size:11px;
									font-family: 'Times New Roman','Khmer OS Battambang';
								}
								table.tb-footer tr{
								line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
								}
								table tr td{
									padding:0 2px;
								}
								tr.voidclass {
									background: #fff7f7;
								}
								td.centerText{
									text-align: center;
								}
								.redBold {
									font-weight: 600;
									color: #f80000;
								}
								@media print{
									@page{
										margin:0.3cm 0.7cm 0cm 0.7cm;
										page-break-before: avoid;
										-webkit-transform: scale(0.5);  /* Chrome, Safari 3.1+  */
										-moz-transform: scale(0.5);  /* Firefox 3.5-15 */
										-ms-transform: scale(0.5);   /* IE 9 */
										-o-transform: scale(0.5);    /* Opera 10.50-12.00 */
										transform: scale(0.5);
										page: A4;
									}
								}
				
			</style>
			<tr>
				<td colspan="3" id="exportExcel">
					<table cellpadding="2"​  class="content-data" width="100%" border="1" align="center"  >
						<thead>
							<tr class="style" align="center">
								<td scope="col"><?php echo $tr->translate('N_O')?></td>
								<td scope="col" ><?php echo $tr->translate('BRANCH')?></td>
								<td scope="col"><?php echo $tr->translate('ACADEMIC_YEAR')?></td>
								<td scope="col"><?php echo $tr->translate('SERVICE_CATE')?></td>
								<td scope="col"><?php echo $tr->translate('SERVICE_NAME')?></td>
								<td scope="col"><?php echo $tr->translate('MONTHLY')?></td>
								<td scope="col"><?php echo $tr->translate('TERM')?></td>
								<td scope="col"><?php echo $tr->translate('SEMESTER')?></td>
								<td scope="col"><?php echo $tr->translate('YEAR')?></td>
								<td scope="col"><?php echo $tr->translate('NOTE')?></td>
							</tr>
						</thead>
					<?php $i=0;if(!empty($this->rs))foreach ($this->rs AS $row) { $i++;?>
							<tr class="hover style"  align="center" >
								<td data-label="<?php echo $tr->translate("N_O");?>" ><?php echo $i;?></td>
								<td data-label="<?php echo $tr->translate("BRANCH");?>" ><?php echo @$row['branch_id'];?></td>
								<td data-label="<?php echo $tr->translate("ACADEMIC_YEAR");?>" ><?php echo @$row['academic'];?></td>
								<td data-label="<?php echo $tr->translate("SERVICE_CATE");?>" align="left" >&nbsp;&nbsp;<?php echo @$row['degree'];?></td>	
								<td data-label="<?php echo $tr->translate("SERVICE_NAME");?>" align="left" >&nbsp;&nbsp;<?php echo @$row['class'];?></td>	
								<td data-label="<?php echo $tr->translate("MONTHLY");?>" ><?php echo number_format(@$row['monthly'],2);?> $</td>
								<td data-label="<?php echo $tr->translate("TERM");?>" ><?php echo number_format(@$row['quarter'],2);?> $</td>
								<td data-label="<?php echo $tr->translate("SEMESTER");?>" ><?php echo number_format(@$row['semester'],2);?> $</td>
								<td data-label="<?php echo $tr->translate("YEAR");?>" ><?php echo number_format(@$row['year'],2);?> $</td>
								<td data-label="<?php echo $tr->translate("NOTE");?>" ><?php echo @$row['remark'];?></td>
							</tr>
					<?php }?>	
					</table>	
				</td>
			</tr>
			<tr>
				<td colspan="3" width="100%" >
					<?php echo $this->rsfooteracc;?>
				</td>
			</tr>
		</table>
	</div>	
</div>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	
	var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: academic_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "academic_year",
			name: "academic_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				
			}
		}, "academic_year");
		getAllAcademicByBranch();
		
		var branch_id = dijit.byId('branch_id');
		branch_id.on('change', function(evt) {
			getAllAcademicByBranch();
		});
	});
	
	url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
	var oldBranch = "<?php echo $this->search['branch_id']?>";
	function getAllAcademicByBranch(){
		dijit.byId('academic_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('academic_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		
		contentData = {
			'branch_id':branch_id
		}
		selectedId = '';
		if(oldBranch==branch_id){
			selectedId = '<?php echo $this->search['academic_year']?>';
		}
		getAllYear(url_getacademic,contentData,selectedId);
		
	}
</script>