<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Other Income'); 
	echo $this->headTitle(''); 
	$frm=$this->form_search;
	
	//echo 'test';exit();
	
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-other-income')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table style="width: 90%">	
		<tr>
			<td>	
				<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td> <?php echo $frm->getElement("branch_id");?></td>
			<td> <?php echo $frm->getElement("user");?></td>
			<td><input dojoType="dijit.form.DateTextBox" class="fullside"  id="start_date" name="start_date" placeholder="Search....." value="<?php echo $this->search['start_date'];?>" type="text"></td>
			<td><input dojoType="dijit.form.DateTextBox" class="fullside"  id="end_date" name="end_date"  value="<?php echo $this->search['end_date'];?>" type="text"></td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>	
</form>		
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
			<div id="divPrint">
				<div id="exportExcel">
				
									<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
										<tr >
											<td width="15%" align="center">
												<img style="width: 60%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
											</td>
											<td width="70%" align="center">
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_BRANCH");?></strong><br />
												<strong style="padding-left: 0px;font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('RPT_OTHER_INCOME')?></strong><br />
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php if(!empty($this->search['start_date'])){?>&nbsp <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> ដល់ <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></strong>     
											</td>
											<td width="15%" align="center">
											</td>
										</tr>
										
										<style>
											table tr th{background-color: #ccc;}										
										</style>
										
										<tr>
											<td colspan="3" id="exportExcel">
												<table cellpadding="5"​ style="font-family:'Khmer OS Battambang';margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;"  border="1" >
													<tr style="font-size:11px; height: 20px;border: 1px solid #000;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center" >
														<td style="border: 1px solid #000;"><?php echo $tr->translate('N_O')?></td>
														<td style="border: 1px solid #000;"><?php echo $tr->translate('INCOME_TITLE')?></td>
														<td style="border: 1px solid #000;"><?php echo $tr->translate('INVOICE_NO')?></td>
														<td style="border: 1px solid #000;"><?php echo $tr->translate('CURRENCY_TYPE')?></td>
														<td style="border: 1px solid #000;"><?php echo $tr->translate('TOTAL')?></td>
														<td style="border: 1px solid #000;"><?php echo $tr->translate('DATE')?></td>
														<td style="border: 1px solid #000;"><?php echo $tr->translate('USER')?></td>
													</tr>
												<?php $i=0; foreach ($this->row AS $row) { $i++;?>
													<tr class="hover" style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
														<td style="border: 1px solid #000;"><?php echo $i;?></td>
														<td style="border: 1px solid #000;"><?php echo $row['title'];?></td>
														<td style="border: 1px solid #000;"><?php echo $row['invoice'];?></td>
														<td align="canter" style="border: 1px solid #000;"><?php //echo $row['curr_name'];?></td>	
														<td style="border: 1px solid #000;"><?php echo $row['total_amount'];?></td>
														<td style="border: 1px solid #000;"><?php echo date('d-m-Y',strtotime($row['date']));?></td>
														<td style="border: 1px solid #000;"><?php echo $row['name'];?></td>
													</tr>
												<?php }?>	
												</table>	
											</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr >
											<td colspan="3" width="100%">
												<table width="100%" style="font-family:'Khmer OS Battambang';">
													<tr>
														<td  width="25%" align="center">
															<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
														</td>
														<td  width="50%">
															&nbsp;
														</td>
														<td align="center"  width="25%">
															<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
														</td>
													</tr>
												</table>
											</td>
										</tr>
									</table>
					</div>
			</div>		
</div>










