<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('RPT_DISCOUNT_SETTING')); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->form_search;
	$str="";
?>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_DISCOUNT_SETTING');?></h4>
    		</div>
    		<div class="col-sm-4 text-right"></div>
    	</div>
    </div>
	<form id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
			<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement("title");?>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement("branch_id");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
            		<input id="studentId" />
            	</div>
            	<div class="col-md-2 col-sm-2 col-xs-12">
            		<input id="discountId" />
            	</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('status_search');?>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</div>
		</div>
	</form>
<style>
	#footer{display: none;}
	
	.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
	.hiddenblog{display: block !important;}
			
</style>	
	<div id="divPrint">
		<style type="text/css">

			.style{
				line-height: 20px;font-size: 11px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			.hideblog{display: none;}
			.hiddenblog{display: block !important;}
			.style1:hover{ background: #ccc; }
			table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
			table.content-data { page-break-inside:auto }
			tr.content-data{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			display: table-header-group;
			page-break-inside:avoid; page-break-after:auto;
			margin-top: 100px;
			}
			.hide{visibility: hidden;}
			@media print {
			div.divFooter {
				position: fixed;
				top: 0;
				width: 100%;
				height: 100px;
				bottom:0px;
				margin:0;
			}
				.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
				
			}
			.center{text-align: center !important;}
			table.content-data{
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:8px;
			}
			table.content-data thead tr.style {
			line-height: 25px; font-size:10px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #c1d0f3;
				font-weight:600;
			}
			  tr.style {
			 white-space: nowrap;
			}
		
			table.tb-footer{
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:11px;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			table.tb-footer tr{
			line-height: 14px; font-size:11px; padding:2px 0px; height: 20px;
			}
			table tr td{
				padding:0 2px;
			}
			tr.voidclass {
				background: #fff7f7;
			}
			td.centerText{
				text-align: center;
			}
			.redBold {
				font-weight: 600;
			}
/*
			.styleth{
				font-size:12px; 
				height: 20px;
				background-color: #ccd9ff;
				line-height: 30px;
				font-weight: bold;

			}
			.styletr{
				font-size:12px;
				height: 20px;

			}
			

			th,td{ padding:0 1px;}
			table{ border-collapse:collapse; margin:0 auto;
			border-color:#000; }
			.padd tr td{ text-align:left}
			tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
			*/
			</style>
		<form action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'submitlist')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">	
			<table width="100%">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="25%" align="left">
					</td>
					<td align="center" width="50%">
						<strong style="font-weight:normal;font-family: Arial Black;color:#000; font-size: 14px;font-family:'khmer os muol light';"><?php echo $tr->translate('RPT_DISCOUNT_SETTING');?></strong><br >
						<span style="color:#000; font-size: 13px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php if(!empty($this->search['start_date'])){?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> <?php echo $tr->translate('TO')?> <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></span>
					</td>
					<td align="right" width="25%">&nbsp;</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr> 
					<td colspan="3" id="exportExcel" >
						
						<table class="content-data" width="100%" border="1" align="center" >
							  <thead>
								  <tr class="style" align="center">
								    <td scope="col">&nbsp;<?php echo $tr->translate('N_O');?>&nbsp;</td>
								    <td scope="col">&nbsp;<?php echo $tr->translate('BRANCH');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('DISCOUNT_OPTION');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('STUDENT_NAME');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('TYPE');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('COURSE_SERVICE_PRODUCT');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('DISCOUNT_TYPE');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('DIS_MAX');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('START_DATE');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('END_DATE');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('BY_USER');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('STATUS');?>&nbsp;</td>
								  </tr>
							  </thead>
							 <?php 
							 	if(!empty($this->row)){foreach($this->row as $key=>$rs){
							 ?>
							  <tr class="hover style" align="left" >
								    <td data-label="<?php echo $tr->translate("N_O");?>"  style="text-align: center;"><?php echo $key+1;?></td>
								    <td data-label="<?php echo $tr->translate("BRANCH");?>" ><?php echo $rs['branch']; ?></td>
								    <td data-label="<?php echo $tr->translate("DISCOUNT_OPTION");?>" > <?php echo $rs['discountOption']; ?></td>
								    <td data-label="<?php echo $tr->translate("STUDENT_NAME");?>" ><?php echo $rs['studentName']; ?></td>
								    <td data-label="<?php echo $tr->translate("TYPE");?>" ><?php echo $rs['itemType']; ?></td>
								    <td data-label="<?php echo $tr->translate("COURSE_SERVICE_PRODUCT");?>" ><?php echo $rs['itemDetail']; ?></td>
								    <td data-label="<?php echo $tr->translate("DISCOUNT_TYPE");?>" ><?php echo $rs['disc_name']; ?></td>
								    <td data-label="<?php echo $tr->translate("DIS_MAX");?>" ><?php echo $rs['DisValueType']; ?></td>
								    <td data-label="<?php echo $tr->translate("START_DATE");?>" ><?php echo $rs['start_date']; ?></td>
								    <td data-label="<?php echo $tr->translate("END_DATE");?>" ><?php echo $rs['end_date']; ?></td>
								    <td data-label="<?php echo $tr->translate("BY_USER");?>" ><?php echo $rs['user_name']; ?></td>
								    <td data-label="<?php echo $tr->translate("STATUS");?>" ><?php echo $rs['status']; ?></td>
							  </tr>
							  <?php }} ?>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3" width="100%">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
			</table>
		</form>
	</div>	
</div>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
var disname_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->discount));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		required: false,  
		autoComplete: false,
		queryExpr: "*${0}*",                      
	    id: "studentId",
	    name: "studentId",  
	    tabindex: "1",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME")?>", 
	    
	}, "studentId");

	new dijit.form.FilteringSelect({
		store: disname_store,
		required: false,   
		autoComplete: false,
		queryExpr: "*${0}*",  
		id: "discountId",
		name: "discountId", 
		value:"<?php echo $this->adv_search['discountId'];?>",          
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_DISCOUNT");?>",          
		onChange: function() {  
		}
	}, "discountId");

	branchId = dijit.byId('branch_id');
	branchId.on('change',function(evt){
		branchId = dijit.byId('branch_id').get('value');
		if(branchId==''){
			dijit.byId("branch_id").focus();
			return false;
		}
		getAllstudentBranch();
		
	});

	getAllstudentBranch();
});

function getAllstudentBranch(){
	dijit.byId("studentId").reset();
	branchId = dijit.byId('branch_id').get('value');
	if(branchId==''){
		 dijit.byId('branch_id').focus();
		 return false;
	}
	
	var urlGet = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getliststudenturl')); ?>';
	
	contentData = {
			'branchId':branchId,
			'customerType':1
			}
	selectedId='<?php echo $this->adv_search['studentId'];?>';
	getAllStudentByBranch(urlGet,contentData,selectedId);
}
</script>