<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_CATE_EXPENSE')); 
	$frm=$this->form_search;
?>	
<div style="background: #fff;width: 100%;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_CATE_EXPENSE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="<?php echo $tr->translate("SEARCH");?>....." value="<?php echo $this->search['txtsearch'];?>" type="text">
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("branch_id");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("user");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" class="fullside"  id="start_date" name="start_date" placeholder="<?php echo $tr->translate("SEARCH");?>....." value="<?php echo $this->search['start_date'];?>" type="text">
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" class="fullside"  id="end_date" name="end_date"  value="<?php echo $this->search['end_date'];?>" type="text">
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       	</div>
	</form>	
	<div id="divPrint">
		<style>
			table {page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				  #header {
					display: table-header-group;
					page-break-inside:avoid; page-break-after:auto;
				  }
		</style>
		<div id="exportExcel">
			<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="15%" align="center">
					</td>
					<td width="70%" align="center">
						<strong style="color:#000; font-size: 18px;font-family:Times New Roman,'Khmer MEF2';"><?php echo $tr->translate('RPT_CATE_EXPENSE')?></strong><br />
						<strong style="color:#000; font-size: 13px;font-family:Times New Roman,'Khmer MEF2';"><?php if(!empty($this->search["start_date"])){?>For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></strong>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<style>
					table tr th{background-color: #ccc;}	
					tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }									
				</style>
				<tr>
					<td colspan="3" id="exportExcel">
						<table cellpadding="5"​ style="font-family:Times New Roman,'Khmer OS Battambang';margin:0 auto;width:100%; " >
							<thead>
								<tr style="font-size:14px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center" >
									<td style="text-align: right;" colspan="2"><?php echo $tr->translate('CATE_EXPENSE')?></td>
									<td style=""></td>
									<td align="left" style=""><?php echo $tr->translate('TOTAL_EXPENSE')?></td>
								</tr>
							</thead>
						<?php $i=0;
							$total_expense = 0;
						if(!empty($this->row)){foreach ($this->row AS $row) { $i++;?>
							<tr class="hover" style="font-size:15px; height: 20px;" align="center" >
								<td style=""></td>
								<td style="text-align: right;"><?php echo $row['account_name'];?></td>
								<td style="white-space: nowrap;width:200px;">...................................................................................</td>
								<td align="left" style="">&nbsp;&nbsp;<?php echo number_format($row['total_expense'],2);?></td>
							</tr>
							<?php $total_expense = $total_expense + $row['total_expense'];?>
						<?php }}?>
							<tr>
								<td colspan="3"></td>
								<td align="left" >
									<strong style="border-bottom: 5px double #000;font-size:17px">$&nbsp;<?php echo number_format($total_expense,2);?></strong>
								</td>
							</tr>	
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">
						<br />
						<br />
						<table width="100%" style="font-size:12px;color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Battambang';">
							<tr style="text-align: center;">
								<td width="30%">បានឃើញនិង ឯកភាព</td>
								<td width="30%">បានពិនិត្យ</td>
								<td width="30%">ភ្នំពេញ, ថ្ងៃទី……ខែ……ឆ្នាំ………	</td>
							</tr>
							<tr style="text-align: center;">
								<td width="30%" style="font-size: 16px;font-family:'Times New Roman','Khmer OS Muol Light'">លោកអគ្គនាយក</td>
								<td width="30%">ប្រធានគណនេយ្យ</td>
								<td width="30%">បេឡាករ</td>
							</tr>
						</table>
					</td>	
				</tr>
			</table>
		</div>
	</div>		
</div>