<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("STUDENT_PAYMENT_RECEIPT"));
	$frm =  $this->form_search;
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
.hideprintdate{display:none !important;}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div style="min-height:10cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("STUDENT_PAYMENT_RECEIPT");?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>	
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input dojoType="dijit.form.TextBox" class="fullside" id="adv_search" name="adv_search" value="<?php echo $this->search['adv_search']?>" placeholder="<?php echo $tr->translate("SEARCH");?>" type="text" >
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("branch_id");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input id="stu_name" />
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("degree");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
				<input id="grade_all" />
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("session");?>
       		</div>
       	</div>
       	<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("user");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("start_date");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("end_date");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       	</div>
       	<div class="form-group">
       		<div class="col-md-12 col-sm-12 col-xs-12">
       		</div>
       	</div>
		<table width="100%" style="margin: 0px; font-family:'khmer os battambang';">
			<tr>
				<td colspan="5">
					<div style="margin: 10px 0px;">
						<input type="checkBox" style="margin-left: 1%;" dojoType="dijit.form.CheckBox" value="all" id="all_payment" name="all_payment"  <?php if(!empty($this->search['all_payment'])){if($this->search['all_payment']=="all"){echo "checked='checked'";}}?> /><?php echo $tr->translate("RPT_ALLPAYMENTREPORT");?>
						<input type="checkBox" style="margin-left: 3%;" dojoType="dijit.form.CheckBox" value="1" id="student_payment" name="student_payment"  <?php if(!empty($this->search['student_payment'])){if($this->search['student_payment']==1){echo "checked='checked'";}}?>/><?php echo $tr->translate("STUDENT_PAYMENT_INCOME");?>
						<input type="checkBox" style="margin-left: 3%;" dojoType="dijit.form.CheckBox" value="3" id="income" name="income"  <?php if(!empty($this->search['income'])){if($this->search['income']==3){echo "checked='checked'";}}?> /> <?php echo $tr->translate("OTHER_INCOME");?>
						<input type="checkBox" style="margin-left: 3%;" dojoType="dijit.form.CheckBox" value="4" id="expense" name="expense"  <?php if(!empty($this->search['expense'])){if($this->search['expense']==4){echo "checked='checked'";}}?> /><?php echo $tr->translate("OTHER_EXPENSE");?>
					</div>
				</td>
			</tr>
		</table>
	</form>
<style>
.hover:hover{ background: #ddd;}
</style>
	<div id="divPrint" >
			<style>
				table{
					font-family:'Times New Roman','Khmer OS Battambang';
				}
				.hideprintdate{display:block;}
				tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
				table.content-data{
					border-collapse:collapse;
					width:100%;
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:12px;
					white-space: nowrap;
					margin:0 auto;
					color:#000;
					margin:0 auto;
				}
				table.content-data  tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #CCD9FF;
					text-align: center;
				}
				table.content-data tr td{
					padding: 2px;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}
			</style>
			<table style="background:#fff; margin: 0 auto; width:100%;white-space: nowrap;" >
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr style="font-size: 12px;">
					<td width="15%" align="center">
					</td>
					<td align="center"  width="70%">
						<div style="color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("STUDENT_PAYMENT_RECEIPT"); ?></div>
						<?php if(!empty($this->search["start_date"])){?><span style="color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';line-height: 22px;"><?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></span><?php }?>
					</td>
					<td width="15%">&nbsp;
						<label class='hideprintdate'>Print Date <?php echo date("d-m-Y h:i");?></label>
					</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel" valign="top">
						<table  style="width:100%; white-space: nowrap; !important;">
							<?php if (!empty($this->row)){  ?>
							<tr>
								<td colspan="2"><?php echo $tr->translate("STUDENT_PAYMENT_INCOME");?></td>
							</tr>
							<?php }?>
							<tr>
								<td colspan="2" valign="top">
									<table class="content-data" align="center">
										 <?php 
										 	$i=0;
										 	$total_income_dollar=0;
										 	$total_expense_dollar = 0;
										 	$total_payment=0;
										 	$fine = 0;
										 	$credit_memo = 0;
										 	$net_amount = 0;
											$paid_amount = 0;
											$balance = 0;
										 if (!empty($this->row)){  
										 ?>
										  <thead>
											  <tr class="style-head" style="font-size:10px;" align="center">
											    <td><?php echo $tr->translate("N_O"); ?></td>
											    <td><?php echo $tr->translate("RECEIPT_NO"); ?></td>
											    <td><?php echo $tr->translate("STUDENT_ID"); ?></td>
												<td><?php echo $tr->translate("STUDENT_NAME"); ?></td>
												<td><?php echo $tr->translate("TYPE"); ?></td>
												<td><?php echo $tr->translate("DEGREE"); ?></td>
												<td><?php echo $tr->translate("GRADE"); ?></td>
												<td><?php echo $tr->translate("SESSION"); ?></td>
												<td><?php echo $tr->translate("FINE"); ?></td>
												<td><?php echo $tr->translate("TOTAL_PAYMENT"); ?></td>
												<td><?php echo $tr->translate("Credit Memo"); ?></td>
												<td><?php echo $tr->translate("PAID_AMOUNT"); ?></td>
												<td><?php echo $tr->translate("BALANCE"); ?></td>
												<td><?php echo $tr->translate("CREATE_DATE"); ?></td>
												<td><?php echo $tr->translate("NOTE"); ?></td>
												<td><?php echo $tr->translate("USER"); ?></td>
												<td><?php echo $tr->translate("STATUS"); ?></td>
												<td><?php echo $tr->translate("VOID_BY"); ?></td>
											  </tr>
										  </thead>
										 <?php foreach($this->row as $rs){ $i++;?>
										  <tr style="font-size:10px; height: 20px;border-bottom: 1px solid #000;"​ class="style-rowdata hover">
										    <td <?php if($rs['is_void']==1){echo "style='color:red;'";}?>><?php echo $i;?></td>
										    <td><?php echo $rs['receipt_number']; ?></td>
										    <td><?php echo $rs['stu_code']; ?></td>
										    <td style=" white-space:nowrap; text-align:left">&nbsp;<a style="color: #000;" target="_blank" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptreceiptdetail','id'=>$rs['id']))?>"><?php echo !empty($rs['stu_khname'])?$rs['stu_khname']:$rs['stu_enname']; ?></a></td>
											<td><?php echo $rs['type']; ?></td>
											<td><?php echo $rs['degree']; ?></td>
											<td><?php echo $rs['grade']; ?></td>
											<td><?php echo $rs['session']; ?></td>
											<td><?php if($rs['penalty']>0){echo number_format($rs['penalty'],2);} ?></td>
											<td><?php echo number_format($rs['grand_total'],2); ?></td>
										    <td><?php if($rs['credit_memo']>0){echo number_format($rs['credit_memo'],2);} ?></td>
											<td><?php echo number_format($rs['paid_amount'],2); ?></td>
											<td <?php if($rs['balance_due']>0){echo"style='background:#efb6b6;'";}?>><?php echo number_format($rs['balance_due'],2); ?></td>
										    <td><?php echo date('d-m-Y (H:i)', strtotime($rs['create_date'])); ?></td>
										   	<td><?php echo $rs['note']; ?></td>
										    <td><?php echo $rs['user_id'];?></td>
										    <td <?php if($rs['is_void']==1){echo "style='color:red;'";}?>><?php echo $rs['void_status'];?></td>
										    <td><?php echo $rs['void_by'];?></td>
										  </tr>
										  	 <?php 
										  	 	if($rs['is_void']==0){
										  	 		$total_payment = $total_payment + $rs['total_payment'];
										  	 		$fine = $fine + $rs['penalty'];
										  	 		$credit_memo = $credit_memo + $rs['credit_memo'];
									  	 			$net_amount = $net_amount + $rs['grand_total'];
													$paid_amount = $paid_amount + $rs['paid_amount'];
													$balance = $balance + $rs['balance_due'];
									  	 		} 
										  	 ?>
										  <?php } ?>
										  <?php } ?>
									</table>
								</td>
							</tr>
							<?php if(!empty($this->income)){?>
							<tr>
								<td colspan="2"><span style="font-size: 12px;"><?php echo $tr->translate("OTHER_INCOME");?></span> </td>
							</tr>
							<tr>
								<td colspan="2">
									<table class="content-data" align="center">
										<tr class="style-head" style="font-size:10px;" align="center">
											<td><?php echo $tr->translate('N_O')?></td>
											<td><?php echo $tr->translate('TITLE')?></td>
											<td><?php echo $tr->translate('INVOICE_NO')?></td>
											<td><?php echo $tr->translate('INCOME_CATEGORY')?></td>
											<td><?php echo $tr->translate('PAYMENT_METHOD')?></td>
											<td><?php echo $tr->translate('TOTAL')?></td>
											<td><?php echo $tr->translate('FOR_DATE')?></td>
											<td><?php echo $tr->translate('USER')?></td>
										</tr>
										<style> td{padding:0 3px; }</style>
									<?php $i=0;foreach($this->income as $row){ $i++;?>
										<tr class="style-rowdata hover" style="font-size:10px; height: 20px;border-bottom: 1px solid #000;" align="center" >
											<td><?php echo $i;?></td>
											<td style="text-align: left;"><?php echo $row['title'];?></td>
											<td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('module'=>'registrar','controller'=>'allreports','action'=>'reprint-other-income','id'=>$row['id']));?>" target="blank"><?php echo $row['invoice'];?></a></td>
											<td><?php echo $row['income_category'];?></td>
											<td align="center" ><?php echo $row['payment_method'];?></td>	
											<td><?php echo number_format($row['total_amount'],2);?></td>
											<td><?php echo date('d-M-Y',strtotime($row['date']));?></td>
											<td><?php echo $row['name'];?></td>
										</tr>
											<?php 
												$total_income_dollar = $total_income_dollar + $row['total_amount'];
											?> 
										 <?php } ?>
									</table>
								</td>
							</tr>
							<?php }?>
							<?php if(!empty($this->expense)){?>
							<tr>
								<td  colspan="2"><span style="font-size: 12px;"><?php echo $tr->translate("OTHER_EXPENSE");?></span></td>
							</tr>
							<tr>
								<td colspan="2">
									<table class="content-data" width="100%" align="center" >
										<tr class="style-head" style="font-size:10px;" align="center">
											<td><?php echo $tr->translate('N_O')?></td>
											<td><?php echo $tr->translate('TITLE')?></td>
											<td><?php echo $tr->translate('INVOICE_NO')?></td>
											<td><?php echo $tr->translate('PAYMENT_METHOD')?></td>
											<td><?php echo $tr->translate('TOTAL')?></td>
											<td><?php echo $tr->translate('FOR_DATE')?></td>
											<td><?php echo $tr->translate('USER')?></td>
										</tr>
										 <style>td{padding:0 3px; }</style>
										<?php $i=0;$total_expense_dollar=0;foreach($this->expense as $row){ $i++;?>
										<tr class="style-rowdata hover" style="font-size:10px; height: 20px;border-bottom: 1px solid #000;" align="center" >
											<td><?php echo $i;?></td>
											<td style=" text-align: left;">&nbsp;<a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-income-expense-detail','id'=>$row['id']));?>" target="blank"><?php echo $row['title']; ?></a></td>
											<td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-income-expense-detail','id'=>$row['id']));?>" target="blank"><?php echo $row['invoice']; ?></a></td>
											<td align="center"><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-income-expense-detail','id'=>$row['id']));?>" target="blank"><?php echo $row['payment_type']; ?></a></td>	
											<td><?php echo number_format($row['total_amount'],2);?></td>
											<td><?php echo date('d-M-Y',strtotime($row['date']));?></td>
											<td><?php echo $row['name'];?></td>
										</tr>
										<?php 
											$total_expense_dollar = $total_expense_dollar + $row['total_amount'];
										?> 
									 <?php } ?>
									</table>
								</td>
							</tr>
							<?php }?>
							<?php if(!empty($this->row) || !empty($this->income) || !empty($this->expense)){?>
							<tr>
								<td colspan="2">
								<?php 
									$final_total_income = $net_amount + $fine + $total_income_dollar  - $credit_memo - $total_expense_dollar ;
								?>								
									<table width="50%" style="margin-top:5px;white-space:nowrap;font-size:13px;">
								  		<tr>
								  			<td><?php echo $tr->translate("FINE");?></td>
								  			<td><?php echo '$ '.number_format($fine,2);?></td>
								  			<td><?php echo $tr->translate("BALANCE");?></td>
								  			<td><?php echo '$ '.number_format($balance,2);?></td>
								  		</tr>
								  		<tr>
								  			<td><?php echo $tr->translate("NET_AMOUNT");?></td>
								  			<td><?php echo '$ '.number_format($total_payment,2);?></td>	
								  			<td><?php echo $tr->translate("OTHER_INCOME"); ?>&nbsp;</td>
								  			<td style=" color:#F00; font-weight:bold;"><?php echo '$ '.number_format($total_income_dollar,2);?></td>
								  		</tr>
								  		<tr>
								  			<td><?php echo $tr->translate("CREDIT_MEMO");?>(-)</td>
								  			<td><?php echo '$ '.number_format($credit_memo,2);?></td>
								  			<td><?php echo $tr->translate("OTHER_EXPENSE"); ?>&nbsp;</td>
								  			<td style=" color:#F00; font-weight:bold;"><?php echo '$ '.number_format($total_expense_dollar,2);?></td>
								  		</tr>
								  		<tr>
								  			<td><?php echo $tr->translate("PAID_AMOUNT");?></td>
								  			<td><?php echo '$ '.number_format($paid_amount,2);?></td>
								  			<td><?php echo $tr->translate("GRAND_TOTAL");?></td>
											<td colspan="7" style="border-bottom:5px double #000;color:blue; font-weight:bold;font-size: 14px;"><?php echo '$ '.number_format($final_total_income,2);?></td>
								  		</tr>
								    </table>
									<?php }?>
								</td>
							</tr>
						</table>
						<table style="width:100%;font-family: 'Times New Roman','Khmer OS Battambang'; white-space: nowrap; !important;">
							<tr>
								<td colspan="3" >
									<style type="text/css">
										body{font-family: 'Times New Roman','Khmer OS Battambang'; }
										table{ border-collapse:collapse; margin:0 auto;
										border-color:#000; }
										.padd tr td{  text-align:center}
										.padd tr th{  background-color: #e4e4e4; }
										table { page-break-inside:auto }
										tr{ page-break-inside:avoid; page-break-after:auto }
										th,td{ padding:0 1px;}
										table { page-break-inside:auto }
										tr{ page-break-inside:avoid; page-break-after:auto; }
										#header {
										  display: table-header-group;
										  page-break-inside:avoid; page-break-after:auto;
										}
									</style>
								</td>
							</tr>
							<tr>
								<td colspan="3" width="100%">
									<?php echo $this->rsfooteracc;?>
								</td>
							</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>	
</div>
<div class="ptss-frame  js-ptss-frame "><!-- is-opened -->
	<div class="ptss__toggle-btn  js-ptss-toggle-btn ">
		<i class="fa fa-print"></i>
	</div>
	<div class="ptss__header"><?php echo $tr->translate("PRINT");?></div>
	<div class="ptss__settings">
		<div class="ptss__single-setting" id="ptss__layout">
			<div class="ptss__setting-control">
				<div class="ptss__layout-wrapper">
					<a class="qButton" title="<?php echo $tr->translate("Preview");?>" href="#" onclick="preview();"><i class="fa fa-search" aria-hidden="true"></i></a>
					<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrint();" ><i class="fa fa-print" aria-hidden="true"></i></a>
					<a class="qButton excel" href="#"  title="<?php echo $tr->translate("Export");?>"  onclick="exportExcel();"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore"); 
	dojo.require("dijit.form.CheckBox"); 
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade_all",
			name: "grade_all",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
			}
		}, "grade_all");

		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "stu_name",
			name: "stu_name",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
			onChange: function() {  
			}
		}, "stu_name");

		getallGrade();
		getAllAcademicByBranch();
	});
	
	var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade_all').set('store',grade_store);   
				dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
			},
			error: function(err) {
			}
		});
	}
	
	var url_data = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getallstudent')); ?>';
	function getAllAcademicByBranch(){
		branch_id = dijit.byId("branch_id").attr("value");
		if(branch_id==''){  
				dijit.byId("branch_id").focus();
				return false;
		}
		dojo.xhrPost({
			url:url_data,
			content:{
				'branch_id':branch_id
			},
			handleAs:"json",
			load: function(data) {
				student_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('stu_name').set('store',student_store); 
			    dijit.byId('stu_name').attr('value','<?php echo $this->search['stu_name']?>');    
			},
			error: function(err) {
			}
		});
	}
</script>