<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_OTHER_INCOME_EXPENSE')); 
	$frm=$this->form_search;
?>
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>	
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_OTHER_INCOME_EXPENSE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>	
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-expense')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="<?php echo $tr->translate("SEARCH");?>....." value="<?php echo $this->search['txtsearch'];?>" type="text">
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("branch_id");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("start_date");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("end_date");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       	</div>
	</form>		
	<div id="divPrint">
			<style>
				table {page-break-inside:auto; font-family:'Times New Roman','Khmer OS Battambang';}
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}	
				#exportExcel th{text-align: center;}
				tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
				table.content-data{
						border-collapse:collapse;
						width:100%;
						border:1px solid #000; 
						font-family:'Times New Roman','Khmer OS Battambang';
						font-size:13px;
						white-space: nowrap;
						margin:0 auto;
						color:#000;
						margin:0 auto;
					}
					table.content-data  tr.style-head {
					   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #CCD9FF;
						text-align: center;
					}
					table.content-data tr td{
						padding: 2px;
					}
					table.content-data tr.style-rowdata {
						font-size:12px; 
						height: 23px;
					}
			</style>
			<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="15%" align="center">
					</td>
					<td width="70%" align="center">
					    <span style="color:#000; font-size: 16px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate('RPT_OTHER_INCOME_EXPENSE')?></span><br />
						<span style="color:#000; font-size: 13px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php if(!empty($this->search['start_date'])){?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> <?php echo $tr->translate('TO')?> <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></span>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
						<table class="content-data" cellpadding="5"​ border="1" >
							<thead>
							<tr class="style-head" align="center">
								<td><?php echo $tr->translate('N_O')?></td>
								<td><?php echo $tr->translate('BRANCH')?></td>
								<td><?php echo $tr->translate('RECEIVER')?></td>
								<td><?php echo $tr->translate('EXPENSE_TITLE')?></td>
								<td><?php echo $tr->translate('INVOICE_NO')?></td>
								<td><?php echo $tr->translate('PAYMENT_METHOD')?></td>
								<td><?php echo $tr->translate('TOTAL')?></td>
								<td><?php echo $tr->translate('DESCRIPTION')?></td>
								<td><?php echo $tr->translate('FOR_DATE')?></td>
								<td><?php echo $tr->translate('USER')?></td>
							</tr>
							</thead>
							<?php 
								$total_expense = 0;
							if(!empty($this->row)){foreach ($this->row AS $key=>$row) { $key=$key+1;
								$total_expense =$total_expense+$row['total_amount'];
							?>
							<tr class="style-rowdata hover" align="center" >
								<td><?php echo $key;?></td>
								<td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'accounting','action'=>'rpt-income-expense-detail','id'=>$row['id']));?>" target="blank"><?php echo $row['branch_name']; ?></a></td>
								<td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'accounting','action'=>'rpt-income-expense-detail','id'=>$row['id']));?>" target="blank"><?php echo $row['receiver']; ?></a></td>
								<td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'accounting','action'=>'rpt-income-expense-detail','id'=>$row['id']));?>" target="blank"><?php echo $row['title']; ?></a></td>
								<td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'accounting','action'=>'rpt-income-expense-detail','id'=>$row['id']));?>" target="blank"><?php echo $row['invoice']; ?></a></td>
								<td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'accounting','action'=>'rpt-income-expense-detail','id'=>$row['id']));?>" target="blank"><?php echo $row['pay']; ?></a></td>
								<td><?php echo '$ '.$row['total_amount'];?></td>
								<td><?php echo $row['description'];?></td>
								<td><?php echo date('d-M-Y',strtotime($row['date']));?></td>
								<td><?php echo $row['first_name'];?></td>
							</tr>	
							<?php }}?>
							<tr style="border-left: 1px solid #fff; border-bottom: 1px solid #fff; border-right: 1px solid #fff;">
								<td colspan="10" align="right"><?php echo $tr->translate("TOTAL_EXPENSE");?> <strong> $&nbsp;&nbsp;<?php echo number_format($total_expense,2);?></strong></td>
							</tr>	
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3" width="100%">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
		</table>
	</div>		
</div>