<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Suspend Service'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm=$this->form_search;
?>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-suspendservice')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table style="width: 100%;font-family:'khmer os battambang'">
		<tr>
			<td><?php echo $frm->getElement('title')?></td>
			<td align="left"><?php echo $frm->getElement('study_year')?></td>
			<td><?php echo $frm->getElement('service_type')?></td>
			<td><?php echo $frm->getElement('service')?></td>
			<td><?php echo $frm->getElement('degree')?></td>
		</tr>
		<tr>
			<td><?php echo $frm->getElement('grade_all')?></td>
			<td><?php echo $frm->getElement('start_date')?></td>
			<td><?php echo $frm->getElement('end_date')?></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>	
</form>
<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm;">
							<tr>
								<td width="15%" align="center">
									<img style="width: 60%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
								</td>
								<td align="center" width="70%">
									<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('CUSTOMER_BRANCH');?></strong><br />
									<strong style=" padding-left: 20px;font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('STUDENT_STOP_SERVICE_REPORT');?></strong>
									<div><strong​​ style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php if(!empty($this->search['start_date'])){?><?php echo date('d-M-Y',strtotime($this->search['start_date']));?><?php echo $tr->translate('TO');?><?php echo date('d-M-Y',strtotime($this->search['end_date']));}?></strong></div>
								</td>
								<td width="15%" align="center">
								</td>
							</tr>
							<tr>
								<style> th,td{ padding:0 1px;}</style>
								<style type="text/css">
										body{font-family: "Times New Roman",Arial; }
										table{ border-collapse:collapse; margin:0 auto;
										border-color:#000; }
										.padd tr td{  }
										.padd tr th{  background-color: #ccc; }
										table {page-break-inside:auto }
										tr{ page-break-inside:avoid; page-break-after:auto; }
										#header {
										  display: table-header-group;
										  page-break-inside:avoid; page-break-after:auto;
										}	
								</style>
								<td colspan="3" id="exporteExcel">
									<table class="padd" width="99%" border="1" align="center" style="font-size:14px;white-space:nowrap;font-family: 'khmer os battambang',Arial,serif !important;">
												<style> td{padding:0 3px; }</style>
										  <?php
											$student_id =0;
										 	 $i=0; $total=0;if (!empty($this->rs)){ foreach($this->rs as $rs){ $i++;
										 	 if($rs['stu_id']!=$student_id){
										  ?><thead>
										  <tr style="border-left: 1px solid #fff; border-right: 1px solid #fff; border-top: 1px solid #fff;"><td colspan="8">&nbsp;</td></tr>
										  <tr style="font-size:10px; height: 23px; border-left: 1px solid #fff; border-right: 1px solid #fff; border-top: 1px solid #fff; "​>
										  	<td align="left" colspan="8">
										  		<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 12px;font-family:'Hanuman',Arial,serif !important;"><?php echo $tr->translate('STUDENT_ID').' : '.$rs['stu_code'] .' &nbsp;'.$tr->translate('STUDENT_NAME').' : '.$rs['en_name'].' &nbsp; '.$tr->translate('SEX').' : '.$rs['sex'].' &nbsp; '.$tr->translate('ACADEMIC_YEAR').' : '.$rs['academic'];?></strong><br />
										  	</td>
										  </tr>				  
										   <tr style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center">
										    <td>&nbsp;<?php echo $tr->translate('N_O')?>&nbsp;</td>
										    <td>&nbsp;<?php echo $tr->translate('SERVICE_TYPE')?>&nbsp;</td>
										    <td>&nbsp;<?php echo $tr->translate('SERVICE_NAME')?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('SUSPEND_TYPE')?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('REASON')?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('NOTE')?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('STOP_DATE')?>&nbsp;</td>
										  </tr>
										  <thead>
										 <?php  }
										 $student_id=$rs['stu_id'];
										 	 
										 ?>
										   <tr class="hover" style="font-size:11px; height: 18px; border-bottom: 1px solid #000;"​ align="center">
										  	<td><?php echo $i;?></td>
										   	<td><?php echo $rs['service_type']; ?></td>
										   	<td><?php echo $rs['service']; ?></td>
										  	<td><?php echo $rs['type_suspend']; ?></td>
										   	<td><?php echo $rs['reason']; ?></td>
										   	<td><?php echo $rs['note']; ?></td>
										   	<td><?php echo date("d/m/Y",strtotime($rs['define_date'])); ?></td>
										   </tr>
										  <?php } }?>
									</table>
								</td>
							</tr>
						<tr>
							<td colspan="3">&nbsp;</td>
						</tr>
						<tr>
							<td colspan="3">&nbsp;</td>
						</tr>
						<tr >
							<td colspan="3" width="100%">
								<table width="100%" style="font-family: 'Khmer OS Battambang';">
									<tr>
										<td  width="25%" align="center">
											<span style=" font-size: 14px;font-size: 13px;font-family:'Khmer MEF2';"><?php echo $tr->translate('VERIFIED_BY')?></span>
										</td>
										<td  width="50%">
											&nbsp;
										</td>
										<td align="center"  width="25%">
											<span style="font-size: 13px;font-family:'Khmer MEF2';font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
										</td>
									</tr>
								</table>
							</td>
						</tr>
				</table>
		</div>
</div>

