<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_PAYMENT_HISTORY_REPORT'));
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->form_search;
?>
<div style="min-height:10cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("STUDENT_PAYMENT_HISTORY_REPORT");?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
    <form id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("title");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("branch_id");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<input id="study_year" />
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<input id="group" />
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("degree");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<input id="grade_all" />
        	</div>
        </div>
	   <div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("session");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("service_type");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<select required="false" type="text" name="item" id="item" placeHolder="<?php echo $tr->translate('SELECT_CATEGORY');?>" class="fullside" dojoType="dijit.form.FilteringSelect"  autoComplete="false" queryExpr="*${0}*" onchange="getgradebyDegree();" >
					<option value="-1"><?php echo $tr->translate('SELECT_CATEGORY');?></option>
					<?php if(!empty($this->rs_type)){foreach ($this->rs_type as $rs){?>
					<option value="<?php echo $rs['id']?>"><?php echo $rs['name']?></option>
					<?php }}?>
                </select>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php //echo $frm->getElement("service");?>
        		<input id="service" name="service" />
        	</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("pay_term");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("user");?>
        	</div>
        	
        </div>
        <div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("start_date");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("end_date");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
        </div>
	</form>
	<style>
		#footer{display: none;}
	</style>
	<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding:0cm;font-family:'Khmer OS Battambang'; " >
				<tr>
					<td width="15%" align="center">
						<img style="width:60%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td  align="center" width="70%">
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate('CUSTOMER_BRANCH');?></strong><br />
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate('STUDENT_PAYMENT_HISTORY_REPORT');?></strong><br />
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search["start_date"]))?><?php echo $tr->translate('TO');?><?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></strong>             
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
						<style>
						table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
						tr{ page-break-inside:avoid; page-break-after:auto }
						.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap; font-size: 14px;}
						#header {
						  display: table-header-group;
						  page-break-inside:avoid; page-break-after:auto;
						}
					.hover:hover{background:#eee;}										
					</style>
						<?php 
							$total=0;
							$total_balance = 0;
							$total_receive = 0;
							
							$fine=0;
							$credit_memo=0;
							$deduct=0;
							$net_amount=0;
						?>	
						<table class="padd" width="100%" border="1" align="center" style="border:1px solid #000;border-collapse:collapse;white-space:nowrap;font-family: 'Khmer OS Battambang';">
							  <thead>
								  <tr style="text-align:center;background-color:  #ccd9ff;line-height: 30px;font-weight: bold;font-size:12px; height: 20px; align="center" >
								    <th><?php echo $tr->translate('N_O');?></th>
								    <th><?php echo $tr->translate('STUDENT_ID');?></th>
									<th><?php echo $tr->translate('STUDENT_NAME');?></th>
									<th><?php echo $tr->translate('SERVICE_CATE');?></th>
									<th><?php echo $tr->translate('SERVICE_NAME');?></th>
									<th><?php echo $tr->translate('PAID_DATE');?></th>
									<th><?php echo $tr->translate('RECEIPT_NO');?></th>
									<th><?php echo $tr->translate('PAYMENT_TERM');?></th>
									<th><?php echo $tr->translate('QTY');?></th>
									<th><?php echo $tr->translate('PRICE');?></th>
									<th><?php echo $tr->translate('LATE_FEE');?></th>
									<th><?php echo $tr->translate('EXTRA_FEE');?></th>
									<th><?php echo $tr->translate('DISCOUND');?></th>
									<th><?php echo $tr->translate('DISCOUNT');?></th>
									<th><?php echo $tr->translate('PAID_AMOUNT');?></th>
									<th><?php echo $tr->translate('START_DATE');?></th>
									<th><?php echo $tr->translate('END_DATE');?></th>
									<th><?php echo $tr->translate('REMARK');?></th>
									<th><?php echo $tr->translate('STATUS');?></th>
									<th><?php echo $tr->translate('USER');?></th>
								  </tr>
							 </thead>
							<style> 
								td{padding:0 2px; }
								.hover:hover{background: #ccc;}
							</style>
							  <?php $i=0;
							 	    $total=0;
							  		$student_id='';
							  if(!empty($this->row)){foreach($this->row as $key=> $rs){ $i++;?>
								  <?php  if($student_id != $rs['student_id']){?>
									  <?php if($key>0){?>
									   <tr>
									  	<td colspan="18"></td>
									  	<td colspan="2" style="background: #ccc;">$ <?php echo number_format($total,2);?></td>
									  </tr>
								  	<?php 
								 	 		$total=0;
							  				}
							  		?>
							  		 <tr>
									  	<td colspan="20"><?php echo $rs['stu_code']." ".$rs['stu_khname'].'-'.$rs['stu_enname']; ?></td>
									  </tr>
							  		<?php }?>
								  <tr class="hover" style="font-size:12px; color:#000; height: 18px;"​ align="center">
								  	<td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $i;?></td>
								  	<td align="center"><?php echo $rs['stu_code']; ?></td>
								    <td style="text-align:left"><?php echo $rs['stu_khname'].'-'.$rs['stu_enname']; ?></td>
								    <?php 
									 	if($rs['is_void']==0){
									 		$total = $rs['paidamount'] + $total;
									 	}
									 	$rs['late_fee'] = empty($rs['late_fee'])?0:$rs['late_fee'];
								  ?> 
								    <td style="text-align:left"><?php echo $rs['category']; ?></td>
								    <td style="text-align:left"><?php echo $rs['service_name']; ?></td>
								    <td><?php echo date('d/m/Y', strtotime($rs['create_date']));?></td>
								    <td align="center" <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $rs['receipt_number']; ?></td>
								    <td align="center"><?php echo $rs['payment_term']; ?></td>
								    <td><?php echo $rs['qty'];?></td>
								    <td>$ <?php echo number_format($rs['fee'],2); ?></td>
								    <td><?php if($rs['late_fee']>0){echo '$ '.empty($rs['late_fee'])?0:$rs['late_fee'];}?></td>
								    <td><?php if($rs['extra_fee']>0){echo '$ '.$rs['extra_fee'];}?></td>
								    <td><?php if($rs['discount_percent']>0){echo $rs['discount_percent'].' %';} ?> </td>
								    <td><?php echo $rs['discount_amount']; ?> </td>
								    <td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>>$ <?php echo $rs['paidamount']; ?></td>
								    <td><?php echo empty($rs['start_date'])?"":date('d/m/Y', strtotime($rs['start_date'])); ?></td>
								    <td><?php echo empty($rs['validate'])?"":date('d/m/Y', strtotime($rs['validate'])); ?></td>
								    <td style="font-size: 9px;"><?php echo $rs['note']; ?></td>
								   	<td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $rs['void_status']; ?></td>
								  	 <td><?php echo $rs['user']; ?></td>
								  </tr>
								  <?php 
								  $student_id = $rs['student_id'];
							  }}?>
								   <tr>
								  	<td colspan="18"></td>
								  	<td colspan="2" style="background: #ccc;">$ <?php echo number_format($total,2);?></td>
								 </tr>
							</table>
						</td>
					</tr>
					<?php 
						$fine=0;
						$credit_memo=0;
						$deduct=0;
						$net_amount=0;									
					?>
					<?php if(!empty($this->rs)){foreach ($this->rs as $payment){
						if($payment['is_void']==0){
							$payment['deduct'] = empty($payment['deduct'])?0:$payment['deduct'];
							$fine = $fine + $payment['penalty'];
							$credit_memo = $credit_memo + $payment['credit_memo'];
							$deduct = $deduct + $payment['deduct'];
							$net_amount = $net_amount + $payment['total_payment'];
						}
					}}?>
					
					<?php if(!empty($this->row)){ ?>
					<tr>
						<td colspan="3">
							<table width="29.2%" border="1" align="right" style="border:1px solid #000;border-collapse:collapse;white-space:nowrap;font-family: 'Khmer OS Battambang';">
								<tr>
									<td style="font-size: 18px;font-family:'Khmer MEF2';background-color: #ccc; width: 38%; font-weight:bold;font-size: 12px;"><?php echo $tr->translate('GRAND_TOTAL');?></td>
									<td style="font-family:'Khmer MEF2';background-color: #ccc; width: 38%; font-weight:bold; font-size: 12px;"><?php echo $tr->translate('FINE');?></td>
									<td style="font-family:'Khmer MEF2';background-color: #ccc; width: 38%; font-weight:bold;font-size: 12px;"><?php echo $tr->translate('CREDIT_MEMO');?></td>
									<td style="font-family:'Khmer MEF2';background-color: #ccc; width: 38%; font-weight:bold;font-size: 12px;"><?php echo $tr->translate('DEDUCT');?></td>
									<td style="font-family:'Khmer MEF2';background-color: #ccc; width: 38%; font-weight:bold;font-size: 12px;"><?php echo $tr->translate('NET_AMOUNT');?></td>
								</tr>
								<tr>
									<td style="font-weight:bold;font-family: Arial Black; font-size: 12px;"><span style="color: red;">$ <?php echo number_format($total,2);?></span></td>
						  			<td style="font-weight:bold;font-family: Arial Black; font-size: 12px;"><span style="color: red;">$ <?php echo number_format($credit_memo,2);?></span></td>
							  		<td style="font-weight:bold;font-family: Arial Black; font-size: 12px;"><span style="color: red;">$ <?php echo number_format($deduct,2);?></span></td>
							  		<td style="font-weight:bold;font-family: Arial Black; font-size: 12px;"><span style="color: red;">$ <?php echo number_format($total,2);?></span></td>
							  		<td style="font-weight:bold;font-family: Arial Black; font-size: 12px;"><span style="color: red;">$ <?php echo number_format($fine,2);?></span></td>
								</tr>
						  	</table>
						</td>
					</tr>
					<?php }?>
					<tr >
						<td colspan="3" width="100%">
							<table width="100%">
								<tr>
									<td  width="25%" align="center">
										<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
	</div>	
 </div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
	
	dojo.require("dojo.data.ItemFileWriteStore"); 
	

	var service_store = getDataStorefromJSON('id','name');
	var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: service_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "service",
			name: "service",   
			required:false,        
			class: 'fullside',
			placeHolder:'<?php echo $tr->translate('SERVICE');?>',
			onChange: function() {  
			}
		}, "service");
		
		new dijit.form.FilteringSelect({
			store: academic_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "study_year",
			name: "study_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				academic_year = dijit.byId('study_year').get('value');
			}
		}, "study_year");
		new dijit.form.FilteringSelect({
			store: group_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                      
			id: "group",
			name: "group",  
			class: 'fullside', 
			readonly:false,
			required:false,
			placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
			onChange: function() {  
				
			}
		}, "group");
		
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade_all",
			name: "grade_all",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  

			}
		}, "grade_all");
		getallGrade();
		
		 var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getAllAcademicByBranch();
			 getAllGroupByBranch();
		});
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
		 getgradebyDegree();

		 dijit.byId('item').set('value','<?php echo $this->search['item']?>');  	
	});
	url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getacademic'));?>';
	var oldBranch = "<?php echo $this->search['branch_id']?>";
	function getAllAcademicByBranch(){
		dijit.byId('study_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('study_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getacademic,
			content:{
				'branch_id':branch_id,'showall':1
				},
			handleAs:"json",
			load: function(data) {
				academic_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('study_year').set('store',academic_store);  
				if(oldBranch==branch_id){
					dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
				}
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
	function getAllGroupByBranch(){
		dijit.byId('group').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('group').set('store',group_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getgroup,
			content:{
				'branch_id':branch_id
				},
			handleAs:"json",
			load: function(data) {
				group_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('group').set('store',group_store);   
				if(oldBranch==branch_id){
					dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
				}
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade_all').set('store',grade_store);   
				dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
			},
			error: function(err) {
				alert(err);
			}
		});
	}

	var oldItems = '<?php echo $this->search['item']?>';
	var url_degree = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-grade')); ?>';
	function getgradebyDegree(){
		dept_id = dijit.byId("item").get("value");
		dojo.xhrPost({
			url:url_degree,
			content:{
				'dept_id':dept_id,
				},
			handleAs:"json",
			load: function(data) {
				service_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('service').set('store',service_store);  	
				if(oldItems==dept_id){
					dijit.byId('service').set('value','<?php echo $this->search['service']?>');  	
				}
			},
			error: function(err) {
			}
		});
	}
	
</script>
