<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SERVICE_CHARGE_RPT')); 
	$frm = $this->form_search;
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SERVICE_CHARGE_RPT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="<?php echo $tr->translate("SEARCH");?>" value="<?php echo $this->search['txtsearch'];?>" type="text">
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('branch_id')?>
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<input id="study_year" />
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('degree_bac')?>
       		</div>
       	</div>
       	<div class="form-group">
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('grade_all')?>
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('finished_status')?>
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       	</div>
	</form>	
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto; white-space: nowrap;width: 100%">
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr class="line">
				<td colspan="3"></td>
			</tr>
			<tr>
				<td width="15%" align="center">
				</td>
				<td width="70%" align="center">
					<strong style="font-weight:normal;color:#000; font-size: 14px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate('SERVICE_CHARGE_RPT');?></strong><br />
				</td>
				<td width="15%" align="center">
				<style>
				table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
				tr{ page-break-inside:avoid; page-break-after:auto }
				.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap; font-size: 14px;}
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				.hover:hover{background:#ccc;}
				tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
			</style>
				</td>
			</tr>
			<tr>
				<td colspan="3" id="exportExcel">
					<table cellpadding="5"​ style=" font-family:'Khmer OS Battambang';margin:0 auto;width:100%;border: 1px solid #000; border-collapse: collapse;border: 1px solid #000;white-space: nowrap;"  border="1" >
						<thead>
							<tr style="background: #ccd9ff;" class="cheader" align="center" >
								<td><?php echo $tr->translate('N_O')?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate('BRANCH')?></td>
								<td><?php echo $tr->translate('ACADEMIC_YEAR')?></td>
								<td><?php echo $tr->translate('SERVICE_CATE')?></td>
								<td><?php echo $tr->translate('SERVICE_NAME')?></td>
								<td><?php echo $tr->translate('MONTHLY')?></td>
								<td><?php echo $tr->translate('QUARTER')?></td>
								<td><?php echo $tr->translate('SEMESTER')?></td>
								<td><?php echo $tr->translate('YEAR')?></td>
								<td><?php echo $tr->translate('NOTE')?></td>
							</tr>
						</thead>
					<?php $i=0;if(!empty($this->rs))foreach ($this->rs AS $row) { $i++;?>
							<tr class="hover" style="font-size:12px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;"><?php echo @$row['branch_id'];?></td>
								<td style="border: 1px solid #000;"><?php echo @$row['academic'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;&nbsp;<?php echo @$row['degree'];?></td>	
								<td align="left" style="border: 1px solid #000;">&nbsp;&nbsp;<?php echo @$row['class'];?></td>	
								<td style="border: 1px solid #000;"><?php echo number_format(@$row['monthly'],2);?> $</td>
								<td style="border: 1px solid #000;"><?php echo number_format(@$row['quarter'],2);?> $</td>
								<td style="border: 1px solid #000;"><?php echo number_format(@$row['semester'],2);?> $</td>
								<td style="border: 1px solid #000;"><?php echo number_format(@$row['year'],2);?> $</td>
								<td style="border: 1px solid #000;"><?php echo @$row['remark'];?></td>
							</tr>
					<?php }?>	
					</table>	
				</td>
			</tr>
			<tr>
				<td colspan="3" width="100%" >
					<?php echo $this->rsfooteracc;?>
				</td>
			</tr>
		</table>
	</div>	
</div>

<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	
	var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: academic_store,
			autoComplete: true,                        
			required: false,
			id: "study_year",
			name: "study_year",
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_YEAR");?>",          
			onChange: function() {  
			}
		}, "study_year");
		getAllAcademicByBranch();
	});
	
	url_getacademic = '<?php echo $this->url(array('module'=>'accounting','controller'=>'servicecharge','action'=>'get-yearbybranch'));?>';
	function getAllAcademicByBranch(){
		dijit.byId('study_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('study_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getacademic,
			content:{
				'branch_id':branch_id
				},
			handleAs:"json",
			load: function(data){
				academic_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('study_year').set('store',academic_store);  
				dijit.byId('study_year').attr("value","<?php echo $this->search['study_year']?>");
			},
			error: function(err) {
			}
		});
	}
</script>