<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('RPT_DISCOUNT_SETTING_DETAIL')); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->form_search;
	$str="";
	$classHideHeight=classHideHeight;
//	print_r($this->rr);
//	 exit();
?>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_DISCOUNT_SETTING_DETAIL');?></h4>
    		</div>
    		<div class="col-sm-4 text-right"></div>
    	</div>
    </div>
	<div class="x_panel">
		<div class="x_title">
			<h2><i class="fa fa-filter"></i> <?php echo $tr->translate("FILTERING");?> <small><?php echo $tr->translate("STUDENT");?></small></h2>
			<ul class="nav navbar-right panel_toolbox">
				<li>
				<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
				</li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="x_content" style="display: none;" >
			<form action="" dojoType="dijit.form.Form" method="post">
				<script type="dojo/method" event="onSubmit">
					if (this.validate()) {
						loadingBlock();
						return true;
					} else {
						return false;
					}
				</script>
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('degree'); ?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<input id="grade" />
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('academicYearEnroll'); ?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('studentType'); ?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('discount_status'); ?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH"); ?></button>
					</div>
				</div>
			</form>
		</div>
	</div>

	<div id="divPrint">
		<style type="text/css">
			.style{
				line-height: 20px;font-size: 12px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			.style1:hover{ background: #ccc; }
			table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
			tr.content-data{ page-break-inside:avoid; page-break-after:auto; }
			#header{
				display: table-header-group;
				page-break-inside:avoid; page-break-after:auto;
				margin-top: 100px;
			}
			@media print {
			div.divFooter {
				position: fixed;
				top: 0;
				width: 100%;
				height: 100px;
				bottom:0px;
				margin:0;
			}
			}
			.center{text-align: center !important;}
			table.content-data{
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:12px;
			}
			table.content-data thead tr.style {
			line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #c1d0f3;
				font-weight:600;
			}
			tr.style {
			 white-space: nowrap;
			}
		
			
			table tr td{
				padding:0 2px;
			}
			.wrapword{
				white-space: normal;
				width:200px;
				word-break: break-all;
			}
			.bg-grey{
				background: #ccc;
				height: 22px; 
				font-weight:600;
				text-align: center;
			}
			.redBold{
				color: red;
			}
			@media print{
						@page{
							margin:0.3cm 0.7cm 0cm 0.7cm;
							page-break-before: avoid;
							-webkit-transform: scale(0.5);  /* Chrome, Safari 3.1+  */
							-moz-transform: scale(0.5);  /* Firefox 3.5-15 */
							-ms-transform: scale(0.5);   /* IE 9 */
							-o-transform: scale(0.5);    /* Opera 10.50-12.00 */
							transform: scale(0.5);
							page: A4;
						}
				}

			</style>
		
			<table width="100%">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="25%" align="left">
					</td>
					<td align="center" width="50%">
						<strong style="font-weight:normal;font-family: Arial Black;color:#000; font-size: 12px;font-family:'khmer os muol light';"><?php echo $tr->translate('RPT_DISCOUNT_SETTING_DETAIL');?></strong><br >
						<span style="color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php if(!empty($this->search['start_date'])){?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> <?php echo $tr->translate('TO')?> <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></span>
					</td>
					<td align="right" width="25%">&nbsp;</td>
				</tr>
				
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr> 
					<td colspan="3" id="exportExcel" >
						<table width="100%"  align="center" class="style">
							<tr>
								<td width="13%" style="white-space: nowrap;">
									<?php echo $tr->translate("BRANCH");?>
								</td>
								<td width="25%" ><div  class="value"> : &nbsp;<strong><?php echo $this->rr['branch']; ?></strong></div></td>
								<td width="27%">&nbsp;</td>
								<td width="10%" style="white-space: nowrap;">
									<?php echo $tr->translate("ACADEMIC_YEAR");?>
								</td>
								<td width="25%" ><div  class="value"> : &nbsp;<strong><?php echo $this->rr['academicYear']; ?></strong></div></td>
							</tr>
							<tr>
								<td width="13%" style="white-space: nowrap;">
									<?php echo $tr->translate("TITLE");?>
								</td>
								<td width="25%" ><div  class="value"> : &nbsp;<strong><?php echo $this->rr['discountTitle']; ?></strong></div></td>
								<td width="27%">&nbsp;</td>
								<td width="10%" style="white-space: nowrap;">
									<?php echo $tr->translate("DISCOUNT_FOR_TYPE");?>
								</td>
								<td width="25%" ><div  class="value"> : &nbsp; <strong><?php echo $this->rr['discountForText']; ?></strong></div></td>
							</tr>
							<tr>
								<td width="13%" style="white-space: nowrap;">
									<?php echo $tr->translate("DISCOUNT_TYPE");?>
								</td>
								<td width="25%" ><div  class="value"> : &nbsp;<strong><?php echo $this->rr['discName']; ?></strong></div></td>
								<td width="27%">&nbsp;</td>
								<td width="10%" style="white-space: nowrap;">
									<?php echo $tr->translate("DISCOUNT_PERIOD");?>
								</td>
								<td width="25%" ><div  class="value"> : &nbsp; <strong><?php echo $this->rr['discountPeriod']; ?></strong></div></td>
								
							</tr>
							<tr>
								<td width="13%" style="white-space: nowrap;">
									<?php echo $tr->translate("DIS_MAX");?>
								</td>
								<td width="25%" ><div  class="value"> : &nbsp;<strong><?php echo $this->rr['DisValueType']; ?></strong></div></td>
								<td width="27%">&nbsp;</td>
								<td width="10%" style="white-space: nowrap;">
									
								</td>
								<td width="25%" ><div  class="value"> </div></td>
							</tr>

						</table>
						<table class="content-data" width="100%" border="1" align="center" >
							  <thead>
								  <tr class="style" align="center">
								    <td scope="col">&nbsp;<?php echo $tr->translate('N_O');?>&nbsp;</td>
								    <td scope="col">&nbsp;<?php echo $tr->translate('STUDENT_CODE');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('STUDENT_NAME');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('NAME_ENGLISH');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('SEX');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('Tel');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('ACADEMIC_YEAR_ENROLL');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('STUDENT_TYPE');?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate('STATUS');?>&nbsp;</td>
								  </tr>
							  </thead>
							 <?php 
								 $oldGrade='';
							 	if(!empty($this->row)){foreach($this->row as $key=>$rs){

									if($oldGrade!=$rs['grade']){ 
							 ?> 
								
								<tr class="style hover bg-grey" >
									<td colspan="10"><?php echo $tr->translate("GRADE");?> : <?php echo $rs['grade']; ?></td>
								</tr>
							
							<?php } 

								$oldGrade = $rs['grade'];
							?>

							  <tr class=" hover style"  align="left" >
								    <td data-label="<?php echo $tr->translate("N_O");?>"  style="text-align: center;"><?php echo $key+1;?></td>
								    <td data-label="<?php echo $tr->translate("STUDENT_CODE");?>" ><?php echo $rs['stu_code']; ?></td>
								    <td data-label="<?php echo $tr->translate("STUDENT_NAME");?>" > <?php echo $rs['stu_name']; ?></td>
									<td data-label="<?php echo $tr->translate("NAME_ENGLISH");?>" > <?php echo $rs['stu_name_en']; ?></td>
									<td data-label="<?php echo $tr->translate("SEX");?>" align="center"> <?php if($rs['sex']==1){ echo $tr->translate("MALE_SHORT"); }else{ echo $tr->translate("FEMALE_SHORT"); }; ?></td>
									<td data-label="<?php echo $tr->translate("Tel");?>" > <?php echo $rs['tel']; ?></td>
									<td data-label="<?php echo $tr->translate("ACADEMIC_YEAR_ENROLL");?>" ><?php echo $rs['startYear']; ?></td>
									<td data-label="<?php echo $tr->translate("STUDENT_TYPE");?>" ><?php echo $rs['studentType']; ?></td>
									<td data-label="<?php echo $tr->translate("STATUS");?>" align="center" class=" <?php if($rs['isCurrent']==0){ echo "redBold"; } ?> " ><?php if($rs['isCurrent']==1){ echo $tr->translate("USING"); }else{ echo $tr->translate("STOP_USED"); }; ?></td>
							  </tr>
							  <?php  }} ?>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3" width="100%">
						<?php //echo $this->rsfooteracc;?>
					</td>
				</tr>
			</table>
	</div>	
</div>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
var disname_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->discount));?> );
dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete:false,                     
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                     
		id: "grade",
		name: "grade",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  

		}
	}, "grade");

	oldGrade='<?php echo $this->search['grade'];?>';

	getallGrade();
});

var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var urlGetGrade = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(){
	dijit.byId('grade').attr('value','');   
	dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){
			return false;
		}
		dojo.xhrPost({
			url:urlGetGrade,
			content:{
				'dept_id':dept_id,
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);  
				if(oldGrade>0){
					dijit.byId('grade').attr('value',oldGrade);
				} 
			},
			error: function(err) {
			}
		});
}

var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="detail"){
					url='<?php echo $this->baseUrl()."/allreport/accounting/rptDiscountdetail/id/";?>';
				}
				gotoAction();
			},
			items:{
				"detail": {name: "<?php echo $tr->translate("DISCOUNT_DETAIL");?>", icon: "fa-list", accesskey: "c"},
			}
		});
	});
	function setrowdata(index,type){
		row = index;
		typereceipt = type;
	}
	var recordid ='';
	function gotoAction(){
		 window.open(url+row, '_blank');
	}
</script>