<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('RPT_SPECAIL_DISCOUNT')); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->form_search;
	$str="";
?>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_SPECAIL_DISCOUNT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("title");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("dis_type");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("status_type");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("start_date");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("end_date");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       	</div>
	</form>
<style>
#footer{display: none;}
</style>	
	<div id="divPrint">
		<form action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'submitlist')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">	
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; font-family:'Khmer OS Battambang';">
				<tr>
					<td width="25%" align="left">
						<img style="height: 90px" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
					</td>
					<td align="center" width="50%">
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('CUSTOMER_BRANCH');?></strong><br />
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('RPT_SPECAIL_DISCOUNT');?></strong><br >
					</td>
					<td align="right" width="25%">&nbsp;</td>
				</tr>
				<tr> 
					<td colspan="3" id="exportExcel" >
						<style type="text/css">
							th,td{ padding:0 1px;}
							table{ border-collapse:collapse; margin:0 auto;
							border-color:#000; }
							.padd tr td{  text-align:center}
						</style>
						<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;font-family: 'Khmer OS Battambang';">
							  <thead>
							  <tr style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center">
							    <td>&nbsp;<?php echo $tr->translate('N_O');?>&nbsp;</td>
							    <td>&nbsp;<?php echo $tr->translate('STUDENT_NAME');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('REQUEST_NAME');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('PHONE');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('DISCOUNT_TYPE');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('PERIOD');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('EXPIRE_DATE');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('STATUS');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('NOTE');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('USER');?>&nbsp;</td>
							  </tr>
							  </thead>
							 <?php $i=0; $total=0;if(!empty($this->row)){foreach($this->row as $key=>$rs){$i++;
									 if($key==0){
									 	$str=$key+1;
									 }else{
									 	$str.=",".($key+1);
									 }
							 ?>
							  <tr class="hover" style="font-size:11px; height: 20px;"​ align="center">
								    <td ><?php echo $i;?></td>
								    <td><?php echo $rs['stu_name']; ?></td>
								    <td><?php echo $rs['request_name']; ?></td>
								    <td><?php echo $rs['phone']; ?></td>
								    <td><?php echo $rs['discount_type']; ?></td>
								    <td><?php echo $rs['duration_type']; ?></td>
								    <td><?php echo $rs['expired_date']; ?></td>
								    <td><?php echo $rs['status']; ?></td>
								    <td><?php echo $rs['notes']; ?></td>
								    <td><?php echo $rs['user_name']; ?></td>
							  </tr>
							  <?php 
							  ?> 
							  <?php }} ?>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr style="text-align:center;border:1px solid #fff;">
					<td colspan="10" align="center">
					</td>
				</tr>
				<tr>
					<td align="center" width="25%">
						<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY');?></span>
					</td>
					<td  width="50%">
						&nbsp;
					</td>
					<td align="center"  width="25%">
						<span style=" font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY');?></span>
					</td>
				</tr>
			</table>
		</form>
	</div>	
</div>