<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS | Report Student Payment'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->form_search;
?>
<div style="min-height:15cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">
	<form id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-paymentdetailbytype')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table style="width:100%;font-family:'khmer os battambang';">
		  <tr> 
			   <td><?php echo $frm->getElement("title");?></td>
			   <td><?php echo $frm->getElement("branch_id");?></td>
			   <td><?php echo $frm->getElement("study_year");?></td>
			   <td><?php echo $frm->getElement("group");?></td>
			   <td><?php echo $frm->getElement("degree");?></td>
			   <td><?php echo $frm->getElement("grade_all");?></td>
			   <td><?php echo $frm->getElement("session");?></td>
	   	  </tr>
	   	  <tr>	   	  	   
	   	  	   <td><?php echo $frm->getElement("payment_by");?></td>
	   	  	   <td><?php echo $frm->getElement("item");?></td>
	   	  	   <td><?php echo $frm->getElement("service");?></td>
	   	  	   <td><?php echo $frm->getElement("user");?></td>
	   	       <td><?php echo $frm->getElement("start_date");?></td>
	           <td><?php echo $frm->getElement("end_date");?></td>
			   <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		   </tr>
	   </table>
	</form>
<style>
	.hover:hover{background:#ccc;}
</style>	
<div id="divPrint">
		<table style="background:#fff; margin: 0 auto; width: 100%;">
				<tr>
					<td colspan="3" align="left"></td>
				</tr>
				<tr>
					<td width="25%">
						<img style="width: 40%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td align="center" width="50%">
						<strong style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate('CUSTOMER_BRANCH');?></strong><br />
						<strong style="font-weight:bold;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate('STUDENT_PAYMENT_BY_TYPE_REPORT');?></strong><br />
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 12px;font-family:'Khmer MEF2';"><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search["start_date"]))?><?php echo $tr->translate('TO');?><?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></strong>
					</td>
					<td width="25%"></td>
				</tr>
				<tr>			
					<style> th,td{ padding:0 1px;}</style>
						<style type="text/css">
							table{ border-collapse:collapse; margin:0 auto;
							border-color:#000; }
							.padd tr td{  text-align:center}
							table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
							tr{ page-break-inside:avoid; page-break-after:auto }
							.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap; font-size: 14px;}
							#header {
							  display: table-header-group;
							  page-break-inside:avoid; page-break-after:auto;
							}
							.hover:hover{background:#eee;}										
					  </style>
					 <td colspan="3" id="exportExcel">
						<table class="padd" width="100%"  align="center" style="white-space:nowrap;">
							<style> td{padding:0 3px; }</style>
							  <?php 
								$grand_total =0;  
								$all_grandtotal =0;
								$i=0; 
								$type='';
								$other_income = 0;
						 		$payment_term=array("1"=>"Month","2"=>"Term","3"=>"Semester","4"=>"Annual","5"=>"Other",);
							  ?>
						  <?php if(!empty($this->row_detail)) foreach($this->row_detail as $key => $rs){ $i++;?>
						  <?php 
						  if($rs['items_id']!=$type){
						  if($key>0){?>
							</table>
							<table align="right" style="font-family: 'Open Sans', sans-serif,'Kh Battambang','Khmer Battambang'">
								  <tr style="font-size:13px; color:#000; height: 18px;"​ align="center">
									<td style="width:146px; font-weight:bold; ">&nbsp;<?php echo $tr->translate('STUDENT_PAYMENT_INCOME');?>&nbsp;</td>
									<td style=" border-bottom: 1px #000 solid; color:#F00; font-weight:bold; width:112px; ">$ <?php echo number_format($grand_total,2);?></td>
								  </tr>
							 </table><br /><br />
							<table class="padd" width="100%"  align="center" style="white-space:nowrap;">
							  <?php $i=1;
							  	$grand_total=0;
						  	  }
							  ?>
							  <thead>
								  <tr class="hover" style="text-align:center !important;background-color:#ccd9ff;line-height: 30px;font-weight: bold;font-size:10px; height: 22px;font-family: 'Open Sans', sans-serif,'khmer os battambang','Khmer Battambang';" >
									    <th class="center">&nbsp;<?php echo $tr->translate('N_O');?>&nbsp;</th>
									    <th class="center">&nbsp;<?php echo $tr->translate('STUDENT_ID');?>&nbsp;</th>
										<th class="center">&nbsp;<?php echo $tr->translate('NAME_KH');?>&nbsp;</th>
										<th class="center"><?php echo $tr->translate('PAID_DATE');?></th>
										<th class="center"><?php echo $tr->translate('RECEIPT_NO');?></th>
										<th class="center">&nbsp;<?php echo $tr->translate('TYPE');?>&nbsp;</th>
										<th class="center"><?php echo $tr->translate('SERVICE_NAME');?></th>
										<th class="center"><?php echo $tr->translate('PAYMENT_TERM');?></th>
										<th class="center"><?php echo $tr->translate('QTY');?></th>
										<th class="center"><?php echo $tr->translate('PRICE');?></th>
										<th class="center"><?php echo $tr->translate('Deduct/Extra');?></th>
										<th class="center"><?php echo $tr->translate('Disc Type');?></th>
										<th class="center"><?php echo $tr->translate('DISCOUND');?></th>
										<th class="center"><?php echo $tr->translate('PAID_AMOUNT');?></th>
										<th class="center"><?php echo $tr->translate('PERIOD');?></th>
										<th class="center"><?php echo $tr->translate('REMARK');?></th>
										<th class="center"><?php echo $tr->translate('STATUS');?></th>
										<th class="center"><?php echo $tr->translate('USER');?></th>
								  </tr>
							  </thead>
						  <?php 
						   }
						   $type = $rs['items_id'];
						   ?>
						   <tr class="hover" style="font-size:11px; color:#000; height: 18px; border-bottom: 1px solid #000;font-family: 'Open Sans', sans-serif,'Kh Battambang','Khmer Battambang';"​ align="center">
							  	<td <?php if($rs['is_void']==1){echo 'style="color:red;"';}?>><?php echo $i;?></td>
							    <td style="text-align:center;"><?php echo $rs['stu_code']; ?></td>
							    <td style="text-align:left"><?php echo !empty($rs['stu_khname'])?$rs['stu_khname']:$rs['stu_enname']; ?></td>
							    <td><?php echo date('d/m/Y', strtotime($rs['create_date']));?></td>
							    <td align="center" <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $rs['receipt_number']; ?></td>
							    <td style="text-align:left"><?php echo $rs['category']; ?></td>
								<td style="text-align:left"><?php echo $rs['service_name']; ?></td>
							    <?php 
									$total_day=strtotime($rs['validate'])-strtotime($rs['start_date']);
									$day=(int)($total_day/(60*60*24));
									$qty_month = number_format($day/30);
									$qty_day = $day%30;
								?>
								<td align="center">
								<?php 
									if($rs['payment_id']>0){
										if($rs['payment_id']==5){
											if($qty_month>0){
												echo $qty_month." month+".$qty_day." days";
											}else{
												echo $qty_day." days";
											}
										}else{
											echo $payment_term[$rs['payment_id']];
										}
									}
								?>
								</td>
							    <td><?php echo $rs['qty'];?></td>
							    <td><?php echo number_format($rs['fee'],2); ?></td>
							    <td><?php echo $rs['extra_fee'];?></td>
							    <td><?php echo $rs['discount_type']; ?> </td>
							    <td><?php if($rs['discount_percent']>0){echo $rs['discount_percent'].' %';}
									  if($rs['discount_amount']>0){
									    echo $rs['discount_amount'];
									   }
							    	?>
							    </td>
							    <td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $rs['paidamount'];?></td>
							    <td><?php if($rs['is_onepayment']==0){
							    		echo date('d/m/Y', strtotime($rs['start_date']));
							    		echo "-".date('d/m/Y', strtotime($rs['validate']));
							    	}?>44
							    </td>
							    <td style="font-size: 9px;"><?php echo $rs['note'];?></td>
							   	<td <?php if($rs['is_void']==1){echo 'style="color:red;"'; }?>><?php echo $rs['void_status'];?></td>
								<td><?php echo $rs['user']; ?></td>
						 </tr>
						  <?php 
						  	if($rs['is_void']==0){
						  		$grand_total = $grand_total+$rs['paidamount'];
						  		$all_grandtotal = $all_grandtotal+$rs['paidamount'];
						  	}
						  ?>
						  <?php } ?>
						   </table>
					</td>
				</tr>
				<tr>	
					<td colspan="3">
						<table align="right" style="font-family: 'Open Sans', sans-serif,'Kh Battambang','Khmer Battambang'">
							  <tr style="font-size:13px; color:#000; height: 18px;"​ align="center">
								<td style="width:146px; font-weight:bold; ">&nbsp;<?php echo $tr->translate('STUDENT_PAYMENT_INCOME');?>&nbsp;</td>
								<td style=" border-bottom: 1px #000 solid; color:#F00; font-weight:bold; width:112px; ">$ <?php echo number_format($grand_total,2);?></td>
							  </tr>
						 </table>
					</td>
				</tr>
				<?php if(!empty($this->rsincome)){?>
				<tr>
					<td colspan="3">
						<strong><?php echo $tr->translate('OTHER_INCOME')?></strong>
					</td>
				</tr>
				<tr>
					<td colspan="3" >
						<table cellpadding="5"​ style="font-family:'Khmer OS Battambang';margin:0 auto;width:100%; border-collapse: collapse;"   >
							<tr style="font-size:11px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center" >
								<td><?php echo $tr->translate('N_O')?></td>
								<td><?php echo $tr->translate('CATEGORY')?></td>
								<td><?php echo $tr->translate('INCOME_TITLE')?></td>
								<td><?php echo $tr->translate('INVOICE_NO')?></td>
								<td><?php echo $tr->translate('PAID_DATE')?></td>
								<td><?php echo $tr->translate('TOTAL')?></td>
								<td><?php echo $tr->translate('USER')?></td>
							</tr>
						<?php $i=0;
						$other_income = 0;
						foreach ($this->rsincome AS $row) { $i++;
							$other_income = $other_income + $row['total_amount'];
						?>
							<tr class="hover" style="font-size:11px; height: 20px;border-bottom: 1px solid #000;" align="center" >
								<td><?php echo $i;?></td>
								<td><?php echo $row['income_category'];?></td>	
								<td><?php echo $row['title'];?></td>
								<td><?php echo $row['invoice'];?></td>
								<td><?php echo date('d-m-Y',strtotime($row['date']));?></td>
								<td><?php echo number_format($row['total_amount'],2);?></td>
								<td><?php echo $row['name'];?></td>
							</tr>
						<?php }?>	
						</table>
					</td>
				</tr>	
				<?php 
				  }
					$credit_memo=0;
					$penalty=0;
					if(!empty($this->row)){
						foreach ($this->row as $payment){
							$credit_memo = $credit_memo + $payment['credit_memo'];
							$penalty = $penalty + $payment['penalty'];
						}
					}
				?>
				<tr>
					<td colspan="1"></td>
					<td >
						<div>&nbsp;</div>
						<table   align="right" style="width:100%; margin-right:0.5%; white-space:nowrap;font-family: Khmer OS  Battambang;">
							<tr style="font-size:12px; background:#ccd9ff; height: 20px;font-weight: bold;" align="center">
								<th><?php echo $tr->translate('STUDENT_PAYMENT_INCOME');?>(+)</th>
								<th><?php echo $tr->translate('FINE');?>(+)</th>
								<th><?php echo $tr->translate('OTHER_INCOME');?>(+)</th>
								<th><?php echo $tr->translate('Credit Memo');?>(-)</th>
								<th><?php echo $tr->translate('NET_AMOUNT');?>(=)</th>
							</tr>
							<tr align="center" style=" height:18px; font-size:12px; padding: 1px;" >
								<td><span style="color: red;border-bottom:3px double #000;">$ <?php echo number_format($all_grandtotal,2)?></span></td>
								<td><span style="color: red;border-bottom:3px double #000;">$ <?php echo number_format($penalty,2)?></span></td>
								<td><span style="color: red;border-bottom:3px double #000;">$ <?php echo number_format($other_income,2)?></span></td>
								<td><span style="color: red;border-bottom:3px double #000;">$ <?php echo number_format($credit_memo,2)?></span></td>
								<td><div style="color: red;border-bottom:3px double #000;">$ <?php echo number_format($all_grandtotal+$penalty+$other_income-$credit_memo,2)?></div></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3" width="100%">
						<table width="100%" style="font-family:'Khmer OS Battambang';font-weight:bold;">
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
				</td>
			</tr>
		</table>
	</div>	
</div>