<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_OTHER_INCOME_EXPENSE')); 
	$frm=$this->form_search;
	$classHideHeight=classHideHeight;
?>
<style>
	.hover:hover{ background:#ccc;}
	table.content-data tr.style-head,
	table.tb-footer tr.style-head {
	   font-weight: bold !important;
	}
</style>	
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_OTHER_INCOME_EXPENSE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>	
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-expense')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="<?php echo $tr->translate("SEARCH");?>....." value="<?php echo $this->search['txtsearch'];?>" type="text">
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("branch_id");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("start_date");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("end_date");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       	</div>
	</form>		
	<div id="divPrint">
			<style>
				.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table.content-data{ page-break-inside:auto }
					tr.content-data{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:8px;
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:12px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:12px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:0 2px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					.redBold {
						font-weight: 600;
						color: #f80000;
					}
					table.content-data tr td{
						padding: 2px;
					}
					@media print{
						@page{
							margin:0.3cm 0.7cm 0cm 0.7cm;
							page-break-before: avoid;
							-webkit-transform: scale(0.5);  /* Chrome, Safari 3.1+  */
							-moz-transform: scale(0.5);  /* Firefox 3.5-15 */
							-ms-transform: scale(0.5);   /* IE 9 */
							-o-transform: scale(0.5);    /* Opera 10.50-12.00 */
							transform: scale(0.5);
							page: A4;
							
						}
					}

			</style>
			<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="15%" align="center"></td>
					<td width="70%" align="center">
					    <span style="color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate('RPT_OTHER_INCOME_EXPENSE')?></span><br />
						<span style="color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php if(!empty($this->search['start_date'])){?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> <?php echo $tr->translate('TO')?> <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></span>
					</td>
					<td width="15%" align="center"></td>
				</tr>
				<tr>
					<td colspan="3" id="exportExcel">
						<table class="content-data" cellpadding="5"​ border="1" width="100%" >
							<thead>
							<tr class="style" align="center">
								<td scope="col"><?php echo $tr->translate('N_O')?></td>
								<td scope="col"><?php echo $tr->translate('BRANCH')?></td>
								<td scope="col"><?php echo $tr->translate('EXPENSE_TITLE')?></td>
								<td scope="col"><?php echo $tr->translate('RECEIPT_NO')?></td>
								<td scope="col"><?php echo $tr->translate('INVOICE_NUM')?></td>
								<td scope="col"><?php echo $tr->translate('PAYMENT_METHOD')?></td>
								<td scope="col"><?php echo $tr->translate('CHEQUE_NO')?></td>
								<td scope="col"><?php echo $tr->translate('TOTAL')?></td>
								<td scope="col"><?php echo $tr->translate('RECEIVER')?></td>
								<td scope="col"><?php echo $tr->translate('DESCRIPTION')?></td>
								<td scope="col"><?php echo $tr->translate('FOR_DATE')?></td>
								<td scope="col"><?php echo $tr->translate('USER')?></td>
							</tr>
							</thead>
							<?php 
								$total_expense = 0;
							if(!empty($this->row)){foreach ($this->row AS $key=>$row) { $key=$key+1;
								
								if ($row['status']==1){
									$total_expense =$total_expense+$row['total_amount'];
								}
							?>
							<tr class="context-menu-one style hover" oncontextmenu="setrowdata(<?php echo $row['id'];?>);return false;" align="center" <?php if ($row['status']==0){?>style="background: #ffd9d9;"<?php }?> >
								<td data-label="<?php echo $tr->translate("N_O");?>"><?php echo $key;?></td>
								<td data-label="<?php echo $tr->translate("BRANCH");?>"><?php echo $row['branch_name']; ?></td>
								<td data-label="<?php echo $tr->translate("EXPENSE_TITLE");?>" align="left"><?php echo $row['title']; ?></td>
								<td data-label="<?php echo $tr->translate("RECEIPT_NO");?>"><?php echo $row['invoice']; ?></td>
								<td data-label="<?php echo $tr->translate("INVOICE_NUM");?>"><?php echo $row['external_invoice']; ?></td>
								<td data-label="<?php echo $tr->translate("PAYMENT_METHOD");?>"><?php echo $row['pay']; ?></td>
								<td data-label="<?php echo $tr->translate("CHEQUE_NO");?>"><?php echo $row['cheque_no']; ?></td>
								<td data-label="<?php echo $tr->translate("TOTAL");?>" class="bold" align="right"><?php echo $row['total_amount'];?></td>
								<td data-label="<?php echo $tr->translate("RECEIVER");?>"><?php echo $row['receiver']; ?></td>
								<td data-label="<?php echo $tr->translate("DESCRIPTION");?>"><?php echo $row['description'];?></td>
								<td data-label="<?php echo $tr->translate("FOR_DATE");?>"><?php echo date('d-M-Y',strtotime($row['date']));?></td>
								<td data-label="<?php echo $tr->translate("USER");?>"><?php echo $row['first_name'];?></td>
							</tr>	
							<?php }}?>
							<tr style="border-left: 1px solid #fff; border-bottom: 1px solid #fff; border-right: 1px solid #fff;">
								<td colspan="7"></td>
								<td align="right" style="background:#e8e9e9;padding:5px;"><strong ><?php echo $tr->translate("TOTAL");?>  $&nbsp;&nbsp;<?php echo number_format($total_expense,2);?></strong></td>
								<td colspan="4"></td>
							</tr>	
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3" width="100%">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
		</table>
	</div>		
</div>
<script>
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="receipt"){
				url='<?php echo $this->baseUrl()."/allreport/accounting/rpt-expensedetail/id/";?>';
			}
			gotoAction();
		},
		items: {
			"receipt": {name: "<?php echo $tr->translate("PAYMENT_VOUCHER");?>", icon: "fa-money", accesskey: "c"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>