<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_STOP_SERVICE_REPORT'));
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm=$this->form_search;
?>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_STOP_SERVICE_REPORT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>	
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-suspendservice')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">	
       			<?php echo $frm->getElement('title')?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('study_year')?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('service_type')?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('service')?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('degree')?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input id="grade_all" />
       		</div>
       	</div>
       	<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('start_date')?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('end_date')?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       	</div>
	</form>
<style>
#footer{display: none;}
</style>	
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm;">
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr class="line"><td colspan="3"></td></tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td width="15%" align="center">
				</td>
				<td align="center" width="70%">
					<strong style=" padding-left: 20px;font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('STUDENT_STOP_SERVICE_REPORT');?></strong>
					<div><strong​​ style=" font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php if(!empty($this->search['start_date'])){?><?php echo date('d-M-Y',strtotime($this->search['start_date']));?><?php echo $tr->translate('TO');?><?php echo date('d-M-Y',strtotime($this->search['end_date']));}?></strong></div>
				</td>
				<td width="15%" align="center">
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<style> th,td{ padding:0 1px;}</style>
				<style type="text/css">
						table{ border-collapse:collapse; margin:0 auto;
						border-color:#000; }
						.padd tr td{  }
						.padd tr th{  background-color: #ccc; }
						table {page-break-inside:auto }
						tr{ page-break-inside:avoid; page-break-after:auto; }
						#header {
						  display: table-header-group;
						  page-break-inside:avoid; page-break-after:auto;
						}	tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
				</style>
				<td colspan="3" id="exporteExcel">
					<table class="padd" width="99%" border="1" align="center" style="font-size:14px;white-space:nowrap;font-family: 'khmer os battambang',Arial,serif !important;">
								<style> td{padding:0 3px; }</style>
						  <?php
							$student_id =0;
						 	 $i=0; $total=0;if (!empty($this->rs)){ foreach($this->rs as $rs){ $i++;
						 	 if($rs['stu_id']!=$student_id){
						  ?><thead>
						  <tr style="border-left: 1px solid #fff; border-right: 1px solid #fff; border-top: 1px solid #fff;"><td colspan="8">&nbsp;</td></tr>
						  <tr style="font-size:10px; height: 23px; border-left: 1px solid #fff; border-right: 1px solid #fff; border-top: 1px solid #fff; "​>
						  	<td align="left" colspan="8">
						  		<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 12px;font-family:'Hanuman',Arial,serif !important;"><?php echo $tr->translate('STUDENT_ID').' : '.$rs['stu_code'] .' &nbsp;'.$tr->translate('STUDENT_NAME').' : '.$rs['en_name'].' &nbsp; '.$tr->translate('SEX').' : '.$rs['sex'].' &nbsp; '.$tr->translate('ACADEMIC_YEAR').' : '.$rs['academic'];?></strong><br />
						  	</td>
						  </tr>				  
						   <tr style="font-size:12px; height: 20px;background-color: #ccd9ff;line-height: 30px;font-weight: bold;" align="center">
						    <td>&nbsp;<?php echo $tr->translate('N_O')?>&nbsp;</td>
						    <td>&nbsp;<?php echo $tr->translate('SERVICE_TYPE')?>&nbsp;</td>
						    <td>&nbsp;<?php echo $tr->translate('SERVICE_NAME')?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate('SUSPEND_TYPE')?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate('REASON')?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate('NOTE')?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate('STOP_DATE')?>&nbsp;</td>
						  </tr>
						  <thead>
						 <?php  }
						 $student_id=$rs['stu_id'];
						 	 
						 ?>
						   <tr class="hover" style="font-size:11px; height: 18px; border-bottom: 1px solid #000;"​ align="center">
						  	<td><?php echo $i;?></td>
						   	<td><?php echo $rs['service_type']; ?></td>
						   	<td><?php echo $rs['service']; ?></td>
						  	<td><?php echo $rs['type_suspend']; ?></td>
						   	<td><?php echo $rs['reason']; ?></td>
						   	<td><?php echo $rs['note']; ?></td>
						   	<td><?php echo date("d/m/Y",strtotime($rs['define_date'])); ?></td>
						   </tr>
						  <?php } }?>
					</table>
				</td>
			</tr>
			<tr >
				<td colspan="3" width="100%">
					<?php echo $this->rsfooteracc;?>
				</td>
			</tr>
		</table>
	</div>
</div>

<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore"); 
	dojo.require("dijit.form.FilteringSelect"); 
	dojo.require("dojo.html");
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                        
			id: "grade_all",
			name: "grade_all",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  

			}
		}, "grade_all");
		getallGrade();
	});
	
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade_all').set('store',grade_store);   
				dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
			},
			error: function(err) {
				alert(err);
			}
		});
	}
</script>

