<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_FEE')); 
	$frm=$this->form_search;
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_FEE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-fee')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="<?php echo $tr->translate("SEARCH");?>" value="<?php echo $this->search['txtsearch'];?>" type="text">
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('branch_id')?>
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<input id="study_year" />
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('generation')?>
       		</div>
       	</div>
       	<div class="form-group">
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('degree')?>
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<input id="grade_all" />
       		</div>
       		<div class="col-md-3 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('finished_status')?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       	</div>
	</form>		
	<div id="divPrint">
			<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr >
					<td width="15%" align="center">
					</td>
					<td width="70%" align="center">
						<strong style="font-weight:bold;color:#000; font-size: 16px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate('RPT_FEE')?></strong><br />
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<style>
					table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
					tr{ page-break-inside:avoid; page-break-after:auto }
					.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap; font-size: 14px;}
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					}
				.hover:hover{background:#eee;}			
					tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }							
				</style>
				<tr>
					<td colspan="3" id="exportExcel">
						<table cellpadding="2"​ style=" font-family:'Khmer OS Battambang';margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;"  border="1" >
							<thead>
								<tr style="background: #ccd9ff;" class="cheader" align="center" >
									<td style="border: 1px solid #000;"><?php echo $tr->translate('N_O')?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate('BRANCH')?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate('ACADEMIC_YEAR')?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate('TYPE')?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate('DEGREE')?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate('GRADE')?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate('MONTHLY')?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate('QUARTER')?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate('SEMESTER')?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate('YEAR')?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate('NOTE')?></td>
								</tr>
							</thead>
						<?php $i=0; if(!empty($this->rs)){foreach ($this->rs AS $row) { $i++;?>
							<tr class="hover" style="font-size:12px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;"><?php echo @$row['branch_id'];?></td>
								<td style="border: 1px solid #000;"><?php echo @$row['academic'];?></td>
								<td style="border: 1px solid #000;"><?php echo @$row['generation'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;&nbsp;<?php echo @$row['degree'];?></td>	
								<td align="left" style="border: 1px solid #000;">&nbsp;&nbsp;<?php echo @$row['class'];?></td>	
								<td style="border: 1px solid #000;"><?php echo number_format(@$row['monthly'],2);?> $</td>
								<td style="border: 1px solid #000;"><?php echo number_format(@$row['quarter'],2);?> $</td>
								<td style="border: 1px solid #000;"><?php echo number_format(@$row['semester'],2);?> $</td>
								<td style="border: 1px solid #000;"><?php echo number_format(@$row['year'],2);?> $</td>
								<td style="border: 1px solid #000;"><?php echo @$row['remark'];?></td>
							</tr>
						<?php }}?>	
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3" width="100%">
						<table width="100%"  style="font-family: 'Khmer OS Battambang';">
							<tr>
								<td  width="25%" align="center">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
	</div>		
</div>


<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.store.Memory");
	dojo.require("dojo.data.ObjectStore");
	
	dojo.ready(function(){ 
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "study_year",
			name: "study_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  

			}
		}, "study_year");
		
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: true,                        
			id: "grade_all",
			name: "grade_all",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  

			}
		}, "grade_all");
		getallGrade();
		
		getAllAcademicByBranch();
	});

	url_getacademic = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
	function getAllAcademicByBranch(){
		dijit.byId('study_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('study_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getacademic,
			content:{
				'branch_id':branch_id
				},
			handleAs:"json",
			load: function(data){
				academic_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('study_year').set('store',academic_store);  
				
				dijit.byId('study_year').attr("value","<?php echo $this->search['study_year']?>");
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade_all').set('store',grade_store);   
				dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
			},
			error: function(err) {
				alert(err);
			}
		});
	}

</script> 