<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('CREDIT_MEMO_RePORT'));
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->frm_search;
?>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
	  	<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("adv_search");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('branch_id');?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('status');?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('paid_transfer');?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<select name="paid_type" id="paid_type" dojoType="dijit.form.FilteringSelect" class="fullside"  >
		        		<option value="0" <?php if($this->search['paid_type']==0){echo "selected='selected'";}?>><?php echo $tr->translate('SELECT_FORM_REPORT');?></option>
						<option value="1" <?php if($this->search['paid_type']==1){echo "selected='selected'";}?>>Credit Memo</option>
						<option value="2" <?php if($this->search['paid_type']==2){echo "selected='selected'";}?>>Credit Memo Transfer</option>	
		        	</select>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('by_date');?>
       		</div>
       	</div>
       	<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('start_date');?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement('end_date');?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">	
       			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       	</div>
	</form>
	<div id="divPrint">
		<style>
			#footer{display: none;}
			table {page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}	
				td{ padding: 1px !important;}
				tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
			</style>	
		<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
			<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
			<tr>
				<td width="15%" align="center">
				</td>
				<td width="70%" align="center">
				    <strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('CREDIT_MEMO_RePORT')?></strong><br />
					<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search["start_date"]))?><?php echo $tr->translate('TO')?><?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></strong>
				</td>
				<td width="15%" align="center"></td>
			</tr>
			<tr>
					<td>&nbsp;</td>
				</tr>
			<tr>
				<td colspan="3" >
					<div id="exportExcel">
								<?php if(!empty($this->all_memo)){?>
					            <table style="border-collapse:collapse;" width="100%"  cellspacing="0">
					                <tr>
					                    <td style="font-size:18px;font-weight: bold;">Credit Memo</td>
					                </tr>
					            </table>
								<table class="table" style="width:100%; border:1px solid #ddd; border-collapse: collapse;font-family:'Khmer OS Battambang';" >
									<thead>
									<tr style="background: #ccd9ff;font-weight: bold; font-size: 13px;">
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("N_O");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("BRANCH_NAME");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("STUDENT_CODE");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("STUDENT_NAME");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("TOTAL_AMOUNT");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("START_DATE");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("END_DATE");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("NOTE");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("PAID_TRANSFER");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("BY_USER");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("STATUS");?></th>
									</tr>
									</thead>
									<?php $num=1; $d_balance = 0;
									if(!empty($this->all_memo)){ foreach($this->all_memo as $key=>$rs){ $key=$key+1; ?>
									<tr>
										<td style="border:1px solid #000;text-align: center;"><?php echo $key; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['branch_name']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['stu_code']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['student_name']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo "$ ".number_format($rs["total_amount"],2);?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['date']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['end_date']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['note']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['paid_transfer']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['user_name']; ?></td>
										<?php if($rs['status']==1){ ?>
											<td style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("ACTIVE");?></td>
										<?php }else{ ?> 
											<td style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("DEACTIVE");?></td>
										<?php } ?>
									</tr>
									<?php
										$d_balance = $d_balance+$rs["total_amount"];
									}}
									?>
									</table>
									<table width="20%" align="right" style="margin-top: 5px;border-collapse: collapse;">
									<tbody>			                
						                <tr style="font-size:14px; height: 30px;border: 1px solid #000;font-weight: bold;" align="center" >
											<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="6"></td>
											<td bgcolor="#b0bdfd" style="border: 1px solid #000;white-space: nowrap;">ចំនួនទឹកប្រាក់សរុប</td>
										</tr>
										<tr style="font-size:14px; height: 30px;border: 1px solid #000;font-weight: bold;" align="center" >
											<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="6"></td>
											<td style="border: 1px solid #000;"><?php echo "$ ".number_format($d_balance,2);?></td>
										</tr>
					                </tbody>
					           		</table>
									</table>
								<?php }?>
								
								<?php if(!empty($this->all_memo_transfer)){?>
					            <table style="border-collapse:collapse;" width="100%"  cellspacing="0">
					                <tr>
					                    <td style="font-size:18px;font-weight: bold;">Credit Memo Transfer</td>
					                </tr>
					            </table>
								<table class="table" style="width:100%; border:1px solid #ddd; border-collapse: collapse;font-family:'Khmer OS Battambang';" >
									<thead>
									<tr style="background: #ccd9ff;font-weight: bold; font-size: 13px;">
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("N_O");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("BRANCH_NAME");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("STUDENT_CODE");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("INFORS_TO");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("STUDENT_CODE");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("INFORS_RECEIVE");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("TOTAL_AMOUNT");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("REASON_TO");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("REASON_RESIVE");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("BY_USER");?></th>
										<th style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("STATUS");?></th>
									</tr>
									</thead>
									<?php $num=1; $d_balance = 0;
									if(!empty($this->all_memo_transfer)){ foreach($this->all_memo_transfer as $key=>$rs){ $key=$key+1; ?>
									<tr>
										<td style="border:1px solid #000;text-align: center;"><?php echo $key; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['branch_name']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['stu_id']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['stu_idname']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['stu_idto']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['stu_name']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo "$ ".number_format($rs["total_amount"],2);?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['prob']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['problem']; ?></td>
										<td style="border:1px solid #000;text-align: center;"><?php echo $rs['user_name']; ?></td>
										<?php if($rs['status']==1){ ?>
											<td style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("ACTIVE");?></td>
										<?php }else{ ?> 
											<td style="border:1px solid #000;text-align: center;"><?php echo $tr->translate("DEACTIVE");?></td>
										<?php } ?>
									</tr>
									<?php
										$d_balance = $d_balance+$rs["total_amount"];
									}}
									?>
								</table>
								<table width="20%" align="right" style="margin-top: 5px;border-collapse: collapse;">
								<tbody>			                
					                <tr style="font-size:14px; height: 30px;border: 1px solid #000;font-weight: bold;" align="center" >
										<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="6"></td>
										<td bgcolor="#b0bdfd" style="border: 1px solid #000;white-space: nowrap;">ចំនួនទឹកប្រាក់សរុប</td>
									</tr>
									<tr style="font-size:14px; height: 30px;border: 1px solid #000;font-weight: bold;" align="center" >
										<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="6"></td>
										<td style="border: 1px solid #000;"><?php echo "$ ".number_format($d_balance,2);?></td>
									</tr>
				                </tbody>
				           		</table>
								<?php }?>
						</td>
					</tr>
					<tr>
						<td colspan="3">&nbsp;</td>
					</tr>
			  <tr>
				<td colspan="3" width="100%">
					<table width="100%" style="font-family:'Khmer OS Battambang';">
						<tr>
							<td  width="25%" align="center">
								<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY')?></span>
							</td>
							<td  width="50%">
								&nbsp;
							</td>
							<td align="center"  width="25%">
								<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY')?></span>
							</td>
						</tr>
					</table>
				</td>
			</tr>
	</div>	
</div>