<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_STOP_SERVICE_REPORT'));
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm=$this->form_search;
?>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_STOP_SERVICE_REPORT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>	
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-suspendservice')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-1 col-sm-1 col-xs-12">
				<?php echo $frm->getElement("adv_search");?>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement("branch_id");?>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
       			<input id="stu_name" />
       		</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<select name="category" id="category" class="fullside" dojoType="dijit.form.FilteringSelect" >
					<option value=""><?php echo $tr->translate('SELECT_CATEGORY')?></option>
					<?php if(!empty($this->category)){foreach($this->category as $cate){?>
					<option value="<?php echo $cate['id']?>" <?php if($cate['id']==$this->search['category']){echo "selected";}?>><?php echo $cate['name']?></option>
					<?php }}?>
				</select>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement("start_date");?>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement("end_date");?>
			</div>
			<div class="col-md-1 col-sm-2 col-xs-12 text-right">
				<button  iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</div>
       	</div>
	</form>
<style>
#footer{display: none;}
.hideprintdate{display:none !important;}
</style>	
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm;">
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr class="line"><td colspan="3"></td></tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td width="20%" align="center">
				</td>
				<td width="60%" align="center">
					<span style="padding-left: 0px;  color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate('STUDENT_STOP_SERVICE_REPORT')?></span><br />
					<span style="color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php if(!empty($this->search['start_date'])){?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> <?php echo $tr->translate('TO')?> <?php echo date("d-M-Y",strtotime($this->search["end_date"]));}?></span>     
				</td>
				<td width="20%" align="center">
					<label class='hideprintdate'>Print Date <?php echo date("d-m-Y h:i");?></label>
				</td>
			</tr>
			<tr>
				<style> th,td{ padding:0 1px;}</style>
				<style type="text/css">
						table{ border-collapse:collapse; margin:0 auto;
						border-color:#000; }
						.padd tr td{  }
						.padd tr th{  background-color: #ccc; }
						table {page-break-inside:auto }
						tr{ page-break-inside:avoid; page-break-after:auto; }
						#header {
						  display: table-header-group;
						  page-break-inside:avoid; page-break-after:auto;
						}	tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
						.hideprintdate{display:block;font-size:10px;white-space:nowrap;}
				</style>
				<td colspan="3" id="exporteExcel">
					<table class="padd" width="99%" border="1" align="center" style="font-size:14px;white-space:nowrap;font-family: Times New Roman,Khmer OS Battambang;">
						<style> td{padding:0 3px; }</style>
						<thead>
							<tr style="font-size:13px; height: 30px;background-color: #ccd9ff;font-weight: bold;" align="center">
								<td>&nbsp;<?php echo $tr->translate('N_O')?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('BRANCH')?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('STUDENT_ID')?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('STUDENT_NAME')?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('CATEGORY')?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('SERVICE')?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('REASON')?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('CREATE_DATE')?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('USER')?>&nbsp;</td>
							</tr>
						</thead>
						<?php $i=0; if(!empty($this->rs)){foreach($this->rs as $rs){$i++;?>
							<tr class="hover" style="font-size:12px; height: 25px; border-bottom: 1px solid #000;"​ align="center">
								<td><?php echo $i;?></td>
								<td><?php echo $rs['branch']; ?></td>
								<td><?php echo $rs['code']; ?></td>
								<td align="left"> <?php echo $rs['kh_name']." - ".$rs['en_name']; ?></td>
								<td align="left"><?php echo $rs['category']; ?></td>
								<td align="left"><?php echo $rs['service_name']; ?></td>
								<td align="left"> <?php echo $rs['reason']; ?></td>
								<td><?php echo date("d/m/Y",strtotime($rs['create_date'])); ?></td>
								<td><?php echo $rs['user']; ?></td>
							</tr>
						<?php } }?>
					</table>
				</td>
			</tr>
			<tr>
				<td colspan="3" width="100%">
					<?php echo $this->rsfooteracc;?>
				</td>
			</tr>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var student_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: student_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "stu_name",
			name: "stu_name",   
			required: false,        
			class: 'fullside', 
			placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
			onChange: function() { 

			}
		}, "stu_name");
		getallstudentname();
		var branch_id = dijit.byId('branch_id');
		branch_id.on('change', function(evt) {
			 getallstudentname();
		});
	});
	
	var url_data = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getallstudent')); ?>';
	function getallstudentname(){//
		dijit.byId('stu_name').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var student_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('stu_name').set('store',student_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url:url_data,
			content:{
				'branch_id':branch_id
			},
			handleAs:"json",
			load: function(data){
				student_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('stu_name').set('store',student_store);  
				dijit.byId('stu_name').set('value','<?php echo $this->search['stu_name']?>');  
			},
			error: function(err) {
			}
		});
	}
	
</script>