<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_NEARLY_END_REPORT')); 
	$frm =  $this->form_search;
?>	
<div style="min-height:15cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_NEARLY_END_REPORT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentnearlyendservice')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("adv_search");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("branch_id");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input id="study_year" />
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input id="group" />
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("degree");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input type="text" id="grade_all" />
       		</div>
       	</div>
       	<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("service_type");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<select required="false" type="text" name="item" id="item" placeHolder="<?php echo $tr->translate('SELECT_CATEGORY');?>" class="fullside" dojoType="dijit.form.FilteringSelect"  autoComplete="false" queryExpr="*${0}*" onchange="getgradebyDegree();" >
					<option value="-1"><?php echo $tr->translate('SELECT_CATEGORY');?></option>
					<?php if(!empty($this->rs_type)){foreach ($this->rs_type as $rs){?>
					<option value="<?php echo $rs['id']?>" <?php if($rs['id']== $this->search['item']){echo "selected";}?>><?php echo $rs['name']?></option>
					<?php }}?>
                </select>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input id="service" name="service" />
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("end_date");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       	</div>
	</form>	
	<div id="divPrint">
			<table style="background:#fff;width:100%; margin: 0 auto;width: 100%;">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="15%" align="center"></td>
					<td align="center" width="70%">
						<strong style="font-weight:normal;font-family: Arial Black;color:#000; font-size: 14px;font-family:'khmer os muol light';"><?php echo $tr->translate('STUDENT_NEARLY_END_REPORT');?></strong><br />
						<span​​ style="color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Battambang';"><?php if(!empty($this->search['end_date'])){?><?php echo date('d-M-Y',strtotime($this->search['end_date']));}?>  </span>
					</td>
					<td width="15%" align="center">&nbsp;</td>					
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<style>
					table{ page-break-inside:auto;font-family:Times New Roman,'Khmer OS Battambang'; }
					tr{ page-break-inside:avoid; page-break-after:auto }
					.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap; font-size: 14px;}
					#header {
						  display: table-header-group;
						  page-break-inside:avoid; page-break-after:auto;
					}
					.hover:hover{background: #ccc;}
					#exportExcel th{text-align: center;}
					tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
				</style>
				<tr>
					<td colspan="3">
					<div id="exportExcel">
						<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<thead>
								<tr style="font-weight:bold;font-size:12px; height: 25px;border: 1px solid #000;background: #ccd9ff;" align="center"  >
									<td>&nbsp;<?php echo $tr->translate("N_O"); ?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("BRANCH"); ?>&nbsp;</td>
									<td><?php echo $tr->translate("STUDENT_ID"); ?></td>
									<td>&nbsp;<?php echo $tr->translate("STUDENT_NAME"); ?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("SEX"); ?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("PHONE");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("STUDY_INFO");?>&nbsp;</td>
									<td><?php echo $tr->translate("SERVICE_TYPE"); ?></td>
									<td><?php echo $tr->translate("SERVICE_NAME"); ?></td>
								    <td><?php echo $tr->translate("PAID_DATE"); ?></td>
								    <td><?php echo $tr->translate("RECEIPT_NO"); ?></td>
									<td><?php echo $tr->translate("START_DATE"); ?></td>
									<td><?php echo $tr->translate("VALIDATE"); ?></td>
									<td><?php echo $tr->translate("REMAIN_DAY")."/".$tr->translate("LATE"); ?>(Days)</td>
									<td><?php echo $tr->translate("DETAIL"); ?></td>
								</tr>
							</thead>
						<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
						?>
							<tr class="hover" style="font-size:11px; height: 22px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo $row['stu_code'];?>&nbsp;</td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['stu_khname']." ".$row['last_name']." ".$row['first_name'];?></td>	
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['sex'];?></td>
								<td align="left" style="border: 1px solid #000;max-width:180px;white-space: normal;">&nbsp;<?php echo $row['tel'];?></td>
								<td align="left" style="border: 1px solid #000;max-width:180px;white-space: normal;">&nbsp;<?php //echo $row['group_name'].'/'.$row['grade'].'/'.$row['session'];?></td>
								<td align="left" style="border: 1px solid #000;max-width:180px;white-space: normal;">&nbsp;<?php echo $row['category_name'];?></td>
								<td align="left" style="border: 1px solid #000;max-width:180px;white-space: normal;">&nbsp;<?php  echo $row['service_name'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-m-Y",strtotime($row['create_date']));?>&nbsp;</td>
								<td align="left" style="border: 1px solid #000;max-width:180px;white-space: normal;">&nbsp;<a target="_blank" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptreceiptdetail','id'=>$row['payment_id']))?>"><?php echo $row['receipt'];?></a></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-m-Y",strtotime($row['start_date']));?>&nbsp;</td>
								<td style="border: 1px solid #000;color: red;">&nbsp;<?php echo date("d-m-Y",strtotime($row['end_date']));?>&nbsp;</td>
								<?php 
									$end_dat=$row['end_date'];
									$total_day=strtotime($end_dat)-strtotime($this->search['end_date']);
									$day=(int)($total_day/(60*60*24));
									$daylate =$day;
									if($day>=0){
										$daylate ="Remain ".abs($day);
									}else{
										$daylate ="Late ".abs($day);
									}
								?>
								<td align="center" style="border: 1px solid #000;color: red;font-weight: bold;">&nbsp;<?php echo $daylate;?></td>
								<td><a target="_blank" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptreceiptdetail','id'=>$row['payment_id']))?>"><?php echo $tr->translate('DETAIL');?></a></td>
 							</tr>
							<?php }}?>	 
						</table>
						</div>							
					</td>
				</tr>
				<tr >
					<td colspan="3">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
		</table>		
	</div>		
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var service_store = getDataStorefromJSON('id','name');

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
	    }
	}, "group");

	new dijit.form.FilteringSelect({
		store: service_store,
		autoComplete: false,
		queryExpr: "*${0}*",                     
		id: "service",
		name: "service",   
		required:false,        
		class: 'fullside',
		placeHolder:'<?php echo $tr->translate('SERVICE');?>',
		onChange: function() {  
		}
	}, "service");
	
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
    });
	 getAllAcademicByBranch();
	 getAllGroupByBranch();
	 getgradebyDegree();
});
url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id,'showall':1
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
		    }
		},
		error: function(err) {
		}
	});
}
url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1,'forfilter':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
		}
	});
}
</script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore"); 
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade_all",
			name: "grade_all",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
			}
		}, "grade_all");
		getallGrade();
	});
	var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade_all').set('store',grade_store);   
				dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
			},
			error: function(err) {
			}
		});
	}
	
var oldItems = '<?php echo $this->search['item']?>';
var url_degree = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-grade')); ?>';
function getgradebyDegree(){
		dept_id = dijit.byId("item").get("value");
		if(dept_id==-1){
			return false;
		}
		dojo.xhrPost({
			url:url_degree,
			content:{
				'dept_id':dept_id,
				},
			handleAs:"json",
			load: function(data) {
				service_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('service').set('store',service_store);  	
				//if(oldItems==dept_id){
					dijit.byId('service').set('value','<?php echo $this->search['service']?>');  	
				//}
			},
			error: function(err) {
			}
	});
}
</script>