<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_NEARLY_END_REPORT')); 
	$frm =  $this->form_search;
	$classHideHeight=classHideHeight;
?>	
<div style="min-height:15cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_NEARLY_END_REPORT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentnearlyendservice')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("adv_search");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("branch_id");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input id="study_year" />
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input id="group" />
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("degree");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input type="text" id="grade_all" />
       		</div>
       	</div>
       	<div class="form-group">
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("service_type");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<select required="false" type="text" name="item" id="item" placeHolder="<?php echo $tr->translate('SELECT_CATEGORY');?>" class="fullside" dojoType="dijit.form.FilteringSelect"  autoComplete="false" queryExpr="*${0}*" onchange="getgradebyDegree();" >
					<option value="-1"><?php echo $tr->translate('SELECT_CATEGORY');?></option>
					<?php if(!empty($this->rs_type)){foreach ($this->rs_type as $rs){?>
					<option value="<?php echo $rs['id']?>" <?php if($rs['id']== $this->search['item']){echo "selected";}?>><?php echo $rs['name']?></option>
					<?php }}?>
                </select>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<input id="service" name="service" />
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<?php echo $frm->getElement("end_date");?>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       			<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
       		</div>
       		<div class="col-md-2 col-sm-2 col-xs-12">
       		</div>
       	</div>
	</form>	
	<div id="divPrint">
			<table style="width:100%; white-space: nowrap;">
				<tr>
					<td colspan="2"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="2"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					
					<td align="center" width="100%" colspan="2">
						<strong style="font-weight:normal;font-family: Arial Black;color:#000; font-size: 12px;font-family:'khmer os muol light';"><?php echo $tr->translate('STUDENT_NEARLY_END_REPORT');?></strong><br />
						<span​​ style="color:#000; font-size: 12px;font-family:'Times New Roman','Khmer OS Battambang';"><?php if(!empty($this->search['end_date'])){?><?php echo date('d-M-Y',strtotime($this->search['end_date']));}?>  </span>
					</td>
									
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<style>
					.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table.content-data { page-break-inside:auto }
					tr.content-data{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:12px;
						width:100%;
				
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					
					
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:12px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:12px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:0 2px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					.redBold {
						font-weight: 600;
						color: #f80000;
					}
					table.content-data tr td{
						padding: 1px;
					}
					@media print{
						@page{
							margin:0.3cm 0.7cm 0cm 0.7cm;
							page-break-before: avoid;
							-webkit-transform: scale(0.5);  /* Chrome, Safari 3.1+  */
							-moz-transform: scale(0.5);  /* Firefox 3.5-15 */
							-ms-transform: scale(0.5);   /* IE 9 */
							-o-transform: scale(0.5);    /* Opera 10.50-12.00 */
							transform: scale(0.5);
							page: A4;
							size: landscape;
						}
					}
					
				</style>
				<tr>
					<td colspan="2" id="exportExcel" >
				
						<table cellpadding="2" class="content-data" border="1"  >
							<thead>
								<tr class="style" align="center" >
									<td scope="col">&nbsp;<?php echo $tr->translate("N_O"); ?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate("BRANCH"); ?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("STUDENT_ID"); ?></td>
									<td scope="col">&nbsp;<?php echo $tr->translate("STUDENT_NAME"); ?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate("SEX"); ?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate("PHONE");?>&nbsp;</td>
									<td scope="col">&nbsp;<?php echo $tr->translate("STUDY_INFO");?>&nbsp;</td>
									<td scope="col"><?php echo $tr->translate("SERVICE_TYPE"); ?></td>
									<td scope="col"><?php echo $tr->translate("SERVICE_NAME"); ?></td>
								    <td scope="col"><?php echo $tr->translate("PAID_DATE"); ?></td>
								    <td scope="col"><?php echo $tr->translate("RECEIPT_NO"); ?></td>
									<td scope="col"><?php echo $tr->translate("START_DATE"); ?></td>
									<td scope="col"><?php echo $tr->translate("VALIDATE"); ?></td>
									<td scope="col"><?php echo $tr->translate("REMAIN_DAY")."/".$tr->translate("LATE"); ?>(Days)</td>
									<td scope="col"><?php echo $tr->translate("DETAIL"); ?></td>
								</tr>
							</thead>
						<?php  $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
						?>
							<tr  class="style hover context-menu-one" oncontextmenu="setrowdata(<?php echo $row['payment_id_detail'];?>);return false;"  style="white-space:nowrap;">
								<td data-label="<?php echo $tr->translate("N_O");?>"  ><?php echo $i;?></td>
								<td data-label="<?php echo $tr->translate("BRANCH");?>"  >&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("STUDENT_ID");?>" >&nbsp;<?php echo $row['stu_code'];?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("STUDENT_NAME");?>"  class="stuName_<?php echo $row['payment_id_detail'];?>" ><?php echo $row['stu_khname']." ".$row['last_name']." ".$row['first_name'];?></td>	
								<td data-label="<?php echo $tr->translate("SEX");?>"  align="left" >&nbsp;<?php echo $row['sex'];?></td>
								<td data-label="<?php echo $tr->translate("PHONE");?>"  align="left" >&nbsp;<?php echo $row['tel'];?></td>
								<td data-label="<?php echo $tr->translate("STUDY_INFO");?>"  align="left" >&nbsp;<?php //echo $row['group_name'].'/'.$row['grade'].'/'.$row['session'];?></td>
								<td data-label="<?php echo $tr->translate("SERVICE_TYPE");?>"  align="left" >&nbsp;<?php echo $row['category_name'];?></td>
								<td data-label="<?php echo $tr->translate("SERVICE_NAME");?>" class="serviceName_<?php echo $row['payment_id_detail'];?>"  align="left" >&nbsp;<?php  echo $row['service_name'];?></td>
								<td data-label="<?php echo $tr->translate("PAID_DATE");?>"  >&nbsp;<?php echo date("d-m-Y",strtotime($row['create_date']));?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("RECEIPT_NO");?>"  align="left">&nbsp;<a target="_blank" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptreceiptdetail','id'=>$row['payment_id']))?>"><?php echo $row['receipt'];?></a></td>
								<td data-label="<?php echo $tr->translate("START_DATE");?>" >&nbsp;<?php echo date("d-m-Y",strtotime($row['start_date']));?>&nbsp;  <input type="hidden" dojoType="dijit.form.TextBox" name="start_date_<?php echo $row['payment_id_detail']; ?>" id="start_date_<?php echo $row['payment_id_detail']; ?>" value="<?php echo $row['start_date'];?>" /></td>
								<td data-label="<?php echo $tr->translate("VALIDATE");?>">&nbsp;<?php echo date("d-m-Y",strtotime($row['end_date']));?>&nbsp;  <input type="hidden" dojoType="dijit.form.TextBox" name="validate_<?php echo $row['payment_id_detail']; ?>" id="validate_<?php echo $row['payment_id_detail']; ?>" value="<?php echo $row['end_date'];?>" /></td>
								<?php 
									$end_dat=$row['end_date'];
									$total_day=strtotime($end_dat)-strtotime($this->search['end_date']);
									$day=(int)($total_day/(60*60*24));
									$daylate =$day;
									if($day>=0){
										$daylate ="Remain ".abs($day);
									}else{
										$daylate ="Late ".abs($day);
									}
								?>
								<td data-label="<?php echo $tr->translate("REMAIN_DAY");?>"  align="center" style="color: red;font-weight: bold;">&nbsp;<?php echo $daylate;?></td>
								<td data-label="<?php echo $tr->translate("DETAIL");?>" ><a target="_blank" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptreceiptdetail','id'=>$row['payment_id']))?>"><?php echo $tr->translate('DETAIL');?></a></td>
 							</tr>
							<?php }}?>	 
						</table>
											
					</td>
				</tr>
				<tr >
					<td colspan="2">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
		</table>		
	</div>		
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate('EDIT_VALIDATE');?>'"  id="updateForm" style="width:350px;" >
		<div class="card pb-10 pt-10 pl-10 pr-10">
			<form id="validateFormInfo"  name="data" action="" dojoType="dijit.form.Form" method="post">
				<div class="card-box">
					<div class="form-group">
						<div class="col-md-12 col-sm-12 col-xs-12 text-center bg-primary border rounded">
					  		<h5 class="card-title" id ="serviceName" ></h5>
							<h5 class="card-title" id ="stuName" ></h5>
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-12 col-sm-12 col-xs-12 ">
							&nbsp;
						</div>
					</div>
					<div class="form-group">
					   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate('START_DATE');?> :
					   </label>
					   <div class="col-md-7 col-sm-7 col-xs-12">
							<input  class="fullside" type="text" dojoType="dijit.form.DateTextBox" name="start_date" id="start_date" placeholder="<?php echo $tr->translate("START_DATE");?>" />
					   </div>
					</div>
					<div class="form-group">
					   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate('VALIDATE');?> :
					   </label>
					   <div class="col-md-7 col-sm-7 col-xs-12">
							<input  class="fullside" type="text" dojoType="dijit.form.DateTextBox" name="validate" id="validate" placeholder="<?php echo $tr->translate("VALIDATE");?>" />
					   </div>
					   <input type="hidden" dojoType="dijit.form.TextBox" name="id" id="id"  />
					</div>
				
					<div class="form-group">
						<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
							<input onclick="updateValidate();" type="button" value="1" label="<?php echo $tr->translate('EDIT');?>" id="busyButton" dojoType="dijit.form.Button" 
								class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" /> 
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var service_store = getDataStorefromJSON('id','name');

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
	    }
	}, "group");

	new dijit.form.FilteringSelect({
		store: service_store,
		autoComplete: false,
		queryExpr: "*${0}*",                     
		id: "service",
		name: "service",   
		required:false,        
		class: 'fullside',
		placeHolder:'<?php echo $tr->translate('SERVICE');?>',
		onChange: function() {  
		}
	}, "service");
	
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
    });
	 getAllAcademicByBranch();
	 getAllGroupByBranch();
	 getgradebyDegree();
});
url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	
		contentData = {
			'branch_id':branch_id
		}
		selectedId = '';
		if(oldBranch==branch_id){
			selectedId = '<?php echo $this->search['study_year']?>';
		}
		getAllYear(url_getacademic,contentData,selectedId,'study_year');
}
url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1,'forfilter':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
		}
	});
}
</script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore"); 
	dojo.require("dijit.form.Textarea");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade_all",
			name: "grade_all",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
			}
		}, "grade_all");
		getallGrade();
	});
	var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade_all').set('store',grade_store);   
				dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
			},
			error: function(err) {
			}
		});
	}
	
var oldItems = '<?php echo $this->search['item']?>';
var url_degree = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getgradebyDegree(){
		dept_id = dijit.byId("item").get("value");
		if(dept_id==-1){
			return false;
		}
		dojo.xhrPost({
			url:url_degree,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				service_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('service').set('store',service_store);  	
				//if(oldItems==dept_id){
					dijit.byId('service').set('value','<?php echo $this->search['service']?>');  	
				//}
			},
			error: function(err) {
			}
	});
}


var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="edit"){
				dijit.byId('id').set('value',row);

				var stuname = $(".stuName_"+row).html();
				var serviceName = $(".serviceName_"+row).html();
		
				document.getElementById('stuName').innerHTML = stuname;
				document.getElementById('serviceName').innerHTML = serviceName;
				var oldStartDate = dijit.byId("start_date_"+row).get("value");
				var oldValidate = dijit.byId("validate_"+row).get("value");
				dijit.byId('start_date').set('value',oldStartDate);
				dijit.byId('validate').set('value',oldValidate);
				dijit.byId('updateForm').show();
			}
		},
		items: {
			"edit": {name: "<?php echo $tr->translate("EDIT_VALIDATE");?>", icon: "fa-calendar"},
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	window.open(url+row);
}
var voidReciept = '<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'updatevalidate')); ?>';
	function updateValidate(){
		if(dijit.byId('validateFormInfo').validate()){
			if(confirm("<?php echo $tr->translate("Do you want to edit validate");?>")){
		}else{
			dijit.byId('validateFormInfo').reset();
			dijit.byId('updateForm').hide();
			return false;
		}
			loadingBlock();
			dojo.xhrPost({
				url: voidReciept,
				form: dojo.byId("validateFormInfo"),
				handleAs:"json",
				load: function(data){
					dijit.byId('validateFormInfo').reset();
					dijit.byId('updateForm').hide();
					if(data==1){
						alert("<?php echo $tr->translate("SUCCESS");?>");
					}
					location.reload();
					HideloadingBlock();
				},
				error: function(err){
					dijit.byId('validateFormInfo').reset();
					dijit.byId('updateForm').hide();
					HideloadingBlock();
				}
			});
		}
	}
</script>