<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Nearly End Service'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<?php
?>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentnearlyendservice')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td> <?php echo $frm->getElement("grade_all");?></td>
			<td> <?php echo $frm->getElement("session");?></td>
			<td> <?php echo $frm->getElement("service");?></td>
			<td>
				<input class="fullside" name="end_date" id="end_date" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" placeholder="end date" value="<?php echo $this->search['end_date'];?>" type="text">
			</td>
		</tr>
		<tr>
			<td> <?php echo $frm->getElement("stu_code");?></td>
			<td> <?php echo $frm->getElement("stu_name");?></td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<div id="divPrint">
		<div id="exportExcel">
			<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;">
				
				<tr>
					<td width="15%" align="center">
						<img style="width:60%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
					</td>
					<td align="center" width="70%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';">របាយការណ៏​​ សិស្សជិតដល់ថ្ងៃបង់លុយ</strong><br />
						<span style="font-weight: bold;font-size: 11px;">&nbsp;ON&nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));?></span>
					</td>
					<td width="15%" align="center">
						&nbsp;
					</td>
					
				</tr>
				<style>
					.hover:hover{background: #ccc;}
				</style>
				<tr>
					<td colspan="3">
						<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<tr style="font-size:12px; height: 20px;border: 1px solid #000;background: #ccc;" align="center"  >
								<td style="border: 1px solid #000;">&nbsp;N.o&nbsp;</td>
								<td style="border: 1px solid #000;">Code</td>
								<td style="border: 1px solid #000;">&nbsp;Student Name&nbsp;</td>
								<td style="border: 1px solid #000;">&nbsp;Sex&nbsp;</td>
								<td style="border: 1px solid #000;">&nbsp;Grade&nbsp;</td>
								<td style="border: 1px solid #000;">&nbsp;Session&nbsp;</td>
								<td style="border: 1px solid #000;">Service Name</td>
								<td style="border: 1px solid #000;">Paid Date</td>
								<td style="border: 1px solid #000;">Start Date</td>
								<td style="border: 1px solid #000;">Validate</td>
								<td style="border: 1px solid #000;">Remain (Days)</td>
								
							</tr>
						<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
													
							$end_dat=$row['end'];//date("Y-m-d");
							$total_day=strtotime($end_dat)-strtotime($this->search['end_date']);
							$day=(int)($total_day/(60*60*24));
						?>
							<tr class="hover" style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo $row['code'];?>&nbsp;</td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['name'];?></td>	
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['sex'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['grade'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['session'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['service'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['create_date']));?>&nbsp;</td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['start']));?>&nbsp;</td>
								<td style="border: 1px solid #000;color: red;">&nbsp;<?php echo date("d-M-Y",strtotime($row['end']));?>&nbsp;</td>
								<?php if($day>=0){
									$daylate ="Late ".abs($day);
								}else{
									$daylate ="Remain ".abs($day);
								}?>
								<td align="center" style="border: 1px solid #000;color: red;font-weight: bold;"<?php //if($day>=0){echo"background:red;color:#fff;";}?>">&nbsp;<?php echo $daylate;?> days</td>
 													</tr>
												<?php }}?>	 
						</table>	
					</td>
				</tr>
				
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3">
						<table width="100%" style="font-family: 'Khmer OS Battambang';">
							<tr>
								<td align="center" width="25%">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY');?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARED_BY');?></span>
								</td>
							</tr>
						</table>
					</td>
						
				</tr>
			</table>
		</div>			
	</div>		
</div>





