<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:415px;" align="center" data-dojo-props="title:'<?php echo $tr->translate("CALCULATOR");?>'" id="popupCalculator" >
		<div class="container text-center" id="calc" style="padding: 0;">
		  <div class="calcBG col-md-12  text-center">
		    <div class="row" id="result">
		      <form name="calc">
		        <input type="text" class="screen text-right" name="result" id="result">
		      </form>
		    </div>
		    <div class="row">
		      <button id="allClear" type="button" class="btn btn-danger" onclick="clearScreen()">AC</button>
		      <button id="clear" type="button" class="btn btn-warning operator-group-light" onclick="clearScreen()">CE</button>
		      <button id="clearone" type="button" class="btn btn-warning operator-group-light" onclick="clearOne()">⌫</button>
		      <button id="%" type="button" class="btn btn-info operator-group-light" onclick="myFunction(this.id)">%</button>
		    </div>
		    <div class="row">
		      <button id="7" type="button" class="btn btn-info" onclick="myFunction(this.id)">7</button>
		      <button id="8" type="button" class="btn btn-info" onclick="myFunction(this.id)">8</button>
		      <button id="9" type="button" class="btn btn-info" onclick="myFunction(this.id)">9</button>
		      <button id="/" type="button" class="btn btn-info operator-group-light" onclick="myFunction(this.id)">÷</button>
		      
		    </div>
		    <div class="row">
		      <button id="4" type="button" class="btn btn-info" onclick="myFunction(this.id)">4</button>
		      <button id="5" type="button" class="btn btn-info" onclick="myFunction(this.id)">5</button>
		      <button id="6" type="button" class="btn btn-info" onclick="myFunction(this.id)">6</button>
		      <button id="*" type="button" class="btn btn-info operator-group-light" onclick="myFunction(this.id)">x</button>
		    </div>
		    <div class="row">
		      <button id="1" type="button" class="btn btn-info" onclick="myFunction(this.id)">1</button>
		      <button id="2" type="button" class="btn btn-info" onclick="myFunction(this.id)">2</button>
		      <button id="3" type="button" class="btn btn-info" onclick="myFunction(this.id)">3</button>
		      <button id="-" type="button" class="btn btn-info operator-group-light" onclick="myFunction(this.id)">-</button>
		    </div>
		    <div class="row">
		      <button id="0" type="button" class="btn btn-info" onclick="myFunction(this.id)">0</button>
		      <button id="." type="button" class="btn btn-info" onclick="myFunction(this.id)">.</button>
		      <button id="equals" type="button" class="btn operator-group-light" onclick="calculate()">=</button>
		      <button id="+" type="button" class="btn btn-info operator-group-light" onclick="myFunction(this.id)">+</button>
		    </div>
		  </div>
		</div>
	</div>
</div>
<style>
#popupCalculator button {
  	width: 65px;
    height: 45px;
    font-family: 'Roboto', sans-serif;
    border: none;
        font-weight: 700;
    border-radius: 5px;
    outline: none !important;
    position: relative;
    transition: all 0.1s;
    
    background-color: #90a4ae;
    border-color: #90a4ae;
    color: black;
    box-shadow: 0px 5px 0px #6b8694;
}
#popupCalculator button.operator-group-light {
    background-color: #546e7a;
    border-color: #546e7a;
    color: #ffffff;
    box-shadow: 0px 5px 0px #3f525a;
}
#popupCalculator *:focus {
    outline: 0 !important;
}
#popupCalculator #allClear {
 	background-color: #f44336;
    border-color: #f44336;
    color: #ffffff;
    box-shadow: 0px 5px 0px #c2160a;
    color: #ffffff;
}
#popupCalculator #clearone,
#popupCalculator #clear {
  	background-color: #ff9800;
    border-color: #ff9800;
    color: #ffffff;
    box-shadow: 0px 5px 0px #cc7a00;
    color: #ffffff;
}
#popupCalculator #equals{
     background-color: #4caf50;
    border-color: #4caf50;
    color: #ffffff;
    box-shadow: 0px 5px 0px #3e8e41;
    color: #ffffff;
}
/* Hidden button for formatting sake */
#popupCalculator #blank {
  visibility: hidden;
}
#popupCalculator .calcBG {
  	border-radius: 0;
    background-color: #cfd8dc;
    border: 1px solid #cfd8dc;
}
#popupCalculator .screen {
    height: 40px;
        width: 90%;
    border-radius: 10px;
    padding: 10px;
    margin: 10px 2px;
    font-size: 16px;
    font-weight: bold;
    background: #d5e3ef;
    background: -webkit-linear-gradient(to right, #d5e3ef , #eef2f3);
    background: linear-gradient(to right, #d5e3ef , #eef2f3);
    box-shadow: 0px 4px #9292ad inset;
  
}
#popupCalculator small {
  color: #fff;
  font-weight: bold;
}
div#popupCalculator .dijitDialogPaneContent {
    padding: 0 !important;
}
div#calc {
    width: 415px !important;
}
</style>
<script>
//Determines button clicked via id
function myFunction(id) {
  document.calc.result.value+=id;
}

// Clears calculator input screen
function clearScreen() {
  document.calc.result.value="";
}

function clearOne() {
	var bla = document.calc.result.value;
  document.calc.result.value = (bla.slice(0, -1));
}
	
// Calculates input values
function calculate() {
  try {
    var input = eval(document.calc.result.value);
    document.calc.result.value=input;
  } catch(err){
      document.calc.result.value="Error";
    }
}
</script>