	<?php
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
	$other=$acl=$this->url(array('module'=>'allreport','controller'=>'other','action'=>'index'), null, true);
	$registrar=$acl=$this->url(array('module'=>'allreport','controller'=>'receiptionist','action'=>'index'), null, true);
	$accoutning=$acl=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'index'), null, true);
	$fundation=$acl=$this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'index'), null, true);
	$allstudent=$acl=$this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'index'), null, true);
	$otherExpense = $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-other-expense'), null, true);
	$otherIncome = $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-other-income'), null, true);
	$library=$acl=$this->url(array('module'=>'allreport','controller'=>'library','action'=>'index'), null, true);
	
	$dailyReport = $this->url(array('module'=>'registrar','controller'=>'allreports','action'=>'rpt-daily'), null, true);
	
	/*--------------------URLs link display--------------------------*/
		  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
		  $session_user=new Zend_Session_Namespace('authstu');
		  $arr_module = $session_user->arr_acl;
// 		  print_r($arr_module);exit();
		  $menu = array();
		  $module = '';
		  $controller=array();
		  $newarray=array();
		  if(!empty($arr_module)){
		  	foreach ($arr_module as $key => $rs){
		  		
		  		$lblcontroller = $rs['label'];
		  		// 			if($rs['controller']=='index' AND $rs['module']=='group' ){
		  		// 				$lblcontroller='CLIENT_INFO';
		  		// 			}
		  		// 			if($rs['controller']=='index' AND $rs['module']=='loan' ){
		  		// 				$lblcontroller='IL_DISBURSE';
		  		// 			}
		  		// 			if($rs['controller']=='index' AND $rs['module']=='other' ){
		  		// 				$lblcontroller='province';
		  		// 			}
		  		// 			if($rs['controller']=='loantype' AND $rs['module']=='other' ){
		  		// 				$lblcontroller='OTHER';
		  		// 			}
		  		// 			if($rs['controller']=='term' AND $rs['module']=='other' ){
		  		// 				$lblcontroller='termcondition';
		  		// 			}
		  		if($module!=$rs['module']){
		  			$newarray= array($rs['controller']=>'<li><a href="">'.$tr->translate(($lblcontroller)).'</a></li>');
		  			$menu[$rs['module']]= $newarray;
		  			$old_module=$rs['module'];
		  		}else{
		  			$newarray= array_merge($newarray,array($rs['controller']=>'<li><a href="">'.$tr->translate(($lblcontroller)).'</a></li>'));
		  			$menu[$rs['module']] = $newarray;
		  		}
		  		$module=$rs['module'];
		  	}
		  }
		  $arr_param_menu = $menu;
		
	

	?>
	<div id="header-left">
		<ul>
			<?php 
	// 				$request=Zend_Controller_Front::getInstance()->getRequest();
				if($request->getModuleName()!='report'){
					if($request->getModuleName()!='default' AND $action!='changepassword' ){
						$dc=new Application_Model_Decorator();					
						$class="current-left";					
						$menu=@$dc->getMenuLeft($arr_param_menu[$request->getModuleName()],$request->getControllerName(),$request->getModuleName());
						//print_r($arr_param_menu[$request->getModuleName()]);
						if($menu) echo $menu;	
					 }		
				}				
			?>
		</ul>																
	</div>