<?php
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
	
	/*--------------------URLs link display--------------------------*/
		  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
		  $session_user=new Zend_Session_Namespace(SYSTEM_SES);
		  $arr_module = $session_user->arr_acl;
		  $menu = array();
		  $module = '';
		  $controller=array();
		  $newarray=array();
		  if(!empty($arr_module)){
		  	foreach ($arr_module as $key => $rs){
		  		$lblcontroller = $rs['label'];
		  		if($module!=$rs['module']){
		  			$newarray= array($rs['controller']=>$tr->translate(($lblcontroller)));
		  			$menu[$rs['module']]= $newarray;
		  			$old_module=$rs['module'];
		  		}else{
		  			$newarray= array_merge($newarray,array($rs['controller']=>$tr->translate(($lblcontroller))));
		  			$menu[$rs['module']] = $newarray;
		  		}
		  		$module=$rs['module'];
		  	}
		  }
		  $arr_param_menu = $menu;
		  $module = $request->getModuleName();
		  $controller = $request->getControllerName();
	?>
	<?php 
	$array_icon = array(
      		'home'=>'<i class="glyphicon glyphicon-home" aria-hidden="true"></i>',
			'test'=>'<i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>',
      		'registrar'=>'<i class="fa fa-graduation-cap" aria-hidden="true"></i>',
      		'global'=>'<i class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></i>',
      		'foundation'=>'<i class="glyphicon glyphicon-blackboard" aria-hidden="true"></i>',
			'issue'=>'<i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>',
      		'accounting'=>'<i class="fa fa-money" aria-hidden="true"></i>',
      		'stock'=>'<i class="fa fa-cubes" aria-hidden="true"></i>',
			'library'=>'<i class="fa  fa-book" aria-hidden="true"></i>',
			'mobileapp'=>'<i class="fa fa-apple" aria-hidden="true"></i>',
      		'allreport'=>'<i class="fa  fa-file-text" aria-hidden="true"></i>',
      		'rsvacl'=>'<i class="fa  fa-cog" aria-hidden="true"></i>',
      		'setting'=>'<i class="fa  fa-database" aria-hidden="true"></i>',
			'placement'=>'<i class="fa  fa-edit" aria-hidden="true"></i>',
			'scan'=>'<i class="fa fa-qrcode" aria-hidden="true"></i>',
      		
      );
	
	$arr_module = $session_user->arr_module;
	$arr_acl = $session_user->arr_acl;
	?>
	<!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
              &nbsp;
               <?php 
					$db = new Application_Model_DbTable_DbUsers();
					$rs = $db->getAccessUrl("registrar","register","add");
					if(!empty($rs)){
				?>
			<div class="button-make-loan mb-10">
				<a href="<?php echo $this->baseUrl()."/registrar/register/add"?>"  class="closebtn-makesale"  ><i class="fa fa-graduation-cap" ></i> <?php echo $tr->translate("REGISTER");?> </a>
			</div>
			<?php }?>
                <ul class="nav side-menu">
                	<?php if(!empty($arr_module)){ foreach ($arr_module as $rs){
                		$url =$this->url(array('module'=>$rs,'controller'=>'index','action'=>'index'), null, true);
                		if ($rs=="project"){
                			$title=$tr->translate("JOBS");
                		}else if ($rs=="test"){
                			$title=$tr->translate("STUDENTTEST");
                		}else if ($rs=="issue"){
                			$title=$tr->translate("STUDENT_AFFAIR");
                		}
                		else{
                			$title=$tr->translate(strtoupper($rs));
                		}
                	?>
                	<li <?php if ($rs==$module ){ echo 'class="active"';}?> >
                		<?php if ($rs=="report"){?>
                			<a href="<?php echo $this->url(array('module'=>$rs,'controller'=>'index','action'=>'index'), null, true);;?>">
                			<?php echo $array_icon[$rs];?> <?php echo $title;?> 
	                		</a>
                		<?php }else{?>
                		
                			<?php if (count($arr_param_menu[$rs])>1){?>
	                		<a><?php echo $array_icon[$rs];?> <?php echo $title;?> 
	                		<?php if (!empty($arr_param_menu[$rs])){?><span class="fa fa-chevron-down"></span><?php }?>
	                		</a>
	                		<?php if (!empty($arr_param_menu[$rs])){?>
		                    <ul class="nav child_menu" <?php if ($rs==$module ){ echo 'style="display: block;"';}?>>
		                       <?php  foreach ($arr_param_menu[$rs] as $key => $sub){
		                       	$urlsub = $this->url(array('module'=>$rs,'controller'=>$key,'action'=>'index'), null, true);
		                       	?>
		                      <li <?php if ($rs==$module AND $key==$controller){ echo 'class="current-page"';}?> ><a href="<?php echo $urlsub;?>"><?php echo $sub;?></a></li>
		                       <?php }?>
		                    </ul>
		                    <?php }?>
	                    <?php }else{?>
	                    	<?php  foreach ($arr_param_menu[$rs] as $key => $sub){
		                       	$urlsub = $this->url(array('module'=>$rs,'controller'=>$key,'action'=>'index'), null, true);
		                       	$title=$tr->translate(strtoupper($key));
		                       	if($rs=='foundation' AND $key=='register'){
		                       		$title=$tr->translate('STUDENT_INFO');
		                       	}
		                       	if($rs=='global' AND $key=='term'){
		                       		$title=$tr->translate('START_DATE_END_DATE');
		                       	}
		                       	if ($rs=="home" and $key=="index" ){
		                       		$title=$tr->translate(strtoupper($rs));
		                       	}else if ($rs=="test" AND $key=="index"){
                					$title=$tr->translate("STUDENT_TEST");
		                       	}
		                       	?>
		                    <a href="<?php echo $urlsub;?>">
                			<?php echo $array_icon[$rs];?> <?php echo $title;?> 
	                		</a>
	                		<?php }?>
	                    <?php }?>
                    <?php }?>
                 	 </li>
                	<?php }
                	}?>
                </ul>
              </div>
            </div>