<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('UPDATE_STUDENT_DISCOUNT')); 
	$frm =  $this->form_search;
?>	
<head>
 <link href="<?php echo $this->baseUrl()."/jsmultiselect"?>/multi-select.css" media="screen" rel="stylesheet" type="text/css" />
<style>
a.btnstyle{background:#337ab7;padding:6px;border-radius:5px;color:#fff;border:1px solid #265074;}
a.btnstyle:hover{color:#eee;}
</style>

</head>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		   			<h4 class="m-b-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('UPDATE_STUDENT_DISCOUNT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
			<form id='submitgroup' dojoType="dijit.form.Form" action="<?php echo $this->url(array('module'=>'accounting','controller'=>'updatestudentdiscount','action'=>'submit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<script type="dojo/method" event="onSubmit">			
					if(this.validate()) {

						updateOption = dijit.byId('updateOption').get('value');
						if(updateOption==''){
							alert('<?php echo $tr->translate("SELECT_TYPE");?>');
							dijit.byId('updateOption').focus();
							return false;
						}
						if(updateOption==2){	
						 	discountSettengId = dijit.byId('discountSettengId').get('value');
							if(discountSettengId==''){
								alert('<?php echo $tr->translate("SELECT_DISCOUNT");?>');
								dijit.byId('discountSettengId').focus();
								return false;
							}
						}		
					
						discountStatus = dijit.byId('discountStatus').get('value');
						if(discountStatus==1){
							toDiscountId = dijit.byId('toDiscountId').get('value');
							if(toDiscountId=='' || toDiscountId==-1){
								alert('<?php echo $tr->translate("SELECT_DISCOUNT");?>');
								dijit.byId('toDiscountId').focus();
								return false;
							}
						}
						loadingBlock();	
						return true;
	   				}else {
						return false;
	   				}
				</script>
	    		<div class="card-box">
					<div class="col-md-8 col-sm-8 col-xs-12 ">
						<div class="x_panel">
							<div class="x_title">
								<h2><i class="fa fa-filter"></i> <?php echo $tr->translate("FILTERING");?> <small><?php echo $tr->translate("STUDENT_LIST");?></small></h2>
								<ul class="nav navbar-right panel_toolbox">
								  <li>
									<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
								  </li>
								</ul>
								<div class="clearfix"></div>
							</div>
							<div class="x_content" >
								<div class="card-blogform">
									<div class="card-body"> 
										<div class="row">
											<div class="col-md-6 col-sm-6 col-xs-12 ">
												<div class="card-blogform">
													<div class="card-body"> 
														<div class="row"> 
															<div class="col-md-12 col-sm-12 col-xs-12">
																<div class="d-flex"> 
																	<div class="settings-main-icon ">
																		<i class="glyphicon glyphicon-education"></i>
																	</div> 
																	<div class="col-md-10 col-sm-10 col-xs-12"> 
																		<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("TYPE");?></p>
																	</div> 
																</div>
																<div class="form-group">
																	<div class="col-md-12 col-sm-12 col-xs-12">
																		<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE");?> </label>
																		<div class="col-md-7 col-sm-7 col-xs-12">
																			<?php echo $frm->getElement("updateOption");?>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
												<div class="card-blogform">
													<div class="card-body"> 
														<div class="row"> 
															<div class="col-md-12 col-sm-12 col-xs-12">
																<div class="d-flex"> 
																	<div class="settings-main-icon ">
																		<i class="glyphicon glyphicon-education"></i>
																	</div> 
																	<div class="col-md-10 col-sm-10 col-xs-12"> 
																		<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT_INFO");?></p>
																	</div> 
																</div>
																<div class="form-group">
																	<div class="col-md-12 col-sm-12 col-xs-12">
																		<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
																		<div class="col-md-7 col-sm-7 col-xs-12">
																			<?php echo $frm->getElement("branch_id");?>
																		</div>
																	</div>
																</div>
																<div class="form-group curent_discount_display">
																	<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("OLD_DISCOUNT");?>  :
																	</label>
																	<div class="col-md-7 col-sm-7 col-xs-12">
																		<input id="discountSettengId" />
																	</div>
																</div>
																<div class="form-group">
																	<div class="col-md-12 col-sm-12 col-xs-12">
																		<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ACADEMIC_YEAR_ENROLL");?> </label>
																		<div class="col-md-7 col-sm-7 col-xs-12">
																			<?php echo $frm->getElement("academicYearEnroll");?>
																		</div>
																	</div>
																</div>
																<div class="form-group">
																	<div class="col-md-12 col-sm-12 col-xs-12">
																		<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_TYPE");?> </label>
																		<div class="col-md-7 col-sm-7 col-xs-12">
																			<?php echo $frm->getElement("studentType");?>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div> 

											<div class="col-md-6 col-sm-6 col-xs-12 ">
												<div class="card-blogform">
													<div class="card-body"> 
														<div class="row"> 
															<div class="col-md-12 col-sm-12 col-xs-12">
																<div class="d-flex"> 
																	<div class="settings-main-icon ">
																		<i class="glyphicon glyphicon-education"></i>
																	</div> 
																	<div class="col-md-10 col-sm-10 col-xs-12"> 
																		<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDY_INFO");?></p>
																	</div> 
																</div>	
																<div class="form-group academic_display">
																	<div class="col-md-12 col-sm-12 col-xs-12">
																		<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ACADEMIC_YEAR");?> </label>
																		<div class="col-md-7 col-sm-7 col-xs-12">
																			<?php echo $frm->getElement("academic_year");?>
																		</div>
																	</div>
																</div>
																
																<div class="form-group">
																	<div class="col-md-12 col-sm-12 col-xs-12">
																		<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DEGREE");?> </label>
																		<div class="col-md-7 col-sm-7 col-xs-12">
																			<?php echo $frm->getElement("degree");?>
																		</div>
																	</div>
																</div>
																<div class="form-group">
																	<div class="col-md-12 col-sm-12 col-xs-12">
																		<div class="form-group">
																		<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GRADE");?>  :
																		</label>
																		<div class="col-md-7 col-sm-7 col-xs-12">
																				<input id="grade" />
																		</div>
																		</div>
																	</div>
																</div>
																<div class="form-group">
																	<div class="col-md-12 col-sm-12 col-xs-12">
																		<div class="form-group">
																		<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SEARCH")?>  :
																		</label>
																		<div class="col-md-7 col-sm-7 col-xs-12">
																				<?php echo $frm->getElement("adv_search");?>
																		</div>
																		</div>
																	</div>
																</div>
																<div class="form-group">
																	<div class="col-md-12 col-sm-12 col-xs-12">
																		<div class="form-group">
																		<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("LIMIT")?>  :
																		</label>
																		<div class="col-md-7 col-sm-7 col-xs-12">
																				<?php echo $frm->getElement("limit");?>
																		</div>
																		</div>
																	</div>
																</div>
																<div class="form-group">
																	<label class="control-label  col-md-5 col-sm-5 col-xs-12" >
																	<?php echo $tr->translate("STUDENT_INFO");?>
																	</label>
																	<div class="col-md-7 col-sm-7 col-xs-12">
																		<input class="button-class button-primary" iconClass="glyphicon glyphicon-refresh" type="button" label="<?php echo $tr->translate('GET_STUDENT');?>" dojoType="dijit.form.Button" onclick="getStudentFromGroup();"/>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>

										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="card-box" style="margin-top: 10px;">
							<div class="col-md-12 col-sm-12 col-xs-12">
								<div class="d-flex"> 
									<div class="settings-main-icon ">
										<i class="fa fa-users" aria-hidden="true"></i>
									</div> 
									<div class="col-md-8 col-sm-8 col-xs-12"> 
										<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDENT_LIST");?></p>
									</div> 
									<div class="col-md-2 col-sm-2 col-xs-12 ">
										<input  dojoType="dijit.form.Button" onclick="doPrintRowCheck();" label="<?php echo $tr->translate("PREVIEW");?>" 
										class="button-class button-warning " iconClass="glyphicon glyphicon-print"/>
									</div>
								</div>
								<div class="form-group">&nbsp;</div>
								<div class="form-group" style="min-height: 300px !important;overflow-y: auto; padding: 5px; border: solid 1px #ccc;">
									<div id="divPrint">
										<style>
											ul.listFor {
												list-style: none;
												margin: 0;
												padding: 10px;
												border: solid 1px #02014a;
												width: 100%;
												display: block;
												background: #feffca;
												border-radius: 5px;
											}
											li.row-value {
												display: inline-block;
												width: 50%;
											}
											li.row-value span.title {
												min-width: 22%;
												display: inline-block;
												font-weight: 600;
												color: #0063a5;
											}
											li.row-value span.value {
												color: #02014a;
											}

											table#table {
												border: 1px solid #000;
												border-collapse: collapse;
												font-size: 12px;
												background-color: white;
												width: 99.5%;
												font-family: 'Times New Roman','Khmer OS Battambang';
											}
											table#table tr.header-row td {
												background: #02014a;
												font-size: 14px;
												font-weight: bold;
												color: #fff;
												padding: 5px 1px;
											}
											table#table tr td {
												padding: 3px 1px;
											}
										</style>
										<div id="data_table"  class="col-md-12 col-sm-12 col-xs-12">
										</div>
										<input type="hidden" name="all_student" id="all_student" dojoType="dijit.form.TextBox"  />
									</div>
								</div>
							</div>
							<div class="clearfix"></div>
						</div>

					</div>

					<div class="col-md-4 col-sm-4 col-xs-12">
						<div class="card-blogform">
							<div class="card-body"> 
								<div class="row"> 
									<div class="col-md-12 col-sm-12 col-xs-12">
										<div class="d-flex"> 
											<div class="settings-main-icon ">
												<i class="glyphicon glyphicon-tags"></i>
											</div> 
											<div class="col-md-10 col-sm-10 col-xs-12"> 
												<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("NEW_DISCOUNT_INFORMATION");?></p>
											</div> 
										</div>

										<div class="form-group adiscountStatus_display">
											<div class="col-md-12 col-sm-12 col-xs-12">
												<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DISCOUNT_STATUS");?> </label>
												<div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement("discountStatus");?>
												</div>
											</div>
										</div>

										<div class="form-group new_discount_display">
											<label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NEW_DISCOUNT");?> :
											</label>
											<div class="col-md-7 col-sm-7 col-xs-12">
											
												<input id="toDiscountId" />
												<input type="hidden" name="branch" id="branch" dojoType="dijit.form.TextBox" /> 
												<input type="hidden" name="oldDiscountSettengId" id="oldDiscountSettengId" dojoType="dijit.form.TextBox" /> 
												<input type="hidden" name="type" id="type" dojoType="dijit.form.TextBox" /> 
												<input type="hidden" dojoType="dijit.form.TextBox"  name="identity" id="identity" />
											</div>
										</div>
										<div class="form-group">
											<div class="col-md-12 col-sm-12 col-xs-12">
													<div class="card-blogform">
														<div class="card-body"> 
															<div class="row"> 
																<div class="col-md-12 col-sm-12 col-xs-12"> 
																	<div id="new-discount-info"></div>
																</div>
															</div>
														</div>
													</div>
											</div>
										</div>
										<div class="form-group">
											<div class="col-md-12 col-sm-12 col-xs-12">
													<div class="col-md-6 col-sm-6 col-xs-12 ">
													</div>
													<div class="col-md-6 col-sm-6 col-xs-12">
														<input type="submit" id="save_close" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("SAVE");?>" 
														class="button-class button-primary" iconClass="	glyphicon glyphicon-floppy-saved"/>
													</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
		            </div>
	        		<div class="clearfix"></div>
	   			</div>
			</form>
	</div>
</div>

<style>
select{ width:100%;}
fieldset{  background:#DFF7FD;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:0px solid #ccc;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
table .set-style tr td a {
    font-size: 14px;
}
.ms-container .ms-selectable {
    margin: 0 3.2%;
}
.search-blog {
    background: #bcd5f0;
    border-radius: 5px;
}

.ms-container .ms-selectable li.ms-elem-selectable, .ms-container .ms-selection li.ms-elem-selection {
    font-size: 13px;
    white-space: nowrap;
    color: #000;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/jquery.multi-select.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/rainbow.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()."/jsmultiselect"?>/application.js" type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.NodeList-manipulate");
dojo.require('dijit.form.Textarea');
dojo.require("dojo.data.ItemFileWriteStore"); 


dojo.ready(function(){

	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete:false,                     
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                     
		id: "discountSettengId",
		name: "discountSettengId",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_DISCOUNT");?>",          
		onChange: function() {  
			discountSettengId = dijit.byId('discountSettengId').get('value');
			dijit.byId('oldDiscountSettengId').attr('value',discountSettengId);

			dojo.byId('data_table').innerHTML = "";
			$("#identity").val('');

			//getDiscounInfoById();
		}
	}, "discountSettengId");

	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete:false,                     
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                     
		id: "toDiscountId",
		name: "toDiscountId",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_DISCOUNT");?>",          
		onChange: function() {  
			getNewDiscountInfoById();
		}
	}, "toDiscountId");
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete:false,                     
		queryExpr: "*${0}*",
		autoComplete:false,                     
		required: false,                     
		id: "grade",
		name: "grade",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
			//getNewDiscountInfoById();
		}
	}, "grade");
	
	var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllDiscountSetting();
  	});

	var updateOption = dijit.byId('updateOption');
	updateOption.on('change', function(evt) {
		
		 dojo.byId('data_table').innerHTML = "";
		 $("#identity").val('');

		 OptionChange();
  	});

	var discountStatus = dijit.byId('discountStatus');
	discountStatus.on('change', function(evt) {
		changeDisocuntStatus();
  	});

	 oldDiscountSettengId='<?php echo $this->search['discountSettengId'];?>';
	 oldGrade='<?php echo $this->search['grade'];?>';
	 getAllDiscountSetting();
	 getallGrade();
	 OptionChange();
});


var url_get_all_student_from_group = "<?php echo $this->url(array('module'=>'accounting','controller'=>'updatestudentdiscount','action'=>'get-all-student')); ?>";
function getStudentFromGroup(){
	loadingBlock()
	$("#identity").val('');

	updateOption = dijit.byId('updateOption').get('value');
	if(updateOption==0 || updateOption==""){
		alert('<?php echo $tr->translate('SELECT_TYPE'); ?>');
		dijit.byId('updateOption').focus();
		dojo.byId('data_table').innerHTML = "";
		HideloadingBlock();
		return false;
	}

	discountSettengId = dijit.byId('discountSettengId').get('value');
	if(updateOption==2){
		if(discountSettengId==0 || discountSettengId==""){
			alert('<?php echo $tr->translate('SELECT_DISCOUNT'); ?>');
			dijit.byId('discountSettengId').focus();
			HideloadingBlock();
			return false;
		}
	}

	branch_id = dijit.byId('branch_id').get('value');
	academicYearEnroll = dijit.byId('academicYearEnroll').get('value');
	studentType = dijit.byId('studentType').get('value');

	academic_year = dijit.byId('academic_year').get('value');
	degree = dijit.byId('degree').get('value');
	grade = dijit.byId('grade').get('value');
	adv_search = dijit.byId('adv_search').get('value');
	limit = dijit.byId('limit').get('value');

	dojo.xhrPost({
		url:url_get_all_student_from_group,
		content:{
			'updateOption':updateOption,
			'branch_id':branch_id,
			'discountSettengId':discountSettengId,
			'academicYearEnroll':academicYearEnroll,
			'studentType':studentType,

			'academic_year':academic_year,
			'degree':degree,
			'grade':grade,
			'adv_search':adv_search,
			'limit':limit,
			
			},
		handleAs:"json",
		load: function(respone){

			tem='<table border="1"   id="table" >'
				+'<thead><tr align="center" class="header-row">'
					+'<td style="white-space:nowrap; border-right: 0px none;" colspan="1"><?php echo $tr->translate('ALL');?> <br><input style="height: 13px;" type="checkBox" value="0" checked="checked" name="checkall" onclick="check('+respone.length+');setValue('+respone.length+');" id="checkall"/></td>'
				    +'<td><?php echo $tr->translate('NUM');?></td>'
					+'<td><?php echo $tr->translate('STUDENT_CODE');?></td>'
					+'<td><?php echo $tr->translate('STUDENT_NAMEKHMER');?></td>'
					+'<td><?php echo $tr->translate('NAME_EN');?></td>'
					+'<td ><?php echo $tr->translate('SEX');?></td>'
					+'<td ><?php echo $tr->translate('ACADEMIC_YEAR_ENROLL');?></td>'
					+'<td ><?php echo $tr->translate('STUDENT_TYPE');?></td>'
					+'<td ><?php echo $tr->translate('GRADE');?></td>'
					+'</tr>'
				+'</thead>';
			if(respone!=""){
				num=0;
				all_student = respone.length;
				for(var i=0;i<respone.length;i++){
					inx = i+1;
					tem += '<tr style="border:1px solid #000;">';
					tem += '<td align="center"><input style="height: 13px;" class="print-checkbox"  type="checkBox" checked="checked" value="'+inx+'" onclick="setValue('+respone.length+');" name="checkbox'+inx+'" id="checkbox'+inx+'"/></td>';
					tem += '<td align="center">'+inx+' ';
					tem += '<input type="hidden"  name="stu_id_'+inx+'" id="stu_id_'+inx+'" value="'+respone[i].stu_id+'" />';
					tem += '<input type="hidden"  name="degree_'+inx+'" id="degree_'+inx+'" value="'+respone[i].degree+'" />';
					tem += '<input type="hidden"  name="grade_'+inx+'" id="grade_'+inx+'" value="'+respone[i].grade+'" />';
					tem += '</td>';
					tem += '<td>&nbsp;'+respone[i].stu_code+'</td>';
					tem += '<td>&nbsp;'+respone[i].stu_khname+'</label></td>';
					tem += '<td>&nbsp;'+respone[i].last_name+" "+respone[i].stu_enname+'</td>';
					tem += '<td align="center">&nbsp;'+respone[i].sex+'</td>';
					tem += '<td align="center">'+respone[i].startYear+'</td>';
					tem += '<td align="center">'+respone[i].studentType+'</td>';
					tem += '<td align="center">'+respone[i].grade_title+'</td>';
					tem += '</tr>';
					if($("#identity").val()!="") {
						var identity = $("#identity").val();
						$("#identity").val(identity+','+inx);
					} else {$("#identity").val(inx);}
				}
			}
			tem+='</table>';
			dojo.byId('data_table').innerHTML = tem;
			HideloadingBlock();
		},
		error: function(err) {
			HideloadingBlock();
		}
	});
}


function setValue(i){
	$('#identity').val('');
	for(var j=1;j<=i;j++){
		if(dojo.byId('checkbox'+j).checked){
			if($("#identity").val()!="") {
				var iden = $("#identity").val();
				$("#identity").val(iden+','+j);
			} else{
				$("#identity").val(j);
			}
		}
	}
	//countStudentSelected();
}
// function countStudentSelected(){
// 	$('#lblStudentSelected').html('');
// 	identitys = $('#identity').val();
// 	if(identitys!=''){
// 		arraysStu = identitys.split(',');
// 		$('#lblStudentSelected').html(arraysStu.length);
// 	}
// }
function check(i){
	if($('#checkall').is(":checked")){setValue
		for(var j=1;j<=i;j++){
			$('#checkbox'+j).each(function() { //loop through each checkbox
	            this.checked = true;  
			});
		}
	}else{
		for(var j=1;j<=i;j++){
			$("#checkbox"+j).removeAttr("checked");
		}
	}
}


var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var urlGetGrade = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
function getallGrade(){
	dijit.byId('grade').attr('value','');   
	dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){
			return false;
		}
		dojo.xhrPost({
			url:urlGetGrade,
			content:{
				'dept_id':dept_id,
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);  
				if(oldGrade>0){
					dijit.byId('grade').attr('value',oldGrade);
				} 
			},
			error: function(err) {
			}
		});
}

url_dic = '<?php echo $this->url(array('module'=>'accounting','controller'=>'updatestudentdiscount','action'=>'getdiscount'));?>';
function getAllDiscountSetting(){
	
	dijit.byId('discountSettengId').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var discount_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('discountSettengId').set('store',discount_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_dic,
		content:{
			'branchId':branch_id,
			},
		handleAs:"json",
		load: function(data){
			discount_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('discountSettengId').set('store',discount_store);  
			dijit.byId('toDiscountId').set('store',discount_store);  
			if(oldDiscountSettengId>0){
				dijit.byId('discountSettengId').attr('value',oldDiscountSettengId);
			}
			dijit.byId('branch').set('value',branch_id);  
		},
		error: function(err) {
		}
	});
}

function getDiscounInfoById(){
	url_dis_info = '<?php echo $this->url(array('module'=>'accounting','controller'=>'updatestudentdiscount','action'=>'getdiscountinfo'));?>';
	discountSettengId = dijit.byId('discountSettengId').get('value');
	if(discountSettengId==''){
		alert("<?php echo $tr->translate("SELECT_DISCOUNT");?>");
		dojo.byId("discount-info").innerHTML = "";
		return false;
	}
	dojo.xhrPost({
		url:url_dis_info,	
		content:{ 
			'discountSettengId': discountSettengId,'string':1
		},
		handleAs:"json",
		load: function(data) {
			string='';
				string+='<div class="card-info bg-gradient-directional-warning">';
					string+='<div class="card-content">';
						string+='<div class="card-body">';
							string+='<div class="media d-flex">';
								string+='<div class="media-body text-white text-left align-self-bottom mt-3">';
									string+='<span class="d-block mb-1 font-medium-1"></span>';
									string+='<h3 class="text-white mb-10"><?php echo $tr->translate("DISCOUNT_INFO");?></h3>';
										string+=data;
								string+='</div>';
								string+='<div class="align-self-top">';
									string+='<i class="	glyphicon glyphicon-tags icon-opacity text-white font-large-4 float-end"></i>';
								string+='</div>';
							string+='</div>';
						string+='</div>';
					string+='</div>';
				string+='</div>';
			dojo.byId("discount-info").innerHTML = string;
		},
		error: function(err) {
		}
	});
}

function getNewDiscountInfoById(){
	url_dis_info = '<?php echo $this->url(array('module'=>'accounting','controller'=>'updatestudentdiscount','action'=>'getdiscountinfo'));?>';
	toDiscountId = dijit.byId('toDiscountId').get('value');
	if(toDiscountId==''){
		alert("<?php echo $tr->translate("SELECT_DISCOUNT");?>");
		dojo.byId("new-discount-info").innerHTML = "";
		return false;
	}
	dojo.xhrPost({
		url:url_dis_info,	
		content:{ 
			'discountSettengId': toDiscountId,'string':1
		},
		handleAs:"json",
		load: function(data) {
			string='';
			string+=data;
			dojo.byId("new-discount-info").innerHTML = string;
		},
		error: function(err) {
		}
	});
}
	function OptionChange() {
		updateOption = dijit.byId("updateOption").get("value");
		dijit.byId('type').attr('value',updateOption);
		dijit.byId('discountStatus').attr('value',1);

		$(".academic_display").css("display", "flow-root");
		$(".curent_discount_display").css("display", "flow-root");
		$(".adiscountStatus_display").css("display", "flow-root");

		
		if (updateOption == 1) {
			$(".curent_discount_display").css("display", "none");
			$(".adiscountStatus_display").css("display", "none");
		}
		if(updateOption == 2){
			$(".academic_display").css("display", "none");
		}
		
	}

	function changeDisocuntStatus() {
		discountStatus = dijit.byId("discountStatus").get("value");
		
		$(".new_discount_display").css("display", "flow-root");

		if (discountStatus == 0) {
			$(".new_discount_display").css("display", "none");
		}
		
		
	}

	
	
function doPrintRowCheck() {
	var table = document.getElementById('divPrint');
    var checkboxes = table.getElementsByClassName('print-checkbox');
    var checkedRows = [];
    var rowNum = 1; // Initialize row number

    // Loop through all checkboxes
    for (var i = 0; i < checkboxes.length; i++) {
        var checkbox = checkboxes[i];
        var row = checkbox.closest('tr'); // Get the parent row
        var cells = row.cells;
        
        // If checkbox is checked, add row HTML to checkedRows array
        if (checkbox.checked) {
            var rowHtml = '<tr>';
            
            // Adjust the number column to be reset
            rowHtml += '<td class="center">' + rowNum + '</td>';
            rowNum++; // Increment row number
            
            for (var j = 1; j < cells.length; j++) { // Start from 1 to skip the first hidden column
                var hideclass = '';
                if (j == 1) {
                    hideclass = 'hidden';
                }
                rowHtml += '<td class="' + hideclass + '">' + cells[j].textContent + '</td>';
            }
            rowHtml += '</tr>';
            checkedRows.push(rowHtml);
        }
    }

////Print 

  var w = 1000;
  var h = 600;
  var left = Number((screen.width/2)-(w/2));
  var tops = Number((screen.height/2)-(h/2));

  var winPrint = window.open('', '', 'toolbar=0,scrollbars=0,status=0,width='+w+', height='+h+', top='+tops+', left='+left);
  //winPrint.document.write('<title>'+currentTitle+'</title>'+dojo.byId(keyid).innerHTML);
  winPrint.document.write(`
    <html>
      <head>
        <title>Checked Rows</title>
        <style>
			table#table {
				border: 1px solid #000;
				border-collapse: collapse;
				font-size: 12px;
				background-color: white;
				width: 99.5%;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			table#table tr.header-row td {
				background: #02014a;
				font-size: 14px;
				font-weight: bold;
				color: #fff;
				padding: 5px 1px;
			}
			table#table tr td {
				padding: 3px 1px;
			}
			.header{
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			@media print {
				.hidden{visibility: hidden; display: none;}
			}
			.center{
				text-align:center;
			}
        </style>
      </head>
      <body>
  		<h3 align="center" class="header"><?php echo $tr->translate("STUDENT_DISCOUNT_LIST");?></h3>
	 	<table border="1" id="table">
        	<thead>
		 		<tr align="center" class="header-row">
					<td class="hidden" align="left" style="white-space:nowrap;border-left: 0px none;" > <?php echo $tr->translate('ALL');?></td>
				    <td><?php echo $tr->translate('NUM');?></td>
					<td><?php echo $tr->translate('STUDENT_CODE');?></td>
					<td><?php echo $tr->translate('STUDENT_NAMEKHMER');?></td>
					<td><?php echo $tr->translate('NAME_EN');?></td>
					<td><?php echo $tr->translate('SEX');?></td>
					<td><?php echo $tr->translate('ACADEMIC_YEAR_ENROLL');?></td>
					<td><?php echo $tr->translate('STUDENT_TYPE');?></td>
					<td><?php echo $tr->translate('GRADE');?></td>
				</tr>	
			</thead>
			<tbody >
				${checkedRows.join('')}
			</tbody>
        </table>
      </body>
    </html>
  `);
  winPrint.document.close();
  winPrint.focus();
  winPrint.print();
  winPrint.close();
 
}

</script>