<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_DISCOUNT')); 
	$frm =  $this->form_search;
	$frm_fee = $this->frm_fee;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
             <div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_DISCOUNT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					 <div class="col-md-3 col-sm-3 col-xs-12">
					 	<?php echo $frm->getElement("title");?>
					 </div>
					 <div class="col-md-3 col-sm-3 col-xs-12">
					  	<select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" class="fullside" onChange="getAllAcademicByBranch();" id="branch_id" name="branch_id" type="text">
							<option value=""><?php echo $tr->translate("SELECT_BRANCH");?></option>
							<?php if(!empty($this->branch)){ foreach ($this->branch as $year){?>	
								<option value="<?php echo $year['id'];?>" <?php if ($this->adv_search['branch_id']==$year['id']){ echo 'selected="selected"';}?>><?php echo $year['name'];?></option>
							<?php }}?>
						</select>	
					 </div>
					 <div class="col-md-3 col-sm-3 col-xs-12">
						<input id="academic_year" />
					 </div>
					 <div class="col-md-3 col-sm-3 col-xs-12">
					  	<?php echo $frm_fee->getElement("type_study");?>
					 </div>
			    </div>
				<div class="form-group">
					<div class="col-md-3 col-sm-3 col-xs-12">
					  	<?php echo $frm_fee->getElement("school_option");?>
					 </div>
					 <div class="col-md-3 col-sm-3 col-xs-12">
					  	<?php echo $frm->getElement("status");?>
					 </div>
					 <div class="col-md-3 col-sm-3 col-xs-12">
					 	<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					 </div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list; ?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore"); 
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.DateTextBox");

	dojo.ready(function(){ 
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "academic_year",
			name: "academic_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				academic_year = dijit.byId('academic_year').get('value');
			}
		}, "academic_year");
		
		getAllAcademicByBranch();
	});

url_getacademic = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'get-academicyear'));?>';
function getAllAcademicByBranch(){
	dijit.byId('academic_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('academic_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	
	contentData = {
		'branch_id':branch_id
	}
	selectedId = '<?php echo $this->adv_search['academic_year']?>';
	getAllYear(url_getacademic,contentData,selectedId);
	
	
}

</script>