<?php
	$request = Zend_Controller_Front::getInstance ()->getRequest ();
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("UPDATE_STUDENT_DISCOUNT"));
	$urlDetail = $this->baseUrl()."/allreport/accounting/rpt-discountdetail/id/";
?>	
<?php $frm =  $this->form_search;?>

<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-tags " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('UPDATE_STUDENT_DISCOUNT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'accounting','controller'=>'updatestudentdiscount','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("title");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("academic_year");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('discountFor');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
	            		<input id="studentId" />
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<input id="discountId" />
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('discountPeriod');?>
	            	</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('status_search');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
var disname_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->discount));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		required: false,  
		autoComplete: false,
		queryExpr: "*${0}*",                      
	    id: "studentId",
	    name: "studentId",  
	    tabindex: "1",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME")?>", 
	    
	}, "studentId");

	new dijit.form.FilteringSelect({
		store: disname_store,
		required: false,   
		autoComplete: false,
		queryExpr: "*${0}*",  
		id: "discountId",
		name: "discountId", 
		value:"<?php echo $this->adv_search['discountId'];?>",          
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_DISCOUNT");?>",          
		onChange: function() {  
		}
	}, "discountId");

	branchId = dijit.byId('branch_id');
	branchId.on('change',function(evt){
		branchId = dijit.byId('branch_id').get('value');
		if(branchId==''){
			dijit.byId("branch_id").focus();
			return false;
		}
		getAllstudentBranch();
	});

	getAllstudentBranch();
});

function getAllstudentBranch(){
	dijit.byId("studentId").reset();
	branchId = dijit.byId('branch_id').get('value');
	if(branchId==''){
		 dijit.byId('branch_id').focus();
		 return false;
	}
	
	var urlGet = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getliststudenturl')); ?>';
	
	contentData = {
			'branchId':branchId,
			'customerType':1
			}
	selectedId='<?php echo $this->adv_search['studentId'];?>';
	getAllStudentByBranch(urlGet,contentData,selectedId);
}

var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="reprint"){
					url='<?php echo $urlDetail;?>';
					newPageTitle="<?php echo $tr->translate("RPT_DISCOUNT_SETTING_DETAIL");?>";
				}
				addTab(newPageTitle,url+row+'?inFrame=true');
				//gotoAction();
			},
			items: {
				"reprint": {name: "<?php echo $tr->translate("RPT_DISCOUNT_SETTING_DETAIL");?>", icon: "fa-list", accesskey: "e"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.location.href =url+row;
	}
</script>