<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_TEST'));
	$frm =  $this->form_search;
	$urlEnterResult = $this->baseUrl()."/test/index/createtestexam?type=2&id=";
	$urlCreateExamKh = $this->baseUrl()."/test/index/createtestexam?type=1&id=";
	$urlCreateExamUniver = $this->baseUrl()."/test/index/createtestexam?type=3&id=";
	$urlProfile = $this->baseUrl()."/test/index/profile/id/";
	$urledit = $this->baseUrl()."/test/index/edit/id/";
	
	$_dbgb = new Application_Model_DbTable_DbGlobal();
	$userinfo = $_dbgb->getUserInfo();

	
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom m-0">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_TEST');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    		<div class=" nav_menu page-notification" style="display: none;">
		   		<nav>
              		<ul class="nav navbar-nav navbar-left">
              			<li role="presentation" class="dropdown">
			                  <a title="<?php echo $tr->translate("CREATE_TO_STUDENT_TEST");?>" href="javascript:;"  class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="true">
			                    <i class="fa fa-universal-access"></i>
			                    <span id="countNews" class="badge bg-green"><?php $count = count($this->crm); if ($count>0){ echo $count;}?></span>
			                  </a>
			                  <ul id="menu1" class="dropdown-menu list-unstyled " role="menu">
				                 <li class=" event title">
				                  	<h4><?php echo $tr->translate("CREATE_TO_STUDENT_TEST");?></h4>
				                  </li>
				                  <?php if (!empty($this->crm)) foreach ($this->crm as $crm){?>
		                          <li class="items-list event">
		                         	 <a href="<?php echo $this->baseUrl()."/test/index/makecrmtest/id/".$crm['stu_id'];?>">
			                            <div class="pull-left profile-list ">
			                              <img src="<?php echo $this->baseUrl()."/images/no-profile.png";?>" />
			                            </div>
			                            <div class="media-body">
			                              <p><strong><i class="fa fa-university"></i> <?php echo $crm['branch_name'];?> </strong>  </p>
			                              <span class="title" ><?php echo $crm['stu_khname']." (".$crm['stu_enname']." ".$crm['last_name'].")";?></span>
			                              <p><?php echo $tr->translate("GENDER");?> <?php if ($crm['sex']==1){ echo $tr->translate("MALE");}else { echo  $tr->translate("FEMALE");}?> </p>
			                              <p><strong><i class="fa fa-phone"></i> <?php echo $crm['guardian_tel'];?> </strong>  </p>
			                              <p> <small><?php echo empty($crm['from_school'])?"":"(".$crm['from_school'].")";?></small>
			                              </p>
			                            </div>
		                            </a>
		                          </li>
		                          <?php }?>
			                  </ul>
			              </li>
			          </ul>
			      </nav>
			  </div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
  				<div class="form-group">
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<input type="text" name="txtsearch" id="txtsearch" dojoType="dijit.form.TextBox" value="<?php echo $this->adv_search['txtsearch']; ?>" placeholder="<?php echo $tr->translate('SEARCH');?>" class="fullside" />
                   </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("branch_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("degree");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("start_date");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement("end_date");?>
                   </div>
                	<div class="col-md-2 col-sm-2 col-xs-12">
			   			<button style="width: 30%;display: inline-block;" iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                </div>
  			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
 <script type="text/javascript">
	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
			
				var m = "clicked: " + key;
				if(key=="enterresult"){
					url='<?php echo $urlEnterResult;?>';
				}else if(key=="enterresultkh"){
					url='<?php echo $urlCreateExamKh;?>';
				}else if(key=="enterresultuniver"){
					url='<?php echo $urlCreateExamUniver;?>';
				}
				else if(key=="profile"){
					url='<?php echo $urlProfile;?>';
				}
				else if(key=="edit"){
					url='<?php echo $urledit;?>';
				}
				gotoAction();
			},
			items: {
				<?php if($userinfo['level']==1){ ?>
				"enterresult": {name: "<?php echo $tr->translate("CREATE_TEST_EXAM_EN");?>", icon: "fa-laptop  "},
				"enterresultkh": {name: "<?php echo $tr->translate("CREATE_TEST_EXAM_KH");?>", icon: "fa-laptop  "},
				"enterresultuniver": {name: "<?php echo $tr->translate("CREATE_TEST_EXAM_UNIV");?>", icon: "fa-laptop  "},
				<?php }else{ 
					if(!empty($userinfo['schoolOption'])){
						$schoolOption = explode(",",$userinfo['schoolOption']);
						foreach($schoolOption as $scp){
						?>
							<?php if($scp==1){ ?>
							"enterresultkh": {name: "<?php echo $tr->translate("CREATE_TEST_EXAM_KH");?>", icon: "fa-laptop  "},
							<?php }else if($scp==2){ ?>
							"enterresult": {name: "<?php echo $tr->translate("CREATE_TEST_EXAM_EN");?>", icon: "fa-laptop  "},
							<?php }else if($scp==3){ ?>
							"enterresultuniver": {name: "<?php echo $tr->translate("CREATE_TEST_EXAM_UNIV");?>", icon: "fa-laptop  "},
							<?php }?>
						
						<?php }?>
				<?php } 
				}?>
				
				"profile": {name: "<?php echo $tr->translate("STUDENT_PROFILE");?>", icon: "fa fa-user"},
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "fa fa-edit"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
	 	window.open(url+row);
	}
</script> 