<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_credit;
?>
<title><?php echo $tr->translate("CREDIT_MEMO");?></title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-tasks" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CREDIT_MEMO');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'creditmemo','action'=>'add')); ?>" 
		dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					student_id = dijit.byId('student_id').get('value');
        			if(student_id==0){
						alert("សូមជ្រើសរើសសិស្ស");dijit.byId('student_id').focus();return false;
					}
        			dijit.byId("save_new").set("disabled",true);
        			dijit.byId("save_close").set("disabled",true);
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
							<div class="card-body"> 
								<div class="row"> 
									<div class="col-md-12 col-sm-12 col-xs-12">
										<div class="d-flex "> 
											<div class="settings-main-icon ">
												<i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
											</div> 
											<div class="col-md-10 col-sm-10 col-xs-12"> 
												<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("DETAIL_INFORMATION");?></p>
											</div> 
										</div>
										<div class="col-md-12 col-sm-12 col-xs-12">
												&nbsp; 
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<select class="fullside" name="branch_id" id="branch_id" dojoType="dijit.form.FilteringSelect" >
													<?php if(!empty($this->rsbranch))foreach($this->rsbranch as $row){?>
													<option value="<?php echo $row['id']?>"><?php echo $row['name'];?></option>
													<?php }?>
												</select>
										</div>
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<input id="student_id" />
											</div>
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("CREATED_DATE");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('Date');?>
											</div>
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EXPIRE_DATE");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('end_date');?>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
		         </div>
		         <div class="col-md-4 col-sm-4 col-xs-12">
					 <div class="card-blogform">
							<div class="card-body"> 
								<div class="row"> 
									<div class="col-md-12 col-sm-12 col-xs-12">
										<div class="d-flex "> 
											<div class="settings-main-icon ">
												<i class="glyphicon glyphicon-tasks" aria-hidden="true"></i>
											</div> 
											<div class="col-md-10 col-sm-10 col-xs-12"> 
												<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("CREDIT_MEMO");?></p>
											</div> 
										</div>
										<div class="col-md-12 col-sm-12 col-xs-12">
												&nbsp; 
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TOTAL_AMOUNT");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<?php echo $frm->getElement('total_amount');?>
											</div>
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("REASON");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<?php echo $frm->getElement('prob');?>
											</div>
										</div>
										<div class="form-group">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<input type="hidden" id="identity" name="identity" />
												<?php echo $frm->getElement('Description');?>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
		         </div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="button"  onclick="submitDataClose()" label="<?php echo $tr->translate("SAVECLOSE");?>" name='save_close' id='save_close' value='save_close' dojoType="dijit.form.Button"
					   class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-saved"/>
					<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='save_new' id='save_new' value='save_new' dojoType="dijit.form.Button"
					class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-open"/>
               	</div>
             </div>
		</form>
    </div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
 </script>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		autoComplete: false,
		queryExpr: "*${0}*",                     
		id: "student_id",
		name: "student_id",   
		required:true,        
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
		onChange: function() {  
		}
	}, "student_id");
	getallstudentname();
	 var branch_id = dijit.byId('branch_id');
	 	branch_id.on('change', function(evt) {
	 		getallstudentname();
	    });
});
function getallstudentname(){
	let url_data = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getliststudenturl')); ?>';
	branch_id = dijit.byId("branch_id").attr("value");
	if(branch_id==''){  
		dijit.byId("branch_id").focus();
		return false;}
		dojo.xhrPost({
			url:url_data,
			content:{
				'branch_id':branch_id,
				'customer_type':1
			},
			handleAs:"json",
			load: function(data) {
				student_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('student_id').set('store',student_store);  
			},
			error: function(err) {
			}
		});
}
function submitDataClose(){
	student_id = dijit.byId('student_id').get('value');
    if(student_id==0){
		alert("សូមជ្រើសរើសសិស្ស");dijit.byId('student_id').focus();return false;
	}
	if(dijit.byId('office_receipt').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'creditmemo','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/accounting/creditmemo";
			},
			error: function(e) {
			}
		});
	}
}
</script>