<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_STUDENT_DROP')); 
?>
<form id="add_car" action="<?php echo $this->url(array('module'=>'kindergarten','controller'=>'studentdrop','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table cellspacing="20" style="margin: 0 auto; width: 600px">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_STUDENT_DROP");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table cellspacing="10" width="100%"​>
									<tr>
										<td><?php echo $tr->translate("STUDENT_CODE")?></td>
										<td>
											<select class="fullside" name="studentid" id="studentid" dojoType="dijit.form.FilteringSelect" placeholder="Select student " onchange="getStudentInfo();" >
										    	<option value="-1"> </option>
										    	<?php if(!empty($this->rs))foreach ($this->rs as $row){?>
													<option value="<?php echo $row['stu_id']?>"><?php echo $row['stu_code']?></option>
												<?php }?>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("STUDENT_NAME")?></td>
										<td><input dojoType="dijit.form.TextBox" readonly="readonly" class="fullside" id="studentname" name="studentname" value="" type="text">
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("SEX")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect"  readonly="readonly" class="fullside" id="gender" name="gender" type="text">
												<option value="1">Male</option>
												<option value="2">Female</option>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("TYPE")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="type" name="type" type="text">
												<option value="1">Suspend</option>
												<option value="2">Stop</option>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("REASON")?></td>
										<td><input dojoType="dijit.form.TextBox" required="true" class="fullside" id="reason" name="reason" value="" type="text"></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("STOP_DATE")?></td>
										<td><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="datestop" name="datestop" value="now" type="text"></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("NOTE")?></td>
										<td><input dojoType="dijit.form.TextBox" required="true" class="fullside" id="note" name="note" value="" type="text"></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("STATUS")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="status" name="status" type="text">
												<option value="1">Active</option>
												<option value="0">Deactive</option>
											</select>
										</td>
									</tr>
									<tr>
										<td colspan="2" align="center">
										<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
										<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
										<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>
<script type="text/javascript">
var url_student = '<?php echo $this->url(array('module'=>'kindergarten','controller'=>'studentdrop','action'=>'get-student')); ?>';
function getStudentInfo(){
			studentid = dijit.byId('studentid').get('value');
			//alert(studentid);
			dojo.xhrPost({
				url:url_student,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data.stu_enname);
					dijit.byId("studentname").attr("value",data.stu_enname);
					dijit.byId("gender").attr("value",data.sex);

				},
				error: function(err) {
					alert(err);
				}
			});
}
</script>