<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
	$urlCopy = $this->baseUrl()."/global/mentionsetting/copy/id/";
	$urlEdit = $this->baseUrl()."/global/mentionsetting/edit/id/";
?>
<title><?php echo $tr->translate("MENTION_SETTING");?></title>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<meta charset="utf-8">
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('MENTION_SETTING');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form action=" " dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
					 	<input dojoType="dijit.form.ValidationTextBox" placeholder="<?php echo $tr->translate("SEARCH");?>..." class="fullside" id="search" name="search" value="<?php echo $this->search['search']?>" type="text" >
					 </div>
					<div class="col-md-2 col-sm-2 col-xs-12">
							<select dojoType="dijit.form.FilteringSelect" class="fullside" onchange="getAllDegreeByAcademicSchoolOption();" id="academic_year" name="academic_year" type="text">
								<option value=""><?php echo $tr->translate("SELECT_YEAR");?></option>
								<?php if(!empty($this->year)){ foreach ($this->year as $year){?>	
									<option value="<?php echo $year['id'];?>" <?php if ($this->search['academic_year']==$year['id']){ echo 'selected="selected"';}?>><?php echo $year['name'];?></option>
								<?php }}?>
							</select>	
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
						<input id="degree" />
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					 </div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list; ?>
		</div>
	</div>
</div>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
    var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){ 
		new dijit.form.FilteringSelect({
			store: dept_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,
			id: "degree",
			name: "degree",           
			class: "fullside", 
			placeHolder:"<?php echo $tr->translate("SELECT_DEGREE");?>",          
		}, "degree");
		getAllDegreeByAcademicSchoolOption();
	});

	var oldAcademic = '<?php echo $this->search['academic_year'];?>';
	url_getdegree= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getdegree'));?>';
	function getAllDegreeByAcademicSchoolOption(){
		dijit.byId('degree').reset();
		academic_year = dijit.byId('academic_year').get('value');
		if(academic_year=='' || academic_year==-1){
			var dept_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('degree').set('store',dept_store);  
			dijit.byId('academic_year').focus();
			return false;
		}
		if(academic_year=='' || academic_year == -1){
			return false;
		}
		dojo.xhrPost({
			url: url_getdegree,
			content:{
				'academic_year':academic_year
				},
			handleAs:"json",
			load: function(data) {
				dept_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('degree').set('store',dept_store);   
			    if(oldAcademic==academic_year){
			    	 dijit.byId('degree').set('value','<?php echo $this->search['degree'];?>');   
			    }
			},
			error: function(err) {
			}
		});
		
	}
	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}else if(key=="copy"){
					url='<?php echo $urlCopy;?>';
				}
				gotoAction();
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
				"copy": {name: "<?php echo $tr->translate("COPY");?>", icon: "copy"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.location.href =url+row;
	}
</script>