<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SRMS_ADD_FACULTY"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$subject_exam= $this->frm_subject_exam;
	
?>	
<?php  $frm_dept= $this->frm_dept;?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
</script>
<form  id='frm_degree' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				var rowId = $('#identity').val();
				if(rowId!=''){ 
				var rowIDArray = rowId.split(',');
				for(var n = 0; n < rowIDArray.length; n++){
				var row_id = dijit.byId('subject_study_'+rowIDArray[n]).get('value');
				if(row_id==''){
						alert("Please select subject title!");
						return false;
						}
					}
				}
                dijit.byId("save_new").attr("disabled",true);
				dijit.byId("save_close").attr("disabled",true);
				return true;
			}else {
				return false;
			}
</script>

<table cellspacing="10" width="100%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background: #fff;   border: solid 1px #008;">
			<legend align="center" ><strong><?php echo $tr->translate("ADD_FACULTY");?></strong></legend>
			<table style="margin: 0 auto; width: 100%;white-space: nowrap;" cellspacing="10">
				<tr>
					<td style=" vertical-align: top; width: 40%;">
						<table style="margin: 0 auto; width: 100%;white-space: nowrap;" cellspacing="10">
							<tr>
								<td><?php echo $tr->translate("NAME");?></td>
								<td>
								 <?php echo $frm_dept->getElement("en_name");?>
								</td>
								<td><?php echo $tr->translate("SHORTCUT");?></td>
								<td><?php echo $frm_dept->getElement("shortcut");?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("MAX_AVERAGE");?></td>
								<td>
									<input name="max_average" id="max_average"  dojoType="dijit.form.TextBox"  class="fullside" />
								</td>
								
								<td><?php echo $tr->translate("PASS_AVERAGE");?></td>
								<td>
									<input name="pass_average" id="pass_average" dojoType="dijit.form.TextBox"  class="fullside" />
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>	
					<td style=" vertical-align: top;">
						<table style="margin: 0 auto; width: 100%;white-space: nowrap;" cellspacing="10">
							
							<tr>
								<td colspan="6">
									<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;">
											<tr id="head-title" class="head-td" align="right"></tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="4" align="left">
										<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
											iconClass="dijitIconEditProperty" onclick="addRow();" />
								</td>
								<input type="hidden" name="identity" id="identity"  />
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center"><br />
					    <input type="button" onClick="submitDataClose()"  label="<?php echo $tr->translate("SAVE_CLOSE");?>" id="save_close" name="save_close" value="save_close"
						dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
						<input type="submit"  label="<?php echo $tr->translate("SAVE_NEW");?>" id="save_new" name="save_new" 
						dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
						
				</tr>
			</table>			
		</fieldset>		
		</td>
	</tr>
</table>	
</form>

<script type="text/javascript">
dojo.require("dojo.date.locale");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
//dojo.require('dojox.form.BusyButton');
dojo.ready(function(){
	addRow();
	getValue();
});
var subject = '<?php echo $this->subject;?>';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th id="lbl_titlemetion" width="200px"><?php echo $tr->translate("SUBJECT_STUDY");?></th>';
		temp+='<th id="lbl_titlemetion" width="50px"><?php echo $tr->translate("SCORE_IN_CLASS");?></th>';
		temp+='<th id="lbl_titlemetion" width="50px"><?php echo $tr->translate("SCORE_OUT_CLASS");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SCORE_SHORT");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("NOTE");?></th>';
		temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("STATUS");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="4%" align="center">'+no+'</td>';
		template+='<td><select style="width:100%;" dojoType="dijit.form.FilteringSelect" queryExpr="*${0}*" autoComplete="false" class="fullside" id="subject_study_'+col+'" name="subject_study_'+col+'" onchange="popupsubject('+col+');" >'+subject+'</select></td>';
		template+='<td><input style="width:100%;" required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="scoreinclass_'+col+'" id="scoreinclass_'+col+'" onkeyup="calculateTotalScore();" value="" type="text"></td>';	
		template+='<td><input style="width:100%;" required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="scoreoutclass_'+col+'" id="scoreoutclass_'+col+'" value="" type="text"></td>';
		template+='<td><input style="width:100%;" required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="scoreshort_'+col+'" id="scoreshort_'+col+'" value="0" type="text"></td>';
		template+='<td><input style="width:100%;" dojoType="dijit.form.TextBox" class="fullside" name="note_'+col+'" id="note_'+col+'" value="" type="text"></td>';		
		template+='<td><select dojoType="dijit.form.FilteringSelect" class="fullside" id="status_'+col+'" name="status_'+col+'" style="width:100%;"><option value="1"><?php echo $tr->translate("ACTIVE")?></option><option value="0"><?php echo $tr->translate("DEACTIVE")?></option></select> <input style="width:10px;" dojoType="dijit.form.TextBox" class="fullside" name="oldindex_'+col+'" id="oldindex_'+col+'" value="'+col+'" type="hidden"></td>';
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
}

function getValue(){
	var par='';
	if(dojo.byId('is_parent').checked){
		par = 1;
		dijit.byId('parent').attr('value','');
		dijit.byId("parent").set('readOnly',true);
		 dijit.byId('parent').set('required',false);  
	}else{
		par=0;
		dijit.byId("parent").set('readOnly',false);
		 dijit.byId('parent').set('required',true);  
	}
	$('#par').val(par);
}
record_id=0;
function popupsubject(index){
	record_id = dijit.byId("subject_study_"+index).get('value');
	one_value = dijit.byId("oldindex_"+index).get('value');
	$("#tow_value").val(one_value);
	if(record_id==-1){
		dijit.byId("popup_subject").show();
	}
}
/*
var url_add_dept = '<?php echo $this->url(array("module"=>"global","controller"=>"subject","action"=>"addsubjectajax")); ?>';
function addSubject(){
	if(dijit.byId('add_subject_exam').validate()) {
		dojo.xhrPost({
				url:url_add_dept,
				form: dojo.byId("add_subject_exam"),
				handleAs:"json",
				load: function(option) {
					//alert("record_id"+option.data);
					//alert("record_id"+option.option);
					dojo.byId("subject_label"+record_id).innerHTML='';
					dojo.byId("subject_label"+record_id).innerHTML='<select Onchange="popupsubject('+record_id+')" id="subject_study_'+record_id+'" name="subject_study_'+record_id+'" dojoType="dijit.form.FilteringSelect" >'+option+'</option>';
				  dijit.byId('add_subject_exam').reset();
				  dijit.byId("popup_subject").hide();
				},
				error: function(err) {
					alert(err);
				}
		});
	}
}*/

var sub_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->sub));?> );
var url_add_sub = '<?php echo $this->url(array("module"=>"global","controller"=>"degree","action"=>"addsubjectajax")); ?>';
function addSubject(){
	if(dijit.byId('add_subject_exam').validate()) {
		dojo.xhrPost({
				url:url_add_sub,
				form: dojo.byId("add_subject_exam"),
				handleAs:"json",
				load: function(data) {
				  var Itemmake = { 
					        id: data.id,
					        name: dijit.byId('subject_en').get('value')
					         };
						ind=$("#tow_value").val();
					    addDataToSelectbox(dijit.byId('subject_study_'+ind), sub_store , Itemmake, data.id);
				  
				  dijit.byId('add_subject_exam').reset();
				  dijit.byId("popup_subject").hide();
				   
				},
				error: function(err) {
					alert(err);
				}
		});
	}
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}

function calculateTotalScore() {
	var total_score = 0;
	var max_average = 0;
	var pass_average = 0;
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++){
		total_score += parseFloat(dijit.byId('scoreinclass_'+arrays[i]).get('value'));
	}

	amount_subject = arrays.length;
	max_average = total_score / amount_subject;
	pass_average = max_average / 2;

	dijit.byId('max_average').attr('value',max_average.toFixed(2));
	dijit.byId('pass_average').attr('value',pass_average.toFixed(2));
	
	//alert("total score = "+total_score+",amt_sub = "+amount_subject+", max avg = "+max_average+", pass avg = "+pass_average);
}

</script>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_subject" >
		<form  name='add_subject_exam' id='add_subject_exam'  dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color:menu;">
									<legend align="center" style="font-size: 18px;"><strong><?php echo $tr->translate("ADD_NEW_SUBJECT");?></strong></legend>
									<table style="margin: 0 auto; width: 95%;white-space: nowrap;" cellspacing="10">
										<tr>
											<td><input type="checkBox" checked="checked" dojoType="dijit.form.CheckBox" value="1" id="is_parent" onChange="getValue();" name="is_parent" /><?php echo $tr->translate("IS_PARENT")?></td>
											<input type="hidden" id="par" name="par" />
										</tr>
										<tr>
											<td style="width: 100px"><?php echo $tr->translate("PARENT")?></td>
											<td>
												<select class="fullside" name="parent" id="parent" dojoType="dijit.form.FilteringSelect" >
													<option value="0"></option>
													<?php if(!empty($this->rs))foreach ($this->rs as $row){?>
																<option value="<?php echo $row['id']?>"><?php echo $row['subject_titleen']?></option>
													<?php }?>
												</select>
											</td>
										</tr>
										<tr>
											<td style="width: 100px"><?php echo $tr->translate("SUBJECT_IN_KH")?></td>
											<td>
												<input name="subject_kh" id="subject_kh" dojoType="dijit.form.ValidationTextBox" required="required" class="fullside" />
											</td>
										</tr>
										<tr>
											<td style="width: 100px"><?php echo $tr->translate("SUBJECT_IN_EN")?></td>
											<td>
												<input name="subject_en" id="subject_en" dojoType="dijit.form.ValidationTextBox" required="required" class="fullside" />
											</td>
										</tr>
										<tr>
											<td style="width: 100px"><?php echo $tr->translate("SHORTCUT")?></td>
											<td>
												<input name="shortcut_sub" id="shortcut_sub" dojoType="dijit.form.TextBox" class="fullside" />
											</td>
										</tr>
										<tr>
											<td colspan="2" align="center">
												<input type="button" onclick="addSubject();" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
													iconClass="dijitEditorIcon dijitEditorIconSave" />
											</td>
										</tr>
									</table>	
						</fieldset>		
					</td>
				</tr>
			</table>	
			<input type="hidden"  name="tow_value" id="tow_value" value="" />
 			</form>
	</div>
</div>

<script>

function submitDataClose(){
	var rowId = $('#identity').val();
	if(rowId!=''){ 
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++){
	var row_id = dijit.byId('subject_study_'+rowIDArray[n]).get('value');
	if(row_id==''){
			alert("Please select subject title!");
			return false;
			}
		}
	}
	if(dijit.byId('frm_degree').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'global','controller'=>'degree','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_degree"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/global/degree";
			},
			error: function(e) {
			}
		});
	}
}

</script>