<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SRMS_FACULTIES_LIST"));
?>	
<?php $frm = $this->frm_search;?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'global','controller'=>'degree','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	 <?php echo $frm->getElement("title");?>
	 <?php echo $frm->getElement('status_search');?>
	 <button IconClass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>
<?php echo $this->list;?>

