<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('EDIT_STUDENT_REGISTER')); 
	echo $this->headTitle(''); 

	//print_r($photo); exit();
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<style>
tr.head td h2 {
    font-size: 16px !important;
    line-height: 27px !important;
}
.b{ font-weight: bold; }

p.padding-left {
    line-height: 24px !important;
}

table#exportExcel tr td {
    font-size: 14px !important;
}
label.title {
    font-size: 14px !important;
    min-width: 100px !important;
}
label.value {
    font-size: 14px !important;
    min-width: 100px !important;
}
</style>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.ready(function(){
	 
}); 
 
</script>
<table width="100%">
<div class="ptss-frame  js-ptss-frame "><!-- is-opened -->
		<div class="ptss__toggle-btn  js-ptss-toggle-btn ">
			<i class="fa fa-print"></i>
		</div>
      <div class="ptss__header"><?php echo $tr->translate("PRINT");?></div>
		<div class="ptss__settings">
			<div class="ptss__single-setting" id="ptss__layout">
				<div class="ptss__setting-control">
					<div class="ptss__layout-wrapper">
						<a class="qButton" title="<?php echo $tr->translate("Preview");?>" href="#" onclick="preview();"><i class="fa fa-search" aria-hidden="true"></i></a>
						<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrint();" ><i class="fa fa-print" aria-hidden="true"></i></a>
						<a class="qButton excel" href="#"  title="<?php echo $tr->translate("Export");?>"  onclick="exportExcel();"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a>
					</div>
					
				</div>
			</div>
		</div>
</div>
</table>
<div id="divPrint">
<div style="background: #fff;width: 28cm;margin: 0 auto;min-height: 32cm; padding: 0.5cm; border1px solid #000;">
			<style>
	   			label.value{
	   				font-weight: initial;
	   				min-width: 90px;
	   				font-size: 14px;
	   				display: inline-block;
				}
				p.padding-left {
				    padding-left: 10px;
					    line-height: 20px;
				}
				label.title {
				    font-size: 14px;
				    min-width: 80px;
				    display: inline-block;
				}
				.border {
				    
				    display: block;
				    width: 100%;
				    height: 1px;
				    margin-bottom: 10px;
				}
	  		 </style>
				<table id="exportExcel" width="100%" style="font-size:12px; font-family:Tahoma,'Khmer OS Battambang';"> 
					<tr colspan="5" class="head">
						<td style="text-align: left; list-style:22px; line-height:24px; font-size:30px;font-weight: bold; list-style:none;​">
							<li align="center" style="margin-right: 45%;"><img alt="" src="<?php echo $this->baseUrl()."/images/logo.png"?>" style="width: 112px;   display: inline-block;"></li>
					   		<li style="font-size:16px;  font-weight: initial; font-family:'Khmer OS Muol Light';">វិទ្យាស្ថានបច្ចេកទេសឧស្សាហកម្ម</li>
					   		<li style="font-size:16px;  font-weight: initial; font-family:'Times New Roman';" >INDUSTRIAL TECHNICAL INSTITUTE</li>
					   		<li style="font-size:16px;  font-weight: initial; font-family:'Khmer OS Muol Light';" >លេខ :  ................................</li>
					   </td>
					   <td width="40%" valign="middle">
						</td>
					   <td style="list-style:25px; line-height:25px; font-size:30px;font-weight: bold; list-style:none;">
					   		<li style="font-size:18px; text-align: center;    font-weight: initial; font-family:'Khmer OS Muol Light';" >ព្រះរាជាណាចក្រកម្ពុជា</li>
					   		<li style="font-size:18px; text-align: center;     font-weight: initial; font-family:'Times New Roman';" >KINGDOM OF CAMBODIA</li>
					   		<li style="font-size:18px; text-align: center;     font-weight: initial; font-family:'Khmer OS Muol Light';">ជាតិ សាសនា ព្រះមហាក្សត្រ</li>
					   		<li style="font-size:18px; text-align: center;     font-weight: initial; font-family:'Times New Roman';" >NATION RELIGION KING</li>
					   		<li align="center" ><img alt="" src="<?php echo $this->baseUrl()."/images/ifrma.png"?>" style="width: 170px; height: 18px;  display: inline-block;"></li>
					   </td>
					</tr>
					
					<tr class="head" style="font-weight: initial;font-family:'Khmer OS Muol Light';" >
					   <td width="30%">
					   		&nbsp;&nbsp; 
					   </td>
					</tr>
					
					<tr class="head" style="font-weight: initial;font-family:'Khmer OS Muol Light';" >
					   <td colspan="5" align="center">
					   		<label style="font-size:28px;font-weight: initial;font-family:'Khmer OS Muol Light';">វិញ្ញាបនបត្របញ្ជាក់ការសិក្សា</label><br>
					   		<label style="font-size:28px;font-weight: initial;font-family:'Times New Roman';">CERTIFICATION</label><br>
					   		<label style="font-size:18px;font-weight: initial;font-family:'Khmer OS Muol Light';">នាយក វិទ្យាស្ថានបច្ចេកទេសឧស្សាហកម្ម បញ្ជាក់ថា </label><br>
					   		<label style="font-size:18px;font-weight: initial;font-family:'Times New Roman';">The Director of the Industrial Technical Institute certifies that:</label>
					   </td>
					</tr>
					<tr>
					<td colspan="5">
					<table  style="font-family:'Khmer OS Battambang'; border-collapse:collapse;  white-space: nowrap;" width="100%" cellspacing="0">
					<tr style="list-style:25px; font-family:  Times New Roman;line-height:45px; font-size:13px; font-weight: bold; list-style:none; white-space: nowrap;">
	  						<tr style="list-style:25px; font-family:  Times New Roman;line-height:45px; font-size:15px; list-style:none; white-space: nowrap;">
								<td style="font-weight: bold;">និស្សិតឈ្មោះ</td>
								<td> : &nbsp;&nbsp;សន វុទ្ធា</td>
								<td style="font-weight: bold;">Name</td>
								<td> : &nbsp;Sorn Sokun</td>
							</tr>
							<tr style="list-style:25px; font-family:  Times New Roman;line-height:45px; font-size:15px; list-style:none; white-space: nowrap;">
								<td style="font-weight: bold;">ភេទ</td>
								<td> : &nbsp;&nbsp;ប្រុស </td>
								<td style="font-weight: bold;">Sex </td>
								<td>  : &nbsp; Male</td>
							</tr>
							<tr style="list-style:25px; font-family:  Times New Roman;line-height:45px; font-size:15px; list-style:none; white-space: nowrap;">
								<td style="font-weight: bold;">ថ្ងៃ / ខែ / ឆ្នាំ / កំណើត</td>
								<td> : &nbsp;&nbsp; ១៩៩៧ / ០៥ / ០៨</td>
								<td style="font-weight: bold;">Date of Birth</td>
								<td> : &nbsp; 1997 / 05 / 08</td>
							</tr>
							<tr style="list-style:25px; font-family:  Times New Roman;line-height:45px; font-size:15px; list-style:none; white-space: nowrap;">
								<td style="font-weight: bold;">ទីកន្លែងកំណើត</td>
								<td> : &nbsp;&nbsp;	ត្រពាំងអង្គ ឃុំកំពែង ស្រុកព្រៃកប្បាស តាកែវ</td>
								<td style="font-weight: bold;">Place of Birth</td>
								<td> : &nbsp;Diploma level of Metal Engineering</td>
							</tr>
							<tr style="list-style:25px; font-family:  Times New Roman;line-height:45px; font-size:15px; list-style:none; white-space: nowrap;">
								<td style="font-weight: bold;">ឪពុកឈ្មោះ និងមុខរបរ</td>
								<td> : &nbsp;&nbsp;កក់ ម៉េង </td>
								<td style="font-weight: bold;">Father Name & Job</td>
								<td> : &nbsp;Kok Meng</td>
	 						</tr>
	 						<tr style="list-style:25px; font-family:  Times New Roman;line-height:45px; font-size:15px; list-style:none; white-space: nowrap;">
								<td style="font-weight: bold;">ម្ដាយឈ្មោះ និងមុខរបរ</td>
								<td> : &nbsp;&nbsp;ឆាយ ឡេងណា ជា កសិករ</td>
								<td style="font-weight: bold;">Mother Name & Job</td>
								<td> : &nbsp;Chhay Leng</td>
	 						</tr>
	 						<tr style="list-style:25px; font-family:  Times New Roman;line-height:45px; font-size:15px; list-style:none; white-space: nowrap;">
								<td style="font-weight: bold;">ពិតជានិស្សិតកំពុងសិក្សាថ្នាក់</td>
								<td> : &nbsp;&nbsp;	ថ្ងៃទី ១៧ ខែ កញ្ញា ឆ្នាំ ២០១៥</td>
								<td style="font-weight: bold;">Has attended High Diploma of Technical</td>
								<td> : &nbsp;Year 2015</td>
	 						</tr>
	 						<tr style="list-style:25px; font-family:  Times New Roman;line-height:45px; font-size:15px; list-style:none; white-space: nowrap;">
								<td style="font-weight: bold;">ឯកទេស</td>
								<td> : &nbsp;&nbsp;	កុំព្យូទ័រ</td>
								<td style="font-weight: bold;">Specializes in Automotive Engineering</td>
								<td> : &nbsp; 2015 - 2016</td>
	 						</tr>
	 						<tr style="list-style:25px; font-family:  Times New Roman;line-height:45px; font-size:15px; list-style:none; white-space: nowrap;">
								<td style="font-weight: bold;">ឆ្នាំសិក្សា</td>
								<td> : &nbsp;&nbsp;2015 - 2016</td>
								<td style="font-weight: bold;">In the Academic year</td>
								<td> : &nbsp; 2015 - 2016</td>
	 						</tr>
	  				</tr>
	  				<tr class="head" style="font-weight: initial;font-family:'Khmer OS Muol Light';" >
					   <td colspan="5" align="center">
					   		<label style="font-size:13px;font-weight:bold; font-family:'Khmer OS Muol Light';">លិខិតបញ្ជាក់នេះបានចេញអោយសាមីជន ដើមយកទៅប្រើប្រាស់តាមការដែលអាចប្រើបាន </label><br>
					   		<label style="font-size:13px;font-weight:initial;font-family:'Khmer OS Muol Light';">This certification is presented to the bearer for official purposes it may serve</label>
					   </td>
					</tr>
					<tr class="head" style="font-weight: initial;font-family:'Khmer OS Muol Light';" >
					   <td colspan="4" align="center" >
					   		<label style=" margin-left: 55%; font-size:13px;font-weight: initial;font-family:'Khmer OS Muol Light';">រាជធានីភ្នំពេញ ថ្ងៃទី០៩ ខែ កុម្ភៈ ឆ្នាំ ២០១៧ </label><br>
					   		<label style=" margin-left: 55%; font-size:13px;font-weight: initial;font-family:'Times New Roman';">Phnom Penh, Feburary 09, 2017</label><br>
					  		<label style=" margin-left: 55%; font-size:18px;font-weight: initial;font-family:'Khmer OS Muol Light';">នាយក</label><br>
					  		<label style=" margin-left: 55%; font-size:18px;font-weight: initial;font-family:'Times New Roman';">Director</label>
					   </td>
					</tr>
				  </table>
			  </td>
			</tr>
  		</table>
   	</div>
</div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>

