<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("TOTAL_ATTENDANT_LIST")); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
	<style>
	.hide{visibility:visible !important;
	}
	.hover:hover{ background:#ccc;}
	table.content-data tr.style-head,
	table.tb-footer tr.style-head {
	   font-weight: bold !important;
	}
	</style>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
    	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('TOTAL_ATTENDANT_LIST');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
            <div class="col-md-3 col-sm-3 col-xs-12">
            	<?php $stuOrderBy = empty($this->search['stuOrderBy'])?0:$this->search['stuOrderBy'];?>
            	<select class="fullside" dojoType="dijit.form.FilteringSelect" id="stuOrderBy" name=stuOrderBy>
					<option value="0" <?php if($stuOrderBy==0){echo "selected";}?> ><?php echo $tr->translate("BY_STU_KHNAME_ASC");?></option>
					<option value="1" <?php if($stuOrderBy==1){echo "selected";}?>><?php echo $tr->translate("BY_STU_ENNAME_ASC");?></option>
				</select>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
            </div>
        </div>
	</form>
    </div>
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto; width: 100%;" >
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr class="line"><td colspan="3"></td></tr>
			<tr>
				<td style="width:200px;">
				</td>
				<td align="center" style="color:#4839bd;">
					<span style="font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("TOTAL_ATTENDANT_LIST");?></span><br />
					<span style="font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';white-space: nowrap;"><?php echo $tr->translate("ACADEMIC_YEAR");?> : <?php echo $this->rr['academic'];?></span><br />
					<span style="font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("STUDY_GROUP");?> : <?php echo $this->rr['group_code'];?> </span><br />
				</td>
				<td style="width:200px;"></td>
			</tr>
			<tr>
				<td colspan="3" id="exportExcel">
					<style> 
						td{padding:0 3px; }
						.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap;}
						table{ page-break-inside:auto;font-family:'Times New Roman','Khmer OS Battambang'; }
						tr{ page-break-inside:avoid; page-break-after:auto }
						#header {
						  display: table-header-group;
						  page-break-inside:avoid; page-break-after:auto;
						}
						
						tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
						table.content-data{
							border-collapse:collapse;
							width:100%;
							border:1px solid #4839bd; 
							font-family:'Times New Roman','Khmer OS Battambang';
							font-size:13px;
							white-space: nowrap;
							margin:0 auto;
							color:#4839bd;
							margin:0 auto;
						}
						table.content-data thead tr.style-head {
						   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
							background: #ccd9ff;
							text-align: center;
						}
						table.content-data tr.style-rowdata {
							font-size:12px; 
							height: 23px;
						}
						@media print{
							@page {
								page:A4;
								size: portrait;
								margin: 0.5cm;
							}
						}
					</style>
					<table class="content-data" cellpadding="3" border="1">
						<thead>
							<tr class="style-head" >
								<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
								<td rowspan="2"><?php echo $tr->translate("STUDENT_ID");?></td>
								<td rowspan="2"><?php echo $tr->translate("STUDENT_NAMEKHMER");?></td>
								<td rowspan="2"><?php echo $tr->translate("NAME_ENGLISH");?></td>
								<td rowspan="2"><?php echo $tr->translate("SEX");?></td>
								<td colspan="4" align="center"><?php echo $tr->translate("ABSENT");?></td>
								<td colspan="4" align="center"><?php echo $tr->translate("DISCIPLINE_TYPE");?></td>
							</tr>
							<tr class="style-head" >
								<td align="center"><?php echo $tr->translate("NO_PERMISSION");?></td>
								<td align="center"><?php echo $tr->translate("PERMISSION");?></td>
								<td align="center"><?php echo $tr->translate("LATE");?></td>
								<td align="center"><?php echo $tr->translate("EARLY_LEAVE");?></td>	
								
								<td align="center"><?php echo $tr->translate("SMALL_MISTACK");?></td>
								<td align="center"><?php echo $tr->translate("MEDIUM_MISTACK");?></td>
								<td align="center"><?php echo $tr->translate("BIG_MISTACK");?></td>	
								<td align="center"><?php echo $tr->translate("OTHER");?></td>	
							</tr>
						</thead>
						<?php  
						$db = new Home_Model_DbTable_DbStudent();
						$A=0;
						$P=0;
						$L=0;
						$EL=0;
						$i=0;
						$male=0;$femle=0;
						foreach ($this->rs as $row){ $i++;?>
						<tr align="center" class="style-rowdata hover">
							<td><?php echo $i;?></td>
							<td><?php echo $row['stu_code'];?></td>
							<td align="left"><?php echo $row['kh_name'];?></td>
							<td align="left"><?php echo $row['last_name'].' '.$row['en_name'];?></td>
							<td>
								<?php echo $row['sex'];
									if($row['gender']==1){
										$male=$male+1;
									}else{
										$femle=$femle+1;
									}
								?>
							</td>
							<?php 
							$attentence_status = $db->getSumStatusAttendence($row['stu_id'], $row['group_id']);
							$absent=0;
							$permission=0;
							$late=0;
							$early_leave=0;
							foreach ($attentence_status as $rs){
									if ($rs['attendence_status']==2){
										$absent =$absent+$rs['total'];
										$A=$A+1;
										//Absent
									}
									else if ($rs['attendence_status']==3){
										$permission =$permission+$rs['total'];
										 $P = $P+1;
										//Permission
									}
									else if ($rs['attendence_status']==4){
										$late =$late+$rs['total'];
										$L = $L+1;
										//Late
									}
									else if ($rs['attendence_status']==5){
										$early_leave =$early_leave+$rs['total'];
										$EL = $EL+1;
										//Early Leave
									}else{
										echo " ";
									}
								}
							?>
							<td align="center"><?php echo $absent;?></td>
							<td align="center"><?php echo $permission;?></td>
							<td align="center"><?php echo $late;?></td>
							<td align="center"><?php echo $early_leave;?></td>
							
							<?php $s=0; $m=0; $b=0;$other=0; ?>
							<?php  
								$_db = new Allreport_Model_DbTable_DbRptAllStudent();
								$mistake_status = $_db->getTotalStatusMistake($row['stu_id'], null, $row['group_id']);
								$lateAttedence = $_db->getAttendenceFoul($row['group_id'],$row['stu_id']);
								$late_foul = 0;
								if (!empty($lateAttedence)){
									$late_foul = $lateAttedence['count_foul_att'];
								}
								if (!empty($mistake_status)) foreach ($mistake_status as $sta){
									if ($sta['mistake_type']==1){
										$s=$sta['count_mistack'];
									}
									else if ($sta['mistake_type']==2){
										$m = $sta['count_mistack'];
									}
									else if ($sta['mistake_type']==3){
										$b = $sta['count_mistack'];
									}
									else if ($sta['mistake_type']==4){
										$other = $sta['count_mistack'];
									}
								}
							?>
							    
							<td align="center"><?php echo $s+$late_foul;?></td>
							<td align="center"><?php echo $m;?></td>
							<td align="center"><?php echo $b;?></td>
							<td align="center"><?php echo $other;?></td>
						</tr>
						<?php }?>	
					</table>	
				</td>
			</tr>
			<tr>
				<td colspan="3" style="border:1px solid #fff;">
					&nbsp;
				</td>
			</tr>
			<tr>
				<td colspan="3" style="border:1px solid #fff;">
					<table cellpadding="0" cellspacing="0" width="100%" style="font-family:'Khmer OS Battambang';font-size: 12px">
						<tr>
							<td width="35%" align="center">
								<span style="color:#4839bd; font-size: 12px;font-family:Times New Roman,'khmer os battambang';"><?php echo $tr->translate("CHECKANDAPPROVED");?></span><br />
								<span style="color:#4839bd; font-size: 12px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate("PRINCIPAL");?></span>
							</td>
							<td width="30%">&nbsp;</td>
							<td width="35%" align="center">
								<span style="color:#4839bd; font-size: 12px;font-family:Times New Roman,'khmer os battambang';"><?php echo $tr->translate("CREATE_WORK_DATE");?></span><br />
								<span style="color:#4839bd; font-size: 12px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate("PREPARE_BY");?></span>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>
</div>