<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$session_lang = new Zend_Session_Namespace('lang');
	$lang_id = $session_lang->lang_id;
	$dbgb = new Application_Model_DbTable_DbGlobal();
	$this->headTitle($tr->translate('RPT_SUBJECT_STATISTIC_GRAPH')); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
	$footerScoreDocument = Setting_Model_DbTable_DbGeneral::geValueByKeyName('footerScoreDocument');
	
?>

<style type="text/css">
svg {
    position: relative !important;
}
</style>
<div style="min-height:10cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
    	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_SUBJECT_STATISTIC_GRAPH');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'score','action'=>'rpt-subject-statistic-graph')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
						<script type="dojo/method" event="onSubmit">			
								if(this.validate()) {
									academic_year=dijit.byId('academic_year').get('value');
									if(academic_year=='' || academic_year==0){
										alert('<?php echo $tr->translate('SELECT_ACADEMIC_YEAR');?>!');
										dijit.byId('academic_year').focus(); 
										return false;
									}

									exam_type=dijit.byId('exam_type').get('value');
									if(exam_type=='' || exam_type==0){
										alert('<?php echo $tr->translate('SELECT_EXAM_TYPE');?>!');
										dijit.byId('exam_type').focus(); 
										return false;
									}else if(exam_type==2){
										for_semester=dijit.byId('for_semester').get('value');
										if(for_semester=='' || for_semester==0){
											alert('<?php echo $tr->translate('SELECT_SEMESTER');?>!');
											dijit.byId('for_semester').focus(); 
											return false;
										}
									}else if(exam_type==1){
										for_month=dijit.byId('for_month').get('value');
										if(for_month=='' || for_month==0){
											alert('<?php echo $tr->translate('CHOOSE_MONTH');?>!');
											dijit.byId('for_month').focus(); 
											return false;
										}
									}
									loadingBlock();
									return true;
								}else {
									return false;
								}
			</script>
		<div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("branch_id");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("academic_year");?>
            </div>
			<div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("degree");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="grade" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="group" />
            </div>
			<div class="col-md-2 col-sm-2 col-xs-12">
				<select name="sort_degree" class="fullside height-text" dojoType="dijit.form.FilteringSelect" required="false" placeholder="Select Degree Option">
					<option></option>
					<option <?php echo($this->search['sort_degree']==4)?"selected":"";?> value="4">Kindergarten</option>
					<option <?php echo($this->search['sort_degree']==1)?"selected":"";?> value="1">Primary</option>
					<option <?php echo($this->search['sort_degree']=='3,4')?"selected":"";?> value="2,3">Junior-Senior</option>
				</select>
            </div>
        </div>
        <div class="form-group">
			<div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("exam_type");?>
            </div>
			<div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("for_semester");?>
            </div>
			<div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("for_month");?>
            </div>
			<div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("teacher");?>
            </div>
			<div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="subjectId" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
            </div>
        </div>
	</form>	
<style>
.hidden{
	display: table-cell !important;
}
</style>
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto; width: 100%;">
			<thead>
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr>
					<td width="28%" align="left"></td>
					<td width="44%" align="center">
						<?php 
						$resulTilte="";
						$academicYear="";
						
						if(!empty($this->rs)){ 
							if(!empty($this->search)){
								if($this->search['exam_type']==1){
									$titleScore=$this->rs['0']['title_score'];
									$resulTilte = "ប្រចាំខែ ".$titleScore;
								}elseif($this->search['exam_type']==2){
									if($this->search['for_semester']==1){
										$resulTilte = "ប្រចាំ ឆមាសទី១";
									}elseif($this->search['for_semester']==2){
										$resulTilte = "ប្រចាំ ឆមាសទី២";
									}
								}else{
									$resulTilte = "ប្រចាំឆ្នាំ";
								}
							 } 
							 $academicYear = "ឆ្នាំសិក្សា ".$this->rs[0]['academicYear'];
							}
						?>
						<ul class="headerTitle">
							<li>
								<strong><?php echo $tr->translate("RPT_SUBJECT_STATISTIC_GRAPH");?></strong>
							</li>
							<li>
								<?php echo $resulTilte;?>
							</li>
							<li>
								<?php echo $academicYear;?>
							</li>
						</ul>
					</td>
					<td align="right" width="28%"></td>
				</tr>
			</thead>
			<tr>
				<td colspan="3" valign="top" id="exportExcel">
						<style type="text/css">
								.style{
										line-height: 20px;font-size: 13px !important;
										font-family: 'Times New Roman','Khmer OS Battambang';
									}
									.hideblog{display: none;}
									.hiddenblog{display: block !important;}
									.style1:hover{ background: #ccc; }
									table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
									
									table.content-data { page-break-inside:avoid; page-break-after:auto; }
									#header {
										display: table-header-group;
										page-break-inside:avoid; page-break-after:auto;
										margin-top: 100px;
									}
									.hide{visibility: hidden;}
									@media print {
										div.divFooter {
											position: fixed;
											top: 0;
											width: 100%;
											height: 100px;
											bottom:0px;
											margin:0;
										}
									}
									.center{text-align: center !important;}
									table.content-data{
										border-collapse:collapse;
										border:1px solid #000; 
										font-size:8px;
										width:100%;
								
									}
									table.content-data tr.style.header,
									table.content-data thead tr.style {
										line-height: 25px; 
										font-size:12px !important; 
										padding:1px 0px; 
										white-space: nowrap;height: 22px; 
										background: #c1d0f3;
										font-weight:600;
									}
									table.content-data  tr.style {
										white-space: nowrap;
									}
									
									ul.headerTitle li{
										list-style:none;line-height:20px;
										font-size: 14px;
										font-family:'Times New Roman','Khmer OS Battambang';
									}
									span.separateColumn{
										width:49%;
										display: inline-block;
									}
									
									table.tb-footer{
										border-collapse:collapse;
										border:1px solid #000; 
										font-size:12px;
										font-family: 'Times New Roman','Khmer OS Battambang';
									}
									table.tb-footer tr{
									line-height: 14px; font-size:12px; padding:2px 0px; height: 25px;
									}
									table tr td{
										padding:0 2px;
									}
									tr.voidclass {
										background: #fff7f7;
									}
									td.centerText{
										text-align: center;
									}
									.redBold {
										font-weight: 600;
										color: #f80000;
									}
									table.content-data tr td{
										padding: 1px;
									}
									.bold{font-weight: bold;
									background:#dee5e7;}

									@media print{
										<?php if(!empty($this->printFormat)){ echo $this->printFormat; } ?>
									}
									.principalStamp {
										position:relative;
										width: 300px;
										height: 140px;
										margin:0 auto;
										margin-top:-20px;
									}
									.principalStamp .stamp {
										width:140px;
										height:140px;
										position:absolute;
										transform: translate(-81%);
										left:50%;
									}
									.principalStamp .signature {
										left: 40px;
										bottom: 32px;
										height: 100px;
										width:200px;
										position: absolute;
									}
									.principalStamp .principalName{
										left: 65px;
										top: 113px;
										height: 100px;
										width: 200px;
										position: absolute;
									}
									.seenApproved{
										position: relative;
									}
									.seenApproved .interimPrincipal{
										position: absolute;
										left: 50%;
										top: 20px;
										transform: translate(-50%);
										z-index: 1;
									}
									
									.administrator {
											position:relative;
											width: 300px;
											height: 140px;
											margin:0 auto;
										}
										.administrator .administratorstamp {
											width:130px;
											height:130px;
											position:absolute;
											transform: translate(-50%);
											left:50%;
										}
										.administrator .administratorsignature {
											left: 40px;
											bottom: 32px;
											height: 100px;
											width:200px;
											position: absolute;
										}
										.administrator .administratorName {
											left: 65px;
											top: 80px;
											height: 100px;
											width: 200px;
											position: absolute;
										}
										label.LabelTeacher {
											line-height: 25px;
											font-weight: initial;
											font-family: 'Times New Roman','Khmer OS Battambang';
											white-space: nowrap;
										}
										.border-top{
											border-top: 1px solid #000000;
										}
										.bold-text {
											font-weight: bold;
											
										}
										
										.square {
											width: 15px;
											height: 12px;
											display: inline-block;
										}

										ul.list-inline.chart-detail-list {
											list-style: none;
											margin: 0;
											padding: 0;
											width: 100%;
											font-family: 'Times New Roman','Khmer OS Battambang';
										}

										ul.list-inline.chart-detail-list li {
											display: inline-block;
											padding-right: 10px;
											vertical-align: middle;
										}
										ul.list-inline.chart-detail-list li h5 {
											font-size: 12px;
											line-height: inherit;
											margin: 0;
											padding: 0;
											font-family: 'Times New Roman','Khmer OS Battambang';
										}
										.charTitle,
										.charTitleBottom{
											margin: 0;
											padding: 0;
											font-size: 14px;
											line-height: inherit;
											font-family: 'Times New Roman','Khmer OS Muol Light';
										}
										.charTitle {
											margin-top: 10px;
										}
										.charTitleBottom{
											margin-bottom: 10px;
										}
										
										div.bar-chart{
											height:220px;
										}
										
						</style>
						<?php 
						
						$active_student = 0;
						$drop_student = 0;?>
					<div id="exportExcel">
						
					<table class="content-data" cellpadding="4" border="1">
						  <?php

						  $i=0; 
						  $Total_Group_A_Percent =0;
						  $Total_Group_B_Percent =0;
						  $Total_Group_C_Percent =0;
						  $Total_Group_D_Percent =0;
						  $Total_Group_E_Percent =0;
						  $Total_Group_F_Percent =0;
						  $oldGradeName=''; 
						  $oldDegreeName=''; 

						  $lineColors = array(
								"#4394E5",
								"#87BB62",
								"#ea5455",
								"#ff9f43",
								"#92cad1",
								"#673ab7",
								"#153c7f",
								"#28c76f",
								"#3D2785",
								"#f4e604",
								"#308fac",
								"#ff7954",
								"#79ccb3",
								"#a73c5a",
								"#631e50",
							);

						  $oldTeacher = '';  // Track previous teacher for rowspan
						 
							$arrForBar = array(
								array("y"=>"A"),
								array("y"=>"B"),
								array("y"=>"C"),
								array("y"=>"D"),
								array("y"=>"E"),
								array("y"=>"F"),
							);

							$fullArrayByTeacher = array();
							$yKey =array();
							$arrRowColor =array();
						  	$chartKey=0;
						  	$chartKey=0;

							$thisColor  ="#673ab7";
							$teacherClass=0;
							$arrGroupColor =array();
						  if (!empty($this->rs)){ foreach($this->rs as $key=> $rs ){ 

								$i++;
								$Total_Group_A_Percent =@str_replace('.00','',number_format($rs['Total_A']/$rs['TotaStudent']*100,2));
								$Total_Group_B_Percent =@str_replace('.00','',number_format($rs['Total_B']/$rs['TotaStudent']*100,2));
								$Total_Group_C_Percent =@str_replace('.00','',number_format($rs['Total_C']/$rs['TotaStudent']*100,2));
								$Total_Group_D_Percent =@str_replace('.00','',number_format($rs['Total_D']/$rs['TotaStudent']*100,2));
								$Total_Group_E_Percent =@str_replace('.00','',number_format($rs['Total_E']/$rs['TotaStudent']*100,2));
								$Total_Group_F_Percent =@str_replace('.00','',number_format($rs['Total_F']/$rs['TotaStudent']*100,2));

                               
							//	techer
								
								if($oldTeacher!=$rs['teacher_name']  ){
								 if($key>0){ 
									$chartKey++;
									$arrRow = array(
										"yKey"=>$yKey,
										"data"=>$arrForBar,
										"rowCode"=>$chartKey,
										"colorBar"=>$arrRowColor,
								
									);
									array_push($fullArrayByTeacher,$arrRow);

									
								?>
									<tr class="hover" style="height: 70px; " align="center">
										<td colspan="11" style="position: relative;border-left: solid 1px #fff;border-right: solid 1px #fff; border-bottom: solid 1px #fff;">
											<h2 class="charTitle"><?php echo $tr->translate("CHART"); ?></h2>
											<div class="text-center">
												<?php if(!empty($arrGroupColor)){?>
												<ul class="list-inline chart-detail-list">
													<?php foreach($arrGroupColor AS $rsG){
														$gColor = $rsG["color"];
													?>
														<li>
															<h5 class="font-normal">
															<div class="square" style="background:<?php echo $gColor; ?>;"></div>
															&nbsp;<?php echo $rsG["label"];?>
															</h5>
														</li>
													<?php }?>
												</ul>
												<?php }?>
											</div>
											<div id="bar-chart-<?php echo $chartKey; ?>" class="bar-chart" ></div>
											<h2 class="charTitleBottom"><?php echo $tr->translate("MENTION_GRADE"); ?></h2>
										</td>
									</tr>
									</table>
									<table class="content-data" cellpadding="4" border="1">
								<?php 
									$arrForBar = array(
										array("y"=>"A"),
										array("y"=>"B"),
										array("y"=>"C"),
										array("y"=>"D"),
										array("y"=>"E"),
										array("y"=>"F"),
									);
									$yKey =array();
									$arrRowColor =array();
									$teacherClass=0;
									$arrGroupColor =array();
								
								}
							?>
							
								<tr class="style header" align="center">
									<td >&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("BRANCH");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("SUBJECT");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("GROUP");?>&nbsp;</td>
									<td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
									<td>
										<?php echo $tr->translate("GRADE_A").'(%)';?>
										<div  class="border-top">
										<span class="separateColumn border-right"><?php echo $tr->translate("AMOUNT");?></span><span class="separateColumn "><?php echo $tr->translate("PERCENTAGE");?></span>
										</div>
									</td>
									<td>
										<?php echo $tr->translate("GRADE_B").'(%)';?>
										<div class="border-top">
										<span class="separateColumn "><?php echo $tr->translate("AMOUNT");?></span><span class="separateColumn "><?php echo $tr->translate("PERCENTAGE");?></span>
										</div>
									</td>
									<td>
										<?php echo $tr->translate("GRADE_C").'(%)';?>
										<div class="border-top">
										<span class="separateColumn "><?php echo $tr->translate("AMOUNT");?></span><span class="separateColumn "><?php echo $tr->translate("PERCENTAGE");?></span>
										</div>
									</td>
									<td>
										<?php echo $tr->translate("GRADE_D").'(%)';?>
										<div class="border-top">
										<span class="separateColumn "><?php echo $tr->translate("AMOUNT");?></span><span class="separateColumn "><?php echo $tr->translate("PERCENTAGE");?></span>
										</div>
									</td>
									<td>
										<?php echo $tr->translate("GRADE_E").'(%)';?>
										<div class="border-top">
										<span class="separateColumn "><?php echo $tr->translate("AMOUNT");?></span><span class="separateColumn "><?php echo $tr->translate("PERCENTAGE");?></span>
										</div>
									</td>
									<td>
										<?php echo $tr->translate("GRADE_F").'(%)';?>
										<div class="border-top">
										<span class="separateColumn "><?php echo $tr->translate("AMOUNT");?></span><span class="separateColumn "><?php echo $tr->translate("PERCENTAGE");?></span>
										</div>
									</td>
								</tr>

							<tr class="hover" style="font-family:'Times New Roman','Khmer OS Muol Light'; font-size:10px; height: 25px; background: #dfe0e1;" align="center">
								<td colspan="11" ><?php echo $tr->translate("TEACHER").' : '.$rs['teacher_name']; ?></td>
							</tr>
							<?php  } 
								
								//// Chat Data
								$thisColor  = empty($lineColors[$teacherClass]) ? "#673ab7" : $lineColors[$teacherClass];
								array_push($arrRowColor,$thisColor);
								array_push($yKey,$rs["group_code"].' - '.$rs["subject_name"]);
								foreach($arrForBar as $keyA => $aa){
									$val = empty($rs["Total_".$aa["y"]]) ? 0 : (int)$rs["Total_".$aa["y"]];
									$arrForBar[$keyA][$rs["group_code"].' - '.$rs["subject_name"]] = $val;

								}
								$rowGroColor =array(
									"label"=>$rs["group_code"].' - '.$rs["subject_name"],
									"color"=>$thisColor,
								);
								
								array_push($arrGroupColor,$rowGroColor);
								$oldTeacher = $rs['teacher_name'];  
								$teacherClass++;
								?>

								<tr class="style hover" align="center" >
								<td align="center"><?php echo $i;?></td>
								<td><?php echo $rs['branch_name']; ?></td>
								<td ><?php echo $rs['subject_name']; ?></td>
								<td><?php echo $rs['group_code']; ?></td>
								<td><?php echo $rs['TotaStudent']; ?></td>
								<td><span class="separateColumn passedGrade"><?php echo @$rs['Total_A'];?></span><span class="separateColumn passedGrade bold-text"><?php echo $Total_Group_A_Percent; ?></span></td>
								<td><span class="separateColumn passedGrade"><?php echo @$rs['Total_B'];?></span><span class="separateColumn passedGrade bold-text"><?php echo $Total_Group_B_Percent; ?></span></td>
								<td><span class="separateColumn passedGrade"><?php echo @$rs['Total_C'];?></span><span class="separateColumn passedGrade bold-text"><?php echo $Total_Group_C_Percent; ?></span></td>
								<td><span class="separateColumn passedGrade"><?php echo @$rs['Total_D'];?></span><span class="separateColumn passedGrade bold-text"><?php echo $Total_Group_D_Percent; ?></span></td>
								<td><span class="separateColumn passedGrade"><?php echo @$rs['Total_E'];?></span><span class="separateColumn passedGrade bold-text"><?php echo $Total_Group_E_Percent; ?></span></td>
								<td><span class="separateColumn passedGrade"><?php echo @$rs['Total_F'];?></span><span class="separateColumn passedGrade bold-text"><?php echo $Total_Group_F_Percent; ?></span></td>
							</tr>
							
						<?php }  
							$chartKey++;
							$arrRow = array(
								"yKey"=>$yKey,
								"data"=>$arrForBar,
								"rowCode"=>$chartKey,
								"colorBar"=>$arrRowColor,
						
							);
							array_push($fullArrayByTeacher,$arrRow);

						?>
						
							<tr class="hover" style="position:relative; " align="center">
								<td colspan="11" style="position: relative; border-left: solid 1px #fff; border-right: solid 1px #fff; border-bottom: solid 1px #fff;"  >
									<h2 class="charTitle"><?php echo $tr->translate("CHART"); ?></h2>
									<div class="text-center" >
										<?php if(!empty($arrGroupColor)){?>
											<ul class="list-inline chart-detail-list">
												<?php foreach($arrGroupColor AS $rsG){
														$gColor = $rsG["color"];
													?>
												<li>
													<h5 class="font-normal">
													<div class="square" style="background:<?php echo $gColor; ?>;"></div>
													&nbsp;<?php echo $rsG["label"];?>
													</h5>
												</li>
												<?php }?>
											</ul>
										<?php }?>
									</div>
									<div id="bar-chart-<?php echo $chartKey;?>" class="bar-chart"></div>
									<h2 class="charTitleBottom"><?php echo $tr->translate("MENTION_GRADE"); ?></h2>
								</td>
							</tr>
						
							<?php }  ?>
						</table>
						<br>
					</div>
				</td>
			</tr>
			
		</table>
	</div>	
	
</div>

<link rel="stylesheet" href="<?php echo $this->baseUrl()."/"?>dashboard/plugins/morris/morris.css">
<script src="<?php echo $this->baseUrl()."/"?>dashboard/plugins/morris/morris.min.js"></script>
<script src="<?php echo $this->baseUrl()."/"?>dashboard/plugins/raphael/raphael-min.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>

<script type="text/javascript">
	dojo.require("dojo.NodeList");
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ItemFileWriteStore"); 

	var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var grade_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){

		new dijit.form.FilteringSelect({
			store: group_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                     
		    id: "group",
		    name: "group",  
		    class: 'fullside', 
		    readonly:false,
		    required:false,
		    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
		    onChange: function() {  
			    getAllSubject();
		    }
		}, "group");
		
		new dijit.form.FilteringSelect({
			store: grade_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade",
			name: "grade",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
				getAllGroupByBranch();
			}
		}, "grade");

		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false, 
			required:false,            
			id: "subjectId",
			name: "subjectId",           
			class: 'fullside', 
			placeHolder:"ជ្រើសមុខវិជ្ជា/Select Subject",          
			onChange: function() {
			}
		}, "subjectId");
		
		 var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getAllGroupByBranch();
			
	     });

		var teacher = dijit.byId('teacher');
		teacher.on('change', function(evt) {
			getAllSubject();
			
	    });

		 var academic_year = dijit.byId('academic_year');
		 academic_year.on('change', function(evt) {
			 getAllGroupByBranch();
	    });
		 getAllSubject();
		 getallGrade();
		 getAllGroupByBranch();
	});
	
	urlGetSubjectStore = '<?php echo $this->url(array('module'=>'issue','controller'=>'scoretmp','action'=>'getsubjectlist'));?>';
	function getAllSubject(){
		dijit.byId('subjectId').reset();
		var subjectStore  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('subjectId').set('store',subjectStore); 

		group    = dijit.byId('group').get('value');
		teacherId   = dijit.byId('teacher').get('value');
		
		dojo.xhrPost({
			url: urlGetSubjectStore,
			content:{
				'groupId':group,
				'teacherId':teacherId,
				},
			handleAs:"json",
			load: function(data) {
				subjectStore  = getDataStorefromJSON('id','name', data);
				dijit.byId('subjectId').set('store',subjectStore); 
				dijit.byId('subjectId').attr('value','<?php echo $this->search['subjectId']?>');      
			},
			error: function(err) {
			}
		});
	}

	url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
	function getAllGroupByBranch(){
		dijit.byId('group').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('group').set('store',group_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		degree = dijit.byId('degree').get('value');
		if(degree=='' || degree==-1){degree ="";}
		grade = dijit.byId('grade').get('value');
		if(grade=='' || grade==-1){grade ="";}
		academic_year = dijit.byId('academic_year').get('value');
		if(academic_year=='' || academic_year==-1){academic_year ="";}
		
		dojo.xhrPost({
			url: url_getgroup,
			content:{
				'branch_id':branch_id,
				'degree':degree,
				'grade':grade,
				'academic_year':academic_year,
				'noaddnew':1,
				'forfilter':1
				},
			handleAs:"json",
			load: function(data) {
			    group_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('group').set('store',group_store);
				<?php if (!empty($this->search['group'])){?>
					dijit.byId('group').attr('value','<?php echo $this->search['group']?>');  
				<?php }?>   
			   
			},
			error: function(err) {
			}
		});
	}
	var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id=='' || dept_id==-1){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id,
				'noaddnew':1
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade').set('store',grade_store); 
				<?php if (!empty($this->search['grade'])){?>
				dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');  
				<?php }?> 
				
			},
			error: function(err) {
			}
		});
		getAllGroupByBranch();  
	}

	<?php foreach($fullArrayByTeacher as $fullarr){ ?>

		config<?php echo $fullarr['rowCode'] ?> = {
			data: <?php echo Zend_Json::encode($fullarr['data']); ?>,
			xkey: 'y',
			ykeys: <?php echo Zend_Json::encode($fullarr['yKey']); ?>,
			labels: <?php echo Zend_Json::encode($fullarr['yKey']); ?>,
		
			dataLabelsPosition: "inside",
			hideHover: 'auto',
			gridTextColor: '#000',
			showZero: false,
			resize: true,
			barColors: <?php echo Zend_Json::encode($fullarr['colorBar']); ?>
	};
	config<?php echo $fullarr['rowCode'] ?>.element = 'bar-chart-<?php echo $fullarr['rowCode'] ?>';
	Morris.Bar(config<?php echo $fullarr['rowCode'] ?>);

	<?php } ?>
   
</script>
