<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RPT_TOTAL_STUDENT_MISTAKE"));
	
	$frm =  $this->form_search;
	$db = new Allreport_Model_DbTable_DbRptAllStudent();
	
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
?>	
<style>
.hover:hover{ background:#ccc;}
table.content-data tr.style-head,
table.tb-footer tr.style-head {
   font-weight: bold !important;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_TOTAL_STUDENT_MISTAKE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("title");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("branch_id");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="group" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="study_year" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("degree");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="grade_all" />
            </div>
         </div>
         <div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("session");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            </div>
         </div>
	</form>
	<div id="divPrint">
		<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
			<style>
				table tr th{
					border: 1px solid #000;	
				}	
				table {page-break-inside:auto }
				.style{
					line-height: 20px; font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				 td.rotate {
				  height: 120px;
    				vertical-align: bottom;
				}
				
				td.rotate > div {
				  transform: rotate(270deg);
					width: 20px;
				}
				 td.rotate span{
				    white-space: nowrap;
				    overflow: hidden;
				    text-overflow: ellipsis;
				    display: inline-block;
				    /* max-width: 130px; */
				}
				table {page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}	
				tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
				
				table.content-data{
					border-collapse:collapse;
					width:100%;
					border:1px solid #4839bd; 
					font-family:'Times New Roman','Khmer OS Battambang';
					font-size:12px;
					white-space: nowrap;
					margin:0 auto;
					color: #4839bd;
				}
				table.content-data a{
					color: #4839bd;
				}
				table.content-data  tr.style-head {
				   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #fdbdbd;
					text-align: center;;
				}
				table.content-data tr td {
					padding: 0 2px;
				}
				table.content-data tr.style-rowdata {
					font-size:12px; 
					height: 23px;
				}			
			</style>
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr class="line"><td colspan="3"></td></tr>
			<tr>
				<td colspan="3" id="exportExcel">
					<table class="content-data" cellpadding="5"​  border="1" >							
						<?php $i=0; $old_groupid=0; if (!empty($this->student)) foreach ($this->student as $key => $rs){
							if ($rs['sex']==1){$sex = $tr->translate("MALE");}else{$sex = $tr->translate("FEMALE");}
						?>
						<?php if ($old_groupid!=$rs['group_id']){ ?>
						<?php if ($key>0){ 
						?>
						<tr>
							<td align="right" style="  border-left: 1px solid #fff; border-right: 1px solid #fff;">
								<span​​ style="color:#000; font-size: 12px;font-family: 'Times New Roman','Khmer OS Battambang';">
								<?php echo $tr->translate("TOTAL_STUDENT");?> : <span>&nbsp;<strong><?php echo $i;?></strong> <?php echo $tr->translate("STUDENT_UNIT");?>&nbsp;</span> 
								</span>
							</td>
						</tr>
						<?php }$i=0; ?>	
						<thead>										
							<tr>
								<td align="center" colspan="7" style=" border-top: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
									<span​​ style=" font-size: 12px;font-family: 'Times New Roman','Khmer OS Muol light';"><?php echo $tr->translate("STUDENT_MISTAKE");?></span><br />
									<span​​ style=" font-size: 12px;font-family:'Times New Roman','Khmer OS Muol light';">
										<?php echo $tr->translate("ACADEMIC_YEAR");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['academic_year'];?></span> ,
										<?php echo $tr->translate("DEGREE");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['degree'];?></span> 
										<br />
										<?php echo $tr->translate("GROUP");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['group_code'];?></span> , 
										<?php echo $tr->translate("GRADE");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['grade'];?></span> , 
									 	<?php echo $tr->translate("SEMESTER");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['semester'];?></span> , 
									 	<?php echo $tr->translate("ROOM_NAME");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['room_name'];?></span> 
									 	, <?php echo $tr->translate("SESSION");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['session'];?></span>
									</span>
								</td>
							</tr>						
							<tr class="style-head" >
								<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
								<td rowspan="2"><?php echo $tr->translate("STUDENT_CODE");?></td>
								<td rowspan="2"><?php echo $tr->translate("STUDENT_NAMEKHMER");?></td>
								<td rowspan="2">Name in Latin</td>
								<td rowspan="2"><?php echo $tr->translate("SEX");?></td>
								<td colspan="3" style="font-family: 'Times New Roman','Khmer OS Battambang';">&nbsp;<?php echo $tr->translate("DISCIPLINE_TYPE");?>&nbsp;</td>
							</tr>							
							<tr class="style-head">
								<td style="width: 40px;">&nbsp;<?php echo $tr->translate("SMALL_MISTACK");?>&nbsp;</td>
								<td style="width: 40px;">&nbsp;<?php echo $tr->translate("MEDIUM_MISTACK");?>&nbsp;</td>
								<td style="width: 40px;">&nbsp;<?php echo $tr->translate("BIG_MISTACK");?>&nbsp;</td>
							</tr>
						</thead>
						<?php } $i++;?>
						<tr class="style-rowdata hover">
							<td align="center">&nbsp;<?php echo $i;?>&nbsp;</td>
							<td><a style=" text-decoration: none; " href="<?php echo $this->url(array('controller'=>'score','action'=>'mistake-certificate','id'=>$rs['group_id'],'stu_id'=>$rs['stu_id']));?>" target="_blank">&nbsp; <?php echo $rs['stu_code'];?></a></td>
							<td><a style=" text-decoration: none; " href="<?php echo $this->url(array('controller'=>'score','action'=>'mistake-certificate','id'=>$rs['group_id'],'stu_id'=>$rs['stu_id']));?>" target="_blank">&nbsp; <?php echo $rs['stu_khname'];?>&nbsp;</a></td>
							<td><a style=" text-decoration: none; " href="<?php echo $this->url(array('controller'=>'score','action'=>'mistake-certificate','id'=>$rs['group_id'],'stu_id'=>$rs['stu_id']));?>" target="_blank">&nbsp; <?php echo $rs['last_name'].' '.$rs['stu_enname'];?>&nbsp;</a></td>
							<td align="center">&nbsp;<?php echo $sex;?>&nbsp;</td>
							<?php $s=0; $m=0; $b=0;$el=0; ?>
							<?php  
								$mistake_status = $db->getTotalStatusMistake($rs['stu_id'], null, $rs['group_id']);
								$lateAttedence = $db->getAttendenceFoul($rs['group_id'],$rs['stu_id']);
								$late_foul = 0;
								if (!empty($lateAttedence)){
									$late_foul = $lateAttedence['count_foul_att'];
								}
								if (!empty($mistake_status)) foreach ($mistake_status as $sta){
									if ($sta['mistake_type']==1){
										$s=$sta['count_mistack']+$late_foul;
									}
									else if ($sta['mistake_type']==2){
										$m = $sta['count_mistack'];
									}
									else if ($sta['mistake_type']==3){
										$b = $sta['count_mistack'];
									}else{
										echo " ";
									}
								}
								?>
							<td align="center"><?php echo $s+$late_foul;?></td>
							<td align="center"><?php echo $m;?></td>
							<td align="center"><?php echo $b;?></td>
						</tr>
							<?php $old_groupid = $rs['group_id'];
						}?>
						<tr>
							<td align="right" colspan="7" style=" border-bottom: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
								<span​​ style="font-family: 'Times New Roman','Khmer OS Battambang'; font-size: 12px;">
								<?php echo $tr->translate("TOTAL_STUDENT");?> : <span>&nbsp;<strong><?php echo $i;?></strong> <?php echo $tr->translate("STUDENT_UNIT");?>&nbsp;</span> 
								</span><br />
							</td>
						</tr>
					</table>	
				</td>
			</tr>
			<tr>
				<td colspan="3" width="100%">
					<?php echo $this->rsfooteracc;?>
				</td>
			</tr>
		</table>
	</div>
</div>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 

var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
	    }
	}, "group");
	
	new dijit.form.FilteringSelect({
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                        
		id: "grade_all",
		name: "grade_all",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
		}
	}, "grade_all");
	getallGrade();
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
    });
	 getAllAcademicByBranch();
	 getAllGroupByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
		    }
		},
		error: function(err) {
		}
	});
}
url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
		}
	});
}

var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id==''){return false;}
	dojo.xhrPost({
		url:url_dept,
		content:{
			'dept_id':dept_id
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('grade_all').set('store',grade_store);   
			dijit.byId('grade_all').attr('value','<?php echo $this->search['grade_all']?>');  
		},
		error: function(err) {
		}
	});
}
</script>