<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_RESCHEDULE_BYGROUP')); 
	$frm =  $this->form_search;
	$db_sub=new Allreport_Model_DbTable_DbRptStudentDrop();
	$day = array(
			1=>'Monday',
			2 =>'Tuesday',
			3 =>'Wednesday',
			4=>'Thursday',
			5=>'Friday',
	);
?>	
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_RESCHEDULE_BYGROUP');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("title");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("branch_id");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="study_year" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="group" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("room");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("grade");?>
            </div>
         </div>	
         <div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("start_date");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("end_date");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            </div>
         </div>
	</form>
	<table style="background:#fff; margin: 0 auto;width: 100%; font-family: 'Times New Roman','Kh Battambang','Khmer Battambang';">
		<tr>
			<td width="25%" align="left">
			</td>
			<td align="center">
				<strong style="font-weight:bold;color:#000; font-size: 14px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate("RPT_RESCHEDULE_BYGROUP");?></strong><br />
				<strong style="font-weight:bold;color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Battambang';"><?php if(!empty($this->search['start_date'])){?><?php echo date('d-M-Y',strtotime($this->search['start_date']));?><?php echo $tr->translate("TO");?><?php echo date('d-M-Y',strtotime($this->search['end_date']));}?> </strong>
			</td>
			<td width="25%" align="right">
			</td>
		</tr>
	</table>	
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto;width: 100%; font-family: 'Times New Roman','Kh Battambang','Khmer Battambang';">
		<style>
				table tr th{
					border: 1px solid #000;	
				}
				.hover:hover{background: #ccc;}
				table { page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				tr.head_schedule th {
				    padding: 5px 0;
				    text-align: center;
				}
				tr.head_schedule {
				    background-color: #ffdbdb;
				}
				thead tr th,tr.hover td,tr.head_schedule td {
				        border: 1px solid #4839bd;
				}
				.green {
				    color: #1ABB9C;
				}
				ul.subject {
				    list-style: none;
				    padding: 0;
				    line-height: 24px;
				    margin: 0;
				}
				tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
		</style>
			
				<?php $title=0; $titles=0; $year='';$group='';$hour=''; if(!empty($this->rs)) 
					foreach ($this->rs As $rs){
					$timestudy = $db_sub->getTimeSchelduleByYGS($rs['year_id'],$rs['group_id']);
					
					$branch_id = empty($rs['branch_id'])?1:$rs['branch_id'];
					$frm = new Application_Form_FrmGlobal();
					$rsheader = $frm->getLetterHeaderReport($branch_id);
					?>
					<tr>
						<td colspan="3">&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3"><?php echo $rsheader;?></td>
					</tr>
					<tr class="line"><td colspan="3"></td></tr>
					<tr>
						<td colspan="3">&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3" align="center">
							<span style="color: #4839bd; font-size:18px;font-weight: initial;font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("RPT_RESCHEDULE_BYGROUP");?></span>
						</td>
					</tr>
					<tr>
				<td colspan="3">
					<table border="1" cellpadding="5"​ style="color: #4839bd; margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;" >
						<thead>
							
							<tr>
								<td align="left" colspan="7" style="border:1px solid #fff;border-bottom: solid 1px #4839bd;">
								<ul class="subject">
									<li><?php echo $tr->translate("BRANCH_NAME");?>:&nbsp;<?php echo $rs['branch_name']?></li>
									<li><?php echo $tr->translate("ROOM");?>:&nbsp;<?php echo $rs['room_name']?></li>
									<li><?php echo $tr->translate("GROUP");?>:&nbsp;<?php echo $rs['group_code']?></li>	
								</ul>
								</td>
							</tr>
							<tr class="head_schedule" style="font-size:14px;" align="center" >
								<td rowspan="2" ><?php echo $tr->translate("TIME");?></td>
								<td colspan="5" ><?php echo $tr->translate("DAYS");?></td>
							</tr>
							<tr class="head_schedule" style="font-size:14px;" align="center" >
							<?php foreach ($day as $key => $days){?>
								<td style="width:18%;"><?php echo $tr->translate($days);?></td>
							<?php }?>
							</tr>
						</thead>
					<?php $session='';foreach($timestudy As $time){
						if($time['from_hour']<=12){
							if($title==0){?>
							<tr  align="center" >
								<td  align="center"  colspan="6" style="font-size:12px;padding: 5px 2px;text-decoration: underline;border: solid 1px #4839bd;"><?php echo  $tr->translate("Morning");?></td>
							</tr>
					        <?php $title=1;}
						}else{
							if($titles==0){
				        ?>
				        	<tr  align="center" >
								<td  align="center" colspan="6" style="font-size:12px;padding: 5px 2px;text-decoration: underline;border: solid 1px #4839bd;"><?php echo  $tr->translate("Afternoon");?></td>
							</tr>
				        <?php $titles=1;}
							}
				        ?>
							<tr class="hover" style="font-size:13px; height: 20px;" align="center" >
								<td align="center" style="min-width:50px;white-space: nowrap;"><strong><?php echo $time['times'];?></strong></td>
								<?php foreach ($day as $key => $days){
									$subjecNteacher = $db_sub->getSubjectTeacherByScheduleAndGroup($rs['year_id'],$rs['group_id'],$time['times'], $key)
								?>
								<td align="center">
									<?php 
								 	if (!empty($subjecNteacher)){
								 		if (!empty($subjecNteacher['subject_name'])){
								 			echo "(".$subjecNteacher['subject_name'].")<br />";
								 		}
								 		if (!empty($subjecNteacher['teacher_name'])){echo "".$subjecNteacher['teacher_name']."<br />";}
										if (!empty($subjecNteacher['teacher_phone'])){echo "".$subjecNteacher['teacher_phone']."";}
								   }?>
								</td>
								<?php }?>
							</tr>
					 <?php }?>						 
					 <?php  foreach($db_sub->getSubjectListByYG($rs['year_id'],$rs['group_id'] ) As $key=>$rs_list){
					 	if($rs_list['total_hour']>1){
					        $h_label='hrs';
					 	}else{
					 		$h_label='hr';
					 	}
					 	$totalTime = $db_sub->getSubjectForCalculateTime($rs['year_id'], $rs['group_id'], $rs_list['subject_id'])
					 ?>
					 <tr>
					    <td style="border-left: 1px solid #fff;border-right: 1px solid #fff;border-bottom: 1px solid #fff;padding:0px;line-height: 20px;" colspan="2"><?php echo $key+1?>.&nbsp;<?php echo $rs_list['subject_name']?>:&nbsp;<?php echo $totalTime;//$rs_list['total_hour'].''.$h_label?></td>
					 </tr>
					 <?php }?>
					 <tr >
					 	<td  style="border: 1px solid #fff;">&nbsp;</td>
					 </tr>
					</table>											
					</td>
				</tr>
				<tr>
					<td colspan="3" style="border:1px solid #fff;">
						<table cellpadding="0" cellspacing="0" width="100%" style="color:#4839bd; font-family:'Times New Roman','Khmer OS Battambang';font-size: 14px">
							<tr>
								<td width="35%" align="center">
									<span><?php echo $tr->translate("CHECKANDAPPROVED");?></span><br />
									<span style="font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("PRINCIPAL");?></span>
								</td>
								<td width="30%">&nbsp;</td>
								<td width="35%" align="center">
									<span><?php echo $tr->translate("CREATE_WORK_DATE");?></span><br />
									<span style="font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("PREPARE_BY");?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<?php  }?>
		</table>
	</div>		
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore"); 

dojo.require("dojo.html");
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                     
		id: "study_year",
		name: "study_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('study_year').get('value');
		}
	}, "study_year");
	new dijit.form.FilteringSelect({
		store: group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                      
	    id: "group",
	    name: "group",  
	    class: 'fullside', 
	    readonly:false,
	    required:false,
	    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
	    onChange: function() {  
		    
	    }
	}, "group");
	
	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
		 getAllGroupByBranch();
    });
	 getAllAcademicByBranch();
	 getAllGroupByBranch();
});
url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch = "<?php echo $this->search['branch_id']?>";
function getAllAcademicByBranch(){
	dijit.byId('study_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('study_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('study_year').set('store',academic_store);  
		    if(oldBranch==branch_id){
		    	dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
		    }
		},
		error: function(err) {
		}
	});
}
url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group').set('store',group_store);   
		    if(oldBranch==branch_id){
		    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
		    }
		},
		error: function(err) {
		}
	});
}
</script>