<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("STUDENT_SCORE_REPORT")); 
	$this->headTitle($tr->translate("STUDENT_SCORE_REPORT")); 
	echo $this->headTitle();
	$frm =  $this->form_search;
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$db = new Allreport_Model_DbTable_DbRptStudentScore();
	$day = array(
			"Mon" =>'ច័ន្ទ',
			"Tue" =>'អង្គារ',
			"Wed" =>'ពុធ',
			"Thu" =>'ព្រហស្បតិ៍',
			"Fri" =>'សុក្រ',
			"Sat" =>'សៅរ៍',
			"Sun" =>'អាទិត្យ',
	);
	$month = array(
				"01"=>"មករា",
				"02"=>"កុម្ភៈ",
				"03"=>"មិនា",
				"04"=>"មេសា",
				"05"=>"ឧសភា",
				"06"=>"មិថុនា",
				"07"=>"កក្កដា",
				"08"=>"សីហា",
				"09"=>"កញ្ញា",
				"10"=>"តុលា",
				"11"=>"វិច្ឆិកា",
				"12"=>"ធ្នូ"
			);
?>	
<script type="text/javascript">
//dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
//dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");
//dojo.require('dojox.form.BusyButton');
dojo.ready(function(){
	//control study year
		var group_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->g_all_name));?> );
		new dijit.form.FilteringSelect({
		    store:group_store,
		    autoComplete: true,                        
		    required:false,
		    id: "group_name",
		    name: "group_name",
		    class:'fullside',  
		    value:'<?php echo $this->search['group_name'];?>',         
		    required:'true',
		    placeHolder:"Selected Group Name",          
		    onChange: function() {  
		    }
		}, "group_name");
});
</script>
<form  action="<?php echo $this->url(array('module'=>'allreport','controller'=>'score','action'=>'rpt-score-bac-monthly')); ?>" dojoType="dijit.form.Form" method="post">
	<table style="width:90%">
		<tr> 
			<td><input id="group_name" /></td>
			<td><?php echo $frm->getElement("degree_bac");?></td>
			<td><?php echo $frm->getElement("grade_bac");?></td>
			<td><?php echo $frm->getElement("session");?></td>
		</tr>
		<tr>
			<td><?php echo $frm->getElement("study_year");?></td>
			<td>
				<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="for_month" name="for_month" type="text">								
					<?php if(!empty($this->month)){foreach ($this->month as $month){?>
						<option value="<?php echo $month['id']?>" <?php if($month['id']==$this->search['for_month']){echo "selected='selected'";}?>><?php echo $month['month_kh']?></option>
					<?php }}?>
				</select>
			</td>
			<td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
</form>
	<div style="border: 1px dotted #000;background: #fff;width:28cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
		<div id="divPrint">
		<style type="text/css">
			.style{
				line-height: 20px; font-size: 12px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
				
			}
			.padding{ padding: 0 1px !important;}
			table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
			tr{ page-break-inside:avoid; page-break-after:auto }
			.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap;}
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
		</style>
		<table style="width:27cm;background:#fff; margin: 0 auto; font-family: 'Times New Roman','Khmer OS Battambang'; ">
				<tr>
					<td colspan="3">
						<table  cellpadding="5"​ style="margin:0 auto;width:100%;border-collapse:collapse;border:1px solid #000;"  border="1" >
							<?php
							 $old_groupid=0; $i=0; $count_fail=0; $count=0; $old_average = 0; $old_rank=0;
							 if (!empty($this->studentgroup)){ foreach($this->studentgroup as $key=> $rs){ 
								if($rs['sex']==1){ $sex = $tr->translate("MALE");}else{$sex = $tr->translate("FEMALE");}
								$subj = $db->getSubjectScoreGroup($rs['group_id']);
							?>
							<?php if ($old_groupid!=$rs['group_id']){ $count = count($subj); ?>
								<?php if ($key>0){ 
								?>
								<tr>
									<td align="right" colspan="<?php echo $count+7;?>" style="  border-left: 1px solid #fff; border-right: 1px solid #fff;">
										<strong​​ style="font-weight:bold;color:#000; font-size: 13px;font-family: 'Times New Roman','Khmer OS Battambang';">
										<?php echo $tr->translate("TOTAL_STUDENT");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';">&nbsp;<?php echo $i." ".$tr->translate("STUDENT_UNIT");?>&nbsp;</span> 
										</strong><br />
										<strong​​ style="font-weight:bold;color:#000; font-size: 13px;font-family: 'Times New Roman','Khmer OS Battambang';">
										<?php echo $tr->translate("AMOUNT_STUDENT_FAIL");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';">&nbsp;<?php echo $count_fail." ".$tr->translate("STUDENT_UNIT");?>&nbsp;</span> 
										</strong><br />
									</td>
								</tr>
								<?php }$i=0; $count_fail=0;?>
							<tr>
								<td align="center" colspan="<?php echo $count+7;?>" style=" border-top: 1px solid #fff;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
									<strong​​ style="font-weight:bold;color:#000; font-size: 16px;font-family: 'Times New Roman','Khmer MEF2';"><?php echo $tr->translate("STUDENT_SCORE_REPORT");?></strong><br />
									<strong​​ style="font-weight:bold;color:#000; font-size: 13px;font-family:'Times New Roman','Khmer MEF2';">
										<?php echo $tr->translate("ACADEMIC_YEAR");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['academic_year'];?></span> ,
										<?php echo $tr->translate("DEGREE");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['degree'];?></span> ,
										<?php echo $tr->translate("MONTHLY");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['for_month'];?></span>
										<br />
										<?php echo $tr->translate("GROUP");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['group_code'];?></span> , 
										<?php echo $tr->translate("GRADE");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['grade'];?></span> , 
									 	<?php echo $tr->translate("SEMESTER");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['for_semester'];?></span> , 
									 	<?php echo $tr->translate("ROOM_NAME");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['room_name'];?></span> ,
									 	<?php echo $tr->translate("SESSION");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';"><?php echo $rs['session'];?></span>
									</strong>
								</td>
							</tr>
							<tr class="cheader" align="center" >
								<td><?php echo $tr->translate("NUM");?></td>
								<td><?php echo $tr->translate("ID_NUMBER");?></td>
								<td><?php echo $tr->translate("STUDENT_NAME");?></td>
								<td><?php echo $tr->translate("SEX");?></td>
								<?php  if (!empty($subj)) foreach ($subj as $subject){?>
								<td><?php echo $subject['subject_titlekh'];?></td>
								<?php }?>
								<td><?php echo $tr->translate("TOTAL_SCORE");?></td>
								<td><?php echo $tr->translate("AVERAGE");?></td>
								<td><?php echo $tr->translate("RESULT");?></td>
								<td><?php echo $tr->translate("RANK");?></td>
							</tr>
							<?php } $i++;?>
							<tr class="style" style=" line-height: 18px;">
								<td align="center">&nbsp;<?php echo $i;?>&nbsp;</td>
								<td align="center" style="white-space:nowrap;">&nbsp;<?php echo $rs['stu_code'];?>&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $rs['stu_khname'];?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo $sex;?>&nbsp;</td>
								<?php 
									$total_score = 0; 
									$subj = $db->getSubjectScoreGroup($rs['group_id']); 
									if (!empty($subj)) foreach ($subj as $subject){
								?>
								<td align="center">
									<?php $score = $db->getScoreBySubject($rs['id'],$rs['student_id'],$subject['subject_id']); echo number_format($score['score'],2); $total_score = $total_score + $score['score'];?>
								</td>
								<?php }?>
								<td align="center"><?php echo number_format($rs['total_score'],2);?></td>
								<td align="center"><?php echo number_format($rs['average'],2);// Average ?></td>
								<td align="center" <?php if(($total_score/$count)<50){echo 'style=" background: #fe4747;"'; $count_fail++;}?>>
									<?php if(($total_score/$count)>=50){echo $tr->translate("STUDENT_PASS");}else{echo $tr->translate("STUDENT_FAIL");}?>
								</td>
								<td><label id="record<?php echo $i;?>"></label></td>
							</tr>
							<?php $old_groupid=$rs['group_id']; ?>
							<?php }}?>
							<?php if (!empty($this->studentgroup)){?>
							<tr>
								<td align="right" colspan="<?php echo $count+7;?>" style="  border-left: 1px solid #fff; border-right: 1px solid #fff;  border-bottom: 1px solid #fff;" >
									<strong​​ style="font-weight:bold;color:#000; font-size: 13px;font-family: 'Times New Roman','Khmer OS Battambang';">
									<?php echo $tr->translate("STUDENT_PASS");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';">&nbsp;<?php echo $i." ".$tr->translate("STUDENT_UNIT");?>&nbsp;</span> 
									</strong><br />
									<strong​​ style="font-weight:bold;color:#000; font-size: 13px;font-family: 'Times New Roman','Khmer OS Battambang';">
										<?php echo $tr->translate("STUDENT_FAIL");?> : <span style="font-family: 'Times New Roman','Khmer OS Battambang';">&nbsp;<?php echo $count_fail." ".$tr->translate("STUDENT_UNIT");?>&nbsp;</span> 
									</strong>
								</td>
							</tr>
							<?php }?>
						</table>
					</td>
				</tr>
			</table>
		</div>
	</div>