<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("តារាងកិត្តិយស")); 
	echo $this->headTitle();
	$frm =  $this->form_search;
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$db = new Allreport_Model_DbTable_DbRptStudentScore();
	
	$semester = array(
				"1"=>"១",
				"2"=>"២",
			); 
?>	
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<div style="min-height:15cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div id="divPrint">
		<style type="text/css">
			.style{
				line-height: 21px; font-size: 15px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
				white-space: nowrap;
			}
			.padding{ padding: 0 1px !important;}
			table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
			tr{ page-break-inside:avoid; page-break-after:auto }
			.cheader{height: 27px;font-weight: bold; background: #ccc; white-space: nowrap;}
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
		</style>
		<table style="width:27cm;background:#fff; margin: 0 auto; font-family: 'Times New Roman','Khmer OS Battambang'; ">
				<?php
					 $i=0;$old_average = 0; $old_rank=0;
					 $rank1="";$rank2="";$rank3="";$rank4="";$rank5="";
					 if (!empty($this->studentgroup)){ foreach($this->studentgroup as $key=> $rs){
						$semester_average = @($rs['avg_forsemester']+$rs['avg_formonth'])/2;
						if($semester_average == $old_average){
							if($key==1){
								$rank2=$old_rank;
							}
							if($key==2){
								$rank3=$old_rank;
							}
							if($key==3){
								$rank4=$old_rank;
							}
							if($key==4){
								$rank5=$old_rank;
							}
						}else{
							if($key==0){
								$rank1="១";
								$old_rank = "១";
							}
							if($key==1){
								$rank2="២";
								$old_rank = "២";
							}
							if($key==2){
								$rank3="៣";
								$old_rank = "៣";
							}
							if($key==3){
								$rank4="៤";
								$old_rank = "៤";
							}
							if($key==4){
								$rank5="៥";
								$old_rank = "៥";
							}
						}
					?>
					<?php 
						$old_average = $semester_average;
					?>
					
				<?php }}?>
				<tr>
					<td>
						<table width="100%" border="0" style="background-image: url('logo.png');" border="1">
							<tr>
								<td colspan="3" align="center" style="font-family: Khmer OS Muol Light;font-size: 25px;">
									ព្រះរាជាណាចក្រកម្ពុជា <br />
									ជាតិ សាសនា ព្រះមហាក្សត្រ <br />
									<img style="width: 20%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/style.png'?>">
								</td>
							</tr>						
							<tr>
								<td width="33%">&nbsp;</td>
								<td width="34%">&nbsp;</td>	
								<td width="33%">&nbsp;</td>
							</tr>
							<tr>
								<td>
									<table width="70%">
										<tr>
											<td width="100%" align="center">
												<?php $logo = $this->baseUrl().'/images/logo.png';
													if (!empty($this->studentgroup[0]['branch_logo'])){
														$logo = $this->baseUrl().'/images/'.$this->studentgroup[0]['branch_logo'];
													}
													?>
												<img style="width: 65%;" alt="<?php ?>" src="<?php echo $logo;?>"><br />
											</td>
										</tr>
									</table>
								</td>
								<td align="center" style="font-family: Khmer OS Muol Light;font-size: 22px;">
									<span style="font-size: 25px;">តារាងកិត្តិយស </span><br />
									ប្រចាំឆមាស <?php echo $semester[$this->studentgroup[0]['for_semester']];?><br />
									<span style="white-space: nowrap;">ថ្នាក់  <?php echo $this->studentgroup[0]['group_code'];?></span><br />
									ឆ្នាំសិក្សា  <label id="academic_year"></label>
								</td>
								<script type="text/javascript">
									year = convertEnglishToKhmerNumber('<?php echo $this->studentgroup[0]['start_year'];?>')+' - '+convertEnglishToKhmerNumber('<?php echo $this->studentgroup[0]['end_year'];?>');
									dojo.byId('academic_year').innerHTML=year;
								</script>
								<td></td>
							</tr>
							<style>
								.number{color: red;}
								.studentname{color:#1318b9;font-size: 19px;}
							</style>
							<tr>
								<td>&nbsp;</td>
							</tr>	
							<tr>
								<td>&nbsp;</td>
								<td>
									<table width="100%" style="margin: 0 auto; font-family: Khmer OS Muol Light;font-size: 17px;">
										<tr>
											<td align="center">
												<table width="125px" height="150px">
													<tr>
														<td style="border:1px solid #000;">
															<img style="width: 125px;height: 150px;" alt="<?php ?>" src="<?php if(!empty($this->studentgroup[0])){echo $this->baseUrl().'/images/photo/'.$this->studentgroup[0]['photo'];}?>">
														</td>
													</tr>
												</table>											
											</td>
										</tr>
										<tr align="center">
											<td colspan="1" class="number">លេខ <?php echo $rank1;?></td>
										</tr>
										<tr align="center">
											<td class="studentname" colspan="1">
												<?php if(!empty($this->studentgroup[0])){if(!empty($this->studentgroup[0]['stu_khname'])){echo $this->studentgroup[0]['stu_khname'];}else{echo $this->studentgroup[0]['stu_enname'];}}?>
											</td>
										</tr>
									</table>
								</td>
								<td>&nbsp;</td>
							</tr>	
							<tr>
								<td>
									<table width="50%" style="margin: 0 auto;font-family: Khmer OS Muol Light;font-size: 17px;">
										<tr>
											<td align="center">
												<table width="125px" height="150px">
													<tr>
														<td style="border:1px solid #000;">
															<img style="width: 125px;height: 150px;" alt="<?php ?>" src="<?php if(!empty($this->studentgroup[1])){echo $this->baseUrl().'/images/photo/'.$this->studentgroup[1]['photo'];}?>">
														</td>
													</tr>
												</table>											
											</td>
										</tr>
										<tr align="center">
											<td class="number">លេខ <?php echo $rank2;?></td>
										</tr>
										<tr align="center">
											<td class="studentname" >
												<?php if(!empty($this->studentgroup[1])){if(!empty($this->studentgroup[1]['stu_khname'])){echo $this->studentgroup[1]['stu_khname'];}else{echo $this->studentgroup[1]['stu_enname'];}}?>
											</td>
										</tr>
									</table>
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									<table width="50%" style="margin: 0 auto;font-family: Khmer OS Muol Light;font-size: 17px;">
										<tr>
											<td align="center">
												<table width="125px" height="150px">
													<tr>
														<td style="border:1px solid #000;">
															<img style="width: 125px;height: 150px;" alt="<?php ?>" src="<?php if(!empty($this->studentgroup[2])){echo $this->baseUrl().'/images/photo/'.$this->studentgroup[2]['photo'];}?>">
														</td>
													</tr>
												</table>											
											</td>
										</tr>
										<tr align="center">
											<td class="number">លេខ <?php echo $rank3;?></td>
										</tr>
										<tr align="center">
											<td style=""  class="studentname" >
												<?php if(!empty($this->studentgroup[2])){if(!empty($this->studentgroup[2]['stu_khname'])){echo $this->studentgroup[2]['stu_khname'];}else{echo $this->studentgroup[2]['stu_enname'];}}?>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="3">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="3">&nbsp;</td>
							</tr>							
							<tr>
								<td>
									<table width="50%" style="margin: 0 auto;font-family: Khmer OS Muol Light;font-size: 17px;">
										<tr>
											<td align="center">
												<table width="125px" height="150px">
													<tr>
														<td style="border:1px solid #000;">
															<img style="width: 125px;height: 150px;" alt="<?php ?>" src="<?php if(!empty($this->studentgroup[3])){echo $this->baseUrl().'/images/photo/'.$this->studentgroup[3]['photo'];}?>">
														</td>
													</tr>
												</table>											
											</td>
										</tr>
										<tr align="center">
											<td class="number">លេខ <?php echo $rank4;?></td>
										</tr>
										<tr align="center">
											<td style=""  class="studentname" >
												<?php if(!empty($this->studentgroup[3])){if(!empty($this->studentgroup[3]['stu_khname'])){echo $this->studentgroup[3]['stu_khname'];}else{echo $this->studentgroup[3]['stu_enname'];}}?>
											</td>
										</tr>
									</table>
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									<table width="50%" style="margin: 0 auto;font-family: Khmer OS Muol Light;font-size: 17px;">
										<tr>
											<td align="center">
												<table width="125px" height="150px">
													<tr>
														<td style="border:1px solid #000;">
															<img style="width: 125px;height: 150px;" alt="<?php ?>" src="<?php if(!empty($this->studentgroup[4])){echo $this->baseUrl().'/images/photo/'.$this->studentgroup[4]['photo'];}?>">
														</td>
													</tr>
												</table>											
											</td>
										</tr>
										<tr align="center">
											<td class="number">លេខ <?php echo $rank5;?></td>
										</tr>
										<tr align="center">
											<td  class="studentname" >
												<?php if(!empty($this->studentgroup[4])){if(!empty($this->studentgroup[4]['stu_khname'])){echo $this->studentgroup[4]['stu_khname'];}else{echo $this->studentgroup[4]['stu_enname'];}}?>
											</td>
										</tr>
									</table>
								</td>
							</tr>	
							<tr>
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">
									&nbsp;
								</td>
							</tr>	
							<tr>	
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>	
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>	
								<td colspan="3">
									<table cellpadding="0" cellspacing="0" width="100%" style="font-family:'Khmer OS Battambang';font-size: 14px">
										<tr>
											<td width="35%" align="center">
												<span style="color:#000; font-size: 16px;font-family:Times New Roman,Khmer OS Battambang;"><?php echo $tr->translate("CHECKANDAPPROVED");?></span><br />
												<span style="color:#000; font-size: 16px;font-family:Times New Roman,Khmer OS Battambang;"><?php echo $tr->translate("PRINCIPAL");?></span>
											</td>
											<td width="30%">&nbsp;</td>
											<td width="35%" align="center">
												<span style="color:#000; font-size: 16px;font-family:Times New Roman,Khmer OS Battambang;;"><?php echo $tr->translate("CREATE_WORK_DATE");?></span><br />
												<span style="color:#000; font-size: 16px;font-family:Times New Roman,Khmer OS Battambang;;"><?php echo $tr->translate("TEACHER_ROOM");?></span>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>	
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>	
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>	
								<td colspan="3">
									&nbsp;
								</td>
							</tr>
							<tr>	
								<td colspan="2">
									&nbsp;
								</td>
								<td colspan="1" align="center" style="font-family: Khmer OS Muol Light;font-size: 15px;">
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <?php echo $this->studentgroup[0]['teacher_name'];?>
								</td>
							</tr>
						</table>
					</td>
				</tr>
		</table>
	</div>
</div>