<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('SCORE_SEMESTER_YEAR')); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
?>
<div style="min-height:10cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<div class="card-box">
    	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SCORE_SEMESTER_YEAR');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'score','action'=>'student-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("adv_search");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("branch_id");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("academic_year");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="group" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="teacher" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("study_status");?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("degree");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<input id="grade" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php echo $frm->getElement("session");?>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<?php //echo $frm->getElement("room");?>
            	<input id="room" />
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
            </div>
        </div>
	</form>	
<style>
.hidden{
	display: table-cell !important;
}
</style>
	<div id="divPrint">
		<table style="background:#fff; margin: 0 auto; width: 100%;">
			<tr>
				<td colspan="3"><?php echo $this->rsheader;?></td>
			</tr>
			<tr class="line"><td colspan="3"></td></tr>
			<tr>
				<td width="28%" align="left"></td>
				<td width="44%" align="center">
					<p><strong style="font-weight:normal;color:#000; font-size: 14px;font-family:Times New Roman,'Khmer OS Muol Light';"><?php echo $tr->translate("SCORE_SEMESTER_YEAR");?></strong></p>
				</td>
				<td align="right" width="28%"></td>
			</tr>
			<tr>
				<td colspan="3" valign="top" id="exportExcel">
						<style type="text/css">
							th,td{ padding:0 1px;}
							table{ border-collapse:collapse; margin:0 auto;border-color:#000; }
							.padding{ padding: 0 1px !important;}
							table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
							tr{ page-break-inside:avoid; page-break-after:auto }
							#header {display: table-header-group;page-break-inside:avoid; page-break-after:auto;}
							.hover:hover{background: #ccc;}
							.hidden{display: none;}
							tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }
						</style>
						<?php 
						$all_student = 0;
						$active_student = 0;
						$drop_student = 0;?>
					<div id="exportExcel">
						<table cellpadding="3" class="padd" width="99%" border="1" align="left" style="white-space:nowrap;font-family:Times New Roman,Khmer OS Battambang">
						  <thead>
							  <tr style="font-size:12px; height: 28px; font-weight: bold; background: #ccd9ff;" align="center">
								<td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("BRANCH");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("STUDY_GROUP");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("ACADEMIC_YEAR");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("SEMESTER");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("SESSION");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("CLASSES");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("STATUS");?>&nbsp;</td>
								<!-- <td>&nbsp;<?php echo $tr->translate("TOTAL_STUDENT");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("STUDENT_DROP");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("STUDENT_STUDY");?>&nbsp;</td> -->
							  </tr>
						  </thead>
						  <?php $i=0; 
						  foreach($this->rs as $rs)if (!empty($this->rs)){ $i++;?>
							  <tr oncontextmenu="setrowdata(<?php echo $rs['id'];?>);return false;" style="font-size:12px; height: 24px;"​ align="left" class='hover padding context-menu-one'>
								<td align="center"><?php echo $i;?></td>
								<td><?php echo $rs['branch_name']; ?></td>
								<td><?php echo $rs['group_code']; ?></td>
								<td><?php echo $rs['academic']; ?></td>
								<td><?php echo $rs['semester']; ?></td>
								<td>&nbsp;<?php echo $rs['session']; ?>&nbsp;</td>
								<td align="left">&nbsp;&nbsp;<?php echo $rs['room_name']; ?>&nbsp;</td>
								<td>&nbsp;<?php echo $rs['status']; ?>&nbsp;</td>
								<!-- 
								<td>&nbsp;<?php //echo $rs['Num_Student']; ?>&nbsp; <?php //echo $tr->translate("STUDENT_UNIT");?></td>
								<td>&nbsp;<?php //echo $rs['student_drop']; ?>&nbsp; <?php //echo $tr->translate("STUDENT_UNIT");?></td>
								<td>&nbsp;<?php //echo $rs['Num_Student']-$rs['student_drop']; ?>&nbsp; <?php //echo $tr->translate("STUDENT_UNIT");?></td>
							  	 -->
							  </tr>
						  <?php 
							  	$all_student = $all_student+$rs['Num_Student'];
							  	$drop_student = $drop_student+$rs['student_drop'];
							} ?>
						</table>
						<br>
						<!-- <table cellpadding="3" class="padd" width="20%" align="right" style="font-size:14px;line-height:27px;white-space:nowrap;font-family:Time New Roman , Khmer OS Battambang;margin-bottom:10px;color:#4839bd;">
							<tr>
								<td width="60%" style="border-bottom:1px solid #4839bd;"><?php echo $tr->translate("TOTAL_STUDENT");?></td>
								<td width="40%" align="center" style="border-bottom:1px solid #4839bd;"><strong><?php echo $all_student;?> <?php echo $tr->translate("STUDENT_UNIT");?></strong></td>
							</tr>
							<tr>
								<td style="border-bottom:1px solid #4839bd;"><?php echo $tr->translate("STUDENT_DROP");?></td>
								<td align="center" style="border-bottom:1px solid #4839bd;"><strong><?php echo $drop_student;?> <?php echo $tr->translate("STUDENT_UNIT");?></strong></td>
							</tr>
							<tr>
								<td style="border-bottom:1px solid #4839bd;"><?php echo $tr->translate("STUDENT_STUDY");?></td>
								<td align="center" style="border-bottom:1px solid #4839bd;"><strong><?php echo $all_student - $drop_student;?> <?php echo $tr->translate("STUDENT_UNIT");?></strong></td>
							</tr>
						</table> -->
					</div>
				</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
			<tr >
				<td colspan="3" width="100%">
					<table cellpadding="0" cellspacing="0" width="100%" style="font-size: 14px">
						<tr>
							<td width="35%" align="center">
								<span style="color:#4839bd; font-size: 14px;font-family:Times New Roman , khmer os battambang;"><?php echo $tr->translate("CHECKANDAPPROVED");?></span><br />
								<span style="color:#4839bd; font-size: 14px;font-family:Times New Roman , Khmer OS Muol Light;"><?php echo $tr->translate("PRINCIPAL");?></span>
							</td>
							<td width="30%">&nbsp;</td>
							<td width="35%" align="center">
								<span style="color:#4839bd; font-size: 14px;font-family:Times New Roman , khmer os battambang;"><?php echo $tr->translate("CREATE_WORK_DATE");?></span><br />
								<span style="color:#4839bd; font-size: 14px;font-family:Times New Roman , Khmer OS Muol Light;"><?php echo $tr->translate("PREPARE_BY");?></span>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>	
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var teacher_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var room_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){

		new dijit.form.FilteringSelect({
			store: teacher_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,
			id: "teacher",
			name: "teacher",           
			class: "fullside", 
			placeHolder:"<?php echo $tr->translate("SELECT_TEACHER");?>",          
			onChange: function() {  
			}
		}, "teacher");

		new dijit.form.FilteringSelect({
			store: room_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "room",
			name: "room",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ROOM");?>",          
			onChange: function() {
				  
			}
		}, "room");
		
		new dijit.form.FilteringSelect({
			store: group_store,
		    queryExpr: "*${0}*",
			autoComplete: false,                     
		    id: "group",
		    name: "group",  
		    class: 'fullside', 
		    readonly:false,
		    required:false,
		    placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",          
		    onChange: function() {  
			    
		    }
		}, "group");
		
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade",
			name: "grade",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
			}
		}, "grade");
		
		 var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getAllGroupByBranch();
			 getRefreshRoom();
			 getRefreshTeacher();
	    });
		 var academic_year = dijit.byId('academic_year');
		 academic_year.on('change', function(evt) {
			 getAllGroupByBranch();
	    });
		 getallGrade();
		 getRefreshTeacher();
		 getAllGroupByBranch();
		 getRefreshRoom();
	});
	var oldBranch = "<?php echo $this->search['branch_id']?>";
	url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getallgroup'));?>';
	function getAllGroupByBranch(){
		dijit.byId('group').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('group').set('store',group_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		degree = dijit.byId('degree').get('value');
		if(degree=='' || degree==-1){degree ="";}
		grade = dijit.byId('grade').get('value');
		if(grade=='' || grade==-1){grade ="";}
		academic_year = dijit.byId('academic_year').get('value');
		if(academic_year=='' || academic_year==-1){academic_year ="";}
		
		dojo.xhrPost({
			url: url_getgroup,
			content:{
				'branch_id':branch_id,'degree':degree,'grade':grade,'academic_year':academic_year,'noaddnew':1,'forfilter':1
				},
			handleAs:"json",
			load: function(data) {
			    group_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('group').set('store',group_store);   
			    if(oldBranch==branch_id){
			    	dijit.byId('group').set('value','<?php echo $this->search['group']?>');  
			    }
			},
			error: function(err) {
			}
		});
	}
	var url_dept = '<?php echo $this->url(array('module'=>'global','controller'=>'grade','action'=>'get-grade')); ?>';
	function getallGrade(){
		getAllGroupByBranch();  
		dept_id = dijit.byId('degree').get('value');
		if(dept_id=='' || dept_id==-1){return false;}
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id,
					'noaddnew':1
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId('grade').attr('value','');
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store); 
				    dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');  
				},
				error: function(err) {
				}
			});
	}
	var url_gettecher = '<?php echo $this->url(array("module"=>"foundation","controller"=>"lecturer","action"=>"getteacher"));?>';										
	function getRefreshTeacher(){
		dijit.byId('teacher').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var teacher_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('teacher').set('store',teacher_store);  
			return false;
		}
		dojo.xhrPost({
			url:url_gettecher,
			content:{
				'branch_id':branch_id,'has_addnew':1
				},
			handleAs:"json",
			load: function(data) {
			    teacher_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('teacher').set('store',teacher_store);  
			    if(oldBranch==branch_id){
			   	 dijit.byId('teacher').set('value','<?php echo $this->search['teacher']?>'); 
			    }
			    document.getElementsByClassName("overlay")[0].style.display="none";
			},
			error: function(err){
				document.getElementsByClassName("overlay")[0].style.display="none";
			}
		});
	}

	var url_getRoom = '<?php echo $this->url(array("module"=>"global","controller"=>"room","action"=>"getroom"));?>';	
	function getRefreshRoom(){
		dijit.byId('room').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id == -1){
			return false;
		}
		dojo.xhrPost({
			url: url_getRoom,
			handleAs:"json",
			content:{
					'branch_id':branch_id,'has_addnew':1
					},
			load: function(data) {
				room_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('room').set('store',room_store);  
			    if(oldBranch==branch_id){
			    	dijit.byId('room').set('value','<?php echo $this->search['room']?>');  
			    }
			    document.getElementsByClassName("overlay")[0].style.display="none";
			},
			error: function(err) {
				document.getElementsByClassName("overlay")[0].style.display="none";
			}
		});
	}
<?php
	$urlResultSemester1 = $this->baseUrl()."/allreport/score/rpt-resultbysemester/id/";
	$urlHonorSemester1 = $this->baseUrl()."/allreport/score/semester-outstanding-student/id/";
	$urlHonorSemester1_nophoto = $this->baseUrl()."/allreport/score/semester-outstanding-student-nophoto/id/";
	
	$urlResultSemester2 = $this->baseUrl()."/allreport/score/rpt-resultbysemester/id/";
	$urlHonorSemester2 = $this->baseUrl()."/allreport/score/semester-outstanding-student/id/";
	$urlHonorSemester2_nophoto = $this->baseUrl()."/allreport/score/semester-outstanding-student-nophoto/id/";
	
	$urlResultYearly = $this->baseUrl()."/allreport/score/rpt-resultbyyear/id/";
	$urlHonorYearly = $this->baseUrl()."/allreport/score/yearly-outstanding-student/id/";
	$urlHonorYearly_nophoto = $this->baseUrl()."/allreport/score/yearly-outstanding-student-nophoto/id/";
	
	$type1 = "/type/1";
	$type2 = "/type/2";
	$type3 = "/type/3";
?>
	var row=0;
	var url="";
	var type="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				if(key=="rpt-resultbysemester1"){
					url='<?php echo $urlResultSemester1;?>';
					type='<?php echo $type1;?>';
				}else if(key=="rpt-resultbysemester2"){
					url='<?php echo $urlResultSemester2;?>';
					type='<?php echo $type2;?>';
				}else if(key=="rpt-resultbyyear"){
					url='<?php echo $urlResultYearly;?>';
					type='<?php echo $type3;?>';
				}else if(key=="semester-outstanding-student1"){
					url='<?php echo $urlHonorSemester1;?>';
					type='<?php echo $type1;?>';
				}
				else if(key=="semester-outstanding-student1-nophoto"){
					url='<?php echo $urlHonorSemester1_nophoto;?>';
					type='<?php echo $type1;?>';
				} 
				else if(key=="semester-outstanding-student2"){
					url='<?php echo $urlHonorSemester2;?>';
					type='<?php echo $type2;?>';
				}
				else if(key=="semester-outstanding-student2-nophoto"){
					url='<?php echo $urlHonorSemester2_nophoto;?>';
					type='<?php echo $type2;?>';
				}
				else if(key=="yearly-outstanding-student"){
					url='<?php echo $urlHonorYearly;?>';
					type='<?php echo $type3;?>';
				}
				else if(key=="yearly-outstanding-student-nophoto"){
					url='<?php echo $urlHonorYearly_nophoto;?>';
					type='<?php echo $type3;?>';
				}  
				gotoAction();
			},
			items: {
				"rpt-resultbysemester1": {name: "<?php echo $tr->translate("RESULT_SEMESTER1");?>", icon: "fa-file-text-o",},
				"rpt-resultbysemester2": {name: "<?php echo $tr->translate("RESULT_SEMESTER2");?>", icon: "fa-file-text-o"},
				"rpt-resultbyyear": {name: "<?php echo $tr->translate("YEARLY_EXAM");?>", icon: "fa-file-text-o"},
				"semester-outstanding-student1": {name: "<?php echo $tr->translate("HONOR_SEMESTER1");?>", icon: "fa-file-text-o"},
				"semester-outstanding-student1-nophoto": {name: "<?php echo $tr->translate("HONOR_SEMESTER1");?> (No Photo)", icon: "fa-file-text-o"},
				"semester-outstanding-student2": {name: "<?php echo $tr->translate("HONOR_SEMESTER2");?>", icon: "fa-file-text-o"},
				"semester-outstanding-student2-nophoto": {name: "<?php echo $tr->translate("HONOR_SEMESTER2");?> (No Photo)", icon: "fa-file-text-o"},
				"yearly-outstanding-student": {name: "<?php echo $tr->translate("HONOR_YEARLY");?>", icon: "fa-file-text-o"},
				"yearly-outstanding-student-nophoto": {name: "<?php echo $tr->translate("HONOR_YEARLY");?> (No Photo)", icon: "fa-file-text-o"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		window.open(url+row+type);
	}
</script>