<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_STUDENT_SERVICE_PAYMENT')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.store.Memory");
	dojo.ready(function(){ 
		addRow();
		<?php /*?>
		new dijit.form.FilteringSelect({
		    store: student_store,
		    autoComplete: true,                        
		    required: true,
		    id: "studentid",
		    name: "studentid",           
		    class: 'fullside',  
		    placeHolder:"Selected Student id",          
		    onChange: function() {  
		    	//dept_id = dijit.byId('dept').get('value');
		    	//dijit.byId('grade').attr('value','');
		    	//getallModel(dept_id,a=''); 
		    	//getStudentNo(dept_id);
		    	setID(1);
		    	getStudentInfo();getservicefee();
		    	
		    }
		}, "studentid");

		new dijit.form.FilteringSelect({
		    store: student_store,
		    autoComplete: true,                        
		    required: true,
		    id: "stu_name",
		    name: "stu_name",           
		    class: 'fullside',  
		    placeHolder:"Selected Student name",          
		    onChange: function() {  
				setID(2);
			}
		}, "stu_name");
		<?php */ ?>
	});	

</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
.head-td{font-size: 12px;}
</style>
<?php $register = $this->frm_register;
//print_r($register);
?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
	if(dijit.byId('study_year').get('value')==-1){
		alert("You must select Year ! ");
		dijit.byId('study_year').focus();
		return false;
	}
    else if(this.validate()) {
    	return true;
    }else {
    	return false;
    }
</script>
<table id="head_tbl"  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong​ style="font-size: 18px;"><?php echo $tr->translate("ADD_STUDENT_SERVICE_PAYMENT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" cellpadding="10px" >
						<tr>
							<td style="width: 12%"><?php echo $tr->translate("STUDY_YEAR");?></td>
							<td style="width: 37%"><?php echo $register->getElement('study_year');?></td>
							<td align="right" style="width: 12%"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td align="center" style="width: 37%"><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td>
								<select type="text" class="fullside" dojoType="dijit.form.FilteringSelect" name="studentid" id="studentid" onChange="getStudentInfo();setID(1);" >
									<option value="-1">Select Student ID</option>
									<?php if(!empty($this->rs)){foreach ($this->rs as $rs){?>
									<option value="<?php echo $rs['id']?>"><?php echo $rs['code']?></option>
									<?php }}?>
								</select>
							</td>
							<td align="right"><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td align="center">
								<select type="text" style="" class="fullside" dojoType="dijit.form.FilteringSelect" name="stu_name" id="stu_name" onChange="setID(2);" >
									<option value="-1">Select Student Name</option>
									<?php if(!empty($this->row)){foreach ($this->row as $row){?>
									<option value="<?php echo $row['id']?>"><?php echo $row['name']?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
							<td align="right"><?php echo $tr->translate("NAME_KH");?></td>
							<td align="center"><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("SEX");?></td>
							<td ><?php echo $register->getElement('sex');?></td>
						    <td align="right"><?php echo $tr->translate("NOT");?></td>
							<td align="center"><?php echo $register->getElement('not');?></td>	
						</tr>
						<tr>
							<td colspan="4">
								<table>
									<tr>
										<td style="padding-left: 20px;"><input type="checkBox" dojoType="dijit.form.CheckBox" value="07:00 am" id="time1" name="time1" onclick="getValue()" />07:00 am</td>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="07:30 am" id="time2" name="time2" onclick="getValue();" />07:30 am</td>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="10:30 am" id="time3" name="time3" onclick="getValue();" />10:30 am</td>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="11:00 am" id="time4" name="time4" onclick="getValue();" />11:00 am</td>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="01:00 pm" id="time5" name="time5" onclick="getValue();" />01:00 pm</td>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="01:30 pm" id="time6" name="time6" onclick="getValue();" />01:30 pm</td>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="04:30 pm" id="time7" name="time7" onclick="getValue();" />04:30 pm</td>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="05:00 pm" id="time8" name="time8" onclick="getValue();" />05:00 pm</td>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="05:30 pm" id="time9" name="time9" onclick="getValue();" />05:30 pm</td>
										<input type="hidden" id="time" name="time" />
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
							</td>
						</tr>
						<tr>
							<td colspan="4">
								<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="2"><input type="hidden" id="identity" name="identity" /></td>
							<td colspan="2" align="right">
								<table style="width:400px;border-collapse: collapse;" cellpadding="10" cellspacing="10" >
									<tr>
										<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
										<td align="right"><input type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("RECEIVED_AMOUNT");?></td>
										<td align="right"><input  type="text" onkeyup="calculatBalanceAndReturn();" required="true"  name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("BALANCE");?></td>
										<td align="right"><input type="text" readonly="readonly" name="total_balance" value="<?php echo 0?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("RETURN");?></td>
										<td align="right"><input type="text" readonly="readonly" name="total_return" id="total_return" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
								<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
								<input type="submit" name="save_close" id="save_close" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								 
								<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								
								 <input type="button" value="បោះពុម្ព" label="<?php echo $tr->translate('PRINT');?>" id="print" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">
function printSave(){		
		if(dijit.byId('office_receipt').validate()) {
	
	dojo.byId("lbl_khname").innerHTML = dijit.byId("kh_name").get('value');
	dojo.byId("lbl_enname").innerHTML = dijit.byId("en_name").get('value');
	dojo.byId("lbl_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
	dojo.byId("lbl_stuid").innerHTML = dijit.byId("studentid").attr('displayedValue');
	dojo.byId("lbl_recieptno").innerHTML = dijit.byId("reciept_no").get('value');
	var total = dijit.byId("grand_total").get('value');
	var recieve = dijit.byId("total_received").get('value');
	var balance_due = dijit.byId("total_balance").get('value');
	var toral_return = dijit.byId("total_return").get('value');
	
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	template="";
		 temp='<table class="collape tablesorter" border="1" align="center" style=" width: 100%; padding: 0px; margin: 0px; border-collapse: collapse; white-space:nowrap; border: 1px solid #000; font-size:10px;  " id="table">'
		      temp+='<tr style="background:#ccc; font-size:10px; "><th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate("លេខ/No");?></strong></th>';
		      temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate("ឈ្មោះសេវាកម្ម / Service Name");?></strong></th>';
		      temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate(" បង់ជា / Payment Term ");?></strong></th>';
		      temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate(" តំលៃ / Price ");?></strong></th>';
		      temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate(" ចំនួន / Amount ");?></strong></th>';
		      temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate(" បញ្ចុះតំលៃ / Discount ");?></strong></th>';
		      temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate(" តំលៃសរុប​ / Sub Total ");?></strong></th>';
		      temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate(" ថ្ងៃចាប់ផ្តើម / Start Date ");?></strong></th>';
		      temp+='<th><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;"><?php echo $tr->translate(" សុពលភាព / Validate ");?></strong></th></tr>';
 
			    i=1;  for(var n = 0; n < rowIDArray.length; n++) {
			     
		      temp+='<tr style=" font-size:10px;height: 23px;"​ align="center"><td align="center" style="border:1px solid #000;">'+i+'</td>';
		      temp+='<td align="left" style="border:1px solid #000;">&nbsp;&nbsp;'+dijit.byId("service_"+rowIDArray[n]).attr('displayedValue')+'</td>'; 
		      temp+='<td align="left" style="border:1px solid #000;"><span style="font-family: Khmer OS Battambang;color:#000;font-size: 9px;">&nbsp;&nbsp;'+dijit.byId("term_"+rowIDArray[n]).attr('displayedValue')+'</td>';
		      temp+='<td style="border:1px solid #000;">$ '+dijit.byId("price_"+rowIDArray[n]).get('value')+'</td>';
		      temp+='<td style="border:1px solid #000;">'+dijit.byId("qty_"+rowIDArray[n]).get('value')+'</td>';
		      temp+='<td style="border:1px solid #000;">$ '+dijit.byId("discount_"+rowIDArray[n]).get('value')+'</td>';
		      temp+='<td style="border:1px solid #000;">$ '+dijit.byId("subtotal_"+rowIDArray[n]).get('value')+'</td>';

		      var b = new Date(dijit.byId("date_start_"+rowIDArray[n]).get('value'));
			  mm = b.getMonth()+1;
			  var dd = b.getDate();
			   if(dd<10){
			    dd = "0"+dd;
			   }
			   if(mm<10){
			    mm = "0"+mm;
			   }
			  var y = b.getFullYear();
			  var start_date = dd + '-' + mm + '-' + y ;
			  temp+='<td style="border:1px solid #000;"> '+start_date+'</td>';

		      var a = new Date(dijit.byId("validate_"+rowIDArray[n]).get('value'));
			  mm = a.getMonth()+1;
			  var dd = a.getDate();
			   if(dd<10){
			    dd = "0"+dd;
			   }
			   if(mm<10){
			    mm = "0"+mm;
			   }
			  var y = a.getFullYear();
			  var epx_date = dd + '-' + mm + '-' + y ;
		      temp+='<td style="border:1px solid #000;"> '+epx_date+'</td>';
		      
		      i++;
		      temp+='</tr>';
		     }
		      temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="7"></td><td style="border:1px solid #000; padding-left: 10px;"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;">ទឹកប្រាក់ត្រូវបង់ / Total Payment</strong></td><td style="border:1px solid #000; padding-left: 10px;">$ '+total+'</td></tr>';
		      temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="7"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 11px;color:red;">** ទឹកប្រាក់ដែលបង់ហើយ មិនអាចផ្ទេរ ឬ ដកវិញបានទេ</strong></td><td style="border:1px solid #000; padding-left: 10px;"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;">ទឹកប្រាក់ទទួលបាន / Recieve Amount</strong></td><td style="border:1px solid #000; padding-left: 10px;">$ '+recieve+'</td></tr>';
		      temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="7"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 13px;color:red;">** All fees are not transferable or refundable.</strong></td><td style="border:1px solid #000; padding-left: 10px;"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;">ប្រាក់នៅខ្វះ / Balance Due</strong></td><td style="border:1px solid #000; padding-left: 10px;">$ '+balance_due+'</td></tr>';
		      temp+='<tr style="font-size:10px;height: 23px;"​ align="left"> <td style=" border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: 1px solid #000;" colspan="7"></td><td style="border:1px solid #000; padding-left: 10px;"><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 8px;">ប្រាក់អាប់ / Return Amount</strong></td><td style="border:1px solid #000; padding-left: 10px;">$ '+toral_return+'</td></tr>';
		    temp+='</table>';
		    dojo.byId('t_amountmoneytype').innerHTML = temp;

		dijit.byId("popup_invoice").show();	
		
	}
	
}
</script>


<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" id="popup_invoice" >
		<div id="divPrint" style=" width: 26cm; height: 12cm ; padding: 0px; margin: 0px;">
			<table style="background:#fff; margin: 0 auto; width: 26cm;height: 12cm; padding: 1cm; margin: 0 auto;" align="center">
							<tr>
								<td width="25%" align="left">
								</td>
								<td align="center">
									<strong style=" font: bold 15px 'Khmer MEF2',Arial Black; color:#000;"><u>បង្កាន់ដៃបង់ប្រាក់របស់សិស្ស</u></strong><br >
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 15px;padding-right: 10px;">OFFICAIL RECEIPT</strong><br >
								</td>
								<td align="right" width="20%">
								</td>
							</tr>
							<tr>
								<td width="35%" style="line-height: 32px;">
									<table style="white-space: nowrap;"  >
										<tr>
											<td style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">អត្តលេខសិស្ស</strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 11px;">Student ID &nbsp;&nbsp;&nbsp;</strong>
											</td>
											<td >
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;vertical-align: middle;"> : &nbsp;<label id="lbl_stuid" ></label></strong>
											</td>
											
										</tr>
										<tr>
											<td style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">ឈ្មោះសិស្ស</strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">Student Name </strong>
											</td>
											<td >
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"> : &nbsp;<label id="lbl_khname"></label></strong> - <label id="lbl_enname"></label>
											</td>
										</tr>
										<tr style="line-height: 13px;">
											<td valign="top" ><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">ភេទ / Sex</strong></td>
											<td ><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"> : &nbsp;<label id="lbl_sex"></label></strong></td>
										</tr>
									</table>
								</td>
								<td width="30%">
									&nbsp;
								</td>
								<td width="35%" style="line-height: 32px;">
									<table style="white-space: nowrap;">
										<tr>
											<td width="20%" style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">វិក័យប័ត្រលេខ​</strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">Reciept N.o  </strong>
											</td>
											
											<td width="20%" >
												 <strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;">: &nbsp;</strong><b><label id="lbl_recieptno"> </label></b>
											</td>
										</tr>
										<tr>
											<td width="20%" style="line-height: 13px;">
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">ថ្ងៃបង់</strong><br />
												<strong style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;padding-left: 15px;">Date Paid  </strong>
											</td>
											<td width="80%"><span style="font-family: Khmer OS Battambang;color:#000;font-size: 12px;"><strong>: &nbsp;</strong><?php echo Zend_Date::now();?></span></td>
										</tr>
										<tr>
											<td colspan="2">&nbsp;</td>
										</tr>
									</table>
								</td>
								
							</tr>
							<tr>
								<td colspan="3">
                                    	 <div id="t_amountmoneytype"></div>
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td align="left">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';padding-left: 50px;">ហត្ថលេខា និង​ ឈ្មោះអ្នកទទួល  </strong><br />
								</td>
								<td>&nbsp;</td>
								<td align="right">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';padding-right: 80px;">ហត្ថលេខា និង​ ឈ្មោះអ្នកបង់</strong><br />
								</td>
							</tr>
							<tr>
								<td colspan="3"> <div style="padding-left: 100px;font-family: Khmer OS Battambang;color:#000;font-size: 13px;"><?php $session_user=new Zend_Session_Namespace('auth'); $last = $session_user->last_name;$first=$session_user->first_name;echo $last.' '.$first; ?></div></td>
							</tr>
							
						</table>
	</div>
	<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="printSubmit();doPrint();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
</div>
</div>	
	<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
<?php $keycode = $this->keycode;?>


<script>

function setID(type){
	if(type==1){
		dijit.byId('stu_name').attr('value',dijit.byId('studentid').get('value')); 
	}else{
		dijit.byId('studentid').attr('value',dijit.byId('stu_name').get('value')); 
	}
}
function clearControll(){
	dijit.byId('en_name').attr('value','');
	dijit.byId('studentid').attr('value','');
	dijit.byId('kh_name').attr('value','');
	dijit.byId('sex').attr('value','');
}
//save daata when sub button print 
function printSubmit(){
	$('#office_receipt').submit();
}
function calculatePrice() {
	var total = $('#tuitionfee').val();
	var ds = $('#discount').val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				return after_discount;

			}else{
				after_discount = total - ds;
				return after_discount;
			}
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
				return after_discount;
			}else{
				//batch
				after_discount = total;
				return after_discount;
				}
		}
	}
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}


</script>
<script type="text/javascript">
function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("popup_invoice").hide();
}

var template = '';

var service = '<?php echo $this->all_service; ?>';

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PAYMENT_TERM");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DISCOUNT");?> %</th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBTOTAL");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PAID_AMOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DATE_START");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("VALIDATE");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+');calculateTotal('+col+');calculatePaidAmount('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="23%" align="center">'+no+'</td>';
			template+='<td><input type="hidden" dojoType="dijit.form.TextBox" name="old_service_'+col+'" id="old_service_'+col+'"/><select style="width:200px;" onchange="getservicefee('+col+');calculatePaidAmount('+col+');getValidate('+col+');" dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			

			
			template+='<td><select onchange="getservicefee('+col+');getValidate('+col+');calculatePaidAmount('+col+');" dojoType="dijit.form.FilteringSelect" id="term_'+col+'" name="term_'+col+'" style="width:110px;">';
				<?php foreach($this->payment_term as $key => $value){?>
					template+='<option value="'+<?php echo $key?>+'"><?php echo $value;?></option>';
				<?php }?>
			template+='</select></td>';
			column = 0;
			template+='<td> <input type="text" required="true" onkeyup="calculateTotal('+col+');" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="subsub"></label></td>';
			template+='<td> <input type="text"  onkeyup="calculateTotal('+col+');getValidate('+col+');" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="qty"></label></td>';
			
			template+='<td> <input type="text" onkeyup="calculateDiscount('+col+');" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="subsub"></label></td>';
			template+='<td> <input type="text"  readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="qty"></label></td>';
			template+='<td> <input type="text" required="true" onkeyup="alerterror('+col+');calculatePaidAmount('+col+');"  name="paidamount_'+col+'" id="paidamount_'+col+'" dojoType="dijit.form.NumberTextBox" style="width:70px;" /><label id="paidamount"></label></td>';
			template+='<td> <input type="text"  name="date_start_'+col+'" onchange="getValidate('+col+');" id="date_start_'+col+'" dojoType="dijit.form.DateTextBox" style="width:100px;" value="<?php echo date('Y-m-d')?>" /><label id="validate"></label></td>';
			template+='<td> <input type="text" name="validate_'+col+'" id="validate_'+col+'" dojoType="dijit.form.DateTextBox" style="width:100px;" /><label id="validate"></label></td>';
			template+='<td> <input type="text" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" style="width:140px;" /><label id="subsub"></label></td>';

		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
		getValidate(col);
 }
function calculateTotal(index){
	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	//dijit.byId('total_'+index).attr('value',total);
	calculateDiscount(index);
}
function calculateDiscount(index){

	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	
	//total = dijit.byId('total_'+index).get('value');
	
	discount = dijit.byId('discount_'+index).get('value');
	discount = isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-(total*discount/100));
	dijit.byId('paidamount_'+index).attr('value',total-(total*discount/100));
	netTotal();
}

function alerterror(index){
	
	subtotal = dijit.byId('subtotal_'+index).get('value');
	paid = dijit.byId('paidamount_'+index).get('value');
	if(paid>subtotal){
		alert("Paid amount must be equal or smaller than subtotal");
		dijit.byId('paidamount_'+index).attr('value',subtotal);
	}
}

function calculatePaidAmount(index){
	//price = dijit.byId('price_'+index).get('value');
	var netPaidAmount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		//netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
		netPaidAmount += dijit.byId('paidamount_'+rowIDArray[n]).get('value');
	}
	dijit.byId('total_received').attr('value',netPaidAmount);
	calculatBalanceAndReturn();
}

function netTotal() {
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		//netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
		netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
	}
	dijit.byId('grand_total').attr('value',netTotal);
	//dijit.byId('total_received').attr('value',netTotal);
	//$('#grand_total').val(netTotal);
	//$('#total_received').val(netTotal);
	calculatePaidAmount();
	calculatBalanceAndReturn();
}
function calculatBalanceAndReturn(){
	totalreceived = dijit.byId('total_received').get('value');
	grand_total = dijit.byId('grand_total').get('value');

	if(totalreceived>grand_total){
		dijit.byId('total_return').attr('value',totalreceived-grand_total);
		dijit.byId('total_balance').attr('value',0);
	}
	else{
		dijit.byId('total_balance').attr('value',grand_total-totalreceived);
		dijit.byId('total_return').attr('value',0);
	}
}

var url_service = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-service')); ?>";
function getServiceName(){
	year = dijit.byId('study_year').get('value');
	//alert(year);
	dojo.xhrPost({
		url:url_service,
		content:{
			'year':year
			},
		handleAs:"json",
		load: function(data) {
			alert(data);
			//alert(data.sex);
			dijit.byId("kh_name").attr("value",data.stu_khname);
			dijit.byId("en_name").attr("value",data.stu_enname);
			dijit.byId("sex").attr("value",data.sex);
			//alert(data);
			//dijit.byId("price_"+key).attr("value",data.price_fee);
		},
		error: function(err) {
			alert(err);
		}
	});
}


var url_student_info = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-student')); ?>";
function getStudentInfo(){
			studentid = dijit.byId('studentid').get('value');
			//alert(studentid);
			dojo.xhrPost({
				url:url_student_info,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//alert(data.sex);
					dijit.byId("kh_name").attr("value",data.stu_khname);
					dijit.byId("en_name").attr("value",data.stu_enname);
					dijit.byId("sex").attr("value",data.sex);
					//alert(data);
					//dijit.byId("price_"+key).attr("value",data.price_fee);
				},
				error: function(err) {
					//alert(err);
				}
			});
}
var url_service_fee = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-price')); ?>";
function getservicefee(key){
			studentid = dijit.byId('studentid').get('value');
			services = dijit.byId('service_'+key).get('value');
			term = dijit.byId('term_'+key).get('value');
			year = dijit.byId('study_year').get('value');
			//alert(year);
			dojo.xhrPost({
				url:url_service_fee,
				content:{
					'term':term,
					'service':services,
					'studentid':studentid,
					'year':year,
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId("remark"+key).attr("value",'');
					dijit.byId("old_service_"+key).attr("value",'');
					//dijit.byId("validate_"+key).attr("value",<?php Zend_Date::now()?>);
					
					if(data.sms!=''){
						dijit.byId("remark"+key).attr("value",data.sms);
						dijit.byId("old_service_"+key).attr("value",data.id);
						dijit.byId("validate_"+key).attr("value",data.validate);
					}

					dijit.byId("price_"+key).attr("value",data.price_fee);
					//dijit.byId("total_"+key).attr("value",data.price_fee);
					calculateTotal(key);

				},
				error: function(err) {
					alert(err);
				}
			});
}

function getValidate(key){
	 //alert(1);
	 amount= dijit.byId('qty_'+key).get('value');
	 term = dijit.byId('term_'+key).get('value');
	 start_date = dijit.byId('date_start_'+key).get('value');
	 //alert(amount+'-'+term+'-'+start_date);
	 //var dNow = new Date();
	 //var localdate= (dNow.getMonth()+1) + '/' + dNow.getDate() + '/' + dNow.getFullYear();
	 
	 //alert(start_date);
	 
	 if(term==1){
		 var a = new Date(start_date);
		  mm = a.getMonth()+amount+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('validate_'+key).attr('value',epx_date);
	 }
	 if(term==2){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(amount*3)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('validate_'+key).attr('value',epx_date);
	 }
	 if(term==3){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(amount*6)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('validate_'+key).attr('value',epx_date);
	 }
	 if(term==4){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(amount*12)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('validate_'+key).attr('value',epx_date);
	 }

}

function getValue(){
	seperater='';
	i=0;
	hour='';
	$("#time").val('');
	for(i=1;i<=9;i++){
		if(i>1){
			seperater='-';
		}
		if(dojo.byId('time'+i).checked){
			hour+=seperater+dijit.byId('time'+i).get('value');
			if($("#time").val()!="") {
				var time = $("#time").val();
				$("#time").val(time+','+i);
			} else {$("#time").val(i);}
		}
	}
	dijit.byId('not').attr('value',hour);
}

function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>


