<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_callteral;
echo $this->headTitle($tr->translate("EDIT_STUDY_GROUP"));
$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();

?>

<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
</script>


<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudy','action'=>'edit')); ?>" 
dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
                major = dijit.byId('major').get('value');
                room = dijit.byId('room').get('value');

				if (major=='' || major==-1){
					alert('Please Select Faculty !');
                    dijit.byId('major').focus();
			        return false;
                }
               if (room=='' || room==-1){
					alert('Please Select room !');
                    dijit.byId('room').focus();
			        return false;
                }
				return true;
			}else {
				return false;
			}
</script>
<table width="100%">
	<tr>
		<td>
				<fieldset style="margin-top:-13px;">
					<legend align="center" ><strong style="font-size: 18px;"><?php echo $tr->translate("EDIT_STUDY_GROUP");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;white-space: nowrap;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("GROUP_CODE")?><input type="hidden" name="id" value="<?php echo $this->rs['id'];?>" /></td>
							<td><input class="fullside" dojoType="dijit.form.ValidationTextBox" required="true" id="group_code" name="group_code" value="<?php echo $this->rs['group_code'];?>" type="text"></td>
						    
						    <td ><?php echo $tr->translate("YEARS")?></td>
							<td>
								<select class="fullside" name="academic_year" id="academic_year" placeholder="Select Year" type="text" dojoType="dijit.form.FilteringSelect">
									<option value="-1">Select AcademicYear</option>
									<?php foreach($this->year as $year){?>
										<option value="<?php echo $year['id'];?>"<?php if($year['id']==$this->rs['academic_year']) echo 'selected="selected"';?>><?php echo $year['years'];?></option>
									<?php }?>
							    </select>
							</td>
							
							<td ><?php echo $tr->translate("DEGREE")?></td>
							<td>
								<select class="fullside"  name="degree" id="degree" dojoType="dijit.form.FilteringSelect" onchange="getallGrade();">
									<option value="-1">Select Degree</option>
									<?php if(!empty($this->degree))foreach ($this->degree as $row){?>
										<option value="<?php echo $row['dept_id']?>"<?php if($row['dept_id']==$this->rs['degree']) echo 'selected="selected"';?> ><?php echo $row['en_name']?></option>
									<?php }?>
								</select>
							</td>
							
							
						</tr>
						<tr>
							<td ><?php echo $tr->translate("GRADE")?></td>
							<td  >
								<input id="grade" name="grade" value="<?php echo $this->rs['grade']; ?>" />
							</td>
							
							<td><?php echo $tr->translate("SESSION")?></td>
							<td>
								<select class="fullside" name="session" id="session" dojoType="dijit.form.FilteringSelect">
								<?php $row= new Application_Model_DbTable_DbGlobal();
								      $rows=$row->getSession();
									foreach($rows as $key =>$rs){?>
										<option value='<?php echo $rs['key_code']?>' ><?php echo $rs['view_name'];?></option>
								<?php 	}?>
								</select>
							</td>
							
							<td><?php echo $tr->translate("SEMESTER")?></td>
							<td><input class="fullside" dojoType="dijit.form.ValidationTextBox" name="semester" value="<?php echo $this->rs['semester'];?>" type="text"></td>
							 
						</tr>
						
						<tr>
							<td ><?php echo $tr->translate("START_DATE")?></td>
							<td><input class="fullside" dojoType="dijit.form.DateTextBox" name="start_date" id="start_date" onchange="setEndDate();" value="<?php echo $this->rs['start_date'];?>" type="text"></td>
							<td><?php echo $tr->translate("AMOUNT_MONTH")?></td>
							<td><input class="fullside" dojoType="dijit.form.NumberTextBox"   name="amountmonth" id="amountmonth" value="<?php echo $this->rs['amount_month'];?>" onkeyup="setEndDate();" type="text"></td>
							<td ><?php echo $tr->translate("END_DATE")?></td>
							<td><input class="fullside" dojoType="dijit.form.DateTextBox" id="end_date" name="end_date" type="text" value="<?php echo $this->rs['expired_date'];?>" ></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ROOM_NAME")?></td>
							<td>
								<input id="room" />
							</td>
							<td ><?php echo $tr->translate("STATUS")?></td>
							<td><select class="fullside" name="status" id="status" dojoType="dijit.form.FilteringSelect">
								    <option value="1" <?php if($this->rs['status']==1) echo 'selected="selected"';?>>ប្រើប្រាស់</option>
								    <option value="0" <?php if($this->rs['status']==0) echo 'selected="selected"';?>>មិនប្រើប្រាស់</option>
								</select>
							</td>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><input class="fullside" dojoType="dijit.form.TextBox"   name="note" value="<?php echo $this->rs['note'];?>" type="text"></td>
						</tr>
						
						<tr>
							<td ><?php echo $tr->translate("TIME")?></td>
							<td>
								<select class="fullside" name="time" id="time" dojoType="dijit.form.FilteringSelect">
									<option value="-1" <?php if($this->rs['time']==-1) echo 'selected="selected"';?>>Select Time</option>
								    <option value="1" <?php if($this->rs['time']==1) echo 'selected="selected"';?>>Part Time</option>
								    <option value="2" <?php if($this->rs['time']==2) echo 'selected="selected"';?>>Full TIme</option>
								</select>
							</td>
						</tr>

						<tr>
							<td colspan="6" align="center">
								<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
								<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'global','controller'=>"group",'action'=>'index'),null,true); ?>';" />
								<input type="submit" value="save" name="save" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>
</table>
</form>
<?php 
$techer= $this->frm_techer;
?>
<script type="text/javascript">

dojo.require("dojo.date.locale");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require('dojox.form.BusyButton');
dojo.require("dojo.html");

var room_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->room));?> );
dojo.ready(function(){
			
			new dijit.form.FilteringSelect({
			    autoComplete: true,                        
			    id: "grade",
			    name: "grade",           
			    class: 'fullside',  
			    placeHolder:"Selected Grade",          
			    onChange: function() {  
			    	make_id = dijit.byId('grade').get('value');
			    	//paymentTerm();
			    }
			}, "grade");
			getallGrade();

			new dijit.form.FilteringSelect({
				store: room_store,
			    autoComplete: true,                        
			    id: "room",
			    name: "room",   
			    class: "fullside",
			    value:"<?php echo $this->rs['room_id'];?>",        
			    placeHolder:"Select Room",          
			    onChange: function() {  
			    	room = dijit.byId('room').get('value');
			    	if(room==-1){
						dijit.byId("popup_room").show();
				    }
			    }
			}, "room");
			//dijit.byId('room').attr('value','<?php //echo $this->rs['room_id'];?>');
		
	});
function setEndDate(){
	amount_date = dijit.byId('amountmonth').get('value');
	release_date = dijit.byId("start_date").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		mm = a.getMonth()+amount_date+1;
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('end_date').attr('value',epx_date);	
    }
}

var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);   
			    dijit.byId('grade').attr('value',<?php echo $this->rs['grade'];?>);   
			    

			},
			error: function(err) {
				alert(err);
			}
		});
}


var url_room = '<?php echo $this->url(array('module'=>'foundation','controller'=>'groupstudy','action'=>'add-room')); ?>';
function addRoom(){
	
		dojo.xhrPost({
			url:url_room,
			form: dojo.byId("form_add_room"),
			handleAs:"json",
			load: function(data) {
				var myNewItem = {					
						id: data,
						name: dijit.byId('room_name').get('value')
				};			
				addDataToSelectbox(dijit.byId('room'), room_store, myNewItem, data);
				dijit.byId('form_add_room').reset();
				hideDialog();
			},
			error: function(err) {
				alert(err);
			}
		});
	}



var subject = '<?php echo $this->subject;?>';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';


function hideDialog(){
	dijit.byId("popup_room").hide();
}


</script>
	

	<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:100%;" id="popup_room" >
		<form style="background-color: buttonface; width:15cm;" id='form_add_room' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate("ADD_NEW_ROOM")?></legend><br />
						<table style="margin: 0 auto; width: 95%;" cellspacing="5">
							<tr>
								<td style="width:100px"><?php echo $tr->translate("ROOM_NAME")?></td>
								<td><input class="fullside" tabindex="1" value="" dojoType="dijit.form.ValidationTextBox" name="room_name" id="room_name" type="text" required="required" /></td>
							</tr>
							
							<tr>
								<td style="width:100px"><?php echo $tr->translate("STATUS")?></td>
								<td>
									<select class="fullside"  tabindex="3" name="status_room" id="status_room" dojoType="dijit.form.FilteringSelect" >
										    <option value="1"><?php echo $tr->translate("Active")?></option>
										    <option value="0"><?php echo $tr->translate("Deactive")?></option>
									</select>
								</td>
							</tr>
							<tr>
								<td colspan="2" align="center">
									<input iconClass="dijitIconUndo" type="button" value="close" label="Close" dojoType="dijit.form.Button" onclick="hideDialog();"/>
									<input type="button" value="save" name="save" label="Save" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addRoom();"/>
								</td>
							</tr>
						</table>
					</fieldset>
					</td>
				</tr>
		</table>

		</form>
	</div>
</div>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	