<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("DISCIPLINE"));
	$frm =  $this->form_search;
?>	
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-gavel " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('DISCIPLINE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form  action="<?php echo $this->url(array('module'=>'foundation','controller'=>'discipline','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("branch_id");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<input id="group_name" />
					 </div>
					 
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("study_year");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("grade");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("session");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("room");?>
					 </div>
				</div>
				<div class="form-group">
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("start_date");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">	
					 	<?php echo $frm->getElement("end_date");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					 </div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php  echo $this->list;?>
		</div>
	</div>
</div>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
dojo.require("dojo.data.ObjectStore");
////dojo.require('dojox.form.BusyButton');
dojo.ready(function(){
		var group_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
		new dijit.form.FilteringSelect({
		    store:group_store,
		    autoComplete: true,                        
		    required:false,
		    id: "group_name",
		    name: "group_name",
		    class:'fullside',  
		    value:'<?php echo $this->g_name['group_name'];?>',         
		    required:'true',
		    placeHolder:"<?php echo $tr->translate('PLEASE_SELECT_GROUP');?>",          
		    onChange: function() {  
		    }
		}, "group_name");

		 var branch_id = dijit.byId('branch_id');
		 	branch_id.on('change', function(evt) {
		 		getAllGroupByBranch();
		    });
		 	getAllGroupByBranch();
});
url_getgroup = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group_name').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group_name').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
		    group_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('group_name').set('store',group_store);   
		    <?php if (!empty($this->search['group_name'])){?>
		    dijit.byId('group_name').set('value','<?php echo $this->search['group_name'];?>');   
		    <?php }?>
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>

