<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_RESCHEDULE_GROUP"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-calendar " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_RESCHEDULE_GROUP');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id=dijit.byId("branch_id").get("value");
                if(branch_id==-1){
					alert("Please Selected Branch!!!");
					dijit.byId("branch_id").focus();
                    return false;
				}
				group_code=dijit.byId("group_code").get("value");
                if(group_code==-1){
					alert("Please Selected group code!!!");
					dijit.byId("group_code").focus();
                    return false;
				}
                year=dijit.byId("academic_year").get("value");
                if(year==-1){
					alert("Please Selected Year!!!");
					dijit.byId("academic_year").focus();
                    return false;
				}
    			var rowId = $('#identity1').val();
				if(rowId==''){
					alert("Please add data !!! ");
					return false;
				}
				dijit.byId('save_new').set('disabled',true);
				dijit.byId('save_close').set('disabled',true);
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select name="branch_id" class="fullside" id="branch_id" placeholder="Select Branch" type="text" dojoType="dijit.form.FilteringSelect"  queryExpr="*${0}*" autoComplete="false" placeholder="" >
								<option value="-1"><?php echo $tr->translate("SELECT_BRANCH")?></option>
								<?php if(!empty($this->branch_name)){foreach($this->branch_name as $name){?>
									<option value="<?php echo $name['id'];?>"><?php echo $name['name'];?></option>
								<?php }}?>
							</select>
		                </div>
		            </div>
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ACADEMIC_YEAR");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<input id="academic_year" />
		                </div>
		             </div>
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP_CODE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<input id="group_code" />
		                </div>
		             </div>
		        </div>
		        <div class="col-md-8 col-sm-8 col-xs-12">
					<div class="form-group">
						<label class="control-label text-center col-md-1 col-sm-5 col-xs-12">
							<?php echo $tr->translate("DAY");?>
						</label>
		                <div class="col-md-2 col-sm-7 col-xs-12">
							<select dojoType="dijit.form.FilteringSelect" class="fullside" name="day" id="day" >
								<?php echo $this->optday;?>
							</select>
		                </div>
						<label class="control-label text-center col-md-2 col-sm-5 col-xs-12">
							<?php echo $tr->translate("FROM_HOUR");?>
						</label>
		                <div class="col-md-2 col-sm-7 col-xs-12">
							<select dojoType="dijit.form.FilteringSelect" class="fullside" name="from_hour" id="from_hour" >
								<?php echo $this->opttime;?>
							</select>
		                </div>
						<label class="control-label text-center col-md-2 col-sm-5 col-xs-12">
							<?php echo $tr->translate("TO_HOUR");?>
						</label>
		                <div class="col-md-2 col-sm-7 col-xs-12">
							<select dojoType="dijit.form.FilteringSelect" class="fullside" name="to_hour" id="to_hour" >
								<?php echo $this->opttime;?>
							</select>
		                </div>
						<div class="col-md-1 col-sm-7 col-xs-12">
							<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="refreshFunction();"/>
		                </div>
		        	</div>
					<div class="form-group">
						<label class="control-label text-center col-md-1 col-sm-5 col-xs-12">
							<?php echo $tr->translate("SUBJECT_STUDY");?>
						</label>
		                <div class="col-md-2 col-sm-7 col-xs-12">
							<input id="subject_id" />
		                </div>
						<label class="control-label text-center col-md-2 col-sm-5 col-xs-12">
							<?php echo $tr->translate("TEACHER");?>
						</label>
		                <div class="col-md-2 col-sm-7 col-xs-12">
							<input id="teacher" />
		                </div>
						<label class="control-label text-center col-md-2 col-sm-5 col-xs-12">
							<?php echo $tr->translate("NOTE");?>
						</label>
		                <div class="col-md-2 col-sm-7 col-xs-12">
							<input name="note" id="note" dojoType="dijit.form.TextBox" class="fullside" placeHolder="<?php echo $tr->translate("NOTE");?>"/>
		                </div>
						<div class="col-md-1 col-sm-7 col-xs-12">
							<input type="button" label="<?php echo $tr->translate('ADD');?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconEditProperty" onclick="addRow();" />
		                </div>
		        	</div>
		        	<div class="form-group">
		        		<table style="border-collapse: collapse; border:1px solid #ccc;">
							<thead  id="head-title">
								<tr class="head-td">
									<th width="5%"><?php echo $tr->translate("DEL");?></th>
									<th width="5%"><?php echo $tr->translate("N_O");?></th>
									<th width="15%"><?php echo $tr->translate("DAY");?></th>
									<th width="15%"><?php echo $tr->translate("FROM_HOUR");?></th>
									<th width="15%"><?php echo $tr->translate("TO_HOUR");?></th>
									<th width="15%"><?php echo $tr->translate("SUBJECT_STUDY");?></th>
									<th width="15%"><?php echo $tr->translate("TEACHER");?></th>
									<th width="15%"><?php echo $tr->translate("NOTE");?></th>
								</tr>
								<tbody id="table_row"></tbody>
								<input type="hidden" name="identity1" id="identity1"  />
							</thead>
						</table>
						
		        	</div>
		        </div>
		    </div>
		    <div class="clearfix"></div>
	       	<div class="card-box mt-20 ">
	      	 	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
              		<input type="button" onclick="submitDataClose();"  value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
            	 </div>
            </div>
		</form>
	</div>
</div>
<?php 
	$techer= $this->frm_techer;
?>
<script type="text/javascript">
	//dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	//dojo.require('dijit.form.TextBox');
	//dojo.require('dijit.form.CheckBox');
	dojo.require('dijit.form.DateTextBox');
	
	var subject_store  = getDataStorefromJSON('id','name');
	var teacher_store  = getDataStorefromJSON('id','name');
	var group_store  = getDataStorefromJSON('id','name',);
	var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store:group_store,
		queryExpr: "*${0}*",
		autoComplete: false,                      
		required: false,               
		id: "group_code",
		name: "group_code",   
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_GROUP");?>",
		onChange: function() {
			group_code = dijit.byId("group_code").get("value");
			if(group_code==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/foundation/group/add";?>','_blank');
			}
		}
	}, "group_code");
	
	new dijit.form.FilteringSelect({
		store:academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                      
		required: false,               
		id: "academic_year",
		name: "academic_year",   
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",
		onChange: function() {  
			getSubject();
		}
	}, "academic_year");
	
	new dijit.form.FilteringSelect({
		store:subject_store,
		queryExpr: "*${0}*",
		autoComplete: false,                      
		required: false,               
		id: "subject_id",
		name: "subject_id",   
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SUBJECT_STUDY");?>",
		onChange: function() {  
			subject = dijit.byId("subject_id").get("value");
			if(subject==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/subject/add";?>','_blank');
			}
		}
	}, "subject_id");
	
	new dijit.form.FilteringSelect({
		store:teacher_store,
		queryExpr: "*${0}*",
		autoComplete: false,                      
		required: false,               
		id: "teacher",
		name: "teacher",   
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("TEACHER");?>",
		onChange: function() {  
			teacher = dijit.byId("teacher").get("value");
			if(teacher==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/foundation/lecturer/add";?>','_blank');
			}
		}
	}, "teacher");
	
	var branch_id = dijit.byId('branch_id');
	branch_id.on('change', function(evt) {
		dojo.query("#table_row").append('');
		$('#identity1').val('');
		
		getAllGroupByBranch();
		getAllAcademicByBranch();
		getTeacherByBranch();
	});
	//addRow();
});

function refreshFunction(){
	getAllGroupByBranch();
	getTeacherByBranch();
	getSubject();
}

url_getgroup = '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getgroupbybranch'));?>';
function getAllGroupByBranch(){
	dijit.byId('group_code').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('group_code').set('store',group_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			group_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('group_code').set('store',group_store);   
		},
		error: function(err) {
			alert(err);
		}
	});
}

url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
function getAllAcademicByBranch(){
	dijit.byId('academic_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('academic_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('academic_year').set('store',academic_store);   
		},
		error: function(err) {
		}
	});
}

var url_gettecher = '<?php echo $this->url(array("module"=>"foundation","controller"=>"group","action"=>"getteacher"));?>';										
function getTeacherByBranch(){
	dijit.byId('teacher').reset();
	academic_year = dijit.byId('academic_year').get('value');
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var teacher_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('teacher').set('store',teacher_store);  
		return false;
	}
	dojo.xhrPost({
		url:url_gettecher,
		content:{
			'academic_year':academic_year,
			'branch_id':branch_id
		},
		handleAs:"json",
		load: function(data) {
			teacher_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('teacher').set('store',teacher_store);  
		},
		error: function(err){

		}
	});
}

var subject = '';
var url_getsubject = '<?php echo $this->url(array("module"=>"global","controller"=>"group","action"=>"getsubject"));?>';										
function getSubject(){
	dijit.byId('subject_id').reset();
	academic_year = dijit.byId('academic_year').get('value');
	if(academic_year=='' || academic_year==-1){
		var subject_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		return false;
	}
	dojo.xhrPost({
		url:url_getsubject,
		content:{
			'academic_year':academic_year,
		},
		handleAs:"json",
		load: function(data) {
			if(data){
				subject_store = getDataStorefromJSON('id','name', data);
				dijit.byId('subject_id').set('store',subject_store);  
			}
		},
		error: function(err) {
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}

var col = 0;
var no = 0;
tmp = '';
temp='';
function addRow() {
	
	day = dijit.byId("day").get("value");
	from_hour = dijit.byId("from_hour").get("value");
	to_hour = dijit.byId("to_hour").get("value");
	subject = dijit.byId("subject_id").get("value");
	teacher = dijit.byId("teacher").get("value");
	note = dijit.byId("note").get("value");
	dayLabel = dijit.byId("day").attr("displayedValue");
	from_hourLabel = dijit.byId("from_hour").attr("displayedValue");
	to_hourLabel = dijit.byId("to_hour").attr("displayedValue");
	subjectLabel = dijit.byId("subject_id").attr("displayedValue");
	teacherLabel = dijit.byId("teacher").attr("displayedValue");
	noteLabel = dijit.byId("note").attr("displayedValue");
	if(from_hour>=to_hour){
		alert("Start hour can't bigger than End hour!!!");
		dijit.byId("to_hour").focus();
		return false;
	}	
	if(subject<1){
		alert("select subject !!!");
		dijit.byId("subject_id").focus();
		return false;
	}
	if(teacher<1){
		alert("select teacher !!!");
		dijit.byId("teacher").focus();
		return false;
	}
	
	col++;no++;
	template='';
		template+='<td align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td align="center">'+no+'</td>';
		template+='<td ><input dojoType="dijit.form.TextBox"  class="fullside" id="day_id_'+col+'" name="day_id_'+col+'" value="'+day+'" type="hidden" />'+dayLabel+'</td>';
		template+='<td ><input class="fullside"  required="false" dojoType="dijit.form.TextBox" id="from_hour_'+col+'" value="'+from_hour+'" name="from_hour_'+col+'" type="hidden" />'+from_hourLabel+'</td>';
		template+='<td ><input class="fullside"  required="false" dojoType="dijit.form.TextBox" id="to_hour_'+col+'" value="'+to_hour+'" name="to_hour_'+col+'" type="hidden" />'+to_hourLabel+'</td>';
		template+='<td ><input dojoType="dijit.form.TextBox"  class="fullside" id="group_subject_study_'+col+'" name="group_subject_study_'+col+'" value="'+subject+'" type="hidden" />'+subjectLabel+'</td>';
		template+='<td ><input dojoType="dijit.form.TextBox" onchange="popupTeacher('+col+');" class="fullside" id="teacher_'+col+'" name="teacher_'+col+'" value="'+teacher+'" type="hidden" />'+teacherLabel+'</td>';
		template+='<td ><input dojoType="dijit.form.TextBox" class="fullside" name="group_note_'+col+'" id="group_note_'+col+'" value="'+note+'" type="hidden" />'+noteLabel+'</td>';		
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);
	if($("#identity1").val()!="") {
		var identity = $("#identity1").val();
		$("#identity1").val(identity+','+col);
	} else {$("#identity1").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	dijit.byId("subject_id").set("value",'');
	dijit.byId("teacher").set("value",'');
	dijit.byId("note").set("value",'');
}
function deleteRecord(index) {
	var identity = $('#identity1').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity1').val(strings);
	dojo.query("#row"+index).remove();
}

function submitDataClose(){
	branch_id=dijit.byId("branch_id").get("value");
    if(branch_id==-1){
		alert("Please Selected Branch!!!");
		dijit.byId("branch_id").focus();
        return false;
	}
	group_code=dijit.byId("group_code").get("value");
    if(group_code==-1){
		alert("Please Selected group code!!!");
		dijit.byId("group_code").focus();
        return false;
	}
    year=dijit.byId("academic_year").get("value");
    if(year==-1){
		alert("Please Selected Year!!!");
		dijit.byId("academic_year").focus();
        return false;
	}
	
	var rowId = $('#identity1').val();
	if(rowId==''){ 
		alert("Please add data !!!");
		return false;
	}
	if(dijit.byId('frm_add_tran').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'issue','controller'=>'reschedulegroup','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_add_tran"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/issue/reschedulegroup";
			},
			error: function(e) {
			}
		});
	}
}

</script>