<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("COMMUNE_LIST"));
$frm = $this->frm_district;
?>

<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="col-sm-12 border-botom m-0">
	    	<div class="col-sm-8 pd-0">
    			<h4 class="m-b-0"><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('COMMUNE_LIST');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'global','controller'=>'commune','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					 <div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					 </div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
				 		<?php echo $frm->getElement("province_name");?>
				 	</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<input id="district_name" >
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('search_status');?>
					</div>
					 <div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					 </div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){		 
		new dijit.form.FilteringSelect({
		store: district_store,
		queryExpr: "*${0}*",
		autoComplete: false,        
		required: false,		           
		name: "district_name",
		id: "district_name",
		searchAttr: "name",
		class: 'fullside',
		value:"",
		placeHolder:"<?php echo $tr->translate("DISTRICT");?>",
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះសាខា​កូន!",	
			onChange: function() {
					filterCommune();
		    }
		}, "district_name");
				filterDistrict();
});
url_getdistrict = '<?php echo $this->url(array('module'=>'global','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province_name').get('value');
	if(pro_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getdistrict,	
		content:{ 
			'pro_id': pro_id
		},
		handleAs:"json",
		load: function(data) {	
			district_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('district_name').set('store', district_store);
		    dijit.byId('district_name').attr('value','<?php echo $this->result['district_name'];?>');
		},
		error: function(err) {
			alert(err);
		}
	});	
}
</script>