<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('RPT_STUDENT_GROUP'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<div style="width: 28cm;margin: 0 auto;">
<table>
	<tr>
		<td>
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'rpt-student-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search by student name....." value="" type="text">
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</form>
		</td>
	</tr>
</table>
</div>
<div style="border: 1px dotted #000;background: #fff;width: 28cm;margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%;">
					<tr>
						<td colspan="3" align="center">
							<strong style="font-weight:bold;color:#000; font-size: 16px;font-family:Arial,'Khmer MEF2';"><?php echo $tr->translate("NATIONALITY_OFKINGDOM");?></strong><br />
							<strong style="font-weight:bold;color:#000; font-size: 16px;font-family:Arial,'Khmer MEF2';"><?php echo $tr->translate("NATION_RELIGION_KING");?></strong>
						</td>
					</tr>
					<tr>
						<td width="10%" >
							<img style="max-height:100px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
						</td>
						<td align="center" >
							<strong style="font-weight:bold;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("STUDENT_LIST_REPORT");?></strong><br />
							<strong style="font-weight:bold;color:#000; font-size: 12px;font-family:'Khmer MEF2';white-space: nowrap;"><?php echo $tr->translate("ACADEMIC_YEAR");?> : <?php echo $this->rr['academic'];?><?php echo ", ".$tr->translate("DEGREE");?> : <?php echo $this->rr['degree'];?> <?php echo ','.$tr->translate("GRADE");?> : <?php echo $this->rr['grade'];?> </strong><br />
							<strong style="font-weight:bold;color:#000; font-size: 12px;font-family:'Khmer MEF2';"><?php echo $tr->translate("SESSION");?> : <?php echo $this->rr['session'];?> <?php echo ','.$tr->translate("CLASSES");?> : <?php echo $this->rr['room_name'];?><?php echo ", ".$tr->translate("STUDY_GROUP");?> : <?php echo $this->rr['group_code'];?> </strong><br />
						</td>
						<td width="20%"></td>
					</tr>
					<tr>
						<td colspan="3" id="exportExcel">
							<table cellpadding="5"​ style="font-size:12px; margin:0 auto;width:100%; border-collapse: collapse;border:1px solid #000; white-space: nowrap;"  border="1" >
								<style> td{padding:0 3px; }
								.cheader{height: 30px;font-weight: bold; background: #ccc; white-space: nowrap;}
								table{ page-break-inside:auto;font-family:Arial,'Khmer OS Battambang'; }
								tr{ page-break-inside:avoid; page-break-after:auto }
								#header {
								  display: table-header-group;
								  page-break-inside:avoid; page-break-after:auto;
								}
								</style>
								<thead>
								<tr class="cheader" align="center" >
									<td><?php echo $tr->translate("NUM");?></td>
									<td><?php echo $tr->translate("STUDENT_ID");?></td>
									<td><?php echo $tr->translate("STUDENT_NAMEKHMER");?></td>
									<td><?php echo $tr->translate("NAME_ENGLISH");?></td>
									<td><?php echo $tr->translate("SEX");?></td>
									<td><?php echo $tr->translate("NATIONALITY");?></td>
									<td><?php echo $tr->translate("DATE_OF_BIRTH");?></td>	
									<td><?php echo $tr->translate("POB");?></td>
									<td><?php echo $tr->translate("CONTACT_NO");?></td>	
									<td><?php echo $tr->translate("PRINT");?></td>					
								</tr>
								</thead>
								<?php  $i=0; foreach ($this->rs as $row){ $i++;?>
								<tr style="font-size:12px;height: 23px;"​ align="center">
									<td><?php echo $i;?></td>
									<td><?php echo $row['stu_code'];?></td>
									<td align="left"><?php echo $row['kh_name'];?></td>
									<td align="left"><?php echo $row['en_name'];?></td>
									<td><?php echo $row['sex'];?></td>
									<td><?php echo $row['nation'];?></td>
									<td><?php echo date("d-m-Y",strtotime($row['dob']));?></td>
									<td><?php echo $row['pob'];?></td>
									<td><?php echo $row['tel'];?></td>
									<td><a target="_blank" href="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'certify','id'=>$row['gd_id'])); ?>"><?php echo $tr->translate("PRINT_CERTIFY");?></a></td>
								</tr>
								<?php }?>	
							</table>	
						</td>
					</tr>
			</table>
	</div>
</div>