<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Add Student Test Payment')); 
?>	
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	dojo.require('dijit.form.TextBox');
	var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_dept));?> );
	dojo.ready(function(){
		getReceiptNo('');
		getDefaultTutionfee();
	});	
	
	var url_getreceipt_no = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-receipt-no')); ?>';
	function getReceiptNo(stu_id){
		dojo.xhrPost({
			url:url_getreceipt_no,
			content:{
				//'dept_id':dept_id   // student id ??????? degree ???  prefix ?? ? ????????????????
				'dept_id':1			  // ?????????? degree ?????????????????????????
				},
			handleAs:"json",
			load: function(data) {
				  dijit.byId('receipt_no').attr('value',data); 
				  if(stu_id!=''){
					  printSave(stu_id,data);
				  }
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	
	
</script>

<script>
		require(["dijit/form/DateTextBox","dijit/form/Textarea"]);
 </script>

<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttestpayment','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    	stu_test = dijit.byId('stu_test').get('value');
    	if(stu_test==0){
         	dijit.byId("stu_test").focus();
         	return false;
    	}
		dijit.byId('save_new').set('disabled',true);	
		dijit.byId('save_close').set('disabled',true);
    	return true;
   }else {
    	return false;
   }
</script>
	<fieldset style="margin-top: -10px;"> 
		<legend align="center"><strong><?php echo $tr->translate("STUDENT_INFO");?></strong></legend>
			<table  cellspacing="1" style="margin: 0 auto; width: 100%;">
				<tr>
					<td width="45%;" valign="top">
						<table style="margin: 0 auto; width: 100%;" cellspacing="2" >
							<tr>
								<td><?php echo $tr->translate("STUDENT_NAME");?></td>
								<td>
									<select type="text" name="stu_test" id="stu_test" class="fullside" dojoType="dijit.form.FilteringSelect" onchange="getStudentTestInfo();"  >
										<option value="0">--- Select Student Tested ---</option>
										<?php if(!empty($this->all_student_test)){foreach ($this->all_student_test as $all_student_test){?>
										<option value="<?php echo $all_student_test['id']?>"><?php echo $all_student_test['name']?></option>
										<?php }}?>
									</select>
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("NAME_KH");?></td>
								<td><input type="text" name="kh_name" readonly id="kh_name" class="fullside" dojoType="dijit.form.TextBox"/></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("NAME_EN");?></td>
								<td><input type="text" name="en_name" id="en_name" readonly class="fullside" required="1" dojoType="dijit.form.ValidationTextBox"/></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("SEX");?></td>
								<td>
									<select type="text" name="sex" id="sex" readonly class="fullside" dojoType="dijit.form.FilteringSelect" >
										<option value="1">Male</option>
										<option value="2">Female</option>
									</select>
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("DOB");?></td>
								<td>
									<input name="dob" id="dob" constraints="{datePattern:'dd/MM/yyyy'}" readonly dojoType="dijit.form.DateTextBox" value="now" class="fullside" type="text" />
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("PARENT_PHONE");?></td>
								<td><input type="text" name="parent_phone" id="parent_phone" readonly class="fullside" dojoType="dijit.form.TextBox"/></td>
							</tr>
							<tr>
								 <td><?php echo $tr->translate("TEST_DATE")?></td>
								 <td><input type="text" name="test_date" required="true" readonly id="test_date" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" value="now" dojoType="dijit.form.DateTextBox"   /></td>
							</tr>
						</table>
					</td>
					
					<td width="10%">
						&nbsp;
					</td>
					
					<td width="45%" valign="top">
						<table style="margin: 0 auto; width: 100%;" cellspacing="2" >
							<tr>
								<td><?php echo $tr->translate("RECEIPT_NO");?></td>
								<td><input type="text" style="color: red;" required="1" dojoType="dijit.form.ValidationTextBox" name="receipt_no" id="receipt_no" class="fullside" /></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("SERIAL")?></td>
								<td><input type="text" name="serial" id="serial" readonly class="fullside" dojoType="dijit.form.TextBox"   /></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("DEGREE")?></td>
								<td>
									<select onchange="getDefaultTutionfee();" name="degree" id="degree" class="fullside" dojoType="dijit.form.FilteringSelect"  >
										<?php if(!empty($this->degree)){foreach($this->degree as $rs){?>
											<option value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
										<?php }}?>
									</select>
								</td>
							</tr>
							
							<tr>
								<td valign="top"><?php echo $tr->translate("NOTE")?></td>
								<td><input type="text" name="note" id="note" readonly class="fullside" dojoType="dijit.form.TextBox"   /></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("PAID_DATE");?></td>
								<td><input type="text" dojoType="dijit.form.DateTextBox" required="true" constraints="{datePattern:'dd/MM/yyyy'}" required="1" value="now" name="paid_date" id="paid_date" class="fullside"/></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("PRICE")?></td>
								<td><input type="text" name="price" id="price" required="true" class="fullside" onkeyup="readMoneyInKhmer();" dojoType="dijit.form.NumberTextBox"   /></td>
							</tr>
							<tr>
								<td >អានជាខ្មែរ</td>
								<td colspan="3">
									<Textarea type="text" name="money_in_khmer" id="money_in_khmer" readonly="readonly" dojoType="dijit.form.TextBox" class="fullside" ></Textarea>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3" align="center">
					    <input type="button" onclick="submitDataClose();"  name="save_close" id="save_close" value="1" label="<?php echo $tr->translate('SAVE_CLOSE');?>"   dojoType="dijit.form.Button" 
						 iconClass="dijitEditorIcon dijitEditorIconSave"  />
						<input type="button" onclick="submitDataAddNew();" name="save_new" id="save_new" value="1" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
						 iconClass="dijitEditorIcon dijitEditorIconSave"  />
						 <input type="button" value="1" label="<?php echo $tr->translate('PRINT');?>" id="busyButton" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave('','');"/> 
					</td>
				</tr>
			</table>
	</fieldset>
</form>
<style>
	.tablesorter tr td{
		border: 1px solid #000;	
	}
</style>
<script type="text/javascript">

function submitDataClose(){
	
	if(dijit.byId('office_receipt').validate()) {
		
		dijit.byId('save_close').set('disabled',true);
	
		var url_submit = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttestpayment','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";	
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/registrar/studenttestpayment";
			},
			error: function(e) {
			}
		});
	}
}
function submitDataAddNew(){
	if(dijit.byId('office_receipt').validate()) {
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttestpayment','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";		
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/registrar/studenttestpayment/add";
			},
			error: function(e) {
			}
		});
	}
}

function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}

</script>

<div class="dijitHidden" style="padding: 0px; margin: 0px;">
	<div id="terms" data-dojo-type="dijit.Dialog" style="width:23.5cm;height: 16cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("OFFICIAL_RECEIPT");?>'"  >
		<style>
			.hearder_table{height:25px !important;}
			.defaulheight{line-height: 22px !important;}
		</style>
		<div id="PrintReceipt" style="width: 22cm !important; padding: 0px; margin-bottom:30px; ">
			<table width="100%"  class="print" cellspacing="0"  cellpadding="0" style="height:10.97cm; font-family: 'Khmer OS Battambang' !important; font-size:11px !important; margin-top: -14px;white-space:nowrap;">
				
				<?php if($this->data['show_header_receipt']==1){?>
					<tr height="40px;">
						<td colspan="10"  style="" align="center" valign="top">
							<table width="100%" style="font-size: 10px;margin-bottom: 0px;" >
								<tr>
									<td width="30%">
										<img style="height: 80px" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
									</td>
									<td width="40%" align="center" valign="top" style="font-size: 16px;font-weight: bold;">OFFICIAL RECEIPT
										<div><img height="20px" style="margin-top: -2px" src="<?php echo $this->baseUrl().'/images/fonttateng.png'?>"></div>
									</td>
									<td width="30%" valign="center" align="center">
										<div style="font-size: 15px;font-family:Battambang,Arial,Helvetica,sans-serif;"><u>Receipt N<sup>o</sup></u> <label id="lb_receipt_no"></label></div> 
										<span style="font-size: 14px;font-weight: bold;font-family: arail">Pmt Date : <label id="lb_date" class=" one bold"></label></span>
									</td>
								</tr>
							</table>
						</td>
					</tr> 
				<?php }else{?>
					<tr height="115px;" >
						<td colspan="10"  style="" align="center" valign="top"></td>
					</tr>
				<?php }?>
				
				<style>
					.bold{
						font-weight:bold;
						}
				</style>
				
				<tr height="40px;">
					<td colspan="10"  style="" align="center" valign="top">
						<table width="100%" style="font-size: 10px;margin-bottom: 0px;" >
							<tr>
								<td width="30%">
								</td>
								<td width="30%" valign="center" align="center">
									<div style="font-size: 15px;font-family:Battambang,Arial,Helvetica,sans-serif;"><u>Receipt N<sup>o</sup></u> <label id="lb_receipt_no"></label></div> 
									<span style="font-size: 14px;font-weight: bold;font-family: arail">Pmt Date : <label id="lb_date" class=" one bold"></label></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="10" valign="top">
						<table class='defaulheight' width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:12px;white-space:nowrap;margin-top:-5px;line-height: 11px;">
							<tr>
								<td>Serial</td>
								<td> : &nbsp;&nbsp;<label id="lb_serial" class="one bold"></label></td>
								<td>Dob</td>
								<td> : &nbsp;&nbsp;<label id="lb_dob" class="one bold"></label> </td>
								<td >Grade</td>
								<td> : &nbsp; </td>
							</tr>
							<tr >
								<td>Student's Name</td>
								<td colspan="1"> : &nbsp;&nbsp;<label id="lb_name" class="one bold"></label> </td>
								<td>Phone</td>
								<td> : &nbsp;&nbsp;<label id="lb_phone" class="one bold"></label> </td>
								<td>Academic Year</td>
								<td>  : &nbsp; </td>
							</tr>
							<tr >
								<td>Gender </td>
								<td> : &nbsp;&nbsp;<label id="lb_sex" class=" one bold"></label></td>
								<td>Degree</td>
								<td> : &nbsp;&nbsp;<label id="lb_degree" class="one bold"></label> </td>
								<td>Session</td>
								<td> : &nbsp; </td>
							</tr>
							<tr>
								<td colspan="6">
									<div id="t_amountmoneytype"></div>
								</td>
							</tr>
							<tr>
								<td colspan="6">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="6">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="6">
									<table border="0" width="100%" style="font-size:12px; white-space:nowrap;line-height:15px;margin-top:-3px;border-collapse:collapse;">
										<tr>
											<td width="37%"></td>
											<td width="37%"></td>
											<td width="11%"></td>
											<td width="15%"></td>
										</tr>
										<tr>
											<td colspan="2">
												<table width="100%" border="0" style="white-space:nowrap;border-collapse:collapse;font-size:12px;line-height:16px;">	
													<tr>
														<td width="33%" align="center">Cashier</td>
														<td width="34%" align="center">Customer</td>
														<td width="33%" align="center">Verified By</td>
													</tr>	
													<tr>
														<td align="center">&nbsp;</td>
														<td align="center"></td>
														<td align="center"></td>
													</tr>	
													<tr style="height:15px;">
														<td align="center">
															<div style="font-weight:bold;color:#000; font-size: 11px;font-family:'Khmer OS Battambang';margin-top: 5px;"> 
																<?php 
																   $session_user=new Zend_Session_Namespace('authstu');
																   $last_name=$session_user->last_name;
																   $username = $session_user->first_name;
																   echo "".$last_name." ".$username;
																?>
																<div style="margin-top:-2px;font-size:10px;"><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?></div>
															</div>
														</td>
														<td align="center"></td>
														<td align="center"></td>
													</tr>	
												</table>	
											</td>
											<td valign="top"><span style="font-size: 14px;font-weight: bold;font-family: arail">Net Amount</span></td>
											<td valign="top"> : &nbsp;&nbsp; <span style="font-size: 14px;font-weight: bold;font-family: arail"><label id="lb_net_amount" ></label></span></td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				 type="button" onclick="confirmBeforePrint();"><?php echo $tr->translate("SAVE_PRINT");?></button>
	</div>
</div>

<div class="dijitHidden" style="padding: 0px; margin: 0px;">
	<div id="alertBeforePrint" data-dojo-type="dijit.Dialog" style="width:10cm;height: 5cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("បោះពុម្ពបង្កាន់ដៃ");?>'"  >
		<table width="100%"  class="print" cellspacing="0"  cellpadding="0" style="height:4cm;color:red; font-family: 'Khmer OS Battambang' !important;font-size:15px !important;white-space:nowrap;">
			<tr>
				<td align="center" >
					តើលោកអ្នកពិតជាចង់បោះពុម្ពបង្កាន់ដៃនេះ មែនទេ? <br />
					Do you really want to print ?
				</td>
			</tr>
			<tr>
				<td align="center">
					<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
						type="button" onclick="hideDialog1(),dijit.byId('office_receipt').submit();">No</button>
					<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
						type="button" onclick="printSubmit();"><?php echo $tr->translate("Yes");?></button>
				</td>
			</tr>
		</table>
	</div>
</div>


<script>

function confirmBeforePrint(){
	dijit.byId('alertBeforePrint').show();
}
function displayNone(){
	document.getElementById('PrintReceipt1').style.display="none";
}
function printSubmit(){
	window.frames["print_frame"].document.body.innerHTML = dojo.byId('PrintReceipt').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
	hideDialog1();
    dijit.byId('office_receipt').submit();
}
function hideDialog(){
	dijit.byId('terms').hide();
}

function hideDialog1(){
	dijit.byId('alertBeforePrint').hide();
}

function setID(){
	stu_id = dijit.byId('old_stu_name').get('value');
	dijit.byId('old_studens').attr('value',stu_id);
	getPaymentHistory(stu_id);
}

function readMoneyInKhmer(){

		netTotal = dijit.byId('price').get('value').toFixed(2);
	
		var str = netTotal.toString();
        str_cent = 'សេន';
		first_decimal = str.substr(-2);
		last_decimal = str.substr(-1);
        if(first_decimal>0){string=' ចុច ';}else{string="";str_cent=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
	    first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
	    last_money_decimal = read_in_khmer_from_0_to_9(last_decimal)
	    money_khmer=read_money_in_khmer(netTotal);

	    if(first_decimal>0){string_en=' dot ';}else{string_en="";str_cent_en=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
	    first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
	    last_money_decimal_en = read_in_english_from_0_to_9(last_decimal)
	    money_english=read_money_in_english(netTotal);
	    read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់'

	    read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )'
	    
	    dijit.byId('money_in_khmer').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់'+read_eng);
}

function alerterror(index){	
	subtotal = dijit.byId('subtotal_'+index).get('value');
	paid = dijit.byId('paidamount_'+index).get('value');
	if(paid>subtotal){
		alert("Paid amount must be equal or smaller than subtotal");
		dijit.byId('paidamount_'+index).attr('value',subtotal);
	}
}


function printSave(new_stu_id,new_receipt){		
	if(dijit.byId('office_receipt').validate()) {
		//receipt='';
		receipt=dijit.byId("receipt_no").get("value");
		degree = dijit.byId('degree').get('value');

		//var today = new Date();
		today = dijit.byId("paid_date").get("value");
		var dd = today.getDate();
		var mon = today.toDateString().substr(4,3); //January is 0!
		var yyyy = today.getFullYear();
		
		dojo.byId("lb_receipt_no").innerHTML = receipt;
		dojo.byId("lb_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
		dojo.byId("lb_degree").innerHTML = dijit.byId("degree").attr('displayedValue');
		dojo.byId("lb_date").innerHTML  = dd+'-'+mon+'-'+yyyy;
		dojo.byId("lb_dob").innerHTML = dijit.byId("dob").attr('displayedValue');
		dojo.byId("lb_name").innerHTML = dijit.byId("kh_name").get('value')+" - "+dijit.byId("en_name").get('value');

		dojo.byId("lb_serial").innerHTML = dijit.byId("serial").get('value');
		dojo.byId("lb_phone").innerHTML = dijit.byId("parent_phone").attr('displayedValue');
		//dojo.byId("lb_read_khmer").innerHTML = dijit.byId("money_in_khmer").attr('displayedValue');
		
		dojo.byId("lb_phone").innerHTML = dijit.byId("parent_phone").attr('displayedValue');

		dojo.byId("lb_net_amount").innerHTML = " $ "+dojo.number.format(dijit.byId("price").get('value'),{places:2});
		
		temp = "";
		temp='<table class="collape tablesorter"  align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:11px;font-family:Khmer OS Battambang !important;  " id="table">'
			temp+='<tr class="hearder_table" style=" font-size:12px; text-align:center;background:#f2f2f2;font-weight:bold;">';
			temp+='<td style="border:1px solid #000;">No</td>';
			temp+='<td style="border:1px solid #000;><strong style="color:#000;">Item Name</strong></td>';
			temp+='<td style="border:1px solid #000;><strong style="color:#000;">Term</strong></td>';
			temp+='<td style="border:1px solid #000;><strong style="color:#000;">Period</strong></td>';
			temp+='<td style="border:1px solid #000;><strong style="color:#000;">Unit Price</strong></td>';
			temp+='<td style="border:1px solid #000;><strong style="color:#000;">Qty</strong></td>';
			temp+='<td style="border:1px solid #000;><strong style="color:#000;">Late Fee</strong></td>';
			temp+='<td style="border:1px solid #000;><strong style="color:#000;">Extra Fee</strong></td>';
			temp+='<td style="border:1px solid #000;><strong style="color:#000;">Discount</strong></td>';
			temp+='<td style="border:1px solid #000;><strong style="color:#000;">Amount</strong></td>';
			temp+='<td style="border:1px solid #000;><strong style="color:#000;">Note</strong></td>';
		temp+='</tr>';
		temp+='<tr style="font-size:12px !important;height: 10px;border:1px solid #000; ">';
		  temp+='<td align="center" style="border:1px solid #000;">1</td>';
		  temp+='<td style="border:1px solid #000;">&nbsp;&nbsp;Test Fee</td>';
		  temp+='<td align="center" style="border:1px solid #000;"> </td>';
		  temp+='<td align="center" style="border:1px solid #000;"> </td>';
		  temp+='<td align="center" style="border:1px solid #000;">$ '+dojo.number.format(dijit.byId("price").get('value'),{places:2})+'</td>';
		  temp+='<td align="center" style="border:1px solid #000;">'+1+'</td>';
		  
		  temp+='<td align="center" style="border:1px solid #000;">$ 0</td>';
		  temp+='<td align="center" style="border:1px solid #000;">$ 0</td>';
		  
		  temp+='<td align="center" style="border:1px solid #000;">0</td>';
		  temp+='<td align="center" style="border:1px solid #000;">$ '+dojo.number.format(dijit.byId("price").get('value'),{places:2})+'</td>';
		  temp+='<td align="center" style="border:1px solid #000;">'+dojo.number.format(dijit.byId("price").get('value'),{places:2})+'</td>';
		  
	  temp+='</tr>';
		
		temp+='</table>';
		dojo.byId('t_amountmoneytype').innerHTML = temp;
		dijit.byId("terms").show();	
	}
}

/////////////// get student test info ////////////////////////////////////////////////////////
var url_student_test = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttestpayment','action'=>'get-student-test-info')); ?>";
function getStudentTestInfo(){
	stu_test = dijit.byId('stu_test').get('value');
	if(stu_test != ""){
	 	dojo.xhrPost({
	 		url:url_student_test,
	 		content:{
	 			'stu_test_id':stu_test,
	 			},
	 		handleAs:"json",
	 		load: function(data) {
	 			dijit.byId("kh_name").attr("value",data.kh_name);
				dijit.byId("en_name").attr("value",data.en_name);
				dijit.byId("sex").attr("value",data.sex);
				dijit.byId("dob").attr("value",data.dob);
				dijit.byId("parent_phone").attr("value",data.phone);
				dijit.byId("degree").attr("value",data.degree_result);
				dijit.byId("serial").attr("value",data.serial);
				dijit.byId("test_date").attr("value",data.test_date);
				dijit.byId("note").attr("value",data.note);
	 		},
	 		error: function(err) {
	 			alert(err);
	 		}
	 	});	 
	}
}
function getDefaultTutionfee(){
	degree = dijit.byId("degree").get("value");
	if(degree==1 || degree==2 || degree==3){
		dijit.byId("price").attr("value",50.00);
	}else{
		dijit.byId("price").attr("value",2.50);
	}
}
</script>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>