<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_CARDMG')); 
?>
<?php  $frm = $this->frm_branch;?>
<style>
.image-box {
    text-align: center;
    width: 5.15cm;
    height: 8.5cm;
}
.image-box img {
    width: 5.15cm;
    height: 8.5cm;
}

.button_browse {
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 38px;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 38px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 5.15cm;
    margin: 0 auto;
}
ul.opt-school {
    list-style-type: none;
}
 input[type=checkbox],  input[type=radio]{
	height: 15px;
    display: initial;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-book" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_CARDMG');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id="frm_branch" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					
					branch_id=dijit.byId("branch_id").get('value');
					if(branch_id=='' || branch_id==null){
						dijit.byId("branch_id").focus();
						return false;
					}
					schoolOption=dijit.byId("schoolOption").get('value');
					if(schoolOption=='' || schoolOption==null){
						dijit.byId("schoolOption").focus();
						return false;
					}
					loadingBlock();
               	 	
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("BRANCH_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">	
	                   		<?php echo $frm->getElement("branch_id");?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TITLE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("title");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("Card Prefix");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("card_prefix");?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("Card Type");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("card_type");?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("School Option");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("schoolOption");?>
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("Issue Date");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("issue");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("Valid Date");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("valid");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("COLOR");?> (ID Card)
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("colorcode");?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("note");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DISPLAY_BY");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("display_by");?>
	                   </div>
	                </div>
	            </div>
	           <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PHOTO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12 text-center">
	                    	<div class="account-image">
	                    		<div class="image-box">
									<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/card/default_card_bg.jpg';?>" alt=""  />
								</div>
								<div class="button_browse">
								<div id='preview'></div>	
									<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
									<input class="btn_borwse_image" type="file" id="photo" name="photo" >
								</div>
							</div>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
	            	<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" >
	                   <i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("FRONT_CARD");?> 
					   </label>
	                </div>	
	                <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12 text-center">
	                    	<div class="account-image">
	                    		<div class="image-box">
									<img id="profile_wiew_front" src="<?php echo $this->baseUrl().'/images/card/default_card_bg.jpg';?>" alt=""  />
								</div>
								<div class="button_browse">
								<div id='preview'></div>	
									<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
									<input class="btn_borwse_image" type="file" id="front_background" name="front_background" >
								</div>
							</div>
	                   </div>
	                </div>
	            </div>
            <div class="card-box">
	         	<div class="col-md-8 col-sm-8 col-xs-12">
	         		<table id="table_row" border="1" style="border-collapse: collapse; border:1px solid #ccc;">
							<tr id="head-title" class="head-td" align="right"></tr>
					</table>
					<input type="hidden" id="identity" name="identity" />
	         	</div>
	         </div>          
            <div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear" />
					<input type="submit"  value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					<input type="submit" value="save_new" name="save_new"  id="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
	</div>
</div>
<script>
dojo.require("dijit.form.DateTextBox");
dojo.require('dijit.form.NumberTextBox');
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#profile_wiew').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#photo").change(function(){
    readURL(this);
});


function readURLFront(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#profile_wiew_front').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#front_background").change(function(){
	readURLFront(this);
});
</script>