<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_STUDENT_DROP')); 
	$frm = $this->frm;
?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_STUDENT_DROP');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id="add_studentdrop" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentdrop','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit" >			
				if(this.validate()) {
              	 	studentid=dijit.byId('studentid').get('value');
      				if(studentid==0 || studentid=='' || studentid ==-1){
						alert("<?php echo $tr->translate("PLEASE_SELECT_STUDENT");?>");
						dijit.byId('studentid').focus();
						return false;
					}
  					if(dijit.byId('type').get('value')==''){
						alert("<?php echo $tr->translate("PLEASE_SELECT_TYPE");?>");
  						dijit.byId('type').focus();
						return false;
  	  	  			}
					loadingBlock();
					dijit.byId('save_close').set('disabled',true);
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement("branch_id");?>
	                   		<?php echo $frm->getElement("id");?>
	                   </div>
		             </div>
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<input id="studentid" />
		                </div>
		            </div>
		            <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SEX");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("gender");?>
		                </div>
		            </div>
		            <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("CULTURE_LEVEL");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<?php echo $frm->getElement("calture");?>
		                </div>
		            </div>
		            <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ACADEMIC_YEAR");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("academic_year");?>
		                </div>
		            </div>
		            <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GRADE");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<input id="grade" />
		                </div>
		            </div>
		            <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DEGREE");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("degree");?>
		                </div>
		            </div>
		            <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SESSION");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("session");?>
		                </div>
		            </div>
		        </div>
		        <div class="col-md-4 col-sm-4 col-xs-12">
		            <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ROOM_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
	                		<?php echo $frm->getElement("room");?>
		                </div>
		            </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<input id="group" />
		                </div>
		            </div>
		            <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("type");?>
		                </div>
		            </div>
		            <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STOP_DATE");?> <span class="required">*</span></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input dojoType="dijit.form.DateTextBox" required="true" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" id="datestop" name="datestop" value="now" type="text">
		                </div>
		            </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("REASON");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("reason");?>
		                </div>
		            </div>
		        </div>
		        <div class="col-md-4 col-sm-4 col-xs-12">
		        </div>
			</div>
		     <div class="clearfix"></div>
	       	<div class="card-box mt-20 ">
	      	 	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
              		 <input iconClass="dijitIconClear" type="reset"  label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
					<input type="submit" id="save_close" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
					iconClass="dijitEditorIcon dijitEditorIconSave" />
            	 </div>
            </div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");

var stuid_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->stuname));?> );
var group_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->group));?> );
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->grade_name));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
	    store:group_store,
	    queryExpr: "*${0}*",
		autoComplete: false,                      
	    required: false,
	    id: "group",
	    name: "group",   
	    readOnly:true,           
	    class: 'fullside', 
	    value:'<?php echo $this->row['group'];?>',         
	    required:'true',
	    placeHolder:"<?php echo $tr->translate("SELECT_YEAR")?>",          
	    onChange: function() {  
	    }
	}, "group");
	new dijit.form.FilteringSelect({
		store:grade_store,
		queryExpr: "*${0}*",
		autoComplete: false,                                           
		id: "grade",
		name: "grade", 
		readOnly:true, 
		value:'<?php echo $this->row['grade'];?>',          
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
		}
	}, "grade");
	
	new dijit.form.FilteringSelect({
		store:stuid_store,
		autoComplete: false,
		queryExpr: "*${0}*",                     
		id: "studentid",
		name: "studentid",  
		readOnly:true,   
		required:true,        
		class: 'fullside',
		placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
		onChange: function() { 
			getStudentInfo();
		}
	}, "studentid");
	
	getallstudentname();
	 var branch_id = dijit.byId('branch_id');
	 	branch_id.on('change', function(evt){
	 		getallstudentname();
	    });
});
var study_id = '<?php echo $this->row['study_id']?>';
var url_data = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getallstudent')); ?>';
function getallstudentname(){//
	branch_id = dijit.byId("branch_id").attr("value");
	if(branch_id==''){  
		dijit.byId("branch_id").focus();
		return false;}
	dojo.xhrPost({
		url:url_data,
		content:{
			'branch_id':branch_id,'study_id':study_id
		},
		handleAs:"json",
		load: function(data) {
			student_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('studentid').set('store',student_store);  
		    dijit.byId('studentid').set('value',study_id);  
		},
		error: function(err) {
			alert(err);
		}
	});
}
function getallGrade(){
	
}
function getStudentNo(){
	
}
function getStudentInfo(){
	
}
//var url_student = '<?php //echo $this->url(array('module'=>'foundation','controller'=>'studentdrop','action'=>'get-student')); ?>';
/*var url_student = '<?php //echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'getstudentstudyinfo')); ?>';
function getStudentInfo(){
	studentid = dijit.byId('studentid').get('value');
	if(studentid==''){
		alert("Please Select Student");
		return false;
	}
	dojo.xhrPost({
		url:url_student,
		content:{
			'study_id':studentid
			},
		handleAs:"json",
		load: function(data) { 
			dijit.byId("gender").attr("value",data.sex);
			dijit.byId('gender').set('readOnly',true);
			dijit.byId("academic_year").attr("value",data.academic_year);
			dijit.byId('academic_year').set('readOnly',true);
			if(data.calture>0){
				dijit.byId("calture").attr("value",data.calture);
			}
			if(data.session>0){
				dijit.byId("session").attr("value",data.session);
			}
			dijit.byId('calture').set('readOnly',true);
			dijit.byId('session').set('readOnly',true);

			//if(data.group_id>0){
				//dijit.byId("group").attr("value",data.group_id);
				//dijit.byId('group').set('readOnly',true);
			//}
			
			dijit.byId('degree').set('value',data.degree);
			dijit.byId('degree').set('readOnly',true);
			dijit.byId('grade').set('value',data.grade);
			dijit.byId('grade').set('readOnly',true);
			if(data.room>0){
				dijit.byId('room').set('value',data.room);
			}
			dijit.byId('room').set('readOnly',true);
		},
		error: function(err) {
		}
	});
}*/
</script>

