
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_DROP')); 
	$frm =  $this->form_search;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentdrop','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<table style="width:100%">
				  <tr> 
						<td> <?php echo $frm->getElement("title");?></td>
						<td> <?php echo $frm->getElement("study_year");?></td>
						<td> <?php echo $frm->getElement("grade_bac");?></td>
						<td> <?php echo $frm->getElement("session");?></td>
						<td> <?php echo $frm->getElement("start_date");?></td>
						<td> <?php echo $frm->getElement("end_date");?></td>
						<td>
							<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
						</td>
				  </tr>
				 </table>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
