<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_DROP')); 
	$frm =  $this->form_search;
	$urlLetter = $this->baseUrl()."/allreport/allstudent/suspensionletter/id/";
	$urlEdit = $this->baseUrl()."/foundation/studentdrop/edit/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		   			<h4 class="m-b-0"><i class="fa fa-server" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('STUDENT_DROP');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentdrop','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				<div class="form-group">
					 <div class="col-md-2 col-sm-3 col-xs-12">
					 	<?php echo $frm->getElement("title");?>
					 </div>
					 <div class="col-md-2 col-sm-3 col-xs-12">
					  	<?php echo $frm->getElement("branch_id");?>
					 </div>
					  <div class="col-md-2 col-sm-3 col-xs-12">
					  	<input id="study_year" />
					 </div>
					 <div class="col-md-2 col-sm-3 col-xs-12">
					  	<?php echo $frm->getElement("degree");?>
					 </div>
					 <div class="col-md-2 col-sm-3 col-xs-12">
					  	<input id="grade" />
					 </div>
					 <div class="col-md-2 col-sm-3 col-xs-12">
					  	<?php echo $frm->getElement("session");?>
					 </div>
				</div>
				<div class="form-group">
					 
					 <div class="col-md-2 col-sm-3 col-xs-12">
					 	<?php echo $frm->getElement("start_date");?>
					 </div>
					  <div class="col-md-2 col-sm-3 col-xs-12">
					  <?php echo $frm->getElement("end_date");?>
					 </div>
					  <div class="col-md-2 col-sm-2 col-xs-12">
					  	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
					 </div>
					  <div class="col-md-2 col-sm-2 col-xs-12">
					 </div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore"); 
	dojo.require("dijit.form.DateTextBox");	
	
	var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	var group_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: academic_store,
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                     
			id: "study_year",
			name: "study_year",
			class: "fullside", 		
			placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
			onChange: function() {  
				academic_year = dijit.byId('study_year').get('value');
			}
		}, "study_year");
		
		new dijit.form.FilteringSelect({
			queryExpr: "*${0}*",
			autoComplete: false,                     
			required: false,                        
			id: "grade",
			name: "grade",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
			}
		}, "grade");
		getallGrade();
		
		 var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getAllAcademicByBranch();
		});
		 getAllAcademicByBranch();
	});
	url_getacademic= '<?php echo $this->url(array('module'=>'foundation','controller'=>'group','action'=>'getacademic'));?>';
	var oldBranch = "<?php echo $this->search['branch_id']?>";
	function getAllAcademicByBranch(){
		dijit.byId('study_year').reset();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==-1){
			var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
			dijit.byId('study_year').set('store',academic_store);  
			dijit.byId('branch_id').focus();
			return false;
		}
		dojo.xhrPost({
			url: url_getacademic,
			content:{
				'branch_id':branch_id,'showall':1
				},
			handleAs:"json",
			load: function(data) {
				academic_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('study_year').set('store',academic_store);  
				if(oldBranch==branch_id){
					dijit.byId('study_year').set('value','<?php echo $this->search['study_year']?>');  
				}
			},
			error: function(err) {
			}
		});
	}
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
	function getallGrade(){
		dept_id = dijit.byId('degree').get('value');
		if(dept_id==''){return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				grade_store  = getDataStorefromJSON('id','name', data);
				dijit.byId('grade').set('store',grade_store);   
				dijit.byId('grade').attr('value','<?php echo $this->search['grade']?>');  
			},
			error: function(err) {
			}
		});
	}
	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
			
				var m = "clicked: " + key;
				if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}else if(key=="letter"){
					url='<?php echo $urlLetter;?>';
				}
				gotoAction();
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
				"letter": {name: "<?php echo $tr->translate("Suspension Letter");?>", icon: "fa-file-text-o"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}

	var recordid ='';
	function gotoAction(){
		window.location.href =url+row;
	}
</script>