<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_NEW_SUBJECT')); 
?>	
<?php  $subject_exam= $this->frm_subject_exam;?>
<form  id='add_subject_exam' action="<?php echo $this->url(array('module'=>'global','controller'=>'subject','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" width="40%" style="margin: 0 auto;">
	<tr>
		<td>
			<fieldset style="background-color:menu;">
						<legend align="center" style="font-size: 18px;"><strong><?php echo $tr->translate("ADD_NEW_SUBJECT");?></strong></legend>
						<table style="margin: 0 auto; width: 95%;white-space: nowrap;" cellspacing="10">
							<tr>
								<td><input type="checkBox" checked="checked" dojoType="dijit.form.CheckBox" value="1" id="is_parent" onChange="getValue();" name="is_parent" /><?php echo $tr->translate("IS_PARENT")?></td>
								<input type="hidden" id="par" name="par" />
							</tr>
							<tr>
								<td style="width: 100px"><?php echo $tr->translate("PARENT")?></td>
								<td>
									<select class="fullside" name="parent" id="parent" dojoType="dijit.form.FilteringSelect" >
										<option value="0"></option>
										<?php if(!empty($this->rs))foreach ($this->rs as $row){?>
													<option value="<?php echo $row['id']?>"><?php echo $row['subject_titleen']?></option>
										<?php }?>
									</select>
								</td>
							</tr>
							<tr>
								<td style="width: 100px"><?php echo $tr->translate("SUBJECT_IN_KH")?></td>
								<td><?php  echo $subject_exam->getElement('subject_kh');?></td>
							</tr>
							<tr>
								<td style="width: 100px"><?php echo $tr->translate("SUBJECT_IN_EN")?></td>
								<td><?php  echo $subject_exam->getElement('subject_en');?></td>
							</tr>
							<tr>
								<td style="width: 100px"><?php echo $tr->translate("SHORT_CUT")?></td>
								<td><?php echo $subject_exam->getElement('score_percent');?></td>
							</tr>
							<tr>
								<td style="width: 5px"><?php echo $tr->translate("DEGREE")?></td>
								<td><input id="access_type" />
								</td>
							</tr>
							<tr>
								<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
								<td><?php  echo $subject_exam->getElement('status');?></td>
							</tr>
							<tr>
								<td colspan="2" align="center">
									<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
									<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
								</td>
							</tr>
						</table>	
			</fieldset>		
		</td>
	</tr>
</table>	
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_add_degree" >
		<form  id='frm_degree' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td><?php echo $tr->translate("DEGREE");?></td>
					<td>
						<input type="text" class="fullside" name='fac_enname' id="fac_enname" required="1" dojoType="dijit.form.ValidationTextBox" />
					</td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("SHORTCUT");?></td>
					<td>
						<input type="text" class="fullside" name='shortcut_fac' id="shortcut_fac" dojoType="dijit.form.TextBox" />
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="button"  label="<?php echo $tr->translate("CANCEL");?>" id="cancelButton" 
						dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideDialog();"/>
						
						<input type="button"  label="<?php echo $tr->translate("SAVE");?>" id="submitButton" 
						dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addDept();"/>
					</td>
				</tr>
			</table>

		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");
var degree_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->degree_store));?> );

require(["dojo/ready"], function(ready){
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
		    store: degree_store,
		    autoComplete: true,                        
		    required: true,
		    id: "access_type",
		    name: "access_type",           
		    class: "full height-text", 
		    placeHolder:"Select Degree",          
		    onChange: function() {  
		    	dept_id = dijit.byId('access_type').get('value');
		    	if(dept_id==-1){
		    			dijit.byId("popup_add_degree").show();
		    		
			    }
		    }
		}, "access_type");
	});
	
	ready(function(){
		getValue();
		dijit.byId("parent").set('readOnly',true);
	});
});
	function getValue(){
		var par='';
		if(dojo.byId('is_parent').checked){
			par = 1;
			dijit.byId('parent').attr('value','');
			dijit.byId("parent").set('readOnly',true);
			 dijit.byId('parent').set('required',false);  
		}else{
			par=0;
			dijit.byId("parent").set('readOnly',false);
			 dijit.byId('parent').set('required',true);  
		}
		$('#par').val(par);
	}
	var url_add_dept = '<?php echo $this->url(array("module"=>"global","controller"=>"grade","action"=>"add-dept")); ?>';
	function addDept(){
		if(dijit.byId('frm_degree').validate()) {
			dojo.xhrPost({
					url:url_add_dept,
					form: dojo.byId("frm_degree"),
					handleAs:"json",
					load: function(data) {
						var Itemmake = { 
						    	 id: data,
							     name: dijit.byId('fac_enname').get('value')
							   };
				   addDataToSelectbox(dijit.byId('access_type'), degree_store, Itemmake, data);
				   dijit.byId('frm_degree').reset();
				   dijit.byId("popup_add_degree").hide();
					},
					error: function(err) {
						alert(err);
					}
			});
		}
	}
</script>