<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_SUBJECT')); 
	$subject_exam= $this->frm_subject_exam;
?>
<style>
span#message {
    color: #fb0101;
    font-style: italic;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_SUBJECT');?></h4>
					<span id="message"></span>
				</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form  id='add_subject_exam' action="<?php echo $this->url(array('module'=>'global','controller'=>'subject','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
   				if(this.validate()) {
   					schoolOption=dijit.byId("schoolOption").get("value");
               		 if(schoolOption==-1 || schoolOption==''){
						alert("<?php echo $tr->translate("PLEASE_SELECT_SCHOOL_OPTION");?>");
						dijit.byId('schoolOption').focus();
                    	return false;
					}
					if(isDuplicate==1){
						alert("<?php echo $tr->translate("ALREADY_EXISTING_RECORD");?>");
						dijit.byId("subject_kh").focus();
						return false;
					}
					loadingBlock();
					return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-folder-open"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("SUBJECT");?></p>
										</div> 
									</div>
									<br />
									<div class="form-group">
										<div class="custom-control custom-checkbox ">
											<input type="checkbox" class="checkbox custom-control-input" <?php if($this->row['is_parent']==1){echo "checked='checked'";}?> value="1" id="is_parent" onChange="getValue();" name="is_parent" >
											<label class="custom-control-label" for="is_parent">
												<?php echo $tr->translate('IS_PARENT');?>
											</label>
											<input type="hidden" id="par" name="par" />
										</div>
									 </div>
									
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("PARENT");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<select class="fullside" name="parent" id="parent" dojoType="dijit.form.FilteringSelect" >
												<option value="0" <?php if($this->row['parent']==0  ) echo 'selected="selected"';?>></option>
												<?php if(!empty($this->rs))foreach ($this->rs as $row){?>
															<option value="<?php echo $row['id']?>" <?php echo 'selected="selected"';?>><?php echo $row['subject_titleen']?></option>
												<?php }?>
											</select>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SUBJECT_IN_KH");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $subject_exam->getElement('subject_kh');?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SUBJECT_IN_EN");?> <span class="required">*</span></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $subject_exam->getElement('subject_en');?>
											<?php  echo $subject_exam->getElement('id');?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SHORTCUT");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $subject_exam->getElement('score_percent');?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $subject_exam->getElement('type_subject');?>
										</div>
									 </div>

									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SUBJECT_STUDY_IN");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $subject_exam->getElement('subject_lang');?>
										</div>
									 </div>

									

									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SCHOOL_OPTION");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $subject_exam->getElement('schoolOption');?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label custom-switch float-end "> 
											<a href="javascript:void(0);" class="switchButton status"><?php echo $tr->translate("STATUS");?></a> 
											<input type="checkbox" id="status" name="status" class="custom-switch-input"  <?php if(!empty($this->rsRow['status'])){ echo "checked";} ?> > 
											<span class="custom-switch-indicator custom-radius switch-status"></span> 
										</label>
									</div>
									 <div class="clearfix"></div>
									 <div class="card-box mt-20">
										 <div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
											<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="<?php echo $tr->translate("GO_EDIT");?>" label="<?php echo $tr->translate("GO_EDIT");?>" id="submitButton" dojoType="dijit.form.Button"  />
										 </div>
									 </div>
								 </div>
							 </div>
						 </div>
					 </div>
		         </div>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require("dijit.form.CheckBox"); 
function getValue(){
	var par='';
	if(dojo.byId('is_parent').checked){
		par = 1;
		dijit.byId('parent').attr('value','');
		dijit.byId("parent").set('readOnly',true);	
	}else{
		par=0;
		dijit.byId('parent').attr('value','0');
		dijit.byId("parent").set('readOnly',false);
	}
	$('#par').val(par);
}
dojo.ready(function(){
	getValue();
	dijit.byId('parent').attr('value','<?php echo $this->row['parent'] ?>');
	
	var subject_kh = dijit.byId('subject_kh');
		subject_kh.on('keyUp', function(evt) {
			checkDuplicateRecord();
		});
});

var isDuplicate = 0;
var url_duplicate = '<?php echo $this->url(array("module"=>"global","controller"=>"subject","action"=>"checkduplicate"));?>';										
function checkDuplicateRecord(){
	subjectKhTitle = dijit.byId('subject_kh').get('value');
	if(subjectKhTitle=='' || subjectKhTitle==-1){
		dijit.byId('subject_kh').focus();
		return false;
	}
	id = dijit.byId('id').get('value');
	dojo.xhrPost({
		url: url_duplicate,
		content:{
			'subjectKhTitle':subjectKhTitle,'id':id
			},
		handleAs:"json",
		load: function(data) {
			if(data==1){
				isDuplicate = 1;
				alert("<?php echo $tr->translate("ALREADY_EXISTING_RECORD");?>");
				$("#message").html('<?php echo '<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> '.$tr->translate("ALREADY_EXISTING_RECORD");?> !');
			}else{
				isDuplicate=0;
				$("#message").html('');
			}
			HideloadingBlock();
		},
		error: function(err) {
			alert(err);
			HideloadingBlock();
		}
	});
}

function langOption(){
	type_sub = dijit.byId('type_subject').get('value');
	if(type_sub == 2){
		dijit.byId("subject_lang").set('value','0');
		dijit.byId("subject_lang").set('readOnly',true);
		 

	}else{
		dijit.byId("subject_lang").set('readOnly',false);
		

	}
	
}


</script>