<?php 
	$frm = $this->form_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("OTHER_INCOME")?></title>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-file-text" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('OTHER_INCOME');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
	    </div>
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'registrar','controller'=>'income','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("adv_search");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement('branch_id');?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<input id="studentId" />
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement('option_type');?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement('cate_income');?>
	            	</div>
	            </div>
	            <div class="form-group">
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement('status');?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("start_date");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<?php echo $frm->getElement("end_date");?>
	            	</div>
	            	<div class="col-md-2 col-sm-2 col-xs-12">
	            		<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	            	</div>
	            </div>
            </form>
		</div>
		<div class="card-box">
			 <?php echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		required: false,  
		autoComplete: false,
		queryExpr: "*${0}*",                      
	    id: "studentId",
	    name: "studentId",  
	    tabindex: "1",         
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME")?>", 
	    
	}, "studentId");

	branchId = dijit.byId('branch_id');
	branchId.on('change',function(evt){
		branchId = dijit.byId('branch_id').get('value');
		if(branchId==''){
			dijit.byId("branch_id").focus();
			return false;
		}
		getAllstudentBranch();
	});

	getAllstudentBranch();
});

function getAllstudentBranch(){
	dijit.byId("studentId").reset();
	branchId = dijit.byId('branch_id').get('value');
	if(branchId==''){
		 dijit.byId('branch_id').focus();
		 return false;
	}
	
	var urlGet = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getallstudent')); ?>';
	
	contentData = {
			'branch_id':branchId,
			'customer_type':1
			}
	selectedId='<?php echo $this->adv_search['studentId'];?>';
	getAllStudentByBranch(urlGet,contentData,selectedId);
}

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="receipt"){
				url='<?php echo $this->baseUrl()."/allreport/accounting/reprint-other-income/id/";?>';
			}
			gotoAction();
		},
		items: {
			"receipt": {name: "<?php echo $tr->translate("RECEIPT");?>", icon: "fa-money", accesskey: "c"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>