<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_FEE')); 
	$frm = $this->frm_fee;
	$payment_term = $this->payment_term;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>
	.dijitTextArea[cols].dijitTextArea[cols]{
		width: 99%;
	}
	select{ width:100%;}
	fieldset{  background:none;}
	table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
	table tr td.null-border{ background: #fff; border-left:none !important;}
	table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
	table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
	table .set-style td, table .set-style th {
	    padding: 0px;
	    border: 1px solid #ccc;
	}
	ul.opt-school {
	    list-style-type: none;
	}
	 input[type=checkbox],  input[type=radio]{
		height: 15px;
	    display: initial;
	}
	.hover:hover{
		background:#eee;
	}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_FEE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id='frm_fee' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
  			 if(this.validate()) {
				branch_id = dijit.byId('branch_id').get('value');
				if(branch_id==""){
					alert("<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>");
					dijit.byId("branch_id").focus();
					return false;
				}
				school_option = dijit.byId('school_option').get('value');
				if(school_option==""){
					alert("<?php echo $tr->translate('PLEASE_SELECT_SCHOOLOPTION');?>");
					dijit.byId("school_option").focus();
					return false;
				}
				identity = dijit.byId('identity').get('value');
				if(identity==''){
					alert('Please set fee for grade !!! ');
					return false;
				}
    			return true;
  			 }else {
    			return false;
   			 }
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12">

									<div class="d-flex "> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-education" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("STUDY_INFO");?></p>
										</div> 
									</div>
									<div class="col-md-12 col-sm-12 col-xs-12">
										&nbsp; 
									</div>

									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("branch_id");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("YEARS");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("from_academic");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE_STUDY");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("type_study");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("IS_MULTY_STUDY");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("ismulty_study");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE");?></label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("generation");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("School Option");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("school_option");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("note");?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
	             </div>

	             <div class="col-md-8 col-sm-8 col-xs-12">
					<div class="card-box">
						<ul class="nav  md-pills pills-primary nav-tab" role="tablist">
							<li class="nav-item active">
								<a class="nav-link " data-toggle="tab" href="#panel21" role="tab">
									<i class="fa fa-money ml-2"></i>
								 <?php echo $tr->translate("FEE");?></a>
							</li>
							<li class="nav-item">
								<a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
								<i class="fa fa-graduation-cap ml-2"></i> <?php echo $tr->translate("START_DATE_END_DATE");?>
								</a>
							</li>
						</ul>
					</div>
					<div class="tab-content vertical">
						<div class="tab-pane fade in active" id="panel21" role="tabpanel">
							<div class="card-blogform">
								<div class="card-body"> 
										<div class="row"> 
											<div class="col-md-12 col-sm-12 col-xs-12">

												<div class="d-flex "> 
													<div class="settings-main-icon ">
														<i class="material-icons-outlined">payments</i>
													</div> 
													<div class="col-md-10 col-sm-10 col-xs-12"> 
														<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("FEE");?></p>
													</div> 
												</div>
												<div class="col-md-12 col-sm-12 col-xs-12">
													&nbsp; 
												</div>

												<div class="form-group" style=" background: #d8e0e2; padding: 5px 15px; margin: 0; border: solid 1px #697996; border-radius: 2px;">
													<label class="control-label bold col-md-2 col-sm-2 col-xs-12"><?php echo $tr->translate("GRADE");?> </label>
													<div class="col-md-5 col-sm-5 col-xs-12">
															<input id="grade" name="grade" />
													</div>
													<div class="clearfix"></div>
												</div>
												<div class="form-group">
													<table  border="1px" style="border-collapse: collapse; width:100%; border:1px solid #ccc;">
														<thead>
															<tr id="head-title" class="head-td" align="right" style="width: 100%;">
																<th width="47px"><?php echo $tr->translate("DEL");?></th>
																<th width="50px"><?php echo $tr->translate("N_O");?></th>
																<th width="20%"><?php echo $tr->translate("GRADE");?></th>
																<?php $s=0; ?>
																<?php  foreach ($payment_term as $value){?>
																<th width="11%"><?php echo"$value"; ?></th>			
																<?php }?>
																<th width="25%"><?php echo $tr->translate("REMARK");?></th>
															</tr>
														</thead>
														<tbody id="table_row">
														</tbody>
													</table>
														<?php $id=0; for($i = 0;$i < count($payment_term);$i++){ ?>
															<?php $id++;if($i==0) $term = $id; 
															else{$term.=','.$id;} ?>
														<?php }?>
														<input type="hidden" name="iden_term" id="iden_term"  value="<?php echo $term;?>" >
														<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
												</div>
											</div>
									</div>
								</div>
							</div>
						</div>
						<div class="tab-pane fade in " id="panel22" role="tabpanel">
							<div class="card-blogform">
								<div class="card-body"> 
									<div class="row"> 
										<div class="col-md-12 col-sm-12 col-xs-12">

											<div class="d-flex "> 
														<div class="settings-main-icon ">
															<i class="glyphicon glyphicon-education"></i>	
														</div> 
														<div class="col-md-10 col-sm-10 col-xs-12"> 
															<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("START_DATE_END_DATE");?></p>
														</div> 
											</div>
											<div class="col-md-12 col-sm-12 col-xs-12">
														&nbsp; 
											</div>

											<table class="collape tablesorter" id="table_term_row" style="width:100%; white-space: nowrap;border:1px solid #ddd;">
												<thead>
													<tr id="head-title1" class="head-td" align="center" style="width: 100%;">
														<td><?php echo $tr->translate("DEL");?></td>
														<td><?php echo $tr->translate("N_O");?></td>
														<td><?php echo $tr->translate("TITLE");?></td>
														<td><?php echo $tr->translate("START_DATE");?></td>
														<td><?php echo $tr->translate("END_DATE");?></td>
														<td><?php echo $tr->translate("NOTE");?></td>
													</tr>
												</thead>
												<tbody>
													<tr id="head-title1" class="head-td" align="right"></tr>
												</tbody>
											</table>
											<input type="hidden" name="identity_term" id="identity_term" dojoType="dijit.form.TextBox" value="" >
											<input type="button" label="<?php echo $tr->translate('ADD_TERM');?>" dojoType="dijit.form.Button" 
											class="button-class button-primary" iconClass="glyphicon glyphicon-sort-by-attributes" onclick="addTermRow();" />
										</div>
									</div>
								</div>
							</div>
						</div>

					</div>


	             </div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="button" onclick="alertBeforeSubmit(1);" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
					   class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-saved" />
					<input type="button" onclick="alertBeforeSubmit(2);" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
						class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-open" />
               	</div>
             </div>
		</form>
    </div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_alert" >
		<form  id='frm_alert' name='frm_alert' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" style="margin: 0 auto; width:100%">
			    <tr>
					<td align="center" style="font-size: 20px;color: red;">
						<?php echo $tr->translate("CONFIRM_SAVE");?>
					</td>
					<input type="hidden" name="save_type" id="save_type" dojoType="dijit.form.TextBox" /> 
				</tr>
				<tr>
					<td align="center">
						<input type="button"  label="<?php echo $tr->translate("CANCEL");?>" id="no" 
							dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideAlert();"/>
						<input type="button"  label="<?php echo $tr->translate("AGREE");?>" id="yes" 
							dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" onclick="checkSaveType();"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dijit.form.Textarea");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: grade_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: false,                        
		id: "grade",
		name: "grade",  
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
			grade   = dijit.byId('grade').get('value');
			if(grade==-1){
				dijit.byId("popup_grate").show();
			}else{
				addRow();
			}
		}
	}, "grade");

	 var school_option = dijit.byId('school_option');
	 school_option.on('change', function(evt) {
		 getAllGradeBySchoolOption();
	});
	 getAllGradeBySchoolOption();
});
url_getgrade = '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'getgrade'));?>';
function getAllGradeBySchoolOption(){
	dojo.query("#table_row").append("");
	$("#identity").val("");
	dijit.byId('grade').reset();
	school_option = dijit.byId('school_option').get('value');
	if(school_option=='' || school_option==-1){
		var grade_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('grade').set('store',grade_store);  
		dijit.byId('school_option').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getgrade,
		content:{
			'school_option':school_option
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('grade').set('store',grade_store);   
		},
		error: function(err) {
		}
	});
}
</script>
<script type="text/javascript">
function alertBeforeSubmit(save_type){
	if(dijit.byId('frm_fee').validate()){
		if(dijit.byId('school_option').get('value')==-1){
			dijit.byId('school_option').focus();
			return false;
		}
		if(dijit.byId('school_option').get('value')==-1){
			dijit.byId('school_option').focus();
			return false;
		}
		var identity = $('#identity').val();
		if(identity==''){
			dijit.byId("grade").focus();
			return false;
		}
		
		dijit.byId('save_type').attr('value',save_type);
		dijit.byId("popup_alert").show();
	}
}
function hideAlert(){
	dijit.byId("popup_alert").hide();
}
function checkSaveType(){
	save_type = dijit.byId('save_type').get('value');
	if(dijit.byId('frm_fee').validate()) {
		var url_submitcheck = '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'get-exitsing-fee')); ?>';
		dojo.xhrPost({
		    url: url_submitcheck,	
			form: dojo.byId("frm_fee"),		    
			load: function(data){
				hideAlert();
				if(data==0){
					if(save_type==1){
						submitDataClose();
					}else{
						submitDataAddNew();
					}
				}else{
					alert('<?php echo $tr->translate('RECORD_EXIST');?>');
				}
			},
			error:function(e){
				alert(e);
			}
		});
	}
}
function submitDataClose(){
	if(dijit.byId('frm_fee').validate()){
		condition = validateGrade();
		if(condition==false){
			alert("Please set fee to grade !!! ");
			return false;
		}
		if(dijit.byId('frm_fee').validate()) {
			dijit.byId('save_close').set('disabled',true);
			var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'add')); ?>';
			loadingBlock();
			dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("frm_fee"),		    
				load: function(data) {
					document.getElementsByClassName("overlay")[0].style.display="none";	
					alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
					window.location.href ="<?php echo $this->baseUrl();?>/accounting/fee";
				},
				error: function(e) {
				}
			});
		}
	}
}
function submitDataAddNew(){
	condition = validateGrade();
	if(condition==false){
		alert("Please set fee to grade !!! ");
		return false;
	}
	if(dijit.byId('frm_fee').validate()) {
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'add')); ?>';
		loadingBlock();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_fee"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";		
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/accounting/fee/add";
			},
			error: function(e) {
			}
		});
	}
}
function validateGrade(){
	var identity = $('#identity').val();
	if(identity==''){
		dijit.byId("grade").focus();
		return false;
	}
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		grade = dijit.byId('class_'+arrays[i]).get('value');
		if(grade==-1){
			return false;
		}
	}
}
function ResetRecordRecord() {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	if(arrays.length==1){
		deleteRecord(identity);
	}	
	else{
		for(var i=0;i<arrays.length;i++) {
			deleteRecord(arrays[i]);
		}
	}
}
var template = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow(){ 
	grade=dijit.byId("grade").get("value");
	if(grade==''){return false;}
	var iden = $("#identity").val();
	var arrays = iden.split(',');
	 if(arrays!=""){
		 for(var i=0;i< arrays.length;i++) {
			 readychoose = dijit.byId('class_'+arrays[i]).get('value');
			 if(readychoose==grade){
					alert("<?php echo $tr->translate("Choosen ready")?>");
				 	return false;
			 }
		}
	}
	var payment_term = '<?php echo count($this->payment_term);?>';
		col++;no++;
		label_grade = dijit.byId("grade").attr('displayedValue');
		template='';
		if(title!=1){
			$("#head-title").html("");    
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th><?php echo $tr->translate("GRADE");?></th>';
			<?php $s=0; ?>
			<?php  foreach ($payment_term as $value){?>
			<?php echo"temp+='<th>$value</th>';"; ?>			
			<?php }?>
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="10px" align="center">'+no+'</td>';
			template+='<td>&nbsp;'+label_grade+'<input type="hidden" dojoType="dijit.form.TextBox" required="true" id="class_'+col+'" name="class_'+col+'" value="'+grade+'" /></td>';
			column = 0;
			for(j=0;j<payment_term;j++){ column++; 
				template+='<td width="60px"><input type="text" required="true" id="fee'+col+'_'+column+'" class="fullside" name="fee'+col+'_'+column+'" value="0" dojoType="dijit.form.NumberTextBox" /></td>';
			}
			template+='<td width="100px"> <input type="text"  name="remark'+col+'" class="fullside" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/></td>';
		tmp='<tr id="row'+col+'" class="hover">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
 function filterClient(){
 }
 function deleteRecord(index){
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}

var col1= 0; var no1=0;
	var title1 = 0;
	function addTermRow() {
		col1++;no1++;
		template='';
		temp = "";
	/*
		if(title1!=1){
			temp+='<td><?php echo $tr->translate("DEL");?></td>';
			temp+='<td><?php echo $tr->translate("N_O");?></td>';
			temp+='<td><?php echo $tr->translate("TITLE");?></td>';
			temp+='<td><?php echo $tr->translate("START_DATE");?></td>';
			temp+='<td><?php echo $tr->translate("END_DATE");?></td>';
			temp+='<td><?php echo $tr->translate("NOTE");?></td>';
			dojo.query("#head-title1").append(temp);
			title1=1;
		}
		*/	
		template+='<td width="2%" align="center"><img onclick="deleteTermRecord('+col1+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td align="center" width="2%">'+no1+'</td>';
		template+='<td width="10%"><input required="1" dojoType="dijit.form.ValidationTextBox" class="fullside" id="title_'+col1+'" name="title_'+col1+'" placeholder="'+'<?php echo $tr->translate("TERM")." ";?> " value="" type="text"  ></td>';	
		template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox" value="now" class="fullside" id="startdate_'+col1+'" name="startdate_'+col1+'" value="" type="text" required="required" ></td>';	
		template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox"  value="now" class="fullside" id="enddate_'+col1+'" name="enddate_'+col1+'" value="" type="text" required="required" ></td>';	
		template+='<td width="10%"><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="remark_'+col1+'" name="remark_'+col1+'" value="" type="text"  ></td>';	
		tmp='<tr id="row_term'+col1+'">';
		tmp+="</tr>";
		dojo.query("#table_term_row").append(tmp);
		if($("#identity_term").val()!="") {
			var identity_term = $("#identity_term").val();
			$("#identity_term").val(identity_term+','+col1);
		} else {$("#identity_term").val(col1);}
		dojo.html.set(dojo.byId("row_term"+col1),template , {
		     parseContent: true,
		});
	}
	function deleteTermRecord(index) {
		var identity_term = $('#identity_term').val();
		var arrays1 = identity_term.split(',');
		for(var i=0;i<arrays1.length;i++) {
		if(arrays1[i] == index) arrays1.splice(i,1);
		}
		var strings1 = arrays1.join(',');
		$('#identity_term').val(strings1);
		dojo.query("#row_term"+index).remove();
	}
</script>