<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_FEE')); 
	$payment_term = $this->payment_term;

	//print_r($this->rows);
		
?>	

<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
</style>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'copy')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" style="margin: 0 auto;width:100%;" >
	<tr>
		<td>
		<fieldset>
					<legend align="center" style="font-size: 20px;"><strong><?php echo $tr->translate("EDIT_FEE");?></strong></legend>
					<table style="margin: 0 auto; width: 100%; background:#DFF7FD;" cellspacing="10" broder 1>
						<tr>
							<td ><?php echo $tr->translate("YEARS");?><input type="hidden" name="id" value="<?php echo $this->rs['id'];?>" /> </td>
							<td>
								<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="from_year" name="from_year"  type="text">
									<?php for($i=2016;$i<=date('Y')+1;$i++){?>
										<option value="<?php echo $i;?>" <?php if($i==$this->rs['from_academic']) echo 'selected="selected"';?> ><?php echo $i; ?></option>
									<?php }?>
								</select>
							</td>
							<td ><?php echo $tr->translate("TO");?></td>
							<td >
								<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="to_year" name="to_year" type="text">
									<?php for($i=2016;$i<=date('Y')+2;$i++){?>
										<option value="<?php echo $i;?>" <?php if($i==$this->rs['to_academic']) echo 'selected="selected"';?> ><?php echo $i; ?></option>
									<?php }?>
								</select>
							</td>
							
							<td ><?php echo $tr->translate("GENERATION");?></td>
							<td ><input dojoType="dijit.form.TextBox" class="fullside" id="generation" value="<?php echo $this->rs['generation']; ?>" name="generation"  type="text"></td>
							
							
						</tr>
						<tr>
							<td ><?php echo $tr->translate("TIME");?></td>
							<td >
								<select dojoType="dijit.form.FilteringSelect"  id="time"  class="fullside" name="time" type="text">								
										<option value="1" <?php if($this->rs['time']==1){ echo "selected='selected'";}?>>ក្រៅម៉ោង</option>
										<option value="2" <?php if($this->rs['time']==2){ echo "selected='selected'";}?>>ពេញម៉ោង</option>
								</select>
							</td>
							
							<td ><?php echo $tr->translate("BRANCH");?></td>
							<td>
								<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="branch" name="branch" type="text">								
									<option value="">Select Branch</option>
									<?php if(!empty($this->branch)){ foreach ($this->branch as $branch){?>	
										<option value="<?php echo $branch['id'];?>"<?php if($branch['id']==$this->rs['branch_id']) echo 'selected="selected"'?>><?php echo $branch['name'];?></option>
									<?php }}?>
								</select>
							</td>
							
							<td ><?php echo $tr->translate("NOTE");?></td>
							<td ><input dojoType="dijit.form.TextBox"  class="fullside" id="note" name="note"  value="<?php echo $this->rs['note']; ?>" type="text"></td>
							
						</tr>
					</table>
					
					<table class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%; background:#DFF7FD;" >
						<thead>
							<tr>
								<td colspan="8" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
								 	<?php $id=0; for($i = 0;$i < count($payment_term);$i++){ ?>
									<?php $id++;if($i==0)$term = $id;
									else{$term.=','.$id;} ?>
								<?php }?>
									<input type="hidden" name="iden_term" id="iden_term"  value="<?php echo $term;?>" >
									<input type="hidden" name="identity" id="identity"  value="" >
								 </td>
							</tr>
							<tr>
								<td colspan="8">
									<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="center" style="text-align: center;"></tr>
									</table>
								</td>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<td colspan="8" align="center">
									<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
									<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									 	iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'accounting','controller'=>"fee",'action'=>'index'),null,true); ?>';" />
									<input type="submit" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_new" dojoType="dijit.form.Button" 
								 		iconClass="dijitEditorIcon dijitEditorIconSave"/>
								</td>
							</tr>
						</tfoot>
				 </table>
		</fieldset>		
		</td>
	</tr>
</table>	
</form>

<script type="text/javascript">
function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("popup_dept").hide();
}

function ResetRecordRecord() {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	if(arrays.length==1){
		deleteRecord(identity);
	}	
	else{
		for(var i=0;i<arrays.length;i++) {
			deleteRecord(arrays[i]);
		}
	}
}
var template = '';
var faculty = '<?php echo $this->all_faculty; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			
			temp+='<th id="lbl_titlemetion"><?php echo $tr->translate("GRADE");?></th>';
			//temp+='<th id="lbl_titlemetion"><?php echo $tr->translate("SESSION");?></th>';
			<?php $s=0; ?>
			<?php  foreach($payment_term as $value){?>
			<?php echo"temp+='<th>$value</th>';"; ?>			
			<?php }?>
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="6%" align="center">'+no+'</td>';
			template+='<td><select dojoType="dijit.form.FilteringSelect"  class="fullside" id="class_'+col+'" name="class_'+col+'">'+faculty+'</select></td>';			
			//template+='<td><select dojoType="dijit.form.FilteringSelect" id="session_'+col+'" name="session_'+col+'">'+session+'</select></td>';
			
			column = 0;
			for(j=0;j<payment_term;j++){ column++;
				template+='<td ><input type="text" class="fullside" id="fee'+col+'_'+column+'" name="fee'+col+'_'+column+'" dojoType="dijit.form.NumberTextBox"  /></td>';
			}
			template+='<td> <input type="text" name="remark'+col+'"  class="fullside" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ "/><label id="subsub"></label></td>';
			
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
dojo.ready(function(){
	 //addRow();
	 initailize();
	 
});
function initailize(){
	<?php if(!empty($this->rows)){
		foreach($this->rows as $row){
	?>
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		
		temp+='<th><?php echo $tr->translate("GRADE");?></th>';
		
	<?php foreach ($payment_term as $value){?>
		<?php echo"temp+='<th>$value</th>';"; ?>			
		<?php }?>
		temp+='<th><?php echo $tr->translate("REMARK");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="50px" align="center">'+no+'</td>';
		template+='<td width="22%" ><select dojoType="dijit.form.FilteringSelect" class="fullside" id="class_'+col+'" name="class_'+col+'">'+faculty+'</select></td>';			
		column = 0;
		for(j=0;j<payment_term;j++){ column++;
			template+='<td width="11%" ><input type="text" id="fee'+col+'_'+column+'"   class="fullside" name="fee'+col+'_'+column+'" dojoType="dijit.form.NumberTextBox"  /></td>';
			
		}
		template+='<td> <input type="text"  name="remark'+col+'" class="fullside" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/></td>';
		
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	dijit.byId('class_'+col).attr('value',<?php echo $row['class_id']?>);
	dijit.byId('fee'+col+'_1').attr('value',<?php echo $row['monthly']?>);
	dijit.byId('fee'+col+'_2').attr('value',<?php echo $row['quarter']?>);
	dijit.byId('fee'+col+'_3').attr('value',<?php echo $row['semester']?>);
	dijit.byId('fee'+col+'_4').attr('value',<?php echo $row['year']?>);
	dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
	
	//dijit.byId('session_'+col).attr('value','<?php //echo $row['session_id']?>');
	
	<?php } }?>
}

 function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>