<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_FEE')); 
	$frm = $this->frm_fee;
	$payment_term = $this->payment_term;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>	
<style>
.dijitTextArea[cols].dijitTextArea[cols]{
	width: 99%;
}
select{ width:100%;}
fieldset{  background:none;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 5px; border:1px solid #ccc;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
table .set-style td, table .set-style th {
    padding: 0px;
    border: 1px solid #ccc;
}
.hover:hover{
	background:#eee;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
             <div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_FEE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
    		<script type="dojo/method" event="onSubmit">   
  			 if(this.validate()) {
				branch_id = dijit.byId('branch_id').get('value');
				if(branch_id==""){
					alert("<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>");
					dijit.byId("branch_id").focus();
					return false;
				}
				school_option = dijit.byId('school_option').get('value');
				if(school_option==""){
					alert("<?php echo $tr->translate('PLEASE_SELECT_SCHOOLOPTION');?>");
					dijit.byId("school_option").focus();
					return false;
				}
				identity = dijit.byId('identity').get('value');
				if(identity==''){
					alert('Please set fee for grade !!! ');
					return false;
				}
    			return true;
  			 }else {
    			return false;
   			 }
			</script>
    		<div class="card-box">
    			<div class="col-md-4 col-sm-4 col-xs-12">
		    		<div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("branch_id");?>
		                	<?php echo $frm->getElement("id");?>
		                </div>
	             	</div>
	             	<div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("YEARS");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
	                		<?php echo $frm->getElement("from_academic");?>
		                </div>
	             	</div>
	             	<div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE_STUDY");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
	                		<?php echo $frm->getElement("type_study");?>
		                </div>
	             	</div>
	             	<div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("IS_MULTY_STUDY");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
	                		<?php echo $frm->getElement("ismulty_study");?>
		                </div>
	             	</div>
	             	<div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TYPE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("generation");?>
		                </div>
		            </div>
		            <div class="form-group">
	                	<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("School Option");?> </label>
	                	<div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("school_option");?>
	                	</div>
	                </div>
		            <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("note");?>
		                </div>
		            </div>
		            <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("PROCESS_TYPE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<?php echo $frm->getElement("is_finished");?>
		                </div>
		            </div>
		            <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("status");?>
		                </div>
		            </div>
	            </div>
	             <div class="col-md-8 col-sm-8 col-xs-12">
		             <div class="form-group" style=" background: #d8e0e2; padding: 5px 15px; margin: 0; border: solid 1px #697996; border-radius: 2px;">
		                <label class="control-label bold col-md-2 col-sm-2 col-xs-12"><?php echo $tr->translate("GRADE");?> </label>
		                 <div class="col-md-5 col-sm-5 col-xs-12">
		                	<input id="grade" name="grade" />
		                </div>
		                 <div class="clearfix"></div>
	             	</div>
	             	<div class="form-group ">
	             		<table border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
							<thead>
								<tr id="head-title" class="head-td" align="center" style="text-align: center;">
										<th width="47px"><?php echo $tr->translate("DEL");?></th>
										<th width="50px"><?php echo $tr->translate("N_O");?></th>
										<th width="20%"><?php echo $tr->translate("GRADE");?></th>
										<?php $s=0; ?>
										<?php  foreach ($payment_term as $value){?>
											<th width="11%"><?php echo"$value"; ?></th>			
										<?php }?>
										<th width="25%"><?php echo $tr->translate("REMARK");?></th>
								</tr>
							</thead>
							<tbody id="table_row" >
							</tbody>
						</table>
						<?php $id=0; for($i = 0;$i < count($payment_term);$i++){ ?>
								<?php $id++;if($i==0)$term = $id;
								else{$term.=','.$id;} ?>
							<?php }?>
						<input type="hidden" name="iden_term" id="iden_term"  value="<?php echo $term;?>" >
						<input type="hidden" name="identity" id="identity"  value="" >
	             	</div>
	             </div>
    		</div>
    		<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
					<input type="button" onclick="submitDataClose();" label="<?php echo $tr->translate('GO_EDIT');?>" id="save_close" name="save_close" dojoType="dijit.form.Button" 
				 		iconClass="dijitEditorIcon dijitEditorIconSave"/>
               	</div>
             </div>
    	</form>
    </div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dijit.form.Textarea");
    dojo.require("dojo.data.ItemFileWriteStore");
    dojo.require('dijit.form.NumberTextBox');
    
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->grade_name));?> );
function submitDataClose(){
	condition = validateGrade();
	if(condition==false){
		alert("Please set fee to grade !!! ");
		return false;
	}
	if(dijit.byId('office_receipt').validate()) {
		dijit.byId('save_close').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'edit')); ?>';
		loadingBlock();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";	
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/accounting/fee";
			},
			error: function(e) {
			}
		});
	}
}
function validateGrade(){
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		grade = dijit.byId('class_'+arrays[i]).get('value');
		if(grade==-1){
			return false;
		}
	}
}
function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("popup_dept").hide();
}
function ResetRecordRecord() {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	if(arrays.length==1){
		deleteRecord(identity);
	}	
	else{
		for(var i=0;i<arrays.length;i++) {
			deleteRecord(arrays[i]);
		}
	}
}
var template = '';
var gradeoption = '<?php echo $this->all_grade; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';
var col = 0;
var no = 0;
var title = 1;
tmp = '';
temp='';
function addRow() {
	grade=dijit.byId("grade").get("value");
	if(grade==''){return false;}
	var iden = $("#identity").val();
	var arrays = iden.split(',');
	 if(arrays!=""){
		 for(var i=0;i< arrays.length;i++) {
			 readychoose = dijit.byId('class_'+arrays[i]).get('value');
			 if(readychoose==grade){
					alert("<?php echo $tr->translate("Choosen ready")?>");
				 return false;
			 }
		}
	}
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th><?php echo $tr->translate("GRADE");?></th>';
			<?php  foreach($payment_term as $value){?>
			<?php echo"temp+='<th>$value</th>';"; ?>			
			<?php }?>
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			label_grade = dijit.byId("grade").attr('displayedValue');
			template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="50px" align="center">'+no+'</td>';
			template+='<td width="20%">&nbsp;'+label_grade+'<input type="hidden" dojoType="dijit.form.TextBox" required="true" id="class_'+col+'" name="class_'+col+'" value="'+grade+'" /></td>';
			column = 0;
			for(j=0;j<payment_term;j++){ column++;
				template+='<td width="11%"><input type="text" value="0" required="true" class="fullside" id="fee'+col+'_'+column+'" name="fee'+col+'_'+column+'" dojoType="dijit.form.NumberTextBox"  /></td>';
			}
			template+='<td width="25%"> <input type="text" name="remark'+col+'"  class="fullside" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ "/><label id="subsub"></label></td>';
			
		tmp='<tr id="row'+col+'" class="hover">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
dojo.ready(function(){
	 new dijit.form.FilteringSelect({
			store: grade_store,
			queryExpr: "*${0}*",
			autoComplete: false,   
			required:false,                     
			id: "grade",
			name: "grade",  
			class: 'fullside',  
			placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
			onChange: function() {  
				make_id = dijit.byId('grade').get('value');
				grade   = dijit.byId('grade').get('value');
				if(grade==-1){
					dijit.byId("popup_grate").show();
				}else{
					addRow();
				}
			}
		}, "grade");

	 var school_option = dijit.byId('school_option');
	 school_option.on('change', function(evt) {
		 getAllGradeBySchoolOption();
	});
	getAllGradeBySchoolOption();
});

url_getgrade = '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'getgrade'));?>';
var oldSchoolOption = '<?php echo $this->rs['school_option'];?>';
function getAllGradeBySchoolOption(){
	dojo.query("#table_row").append("");
	$("#identity").val("");
	dijit.byId('grade').reset();
	school_option = dijit.byId('school_option').get('value');
	if(school_option=='' || school_option==-1){
		var grade_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('grade').set('store',grade_store);  
		dijit.byId('school_option').focus();
		return false;
	}
	if(oldSchoolOption==school_option){
		initailize();
	}
	dojo.xhrPost({
		url: url_getgrade,
		content:{
			'school_option':school_option
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('grade').set('store',grade_store);   
		},
		error: function(err) {
		}
	});
}
function initailize(){
	<?php if(!empty($this->rows)){
		foreach($this->rows as $row){
	?>
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th ><?php echo $tr->translate("GRADE");?></th>';
		<?php  foreach ($payment_term as $value){?>
		<?php echo"temp+='<th>$value</th>';"; ?>			
		<?php }?>
		temp+='<th><?php echo $tr->translate("REMARK");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="47px" align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="50px" align="center">'+no+'</td>';
		template+='<td width="20%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" <?php if($this->rs['is_finished']==1){ echo "readOnly";}?> class="fullside" id="class_'+col+'" name="class_'+col+'">'+gradeoption+'</select></td>';			
		column = 0;
		for(j=0;j<payment_term;j++){ column++;
			template+='<td width="11%"><input type="text" id="fee'+col+'_'+column+'" <?php if($this->rs['is_finished']==1){ echo "readOnly";}?> class="fullside" name="fee'+col+'_'+column+'" dojoType="dijit.form.NumberTextBox"  /></td>';
		}
		template+='<td width="25%"> <input type="text" class="fullside" <?php if($this->rs['is_finished']==1){ echo "readOnly";}?> name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /></td>';
	tmp='<tr id="row'+col+'" class="hover">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	dijit.byId('class_'+col).attr('value',<?php echo $row['class_id']?>);
	dijit.byId('fee'+col+'_1').attr('value',<?php echo $row['monthly']?>);
	dijit.byId('fee'+col+'_2').attr('value',<?php echo $row['quarter']?>);
	dijit.byId('fee'+col+'_3').attr('value',<?php echo $row['semester']?>);
	dijit.byId('fee'+col+'_4').attr('value',<?php echo $row['year']?>);
	dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
	<?php } }?>
}
function filterClient(){
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
</script>
