<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_expense;
?>
<title><?php echo $tr->translate("ADD_CHANGE_PRODUCT")?></title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
 </script>
<div class="card">
	<div class="card-content collapse show">
		<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'changeproduct','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					savenew = dijit.byId('savenew').get('value');
					saveclose = dijit.byId('saveclose').get('value');
					alert("save new :"+savenew);
					alert("save close :"+saveclose);
					return false;
					// dijit.byId('saveclose').set('disabled',true);
					// dijit.byId('savenew').set('disabled',true);
					//return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
	             <div class="col-sm-12 border-botom">
			    	<div class="col-sm-8 pd-0">
			    		<h4 class="m-b-0"><i class="fa fa-random" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_CHANGE_PRODUCT');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box mb-10">
	        	<div class="col-md-4 col-sm-4 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RECEIPT");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input style="color:red;" type="text" name="receipt_no" id="receipt_no" readonly="readonly" dojoType="dijit.form.TextBox" class="fullside" />
	                   </div>
	                </div>
	           </div>
	           <div class="col-md-4 col-sm-4 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STUDENT_ID");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select name="stu_id" id="stu_id" class="fullside" queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="setID(1);" >
								<option value="-1"><?php echo $tr->translate("SELECT_STUDENT_ID")?></option>
								<?php if(!empty($this->stu_code)){foreach ($this->stu_code as $stu_code){?>
									<option value="<?php echo $stu_code['id']?>"><?php echo $stu_code['stu_code']?></option>
								<?php }}?>
							</select>
	                   </div>
	                </div>
	           </div>
	           <div class="col-md-4 col-sm-4 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STUDENT_NAME");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select name="stu_name" id="stu_name" class="fullside" queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="setID(2);" >
								<option value="-1"><?php echo $tr->translate("SELECT_STUDENT_NAME")?></option>
								<?php if(!empty($this->stu_name)){foreach ($this->stu_name as $stu_name){?>
									<option value="<?php echo $stu_name['id']?>"><?php echo $stu_name['name']?></option>
								<?php }}?>
							</select>
	                   </div>
	                </div>
	           </div>
	           <div class="clearfix"></div>
	       </div>
	       <div class="card-box">
	        	<div class="col-md-12 col-sm-12 col-xs-12">
	        		<table id="table_row" border="1" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;width:100%;">
						<tr id="head-title" class="head-td" align="right"></tr>
					</table>
	        	</div>
	        	<div class="col-md-12 col-sm-12 col-xs-12">
	        		<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" />
	        		<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
						 	   iconClass="dijitIconEditProperty" onclick="addRow();" />
	        	</div>
	       </div>
	       <div class="card-box">
	       		<div class="form-group">
		        	<div class="col-md-6 col-sm-6 col-xs-12">
		        	</div>
		        	<div class="col-md-3 col-sm-3 col-xs-12">
		        		<?php echo $tr->translate("TOTAL_PAYMENT")?>
		        	</div>
		        	<div class="col-md-3 col-sm-3 col-xs-12">
		        		<input type="text" name="total_payment" id="total_payment" readonly="readonly" dojoType="dijit.form.TextBox" class="fullside" />
		        	</div>
	        	</div>
	        	
					
	        	<div class="form-group">
		        	<div class="col-md-6 col-sm-6 col-xs-12">
		        	</div>
		        	<div class="col-md-3 col-sm-3 col-xs-12">
		        		<?php echo $tr->translate("CREDIT_MEMO")?>
		        	</div>
		        	<div class="col-md-3 col-sm-3 col-xs-12">
		        		<input type="text" name="credit_memo" id="credit_memo" readonly="readonly" dojoType="dijit.form.TextBox" class="fullside" />
		        	</div>
	        	</div>
	        </div>
	        <div class="card-box">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
						iconClass="dijitIconClear"/>
					<input type="button" onclick="submitDataClose();" label="<?php echo $tr->translate("SAVE_CLOSE");?>" id='saveclose' name='saveclose' value='1' dojoType="dijit.form.Button"
						iconClass="dijitIconDelete"/>
					<input type="button" onclick="submitDataNew();" label="<?php echo $tr->translate("SAVE_NEW");?>" id='savenew' name='savenew' value='2' dojoType="dijit.form.Button"
						iconClass="dijitIconNewTask"/>
					<input type="button" onclick='printSave("");' label="<?php echo $tr->translate("PRINT")?>" name='print' value='print' dojoType="dijit.form.Button"
						iconClass="dijitIconNewTask"/>
               	</div>
            </div>
		</form>
	</div>
</div>


<div class="dijitHidden" style="padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:21cm;height: 15cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("CHANGE_PRODUCT");?>'" id="terms" >
		<div id="printexpense" style="width: 19cm !important; height: 11cm ; padding: 0px; margin-bottom:30px; ">
			<table width="100%"  class="print" cellspacing="0"  cellpadding="0" style=" font-family: 'Khmer OS Battambang' !important; height:10cm; font-size:11px !important; margin-top: -10px;white-space:nowrap;">
				
				<tr height="90px;">
					<td colspan="10"  style="" align="center" valign="top">
						<?php echo $this->header?>
					</td>
				</tr>
				<tr>
				    <td colspan="10"  style="" align="center">
						<table width="100%" style="font-size: 10px;margin-top: -20px;">
							<tr>
								<td width="30%">
								</td>
								<td width="40%" align="center" valign="top" style="">
									<div style="font-size: 16px;font-family: khmer OS Muol Light;">ប័ណ្ណប្តូរផលិតផល</div> 
								</td>
								<td width="30%">&nbsp;
									
								</td>
							</tr>
						</table>
				    </td>
				</tr>
				
				<style>
					.value{font-weight:bold;}
				</style>
				
				<tr>
					<td colspan="10"> 
						<table width="100%" border="0" style="font-family: Khmer OS Battambang,Times New Roman;font-size:14px;white-space:nowrap;margin-top:0px;line-height: 17px;border-collapse:collapse;">
							<tr >
								<td width="10%"></td>
								<td width="20%"></td>
								<td width="15%"></td>
								<td width="30%"></td>
								<td width="15%"></td>
								<td width="10%"></td>
							</tr>
							<tr >
								<td>Student ID</td>
								<td > :&nbsp; <label class="value" id="lb_stu_code"></label> </td>
								<td align="center">Student Name</td>
								<td > :&nbsp; <label class="value" id="lb_stu_name"></label> </td>
								<td align="center">Receipt N<sup>o</sup></label></td>
								<td >:&nbsp; <label class="value" id="lb_receipt_no"></label></td>
							</tr>
							
							<tr>
								<td colspan="10">
									<div id="t_amountmoneytype"></div>
								</td>
							</tr>
							<tr>
								<td colspan="6" >
									<table width="100%" style="font-family:Khmer OS Battambang,Times New Roman;font-size:14px; line-height:20px;">
										<tr>
											<td width="20%"></td>
											<td width="20%"></td>
											<td width="15%"></td>
											<td width="15%"></td>
											<td width="15%"></td>
											<td width="15%"></td>
										</tr>
										
										<tr>
											<td colspan="4"></td>
											<td>
												<div style="">Total Payment</div>
											</td>
											<td>
												<div style="width:100%;font-weight: bold;">: &nbsp;<label id="lb_total_payment"> </label></div>
											</td>
										</tr>
										
										
										<tr>
											<td colspan="4"></td>
											
											<td>
												<div style="">Credit Memo</div>
											</td>
											<td>
												<div style="width:100%;font-weight: bold;">: &nbsp;<label id="lb_credit_memo"> </label></div>
											</td>
										</tr>
										
										
										<tr>
											<td colspan="4">
												<table width="100%" style="white-space:nowrap;font-family:Khmer OS Battambang,Times New Roman;font-size:14px;margin-top:-10px;">
													<tr style="text-align:center;">
														<td width="35%">Cashier</td>
														<td width="35%">Customer</td>
														<td width="30%">Verified By</td>
													</tr>
													
													<tr style="text-align:center;">
														<td colspan="3">&nbsp;</td>
													</tr>
													
													<tr style="text-align:center;">
														<td>
															<div style="font-weight:bold;color:#000; font-size: 14px;margin-top:-10px;"> 
																<?php 
																   $session_user=new Zend_Session_Namespace(SYSTEM_SES);
																   $last_name=$session_user->last_name;
																   $username = $session_user->first_name;
																   echo"".$last_name." ".$username;
																?>
															</div>
															<div style="margin-top:-5px;font-size:10px;"><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?></div>
														</td>
														
														<td></td>
														<td></td>
													</tr>
													
												</table>
											</td>
											<td colspan="2"></td>
										</tr>
									</table>
								</td>
							</tr>
							
						</table>
					</td>
				</tr>
			</table>
		</div>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				 type="button" onclick="doPrintInvoice();"><?php echo $tr->translate("SAVE_PRINT");?></button>
	</div>
</div>

<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.store.Memory");
dojo.ready(function(){
	getReceiptNumber("");
	addRow();
});


function printSave(new_receipt){	
	if(dijit.byId('office_receipt').validate()) {
		if(new_receipt==''){
			getReceiptNumber(1);
		}else{
			dojo.byId("lb_receipt_no").innerHTML = new_receipt;
		}	
		
		dojo.byId("lb_stu_code").innerHTML = dijit.byId("stu_id").attr('displayedValue');
		dojo.byId("lb_stu_name").innerHTML = dijit.byId("stu_name").attr('displayedValue');
		
		dojo.byId("lb_total_payment").innerHTML = '$ ' + dijit.byId("total_payment").get('value');
		dojo.byId("lb_credit_memo").innerHTML = '$ ' + dijit.byId("credit_memo").get('value');
		
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		template="";
			 temp='<table align="center" border="1" style="margin-top:10px; width: 100%;border:1px solid #000; border-collapse: collapse;font-family: Khmer OS Battambang;color:#000;font-size:14px; " id="table">'
				  temp+='<tr style=" font-size:14px; text-align:center; height:25px;background:#eeebeb;">';
				  temp+='<td style="border:1px solid #000;"><strong>No</strong></td>';
				  temp+='<td style="border:1px solid #000;"><strong>Old Product</strong></td>';
				  temp+='<td style="border:1px solid #000;"><strong>Unit Price</strong></td>';
				  temp+='<td style="border:1px solid #000;"><strong>Qty</strong></td>';
				  temp+='<td style="border:1px solid #000;"><strong>Total</strong></td>';
				                                          
				  temp+='<td style="border:1px solid #000;"><strong>New Product</strong></td>';
				  temp+='<td style="border:1px solid #000;"><strong>Unit Price</strong></td>';
				  temp+='<td style="border:1px solid #000;"><strong>Qty</strong></td>';
				  temp+='<td style="border:1px solid #000;"><strong>Total</strong></td>';
				                                          
				  temp+='<td style="border:1px solid #000;"><strong>Different</div></strong></td>';
				  temp+='<td style="border:1px solid #000;"><strong>Note</div></strong></td>';
				  
				  temp+='</tr>';
				  n=0;
				i=1;for(var n = 0; n < rowIDArray.length; n++) {
				  temp+='<tr align="center" style="font-size:12px;height: 23px;border:1px solid #000;"​ >';
					  temp+='<td align="center" >'+i+'</td>';
					  temp+='<td >'+dijit.byId("product_old_"+rowIDArray[n]).attr('displayedValue')+'</td>'; 
					  temp+='<td >'+'$ '+dijit.byId("price_old_"+rowIDArray[n]).attr('displayedValue')+'</td>';
					  temp+='<td >'+dijit.byId("qty_old_"+rowIDArray[n]).get('value')+'</td>';
					  temp+='<td >'+'$ '+dijit.byId("total_old_"+rowIDArray[n]).get('value')+'</td>';
					  
					  temp+='<td >'+dijit.byId("product_new_"+rowIDArray[n]).attr('displayedValue')+'</td>'; 
					  temp+='<td >'+'$ '+dijit.byId("price_new_"+rowIDArray[n]).attr('displayedValue')+'</td>';
					  temp+='<td >'+dijit.byId("qty_new_"+rowIDArray[n]).get('value')+'</td>';
					  temp+='<td >'+'$ '+dijit.byId("total_new_"+rowIDArray[n]).get('value')+'</td>';
					  
					  temp+='<td >'+'$ '+dijit.byId("total_diff_"+rowIDArray[n]).get('value')+'</td>';
					  temp+='<td >'+dijit.byId("remark"+rowIDArray[n]).get('value')+'</td>';
				  i++;
				  temp+='</tr>';
				}
				for(row = n+1;row<=6;row++){
					temp+='<tr style=" font-size:12px;height: 25px;"​ align="center"><td align="center" style="border:1px solid #000;">'+row+'</td>';
						temp+='<td>&nbsp;&nbsp;</td>'; 
						temp+='<td></td>';
						temp+='<td></td>';
						temp+='<td></td>';
						temp+='<td></td>';
						temp+='<td></td>';
						temp+='<td></td>';
						temp+='<td></td>';
						temp+='<td></td>';
						temp+='<td></td>';
					temp+='</tr>';
				}
			temp+='</table>';
		dojo.byId('t_amountmoneytype').innerHTML = temp;
		dijit.byId("terms").show();	
	}
}


function setID(type){
	if(type==1){
		stu_id = dijit.byId('stu_id').get('value');
		dijit.byId('stu_name').attr('value',stu_id);
	}else{
		stu_id = dijit.byId('stu_name').get('value');
		dijit.byId('stu_id').attr('value',stu_id);
	}
}


function hideDialog(){
	dijit.byId('terms').hide();
}

var url_get_recceipt_number = "<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-receipt-no')); ?>";
function getReceiptNumber(receipt){
	dojo.xhrPost({
		url:url_get_recceipt_number,
		content:{
			//'branch_id':dijit.byId('branch_id').get('value')
			},
		handleAs:"json",
		load: function(data) {
			 dijit.byId('receipt_no').attr('value',data);
			 if(receipt!=''){
				 printSave(data);
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}

var template = '';
var service = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th><?php echo $tr->translate("PRODUCT_OLD");?></th>';
			temp+='<th><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th><?php echo $tr->translate("QTY");?></th>';
			temp+='<th><?php echo $tr->translate("TOTAL");?></th>';

			temp+='<th><?php echo $tr->translate("PRODUCT_NEW");?></th>';
			temp+='<th><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th><?php echo $tr->translate("QTY");?></th>';
			temp+='<th><?php echo $tr->translate("TOTAL");?></th>';

			temp+='<th><?php echo $tr->translate("DIFFERENT");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
	    }
		template+='<td width="20px" align="center"><img onclick="deleteRecord('+col+');calculateTotal('+col+');calculatePaidAmount('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="20px" align="center">'+no+'</td>';
		template+='<td width="20%"><input style="width:10px;" type="hidden" name="old_pro_type_'+col+'" id="old_pro_type_'+col+'" dojoType="dijit.form.TextBox"  /> ';
		template+='<input style="width:10px;" type="hidden" name="old_pro_id_'+col+'" id="old_pro_id_'+col+'" dojoType="dijit.form.TextBox"  /> ';
		
		template+='<select onchange="getProductPrice('+col+',1);"   queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" class="fullside" id="product_old_'+col+'" name="product_old_'+col+'">';
		template+='<option value=""><?php echo $tr->translate("SELECT_PRODUCT")?></option>';
					<?php if(!empty($this->all_product)){foreach($this->all_product as $product){?>
						template+='<option value="'+<?php echo $product['id']?>+'"><?php echo $product['name'];?></option>';
					<?php }}?>
		template+='</select></td>';	

		template+='<td width="7%"><input type="text" name="price_old_'+col+'" id="price_old_'+col+'" readonly="readonly" class="fullside" dojoType="dijit.form.NumberTextBox" /></td>';
		template+='<td width="5%"><input type="text" onkeyup="calculateTotal('+col+',1);" name="qty_old_'+col+'" id="qty_old_'+col+'" class="fullside" value="1" dojoType="dijit.form.NumberTextBox" /></td>';
		template+='<td width="8%"><input type="text" name="total_old_'+col+'" id="total_old_'+col+'" readonly="readonly" class="fullside" dojoType="dijit.form.NumberTextBox" /></td>';			

		
		template+='<td width=20%"><input style="width:10px;" type="hidden" name="new_pro_type_'+col+'" id="new_pro_type_'+col+'" dojoType="dijit.form.TextBox"  />';
		template+='<input style="width:10px;" type="hidden" name="new_pro_id_'+col+'" id="new_pro_id_'+col+'" dojoType="dijit.form.TextBox"  /> ';
		template+='<select class="fullside" onchange="getProductPrice('+col+',2);"   queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" id="product_new_'+col+'" name="product_new_'+col+'">';
		template+='<option value=""><?php echo $tr->translate("SELECT_PRODUCT")?></option>';
					<?php if(!empty($this->all_product)){foreach($this->all_product as $product){?>
						template+='<option value="'+<?php echo $product['id']?>+'"><?php echo $product['name'];?></option>';
					<?php }}?>
		template+='</select></td>';	
		
		template+='<td width="7%"><input type="text" name="price_new_'+col+'" id="price_new_'+col+'" readonly="readonly" class="fullside" dojoType="dijit.form.NumberTextBox" /></td>';
		template+='<td width="5%"><input type="text" onkeyup="calculateTotal('+col+',2);" name="qty_new_'+col+'" id="qty_new_'+col+'" class="fullside" value="1" dojoType="dijit.form.NumberTextBox" /></td>';
		template+='<td width="8%"><input type="text" name="total_new_'+col+'" id="total_new_'+col+'" readonly="readonly" class="fullside" dojoType="dijit.form.NumberTextBox" /></td>';	

		template+='<td width="10%"><input type="text" name="total_diff_'+col+'" id="total_diff_'+col+'" readonly="readonly" class="fullside" dojoType="dijit.form.NumberTextBox" /></td>';			
		template+='<td width="10%"><input type="text" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox"  class="fullside" /></td>';


		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }

var url_get_product_price = "<?php echo $this->url(array('module'=>'registrar','controller'=>'changeproduct','action'=>'get-product-price')); ?>";
function getProductPrice(index,type){
	if(type==1){
		pro_id = dijit.byId('product_old_'+index).get('value');
	}else{
		pro_id = dijit.byId('product_new_'+index).get('value');
	}
	dojo.xhrPost({
		url:url_get_product_price,
		content:{
			'pro_id':pro_id
			},
		handleAs:"json",
		load: function(data) {
			if(type==1){
				dijit.byId('price_old_'+index).attr('value',data.price);
				dijit.byId('old_pro_type_'+index).attr('value',data.pro_type);
				dijit.byId('old_pro_id_'+index).attr('value',data.pro_id);
				
			}else{
				dijit.byId('price_new_'+index).attr('value',data.price);
				dijit.byId('new_pro_type_'+index).attr('value',data.pro_type);
				dijit.byId('new_pro_id_'+index).attr('value',data.pro_id);
			}
			
			calculateTotal(index,type);				

		},
		error: function(err) {
			alert(err);
		}
	});
	
}
 
function submitDataClose(){
	if(dijit.byId('office_receipt').validate()) {
		dijit.byId('saveclose').set('disabled',true);
		
		var url_submit = '<?php echo $this->url(array('module'=>'registrar','controller'=>'changeproduct','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";		
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				alert(data);
				
				window.location.href ="<?php echo $this->baseUrl();?>/registrar/changeproduct";
			},
			error: function(e) {
			}
		});
	}
}

function submitDataNew(){
	if(dijit.byId('office_receipt').validate()) {
		dijit.byId('savenew').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'registrar','controller'=>'changeproduct','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";		
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				
				window.location.href ="<?php echo $this->baseUrl();?>/registrar/changeproduct/add";
			},
			error: function(e) {
			}
		});
	}
}

function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
function doPrintInvoice() {
	window.frames["print_frame"].document.body.innerHTML = dojo.byId('printexpense').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    $('#office_receipt').submit();
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
	netTotal();
}

function calculateTotal(index,type){
	if(type==1){
		price = dijit.byId('price_old_'+index).get('value');
		price = isNaN(price)?0:price;
		
		qty = dijit.byId('qty_old_'+index).get('value');
		qty = isNaN(qty)?0:qty;
		
		dijit.byId('total_old_'+index).attr('value',price * qty);
		
	}else{
		price = dijit.byId('price_new_'+index).get('value');
		price = isNaN(price)?0:price;
		
		qty = dijit.byId('qty_new_'+index).get('value');
		qty = isNaN(qty)?0:qty;
		
		dijit.byId('total_new_'+index).attr('value',price * qty);
	}
	
	calculateDifferent(index);
}

function calculateDifferent(index){
	old_total = dijit.byId('total_old_'+index).get('value');
	old_total = isNaN(old_total)?0:old_total;
	
	new_total = dijit.byId('total_new_'+index).get('value');
	new_total = isNaN(new_total)?0:new_total;
	
	dijit.byId('total_diff_'+index).attr('value',new_total - old_total);
	netTotal();
}

function netTotal(){
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += dijit.byId('total_diff_'+rowIDArray[n]).get('value');
	}
	if(netTotal>0){
		dijit.byId('credit_memo').attr('value',0);
		dijit.byId('total_payment').attr('value',netTotal);
	}else if(netTotal<0){
		dijit.byId('total_payment').attr('value',0);
		dijit.byId('credit_memo').attr('value',abs(netTotal));
	}else{
		dijit.byId('total_payment').attr('value',0);
		dijit.byId('credit_memo').attr('value',0);
	}
}
</script>

<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>

