<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("gradingsystem"));
$frm = $this->frm;
?>
<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
   <table>
	  <tr> 
		   <td><?php echo $frm->getElement("adv_search");?></td>
		   <td> <?php echo $frm->getElement("start_date");?></td>
           <td><?php echo $frm->getElement("end_date");?></td>
		   <td><?php echo $frm->getElement('search_status');?></td>
		   <td> <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   	  </tr>
   </table>
</form>
<?php echo $this->list;
$urlDelete = $this->baseUrl()."/mobileapp/gradingsystem/delete/id/";
?>
<script>
var row=0;
var url="";
var indexkey="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="delete"){
				url='<?php echo $urlDelete;?>';
			}
			gotoAction();
		},
		items: {
			"delete": {name: "<?php echo $tr->translate("DELETE");?>", icon: "delete", accesskey: "e"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	if(indexkey=='delete'){
	    if (confirm("<?php echo $tr->translate("Do you want to delete this record ?");?>")) {
	    	window.location.href = url+row;
	    } else {
	    	 return false;
	    }
	}else{
	 	window.open(url+row, '_blank');
	}
}
</script>