<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("contact"));
$frm = $this->frm;
$countlang = count($this->lang);

$row = $this->contact;
$id = $row['id'];
$db = new Mobileapp_Model_DbTable_DbContact();
?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    dojo.require('dijit.form.Textarea');
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-volume-control-phone" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('contact');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
    		</div>
    	</div>
    	<form action="" method="post" enctype="application/x-www-form-urlencoded" >
	    	<div class="card-box">
	    		<div class="col-md-8 col-sm-8 col-xs-12">
	        		<?php if ($countlang>1){?>
				    	<div class="card-box">
				    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
				    		 	<?php $alias=''; foreach($this->lang as $key=> $rs){
			                      	$alias = str_replace(' ','',$rs['title']);?>
					            <li class="nav-item <?php if ($key<1){echo "active";}?>">
					                <a class="nav-link " data-toggle="tab" href="<?php echo "#".$alias;?>" role="tab"><i class="fa fa-flag ml-2"></i> <?php echo $tr->translate(strtoupper($rs['title']));?></a>
					            </li>
					            <?php }?>
					        </ul>
					    </div>
					    <?php }?>
					    <?php if ($countlang>1){?>
					    <div class="col-md-12">
					        <!-- Tab panels -->
					        <div class="tab-content vertical">
					         <?php $alias=''; foreach($this->lang as $key=> $rs){
			                      	$alias = str_replace(' ','',$rs['title']);
			                      	$lang = $db->getArticleTitleByLang($id, $rs['id']);
			                  ?>
						        <!--Panel <?php echo $key+1?>-->
						        <div class="tab-pane fade <?php if ($key<1){echo "active in";}?>" id="<?php echo $alias;?>" role="tabpanel">
						        	<div class="col-md-12 col-sm-12 col-xs-12">
						                <div class="form-group">
						                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>
						                   </label>
						                   <div class="col-md-7 col-sm-7 col-xs-12">
						                   		<input   type="text" dojoType="dijit.form.ValidationTextBox" required="required" name="title<?php echo str_replace(' ','',$rs['title']);?>"  id="title<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['title']?>" class="fullside" placeholder="<?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>" />
						                  		<input type="hidden" dojoType="dijit.form.TextBox" name="iddetail<?php echo str_replace(' ','',$rs['title']);?>"  id="iddetail<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['id'];?>" class="fullside" />
						                   </div>
						                </div>
						                <div class="form-group">
						                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate('ADDRESS_'.strtoupper($rs['title']))?><span class="required">*</span>
						                   </label>
						                   <div class="col-md-12 col-sm-12 col-xs-12">
						                 	  <textarea class="ckeditor"   style="min-height:400px; height:400px;" id="description<?php echo str_replace(' ','',$rs['title']);?>" name="description<?php echo str_replace(' ','',$rs['title']);?>"><?php echo $lang['description']?></textarea>
						                   </div>
						                </div>
						          	</div>
						          	
						          	
						        </div>
						        <!--/ Panel <?php echo $key+1?>-->
						        <?php }?>
						   </div>
						</div>
						<?php }else{?>
						<div class="col-md-12">
								 <?php $alias=''; foreach($this->lang as $key=> $rs){
			                      	$alias = str_replace(' ','',$rs['title']);
			                      	$lang = $db->getArticleTitleByLang($id, $rs['id']);
			                  ?>
						        	<div class="col-md-12 col-sm-12 col-xs-12">
						                <div class="form-group">
						                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>
						                   </label>
						                   <div class="col-md-7 col-sm-7 col-xs-12">
						                   		<input   type="text" dojoType="dijit.form.ValidationTextBox" required="required" name="title<?php echo str_replace(' ','',$rs['title']);?>"  id="title<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['title']?>" class="fullside" placeholder="<?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>" />
						                  		<input type="hidden" dojoType="dijit.form.TextBox" name="iddetail<?php echo str_replace(' ','',$rs['title']);?>"  id="iddetail<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['id'];?>" class="fullside" />
						                   </div>
						                </div>
						                <div class="form-group">
						                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate('ADDRESS_'.strtoupper($rs['title']))?><span class="required">*</span>
						                   </label>
						                   <div class="col-md-12 col-sm-12 col-xs-12">
						                 	  <textarea class="ckeditor"   style="min-height:400px; height:400px;" id="description<?php echo str_replace(' ','',$rs['title']);?>" name="description<?php echo str_replace(' ','',$rs['title']);?>"><?php echo $lang['description']?></textarea>
						                   </div>
						                </div>
						          	</div>
						        <?php }?>
						</div>
						<?php }?>
	            </div>
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	                <!-- 
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php //echo $tr->translate("TITLE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" value="<?php //echo $row['title']?>"  name="title" id="title" dojoType="dijit.form.TextBox" class="fullside"  />
	                   </div>
	                </div>
	                 -->
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Latitude");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="hidden" dojoType="dijit.form.TextBox" name="id"  id="id" value="<?php echo $row['id'];?>" class="fullside" />
	                   		<input type="text" value="<?php echo $row['latitude']?>"  name="latitude" id="latitude" dojoType="dijit.form.TextBox" class="fullside"  />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Longitude");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" value="<?php echo $row['longitude']?>"  name="longitude" id="longitude" dojoType="dijit.form.TextBox" class="fullside"  />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PHONE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" value="<?php echo $row['phone']?>"  name="phone" id="phone" dojoType="dijit.form.TextBox" class="fullside"  />
	                   </div>
	                </div>
	                <!-- 
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php //echo $tr->translate("ADDRESS");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input style="min-height: 80px;" type="text" value="<?php //echo $row['address']?>"  name="address" id="address" dojoType="dijit.form.Textarea" class="fullside"  />
	                   </div>
	                </div>
	                 -->
	            </div>
	       </div>
	       <div class="clearfix"></div>
		    <div class="card-box">
               	<div class="col-md-6 col-sm-6 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate('SAVE');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
            </div>
	    </form>
    </div>
</div>