<?php 
     $url_save = $this->url(array('module'=>'accounting','controller'=>'productcategory','action'=>'add'));
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $status_view=$this->status_view;
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
     $payment_term = $this->payment_term;
     $row=$this->invoice;
?>
<style>
#table tr td{
	border:1px solid #cccccc;
	text-align: center;
}
#table tr th{
	background: #cccccc;
	border:1px solid #ddd;
}
table#table_row tr th {
    background: #3d6b82;
    padding: 5px 0;
	color:#fff;
}
</style>
<title><?php echo $this->tr->translate("EDIT_INVOICE")?></title>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_INVOICE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id="add_province" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	  			 if(this.validate()) {
            		student_id=dijit.byId("student_id").get("value");
            		if(student_id=="" || student_id==-1){
              			 alert("Please Select Student Name or Student Id");
			   			return false;
					}
					identity = dijit.byId('identity').get('value');
					if(identity==''){
						alert('Please Select service !!! ');
						addRow();
						return false;
					}

					var rowId = $('#identity').val();
    				if(rowId!=''){ 
						var rowIDArray = rowId.split(',');
						for(var n = 0; n < rowIDArray.length; n++){
							var type = dijit.byId('type_'+rowIDArray[n]).get('value');
							var service = dijit.byId('service_'+rowIDArray[n]).get('value');
							if(type=='' || service==''){
								alert("Please select type title and service title!");
								return false;
							}
						}
					}

					dijit.byId('save_new').set('disabled',true);
					dijit.byId('save_close').set('disabled',true);
					return true;
	   			}else {
				return false;
	  		 }
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_ID");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select type="text" id="student_id" name="student_id" required="true" class="fullside" dojoType="dijit.form.FilteringSelect" onchange="setname();"  >
								<option value=""><?php echo $tr->translate("SELECT_STUDENT_ID");?></option>
								<?php if(!empty($this->all_student_code)){foreach ($this->all_student_code as $student_code){?>
								<option value="<?php echo $student_code['stu_id']?>" <?php if($row['student_id']==$student_code['stu_id']) echo 'selected="selected"';?>><?php echo $student_code['stu_code']?></option>
								<?php }}?>
							</select>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select type="text" id="student_name" required="true" name="student_name" class="fullside" dojoType="dijit.form.FilteringSelect" onchange="setID();"  >
								<option value=""><?php echo $tr->translate("SELECT_STUDENT_NAME");?></option>
								<?php if(!empty($this->all_student_name)){foreach ($this->all_student_name as $student_name){?>
								<option value="<?php echo $student_name['stu_id']?>" <?php if($row['student_id']==$student_name['stu_id']) echo 'selected="selected"';?>><?php echo $student_name['name']?></option>
								<?php }}?>
							</select>
		                </div>
		             </div>
		        </div>
		        <div class="col-md-4 col-sm-4 col-xs-12">
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("INVOICE_NUMBER");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="invoice_num" name="invoice_num" value="<?php echo $row['invoice_num']?>" readonly type="text" required="required" >
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("INVOICE_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input type="text" name="invoice_date" id="invoice_date" constraints="{datePattern:'dd/MM/yyyy'}" value="<?php echo $row['invoice_date']?>" class="fullside" dojoType="dijit.form.DateTextBox"/>
		                </div>
		             </div>
		        </div>
		        <div class="col-md-4 col-sm-4 col-xs-12">
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("REMARK");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input dojoType="dijit.form.TextBox" class="fullside" id="remark" name="remark" value="<?php echo $row['remark']?>" type="text"  >
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("INPUT_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input type="text" name="input_date" id="input_date" constraints="{datePattern:'dd/MM/yyyy'}" value="<?php echo $row['input_date']?>" class="fullside" dojoType="dijit.form.DateTextBox"/>
		                </div>
		             </div>
		        </div>
		   </div>
		   <div class="card-box" >
	           <div class="form-group" style="background: #d8e0e2; padding: 5px 15px; margin: 0; border: solid 1px #697996; border-radius: 2px;">
		           <div class="col-md-3 col-sm-3 col-xs-12">
		           		 <div class="form-group">
		                   <label class="control-label  col-md-3 col-sm-3 col-xs-12" style="font-size: 16px;" ><?php echo $tr->translate("TYPE");?></label>
		                   <div class="col-md-9 col-sm-9 col-xs-12">
		                   		<select required="false" type="text" name="items_type" id="items_type"  class="fullside" dojoType="dijit.form.FilteringSelect"  autoComplete="false" queryExpr="*${0}*" onchange="getItemsDetailByType();" >
										<option value=""><?php echo $tr->translate("PLEASE_SELECT");?></option>
										<option value="1"><?php echo $tr->translate("TUITION_FEE");?></option>
										<option value="2"><?php echo $tr->translate("SERVICE");?></option>
		                   		</select>
		                   </div>
		                </div>
		           </div>
		           <div class="col-md-5 col-sm-5 col-xs-12">
		           		 <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" style="font-size: 16px;" >វគ្គសិក្សា/សេវាកម្ម</label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input id="item" name="item" />
		                   </div>
		                </div>
		           </div>
		       </div>
		  </div>
		   <div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12 mt-20 ">
					<table class="collape tablesorter" id="table_row" style="width:100%; white-space: nowrap;border:1px solid #ddd;">
					    <tr style="background:#04a2e0; color:#fff;">
						    <th width="4%"><?php echo $tr->translate("DELETE");?></th>
						    <th><?php echo $tr->translate("N_O");?></th>
						    <th><?php echo $tr->translate("TYPE");?></th>
							<th><?php echo $tr->translate("SERVICES");?></th>
							<!--  <th><?php echo $tr->translate("PRICE");?></th>-->
							
							<?php $s=0; ?>
							<?php  foreach ($payment_term as $value){?>
							<?php echo '<th>'.$value.'</th>'; ?>			
							<?php }?>
							<th><?php echo $tr->translate("START_DATE");?></th>
							<th><?php echo $tr->translate("END_DATE");?></th>
							<th><?php echo $tr->translate("REMARK");?></th>
						</tr>
					</table>
					<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
					<!-- 
					<input type="button" label="<?php //echo $tr->translate('ADD_SERVICE');?>" dojoType="dijit.form.Button" 
						iconClass="dijitIconEditProperty" onclick="addRow();" />
					 -->
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TOTLE_AMOUNT");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input dojoType="dijit.form.ValidationTextBox" readonly  class="fullside" id="totle_amount" name="totle_amount" value="<?php echo $row['totale_amount']?>" type="text" required="required" >
		                </div>
		             </div>
				</div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20 ">
	      	 	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
	      	 		<input type="reset" value="Clear" label="Clear"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
					<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVE_CLOSE");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
				    <input type="submit" value="save_new" name="save_new" id="save_new" label="<?php echo $tr->translate("SAVE_NEW");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
            	 </div>
            </div>
		</form>
	</div>
</div>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.data.ObjectStore");
item_store = getDataStorefromJSON('id','name');

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: item_store,
		autoComplete: false,
		queryExpr: "*${0}*",                     
		id: "item",
		name: "item",   
		required:false,        
		class: 'fullside', 
		onChange: function() {  
			addRow();
		}
	}, "item");

	oldRow();
});	

var url_itemsdetail = '<?php echo $this->url(array('module'=>'accounting','controller'=>'invoice','action'=>'getitemsdetail')); ?>';
function getItemsDetailByType(){
	items_type = dijit.byId("items_type").get("value");
	if(items_type==''){
		return false;
	}
	dojo.xhrPost({
		url: url_itemsdetail,
		content:{
			'items_type':items_type
			},
		handleAs:"json",
		load: function(data) {
			item_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('item').set('store',item_store);  
		},
		error: function(err) {
		}
	});
}

var col= 0; var no=0;

function oldRow(){
	 <?php if(!empty($this->invoice_service)) foreach($this->invoice_service  As $row_detail){?>
	col++;no++;
	template='';
		template+='<td width="4%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td align="center" width="2%">'+no+'</td>';
		
		template+='<td width="12%"><input type="hidden" dojoType="dijit.form.TextBox" required="true" id="type_'+col+'" name="type_'+col+'" value="<?php echo $row_detail['type']?>" /> ';
		<?php if ($row_detail['type']==1){?>
		template+= '<?php echo $tr->translate("TUITION_FEE");?>';
		<?php }else if ($row_detail['type']==2){?>
		template+= '<?php echo $tr->translate("SERVICE");?>';
		<?php }?>
	    template+='</td>';	
		
		template+='<td width="12%"> <input type="hidden" dojoType="dijit.form.TextBox" required="true" id="service_'+col+'" name="service_'+col+'" value="<?php echo $row_detail['service_id']?>" /> ';
		template+='<?php echo $row_detail['title'];?></td>';
		
		//template+='<td width="6%"><input dojoType="dijit.form.ValidationTextBox" onkeyup="calulator('+col+');" class="fullside" id="amount_'+col+'" name="amount_'+col+'" value="0" type="text" required="required" ></td>';	
		template+='<td width="6%"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator('+col+');" class="fullside" id="amount_'+col+'" name="amount_'+col+'" value="0" type="text" required="required" ></td>';	
		template+='<td width="6%"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator('+col+');" class="fullside" id="term_'+col+'" name="term_'+col+'" value="0" type="text" required="required" ></td>';
		template+='<td width="6%"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator('+col+');" class="fullside" id="semester_'+col+'" name="semester_'+col+'" value="0" type="text" required="required" ></td>';
		template+='<td width="6%"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator('+col+');" class="fullside" id="year_'+col+'" name="year_'+col+'" value="0" type="text" required="required" ></td>';
		
		template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox" value="now" class="fullside" id="startdate_'+col+'" name="startdate_'+col+'" value="" type="text" required="required" ></td>';	
		template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox"  value="now" class="fullside" id="enddate_'+col+'" name="enddate_'+col+'" value="" type="text" required="required" ></td>';	
		template+='<td width="10%"><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="remark_'+col+'" name="remark_'+col+'" value="" type="text"  ></td>';	
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);
	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	      dijit.byId('amount_'+col).set('value',<?php echo $row_detail['month']?>);
	      dijit.byId('term_'+col).set('value',<?php echo $row_detail['term']?>);
	      dijit.byId('semester_'+col).set('value',<?php echo $row_detail['semester']?>);
	      dijit.byId('year_'+col).set('value',<?php echo $row_detail['year']?>);
	      dijit.byId('startdate_'+col).set('value','<?php echo $row_detail['start_date']?>');
	      dijit.byId('enddate_'+col).set('value','<?php echo $row_detail['end_date']?>');
	      dijit.byId('remark_'+col).set('value','<?php echo $row_detail['remark']?>');
	<?php }?>
}
	
function addRow() {
		var payment_term = '<?php echo count($this->payment_term);?>';
		items_type_lable = dijit.byId("items_type").attr('displayedValue');
		items_type=dijit.byId("items_type").get("value");

		item_Label = dijit.byId("item").attr('displayedValue');
		item=dijit.byId("item").get("value");

		var iden = $("#identity").val();
		var arrays = iden.split(',');
		 if(arrays!=""){
			 for(var i=0;i< arrays.length;i++) {
				 readychoose = dijit.byId('service_'+arrays[i]).get('value');
				 if(readychoose==item){
					 alert("<?php echo $tr->translate("Choosen ready")?>");
					 return false;
				 }
			}
		}
		col++;no++;
		template='';
			template+='<td width="4%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td align="center" width="2%">'+no+'</td>';

			template+='<td width="12%"><input type="hidden" dojoType="dijit.form.TextBox" required="true" id="type_'+col+'" name="type_'+col+'" value="'+items_type+'" /> ';
			template+= items_type_lable;
		    template+='</td>';	
			
			template+='<td width="12%"> <input type="hidden" dojoType="dijit.form.TextBox" required="true" id="service_'+col+'" name="service_'+col+'" value="'+item+'" /> ';
			template+=item_Label+'</td>';
			//template+='<td width="6%"><input dojoType="dijit.form.ValidationTextBox" onkeyup="calulator('+col+');" class="fullside" id="amount_'+col+'" name="amount_'+col+'" value="0" type="text" required="required" ></td>';	
			template+='<td width="6%"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator('+col+');" class="fullside" id="amount_'+col+'" name="amount_'+col+'" value="0" type="text" required="required" ></td>';	
			template+='<td width="6%"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator('+col+');" class="fullside" id="term_'+col+'" name="term_'+col+'" value="0" type="text" required="required" ></td>';
			template+='<td width="6%"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator('+col+');" class="fullside" id="semester_'+col+'" name="semester_'+col+'" value="0" type="text" required="required" ></td>';
			template+='<td width="6%"><input dojoType="dijit.form.NumberTextBox" onkeyup="calulator('+col+');" class="fullside" id="year_'+col+'" name="year_'+col+'" value="0" type="text" required="required" ></td>';
			
			template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox" value="now" class="fullside" id="startdate_'+col+'" name="startdate_'+col+'" value="" type="text" required="required" ></td>';	
			template+='<td width="6%"><input constraints='+'{datePattern:"dd/MM/yyyy"}'+' dojoType="dijit.form.DateTextBox"  value="now" class="fullside" id="enddate_'+col+'" name="enddate_'+col+'" value="" type="text" required="required" ></td>';	
			template+='<td width="10%"><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="remark_'+col+'" name="remark_'+col+'" value="" type="text"  ></td>';	
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	
	if(arrays[i] == index) arrays.splice(i,1);
		
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
	 calulator(arrays['i']);
}
function calulator(index){
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	var amount= 0;
	for(var i=0;i<arrays.length;i++) {
		var  a =  dijit.byId("amount_"+arrays[i]).get('value');
		var  term =  dijit.byId("term_"+arrays[i]).get('value');
		var  semester =  dijit.byId("semester_"+arrays[i]).get('value');
		var  year =  dijit.byId("year_"+arrays[i]).get('value');
		amount = amount + parseFloat(a) + parseFloat(term)+ parseFloat(semester)+ parseFloat(year);
	}
	dijit.byId("totle_amount").attr('value',amount);
}
function setID(){
	stu_id = dijit.byId('student_name').get('value');
	dijit.byId('student_id').attr('value',stu_id);
}
function setname(){
	stu_id = dijit.byId('student_id').get('value');
	dijit.byId('student_name').attr('value',stu_id);
}
</script>