<?php
$request = Zend_Controller_Front::getInstance ()->getRequest ();
$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
$frm = $this->frm;
$formList = new Application_Form_Frmtable();
?>
<title><?php echo $tr->translate("INVOICE");?></title>
<meta charset="utf-8">
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-cubes " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('INVOICE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form action=" " dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<input dojoType="dijit.form.TextBox" class="fullside" id="search" name="search" value="<?php echo $this->rssearch['search'];?>" type="text" >
					 </div>
					  <div class="col-md-2 col-sm-2 col-xs-12">
					  <?php echo $frm->getElement("stu_code");?>
					 </div>
					  <div class="col-md-2 col-sm-2 col-xs-12">
					  <?php echo $frm->getElement("stu_name");?>
					 </div>
					  <div class="col-md-2 col-sm-2 col-xs-12">
					  <?php echo $frm->getElement("group");?>
					 </div>
					  <div class="col-md-2 col-sm-2 col-xs-12">
					  <?php echo $frm->getElement("degree");?>
					 </div>
					  <div class="col-md-2 col-sm-2 col-xs-12">
					  	<?php echo $frm->getElement("grade");?>
					 </div>
				</div>
				<div class="form-group">
					 <div class="col-md-2 col-sm-2 col-xs-12">
					 	<?php echo $frm->getElement("start_date");?>
					 </div>
					  <div class="col-md-2 col-sm-2 col-xs-12">
					  	<?php echo $frm->getElement("end_date");?>
					 </div>
					   <div class="col-md-2 col-sm-2 col-xs-12">
					   	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"
					showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					 </div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list; ?>
		</div>
	</div>
</div>
