<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_callteral;
echo $this->headTitle($tr->translate("EDIT_STUDY_GROUP"));
$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
</script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'edit')); ?>" 
dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
                room = dijit.byId('room').get('value');
				year=dijit.byId("academic_year").get("value");
                if(year==-1){
					alert("Please Selected Year!!!");
                    return false;
				}
    			var rowId = $('#identity').val();
				if(rowId!=''){ 
				var rowIDArray = rowId.split(',');
				for(var n = 0; n < rowIDArray.length; n++){
				var row_id = dijit.byId('subject_study_'+rowIDArray[n]).get('value');
				if(row_id==''){
						alert("Please select subject title!");
						return false;
						}
					}
				}
               if (room=='' || room==-1){
					alert('Please Select room !');
                    dijit.byId('room').focus();
			        return false;
                }
				return true;
			}else {
				return false;
			}
</script>
<table width="100%">
	<tr>
		<td>
				<fieldset style="margin-top:-13px;">
					<legend align="center" ><strong style="font-size: 18px;"><?php echo $tr->translate("EDIT_STUDY_GROUP");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;white-space:nowrap;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("GROUP_CODE")?><input type="hidden" name="id" value="<?php echo $this->rs['id'];?>" /></td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="group_code" name="group_code" value="<?php echo $this->rs['group_code'];?>" type="text"></td>
						    
						    <td><?php echo $tr->translate("YEARS")?></td>
							<td>
								<select name="academic_year" id="academic_year" placeholder="Select Year" class="fullside" type="text" dojoType="dijit.form.FilteringSelect">
									<option value="-1">select year</option>
									<?php if(!empty($this->row_year)){foreach($this->row_year as $year){?>
										<option value="<?php echo $year['id'];?>"<?php if($year['id']==$this->rs['academic_year']) echo 'selected="selected"';?>><?php echo $year['years'];?></option>
									<?php }}?>
							    </select>
							</td>
							<td><?php echo $tr->translate("SEMESTER")?></td>
							<td><input dojoType="dijit.form.ValidationTextBox" required="true" name="semester" class="fullside" value="<?php echo $this->rs['semester'];?>" type="text"></td>
						</tr>
						<tr>
							<td ><?php echo $tr->translate("DEGREE")?></td>
							<td>
								<select   name="degree" id="degree" class="fullside" dojoType="dijit.form.FilteringSelect" onchange="getallGrade(); getSubjectByDegree();">
										<?php 
										if(!empty($this->degree))foreach ($this->degree as $row){?>
										<option value="<?php echo $row['dept_id']?>" <?php if($row['dept_id']==$this->rs['degree']) echo 'selected="selected"';?> ><?php echo $row['en_name']?></option>
										<?php }?>
								</select>
							</td>
							<td style="white-space: nowrap;"><?php echo $tr->translate("GRADE")?></td>
							<td>
								<input id="grade" name="grade" class="fullside" value="<?php echo $this->rs['grade']; ?>" />
							</td>
							<td><?php echo $tr->translate("SESSION")?></td>
							<td>
								<select name="session" id="session" class="fullside" dojoType="dijit.form.FilteringSelect">
								<?php $row= new Application_Model_DbTable_DbGlobal();
								      $rows=$row->getSession();
									foreach($rows as $key =>$rs){?>
										<option value='<?php echo $rs['key_code']?>' <?php if($rs['key_code']==$this->rs['session']) echo 'selected="selected"';?>><?php echo $rs['view_name'];?></option>
								<?php 	}?>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("START_DATE")?></td>
							<td><input dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" name="start_date" id="start_date" class="fullside" onchange="setEndDate();" value="<?php echo $this->rs['start_date'];?>" type="text"></td>
							<td><?php echo $tr->translate("AMOUNT_MONTH")?></td>
							<td><input dojoType="dijit.form.NumberTextBox" class="fullside"  name="amountmonth" id="amountmonth" value="<?php echo $this->rs['amount_month'];?>" onkeyup="setEndDate();" type="text"></td>
							<td style="width: 5px;white-space: nowrap;"><?php echo $tr->translate("END_DATE")?></td>
							<td><input dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="end_date" name="end_date" type="text" value="<?php echo $this->rs['expired_date'];?>" ></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ROOM_NAME")?></td>
							<td>
								<input id="room" />
							</td>
							<td ><?php echo $tr->translate("TEACHER_ROOM")?></td>
							<td><input id="teacher_id" />
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><input dojoType="dijit.form.TextBox" class="fullside"  name="note" value="<?php echo $this->rs['note'];?>" type="text"></td>
						</tr>
						<tr>
							<td ><?php echo $tr->translate("STATUS")?></td>
							<td><select name="status" id="status" class="fullside" dojoType="dijit.form.FilteringSelect">
								    <option value="1" <?php if($this->rs['status']==1) echo 'selected="selected"';?>>ប្រើប្រាស់</option>
								    <option value="0" <?php if($this->rs['status']==0) echo 'selected="selected"';?>>មិនប្រើប្រាស់</option>
								</select>
							</td>
						</tr>
				    	<tr>
							<td colspan="4" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
								 		<input type="hidden" name="identity" id="identity"  />
							</td>
						</tr>
						<tr>
							<td colspan="6">
								<table id="table_row" border="1" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="6" align="center">
								<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
								<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'global','controller'=>"group",'action'=>'index'),null,true); ?>';" />
								<input type="submit" value="save" name="save" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>
				</fieldset>
		</td>
	</tr>
</table>
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:80%;" id="popup_teacher" >
		<form  name='frm_add_teacher' id='frm_add_teacher'  dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color:menu;">
							<legend align="center" style="font-size: 18px;"><strong><?php echo $tr->translate("ADD_TEACHER");?></strong></legend>
							<table style="margin: 0 auto; width: 95%;white-space: nowrap;" cellspacing="10">
								<tr>
									<td><?php echo $tr->translate("ID_NUMBER")?></td>
									<td><input dojoType="dijit.form.TextBox" style="color:red;" class="fullside" id="code" name="code" value="" readonly type="text"></td>
									<td><?php echo $tr->translate("KH_NAME")?></td>
									<td><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="kh_name" name="kh_name" value="" type="text"></td>
									<td><?php echo $tr->translate("EN_NAME")?></td>
									<td><input dojoType="dijit.form.TextBox" class="fullside" id="en_name" name="en_name" value="" type="text"></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("SEX")?></td>
									<td>
										<select dojoType="dijit.form.FilteringSelect" value="1" class="fullside" id="sex" name="sex" value="" type="text">
											<option value="1">Male</option>
											<option value="2">Female</option>
										</select>
									</td>
									<td><?php echo $tr->translate("DOB")?></td>
									<td>
										<input dojoType="dijit.form.DateTextBox" value="now" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" id="dob" name="dob" value="" type="text" />
									</td>
									<td><?php echo $tr->translate("NATIONALITY")?></td>
									<td><input dojoType="dijit.form.TextBox"  class="fullside" id="nationality" name="nationality" value="" type="text"></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("PHONE")?></td>
									<td><input dojoType="dijit.form.TextBox" class="fullside" id="phone" name="phone" value="" type="text"></td>
									
									<td><?php echo $tr->translate("ADDRESS")?></td>
									<td><input dojoType="dijit.form.TextBox"  class="fullside" id="address" name="address" value="" type="text"></td>
								
									<td><?php echo $tr->translate("NOTE")?></td>
									<td><input dojoType="dijit.form.TextBox"  class="fullside" id="note" name="note" value="" type="text"></td>
								</tr>
								<tr>
									<td colspan="6" align="center">
										<input type="button" onclick="addTeacher();" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
									</td>
								</tr>
							</table>	
						</fieldset>		
					</td>
				</tr>
			</table>	
			<input type="hidden"  name="tow_value" id="tow_value" value="" />
 		</form>
	</div>
</div>
<?php 
$techer= $this->frm_techer;
?>
<script type="text/javascript">
//dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require('dojox.form.BusyButton');
dojo.require("dojo.html");
var room_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->room));?> );
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->grade_name));?> );
var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->dept));?> );
var teacher_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->teacher));?> );

dojo.ready(function(){
			Initailize();
			new dijit.form.FilteringSelect({
				store: teacher_store,
				autoComplete: true,                        
				required: false,
				id: "teacher_id",
				name: "teacher_id", 
				value:"<?php echo $this->rs['teacher_id'];?>",          
				class: "fullside", 
				placeHolder:"Select Teacher",          
				onChange: function() {  
					teacher_id = dijit.byId('teacher_id').get('value');
					if(teacher_id==-1){
						$("#tow_value").val(-2)
						dijit.byId("popup_teacher").show();
					}
				}
			}, "teacher_id");
			
			new dijit.form.FilteringSelect({
				store: grade_store,
			    autoComplete: true,                        
			    id: "grade",
			    name: "grade",           
			    class: 'fullside',  
			    placeHolder:"Selected Grade",          
			    onChange: function() {  
			    	make_id = dijit.byId('grade').get('value');
			    	grade = dijit.byId('grade').get('value');
				    if(grade==-1){
				    	dijit.byId('save_grade').set('disabled',false);		
				   		dijit.byId("popup_grate").show();
				    }
			    }
			}, "grade");
			getallGrade();

			new dijit.form.FilteringSelect({
				store: room_store,
			    autoComplete: true,                        
			    id: "room",
			    name: "room", 
				class: 'fullside',				
			    placeHolder:"Select Room",          
			    onChange: function() {  
			    	room = dijit.byId('room').get('value');
			    	if(room==-1){
						dijit.byId("popup_room").show();
				    }
			    }
			}, "room");
			dijit.byId('room').attr('value','<?php echo $this->rs['room_id'];?>');
			dijit.byId('grade').attr('value','<?php echo $this->rs['grade'];?>');

			new dijit.form.FilteringSelect({
			    store: dept_store,
			    autoComplete: true,                        
			    required: true,
			    id: "degree_popup1",
			    name: "degree_popup1",           
			    class: "full height-text", 
			    placeHolder:"Select Degree",          
			    onChange: function() {  
			    	dept_id = dijit.byId('degree_popup1').get('value');
			    	if(dept_id==-1){
			    		dijit.byId("popup_add_dept").show();
				    }
			    }
			}, "degree_popup1");
		
});
function popupTeacher(index){
	teacher_id = dijit.byId('teacher_'+index).get('value');
	if(teacher_id==-1){
		$("#tow_value").val(index);
		getTeacherID();
		dijit.byId("popup_teacher").show();
	}
}
var url_get_teacher_id = '<?php echo $this->url(array("module"=>"global","controller"=>"lecturer","action"=>"get-teacher-id")); ?>';
function getTeacherID(){
	dojo.xhrPost({
		url:url_get_teacher_id,
		handleAs:"json",
		load: function(data) {
			dijit.byId('code').attr('value',data);
		},
		error: function(err) {
			alert(err);
		}
	});
}
var url_add_teacher = '<?php echo $this->url(array("module"=>"global","controller"=>"group","action"=>"add-teacher-popup")); ?>';
function addTeacher(){
	if(dijit.byId('frm_add_teacher').validate()) {
		dojo.xhrPost({
			url:url_add_teacher,
			form: dojo.byId("frm_add_teacher"),
			handleAs:"json",
			load: function(data) {
			  var Itemmake = { 
				        id: data.id,
				        name: dijit.byId('kh_name').get('value')+'-'+dijit.byId('en_name').get('value')
				         };
					index=$("#tow_value").val();
					if(index<0){
						addDataToSelectbox(dijit.byId('teacher_id'), teacher_store, Itemmake, data.id);
					}else{
						 addDataToSelectbox(dijit.byId('teacher_'+index), teacher_store, Itemmake, data.id);
					}
			  teacher_option = data.new_teacher_option;
			  dijit.byId('frm_add_teacher').reset();
			  dijit.byId("popup_teacher").hide();
			   
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}


function setEndDate(){
	amount_date = dijit.byId('amountmonth').get('value');
	release_date = dijit.byId("start_date").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		mm = a.getMonth()+amount_date+1;
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('end_date').attr('value',epx_date);	
    }
}

var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);   
			    dijit.byId('grade').attr('value',<?php echo $this->rs['grade'];?>);   
			},
			error: function(err) {
				alert(err);
			}
		});
}
var url_room = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'add-room')); ?>';
function addRoom(){
	if(dijit.byId('form_add_room').validate()){
		dojo.xhrPost({
			url:url_room,
			form: dojo.byId("form_add_room"),
			handleAs:"json",
			load: function(data) {
				var myNewItem = {					
						id: data,
						name: dijit.byId('room_name').get('value')
				};			
				addDataToSelectbox(dijit.byId('room'), room_store, myNewItem, data);
				dijit.byId('form_add_room').reset();
				hideDialog();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

var subject = '<?php echo $this->subject;?>';
var teacher_option = '<?php echo $this->teacher_option;?>';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function Initailize() {
	<?php if(!empty($this->row)){ 
		foreach ($this->row as $rows){?>
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th><?php echo $tr->translate("SUBJECT_STUDY");?></th>';
		temp+='<th><?php echo $tr->translate("NOTE");?></th>';
		temp+='<th><?php echo $tr->translate("TEACHER");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="4%" align="center">'+no+'</td>';
		template+='<td width="40%"><select dojoType="dijit.form.FilteringSelect" class="fullside" id="subject_study_'+col+'" name="subject_study_'+col+'">'+subject+'</select></td>';
		template+='<td width="23%"><input dojoType="dijit.form.TextBox" class="fullside" name="note_'+col+'" id="note_'+col+'" value="" type="text"></td>';		
		template+='<td width="24%"><select dojoType="dijit.form.FilteringSelect" onchange="popupTeacher('+col+');" class="fullside" id="teacher_'+col+'" name="teacher_'+col+'" >';
		template+=teacher_option;  
		template+='</select></td>';
		
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	dijit.byId('subject_study_'+col).attr('value','<?php echo $rows['subject_id'];?>');
	dijit.byId('note_'+col).attr('value','<?php echo $rows['note'];?>');
	dijit.byId('teacher_'+col).attr('value','<?php echo $rows['teacher'];?>');
	<?php }}?>
}

function addRow() {
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th><?php echo $tr->translate("SUBJECT_STUDY");?></th>';
		temp+='<th><?php echo $tr->translate("NOTE");?></th>';
		temp+='<th><?php echo $tr->translate("TEACHER");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="4%" align="center">'+no+'</td>';
		template+='<td width="40%"><select dojoType="dijit.form.FilteringSelect"  class="fullside" id="subject_study_'+col+'" name="subject_study_'+col+'">'+subject+'</select></td>';
		template+='<td width="23%"><input dojoType="dijit.form.TextBox" class="fullside" name="note_'+col+'" id="note_'+col+'" value="" type="text"></td>';		
		template+='<td width="24%"><select dojoType="dijit.form.FilteringSelect" onchange="popupTeacher('+col+');" class="fullside" id="teacher_'+col+'" name="teacher_'+col+'" >';
		template+=teacher_option;  
		template+='</select></td>';
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
function hideDialog(){
	dijit.byId("popup_room").hide();
}
var url_dept_subject = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getsubjectbydegree')); ?>';
function getSubjectByDegree(){
	dept_id = dijit.byId('degree').get('value');
		dojo.xhrPost({
			url:url_dept_subject,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				var identity = $('#identity').val();
				if(identity !=''){
					var arrays = identity.split(',');
					for(var i=0;i<arrays.length;i++) {
						deleteRecord(arrays[i]);
					}
					$("#identity").val("");
				}
				 tem="";
			       if(data!=""){
			    		template='';
						for(i=0;i<data.length;i++){
							col++;no++;
							template='';
							if(title!=1){
								temp+='<th><?php echo $tr->translate("DEL");?></th>';
								temp+='<th><?php echo $tr->translate("N_O");?></th>';
								temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBJECT_STUDY");?></th>';
								temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("NOTE");?></th>';
								temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("STATUS");?></th>';
								dojo.query("#head-title").append(temp);
								title=1;
							}
								template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
								template+='<td width="4%" align="center">'+no+'</td>';
								template+='<td><select style="width:100%;"  dojoType="dijit.form.FilteringSelect" class="fullside" id="subject_study_'+col+'" name="subject_study_'+col+'">'+subject+'</select></td>';
								template+='<td><input style="width:100%;" dojoType="dijit.form.TextBox" class="fullside" name="note_'+col+'" id="note_'+col+'" value="" type="text"></td>';		
								template+='<td><select dojoType="dijit.form.FilteringSelect" class="fullside" id="status_'+col+'" name="status_'+col+'" style="width:100%;"><option value="1">Active</option><option value="0">Deactive</option></select></td>';
							tmp='<tr id="row'+col+'">';
							tmp+="</tr>";
							dojo.query("#table_row").append(tmp);

							if($("#identity").val()!="") {
								var identity = $("#identity").val();
								$("#identity").val(identity+','+col);
							} else {$("#identity").val(col);}
							dojo.html.set(dojo.byId("row"+col),template , {
							     parseContent: true,
							});
							dijit.byId('subject_study_'+col).attr('value',data[i].subject_id);
							dijit.byId('note_'+col).attr('value',data[i].note);
							dijit.byId('status_'+col).attr('value',data[i].status);
						}
			       }
			},
			error: function(err) {
				alert(err);
			}
		});
}
</script>
	<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_room" >
		<form style="background-color: buttonface; " id='form_add_room' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate("ADD_NEW_ROOM")?></legend><br />
					<table style="margin: 0 auto; width: 95%;" cellspacing="5">
						<tr>
							<td style="width:100px"><?php echo $tr->translate("ROOM_NAME")?></td>
							<td><input class="fullside" tabindex="1" value="" dojoType="dijit.form.ValidationTextBox" name="room_name" id="room_name" type="text" required="required" /></td>
						</tr>
						<tr>
							<td style="width:100px"><?php echo $tr->translate("STATUS")?></td>
							<td>
								<select class="fullside"  tabindex="3" name="status_room" id="status_room" dojoType="dijit.form.FilteringSelect" >
									    <option value="1"><?php echo $tr->translate("Active")?></option>
									    <option value="0"><?php echo $tr->translate("Deactive")?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input iconClass="dijitIconUndo" type="button" value="close" label="Close" dojoType="dijit.form.Button" onclick="hideDialog();"/>
								<input type="button" value="save" name="save" label="Save" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addRoom();"/>
							</td>
						</tr>
					</table>
				</fieldset>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_add_dept" >
		<form  id='frm_add_dep' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			    <tr><td colspan="2" style="text-align:center;"><?php echo $tr->translate("ADD_FACULTY");?></td></tr>
				<tr>
					<td><?php echo $tr->translate("DEGREE");?></td>
					<td>
						<input type="text" class="fullside" name='fac_enname' id="fac_enname" dojoType="dijit.form.TextBox" />
					</td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("SHORTCUT");?></td>
					<td>
						<input type="text" class="fullside" name='shortcut_fac' id="shortcut_fac" dojoType="dijit.form.TextBox" />
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="button"  label="<?php echo $tr->translate("CANCEL");?>" id="cancelButton" 
						dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideDialogDegree()"/>
						
						<input type="button"  label="<?php echo $tr->translate("SAVE");?>" id="save_dep" 
						dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addDept();"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:40%;" id="popup_grate" >
		<form style="background-color: buttonface;" id='frm_add_grade' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate("ADD_GRADE");?></legend><br />
					<table style="margin: 0 auto; width: 95%;" cellspacing="5">
					<tr>
						<td><?php echo $tr->translate("NAME")?></td>
						<td> 
							<input dojoType="dijit.form.ValidationTextBox" required="true" class="full height-text" id="major_enname" name="major_enname" value="" type="text">
						</td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("SHORTCUT")?></td>
							<td> 
								<input dojoType="dijit.form.ValidationTextBox"  class="full height-text" id="shortcut" name="shortcut" value="" type="text">
						</td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("DEGREE")?></td>
						<td>
							<input id="degree_popup1" /> 
						</td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("STATUS")?></td>
						<td>
							<select name="grade_status" id="grade_status" dojoType="dijit.form.FilteringSelect"  class="full height-text">
							    <option value="1" label="ប្រើប្រាស់" selected="selected">ប្រើប្រាស់</option>
							    <option value="0" label="មិនប្រើប្រាស់">មិនប្រើប្រាស់</option>
							</select>
						</td>
					</tr>
						<tr>
							<td colspan="2" align="center">
								<input iconClass="dijitIconUndo" type="button" value="close" label="Close" dojoType="dijit.form.Button" onclick="hideDialogGrade();"/>
								<input type="button" value="save" id="save_grade" label="<?php echo $tr->translate("SAVE");?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addGrade();"/>
							</td>
						</tr>
					</table>
				</fieldset>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<script>
var url_add_dept = '<?php echo $this->url(array("module"=>"global","controller"=>"grade","action"=>"add-dept")); ?>';
function addDept(){
	if(dijit.byId('frm_add_dep').validate()){
		fac_enname=dijit.byId('fac_enname').get('value');
		if(fac_enname==''){
			alert('Please inpute degree field !');
			return false;
		}
	dojo.xhrPost({
			url:url_add_dept,
			form: dojo.byId("frm_add_dep"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = { 
				    	 id: data,
					     name: dijit.byId('fac_enname').get('value')
					   };
		   addDataToSelectbox(dijit.byId('dept'), dept_store, Itemmake, data);
		   dijit.byId('frm_add_dep').reset();
		   dijit.byId("popup_add_dept").hide();	
			},
			error: function(err) {
				alert(err);
			}
	});
	}
}
var url_add_grade = '<?php echo $this->url(array("module"=>"global","controller"=>"group","action"=>"add-graddjax")); ?>';
function addGrade(){
	if(dijit.byId('frm_add_grade').validate()){
	popup_dept = dijit.byId("degree_popup1").get('value');
    if(popup_dept==''){
       alert('Please Selece Degree !');
	   return false;
	}
	dojo.xhrPost({
			url:url_add_grade,
			form: dojo.byId("frm_add_grade"),
			handleAs:"json",
			load: function(data) {
				//alert(data); 
				var Itemmake = { 
				    	 id: data,
					     name: dijit.byId('major_enname').get('value')
					   };
		   addDataToSelectbox(dijit.byId('grade'), grade_store, Itemmake, data);
		   dijit.byId('frm_add_grade').reset();
		   dijit.byId("popup_grate").hide();	
			},
			error: function(err) {
				alert(err);
					dijit.byId('save_grade').set('disabled',false);		
			}
		});
	}
}
function hideDialogGrade() {		
	dijit.byId("popup_grate").hide();
}
function hideDialogDegree() {		
	dijit.byId("popup_add_dept").hide();
}
</script>	