<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_callteral;
	echo $this->headTitle($tr->translate("EDIT_STUDY_GROUP"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$frm = $this->frm;
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require('dijit.form.Textarea');
</script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
               	 	room = dijit.byId('room').get('value');
					year=dijit.byId("academic_year").get("value");
					branch_id=dijit.byId("branch_id").get("value");
					if(branch_id==-1 || branch_id==''){
						alert("<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>");
						dijit.byId('branch_id').focus();
                    	return false;
					}
                	if(year==-1 || year==''){
						alert("<?php echo $tr->translate("PLEASE_SELECT_YEAR");?>");
						dijit.byId('academic_year').focus();
                    	return false;
					}
    				var rowId = $('#identity').val();
					if(rowId!=''){ 
						var rowIDArray = rowId.split(',');
						for(var n = 0; n < rowIDArray.length; n++){
							var row_id = dijit.byId('subject_study_'+rowIDArray[n]).get('value');
							if(row_id==''){
								alert("Please select subject title!");
								return false;
							}
						}
					}
               		if (room=='' || room==-1){
						alert("<?php echo $tr->translate("PLEASE_SELECT_ROOM");?>");
                   	 	dijit.byId('room').focus();
			        	return false;
               		 }
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_STUDY_GROUP');?></h4>
    				</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH");?> <span class="required">*</span> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("branch_id");?>
		                	<?php echo $frm->getElement("id");?>
		                </div>
		             </div>
		    		<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GROUP_CODE");?> :</label>
		               <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("group_code");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("YEARS");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<?php //echo $frm->getElement("academic_year");?>
							<input id="academic_year" name="academic_year" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("CULTURE_LEVEL");?></label>
		                 <div class="col-md-7 col-sm-7 col-xs-12">
							<?php echo $frm->getElement("calture");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DEGREE");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="degree" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("GRADE");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="grade" name="grade" class="fullside" value="<?php echo $this->rs['grade']; ?>" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SEMESTER");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input dojoType="dijit.form.ValidationTextBox" required="true" name="semester" class="fullside" value="<?php echo $this->rs['semester'];?>" type="text">
		                </div>
		             </div>
	    		</div>
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			 
		    		 <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SESSION");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("session");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TIME");?></label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<?php echo $frm->getElement("time");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ROOM_NAME");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="room" />
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TEACHER_ROOM");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input id="teacher_id" />
		                </div>
		             </div>
		            <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TEACHER_ASSISTANCE");?> :</label>
		                <div class="col-md-4 col-sm-4 col-xs-12">
		                	<input id="teacher_ass" />
		                </div>
		                <div class="col-md-3 col-sm-3 col-xs-12">
		                   	<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="AllRefresh();"/>
		                 </div>
		             </div>
		             
	    		</div>
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<!-- 
	    			<div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php //echo $tr->translate("START_DATE");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" name="start_date" id="start_date" class="fullside" onchange="setEndDate();" value="<?php //echo $this->rs['start_date'];?>" type="text">
		                </div>
		             </div>
		               <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php //echo $tr->translate("AMOUNT_MONTH");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input dojoType="dijit.form.NumberTextBox" class="fullside"  name="amountmonth" id="amountmonth" value="<?php //echo $this->rs['amount_month'];?>" onkeyup="setEndDate();" type="text">
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php //echo $tr->translate("END_DATE");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<input dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'dd/MM/yyyy'}" id="end_date" name="end_date" type="text" value="<?php //echo $this->rs['expired_date'];?>" >
		                </div>
		             </div>
	    			 -->
	    			 <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("IS_COMPLETED_GROUP");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select name="is_pass" id="is_pass" class="fullside" dojoType="dijit.form.FilteringSelect">
							    <option value="0" <?php if($this->rs['is_pass']==0) echo 'selected="selected"';?>><?php echo $tr->translate("NOT_USE");?></option>
							    <option value="1" <?php if($this->rs['is_pass']==1) echo 'selected="selected"';?>><?php echo $tr->translate("COMPLETED");?></option>
							    <option value="2" <?php if($this->rs['is_pass']==2) echo 'selected="selected"';?>><?php echo $tr->translate("STUDYING");?></option>
							</select>
		                </div>
		             </div>
	    			 <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("notes");?>
		                </div>
		             </div>
		              <div class="form-group">
		                <label class="control-label  col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> :</label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<select name="status" id="status" class="fullside" dojoType="dijit.form.FilteringSelect">
							    <option value="1" <?php if($this->rs['status']==1) echo 'selected="selected"';?>><?php echo $tr->translate("ACTIVE");?></option>
							    <option value="0" <?php if($this->rs['status']==0) echo 'selected="selected"';?>><?php echo $tr->translate("DEACTIVE");?></option>
							</select>
		                </div>
		             </div>
	    		</div>	
	    	</div>
	    	<div class="card-box">
               	<div class="col-sm-12">
               		<table id="table_row" border="1" style="border-collapse: collapse; border:1px solid #ccc;     white-space: nowrap;">
						<tr id="head-title" class="head-td" align="right"></tr>
					</table>
    			</div>
    			<div class="clearfix"></div>
    			<div class="col-sm-12">
    				<input type="button" label="<?php echo $tr->translate('ADD_SUBJECT_STUDY');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
			 		<input type="hidden" name="identity" id="identity"  />
    			</div>
    		</div>
    		
    		 <div class="clearfix"></div>
	         <div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
					<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
						iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'global','controller'=>"group",'action'=>'index'),null,true); ?>';" />
					<input type="submit" value="save" name="save" id="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
             
		</form>
	</div>
</div>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:80%;" id="popup_teacher" >
		<form  name='frm_add_teacher' id='frm_add_teacher'  dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color:menu;">
							<legend align="center" style="font-size: 18px;"><strong><?php echo $tr->translate("ADD_TEACHER");?></strong></legend>
							<table style="margin: 0 auto; width: 95%;white-space: nowrap;" cellspacing="10">
								<tr>
									<td><?php echo $tr->translate("ID_NUMBER")?></td>
									<td><input dojoType="dijit.form.TextBox" style="color:red;" class="fullside" id="code" name="code" value="" readonly type="text"></td>
									<td><?php echo $tr->translate("NAME")?></td>
									<td><input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="kh_name" name="kh_name" value="" type="text"></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("SEX")?></td>
									<td>
										<select dojoType="dijit.form.FilteringSelect" value="1" class="fullside" id="sex" name="sex" value="" type="text">
											<option value="1"><?php echo $tr->translate("MALE");?></option>
											<option value="2"><?php echo $tr->translate("FEMALE");?></option>
										</select>
									</td>
									<td><?php echo $tr->translate("NATIONALITY")?></td>
									<td><input dojoType="dijit.form.TextBox"  class="fullside" id="nationality" name="nationality" value="" type="text"></td>
								</tr>
								<tr>
									
									<td><?php echo $tr->translate("DOB")?></td>
									<td>
										<input dojoType="dijit.form.DateTextBox" value="now" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" id="dob" name="dob" value="" type="text" />
									</td>
									<td><?php echo $tr->translate("PHONE")?></td>
									<td><input dojoType="dijit.form.TextBox" class="fullside" id="phone" name="phone" value="" type="text"></td>
								</tr>
								<tr>
									
									<td><?php echo $tr->translate("ADDRESS")?></td>
									<td><input dojoType="dijit.form.TextBox"  class="fullside" id="address" name="address" value="" type="text"></td>
								
									<td><?php echo $tr->translate("NOTE")?></td>
									<td><input dojoType="dijit.form.TextBox"  class="fullside" id="note" name="note" value="" type="text"></td>
								</tr>
								<tr>
									<td colspan="6" align="center">
										<input type="button" onclick="addTeacher();" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
									</td>
								</tr>
							</table>	
						</fieldset>		
					</td>
				</tr>
			</table>	
			<input type="hidden"  name="tow_value" id="tow_value" value="" />
 		</form>
	</div>
</div>
<?php 
$techer= $this->frm_techer;
?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.html");
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->grade_name));?> );
var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var room_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->room));?> );
var teacher_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->teacher));?> );
var teacher_storeass  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->teacher));?> );

var subject_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->subjectlist));?> );
var academic_store= getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: teacher_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,
		id: "teacher_id",
		name: "teacher_id",    
		value:"<?php echo $this->rs['teacher_id'];?>",         
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_TEACHER");?>",          
		onChange: function() {  
			teacher_id = dijit.byId('teacher_id').get('value');
			if(teacher_id==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/lecturer/add?rightclick=true";?>','_blank');
				//dijit.byId("popup_teacher").show();
			}
		}
	}, "teacher_id");

	new dijit.form.FilteringSelect({
		store: teacher_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                        
		required: false,
		id: "teacher_ass",
		name: "teacher_ass",   
		value:"<?php echo $this->rs['teacher_assistance'];?>",          
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_TEACHER");?>",          
		onChange: function() {  
			teacher_id = dijit.byId('teacher_ass').get('value');
			if(teacher_id==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/lecturer/add?rightclick=true";?>','_blank');
				//dijit.byId("popup_teacher").show();
			}
		}
	}, "teacher_ass");
	
	new dijit.form.FilteringSelect({
		store: subject_store,
		queryExpr: "*${0}*",
		autoComplete: true,                  
		required: false,
		id: "subject_id",
		name: "subject_id",           
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_SUBJECT");?>",          
		onChange: function() {  
			subject_id = dijit.byId('subject_id').get('value');
			if(subject_id==-1){
				dijit.byId('save_subject').set('disabled',false);	
				dijit.byId("popupsubject").show();
			}else{
				addRowDegree();
			}
		}
	}, "subject_id");
	new dijit.form.FilteringSelect({
		store: dept_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,
		id: "degree",
		name: "degree",    
		value:"<?php echo $this->rs['degree'];?>",        
		class: "fullside", 
		placeHolder:"<?php echo $tr->translate("SELECT_DEGREE");?>",          
		onChange: function() {  
			dept_id = dijit.byId('degree').get('value');
			if(dept_id==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/degree/add?rightclick=true";?>','_blank');
			}else{
				getSubjectByDegree();
				getallGrade();
			}
		}
	}, "degree");	
	

	new dijit.form.FilteringSelect({
		store: grade_store,
		queryExpr: "*${0}*",
		autoComplete: false,                                           
		id: "grade",
		name: "grade",           
		class: 'fullside',  
		placeHolder:"<?php echo $tr->translate("SELECT_GRADE");?>",          
		onChange: function() {  
			make_id = dijit.byId('grade').get('value');
			grade = dijit.byId('grade').get('value');
			if(grade==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/grade/add?rightclick=true";?>','_blank');
			}
		}
	}, "grade");

	new dijit.form.FilteringSelect({
		store: room_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                     
		id: "room",
		name: "room",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ROOM");?>",          
		onChange: function() {  
			room = dijit.byId('room').get('value');
			if(room==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/global/room/add?rightclick=true";?>','_blank');
			}
		}
	}, "room");
	new dijit.form.FilteringSelect({
		store: academic_store,
		queryExpr: "*${0}*",
		autoComplete: false,                     
		required: true,                     
		id: "academic_year",
		name: "academic_year",
		class: "fullside", 		
		placeHolder:"<?php echo $tr->translate("SELECT_ACADEMIC_YEAR");?>",          
		onChange: function() {  
			academic_year = dijit.byId('academic_year').get('value');
			getAllDegreeByAcademicSchoolOption();
		}
	}, "academic_year");
	
	dijit.byId('room').attr('value','<?php echo $this->rs['room_id'];?>');
	dijit.byId('grade').attr('value','<?php echo $this->rs['grade'];?>');
	//dijit.byId('academic_year').attr('value','<?php //echo $this->rs['academic_year'];?>');
	getallGrade();
	Initailize();

	 var branch_id = dijit.byId('branch_id');
	 branch_id.on('change', function(evt) {
		 getAllAcademicByBranch();
    });
	 getAllAcademicByBranch();
});

url_getacademic= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getacademic'));?>';
var oldBranch='<?php echo $this->rs['branch_id'];?>';
function getAllAcademicByBranch(){
	dijit.byId('academic_year').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id=='' || branch_id==-1){
		var academic_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('academic_year').set('store',academic_store);  
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getacademic,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			academic_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('academic_year').set('store',academic_store);   
		    if(oldBranch==branch_id){
		    	 dijit.byId('academic_year').set('value','<?php echo $this->rs['academic_year'];?>');  
		    }
		},
		error: function(err) {
			alert(err);
		}
	});
}

url_getdegree= '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getdegree'));?>';
var oldAcademic='<?php echo $this->rs['academic_year'];?>';
function getAllDegreeByAcademicSchoolOption(){
	dijit.byId('degree').reset();
	academic_year = dijit.byId('academic_year').get('value');
	if(branch_id=='' || branch_id==-1){
		var dept_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('degree').set('store',dept_store);  
		dijit.byId('academic_year').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_getdegree,
		content:{
			'academic_year':academic_year
			},
		handleAs:"json",
		load: function(data) {
			dept_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('degree').set('store',dept_store); 
		    if(oldAcademic==academic_year){
		    	 dijit.byId('degree').set('value','<?php echo $this->rs['degree'];?>');  
		    }  
		},
		error: function(err) {
			alert(err);
		}
	});
}

function AllRefresh(){
	loadingBlock();
	getRefreshItems();
	getRefreshTeacher();
	dept_id = dijit.byId('degree').get('value');
	if(dept_id!='' || dept_id!=-1){getallGrade();}
	getRefreshRoom();
		
}
function getRefreshItems(){
	var url_getItems = '<?php echo $this->url(array("module"=>"global","controller"=>"degree","action"=>"refreshitems"));?>';										
		
		dojo.xhrPost({
			url: url_getItems,
			content:{
				'items_type':1
				},
			handleAs:"json",
			load: function(data) {
				dept_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('degree').set('store',dept_store);  
			   document.getElementsByClassName("overlay")[0].style.display="none";
			},
			error: function(err) {
				document.getElementsByClassName("overlay")[0].style.display="none";
			}
		});
}
var url_get_teacher_id = '<?php echo $this->url(array("module"=>"global","controller"=>"lecturer","action"=>"get-teacher-id")); ?>';
function getTeacherID(){
	dojo.xhrPost({
		url:url_get_teacher_id,
		handleAs:"json",
		load: function(data) {
			dijit.byId('code').attr('value',data);
		},
		error: function(err) {
			alert(err);
		}
	});
}
var url_getRoom = '<?php echo $this->url(array("module"=>"global","controller"=>"group","action"=>"getroom"));?>';										
function getRefreshRoom(){
	dojo.xhrPost({
		url: url_getRoom,
		handleAs:"json",
		load: function(data) {
			room_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('room').set('store',room_store);  
		    
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			alert(err);
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
var url_gettecher = '<?php echo $this->url(array("module"=>"global","controller"=>"group","action"=>"getteacher"));?>';										
function getRefreshTeacher(){
	loading();
	dojo.xhrPost({
		url:url_gettecher,
		handleAs:"json",
		load: function(data) {
			teacher_storeass  = getDataStorefromJSON('id','name', data);
		    dijit.byId('teacher_ass').set('store',teacher_storeass);  
		    teacher_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('teacher_id').set('store',teacher_store);  
		    
		    document.getElementsByClassName("overlay")[0].style.display="none";
		},
		error: function(err) {
			alert(err);
			document.getElementsByClassName("overlay")[0].style.display="none";
		}
	});
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}

function setEndDate(){
	amount_date = dijit.byId('amountmonth').get('value');
	release_date = dijit.byId("start_date").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		mm = a.getMonth()+amount_date+1;
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('end_date').attr('value',epx_date);	
    }
}

var url_dept = '<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'get-grade')); ?>';
function getallGrade(){
	dept_id = dijit.byId('degree').get('value');
	if(dept_id=='' || dept_id==null || dept_id==-1){
		return false;}
		dojo.xhrPost({
			url:url_dept,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				dijit.byId('grade').attr('value','');
				grade_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('grade').set('store',grade_store);   
			    dijit.byId('grade').attr('value',<?php echo $this->rs['grade'];?>);   
			},
			error: function(err) {
				alert(err);
			}
		});
}

var subject = '<?php echo $this->subject;?>';
var teacher_option = '<?php echo $this->teacher_option;?>';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function Initailize() {
	<?php if(!empty($this->row)){ 
		foreach ($this->row as $rows){?>
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th><?php echo $tr->translate("SUBJECT_STUDY");?></th>';
		temp+='<th><?php echo $tr->translate("AMOUNT_SUBJECT");?></th>';
		temp+='<th style="white-space:nowrap"><?php echo $tr->translate("AMOUNT_SUBJECT_FORSEMESTER");?></th>';
		temp+='<th><?php echo $tr->translate("NOTE");?></th>';
		temp+='<th><?php echo $tr->translate("TEACHER");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="4%" align="center">'+no+'</td>';
		template+='<td width="40%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" class="fullside" id="subject_study_'+col+'" name="subject_study_'+col+'">'+subject+'</select></td>';
		template+='<td width="40px"><input required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="amount_subject'+col+'" id="amount_subject'+col+'" value="1" type="text"></td>';	
		template+='<td width="60px"><input required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="amount_subject_semester'+col+'" id="amount_subject_semester'+col+'" value="1" type="text"></td>';	
		template+='<td width="23%"><input dojoType="dijit.form.TextBox" class="fullside" name="note_'+col+'" id="note_'+col+'" value="" type="text"></td>';		
		template+='<td width="24%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="popupTeacher('+col+');" class="fullside" id="teacher_'+col+'" name="teacher_'+col+'" >';
		template+=teacher_option;  
		template+='</select></td>';
		
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	dijit.byId('subject_study_'+col).attr('value','<?php echo $rows['subject_id'];?>');
	dijit.byId('amount_subject'+col).attr('value','<?php echo $rows['amount_subject'];?>');
	dijit.byId('amount_subject_semester'+col).attr('value','<?php echo $rows['amount_subject_sem'];?>');
	dijit.byId('note_'+col).attr('value','<?php echo $rows['note'];?>');
	dijit.byId('teacher_'+col).attr('value','<?php echo $rows['teacher'];?>');
	<?php }}?>
}
function popupTeacher(key){
	
}
function addRow() {
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("DEL");?></th>';
		temp+='<th><?php echo $tr->translate("N_O");?></th>';
		temp+='<th><?php echo $tr->translate("SUBJECT_STUDY");?></th>';
		temp+='<th><?php echo $tr->translate("AMOUNT_SUBJECT");?></th>';
		temp+='<th style="white-space:nowrap"><?php echo $tr->translate("AMOUNT_SUBJECT_FORSEMESTER");?></th>';
		temp+='<th><?php echo $tr->translate("NOTE");?></th>';
		temp+='<th><?php echo $tr->translate("TEACHER");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td width="4%" align="center">'+no+'</td>';
		template+='<td width="40%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect"  class="fullside" id="subject_study_'+col+'" name="subject_study_'+col+'">'+subject+'</select></td>';
		template+='<td width="40px"><input required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="amount_subject'+col+'" id="amount_subject'+col+'" value="1" type="text"></td>';
		template+='<td width="60px"><input required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="amount_subject_semester'+col+'" id="amount_subject_semester'+col+'" value="1" type="text"></td>';	
		template+='<td width="23%"><input dojoType="dijit.form.TextBox" class="fullside" name="note_'+col+'" id="note_'+col+'" value="" type="text"></td>';		
		template+='<td width="24%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="popupTeacher('+col+');" class="fullside" id="teacher_'+col+'" name="teacher_'+col+'" >';
		template+=teacher_option;  
		template+='</select></td>';
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
function hideDialog(){
	dijit.byId("popup_room").hide();
}
var url_dept_subject = '<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'getsubjectbydegree')); ?>';
function getSubjectByDegree(){
	dept_id = dijit.byId('degree').get('value');
		dojo.xhrPost({
			url:url_dept_subject,
			content:{
				'dept_id':dept_id
				},
			handleAs:"json",
			load: function(data) {
				var identity = $('#identity').val();
				if(identity !=''){
					var arrays = identity.split(',');
					for(var i=0;i<arrays.length;i++) {
						deleteRecord(arrays[i]);
					}
					$("#identity").val("");
				}
				tem="";
			    if(data!=""){
					template='';
					for(i=0;i<data.length;i++){
						col++;no++;
						template='';
						if(title!=1){
							temp+='<th><?php echo $tr->translate("DEL");?></th>';
							temp+='<th><?php echo $tr->translate("N_O");?></th>';
							temp+='<th><?php echo $tr->translate("SUBJECT_STUDY");?></th>';
							temp+='<th><?php echo $tr->translate("NOTE");?></th>';
							temp+='<th><?php echo $tr->translate("STATUS");?></th>';
							dojo.query("#head-title").append(temp);
							title=1;
						}
							template+='<td width="4%"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
							template+='<td width="4%" align="center">'+no+'</td>';
							template+='<td width="40%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" class="fullside" id="group_subject_study_'+col+'" name="group_subject_study_'+col+'">'+subject+'</select></td>';
							template+='<td width="50px"><input required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="amount_subject'+col+'" id="amount_subject'+col+'" value="1" type="text"></td>';
							template+='<td width="60px"><input required="1" dojoType="dijit.form.NumberTextBox" class="fullside" name="amount_subject_semester'+col+'" id="amount_subject_semester'+col+'" value="1" type="text"></td>';	
							template+='<td width="35%"><input dojoType="dijit.form.TextBox" class="fullside" name="group_note_'+col+'" id="group_note_'+col+'" value="" type="text"></td>';		
							template+='<td width="24%"><select queryExpr="*${0}*" autoComplete="false" dojoType="dijit.form.FilteringSelect" onchange="popupTeacher('+col+');" class="fullside" id="teacher_'+col+'" name="teacher_'+col+'" >';
							template+=teacher_option;  
							template+='</select></td>';
						
						tmp='<tr id="row'+col+'">';
						tmp+="</tr>";
						dojo.query("#table_row").append(tmp);

						if($("#identity").val()!="") {
							var identity = $("#identity").val();
							$("#identity").val(identity+','+col);
						} else {$("#identity").val(col);}
						dojo.html.set(dojo.byId("row"+col),template , {
							 parseContent: true,
						});
						dijit.byId('group_subject_study_'+col).attr('value',data[i].subject_id);
						dijit.byId('group_note_'+col).attr('value',data[i].note);
					}
			    }
			},
			error: function(err) {
				alert(err);
			}
		});
}

</script>
	
<script>

function hideDialogGrade() {		
	dijit.byId("popup_grate").hide();
}
function hideDialogDegree() {		
	dijit.byId("popup_add_dept").hide();
}
</script>	