<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ក្រុមសិក្សា"));
	$url_copy =$this->url(array('module'=>'global','controller'=>'group','action'=>'copy'));
	$formList = new Application_Form_Frmtable();	
    $frm =  $this->form_search;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'global','controller'=>'group','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<table width="100%">
				       <tr>
							<td style="width: 95px;"><?php echo $formList->showCopyBuntton($url_copy);?></td>
				            <td><?php echo $frm->getElement("title");?></td>
				            <td><?php echo $frm->getElement("study_year");?></td>
				            <td><?php echo $frm->getElement("degree");?></td>
				            <td><?php echo $frm->getElement("grade");?></td>
						    <td><?php echo $frm->getElement("session");?></td>
						    <td><?php echo $frm->getElement("status_search");?></td>
				            <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
				       </tr>
					   <input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />		   
				</table>
			
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list?>
		</div>
	</div>
</div>

<script type="text/javascript">
	dojo.require("dijit.form.CheckBox"); 
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.DateTextBox");
	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 if(id!=''){
			window.location.href = url+'/id/'+id;
		 }else{
			alert('Please select record you want to copy');
			return false;
		 }
	}
	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}
</script> 