<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SET_STUDENT_VACCINE')); 
?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="material-icons-outlined">vaccines</i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SET_STUDENT_VACCINE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='add_discount' action="" method="post" dojoType="dijit.form.Form" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
  				 if(this.validate()) {
					 
					 branch_id = dijit.byId('branch_id').get('value');
   					if(branch_id==-1 || branch_id==""){
         				dijit.byId("branch_id").focus();
        				return false;
    				}
					var identity = $('#identity').val();
					if(identity==''){
						alert("There is no record to save");
						dijit.byId("old_stu").focus();
						return false;
					}
					 loadingBlock();
    				dijit.byId("save_close").attr("disabled",true);
					dijit.byId("save_new").attr("disabled",true);
   					 return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box" >
				<div class="form-group">
				</div>
			   <div class="form-group" style="background: #d8e0e2; padding: 15px 15px; margin: 0; border: solid 1px #697996; border-radius: 2px;">
					<label class="control-label col-md-2 col-sm-2 col-xs-12 title-blog bold" ><?php echo $tr->translate("STUDENT_INFO");?>&nbsp;&nbsp;<i class="fa fa-search" aria-hidden="true"></i> 
				   </label>
					<div class="col-md-3 col-sm-3 col-xs-12">
						 <div class="form-group">
						   <label class="control-label  col-md-3 col-sm-3 col-xs-12" ><?php echo $tr->translate("BRANCH");?></label>
						   <div class="col-md-9 col-sm-9 col-xs-12">
								<select class="fullside" name="branch_id" id="branch_id" dojoType="dijit.form.FilteringSelect" onchange="getbranchinfo();getallstudentname();getAllAcademicByBranch();">
									<?php if(!empty($this->rsbranch))foreach($this->rsbranch as $rs){?>
									<option value="<?php echo $rs['id']?>"><?php echo $rs['name'];?></option>
									<?php }?>
								</select>
								<?php //echo $tr->translate("Existing Student");?>
								<input value="1" dojoType="dijit.form.TextBox" class="fullside" id="student_type" name="student_type" type="hidden">
								<?php //echo $tr->translate("Student");?>
								<input value="1" dojoType="dijit.form.TextBox" class="fullside" id="customer_type" name="customer_type" type="hidden">
						   </div>
						</div>
				   </div>
				   <div class="col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
						   <label class="control-label col-md-4 col-sm-4 col-xs-12"><?php echo $tr->translate("STUDENT_NAME");?></label>
						   <div class="col-md-7 col-sm-7 col-xs-12">
								<input id="studentId" />
						   </div>
						</div>
				   </div>
				   <div style="clear: both;"></div>
			   </div>
			   <div class="form-group">
				   <div class="col-md-12 col-sm-12 col-xs-12">
						<table class="collape responsiveTable" >
							<thead>
								<tr id="head-title" class="head-td" align="center" >
									<th scope="col" width="30px" ><?php echo $tr->translate('DELETE');?></th>
									<th scope="col" width="30px" ><?php echo $tr->translate('N_O');?></th>
									<th scope="col" style="width:150px;" ><?php echo $tr->translate('STUDENT_NAME');?></th>
									<th scope="col" style="width:100px"><?php echo $tr->translate('VACCIN_STATUS');?></th>
									<th scope="col" style="width:100px"><?php echo $tr->translate('COVID_TESTED_STATUS');?></th>
								</tr>
							</thead>
							<tbody id="table_row" >
							</tbody>
						</table>
				   </div>
			   </div>
			   <input type="hidden" id="identity" name="identity" />
			</div>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12">
	                
	                 <div class="clearfix"></div>
			         <div class="card-box mt-20">
		               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
		               		<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE');?>" dojoType="dijit.form.Button" />
		               	</div>
		             </div>
	            </div>
	         </div>
		</form>
	</div>
</div>
<style>
table.tableShowData {
    margin-top: 2px;
	width:100%; border-collapse: 
	collapse; border:1px solid #ccc;
	white-space: nowrap;
}
table.tableShowData tr#head-title {
    background: #02014a !important;
    color: #fff !important;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require('dijit.form.NumberTextBox');
	dojo.require("dojo.number");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");

require(["dojo/ready"], function(ready){
	ready(function(){
		getallstudentname();
	});

	new dijit.form.FilteringSelect({
		autoComplete: false,
		queryExpr: "*${0}*",                     
		id: "studentId",
		name: "studentId",   
		required:true,        
		class: 'fullside', 
		placeHolder:"<?php echo $tr->translate("SELECT_STUDENT_NAME");?>",          
		onChange: function() {  
			addRecord();
		}
	}, "studentId");
	
});

function getallstudentname(){//
	dijit.byId("studentId").reset();
	branchId = dijit.byId('branch_id').get('value');
	if(branchId==''){
		 dijit.byId('branch_id').focus();
		 return false;
	}
	let urlGet = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'getliststudenturl')); ?>';
	
	contentData = {
			'branchId':branchId,
			'customerType':1
		}
	getAllStudentByBranch(urlGet,contentData);
}

var template = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRecord() {
	
		branch_id = dijit.byId("branch_id").attr("value");
		if(branch_id==''){
			alert("<?php echo $tr->translate("SELECT_BRANCH");?>");
			dijit.byId("branch_id").focus();
			return false;
		}
	
		studentName = dijit.byId('old_stu').get('value');
		if(studentName==''){
			alert("<?php echo $tr->translate("SELECT_STUDENT_NAME");?>");
			dijit.byId('old_stu').focus();
			return false;
		}
	
		var duplicateRecord = 0;
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		if(identity!=""){
			currentStudent = dijit.byId('old_stu').get('value');
			for(var i=0;i<arrays.length;i++) {
				oldStudent = dijit.byId('studentId'+arrays[i]).get('value');
				if(currentStudent == oldStudent){
					duplicateRecord=1;
					alert("Can not add the same student");
					break;
				}
			}
		}
		if(duplicateRecord==1){
			return false;
		}
	
		labelStudent = dijit.byId("old_stu").attr('displayedValue');
		studentId = dijit.byId("old_stu").get("value");
		
		col++;no++;
		template='';
		
			template+='<td data-label="<?php echo $tr->translate("DELETE");?>" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD");?>" class="removeRow" onclick="deleteRecord('+col+');" ><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span> </td>';
			template+='<td data-label="<?php echo $tr->translate("N_O");?>" align="center">'+no+'</td>';
			template+='<td data-label="<?php echo $tr->translate("STUDENT_NAME");?>"><label id="item_label_'+col+'">'+labelStudent+'<label><input type="hidden" value="'+studentId+'" dojoType="dijit.form.TextBox" name="studentId'+col+'" id="studentId'+col+'"/>';
			template+='<td data-label="<?php echo $tr->translate("VACCIN_STATUS");?>"><select class="fullside" required="false" dojoType="dijit.form.FilteringSelect" id="is_vaccined'+col+'" name="is_vaccined'+col+'" >';
			template+='<option value="1"><?php echo $tr->translate("VACCIN_COMPLETED");?></option>';	
			template+='<option value="0"><?php echo $tr->translate("VACCIN_UNCOMPLETED");?></option>';	
			template+='</select></td>';
			template+='<td data-label="<?php echo $tr->translate("COVID_TESTED_STATUS");?>"><select class="fullside" required="false" dojoType="dijit.form.FilteringSelect" id="is_covidTested'+col+'" name="is_covidTested'+col+'" >';
			template+='<option value="1"><?php echo $tr->translate("TESTED_COVID");?></option>';
			template+='<option value="0"><?php echo $tr->translate("NOT_YET_TEST_COVID");?></option>';	
			template+='</select></td>';
		tmp='<tr id="row'+col+'" class="rowData" >';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
</script>