<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("FOR_SECTION"));
	$row=$this->row;
?>	
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
           <div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-edit " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('FOR_SECTION');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form  id='frm_book' action="" dojoType="dijit.form.Form" method="post"  enctype="multipart/form-data" >
			<script type="dojo/method" event="onSubmit" enctype="multipart/form-data">			
				if(this.validate()) {
					dijit.byId('save_close').set('disabled',true);
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TITLE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="title" class="fullside" id="title" dojoType="dijit.form.TextBox" value="<?php echo $row['title']?>" required="required" /> 
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<select name="status" class="fullside" id="status" dojoType="dijit.form.FilteringSelect" >
								<option value="1" <?php if($row['status']==1){echo "selected='selected'";}?>><?php echo $tr->translate("ACTIVE");?></option>
								<option value="0" <?php if($row['status']==0){echo "selected='selected'";}?>><?php echo $tr->translate("DEACTIVE");?></option>
							</select> 
	                   </div>
	                </div>
	                 <div class="clearfix"></div>
			         <div class="card-box mt-20">
		               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
		               		<input type="submit" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
		               	</div>
		             </div>
	             </div>
			</div>
		</form>
    </div>
</div>