<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("ADD_ACADEMIC_YEAR"));
$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'global','controller'=>'academicyear','action'=>'add')); ?>" 
dojoType="dijit.form.Form" method="post"  enctype="multipart/form-data">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>

<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.date.locale");
dojo.require("dojo.html");
function getEndDate(){
	//alert(1);
	amount_month = dijit.byId('duration').get('value');
	 start_date = dijit.byId("study_start").get('value');

	 var a = new Date(start_date);
	  mm = a.getMonth()+amount_month+1;

	 var dd = a.getDate();
	  if(dd<10){
	   dd = "0"+dd;
	 }
	  if(mm<10){
	   mm = "0"+mm;
	 }
	 var y = a.getFullYear();
	 var epx_date = y + '-' + mm + '-' + dd ;

	 //alert(epx_date);
	 dijit.byId('start_end').attr('value',epx_date);
}
</script>
<table width="100%">
	<tr>
		<td>
			<fieldset style="margin-top:-13px;">
					<legend align="center" ><strong​ style="font-size: 18px;"><b><?php echo $tr->translate("ADD_ACADEMIC_YEAR");?></b></strong></legend>
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<td valign="top">
							<fieldset>
								<legend align="center"><strong style="font-size: 15px;">ACADEMIC</strong></legend>
									<table style="width:330px;" cellspacing="6">
										
										<tr>
											<td style="width: 5px"><?php echo $tr->translate("NOTE")?></td>
											<td><input dojoType="dijit.form.TextBox" class="fullside" id="note" name="note" value="" type="text"></td>
											<td><?php  //echo $techer->getElement('province');?></td>
										</tr>
										<tr>
											<td style="width: 5px;white-space: nowrap;"><?php echo $tr->translate("STATUS")?></td>
											<td><select dojoType="dijit.form.FilteringSelect" required="true"  class="fullside" id="status" name="status" type="text">								
												<option value="1"><?php echo $tr->translate("Active");?></option>
												<option value="0"><?php echo $tr->translate("Deactive");?></option>
										</select></td>
										</tr>
										<tr>
											<td colspan="6" align="center">
												<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
													<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
														iconClass="dijitEditorIcon dijitEditorIconSave" />
													<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
														iconClass="dijitEditorIcon dijitEditorIconSave" />
											</td>
										</tr>										
								</table>
							</fieldset>
						</td>
						<td valign="top">
						<fieldset>
							<legend align="center"><strong style="font-size: 15px;">TERM PERIOD</strong></legend>
								<table style="width:330px;" cellspacing="6">
								<tr>
									<td>
										<fieldset>
											<legend align="center"><b>Quarter1 Period</b></legend>
											<table style="width:330px;" cellspacing="6">
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("START_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="quarter_start1" name="quarter_start1" value="" ></td>
													<td></td>
												</tr>
												
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("END_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="quarter_end1" name="quarter_end1" value="" ></td>
													<td></td>
												</tr>
											</table>
										</fieldset>
									</td>
									
									<td>
										<fieldset>
											<legend align="center"><b>Quarter2 Period</b></legend>
											<table style="width:330px;" cellspacing="6">
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("START_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="quarter_start2" name="quarter_start2" value="" ></td>
													<td></td>
												</tr>
												
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("END_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="quarter_end2" name="quarter_end2" value="" ></td>
													<td></td>
												</tr>
											</table>
										</fieldset>
									</td>
								</tr>
								<tr>
									<td>
										<fieldset>
											<legend align="center"><b>Quarter3 Period</b></legend>
											<table style="width:330px;" cellspacing="6">
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("START_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="quarter_start3" name="quarter_start3" value="" ></td>
													<td></td>
												</tr>
												
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("END_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="quarter_end3" name="quarter_end3" value="" ></td>
													<td></td>
												</tr>
											</table>
										</fieldset>
									</td>
									
									<td>
										<fieldset>
											<legend align="center"><b>Quarter4 Period</b></legend>
											<table style="width:330px;" cellspacing="6">
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("START_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="quarter_start4" name="quarter_start4" value="" ></td>
													<td></td>
												</tr>
												
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("END_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="quarter_end4" name="quarter_end4" value="" ></td>
													<td></td>
												</tr>
											</table>
										</fieldset>
									</td>
								</tr>
								<tr>
									<td valign="top">
										<fieldset>
											<legend align="center"><b>Semester1</b></legend>
											<table style="width:330px;" cellspacing="6">
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("START_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="semester_start1" name="semester_start1" value="" ></td>
													<td></td>
												</tr>
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("END_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="semester_end1" name="semester_end1" value="" ></td>
													<td></td>
												</tr>
											</table>
										</fieldset>
									</td>
									<td valign="top">
										<fieldset>
											<legend align="center"><b>Semester2</b></legend>
											<table style="width:330px;" cellspacing="6">
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("START_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="semester_start2" name="semester_start2" value="" ></td>
													<td></td>
												</tr>
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("END_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="semester_end2" name="semester_end2" value="" ></td>
													<td></td>
												</tr>
											</table>
										</fieldset>
									</td>
								</tr>
								<table style="width:330px; margin-left:130px;" cellspacing="6">
									<fieldset>
										<td>
											<legend align="center"><th>Yearly</th></legend>
												<tr>
													<td style="width: 100px"><?php echo $tr->translate("START_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="yearly_start" name="yearly_start" value="" ></td>
													<td></td>
												</tr>
												<tr>
													<td style="width: 5px"><?php echo $tr->translate("END_DATE")?></td>
													<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="yearly_end" name="yearly_end" value="" type="text"></td>
													<td><?php  //echo $techer->getElement('issued1');?></td>
												</tr>
										</td>
									</fieldset>
								</table>
							</table>
						</fieldset>
						</td>
						
					</table>
				</fieldset>
		</td>
	</tr>
</table>
</form>