<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ACADEMIC_YEAR"));
?>	
<?php $frm =  $this->frm_search;?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'global','controller'=>'academicyear','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
		<table style="width:60%">
			<tr> 
				<td> <input dojoType="dijit.form.TextBox"   id="adv_search" name="adv_search" placeholder="Search by student name....." value="<?php echo $this->adv_search['txtsearch']; ?>" type="text">
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			</tr>
		</table>
</form>
<?php echo $this->list?>



